### ISSUE TITLE
Check that new heap types cannot be created uninitialised: add Py_TPFLAGS_DISALLOW_INSTANTIATION type flag

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#88082]
BPO | [43916](https://bugs.python.org/issue43916)
--- | :---
Nosy | @vstinner, @tiran, @serhiy-storchaka, @pablogsal, @miss-islington, @erlend-aasland, @shreyanavigyan
PRs | <li>python/cpython#25653</li><li>python/cpython#25721</li><li>python/cpython#25722</li><li>python/cpython#25733</li><li>python/cpython#25745</li><li>python/cpython#25748</li><li>python/cpython#25749</li><li>python/cpython#25750</li><li>python/cpython#25751</li><li>python/cpython#25753</li><li>python/cpython#25768</li><li>python/cpython#25791</li><li>python/cpython#25854</li><li>python/cpython#26412</li><li>python/cpython#26888</li>
Files | <li>[patch.diff](https://bugs.python.org/file49989/patch.diff "Uploaded as text/plain at 2021-04-26.22:13:02 by @erlend-aasland")</li><li>[disablednew.diff](https://bugs.python.org/file49992/disablednew.diff "Uploaded as text/plain at 2021-04-27.08:23:03 by @erlend-aasland")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-22.21:31:58.958>
labels = ['expert-C-API', 'type-bug', '3.9']
title = 'Check that new heap types cannot be created uninitialised: add Py_TPFLAGS_DISALLOW_INSTANTIATION type flag'
updated_at = <Date 2022-01-27.13:51:31.586>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.13:51:31.586>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-04-22.21:31:58.958>
creator = 'pablogsal'
dependencies = []
files = ['49989', '49992']
hgrepos = []
issue_num = 43916
keywords = ['patch']
message_count = 72.0
messages = ['391634', '391635', '391903', '391905', '391909', '391910', '391911', '391912', '391913', '391917', '391924', '391925', '391926', '391928', '391929', '391931', '391934', '391936', '391937', '391984', '391992', '391999', '392036', '392040', '392042', '392044', '392046', '392048', '392057', '392169', '392170', '392297', '392414', '392426', '392427', '392433', '392434', '392435', '392437', '392438', '392451', '392456', '392462', '392464', '392465', '392472', '392473', '392526', '392528', '392534', '392537', '392545', '392546', '392553', '392554', '392556', '392558', '392570', '392621', '392632', '392635', '392811', '394571', '394582', '394603', '396200', '396476', '411785', '411786', '411865', '411867', '411874']
nosy_count = 7.0
nosy_names = ['vstinner', 'christian.heimes', 'serhiy.storchaka', 'pablogsal', 'miss-islington', 'erlendaasland', 'shreyanavigyan']
pr_nums = ['25653', '25721', '25722', '25733', '25745', '25748', '25749', '25750', '25751', '25753', '25768', '25791', '25854', '26412', '26888']
priority = None
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43916'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
Victor:
> > Can we close this issue? Or is there a remaining task?
>
> 3.9 is still affected; we should fix those types first.

3.9 has now entered security-only phase, so I guess that ship has sailed. Suggesting to close this.

**Comment by vstinner** [comment]
Right, I closed the issue.
