### ISSUE TITLE
Processes in Python 3.9 exiting with code 1 when It's created inside a ThreadPoolExecutor

### ISSUE THREAD

**Issue by d3db2e84-efbf-4d7c-b0a2-711a9b76b260** [python/cpython#88110]
BPO | [43944](https://bugs.python.org/issue43944)
--- | :---
Nosy | @pitrou, @graingert, @applio, @Genarito, @jdevries3133

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-26.20:59:45.367>
labels = ['type-bug', '3.9']
title = "Processes in Python 3.9 exiting with code 1 when It's created inside a ThreadPoolExecutor"
updated_at = <Date 2022-04-08.09:35:24.244>
user = 'https://github.com/Genarito'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.09:35:24.244>
actor = 'graingert'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-04-26.20:59:45.367>
creator = 'Genarito'
dependencies = []
files = []
hgrepos = []
issue_num = 43944
keywords = []
message_count = 8.0
messages = ['391985', '396522', '398157', '398159', '398175', '398202', '398203', '416966']
nosy_count = 6.0
nosy_names = ['pitrou', 'graingert', 'davin', 'Genarito', 'jack__d', 'sicard_elda']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43944'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-101940
* gh-126098
* gh-127163
* gh-127164

**Comment by marmarek** [comment]
I'm hitting exactly the same issue without `ThreadPoolExecutor`, but with a PyQt application (that does use QThread), and also tests running under nose2. I think the issue is that concurrent.futures.thread doesn't clear `_threads_queues` in atfork callback. Adding this fixes the issue for me. PR coming soon.

**Comment by marmarek** [comment]
And BTW, this applies to Python 3.11 too. I assume 3.10 is also affected.
