### ISSUE TITLE
Include column offsets for bytecode instructions

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#88116]
BPO | [43950](https://bugs.python.org/issue43950)
--- | :---
Nosy | @terryjreedy, @nedbat, @aroberge, @markshannon, @serhiy-storchaka, @ammaraskar, @pablogsal, @miss-islington, @brandtbucher, @isidentical, @sweeneyde, @sobolevn
PRs | <li>python/cpython#26955</li><li>python/cpython#26958</li><li>python/cpython#26997</li><li>python/cpython#27011</li><li>python/cpython#27015</li><li>python/cpython#27023</li><li>python/cpython#27023</li><li>python/cpython#27023</li><li>python/cpython#27037</li><li>python/cpython#27047</li><li>python/cpython#27117</li><li>python/cpython#27126</li><li>python/cpython#27217</li><li>python/cpython#27313</li><li>python/cpython#27336</li><li>python/cpython#27337</li><li>python/cpython#27339</li><li>python/cpython#28142</li><li>python/cpython#28150</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-27.10:58:38.225>
labels = []
title = 'Include column offsets for bytecode instructions'
updated_at = <Date 2022-01-18.12:31:06.245>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.12:31:06.245>
actor = 'sobolevn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-04-27.10:58:38.225>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 43950
keywords = ['patch']
message_count = 39.0
messages = ['392054', '392062', '392081', '392082', '392520', '392540', '392541', '392555', '392557', '396866', '396874', '396950', '396957', '396962', '397109', '397352', '397368', '397589', '397666', '397667', '397669', '397673', '397829', '397837', '397844', '397882', '397909', '397910', '397911', '397914', '397915', '398089', '398144', '398169', '398170', '398172', '398197', '400998', '410856']
nosy_count = 12.0
nosy_names = ['terry.reedy', 'nedbat', 'aroberge', 'Mark.Shannon', 'serhiy.storchaka', 'ammar2', 'pablogsal', 'miss-islington', 'brandtbucher', 'BTaskaya', 'Dennis Sweeney', 'sobolevn']
pr_nums = ['26955', '26958', '26997', '27011', '27015', '27023', '27023', '27023', '27037', '27047', '27117', '27126', '27217', '27313', '27336', '27337', '27339', '28142', '28150']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43950'
versions = []
```

</p></details>

**Comment by JustAnotherArchivist** [comment]
As far as I can see, this is not yet supported by `inspect.trace` and `inspect.stack`. That would be very useful for debugging.

**Comment by pablogsal** [comment]
> As far as I can see, this is not yet supported by `inspect.trace` and `inspect.stack`. That would be very useful for debugging.

I can try to prepare a PR this week

**Comment by pablogsal** [comment]
Hummm, is unclear to me if we can actually update these interfaces. As they return a (named) tuple, users unpacking the tuple will be broken if we add more items to it.

**Comment by JustAnotherArchivist** [comment]
Yeah, I noticed that as well. The unpacking could be solved with a custom class that provides an `__iter__` method for compatibility. For example:

```python3
import dataclasses
import typing

@dataclasses.dataclass
class X:
	a: int
	b: str
	c: float

	def __iter__(self):
		return iter((self.a, self.b))

x = X(42, 'foo', 3.1416)
a, b = x
print(a, b)
print(x.a, x.b)
```

This would still break other, more obscure uses of the named tuple specifics though, e.g. `isinstance(x, tuple)` or `x._asdict()`.

**Comment by pablogsal** [comment]
> Yeah, I noticed that as well. The unpacking could be solved with a custom class that provides an `__iter__` method for compatibility. For example:
> 
> ```python3
> import dataclasses
> import typing
> 
> @dataclasses.dataclass
> class X:
> 	a: int
> 	b: str
> 	c: float
> 
> 	def __iter__(self):
> 		return iter((self.a, self.b))
> 
> x = X(42, 'foo', 3.1416)
> a, b = x
> print(a, b)
> print(x.a, x.b)
> ```
> 
> This would still break other, more obscure uses of the named tuple specifics though, e.g. `isinstance(x, tuple)` or `x._asdict()`.

That's likely too convoluted and it will certainly be very surprising in a bad way to new users.

**Comment by JustAnotherArchivist** [comment]
I agree that it's more of an awful workaround than an actual solution.

Perhaps a better option might be adding a kwarg to `trace` and `stack` that makes them return a different data structure with the extra info. It would then default to `False` for backward compatibility. There's precedent for that as well: `typing.get_type_hints` and its `include_extras` argument. Although the question would still be what data type would be returned there; if we don't anticipate further additions anytime soon, maybe just an extended named tuple would do, but a dataclass or similar structure would be more future-proof.

**Comment by pablogsal** [comment]
> . Although the question would still be what data type would be returned there; if we don't anticipate further additions anytime soon, maybe just an extended named tuple would do, but a dataclass or similar structure would be more future-proof.

Unfortunately adding a data class to the `inspect` module will have an impact on startup time and size, which is very undesirable as is on the hot path. I don't dislike the keyword argument, though, but we need to see what others think. @ammaraskar  @isidentical

**Comment by JelleZijlstra** [comment]
We can make a namedtuple subclass that adds additional attributes. There is precedent for this in the form of `os.stat_result`, although that's a structseq (the C equivalent of namedtuple). It's a little confusing, but it should preserve compatibility and avoid convoluting the API.

**Comment by pablogsal** [comment]
> We can make a namedtuple subclass that adds additional attributes. There is precedent for this in the form of `os.stat_result`, although that's a structseq (the C equivalent of namedtuple). It's a little confusing, but it should preserve compatibility and avoid convoluting the API.

Yeah, I recall that one. I am not a fan of that approach as I find it very confusing. Maybe we should open a thread in python-dev about this.

**Comment by pablogsal** [comment]
I have sent an email about this to python-dev

**Comment by gpshead** [comment]
As awkward of a beast as a tuple subclass emulating the previous fixed size namedtuple while adding additional attributes seems, it is very practical.

Users don't care about the specifics. They just need existing code to keep working and will want access to new values when updating this code or writing new code. Which means it should still be a tuple subclass for typing reasons known as `inspect.Traceback` and `inspect.FrameInfo`, support the existing indices and unpacking semantics, and support named field access. That this would be adding additional fields that indexing does not provide is a mere curiosity that most users would not notice as modern code should be field based anyways.

Nobody _should_ care if the implementation behind the returned instances is unusual. The behavior will be what they expect. It avoids the need to expand into multiple different return types via an arg flag or the creation of parallel APIs.

This is a good practical example of why we should not design APIs to return tuples if they could conceivably change in the future.  And why people unpacking on API calls that return tuples might find it wise to always `[:slice]` the return value as a style idiom.

---

All this said... we _could_ also just add another field to the namedtuple. Some code inspection among existing API users is required, but I expect most users either immediately unpack upon return value assignment _or_ use field names. Mix and matching of indexing and named access on a single return value is _probably_ rare. The easy modification to existing code using unpacking to deal with this kind of API change upon version upgrade is to append a `[:5]` or similar to the API call. We _have_ had other tuple returning APIs add fields in the past where this was the workaround though I've forgotten what they were off the top of my head.

This would be the more disruptive option. It is nice to avoid this if possible as it delays people's ability to update to and even test their code on 3.11. So I still lean towards the hybrid "half namedtuple" class.

**Comment by pablogsal** [comment]
@markshannon There is something wrong with commit 944fffee8916cb94321fa33cd3a43f4108717746 and the new encoding format. Check out https://github.com/python/cpython/issues/93662

**Comment by pablogsal** [comment]
@markshannon I'm noticing that the implementation for varints and signed varints that we use has two encodings for 0 (both uval==0 and uval==1 decode to 0), and no way to encode -2**31. Is this a problem? What prevents us to need to encode -2**31?

**Comment by pablogsal** [comment]
Also, weirdly there are two ways to encode 0 and no ways to encode -INT_MIN. @markshannon is this expected?
