### ISSUE TITLE
Valgrind memcheck on Py_Initialize

### ISSUE THREAD

**Issue by a3f70755-98ae-46d5-ae48-72cf115438c9** [python/cpython#88133]
BPO | [43967](https://bugs.python.org/issue43967)
--- | :---
Nosy | @shihai1991
Files | <li>[valgrind-libpython.tar.gz](https://bugs.python.org/file49996/valgrind-libpython.tar.gz "Uploaded as application/gzip at 2021-04-28.13:53:21 by simonaldrich"): Reproducer</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-25.16:48:20.995>
created_at = <Date 2021-04-28.13:53:21.645>
labels = ['type-security', 'expert-C-API', '3.8', 'library']
title = 'Valgrind memcheck on Py_Initialize'
updated_at = <Date 2021-07-25.16:48:20.993>
user = 'https://bugs.python.org/simonaldrich'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-25.16:48:20.993>
actor = 'shihai1991'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-25.16:48:20.995>
closer = 'shihai1991'
components = ['Library (Lib)', 'C API']
creation = <Date 2021-04-28.13:53:21.645>
creator = 'simonaldrich'
dependencies = []
files = ['49996']
hgrepos = []
issue_num = 43967
keywords = []
message_count = 2.0
messages = ['392199', '398188']
nosy_count = 2.0
nosy_names = ['shihai1991', 'simonaldrich']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue43967'
versions = ['Python 3.8']
```

</p></details>

**Comment by chubbard-adapdix** [comment]
Suggest we re-open.  The related issue does not address the same problem i.e if it is fixed it wont fix this issue.
Py_Initialize; Py_Finalize(); on its own fails valgrind.
