### ISSUE TITLE
Incorrect MIME type returned for .js files Windows 10.

### ISSUE THREAD

**Issue by 70b58005-5107-4983-b31a-7ffc81063c1e** [python/cpython#88141]
BPO | [43975](https://bugs.python.org/issue43975)
--- | :---
Superseder | <li>bpo-32462: validate mime types loaded from system files. Document that system files take precedence.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-18.13:39:07.304>
created_at = <Date 2021-04-29.09:15:48.278>
labels = ['type-bug', 'library', '3.9']
title = 'Incorrect MIME type returned for .js files Windows 10.'
updated_at = <Date 2022-01-18.13:39:07.304>
user = 'https://bugs.python.org/smeans'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.13:39:07.304>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-18.13:39:07.304>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2021-04-29.09:15:48.278>
creator = 'smeans'
dependencies = []
files = []
hgrepos = []
issue_num = 43975
keywords = []
message_count = 1.0
messages = ['392294']
nosy_count = 1.0
nosy_names = ['smeans']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '32462'
type = 'behavior'
url = 'https://bugs.python.org/issue43975'
versions = ['Python 3.9']
```

</p></details>

**Comment by thelordofscrubs** [comment]
I really had to dig deep into my google fu to find this fix for my issue. Exact same problem, exact same solution worked for me. Was not terribly hard to quickly edit one registry entry to application/javascript.

Thanks for putting this one out there!

**Comment by dfb** [comment]
Just by way of feedback, `mimetypes.add_type` provides a good workaround, at least if you know ahead of time what types you care about.

It may be too late for `guess_type` to be fixed, but the rationale for the current behavior seems to be driven by how it was implemented more than by what one would reasonably expect the API to do, at least for well-defined MIME types, and so from the perspective of someone using Python, this sure feels like a bug in Python - the fact that the implementation is getting its info from an unreliable source doesn't seem super relevant. :)

(It took us a long time to narrow down a production bug to the fact that `.js` URLs were being reported as `text/plain` on some Windows machines and not others and then, per the [HTML spec](https://html.spec.whatwg.org/#the-script-element), an embedded browser wouldn't load the files.)
