### ISSUE TITLE
Current PY_VERSION 3.10.0a7+ does not conform to PEP 440

### ISSUE THREAD

**Issue by a54757d3-0bf5-418c-95bd-f21f5174c12f** [python/cpython#88166]
BPO | [44000](https://bugs.python.org/issue44000)
--- | :---
Nosy | @ned-deily, @ambv, @JelleZijlstra, @jouve, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-01.17:59:25.275>
created_at = <Date 2021-05-01.17:06:30.701>
labels = []
title = 'Current PY_VERSION 3.10.0a7+ does not conform to PEP 440'
updated_at = <Date 2021-05-01.17:59:25.275>
user = 'https://github.com/jouve'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-01.17:59:25.275>
actor = 'Cyril Jouve'
assignee = 'none'
closed = True
closed_date = <Date 2021-05-01.17:59:25.275>
closer = 'Cyril Jouve'
components = []
creation = <Date 2021-05-01.17:06:30.701>
creator = 'Cyril Jouve'
dependencies = []
files = []
hgrepos = []
issue_num = 44000
keywords = []
message_count = 3.0
messages = ['392607', '392609', '392613']
nosy_count = 5.0
nosy_names = ['ned.deily', 'lukasz.langa', 'JelleZijlstra', 'Cyril Jouve', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44000'
versions = []
```

</p></details>

**Comment by radoering** [comment]
> The "+" convention has been used in CPython for a long time, and changing it without a strong justification seems risky.

It might not be a strong justification but at least an argument:

According to [PEP 508](https://peps.python.org/pep-0508/#environment-markers) `python_full_version` is equal to `platform.python_version()`. Although I could not find a direct reference, the sample values for `python_full_version` in PEP 508 seem to indicate that it should be PEP 440 compliant.

However, there is an escape hatch for non-compliant versions:

> The <version_cmp> operators use the [PEP 440](https://peps.python.org/pep-0440) version comparison rules when those are defined (that is when both sides have a valid version specifier). If there is no defined [PEP 440](https://peps.python.org/pep-0440) behaviour and the operator exists in Python, then the operator falls back to the Python behaviour.

So far, so good.

However, if I'm right that implies a marker like `python_full_version >= "3.9.0"` is fulfilled for Python 3.10.0, but not for Python 3.10.0+. (IIUC, a version comparison should be used for the first one and a string comparison for the second one.)
