### ISSUE TITLE
operator.call/operator.__call__

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#88185]
BPO | [44019](https://bugs.python.org/issue44019)
--- | :---
Nosy | @brettcannon, @rhettinger, @terryjreedy, @mdickinson, @vstinner, @corona10, @hrik2001, @Kreusada
PRs | <li>python/cpython#27888</li><li>python/cpython#28551</li><li>python/cpython#29110</li><li>python/cpython#29124</li><li>python/cpython#29142</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-24.15:26:49.947>
created_at = <Date 2021-05-03.14:24:00.272>
labels = ['type-feature', 'library', '3.11']
title = 'operator.call/operator.__call__'
updated_at = <Date 2021-10-21.22:58:23.491>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-21.22:58:23.491>
actor = 'corona10'
assignee = 'none'
closed = True
closed_date = <Date 2021-09-24.15:26:49.947>
closer = 'mark.dickinson'
components = ['Library (Lib)']
creation = <Date 2021-05-03.14:24:00.272>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 44019
keywords = ['patch']
message_count = 15.0
messages = ['392809', '398859', '400125', '400627', '400628', '400640', '400786', '400821', '402570', '402572', '402580', '404579', '404585', '404605', '404702']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'rhettinger', 'terry.reedy', 'mark.dickinson', 'vstinner', 'corona10', 'hrik2001', 'Kreusada']
pr_nums = ['27888', '28551', '29110', '29124', '29142']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44019'
versions = ['Python 3.11']
```

</p></details>

**Comment by mrucker** [comment]
I'd really like to use this in python 3.7. Any chance there is a python package available which backports this?

**Comment by terryjreedy** [comment]
`operator` is written in python, so you can copy anything you want into your code, or even monkeypatch `operator`.
```
def call(obj, /, *args, **kwargs):
    """Same as obj(*args, **kwargs)."""
    return obj(*args, **kwargs)

__call__ = call
```

**Comment by mrucker** [comment]
@terryjreedy Thanks! I have a python implementation already but it is a little slower than I'd like so I was hoping the c implementation in the operator module might be a little faster.
