### ISSUE TITLE
Request for locals().update() to work, it is

### ISSUE THREAD

**Issue by 3ea264e1-9a1d-4ec0-9102-122f05c45178** [python/cpython#88194]
BPO | [44028](https://bugs.python.org/issue44028)
--- | :---
Nosy | @terryjreedy, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-04.05:05:16.839>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Request for locals().update() to work, it is'
updated_at = <Date 2021-05-10.03:21:06.190>
user = 'https://bugs.python.org/xuancong84'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-10.03:21:06.190>
actor = 'xuancong84'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-05-04.05:05:16.839>
creator = 'xuancong84'
dependencies = []
files = []
hgrepos = []
issue_num = 44028
keywords = []
message_count = 5.0
messages = ['392852', '392856', '392860', '393238', '393347']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'steven.daprano', 'xuancong84']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44028'
versions = ['Python 3.11']
```

</p></details>

**Comment by ncoghlan** [comment]
In Python 3.13, `sys._getframe().f_locals.update(ns)` will update the local variables, even in optimized frames (it's still a bad idea to do that from the code itself, but the ability to do this is a side effect of letting debuggers reliably modify the state of running code).

See https://peps.python.org/pep-0667/ for details.
