### ISSUE TITLE
canonicalize "upper-case" -> "uppercase"; "lower-case" -> "lowercase"

### ISSUE THREAD

**Issue by 517b2564-234d-44ce-ae2e-e15a7e99a2ea** [python/cpython#88211]
BPO | [44045](https://bugs.python.org/issue44045)
--- | :---
Nosy | @ericvsmith, @merwok, @jugmac00, @nanjekyejoannah, @akulakov
PRs | <li>python/cpython#25985</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-05.06:55:02.631>
labels = []
title = 'canonicalize "upper-case" -> "uppercase"; "lower-case" -> "lowercase"'
updated_at = <Date 2021-05-28.20:54:32.055>
user = 'https://github.com/jugmac00'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-28.20:54:32.055>
actor = 'nanjekyejoannah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-05-05.06:55:02.631>
creator = 'jugmac00'
dependencies = []
files = []
hgrepos = []
issue_num = 44045
keywords = ['patch']
message_count = 10.0
messages = ['392978', '393065', '393217', '393227', '393229', '393248', '393284', '393292', '393293', '394689']
nosy_count = 5.0
nosy_names = ['eric.smith', 'eric.araujo', 'jugmac00', 'nanjekyejoannah', 'andrei.avk']
pr_nums = ['25985']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44045'
versions = []
```

</p></details>

### Linked PRs
* gh-99625

**Comment by slateny** [comment]
In [imaplib](https://docs.python.org/3/library/imaplib.html#imap4-objects), the first sentence in that section there is this:

```
All IMAP4rev1 commands are represented by methods of the same name, either upper-case or lower-case.
```

Should that be changed over too, or is this issue good to close?

**Comment by nanjekyejoannah** [comment]
> In [imaplib](https://docs.python.org/3/library/imaplib.html#imap4-objects), the first sentence in that section there is this:
> 
> ```
> All IMAP4rev1 commands are represented by methods of the same name, either upper-case or lower-case.
> ```
> 
> Should that be changed over too, or is this issue good to close?

Yes, makes sense, you can open a PR if can.

**Comment by tbwolfe** [comment]
PR Submitted. Please let me know if there are any issues.
