### ISSUE TITLE
Zipfile lib overwrites the extra field during closing when the archive size is more then ZIP64_LIMIT

### ISSUE THREAD

**Issue by f73be7cd-9264-494f-9470-5d225d807bf4** [python/cpython#88233]
BPO | [44067](https://bugs.python.org/issue44067)
--- | :---
Nosy | @Yhg1s, @serhiy-storchaka
Files | <li>[zip_bug.zip](https://bugs.python.org/file50025/zip_bug.zip "Uploaded as application/x-zip-compressed at 2021-05-07.08:18:55 by shaanbhaya")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-07.08:18:55.383>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', '3.7', 'library']
title = 'Zipfile lib overwrites the extra field during closing when the archive size is more then ZIP64_LIMIT'
updated_at = <Date 2021-11-07.00:34:59.007>
user = 'https://bugs.python.org/shaanbhaya'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-07.00:34:59.007>
actor = 'anadius'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-07.08:18:55.383>
creator = 'shaanbhaya'
dependencies = []
files = ['50025']
hgrepos = []
issue_num = 44067
keywords = []
message_count = 3.0
messages = ['393178', '393179', '405760']
nosy_count = 5.0
nosy_names = ['twouters', 'alanmcintyre', 'serhiy.storchaka', 'shaanbhaya', 'anadius']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44067'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-96161
* gh-102083
* gh-102084
* gh-102086
* gh-102087

**Comment by thatch** [comment]
I found the same bug while working on another issue.  I prefer the easier-to-understand one.

**Comment by thatch** [comment]
I ended up not going with the easier-to-understand version, because it failed to pass through 1-3 bytes of garbage after the last extra, which we pass through in the "not modified" case already.

**Comment by jaraco** [comment]
> I ended up not going with the easier-to-understand version, because it failed to pass through 1-3 bytes of garbage after the last extra, which we pass through in the "not modified" case already.

In an attempt to make the code easier to comprehend and less prone to error, I drafted #102084.
