### ISSUE TITLE
Add a method to check interpolation errors in configparser

### ISSUE THREAD

**Issue by 89df4d33-a759-43cc-9ccf-fa4f7b5981e0** [python/cpython#88248]
BPO | [44082](https://bugs.python.org/issue44082)
--- | :---
Nosy | @ambv, @munircontractor
PRs | <li>python/cpython#26002</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-09.01:45:37.032>
labels = ['type-feature', 'library']
title = 'Add a method to check interpolation errors in configparser'
updated_at = <Date 2021-05-09.01:49:58.602>
user = 'https://github.com/munircontractor'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-09.01:49:58.602>
actor = 'munircontractor'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-09.01:45:37.032>
creator = 'munircontractor'
dependencies = []
files = []
hgrepos = []
issue_num = 44082
keywords = ['patch']
message_count = 1.0
messages = ['393291']
nosy_count = 2.0
nosy_names = ['lukasz.langa', 'munircontractor']
pr_nums = ['26002']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44082'
versions = []
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Thank you for your suggestion, @munircontractor, but I think that such function is too application specific. What is an error in one program may be valid in another program if some options are always raw or the vars dictionary is always provided. You can easily write code that checks the ConfigParser in a way that is valid in your program.
