### ISSUE TITLE
[C API] Deprecate legacy API for configure Python initialization

### ISSUE THREAD

**Issue by vstinner** [python/cpython#88279]
BPO | [44113](https://bugs.python.org/issue44113)
--- | :---
Nosy | @vstinner, @corona10, @joukewitteveen
PRs | <li>python/cpython#26060</li><li>python/cpython#24876</li><li>python/cpython#26083</li><li>python/cpython#26084</li><li>python/cpython#26085</li><li>python/cpython#28974</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-14.12:21:54.201>
created_at = <Date 2021-05-12.10:20:54.214>
labels = ['expert-C-API', '3.11', 'docs']
title = '[C API] Deprecate legacy API for configure Python initialization'
updated_at = <Date 2021-10-15.11:43:51.791>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-15.11:43:51.791>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-05-14.12:21:54.201>
closer = 'vstinner'
components = ['Documentation', 'C API']
creation = <Date 2021-05-12.10:20:54.214>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 44113
keywords = ['patch']
message_count = 8.0
messages = ['393499', '393550', '393551', '393553', '393641', '393647', '393648', '404005']
nosy_count = 4.0
nosy_names = ['vstinner', 'docs@python', 'corona10', 'joukewitteveen']
pr_nums = ['26060', '24876', '26083', '26084', '26085', '28974']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44113'
versions = ['Python 3.11']
```

</p></details>

**Comment by milianw** [comment]
Hey there, I'm unsure if this is the right place to ask - if not, please guide me elsewhere.

How are projects using the limited python API supposed to port away from the deprecated API? The "new" API in `cpython/initconfig.h` is guarded behind a `#ifndef Py_LIMITED_API` and thus not accessible...

Can you please make this API available through the limited API, or revert the decision to deprecate this API?

Thanks

**Comment by encukou** [comment]
The proper place is here: https://github.com/python/cpython/issues/105145
Apparently, the new API is available widely enough.

**Comment by vstinner** [comment]
> How are projects using the limited python API supposed to port away from the deprecated API?

I suggest to continue in the dedicated issue: https://github.com/python/cpython/issues/107954 "No limited C API to customize Python initialization (PyConfig, PEP 587)"

I worked on two projects for the limited C API:

* Stable ABI to **configure** Python initialization: https://github.com/python/cpython/pull/110176
* Stable ABI to **get the current** Python **configuration**: https://github.com/python/cpython/pull/112609 => https://github.com/capi-workgroup/decisions/issues/3

So far, I had to put this work aside since I had too many things on my plate.
