### ISSUE TITLE
Improve conversions for fractions

### ISSUE THREAD

**Issue by 0feeca69-f794-43f6-b3ff-ff0ea3439fc0** [python/cpython#88281]
BPO | [44115](https://bugs.python.org/issue44115)
--- | :---
Nosy | @rhettinger, @mdickinson, @serhiy-storchaka, @tecki, @vedgar
PRs | <li>python/cpython#26064</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-12.13:09:37.632>
labels = ['type-feature', 'library', '3.11']
title = 'Improve conversions for fractions'
updated_at = <Date 2021-05-15.04:21:37.665>
user = 'https://github.com/tecki'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-15.04:21:37.665>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-12.13:09:37.632>
creator = 'Martin.Teichmann'
dependencies = []
files = []
hgrepos = []
issue_num = 44115
keywords = ['patch']
message_count = 4.0
messages = ['393507', '393554', '393559', '393560']
nosy_count = 5.0
nosy_names = ['rhettinger', 'mark.dickinson', 'serhiy.storchaka', 'Martin.Teichmann', 'veky']
pr_nums = ['26064']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44115'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
Accepting any object with `as_integer_ratio` was rejected in https://github.com/python/cpython/issues/82017.
If SageMath's use case is common enough, we might want to add a new method like `__integer_ratio__` on *exact* numeric types, similar to `__index__` for exact integer ones. But that would call for wider discussion [on Discourse](https://discuss.python.org/c/ideas/6).
