### ISSUE TITLE
Add optional weights parameter to statistics.fmean()

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#88316]
BPO | [44150](https://bugs.python.org/issue44150)
--- | :---
Nosy | @rhettinger, @stevendaprano
PRs | <li>python/cpython#26175</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-21.03:22:49.037>
created_at = <Date 2021-05-16.18:56:52.909>
labels = ['type-feature', 'library', '3.11']
title = 'Add optional weights parameter to statistics.fmean()'
updated_at = <Date 2021-05-21.03:22:49.037>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-21.03:22:49.037>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2021-05-21.03:22:49.037>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2021-05-16.18:56:52.909>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 44150
keywords = ['patch']
message_count = 1.0
messages = ['393751']
nosy_count = 2.0
nosy_names = ['rhettinger', 'steven.daprano']
pr_nums = ['26175']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44150'
versions = ['Python 3.11']
```

</p></details>

**Comment by pjmcdermott** [comment]
From [manpage:](https://docs.python.org/3/library/statistics.html#statistics.fmean)
"Unless explicitly noted, these functions support [int](https://docs.python.org/3/library/functions.html#int), [float](https://docs.python.org/3/library/functions.html#float), [Decimal](https://docs.python.org/3/library/decimal.html#decimal.Decimal) and [Fraction](https://docs.python.org/3/library/fractions.html#fractions.Fraction)." and (for fmean)
"Convert data to floats and compute the arithmetic mean."
