### ISSUE TITLE
SyntaxError misidentified in 3.10.0b1 when = used instead of : in dict literal

### ISSUE THREAD

**Issue by f2044c74-2589-491b-aea5-3f64941d4a9c** [python/cpython#88346]
BPO | [44180](https://bugs.python.org/issue44180)
--- | :---
Nosy | @aroberge, @lysnikolaou, @pablogsal, @miss-islington, @shreyanavigyan
PRs | <li>python/cpython#26253</li><li>python/cpython#26281</li><li>python/cpython#26283</li><li>python/cpython#26292</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-19.18:38:05.183>
labels = ['interpreter-core', '3.10']
title = 'SyntaxError misidentified in 3.10.0b1 when = used instead of : in dict literal'
updated_at = <Date 2021-05-21.18:20:51.072>
user = 'https://github.com/aroberge'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-21.18:20:51.072>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Parser']
creation = <Date 2021-05-19.18:38:05.183>
creator = 'aroberge'
dependencies = []
files = []
hgrepos = []
issue_num = 44180
keywords = ['patch']
message_count = 10.0
messages = ['393964', '393965', '393966', '393967', '393968', '393969', '393970', '393971', '394119', '394139']
nosy_count = 5.0
nosy_names = ['aroberge', 'lys.nikolaou', 'pablogsal', 'miss-islington', 'shreyanavigyan']
pr_nums = ['26253', '26281', '26283', '26292']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44180'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this is resolved, the error now is:

>>> ages = {'Alice'=22, 'Bob'=23}
  File "<stdin>", line 1
    ages = {'Alice'=22, 'Bob'=23}
            ^^^^^^^
SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?
>>> ages = {'Alice'=22}
  File "<stdin>", line 1
    ages = {'Alice'=22}
            ^^^^^^^
SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?
>>>
