### ISSUE TITLE
Annotations, Inheritance and Circular Reference

### ISSUE THREAD

**Issue by 6b99c0f7-84c2-4dfb-87cd-c6a5c9bdb75d** [python/cpython#88358]
BPO | [44192](https://bugs.python.org/issue44192)
--- | :---
Nosy | @lysnikolaou, @FFY00, @reob-info

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-20.17:01:23.005>
labels = ['interpreter-core', '3.9', 'performance']
title = 'Annotations, Inheritance and Circular Reference'
updated_at = <Date 2021-05-24.18:23:41.166>
user = 'https://github.com/reob-info'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-24.18:23:41.166>
actor = 'FFY00'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Parser']
creation = <Date 2021-05-20.17:01:23.005>
creator = 'reob-info'
dependencies = []
files = []
hgrepos = []
issue_num = 44192
keywords = []
message_count = 3.0
messages = ['394038', '394260', '394261']
nosy_count = 3.0
nosy_names = ['lys.nikolaou', 'FFY00', 'reob-info']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue44192'
versions = ['Python 3.9']
```

</p></details>

**Comment by ronaldoussoren** [comment]
There is no bug here, there are two ways to work with circular dependencies like this.

1. Use ``from __future__ import annotations`` as described by @FFY00 
2. Use a string for the type annotation in the first class:

```
class Base:
    _sub: "list[Sub]"

class Sub:
    _parent: Base
```

Both will work with type checkers.

A new feature that adds explicit forward references is something that should be discussed on discuss.python.org (and likely requires a PEP) before creating an issue, please check for earlier discussions about this first.
