### ISSUE TITLE
multiprocessing AF_PIPE name format is slightly confusing in the docs

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#88355]
BPO | [44189](https://bugs.python.org/issue44189)
--- | :---
Nosy | @anntzer, @eryksun

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-20.12:11:12.410>
labels = ['3.8', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = 'multiprocessing AF_PIPE name format is slightly confusing in the docs'
updated_at = <Date 2021-05-20.23:19:26.845>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-20.23:19:26.845>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-05-20.12:11:12.410>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 44189
keywords = []
message_count = 2.0
messages = ['394020', '394078']
nosy_count = 3.0
nosy_names = ['docs@python', 'Antony.Lee', 'eryksun']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44189'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by slateny** [comment]
What's the reason for the double slashes (`r'\\.\pipe\{PipeName}'` instead of `r'\.\pipe\{PipeName}'`)?

**Comment by cousteaulecommandant** [comment]
> What's the reason for the double slashes (`r'\\.\pipe\{PipeName}'` instead of `r'\.\pipe\{PipeName}'`)?

The string actually has to contain two backslashes, like `\\.\pipe\myProgramPipe` or `\\NetworkPC123\pipe\myProgramPipe`; it's not any markup syntax for the documentation, or Python's `r'...'` syntax, if that's what you're asking.
If you use `r'\.\pipe\myProgramPipe'` with a single `\` you get an error saying that the filename syntax is incorrect (and then will spend a while trying to figure out what you did wrong, until you come across this bug report which explains the proper syntax).

(Fortunately, both Python's `r'...'` syntax and ReST's ``` ``...`` ``` syntax allow you to pass backslashes without needing to escape them, so the backslashes you see there are the ones that actually need to appear in the result.)

**Comment by cousteaulecommandant** [comment]
> Or just use a regular literal and rely on the reader to understand that "{PipeName}" and "{ServerName}" are parameters:

Isn't it more common to use angle brackets `<...>` for this sort of thing when font formatting is not available, like `\\<ServerName>\pipe\<PipeName>`?
(If using braces for this sort of thing is a common idiom in Python documentation, then disregard this comment.)
