### ISSUE TITLE
Add flags or function in pathlib.Path

### ISSUE THREAD

**Issue by d874385e-1431-4256-94f0-c8c66a2e2231** [python/cpython#88364]
BPO | [44198](https://bugs.python.org/issue44198)
--- | :---
Nosy | @barneygale, @tetelevm

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-20.20:56:21.241>
labels = ['library', '3.10']
title = 'Add flags or function in pathlib.Path'
updated_at = <Date 2021-05-21.19:22:11.213>
user = 'https://github.com/tetelevm'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-21.19:22:11.213>
actor = 'barneygale'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-20.20:56:21.241>
creator = 'tetelevm'
dependencies = []
files = []
hgrepos = []
issue_num = 44198
keywords = []
message_count = 2.0
messages = ['394064', '394145']
nosy_count = 2.0
nosy_names = ['barneygale', 'tetelevm']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44198'
versions = ['Python 3.10']
```

</p></details>

**Comment by AlexWaygood** [comment]
I agree with @barneygale. Python provides a general-purpose tool for dealing with this problem: comprehensions! I don't think the small amount of boilerplate here is sufficient grounds for adding a dedicated method, increasing the maintenance burden on the CPython team for (possibly) decades to come. Thanks for the suggestion @tetelevm, but I think we'll say "no" to this one :)
