### ISSUE TITLE
Add errors argument to importlib.abc.Traversable.read_text

### ISSUE THREAD

**Issue by FFY00** [python/cpython#88368]
BPO | [44202](https://bugs.python.org/issue44202)
--- | :---
Nosy | @brettcannon, @jaraco, @FFY00

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-21.00:40:18.784>
labels = ['library', '3.11']
title = 'Add errors argument to importlib.abc.Traversable.read_text'
updated_at = <Date 2021-05-23.17:42:07.295>
user = 'https://github.com/FFY00'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-23.17:42:07.295>
actor = 'jaraco'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-21.00:40:18.784>
creator = 'FFY00'
dependencies = []
files = []
hgrepos = []
issue_num = 44202
keywords = []
message_count = 3.0
messages = ['394088', '394089', '394212']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'jaraco', 'FFY00']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44202'
versions = ['Python 3.11']
```

</p></details>

**Comment by FFY00** [comment]
That sounds reasonable, though it makes it slightly harder for users of the legacy API to migrate. It shouldn't be a big deal though.

**Comment by jaraco** [comment]
Sounds like we're comfortable closing this issue until there's a demand for the behavior.

**Comment by jaraco** [comment]
Sounds like maybe FFY00 was prescient about the need for this behavior. I don't think I fully appreciated the concern until it was dutifully elucidated in #127012.
