### ISSUE TITLE
stop() on a stopped loop inhibits the next run_forever

### ISSUE THREAD

**Issue by a96b159f-cb5c-4623-828e-9a5c36a82034** [python/cpython#88391]
BPO | [44225](https://bugs.python.org/issue44225)
--- | :---
Nosy | @asvetlov, @1st1, @megahypex
PRs | <li>python/cpython#26483</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-24.13:55:00.555>
labels = ['3.11', 'type-bug', '3.10', 'expert-asyncio']
title = 'stop() on a stopped loop inhibits the next run_forever'
updated_at = <Date 2021-06-02.10:26:05.486>
user = 'https://bugs.python.org/mandolaerik'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-02.10:26:05.486>
actor = 'WhosMega'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-05-24.13:55:00.555>
creator = 'mandolaerik'
dependencies = []
files = []
hgrepos = []
issue_num = 44225
keywords = ['patch']
message_count = 2.0
messages = ['394250', '394896']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'mandolaerik', 'WhosMega']
pr_nums = ['26483']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44225'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by akulakov** [comment]
Simply adding `self._stopping = False` at the top of `BaseEventLoop.run_forever` would fix it, but this seems to be intentional way of operation, though I don't know the reason for it:

https://github.com/python/cpython/blob/49f61068f49747164988ffc5a442d2a63874fc17/Lib/test/test_asyncio/test_base_events.py#L926

**Comment by gvanrossum** [comment]
Yeah, this may be surprising, but we shouldn't change it. There's a long discussion in https://bugs.python.org/issue25593 that might shed some light on the reason.
