### ISSUE TITLE
Better explain the GC contract for PyType_FromSpecWithBases

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#88429]
BPO | [44263](https://bugs.python.org/issue44263)
--- | :---
Nosy | @vstinner, @pablogsal, @miss-islington, @shihai1991, @erlend-aasland
PRs | <li>python/cpython#26442</li><li>python/cpython#26443</li><li>python/cpython#26444</li><li>python/cpython#26445</li><li>python/cpython#26446</li><li>python/cpython#26447</li><li>python/cpython#26463</li><li>python/cpython#26464</li><li>python/cpython#26465</li><li>python/cpython#26466</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-01.21:39:22.556>
created_at = <Date 2021-05-29.00:00:31.172>
labels = ['interpreter-core', 'expert-C-API', '3.11']
title = 'Better explain the GC contract for PyType_FromSpecWithBases'
updated_at = <Date 2021-06-01.21:39:22.553>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-01.21:39:22.553>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-01.21:39:22.556>
closer = 'vstinner'
components = ['Interpreter Core', 'C API']
creation = <Date 2021-05-29.00:00:31.172>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 44263
keywords = ['patch']
message_count = 13.0
messages = ['394706', '394708', '394709', '394710', '394711', '394712', '394733', '394799', '394800', '394802', '394803', '394872', '394873']
nosy_count = 5.0
nosy_names = ['vstinner', 'pablogsal', 'miss-islington', 'shihai1991', 'erlendaasland']
pr_nums = ['26442', '26443', '26444', '26445', '26446', '26447', '26463', '26464', '26465', '26466']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44263'
versions = ['Python 3.11']
```

</p></details>

**Comment by vstinner** [comment]
Example of bug in the wild: Boost Python enum type defined Py_TPFLAGS_HAVE_GC flag but has no traverse function and instances doesn't have to be tracked by the GC:
* https://github.com/boostorg/python/pull/385
* https://github.com/boostorg/python/commit/a218babc8daee904a83f550fb66e5cb3f1cb3013

Note: it's an enum such an "enum" in C, like a Python int (1, 2, ...). It's unrelated to Python enum module.
