### ISSUE TITLE
Add descriptive error message when environment variable not detected

### ISSUE THREAD

**Issue by 75a10673-bc11-4b30-a73a-649465aeea24** [python/cpython#88430]
BPO | [44264](https://bugs.python.org/issue44264)
--- | :---
Nosy | @eryksun, @iritkatriel, @astrosticks
PRs | <li>python/cpython#23717</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-29.19:13:51.791>
labels = ['type-feature', '3.11']
title = 'Add descriptive error message when environment variable not detected'
updated_at = <Date 2022-01-30.07:58:02.160>
user = 'https://github.com/astrosticks'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-30.07:58:02.160>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-05-29.19:13:51.791>
creator = 'astrosticks'
dependencies = []
files = []
hgrepos = []
issue_num = 44264
keywords = []
message_count = 6.0
messages = ['394735', '412114', '412115', '412116', '412126', '412132']
nosy_count = 3.0
nosy_names = ['eryksun', 'iritkatriel', 'astrosticks']
pr_nums = ['23717']
priority = 'normal'
resolution = 'rejected'
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44264'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
I agrpp with Irit. The `KeyError` message is aimed at programmers, and it should be accompanied by the traceback, which usually clarifies that it's coming from `os.environ`.
If this is due to a user error, it's the program's job to display a user-friendly message.

I will close the issue & PR in a week if there are no objections.
