### ISSUE TITLE
Add support for yescrypt in crypt.

### ISSUE THREAD

**Issue by 2bdace21-ed06-46f2-b866-437d482f9774** [python/cpython#88475]
BPO | [44309](https://bugs.python.org/issue44309)
--- | :---
Nosy | @tiran, @dseomn, @besser82
PRs | <li>python/cpython#26526</li><li>python/cpython#26527</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-04.11:10:28.051>
labels = ['type-feature', 'library', '3.11']
title = 'Add support for yescrypt in crypt.'
updated_at = <Date 2021-09-23.19:43:10.780>
user = 'https://github.com/besser82'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-23.19:43:10.780>
actor = 'dseomn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-06-04.11:10:28.051>
creator = 'besser82'
dependencies = []
files = []
hgrepos = []
issue_num = 44309
keywords = ['patch']
message_count = 2.0
messages = ['395073', '395160']
nosy_count = 4.0
nosy_names = ['jafo', 'christian.heimes', 'dseomn', 'besser82']
pr_nums = ['26526', '26527']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44309'
versions = ['Python 3.11']
```

</p></details>

**Comment by AlexWaygood** [comment]
The `crypt` module is now deprecated following the acceptance of PEP 594 by the Steering Council. As such, bugfixes and improvements to the module will no longer be accepted; I am therefore closing this issue.
