### ISSUE TITLE
IDLE: Colorizer and output tests hang on macOS

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#88496]
BPO | [44330](https://bugs.python.org/issue44330)
--- | :---
Nosy | @terryjreedy, @taleinat, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-07.01:41:11.947>
labels = ['3.9', '3.10', '3.11']
title = 'IDLE: Colorizer and output tests hang on macOS'
updated_at = <Date 2021-06-07.22:11:14.604>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-07.22:11:14.604>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-06-07.01:41:11.947>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 44330
keywords = []
message_count = 3.0
messages = ['395239', '395285', '395290']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'taleinat', 'ned.deily']
pr_nums = []
priority = 'critical'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44330'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-104025
* gh-104027
* gh-104075
* gh-104076

**Comment by chrstphrchvz** [comment]
I also encounter the hang in test_outwin.OutputWindowTest.test_goto_file_line due to this `update`: https://github.com/python/cpython/blob/c9864121cba5e5366d8e023fa14be0eac504cc06/Lib/idlelib/outwin.py#L115

Changing it to `update_idletasks()` allows this test to pass here as well.

**Comment by terryjreedy** [comment]
Both of those .update() calls are from the original 2000 idlelib commit.  There are 13 others (not all from 2000 ;-).  (Possibly one or two from a locally defined update function.)  I am not sure that I am completely clear on when to use which.  Feel free to check others.

The output update is there to *slow* down the display to make each line visible and then scroll.  When recursively grepping 'editor' the 295 lines take several seconds instead displaying the entire output in a fraction of a second.  CommandPrompt displays 300 lines in about the same time.  Maybe I will delete instead of replace, or consider for later.

The colorizer update() is preceded by this:
```
                if not ok:
                    # We're in an inconsistent state, and the call to
                    # update may tell us to stop.  It may also change
                    # the correct value for "next" (since this is a
                    # line.col string, not a true mark).  So leave a
                    # crumb telling the next invocation to resume here
                    # in case update tells us to leave.
                    self.tag_add("TODO", next)
```
How?  No evidence of the claims, no test case to see if still true 23 years later.  It turns out that either update causes color to be erased after a font face, size, or boldness changes.  Comes back faster with update_idletasks.  With neither, I don't see it disappear.  I need to test behavior while typing or scrolling, but too late today.

**Comment by terryjreedy** [comment]
More is needed for test_idle to pass on my 'Air' with Catalina.  I added another '_idletasks' in test_sidebar to fix another hang, but an 'is' test is failing in test_mousewheel.  I may just skip on mac.  (branch update2.)
