### ISSUE TITLE
Reduce memory usage of urllib.unquote and unquote_to_bytes

### ISSUE THREAD

**Issue by ad186d5a-3642-4a78-96eb-191b051d514d** [python/cpython#88500]
BPO | [44334](https://bugs.python.org/issue44334)
--- | :---
Nosy | @terryjreedy, @gpshead, @orsenthil, @mustafaelagamey
PRs | <li>python/cpython#26576</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-07.15:07:38.990>
labels = ['extension-modules', '3.11', '3.9', '3.10', 'performance']
title = 'Use bytearray in urllib.unquote_to_bytes'
updated_at = <Date 2021-06-07.20:09:11.522>
user = 'https://github.com/mustafaelagamey'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-07.20:09:11.522>
actor = 'gregory.p.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-06-07.15:07:38.990>
creator = 'eng.mustafaelagamey'
dependencies = []
files = []
hgrepos = []
issue_num = 44334
keywords = ['patch']
message_count = 2.0
messages = ['395280', '395281']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'gregory.p.smith', 'orsenthil', 'eng.mustafaelagamey']
pr_nums = ['26576']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue44334'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

* PR: gh-96763

**Comment by iritkatriel** [comment]
The PR was closed due to technicalities (pointing to the wrong branch, CLA) and the OP didn’t follow up.

Unless someone object I will close this issue as well.

**Comment by gpshead** [comment]
I created a new PR and included fixing a similar legacy design issue in `unquote()` as well as the original report's `unquote_to_bytes()`. Some performance microbenchmarks need running before I'll consider moving forward with it.

If someone _wanted_ to consider this a security issue it could be backported. It is at _most_ a fixed constant factor (roughly $len(input) * sizeof(PyObject)$ memory consumption vs a maximally antagonistic input though. That doesn't smell DoS worthy.
