### ISSUE TITLE
IDLE: support Command-click on window title on macOS

### ISSUE THREAD

**Issue by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [python/cpython#88516]
BPO | [44350](https://bugs.python.org/issue44350)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily, @aivarannamaa

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2021-06-08.18:13:50.362>
labels = ['OS-mac', 'expert-IDLE', '3.11']
title = 'IDLE: support Command-click on window title on macOS'
updated_at = <Date 2021-06-08.21:25:08.906>
user = 'https://github.com/aivarannamaa'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-08.21:25:08.906>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'macOS']
creation = <Date 2021-06-08.18:13:50.362>
creator = 'Aivar.Annamaa'
dependencies = []
files = []
hgrepos = []
issue_num = 44350
keywords = []
message_count = 3.0
messages = ['395348', '395349', '395363']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'Aivar.Annamaa']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44350'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-112894
* gh-115840
* gh-115841

**Comment by ronaldoussoren** [comment]
This is a screenshot of the current behaviour:
<img width="596" alt="Screenshot 2023-12-09 at 10 50 23" src="https://github.com/python/cpython/assets/713966/0fbe8a08-1847-40f8-97ff-c8bcf35fd401">

This shows that the file name and full path are shown in the window title, but those are not interactive elements. 

With the proposed change you get to see:

<img width="597" alt="image" src="https://github.com/python/cpython/assets/713966/f75b2f63-8bce-4532-940e-5ccfce128709">

The file icon is an interactive element that can be used to shown the full path to the file, and the icon can also be dragged to locations accepting a file location (shows the full path when dragged into the terminal and can also be used to drag the file into a file open dialog or ...)

<img width="597" alt="image" src="https://github.com/python/cpython/assets/713966/c61a1fe5-a956-4adf-91ed-b6e2ae27ab23">

This is one line change to editor.py, add the following line to the end of "saved_change_hook":

        self.top.wm_attributes("-titlepath", long)

This also works with new files ("File" -> "New File"): This gets shown as "untitled" in the window title and grows the file icon on first save. 

This behaviour matches the behaviour of other editor windows on macOS and is IMHO a good new feature.

**Comment by ronaldoussoren** [comment]
The attached PR does slightly more than just this issue:

- Use the proxy icon (this issue)
- Maintain window save state (black dot in the red close icon instead of modifying the window title)
- Only show the short filename in the title, not the long name as well as the long one can be retrieved from the proxy item. This matches platform behaviour.

This brings the editor window closer to default behaviour.  Behaviour is not perfectly aligned with the platform though, see the screenshot below for a native Cocoa window which has a quick edit dropdown for renaming and moving files. AFAIK that's not possible with Tk, but I'm hardly an expert.

<img width="606" alt="image" src="https://github.com/python/cpython/assets/713966/703a6b52-ef7f-4c8e-9a36-d96a5b9f6a79">

**Comment by ronaldoussoren** [comment]
Another thing I ran into is that IDLE will close without warning when there are open unsaved files. I've filed  #112898 for that.

**Comment by terryjreedy** [comment]
Ronald, thank you for the images.  For once, they are more helpful than text.  Windows has clickable app icons at the left end of the title bar.  I had not noticed before the little icons next to some titles.  IDLE on macOS not having them can be seen as a bug, even though clicking will not do the same.

I will experiment with the PR I hope tomorrow.  A couple of thoughts: first, there is a tension between cross-platform behavior, which I am in favor of as much as sensibly possible, and platform-specific customization.  Second, I hope to eventually switch to a multi-tabbed editor.  At that time, tabs will only have short names.  Notepad++ on Windows puts the path for the currently active tab on the window title bar.  And third, IDLE has (underused) hover tips.  I should see if hovering over the title bar can trigger anything.  Or ditto for hovering over tabs.

**Comment by chrstphrchvz** [comment]
> Behaviour is not perfectly aligned with the platform though, see the screenshot below for a native Cocoa window which has a quick edit dropdown for renaming and moving files. AFAIK that's not possible with Tk, but I'm hardly an expert.
> 
> <img alt="image" width="606" src="https://private-user-images.githubusercontent.com/713966/289274616-703a6b52-ef7f-4c8e-9a36-d96a5b9f6a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDQ0MDcsIm5iZiI6MTcwMjIwNDEwNywicGF0aCI6Ii83MTM5NjYvMjg5Mjc0NjE2LTcwM2E2YjUyLWVmN2YtNGM4ZS05YTM2LWQ5NmE1YjlmNmE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxMDI4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDJjOTc0YjQ1M2JiY2E3ZDU3MGNmYTc1OTNkMzJiOTA5NGMwODgyMmMxNDRkZGJiMDc0ZGM4NTZiNjQwZjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ztpCiU6MMDUz8S_IsMgwg0uEXDPrdTRd6g54g8pVRQ">

That is the “Document Management” feature introduced in OS X 10.9 Mavericks. I believe it is only available in apps using certain AppKit APIs like NSDocument, which Tk Aqua does not and likely will not use.


> And third, IDLE has (underused) hover tips. I should see if hovering over the title bar can trigger anything.

The title bar is a decoration provided by the window manager. On X11, Tk toplevels have no awareness of mouse events for window manager decorations, so I believe there is no supported way to detect titlebar hovering. I cannot say that Tk for Win32 or Aqua have strictly conformed to this X11 behavior; however, if some version of Tk for Win32 or Aqua does report e.g. motion events for window decorations, then I believe that is incidental and not a supported feature.

**Comment by terryjreedy** [comment]
To be clearer than I was before, I support adding mac specific things, but I am opposed to removing cross-platform features when that makes IDLE on mac harder to use by a non-Mac user, such as me.

My memory of looking at file-proxy icons on other Mac Catalina  apps is that there was hardly consistent behavior, but TextEdit and Script Editor both show the path components after control- or command-click.  The problem is discoverability.  The IDLE doc should gain an IDLE on Mac section, or maybe 'OS Differences'.

Save state: Neither TextEdit nor Script Editor put a dot in the upper left red close circle.  Do you mean something else?  Both add `-- edited` to the (short) filename.  A little black dot does not seem standard, and it might be hard to see.

**Comment by ronaldoussoren** [comment]
> To be clearer than I was before, I support adding mac specific things, but I am opposed to removing cross-platform features when that makes IDLE on mac harder to use by a non-Mac user, such as me.
> 
> My memory of looking at file-proxy icons on other Mac Catalina apps is that there was hardly consistent behavior, but TextEdit and Script Editor both show the path components after control- or command-click. The problem is discoverability. The IDLE doc should gain an IDLE on Mac section, or maybe 'OS Differences'.
> 
> Save state: Neither TextEdit nor Script Editor put a dot in the upper left red close circle. Both add `-- edited` to the (short) filename. A little black dot does not seem standard, and it might be hard to see, and would not be visible to non-Mac users. Add it but please leave *s.

I've reverted that part of the change, I agree that keeping them is nicer for cross platform consistency.

Long term it might be nicer to look into using some other way to indicate change (such as one of the unicode bullet characters like  ●, possibly with a different colour), but that's for a different issue and would require cross platform testing.
