### ISSUE TITLE
Bad dataclass post-init example

### ISSUE THREAD

**Issue by c8aa022d-94ac-4f7f-a998-68571f89d539** [python/cpython#88531]
BPO | [44365](https://bugs.python.org/issue44365)
--- | :---
Nosy | @ericvsmith, @akulakov, @MicaelJarniac
Files | <li>[dataclass_inheritance_test.py](https://bugs.python.org/file50414/dataclass_inheritance_test.py "Uploaded as text/plain at 2021-10-31.16:08:57 by da2ce7"): Example of Data Class Inheritance</li><li>[dataclass_inheritance_v2_test.py](https://bugs.python.org/file50415/dataclass_inheritance_v2_test.py "Uploaded as text/plain at 2021-10-31.17:10:54 by da2ce7"): Example of Data Class Inheritance (Updated)</li><li>[dataclass_inheritance_v3_test.py](https://bugs.python.org/file50416/dataclass_inheritance_v3_test.py "Uploaded as text/plain at 2021-10-31.17:30:04 by da2ce7"): Example of Data Class Inheritance (Updated, Version 3)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2021-06-09.15:33:08.429>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', 'docs']
title = 'Bad dataclass post-init example'
updated_at = <Date 2021-10-31.17:30:04.410>
user = 'https://github.com/MicaelJarniac'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-31.17:30:04.410>
actor = 'da2ce7'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-06-09.15:33:08.429>
creator = 'MicaelJarniac'
dependencies = []
files = ['50414', '50415', '50416']
hgrepos = []
issue_num = 44365
keywords = []
message_count = 12.0
messages = ['395427', '395449', '395537', '395541', '395573', '395596', '395861', '395999', '396029', '405406', '405408', '405410']
nosy_count = 5.0
nosy_names = ['eric.smith', 'docs@python', 'andrei.avk', 'MicaelJarniac', 'da2ce7']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44365'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-107404
* gh-114162
* gh-114163

**Comment by ericvsmith** [comment]
Fixed in #107404
