### ISSUE TITLE
PC/frozen_dllmain.c, some expressions have no side effects

### ISSUE THREAD

**Issue by 5fdb60b8-5a12-41dd-847e-6f602f15b195** [python/cpython#88556]
BPO | [44390](https://bugs.python.org/issue44390)
--- | :---
Nosy | @brotherbeer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-11.08:43:42.518>
labels = ['type-bug', '3.10']
title = 'PC/frozen_dllmain.c, some expressions have no side effects'
updated_at = <Date 2021-06-11.08:43:42.518>
user = 'https://github.com/brotherbeer'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-11.08:43:42.518>
actor = 'brotherbeer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-06-11.08:43:42.518>
creator = 'brotherbeer'
dependencies = []
files = []
hgrepos = []
issue_num = 44390
keywords = []
message_count = 1.0
messages = ['395619']
nosy_count = 1.0
nosy_names = ['brotherbeer']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44390'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
CC @pitrou

**Comment by pitrou** [comment]
cc @zooba

**Comment by zooba** [comment]
I have no idea what this file is for or how to use it, but the `*` isn't an issue. The dereference will probably be ignored because it's unused.

In the absence of an actual problem, I see no reason to keep this open. Without knowing what the file is for, I have no desire to change it.
