### ISSUE TITLE
Python 3.9 and 3.10 fails to install in WINE

### ISSUE THREAD

**Issue by e4c32d2e-6bcb-4de3-99c2-ec9071e41964** [python/cpython#88568]
BPO | [44402](https://bugs.python.org/issue44402)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @SamuelMarks

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-14.17:58:42.673>
created_at = <Date 2021-06-12.05:40:12.955>
labels = ['3.10', '3.9', 'OS-windows']
title = 'Python 3.9 and 3.10 fails to install in WINE'
updated_at = <Date 2021-06-14.17:58:42.672>
user = 'https://github.com/SamuelMarks'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-14.17:58:42.672>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-14.17:58:42.673>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2021-06-12.05:40:12.955>
creator = 'samuelmarks'
dependencies = []
files = []
hgrepos = []
issue_num = 44402
keywords = []
message_count = 2.0
messages = ['395677', '395828']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'samuelmarks']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44402'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by sam-ka** [comment]
A hopefully helpful note to all intrepid readers arriving from google and looking for a way to run python on wine: Python version 3.8.6 installs and works fine with wine version 6.0.3 (the version that's available for ubuntu 22.04 LTS). 

It's highly likely that *all* [windows releases](https://www.python.org/downloads/windows/) prior to 3.8.7, the first version that dropped support for windows 7, will work.
