### ISSUE TITLE
A "Coroutines and Tasks" code example needs "asyncio.run(main())"

### ISSUE THREAD

**Issue by 2ce8145f-5244-4ec5-83f5-4816a1590825** [python/cpython#88573]
BPO | [44407](https://bugs.python.org/issue44407)
--- | :---
Nosy | @akulakov, @AtsushiSakai

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-13.05:17:43.545>
labels = ['type-feature', '3.9', 'docs']
title = 'A "Coroutines and Tasks" code example needs "asyncio.run(main())"'
updated_at = <Date 2021-06-15.14:39:52.219>
user = 'https://github.com/AtsushiSakai'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-15.14:39:52.219>
actor = 'andrei.avk'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-06-13.05:17:43.545>
creator = 'AtsushiSakai'
dependencies = []
files = []
hgrepos = []
issue_num = 44407
keywords = []
message_count = 2.0
messages = ['395728', '395882']
nosy_count = 3.0
nosy_names = ['docs@python', 'andrei.avk', 'AtsushiSakai']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44407'
versions = ['Python 3.9']
```

</p></details>

**Comment by slateny** [comment]
I agree with leaving it out - the section says 'Let's modify the above example', so it's implied that whatever example was above should be reused, which includes the imports and the `asyncio.run(main())`. If we were to leave `asyncio.run` in, then we'd also include the imports, but then it seems a bit repetitive to me
