### ISSUE TITLE
Add command-line functionality to uuid module

### ISSUE THREAD

**Issue by f5fd3372-edc3-4555-813b-88415e4a7499** [python/cpython#88597]
BPO | [44431](https://bugs.python.org/issue44431)
--- | :---
Nosy | @serhiy-storchaka, @erlend-aasland, @ephenix
PRs | <li>python/cpython#26751</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-16.04:14:46.410>
labels = ['type-feature', '3.11']
title = 'Add command-line functionality to uuid module'
updated_at = <Date 2021-06-16.22:06:09.458>
user = 'https://github.com/ephenix'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-16.22:06:09.458>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-06-16.04:14:46.410>
creator = 'ephenix'
dependencies = []
files = []
hgrepos = []
issue_num = 44431
keywords = ['patch']
message_count = 2.0
messages = ['395906', '395967']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'erlendaasland', 'ephenix']
pr_nums = ['26751']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44431'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-99463
* gh-101248

**Comment by achhina** [comment]
@ephenix would you still like to work on this as I see you've closed your PR? If not, I'd like to work on this; I'll wait a couple of days to give you a chance to respond if you'd still like to continue.

**Comment by ephenix** [comment]
> @ephenix would you still like to work on this as I see you've closed your PR? If not, I'd like to work on this; I'll wait a couple of days to give you a chance to respond if you'd still like to continue.

I lost track of this -- feel free to take my pull request and do anything necessary to get it merged. IIRC the changes I made were working.

**Comment by gpshead** [comment]
thanks for the contribution.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @achhina. But I have few nitpicks:

1. Most CLI tools on Unix and Linux use minus followed by a single letter as short options, and double minus followed by a sequence of letters as long option. An alternative style used in minority of commands (e.g. `find` and `java`) use single minus for long options. But your proposition mixes the styles: there are short options like `-u`, long options like `--name`, and also long option with a single minus `-ns`. `argparse` of course supports both styles, but I was surprised that it supports a mix, and I am not sure that it will not be broken in future (`-ns` can be interpreted as two separate options `-n` and `-s`).
2. Standard Linux utility `uuidgen` has similar interface, but conflicting short options. `-n` is a short alias of `--namespace`, and `-N` is a short alias of `--name`. As you see option `-n` has different semantic.
3. `uuidgen` accepts namespace argument in form: `@dns @url @oid @x500`. In your proposition it should be in form: `NAMESPACE_DNS NAMESPACE_URL NAMESPACE_OID NAMESPACE_X500`. And it is not documented.

I propose to rename `-n` to `-N` and `-ns` to `-n`, and accept simpler compatible namespace syntax.

**Comment by achhina** [comment]
@serhiy-storchaka that makes sense, I can create a follow-up patch in regards to the proposed changes if everyone agrees - cc @gpshead.

**Comment by gpshead** [comment]
Good thinking Serhiy, those changes makes sense to me.

**Comment by gpshead** [comment]
Just @ me on the PR when you've created one @achhina.

**Comment by gpshead** [comment]
thanks for the contribution!
