### ISSUE TITLE
Implement CALL_FUNCTION adaptive interpreter optimizations

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#88691]
BPO | [44525](https://bugs.python.org/issue44525)
--- | :---
Nosy | @markshannon, @pablogsal, @sobolevn, @Fidget-Spinner, @thesamesam
PRs | <li>python/cpython#26934</li><li>python/cpython#29033</li><li>python/cpython#29271</li><li>python/cpython#29595</li><li>python/cpython#29942</li><li>python/cpython#30011</li><li>python/cpython#30107</li><li>python/cpython#30415</li><li>python/cpython#31273</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-28.14:22:18.192>
labels = ['3.11', 'performance']
title = 'Implement CALL_FUNCTION adaptive interpreter optimizations'
updated_at = <Date 2022-02-11.11:31:07.338>
user = 'https://github.com/Fidget-Spinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-11.11:31:07.338>
actor = 'sobolevn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-06-28.14:22:18.192>
creator = 'kj'
dependencies = []
files = []
hgrepos = []
issue_num = 44525
keywords = ['patch']
message_count = 9.0
messages = ['396639', '404376', '404470', '405108', '405192', '406831', '408554', '408609', '409779']
nosy_count = 5.0
nosy_names = ['Mark.Shannon', 'pablogsal', 'sobolevn', 'kj', 'thesamesam']
pr_nums = ['26934', '29033', '29271', '29595', '29942', '30011', '30107', '30415', '31273']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue44525'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103230

**Comment by iritkatriel** [comment]
Is there anything left to do on this?

**Comment by pablogsal** [comment]
Closing. Please feel free to re-open if we missed anything.
