### ISSUE TITLE
__name__ attribute in typing module

### ISSUE THREAD

**Issue by cdf9c6b9-0048-49db-9fb3-99832523634b** [python/cpython#88690]
BPO | [44524](https://bugs.python.org/issue44524)
--- | :---
Nosy | @gvanrossum, @ambv, @serhiy-storchaka, @JelleZijlstra, @pablogsal, @miss-islington, @uriyyo, @BvB93, @Fidget-Spinner
PRs | <li>python/cpython#27237</li><li>python/cpython#27246</li><li>python/cpython#27614</li><li>python/cpython#27632</li><li>python/cpython#27710</li><li>python/cpython#27815</li><li>python/cpython#27841</li><li>python/cpython#27861</li><li>python/cpython#27871</li><li>python/cpython#27950</li>
Files | <li>[typing_attributes.py](https://bugs.python.org/file50135/typing_attributes.py "Uploaded as text/plain at 2021-06-30.14:35:26 by farcat"): tools to see what items in a module miss given attributes; applied to typing</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ambv'
closed_at = None
created_at = <Date 2021-06-28.14:15:33.897>
labels = ['type-bug', '3.10', '3.11']
title = '__name__ attribute in typing module'
updated_at = <Date 2021-08-28.18:09:48.928>
user = 'https://bugs.python.org/farcat'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-28.18:09:48.928>
actor = 'miss-islington'
assignee = 'lukasz.langa'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-06-28.14:15:33.897>
creator = 'farcat'
dependencies = []
files = ['50135']
hgrepos = []
issue_num = 44524
keywords = ['patch']
message_count = 41.0
messages = ['396638', '396715', '396725', '396729', '396739', '396778', '397684', '397790', '397795', '397804', '397807', '397818', '397819', '397824', '398945', '398969', '398983', '398986', '398991', '399011', '399015', '399019', '399029', '399081', '399087', '399105', '399107', '399157', '399160', '399164', '399176', '399865', '399918', '399924', '399928', '399929', '400020', '400024', '400283', '400286', '400490']
nosy_count = 11.0
nosy_names = ['gvanrossum', 'farcat', 'lukasz.langa', 'serhiy.storchaka', 'JelleZijlstra', 'pablogsal', 'miss-islington', 'uriyyo', 'BvB93', 'kj', 'lars2']
pr_nums = ['27237', '27246', '27614', '27632', '27710', '27815', '27841', '27861', '27871', '27950']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44524'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by AlexWaygood** [comment]
Is there anything left to do here, or can this now be closed?
