### ISSUE TITLE
Document PGO in devguide

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#88703]
BPO | [44537](https://bugs.python.org/issue44537)
--- | :---
Nosy | @gvanrossum

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-29.23:35:17.230>
labels = ['3.11', 'docs']
title = 'Document PGO in devguide'
updated_at = <Date 2021-06-29.23:56:45.021>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-29.23:56:45.021>
actor = 'gvanrossum'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-06-29.23:35:17.230>
creator = 'gvanrossum'
dependencies = []
files = []
hgrepos = []
issue_num = 44537
keywords = []
message_count = 2.0
messages = ['396764', '396766']
nosy_count = 2.0
nosy_names = ['gvanrossum', 'docs@python']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44537'
versions = ['Python 3.11']
```

</p></details>

**Comment by gvanrossum** [comment]
@corona10 Can you check if this is still undocumented? If not maybe we can just close it.

**Comment by corona10** [comment]
> @corona10 Can you check if this is still undocumented? If not maybe we can just close it.

Well, still undocumented, but I will assign the issue to myself, 
FYI, I am preparing the CPython Sprint at PyCon KR this year,
It could be a good first issue for the mentees.

https://2023.pycon.kr/sprint
Not registered yet, but I sent a  request form yesterday.

**Comment by corona10** [comment]
@KilJaeun Would you like to take a look?

**Comment by KilJaeeun** [comment]
!

**Comment by corona10** [comment]
The PR is merged, Thank you @KilJaeeun :)
cc @gvanrossum
