### ISSUE TITLE
Enum: revert to 3.9

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#88725]
BPO | [44559](https://bugs.python.org/issue44559)
--- | :---
Nosy | @Yhg1s, @warsaw, @brettcannon, @pitrou, @ethanfurman, @willingc, @pablogsal
PRs | <li>python/cpython#27010</li><li>python/cpython#27099</li><li>python/cpython#27388</li><li>python/cpython#29114</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2021-11-13.19:06:16.033>
created_at = <Date 2021-07-04.01:48:24.713>
labels = ['library', '3.10', 'release-blocker']
title = 'Enum: revert to 3.9'
updated_at = <Date 2021-11-13.19:06:16.032>
user = 'https://github.com/ethanfurman'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-13.19:06:16.032>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2021-11-13.19:06:16.033>
closer = 'ethan.furman'
components = ['Library (Lib)']
creation = <Date 2021-07-04.01:48:24.713>
creator = 'ethan.furman'
dependencies = []
files = []
hgrepos = []
issue_num = 44559
keywords = ['patch']
message_count = 6.0
messages = ['396935', '396937', '398303', '403863', '403876', '404563']
nosy_count = 8.0
nosy_names = ['twouters', 'barry', 'brett.cannon', 'pitrou', 'ethan.furman', 'python-dev', 'willingc', 'pablogsal']
pr_nums = ['27010', '27099', '27388', '29114']
priority = 'release blocker'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44559'
versions = ['Python 3.10']
```

</p></details>

**Comment by AdamWill** [comment]
Hi folks! So I'm a bit confused here. As I've followed the story so far, @ethanfurman made some major changes to Enum in the 3.10 timeframe, e.g. https://github.com/python/cpython/pull/24215 . There was some opposition to this and the decision in this ticket was that the changes should be reverted for 3.10, and "a PEP be written for Python 3.11" - implicitly, a PEP covering the changes.

It does seem like a [PEP was written](https://peps.python.org/pep-0663/), and it was [rejected](https://groups.google.com/g/dev-python/c/D4lejxQXUbg). That, to me, implies the changes should not be in 3.11, right? But they are. The reversion was only ever done on the 3.10 branch. It was not done on the 3.11 branch. https://github.com/python/cpython/pull/24215 and related changes are present in 3.11, but they are not mentioned at all in the [changes doc](https://docs.python.org/3.11/whatsnew/3.11.html).

Is this intended, or is the SC's expectation that in rejecting the PEP, the changes that were reverted in 3.10 should also be reverted in 3.11 and future releases?

Thanks!

**Comment by AdamWill** [comment]
Ah, never mind, I found https://github.com/python/cpython/issues/91041 . I was looking at the 3.11.0b3 release tag so I was a bit out of date, I see the activity on main now.
