### ISSUE TITLE
Create frame objects lazily when needed

### ISSUE THREAD

**Issue by markshannon** [python/cpython#88756]
BPO | [44590](https://bugs.python.org/issue44590)
--- | :---
Nosy | @gvanrossum, @ncoghlan, @vstinner, @markshannon, @pablogsal
PRs | <li>python/cpython#27077</li><li>python/cpython#27525</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/markshannon'
closed_at = <Date 2021-07-29.10:31:08.811>
created_at = <Date 2021-07-09.10:53:40.343>
labels = ['interpreter-core', '3.11', 'performance']
title = 'Create frame objects lazily when needed'
updated_at = <Date 2022-02-23.15:14:23.151>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-23.15:14:23.151>
actor = 'vstinner'
assignee = 'Mark.Shannon'
closed = True
closed_date = <Date 2021-07-29.10:31:08.811>
closer = 'Mark.Shannon'
components = ['Interpreter Core']
creation = <Date 2021-07-09.10:53:40.343>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 44590
keywords = ['patch']
message_count = 4.0
messages = ['397196', '398220', '398696', '413798']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'ncoghlan', 'vstinner', 'Mark.Shannon', 'pablogsal']
pr_nums = ['27077', '27525']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue44590'
versions = ['Python 3.11']
```

</p></details>

**Comment by vstinner** [comment]
The last time this API changed, I documented it here: https://docs.python.org/dev/whatsnew/3.9.html#id2

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by vstinner** [comment]
The documentation was updated by the commit 5974827c71d884bb3cc58f07a9eaefafe0cbaa6e: https://docs.python.org/dev/c-api/init.html#c._PyFrameEvalFunction

I close the issue.
