### ISSUE TITLE
REPL: exit when the user types exit instead of asking them to explicitly type exit()

### ISSUE THREAD

**Issue by 7331ceeb-1e7b-4771-8136-c50c3f139163** [python/cpython#88769]
BPO | [44603](https://bugs.python.org/issue44603)
--- | :---
Nosy | @terryjreedy, @gpshead, @merwok, @stevendaprano, @eryksun, @vedgar, @pganssle, @pablogsal, @asmeurer, @FFY00, @theacodes, @jdevries3133, @tlalexander, @DiddiLeija
PRs | <li>python/cpython#27096</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-12.03:15:45.559>
labels = ['type-feature', 'library', '3.11']
title = 'REPL: exit when the user types exit instead of asking them to explicitly type exit()'
updated_at = <Date 2021-10-07.08:08:05.232>
user = 'https://github.com/theacodes'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-07.08:08:05.232>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-12.03:15:45.559>
creator = 'theacodes'
dependencies = []
files = []
hgrepos = []
issue_num = 44603
keywords = ['patch']
message_count = 55.0
messages = ['397273', '397275', '397276', '397293', '397294', '397296', '397297', '397301', '397302', '397305', '397306', '397307', '397308', '397309', '397310', '397311', '397313', '397314', '397315', '397316', '397317', '397331', '397334', '397372', '397373', '397374', '397377', '397379', '397382', '397403', '397404', '397422', '397425', '397427', '397458', '397461', '397462', '397505', '397507', '397512', '397516', '397685', '397691', '397698', '397699', '402590', '402605', '402620', '402623', '402644', '402655', '402664', '402667', '402701', '403359']
nosy_count = 14.0
nosy_names = ['terry.reedy', 'gregory.p.smith', 'eric.araujo', 'steven.daprano', 'eryksun', 'veky', 'p-ganssle', 'pablogsal', 'asmeurer', 'FFY00', 'theacodes', 'jack__d', 'tlalexander', 'DiddiLeija']
pr_nums = ['27096']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44603'
versions = ['Python 3.11']
```

</p></details>

**Comment by terryjreedy** [comment]
If 'help' were replaced with 'help()', then the message displayed with the latter should note the help(object) alternative at the beginning, and not just when exiting, as well as how to exit at the `help>` prompt - enter a blank line.  Additional oddity:
`help>exit` displays `Help on Quitter in module _sitebuiltins object:` and several more lines.
`help>quit` exits.  Confusing.

There have been other proposals to exceptionally not require ()s to call a function -- all so far rejected.  I largely agree with Steven about the virtue of consistency.

Any wider discussion, which I agree would be needed for approval, should now go to the Ideas section of discuss.python.org instead of python-dev.

**Comment by merwok** [comment]
Interactive pydoc uses a custom helper (maybe it’s older than `cmd.Cmd`) that doesn’t check for `exit` (which makes sense to me, it’s not a common keyword for little REPLs).  This can be changed easily here to avoid displaying the help for the site built-in `exit`: https://github.com/python/cpython/blob/main/Lib/pydoc.py#L2029

**Comment by pablogsal** [comment]
This will be handled as part of the work in  https://github.com/python/cpython/issues/111201

**Comment by erlend-aasland** [comment]
> This will be handled as part of the work in #111201

Great; let's close this as superseded :)
