### ISSUE TITLE
Teleport method for turtle class

### ISSUE THREAD

**Issue by 485593c8-315f-4961-9e7b-e284f7b2df60** [python/cpython#88773]
BPO | [44607](https://bugs.python.org/issue44607)
--- | :---
Nosy | @serhiy-storchaka, @vedgar, @begilbert-sys

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-12.06:48:56.540>
labels = ['type-feature', 'expert-tkinter', '3.11']
title = 'Teleport method for turtle class'
updated_at = <Date 2021-07-12.17:42:12.710>
user = 'https://github.com/begilbert-sys'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-12.17:42:12.710>
actor = 'Muffinlicious'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tkinter']
creation = <Date 2021-07-12.06:48:56.540>
creator = 'Muffinlicious'
dependencies = []
files = []
hgrepos = []
issue_num = 44607
keywords = []
message_count = 4.0
messages = ['397286', '397292', '397303', '397341']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'veky', 'Muffinlicious']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44607'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103974

**Comment by liam-gersten** [comment]
Hello, my name is Liam, and I’m part of a student software engineer group of 4 at Carnegie Mellon. We’ve been tasked with contributing to an open source project, and this issue seems like a great first start. Would you mind assigning this to me (my group)? Also, you might see the same comment on 1-2 other issues, since we’ll likely be working on more than just one for our assignment.

**Comment by gpshead** [comment]
FWIW I agree that a `teleport` is a useful feature addition.

Some existing other Turtle teleport references:
  * https://weinman.cs.grinnell.edu/courses/CSC151/2014F/labs/turtle-graphics-lab.html - a Scheme or LISP looking thing containing `!turtle-teleport` to x y coordinates.
  * https://wiki.ros.org/turtlesim#Services Robot Operating System (ROS) has a `teleport-absolute` and `teleport-relative` in its `turtlesim`. which takes an x y and theta angle.  why it takes an angle isn't clear (i suppose to declare the new orientation); that isn't something i'd copy.

`teleport` is mirroring the existing goto/setpos/setposition absolute cartesian positioning API, but with more convenient semantics. A polar coordinate system teleport would be a different api and is out of scope for this feature request.

i'm reviewing the PR.

**Comment by gpshead** [comment]
Thanks for your contribution Liam, merged.  We don't often touch the turtle module as it's a bit of a leftover thing that we keep in the standard library because of its usefulness in educational settings, but this feature addition made sense.
