### ISSUE TITLE
Script name for venv PowerShell activate

### ISSUE THREAD

**Issue by 86adf977-f216-4295-bda1-0f1e4092493f** [python/cpython#88790]
BPO | [44624](https://bugs.python.org/issue44624)
--- | :---
Nosy | @pfmoore, @vsajip, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-13.15:04:11.634>
labels = ['type-feature', 'library']
title = 'Script name for venv PowerShell activate'
updated_at = <Date 2021-07-19.13:38:03.531>
user = 'https://bugs.python.org/pwatson'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-19.13:38:03.531>
actor = 'vinay.sajip'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-13.15:04:11.634>
creator = 'pwatson'
dependencies = []
files = []
hgrepos = []
issue_num = 44624
keywords = []
message_count = 2.0
messages = ['397416', '397796']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vinay.sajip', 'tim.golden', 'zach.ware', 'steve.dower', 'pwatson']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44624'
versions = []
```

</p></details>

**Comment by derek-keeler** [comment]
I full agree with the sentiment of (1) @vsajip ... and I feel that it _is_ a Python driven norm rather than a PowerShell one in this instance.

For further insight into the question, @pwatson has a point in that 'canonical' PowerShell cmdlets follow a naming pattern of `Noun-Verb`. The language has a built-in `Get-Verb` that drives that home.
