### ISSUE TITLE
zipfile.ZipFile is closed when zipfile.Path is closed

### ISSUE THREAD

**Issue by 98a8dad2-4075-4d79-bfe0-b335321d92f1** [python/cpython#88804]
BPO | [44638](https://bugs.python.org/issue44638)
--- | :---
Nosy | @jaraco, @miss-islington, @tirkarthi, @jdevries3133, @christian-steinmeyer
PRs | <li>python/cpython#27188</li>
Superseder | <li>bpo-40564: Using zipfile.Path with several files prematurely closes zip</li>
Files | <li>[zipfile.zip](https://bugs.python.org/file50150/zipfile.zip "Uploaded as application/zip at 2021-07-14.14:48:27 by @christian-steinmeyer")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-16.01:12:12.249>
created_at = <Date 2021-07-14.14:48:27.833>
labels = ['3.8', 'type-bug', 'library']
title = 'zipfile.ZipFile is closed when zipfile.Path is closed'
updated_at = <Date 2021-07-16.13:15:04.558>
user = 'https://github.com/christian-steinmeyer'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-16.13:15:04.558>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-16.01:12:12.249>
closer = 'jaraco'
components = ['Library (Lib)']
creation = <Date 2021-07-14.14:48:27.833>
creator = 'christian.steinmeyer'
dependencies = []
files = ['50150']
hgrepos = []
issue_num = 44638
keywords = []
message_count = 13.0
messages = ['397483', '397485', '397520', '397524', '397590', '397591', '397592', '397593', '397594', '397595', '397596', '397601', '397620']
nosy_count = 5.0
nosy_names = ['jaraco', 'miss-islington', 'xtreak', 'jack__d', 'christian.steinmeyer']
pr_nums = ['27188']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '40564'
type = 'behavior'
url = 'https://bugs.python.org/issue44638'
versions = ['Python 3.8']
```

</p></details>

**Comment by smheidrich** [comment]
If a backport isn't desired (as mentioned in https://github.com/python/cpython/issues/84744#issuecomment-1093871456), would it at least be possible to put a note about this bug into the `zipfile.Path` docs of Python versions < 3.10? Would've saved me a couple of hours just now and I'm probably not the only one :-)
