### ISSUE TITLE
Inspect.getsource raises wrong error on classes in interactive session

### ISSUE THREAD

**Issue by akulakov** [python/cpython#88814]
BPO | [44648](https://bugs.python.org/issue44648)
--- | :---
Nosy | @jaraco, @aroberge, @ambv, @pablogsal, @miss-islington, @FFY00, @akulakov
PRs | <li>python/cpython#27171</li><li>python/cpython#27495</li><li>python/cpython#27484</li><li>python/cpython#27436</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-30.17:47:14.167>
created_at = <Date 2021-07-15.18:31:38.611>
labels = ['type-bug', '3.10', '3.11']
title = 'Inspect.getsource raises wrong error on classes in interactive session'
updated_at = <Date 2021-08-02.09:59:39.832>
user = 'https://github.com/akulakov'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-02.09:59:39.832>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-30.17:47:14.167>
closer = 'lukasz.langa'
components = []
creation = <Date 2021-07-15.18:31:38.611>
creator = 'andrei.avk'
dependencies = []
files = []
hgrepos = []
issue_num = 44648
keywords = ['patch']
message_count = 11.0
messages = ['397573', '397629', '397631', '397634', '397636', '398579', '398580', '398588', '398589', '398590', '398748']
nosy_count = 8.0
nosy_names = ['jaraco', 'aroberge', 'lukasz.langa', 'pablogsal', 'miss-islington', 'FFY00', 'andrei.avk', 'othmaneelbouri1']
pr_nums = ['27171', '27495', '27484', '27436']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44648'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I am not sure that OSError was a correct exception. Before this, the only exception raised by `inspect.getfile()` and `inspect.getsourcefile()` was TypeError. In particularly this change cause an issue in doctests (#113329).

Even if this change is correct, it should be documented, have `versionchanged` directives and a What's New entry. But maybe changing it to TypeError is better in long term.
