### ISSUE TITLE
dataclasses should allow frozendict default value

### ISSUE THREAD

**Issue by d47dda9b-0dbd-4994-989e-b8f6a5a56085** [python/cpython#88840]
BPO | [44674](https://bugs.python.org/issue44674)
--- | :---
Nosy | @rhettinger, @ericvsmith, @CCLDArjun
PRs | <li>python/cpython#29867</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = <Date 2021-12-11.21:13:04.100>
created_at = <Date 2021-07-19.14:06:32.276>
labels = ['type-bug', 'library', '3.9']
title = 'dataclasses should allow frozendict default value'
updated_at = <Date 2021-12-12.09:27:52.990>
user = 'https://bugs.python.org/gianni'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-12.09:27:52.990>
actor = 'eric.smith'
assignee = 'eric.smith'
closed = True
closed_date = <Date 2021-12-11.21:13:04.100>
closer = 'eric.smith'
components = ['Library (Lib)']
creation = <Date 2021-07-19.14:06:32.276>
creator = 'gianni'
dependencies = []
files = []
hgrepos = []
issue_num = 44674
keywords = ['patch']
message_count = 10.0
messages = ['397799', '397800', '398098', '398105', '398118', '403103', '403108', '408335', '408365', '408370']
nosy_count = 4.0
nosy_names = ['rhettinger', 'eric.smith', 'CCLDArjun', 'gianni']
pr_nums = ['29867']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44674'
versions = ['Python 3.9']
```

</p></details>

**Comment by carlosgmartin** [comment]
> Consider using non-hashability as a proxy indicator for immutability.

> Unhashability is used to approximate mutability.

Is there a more precise alternative? For example, [JAX](https://github.com/google/jax) arrays are immutable but [unhashable](https://github.com/google/jax/issues/4572#issuecomment-1761560591). The current mutability "check" causes errors like [these](https://github.com/sotetsuk/pgx/issues/1062) (and the ones linked above).

**Comment by carlosgmartin** [comment]
At least, perhaps the error message could be changed to say

>**unhashable** default X for field Y is not allowed: use default_factory

since that's what's actually being checked, to avoid confusion?
