### ISSUE TITLE
Feature request: maxtasksperchild for ProcessPoolExecutor

### ISSUE THREAD

**Issue by 06547701-06a2-4e4a-b672-16a33475101e** [python/cpython#88896]
BPO | [44733](https://bugs.python.org/issue44733)
--- | :---
Nosy | @gpshead, @pitrou, @cool-RR, @loganasherjones
PRs | <li>python/cpython#27373</li><li>python/cpython#32187</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = None
created_at = <Date 2021-07-24.12:14:41.532>
labels = ['type-feature', 'library', '3.11']
title = 'Feature request: maxtasksperchild for ProcessPoolExecutor'
updated_at = <Date 2022-03-31.00:07:58.887>
user = 'https://github.com/cool-RR'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-31.00:07:58.887>
actor = 'loganasherjones'
assignee = 'gregory.p.smith'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-24.12:14:41.532>
creator = 'cool-RR'
dependencies = []
files = []
hgrepos = []
issue_num = 44733
keywords = ['patch']
message_count = 13.0
messages = ['398143', '398240', '398243', '406689', '411449', '411450', '411452', '411471', '411546', '411547', '416310', '416314', '416406']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'pitrou', 'cool-RR', 'loganasherjones']
pr_nums = ['27373', '32187']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44733'
versions = ['Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
your PR was https://github.com/python/cpython/pull/32187 and an equivalent ultimately landed in https://github.com/python/cpython/commit/fa4f0a134e7911b2494ea9866c8a49ff446f9d6c if i'm untangling things correctly.  So this can be closed again.  max_tasks_per_child made it into 3.11beta1.
