### ISSUE TITLE
Tab completion executes @property getter function

### ISSUE THREAD

**Issue by c8adc0d9-ae8d-49da-9f5b-d3b3ef213e90** [python/cpython#88915]
BPO | [44752](https://bugs.python.org/issue44752)
--- | :---
Nosy | @ambv, @miss-islington, @jdevries3133
PRs | <li>python/cpython#27401</li><li>python/cpython#27433</li><li>python/cpython#27444</li><li>python/cpython#27445</li><li>python/cpython#27446</li><li>python/cpython#27447</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-29.15:48:38.581>
created_at = <Date 2021-07-27.21:41:47.767>
labels = ['interpreter-core', 'type-bug', '3.9', '3.10', '3.11']
title = 'Tab completion executes @property getter function'
updated_at = <Date 2021-07-29.15:48:38.575>
user = 'https://bugs.python.org/RPecor'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-29.15:48:38.575>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-29.15:48:38.581>
closer = 'lukasz.langa'
components = ['Interpreter Core']
creation = <Date 2021-07-27.21:41:47.767>
creator = 'RPecor'
dependencies = []
files = []
hgrepos = []
issue_num = 44752
keywords = ['patch']
message_count = 14.0
messages = ['398323', '398324', '398327', '398330', '398331', '398341', '398343', '398479', '398483', '398485', '398486', '398490', '398491', '398492']
nosy_count = 4.0
nosy_names = ['lukasz.langa', 'miss-islington', 'jack__d', 'RPecor']
pr_nums = ['27401', '27433', '27444', '27445', '27446', '27447']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44752'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by LeonarddeR** [comment]
I'm not sure whether this solution is complete yet. It is nice that property descriptors are now excluded, but users can easily add their own descriptors and if the getter on that descriptors raise an exception, the exception is no longer caught.
Ideally we'd have an abstract class for descriptors so we cann filter out all the descriptor stuff.
