### ISSUE TITLE
.popitem() is inconsistent in collections and collections.abc

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#88913]
BPO | [44750](https://bugs.python.org/issue44750)
--- | :---
Nosy | @rhettinger, @AlexWaygood
Files | <li>[collections popitem weirdness.py](https://bugs.python.org/file50187/collections%20popitem%20weirdness.py "Uploaded as text/plain at 2021-07-27.17:35:27 by @AlexWaygood"): Short script demonstrating unexpected behaviour of `.popitem()` in `collections` and `collections.abc` modules</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2021-07-27.20:43:16.677>
created_at = <Date 2021-07-27.17:35:28.063>
labels = ['invalid', 'type-bug', 'library', '3.9']
title = '.popitem() is inconsistent in collections and collections.abc'
updated_at = <Date 2021-07-27.21:20:00.022>
user = 'https://github.com/AlexWaygood'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-27.21:20:00.022>
actor = 'AlexWaygood'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2021-07-27.20:43:16.677>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2021-07-27.17:35:28.063>
creator = 'AlexWaygood'
dependencies = []
files = ['50187']
hgrepos = []
issue_num = 44750
keywords = []
message_count = 3.0
messages = ['398310', '398317', '398319']
nosy_count = 3.0
nosy_names = ['rhettinger', 'stutzbach', 'AlexWaygood']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44750'
versions = ['Python 3.9']
```

</p></details>

**Comment by Shapedsundew9** [comment]
Having just spent sometime figuring this out I second the call for a note in the documentation because the (incorrect) intuition is to expect builtin dict-like behaviour.
