### ISSUE TITLE
Misspelled Word In Docs

### ISSUE THREAD

**Issue by ebd70e4b-233b-45fb-b25c-75eafe12e31a** [python/cpython#88928]
BPO | [44765](https://bugs.python.org/issue44765)
--- | :---
Nosy | @terryjreedy, @ambv, @zware, @miss-islington, @pavel-lexyr
PRs | <li>python/cpython#27430</li><li>python/cpython#27450</li><li>python/cpython#27451</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-29.17:23:52.778>
created_at = <Date 2021-07-28.17:55:24.720>
labels = ['easy', '3.11', '3.9', '3.10', 'docs']
title = 'Misspelled Word In Docs'
updated_at = <Date 2021-08-09.02:23:03.845>
user = 'https://bugs.python.org/khokhareesahome'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-09.02:23:03.845>
actor = 'khokhareesa.home'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-07-29.17:23:52.778>
closer = 'lukasz.langa'
components = ['Documentation']
creation = <Date 2021-07-28.17:55:24.720>
creator = 'khokhareesa.home'
dependencies = []
files = []
hgrepos = []
issue_num = 44765
keywords = ['patch', 'easy', 'newcomer friendly']
message_count = 13.0
messages = ['398410', '398415', '398449', '398500', '398502', '398503', '398504', '398505', '398506', '398507', '398508', '398666', '399246']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'docs@python', 'lukasz.langa', 'zach.ware', 'miss-islington', 'khokhareesa.home', 'pavel-lexyr']
pr_nums = ['27430', '27450', '27451']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue44765'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by CuriousCodingCanadian** [comment]
Is it possible to have this thread removed, or at the very least mannequin renamed? I made this issue and these comments years ago, and I don't like the unprofessionalism appearing when I search for my email address 

It could also be detrimental in terms of getting a job.

**Comment by hugovk** [comment]
Hi there!

I don't see any unprofessionalism here, rather enthusiasm in contributing to CPython, and we appreciate your contribution!

I'm not sure if we can delete the thread or if it's possible to rename mannequins. We can probably edit out the gmail address from the comments, if that helps?

**Comment by AlexWaygood** [comment]
I believe it is possible for repository admins to delete issues entirely. But I agree with @hugovk that there's nothing to be ashamed of here @CuriousCodingCanadian, and I doubt there's anything that would hurt your employment prospects. I think it reflects well on you that you were enthusiastic about contributing to CPython!

From the perspective of preserving the historical record, I'd rather we didn't delete the issue (even if it is just about a typo), but I'd also be okay with editing out your email address from messages in the issue thread, if that's what you'd prefer :-)

**Comment by CuriousCodingCanadian** [comment]
Ah, thanks so much @hugovk and @AlexWaygood for the new perspective! I've thought about this a bit over the past couple days, and I realize that this historical record and my email address being here is, in fact very much a good thing. 

As for editing it out, I don't think that's necessary and would rather have it stay here (for both the sake of historical record and as having contributing even a small thing to the CPython docs being something I can verifiably add to my portfolio).

Best regards,
Eesa
