### ISSUE TITLE
Incorrect message: "Invalid decimal literal" (python 3.10)

### ISSUE THREAD

**Issue by f2044c74-2589-491b-aea5-3f64941d4a9c** [python/cpython#88943]
BPO | [44780](https://bugs.python.org/issue44780)
--- | :---
Nosy | @aroberge, @serhiy-storchaka, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-30.14:52:34.235>
labels = ['3.10', '3.11']
title = 'Incorrect message: "Invalid decimal literal" (python 3.10)'
updated_at = <Date 2021-12-26.17:01:19.886>
user = 'https://github.com/aroberge'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-26.17:01:19.886>
actor = 'aroberge'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-07-30.14:52:34.235>
creator = 'aroberge'
dependencies = []
files = []
hgrepos = []
issue_num = 44780
keywords = []
message_count = 4.0
messages = ['398556', '398595', '398597', '409212']
nosy_count = 3.0
nosy_names = ['aroberge', 'serhiy.storchaka', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44780'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-109081
* gh-109090
* gh-109091

**Comment by CC-Kitten** [comment]
another case -
item1_quantity was working just fine assigned as int(input()) and input()
now all of a sudden it is not working correctly

item1_name = input('Enter food item name:\n')

item1_price = float(input('Enter item price:\n'))

item1_quantity = int(input('Enter item quantity:\n'))


item2_name = input('Enter second food item name:\n')

item2_price = float(input('Enter second item price:\n'))

item2_quantity = input('Enter second item quantity:\n')

#assigning variable for calculations of item1 and item2

item1_total = item1_quantity * item1_price
item2_total = item2_quantity * item2_price

#began with print statement of receipt header
print('________________Receipt________________')
print('')
#creating print statements with f strings
#to display name and quantity/price of item(s) 1 & 2 equaling total price of each item

print(f'{item1_quantity} {item1_name} @ ${item1_price.2f} = ${item1_total:.2f}')
print(f'{item2_quantity} {item2_name} @ ${item2_price.2f} = ${item2_total:.2f}\n')

**Comment by serhiy-storchaka** [comment]
@CC-Kitten, I do not see how your problem is related to this issue. Please open a new issue. Also, it would help if you explain how it "is not working correctly": what is the difference in the behavior between different Python versions, what exactly versions.
