### ISSUE TITLE
Improve some sqlite3 errors

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#89022]
BPO | [44859](https://bugs.python.org/issue44859)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @JelleZijlstra, @erlend-aasland
PRs | <li>python/cpython#27654</li><li>python/cpython#27695</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-07.14:14:16.688>
labels = ['extension-modules', '3.11']
title = 'Improve some sqlite3 errors'
updated_at = <Date 2022-03-17.05:58:28.684>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-17.05:58:28.684>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-08-07.14:14:16.688>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 44859
keywords = ['patch']
message_count = 8.0
messages = ['399183', '399185', '399187', '399211', '399241', '399289', '399441', '415388']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'JelleZijlstra', 'erlendaasland']
pr_nums = ['27654', '27695']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44859'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
The following PRs have improved this issue:

- gh-27654
- gh-91571
- gh-91572
- gh-27695

Suggesting to close this. If other inconsistencies are discovered, we can open a new issue.

**Comment by erlend-aasland** [comment]
There is one inconsistency remaining:

`sqlite3.Cursor.execute` raise `sqlite3.Warning` instead of `sqlite3.ProgrammingError` if multiple SQL statements are supplied. IMO, we should fix this.
