### ISSUE TITLE
Python > 3.7 build fails with IBM XL compiler

### ISSUE THREAD

**Issue by 0612edca-49f0-47c0-a889-348b5584c3e5** [python/cpython#89040]
BPO | [44877](https://bugs.python.org/issue44877)
--- | :---
Nosy | @ericvsmith, @jdevries3133, @quellyn
Files | <li>[cpython.tar.gz](https://bugs.python.org/file50207/cpython.tar.gz "Uploaded as application/x-gzip at 2021-08-09.23:37:13 by @quellyn"): Tarball of output logs from configure and make</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-09.23:37:13.883>
labels = ['3.7', 'expert-installation', '3.9', '3.10', '3.11', '3.8', 'build']
title = 'Python > 3.7 build fails with IBM XL compiler'
updated_at = <Date 2021-08-10.20:42:01.719>
user = 'https://github.com/quellyn'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-10.20:42:01.719>
actor = 'quellyn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2021-08-09.23:37:13.883>
creator = 'quellyn'
dependencies = []
files = ['50207']
hgrepos = []
issue_num = 44877
keywords = []
message_count = 9.0
messages = ['399296', '399307', '399335', '399349', '399350', '399351', '399352', '399353', '399355']
nosy_count = 3.0
nosy_names = ['eric.smith', 'jack__d', 'quellyn']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue44877'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by quellyn** [comment]
Has anyone had a chance to look at the trace I provided yet? Thanks!

**Comment by AA-Turner** [comment]
PowerPC is a supported platform under PEP-11, but it seems only for gcc/clang. The buildbots also seem to have been failing recently due to not being able to check out CPython from git (e.g. https://buildbot.python.org/all/#/builders/90/builds/1716) -- @vstinner / @encukou is this a known issue? (buildmaster-config doesn't have any bug reports for this it seems)

A

**Comment by vstinner** [comment]
I don't know nor support IBM XL compiler. PEP 11 only supports GCC and clang for PowerPC.

**Comment by quellyn** [comment]
Thanks for confirming, @vstinner. I'll close this.
