### ISSUE TITLE
ssl.OP_LEGACY_SERVER_CONNECT missing

### ISSUE THREAD

**Issue by 17206da1-5354-4e07-8a3a-1e959c91eee7** [python/cpython#89051]
BPO | [44888](https://bugs.python.org/issue44888)
--- | :---
Nosy | @tiran, @xtkoba
PRs | <li>python/cpython#27776</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2021-08-11.11:35:40.075>
labels = ['expert-SSL']
title = 'ssl.OP_LEGACY_SERVER_CONNECT missing'
updated_at = <Date 2021-08-16.03:58:50.811>
user = 'https://github.com/xtkoba'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-16.03:58:50.811>
actor = 'python-dev'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2021-08-11.11:35:40.075>
creator = 'xtkoba'
dependencies = []
files = []
hgrepos = []
issue_num = 44888
keywords = ['patch']
message_count = 1.0
messages = ['399386']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'python-dev', 'xtkoba']
pr_nums = ['27776']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44888'
versions = []
```

</p></details>

### Linked PRs
* gh-93927
* gh-100359
* gh-100360

**Comment by tiran** [comment]
@graingert Do you want to backport the change to 3.11 and 3.10?

**Comment by graingert** [comment]
> @graingert Do you want to backport the change to 3.11 and 3.10?

I'd like the backport in 3.10 and I hope the patch will apply automatically

**Comment by tiran** [comment]
> I'd like the backport in 3.10 and I hope the patch will apply automatically

You have to manually backport the patch to 3.11 and 3.11 to adjust the `versionadded` field.

**Comment by graingert** [comment]
oh right so it should be `versionadded: 3.10.6, 3.11` in the original PR?

**Comment by tiran** [comment]
The original PR should have 3.11 and the backport to 3.10 needs to have 3.10.7. AFAIK versionadded does only support one argument.

**Comment by graingert** [comment]
Hmm but then users reading the 3.11 docs will see the wrong versionadded

cc @hugovk

**Comment by hugovk** [comment]
So was it added in 3.11 and backported to 3.10.6?

Can it be `.. versionadded:: 3.10.6` for both?

Otherwise, https://devguide.python.org/documentation/markup/?highlight=versionadded#paragraph-level-markup says of `versionadded`:

> The first argument must be given and is the version in question. The second argument is optional and can be used to describe the details of the feature.

For example:

* `.. versionadded:: 3.9 backported to 3.7 and 3.8.`
  https://docs.python.org/3/library/decimal.html#decimal.HAVE_CONTEXTVAR
* `.. versionadded:: 3.9 (the field exists since 3.8 but it's only used since 3.9)`
  https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall

**Comment by hugovk** [comment]
I've merged https://github.com/python/cpython/pull/93927 with:

* `.. versionadded:: 3.12` in 3.12/main

And let's go for:

* `.. versionadded:: 3.10.10` in 3.10
* `.. versionadded:: 3.11.2` in 3.11

@graingert Please could you make the 3.10 and 3.11 backport PRs?

**Comment by hugovk** [comment]
Actually, let's try using Miss Islington and then modify those PRs.

**Comment by hugovk** [comment]
Miss Islington didn't like the merge conflicts, back to the command line. Please see PRs https://github.com/python/cpython/pull/100359 and https://github.com/python/cpython/pull/100360.

**Comment by hugovk** [comment]
I closed the backports, as we don't normally backport new features to bugfix branches.

https://devguide.python.org/versions/

This will be in the next 3.12.0 alpha 4, due on 2023-01-09.
