### ISSUE TITLE
Classmethod properties are erroneously "called" in multiple modules

### ISSUE THREAD

**Issue by 6a8a58f8-1b72-4437-8fa4-43ec64b2fdf0** [python/cpython#89067]
BPO | [44904](https://bugs.python.org/issue44904)
--- | :---
Nosy | @tim-one, @rhettinger, @serhiy-storchaka, @miss-islington, @AlexWaygood
PRs | <li>python/cpython#28838</li><li>python/cpython#29261</li><li>python/cpython#29262</li>
Superseder | <li>bpo-45356: Calling `help` executes @classmethod @property decorated methods</li>
Files | <li>[bug_report.py](https://bugs.python.org/file50212/bug_report.py "Uploaded as text/plain at 2021-08-12.21:16:40 by rzepecki.t"): Example of the issue</li><li>[classmethod_properties_bug.py](https://bugs.python.org/file50218/classmethod_properties_bug.py "Uploaded as text/plain at 2021-08-15.15:13:33 by @AlexWaygood"): Short  script demonstrating how a bug relating to classmethod properties causes doctest.py to crash</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-10.22:18:34.456>
created_at = <Date 2021-08-12.21:16:41.103>
labels = ['type-bug', '3.9', '3.10', '3.11']
title = 'Classmethod properties are erroneously "called" in multiple modules'
updated_at = <Date 2021-10-28.08:13:53.897>
user = 'https://bugs.python.org/rzepeckit'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-28.08:13:53.897>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-10.22:18:34.456>
closer = 'rhettinger'
components = []
creation = <Date 2021-08-12.21:16:41.103>
creator = 'rzepecki.t'
dependencies = []
files = ['50212', '50218']
hgrepos = []
issue_num = 44904
keywords = ['patch']
message_count = 6.0
messages = ['399482', '399622', '403612', '405154', '405156', '405157']
nosy_count = 6.0
nosy_names = ['tim.peters', 'rhettinger', 'serhiy.storchaka', 'miss-islington', 'AlexWaygood', 'rzepecki.t']
pr_nums = ['28838', '29261', '29262']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '45356'
type = 'behavior'
url = 'https://bugs.python.org/issue44904'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by SharpEdgeMarshall** [comment]
This is not fixed, you just fixed an issue on doctest module but the issue persist if you create an abstract class property
