### ISSUE TITLE
proposal: add support for regex in Literal type hint

### ISSUE THREAD

**Issue by 71155c7e-83b8-4477-a302-494773704618** [python/cpython#89102]
BPO | [44939](https://bugs.python.org/issue44939)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-17.20:11:12.154>
labels = []
title = 'proposal: add support for regex in Literal type hint'
updated_at = <Date 2021-08-17.20:11:12.154>
user = 'https://bugs.python.org/leonmintz'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-17.20:11:12.154>
actor = 'leon.mintz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-08-17.20:11:12.154>
creator = 'leon.mintz'
dependencies = []
files = []
hgrepos = []
issue_num = 44939
keywords = []
message_count = 1.0
messages = ['399787']
nosy_count = 1.0
nosy_names = ['leon.mintz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44939'
versions = []
```

</p></details>

**Comment by AlexWaygood** [comment]
Proposals like this need substantial discussion, either on [the typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/) or at https://github.com/python/typing/issues, before a CPython issue can be created. If you're able to find substantial support for your proposal in one of those forums, please feel free to open a new CPython issue and/or PR for this feature proposal.

Cc. @leonmintz
