### ISSUE TITLE
macOS build test failure

### ISSUE THREAD

**Issue by 569b5fc7-560b-4c48-8a4c-79589186cccd** [python/cpython#89161]
BPO | [44998](https://bugs.python.org/issue44998)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @mcc-devel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-06.04:21:54.348>
created_at = <Date 2021-08-25.10:09:33.585>
labels = ['OS-mac', 'build', '3.11']
title = 'macOS build test failure'
updated_at = <Date 2021-10-06.04:21:54.347>
user = 'https://github.com/mcc-devel'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-06.04:21:54.347>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-06.04:21:54.348>
closer = 'ned.deily'
components = ['Build', 'macOS']
creation = <Date 2021-08-25.10:09:33.585>
creator = 'jett8998'
dependencies = []
files = []
hgrepos = []
issue_num = 44998
keywords = []
message_count = 2.0
messages = ['400250', '403285']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'jett8998']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue44998'
versions = ['Python 3.11']
```

</p></details>

**Comment by YTKme** [comment]
> > /Library/Developer/CommandLineTools/usr/bin/make build_all_merge_profile
> > /usr/local/bin/llvm-profdata merge -output=code.profclangd *.profclangr
> 
> It looks like your build was trying to use a mixture of llvm tools, probably clang from the Apple-supplied Command Line Tools and llvm from /usr/local/bin, perhaps from some package manager like Homebrew. Use one or the other; we strongly recommend building with, and only test with, the Apple-supplied tool chains from either the most Xcode or Command Line Tools release for each macOS release.

How do you use only the apple-supplied tool chains for the compilation?
