### ISSUE TITLE
More compact range iterator

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#89189]
BPO | [45026](https://bugs.python.org/issue45026)
--- | :---
Nosy | @gvanrossum, @rhettinger, @ambv, @serhiy-storchaka, @sweeneyde
PRs | <li>python/cpython#27986</li><li>python/cpython#28176</li>
Files | <li>[three-way-comparison.log](https://bugs.python.org/file50306/three-way-comparison.log "Uploaded as text/plain at 2021-09-27.14:46:46 by @ambv")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-27.03:03:33.269>
labels = ['interpreter-core', '3.11', 'performance']
title = 'More compact range iterator'
updated_at = <Date 2021-09-27.14:46:46.491>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-27.14:46:46.491>
actor = 'lukasz.langa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-08-27.03:03:33.269>
creator = 'serhiy.storchaka'
dependencies = []
files = ['50306']
hgrepos = []
issue_num = 45026
keywords = ['patch']
message_count = 22.0
messages = ['400390', '400392', '400396', '400399', '400528', '401085', '401411', '401419', '402139', '402335', '402347', '402349', '402452', '402477', '402534', '402543', '402555', '402639', '402649', '402708', '402712', '402724']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'rhettinger', 'lukasz.langa', 'serhiy.storchaka', 'Dennis Sweeney']
pr_nums = ['27986', '28176']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue45026'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
Given the benchmark results, are we abandoning this?

**Comment by serhiy-storchaka** [comment]
The difference of 1% is not significant. You can get larger difference from run to run with the same binary. But for large integers the difference is ~2x. And the difference in the memory and the pickle sizes is not insignificant.

The original code was changed, in particular there is a special path in the eval loop for range iteration, so all benchmarks should be rerun.

It sounds funny, but the small difference in iterating small ranges in #27986 disappeared after applying a simple manual optimization:
```diff
         long result = r->start;
-        r->start += r->step;
+        r->start = result + r->step;
         r->len--;
         return PyLong_FromLong(result);
```
I thought that the compiler is smart enough for this.

**Comment by serhiy-storchaka** [comment]
#27986 is now the same as the baseline in iterating small integers range. #28176 is slightly slower.

```
$ ./python -m pyperf timeit -s 'r = range(10000)' 'for i in r: pass'
Baseline: Mean +- std dev: 59.4 us +- 4.2 us
#27986:   Mean +- std dev: 58.8 us +- 3.4 us
#28176:   Mean +- std dev: 64.7 us +- 4.2 us
```
But it is the fastest in iterating large integers range.
```
$ ./python -m pyperf timeit -s 'r = range(0, 10**20, 3**35)' 'for i in r: pass'
Baseline: Mean +- std dev: 185 us +- 8 us
#27986:   Mean +- std dev: 106 us +- 6 us
#28176:   Mean +- std dev: 78.6 us +- 4.4 us
```

**Comment by gvanrossum** [comment]
I would vote for the faster PR when the values are small -- perf for large ranges is not a priority (these occur too rare and everything else is slower with them as well).

**Comment by serhiy-storchaka** [comment]
I agree. Thank you for review.
