### ISSUE TITLE
Update libffi to 3.4.2

### ISSUE THREAD

**Issue by zooba** [python/cpython#89185]
BPO | [45022](https://bugs.python.org/issue45022)
--- | :---
Nosy | @pfmoore, @tjguk, @ned-deily, @ambv, @zware, @zooba, @pablogsal, @miss-islington, @Ghostkeeper
PRs | <li>python/cpython#27982</li><li>python/cpython#27984</li><li>python/cpython#27985</li><li>python/cpython#28001</li><li>python/cpython#28146</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-09.21:03:07.969>
created_at = <Date 2021-08-26.21:13:17.382>
labels = ['type-bug', '3.9', '3.10', '3.11', 'ctypes', 'build', 'OS-windows']
title = 'Update libffi to 3.4.2'
updated_at = <Date 2021-09-13.14:45:40.034>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-13.14:45:40.034>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2021-09-09.21:03:07.969>
closer = 'steve.dower'
components = ['Build', 'Windows', 'ctypes']
creation = <Date 2021-08-26.21:13:17.382>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 45022
keywords = ['patch']
message_count = 13.0
messages = ['400382', '400383', '400385', '400430', '400431', '400432', '401004', '401012', '401013', '401330', '401518', '401696', '401704']
nosy_count = 9.0
nosy_names = ['paul.moore', 'tim.golden', 'ned.deily', 'lukasz.langa', 'zach.ware', 'steve.dower', 'pablogsal', 'miss-islington', 'Ghostkeeper']
pr_nums = ['27982', '27984', '27985', '28001', '28146']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45022'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by itachaaa** [comment]
It seems that libffi-3.4.2 is not supported by CPython 3.8, 3.9, and 3.10. Will this be considered later, Or wo have to have 3.11 to start supporting 3.4.2？

**Comment by iwannastay** [comment]
> Going to just decide that we won't backport the update. If a big enough security issue is found we can consider it, but it would have to justify the potential-but-unlikely breaking change for users who are relying on the name of the DLL.

Do you mean that the version 3.9 of python dont support version 3.4.x of libffi? 

#118171 

We encountered a coredump with the versions above.
