### ISSUE TITLE
asyncio hang in subprocess wait_closed() on Windows, BrokenPipeError

### ISSUE THREAD

**Issue by 6ff8aeae-3783-4009-ab17-9852311ce88b** [python/cpython#89237]
BPO | [45074](https://bugs.python.org/issue45074)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[wait_closed.py](https://bugs.python.org/file50250/wait_closed.py "Uploaded as text/plain at 2021-09-01.05:10:33 by byllyfish"): demonstrate hang in stream.wait_closed()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-01.05:10:33.552>
labels = ['type-bug', '3.9', '3.10', 'expert-asyncio']
title = 'asyncio hang in subprocess wait_closed() on Windows, BrokenPipeError'
updated_at = <Date 2021-09-01.05:10:33.552>
user = 'https://bugs.python.org/byllyfish'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-01.05:10:33.552>
actor = 'byllyfish'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-09-01.05:10:33.552>
creator = 'byllyfish'
dependencies = []
files = ['50250']
hgrepos = []
issue_num = 45074
keywords = []
message_count = 1.0
messages = ['400810']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'byllyfish']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45074'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
This bug is another instance of `protocol.connection_lost` callback not getting called correctly. With https://github.com/python/cpython/pull/98572 the callback is always called which fixes the issue. 

With fix output:
```
Running Debug|x64 interpreter...
BrokenPipe 1 - correct
BrokenPipe 2 - correct
```
