### ISSUE TITLE
DragonflyBSD fix nis module build

### ISSUE THREAD

**Issue by c9ed70e6-85ba-41dd-8968-859cb0429c8e** [python/cpython#89337]
BPO | [45174](https://bugs.python.org/issue45174)
--- | :---
Nosy | @brettcannon, @ronaldoussoren, @ned-deily, @serhiy-storchaka, @devnexen
PRs | <li>python/cpython#28295</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-11.20:34:59.430>
labels = ['OS-mac', 'build', 'library', '3.11']
title = 'DragonflyBSD fix nis module build'
updated_at = <Date 2021-09-11.22:07:47.967>
user = 'https://github.com/devnexen'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-11.22:07:47.967>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2021-09-11.20:34:59.430>
creator = 'devnexen'
dependencies = []
files = []
hgrepos = []
issue_num = 45174
keywords = []
message_count = 1.0
messages = ['401650']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ronaldoussoren', 'ned.deily', 'serhiy.storchaka', 'devnexen']
pr_nums = ['28295']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue45174'
versions = ['Python 3.11']
```

</p></details>

**Comment by hugovk** [comment]
Note the nis module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
Closing this issue as per @brettcannon's guidance in https://github.com/python/cpython/issues/91217#issuecomment-1095605282, given that `nis` is deprecated.
