### ISSUE TITLE
Add `pop` function to remove context manager from (Async)ExitStack

### ISSUE THREAD

**Issue by c511697a-8950-48a3-9772-22ee5188bd16** [python/cpython#89347]
BPO | [45184](https://bugs.python.org/issue45184)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka, @1st1, @aha79, @vbrozik

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-13.14:40:01.985>
labels = ['3.7', '3.8', '3.9', '3.10', '3.11', 'type-feature', 'library']
title = 'Add `pop` function to remove context manager from (Async)ExitStack'
updated_at = <Date 2022-02-23.15:24:26.636>
user = 'https://github.com/aha79'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-23.15:24:26.636>
actor = 'andreash'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-13.14:40:01.985>
creator = 'andreash'
dependencies = []
files = []
hgrepos = []
issue_num = 45184
keywords = []
message_count = 5.0
messages = ['401703', '401708', '401722', '413477', '413806']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'serhiy.storchaka', 'yselivanov', 'andreash', 'vbrozik']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45184'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
The whole idea of a context manager is that every call to ``__enter__`` is matched with a call to ``__exit__``. To make it possible to change that strikes me as a very bad idea. 

You can always flip an attribute on the context manager to tell it to skip some of the code in ``__exit__`` if that's what you want. You don't need language support for it.

**Comment by iritkatriel** [comment]
I see that I misunderstood your suggestion - you want to remove the context manger from the stack and then run its ``__exit__``. 

This means that you are overlapping the scopes of context managers - currently the scopes of two CMs are either disjoint or one is contained in the other. Changing this is also a bad idea.

**Comment by eddawley** [comment]
@iritkatriel 

`ExitStack` supports pushing onto the stack so it is counterintuitive to not allow popping from the stack. I agree with your comment for _popping arbitrary CMs from the stack_ but that argument fails to resonate for LIFO access. It's quite the odd interface to support mutable pushes but immutable pop_alls.

An example use case that I am currently running into is needing to dynamically open/close files while a set of other files is held open. This is very obviously a stack problem that would not be at odds with your stance on scopes.

**Comment by iritkatriel** [comment]
@eddawley That's a different suggestion so it's best to create a new issue for it rather than discuss it here.
