### ISSUE TITLE
Always use unittest for collecting tests in regrtests

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#89392]
BPO | [45229](https://bugs.python.org/issue45229)
--- | :---
Nosy | @terryjreedy, @ambv, @ambv, @zware, @serhiy-storchaka, @pablogsal, @miss-islington
PRs | <li>python/cpython#28405</li><li>python/cpython#28454</li><li>python/cpython#28455</li><li>python/cpython#28456</li><li>python/cpython#28467</li><li>python/cpython#28468</li><li>python/cpython#28478</li><li>python/cpython#28479</li><li>python/cpython#28615</li><li>python/cpython#28637</li><li>python/cpython#28639</li><li>python/cpython#28645</li><li>python/cpython#28650</li><li>python/cpython#28660</li><li>python/cpython#28666</li><li>python/cpython#28667</li><li>python/cpython#28668</li><li>python/cpython#28927</li><li>python/cpython#28929</li><li>python/cpython#28986</li><li>python/cpython#29004</li><li>python/cpython#29006</li><li>python/cpython#29007</li><li>python/cpython#29095</li><li>python/cpython#29096</li>
Dependencies | <li>bpo-40058: Running test_datetime twice fails with: module &#x27;datetime&#x27; has no attribute &#x27;_divide_and_round&#x27;</li><li>bpo-40173: test.support.import_fresh_module fails to correctly block submodules when fresh is specified</li><li>bpo-45185: test.test_ssl.TestEnumerations is not run</li><li>bpo-45187: Some tests in test_socket are not run</li><li>bpo-45500: Rewrite test_dbm</li><li>bpo-45502: Fix test_shelve and make it discoverable</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2021-09-17.07:31:12.126>
labels = ['type-feature', 'tests', '3.9', '3.10', '3.11']
title = 'Always use unittest for collecting tests in regrtests'
updated_at = <Date 2021-10-20.16:52:45.847>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-20.16:52:45.847>
actor = 'lukasz.langa'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2021-09-17.07:31:12.126>
creator = 'serhiy.storchaka'
dependencies = ['40058', '40173', '45185', '45187', '45500', '45502']
files = []
hgrepos = []
issue_num = 45229
keywords = ['patch']
message_count = 33.0
messages = ['402006', '402009', '402053', '402076', '402154', '402156', '402168', '402195', '402214', '402228', '402245', '402254', '402255', '402903', '402945', '402952', '402953', '402956', '402959', '402974', '402982', '402996', '402999', '403000', '403846', '403853', '403855', '404137', '404142', '404143', '404466', '404495', '404496']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'lukasz.langa', 'lukasz.langa', 'zach.ware', 'serhiy.storchaka', 'pablogsal', 'miss-islington', 'jerrylikerice1s']
pr_nums = ['28405', '28454', '28455', '28456', '28467', '28468', '28478', '28479', '28615', '28637', '28639', '28645', '28650', '28660', '28666', '28667', '28668', '28927', '28929', '28986', '29004', '29006', '29007', '29095', '29096']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45229'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-106209
* gh-106229
* gh-106230
* gh-108859
* gh-108860
* gh-108861
* gh-108868
* gh-108869
* gh-108871
* gh-108872
* gh-108873
* gh-108874
* gh-108875
* gh-108876
* gh-108877
* gh-108897
* gh-108898
* gh-108911
* gh-108913
* gh-108914
* gh-108916
* gh-108919
* gh-108920

**Comment by erlend-aasland** [comment]
Serhiy, can we close this, or is there more work left?

**Comment by serhiy-storchaka** [comment]
`test_decimal` and `test_xml_etree` are left. Work in progress.

**Comment by serhiy-storchaka** [comment]
Finally it has been finished.
