### ISSUE TITLE
Missing support for Source Specific Multicast

### ISSUE THREAD

**Issue by b123482c-7181-432f-bbaf-5bdc38bf9b82** [python/cpython#89415]
BPO | [45252](https://bugs.python.org/issue45252)
--- | :---
Nosy | @ciresnave

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-21.00:26:04.617>
labels = ['type-feature', 'library', '3.11']
title = 'Missing support for Source Specific Multicast'
updated_at = <Date 2021-09-24.23:41:45.383>
user = 'https://github.com/ciresnave'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-24.23:41:45.383>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-21.00:26:04.617>
creator = 'ciresnave'
dependencies = []
files = []
hgrepos = []
issue_num = 45252
keywords = []
message_count = 1.0
messages = ['402283']
nosy_count = 1.0
nosy_names = ['ciresnave']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45252'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103684
* gh-105266
* gh-105270

**Comment by multiplemonomials** [comment]
Note that the code posted there is not correct for Windows, where the constant values are different.  I think a more correct version would be something like:
```python
if platform.system().lower().startswith('win'):
    if not hasattr(socket, "IP_UNBLOCK_SOURCE"):
        setattr(socket, "IP_UNBLOCK_SOURCE", 18)
    if not hasattr(socket, "IP_BLOCK_SOURCE"):
        setattr(socket, "IP_BLOCK_SOURCE", 17)
    if not hasattr(socket, "IP_ADD_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_ADD_SOURCE_MEMBERSHIP", 15)
    if not hasattr(socket, "IP_DROP_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_DROP_SOURCE_MEMBERSHIP", 16)
else:
    if not hasattr(socket, "IP_UNBLOCK_SOURCE"):
        setattr(socket, "IP_UNBLOCK_SOURCE", 37)
    if not hasattr(socket, "IP_BLOCK_SOURCE"):
        setattr(socket, "IP_BLOCK_SOURCE", 38)
    if not hasattr(socket, "IP_ADD_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_ADD_SOURCE_MEMBERSHIP", 39)
    if not hasattr(socket, "IP_DROP_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_DROP_SOURCE_MEMBERSHIP", 40)
```

**Comment by danrossi** [comment]
I've been trying to figure out SSM suipport. confirm the flags on windows was causing errors. I've got passed this with the flag change. However the minimal code examples out there any attempt to use "SOL_IP" causes invalid argument. 

Is this the correct method for SSM ? 0.0.0.0 works for asm not sure for ssm yet.

```
multicast_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)

multicast_socket.bind(("0.0.0.0", multicast_port))

mreq=struct.pack("=4s4s4s", 
                 socket.inet_aton(multicast_group), 
                 socket.inet_aton(source_address), 
                 socket.inet_aton(iface))
 multicast_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_SOURCE_MEMBERSHIP, mreq)
```

**Comment by arhadthedev** [comment]
@gpshead (as listed in the socket experts list) Any ideas if @multiplemonomials's snippet can be reliably used?

**Comment by danrossi** [comment]
Yes I just tested it in windows and those flags needed to change. For SSM multicast in windows the bind address needs to be '' also but for asm "0.0.0.0" seems ok. Ive yet to check on the network with the cisco router if I get data yet. 

```
multicast_socket.bind(('', multicast_port))
```

**Comment by gpshead** [comment]
You need to look in the header files on your target platforms to determine if the snippet above adding the constants works. Regardless, this issue really is pretty much about plumbing. When these constants are defined we should expose them in the socket module. Much like we already do for many others. That'd obviate the need for hacks like the above.

**Comment by gpshead** [comment]
For anyone who wants to contribute a PR, it should pretty much just be adding stuff like you see in https://github.com/python/cpython/blob/main/Modules/socketmodule.c#L8104 with ifdef and PyModule_AddIntMacro.

**Comment by danrossi** [comment]
That is what I figured it needs to match the constant flags on the OS. For darwin it says 70. So mac needs something different ?

https://github.com/apple/darwin-xnu/blob/8f02f2a044b9bb1ad951987ef5bab20ec9486310/bsd/netinet/in.h

**Comment by danrossi** [comment]
I found a header for win 10 SDK. It says 15. 

https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/ws2ipdef.h

**Comment by danrossi** [comment]
I'm sorry to ask if getting the right flags setup. Is socket.IPPROTO_IP the correct way to setup SSM because the old examples out there using socket.SOL_IP cause endless "invalid argument" errors.  The struct packing is similar to the windows docs. Needs to join the group, source ip, then local ip

**Comment by danrossi** [comment]
Here is a patch for windows and macOS I've come up with. Will eventually test on macOS but Windows first. 

```
platform = platform.system()
if (platform == "Windows"):
    if not hasattr(socket, "IP_UNBLOCK_SOURCE"):
        setattr(socket, "IP_UNBLOCK_SOURCE", 18)
    if not hasattr(socket, "IP_BLOCK_SOURCE"):
        setattr(socket, "IP_BLOCK_SOURCE", 17)
    if not hasattr(socket, "IP_ADD_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_ADD_SOURCE_MEMBERSHIP", 15)
    if not hasattr(socket, "IP_DROP_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_DROP_SOURCE_MEMBERSHIP", 16)
elif (platform == 'Darwin'):
    if not hasattr(socket, "IP_UNBLOCK_SOURCE"):
        setattr(socket, "IP_UNBLOCK_SOURCE", 73)
    if not hasattr(socket, "IP_BLOCK_SOURCE"):
        setattr(socket, "IP_BLOCK_SOURCE", 72)
    if not hasattr(socket, "IP_ADD_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_ADD_SOURCE_MEMBERSHIP", 70)
    if not hasattr(socket, "IP_DROP_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_DROP_SOURCE_MEMBERSHIP", 71)
else:
    if not hasattr(socket, "IP_UNBLOCK_SOURCE"):
        setattr(socket, "IP_UNBLOCK_SOURCE", 37)
    if not hasattr(socket, "IP_BLOCK_SOURCE"):
        setattr(socket, "IP_BLOCK_SOURCE", 38)
    if not hasattr(socket, "IP_ADD_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_ADD_SOURCE_MEMBERSHIP", 39)
    if not hasattr(socket, "IP_DROP_SOURCE_MEMBERSHIP"):
        setattr(socket, "IP_DROP_SOURCE_MEMBERSHIP", 40)
   ```
