### ISSUE TITLE
mimetypes cannot detect mime of mka files

### ISSUE THREAD

**Issue by ad7be669-db06-416c-845b-c7455d5e6322** [python/cpython#89416]
BPO | [45253](https://bugs.python.org/issue45253)
--- | :---
Nosy | @Fidget-Spinner, @akulakov
Files | <li>[Screenshot from 2021-09-21 13-10-33.png](https://bugs.python.org/file50292/Screenshot%20from%202021-09-21%2013-10-33.png "Uploaded as image/png at 2021-09-21.07:49:08 by manujchandra")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-21.07:49:08.538>
labels = ['type-bug', 'library', '3.9']
title = 'mimetypes cannot detect mime of mka files'
updated_at = <Date 2021-10-11.18:23:24.571>
user = 'https://bugs.python.org/manujchandra'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-11.18:23:24.571>
actor = 'andrei.avk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-21.07:49:08.538>
creator = 'manujchandra'
dependencies = []
files = ['50292']
hgrepos = []
issue_num = 45253
keywords = []
message_count = 2.0
messages = ['402290', '403666']
nosy_count = 3.0
nosy_names = ['kj', 'andrei.avk', 'manujchandra']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45253'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-126412

**Comment by hugovk** [comment]
https://www.iana.org/assignments/media-types/media-types.xhtml now lists:

matroska | [audio/matroska](https://www.iana.org/assignments/media-types/audio/matroska) | [[RFC9559](https://www.iana.org/go/rfc9559)]
-- | -- | --

Where [RFC 9559](https://www.rfc-editor.org/rfc/rfc9559.html) was published in October 2024.

Please see PR https://github.com/python/cpython/pull/126412.

(cc @manujchandra)
