### ISSUE TITLE
IDLE: Better document close and exit.

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#89459]
BPO | [45296](https://bugs.python.org/issue45296)
--- | :---
Nosy | @terryjreedy, @taleinat, @ambv, @miss-islington, @E-Paine
PRs | <li>python/cpython#28577</li><li>python/cpython#28600</li><li>python/cpython#28601</li><li>python/cpython#30936</li><li>python/cpython#30944</li><li>python/cpython#30945</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2022-01-27.03:56:18.530>
created_at = <Date 2021-09-26.20:52:27.906>
labels = ['expert-IDLE', 'type-bug', '3.9', '3.10', '3.11']
title = 'IDLE: Better document close and exit.'
updated_at = <Date 2022-01-27.03:56:18.529>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.03:56:18.529>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2022-01-27.03:56:18.530>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2021-09-26.20:52:27.906>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 45296
keywords = ['patch']
message_count = 12.0
messages = ['402678', '402689', '402693', '402697', '402768', '402773', '402774', '402775', '402820', '411829', '411832', '411834']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'taleinat', 'lukasz.langa', 'miss-islington', 'epaine']
pr_nums = ['28577', '28600', '28601', '30936', '30944', '30945']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45296'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by j0le** [comment]
Can you give me a hint, where the changeset/patch/merge request is, that enables <kbd>Ctrl</kbd>+<kbd>D</kbd> on Windows? That would be very helpful and informative. Thanks in advance!

See also https://github.com/microsoft/terminal/issues/14764#issuecomment-3208498083
