### ISSUE TITLE
[C API] Functions not exported with PyAPI_FUNC()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#89479]
BPO | [45316](https://bugs.python.org/issue45316)
--- | :---
Nosy | @vstinner, @markshannon, @ericsnowcurrently, @serhiy-storchaka, @corona10, @shihai1991
PRs | <li>python/cpython#31576</li><li>python/cpython#31577</li><li>python/cpython#31579</li><li>python/cpython#31580</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-29.08:18:04.824>
labels = ['expert-C-API', '3.11']
title = '[C API] Functions not exported with PyAPI_FUNC()'
updated_at = <Date 2022-02-25.16:49:14.761>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-25.16:49:14.761>
actor = 'eric.snow'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-09-29.08:18:04.824>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 45316
keywords = ['patch']
message_count = 10.0
messages = ['402827', '402831', '402844', '403641', '413995', '413996', '414001', '414007', '414008', '414019']
nosy_count = 6.0
nosy_names = ['vstinner', 'Mark.Shannon', 'eric.snow', 'serhiy.storchaka', 'corona10', 'shihai1991']
pr_nums = ['31576', '31577', '31579', '31580']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45316'
versions = ['Python 3.11']
```

</p></details>

**Comment by penguin-wwy** [comment]
@vstinner hello, I find https://github.com/python/cpython/pull/31576 cause the `_opcode` module to fail to compile
```
renaming "_opcode" since importing it failed: dlopen(/build/lib.macosx-12.1-arm64-3.11-pydebug/_opcode.cpython-311d-darwin.so, 0x0002): symbol not found in flat namespace '__Py_GetSpecializationStats'
```

Maybe this declaration should be written to another file

**Comment by vstinner** [comment]
Please open a new issue for your build error. It's unrelated to this issue.

**Comment by vstinner** [comment]
I close this issue. I don't know how to handle PySignal_SetWakeupFd() and _Py_CheckPython3().

**Comment by vstinner** [comment]
> Please open a new issue for your build error. It's unrelated to this issue.

Oh wait, I misunderstood the issue. You're right, it's a regression caused by commit 4a0c7a1aacd08cead7717479620e62359c828e88. I wrote PR #92011 to fix it.

I didn't notice that this function is actually used by a C extension built as a shared library, but only for a special build.

**Comment by penguin-wwy** [comment]
Thanks

**Comment by vstinner** [comment]
> I wrote PR https://github.com/python/cpython/pull/92011 to fix it.

Merged. I close again the issue.

**Comment by nathan454** [comment]
https://github.com/python/cpython/issues/89479#issuecomment-1093930957

How are you supposed to use these functions than?
If they're private functions, and their symbol isn't exported, how can I link to these functions?
For now I copy paste them, but what if they change?

**Comment by vstinner** [comment]
> How are you supposed to use these functions than? If they're private functions, and their symbol isn't exported, how can I link to these functions?

They are not public on purpose. If you consider that they should be public, please open a feature request (a new issue). This issue is now closed, it's a bad place to discuss it.
