### ISSUE TITLE
Using target python while cross-building

### ISSUE THREAD

**Issue by 344598b6-96ac-40ee-9eab-0ef94aca2622** [python/cpython#89477]
BPO | [45314](https://bugs.python.org/issue45314)
--- | :---
Nosy | @moreati

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-28.18:20:08.721>
labels = ['build', '3.9']
title = 'Using target python while cross-building'
updated_at = <Date 2021-09-29.09:39:19.055>
user = 'https://bugs.python.org/fransdb'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-29.09:39:19.055>
actor = 'fransdb'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2021-09-28.18:20:08.721>
creator = 'fransdb'
dependencies = []
files = []
hgrepos = []
issue_num = 45314
keywords = []
message_count = 3.0
messages = ['402799', '402838', '402841']
nosy_count = 2.0
nosy_names = ['Alex.Willmer', 'fransdb']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue45314'
versions = ['Python 3.9']
```

</p></details>

**Comment by FFY00** [comment]
@moreati, you were in the nosy list on bpo, did you run into the same issue? I am trying to figure out how to reproduce it to see if it's still relevant.

Otherwise, I think I'll just close this as I can't reproduce and 3.9 is only getting security fixes.
