### ISSUE TITLE
Document the removal the usage of the C stack in Python to Python calls

### ISSUE THREAD

**Issue by markshannon** [python/cpython#89480]
BPO | [45317](https://bugs.python.org/issue45317)
--- | :---
Nosy | @markshannon, @pablogsal
PRs | <li>python/cpython#32304</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/pablogsal'
closed_at = None
created_at = <Date 2021-09-29.11:40:33.214>
labels = ['3.11', 'type-feature', 'deferred-blocker', 'docs']
title = 'Document the removal the usage of the C stack in Python to Python calls'
updated_at = <Date 2022-04-04.14:10:02.227>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-04.14:10:02.227>
actor = 'Mark.Shannon'
assignee = 'pablogsal'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-09-29.11:40:33.214>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 45317
keywords = ['patch']
message_count = 3.0
messages = ['402850', '402853', '414655']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mark.Shannon', 'pablogsal']
pr_nums = ['32304']
priority = 'deferred blocker'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45317'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-115657
* gh-115857
* gh-115858

**Comment by pablogsal** [comment]
⚠️ This issue has been updated from 'deferred-blocker' to 'release blocker' as we are past beta1. This issue will block the next release (`Python 3.11.0 beta 2`). ⚠️

**Comment by JelleZijlstra** [comment]
This is still marked a deferred blocker. @pablogsal are you planning on writing new GDB docs, and should those docs block any release?

**Comment by encukou** [comment]
@pablogsal, if you share the draft, in whatever state it is, I can finish it.

**Comment by pablogsal** [comment]
> @pablogsal, if you share the draft, in whatever state it is, I can finish it.

Will try to share it today after the SC meeting

**Comment by pablogsal** [comment]
@encukou Opened a PR here with what I had: https://github.com/python/cpython/pull/115657

Please, feel free to modify it

**Comment by encukou** [comment]
Thanks!
