### ISSUE TITLE
./configure --enable-optimizations should enable LTO

### ISSUE THREAD

**Issue by vstinner** [python/cpython#89536]
BPO | [45373](https://bugs.python.org/issue45373)
--- | :---
Nosy | @gpshead, @vstinner, @ned-deily, @methane, @corona10, @pablogsal, @erlend-aasland

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-05.09:32:25.894>
labels = ['build', '3.11']
title = './configure --enable-optimizations should enable LTO'
updated_at = <Date 2022-03-03.09:51:27.150>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.09:51:27.150>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-10-05.09:32:25.894>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 45373
keywords = []
message_count = 9.0
messages = ['403209', '403210', '403211', '403244', '403248', '403249', '414312', '414313', '414316']
nosy_count = 7.0
nosy_names = ['gregory.p.smith', 'vstinner', 'ned.deily', 'methane', 'corona10', 'pablogsal', 'erlendaasland']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45373'
versions = ['Python 3.11']
```

</p></details>

**Comment by nascheme** [comment]
One data point: when I enabled `with-lto`, the cpython build task failed on my container build host due to an out of memory condition.  It seems that gcc uses a lot more RAM in that case (host has 2 GB, I think).  I fixed it by adding a swap file but I suspect if we make it to default on, more people will run into the issue.

**Comment by methane** [comment]
I like faster LTO by default. Because default LTO is slow.

Random comments:

I don't want to use LTO while profiling build (1st build in PGO).

What about GCC?  GCC supports `-flto=auto` option since GCC 10.
https://www.phoronix.com/scan.php?page=news_item&px=GCC-flto-auto-option

**Comment by ned-deily** [comment]
I don't have an opinion yet. I plan to compare both options on macOS.

**Comment by corona10** [comment]
> I don't want to use LTO while profiling build (1st build in PGO).

+1

> What about GCC? GCC supports -flto=auto option since GCC 10

We may need to add the option for `./configure --with-lto=auto` and I think that we have a chance to add it to Python 3.11 
Also in that case, from Python 3.12 `./configure --with-lto` should use auto option if available, if not should use the default LTO policy for GCC.

**Comment by vstinner** [comment]
So. Can we enable LTO in Python 3.12? Is there a way to opt-out from LTO when ``--enable-optimizations`` is used? For example, does ``./configure --enable-optimizations --without-lto`` work as expected?

**Comment by vstinner** [comment]
Is it possible to disable LTO if it's known to not work properly / if the toolchain is too old? I'm thinking at Ned's toolchain to build Python on macOS for x86 CPU.

**Comment by vstinner** [comment]
What's the status of LTO in 2023? Can it be now enabled by default in Python?

cc @corona10

**Comment by corona10** [comment]
@ned-deily 
Do you have any concerns with unifying into the single optimization from macOS side?


> What's the status of LTO in 2023? Can it be now enabled by default in Python?

One problem is the GCC side, The FullLTO is too slow, we should pass the -flto=$(number of cores) or -flto=auto
I am not sure that it will be an acceptable situation even for the RedHat.
WDYT?

**Comment by vstinner** [comment]
If an user really cares about performance and prefers to disable LTO, would it work to specify ``./configure --enable-optimizations --disable-lto``?

**Comment by corona10** [comment]
> Is the build performance really a matter when the user explicitly asks for enable optimizations? I don't think so.

Yeah, if the customer is okay to use, I am fine.
But I am not familiar with customers of Linux.
So I asked you :)

**Comment by vstinner** [comment]
> But I am not familiar with customers of Linux.

Most popular Linux distributions provide binary packages, like Ubuntu or Fedora: users don't build Python themselves (hopefully!), packages are built once on fast build servers. Source based distros linux ArchLinux are less popular.

macOS users have a .dmg binary installer, even if HomeBrew seems to be popular.

Windows users have .msi binary installer.

FreeBSD is source based.

For source based distributions like ArchLinux and FreeBSD, Python packages can be tuned to disable LTO if they prefer to save some minutes during build but waste CPU time later.

**Comment by nascheme** [comment]
I'm a builder of Python that would be affected by turning on LTO by default.  I would likely turn it off but having it on by default and turning off by command line option is okay with me.  Last time I tried it, I decided it takes too long and too much RAM for the build for too little benefit.  However, my guess is for most people using `--enable-optimizations`, LTO on by default would be better.  Turning it on would likely help it mature more as well (e.g. improve compilers).

**Comment by vstinner** [comment]
> I'm a builder of Python that would be affected by turning on LTO by default

Would you mind to elaborate?

**Comment by nascheme** [comment]
We deploy our software using Linux containers.  I like to use the most up-to-date Python release and so I build my own Python from source when building the container images.  The VM host that builds container images is somewhat limited on RAM and CPU and so enabling LTO stresses it quite a bit.  We could just use a higher spec container build host.  However, last I checked, the gain from using LTO is fairly small so I didn't think it worth it.  Again, I think LTO on by default, with `--enable-optimizations`, would be an okay default.

**Comment by vstinner** [comment]
> One problem is the GCC side, The FullLTO is too slow, we should pass the -flto=$(number of cores) or -flto=auto
> I am not sure that it will be an acceptable situation even for the RedHat.

That sounds like a nice enhancement. Is it required to enable LTO by default when optimizations are enabled?

About RHEL, do you you know which GCC version added the ``-flto=auto`` option? Maybe configure can check if it's supported or not.

**Comment by vstinner** [comment]
I don't see any real blocker issue. Would you be ok to enable LTO optimization with ``./configure --enable-optimizations`` in Python 3.13?

**Comment by gpshead** [comment]
It looks like `--enable-optimizations --with-lto=full` it increases build time from 3x-10x vs `--enable-optimizations --with-lto=no` using gcc due to a couple of long linking steps.  When using clang, `--with-lto=thin` mode is available, that cuts the LTO build time vs `=full` in half for me.

The overall runtime performance gain looks to be about 3% using gcc `--with-lto=full`.

One thing I noticed: It is doing the profile guided build with LTO enabled as well, so the double compilation includes the super long final LTO link steps in both. I'm not sure an LTO enabled build is necessary to generate profile data for PGO. If the LTO flags could be skipped for that first PGO build it'd significantly reduce build time.

I'm in favor of `--enable-optimizations` including LTO by default in 3.13. I'd default to `--with-lto=thin` when the compiler is clang. If this winds up causes problems we can undo it. It's just a configure flag.

**Comment by gpshead** [comment]
Read my last paragraph.

> I'm in favor of --enable-optimizations including LTO by default in 3.13. ... If this winds up causing problems we can undo it. It's just a configure flag.

**Comment by vstinner** [comment]
Oh, it seems like i misunderstood your comment. You are ok to switch it on by default for all compilers. But use thinLTO when available.

**Comment by gpshead** [comment]
My benchmark results came back.  lto=full (+3%) performs significantly better than lto=thin (1%) on clang pyperformance so keeping it simple and always using full makes sense.  (thin does _build_ a lot faster though, but that isn't the point of this configure flag)

**Comment by vstinner** [comment]
Description of the feature in 2020: https://stackoverflow.com/questions/64954525/does-gcc-have-thin-lto

> GCC has an equivalent to Thin LTO: WHOle Program optimizeR (WHOPR)
> 
> WHOPR is an extension of the LTO feature of GCC. You can enable it with -fwhopr (added to the standard LTO options).
> 
>     The standard LTO is fully monolithic (like standard LTO in clang)
>     The WHOPR is a two-stage LTO (like clang Thin LTO)
> 
> The two stages are
> 
>     WPA: The serial part that does some global optimizations and partitions the IR
>     LTRANS: Parallel backends to do the optimizations in each partition
> 
> Now, in practice, GCC WHOPR needs significantly more memory and time than Clang Thin LTO, but the numbers have been improving recently.

**Comment by vstinner** [comment]
Apparently, the status quo is to have a separated option to opt-in for LTO. It's already recommended in https://docs.python.org/dev/using/configure.html#performance-options documentation. So I close the issue.
