### ISSUE TITLE
Custom frozen modules get ignored.

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#89559]
BPO | [45396](https://bugs.python.org/issue45396)
--- | :---
Nosy | @gvanrossum, @brettcannon, @ericsnowcurrently
PRs | <li>python/cpython#28776</li><li>python/cpython#28778</li><li>python/cpython#29301</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericsnowcurrently'
closed_at = None
created_at = <Date 2021-10-06.20:22:14.892>
labels = ['interpreter-core', 'type-bug', '3.11']
title = 'Custom frozen modules get ignored.'
updated_at = <Date 2021-10-28.21:34:52.384>
user = 'https://github.com/ericsnowcurrently'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-28.21:34:52.384>
actor = 'eric.snow'
assignee = 'eric.snow'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-10-06.20:22:14.892>
creator = 'eric.snow'
dependencies = []
files = []
hgrepos = []
issue_num = 45396
keywords = ['patch']
message_count = 4.0
messages = ['403336', '403337', '403705', '405277']
nosy_count = 3.0
nosy_names = ['gvanrossum', 'brett.cannon', 'eric.snow']
pr_nums = ['28776', '28778', '29301']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45396'
versions = ['Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
> However, I'd like to change the name of the -X option from "frozen_modules" to "frozen_stdlib", to avoid any confusion in the future.

Do we still want to pursue this? I don't think we should change the name as it is been this way for the past beta and alphas.

**Comment by gvanrossum** [comment]
> > However, I'd like to change the name of the -X option from "frozen_modules" to "frozen_stdlib", to avoid any confusion in the future.
> 
> Do we still want to pursue this? I don't think we should change the name as it is been this way for the past beta and alphas.

Agreed, let's not change this. Closing as "fixed" because everything else is taken care of.

**Comment by erlend-aasland** [comment]
I assume this implies also closing the linked open PR. I'm marking it as pending close.

**Comment by gvanrossum** [comment]
Yes please.
