### ISSUE TITLE
[C API] Move usage of tp_vectorcall_offset from public headers to the internal C API

### ISSUE THREAD

**Issue by vstinner** [python/cpython#89602]
BPO | [45439](https://bugs.python.org/issue45439)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#28890</li><li>python/cpython#28891</li><li>python/cpython#28893</li><li>python/cpython#28895</li>
Files | <li>[test_bench.patch](https://bugs.python.org/file50345/test_bench.patch "Uploaded as text/plain at 2021-10-12.06:58:51 by @vstinner")</li><li>[bench.py](https://bugs.python.org/file50346/bench.py "Uploaded as text/plain at 2021-10-12.06:59:00 by @vstinner")</li><li>[bench_no_args.patch](https://bugs.python.org/file50347/bench_no_args.patch "Uploaded as text/plain at 2021-10-12.07:38:04 by @vstinner")</li><li>[bench_no_args_inline.py](https://bugs.python.org/file50348/bench_no_args_inline.py "Uploaded as text/plain at 2021-10-12.07:38:10 by @vstinner")</li><li>[bench_no_args_public.py](https://bugs.python.org/file50349/bench_no_args_public.py "Uploaded as text/plain at 2021-10-12.07:38:16 by @vstinner")</li><li>[test_bench2.patch](https://bugs.python.org/file50350/test_bench2.patch "Uploaded as text/plain at 2021-10-12.20:18:41 by @vstinner")</li><li>[bench2.py](https://bugs.python.org/file50351/bench2.py "Uploaded as text/plain at 2021-10-12.20:18:48 by @vstinner")</li><li>[sys_call.patch](https://bugs.python.org/file50355/sys_call.patch "Uploaded as text/plain at 2021-10-13.21:54:14 by @vstinner")</li><li>[stack_overflow-4.py](https://bugs.python.org/file50356/stack_overflow-4.py "Uploaded as text/plain at 2021-10-13.22:03:50 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-15.00:42:16.482>
created_at = <Date 2021-10-11.22:18:05.305>
labels = ['expert-C-API', '3.11']
title = '[C API] Move usage of tp_vectorcall_offset from public headers to the internal C API'
updated_at = <Date 2021-10-15.00:42:16.477>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-15.00:42:16.477>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-15.00:42:16.482>
closer = 'vstinner'
components = ['C API']
creation = <Date 2021-10-11.22:18:05.305>
creator = 'vstinner'
dependencies = []
files = ['50345', '50346', '50347', '50348', '50349', '50350', '50351', '50355', '50356']
hgrepos = []
issue_num = 45439
keywords = ['patch']
message_count = 10.0
messages = ['403695', '403696', '403698', '403708', '403768', '403770', '403877', '403878', '403937', '403939']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['28890', '28891', '28893', '28895']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue45439'
versions = ['Python 3.11']
```

</p></details>

**Comment by mikita-sakalouski** [comment]
Can this change be a root cause for #99152 ?

**Comment by mikita-sakalouski** [comment]
@vstinner Can this change be a root cause for #99152 ?

This [line](https://github.com/python/cpython/blob/de54cf5be371a6f5e2e9f208c38def5f81d3ef02/Modules/_functoolsmodule.c#L2): 
```
#include "pycore_call.h"          // _PyObject_CallNoArgs()
```
