### ISSUE TITLE
Make IDLE recognize .pyi stub files as source for open, save, and edit

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#89610]
BPO | [45447](https://bugs.python.org/issue45447)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @zooba, @miss-islington, @E-Paine, @AlexWaygood
PRs | <li>python/cpython#28950</li><li>python/cpython#31303</li><li>python/cpython#31304</li><li>python/cpython#31305</li><li>python/cpython#31306</li><li>python/cpython#31307</li><li>python/cpython#31308</li><li>python/cpython#31309</li><li>python/cpython#31310</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2021-10-12.15:24:36.540>
labels = ['expert-IDLE', 'type-feature', '3.11']
title = 'Make IDLE recognize .pyi stub files as source for open, save, and edit'
updated_at = <Date 2022-02-14.03:35:10.254>
user = 'https://github.com/AlexWaygood'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-14.03:35:10.254>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2021-10-12.15:24:36.540>
creator = 'AlexWaygood'
dependencies = []
files = []
hgrepos = []
issue_num = 45447
keywords = ['patch']
message_count = 28.0
messages = ['403738', '403741', '403755', '403772', '403884', '403889', '403915', '403998', '404021', '404023', '404030', '404100', '404102', '404110', '410637', '410669', '412561', '412617', '413147', '413149', '413150', '413156', '413157', '413158', '413168', '413169', '413170', '413211']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'steve.dower', 'miss-islington', 'epaine', 'AlexWaygood']
pr_nums = ['28950', '31303', '31304', '31305', '31306', '31307', '31308', '31309', '31310']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45447'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-113222
* gh-113223
* gh-113224

**Comment by erlend-aasland** [comment]
Are there further work to be done here, or can we close this issue?

**Comment by terryjreedy** [comment]
https://github.com/python/cpython/issues/89610#issuecomment-1093932972 indicates other places that need revision.

**Comment by erlend-aasland** [comment]
It is not obvious to me what needs revision. Could you elaborate?

**Comment by terryjreedy** [comment]
All the other places indicated that require python file be .py, thereby excluding .pyi.

**Comment by ronaldoussoren** [comment]
See also my comment about adding ``pyi`` to the list of ``CFBundleTypeExtensions`` in IDLE's Info.plist.  That will allow opening stub files by double clicking on them in the Finder, and is not necessary for the File/open menu.

Otherwise syntax coloring for stub files appears to work fine in the current Python 3.11 beta.

**Comment by erlend-aasland** [comment]
> See also my comment about adding pyi to the list of CFBundleTypeExtensions in IDLE's Info.plist.

=> #95393

**Comment by erlend-aasland** [comment]
> It looks like support for .py files is hardcoded into IDLE's source code in the following places:
> 
> * browser.ModuleBrowserTreeItem.OnDoubleClick
> * browser.ModuleBrowserTreeItem.IsExpandable
> * browser.ModuleBrowserTreeItem.listchildren

👉🏻 #95397

> * iomenu.IOBinding.filetypes

Seems irrelevant for this issue to me; I might be wrong, I only took a quick glance at the code.

**Comment by terryjreedy** [comment]
I listed iomenu filetypes before we added the util.py_extensions tuple, which is used in several places.  Before, the same information was duplicated in multiple places.  That item is now obsolete.

**Comment by terryjreedy** [comment]
I open task issue #95410 with two of the items completed by this issue.  I opened a browser issue #95411 and moved the browser PR there.
