### ISSUE TITLE
[C API] PEP 674: Disallow using macros (Py_TYPE and Py_SIZE) as l-value

### ISSUE THREAD

**Issue by vstinner** [python/cpython#89639]
BPO | [45476](https://bugs.python.org/issue45476)
--- | :---
Nosy | @malemburg, @rhettinger, @vstinner, @gareth-rees, @erlend-aasland, @arhadthedev
PRs | <li>python/cpython#28961</li><li>python/cpython#28976</li><li>python/cpython#29860</li><li>python/cpython#29866</li>
Files | <li>[pep674_regex.py](https://bugs.python.org/file50462/pep674_regex.py "Uploaded as text/plain at 2021-12-01.00:25:37 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-14.21:17:31.326>
labels = ['expert-C-API', '3.11']
title = '[C API] PEP 674: Disallow using macros (Py_TYPE and Py_SIZE) as l-value'
updated_at = <Date 2022-01-27.20:29:40.417>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.20:29:40.417>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-10-14.21:17:31.326>
creator = 'vstinner'
dependencies = []
files = ['50462']
hgrepos = []
issue_num = 45476
keywords = ['patch']
message_count = 41.0
messages = ['403950', '403956', '403961', '403965', '403990', '403995', '403999', '404001', '404010', '404039', '406343', '406344', '406345', '406346', '406348', '406996', '407283', '407358', '407374', '407375', '407395', '407410', '407412', '407416', '407417', '407456', '407463', '407528', '407529', '407531', '407532', '407536', '407872', '407875', '411774', '411802', '411803', '411826', '411827', '411831', '411921']
nosy_count = 6.0
nosy_names = ['lemburg', 'rhettinger', 'vstinner', 'gdr@garethrees.org', 'erlendaasland', 'arhadthedev']
pr_nums = ['28961', '28976', '29860', '29866']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45476'
versions = ['Python 3.11']
```

</p></details>

**Comment by kigawas** [comment]
> > pysha3-1.0.2
> 
> This module must not be used on Python 3.6 and newer which has a built-in support for SHA-3 hash functions. Example:
> 
> ```
> $ python3.6
> Python 3.6.15 (default, Sep  5 2021, 00:00:00) 
> >>> import hashlib
> >>> h=hashlib.new('sha3_224'); h.update(b'hello'); print(h.hexdigest())
> b87f88c72702fff1748e58b87e9141a42c0dbedc29a78cb0d4a5cd81
> ```
> 
> By the way, building pysha3 on Python 3.11 now fails with:
> 
> ```
> [Modules/_sha3/backport.inc:78](https://github.com/python/cpython/blob/main/Modules/_sha3/backport.inc#L78):10: fatal error: pystrhex.h: No such file or directory
> ```
> 
> The pystrhex.h header file has been removed in Python 3.11 by [bpo-45434](https://bugs.python.org/issue?@action=redirect&bpo=45434). But I don't think that it's worth it trying to port it to Python 3.11, if the module must not be used on Python 3.6 and newer.
> 
> Environment markers can be used to skip the pysha3 dependency on Python 3.6 on newer.
> 
> Example: "pysha3; python_version < '3.6'"

Strictly speaking, `pysha3` is not equivalent to `hashlib` because keccak functions are different. If the improvement in #83720 is done, pysha3 may be completely replaced. 

However, since pystrhex.h removed from Python 3.11, the pycryptodome is the only legit library supporting Ethereum keccak.

**Comment by vstinner** [comment]
> However, since pystrhex.h removed from Python 3.11

Technically, these functions are still exported and remain available in the internal C API: Include/internal/pycore_strhex.h

If someone wants a public C API for these, it should be asked. But by default, the private functions must not be used outside Python itself: https://docs.python.org/dev/c-api/stable.html

It's not hard to copy Python/pystrhex.c (174 lines) or reimplement it.

**Comment by kigawas** [comment]
@vstinner 

That's not practical because `pysha3` is not actively being maintained. Many downstream libraries will break from 3.11. 

**For anyone searching the errors, just use `pycryptodome` instead to save your time.**

**Comment by vstinner** [comment]
https://peps.python.org/pep-0674/ was deferred by the SC. For now, I prefer to close this issue.
