### ISSUE TITLE
Missing link(s) to the "Python Module Index" page

### ISSUE THREAD

**Issue by a09e2537-b6b9-4978-9d1d-78b1db358cbc** [python/cpython#89643]
BPO | [45480](https://bugs.python.org/issue45480)
--- | :---
Nosy | @ericvsmith, @mark-summerfield, @ned-deily, @JulienPalard

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-15.07:17:44.306>
labels = ['3.11', '3.9', '3.10', 'docs']
title = 'Missing link(s) to the "Python Module Index" page'
updated_at = <Date 2021-10-15.15:37:06.907>
user = 'https://github.com/mark-summerfield'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-15.15:37:06.907>
actor = 'eric.smith'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-10-15.07:17:44.306>
creator = 'mark'
dependencies = []
files = []
hgrepos = []
issue_num = 45480
keywords = []
message_count = 4.0
messages = ['403977', '403986', '404031', '404032']
nosy_count = 5.0
nosy_names = ['eric.smith', 'mark', 'ned.deily', 'docs@python', 'mdk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45480'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by slateny** [comment]
Looking at
https://docs.python.org/3.8/library/os.html
https://docs.python.org/3.9/library/os.html
https://docs.python.org/3.10/library/os.html
https://docs.python.org/dev/library/os.html

![image](https://user-images.githubusercontent.com/46876382/182108411-cc98b6f7-991f-4a45-86bc-15da6e8b8851.png)
![image](https://user-images.githubusercontent.com/46876382/182108492-98bfa1de-12a2-4e05-9388-3dca77394ed9.png)

I see the module links on Chrome/Firefox on all those versions, so this looks like it's been fixed.

**Comment by slateny** [comment]
Correction, it's still a problem if the window width is too small, described a bit better in this issue: https://github.com/python/cpython/issues/92789
