### ISSUE TITLE
[C API]  PEP 670: Convert macros to functions in the Python C API

### ISSUE THREAD

**Issue by vstinner** [python/cpython#89653]
BPO | [45490](https://bugs.python.org/issue45490)
--- | :---
Nosy | @malemburg, @vstinner, @erlend-aasland
PRs | <li>python/cpython#29728</li><li>python/cpython#31217</li><li>python/cpython#31221</li>
Files | <li>[macros-that-reuse-args.txt](https://bugs.python.org/file50616/macros-that-reuse-args.txt "Uploaded as text/plain at 2022-02-10.12:50:36 by @erlend-aasland")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-15.17:43:25.813>
labels = ['expert-C-API', '3.11']
title = '[C API]  PEP 670: Convert macros to functions in the Python C API'
updated_at = <Date 2022-02-11.16:01:26.957>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-11.16:01:26.957>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-10-15.17:43:25.813>
creator = 'vstinner'
dependencies = []
files = ['50616']
hgrepos = []
issue_num = 45490
keywords = ['patch']
message_count = 7.0
messages = ['404038', '404045', '404183', '404185', '412861', '412995', '413079']
nosy_count = 3.0
nosy_names = ['lemburg', 'vstinner', 'erlendaasland']
pr_nums = ['29728', '31217', '31221']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45490'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-99843

**Comment by vstinner** [comment]
Update: the SC approved PEP 670: https://mail.python.org/archives/list/python-dev@python.org/thread/QQFCJ7LR36RUZSC3WI6WZZMQVQ3ZI4MS/

**Comment by vstinner** [comment]
Merged commits:

* commit 4e52c66f6940a63ef7a62faf8ce32a980ac5aa2c: PEP 670: Convert unicodeobject.h macros to functions (#91705)
* commit 1a2b282f201073d5153e737568c833af6f1b349e: PEP 670: Convert PyWeakref_GET_OBJECT() to function (#91785)
* commit 2a5f171759a31597032cfe52646929e6f8727243: PEP 670: Convert tuple macros to functions (#91786)
* commit 128d6241176a879ea9b6e34ea67f1d113d22a1b8: PEP 670: Convert unicodeobject.h macros to functions (#91773)
* commit c1474fa6c6496e2bf0fd341ccd735ab2fd6d7764: PEP 670: Group deprecated API in unicodeobject.h (#91796)
* commit 636ad7b47e5e1997b6e6979342fe11ae284fc1c7: PEP 670: Convert unicodeobject.h macros to functions (#91799)
* commit efe7fd4170bb809ed46cac35c6a9007d5b794e7e: Add assertions to unicodeobject.h functions (#91800)
* commit 61381d7da1233849b280706f11dbcae4deed949d: PEP 670: Functions don't cast pointers (#91697)
* commit 121806160962d4e96b5e874a173d515531ae994b: PEP 670: Amend docs (GH-91813)

See also #91768 which replaced ``const PyObject*`` with ``PyObject*`` and commit 9e146bbb7e1c0d872817ac63c60454a201b50039 (gh-80527: Deprecate PEP 623 Unicode functions, #91801).

**Comment by vstinner** [comment]
Commit https://github.com/python/cpython/commit/897f14d38d1b455668f9f7ce87892f5efcaf8932: PyCell macros

**Comment by vstinner** [comment]
Bugfixes in the 3.11 branches:

* commit 6f9287205f2fb562262750ac2e80b555ff5003ca: PEP 670: Limited API doesn't cast arguments (#92693)
* commit a1bef8c2e305178fae2ff90b5772e785a97d2201: PEP 670: Use PyObject* type for parameters (#92698)
* commit 6e1a214426f968cd759ebd06e1a3f9d06ab32d7c: PEP 670: unicodeobject.h uses _Py_CAST() (#92703)

**Comment by vstinner** [comment]
Merged commits:

* commit 61381d7da1233849b280706f11dbcae4deed949d: Functions don't cast pointers (#91697)
* commit 2eca5dad0a783153318e91e3e25f16a38a632bfd: Convert PyBytes macros to functions (#91990)
* commit 08b562a5dfc5cb5b94c94622763f79998aa682c3: Convert PyCFunction macros to functions (#92302)
* commit ffcc7cd57f6a52c6074ecc9f0a9f0177fb1dbfee: Convert pycore_gc.h macros to functions (#92649)
* commit 897f14d38d1b455668f9f7ce87892f5efcaf8932: Convert PyCell macros to functions (#92653)
* commit eb88f21301931449718cd4d105018d167a02788b: Convert unicodeobject.h macros to functions (#92648)
* commit 7d3b469e475e6e52ce4f0bad7198bb05ead77b1d: Limited API doesn't cast arguments (#92654)
* commit 6de78ef96afbaa127472bb9dc0a4e41e44555d00: Use PyObject* type for parameters (#92694)
* commit f9b67ad7701a4d51c0c895db4087ebd66743aa82: Convert PyDict_GET_SIZE() macro to function (#92695)
* commit 92f0ed1d90bb3338fb36dbeb997e495ab474ae1e: Update C API unicode documentation (#92702)
* commit d0c9353a79c2003385c83892db5dfd4e443474c9: unicodeobject.h uses _Py_CAST() (#92696)

**Comment by erlend-aasland** [comment]
OT: There should be an easy way of toggle hide/show commit references to issues. This gets pretty noisy after a while.

**Comment by vstinner** [comment]
> OT: There should be an easy way of toggle hide/show commit references to issues. This gets pretty noisy after a while.

It's common that I push a new branch into my vstinner/cpython: the commit is mentioned there. I prepare a PR, but I see a typo. I fix the typo and "git push --force": it adds a second mention. Sometimes, I do that 5 to 10 times for a single PR. Here I created many PRs, so there are tons of mentions.

**Comment by erlend-aasland** [comment]
Yeah, but even simple issues get noisy pretty quickly. There should be a way to collapse these notifications with a keyboard shortcut.

**Comment by vstinner** [comment]
Most important macros have been converted. I close the issue, I marked PEP 670 Status as Final. Maybe I will push a few more changes using this issue number, but the main part is done ;-)

**Comment by erlend-aasland** [comment]
Great job, Victor! 😃 🚀

**Comment by CAM-Gerlach** [comment]
> OT: There should be an easy way of toggle hide/show commit references to issues. This gets pretty noisy after a while.

A little late, but FYI there is with Refined GitHub:

![image](https://user-images.githubusercontent.com/17051931/196017236-1dc16e8b-67a6-4f32-a704-179ab49db3f0.png)
