### ISSUE TITLE
Enum's dir() does not contain inherited members

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#89698]
BPO | [45535](https://bugs.python.org/issue45535)
--- | :---
Nosy | @warsaw, @ethanfurman, @serhiy-storchaka, @AlexWaygood
PRs | <li>python/cpython#29316</li><li>python/cpython#30677</li>
Superseder | <li>bpo-40066: Enum: modify __repr__, __str__; update docs</li>
Files | <li>[Enum_dir_patch.txt](https://bugs.python.org/file50382/Enum_dir_patch.txt "Uploaded as text/plain at 2021-10-21.16:53:09 by @AlexWaygood")</li><li>[enum_dir_output_with_patch.txt](https://bugs.python.org/file50383/enum_dir_output_with_patch.txt "Uploaded as text/plain at 2021-10-21.16:54:24 by @AlexWaygood")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2022-01-17.17:02:11.779>
created_at = <Date 2021-10-20.10:35:06.095>
labels = ['type-bug', 'library', '3.10', '3.11']
title = "Enum's dir() does not contain inherited members"
updated_at = <Date 2022-01-18.23:13:23.710>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.23:13:23.710>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2022-01-17.17:02:11.779>
closer = 'ethan.furman'
components = ['Library (Lib)']
creation = <Date 2021-10-20.10:35:06.095>
creator = 'serhiy.storchaka'
dependencies = []
files = ['50382', '50383']
hgrepos = []
issue_num = 45535
keywords = ['patch']
message_count = 11.0
messages = ['404420', '404621', '404634', '404635', '404721', '405313', '405320', '405323', '407539', '410807', '410912']
nosy_count = 5.0
nosy_names = ['barry', 'eli.bendersky', 'ethan.furman', 'serhiy.storchaka', 'AlexWaygood']
pr_nums = ['29316', '30677']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '40066'
type = 'behavior'
url = 'https://bugs.python.org/issue45535'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by vstinner** [comment]
@ethanfurman: test_enum.test_dir_with_custom_dunders() is skipped since 2022, since commit 7c0914d35eaaab2f323260ba5fe8884732533888:

```
commit 7c0914d35eaaab2f323260ba5fe8884732533888
Author: Ethan Furman <ethan@stoneleaf.us>
Date:   Tue Jan 18 15:13:13 2022 -0800

    bpo-45535: [Enum] include special dunders in dir() (GH-30677)
    
    Include the `__dunders__` in `dir()` that make `Enum` special:
    
    - `__contains__`
    - `__getitem__`
    - `__iter__`
    - `__len__`
    - `__members__`
```

What's the status of this test? Should it be removed?
