### ISSUE TITLE
Use pkg-config autoconf macros to detect flags for Modules/Setup

### ISSUE THREAD

**Issue by tiran** [python/cpython#89736]
BPO | [45573](https://bugs.python.org/issue45573)
--- | :---
Nosy | @Yhg1s, @brettcannon, @tiran, @ned-deily, @erlend-aasland
PRs | <li>python/cpython#29164</li><li>python/cpython#29534</li><li>python/cpython#29559</li><li>python/cpython#29594</li><li>python/cpython#29614</li><li>python/cpython#29615</li><li>python/cpython#29616</li>
Superseder | <li>bpo-45774: Detect SQLite in configure.ac</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2021-10-22.15:22:43.638>
labels = ['type-feature', 'build', '3.11']
title = 'Use pkg-config autoconf macros to detect flags for Modules/Setup'
updated_at = <Date 2021-11-19.15:41:03.253>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-19.15:41:03.253>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-10-22.15:22:43.638>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 45573
keywords = ['patch']
message_count = 14.0
messages = ['404781', '404783', '404784', '406084', '406135', '406138', '406139', '406331', '406375', '406520', '406527', '406535', '406586', '406591']
nosy_count = 5.0
nosy_names = ['twouters', 'brett.cannon', 'christian.heimes', 'ned.deily', 'erlendaasland']
pr_nums = ['29164', '29534', '29559', '29594', '29614', '29615', '29616']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = '45774'
type = 'enhancement'
url = 'https://bugs.python.org/issue45573'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
AFAICS, this is implemented. If you disagree, please re-open or create a new issue describing the problem.
