### ISSUE TITLE
Drop support for 15-bit PyLong digits?

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#89732]
BPO | [45569](https://bugs.python.org/issue45569)
--- | :---
Nosy | @tim-one, @terryjreedy, @mdickinson, @scoder
PRs | <li>python/cpython#30306</li><li>python/cpython#30497</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-22.10:21:47.461>
labels = []
title = 'Drop support for 15-bit PyLong digits?'
updated_at = <Date 2022-01-14.18:55:08.328>
user = 'https://github.com/mdickinson'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-14.18:55:08.328>
actor = 'mark.dickinson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-10-22.10:21:47.461>
creator = 'mark.dickinson'
dependencies = []
files = []
hgrepos = []
issue_num = 45569
keywords = ['patch']
message_count = 11.0
messages = ['404746', '404794', '404852', '409365', '409385', '409415', '410139', '410421', '410425', '410511', '410589']
nosy_count = 4.0
nosy_names = ['tim.peters', 'terry.reedy', 'mark.dickinson', 'scoder']
pr_nums = ['30306', '30497']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45569'
versions = []
```

</p></details>

**Comment by markshannon** [comment]
@mdickinson

I'd like to flip this around and make sure that digits are always half words.
In other words, digits should be 30 bits on 64 machines and 15 bits on 32 bit machines.

This is desirable because it gives us some nice invariants with more efficient integers, https://github.com/python/cpython/issues/101291:

* The long (non-compact) form would always have at least 2 digits, since a single digit value would fit into the compact form.
* `2 * sizeof(digit) == sizeof(intptr_t)` 
* `digit * digit` always fits in `intptr_t`.

I'm assume the primary motivation for this change is to simplify the code, not performance.

**Comment by markshannon** [comment]
Having have 30 bit digits on 32 bits platforms is awkward for #101291 as the compact ints have only 29 bits.

**Comment by mdickinson** [comment]
@markshannon Sounds reasonable to me. I think the recent change in direction in `Objects/longobject.c` invalidates much of the discussion in this issue - it could be closed as out of date. I trust you to do whatever makes sense here. :-)

**Comment by erlend-aasland** [comment]
> @markshannon Sounds reasonable to me. I think the recent change in direction in `Objects/longobject.c` invalidates much of the discussion in this issue - it could be closed as out of date. I trust you to do whatever makes sense here. :-)

Based on the last comment from @mdickinson, it seems to me we can now close this issue. Correct me if I'm wrong.

**Comment by tim-one** [comment]
@erlend-aasland, yes, I too believe this issue has in fact been resolved.

**Comment by gpshead** [comment]
the 32-bit gps-raspbian buildbot has just been flipped over to --enable-big-digits=15 configuration after confirming manually that such builds work.
