### ISSUE TITLE
argparse add_argument_group: distinguish title and description from **kwargs

### ISSUE THREAD

**Issue by fc4786d0-d04b-4f19-8c02-f1f3c6a875db** [python/cpython#89750]
BPO | [45587](https://bugs.python.org/issue45587)
--- | :---
Nosy | @SelfAdjointOperator
PRs | <li>python/cpython#29192</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-23.12:43:40.221>
labels = ['3.9', '3.10', '3.11', 'type-feature', 'library', 'docs']
title = 'argparse add_argument_group: distinguish title and description from **kwargs'
updated_at = <Date 2021-12-23.22:27:31.272>
user = 'https://github.com/SelfAdjointOperator'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-23.22:27:31.272>
actor = 'SelfAdjointOperator'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-10-23.12:43:40.221>
creator = 'SelfAdjointOperator'
dependencies = []
files = []
hgrepos = []
issue_num = 45587
keywords = ['patch']
message_count = 1.0
messages = ['409109']
nosy_count = 3.0
nosy_names = ['docs@python', 'paul.j3', 'SelfAdjointOperator']
pr_nums = ['29192']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45587'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The module documentation already documents `title` and `description`. It lacks mention of other keyword parameters, this is tracked by #89819.

The proposed PR changes how the `add_argument_group()` signature is shown in the help output. But I do not think it is worth complicating the implementation. The help output can be improved by adding a docstring.
