### ISSUE TITLE
argparse bug: prefix_chars argument to add_argument_group doesn't really work

### ISSUE THREAD

**Issue by ca7ace24-b88c-4714-94ae-52605b2ac070** [python/cpython#89819]
BPO | [45656](https://bugs.python.org/issue45656)
--- | :---
Files | <li>[argparser-bug.py](https://bugs.python.org/file50410/argparser-bug.py "Uploaded as text/plain at 2021-10-28.18:27:12 by samwyse")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-28.18:27:12.120>
labels = ['type-bug', 'library']
title = "argparse bug: prefix_chars argument to add_argument_group doesn't really work"
updated_at = <Date 2021-11-02.20:19:39.416>
user = 'https://bugs.python.org/samwyse'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-02.20:19:39.416>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-28.18:27:12.120>
creator = 'samwyse'
dependencies = []
files = ['50410']
hgrepos = []
issue_num = 45656
keywords = []
message_count = 3.0
messages = ['405217', '405525', '405542']
nosy_count = 2.0
nosy_names = ['samwyse', 'paul.j3']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45656'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-125379
* gh-125538
* gh-125539

**Comment by serhiy-storchaka** [comment]
The code implies that `prefix_chars`, as well as `conflict_handler` and `argument_default` can be overridden. Overriding 
the latter two makes sense, but I have difficulties with finding a use case for overriding `prefix_chars`. The group's `prefix_chars` affects how optional arguments are distinguished from positional arguments in `add_argument()` and how optional arguments are configured. But it does not affect command line parsing.

This is at least partially a documentation issue. `conflict_handler` and `argument_default` should be documented for `add_argument_group()`. And maybe `prefix_chars` if there are legitimate cases for this.

If it contains characters not in the parser's set, some options can be not recognizable as options in the command line. If it is a subset of the parser's set, you can define some weird options. For example, if the parser's `prefix_chars` is `'-+'` and the groups `prefix_chars` is just `'-'`, then `-+` is a short option. But there may be glitches in parsing the command line. No, I have no good use cases. Let keep it undocumented.

**Comment by serhiy-storchaka** [comment]
@savannahostrowski, are you interesting in this issue? I think that it is mainly a documentation issue. Some keyword-only arguments should be documented.

**Comment by savannahostrowski** [comment]
Sure thing - I have a couple other docs issues that I'm going to get squared away so I'll add this to the queue.

**Comment by serhiy-storchaka** [comment]
Now, after `conflict_handler` and `argument_default` have been documented, we can deprecate `prefix_chars`. @savannahostrowski, are you interesting? We should just add a runtime warning in the `_ArgumentGroup` constructor, test, and documentation (the `deprecated` instruction and something in What's New).

**Comment by savannahostrowski** [comment]
Yep - I can do that!

**Comment by serhiy-storchaka** [comment]
The documentation was clarified and the dubious feature (which looks simply like an implementation detail) was deprecated.
