### ISSUE TITLE
Some PGO tests are failing when building with --enable-optimizations --disable-test-modules

### ISSUE THREAD

**Issue by tiran** [python/cpython#89831]
BPO | [45668](https://bugs.python.org/issue45668)
--- | :---
Nosy | @tiran, @thesamesam
PRs | <li>python/cpython#29315</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-11-01.11:18:19.551>
created_at = <Date 2021-10-29.14:37:29.097>
labels = ['type-bug', 'tests', 'build', '3.11']
title = 'Some PGO tests are failing when building with --enable-optimizations --disable-test-modules'
updated_at = <Date 2021-11-01.11:18:19.551>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-01.11:18:19.551>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2021-11-01.11:18:19.551>
closer = 'christian.heimes'
components = ['Build', 'Tests']
creation = <Date 2021-10-29.14:37:29.097>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 45668
keywords = ['patch']
message_count = 2.0
messages = ['405308', '405425']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'thesamesam']
pr_nums = ['29315']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45668'
versions = ['Python 3.11']
```

</p></details>

**Comment by htmltiger** [comment]
@tiran this is failing again in 3.11.2 as the changes are now no longer in the file
https://github.com/python/cpython/commit/882d8096c262a5945e0cfdd706e5db3ad2b73543#r105830468

**Comment by vstinner** [comment]
> @tiran this is failing again in 3.11.2 as the changes are now no longer in the file

Hi. This issue is closed. Please open a new issue. It's even better if you propose a PR to fix the issue :-)
