### ISSUE TITLE
tkinter breaks on high resolution screen after ctypes SetProcessDPIAware()

### ISSUE THREAD

**Issue by c6c9fd4b-e1a4-4019-a457-1204227c5dc2** [python/cpython#89844]
BPO | [45681](https://bugs.python.org/issue45681)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba, @E-Paine, @GabeMillikan
Files | <li>[KwUqCTWl58.gif](https://bugs.python.org/file50413/KwUqCTWl58.gif "Uploaded as image/gif at 2021-10-31.12:12:01 by @GabeMillikan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-31.12:12:02.285>
labels = ['3.8', 'type-bug', 'expert-tkinter', 'OS-windows']
title = 'tkinter breaks on high resolution screen after ctypes SetProcessDPIAware()'
updated_at = <Date 2021-11-01.22:43:16.739>
user = 'https://github.com/GabeMillikan'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-01.22:43:16.739>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tkinter', 'Windows']
creation = <Date 2021-10-31.12:12:02.285>
creator = 'GabeMillikan'
dependencies = []
files = ['50413']
hgrepos = []
issue_num = 45681
keywords = []
message_count = 5.0
messages = ['405401', '405438', '405450', '405452', '405454']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'epaine', 'GabeMillikan']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45681'
versions = ['Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
IDLE sets the dpi awareness to 1 and that has been working for a few years without issue.  Windows installers ugraded on other issues (now 8.6.12).  Closing as 'no action' here.
