### ISSUE TITLE
SharedMemory documentation: System V vs Posix

### ISSUE THREAD

**Issue by fb56c49d-a6fe-49ac-8f6d-9b6ad0098e67** [python/cpython#89891]
BPO | [45728](https://bugs.python.org/issue45728)
--- | :---
Nosy | @terryjreedy, @pitrou, @applio, @nescio007

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-05.13:46:16.151>
labels = ['3.11', 'type-feature', '3.9', '3.10', 'docs']
title = 'SharedMemory documentation: System V vs Posix'
updated_at = <Date 2021-11-06.02:30:17.465>
user = 'https://github.com/nescio007'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-06.02:30:17.465>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-11-05.13:46:16.151>
creator = 'jkrupp'
dependencies = []
files = []
hgrepos = []
issue_num = 45728
keywords = []
message_count = 2.0
messages = ['405797', '405843']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'pitrou', 'docs@python', 'davin', 'jkrupp']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45728'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-104678
* gh-114873
* gh-114874

**Comment by torokati44** [comment]
This note in the docs also confused me (when trying to switch away from the `posix_ipc` package), and had to check the source that it is indeed "POSIX-style" instead.

See the answer by Terry Lambert here about the differences: https://www.quora.com/What-are-the-major-differences-between-System-V-and-POSIX-Shared-memory-implementations-available-on-Linux

I think that note should not reference "System V" as it is not correct, and only causes confusion.
