### ISSUE TITLE
Crash on Py_DecRef'ing builtin object from previous run

### ISSUE THREAD

**Issue by 830289f3-c246-4665-b74b-ea6077bfa558** [python/cpython#89919]
BPO | [45758](https://bugs.python.org/issue45758)
--- | :---
Nosy | @ronaldoussoren, @pablogsal, @shihai1991

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-08.23:07:35.232>
labels = ['expert-C-API', 'invalid', '3.10', '3.9', 'type-crash']
title = "Crash on Py_DecRef'ing builtin object from previous run"
updated_at = <Date 2021-11-12.18:03:36.159>
user = 'https://bugs.python.org/VictorMilovanov'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-12.18:03:36.159>
actor = 'Victor Milovanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-11-08.23:07:35.232>
creator = 'Victor Milovanov'
dependencies = []
files = []
hgrepos = []
issue_num = 45758
keywords = []
message_count = 4.0
messages = ['405987', '406075', '406204', '406228']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'pablogsal', 'shihai1991', 'Victor Milovanov']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue45758'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
> I think documentation should clarify that. Right now this line in the docs got me thinking that anything with an external strong reference won't be deallocated: "Memory tied up in circular references between objects is not freed."

There is a difference between "won't be deallocated" and "reference stays valid".   Any object reference you have is invalid after calling ``Py_Finalize``.  Calling ``Py_Initialize`` afterwards does not change that.
