### ISSUE TITLE
Race condition in WeakKeyDictionary/WeakValueDictionary

### ISSUE THREAD

**Issue by colesbury** [python/cpython#89967]
BPO | [45809](https://bugs.python.org/issue45809)
--- | :---
Nosy | @colesbury
Files | <li>[issue45809-repro.patch](https://bugs.python.org/file50440/issue45809-repro.patch "Uploaded as text/plain at 2021-11-15.19:05:22 by @colesbury"): Patch to make reproduction easier</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-15.19:02:38.373>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'Race condition in WeakKeyDictionary/WeakKeyDictionary'
updated_at = <Date 2021-11-15.19:05:22.656>
user = 'https://github.com/colesbury'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-15.19:05:22.656>
actor = 'colesbury'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-11-15.19:02:38.373>
creator = 'colesbury'
dependencies = []
files = ['50440']
hgrepos = []
issue_num = 45809
keywords = ['patch']
message_count = 2.0
messages = ['406357', '406358']
nosy_count = 1.0
nosy_names = ['colesbury']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45809'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-125325

**Comment by kumaraditya303** [comment]
FWIW I think weakrefs should entirely be re-written in C. it is really hard to write it in python without issues like this.
