### ISSUE TITLE
Document exceptions raised by fnmtach

### ISSUE THREAD

**Issue by c0f8bb0f-5dbb-452e-af65-1ca4c79ccb0d** [python/cpython#89973]
BPO | [45815](https://bugs.python.org/issue45815)
--- | :---
Nosy | @ezio-melotti, @DimitriPapadopoulos
Files | <li>[sre_constants.error_stderr.txt](https://bugs.python.org/file50442/sre_constants.error_stderr.txt "Uploaded as text/plain at 2021-11-16.10:46:44 by @DimitriPapadopoulos"): Last part of the stderr output of a Python script that calls fnmatch() on a bad glob</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-16.10:46:44.748>
labels = ['expert-regex', '3.11', 'library', 'docs']
title = 'Document exceptions raised by fnmtach'
updated_at = <Date 2021-11-16.10:46:44.748>
user = 'https://github.com/DimitriPapadopoulos'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-16.10:46:44.748>
actor = 'DimitriPapadopoulosOrfanos'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)', 'Regular Expressions']
creation = <Date 2021-11-16.10:46:44.748>
creator = 'DimitriPapadopoulosOrfanos'
dependencies = []
files = ['50442']
hgrepos = []
issue_num = 45815
keywords = []
message_count = 1.0
messages = ['406396']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'docs@python', 'DimitriPapadopoulosOrfanos']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45815'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-139405

**Comment by gpshead** [comment]
It'd also be reasonable for the `fnmatch._compile_pattern` function to be updated to catch `re.error` and internally and reraise `ValueError`. The only times this should happen are when the input pattern turns into an invalid regular expression so our code cannot use it.  So in absense of us improving fnmatch's abilities, it is an error with the user supplied value.

Or for maximum backwards compatibility, an fnmatch.PatternError class that inherits from both re.error and ValueError so that code can be written to catch either.

**Comment by serhiy-storchaka** [comment]
In what case it raises `re.error`?

**Comment by serhiy-storchaka** [comment]
I do not see how `fnmatch.fnmatch()` can raise `re.error`. If you found an example, reopen the issue.

**Comment by ezio-melotti** [comment]
> If you found an example, reopen the issue.

@DimitriPapadopoulos ^

(He might not be subscribed to the issue after the migration.)

**Comment by DimitriPapadopoulos** [comment]
That's the initial issue:
https://github.com/codespell-project/codespell/issues/2145

Here is how to reproduce it:
```python
import fnmatch
fnmatch.fnmatch("/some/random/path", "[b-a]")
```

```
$ python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> fnmatch.fnmatch("/some/random/path", "[b-a]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/fnmatch.py", line 36, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib/python3.6/fnmatch.py", line 70, in fnmatchcase
    match = _compile_pattern(pat)
  File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range b-a at position 5
>>> 
```

**Comment by DimitriPapadopoulos** [comment]
I cannot reopen this specific issue. Do I need to reopen a new one?

**Comment by serhiy-storchaka** [comment]
Thank you. Indeed, in this case `fnmatch.translate()` produces an incorrect RE.

Bash interprets this range as empty (not matching any character). `fnmatch.translate()` should be changed to produce compatible result.

**Comment by DimitriPapadopoulos** [comment]
Still, it would be nice to:
* either document that `fnmatch()` might raise a `re.error` if something goes wrong with pattern processing,
* or catch the `re.error` exception and raise a **ValueError**.

Just in case...
