### ISSUE TITLE
Python does not support standalone MSVC v143 (VS 2022) Build Tools

### ISSUE THREAD

**Issue by 173e4dcc-a6a2-4ee8-8842-143e9ac6e11f** [python/cpython#89974]
BPO | [45816](https://bugs.python.org/issue45816)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @animalize, @kumaraditya303, @thatbirdguythatuknownot
PRs | <li>python/cpython#29577</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-12-03.19:48:45.031>
created_at = <Date 2021-11-16.14:35:04.395>
labels = ['build', 'OS-windows', '3.11']
title = 'Python does not support standalone MSVC v143 (VS 2022) Build Tools'
updated_at = <Date 2021-12-03.19:48:45.031>
user = 'https://github.com/thatbirdguythatuknownot'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-03.19:48:45.031>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-12-03.19:48:45.031>
closer = 'steve.dower'
components = ['Build', 'Windows']
creation = <Date 2021-11-16.14:35:04.395>
creator = 'Crowthebird'
dependencies = []
files = []
hgrepos = []
issue_num = 45816
keywords = ['patch']
message_count = 10.0
messages = ['406405', '406411', '406464', '406475', '406518', '406635', '407356', '407382', '407384', '407599']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'malin', 'kumaraditya', 'Crowthebird']
pr_nums = ['29577']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue45816'
versions = ['Python 3.11']
```

</p></details>

**Comment by liudonghua123** [comment]
I have the similar error when build cpython on windows.

The related error messages are below.

    Project "D:\code\python\windows-python-installer\cpython\Tools\msi\launcher\launcher.wixproj" on node 1 (default targets).
    Project "D:\code\python\windows-python-installer\cpython\Tools\msi\launcher\launcher.wixproj" (1) is building "D:\code\python\windows-python-installe
    r\cpython\PCbuild\pyshellext.vcxproj" (2) on node 1 (Build target(s)).
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools f 
    or v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may up 
    grade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\code\ 
    python\windows-python-installer\cpython\PCbuild\pyshellext.vcxproj]
    Done Building Project "D:\code\python\windows-python-installer\cpython\PCbuild\pyshellext.vcxproj" (Build target(s)) -- FAILED.
    
    Done Building Project "D:\code\python\windows-python-installer\cpython\Tools\msi\launcher\launcher.wixproj" (default targets) -- FAILED.
    
    
    Build FAILED.
    
    "D:\code\python\windows-python-installer\cpython\Tools\msi\launcher\launcher.wixproj" (default target) (1) ->
    "D:\code\python\windows-python-installer\cpython\PCbuild\pyshellext.vcxproj" (Build target) (2) ->
    (PrepareForBuild target) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools 
     for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may  
    upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\cod 
    e\python\windows-python-installer\cpython\PCbuild\pyshellext.vcxproj]
    
        0 Warning(s)
        1 Error(s)

And I fixed this via install `C++(v143) Universal windows Platform ...`.

[![enter image description here][1]][1]


  [1]: https://i.sstatic.net/GPlpbDkQ.png
