### ISSUE TITLE
Custom pickler memory leak

### ISSUE THREAD

**Issue by 321b4b3e-75d5-44c9-b8ef-7555e8fd41ba** [python/cpython#89988]
BPO | [45830](https://bugs.python.org/issue45830)
--- | :---
Nosy | @douglas-raillard-arm

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-17.16:42:28.795>
labels = ['library', '3.10', 'performance']
title = 'Custom pickler memory leak'
updated_at = <Date 2021-11-17.16:42:28.795>
user = 'https://github.com/douglas-raillard-arm'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-17.16:42:28.795>
actor = 'douglas-raillard-arm'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-11-17.16:42:28.795>
creator = 'douglas-raillard-arm'
dependencies = []
files = []
hgrepos = []
issue_num = 45830
keywords = []
message_count = 1.0
messages = ['406478']
nosy_count = 1.0
nosy_names = ['douglas-raillard-arm']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue45830'
versions = ['Python 3.10']
```

</p></details>

**Comment by tigerinus** [comment]
I can verify this also happens on Python 3.9.2

I also have a demonstration of this memory leak at https://github.com/tigerinus/pickle_memory_leak_with_msgspec

**Comment by tigerinus** [comment]
> I can verify this also happens on Python 3.9.2
> 
> I also have a demonstration of this memory leak at https://github.com/tigerinus/pickle_memory_leak_with_msgspec

The issue I found turns out to be an issue of msgspec.Struct and should be fixed by https://github.com/jcrist/msgspec/pull/117
