### ISSUE TITLE
PEP 604 Union syntax does not support forward references

### ISSUE THREAD

**Issue by ca28ffc1-8e8d-4ee5-9521-4f8c91662f17** [python/cpython#90015]
BPO | [45857](https://bugs.python.org/issue45857)
--- | :---
Nosy | @gvanrossum, @ericvsmith, @Fidget-Spinner, @AlexWaygood

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-21.14:48:31.479>
labels = ['type-bug', '3.10', '3.11']
title = 'PEP 604 Union syntax does not support forward references'
updated_at = <Date 2021-11-22.16:46:08.109>
user = 'https://bugs.python.org/TNThung'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-22.16:46:08.109>
actor = 'AlexWaygood'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-11-21.14:48:31.479>
creator = 'TNThung'
dependencies = []
files = []
hgrepos = []
issue_num = 45857
keywords = []
message_count = 6.0
messages = ['406720', '406724', '406726', '406731', '406775', '406792']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'eric.smith', 'kj', 'AlexWaygood', 'TNThung']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45857'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-105366
* gh-105460
* gh-105461

**Comment by pbryan** [comment]
I have a related question about how type aliases should work.

Starting with `Union` with a forward reference as a type alias:
```
>>> from typing import Union
>>> Alias = Union[str, "Foo"]
>>> Alias
typing.Union[str, ForwardRef('Foo')]
```

With the new `UnionType`, the following is not valid:
```
>>> Alias = str | "Foo"
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'str'
```

The following is also invalid:
```
>>> from typing import ForwardRef
>>> Alias = str | ForwardRef("Foo")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'ForwardRef' 
```

Putting everything in a string seems wrong to me, because it's not evaluated as a type:
```
>>> Alias = "str | Foo"
>>> Alias
'str | Foo'
```

I would suggest enhancing `ForwardRef.__or__` to be compatible with UnionType, so that the following would be valid:
```
>>> from typing import ForwardRef
>>> Alias = str | ForwardRef("Foo")
>>> Alias
str | ForwardRef('Foo')
```

Thoughts?

**Comment by gvanrossum** [comment]
You should never use `ForwardRef` -- it was intended for internal use only. The [docs](https://docs.python.org/3/library/typing.html#typing.ForwardRef) say "This class should not be instantiated by a user, but may be used by introspection tools." (by the latter use, they mean things like `isinstance(x, typing.ForwardRef)`.

Instead, use `TypeAlias` to explicitly declare `Alias` to be a type alias, like this:
```py
from typing import TypeAlias
Alias: TypeAlias = 'str | Foo'
```

**Comment by pbryan** [comment]
> Instead, use `TypeAlias` to explicitly declare `Alias` to be a type alias, like this:

Ah, thanks.

**Comment by pbryan** [comment]
Is there some way to evaluate `TypeAlias` as a type alias at runtime?

**Comment by gvanrossum** [comment]
> Is there some way to evaluate `TypeAlias` as a type alias at runtime?

Alas not. I think earlier in the thread it was suggested that it would be a bad idea to change the runtime implementation, so we're probably stuck with this, unless you have a compelling (i.e., *real-world*) use case that needs to handle this.

**Comment by pbryan** [comment]
The easy workaround is to continue to use `Union` for now. I'll hold off on making a case to see what changes to string annotations occur (e.g. PEP 649).
