### ISSUE TITLE
Cross compiling on Linux is untested, undocumented, and broken

### ISSUE THREAD

**Issue by tiran** [python/cpython#90039]
BPO | [45881](https://bugs.python.org/issue45881)
--- | :---
Nosy | @brettcannon, @tiran, @moreati
PRs | <li>python/cpython#29752</li><li>python/cpython#29753</li><li>python/cpython#29754</li><li>python/cpython#29835</li>
Dependencies | <li>bpo-45886: Fix Program/_freeze_module for cross compiling Python</li><li>bpo-45909: sysconfig --generate-posix-vars creates wrong file when cross compiling</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-23.16:37:45.271>
labels = ['3.9', '3.10', '3.11', 'build', 'tests', 'docs']
title = 'Cross compiling on Linux is untested, undocumented, and broken'
updated_at = <Date 2021-11-29.16:23:38.440>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-29.16:23:38.440>
actor = 'christian.heimes'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Build', 'Documentation', 'Tests', 'Cross-Build']
creation = <Date 2021-11-23.16:37:45.271>
creator = 'christian.heimes'
dependencies = ['45886', '45909']
files = []
hgrepos = []
issue_num = 45881
keywords = ['patch']
message_count = 7.0
messages = ['406853', '406860', '406935', '406942', '407016', '407165', '407292']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'christian.heimes', 'docs@python', 'Alex.Willmer']
pr_nums = ['29752', '29753', '29754', '29835']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45881'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
Some improvements were applied:

- #29752

I've created follow-up issues on the devguide and buildbot repos. Suggesting to close this, as there is no more actionable items at the moment.
