### ISSUE TITLE
Frozen dataclasses with slots raise TypeError

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#90055]
BPO | [45897](https://bugs.python.org/issue45897)
--- | :---
Nosy | @ericvsmith, @treyhunner, @AlexWaygood
PRs | <li>python/cpython#29895</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2021-11-25.01:53:51.202>
labels = ['type-bug', 'library', '3.10', '3.11']
title = 'Frozen dataclasses with slots raise TypeError'
updated_at = <Date 2021-12-02.17:20:40.230>
user = 'https://github.com/treyhunner'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-02.17:20:40.230>
actor = 'AlexWaygood'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-11-25.01:53:51.202>
creator = 'trey'
dependencies = []
files = []
hgrepos = []
issue_num = 45897
keywords = ['patch']
message_count = 4.0
messages = ['406973', '406974', '406995', '407540']
nosy_count = 3.0
nosy_names = ['eric.smith', 'trey', 'AlexWaygood']
pr_nums = ['29895']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45897'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by MojoVampire** [comment]
> I believe this can be fixed by tweaking `_frozen_get_del_attr` so that `cls` in the generated `__setattr__` and `__delattr__` methods is dynamically computed (`cls = type(self)`), rather than read from a closure, as is currently the case.

It looks like this is not the approach you took, but to be clear, using `type(self)` for the `cls` argument to `super()` does not work. It *seems* to work when you just have the one class, then becomes an infinite recursion error when you subclass the class (an empty stub subclass is all you need) and try to call the method in question on an instance of the subclass.

**Comment by AlexWaygood** [comment]
> > I believe this can be fixed by tweaking `_frozen_get_del_attr` so that `cls` in the generated `__setattr__` and `__delattr__` methods is dynamically computed (`cls = type(self)`), rather than read from a closure, as is currently the case.
> 
> It looks like this is not the approach you took, but to be clear, using `type(self)` for the `cls` argument to `super()` does not work. It _seems_ to work when you just have the one class, then becomes an infinite recursion error when you subclass the class (an empty stub subclass is all you need) and try to call the method in question on an instance of the subclass.

Yes, this is why this is not the approach I took :) thanks for updating the issue though! I forgot that I'd left that comment

**Comment by ericvsmith** [comment]
Okay, I'm finally getting a chance to look at this. A few things:

- I don't think we can change this in a minor release (3.10 or 3.11, at this point).
- Is this even worth fixing? If the code had always raised AttributeError, I would be happy with it. But is the cost of disruption worth it? I realize that very few people probably actually catching this exception, and the value here is at the REPL to give a better error message. But still, there's probably more than zero people this would affect.

**Comment by ericvsmith** [comment]
I'm going to close this. If someone really feels strongly that the exception needs to change, please open a discussion on discuss.python.org. We can re-open this issue if a discussion there produces some consensus.

**Comment by sndrtj** [comment]
As a workaround, setting `__slots__` manually gives the normal, expected exception. 

E.g. 

```py
@dataclasses.dataclass(frozen=True)
class Point:
    __slots__ = ("x", "y")
    x: int
    y: int

point = Point(x=1, y=1)

point.z = 1
```

raises `dataclasses.FrozenInstanceError: cannot assign to field 'z'` instead of `TypeError: super(type, obj): obj (instance of Point) is not an instance or subtype of type (Point).`
