### ISSUE TITLE
Reintroduce bootstrap_python for freezing

### ISSUE THREAD

**Issue by tiran** [python/cpython#90108]
BPO | [45950](https://bugs.python.org/issue45950)
--- | :---
Nosy | @gvanrossum, @ronaldoussoren, @tiran, @ned-deily, @ericsnowcurrently, @pablogsal
PRs | <li>python/cpython#29859</li><li>python/cpython#29936</li><li>python/cpython#29939</li><li>python/cpython#29939</li>
Dependencies | <li>bpo-45696: &quot;Deep-freeze&quot;: skip the marshal step by generating C code</li><li>bpo-45873: Stop using bootstrap_python for deep-freeze in UNIX builds</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2021-12-01.16:26:37.476>
labels = ['type-bug', 'build', '3.11']
title = 'Reintroduce bootstrap_python for freezing'
updated_at = <Date 2021-12-07.02:25:38.567>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-07.02:25:38.567>
actor = 'ned.deily'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-12-01.16:26:37.476>
creator = 'christian.heimes'
dependencies = ['45696', '45873']
files = []
hgrepos = []
issue_num = 45950
keywords = ['patch']
message_count = 11.0
messages = ['407467', '407592', '407776', '407777', '407779', '407782', '407790', '407801', '407827', '407830', '407889']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'ronaldoussoren', 'christian.heimes', 'ned.deily', 'eric.snow', 'pablogsal']
pr_nums = ['29859', '29936', '29939', '29939']
priority = None
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45950'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-109581

**Comment by kumaraditya303** [comment]
The issue has been fixed, I am closing the issue.
