### ISSUE TITLE
Avoid calling isatty() for most open() calls

### ISSUE THREAD

**Issue by 0e9d8850-8109-40a2-b265-ee27fc9d0b8a** [python/cpython#90102]
BPO | [45944](https://bugs.python.org/issue45944)
--- | :---
Nosy | @pitrou, @benjaminp, @serhiy-storchaka, @eryksun, @collinanderson
PRs | <li>python/cpython#29870</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-01.05:08:15.763>
labels = ['3.11', 'expert-IO', 'performance']
title = 'Avoid calling isatty() for most open() calls'
updated_at = <Date 2021-12-01.11:53:13.388>
user = 'https://github.com/collinanderson'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-01.11:53:13.388>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2021-12-01.05:08:15.763>
creator = 'collinanderson'
dependencies = []
files = []
hgrepos = []
issue_num = 45944
keywords = ['patch']
message_count = 3.0
messages = ['407427', '407434', '407444']
nosy_count = 6.0
nosy_names = ['pitrou', 'benjamin.peterson', 'stutzbach', 'serhiy.storchaka', 'eryksun', 'collinanderson']
pr_nums = ['29870']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue45944'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-112495
* gh-124922
* gh-125089

**Comment by serhiy-storchaka** [comment]
One test fails with #112495 if the stdin is not a terminal. For example:
```
$ ./python -m test -v test_builtin -m test_input_no_stdout_fileno <python
...
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 2393, in test_input_no_stdout_fileno
    self.assertSequenceEqual(lines, expected)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
AssertionError: Sequences differ: ['stdin.isatty(): False', "captured: 'prompt'"] != ('stdin.isatty(): True', "captured: 'prompt'")

First differing element 0:
'stdin.isatty(): False'
'stdin.isatty(): True'

- ['stdin.isatty(): False', "captured: 'prompt'"]
? ^                 ^^^^                        ^

+ ('stdin.isatty(): True', "captured: 'prompt'")
? ^                 ^^^                        ^
```
This is because the result of `isatty()` is not constant during the lifetime of the file object. The file descriptor can be reassigned to other file or device, so it should not be cached.

#29870 uses the cached value only in `open()`, immediately after creating the FileIO object, so it is not affected by this. But it is more complex, and making it more portable will make it even more complex. How much time it saves?

**Comment by vstinner** [comment]
PR gh-112495 was closed. @serhiy-storchaka wrote:

> It does not work, because the file descriptor can be reassigned from tty to non-tty and vice versa. The result of isatty() can not be cached.

Should we close the issue?

**Comment by cmaloney** [comment]
I think it's okay to rely on the `fd` not being modified inside of `open()` which is what https://github.com/python/cpython/pull/121593 does. It doesn't cache isatty generally (any future call still does a `isatty` libc call), just says "we can skip this call/check during open if we already have enough information from `stat` that the fd isn't a TTY".

**Comment by vstinner** [comment]
Optimization implemented by change https://github.com/python/cpython/commit/cc9b9bebb2c09c475cb0f278268cce03c115eaea.
