### ISSUE TITLE
functools.singledispatch does not support Union types

### ISSUE THREAD

**Issue by f12669fb-a5e7-4e4e-8615-43546289db00** [python/cpython#90172]
BPO | [46014](https://bugs.python.org/issue46014)
--- | :---
Nosy | @rhettinger, @ambv, @uriyyo, @AlexWaygood, @evansd
PRs | <li>python/cpython#30017</li><li>python/cpython#32282</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-12-10.23:29:02.779>
created_at = <Date 2021-12-08.13:34:12.625>
labels = ['type-feature', 'library', '3.9', '3.10', '3.11']
title = 'functools.singledispatch does not support Union types'
updated_at = <Date 2022-04-03.08:22:50.956>
user = 'https://github.com/evansd'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-03.08:22:50.956>
actor = 'uriyyo'
assignee = 'none'
closed = True
closed_date = <Date 2021-12-10.23:29:02.779>
closer = 'lukasz.langa'
components = ['Library (Lib)']
creation = <Date 2021-12-08.13:34:12.625>
creator = 'evansd'
dependencies = []
files = []
hgrepos = []
issue_num = 46014
keywords = ['patch']
message_count = 6.0
messages = ['408018', '408261', '408262', '408272', '409366', '409369']
nosy_count = 6.0
nosy_names = ['rhettinger', 'wrobell', 'lukasz.langa', 'uriyyo', 'AlexWaygood', 'evansd']
pr_nums = ['30017', '32282']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46014'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
Reopening as per https://github.com/python/cpython/pull/32282#issuecomment-1095659746

**Comment by JelleZijlstra** [comment]
> ```
> >>> from typing import Optional, get_origin
> >>> get_origin(Optional[int])
> typing.Union
> ```
> 
> ^Because of that, it will work with typing.Optional as well as typing.Union and types.UnionType, yes.

It does indeed work (continuing from the OP's example):

```pycon
>>> @test.register
... def _(arg: str  | None):
...     print(f"{arg} may be a string")
... 
>>> test(None)
None may be a string
>>> test("x")
x may be a string
```

But it's not obvious that it should, because `None` isn't a type. It apparently works because `None` gets turned into `type(None)` somewhere along the way in typing.py, but this seems worth testing explicitly in `test_functools`.

So anyone up for adding a test case that uses an Optional type?

**Comment by JelleZijlstra** [comment]
Thanks @Thaddeus1499 for contributing more tests.
