### ISSUE TITLE
email.utils.parsedate_to_datetime() handling of -0000 offset

### ISSUE THREAD

**Issue by freddrake** [python/cpython#90185]
BPO | [46027](https://bugs.python.org/issue46027)
--- | :---
Nosy | @freddrake, @warsaw, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-09.18:12:25.973>
labels = ['type-bug', 'expert-email', '3.10', '3.9']
title = 'email.utils.parsedate_to_datetime() handling of -0000 offset'
updated_at = <Date 2021-12-09.18:12:25.973>
user = 'https://github.com/freddrake'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-09.18:12:25.973>
actor = 'fdrake'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['email']
creation = <Date 2021-12-09.18:12:25.973>
creator = 'fdrake'
dependencies = []
files = []
hgrepos = []
issue_num = 46027
keywords = []
message_count = 1.0
messages = ['408149']
nosy_count = 3.0
nosy_names = ['fdrake', 'barry', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46027'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by RanKKI** [comment]
It's an intentional design, as -0000 and +0000 have different meanings

https://github.com/python/cpython/blob/3a77980002845c22e5b294ca47a12d62bf5baf53/Lib/email/_parseaddr.py#L57-L66

**Comment by skirpichev** [comment]
And it seems to be documented: https://docs.python.org/3.13/library/email.utils.html#email.utils.parsedate_to_datetime
