### ISSUE TITLE
functools' singledispatch does not support GenericAlias

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#90190]
BPO | [46032](https://bugs.python.org/issue46032)
--- | :---
Nosy | @rhettinger, @ambv, @serhiy-storchaka, @miss-islington, @uriyyo, @kumaraditya303, @AlexWaygood
PRs | <li>python/cpython#30050</li><li>python/cpython#30254</li><li>python/cpython#30255</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2021-12-26.12:23:57.239>
created_at = <Date 2021-12-10.09:04:56.137>
labels = ['type-bug', '3.9', '3.10', '3.11', 'library', 'docs']
title = "functools' singledispatch does not support GenericAlias"
updated_at = <Date 2021-12-26.12:23:57.239>
user = 'https://github.com/kumaraditya303'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-26.12:23:57.239>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2021-12-26.12:23:57.239>
closer = 'serhiy.storchaka'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-12-10.09:04:56.137>
creator = 'kumaraditya'
dependencies = []
files = []
hgrepos = []
issue_num = 46032
keywords = ['patch']
message_count = 9.0
messages = ['408179', '408181', '408204', '408205', '408306', '408348', '409169', '409170', '409197']
nosy_count = 7.0
nosy_names = ['rhettinger', 'lukasz.langa', 'serhiy.storchaka', 'miss-islington', 'uriyyo', 'kumaraditya', 'AlexWaygood']
pr_nums = ['30050', '30254', '30255']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46032'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-116544
* gh-124710
* gh-124711

**Comment by Delengowski** [comment]
> It would be well worth it to improve the error message, however:
> 
> ```
> >>> from functools import singledispatch
> >>> @singledispatch
> ... def func(arg):
> ...     raise NotImplementedError
> ... 
> >>> @func.register
> ... def _(arg: list[str]):
> ...     print('Got a list of strings')
> ... 
> >>> func(1)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/functools.py", line 830, in dispatch
>     impl = dispatch_cache[cls]
>   File "/usr/local/lib/python3.9/weakref.py", line 405, in __getitem__
>     return self.data[ref(key)]
> KeyError: <weakref at 0x7f2a0d9141d0; to 'type' at 0x7f2a0e08b200 (int)>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/functools.py", line 833, in dispatch
>     impl = registry[cls]
> KeyError: <class 'int'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/functools.py", line 877, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "/usr/local/lib/python3.9/functools.py", line 835, in dispatch
>     impl = _find_impl(cls, registry)
>   File "/usr/local/lib/python3.9/functools.py", line 782, in _find_impl
>     mro = _compose_mro(cls, registry.keys())
>   File "/usr/local/lib/python3.9/functools.py", line 743, in _compose_mro
>     types = [n for n in types if is_related(n)]
>   File "/usr/local/lib/python3.9/functools.py", line 743, in <listcomp>
>     types = [n for n in types if is_related(n)]
>   File "/usr/local/lib/python3.9/functools.py", line 742, in is_related
>     and issubclass(cls, typ))
> TypeError: issubclass() argument 2 cannot be a parameterized generic
> ```

I came across this today, and I was quite surprised I could not do this but then it made sense since we cannot do `isinstance` on `GenericAlias`. It certainly makes the idea of using `functools.singledispatch` less appealing. If I had 3.10 available to me I would just use match case.

I see there is still no documentation stating this is not supported. https://docs.python.org/3/library/functools.html#functools.singledispatch

Proposal, I'll create a PR adding an example with additional example of how to properly type hint it correctly? I'm not sure if there even is a way to properly type hint that a function takes a `list[str]` while still dispatching using that type hint and not just `list`

i.e.
```
@singledispatch
def func(x):
    print("any")

@func.register
def _(x: list[str]):
    print("list[str]")
```

raises error `TypeError: Invalid annotation for 'a'. list[str] is not a class.` but I'm not sure of a way to actually type hint that `func` should take a `list[str]` and not just a `list`.

**Comment by AlexWaygood** [comment]
If you want to use type hints with generics in a singledispatch function, I'd recommend doing something like this:

```py
@singledispatch
def func(x):
    print("any")

@func.register(list)
def _(x: list[str]):
    print("list[str]")
```

A PR to improve the docs would be welcome. If you ping me on the PR, I can review it.
