### ISSUE TITLE
Permalinks to underscored documentation entries don't work.

### ISSUE THREAD

**Issue by 6bb5900f-8be1-497f-adaf-0916c9cfac7c** [python/cpython#90222]
BPO | [46064](https://bugs.python.org/issue46064)
--- | :---
Nosy | @merwok, @AlexWaygood

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-13.13:14:42.171>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = "Permalinks to underscored documentation entries don't work."
updated_at = <Date 2021-12-17.19:04:51.264>
user = 'https://bugs.python.org/FabianDill'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-17.19:04:51.264>
actor = 'eric.araujo'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-12-13.13:14:42.171>
creator = 'Fabian Dill'
dependencies = []
files = []
hgrepos = []
issue_num = 46064
keywords = []
message_count = 3.0
messages = ['408451', '408452', '408809']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'docs@python', 'Fabian Dill', 'AlexWaygood']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46064'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by slateny** [comment]
I also can't reproduce this one on Windows + Chrome/Firefox. [This link here](https://docs.python.org/3/library/constants.html#debug__) is what I get for a perma link, and it does jump and highlight `__debug__` on my end:
![image](https://user-images.githubusercontent.com/46876382/189604775-8fec44be-6bf9-44f1-b7b5-078e80256b27.png)

**Comment by merwok** [comment]
Recent sphinx must have fixed the ID generation, now it’s `debug__`.  Thanks for checking, this is fixed.
