### ISSUE TITLE
[docs] IO > Text Encoding info outdated

### ISSUE THREAD

**Issue by 8cabb5f9-2fd8-4297-ac91-6dcbb284e954** [python/cpython#90301]
BPO | [46143](https://bugs.python.org/issue46143)
--- | :---
Nosy | @methane, @eryksun, @davidgilbertson

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-21.04:42:17.894>
labels = ['type-bug', '3.10', 'docs']
title = '[docs] IO > Text Encoding info outdated'
updated_at = <Date 2021-12-21.09:07:08.224>
user = 'https://github.com/davidgilbertson'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-21.09:07:08.224>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-12-21.04:42:17.894>
creator = 'gilbertson.david'
dependencies = []
files = []
hgrepos = []
issue_num = 46143
keywords = []
message_count = 3.0
messages = ['408983', '408985', '408993']
nosy_count = 4.0
nosy_names = ['methane', 'docs@python', 'eryksun', 'gilbertson.david']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46143'
versions = ['Python 3.10']
```

</p></details>

**Comment by slateny** [comment]
Is there anything to change on the `os` docs then since the comments on `... use the UTF-8 encoding` apply when UTF-8 mode is enabled only? Or should it be clarified, so something like

`... other higher level APIs also exhibit different default behaviours [if UTF-8 mode is enabled:]`

**Comment by methane** [comment]
[PEP 686](https://peps.python.org/pep-0686/) has been accepted.
There *is* a plan to enable UTF-8 mode by default for now.

It is better to update 3.11 and 3.12 document about PEP 686.

**Comment by orsenthil** [comment]
> It is better to update 3.11 and 3.12 document about PEP 686.

SGTM. Thank you.
