### ISSUE TITLE
python --help output is too long

### ISSUE THREAD

**Issue by merwok** [python/cpython#90300]
BPO | [46142](https://bugs.python.org/issue46142)
--- | :---
Nosy | @warsaw, @vstinner, @merwok, @serhiy-storchaka, @eryksun
PRs | <li>python/cpython#30331</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

Linked PRs:

- #93415

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-20.23:43:15.950>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'python --help output is too long'
updated_at = <Date 2022-01-12.01:45:18.299>
user = 'https://github.com/merwok'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-12.01:45:18.299>
actor = 'eric.araujo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-12-20.23:43:15.950>
creator = 'eric.araujo'
dependencies = []
files = []
hgrepos = []
issue_num = 46142
keywords = ['patch']
message_count = 15.0
messages = ['408981', '408982', '409449', '409450', '409470', '409483', '409738', '409890', '409928', '410052', '410203', '410207', '410238', '410239', '410378']
nosy_count = 5.0
nosy_names = ['barry', 'vstinner', 'eric.araujo', 'serhiy.storchaka', 'eryksun']
pr_nums = ['30331']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46142'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-93415
* gh-115847
* gh-115853
* gh-116418
* gh-116721
* gh-116724
* gh-116725
* gh-116739
* gh-116756
* gh-116765
* gh-116766
* gh-116779
* gh-116786
* gh-116796
* gh-116797
* gh-116803
* gh-117022
* gh-117034
* gh-117035

**Comment by merwok** [comment]
I have extracted some bugfixes to ticket #93217 and PR #93219

**Comment by erlend-aasland** [comment]
@merwok, you reopened this in 2022; what is the remaining actionable items?

**Comment by merwok** [comment]
There is an open PR from Serhiy with some discussion / disagreement on reformatting IIRC.

**Comment by serhiy-storchaka** [comment]
#115847 simply reformatted existing help, without significant changes in the text, #115853 fixes and shortened the text. It adds missed variables and references and remove too verbose descriptions.

The CLI help should be short. It is a list of options and environment variables with short descriptions to have some idea what they are about. Ideally, every option description should be a single line. If you want to learn details, you should read the documentation. The CLI help is just to remind you exact names and format of some options and environment variables.

**Comment by hugovk** [comment]
The Command Line Interface Guidelines have a detailed section on help text:

* https://clig.dev/#help

(They suggest a concise help by default, when `-h` or `--help` not passed. This does not apply to Python.) 

They suggest showing full help when `-h` or `--help` is passed, including:

* link to web version of the docs
* lead with examples
* display most common flags/options at the start
* use formatting for readability

I would especially like us to use bold/colour formatting, which should be controllable via the new colour env vars: https://docs.python.org/3.13/using/cmdline.html#using-on-controlling-color

**Comment by ericsnowcurrently** [comment]
> The Command Line Interface Guidelines have a detailed section on help text:
> 
> * https://clig.dev/#help

That's a fantastic resource.  Thanks for pointing it out.
