### ISSUE TITLE
[C API] Get "self" args or non-null co_varnames from frame object with C-API

### ISSUE THREAD

**Issue by 44140769-2ebc-4310-a2f4-8665db53fe05** [python/cpython#90324]
BPO | [46166](https://bugs.python.org/issue46166)
--- | :---
Nosy | @terryjreedy, @gpshead, @vstinner, @markshannon, @ericsnowcurrently, @henryiii, @pablogsal, @Skylion007
PRs | <li>python/cpython#31198</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-23.19:33:30.242>
labels = ['expert-C-API', 'type-feature', '3.11']
title = '[C API] Get "self" args or non-null co_varnames from frame object with C-API'
updated_at = <Date 2022-02-07.16:46:31.649>
user = 'https://github.com/Skylion007'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-07.16:46:31.649>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-12-23.19:33:30.242>
creator = 'Skylion007'
dependencies = []
files = []
hgrepos = []
issue_num = 46166
keywords = ['patch', '3.11regression']
message_count = 15.0
messages = ['409100', '409162', '411902', '411906', '411908', '412206', '412208', '412210', '412528', '412547', '412761', '412762', '412763', '412764', '412768']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'gregory.p.smith', 'vstinner', 'Mark.Shannon', 'eric.snow', 'Henry Schreiner', 'pablogsal', 'Skylion007']
pr_nums = ['31198']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46166'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
It seems that with @vstinner 's suggestions the immediate problem was resolved. Is there a longer term concern here? Is this similar to https://github.com/python/cpython/issues/89410?

**Comment by vstinner** [comment]
Python 3.12 added PyFrame_GetVar() and PyFrame_GetVarString(). You can use https://pythoncapi-compat.readthedocs.io/ to get these functions on older Python versions.

I gave examples on how to get the `f_locals` attribute of a frame object.

Python now has a wider C API to access PyFrameObject members: https://docs.python.org/dev/c-api/frame.html

Finally, https://docs.python.org/dev/whatsnew/3.11.html#whatsnew311-c-api-porting documents how to replace removed PyFrameObject members with function calls.

I close the issue.
