### ISSUE TITLE
Optimize builtin functions min() and max()

### ISSUE THREAD

**Issue by accec968-4cc5-4665-bf48-0da6b8042d0e** [python/cpython#90350]
BPO | [46192](https://bugs.python.org/issue46192)
--- | :---
Nosy | @sweeneyde, @erlend-aasland, @colorfulappl
PRs | <li>python/cpython#30286</li>
Files | <li>[bench-minmax.py](https://bugs.python.org/file50528/bench-minmax.py "Uploaded as text/plain at 2021-12-30.13:06:30 by @erlend-aasland")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-29.10:04:55.181>
labels = ['interpreter-core', '3.11', 'performance']
title = 'Optimize builtin functions min() and max()'
updated_at = <Date 2021-12-31.14:22:47.367>
user = 'https://github.com/colorfulappl'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-31.14:22:47.367>
actor = 'Dennis Sweeney'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-12-29.10:04:55.181>
creator = 'colorfulappl'
dependencies = []
files = ['50528']
hgrepos = []
issue_num = 46192
keywords = ['patch']
message_count = 3.0
messages = ['409299', '409367', '409421']
nosy_count = 3.0
nosy_names = ['Dennis Sweeney', 'erlendaasland', 'colorfulappl']
pr_nums = ['30286']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue46192'
versions = ['Python 3.11']
```

</p></details>

**Comment by arhadthedev** [comment]
@erlend-aasland Would you mind to publish https://github.com/erlend-aasland/cpython/tree/gh-30286-ac you mentioned as a PR, please? It will be a great opportunity to close gh-30286 and resolve this issue for good.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @colorfulappl.
