### ISSUE TITLE
3.11: Tracing of decorators now visits the decorator line before the decorator function

### ISSUE THREAD

**Issue by nedbat** [python/cpython#90392]
BPO | [46234](https://bugs.python.org/issue46234)
--- | :---
Nosy | @nedbat, @markshannon

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-02.23:14:57.596>
labels = ['interpreter-core', 'type-bug', '3.11']
title = '3.11: Tracing of decorators now visits the decorator line before the decorator function'
updated_at = <Date 2022-01-02.23:14:57.596>
user = 'https://github.com/nedbat'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-02.23:14:57.596>
actor = 'nedbat'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-01-02.23:14:57.596>
creator = 'nedbat'
dependencies = []
files = []
hgrepos = []
issue_num = 46234
keywords = ['3.11regression']
message_count = 1.0
messages = ['409539']
nosy_count = 2.0
nosy_names = ['nedbat', 'Mark.Shannon']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46234'
versions = ['Python 3.11']
```

</p></details>

**Comment by sweeneyde** [comment]
I verified that the change is from https://github.com/python/cpython/pull/30027. It looks like that could still be backported to 3.10?

I think the tracing behavior here is a natural consequence of wanting tracebacks to include the decorator line: in order for that to happen, the call instruction has be associated to that line, and so some line trace event has to be generated. Unless we wanted to add a special case to the line-tracing logic in ceval.c, which I'm not sure we want.

cc @ambv

**Comment by ambv** [comment]
The change is intentional, yes.

I changed my mind since #30027 about whether this should be backported. It's a somewhat of an edge case to call the change there a bug fix. It's an improvement but also a change that Ned noticed. It's much easier to work around it in third-party software is the check required is simply `>= 3.11.0`. So we won't be bringing this to Python 3.10.
