### ISSUE TITLE
About vulnerabilities in Cpython native code

### ISSUE THREAD

**Issue by e4c45f66-5c87-4614-bb74-c430e0d79e44** [python/cpython#90438]
BPO | [46280](https://bugs.python.org/issue46280)
--- | :---
Nosy | @rhettinger, @terryjreedy, @vstinner, @ericvsmith, @serhiy-storchaka, @pablogsal, @miss-islington, @nanjekyejoannah
PRs | <li>python/cpython#30445</li><li>python/cpython#30591</li><li>python/cpython#30592</li><li>python/cpython#30593</li>
Files | <li>[CPython3.10.0_vulnerability_report.txt](https://bugs.python.org/file50544/CPython3.10.0_vulnerability_report.txt "Uploaded as text/plain at 2022-01-06.13:07:47 by urnotmax")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-06.13:07:52.809>
labels = ['type-security', 'build', '3.10', '3.11']
title = 'About vulnerabilities in Cpython native code'
updated_at = <Date 2022-01-14.04:35:25.101>
user = 'https://bugs.python.org/urnotmax'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-14.04:35:25.101>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2022-01-06.13:07:52.809>
creator = 'urnotmax'
dependencies = []
files = ['50544']
hgrepos = []
issue_num = 46280
keywords = ['patch']
message_count = 26.0
messages = ['409841', '409854', '409859', '409868', '409884', '409895', '409902', '409904', '409907', '409909', '409911', '409912', '409918', '409921', '409922', '409923', '409925', '409926', '409927', '409929', '409930', '409933', '410539', '410540', '410541', '410542']
nosy_count = 8.0
nosy_names = ['rhettinger', 'terry.reedy', 'vstinner', 'eric.smith', 'serhiy.storchaka', 'pablogsal', 'miss-islington', 'nanjekyejoannah']
pr_nums = ['30445', '30591', '30592', '30593']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue46280'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by alittlesir** [comment]
any question about this issue? if not, i think it is better to close it
