### ISSUE TITLE
protocol_version in http.server.test can be ignored

### ISSUE THREAD

**Issue by f19b7009-4c1c-4642-bb8f-335eca04421b** [python/cpython#90443]
BPO | [46285](https://bugs.python.org/issue46285)
--- | :---
Nosy | @merwok, @matrixise, @JelleZijlstra, @maggyero, @openalmeida
PRs | <li>python/cpython#30999</li>
Dependencies | <li>bpo-46436: Pass the -d/--directory command-line option to http.server.CGIHTTPRequestHandler</li>
Files | <li>[my_http.py](https://bugs.python.org/file50551/my_http.py "Uploaded as text/plain at 2022-01-08.19:41:59 by @openalmeida")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-06.18:39:21.504>
labels = ['type-feature', 'library', '3.11']
title = 'protocol_version in http.server.test can be ignored'
updated_at = <Date 2022-02-03.15:57:34.891>
user = 'https://github.com/openalmeida'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-03.15:57:34.891>
actor = 'eric.araujo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-06.18:39:21.504>
creator = 'openalmeida'
dependencies = ['46436']
files = ['50551']
hgrepos = []
issue_num = 46285
keywords = ['patch']
message_count = 11.0
messages = ['409894', '409899', '410012', '410015', '410107', '410161', '410163', '411310', '411392', '411841', '411887']
nosy_count = 5.0
nosy_names = ['eric.araujo', 'matrixise', 'JelleZijlstra', 'maggyero', 'openalmeida']
pr_nums = ['30999']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46285'
versions = ['Python 3.11']
```

</p></details>

**Comment by merwok** [comment]
#30999 was merged.  Thanks to all!
