### ISSUE TITLE
Sixth element of tuple from __reduce__(), inconsistency between pickle and copy

### ISSUE THREAD

**Issue by 0cb8e62c-2147-4256-a1a5-5e2ca7668bf9** [python/cpython#90494]
BPO | [46336](https://bugs.python.org/issue46336)
--- | :---
Nosy | @rhettinger, @pitrou, @serhiy-storchaka, @iritkatriel
Files | <li>[reduce.py](https://bugs.python.org/file50554/reduce.py "Uploaded as text/plain at 2022-01-10.21:41:04 by lev.bishop")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-10.21:41:04.524>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'Sixth element of tuple from __reduce__(), inconsistency between pickle and copy'
updated_at = <Date 2022-01-10.22:33:13.389>
user = 'https://bugs.python.org/levbishop'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-10.22:33:13.389>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-10.21:41:04.524>
creator = 'lev.bishop'
dependencies = []
files = ['50554']
hgrepos = []
issue_num = 46336
keywords = []
message_count = 2.0
messages = ['410256', '410262']
nosy_count = 5.0
nosy_names = ['rhettinger', 'pitrou', 'serhiy.storchaka', 'iritkatriel', 'lev.bishop']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46336'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The code was written with expectation that `__reduce__()` returns 2 to 5 items. The `deepcopy` parameter was not designed to be overridden, it was a pure microoptimization (access to a global). The simplest correct solution is either to make it keyword-only, or remove it at all.

There is only one vague test for the 6th item of `__reduce__()`, so I hesitate to implement its support for `copy`.

**Comment by nneonneo** [comment]
I just ran into this bug. Why can't we just add support for the sixth `setstate` arg by testing for it before `if hasattr(y, '__setstate__'):`? Something like this:

```diff
--- copy.py.old	2022-09-27 12:30:15.000000000 -0700
+++ copy.py.new	2022-09-27 12:30:44.000000000 -0700
@@ -258,7 +258,7 @@
 
 def _reconstruct(x, memo, func, args,
                  state=None, listiter=None, dictiter=None,
-                 *, deepcopy=deepcopy):
+                 setstate=None, *, deepcopy=deepcopy):
     deep = memo is not None
     if deep and args:
         args = (deepcopy(arg, memo) for arg in args)
@@ -269,7 +269,9 @@
     if state is not None:
         if deep:
             state = deepcopy(state, memo)
-        if hasattr(y, '__setstate__'):
+        if setstate is not None:
+            setstate(y, state)
+        elif hasattr(y, '__setstate__'):
             y.__setstate__(state)
         else:
             if isinstance(state, tuple) and len(state) == 2:
```

I think this would be a cleaner fix; I doubt anyone is depending on passing a different `deepcopy` as the sixth argument because it would directly break pickling.

The test case I'm using:

```python
import pickle
import copy

class X:
    def setstate(self, state):
        # This is passed {"x": 42} as expected with pickle,
        # but is incorrectly passed the memo object with copy
        print(self, state)
        self.__dict__.update(state)

    def __reduce__(self):
        return (X, (), dict(x=42), iter([]), iter([]), X.setstate)

print("Pickle:")
print(pickle.loads(pickle.dumps(X())))
print("Deepcopy:")
print(copy.deepcopy(X()))
```

**Comment by serhiy-storchaka** [comment]
It would be not safer to add the `setstate` in a bugfix release, because the code written with intention of using this feature would could work incorrectly (producing a wrong result rather than failing) in older releases. This should be considered as a new feature and only added in a new feature release (3.12). Please open a new issue for this.
