### ISSUE TITLE
asyncio.create_subprocess_exec throws RuntimeError yet still executes subprogram

### ISSUE THREAD

**Issue by baa0fc1d-1ea7-4ba4-8d7c-ce23bc3f5a01** [python/cpython#90493]
BPO | [46335](https://bugs.python.org/issue46335)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[example](https://bugs.python.org/file50553/example "Uploaded as text/plain at 2022-01-10.18:55:53 by Clint Olsen")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-10.18:55:53.538>
labels = ['3.9', 'expert-asyncio']
title = 'asyncio.create_subprocess_exec throws RuntimeError yet still executes subprogram'
updated_at = <Date 2022-01-12.17:27:53.099>
user = 'https://bugs.python.org/ClintOlsen'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-12.17:27:53.099>
actor = 'Clint Olsen'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2022-01-10.18:55:53.538>
creator = 'Clint Olsen'
dependencies = []
files = ['50553']
hgrepos = []
issue_num = 46335
keywords = []
message_count = 5.0
messages = ['410242', '410285', '410321', '410391', '410417']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'Clint Olsen']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46335'
versions = ['Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
`PidfdChildWatcher` is the best solution here as it avoids threads altogether, but the solution depends on your Linux kernel version. This isn't a bug as it can be fixed by changing the child watcher.
