### ISSUE TITLE
Makefile missing '/' for some path names

### ISSUE THREAD

**Issue by 2a8649c6-7941-4e1c-a7d3-2840faf4cd5f** [python/cpython#90509]
BPO | [46351](https://bugs.python.org/issue46351)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @zware, @gwolski

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-11.23:32:47.369>
labels = ['OS-mac', 'type-bug', 'expert-installation', '3.9', '3.10']
title = "Makefile missing '/' for some path names"
updated_at = <Date 2022-01-12.16:45:39.368>
user = 'https://github.com/gwolski'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-12.16:45:39.368>
actor = 'zach.ware'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'macOS']
creation = <Date 2022-01-11.23:32:47.369>
creator = 'gwolski'
dependencies = []
files = []
hgrepos = []
issue_num = 46351
keywords = []
message_count = 2.0
messages = ['410356', '410413']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'zach.ware', 'gwolski']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'backport needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46351'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
#28659 is the PR that fixed this in main (and was included in 3.11)

I don't think it is worthwhile to spend time on a back port for the 3.10 branch, especially as the procedural issue with the PR was that there's an invalid NEWS entry. I'm therefore closing the issue.
