### ISSUE TITLE
re.sub, re.Match.expand, etc doesn't allow x, u, U, or N escapes in the template

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#90508]
BPO | [46350](https://bugs.python.org/issue46350)
--- | :---
Nosy | @stevendaprano, @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-11.22:10:12.175>
labels = ['type-bug']
title = "re.sub, re.Match.expand, etc doesn't allow x, u, U, or N escapes in the template"
updated_at = <Date 2022-01-11.22:21:30.194>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-11.22:21:30.194>
actor = 'steven.daprano'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-01-11.22:10:12.175>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 46350
keywords = []
message_count = 2.0
messages = ['410337', '410340']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'bup']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46350'
versions = []
```

</p></details>

**Comment by arhadthedev** [comment]
The following points really hold true for template parameters:

- > Unicode guarantees that code point names are ASCII
- > I can't imagine the Unicode consortium ever deciding on a name > 255 characters, it wouldn't be practical

So the reported failure happens only when the fixed lookup would fail too. As a result, the bugfix will not change observable behavior and become dead code.
