### ISSUE TITLE
PyMapping_Check returns 1 for list

### ISSUE THREAD

**Issue by 744d82b5-30ef-4294-8536-1bb4ff002786** [python/cpython#90534]
BPO | [46376](https://bugs.python.org/issue46376)
--- | :---
Nosy | @birkenfeld, @rhettinger, @pitrou, @benjaminp, @encukou, @methane, @bukzor, @aganders3, @serhiy-storchaka, @ilevkivskyi, @bharel, @miss-islington, @brandtbucher, @aviramha, @bentheiii
PRs | <li>python/cpython#30600</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-14.11:12:18.063>
labels = ['expert-C-API', 'type-feature', '3.11']
title = 'PyMapping_Check returns 1 for list'
updated_at = <Date 2022-01-25.09:43:02.608>
user = 'https://github.com/aviramha'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-25.09:43:02.608>
actor = 'avrahami.ben'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-01-14.11:12:18.063>
creator = 'aviramha'
dependencies = []
files = []
hgrepos = []
issue_num = 46376
keywords = ['patch']
message_count = 23.0
messages = ['410555', '410556', '410557', '410564', '410566', '410585', '410618', '410619', '410621', '410622', '410624', '410626', '410627', '410629', '410632', '410633', '410944', '410949', '410951', '411363', '411387', '411422', '411568']
nosy_count = 15.0
nosy_names = ['georg.brandl', 'rhettinger', 'pitrou', 'benjamin.peterson', 'petr.viktorin', 'methane', 'bukzor', 'aganders3', 'serhiy.storchaka', 'levkivskyi', 'bar.harel', 'miss-islington', 'brandtbucher', 'aviramha', 'avrahami.ben']
pr_nums = ['30600']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46376'
versions = ['Python 3.11']
```

</p></details>

**Comment by rhettinger** [comment]
Marking this as closed:
* The PR was a breaking change.   
* The API has existed in its current form for long time without constraining development.
* The API is dead-end in that it is not always possible to recognize a mapping and this cannot be made into a portable, reliable feature.
* We would have deprecated this a long time ago but didn't want to break any code that happened to be working.
* C code that wants mapping recognition should follow the new norms established by structural pattern matching or it should use ABCs if it needs a tighter promise.
* I'm sympathetic to wanting this function to magically just work, but I've worked on it over the last two decades and have concluded that it cannot be done reliably and portably, and that the API should be abandoned rather that leading people down an untenable path.
