### ISSUE TITLE
Improve documentation of CFLAGS_NODIST, LDFLAGS_NODIST

### ISSUE THREAD

**Issue by 52d8245c-ae1c-4ba3-96ff-21e95163c0f3** [python/cpython#90539]
BPO | [46381](https://bugs.python.org/issue46381)
--- | :---
Nosy | @vstinner, @DiddiLeija

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-14.18:38:16.475>
labels = ['3.11', 'type-feature', '3.9', '3.10', 'docs']
title = 'Improve documentation of CFLAGS_NODIST, LDFLAGS_NODIST'
updated_at = <Date 2022-01-17.15:21:27.848>
user = 'https://bugs.python.org/matthiaskoeppe'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-17.15:21:27.848>
actor = 'vstinner'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-01-14.18:38:16.475>
creator = 'matthiaskoeppe'
dependencies = []
files = []
hgrepos = []
issue_num = 46381
keywords = []
message_count = 2.0
messages = ['410586', '410799']
nosy_count = 4.0
nosy_names = ['vstinner', 'docs@python', 'DiddiLeija', 'matthiaskoeppe']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46381'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by mkoeppe** [comment]
@jaraco Is there setuptools/distutils documentation that we can refer to explain how sysconfig `CFLAGS` and `LDFLAGS` are used?

**Comment by native-api** [comment]
As I mentioned in https://github.com/pyenv/pyenv/issues/2204#issuecomment-1007105864, the core user problem that led to this suggestion seems to be that sometimes, an extension needs to override the core's complier flags -- e.g. when it wants to build a private version of a library that's already installed system-wide.

So the logical way to go seems to allow extensions do that.
Trying to instead filter out anything from core flags that could ever possibly interfere with any package whatsoever seems like an exercise in futility.
If there are flags that CPython's build logic itself sets that are deemed inappropriate to force onto extensions, too -- e.g. the aforementioned `-Werror` (I've no opinion if these are appropriate, it's just an example) -- the build should exclude them from flags passed to extensions itself.

**Comment by mkoeppe** [comment]
> So the logical way to go seems to allow extensions do that.

New mechanisms are not needed, downstream packagers of Python just need to configure CPython correctly using the existing mechanisms (`CFLAGS_NODIST`, `LDFLAGS_NODIST`) that have been created for this very purpose.

**Comment by mkoeppe** [comment]
> Various downstream packagers have provided misconfigured Pythons:
> 
> * Homebrew (https://trac.sagemath.org/ticket/31132, [Python: Change Homebrew includes into NODIST flags Homebrew/homebrew-core#68528](https://github.com/Homebrew/homebrew-core/pull/68528), resolved)
> * Cygwin (https://trac.sagemath.org/ticket/33078, https://cygwin.com/pipermail/cygwin/2021-December/250302.html, resolved in a proposed package update)
> * pyenv (https://trac.sagemath.org/ticket/32531, [pythons built with pyenv's python-build leak CFLAGS/LDFLAGS into user packages via sysconfig pyenv/pyenv#2204](https://github.com/pyenv/pyenv/issues/2204), open)

Also:
* conda (https://trac.sagemath.org/ticket/31539) @isuruf

**Comment by jaraco** [comment]
> @jaraco Is there setuptools/distutils documentation that we can refer to explain how sysconfig `CFLAGS` and `LDFLAGS` are used?

It appears not. Distutils docs have been migrated to [setuptools docs](https://setuptools.readthedocs.io). When I searched there, I got no results, so it appears to be undocumented. I'd appreciate contributions in this area, especially if you invest the time to discover the details based on the code.

**Comment by vstinner** [comment]
Current documentation:

* https://docs.python.org/dev/using/configure.html#envvar-CFLAGS_NODIST
* https://docs.python.org/dev/using/configure.html#envvar-PY_CFLAGS_NODIST
* https://docs.python.org/dev/using/configure.html#envvar-LDFLAGS_NODIST
* https://docs.python.org/dev/using/configure.html#envvar-PY_LDFLAGS_NODIST

**Comment by mkoeppe** [comment]
> Current documentation:
> 
> * https://docs.python.org/dev/using/configure.html#envvar-CFLAGS_NODIST
> * https://docs.python.org/dev/using/configure.html#envvar-PY_CFLAGS_NODIST
> * https://docs.python.org/dev/using/configure.html#envvar-LDFLAGS_NODIST
> * https://docs.python.org/dev/using/configure.html#envvar-PY_LDFLAGS_NODIST

Yes, this is what my PR #90539 extends.

**Comment by mkoeppe** [comment]
> > @jaraco Is there setuptools/distutils documentation that we can refer to explain how sysconfig `CFLAGS` and `LDFLAGS` are used?
> 
> It appears not. Distutils docs have been migrated to [setuptools docs](https://setuptools.readthedocs.io). When I searched there, I got no results, so it appears to be undocumented. I'd appreciate contributions in this area, especially if you invest the time to discover the details based on the code.

I'll prepare a PR. Is it already possible to refer to the (sparse) docstrings such as those found in https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/unixccompiler.py? (Is it formatted with sphinx somewhere?)

**Comment by vstinner** [comment]
> Yes, this is what my PR https://github.com/python/cpython/issues/90539 extends.

The link is this issue, not a PR. I'm confused.

**Comment by mkoeppe** [comment]
> > Yes, this is what my PR #90539 extends.
> 
> The link is this issue, not a PR. I'm confused.

Sorry, edited. I meant https://github.com/python/cpython/pull/92754

**Comment by mkoeppe** [comment]
> > @jaraco Is there setuptools/distutils documentation that we can refer to explain how sysconfig `CFLAGS` and `LDFLAGS` are used?
> 
> It appears not. Distutils docs have been migrated to [setuptools docs](https://setuptools.readthedocs.io). When I searched there, I got no results, so it appears to be undocumented. I'd appreciate contributions in this area, especially if you invest the time to discover the details based on the code.

That's now https://github.com/pypa/setuptools/pull/3368
