### ISSUE TITLE
Multiple test modules fail to run if invoked directly

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#90583]
BPO | [46425](https://bugs.python.org/issue46425)
--- | :---
Nosy | @terryjreedy, @jaraco, @asvetlov, @ethanfurman, @zware, @serhiy-storchaka, @corona10, @miss-islington, @sobolevn
PRs | <li>python/cpython#30666</li><li>python/cpython#30676</li><li>python/cpython#30681</li><li>python/cpython#30682</li><li>python/cpython#30699</li><li>python/cpython#30700</li><li>python/cpython#30725</li><li>python/cpython#30746</li><li>python/cpython#30782</li><li>python/cpython#30783</li><li>python/cpython#30792</li><li>python/cpython#30799</li><li>python/cpython#30800</li><li>python/cpython#30802</li><li>python/cpython#30803</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-18.18:41:39.303>
labels = ['type-bug', 'tests', '3.9', '3.10', '3.11']
title = 'Multiple test modules fail to run if invoked directly'
updated_at = <Date 2022-01-23.02:38:46.011>
user = 'https://github.com/sobolevn'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-23.02:38:46.011>
actor = 'jaraco'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2022-01-18.18:41:39.303>
creator = 'sobolevn'
dependencies = []
files = []
hgrepos = []
issue_num = 46425
keywords = ['patch']
message_count = 18.0
messages = ['410879', '410880', '410881', '410886', '410887', '410911', '410924', '410999', '411000', '411088', '411247', '411250', '411252', '411264', '411265', '411266', '411267', '411334']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'jaraco', 'asvetlov', 'ethan.furman', 'zach.ware', 'serhiy.storchaka', 'corona10', 'miss-islington', 'sobolevn']
pr_nums = ['30666', '30676', '30681', '30682', '30699', '30700', '30725', '30746', '30782', '30783', '30792', '30799', '30800', '30802', '30803']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46425'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
@sobolevn Is this fixed now or are there more modules left?
