### ISSUE TITLE
Regression caused by CALL_FUNCTION specialization for C function calls (test_urllib fails when run multiple times)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#90623]
BPO | [46465](https://bugs.python.org/issue46465)
--- | :---
Nosy | @gvanrossum, @vstinner, @markshannon, @ericsnowcurrently, @corona10, @brandtbucher, @sobolevn, @Fidget-Spinner
PRs | <li>python/cpython#30826</li><li>python/cpython#31404</li>
Files | <li>[bug.py](https://bugs.python.org/file50575/bug.py "Uploaded as text/plain at 2022-01-22.02:18:28 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-22.01:30:09.079>
labels = ['release-blocker', 'tests', '3.11']
title = 'Regression caused by CALL_FUNCTION specialization for C function calls (test_urllib fails when run multiple times)'
updated_at = <Date 2022-02-18.11:00:24.942>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-18.11:00:24.942>
actor = 'sobolevn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2022-01-22.01:30:09.079>
creator = 'vstinner'
dependencies = []
files = ['50575']
hgrepos = []
issue_num = 46465
keywords = ['patch', '3.11regression']
message_count = 14.0
messages = ['411217', '411219', '411220', '411288', '411348', '411349', '411364', '411366', '411367', '411369', '411370', '411371', '411461', '411652']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'vstinner', 'Mark.Shannon', 'eric.snow', 'corona10', 'brandtbucher', 'sobolevn', 'kj']
pr_nums = ['30826', '31404']
priority = 'release blocker'
resolution = None
stage = 'patch review'
status = 'pending'
superseder = None
type = None
url = 'https://bugs.python.org/issue46465'
versions = ['Python 3.11']
```

</p></details>

**Comment by Fidget-Spinner** [comment]
@vstinner this bug is fixed after https://github.com/python/cpython/pull/31404 right? Can this be closed?

**Comment by vstinner** [comment]
> @vstinner this bug is fixed after https://github.com/python/cpython/pull/31404 right? Can this be closed?

I wanted to enhance signal.raise_signal(), here is my new PR: https://github.com/python/cpython/pull/91756

**Comment by vstinner** [comment]
> I wanted to enhance signal.raise_signal(), here is my new PR: https://github.com/python/cpython/pull/91756

Merged. I close the issue. Thanks for the fix!
