### ISSUE TITLE
typing.Never and typing.assert_never

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#90633]
BPO | [46475](https://bugs.python.org/issue46475)
--- | :---
Nosy | @gvanrossum, @davidfstr, @JelleZijlstra, @sobolevn, @Fidget-Spinner, @AlexWaygood
PRs | <li>python/cpython#30842</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/JelleZijlstra'
closed_at = <Date 2022-02-08.19:07:21.141>
created_at = <Date 2022-01-22.22:48:21.675>
labels = ['type-feature', 'library', '3.11']
title = 'typing.Never and typing.assert_never'
updated_at = <Date 2022-02-08.19:07:21.140>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-08.19:07:21.140>
actor = 'JelleZijlstra'
assignee = 'JelleZijlstra'
closed = True
closed_date = <Date 2022-02-08.19:07:21.141>
closer = 'JelleZijlstra'
components = ['Library (Lib)']
creation = <Date 2022-01-22.22:48:21.675>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 46475
keywords = ['patch']
message_count = 5.0
messages = ['411297', '411301', '411309', '411347', '412860']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'David Foster', 'JelleZijlstra', 'sobolevn', 'kj', 'AlexWaygood']
pr_nums = ['30842']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46475'
versions = ['Python 3.11']
```

</p></details>

**Comment by JelleZijlstra** [comment]
@ptmcg it always throws at runtime; the point is that static typecheckers will verify that the code really is unreachable. See https://docs.python.org/3.11/library/typing.html#typing.assert_never and https://typing.readthedocs.io/en/latest/source/unreachable.html

**Comment by ptmcg** [comment]
Thank you @gvanrossum , that is what I was asking.

**Comment by JelleZijlstra** [comment]
I see. Usually you'd use this function in a place where some variable gets narrowed down to Never. Making it an explicit argument makes it possible to implement the function without any special casing in type checkers, because they already know how to treat Never in an argument position.

We could add a similar function with no arguments that asserts a block is unreachable, but unlike `assert_never()` it would need to be special cased in type checkers.

We might want to revisit the fact that the error message is always the same. We did that on the basis of security concerns about str() on untrusted input, but I don't find those concerns that convincing, and it's useful to have some representation of the object in the error message.

**Comment by gvanrossum** [comment]
*Security* concerns? That seems excessive. Millions of things in the stdlib print the repr() of the thing that unexpectedly failed some check.

**Comment by JelleZijlstra** [comment]
Sending a PR shortly to add the asserted value to assert_never()'s error message, and also to link to https://typing.readthedocs.io/en/latest/source/unreachable.html while I'm at it.
