### ISSUE TITLE
Add new triplets for 64-bit LoongArch

### ISSUE THREAD

**Issue by 20fc62b8-2153-40dc-9ae9-195ead165f6f** [python/cpython#90656]
BPO | [46498](https://bugs.python.org/issue46498)
--- | :---
Nosy | @loongson-zn, @xen0n
PRs | <li>python/cpython#30939</li>
Files | <li>[loongarch64.diff](https://bugs.python.org/file50579/loongarch64.diff "Uploaded as text/plain at 2022-01-24.05:00:21 by @loongson-zn")</li><li>[loongarch64-new.diff](https://bugs.python.org/file50590/loongarch64-new.diff "Uploaded as text/plain at 2022-01-27.08:05:29 by @loongson-zn"): update loongarch64.diff</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-24.05:00:22.024>
labels = ['build', '3.9']
title = 'Add new triplets for loongarch64'
updated_at = <Date 2022-01-27.08:05:30.042>
user = 'https://github.com/loongson-zn'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.08:05:30.042>
actor = 'loongson-zn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2022-01-24.05:00:22.024>
creator = 'loongson-zn'
dependencies = []
files = ['50579', '50590']
hgrepos = []
issue_num = 46498
keywords = ['patch']
message_count = 2.0
messages = ['411701', '411842']
nosy_count = 2.0
nosy_names = ['loongson-zn', 'xen0n']
pr_nums = ['30939']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue46498'
versions = ['Python 3.9']
```

</p></details>

**Comment by corona10** [comment]
I left the opinion about the issue: https://github.com/python/cpython/pull/30939#issuecomment-1537817984

**Comment by erlend-aasland** [comment]
Should we also add triplets for LA32R and LA32S?

**Comment by erlend-aasland** [comment]
@xen0n, let me know if you want your attribution in the NEWS and What's New entries (IMO, it seems like that would be appropriate). We can easily patch those two files in a follow-up PR.
