### ISSUE TITLE
Possible bug: pdb causes exception

### ISSUE THREAD

**Issue by 80dad885-8dbd-4e5f-818f-af7803b40118** [python/cpython#90693]
BPO | [46535](https://bugs.python.org/issue46535)
--- | :---
Nosy | @cklb

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-26.11:20:07.032>
labels = ['type-bug', 'library', '3.10']
title = 'Possible bug: pdb causes exception'
updated_at = <Date 2022-01-27.15:39:46.150>
user = 'https://github.com/cklb'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.15:39:46.150>
actor = 'cklb'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-26.11:20:07.032>
creator = 'cklb'
dependencies = []
files = []
hgrepos = []
issue_num = 46535
keywords = []
message_count = 1.0
messages = ['411738']
nosy_count = 1.0
nosy_names = ['cklb']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46535'
versions = ['Python 3.10']
```

</p></details>

**Comment by damarvin** [comment]
Hi,
I see this when debugging in PyCharm, and I cannot downgrade to python 3.9.

_(besides commenting out the try-except in numpy/core/getlimits.py::`finfo.__new__`)_
Is there a workaround?

**Comment by cklb** [comment]
@iritkatriel sorry for the delay

I just reran the snippet with the following configuration:

```
Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] on linux
numpy==1.23.1
pandas==1.4.0
```

and still get the following output:

```
python -m pdb snippet.py
> /PATH/snippet.py(1)<module>()
-> import numpy as np
(Pdb) r
--Return--
> /PATH/snippet.py(6)<module>()->None
-> np.finfo(float)
(Pdb) c
Traceback (most recent call last):
  File "/VENV/lib/python3.10/site-packages/numpy/core/getlimits.py", line 460, in __new__
    dtype = numeric.dtype(dtype)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/PATH/snippet.py", line 6, in <module>
    np.finfo(float)
  File "/VENV/lib/python3.10/site-packages/numpy/core/getlimits.py", line 463, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /VENVl/lib/python3.10/site-packages/numpy/core/getlimits.py(463)__new__()
-> dtype = numeric.dtype(type(dtype))
(Pdb) 
```

**Comment by iritkatriel** [comment]
Have you reported this on the numpy bug tracker?

**Comment by cklb** [comment]
Negative. I also did not open an issue in the pandas repo. However, if you think that this help I'll gladly do so.

**Comment by iritkatriel** [comment]
The exception is coming from numpy code, so I would start there. If it's a cpython bug they will know how to narrow it down to a small reproducer that doesn't involve so many dependencies.

**Comment by cklb** [comment]
I just had a look at the numpy bugtracker and it seems like this actually was a cython issue:

* https://github.com/numpy/numpy/issues/21693
* https://github.com/numpy/numpy/issues/21519

My fault was to only update numpy, but pandas was also still using the affected cython version:

* https://github.com/pandas-dev/pandas/issues/47429

After updating to v1.4.3 of pandas the code now behaves as expected in the debugger :smile: 

Thank you very much for looking into this.

**Comment by Kaliteli** [comment]
.traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
ValueError: source code string cannot contain null bytes
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

**Comment by Kaliteli** [comment]
Anlayamıyorum

**Comment by isidentical** [comment]
@Kaliteli can you please check versions of the local libraries you are using (`pip freeze`) and ensure that they are up to date? Also, let's try to keep the communication in this tracker in English.

> Lütfen kullandığınız yerel kütüphanelerin sürümlerini ("pip freeze" ve "python --version") kontrol edip güncel olduklarından emin olur musunuz? Ayrıca GitHub'daki iletişimi ingilizce tutmaya çalışalım.
