### ISSUE TITLE
pathlib.Path.__enter__() should emit DeprecationWarning

### ISSUE THREAD

**Issue by 4b0c5ead-8181-475a-af87-9342ce46c4e3** [python/cpython#90714]
BPO | [46556](https://bugs.python.org/issue46556)
--- | :---
Nosy | @brettcannon, @barneygale
PRs | <li>python/cpython#30971</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-08.21:02:04.592>
created_at = <Date 2022-01-27.23:07:21.767>
labels = ['type-bug', 'library', '3.11']
title = 'pathlib.Path.__enter__() should emit DeprecationWarning'
updated_at = <Date 2022-02-08.21:02:04.592>
user = 'https://github.com/barneygale'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-08.21:02:04.592>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2022-02-08.21:02:04.592>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2022-01-27.23:07:21.767>
creator = 'barneygale'
dependencies = []
files = []
hgrepos = []
issue_num = 46556
keywords = ['patch']
message_count = 2.0
messages = ['411936', '412870']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'barneygale']
pr_nums = ['30971']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46556'
versions = ['Python 3.11']
```

</p></details>

**Comment by dss010101** [comment]
anyone..anyone...

**Comment by barneygale** [comment]
> so how do we use Path to avoid this warning?

Don't use a path object as a context manager, e.g. rather than:

```python
with Path('foo') as path:
    ...
```

use:

```python
path = Path('foo')
```

**Comment by dss010101** [comment]
> > so how do we use Path to avoid this warning?
> 
> Don't use a path object as a context manager, e.g. rather than:
> 
> ```python
> with Path('foo') as path:
>     ...
> ```
> 
> use:
> 
> ```python
> path = Path('foo')
> ```

Ah got it. that is what i had ended up doing - wasn't sure if there still was a way to use it with the 'with' block.
