### ISSUE TITLE
Python modules such as pyglet or pygame crash Python when tkinter message boxes are opened on MacOS.

### ISSUE THREAD

**Issue by d847c2ee-a917-4642-94ed-e54f1550f388** [python/cpython#90731]
BPO | [46573](https://bugs.python.org/issue46573)
--- | :---
Nosy | @ronaldoussoren, @ned-deily
Files | <li>[issue.py](https://bugs.python.org/file50597/issue.py "Uploaded as text/plain at 2022-01-29.18:48:13 by remyrfouquette"): A short test I put together showing the issue.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-03.21:05:49.571>
created_at = <Date 2022-01-29.18:48:13.856>
labels = ['OS-mac', 'expert-tkinter', '3.10', 'type-crash']
title = 'Python modules such as pyglet or pygame crash Python when tkinter message boxes are opened on MacOS.'
updated_at = <Date 2022-02-03.21:05:49.570>
user = 'https://bugs.python.org/remyrfouquette'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-03.21:05:49.570>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2022-02-03.21:05:49.571>
closer = 'ned.deily'
components = ['macOS', 'Tkinter']
creation = <Date 2022-01-29.18:48:13.856>
creator = 'remyrfouquette'
dependencies = []
files = ['50597']
hgrepos = []
issue_num = 46573
keywords = []
message_count = 12.0
messages = ['412093', '412309', '412310', '412311', '412312', '412344', '412349', '412392', '412399', '412423', '412425', '412469']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'culler', 'Marc.Culler', 'remyrfouquette']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue46573'
versions = ['Python 3.10']
```

</p></details>

**Comment by mdehoon** [comment]
@ronaldoussoren 
> Something I forgot to mention: I don't think this is a bug in Tk now that I've looked into this more deeply.
> 
> The integration problem between Tk and other users of the Cocoa event loop is unfortunate but not a bug.

I do think that this is a bug in Tk, as this can be fixed in Tk simply by not subclassing NSApplication, and using categories and some global variables instead.

See https://core.tcl-lang.org/tk/tktview/637e74c1e7 for a bug report in Tk.
