### ISSUE TITLE
Undocumented behavior in strptime for ISO week dates

### ISSUE THREAD

**Issue by 4dc7cd77-30b0-40c2-a775-a7fab984054d** [python/cpython#90750]
BPO | [46592](https://bugs.python.org/issue46592)
--- | :---
Nosy | @abalkin, @JonatanSkogsfors, @pganssle

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-31.13:06:25.880>
labels = ['type-bug', 'library', '3.10']
title = 'Undocumented behavior in strptime for ISO week dates'
updated_at = <Date 2022-01-31.13:18:52.284>
user = 'https://github.com/jonatanskogsfors'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-31.13:18:52.284>
actor = 'AlexWaygood'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-31.13:06:25.880>
creator = 'Jonatan Skogsfors'
dependencies = []
files = []
hgrepos = []
issue_num = 46592
keywords = []
message_count = 1.0
messages = ['412200']
nosy_count = 3.0
nosy_names = ['belopolsky', 'Jonatan Skogsfors', 'p-ganssle']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46592'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-103802

**Comment by Ev2geny** [comment]
From common sense point of view I would expect datetime to through an error when one tries to create a date with none-existing week. In the same way as it now throws an error, when one tries to create a date with 31 of February for instance

```py
import datetime
print(datetime.datetime(2021, 2, 31).strftime("%d %b %Y %H:%M"))

#    print(datetime.datetime(2021, 2, 31).strftime("%d %b %Y %H:%M"))
# ValueError: day is out of range for month
```

Having said, that I see, that all other similar packages from standard libraries of other languages (Java, C#, C) also do not complain about none-existing week 53. It looks like they all have taken a decision not to check the week number (unlike with the month day). I am not sure why such decision was taken.

**C#**
```C#
// https://weeknumber.com/how-to/c-sharp
Console.WriteLine(System.Globalization.ISOWeek.ToDateTime(2021, 53, DayOfWeek.Monday));

// 03-Jan-2022 00:00:00
```
**Java**
```java
package com.company;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

public class Main {

    public static void main(String[] args) {
	// https://weeknumber.com/how-to/java

        GregorianCalendar calendar = new GregorianCalendar();
        calendar.setFirstDayOfWeek(GregorianCalendar.MONDAY);
        calendar.setMinimalDaysInFirstWeek(4);

        calendar.setWeekDate(2021, 53, GregorianCalendar.MONDAY);

        SimpleDateFormat sdf1 = new SimpleDateFormat("d-MMM-y");
        System.out.println(sdf1.format(calendar.getTime()));
        // 3-Jan-2022


        // However
        System.out.println(calendar.get(GregorianCalendar.WEEK_OF_YEAR));
       // 1
    }
}
```
And **C** (tested under Ubuntu) got it totally wrong

```c
       // https://man7.org/linux/man-pages/man3/strptime.3.html
       
       #define _XOPEN_SOURCE
       #include <stdio.h>
       #include <stdlib.h>
       #include <string.h>
       #include <time.h>

       int
       main(void)
       {
           struct tm tm;
           char buf[255];

           memset(&tm, 0, sizeof(tm));
           strptime("Y2021 W53 D1", "Y%Y W%OW D%w", &tm);
           strftime(buf, sizeof(buf), "%d %b %Y %H:%M", &tm);
           puts(buf);
           
          // !!!!!     34 Dec 2021 00:00


           exit(EXIT_SUCCESS);
       }
```

**Comment by Ev2geny** [comment]
So, I guess someone need to take a decision whether the functionality of  `strptime` is a bug or a feature and either to fix it or document.

**Comment by encukou** [comment]
datetime [experts](https://devguide.python.org/core-developers/experts/) @pganssle & @abalkin, do you have opinions here?

**Comment by Ev2geny** [comment]
@pganssle & @abalkin , just a kind reminder. Do you have any opinion on this subject?

**Comment by pganssle** [comment]
I think we can probably fix this, since the ISO parsing code is happening on our side. Maybe we can replace [this section](https://github.com/python/cpython/blob/1c01f8d79760ca74f6d35b839d23ac408b3bb44e/Lib/_strptime.py#L515-L545) of `_strptime` with a `datetime.fromisocalendar` call?

**Comment by pganssle** [comment]
OK, this seems like a pretty simple fix, I've created a PR for it: https://github.com/python/cpython/pull/103802

**Comment by hauntsaninja** [comment]
Looks like the fix was merged, thanks all!
