### ISSUE TITLE
Python built with clang -O0 allocates 10x more stack memory than clang -O3 on a Python function call

### ISSUE THREAD

**Issue by vstinner** [python/cpython#90758]
BPO | [46600](https://bugs.python.org/issue46600)
--- | :---
Nosy | @vstinner, @methane, @corona10, @pablogsal
PRs | <li>python/cpython#31052</li><li>python/cpython#31058</li>
Files | <li>[stack_overflow-4.py](https://bugs.python.org/file50600/stack_overflow-4.py "Uploaded as text/plain at 2022-02-01.13:40:57 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-01.13:06:00.875>
labels = ['3.11', 'build', 'performance']
title = 'Python built with clang -O0 allocates 10x more stack memory than clang -O3 on a Python function call'
updated_at = <Date 2022-02-03.00:00:28.611>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-03.00:00:28.611>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2022-02-01.13:06:00.875>
creator = 'vstinner'
dependencies = []
files = ['50600']
hgrepos = []
issue_num = 46600
keywords = ['patch']
message_count = 14.0
messages = ['412252', '412253', '412254', '412255', '412256', '412258', '412260', '412261', '412278', '412286', '412294', '412334', '412348', '412407']
nosy_count = 4.0
nosy_names = ['vstinner', 'methane', 'corona10', 'pablogsal']
pr_nums = ['31052', '31058']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue46600'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by vstinner** [comment]
There is always room for enhancement :-) But for now, IMO merged changes are enough to make the issue less complicated.

The main change is to use -Og when Python is built in debug mode by clang.
