### ISSUE TITLE
PyLineTable_InitAddressRange isn't exported - causing C Extensions to fail at import

### ISSUE THREAD

**Issue by 6b7c76ad-5e7c-4036-969d-2d472c77a4bb** [python/cpython#90754]
BPO | [46596](https://bugs.python.org/issue46596)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-01.08:48:19.848>
labels = ['expert-C-API', '3.10']
title = "PyLineTable_InitAddressRange isn't exported - causing C Extensions to fail at import"
updated_at = <Date 2022-02-01.08:48:19.848>
user = 'https://bugs.python.org/nathan3'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-01.08:48:19.848>
actor = 'nathan3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-02-01.08:48:19.848>
creator = 'nathan3'
dependencies = []
files = []
hgrepos = []
issue_num = 46596
keywords = []
message_count = 1.0
messages = ['412237']
nosy_count = 1.0
nosy_names = ['nathan3']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46596'
versions = ['Python 3.10']
```

</p></details>

**Comment by nathan454** [comment]
@vstinner 
continuing the discussion from here https://github.com/python/cpython/issues/89479#issuecomment-1147337050

It's impossible to access those functions as native extension, so I think exporting them is necessary.

**Comment by encukou** [comment]
It seems the [promises from PEP 626](https://peps.python.org/pep-0626/#out-of-process-debuggers-and-profilers) were broken.
Victor, could you revert?

**Comment by vstinner** [comment]
>  Victor, could you revert?

@markshannon told me that these functions must be private on purpose.

**Comment by encukou** [comment]
Right, but the PEP also says:

> Although these functions are not part of C-API, they will provided by all future versions of CPython. 

Python 3.11 currently does not provide `PyLineTable_InitAddressRange` etc. at all.

**Comment by nathan454** [comment]
> > It seems the [promises from PEP 626](https://peps.python.org/pep-0626/#out-of-process-debuggers-and-profilers) were broken.
> 
> The PEP says:
> 
> > Note that these functions are **not part of the C-API**, so will be need to be linked into any code that needs to use them.

How can one link to this functions if their symbol isn't exported?
When trying to load the native extensions It throws "undefined symbol" for these functions

**Comment by vstinner** [comment]
cc @pablogsal (PEP delegate)

**Comment by markshannon** [comment]
PEP 626 states quite clearly that `PyLineTable_InitAddressRange` isn't part of the C-API.

The section title is "Out of process debuggers and profilers". Code in one process cannot call code in another.

@nathan454 why can't you use the API functions?

**Comment by nathan454** [comment]
> PEP 626 states quite clearly that `PyLineTable_InitAddressRange` isn't part of the C-API.
> 
> The section title is "Out of process debuggers and profilers". Code in one process cannot call code in another.
> 
> @nathan454 why can't you use the API functions?

@markshannon I'm trying to access the API functions through native extension that is imported from python module. Upon loading the native extension, the loader searches for the API functions symbols, and can't find any since it's not exported.

`nm .pyenv/versions/3.10.0/bin/python | grep -i PyLineTable_InitAddressRange
000000010004e080 t _PyLineTable_InitAddressRange`

**Comment by nathan454** [comment]
Do we have any solution here?

**Comment by markshannon** [comment]
I will say it again, `_PyLineTable_InitAddressRange` is **not** part of the C API.

Why can't you use functions that are part of the C API?

**Comment by vstinner** [comment]
@nathan3:
> I'm trying to develop C++ Extension that needs to access the new line table.

@markshannon:
> Why can't you use functions that are part of the C API?

Which C API functions give access to the line table?

**Comment by nathan454** [comment]
@markshannon Am I missing a C API function that will allow C extension to access the table?
Is there actual reason that `_PyLineTable_InitAddressRange` can't be / shouldn't be part of C API?

**Comment by nathan454** [comment]
@vstinner Following the conversion in this issue and in https://github.com/python/cpython/issues/89479

I'm developing a tool that needs to have an access to the line table. I need to get the correct offset of a given line number,
I have seen that in GH-89479 you've removed it from the API hence it's unusable. 
Is there other way to get an offset from given line number? If not, I think these functions should be part of the public API

**Comment by vstinner** [comment]
> I have seen that in https://github.com/python/cpython/issues/89479 you've removed it from the API hence it's unusable.

It was not usable before my change. I just fixed the header file, it doesn't change the API.

I let you see this issue with @markshannon and others who work on optimizing Python and changing APIs related to that ;-)

**Comment by markshannon** [comment]
> Is there actual reason that _PyLineTable_InitAddressRange can't be / shouldn't be part of C API?

Yes. The more stuff we add to the C API, the harder it is to maintain, and the more it restricts the development of CPython.

If you want line numbers, `PyCode_Addr2Line()` is part of the C API.
Alternatively, you can call any Python functions through the C API, specifically `code.co_lines()` and `code.co_positions()`.

**Comment by vstinner** [comment]
>  Alternatively, you can call any Python functions through the C API, specifically code.co_lines() and code.co_positions().

Can we just close this feature request in this case?

**Comment by nathan454** [comment]
@markshannon `PyCode_Addr2Line()` does the opposite, it returns a line number for given address. 
I'm looking for getting an offset by given line number
I think PySpy require the same functionality

**Comment by iritkatriel** [comment]
My guess is that @markshannon meant that with PyCode_Addr2Line you can get the information, and process it into the format you need.

Closing as the discussion seems to have come to a conclusion and the feature request was rejected.
