### ISSUE TITLE
Add mimalloc memory allocator

### ISSUE THREAD

**Issue by tiran** [python/cpython#90815]
BPO | [46657](https://bugs.python.org/issue46657)
--- | :---
Nosy | @nascheme, @tiran, @corona10, @erlend-aasland, @h-vetinari
PRs | <li>python/cpython#31164</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-06.14:49:12.884>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Add mimalloc memory allocator'
updated_at = <Date 2022-03-24.02:10:23.628>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-24.02:10:23.628>
actor = 'h-vetinari'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-02-06.14:49:12.884>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 46657
keywords = ['patch']
message_count = 12.0
messages = ['412639', '412641', '412645', '412654', '412669', '412679', '412741', '412749', '412796', '412835', '412867', '412986']
nosy_count = 5.0
nosy_names = ['nascheme', 'christian.heimes', 'corona10', 'erlendaasland', 'h-vetinari']
pr_nums = ['31164']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46657'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-109914
* gh-111522
* gh-111524
* gh-111527
* gh-111528
* gh-111532
* gh-117811

**Comment by ericsnowcurrently** [comment]
FYI, PR #31164 indicates the following 3 blockers:

* [mimalloc is holding on to large blocks of memory](https://github.com/python/cpython/pull/31164#issuecomment-1036690222) (thanks @neonene)
* [the ASAN CI job is failing](https://github.com/python/cpython/runs/6530552258)
* [PGO on Windows is failing](https://github.com/python/cpython/pull/31164#issuecomment-1036690222)

After a conversation between @tiran, @daanx (the mimalloc creator), and me, we have a good idea on how to move forward.  I'm looking into the PGO issue (with some help).

**Comment by ericsnowcurrently** [comment]
The PGO-on-Windows issue may be resolved now (thanks to gh-94790).  Here's what I did to check:

1. merge main into `tiran:bpo-46657-mimalloc` (PR gh-31164)
   a. run `git merge main`
   b. fix Makefile.pre.in
   c. run `git checkout main -- Python/clinic/sysmodule.c.h`
2. run `python3 Tools/clinic/clinic.py --make`
3. run `python3 Tools/scripts/generate_global_objects.py`
4. change `_PyStructSequence_InitType` to `_PyStructSequence_InitBuiltinWithFlags` in Python/sysmodule.c
5. run `.\PCbuild\build.bat --pgo`

@neonene Could you verify that we should expect PGO builds to be working correctly now?  Thanks!

**Comment by gvanrossum** [comment]
Do these steps point towards improvements for @tiran's mimalloc branch?

**Comment by neonene** [comment]
@ericsnowcurrently Thanks for the check. I can also build the newest mimalloc branch successfully with PGO on Windows.

As for the issue around releasing memory, my builds still show:
```
>>> from test.support import Py_DEBUG

>>> about32MiB = 1024*1024*32 - (32*Py_DEBUG)

>>> b = [bytearray(about32MiB) for i in range(3)]
>>> del b  # 100MB is freed to the OS

>>> b = [bytearray(about32MiB - 1) for i in range(3)]
>>> del b  # 100MB remains cached
```
The threshold size was `1024*1024*32 - (32*Py_DEBUG) - 32` when I used `bytes()` instead.

**Comment by ericsnowcurrently** [comment]
> @ericsnowcurrently Thanks for the check. I can also build the newest mimalloc branch successfully with PGO on Windows.

Great!  I'll cross it off my list. 😄

> As for the issue around releasing memory, my builds still show:

Yeah, I'm going to follow up with @daanx about this.

**Comment by romange** [comment]
subscribing here to learn how the issue with mimalloc is being resolved. My project uses mimalloc as well, and I am curious to learn how to configure it to have a slimmer memory footprint.

**Comment by ericsnowcurrently** [comment]
@romange, take a look at https://github.com/python/cpython/pull/31164#issuecomment-1133583811.  Other than that, there's only the existing mimalloc documentation, as well as any insight @daanx can offer.

**Comment by romange** [comment]
@ericsnowcurrently thanks! btw, I chose mimalloc because of its elegant design and its thread-local heap support. 
However, it seems that the project is not under active development anymore. Maybe it's because of good reasons and everything is perfect, but I can see how it can become a problem in the future (and daanx is a one-person army).
What do you think about it?

**Comment by daanx** [comment]
Hi @romange, here is me: just to clarify mimalloc _is_ actively maintained and I am dedicated to make the CPython integration work.  However, I did take some needed time off this summer, :-) but am back now and hope to help resolve the outstanding issues. I already started work on the ASAN support so hope that is coming soon (although I am at ICFP'23 next week).

**Comment by romange** [comment]
Hi @daanx  I am psyched to hear! :) and sorry for quickly jumping to conclusions 🤦🏼‍♂️

**Comment by daanx** [comment]
> @ericsnowcurrently Thanks for the check. I can also build the newest mimalloc branch successfully with PGO on Windows.
> 
> As for the issue around releasing memory, my builds still show:
> 
> ```
> >>> from test.support import Py_DEBUG
> 
> >>> about32MiB = 1024*1024*32 - (32*Py_DEBUG)
> 
> >>> b = [bytearray(about32MiB) for i in range(3)]
> >>> del b  # 100MB is freed to the OS
> 
> >>> b = [bytearray(about32MiB - 1) for i in range(3)]
> >>> del b  # 100MB remains cached
> 
> >>> sys._mi_collect(True)  # purge cached segments
> ```
> 
> The threshold size was `1024*1024*32 - (32*Py_DEBUG) - 32` when I used `bytes()` instead.

Thanks for testing this, just to clarify:

* after the `sys.mi_collect(True)`, was there still 100MiB being "cached"
* with "cached", you mean that the RSS was 100MiB more than expected?  (was this on Linux or Windows?)

Generally, when an allocator requests memory from the OS (when allocating the bytearray for example), it should not immediately free that OS memory when memory is `free`'d just in case the program will start allocating again (which is usually the case). `mimalloc` does this as well and only releases more unused OS memory after a while. 

However,  at an interpreter prompt the program is just waiting and may therefore not get an opportunity to do this. In such case the CPython interpreter should call `sys._mi_collect(True)` to collect outstanding OS memory just before blocking for user input. 

(In case you still see an increased usage after manually calling this as in your test above, something else may be going on which we should investigate in that case).

**Comment by neonene** [comment]
When I tried the following steps on Windows:
1. `b = [bytearray(1024*1024*32 - 1) for i in range(32)]`
2. `del b`
3. `sys._mi_collect(True)`

Then, TaskManager showed that the memory usages of `python.exe` are:
|65af44c (PR)|1|2|3||
|:--|:--:|:--:|:--:|:--|
|v2.0.6 as-is [(options)](https://github.com/microsoft/mimalloc/blob/f2712f4a8f038a7fb4df2790f4c3b7e3ed9e219b/src/options.c#L58)|1 GB|1 GB|40,932 KB|holds 32MB?|
|v2.0.6 decommit_delay = 0|1 GB|8,392 KB|8,112 KB||
|v2.0.6 page_reset = 1|1 GB|6,480 KB|8,060 KB|slower than above?|

|main|1|2|
|:--|:--:|:--:|
|pymalloc|1 GB|3,760 K|

**Comment by daanx** [comment]
Thanks for the quick test and explanation! 

1. I think generally, we should call  `mi_collect(true)` in CPython  when entering the interpreter prompt just in general so we always clean up as much as we can after each expression evaluation. Is this easy to do? 
2. Thanks for testing `decommit_delay=0` -- this shows that it is indeed the delay heuristic in mimalloc. This is a good thing though in general and we should not use `decommit_delay=0` generally as it would slow down the allocator for large computations.
3. `page_reset` eagerly resets and is generally the best for lowest heap usage (but also costs a bit as the OS call is slowish)

I am thinking that I should probably enable the `page_reset` for large block pages where the cost would be amortized and we would see the largest gains. This would fix your example I think. However, the 32MiB is exactly the "huge" block boundary, can you do the same test with other block sizes, like 64 16MiB arrays, and 16 64MiB arrays? 

Thanks

**Comment by gvanrossum** [comment]
> I think generally, we should call `mi_collect(true)` in CPython when entering the interpreter prompt just in general so we always clean up as much as we can after each expression evaluation. Is this easy to do?

Should be easy enough for the REPR, but there are any number of other situations where this cleanup would be expected -- before waiting for a socket operation, before reading from stdin (or any tty device), before sleeping (or select/poll/etc.), and so on.

Maybe it should be done whenever we do a GC run too?

**Comment by gvanrossum** [comment]
So maybe this whole "mimalloc doesn't release memory to the system" is a non-issue? Calling `mi_collect()` before entering the REPL only "works" because to *demonstrate* the problem people will do things like start an interactive interpreter, run a bit of code that allocates a huge block, free it again, and then in a separate shell run "ps" to observe the process size, while keeping the python process waiting at the next `>>>` prompt.

What I think you're saying is if instead they would just continue to run some other code (that doesn't reuse the huge block that was just freed) the excess memory *will* be returned to the system after some time (how is that measured? wall clock time? number of alloc/free ops?), and the observation that the huge block is not returned to the system is a mere artifact of the way people try to demonstrate the issue.

**Comment by neonene** [comment]
>However, the 32MiB is exactly the "huge" block boundary, can you do the same test with other block sizes, like 64 16MiB arrays, and 16 64MiB arrays?

@daanx This example holds 168 MiB, and the same goes for the reversed arrays:
```
[bytearray(1024*1024 * [64,16][i%2]) for i in range(20)]  # 16MiB blocks are cached?
```
Also, the cases below return about 1GiB to the OS with `mi_collect()`:
```
[bytearray(1024*1024) for i in range(1024)]
[bytearray(1024*512)  for i in range(1024*2)]
[bytearray(1024*256)  for i in range(1024*4)]
[bytearray(1024*128)  for i in range(1024*8)]
[bytearray(1024*64)   for i in range(1024*16)]
[bytearray(1024*32)   for i in range(1024*32)]
[bytearray(1024*16)   for i in range(1024*64)]
[bytearray(1024*8)    for i in range(1024*128)]
```
What I'm trying is to simplify `test_fstring.test_many_expressions`.
Thanks.

**Comment by daanx** [comment]
(back from ICFP)
> So maybe this whole "mimalloc doesn't release memory to the system" is a non-issue? Calling `mi_collect()` before entering the REPL only "works" because to _demonstrate_ the problem people will do things like start an interactive interpreter, run a bit of code that allocates a huge block, free it again, and then in a separate shell run "ps" to observe the process size, while keeping the python process waiting at the next `>>>` prompt.
> What I think you're saying is if instead they would just continue to run some other code (that doesn't reuse the huge block that was just freed) the excess memory _will_ be returned to the system after some time (how is that measured? wall clock time? number of alloc/free ops?), and the observation that the huge block is not returned to the system is a mere artifact of the way people try to demonstrate the issue.

Yes, this is exactly right! Since reserving and releasing OS memory is so expensive, we delay the release a bit as the memory may be needed soon enough. The current delay is in wall clock time but fairly short (I think 500ms by default). 

When someone runs an expression from the REPL, it will actually always be the case that we no longer require any OS memory to be retained afterwards (it is like running a separate program). So, _in this particular case_ it is actually beneficial to call `mi_collect(true)` after evaluation. (but again, calling `mi_collect` in general is not).

**Comment by daanx** [comment]
> Also, the cases below return about 1GiB to the OS with `mi_collect()`:
> 

Thanks for testing! When I get back home I will set things up so I can directly test these myself as well. I tried this also directly and verified that it wasn't something specific to huge objects so that's good.

**Comment by thesamesam** [comment]
> My preference would be for --with-mimalloc=yes in an upcoming release. For platforms without the required stdatomic.h stuff, they can manually specify --with-mimalloc=no. That will make them aware that a future release of Python might no longer build (if mimalloc is no longer optional).
> 
> A soft-landing for merging nogil is not a good enough reason to merge mimalloc, IMHO. nogil may never be merged. There should be some concrete and immediate advantage to switch to mimalloc. The idea of using the "heap walking" to improve is cyclic GC is not concrete enough. It's just an idea at this point.
> 
> I think the (small) performance win could be enough of a reason to merge. This seems to be the most recent benchmark:
> 
> [gist.github.com/pablogsal/8027937b71cd30f17aaaa5ef7c885d3e](https://gist.github.com/pablogsal/8027937b71cd30f17aaaa5ef7c885d3e)
> 
> There is also the long-term maintenance issue. So far, mimalloc upstream has been responsive. The mimalloc code is not so huge or complicated that we couldn't maintain it (if for some reason it gets abandoned upstream). However, I think we would prefer to maintain obmalloc rather than mimalloc, all else being equal. Abandonment by the upstream seems fairly unlikely. So, I'm not too concerned about maintenance.

I made a similar point wrt the bundling at https://github.com/python/cpython/pull/109914#issuecomment-1784315022.

**Comment by nascheme** [comment]
I think this issue could be closed now that mimalloc went into HEAD already.

**Comment by erlend-aasland** [comment]
> > [...]
> > There is also the long-term maintenance issue. So far, mimalloc upstream has been responsive. The mimalloc code is not so huge or complicated that we couldn't maintain it (if for some reason it gets abandoned upstream). However, I think we would prefer to maintain obmalloc rather than mimalloc, all else being equal. Abandonment by the upstream seems fairly unlikely. So, I'm not too concerned about maintenance.
> 
> I made a similar point wrt the bundling at [#109914 (comment)](https://github.com/python/cpython/pull/109914#issuecomment-1784315022).

See follow-up issue:

- #113141
