### ISSUE TITLE
shutil Lib enables sendfile on solaris for regular files

### ISSUE THREAD

**Issue by c9ed70e6-85ba-41dd-8968-859cb0429c8e** [python/cpython#90816]
BPO | [46658](https://bugs.python.org/issue46658)
--- | :---
Nosy | @devnexen
PRs | <li>python/cpython#31165</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-06.15:52:18.465>
labels = ['library', '3.11']
title = 'shutil Lib enables sendfile on solaris for regular files'
updated_at = <Date 2022-02-06.15:52:18.465>
user = 'https://github.com/devnexen'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-06.15:52:18.465>
actor = 'devnexen'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-06.15:52:18.465>
creator = 'devnexen'
dependencies = []
files = []
hgrepos = []
issue_num = 46658
keywords = []
message_count = 1.0
messages = ['412643']
nosy_count = 1.0
nosy_names = ['devnexen']
pr_nums = ['31165']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46658'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
cc @jcea

Is this still relevant? Do tests pass with the PR?

**Comment by encukou** [comment]
@kulikjak, do you want to send an updated PR for this?

**Comment by kulikjak** [comment]
@encukou I just realized that I have very similar PR #23893. That one is rebased and ready to be merged (except for the version question I had there).

**Comment by encukou** [comment]
Ah! Let's go with that one, then.
