### ISSUE TITLE
Deprecate locale.getdefaultlocale() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#90817]
BPO | [46659](https://bugs.python.org/issue46659)
--- | :---
Nosy | @malemburg, @vstinner, @serhiy-storchaka, @eryksun
PRs | <li>python/cpython#31166</li><li>python/cpython#31167</li><li>python/cpython#31168</li><li>python/cpython#31206</li><li>python/cpython#31214</li><li>python/cpython#31218</li>
Files | <li>[cal_locale.py](https://bugs.python.org/file50606/cal_locale.py "Uploaded as text/plain at 2022-02-06.18:24:05 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-24.13:41:35.585>
created_at = <Date 2022-02-06.17:33:14.432>
labels = ['library', '3.11']
title = 'Deprecate locale.getdefaultlocale() function'
updated_at = <Date 2022-02-24.14:53:20.800>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-24.14:53:20.800>
actor = 'lemburg'
assignee = 'none'
closed = True
closed_date = <Date 2022-02-24.13:41:35.585>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2022-02-06.17:33:14.432>
creator = 'vstinner'
dependencies = []
files = ['50606']
hgrepos = []
issue_num = 46659
keywords = ['patch']
message_count = 19.0
messages = ['412647', '412652', '412664', '412666', '412667', '412668', '412687', '412800', '412819', '412825', '412826', '412827', '412829', '412842', '413744', '413745', '413907', '413910', '413915']
nosy_count = 4.0
nosy_names = ['lemburg', 'vstinner', 'serhiy.storchaka', 'eryksun']
pr_nums = ['31166', '31167', '31168', '31206', '31214', '31218']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue46659'
versions = ['Python 3.11']
```

</p></details>

**Comment by malemburg** [comment]
> For these reasons, I propose to deprecate locale.getdefaultlocale(): setlocale(), getpreferredencoding() and getlocale() should be used instead.

Please see the discussion on [https://bugs.python.org/issue43552](https://github.com/python/cpython/issues/87718): locale.getpreferredencoding() needs to be deprecated as well. Instead we should have a single locale.getencoding() as outlined there... perhaps in a separate ticket ?! Thanks.

**Comment by danny0838** [comment]
`locale.getlocale` does not return a correct RFC 1766 language code on Windows, which makes it incompatible with `locale.getdefaultlocale`. (#82986)

Our project relies on `locale.getdefaultlocale` to get the default system language code, which won't work using `locale.getlocale` due to the above bug. May I request NOT REMOVING `locale.getdefaultlocale` until there is a good solution for the bug of `locale.getlocale`?

**Comment by shineworld** [comment]
Return of locale.getlocale() is not compatibile with typical locale string (Python 3.11.7 on Windows):
```pycon
>>> locale.getdefaultlocale()
('it_IT', 'cp1252')

>>> locale.getlocale()
('Italian_Italy', '1252')
```
'it_IT' permits to fastly use gettext ./locale/<it_IT>/... translations mo files.

**Comment by vstinner** [comment]
> Return of locale.getlocale() is not compatibile with typical locale string

That's why the deprecation suggests using locale.setlocale(). Hum, the API is surprising, but locale.setlocale() should be used to **get** the current locale: ``locale.setlocale(locale.LC_CTYPE, None)`` gets the current `LC_CTYPE` locale for example.

**Comment by vstinner** [comment]
Maybe the deprecation message should be clarified. I dislike locale.getlocale(), it can return invalid locale which is not accepted by setlocale(). I wanted to deprecate it.

**Comment by malemburg** [comment]
The point of having getlocale() is to be able to normalize the returned values to make them compatible to setlocale().

The C lib API of setlocale() to actually fetch the current locale values is completely counterintuitive, which is why I had added getlocale() instead. On top of this, setlocale() does not always return values which you can feed back into it.

@shinewook: Could you please check what locale._setlocale(locale.LC_TYPE) returns on your Windows system ? It's possible that we'll have to add more aliases to the table to fix this. Thanks.

**Comment by Wedge009** [comment]
> Return of locale.getlocale() is not compatibile with typical locale string (Python 3.11.7 on Windows):
> 
> 'it_IT' permits to fastly use gettext ./locale/<it_IT>/... translations mo files.

We are running into the same issue for our project.

> Hum, the API is surprising, but locale.setlocale() should be used to **get** the current locale: `locale.setlocale(locale.LC_CTYPE, None)` gets the current `LC_CTYPE` locale for example.

It is indeed quite misleading. I had thought `setlocale` _only_ did just that - set the locale. However, we still have the same issue - `LC_CTYPE` still returns a non-POSIX locale code.

> BTW: Perhaps better to open a separate ticket for that problem...

Have there been any issues reported for this?

**Comment by malemburg** [comment]
> Return of locale.getlocale() is not compatibile with typical locale string (Python 3.11.7 on Windows):
> 
> > > > locale.getdefaultlocale()
> > > > ('it_IT', 'cp1252')
> 
> > > > locale.getlocale()
> > > > ('Italian_Italy', '1252')
> 
> 'it_IT' permits to fastly use gettext ./locale/<it_IT>/... translations mo files.

Is there a separate issue we can track this ?

I just tried on my German Windows box and it returns 'de_DE' just fine. Perhaps there's some alias missing from the normalization logic ?!

**Comment by Wedge009** [comment]
I didn't find any existing issue for this. For me, `getlocale` and `setlocale` returns 'English_Australia', similar to what shineworld reported. We have been discussing a [work-around in our project](https://github.com/wesnoth/wesnoth/issues/9972) of using Win32 directly, but it's not a comprehensive substitute.

**Comment by vstinner** [comment]
This issue is closed. Please open a new issue.

**Comment by malemburg** [comment]
> I didn't find any existing issue for this. For me, `getlocale` and `setlocale` returns 'English_Australia', similar to what shineworld reported. We have been discussing a [work-around in our project](https://github.com/wesnoth/wesnoth/issues/9972) of using Win32 directly, but it's not a comprehensive substitute.

Please open a new ticket, so we can track the issue. Thanks.

**Comment by cclauss** [comment]
## Will `locale.getdefaultlocale()` be removed in Python 3.15?

Py3.14 says yes but Py3.15b2 still has it.

% `python3.14 -V &&  python3.14 -c 'import locale;print(locale.getdefaultlocale())'`
```
Python 3.14.5
<string>:1: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python
    3.15.  Use setlocale(), getencoding() and getlocale() instead.
('en_US', 'UTF-8')
```
---
% `python3.15 -V &&  python3.15 -c 'import locale;print(locale.getdefaultlocale())'`
```
Python 3.15.0b2
('en_US', 'UTF-8')
```

**Comment by hugovk** [comment]
No, it was undeprecated in https://github.com/python/cpython/issues/130796 / https://github.com/python/cpython/pull/143069.

Let's backport the undeprecation to avoid further confusion.
