### ISSUE TITLE
Lib/sqlite3/dbapi2.py: convert_timestamp function failed to correctly parse timestamp

### ISSUE THREAD

**Issue by d8639ba2-3f7f-4f7e-b3ba-79048d256ece** [python/cpython#90820]
BPO | [46662](https://bugs.python.org/issue46662)
--- | :---
Nosy | @malemburg, @erlend-aasland, @Rayologist
PRs | <li>python/cpython#31169</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-06.19:03:59.534>
labels = ['type-bug', 'library', '3.9']
title = 'Lib/sqlite3/dbapi2.py: convert_timestamp function failed to correctly parse timestamp'
updated_at = <Date 2022-02-09.09:36:33.984>
user = 'https://github.com/Rayologist'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-09.09:36:33.984>
actor = 'lemburg'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-06.19:03:59.534>
creator = 'Rayologist'
dependencies = []
files = []
hgrepos = []
issue_num = 46662
keywords = ['patch']
message_count = 3.0
messages = ['412655', '412828', '412895']
nosy_count = 3.0
nosy_names = ['lemburg', 'erlendaasland', 'Rayologist']
pr_nums = ['31169']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46662'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
> I think it's better to deprecate these converters and let users implement their own.

Suggesting to deprecate the built-in converters when 3.12 dev opens up.

**Comment by erlend-aasland** [comment]
As per [discussion on Discourse](https://discuss.python.org/t/deprecate-default-built-in-sqlite3-converters-and-adapters/15781?u=erlendaasland), we will deprecate the built-in, default adapters and converters. Thus, this issue is now superseded by gh-90016.
