### ISSUE TITLE
python 3.10 Py_Initialize/Py_Main std path no longer includes site-packages

### ISSUE THREAD

**Issue by 33555a03-1463-4f64-8a07-2ddce7792eaa** [python/cpython#90840]
BPO | [46682](https://bugs.python.org/issue46682)
--- | :---
Nosy | @pjaggi1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-08.17:39:09.281>
labels = ['expert-C-API', 'type-bug', '3.10']
title = 'python 3.10 Py_Initialize/Py_Main std path no longer includes site-packages'
updated_at = <Date 2022-02-08.17:39:09.281>
user = 'https://github.com/pjaggi1'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-08.17:39:09.281>
actor = 'pjaggi1'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-02-08.17:39:09.281>
creator = 'pjaggi1'
dependencies = []
files = []
hgrepos = []
issue_num = 46682
keywords = []
message_count = 1.0
messages = ['412848']
nosy_count = 1.0
nosy_names = ['pjaggi1']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46682'
versions = ['Python 3.10']
```

</p></details>

**Comment by AmeyaVSingh** [comment]
Observing same issue while trying to embed python in my application.

**Comment by vstinner** [comment]
Sadly, this issue lacks details about the program name, the current working directory, the sys.path output, etc.

Since it's inactive for 1 year, I close the issue.

@AmeyaVSingh: Please reopen the issue if you can provide the requested information.
