### ISSUE TITLE
Improve Telnetlib's throughput

### ISSUE THREAD

**Issue by 8d0300d5-2c51-4cdf-9d9f-7d0147af5290** [python/cpython#90896]
BPO | [46740](https://bugs.python.org/issue46740)
--- | :---
Nosy | @terryjreedy, @JelleZijlstra, @martinkirch
PRs | <li>python/cpython#31449</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-13.20:17:40.706>
labels = ['library', '3.10', 'performance']
title = "Improve Telnetlib's throughput"
updated_at = <Date 2022-02-20.15:04:10.574>
user = 'https://github.com/martinkirch'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-20.15:04:10.574>
actor = 'martin_kirch'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-13.20:17:40.706>
creator = 'martin_kirch'
dependencies = []
files = []
hgrepos = []
issue_num = 46740
keywords = ['patch']
message_count = 3.0
messages = ['413195', '413206', '413509']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'JelleZijlstra', 'martin_kirch']
pr_nums = ['31449']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue46740'
versions = ['Python 3.10']
```

</p></details>

**Comment by hugovk** [comment]
(Linking to https://github.com/python/cpython/issues/91217 for future reference.)

**Comment by hugovk** [comment]
> As such, unless there are any core developers who want to volunteer to review PR #9121 (which has now been open for nearly two months without core review), ...

Correction, it's this PR: https://github.com/python/cpython/pull/31449

**Comment by martinkirch** [comment]
OK, closed the PR ; but I can only comment this issue.
