### ISSUE TITLE
Introduce task groups to asyncio and change task cancellation semantics

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#90908]
BPO | [46752](https://bugs.python.org/issue46752)
--- | :---
Nosy | @gvanrossum, @njsmith, @asvetlov, @dhalbert, @1st1, @Tinche, @iritkatriel, @YvesDup
PRs | <li>python/cpython#31270</li><li>python/cpython#31398</li><li>python/cpython#31409</li><li>python/cpython#31411</li><li>python/cpython#31513</li><li>python/cpython#31559</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gvanrossum'
closed_at = None
created_at = <Date 2022-02-14.20:44:29.619>
labels = ['3.11', 'expert-asyncio']
title = 'Introduce task groups to asyncio and change task cancellation semantics'
updated_at = <Date 2022-02-25.15:33:21.072>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-25.15:33:21.072>
actor = 'yduprat'
assignee = 'gvanrossum'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2022-02-14.20:44:29.619>
creator = 'gvanrossum'
dependencies = []
files = []
hgrepos = []
issue_num = 46752
keywords = ['patch', 'needs review']
message_count = 10.0
messages = ['413260', '413305', '413306', '413335', '413344', '413346', '413348', '413353', '413467', '413577']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'njs', 'asvetlov', 'dhalbert', 'yselivanov', 'tinchester', 'iritkatriel', 'yduprat']
pr_nums = ['31270', '31398', '31409', '31411', '31513', '31559']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46752'
versions = ['Python 3.11']
```

</p></details>

**Comment by warsaw** [comment]
> Documentation and What's New entry (in a separate PR, probably).

Is there a plan or PR yet for documenting `TaskGroup`?  I can find it and there is no documentation in `main` AFAICT.

**Comment by gvanrossum** [comment]
No, that’s why this issue is still open.

**Comment by kumaraditya303** [comment]
Adding deferred blocker as it would be nice to have docs before the rc.

**Comment by gvanrossum** [comment]
I'll try to write docs for taskgroups.

**Comment by gvanrossum** [comment]
We should also document the new Task.uncancel() method, and the subtly new cancellation semantics in general. I'd like to do that in a separate PR: unlike `TaskGroup`, few people will care, and those that do can read the code for now.

**Comment by gvanrossum** [comment]
Now the docs are up we can close this.
