### ISSUE TITLE
Implement asyncio.timeout() context manager

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#90927]
BPO | [46771](https://bugs.python.org/issue46771)
--- | :---
Nosy | @gvanrossum, @njsmith, @jab, @asvetlov, @agronholm, @cjerdonek, @1st1, @Tinche, @iritkatriel, @Dreamsorcerer, @YvesDup, @ajoino
PRs | <li>python/cpython#31270</li><li>python/cpython#31394</li><li>python/cpython#31398</li><li>python/cpython#31415</li><li>python/cpython#31434</li><li>python/cpython#31483</li><li>python/cpython#31508</li><li>python/cpython#31513</li><li>python/cpython#31623</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-16.17:59:12.940>
labels = ['3.11', 'type-feature', 'expert-asyncio']
title = 'Implement asyncio.timeout() context manager'
updated_at = <Date 2022-03-23.21:50:42.068>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.21:50:42.068>
actor = 'asvetlov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2022-02-16.17:59:12.940>
creator = 'gvanrossum'
dependencies = []
files = []
hgrepos = []
issue_num = 46771
keywords = ['patch']
message_count = 76.0
messages = ['413345', '413347', '413349', '413350', '413354', '413356', '413358', '413359', '413360', '413361', '413365', '413366', '413367', '413368', '413369', '413370', '413371', '413372', '413376', '413377', '413387', '413388', '413389', '413402', '413409', '413410', '413411', '413415', '413445', '413460', '413461', '413465', '413466', '413475', '413478', '413480', '413481', '413489', '413491', '413591', '413600', '413601', '413602', '413603', '413604', '413607', '413608', '413610', '413611', '413612', '413613', '413614', '413618', '413619', '413621', '413622', '413623', '413624', '413625', '413631', '413632', '413633', '413760', '413767', '413812', '413820', '413840', '413841', '413874', '414221', '414224', '414853', '414854', '414856', '414857', '414858']
nosy_count = 12.0
nosy_names = ['gvanrossum', 'njs', 'jab', 'asvetlov', 'alex.gronholm', 'chris.jerdonek', 'yselivanov', 'tinchester', 'iritkatriel', 'dreamsorcerer', 'yduprat', 'ajoino']
pr_nums = ['31270', '31394', '31398', '31415', '31434', '31483', '31508', '31513', '31623']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46771'
versions = ['Python 3.11']
```

</p></details>

**Comment by gvanrossum** [comment]
We still need docs for this. There were also some mutterings that perhaps it's not fully cooked. During the beta period I suppose it should be possible to still tweak the API and behavior if testing shows problems. But first and foremost, we need docs. (Writing docs gives you good karma. It can also help reveal weaknesses in the design.)

(@agronholm @Tinche -- adding you back since the migration might have dropped you from the nosy list.)

**Comment by gvanrossum** [comment]
Yeah, unless someone beats you to it, mid June will be give us plenty of time (the last beta is July 9, the final release Oct 3 -- see PEP 664).

**Comment by gvanrossum** [comment]
@Tinche are you still up for writing docs here? It's the other big new thing in asyncio that's yet undocumented... (I'm fixing that for TaskGroup in GH-94359.)

**Comment by Tinche** [comment]
@gvanrossum yes sir. I have not written docs for CPython yet, are there any instructions on how do I get started or should I just figure it out?

**Comment by iritkatriel** [comment]
The devguide has a lot of information in this section: https://devguide.python.org/#contributing

**Comment by gvanrossum** [comment]
FWIW I assume that it should be added to the top of this section: https://docs.python.org/3.12/library/asyncio-task.html#timeouts

**Comment by Tinche** [comment]
Great, thanks. I got COVID so this is a little paused, but I'll get started ASAP

**Comment by gvanrossum** [comment]
Sorry to hear it. Get well soon!

**Comment by gvanrossum** [comment]
@pablogsal This is just lacking documentation. Does that qualify for it to be a (deferred) release blocker? The lack of documentation doesn't affect stability!

**Comment by pablogsal** [comment]
> @pablogsal This is just lacking documentation. Does that qualify for it to be a (deferred) release blocker? The lack of documentation doesn't affect stability!

Yes, there is no problem with this one. This can be left as a deferred blocker and will not affect any betas or RCs 👍

**Comment by achimnol** [comment]
> Can’t happen in 3.11 due to the feature freeze at 3.11b1, and in fact we decided to deprecate the cancel message. There’s some discussion about it (maybe in this issue, maybe in a linked one).

I totally understand now the 3.11 features are frozen.  I just want to note that using cancel messages sometimes greatly helps me to debug and understand what's happening when writing asyncio-based libraries.

**Comment by gvanrossum** [comment]
You should probably start a new discussion if you really want to revert the deprecation of the message parameter. E.g. on discuss.python.org.

**Comment by achimnol** [comment]
I've created [a thread in discuss.python.org](https://discuss.python.org/t/about-the-task-cancel-messages/17122)!

**Comment by Tinche** [comment]
I've started on the docs. I'll be using the docs of the `async-timeout`, `anyio`, `trio` and `quattro` packages as references, I guess.

Where should I put these docs? I'm leaning towards a new section in `asyncio-task.rst`.

We might want to spin out docs on cancellation to a separate page in the future, since I feel like very few people understand the implications of it, and it's (in my opinion) the second most important asyncio superpower.

**Comment by gvanrossum** [comment]
I agree it belongs in `asyncio-task.rst`. It's perhaps most closely related to `wait_for`, so possibly in the same section (on top)? We're not deprecating `wait_for`, but we *are* trying to steer people in the direction of the new context managers.

Eventually we may have an "explanation" about cancellation (using the Diataxis term), but that seems a separate doc change.

**Comment by Tinche** [comment]
How about this for a start: https://github.com/Tinche/cpython/commit/63221c92ba7815a3c3c725f2ed9178f95b52e75d

I have a very small section on task cancellation, and the timeout context managers below, but before `wait_for`.

I feel like a bunch of sections (including the new TaskGroup section) keep mentioning cancellation, so we should at least introduce it fairly quickly.

**Comment by gvanrossum** [comment]
And now that the docs have landed this issue can be laid to rest.
