### ISSUE TITLE
Docs error for 3.10

### ISSUE THREAD

**Issue by 551dbef3-cf37-4e8f-965e-e29e5d65df8a** [python/cpython#90938]
BPO | [46782](https://bugs.python.org/issue46782)
--- | :---
Nosy | @terryjreedy, @merwok, @JulienPalard

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-17.18:12:21.064>
labels = ['type-bug', '3.10', 'docs']
title = 'Docs error for 3.10'
updated_at = <Date 2022-02-19.10:49:50.869>
user = 'https://bugs.python.org/usetohandletrush'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-19.10:49:50.869>
actor = 'eric.araujo'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-02-17.18:12:21.064>
creator = 'usetohandletrush'
dependencies = []
files = []
hgrepos = []
issue_num = 46782
keywords = []
message_count = 4.0
messages = ['413425', '413518', '413533', '413542']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'eric.araujo', 'docs@python', 'mdk', 'usetohandletrush']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46782'
versions = ['Python 3.10']
```

</p></details>

**Comment by CAM-Gerlach** [comment]
Thanks for the ping and sorry for the delay; been heavily backlogged lately.

Seems like the issue was resolved in Sphinx, since both the 3.10 docs (on Sphinx 3.4) and the 3.11/3.12 docs (on Sphinx 4.5) no longer display `0o777` as `511` in the live docs. Therefore, closing, thanks!
