### ISSUE TITLE
ProcessPoolExecutor exception memory leak

### ISSUE THREAD

**Issue by bea15f7d-3e66-46bb-b71c-71f9827ce61a** [python/cpython#90943]
BPO | [46787](https://bugs.python.org/issue46787)
--- | :---
Nosy | @themylogin
PRs | <li>python/cpython#31408</li>
Files | <li>[1.py](https://bugs.python.org/file50628/1.py "Uploaded as text/plain at 2022-02-18.15:16:10 by @themylogin")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-18.15:16:10.733>
labels = ['library', '3.9', 'performance']
title = 'ProcessPoolExecutor exception memory leak'
updated_at = <Date 2022-02-18.15:23:21.328>
user = 'https://github.com/themylogin'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-18.15:23:21.328>
actor = 'python-dev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-18.15:16:10.733>
creator = 'themylogin'
dependencies = []
files = ['50628']
hgrepos = []
issue_num = 46787
keywords = ['patch']
message_count = 1.0
messages = ['413485']
nosy_count = 2.0
nosy_names = ['python-dev', 'themylogin']
pr_nums = ['31408']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue46787'
versions = ['Python 3.9']
```

</p></details>

**Comment by clchiou** [comment]
I wonder if this patch also needs to be applied to [Lib/multiprocessing/pool.py](https://github.com/python/cpython/blob/538f28921f67e36617272faa662375d305d9284c/Lib/multiprocessing/pool.py#L63) as it appears to me that Lib/concurrent/futures/process.py and Lib/multiprocessing/pool.py are quite similar in this aspect: sending exceptions with (stringified) traceback across process boundary. What do you think?
