### ISSUE TITLE
Add LOAD_FAST__LOAD_ATTR_INSTANCE_VALUE combined opcode

### ISSUE THREAD

**Issue by sweeneyde** [python/cpython#90979]
BPO | [46823](https://bugs.python.org/issue46823)
--- | :---
Nosy | @markshannon, @brandtbucher, @sweeneyde
PRs | <li>python/cpython#31484</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-22.05:11:54.712>
labels = []
title = 'Add LOAD_FAST__LOAD_ATTR_INSTANCE_VALUE combined opcode'
updated_at = <Date 2022-03-03.20:07:12.224>
user = 'https://github.com/sweeneyde'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.20:07:12.224>
actor = 'brandtbucher'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-02-22.05:11:54.712>
creator = 'Dennis Sweeney'
dependencies = []
files = []
hgrepos = []
issue_num = 46823
keywords = ['patch']
message_count = 3.0
messages = ['413692', '413916', '414463']
nosy_count = 3.0
nosy_names = ['Mark.Shannon', 'brandtbucher', 'Dennis Sweeney']
pr_nums = ['31484']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46823'
versions = []
```

</p></details>

**Comment by markshannon** [comment]
The adapter interpreter is strictly a one-instruction-at-a-time optimizer, and does not specialize superinstructions.
`LOAD_FAST__LOAD_ATTR_INSTANCE_VALUE` is clearly a specialized superinstruction, so we should leave it for tier-2.
Any tier-2 interpreter will have its own set of superinstructions, presumably automatically generated.
