### ISSUE TITLE
Windows installer is unclear and has redundant settings

### ISSUE THREAD

**Issue by 1b2848ad-d498-46e8-b8a5-0becdd0d891c** [python/cpython#90989]
BPO | [46833](https://bugs.python.org/issue46833)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @Codeberg-AsGithubAlternative-buhtz
Files | <li>[python3_9_10_install_wizard_page1-3.png](https://bugs.python.org/file50638/python3_9_10_install_wizard_page1-3.png "Uploaded as image/png at 2022-02-23.08:22:08 by @Codeberg-AsGithubAlternative-buhtz"): Screenshot of all 3 installer wizart pages at once</li><li>[py_installer.pdf](https://bugs.python.org/file50640/py_installer.pdf "Uploaded as application/pdf at 2022-02-23.16:49:00 by @Codeberg-AsGithubAlternative-buhtz"): drafts of 4 variants of an alternative install wizard</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-23.08:22:08.475>
labels = ['expert-installation', 'OS-windows', '3.11']
title = 'Windows installer is unclear and has redundant settings'
updated_at = <Date 2022-02-26.15:00:05.612>
user = 'https://github.com/Codeberg-AsGithubAlternative-buhtz'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-26.15:00:05.612>
actor = 'eric.araujo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2022-02-23.08:22:08.475>
creator = 'buhtz'
dependencies = []
files = ['50638', '50640']
hgrepos = []
issue_num = 46833
keywords = []
message_count = 6.0
messages = ['413777', '413793', '413809', '413818', '413932', '414081']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'buhtz', 'h30-04213']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46833'
versions = ['Python 3.11']
```

</p></details>

**Comment by zooba** [comment]
I made some tweaks to the text that should be helpful. I also made the launcher install per-user by default (unless an existing version is for all users, in which case the option gets flipped automatically), which I've been planning to do for a while. I don't think I can backport that change, unfortunately, but I'll take the text updates back to 3.10
