### ISSUE TITLE
Confusing CancelError message if multiple cancellations are scheduled

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#90985]
BPO | [46829](https://bugs.python.org/issue46829)
--- | :---
Nosy | @gvanrossum, @njsmith, @jab, @asvetlov, @agronholm, @cjerdonek, @serhiy-storchaka, @1st1, @Tinche, @iritkatriel, @Dreamsorcerer, @ajoino
PRs | <li>python/cpython#31840</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-23.16:01:27.456>
created_at = <Date 2022-02-22.22:02:51.215>
labels = ['3.11', 'expert-asyncio']
title = 'Confusing CancelError message if multiple cancellations are scheduled'
updated_at = <Date 2022-03-23.16:01:27.455>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.16:01:27.455>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-23.16:01:27.456>
closer = 'gvanrossum'
components = ['asyncio']
creation = <Date 2022-02-22.22:02:51.215>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 46829
keywords = ['patch']
message_count = 13.0
messages = ['413749', '413753', '413755', '413757', '413776', '413817', '413821', '415013', '415014', '415098', '415099', '415879', '415883']
nosy_count = 12.0
nosy_names = ['gvanrossum', 'njs', 'jab', 'asvetlov', 'alex.gronholm', 'chris.jerdonek', 'serhiy.storchaka', 'yselivanov', 'tinchester', 'iritkatriel', 'dreamsorcerer', 'ajoino']
pr_nums = ['31840']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue46829'
versions = ['Python 3.11']
```

</p></details>

**Comment by fancidev** [comment]
Late to the party, but an alternative to make both party happy might be to let Task.cancel accept an exception object that’s derived from asyncio.CancelledError?

**Comment by xitop** [comment]
Could the problem discussed here be solved with exceptions notes? The PEP-678 mentions adding notes to caught exceptions, but I tested that it is possible to create an exception instance with several notes added and raise it (I did not test throwing it into a coroutine though).
