### ISSUE TITLE
Inline bytecode caches

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#90997]
BPO | [46841](https://bugs.python.org/issue46841)
--- | :---
Nosy | @markshannon, @corona10, @pablogsal, @brandtbucher, @neonene, @iritkatriel, @penguin-wwy
PRs | <li>python/cpython#31543</li><li>python/cpython#31552</li><li>python/cpython#31575</li><li>python/cpython#31591</li><li>python/cpython#31618</li><li>python/cpython#31622</li><li>python/cpython#31640</li><li>python/cpython#31663</li><li>python/cpython#31664</li><li>python/cpython#31671</li><li>python/cpython#31709</li><li>python/cpython#31742</li><li>python/cpython#31780</li><li>python/cpython#31817</li><li>python/cpython#31888</li><li>python/cpython#31901</li><li>python/cpython#31968</li><li>python/cpython#32099</li><li>python/cpython#32100</li><li>python/cpython#32205</li><li>python/cpython#32222</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brandtbucher'
closed_at = None
created_at = <Date 2022-02-24.02:17:14.449>
labels = ['interpreter-core', 'deferred-blocker', '3.11', 'performance']
title = 'Inline bytecode caches'
updated_at = <Date 2022-04-01.11:29:28.677>
user = 'https://github.com/brandtbucher'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-01.11:29:28.677>
actor = 'Mark.Shannon'
assignee = 'brandtbucher'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-02-24.02:17:14.449>
creator = 'brandtbucher'
dependencies = []
files = []
hgrepos = []
issue_num = 46841
keywords = ['patch']
message_count = 29.0
messages = ['413875', '413901', '413987', '413988', '414188', '414194', '414261', '414277', '414343', '414349', '414358', '414359', '414364', '414371', '414372', '414378', '414391', '414461', '414490', '414523', '414547', '414696', '414763', '414955', '415307', '415676', '415969', '416482', '416483']
nosy_count = 7.0
nosy_names = ['Mark.Shannon', 'corona10', 'pablogsal', 'brandtbucher', 'neonene', 'iritkatriel', 'penguin_wwy']
pr_nums = ['31543', '31552', '31575', '31591', '31618', '31622', '31640', '31663', '31664', '31671', '31709', '31742', '31780', '31817', '31888', '31901', '31968', '32099', '32100', '32205', '32222']
priority = 'deferred blocker'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue46841'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-102569

**Comment by pablogsal** [comment]
⚠️ This issue has been updated from 'deferred-blocker' to 'release blocker' as we are past beta1. This issue will block the next release (`Python 3.11.0 beta 2`). ⚠️

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by markshannon** [comment]
No. This is done.
