### ISSUE TITLE
Parameters and arguments parser syntax error improvments

### ISSUE THREAD

**Issue by 5e760aa2-a555-4939-ba06-206fc75f8e67** [python/cpython#90994]
BPO | [46838](https://bugs.python.org/issue46838)
--- | :---
Nosy | @terryjreedy, @aroberge, @lysnikolaou, @pablogsal, @Andykl
PRs | <li>python/cpython#31590</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-23.21:23:21.121>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Parameters and arguments parser syntax error improvments'
updated_at = <Date 2022-03-22.11:39:09.698>
user = 'https://github.com/Andykl'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.11:39:09.698>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Parser']
creation = <Date 2022-02-23.21:23:21.121>
creator = 'Andy_kl'
dependencies = []
files = []
hgrepos = []
issue_num = 46838
keywords = ['patch']
message_count = 6.0
messages = ['413856', '413858', '413860', '414038', '414052', '415760']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'aroberge', 'lys.nikolaou', 'pablogsal', 'Andy_kl']
pr_nums = ['31590']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46838'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-96893

**Comment by hauntsaninja** [comment]
Thanks Andykl for the suggestion and pablogsal and lysnikolaou for implementing. I think all of the suggestions have now been implemented, so this can be closed.

Also linking Pablo's PR https://github.com/python/cpython/pull/31590 (since it linked the bpo)
