### ISSUE TITLE
Odd handling of signal raised if an illegal syscall is attempted on Android

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#91028]
BPO | [46872](https://bugs.python.org/issue46872)
--- | :---
Nosy | @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-27.11:26:00.251>
labels = ['expert-C-API', 'type-bug']
title = 'Odd handling of signal raised if an illegal syscall is attempted on Android'
updated_at = <Date 2022-02-27.11:26:00.251>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-27.11:26:00.251>
actor = 'bup'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-02-27.11:26:00.251>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 46872
keywords = []
message_count = 1.0
messages = ['414148']
nosy_count = 1.0
nosy_names = ['bup']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46872'
versions = []
```

</p></details>

**Comment by mhsmith** [comment]
Most of these functions have now been disabled at build time by #115955. The only missing one is `socket.sethostname`, which I didn't notice because it isn't available until API level 23, and we're building against level 21. I'll create a separate PR to fix that.
