### ISSUE TITLE
Improve performance of math.prod with bignums (and functools.reduce?)

### ISSUE THREAD

**Issue by c6a16194-fbe2-452d-ab7b-5a02c5e92e91** [python/cpython#91024]
BPO | [46868](https://bugs.python.org/issue46868)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-26.23:35:53.176>
labels = ['type-feature', 'library', '3.11']
title = 'Improve performance of math.prod with bignums (and functools.reduce?)'
updated_at = <Date 2022-03-01.02:30:42.062>
user = 'https://bugs.python.org/benrg'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-01.02:30:42.062>
actor = 'tim.peters'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-26.23:35:53.176>
creator = 'benrg'
dependencies = []
files = []
hgrepos = []
issue_num = 46868
keywords = []
message_count = 9.0
messages = ['414126', '414138', '414144', '414164', '414216', '414219', '414225', '414231', '414233']
nosy_count = 4.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'benrg']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46868'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
So what is the conclusion? `treereduce()` could not help in general case for `math.prod()`. Writing integer-specific optimization for `math.prod()` is perhaps not worth hassle. If you need to multiply millions of integers, a pure Python implementation should be enough, and it can also utilize the specifics of your application.

**Comment by tim-one** [comment]
After over 2 years w/o another comment, I'm closing as "not planned";
