### ISSUE TITLE
Deprecate ob_shash in BytesObject

### ISSUE THREAD

**Issue by methane** [python/cpython#91020]
BPO | [46864](https://bugs.python.org/issue46864)
--- | :---
Nosy | @tiran, @methane, @serhiy-storchaka, @animalize, @brandtbucher
PRs | <li>python/cpython#31598</li><li>python/cpython#32042</li><li>python/cpython#32176</li>
Files | <li>[remove-bytes-hash.patch](https://bugs.python.org/file50649/remove-bytes-hash.patch "Uploaded as text/plain at 2022-02-27.02:52:55 by @methane")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-25.02:15:16.155>
created_at = <Date 2022-02-26.08:49:05.075>
labels = ['interpreter-core', 'build', '3.11']
title = 'Deprecate ob_shash in BytesObject'
updated_at = <Date 2022-03-30.06:35:35.207>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-30.06:35:35.207>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-25.02:15:16.155>
closer = 'methane'
components = ['Interpreter Core']
creation = <Date 2022-02-26.08:49:05.075>
creator = 'methane'
dependencies = []
files = ['50649']
hgrepos = []
issue_num = 46864
keywords = ['patch']
message_count = 21.0
messages = ['414083', '414096', '414134', '414136', '414605', '415684', '415743', '415744', '415747', '415748', '415749', '415854', '415855', '415857', '415865', '415923', '415925', '415927', '415958', '415984', '416325']
nosy_count = 5.0
nosy_names = ['christian.heimes', 'methane', 'serhiy.storchaka', 'malin', 'brandtbucher']
pr_nums = ['31598', '32042', '32176']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue46864'
versions = ['Python 3.11']
```

</p></details>

**Comment by seberg** [comment]
This has been brought up in NumPy, NumPy subclasses bytes, and I am not immediately sure how to best initialize the hash value.  We can't really call `__new__` from C, but `FromString` would give the wrong type.

Would it make sense to move the `-1` initialization to a custom `tp_alloc`?  Or am I missing an obvious solution?  If this the slow is removed entirely, then it does not matter of course.

**Comment by methane** [comment]
> This has been brought up in NumPy, NumPy subclasses bytes, and I am not immediately sure how to best initialize the hash value.

Would you give me a link to the code?

> Would it make sense to move the -1 initialization to a custom tp_alloc? Or am I missing an obvious solution? If this the slow is removed entirely, then it does not matter of course.

How about tp_init?

**Comment by seberg** [comment]
@methane the code is here:
https://github.com/numpy/numpy/blob/46a61b3aed3cf674586b456b05c6c9b7b9c5020d/numpy/core/src/multiarray/scalarapi.c#L687

With the initialization a [bit later](https://github.com/numpy/numpy/blob/46a61b3aed3cf674586b456b05c6c9b7b9c5020d/numpy/core/src/multiarray/scalarapi.c#L709).

The point being, this creates a bytes subclass the manual way currently.  I am not condoning that, but I am also not sure there is an obvious replacement for creating a byte subclass instances. `FromStringAndSize` would be the right thing, but that won't give the subclass.

**Comment by methane** [comment]
Thank you. tp_alloc seems good.

**Comment by serhiy-storchaka** [comment]
What are problems with calling `__new__` (`tp_new`)?

**Comment by methane** [comment]
Current ideas:

* Create custom `.tp_alloc()`
* Add new `PyTypeObject *type` parameter to `_PyBytes_FromSize()` and expose it as a cpython API.

BTW, Since bytes object is PyVarObject, every subclasses won't extend the PyBytesObject, am I right?

**Comment by seberg** [comment]
> BTW, Since bytes object is PyVarObject, every subclasses won't extend the PyBytesObject, am I right?

NumPy certainly does not, I suppose you could dynamically add more "items" at the end in a custom `tp_alloc`, though?  Again, I am happy with changes or removal of `ob_shash` (so long it is not in a bug-fix release).
It just would be nice to avoid the `DeprecationWarning` in a clean way

**Comment by mattip** [comment]
The happy path of the code in question is:
```C
    PyTypeObject *type = /* get the type object */;
    int itemsize = /* get the string 'length' */;
    PyObject *obj;
    void *destptr;
    obj = type->tp_alloc(type, itemsize);
    destptr = PyBytes_AS_STRING(obj);
    ((PyBytesObject *)obj)->ob_shash = -1;
    memcpy(destptr, data, itemsize);
    return obj;
```

How should NumPy refactor that?

**Comment by methane** [comment]
```c
#if PY_VERSION_HEX < 0x030b00b0
    ((PyBytesObject *)obj)->ob_shash = -1;
#endif
```

**Comment by rhettinger** [comment]
I recommend keeping the `ob_shash` field.  The memory use is negligible (10% on tiny bytes instances and diminishing further in significance as the sizes get larger.   

The caching benefit doesn't happen often but when it does the benefits are significant.  Crypto hashes are always stored as bytes and we use them to check for duplicates (i.e. they way git works).  The output of str.encode() is bytes and it is legitimate to use this as a cache key (with the lru_cache) for example.  If I recall correctly, DNA sequence fragments are often stored as bytes and are used for dict/set lookups.

This code has been stable for a very long time and it is almost certain that some code in the wild depends on cached hash values for efficient computation.   The deprecation damages that code for no good reason.  It is a false optimization (in chess, we call it pawn grabbing).

**Comment by methane** [comment]
Memory saving is not the only reason for this change.
Please read [my previous comment](https://github.com/python/cpython/issues/91020#issuecomment-1093945674).

This issue doesn't remove the hash cache.
This issue only deprecate direct access to `PyBytesObjects.ob_shash`.
Even if we won't remove the hash cache, direct access to struct member is not recommended.

**Comment by rhettinger** [comment]
The hash cache should remain.  If you want to block direct access to the structure member that is reasonable.
