### ISSUE TITLE
getpath problems with framework build

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#91046]
BPO | [46890](https://bugs.python.org/issue46890)
--- | :---
Nosy | @vsajip, @ronaldoussoren, @ned-deily, @ericsnowcurrently, @eryksun, @zooba, @pablogsal
PRs | <li>python/cpython#31958</li>
Files | <li>[issue-46890.txt](https://bugs.python.org/file50660/issue-46890.txt "Uploaded as text/plain at 2022-03-07.11:52:51 by @ronaldoussoren")</li><li>[issue-46890-v2.txt](https://bugs.python.org/file50662/issue-46890-v2.txt "Uploaded as text/plain at 2022-03-07.13:50:49 by @ronaldoussoren")</li><li>[issue-46890-v3.txt](https://bugs.python.org/file50669/issue-46890-v3.txt "Uploaded as text/plain at 2022-03-13.10:38:20 by @ronaldoussoren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-01.16:25:46.271>
labels = ['OS-mac', 'interpreter-core', 'deferred-blocker', 'type-bug', '3.11', 'library']
title = 'getpath problems with framework build'
updated_at = <Date 2022-04-05.06:05:44.693>
user = 'https://github.com/ronaldoussoren'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.06:05:44.693>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Library (Lib)', 'macOS']
creation = <Date 2022-03-01.16:25:46.271>
creator = 'ronaldoussoren'
dependencies = []
files = ['50660', '50662', '50669']
hgrepos = []
issue_num = 46890
keywords = ['patch', '3.11regression']
message_count = 29.0
messages = ['414278', '414281', '414282', '414285', '414288', '414290', '414291', '414336', '414337', '414341', '414348', '414354', '414355', '414365', '414373', '414659', '414665', '414667', '414669', '414676', '414699', '414701', '415033', '415175', '415334', '415335', '415343', '415346', '416755']
nosy_count = 7.0
nosy_names = ['vinay.sajip', 'ronaldoussoren', 'ned.deily', 'eric.snow', 'eryksun', 'steve.dower', 'pablogsal']
pr_nums = ['31958']
priority = 'deferred blocker'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46890'
versions = ['Python 3.11']
```

</p></details>

**Comment by pablogsal** [comment]
⚠️ This issue has been updated from 'deferred-blocker' to 'release blocker' as we are past beta1. This issue will block the next release (`Python 3.11.0 beta 2`). ⚠️

**Comment by ronaldoussoren** [comment]
This issue itself has been fixed, one thing I still want to look into is one of my comments about looking for python311.zip outside of ``sys.prefix``, but that should be a different issue (if I find anything).
