### ISSUE TITLE
Typo hint message for from-imports?

### ISSUE THREAD

**Issue by d5768b30-a370-4853-a7d6-588a74fb273c** [python/cpython#91058]
BPO | [46902](https://bugs.python.org/issue46902)
--- | :---
Nosy | @aroberge, @pablogsal, @Jean-Abou-Samra

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-02.20:42:20.452>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Typo hint message for from-imports?'
updated_at = <Date 2022-03-03.01:54:35.713>
user = 'https://github.com/Jean-Abou-Samra'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.01:54:35.713>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-02.20:42:20.452>
creator = 'Jean_Abou_Samra'
dependencies = []
files = []
hgrepos = []
issue_num = 46902
keywords = []
message_count = 2.0
messages = ['414385', '414398']
nosy_count = 3.0
nosy_names = ['aroberge', 'pablogsal', 'Jean_Abou_Samra']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46902'
versions = ['Python 3.11']
```

</p></details>

* PR: gh-99198

**Comment by erlend-aasland** [comment]
Pablo's reply hints that the added complexity would not be worth it. I suggest to consider closing this as rejected, unless Pablo found a less complex way :)

**Comment by aroberge** [comment]
Perhaps it is doable within CPython without too much added code since is something that friendly_traceback can do.
```
[1]: from pygments.regexopt import regexopt

Traceback (most recent call last):
  Code block [1], line 1
    from pygments.regexopt import regexopt
ImportError: cannot import name 'regexopt' from 'pygments.regexopt'
(C:\Users\Andre.Roberge\AppData\Local\Programs\Python\Python310\lib\site-packages\pygments\regexopt.py)

Did you mean regex_opt?

[2]: why()

Perhaps you meant to import regex_opt (from pygments.regexopt) instead of regexopt

[3] import sys;

[4] 'pygments' in sys.modules
True
```

**Comment by pablogsal** [comment]
@aroberge You comment shows that friendly_traceback does it but unfortunately, it doesn't mention how you are proposing us to do it so we cannot evaluate the solution :( Could you add a brief sketch of how you are doing it in `friendly_traceback`?

**Comment by aroberge** [comment]
@pablogsal `friendly_traceback` looks at the list of modules found in `sys.modules` and, if the desired module is found, it proceeds from there.

The relevant code starts at: 
https://github.com/friendly-traceback/friendly-traceback/blob/cdf87b1a623c4afcab4ad869eb29fe885e2d0621/friendly_traceback/runtime_errors/import_error.py#L104

Perhaps the way that the information available to friendly_traceback after an exception has been raised is not yet available to CPython at that point, but I thought I should mention this possibility.

**Comment by pablogsal** [comment]
> @pablogsal `friendly_traceback` looks at the list of modules found in `sys.modules` and, if the desired module is found, it proceeds from there.
> 
> The relevant code starts at: [friendly-traceback/friendly-traceback@`cdf87b1`/friendly_traceback/runtime_errors/import_error.py#L104](https://github.com/friendly-traceback/friendly-traceback/blob/cdf87b1a623c4afcab4ad869eb29fe885e2d0621/friendly_traceback/runtime_errors/import_error.py#L104)
> 
> Perhaps the way that the information available to friendly_traceback after an exception has been raised is not yet available to CPython at that point, but I thought I should mention this possibility.

The problem with this approach is that if we do this every time the interpreter raises an `ImportError` we will slow down the interpreter when someone is catching said exception and continuing so they will have to pay an important (unbounded) cost for a message they won't see. That is what I am trying to circumvent.

**Comment by aroberge** [comment]
Understood; most Python users (myself included) do appreciate this emphasis on speed. Those requiring better traceback analysis can use third-party packages, like friendly_traceback.

**Comment by erlend-aasland** [comment]
Yeah, I think this approach is not very useful for CPython. A lot of stdlib modules try to import their C implementation first, else fall back to a Python implementation. I think we can safely close this.

**Comment by pablogsal** [comment]
The fairy of error messages is back! I found a way to implement this without penalty to control-flow failed imports that is quite clean IMHO
