### ISSUE TITLE
add support for watching writes to selected dictionaries

### ISSUE THREAD

**Issue by carljm** [python/cpython#91052]
BPO | [46896](https://bugs.python.org/issue46896)
--- | :---
Nosy | @gvanrossum, @warsaw, @gpshead, @carljm, @DinoV, @markshannon, @brandtbucher, @sweeneyde, @itamaro
PRs | <li>python/cpython#31787</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-01.22:19:05.128>
labels = ['expert-C-API', '3.11']
title = 'add support for watching writes to selected dictionaries'
updated_at = <Date 2022-03-15.17:17:40.946>
user = 'https://github.com/carljm'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-15.17:17:40.946>
actor = 'carljm'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-03-01.22:19:05.128>
creator = 'carljm'
dependencies = []
files = []
hgrepos = []
issue_num = 46896
keywords = ['patch']
message_count = 22.0
messages = ['414307', '414330', '414462', '414466', '414467', '414468', '414470', '414531', '414540', '414551', '414803', '414804', '414808', '414810', '414839', '414877', '414882', '414898', '414899', '415253', '415261', '415268']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'barry', 'gregory.p.smith', 'carljm', 'dino.viehland', 'Mark.Shannon', 'brandtbucher', 'Dennis Sweeney', 'itamaro']
pr_nums = ['31787']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46896'
versions = ['Python 3.11']
```

</p></details>

**Comment by carljm** [comment]
@markshannon and I discussed this at the PyCon sprints and agreed on an alternative design that places more complexity in the CPython core in exchange for making it easier to implement watching clients (and probably somewhat more CPU-efficient overall in the presence of multiple watching clients).

The design will still initially not support per-key watching, only watching of entire dicts; per-key watching can be layered on top of it later without disturbing the initial whole-dict semantics.

The change is that now the core dispatcher will track individual watchers, limited to a maximum of 8 watchers total. This seems reasonable given that we don't really see a use case for more than 3 watchers (the interpreter loop, maybe a JIT, and maybe a debugger) to be active at one time. 640k should be more than enough for anybody, right?!

Rather than stealing only one bit from the dict version, we will now steal 8, one bit for each registered watcher. When a watcher first registers its callback, it will get back an integer ID. Whenever it wants to watch or unwatch a dict, it must pass in that ID. Each dict will track a "watched" bit for each watcher.

The advantages of this design are that a) watchers are no longer responsible to chain to other watchers, b) watchers no longer have to potentially handle events for dicts they did not ask to watch (and thus don't have to necessarily maintain their own internal data structure of dicts they are interested in and check that data structure for every event), and c) it can now be possible for a client to unwatch a dict, since that won't impact other clients.

A future enhancement (which will probably need a PEP, to take over the dict version entirely) can replace the dict version with a pointer to an array that holds a byte per key, marking which watcher(s) are interested in each individual key, as suggested by Mark above.

cc @DinoV @mpage @kmod

**Comment by mpage** [comment]
Sounds good to me! This still supports Cinder's use case and should require minimal effort on our end.

**Comment by gvanrossum** [comment]
This issue seems stalled. IIRC Mark and Carl have agreed on a plan -- who's on the hook for executing (getting a PR ready for review in 3.12)?

**Comment by carljm** [comment]
I am on the hook, just not finding time... I definitely plan to make it happen in time for 3.12 though.

**Comment by carljm** [comment]
Fixed with merge of https://github.com/python/cpython/pull/31787
