### ISSUE TITLE
Update Windows and MacOS installer to SQLite 3.38.4

### ISSUE THREAD

**Issue by 341b2d53-9c47-429a-89a2-f88644ed631d** [python/cpython#91063]
BPO | [46907](https://bugs.python.org/issue46907)
--- | :---
Nosy | @pfmoore, @ronaldoussoren, @tjguk, @ned-deily, @zware, @zooba, @tirkarthi, @erlend-aasland, @felixxm, @180909
PRs | <li>python/cpython#31655</li><li>python/cpython#31656</li><li>python/cpython#32147</li><li>python/cpython#32148</li><li>python/cpython#32149</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-03.08:27:32.906>
labels = ['OS-mac', 'type-feature', 'OS-windows', '3.11']
title = 'Update Windows and MacOS installer to SQLite 3.38.2'
updated_at = <Date 2022-03-31.18:05:03.473>
user = 'https://github.com/felixxm'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-31.18:05:03.473>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Windows']
creation = <Date 2022-03-03.08:27:32.906>
creator = 'felixxm'
dependencies = []
files = []
hgrepos = []
issue_num = 46907
keywords = ['patch']
message_count = 17.0
messages = ['414412', '414413', '414414', '415015', '415251', '415265', '415266', '415269', '415270', '415271', '416140', '416274', '416429', '416442', '416446', '416450', '416453']
nosy_count = 10.0
nosy_names = ['paul.moore', 'ronaldoussoren', 'tim.golden', 'ned.deily', 'zach.ware', 'steve.dower', 'xtreak', 'erlendaasland', 'felixxm', 'wangjiahua']
pr_nums = ['31655', '31656', '32147', '32148', '32149']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46907'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
> https://sqlite.org/src/info/336851b191fe79f0 was merged to the 3.38 branch, so we should expect 3.38.3 in the coming days.

I haven't seen any signs for an upcoming release on the forum, and the 3.38 branch haven't been touched in weeks. Let's just merge gh-32147 and gh-32148 now, so we have a fresh lib for the upcoming alpha :)

**Comment by zooba** [comment]
Are we backporting this? Normally it needs manual backports, but I can try the tags if someone lets me know how far back it ought to go.

**Comment by felixxm** [comment]
I can prepare backports, if needed.

**Comment by erlend-aasland** [comment]
Last time we backported an SQLite bump, it was because of a data corruption bugfix. AFAIK, there's nothing like that in SQLite 3.38, _but_ historically there has been no consistency for how to backport these PRs. I'm fine with backporting if the release managers are :)

**Comment by erlend-aasland** [comment]
> I haven't seen any signs for an upcoming release on the forum, and the 3.38 branch haven't been touched in weeks. Let's just merge gh-32147 and gh-32148 now, so we have a fresh lib for the upcoming ~alpha~ beta! :)

Hah, I'll eat those words! 😆 The SQLite 3.38.3 release announcement just arrived in my inbox.

**Comment by felixxm** [comment]
@erlend-aasland Will do, thanks :+1:

**Comment by erlend-aasland** [comment]
FYI, I've updated the sources deps repo, so all is set for the Windows installer/PR.

**Comment by ned-deily** [comment]
And today [3.38.4](https://sqlite.org/releaselog/3_38_4.html) was released. Sigh!

**Comment by erlend-aasland** [comment]
Quoting an email that appeared in my inbox, some forty minutes ago:

> SQLite version 3.38.5 is now available on the website.
>
> As previously announced, the 3.38.4 patch release contained a bug.  There was a last-minute change, and rather than run the full test suite after that change, only spot-checks were run.  Those spot checks missed a fatal flaw in the last-minute change.  This patch release fixes that problem that was introduced by the last-minute change in the previous release.
>
> The lesson from this is: Always, always, always run the full test suite before every release, even for just a "trivial" change.  I knew this.  But sometimes I need reminders.
>
> Sorry for the extra, unnecessary, release...

The good news is that the new release apparently only affects the CLI, so we're good to go. Quoting the 3.38.5 [changelog](https://sqlite.org/releaselog/3_38_5.html):

> Fix [a blunder](https://sqlite.org/news.html#2022-05-06) in the [CLI](https://sqlite.org/cli.html) of the 3.38.4 release.

**Comment by erlend-aasland** [comment]
I'm closing this issue, as the macOS and Windows installers are now updated to SQLite 3.38.4. If a relevant SQLite 3.38 patch release appears in the future, open a new issue.

Thanks for the PRs, Mariusz!
