### ISSUE TITLE
winsound.PlaySound should accept pathlib.Path instances

### ISSUE THREAD

**Issue by 036e467e-0df1-4087-ab78-784f40d86bfb** [python/cpython#91061]
BPO | [46905](https://bugs.python.org/issue46905)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @Julian-O

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-03.00:02:59.656>
labels = ['easy', 'type-feature', 'library', 'OS-windows', '3.11']
title = 'winsound.PlaySound should accept pathlib.Path instances'
updated_at = <Date 2022-03-03.06:53:50.243>
user = 'https://github.com/Julian-O'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.06:53:50.243>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2022-03-03.00:02:59.656>
creator = 'Julian-O'
dependencies = []
files = []
hgrepos = []
issue_num = 46905
keywords = ['easy (C)']
message_count = 2.0
messages = ['414393', '414408']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Julian-O']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46905'
versions = ['Python 3.11']
```

</p></details>

**Comment by moribellamy** [comment]
I'm interested in trying this issue. What's an appropriate way to test the fix in CI? I'm assuming manual testing will be straightforward (just build the binary and have a simple script that tries to use a PathLib.Path instead of a string)

**Comment by moribellamy** [comment]
Thanks all. My first ever python PR is out. Looking forward to learning how to do things properly :)
