### ISSUE TITLE
Python Decimal supports '#' format, C Decimal does not.

### ISSUE THREAD

**Issue by fbd3a0ca-e824-4253-b45f-5be9a11e51c4** [python/cpython#91060]
BPO | [46904](https://bugs.python.org/issue46904)
--- | :---
Nosy | @mdickinson, @ericvsmith, @cgevans

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-02.23:39:51.993>
labels = ['type-bug', 'library', '3.10', '3.11']
title = "Python Decimal supports '#' format, C Decimal does not."
updated_at = <Date 2022-03-03.00:03:06.014>
user = 'https://github.com/cgevans'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.00:03:06.014>
actor = 'eric.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-02.23:39:51.993>
creator = 'const'
dependencies = []
files = []
hgrepos = []
issue_num = 46904
keywords = []
message_count = 1.0
messages = ['414390']
nosy_count = 3.0
nosy_names = ['mark.dickinson', 'eric.smith', 'const']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46904'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by mdickinson** [comment]
I agree that the Python and C versions of Decimal should be consistent. The support in the Python version definitely _was_ intentional, and I'd be reluctant to remove it. So options are: (a) do nothing, (b) document the discrepancy, or (c) fix cdecimal.

#58046 is somewhat related.

**Comment by skrah** [comment]
This is fixed by applying the general format patch in #114563.
