### ISSUE TITLE
Document dict behavior when setting equal but not identical key

### ISSUE THREAD

**Issue by b4b182d0-7159-460b-928a-e7dab6ddc2f9** [python/cpython#91081]
BPO | [46925](https://bugs.python.org/issue46925)
--- | :---
Nosy | @rhettinger, @methane, @malthe, @JelleZijlstra, @potiuk
PRs | <li>python/cpython#31685</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-04.23:25:53.644>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = 'Document dict behavior when setting equal but not identical key'
updated_at = <Date 2022-03-07.10:13:25.530>
user = 'https://github.com/malthe'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-07.10:13:25.530>
actor = 'potiuk'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-03-04.23:25:53.644>
creator = 'malthe'
dependencies = []
files = []
hgrepos = []
issue_num = 46925
keywords = []
message_count = 9.0
messages = ['414554', '414560', '414562', '414572', '414581', '414586', '414607', '414636', '414652']
nosy_count = 6.0
nosy_names = ['rhettinger', 'methane', 'docs@python', 'malthe', 'JelleZijlstra', 'potiuk']
pr_nums = ['31685']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46925'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-91499
* gh-100390
* gh-100391

**Comment by hauntsaninja** [comment]
Thanks to slateny, the behaviour is now documented in the weakref docs. Since this addresses OP's issue, which is where this is most clearly pernicious, I'm closing. But do let me know if you think this should be documented more generally somewhere else.
