### ISSUE TITLE
Logger with a custom class breaks on copy

### ISSUE THREAD

**Issue by b889d301-32ce-4209-8756-ab5aeed0023a** [python/cpython#91113]
BPO | [46957](https://bugs.python.org/issue46957)
--- | :---
Nosy | @ericvsmith, @govinda18

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-08.12:45:10.453>
labels = ['library', '3.9', 'type-crash']
title = 'Logger with a custom class breaks on copy'
updated_at = <Date 2022-03-09.07:11:41.061>
user = 'https://github.com/govinda18'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-09.07:11:41.061>
actor = 'eric.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-08.12:45:10.453>
creator = 'govinda18'
dependencies = []
files = []
hgrepos = []
issue_num = 46957
keywords = []
message_count = 2.0
messages = ['414750', '414786']
nosy_count = 2.0
nosy_names = ['eric.smith', 'govinda18']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue46957'
versions = ['Python 3.9']
```

</p></details>

**Comment by vsajip** [comment]
> I am not sure that overriding instantiated loggers is supported strategy

No, it isn't. People sometimes use (and misuse) logging in odd ways for no particularly good reasons, so without knowing more about this specific use case, it's not yet clear whether it's worthy of any special support.
