### ISSUE TITLE
dataclass(slots=True) incompatible with __init_subclass__

### ISSUE THREAD

**Issue by 1c23ebe2-087a-4be2-9b19-c5cb5aeb1577** [python/cpython#91126]
BPO | [46970](https://bugs.python.org/issue46970)
--- | :---
Nosy | @ericvsmith, @crusaderky

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2022-03-10.00:14:28.417>
labels = ['type-bug', 'library', '3.10']
title = 'dataclass(slots=True) incompatible with __init_subclass__'
updated_at = <Date 2022-03-10.00:28:03.767>
user = 'https://github.com/crusaderky'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-10.00:28:03.767>
actor = 'eric.smith'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-10.00:14:28.417>
creator = 'crusaderky'
dependencies = []
files = []
hgrepos = []
issue_num = 46970
keywords = []
message_count = 2.0
messages = ['414822', '414823']
nosy_count = 2.0
nosy_names = ['eric.smith', 'crusaderky']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46970'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-123342
* gh-123568
* gh-123569

**Comment by sobolevn** [comment]
I think that we should add this case to the docs. Because there's really nothing we can do to support this case.

Solutions:

1. Don't do that
2. Don't use `slots=True`, write manual slots
3. Have defaults for `__init_subclass__`

I will send a PR with the proposed note about that.
