### ISSUE TITLE
Doc strings for built-in, in-place operators are misleading

### ISSUE THREAD

**Issue by 4b5d99f5-9955-4f9c-8c1d-77a17ab3e25a** [python/cpython#91134]
BPO | [46978](https://bugs.python.org/issue46978)
--- | :---
Nosy | @nickovs
PRs | <li>python/cpython#31802</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-10.19:36:25.115>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10', '3.11', '3.7']
title = 'Doc strings for built-in, in-place operators are misleading'
updated_at = <Date 2022-03-10.21:33:23.525>
user = 'https://github.com/nickovs'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-10.21:33:23.525>
actor = 'nickovs'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-10.19:36:25.115>
creator = 'nickovs'
dependencies = []
files = []
hgrepos = []
issue_num = 46978
keywords = ['patch']
message_count = 1.0
messages = ['414876']
nosy_count = 1.0
nosy_names = ['nickovs']
pr_nums = ['31802']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46978'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by merwok** [comment]
In-place methods **do** return values, otherwise the re-assignment of the variable would not be working.

```
>>> a = []
>>> a.__iadd__(['new'])
['new']
>>> a
['new']
>>>
```

**Comment by MojoVampire** [comment]
@merwok: Yes, but the docs don't say "Return self.__isub__(value).`, they say `Return self-=value.` (Notable exception: the `__iadd__` and `__imul__` that wrap the *sequence* versions of those operators, e.g. on `list`, say "Implement self+=value.", which is more correct). `.__isub__` has a return value, but `self-=other` is a statement, not an expression, it can't "return" anything.

**Comment by merwok** [comment]
I see your point!  I disagree with your last sentence:

> `self-= other` is a statement, not an expression, it can’t "return" anything

yes but the docstring is for the method (`__isub__`), which does something and returns something, so it is correct there.

**Comment by rhettinger** [comment]
I would leave this docstring as-is.  The method **DOES** return a value.

```
>>> x = [10]
>>> y = x.__iadd__([20])
>>> x
[10, 20]
>>> y
[10, 20]
```

The OP is confusing the action of the `+=` operator with the action of the `__iadd__` method.

**Comment by merwok** [comment]
The linked PR was merged before your comment.

**Comment by rhettinger** [comment]
Consider reverting it.  It is now less correct.

**Comment by iritkatriel** [comment]
While I'm not sure the change made the docstring less correct, because the function does calculate the value, I reverted the change and I am closing this issue on the basis that there is a limit how much core dev time should be spent discussing a single word in a docstring (which is not incorrect).
