### ISSUE TITLE
BytesWarning in zipimport paths on sys.path

### ISSUE THREAD

**Issue by f82f2f79-bfff-44c7-86e7-c93f7a9fd1fe** [python/cpython#91182]
BPO | [47026](https://bugs.python.org/issue47026)
--- | :---
Nosy | @brettcannon, @graingert, @akulakov
Dependencies | <li>bpo-47025: bytes do not work on sys.path</li>
Files | <li>[zipfile_demo.py](https://bugs.python.org/file50680/zipfile_demo.py "Uploaded as text/plain at 2022-03-15.13:29:09 by @graingert")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-15.13:29:09.171>
labels = ['library', '3.9', '3.10', '3.11']
title = 'BytesWarning in zipimport paths on sys.path'
updated_at = <Date 2022-03-21.23:00:44.042>
user = 'https://github.com/graingert'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-21.23:00:44.042>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-15.13:29:09.171>
creator = 'graingert'
dependencies = ['47025']
files = ['50680']
hgrepos = []
issue_num = 47026
keywords = []
message_count = 3.0
messages = ['415245', '415643', '415721']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'graingert', 'andrei.avk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47026'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The support of bytes paths was completely dropped in bpo-47025 (gh-91181).
