### ISSUE TITLE
Argparse can't parse subparsers with parse_known_args

### ISSUE THREAD

**Issue by 9bb68ee1-2756-40a9-bebe-0faf06ea4645** [python/cpython#91199]
BPO | [47043](https://bugs.python.org/issue47043)
--- | :---
Nosy | @lysnikolaou, @rive-n

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-17.13:49:54.593>
labels = ['interpreter-core', 'type-bug', '3.8']
title = "Argparse can't parse subparsers with parse_known_args"
updated_at = <Date 2022-03-22.08:42:30.118>
user = 'https://github.com/rive-n'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.08:42:30.118>
actor = 'rive-n'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Parser']
creation = <Date 2022-03-17.13:49:54.593>
creator = 'rive-n'
dependencies = []
files = []
hgrepos = []
issue_num = 47043
keywords = []
message_count = 4.0
messages = ['415412', '415414', '415490', '415751']
nosy_count = 2.0
nosy_names = ['lys.nikolaou', 'rive-n']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47043'
versions = ['Python 3.8']
```

</p></details>

**Comment by hpaulj** [comment]
You got caught up in the migration, so didn't get any responses.

The behavior that bothers you is normal and expected.  `add_subparsers` creates a positional argument, and explicitly allows only one of its kind.  Handling only one subcommand might not be universal, but it is typical  - `pip` and `jupyter` are two examples I use.

You've gotten around this by giving the `Action` itself the ability to find and call multiple parsers.  But the change is not reflected in the `help` or `usage`, which depends only on what the main parser "knows". 

You are welcome to develop and publish the change as a pypi package, but I don't think it should be considered as a change to the standard a`rgparse` module.

**Comment by hpaulj** [comment]
This should be changed from **type-bug** to **type-feature**

**Comment by serhiy-storchaka** [comment]
I agree with @hpaulj, this is an expected behavior. And we have no resources to add such feature. Not until we fix numerous existing bugs in argparse and implement less controversial features.
