### ISSUE TITLE
Deprecate modules listed in PEP 594

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#91217]
BPO | [47061](https://bugs.python.org/issue47061)
--- | :---
Nosy | @warsaw, @brettcannon, @hugovk, @miss-islington, @tirkarthi
PRs | <li>python/cpython#31984</li><li>python/cpython#32039</li><li>python/cpython#32082</li><li>python/cpython#32134</li><li>python/cpython#32350</li><li>python/cpython#32392</li><li>python/cpython#32410</li>
Dependencies | <li>bpo-47022: PEP 594: Document removal of asynchat, asyncore and smtpd</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brettcannon'
closed_at = None
created_at = <Date 2022-03-18.19:46:10.638>
labels = ['deferred-blocker', 'library', '3.11']
title = 'Deprecate modules listed in PEP 594'
updated_at = <Date 2022-04-08.03:39:21.812>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.03:39:21.812>
actor = 'brett.cannon'
assignee = 'brett.cannon'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-18.19:46:10.638>
creator = 'brett.cannon'
dependencies = ['47022']
files = []
hgrepos = []
issue_num = 47061
keywords = ['patch']
message_count = 8.0
messages = ['415521', '415525', '415725', '415732', '415733', '415906', '416804', '416896']
nosy_count = 5.0
nosy_names = ['barry', 'brett.cannon', 'hugovk', 'miss-islington', 'xtreak']
pr_nums = ['31984', '32039', '32082', '32134', '32350', '32392', '32410']
priority = 'deferred blocker'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47061'
versions = ['Python 3.11']
```

</p></details>

**Comment by brettcannon** [comment]
Should close https://github.com/python/cpython/issues/89337 once `nis` is deprecated.

**Comment by vstinner** [comment]
I created the PR https://github.com/python/cpython/pull/91951 to deprecate the mailcap module (see issue #68966).

**Comment by gnat** [comment]
Is deprecating CGI a logical thing to do here? Was there any real benefit to this? 

There's very likely going to be breakage from this in the Python ecosystem. Deprecating CGI is kind of like deprecating HTTP or JSON or CSV.. it's a very well established standard.

Just because "my current project at work" doesn't use something, doesn't mean it should go into the trashbin for everybody. Seems totally random.

**Comment by hugovk** [comment]
cgi has been moved to a separate package on PyPI that you can use instead:

* https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508/23?u=hugovk

* https://pypi.org/project/legacy-cgi/

**Comment by brettcannon** [comment]
> Is deprecating CGI a logical thing to do here? Was there any real benefit to this?

Yes, please read the PEP for the motivation.
