### ISSUE TITLE
Implement PEP 655 (Required/NotRequired)

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#91243]
BPO | [47087](https://bugs.python.org/issue47087)
--- | :---
Nosy | @gvanrossum, @davidfstr, @JelleZijlstra, @Fidget-Spinner, @AlexWaygood
PRs | <li>python/cpython#32419</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-21.21:18:31.184>
labels = ['type-feature', 'library', '3.11']
title = 'Implement PEP 655 (Required/NotRequired)'
updated_at = <Date 2022-04-08.16:10:23.222>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.16:10:23.222>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-21.21:18:31.184>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 47087
keywords = ['patch']
message_count = 1.0
messages = ['415704']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'David Foster', 'JelleZijlstra', 'kj', 'AlexWaygood']
pr_nums = ['32419']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47087'
versions = ['Python 3.11']
```

</p></details>

**Comment by JelleZijlstra** [comment]
I just merged #32419 to provide the runtime implementation. We still need documentation.

**Comment by davidfstr** [comment]
(I'm planning to pick up the documentation piece here within the next 2 weeks)

**Comment by davidfstr** [comment]
Runtime implementation and documentation for Required/NotRequired is complete. 🎉

I believe this issue can be closed.

**Comment by AlexWaygood** [comment]
@davidfstr congratulations!
