### ISSUE TITLE
Include HTML docs with Windows installer instead of CHM

### ISSUE THREAD

**Issue by zooba** [python/cpython#91242]
BPO | [47086](https://bugs.python.org/issue47086)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @ned-deily, @zware, @zooba, @JulienPalard
PRs | <li>python/cpython#32038</li><li>python/cpython#32075</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = None
created_at = <Date 2022-03-21.20:44:27.135>
labels = ['type-feature', 'OS-windows', '3.11']
title = 'Include HTML docs with Windows installer instead of CHM'
updated_at = <Date 2022-03-23.16:14:17.736>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.16:14:17.736>
actor = 'steve.dower'
assignee = 'steve.dower'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2022-03-21.20:44:27.135>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 47086
keywords = ['patch']
message_count = 14.0
messages = ['415701', '415735', '415736', '415819', '415822', '415824', '415825', '415827', '415828', '415829', '415830', '415848', '415866', '415884']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'ned.deily', 'zach.ware', 'steve.dower', 'mdk']
pr_nums = ['32038', '32075']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47086'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-141643

**Comment by kilitary** [comment]
CHM is totally removed? It is very good at search and fast navigating, rather than render all the documentation tree. 
It would be good if user can compile it for itself, because this format is very handy over browser.

**Comment by zooba** [comment]
People can still compile the CHM themselves - use `Doc\make.bat htmlhelp` - though we aren't accepting fixes specifically for it anymore (e.g. to fix crashes due to unsupported characters in the index).
