### ISSUE TITLE
Prefer libb2 over vendored copy of blake2

### ISSUE THREAD

**Issue by tiran** [python/cpython#91251]
BPO | [47095](https://bugs.python.org/issue47095)
--- | :---
Nosy | @gpshead, @tiran
PRs | <li>python/cpython#32059</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-26.20:05:29.265>
created_at = <Date 2022-03-22.19:51:17.380>
labels = ['extension-modules', 'type-bug', '3.11']
title = 'Prefer libb2 over vendored copy of blake2'
updated_at = <Date 2022-03-26.20:05:29.265>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-26.20:05:29.265>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-26.20:05:29.265>
closer = 'christian.heimes'
components = ['Extension Modules']
creation = <Date 2022-03-22.19:51:17.380>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 47095
keywords = ['patch']
message_count = 3.0
messages = ['415807', '415833', '416085']
nosy_count = 2.0
nosy_names = ['gregory.p.smith', 'christian.heimes']
pr_nums = ['32059']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47095'
versions = ['Python 3.11']
```

</p></details>

**Comment by zooba** [comment]
Is there a configure option to prefer the vendored copy? Or static linking? (This change has broken some of my semi-portable builds, because libb2 isn't installed by default but it gets pulled in by the build tools, so it's on the build machines.)

**Comment by tiran** [comment]
Untested: You should be able to statically link with libb2 using something like ``LIBB2_LIBS="-L/path/to/libdir -l:libb2.a -Wl,--exclude-libs,libb2.a``

**Comment by zooba** [comment]
Thanks! I used `LIBB2_LIBS="-L$(pkg-config libb2 --variable=libdir) -l:libb2.a -Wl,--exclude-libs,libb2.a"` and it's worked just fine (well, with one targeted test, going to be another hour or so before I can do a "real" test).
