### ISSUE TITLE
explore hashlib use of the Linux Kernel CryptoAPI

### ISSUE THREAD

**Issue by gpshead** [python/cpython#91258]
BPO | [47102](https://bugs.python.org/issue47102)
--- | :---
Nosy | @gpshead, @tiran
PRs | <li>python/cpython#32173</li><li>python/cpython#32176</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-23.19:30:13.093>
labels = ['type-feature']
title = 'explore hashlib use of the Linux Kernel CryptoAPI'
updated_at = <Date 2022-03-29.15:34:13.058>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-29.15:34:13.058>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-03-23.19:30:13.093>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 47102
keywords = ['patch']
message_count = 6.0
messages = ['415896', '415899', '415901', '415903', '415904', '416251']
nosy_count = 2.0
nosy_names = ['gregory.p.smith', 'christian.heimes']
pr_nums = ['32173', '32176']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47102'
versions = []
```

</p></details>

**Comment by gpshead** [comment]
Playing with your draft PR branch and testing things out... the performance of the Linux kernel crypto API for hash algorithms is several times slower on a modern AMD Zen, regardless of data size.

I realize it probably gets a tad better in limited situations where sendfile or splice can used, but it doesn't seem like a useful API on modern mainstream hardware. It could still make sense on low performance things that have non-userspace accelerator hardware. But this doesn't leave much motivation to implement code using it.

This one sounds like it could be a bit faster https://github.com/cryptodev-linux/cryptodev-linux (and is what would be needed for this on FreeBSD and OpenBSD), but is not in mainline in Linux.

**Comment by arhadthedev** [comment]
> Playing with your draft PR branch and testing things out... the performance of the Linux kernel crypto API for hash algorithms is several times slower on a modern AMD Zen, regardless of data size.

Probably, this should be added into the documentation if this issue gets rejected. Otherwise, there will be another attempts to introduce CryptoAPI, and one of them can even accidentally slip through.

**Comment by gpshead** [comment]
> Probably, this should be added into the documentation if this issue gets rejected. Otherwise, there will be another attempts to introduce CryptoAPI, and one of them can even accidentally slip through.

I'm not worried about that. This issue existing in our issue tracker is sufficient documentation.
