### ISSUE TITLE
Fix the table of methods in the collections.abc documentation

### ISSUE THREAD

**Issue by 53cd72ed-7768-4f34-9566-9995ab0e9dae** [python/cpython#91278]
BPO | [47122](https://bugs.python.org/issue47122)
--- | :---
Nosy | @rhettinger, @maggyero
PRs | <li>python/cpython#32090</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = None
created_at = <Date 2022-03-25.18:24:12.381>
labels = ['3.11', 'type-feature', '3.9', '3.10', 'docs']
title = 'Fix the table of methods in the collections.abc documentation'
updated_at = <Date 2022-03-25.19:11:06.207>
user = 'https://github.com/maggyero'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-25.19:11:06.207>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-03-25.18:24:12.381>
creator = 'maggyero'
dependencies = []
files = []
hgrepos = []
issue_num = 47122
keywords = []
message_count = 1.0
messages = ['416013']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'maggyero']
pr_nums = ['32090']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47122'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
There is no rationale or motivation given for this change. Suggesting to close it not planned.

**Comment by hugovk** [comment]
cc reporter @geryogam (who might not have been pinged after migration of BPO to GitHub)

**Comment by willingc** [comment]
I'm going to close this issue as not planned and its associated PR. I thank everyone for their effort. If people wish to move forward, please open a new issue/PR with specific desired changes. Thanks!

**Comment by willingc** [comment]
Closing
