### ISSUE TITLE
test_freeze_simple_script in test_tools fails

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#91275]
BPO | [47119](https://bugs.python.org/issue47119)
--- | :---
Nosy | @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-25.14:25:30.791>
labels = ['type-bug', 'tests', '3.11']
title = 'test_freeze_simple_script in test_tools fails'
updated_at = <Date 2022-03-25.14:25:30.791>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-25.14:25:30.791>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Demos and Tools', 'Tests']
creation = <Date 2022-03-25.14:25:30.791>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 47119
keywords = []
message_count = 1.0
messages = ['416001']
nosy_count = 1.0
nosy_names = ['serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47119'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Seems it was problems with my computer.

**Comment by Aditya102010** [comment]
Hi @serhiy-storchaka, I am facing the same issue at my end. Wanted to understand how did you resolve that. It was actually a FileNotFoundError right  ?

**Comment by serhiy-storchaka** [comment]
It was a hardware failure on my SSD. It soon turned into a brick. Fortunately, I managed to save most of the data.

So make a backup while you can.

**Comment by Aditya102010** [comment]
Just curious as I was facing this issue only. That issue looked like
something else. It was actually searching for a file  that was not present
in the system. And that file is generated while python is building some C
extension.
