### ISSUE TITLE
DatagramHandler doing DNS lookup on every log message

### ISSUE THREAD

**Issue by a1b08a40-034a-40a3-9764-5478a287bfe4** [python/cpython#91305]
BPO | [47149](https://bugs.python.org/issue47149)
--- | :---
Nosy | @ericvsmith, @bmerry

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-29.08:47:19.565>
labels = ['library', '3.10', 'performance']
title = 'DatagramHandler doing DNS lookup on every log message'
updated_at = <Date 2022-03-30.07:10:36.998>
user = 'https://github.com/bmerry'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-30.07:10:36.998>
actor = 'bmerry'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-03-29.08:47:19.565>
creator = 'bmerry'
dependencies = []
files = []
hgrepos = []
issue_num = 47149
keywords = []
message_count = 9.0
messages = ['416247', '416270', '416279', '416286', '416287', '416288', '416289', '416290', '416327']
nosy_count = 2.0
nosy_names = ['eric.smith', 'bmerry']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue47149'
versions = ['Python 3.10']
```

</p></details>

**Comment by vsajip** [comment]
> Maybe some documentation is achievable in the short term though, so that users who care more about latency than changing DNS are aware that they should do the lookup themselves?

This isn't specific to `DatagramHandler`, though, right? Isn't it something that users can figure out if they are having latency problems. It seems like every Python API that accepts a hostname can potentially hit this problem depending on the exact application using it.
