### ISSUE TITLE
Reorganize the re module sources

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#91308]
BPO | [47152](https://bugs.python.org/issue47152)
--- | :---
Nosy | @gvanrossum, @vstinner, @ezio-melotti, @serhiy-storchaka, @animalize, @asottile
PRs | <li>python/cpython#32177</li><li>python/cpython#32188</li><li>python/cpython#32290</li><li>python/cpython#32298</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-29.15:54:32.145>
labels = ['expert-regex', 'library', '3.11']
title = 'Reorganize the re module sources'
updated_at = <Date 2022-04-05.08:10:39.512>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.08:10:39.512>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Regular Expressions']
creation = <Date 2022-03-29.15:54:32.145>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 47152
keywords = ['patch']
message_count = 26.0
messages = ['416268', '416294', '416320', '416328', '416471', '416497', '416502', '416523', '416543', '416545', '416547', '416548', '416551', '416557', '416563', '416591', '416593', '416595', '416615', '416657', '416659', '416667', '416676', '416693', '416747', '416761']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'vstinner', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'malin', 'Anthony Sottile', 'dom1310df']
pr_nums = ['32177', '32188', '32290', '32298']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47152'
versions = ['Python 3.11']
```

</p></details>

**Comment by facelessuser** [comment]
I'd like to chime in that preserving `sre_parse.parse_template` would be nice. It is probably the only non-standard thing I've ever pulled in, but being able to get access to the group index and literals as it returns them is useful, at least for automating some more advanced template replacement stuff.

**Comment by serhiy-storchaka** [comment]
The original thread on Python-Dev: https://mail.python.org/archives/list/python-dev@python.org/thread/KRJ2EHKSXHCNTCZWG3HPGNKI272RRZ4S/.

**Comment by serhiy-storchaka** [comment]
It is more than 100 lines of code. It depends on other code and data defined in this file.

Look at #91525 (note that it changes the form of the result of `parse_template()`). After merging it I may add a public API for compiling replacement strings. It can be used to validate the replacement string. But I do not plan any introspection.

Adding a public API is still questionable, because I do not see significant performance benefit over using implicit caching.

**Comment by serhiy-storchaka** [comment]
All planned goals in this issue have been achieved.
