### ISSUE TITLE
Allow overriding future-task compliance check in  asyncio

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#91323]
BPO | [47167](https://bugs.python.org/issue47167)
--- | :---
Nosy | @asvetlov, @1st1
PRs | <li>python/cpython#32197</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-30.15:34:50.023>
labels = ['3.11', 'expert-asyncio']
title = 'Allow overriding future-task compliance check in  asyncio'
updated_at = <Date 2022-04-01.02:14:55.054>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-01.02:14:55.054>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2022-03-30.15:34:50.023>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 47167
keywords = ['patch']
message_count = 3.0
messages = ['416374', '416467', '416468']
nosy_count = 2.0
nosy_names = ['asvetlov', 'yselivanov']
pr_nums = ['32197']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47167'
versions = ['Python 3.11']
```

</p></details>

**Comment by graingert** [comment]
This patch isn't needed to support the aioloop-proxy use case, you can use an interceptor coroutine to pass the check instead:

https://github.com/aio-libs/aioloop-proxy/commit/a65565209f8ac5611ca7ffd2e987915c83b25433

this way aioloop proxy works with asyncio.Task CTask PyTask and *in addition* custom set_task_factory Tasks

**Comment by kumaraditya303** [comment]
Closing as the PR was reverted and it is not needed https://github.com/python/cpython/issues/91323#issuecomment-1194100664.
