### ISSUE TITLE
[C API] Test that the Python C API is compatible with C++

### ISSUE THREAD

**Issue by vstinner** [python/cpython#91321]
BPO | [47165](https://bugs.python.org/issue47165)
--- | :---
Nosy | @gpshead, @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-30.14:14:35.817>
labels = ['expert-C-API', 'type-feature', 'tests', '3.11']
title = '[C API] Test that the Python C API is compatible with C++'
updated_at = <Date 2022-04-05.06:49:28.827>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.06:49:28.827>
actor = 'gregory.p.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'C API']
creation = <Date 2022-03-30.14:14:35.817>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 47165
keywords = []
message_count = 2.0
messages = ['416359', '416756']
nosy_count = 2.0
nosy_names = ['gregory.p.smith', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47165'
versions = ['Python 3.11']
```

</p></details>

**Comment by vstinner** [comment]
@erlend-aasland: it seems like PEP 670 made this issue worse. It seems like C and C++ compilers emit more warnings when code comes from a static inline function, rather than from a macro.

cc @corona10

**Comment by erlend-aasland** [comment]
That depends on how the macro was written in the first place (argument casts?, "return" cast?), so yeah, for some macros you'll get more warnings if you convert them to static inlined functions because of the strict typing.

**Comment by vstinner** [comment]
An example of (fixed) C++ issue with the Python C API: https://github.com/python/cpython/issues/87347

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/32175 to check that the Python C API is compatible with C++.

**Comment by vstinner** [comment]
Discussion on python-dev: https://mail.python.org/archives/list/python-dev@python.org/thread/73UTO4MTKVJR7XWXTHLOV3V2L2QKP2TK/

**Comment by vstinner** [comment]
Feature implemented by https://github.com/python/cpython/pull/32175

**Comment by kumaraditya303** [comment]
C++ does not support designated initializers in array and is causing compilation errors in https://github.com/python/cpython/pull/92142. I reopen the issue.

**Comment by vstinner** [comment]
> C++ does not support designated initializers in array and is causing compilation errors in https://github.com/python/cpython/pull/92142. I reopen the issue.

Which code fails to build? What is the error message?

This issue is about testing that the current Python C API builds successfully in C++. It does: the test passed on all CIs.

Is the issue related to your PR? If yes, please open a new issue.

**Comment by kumaraditya303** [comment]
Okay I'll create a separate issue for it.

**Comment by vstinner** [comment]
I was still able to reproduce the C++ warning about NULL, so I pushed: commit 551d02b3e697098236bb3a6e0a855b2ad8dc0424 "gh-91321: Add _Py_NULL macro (#92253)".
