### ISSUE TITLE
_PyUnicode_Fini should invalidate ucnhash_capi capsule pointer

### ISSUE THREAD

**Issue by tiran** [python/cpython#91338]
BPO | [47182](https://bugs.python.org/issue47182)
--- | :---
Nosy | @vstinner, @tiran, @ambv, @pablogsal, @miss-islington, @neonene
PRs | <li>python/cpython#32212</li><li>python/cpython#32216</li><li>python/cpython#32217</li><li>python/cpython#32313</li>
Files | <li>[ucnbug.c](https://bugs.python.org/file50708/ucnbug.c "Uploaded as text/x-csrc at 2022-03-31.13:34:15 by @tiran")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-31.13:34:15.298>
labels = ['interpreter-core', '3.10', 'type-crash', '3.11']
title = '_PyUnicode_Fini should invalidate ucnhash_capi capsule pointer'
updated_at = <Date 2022-04-04.19:17:34.058>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-04.19:17:34.058>
actor = 'neonene'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-31.13:34:15.298>
creator = 'christian.heimes'
dependencies = []
files = ['50708']
hgrepos = []
issue_num = 47182
keywords = ['patch']
message_count = 3.0
messages = ['416432', '416440', '416474']
nosy_count = 6.0
nosy_names = ['vstinner', 'christian.heimes', 'lukasz.langa', 'pablogsal', 'miss-islington', 'neonene']
pr_nums = ['32212', '32216', '32217', '32313']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue47182'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/32212
