### ISSUE TITLE
Documentation for asserting values of `unittest.mock.Mock.call_args_list`

### ISSUE THREAD

**Issue by 93cd3954-55e8-4a15-8dba-fe813364f9e5** [python/cpython#91365]
BPO | [47209](https://bugs.python.org/issue47209)
--- | :---
Nosy | @himkt

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-04.03:24:22.676>
labels = ['3.11', 'type-bug', 'docs']
title = 'Documentation for asserting values of `unittest.mock.Mock.call_args_list`'
updated_at = <Date 2022-04-04.05:58:03.586>
user = 'https://github.com/himkt'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-04.05:58:03.586>
actor = 'himkt'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-04-04.03:24:22.676>
creator = 'himkt'
dependencies = []
files = []
hgrepos = []
issue_num = 47209
keywords = []
message_count = 3.0
messages = ['416650', '416652', '416653']
nosy_count = 2.0
nosy_names = ['docs@python', 'himkt']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47209'
versions = ['Python 3.11']
```

</p></details>

**Comment by tirkarthi** [comment]
Just to add call objects themselves are tuples. The docstring of `_Call` has similar examples

https://github.com/python/cpython/blob/2fadde7e6645e45e090b0187c28877300b07cba3/Lib/unittest/mock.py#L2418-L2436

**Comment by slateny** [comment]
@himkt Do you still think the docs need clarification or are fine as-is?

**Comment by himkt** [comment]
Sorry, I just noticed the thread is tracked here. Yeah I think the docs are fine as-is. Thank you for pinning.
