### ISSUE TITLE
show_caches option affects code positions reported by dis.get_instructions(...)

### ISSUE THREAD

**Issue by 974de63f-5f86-4aaf-9a56-25ffb8aa8d42** [python/cpython#91389]
BPO | [47233](https://bugs.python.org/issue47233)
--- | :---
Nosy | @brandtbucher, @15r10nk
PRs | <li>python/cpython#32406</li>
Files | <li>[test2.py](https://bugs.python.org/file50722/test2.py "Uploaded as text/plain at 2022-04-05.19:47:24 by @15r10nk")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-05.19:47:24.937>
labels = ['type-bug', '3.11']
title = 'show_caches option affects code positions reported by dis.get_instructions(...)'
updated_at = <Date 2022-04-07.20:52:49.864>
user = 'https://github.com/15r10nk'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-07.20:52:49.864>
actor = '15r10nk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-04-05.19:47:24.937>
creator = '15r10nk'
dependencies = []
files = ['50722']
hgrepos = []
issue_num = 47233
keywords = ['patch']
message_count = 3.0
messages = ['416810', '416828', '416944']
nosy_count = 2.0
nosy_names = ['brandtbucher', '15r10nk']
pr_nums = ['32406']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47233'
versions = ['Python 3.11']
```

</p></details>

**Comment by 15r10nk** [comment]
The problem was fixed with e590379.

**Comment by brandtbucher** [comment]
Was it? I haven't run it yet, but that patch doesn't look like it fixed the issue (there's still an early continue at the top of the loop).

**Comment by 15r10nk** [comment]
yes, I bisected it down to this commit.

**Comment by 15r10nk** [comment]
wait, maybe cache_counter gets never >0 in my tests ... the bug might be still there.

**Comment by 15r10nk** [comment]
I have verified that the cache_counter gets >0 in my tests.

I think the CACHE instructions have no corresponding positions in co_positions. It always continues the loop if the cache_conter is > 0.

I think the current implementation is has no bug.
