### ISSUE TITLE
potential undefined behavior with subprocess using vfork() on Linux?

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#91401]
BPO | [47245](https://bugs.python.org/issue47245)
--- | :---
Nosy | @gpshead, @socketpair, @izbyshev

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2022-04-08.13:33:50.215>
created_at = <Date 2022-04-06.20:24:52.654>
labels = ['extension-modules', 'type-bug', '3.10', '3.11']
title = 'potential undefined behavior with subprocess using vfork() on Linux?'
updated_at = <Date 2022-04-08.13:33:50.214>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.13:33:50.214>
actor = 'socketpair'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2022-04-08.13:33:50.215>
closer = 'socketpair'
components = ['Extension Modules']
creation = <Date 2022-04-06.20:24:52.654>
creator = 'socketpair'
dependencies = []
files = []
hgrepos = []
issue_num = 47245
keywords = ['3.10regression']
message_count = 13.0
messages = ['416897', '416898', '416899', '416900', '416904', '416905', '416909', '416917', '416946', '416964', '416974', '416976', '416984']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'socketpair', 'izbyshev']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47245'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
I'm reopening this to track adding a failsafe so people have a big-red-button style way to disable Python's use of vfork without recompiling just in case of future problems.  That arguably should've been there from the start in 3.10.  Though we still have no known need to use it, by the time you do it needs to already exist.

I'll do a manual more conservative backport of the disable_vfork_reason button to 3.10 for 3.10.5.

**Comment by vstinner** [comment]
I wish posix_spawn() could be used in more cases on Linux: see #86904.

**Comment by izbyshev** [comment]
> I wish posix_spawn() could be used in more cases on Linux: see #86904.

On the contrary, I wish posix_spawn() completely disabled on Linux. Using different backends depending on Popen() arguments only adds possibility for hard-to-understand behavioral differences. And posix_spawn() in glibc is *still* buggy (https://github.com/python/cpython/issues/91307#issuecomment-1114273061).

**Comment by MojoVampire** [comment]
@gpshead: It looks like you added the big-red-button; can this be closed?

**Comment by gpshead** [comment]
> On the contrary, I wish posix_spawn() completely disabled on Linux. Using different backends depending on Popen() arguments only adds possibility for hard-to-understand behavioral differences. And posix_spawn() in glibc is _still_ buggy ([#91307 (comment)](https://github.com/python/cpython/issues/91307#issuecomment-1114273061)).

Hah, joy, but not surprised, that at least proves that failsafes knobs to let modern things be disabled have uses.

The 3.10 PR being merged should close this issue out.

**Comment by vstinner** [comment]
> Sorry to dig up this old issue.

This issue is closed. I suggest you to open a new issue.
