### ISSUE TITLE
Clarify SortingHOWTO regarding locale aware string sorting

### ISSUE THREAD

**Issue by d3de1998-5581-4e9d-9d98-72eb1cbd3618** [python/cpython#91415]
BPO | [47259](https://bugs.python.org/issue47259)
--- | :---
Nosy | @rhettinger, @stevendaprano, @CendioOssman

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = None
created_at = <Date 2022-04-08.10:31:59.766>
labels = ['3.11', '3.10', 'docs']
title = 'Clarify SortingHOWTO regarding locale aware string sorting'
updated_at = <Date 2022-04-08.17:49:04.631>
user = 'https://github.com/CendioOssman'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.17:49:04.631>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-04-08.10:31:59.766>
creator = 'CendioOssman'
dependencies = []
files = []
hgrepos = []
issue_num = 47259
keywords = []
message_count = 2.0
messages = ['416972', '416997']
nosy_count = 3.0
nosy_names = ['rhettinger', 'steven.daprano', 'CendioOssman']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47259'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by andjc** [comment]
Actually sorting, and collation in general, can be quite a complex topic, I am slowly working through writing my own notes on it, and it can bend the mind at times.

You have various approaches to sorting, including:

- ISO/IEC 14651
- normalised ISO/IEC 14651
- language tailored ISO/IEC 14651
- normalised language tailored ISO/IEC 14651
- EOR (either ISO/IEC 14651 based implementation or CLDR based implementation)
- DUCET
- CLDR collation algorithm
- language tailored CLDR collation
- customisations to the CLDR collation algorithm or language tailored CLDR collations
