### ISSUE TITLE
enhanced dir?

### ISSUE THREAD

**Issue by cce42824-3b4b-42ba-b4ea-d813d8d3dc4d** [python/cpython#91410]
BPO | [47254](https://bugs.python.org/issue47254)
--- | :---
Nosy | @JelleZijlstra, @ravi140222
PRs | <li>python/cpython#32408</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-07.22:21:22.563>
labels = ['type-feature', '3.11']
title = 'enhanced dir?'
updated_at = <Date 2022-04-08.01:33:59.720>
user = 'https://github.com/ravi140222'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.01:33:59.720>
actor = 'apostofes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-04-07.22:21:22.563>
creator = 'apostofes'
dependencies = []
files = []
hgrepos = []
issue_num = 47254
keywords = ['patch']
message_count = 4.0
messages = ['416948', '416951', '416954', '416955']
nosy_count = 2.0
nosy_names = ['JelleZijlstra', 'apostofes']
pr_nums = ['32408']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47254'
versions = ['Python 3.11']
```

</p></details>

**Comment by ravi140222** [comment]
I would like this enhanced dir to have one more feature, that is the type of these functions, so, our enhanced dir would work something like this,
```
l = [1, 2, 3]
enhanced_dir(l, show_types=True) # one feature is categorize which I showed above, and show_types is the second feature
```
which gives,
```
{ <class 'method-wrapper': {'__add__', '__contains__', '__delattr__', ...}
{ <class 'builtin_function_or_method: {'__dir__', 'append', 'insert', ...}
```

**Comment by vainaijr** [comment]
i think so one more thing could be added to it, could name the keyword as `checks`,
for example,
```
enhanced_dir(None, checks=True)
```
this would run a few checks on our argument, such as, whether it,
1) is inheritable
2) could be used as a key in a dictionary
3) could be passed as an argument to defaultdict 
4) ...
so, for `None`, the output would be something like this,
```
{inheritable: False
dict_key: True
defaultdict_arg: True, ...}
```

**Comment by iritkatriel** [comment]
This is the kind of thing that people implement as a utility and publish on pypl. After a few years, if it's stable and has many users, it becomes possible to discuss adding it to the stdlib (which requires a PEP).  You don't start by adding it to the stdlib.

**Comment by vainaijr** [comment]
sorry, i am new to this, and dont know much about pypl (or is it pypi?), i created a pull request for this also, that is this, 

https://github.com/python/cpython/pull/91449

could you inform me where would be the suitable place for the function i created. is this the pypl url?
https://github.com/pypa/warehouse
will i have to create some package and then do something like `pip install enhanced_dir`, but i have only one function in it.

**Comment by iritkatriel** [comment]
The cpython bug tracker and review system are not the places for learner questions. They are the places where we actually work in cpython.

Try python-list for general python questions and core-mentorship for questions about contributing to python.
