### ISSUE TITLE
Out-of-date links to Python 3 docs from docs.python.org/2

### ISSUE THREAD

**Issue by Zac-HD** [python/cpython#91427]
It seems desirable for https://docs.python.org/2/ to link to the same version as https://docs.python.org/3/ - and more specifically, *undesirable* for the Python 2 docs to describe EOL Pythons (3.5 and 3.6) as still receiving security fixes, while the stable 3.9 and 3.10 series are described as pre-release and in development.

![image](https://user-images.githubusercontent.com/12229877/162641817-89417f74-d4a1-426b-a8c2-c95c9e9c1db2.png)

**Comment by zware** [comment]
I think this change will need to be made directly on docs.python.org at this point; the 2.7 branch no longer exists.

This is still a consideration for all old branches, though; for example, the 3.5 docs list 3.6 in security-fixes mode and 3.10 as in development.  Perhaps as part of going EOL, all links to other versions should be replaced by a single "Latest version of Python 3" link to `/3/`?

cc: @JulienPalard

**Comment by JulienPalard** [comment]
We may be able to rebuild old documentations periodically to fix the links, but;

- It may sometime break (we can pin many thing, like the theme version, sub-dependencies, and so on, but we'll not be able to pin underlying things easily, like python, the libc, ...).
- It'll take CPU time for ... not a very interesting thing.
- Just storing HTML and not touching it is stable and predictable.

So I don't want to go this way. The alternative is to manually remove those links, like I just did for 2.7:

=> https://docs.python.org/2.7/

and to make future EOL builds not generate this block (like in https://github.com/python/docsbuild-scripts/pull/125).

What do you think?

**Comment by Zac-HD** [comment]
I also prefer not-generating these links to keeping them updated; as you say it's risky in the long run. Two other considerations:

- the version-selection drop down could likewise be removed
- (IMO) we should remove links from active to EOL versions of the docs. It still makes sense to host docs for 2.7, but does 3.10 really need to link to 3.5 or 3.6?

**Comment by JulienPalard** [comment]
My gut feeling is: keep all the links as the files will be kept online as long as possible anyway.

We still host the doc of [Python 2.1](https://docs.python.org/2.1/), in one hand I'd be happy to see `2.1` in the version switcher.

But dropping them from the side-menu and language switcher have a benefit: readability. I don't want 50 nor 200 versions listed here, they have to be dropped.

Maybe data can help us decide, and it looks like 3.5 is still used, so its doc should still be easily readable:

=> https://github.com/JulienPalard/python-versions

**Comment by JulienPalard** [comment]
I merged https://github.com/python/docsbuild-scripts/pull/125 so the next EOL builds shoud no longer list those links, and removed old links on docs.python.org for 2.7, 3.5, 3.6.

If it's good for you, feel free to close the issue.
