### ISSUE TITLE
Docs for `re` inaccurately indicate support for non-capturing inline modifiers

### ISSUE THREAD

**Issue by ofek** [python/cpython#91431]
More info: https://stackoverflow.com/a/32860842/5854007

On https://docs.python.org/3.10/library/re.html the offending section starts with `(?aiLmsux-imsx:...)`

**Comment by serhiy-storchaka** [comment]
What is wrong in the current documentation and how do you suggest to improve it?

The StackOverflow answer you are referring to is outdated.

**Comment by ofek** [comment]
Ah, this does work on newer versions of Python. Thank you.
