### ISSUE TITLE
Some after-migration messages are semi-attributed to mannequins

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#91437]
### Bug occurence 1

There is a message (https://github.com/python/cpython/issues/91404#issuecomment-1094555211) from a non-core contributor with authorship inconsistence. It's properly attributed to a GitHub user but a big message avatar image is taken from a mannequin.

However, another after-migration message from the same user (https://github.com/python/cpython/issues/89702#issuecomment-1094563946) has no such an issue.

A screenshot of #91404:

![image](https://user-images.githubusercontent.com/4881073/162675931-47a6c20a-51e3-44d6-a826-3c43dfd6d76b.png)

---

### Bug occurence 2

A notification on referring from another issue/PR (https://github.com/python/cpython/issues/91230#ref-pullrequest-1199238778) is fully attributed to a mannequin:

![image](https://user-images.githubusercontent.com/4881073/162679373-6b2a5629-0b72-4c1e-9916-6c400fe06db8.png)

while the referrer isn't and can't because it's a PR:

![image](https://user-images.githubusercontent.com/4881073/162679660-0e7b9081-1bb9-488d-86c9-05a547f93561.png)

---

### Bug occurence 3

https://github.com/python/cpython/issues/89279#issuecomment-1094415941, the same as occurence 1.

![image](https://user-images.githubusercontent.com/4881073/162680223-f1cc0d53-63d7-4c14-a95d-3a85836b545f.png)

**Comment by AlexWaygood** [comment]
See also https://discuss.python.org/t/github-issues-migration-mannequin-users/14965

**Comment by ezio-melotti** [comment]
Thanks for the report.  I notified GitHub about the issue.

**Comment by hugovk** [comment]
When I opened this comment it showed the ghost mannequin icon, but as I was reading, it updated to the real profile image. So I guess it's a caching thing?

![image](https://user-images.githubusercontent.com/1324225/162945118-715109ee-485b-4381-bc51-a6ee7625e352.png)

**Comment by AlexWaygood** [comment]
> When I opened this comment it showed the ghost mannequin icon, but as I was reading, it updated to the real profile image. So I guess it's a caching thing?
> 
> ![image](https://user-images.githubusercontent.com/1324225/162945118-715109ee-485b-4381-bc51-a6ee7625e352.png)

It seems to vary depending on browser I'm on. I can reproduce what you're seeing on Opera on my mobile, but this is what I see on Safari on my iPad:

![54A28126-B233-4802-8263-9704174A018E](https://user-images.githubusercontent.com/66076021/162945776-a9692377-2ff4-45b6-9d67-48b7bdcb03a4.jpeg)

**Comment by arhadthedev** [comment]
> When I opened this comment it showed the ghost mannequin icon, but as I was reading, it updated to the real profile image. So I guess it's a caching thing?

DevTools shows no attempts of afterload network activity. Its console also reports nothing but `unrecognized feature: 'interest-cohort'` and lazy loading of my own userpic.

> It seems to vary depending on which browser I'm on

- desktop Edge 100.0.1185.36 I reported from shows the mannequin
- mobile Chrome 99.0.4844.88 for Android immediately shows a correct avatar

**Comment by arhadthedev** [comment]
@ezio-melotti Any news from the GitHub side? The issue continues to occasionally manifest itself.

**Comment by ezio-melotti** [comment]
I haven't heard from them.

**Comment by arhadthedev** [comment]
Is there an ability to contact the team once more? The pages mentioned in this issue continue to manifest the bug.

**Comment by ezio-melotti** [comment]
If the problem is in the issue metadata (i.e. the user/author/commenter is stored as a mannequin), it might be difficult (or impossible) to fix it.  The only thing that comes to mind is trying to reclaim the mannequin for that user and see if it triggers an update that solves the problem, but that can only be done for org members and it needs to be done manually.

Since this doesn't seem easy to fix and doesn't seem to create any major issue, I think we can just close it.

**Comment by arhadthedev** [comment]
> Since this doesn't seem easy to fix and doesn't seem to create any major issue, I think we can just close it.

In addition, this problem is transient and will stop to manifest itself after all migrated issues are closed.
