### ISSUE TITLE
Syntax for aliases to keys of python dictionaries

### ISSUE THREAD

**Issue by tomlin7** [python/cpython#91440]
## Description
There are cases where keys of python dictionaries may need aliases. When two keys point to the same value, duplication can also be avoided with this feature. 

### How it is done currently:
```py
foo = {
    key1: "value",
    key2: "value",
    ...
}
```
Here "value" is repeatedly used as value of the keys. When there are more keys with the same value, the more duplication occurs. 
See the following syntax:
## Conceptual syntax
```py
foo = {
    key1, key2, ...: "value"
}
```
Here, the duplication is less and the code looks cleaner. Do note that the punctuator `,` is just as per my concept. If it may hold conflicts with the item separators of dictionaries (which is also `,`), another punctuator can be used  instead. E.g: `|`, `;`, `+`

## Use cases
- This feature can be extremely useful for libraries which tends to be user friendly. 
- In big projects, when there is a confusion of key names ("was that `show` or `display`?"), this feature helps to avoid scrolling all the way up. 
- When key names are long, this feature helps to also accept acronyms or short names.

## Examples
```py
>>> foo = {
...     "person1", "p1": "yes",
...     "person2", "p2": "no",
... }
>>>
>>> a["person1"]
'yes'
>>> a["p1"]
'yes'
```

**Comment by AlexWaygood** [comment]
Hi, thanks for the feature request! I'm going to close this issue for now, as a change in syntax of this magnitude should first be discussed in the [Python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/) or at https://discuss.python.org/c/ideas/6

**Comment by billyeatcookies** [comment]
I have opened just opened a topic at discuss.python.org, thank you for responding! I will make sure to follow the instructions you mentioned for future issues 🤝

**Comment by AlexWaygood** [comment]
No worries 😊
