### ISSUE TITLE
@staticmethod called as regular function (= outside the class scope?)

### ISSUE THREAD

**Issue by Scharka** [python/cpython#91473]
553ee2781a37ac9d2068da3e1325a780ca79e21e

Do I understand correctly that (according to the docummentation) this should now work (in Python 3.10)?

```python
class C:
    @staticmethod
    def f():
        print("Hi!")

f()
```

(I see there has probably been some fundamental discussion about this (https://github.com/python/cpython/issues/87848). I'm asking as a beginner just to grasp the concept/syntax correctly.)

Thank you for the clarification!

**Comment by AlexWaygood** [comment]
Hi! This issue tracker is for bug reports and feature requests relating to Python. This is neither, so I'm going to close this issue — I recommend you ask your question here instead: https://discuss.python.org/c/users/7.

Good luck on your journey learning Python 🙂
