### ISSUE TITLE
Error 0x80070642: Failed to install MSI package.

### ISSUE THREAD

**Issue by ichbinrishab** [python/cpython#91475]
I'm getting this error constantly while installing python version 3.10.3 and 3.10.4 on my PC. 
Does someone know what exactly it is and what the solution for this problem could be?

**Comment by matrixise** [comment]
Hi @ichbinrishab,

Could you add more information about your issue, version of Windows, etc...

Thank you

**Comment by arhadthedev** [comment]
... language of Windows because there may be encoding shenanigans.

**Comment by ichbinrishab** [comment]
Hi you all, somehow I was able to solve the problem. Thankyou guys anyways.

**Comment by JianhengShang** [comment]
@ichbinrishab Could you kindly tell us how you fix the issue?
