### ISSUE TITLE
Improve decorators documentation

### ISSUE THREAD

**Issue by Booplicate** [python/cpython#91470]
I'd like to propose a bit more documentation about how `@property` works.

In my code example:
```py
import abc

class Base(abc.ABC):
    @classmethod
    @property
    @abc.abstractmethod
    def prop1(cls):
        return "abc prop 1"

    @classmethod
    @property
    @abc.abstractmethod
    def prop2(cls):
        return "abc prop 2"

class Test(Base):
    prop1 = "prop 1 override"

t = Test()
print(t.prop1, t.prop2)
>>> prop 1 override abc prop 2
```
Some linters detect the mistake, but Python will let this compile and run. I expect that to crash as `prop2` wasn't implemented.
The mistake is the order of `@property` and `@classmethod`
If I correct my base class:
```py
class Base(abc.ABC):
    @property
    @classmethod
    @abc.abstractmethod
    def prop1(cls):
        return "abc prop 1"

    @property
    @classmethod
    @abc.abstractmethod
    def prop2(cls):
        return "abc prop 2"
```
I get the expected `TypeError`.

In the docs I found
> Class methods can now wrap other [descriptors](https://docs.python.org/3/glossary.html#term-descriptor) such as [property()](https://docs.python.org/3/library/functions.html?highlight=property#property).

But I don't think it can, or at least not in the case of abc. Although, I found no discrepancy in the `abc` docs:
> When [abstractmethod()](https://docs.python.org/3/library/abc.html?highlight=abc#abc.abstractmethod) is applied in combination with other method descriptors, it should be applied as the innermost decorator

Which seems to be consistent with what I got.

It makes total sense we have to apply `@property` last! But maybe we could clarify that? Or maybe that `@classmethod` shouldn't wrap `@property`? Thanks.

**Comment by rhettinger** [comment]
In another issue, I'm looking at deprecating this kind of composition using classmethod.   It seems to have only caused confusion.

**Comment by Booplicate** [comment]
Oh, I actually found this very useful. Will there be another way to achieve the same?

**Comment by rhettinger** [comment]
> Will there be another way to achieve the same?

The ``__wrapped__`` attribute for classmethod lets you penetrate the classmethod wrapper.  But there isn't anything like the triply nested decorators in your original post.  

These tools don't compose as well as one would hope; they were not originally designed with that in mind.  Even the meaning of an abstractmethod/classmethod/property is ambiguous (if not to a computer, then to a reader).
