### ISSUE TITLE
os.getgroups is not consistent with macOS's getgroups

### ISSUE THREAD

**Issue by Kentzo** [python/cpython#91497]
With CPython (tested 3.8.9 and 3.10.1) on macOS 11.6.5 the [`os.getgroups`](https://docs.python.org/3/library/os.html#os.getgroups) function returns values that differ from `getgroups` when run under `sudo` (which uses `setgroups`):

```
$ id -G $(whoami)
20 701 12 61 79 80 81 98 399 101 702 703 33 100 204 250 395 398 400

$ id -G _unknown
99 12 61 702 701 703 100
```

With the bundled CPython:
```
$ /usr/bin/python3 -c "import sysconfig; print(sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET'))"
10.14

$ /usr/bin/python3 -c "import sys; print(sys.version)"     
3.8.9 (default, Oct 26 2021, 07:25:54) 
[Clang 13.0.0 (clang-1300.0.29.30)]

$ sudo --user=_unknown /usr/bin/python3 -c "import os; print(os.getgroups())"
[99, 12, 61, 702, 701, 703, 100]

$ sudo --preserve-groups --user=_unknown /usr/bin/python3 -c "import os; print(os.getgroups())"
[99, 12, 61, 702, 701, 703, 100]
```

With CPython from Homebrew:
```
$ /usr/local/bin/python3 -c "import sysconfig; print(sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET'))"
10.14

$ /usr/local/bin/python3 -c "import sys; print(sys.version)"     
3.10.1 (main, Jan 27 2022, 00:38:48) [Clang 11.0.0 (clang-1100.0.33.17)]

$ sudo --user=_unknown /usr/local/bin/python3 -c "import os; print(os.getgroups())"
[99, 12, 61, 702, 701, 703, 100] 

$ sudo --preserve-groups --user=_unknown /usr/local/bin/python3 -c "import os; print(os.getgroups())"
[99, 12, 61, 702, 701, 703, 100]
```

As you can see, python's process ignored invoking user's groups preserved with the `--preserve-groups` option.

While CPython [uses](https://github.com/python/cpython/blob/9d38120e335357a3b294277fd5eff0a10e46e043/Modules/posixmodule.c#L7599) the `getgroups` function to implement `os.getgroups` in a straightforward way, its behavior differs from when the very same function is used in a simpler program under `sudo`.

With plain C:

```
$ cat >groups.c <<EOT
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char const *argv[])
{
    int count = getgroups(0, NULL);
    gid_t *groups = calloc(count, sizeof(gid_t));
    getgroups(count, groups);

    for (int i = 0; i < count; ++i)
    {
        printf("%d ", groups[i]);
    }

    printf("\n");

    free(groups);
    return 0;
}
EOT
$ clang groups.c -o groups.out

$ sudo --user=_unknown ./groups.out
99 12 61 702 701 703 100

$ sudo --preserve-groups --user=_unknown ./groups.out
99 701 12 61 79 80 81 98 399 101 702 703 33 100 204 250
```

With Swift:

```
$ cat >groups.swift <<EOT
import Darwin

let count = Int(getgroups(0, nil))
var groups = [gid_t](repeating: 0, count: count)
getgroups(Int32(count), &groups)
print(groups.map({"\(\$0)"}).joined(separator: " "))
EOT

$ sudo --user=_unknown swift ./groups.swift
99 12 61 702 701 703 100

$ sudo --preserve-groups --user=_unknown swift ./groups.swift
99 701 12 61 79 80 81 98 399 101 702 703 33 100 204 250
```

As you can see, both examples provide different output in the presence of the `--preserve-groups` option. It seems like some initialization process in Python alters the behavior.

---

It's notable to say, that CPython's behavior matches `/usr/bin/groups` and `/usr/bin/id -G`:

```
$ sudo --user=_unknown id -G
99 12 61 702 701 703 100

$ sudo --preserve-groups --user=_unknown id -G
99 12 61 702 701 703 100
```

Which is expected, since `id` [uses `getgrouplist`](https://github.com/apple-oss-distributions/shell_cmds/blob/3675cf36782e8339492447b881daf7f82f419859/id/id.c#L406) and thus ignores whatever groups are set by `sudo`.

**Comment by Kentzo** [comment]
After re-reading the documentation and checking further into CPython's source code I now realize that this is a documented and expected behavior.

For macOS CPython is compiled with the `_DARWIN_C_SOURCE` macro defined which enforces the following behavior on `getgroups`:

     To provide compatibility with applications that use getgroups() in environments
     where users may be in more than {NGROUPS_MAX} groups, a variant of getgroups(),
     obtained when compiling with either the macros _DARWIN_UNLIMITED_GETGROUPS or
     _DARWIN_C_SOURCE defined, can be used that is not limited to {NGROUPS_MAX} groups.
     However, this variant only returns the user's default group access list and not
     the group list modified by a call to setgroups(2) (either in the current process
     or an ancestor process).  Use of setgroups(2) is highly discouraged, and there is
     no foolproof way to determine if it has been previously called.

However, `sudo` is so ubiquitous that I request the macOS note for `os.getgroups` to mention this specific use-case explicitly, i.e. that `os.getgetroups` ignores groups preserved via `sudo --preserve-groups`.

**Comment by Kentzo** [comment]
Related feature request for sudo: https://bugzilla.sudo.ws/show_bug.cgi?id=1028

**Comment by ronaldoussoren** [comment]
I've added aa 'docs' label because that's the best we can do here.  Apple has created a mess w.r.t. supplementary groups and our current behaviour looked like the most useful behaviour at the time. I still think it is as this allows code to get the groups of a regular logged in user.

The sudo use-case is an edge case that Apple has made almost impossible to support while still supporting more that NGROUPS_MAX groups. (Sigh...).

**Comment by ronaldoussoren** [comment]
Update: I'm closing this issue because we already document the weird behaviour of macOS: https://docs.python.org/3/library/os.html#os.getgroups

The system does not allow us to support both a large number of groups and seeing the result of setgroups, therefore there's nothing left to do.
