### ISSUE TITLE
Add typing to 3.11 What's New

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#91491]
I promised somewhere to write the typing section of the 3.11 What's New.

Here's what needs to be covered:
- PEP 646 (TypeVarTuple, Unpack)
- PEP 655 (Required/NotRequired)
- PEP 673 (Self)
- PEP 675 (LiteralString)
- (if accepted) PEP 681 (dataclass_transform)
- typing.reveal_type()
- typing.Never
- typing.assert_never()
- typing.assert_type()
- Improved introspection: @final, @overload 
- Runtime changes: #31628, #31841, #31836, #31151, #30900, #30304, #31042, #31126, #31156, #30983 and probably others

**Comment by AlexWaygood** [comment]
If #32335 is merged before the feature freeze, it will need a mention in the "new modules" section.

**Comment by hauntsaninja** [comment]
To clarify the state here, following #92060 , all the individual bullet points in ^^ have been covered, but we're missing coverage in What's New for the large clump of changes in the last bullet point.

**Comment by pablogsal** [comment]
⚠️ This issue has been updated from 'deferred-blocker' to 'release blocker' as we are past beta1. This issue will block the next release (`Python 3.11.0 beta 2`). ⚠️
