### ISSUE TITLE
`csv` module documentation looks funny for Python 3.10.4

### ISSUE THREAD

**Issue by dnicolodi** [python/cpython#91500]
Something must have gone wrong with the markup of the "See also" box in the `csv` module documentation on the Python 3.10.4 branch: all the following text is included in the note: https://docs.python.org/3.10/library/csv.html. The documentation looks fine for the other Python version I looked at.

Just noting this here till I find the time to send a patch. Happy to have someone else beat me to it.

**Comment by dnicolodi** [comment]
Thanks @AlexWaygood. I searched to check if the issue was already reported, but Github does not show closed issues by default...

**Comment by AlexWaygood** [comment]
#91483 isn't closed. But no worries, it wasn't a rebuke to you in anyway. Many thanks for the report! 🙂

**Comment by dnicolodi** [comment]
I know, I was just thanking you for being on top of things.

**Comment by AlexWaygood** [comment]
It should be fixed now for the English-language docs 👍 https://github.com/python/cpython/issues/91483#issuecomment-1097777373

**Comment by JulienPalard** [comment]
@dnicolodi it should be fixed now for every versions and every languages.
