### ISSUE TITLE
localtime fails when run from a cygwin terminal

### ISSUE THREAD

**Issue by in-tension** [python/cpython#91511]
So I'm not entirely sure whether this would be considered a bug. It's unclear to me whether running python using cygwin is supported. 

Anyway, when using a cygwin terminal (on windows), python fails to get the right localtime/timezone. It seems to revert to default UTC/GMT. I'm guessing that python thinks it's on linux. Then when it looks in the default locations for timezone data for linux, it fails because it's actually on windows.

The same python executable when run from a windows command prompt accurately determines the local timezone.

python version: 3.10.2

**Comment by ericvsmith** [comment]
Are you running the cygwin version of Python, or the Windows version from python.org? Please send the header you get when you run `python`, from both a cygwin terminal and from the Windows command prompt. For example:
```
Python 3.8.12 (default, Nov 23 2021, 20:18:25)
[GCC 11.2.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
```

In any event, try setting the TZ environment variable before running it.

**Comment by in-tension** [comment]
Oh, I'm definitely on a windows version. I had no Idea there was a cygwin version. I'll get that.

```
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by ericvsmith** [comment]
I don't know if cygwin has a 3.10 version yet, and if it does, what's involved in installing it: I was just trying to debug your issue. It's even more likely with the cygwin version that you'll need to set TZ. There's also functionality that's specific to each version. I install both, depending on what I'm trying to do.
