### ISSUE TITLE
ExceptionGroup should be generic

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#91549]
Thanks to PEP 654, 3.11 will have the new `except*` syntax. Let's take this sample:

```python
try:
    do_failing_things()
except* ValueError as eg:
    reveal_type(eg)
```

In the `except*` block, `eg` is an `ExceptionGroup` instance that in its `exceptions` attribute contains either `ValueError` instances or more nested `ExceptionGroup`s containing `ValueError`s. I expect that many `except*` blocks will do operations specific to the exception type they operate on, but right now there's no way to represent that information in the type system.

To fix this, we can make `ExceptionGroup` (and `BaseExceptionGroup`) generic. In the example, `eg` would be of type `ExceptionGroup[ValueError]` (to static type checkers), indicating that all the contained exceptions are `ValueError`s.

Recommendations:
- In CPython, add the C equivalent of `__class_getitem__ = GenericAlias` to `ExceptionGroup` and `BaseExceptionGroup`.
- In typeshed, make `ExceptionGroup` (and base) generic over a `TypeVar("ExceptionT", bound=Exception)`, and type its `exceptions` attribute as `tuple[ExceptionT | ExceptionGroup[ExceptionT], ...]`.
- In type checkers, for code of the form `except* T as eg:`, infer `eg` to be of type `ExceptionGroup[T]`. (Or `BaseExceptionGroup[T]` if `T` does not inherit from `Exception`.)

If we're in agreement, I can implement the first two recommendations.

Links:
- https://peps.python.org/pep-0654/#except (spec)
- https://github.com/python/typeshed/blob/7f9be7fd00ff86750a3d983681a9ef94b5511e2c/stdlib/builtins.pyi#L1752 (current typeshed stubs)

cc @iritkatriel @gvanrossum for PEP 654, @srittau @AlexWaygood for typeshed, @erictraut as a type checker maintainer.

**Comment by iritkatriel** [comment]
Is this related? 

https://github.com/python/cpython/blob/c9d41bcd68dbe339396523e931904930a87819b9/Lib/test/test_exception_group.py#L17

**Comment by iritkatriel** [comment]
Yeah I think it's there: https://github.com/iritkatriel/cpython/blob/8912054607c3cc83da8517b2ee56c5b250d8a16c/Objects/exceptions.c#L1043

**Comment by JelleZijlstra** [comment]
Great, you're well ahead of me :). I should have checked. Then we just need to make the corresponding typeshed change.
