### ISSUE TITLE
Remove "Undocumented modules" page

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#91547]
https://docs.python.org/3.11/library/undoc.html asks people to contribute docs for undocumented modules. But the only modules listed are `ntpath` and `posixpath`, and as the page itself acknowledges, there's little need to document those as end users should just use `os.path`.

I don't think the page is still useful; we should just remove it.

**Comment by slateny** [comment]
@AlexWaygood I think this looks good to close

**Comment by AlexWaygood** [comment]
> @AlexWaygood I think this looks good to close

@JelleZijlstra is right next to me at PyCon and he agrees :)
