### ISSUE TITLE
Remove Tools/pynche

### ISSUE THREAD

**Issue by warsaw** [python/cpython#91551]
@larryhastings reminded me of this ancient program.  It's way past time to remove this directory from `Tools/`.  I have no way to test it and zero interest in supporting it.  I don't even know the last time anybody mentioned it.  I don't even have enough interest to keep it alive in a separate repository.

Fun historical fact: I wrote the original version of this color editor for SunView.

**Comment by arhadthedev** [comment]
I see this tool as a neat way to find some pretty named color. Maybe it should be moved to `Tools/demo` as an example of how to use TKInter in a real (multifile) program? I can reorganize the tool's code to make it testable if it's viable.

<details><summary>Pynche screenshot</summary>

![image](https://user-images.githubusercontent.com/4881073/163524187-b0210902-9222-40e2-bed0-8a83543d305b.png)
</details>

A patch to make a program runnable:

```patch
diff --git a/Tools/pynche/PyncheWidget.py b/Tools/pynche/PyncheWidget.py
index ea456e577e..e73d48f16a 100644
--- a/Tools/pynche/PyncheWidget.py
+++ b/Tools/pynche/PyncheWidget.py
@@ -37,7 +37,7 @@ def __init__(self, version, switchboard, master=None, extrapath=[]):
             # Is there already a default root for Tk, say because we're
             # running under Guido's IDE? :-) Two conditions say no, either the
             # _default_root is None or it is unset.
-            tkroot = getattr(tkinter, '_default_root', None)
+            tkroot = getattr(sys.modules['tkinter'], '_default_root', None)
             if not tkroot:
                 tkroot = Tk(className='Pynche')
             self.__tkroot = tkroot
```

I runned it as follows:

```cmd
PCbuild\amd64\python Tools\pynche\Main.py -d Tools\pynche\X\rgb.txt
```

**Comment by arhadthedev** [comment]
JFY: I'm trying it out in https://github.com/python/cpython/compare/main...arhadthedev:dustoff-pynche?expand=1.

**Comment by JelleZijlstra** [comment]
@arhadthedev if you're interested in maintaining it, probably better to just start a new repo. That way there's one less thing to keep around in Python itself.

**Comment by warsaw** [comment]
> Maybe it should be moved to Tools/demo as an example of how to use TKInter in a real (multifile) program?

> if you're interested in maintaining it, probably better to just start a new repo.

I wouldn't be opposed to either option.  I can think of a couple of choices:

1. Move it to a separate repository in the `python` org
2. Create a new project outside the `python` org and set up some contributors
3. Delete it as planned above

If I was to do it, I'd prefer GitLab, but GitHub is just fine too.   Preferences?

**Comment by gpshead** [comment]
I see no reason to keep this buried within the CPython repo.. Delete it here. Let whoever wants to maintain it put it up in a new repo anywhere (and presumably on pypi - their choice).

LOL SunView!

**Comment by warsaw** [comment]
Okay, I will copy the files out into my own repo (likely on GitLab though), and will happily add any contributors who want to help out.  I'm going to mark this PR as draft until then, then will undraft it and merge.  Thanks!

**Comment by hugovk** [comment]
You may know it already but in case not, here are some magic git commands to copy files into a new repo, preserving history:



https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508/34?u=hugovk

**Comment by warsaw** [comment]
Contributions and collaborations welcome: https://gitlab.com/warsaw/pynche

**Comment by vstinner** [comment]
Screenshots in Python 3.10 with @arhadthedev patch.

Main window:

![color](https://user-images.githubusercontent.com/194129/163928106-5e8b57c2-5b14-44e3-9aab-c52daae30e67.png)

About  window:

![about](https://user-images.githubusercontent.com/194129/163927958-18ecd44b-fd00-423f-9814-964b90abdadb.png)

Before this tool has been removed, I didn't know it! It's interesting that it still works (with a oneliner patch)! I didn't know SunOS SunView neither!

Tool added to Python in 1998 (Python v1.5.1) with commit 516f18993f97c58f2bb41543bc878b3d7a1338fe:

```
commit 516f18993f97c58f2bb41543bc878b3d7a1338fe
Author: Barry Warsaw <barry@python.org>
Date:   Tue Jan 27 03:19:00 1998 +0000

    Initial revision

 Tools/pynche/Main.py | 23 +++++++++++++++++++++++
 1 file changed, 23 insertions(+)
```
