### ISSUE TITLE
Code still refers to bugs.python.org

### ISSUE THREAD

**Issue by GadgetSteve** [python/cpython#91565]
The code on main still references bugs.python.org as the location to report bugs rather than https://github.com/python/cpython/issues while the users will be redirected from bugs.python.org it would be preferable to reference the correct URL.

Using an re of "bugs\.python\.org/?[\)\s>]" to try to exclude results that are mentioning past bugs/issues this returns instances of:

```
.\Doc\README.rst:
  133 : `Python bug tracker <https://bugs.python.org>`_.
.\Doc\tools\extensions\pyspecific.py:
   57 : # Support for marking up and linking to bugs.python.org issues
.\Doc\whatsnew\2.6.rst:
  184 :   https://bugs.python.org

.\Doc\whatsnew\2.7.rst:
   73 : feature or the issue on https://bugs.python.org in which a change was
.\Lib\locale.py:
 1478 : # submit a bug report to the Python bug tracker at http://bugs.python.org/

.\Lib\platform.py:
   13 : #    Python bug tracker (http://bugs.python.org) and assign them to "lemburg".
.\Lib\test\crashers\README:
   11 : failure, as well as a bugs.python.org issue number if it exists.  Particularly
.\Lib\test\test_xml_etree.py:
 2182 :     # reported on bugs.python.org

.\Mac\README.rst:
  338 :    configure: WARNING:     ## Report this to https://bugs.python.org/ ##
.\Python\dtoa.c:
   75 :  * (http://bugs.python.org). */
.\configure:
    5 : # Report bugs to <https://bugs.python.org/>.
  270 : $0: https://bugs.python.org/ about your system, including
 1918 : Report bugs to <https://bugs.python.org/>.
 2141 : ## Report this to https://bugs.python.org/ ##
25522 : Report bugs to <https://bugs.python.org/>."
```
The Doc\whatsnew entries could safely be ignored in my opinion, the platform, readme and configure items only need simple substitutions but the .\Doc\tools\extensions\pyspecific.py will require more work as it maps between bpo and bugs.
I would suggest that any changes to the platform, readme and configure items could be considered for backporting to versions still in maintenance. 

### Linked PRs
* gh-91568
* gh-117450
* gh-117497
* gh-117890

**Comment by GadgetSteve** [comment]
The simple changes are done in the commit above 265a778 but changes to `Doc/tools/extensions/pyspecific.py` to reference GitHub result in problems as the BPO issue numbers do not map directly to the GitHub issue numbers. Separating that to an new issue #91567 as it will need some discussion on how to get it to work correctly. Creating a PR for the "simple" substitutions.

**Comment by encukou** [comment]
Hm, turns out there's one more.
```
$ git grep --perl 'bugs.python.org/(?!(issue|msg|review|file))'
Modules/selectmodule.c:823:                "Please, report at http://bugs.python.org/. "
```

**Comment by ezio-melotti** [comment]
This should now be fixed.
@encukou, do you want to backport #91568 to 3.12?

**Comment by encukou** [comment]
Yes; I just did so. Sorry for the delay!

**Comment by GadgetSteve** [comment]
Thanks all!
