### ISSUE TITLE
Cannot use multiprocessing-based python code as a function argument on windows ?

### ISSUE THREAD

**Issue by antoinecarme** [python/cpython#91573]
Dear all,

I am developing a data library that uses multiprocessing internally. 

https://github.com/antoinecarme/pyaf

The code based on this library works flawlessly on linux, but some users, including myself, cannot execute it on Windows (with different versions of python : 3.8, 3.9, 3.10). 

https://github.com/antoinecarme/pyaf/issues/156

This seems to be a general buggy pattern. A function that uses mutliprocessing cannot be called from another function. 

I reduced the code to get something that demonstrates this issue, the code below works on debian but not on windows (python 3.10, downloaded yesterday from python website and installed on windows 10)

```
from multiprocessing import Pool

def f(x):
    return x*x

def g(K, N):
    # Any external function that uses multiprocessing can be used here.
    with Pool(K) as p:
        x = p.map(f, [x for x in range(N)])
        return x
    
# mix of different multiprocessing tasks.
# expected output : [0, 1, 0, 1, 4]
print(g(3,2) + g(2, 3))
```

The expected output is copy-pasted from debian. this is a very blocking issue for Windows users.

**Comment by arhadthedev** [comment]
I confirm the bug (I've compiled the freshest 72965981d1128b3923dad5e850c8cff626ae4dc7 for it).

The output is repeated in an infinite loop and neither <kbd>Ctrl+C</kbd>, nor <kbd>Ctrl+Z</kbd>, nor `pcbuild\amd64\python test.py > out.txt` work so here's a screenshot:

![image](https://user-images.githubusercontent.com/4881073/163591529-3d6d6a45-96b3-4b14-9cd7-fca6b67af2f7.png)

**Comment by arhadthedev** [comment]
@antoinecarme That's not a bug. You need to wrap all out-of-function code with `if __name__ == '__main__'`:

```python
from multiprocessing import Pool

def f(x):
    return x*x

def g(K, N):
    # Any external function that uses multiprocessing can be used here.
    with Pool(K) as p:
        x = p.map(f, [x for x in range(N)])
        return x

if __name__ == '__main__':
   # mix of different multiprocessing tasks.
   # expected output : [0, 1, 0, 1, 4]
   print(g(3,2) + g(2, 3))
```

See, the children processes excute the whole script first to perform imports, declare functions and global variables, AND ONLY THEN jump into `f()`. As a result, `print(g(3,2) + g(2, 3))` executed recursively.

So the isue can be closed.

**Comment by antoinecarme** [comment]
Oleg,

Thanks for your help.

Not sure I understand well. This is a library and then, it does not have a main function. I really don't know how people will use it, and that's OK.

Do you mean that multiprocessing code lying inside an external code cannot not be used outside a main function ? It is a bit tough to tell people how they can use your code (developer freedom / political issue here ;)

Still trying to find a trick to fool python here ;)

**Comment by antoinecarme** [comment]
Oleg,

Can there be a  major/big difference of handling out-of-function code between unix and windows when in multiprocessing ?

Why is out-of-function code executed at all if that leads to an infinite loop? No error message, no warning.

**Comment by AshleyT3** [comment]
@antoinecarme MP on Unix utilizes fork by default, I believe...
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

<pre>
The parent process uses os.fork() to fork the Python interpreter.
The child process, when it begins, is effectively identical to the parent process. 
All resources of the parent are inherited by the child process. 
Note that safely forking a multithreaded process is problematic.
<b>Available on Unix only. The default on Unix.</b>
</pre>
...which may account for the differences you see. For a cross-platform script, putting the __main__ check in place fixes the module. 

Windows MP uses spawn for child processes and will certainly load that module fresh/anew, running/processing everything including running the so-called "main" code. 

Python does not pick-and-choose what to run when loading a module. It just runs whatever the developer has there. On Windows, you do not want that code to execute but once when the module is run as the main program, but not as a child process where it must nevertheless be loaded fresh (so will run that main code if you do not prevent with 'if'). 

The check Oleg recommends ensures the main code only runs in contexts where you want it to run, not elsewhere.

**Comment by MojoVampire** [comment]
Take a look at the programming recommendations for spawn and forkserver start methods: https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods The "Safe importing of main module" guideline is the one being violated here. If you're on Windows or macOS, you're not using fork as your start method, and several of these guidelines become effectively mandatory.

**Comment by antoinecarme** [comment]
@MojoVampire 

Thanks for pointing the The "Safe importing of main module" guideline in the doc.

It would be nice to have this guideline mandatory in some cases, to de defined. At least a warning is welcome.

The user does not always known that the module she is importing will run some multiprocessing stuff.

**Comment by arhadthedev** [comment]
> I am just wondering, if this is not a "user-friendliness bug"

@antoinecarme It actually is. I just didn't give at a second thought being like "when I started with Python many years ago, each and every tutorial pointed to this "feature"; so it's how it's supposed to be".

However, on second thought I see that this Windows-vs-Linux defference shouldn't surface on a high level of parallel data processing.

To get started with it, first I need to finish on-demand de-TLSfication of network sockets (for `asyncio.loop` and `asyncio.StreamWriter`), its recognition on another side, and clearify "never use the pre-wrapping socket" moment to not introduce new machinery.

**Comment by ronaldoussoren** [comment]
As @arhadthedev noted this is not a bug but expected behaviour, with documentation at <https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods>.

The "fork" spewing method used on Linux cannot be used on Windows because Windows does not have a "fork" system call.   Note that on macOS multiprocessing behaves the same as on Windows by default, because macOS does have.a "fork" system call but higher level system APIs are not compatible with the "fork" spawning method.
