### ISSUE TITLE
SyntaxError message pointing to comment line

### ISSUE THREAD

**Issue by snoopyjc** [python/cpython#91584]
Python 3.10.1:

I'm getting a SyntaxError pointing to a comment line and I can't figure out what the error is:

     python Pythonizer.py
      File "C:\pythonizer\bootstrap\Pythonizer.py", line 2769
        # issue 79 output_line('',q['''']);
                                       ^
    SyntaxError: unterminated string literal (detected at line 2769)
[Pythonizer.py.txt](https://github.com/python/cpython/files/8497889/Pythonizer.py.txt)

**Comment by zware** [comment]
Please direct usage questions to the [Users](https://discuss.python.org/c/users/7) section of discuss.python.org.

That comment line is within a triple-quoted string literal, which is terminated at the position before where the caret is pointing.  The fourth `'` is the start of the unterminated string literal.

**Comment by snoopyjc** [comment]
Thank you!!  Gotta figure out where that's coming from - this is generated code.

**Comment by snoopyjc** [comment]
Would be nice if the error message told me where the START of the string is

**Comment by zware** [comment]
It did; the syntax error is *after* the triple-quoted string; the start of the string it doesn't like is where it pointed.

Please direct any further followup to discuss.python.org.
