### ISSUE TITLE
Regression in the AC generated code

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#91583]
Argument Clinic now generates less efficient code using `_PyArg_ParseStackAndKeywords` instead of `_PyArg_UnpackKeywords`. It is a regression introduced after establishing module state. For example see #23393. It may be a cause of #91404.

@erlend-aasland

**Comment by erlend-aasland** [comment]
FYI GH-23393 is also in 3.10, not just 3.11.

**Comment by erlend-aasland** [comment]
Did you benchmark the difference?

**Comment by serhiy-storchaka** [comment]
No, but `_PyArg_ParseStackAndKeywords` adds some overhead, and I do not see reason of not using more efficient code here. It seems that adding the implicit `cls` parameter broke some checks in Argument Clinic. These checks should ignore that parameter (as they ignore `self`), it does not affect the parsing code.

**Comment by erlend-aasland** [comment]
> I do not see reason of not using more efficient code here

+1

> It seems that adding the implicit cls parameter broke some checks in Argument Clinic. These checks should ignore that parameter (as they ignore self), it does not affect the parsing code.

In sqlite3, for the sqlite3.Connection class, I store a pointer to the module state in the class context. A module state lookup in any of the connection methods is simply a class context member lookup. We could do a similar optimisation here.

**Comment by serhiy-storchaka** [comment]
`METH_METHOD` was introduced in 3.9, and Argument Clinic support was added at the same time.
