### ISSUE TITLE
Comparison of character and integer

### ISSUE THREAD

**Issue by sweetStreet** [python/cpython#91595]
**Bug report**
"ch == 0x7F" seems to be incorrect, use "ord(ch) == 0x7F" instead
https://github.com/python/cpython/blob/f2bc12f0d5297899b57f3fa688b24f3c1d1bee7b/Tools/gdb/libpython.py#L1421

**Your environment**
- CPython versions tested on: 3.7.10
- Operating system and architecture: Linux x86-64

**Comment by ezio-melotti** [comment]
I created GH-91597.

**Comment by ezio-melotti** [comment]
I see you already created GH-91596, I closed mine :)

**Comment by ezio-melotti** [comment]
This is now fixed in 3.11/3.10/3.9.  Thanks for the report and the PR!
