### ISSUE TITLE
I have written a simple code using the docs, but it is getting stuck after the last iteration. The code works perfectly if we use less iterations.

### ISSUE THREAD

**Issue by HarshGrandeur** [python/cpython#91594]
I have written a simple code using the docs, but it is getting stuck after the last iteration. The code works perfectly if we use less iterations.
```
from multiprocessing import Process, Queue
import os
import signal
def f(q):
    for i in range(10000):
        q.put([42, None, 'hello'])
        print("Iteration ", i , " " , os.getpid())
if __name__ == '__main__':
    q = Queue()
    p = Process(target=f, args=(q,))
    p.start()
    print(q.get())    # prints "[42, None, 'hello']"
    p.join(1)
```

_Originally posted by @HarshGrandeur in https://github.com/python/cpython/issues/73983#issuecomment-1100566883_

**Comment by hugovk** [comment]
Including @tim-one's reply from https://github.com/python/cpython/issues/73983#issuecomment-1100568712:


> @HarshGrandeur, read the docs more carefully. You can't be this careless with a Queue 😉. If you put something on it, some process needs to take it off, or the program may hang forever.
> 
> > Warning:
> > As mentioned above, if a child process has put items on a queue (and it has not used [JoinableQueue.cancel_join_thread], then that process will not terminate until all buffered items have been flushed to the pipe.
> > This means that if you try joining that process you may get a deadlock unless you are sure that all items which have been put on the queue have been consumed. Similarly, if the child process is non-daemonic then the parent process may hang on exit when it tries to join all its non-daemonic children.
> > Note that a queue created using a manager does not have this issue. See [Programming guidelines]

**Comment by HarshGrandeur** [comment]
Thankyou very much for your prompt response @tim-one and @hugovk . This particular part of the documentation skipped my eyes. Thanks for making the stuff clear to me, it all makes sense now and my code is running perfectly.
