### ISSUE TITLE
`__abstractmethods__` gives attribute error although described in `dir(type)`

### ISSUE THREAD

**Issue by vainaixr** [python/cpython#91591]
current scenario:
running `dir` on `type` gives this
```
['__abstractmethods__', '__base__', '__bases__', '__basicsize__', '__call__',
 '__class__', '__delattr__', '__dict__', '__dictoffset__', '__dir__', '__doc__',
 '__eq__', '__flags__', '__format__', '__ge__', '__getattribute__', '__gt__',
 '__hash__', '__init__', '__init_subclass__', '__instancecheck__',
 '__itemsize__', '__le__', '__lt__', '__module__', '__mro__', '__name__',
 '__ne__', '__new__', '__prepare__', '__qualname__', '__reduce__',
 '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__',
 '__subclasscheck__', '__subclasses__', '__subclasshook__',
 '__text_signature__', '__weakrefoffset__', 'mro']
```
but when we do,
```
type.__abstractmethods__
```
it gives,
```
AttributeError: __abstractmethods__
```
I ran `type` on every attribute of every builtin, (like, `type(zip.__init__)`, `type(type.__base__)`, `type(super.__thisclass__)`, ...)
and this was the only one that resulted in an error.

expected scenario:
1) either change the implementation of `__abstractmethods__` to return an empty frozen set,
2) or change `dir` to not return `__abstractmethods__` for `type`.

related issue,
https://stackoverflow.com/questions/24914584/abstractmethods-and-attributeerror

**Comment by ajoino** [comment]
Has this caused issues in real code?

**Comment by vainaijr** [comment]
I was using it to get the list of `getset_descriptors` and `member_descriptors`, to understand which methods are classified in each. something like this,

```
{'member_descriptor':
{
    {"<class 'complex'>": {'real', 'imag'}},
    {"<class 'range'>": {'start', 'step', 'stop'}},
    {"<class 'slice'>": {'start', 'step', 'stop'}},
    {"<class 'super'>": {'__self__', '__thisclass__', '__self_class__'}}
}
}
```
```
getset
{"<class 'bool'>": {'denominator', 'numerator', 'real', 'imag'}}
{"<class 'classmethod'>": {'__isabstractmethod__'}}
{"<class 'float'>": {'real', 'imag'}}
{"<class 'int'>": {'denominator', 'numerator', 'real', 'imag'}}
{"<class 'memoryview'>": {'c_contiguous', 'contiguous', 'f_contiguous', 'format', 'itemsize', 'nbytes', 'ndim', 'obj',
                          'readonly', 'shape', 'strides', 'suboffsets'}}
{"<class 'property'>": {'__isabstractmethod__'}}
{"<class 'staticmethod'>": {'__isabstractmethod__'}
```
I had to use the `type(arg.method)`, (again like, `type(zip.__init__), type(type.__base__), type(super.__thisclass__)` ...), that is where I got this error.

If one is inspecting through the builtins, then they could get this error.

**Comment by ajoino** [comment]
> If one is inspecting through the builtins, then they could get this error.

When would you need to do that in production code? I cannot see anybody calling `getattr(type, '__abstractmethods__')` beyond experimentation in the REPL, in which case it's just one of the many quirks of the cpython implementation.

**Comment by AlexWaygood** [comment]
@ajoino is correct.

I admire your curiosity, @vainaijr, and this is indeed an interesting quirk of Python. However, there only a small chance of this causing real-world problems, and an even smaller chance of this behaviour being changed any time soon. As such, I'm closing this issue.

In the future, if you find an interesting quirk or oddity in Python, please open a discussion at https://discuss.python.org/c/users/7 unless it is causing a problem in real-world code 🙂
