### ISSUE TITLE
use example.com for documentation

### ISSUE THREAD

**Issue by narusemotoki** [python/cpython#91611]
**Documentation**

Hello,
I found `mydomain.com` in the documentation. I would prefer to use example.com instead of that domain.

> The domain names example.com, example.net, example.org, and example.edu are [second-level domain](https://en.wikipedia.org/wiki/Second-level_domain) names in the [Domain Name System](https://en.wikipedia.org/wiki/Domain_Name_System) of the [Internet](https://en.wikipedia.org/wiki/Internet). They are reserved by the [Internet Assigned Numbers Authority](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority) (IANA) at the direction of the [Internet Engineering Task Force](https://en.wikipedia.org/wiki/Internet_Engineering_Task_Force) (IETF) as [special-use domain names](https://en.wikipedia.org/wiki/Special-use_domain_name) for documentation purposes. The domain names are used widely in books, tutorials, sample network configurations, and generally as examples for the use of domain names. The [Internet Corporation for Assigned Names and Numbers](https://en.wikipedia.org/wiki/Internet_Corporation_for_Assigned_Names_and_Numbers) (ICANN) operates web sites for these domains with content that reflects their purpose.

https://en.wikipedia.org/wiki/Example.com

example.net, org and edu are also good.

`mydomain.com` is here
- https://github.com/python/cpython/blob/0ddc63b240340a952692b11dfe0810973393ed11/Doc/library/ssl.rst
- https://github.com/python/cpython/blob/0ddc63b240340a952692b11dfe0810973393ed11/Doc/library/secrets.rst

I will send a Pull Request.

**Comment by rhettinger** [comment]
When you make the PR, request a review from me and I'll push it through.

**Comment by hauntsaninja** [comment]
Thanks, this appears to be fixed
