### ISSUE TITLE
argparse: _AttributeHolder repr() prints out positional arguments twice

### ISSUE THREAD

**Issue by achhina** [python/cpython#91622]
**Bug Report**
Overriding `_get_args()` to give positional arguments for classes subclassing `_AttributeHolder` get printed out twice. 

Example of a public API `Namespace` which inherits from `_AttributeHolder`:
```python
from argparse import Namespace


class Foo(Namespace):

    def __init__(self, bar, baz='baz'):
        self.bar = bar
        self.baz = baz

    def _get_args(self):
        return [self.bar]


print(Foo('bar'))

# Output
>>> Foo('bar', bar='bar', baz='baz')
```

**Proposal**
I was conflicted in calling this a bug, as when going through `argparse` this seemed more like unused code. Currently, `_get_args()` is unused throughout the codebase, also found no matches when searching through GitHub, and as it's private it should be safe to remove. However, to be safe, I propose to _deprecate_ `_get_args()` in 3.11 and remove it at a later point.

Here's a patch to the above proposal: [PR-91624](https://github.com/python/cpython/pull/91624)

**Comment by rhettinger** [comment]
ISTM that it is safer to leave the code as is.  We have no way of knowing if anyone is currently using it and there is no evidence that it has causing any problems.  Also, there's no downside to leaving it as is.

**Comment by achhina** [comment]
> ISTM that it is safer to leave the code as is.

Okay, fair enough.

> Also, there's no downside to leaving it as is.

Admittedly this won't be the hill I die on, but I do see value in deprecating this. 

According to anything I can find it is currently unused, it's a private method, and even when it is used it does not work as expected, but I still suggested deprecating it to be as safe as possible. When I was reading through the `_AttributeHolder` implementation I was confused about the purpose of this method until I realized it didn't currently serve any, so this seemed like a small but safe way to improve the legibility.
