### ISSUE TITLE
Improve Fish path setup on macOS

### ISSUE THREAD

**Issue by drewcassidy** [python/cpython#91629]
**Feature or enhancement**

Improve the path setup on macOS for users of the Fish shell

**Pitch**

Right now, the installer sets up python paths the same way as on every other shell: by appending a line to the end of the config file that adds directly to $PATH. Modifying the users config directly is not the best way to do this in fish, which has a conf.d directory to place configs into instead. In addition, fish has the `fish_add_path` function that doesn't allow duplicate entries in the PATH which can get out of hand when re-sourcing the config file multiple times.

I am working on a PR to address this right now, by writing a file for each python install to conf.d which adds the path using `fish_add_path`

### Linked PRs
* gh-91630

**Comment by ned-deily** [comment]
Thanks for the PR and your patience. Merged for 3.13.
