### ISSUE TITLE
Python 3.8.13 unconditionally enables -g with LTO even without debug features

### ISSUE THREAD

**Issue by mandree** [python/cpython#91620]
Python 3.8.13 unconditionally adds -g to CFLAGS and LDFLAGS if LTO is enabled, even if no debugging support is requested. This considerably raises memory requirements, and I am unable to *link* Python 3.8.13 with LTO on FreeBSD 13.0 amd64 on a computer with 1 GB RAM + 1 GB swap, where I used to be able to link it without `-flto -g`. (This computer uses clang 11 as system compiler, and ld.lld for the linker).

Manually removing the excess `-g` from CFLAGS and LDFLAGS (CONFIGURE_*FLAGS_NODIST) considerably reduces memory requirement of the linker to below 400 MB virtual, and the computer does not need to reach into swap, in spite of LTO.

I am hereby proposing that configure.ac should only add the `-g` along with `-flto` **if debug support is enabled.**

**Comment by erlend-aasland** [comment]
See also gh-74530

**Comment by erlend-aasland** [comment]
Based on a quick glance at the discussion in gh-74530, I don't expect the `-g` flag to be removed with LTO any time soon. Unless the problem in gh-74530 is no longer a problem, or it can be worked around in another way.

**Comment by erlend-aasland** [comment]
Closing due to the lack of response.
