### ISSUE TITLE
Memory leak with static iterator types

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#91632]
Python does not finalizes iterators of some types at exit leading to memory leak.

Reproducer:

```py
a = type(iter(tuple[int]))
print(a.mro())
```

Leak:
```console
[<class 'generic_alias_iterator'>, <class 'object'>]
[119 refs, 46 blocks]
```

See also https://github.com/python/cpython/issues/90575

**Comment by corona10** [comment]
cc @vstinner
