### ISSUE TITLE
Inconsistent behavior of asyncio.Transport.get_extra_info("peername") on TLS vs. non-TLS connections

### ISSUE THREAD

**Issue by aaugustin** [python/cpython#91635]
**Bug report**

After an `asyncio.Transport` is closed, `transport.get_extra_info("peername")` still returns the remote address if it's a non-TLS transport, while it doesn't return anything when it's a TLS transport. This inconsistency is surprising.

By TLS transport, I mean `<class 'asyncio.sslproto._SSLProtocolTransport'>` and by non-TLS transport, I mean `<class 'asyncio.selector_events._SelectorSocketTransport'>`. I observed this behavior on macOS.

_Setup_

```python
>>> import asyncio
>>> loop = asyncio.get_event_loop()
<stdin>:1: DeprecationWarning: There is no current event loop
```

_Test with TLS_

```python
>>> transport, protocol = loop.run_until_complete(loop.create_connection(asyncio.Protocol, "google.com", 443, ssl=True))
>>> transport
<asyncio.sslproto._SSLProtocolTransport object at 0x101c2c100>
>>> transport.get_extra_info("peername")
('142.250.74.238', 443)
>>> transport.close()
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> transport
<asyncio.sslproto._SSLProtocolTransport object at 0x101c2c100>
>>> transport.get_extra_info("peername")
>>>
```

Note that the second `transport.get_extra_info("peername")` doesn't return anything.

_Test without TLS_

```python
>>> transport, protocol = loop.run_until_complete(loop.create_connection(asyncio.Protocol, "google.com", 80))
>>> transport
<_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
>>> transport.get_extra_info("peername")
('142.250.74.238', 80)
>>> transport.close()
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> transport
<_SelectorSocketTransport closed fd=8>
>>> transport.get_extra_info("peername")
('142.250.74.238', 80)
>>>
```

Note that the second `transport.get_extra_info("peername")` still returns the address.

**Your environment**

```
Python 3.10.0 (default, Nov 20 2021, 14:34:51) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
```

**Comment by kumaraditya303** [comment]
Tested on 3.11:

TLS transport does not return `peername` after closing as it sets it's underlying transport to `None`:

https://github.com/python/cpython/blob/3289209716011b21128f45de69f4a8e9d376c78e/Lib/asyncio/sslproto.py#L484-L490

However non-TLS transport does not wrap another transport so it continues to return in this case  `peername`.

**Comment by kumaraditya303** [comment]
I am not sure what to do here. After closing the transport, I don't think you can expect to get connection information, otherwise  this has other unwanted consequences as the ssl context is destroyed so you cannot ssl ciphers etc. I would say you get all the info once connection is made and don't rely on this implementation detail.

**Comment by armw4** [comment]
#googleme

https://music.apple.com/us/album/just-us-feat-sza/1464024147?i=1464024175

#pending

Sure google

#oronnadiv but of course I am zeh part #israeli

That could be my cousin

I’m #multiracial

Because my parents were #jewish immigrants by way of #europe

Zeh #ellisisland is a global network

Don’t show up unannounced on #federalland

**Comment by gvanrossum** [comment]
Would like to hear from @aaugustin about the use case before we close this.

**Comment by aaugustin** [comment]
Hello, you can find the original use case in the aforementioned issue: https://github.com/aaugustin/websockets/issues/1136

So, if an application wants this info after the connection is closed, it has to be cached at one of the following three levels:

A. standard library (Python)
B. third-party library (websockets or any other asyncio-based library)
C. application

Currently, the answer is "A. for plain TCP connections, B. or C. for TCP + TLS connections". This behavior appears to be an implementation detail rather than an intentional behavior. So we're in Hyrum's law territory....

It could be better to raise an exception when `get_extra_info` is called on a closed transport. But it's hard to justify the backwards incompatibility at this point: users may depend on the fact that this currently works for plain TCP connections.

In the end, I don't care which choice we make: websockets will promise exactly what Python promises. It will be zero effort for me in all cases :-)

**Comment by kumaraditya303** [comment]
PR https://github.com/python/cpython/pull/98563 adds clarification that transports should not be used after they are closed. IMO a doc update is enough for this.

**Comment by gvanrossum** [comment]
Marking as not planned since we decided to keep the existing inconsistent behavior, and just document that you shouldn't do that.
