### ISSUE TITLE
possible solution for the import problem in python 3.10 (import Mapping from collections)

### ISSUE THREAD

**Issue by Omar-Nour** [python/cpython#91639]
Concerning python 3.10, the following error occurs for scripts trying to import `Mapping` from `collections`

### Error:
`
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py
`
### Proposed Solution:
add the following line to the `collections/__init__.py`
**Line :** `from collections.abc import Mapping`

### Reason:
Python scripts using the `collections` library from older versions would face problems when updating to **python 3.10**

**Comment by hugovk** [comment]
Thank you for the suggestion, however `Mapping` (and several other datatypes) was moved to `collections.abc` in Python 3.3 (released 2012-09-29).

https://docs.python.org/3.3/library/collections.abc.html#collections-abstract-base-classes

As a convenience, it was also in `collections` until Python 3.9 (raising a deprecation warning) and was finally removed in Python 3.10 (released 2021-10-04), nine years later.

So for Python 3.3 and up, you can use:

```python
from collections.abc import Mapping
```

If you need to support Python _older than 3.3_ as well, then please use:

```python
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
```

**Comment by thewriteway** [comment]
Can this be reopened for triage as its still happening even with the new syntax `collections.abc import Mapping` being used.

The error only stopped occurring after the following code was added to `3.10/lib/python3.10/collections/__init__.py`

```
from collections.abc import Mapping
from collections.abc import MutableMapping
from collections.abc import Sequence
```

**Comment by hugovk** [comment]
@thewriteway What code do you run, and what error happens, with which Python versions?

**Comment by thewriteway** [comment]
Environment:
Python 3.10.6
Windows 10

I ran the following project locally and updated any references I could find to the new naming scheme (collections.abc): 

https://github.com/l3uddz/plex_dupefinder

This is the error that occurs:
plex_dupefinder-master>python plex_dupefinder.py
Traceback (most recent call last):
  File "plex_dupefinder-master\plex_dupefinder.py", line 12, in <module>
    from config import cfg
  File "plex_dupefinder-master\config.py", line 8, in <module>
    from attrdict import AttrDict
  File "C:\Program Files\Python310\lib\site-packages\attrdict\__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "C:\Program Files\Python310\lib\site-packages\attrdict\mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)

**Comment by hugovk** [comment]
Thank you, so the problem isn't in Python itself.

The problem is plex_dupefinder uses another library called AttrDict, and AttrDict is incompatible with Python 3.10.

However, AttrDict is no longer maintained and the repo has been archived:

https://github.com/bcj/AttrDict

Therefore plex_dupefinder should replace AttrDict with something else or "vendor" and fix the code. Please report this to them:

https://github.com/l3uddz/plex_dupefinder/issues
