### ISSUE TITLE
Missing import in example at dataclasses.rst 

### ISSUE THREAD

**Issue by xandrade** [python/cpython#91673]
**Documentation**

Found that the typing ```List``` is used in example, but import is missed at ```dataclasses.rst``` file.

In this example:

```
  @dataclass
  class D:
      x: List = []
      def add(self, element):
          self.x += element
```
the import ```from typing import List``` is missing

**Comment by ericvsmith** [comment]
I'm not sure how important this is. The example already says the code isn't valid. Maybe just use "list" instead of "List".

**Comment by xandrade** [comment]
Sure @ericvsmith, but the example in the documentation doesn't run.
Your suggestion for using list instead of list works, as long it is defined as ```x: list = field(default_factory=list)```.
However, I think the example is about forcing the datatype in the list using List from typing.

This works (as example only):

```
from dataclasses import dataclass
from typing import List

@dataclass
class User:
    x: list = field(default_factory=list)
    y: List[int] = field(default_factory=list)
```

this doesn't work

```
from dataclasses import dataclass

@dataclass
class User:
    x: list = []
```
