### ISSUE TITLE
Proposal to add a string.simplified() method

### ISSUE THREAD

**Issue by vkbo** [python/cpython#91688]
**Feature or enhancement**

I propose to add a method to the string class to return a "simplified" string. It is the same feature that QString provides in the [Qt library](https://doc.qt.io/qt-5/qstring.html#simplified). It is one I use frequently in C++, and miss in Python. Essentially, the method returns a string that has leading and trailing whitespaces stripped, and all internal (consecutive) whitespaces replaced with a single ASCII whitespace.

The implementation is trivial, and depends on the already existing definition of a whitespace in Python. See my own code [here](https://github.com/vkbo/novelWriter/blob/e938ea89678360974d4adfb269f43299c86531a1/novelwriter/common.py#L254).

**Pitch**

The primary use case is for sanitising user-provided input. I use this a lot to clean up labels that end up on a GUI. Another frequent use case in my experience is to prepare simple strings for output to XML and HTML where the preservation of multiple and mixed whitespaces are not guaranteed to be treated consistently between parsers.

**Previous discussion**

I could not find any previous discussions on this.

**Comment by ajoino** [comment]
This kind of feature request is typically discussed in the python-ideas mailing list or on discuss.python.org, and changes to the API of builtins have previously required PEPs to motivate the changes. For example, [PEP 616](https://peps.python.org/pep-0616/) was written to motivate the addition of remove prefix/suffix methods to `str`.

Regarding the feature request, it seems like a very niche feature to me, and considering it's a fairly simple one-liner it probably shouldn't be included in `str`.

**Comment by vkbo** [comment]
Yes, I was wondering if it perhaps was a little simple. I had the suffix/prefix addition in mind, which are also very simple, so I thought it might be worth it still. It's a clunky enough oneliner that I at least prefer to wrap it in a function for my own use.

Should I close it and take it to the mailing list instead?

**Comment by AlexWaygood** [comment]
> Should I close it and take it to the mailing list instead?

Yes, a change to a builtin class is a very significant change, so please take this idea to the [Python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/?utm_source=rss&utm_medium=rss) or the [Ideas section of Discourse](https://discuss.python.org/c/ideas/6) first. If the reaction there is positive, please feel free to open a new issue, and you can post the link to the previous discussion in the "Previous discussion" section in the issue template.

Thanks! 🙂
