### ISSUE TITLE
Build Python with C11

### ISSUE THREAD

**Issue by vstinner** [python/cpython#91731]
PEP 7 was recently updated to require a C11 compiler (without optional features) to build Python. I propose to now implement this new requirement:

* Build Python with -std=c11 rather than -std=c99
* Use static_assert() of <assert.h>

It's already documented in What's New in Python 3.11:

> Building Python now requires a C11 compiler without optional C11 features. (Contributed by Victor Stinner in bpo-46656.

https://docs.python.org/dev/whatsnew/3.11.html#build-changes

* PR: gh-94766

**Comment by corona10** [comment]
+1

**Comment by vstinner** [comment]
I merged 2 PRs:

* https://github.com/python/cpython/pull/91733
* https://github.com/python/cpython/pull/91730

I close the issue.

**Comment by gvanrossum** [comment]
What about Windows? @zooba are we already building with C11 there?

**Comment by zooba** [comment]
> What about Windows? @zooba are we already building with C11 there?

Apparently, or CI would have broken. I guess we'll find out when people start using new language features.

**Comment by vstinner** [comment]
> What about Windows? @zooba are we already building with C11 there?

When the PEP 7 change was discussed on python-dev, it was said that MSVC supports C11 without optional features.

* https://mail.python.org/archives/list/python-dev@python.org/thread/J5FSP6J4EITPY5C2UJI7HSL2GQCTCUWN/
* https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/ <= mentions ``_Static_assert`` and has an example using ``static_assert()`` of ``<assert.h>``

My PR got merged and the CI is fine. Do you have remaining concerns about MSVC?

The blog post mentions the ``/std:c11`` option: https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170 It doesn't seem to be used by Python currently.

I only these /std options:

```
PCbuild/python_uwp.vcxproj:93:      <AdditionalOptions>/EHsc /std:c++17 %(AdditionalOptions)</AdditionalOptions>
PCbuild/pythonw_uwp.vcxproj:93:      <AdditionalOptions>/EHsc /std:c++17 %(AdditionalOptions)</AdditionalOptions>
```

The blog post also mentions the ``/Zc:preprocessor`` option to switch the preprocessor to C11 mode ("conformant preprocessor"): https://docs.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170 This option doesn't seem to be currently used by Python.

**Comment by gvanrossum** [comment]
My remaining concern is that I tried to use static_assert() in #32387 and it broke on Windows. I've merged the latest main and it still breaks. I'll just assume that that is a different problem so I'll move on. (If you want to look into it, details are in that issue.)

**Comment by zooba** [comment]
> The blog post mentions the `/std:c11` option: https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170 It doesn't seem to be used by Python currently.

Yeah, this probably needs to be added (in pyproject.props). I don't _think_ it will matter if it's included twice in the C++ projects, but that would be the biggest issue.

**Comment by gvanrossum** [comment]
I reopen the issue.

**Comment by sweeneyde** [comment]
It looks like [AMD64 FreeBSD Non-Debug 3.x](https://buildbot.python.org/all/#/builders/172) is now failing like this:

```
-- Objects/longobject.o ---
cc -pthread -c  -DNDEBUG -g -fwrapv -O3 -Wall -UNDEBUG -O2 -pipe  -std=c11 -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE -o Objects/longobject.o Objects/longobject.c
Objects/longobject.c:776:5: error: implicit declaration of function 'static_assert' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    static_assert(PyLong_SHIFT <= sizeof(unsigned long) * 8,
    ^
```

**Comment by arhadthedev** [comment]
@sweeneyde

> 'static_assert' is invalid in C99

Is `config` regenerated in a commit pulled by the buildbot?

**Comment by vstinner** [comment]
> It looks like [AMD64 FreeBSD Non-Debug 3.x](https://buildbot.python.org/all/#/builders/172) is now failing like this:

Right, I just noticed that: I created https://github.com/python/cpython/issues/91782 to track this issue.

Sadly, this specific FreeBSD buildbot worker failed on the Git step but the CI job was marked as successful on my PR :-(

**Comment by kumaraditya303** [comment]
`_Py_NO_RETURN` macro can also be changed to use `noreturn` from `stdnoreturn.h`. 
See https://www.gnu.org/software/gnulib/manual/html_node/stdnoreturn_002eh.html

**Comment by vstinner** [comment]
> _Py_NO_RETURN macro can also be changed to use noreturn from stdnoreturn.h.

If you consider that it's worth it, please open a separated issue.

I already got enough issues with static_assert(), so I prefer to restrict this issue to that :-)

**Comment by pablogsal** [comment]
I'm marking this as release blocker as there may be multiple systems affected

**Comment by pablogsal** [comment]
Seems that the C11 symbol is `_Static_assert` not `static_assert`. The later is a C++ symbol:

https://gcc.gnu.org/wiki/C11Status

`static_assert` requires glibc `2.16` or newer.

**Comment by pablogsal** [comment]
Seems that `muslc` has the macro as well https://github.com/seL4/musllibc/blob/c7aa943a2ad4fccaccf52a1f957bf8860f57f5b0/include/assert.h

**Comment by mdickinson** [comment]
> Seems that the C11 symbol is `_Static_assert` not `static_assert`.

`static_assert` should be valid in standard C11, too. It's a macro in `assert.h`. See C11 §7.2p3, which says:

> The macro static_assert expands to _Static_assert.

**Comment by pablogsal** [comment]
> `static_assert` should be valid in standard C11, too. It's a macro in `assert.h`. See C11 §7.2p3, which says:
> 
> >

That's only on glibc 2.16 or newer. GCC itself only provides _Static_assert

**Comment by mdickinson** [comment]
Agreed that the C11 requirement apparently mandates glibc >= 2.16. But `static_assert` _is_ a C11 feature, not just a C++ feature.

**Comment by vstinner** [comment]
> static_assert should be valid in standard C11, too. It's a macro in assert.h. See C11 §7.2p3, which says:

There is the theory, and the practice. Did you see the FreeBSD issue about the practice? :-) https://github.com/python/cpython/issues/91782

**Comment by jmroot** [comment]
macOS 10.10 and older also don't have static_assert defined even when using a C11 compiler.

**Comment by vstinner** [comment]
> macOS 10.10 and older also don't have static_assert defined even when using a C11 compiler.

What is your C compiler? What is your error message?

Can you try to add this code at the top of pymacro.h? Does it fix your build issue?

```
#ifndef static_assert
#  define static_assert _Static_assert
#endif
```

**Comment by pablogsal** [comment]
We have another problem. In C++11 `static_assert` is a keyword and defining the macro is undefined behaviour. This can lead to errors:

```
         /opt/python/cp311-cp311/include/python3.11/pymacro.h:18:25: error: ‘int std::vector<_Tp, _Alloc>::_Static_assert(int, int)’ cannot be overloaded with ‘int std::vector<_Tp, _Alloc>::_Static_assert(int, int)’
          #  define static_assert _Static_assert
                                  ^~~~~~~~~~~~~~
         /opt/python/cp311-cp311/include/python3.11/pymacro.h:18:25: note: previous declaration ‘int std::vector<_Tp, _Alloc>::_Static_assert(int, int)’
          #  define static_assert _Static_assert
                                  ^~~~~~~~~~~~~~
         In file included from src/memray/_memray/records.h:3,
                          from src/memray/_memray.cpp:790:

```

According to https://eel.is/c++draft/diff.header.assert.h#:static_assert

>  the token static_assert is a keyword in C++. It does not appear as a macro name defined in <cassert>.

So we cannot even really rely on anything defined on the cassert header

**Comment by pablogsal** [comment]
I will submit a PR to add yet another macro guard.

**Comment by pablogsal** [comment]
Also, from https://eel.is/c++draft/macro.names:


> A translation unit shall not #define or #undef names lexically identical to keywords, to the identifiers listed in Table 4, or to the attribute-tokens described in [dcl.attr], except that the names likely and unlikely may be defined as function-like macros ([cpp.replace]).

**Comment by vstinner** [comment]
@pablogsal's PR for C++: https://github.com/python/cpython/pull/93700

**Comment by vstinner** [comment]
An alternative would be to use _Static_assert() rather than static_assert(). If possible, I would prefer to use "standard" (?!) static_assert().

**Comment by gvanrossum** [comment]
Why is this a release blocker? Should it be fixed in 3.12 or also for 3.11?

**Comment by pablogsal** [comment]
Is not a release blocker anymore (it was when it caused c++ compilers to fail) but I removed the label one week ago.

**Comment by gvanrossum** [comment]
Hm it’s still in Ezio’s project: https://github.com/orgs/python/projects/2/views/2

**Comment by pablogsal** [comment]
> Hm it’s still in Ezio’s project: https://github.com/orgs/python/projects/2/views/2

Ah, that's because according to Ezio that will require manual update, which is unfortunate :(

**Comment by vstinner** [comment]
On Linux, all C++ compiler errors have been fixed and now have tests (test_cppext: C++03 and C++11).

On Windows, test_cppext is skipped and Python doesn't pass /std:c11 compiler flag. I would suggest opening a separated issue to enhance C11 and C++ support on Windows.

```
    # With MSVC, the linker fails with: cannot open file 'python311.lib'
    # https://github.com/python/cpython/pull/32175#issuecomment-1111175897
    @unittest.skipIf(MS_WINDOWS, 'test fails on Windows')
```

Well, C11 features *are* used in Python on Windows as well. So I consider that the initial issue is now fixed. /std:c11 doesn't seem to be *required* at this point.

Can I close this issue?

**Comment by vstinner** [comment]
Python 3.11 was released and it now requires a C11 compiler. I close the issue. If you want to enhance Python build, please open a new separated issue ;-)
