### ISSUE TITLE
Uninstalling 3.10.0 on Windows 10 gets "Type mismatch" error

### ISSUE THREAD

**Issue by rahbert1** [python/cpython#91745]
**Bug report**

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

**Your environment**

- CPython versions tested on:
- Operating system and architecture:

**Comment by rahbert1** [comment]
Error thrown at line 5173 of ScriptLib.vbs, appears that the intReturnCode is a string of length 0 instead of numeric..

**Comment by kumaraditya303** [comment]
No reproducer and no description so closing. Create a new issue with more information if this is still an issue.
