### ISSUE TITLE
C API docs: Py_IncRef and Py_DecRef are not documented as functions

### ISSUE THREAD

**Issue by encukou** [python/cpython#91755]
**Documentation**

`Py_IncRef` and `Py_DecRef` are mentioned in prose at the end of [Reference Counting docs](https://docs.python.org/3.10/c-api/refcounting.html). They should be documented as C functions so they show up in the index and can be linked.

**Comment by erlend-aasland** [comment]
Fixed by:

- gh-91805
- gh-92916
- gh-92917
