### ISSUE TITLE
ElementTree.tostring() changes text by not escaping carriage return during serialization

### ISSUE THREAD

**Issue by mforner** [python/cpython#91767]
The function <code>ET.tostring()</code> does not escape carriage return (<code>\r</code>) when serializing a XML tree. This eventually causes the <code>\r</code> to disappear when re-parsing the output of <code>ET.tostring()</code>. 
```python
>>> import xml.etree.ElementTree as ET
>>> xmlstr = "<elem>x&#13;&#10;</elem>" 
>>> ET.tostring(ET.fromstring(xmlstr))
b'<foo>x\r\n</foo>'
>>> ET.tostring(ET.fromstring(_))
b'<foo>x\n</foo>'
```
This happens with Python 2.7.12 and Python 3.8.1.
I also tried lxml and the C++ libraries TinyXml and Xerces whith this problem and all of them replaced <code>\r</code> with <code>\&#13;</code> or '<code>\&#xD;</code>, making the tostring() function reversible.

**Comment by dignissimus** [comment]
I wonder if this is relevant.

> # 2.11 End-of-Line Handling
>XML [parsed entities](https://www.w3.org/TR/REC-xml/#dt-parsedent) are often stored in computer files which, for editing convenience, are organized into lines. These lines are typically separated by some combination of the characters CARRIAGE RETURN (#xD) and LINE FEED (#xA).
>
>To simplify the tasks of [applications](https://www.w3.org/TR/REC-xml/#dt-app), the XML processor MUST behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating both the two-character sequence #xD #xA and any #xD that is not followed by #xA to a single #xA character.

https://www.w3.org/TR/REC-xml/#sec-line-ends

**Comment by mforner** [comment]
The W3 XML recommendations say a XML processor must replace '\r' or '\r\n' with a single '\n'. `ET.fromstring()` does this. That's why I believe, '\r' should  be escaped when converting a text element to a string (otherwise it will get lost).

The function doing the escaping for text elements is `ET._escape_cdata()`. Since 3.8 there also exists `ET._escape_cdata_c14n()` that replace '\r', but there seems to be no corresponding serialization method yet (just 'xml', 'html' and 'text').

As a workaround something like this should work:
```python
>>> ET._escape_cdata = ET._escape_cdata_c14n
>>> ET.tostring(ET.fromstring('<foo>x&#13;</foo>'))
b'<foo>x&#D;</foo>'
```
I don't think the current default behavior of `ET.tostring()` should be altered. It would be nice to have an additional serialization method.
