### ISSUE TITLE
Inconsistent behaviour of `dict.__ior__` compared to `dict.__or__`

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#91777]
**Bug report**

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

**Your environment**

- CPython versions tested on: Python 3.11.0a7
- Operating system and architecture: Windows 10 x64

Behaviour of `dict.__ior__` is inconsistent with `dict.__or__`:
```py
>>> a = {1: 2}
>>> a |= [(3, 4)]
>>> a
{1: 2, 3: 4}
>>> {1: 2} | [(3, 4)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'dict' and 'list'
```

**Comment by JelleZijlstra** [comment]
Why do you think it's a bug? The same thing happens with `list.__iadd__`:

```
>>> lst = [1, 2]
>>> lst += (3, 4)
>>> lst
[1, 2, 3, 4]
>>> lst + (5, 6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by thatbirdguythatuknownot** [comment]
It renders the equivalence (the in-place and evaluation properties not included) of `seq += other_seq` and `seq = seq + other_seq` as not true, since they would have different results for apparently the same thing.

**Comment by wimglenn** [comment]
Not a bug, that's the specification ([PEP584](https://peps.python.org/pep-0584/#specification))

> Dict union will return a new dict consisting of the left operand merged with the right operand, each of which must be a dict (or an instance of a dict subclass).

and 

> Augmented assignment behaves identically to the update method called with a single positional argument, so it also accepts ... iterables of key-value pairs. This is analogous to list += and list.extend, which accept any iterable, not just lists.

**Comment by thatbirdguythatuknownot** [comment]
I see. So I guess this issue can be closed?

**Comment by AlexWaygood** [comment]
> I see. So I guess this issue can be closed?

I think so; in general, in Python, there's no guarantee of equivalence between `x + y` and `x += y`. But feel free to start a discussion over at https://discuss.python.org if you think that should change :)
