### ISSUE TITLE
json mishandles integers in keys of dictionaries

### ISSUE THREAD

**Issue by eebop** [python/cpython#91774]
**Bug report**

When json encounters a integer as a key of a dictionaries, it converts it to the string representation of that int, which can cause problems.

>>> import json
>>> a = json.dumps({1:'a'})
>>> b = json.loads(a)
>>> b
{'1': 'a'}
>>> b[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 1

**Your environment**

- CPython versions tested on:
python 3.10.4

- Operating system and architecture:
ubuntu x86-64
GCC 9.4.0

**Comment by sweeneyde** [comment]
This is also the documented behavior:

https://docs.python.org/3/library/json.html#json.dumps

> Note: Keys in key/value pairs of JSON are always of the type str. When a dictionary is converted into JSON, all the keys of the dictionary are coerced to strings. As a result of this, if a dictionary is converted into JSON and then back into a dictionary, the dictionary may not equal the original one. That is, loads(dumps(x)) != x if x has non-string keys.

**Comment by rhettinger** [comment]
Closing this as not-bug.  This is long-standing, documented, and tested behavior.  It was added on purpose.
