### ISSUE TITLE
Float parsing and attribute parsing interfere with one another

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#91772]
**Bug report**

`5` compiles correctly
`5.` compiles correctly
`5 .` does not compile (and it's normal)
`5.__class__` and `5. __class__` **do not compile**, for no apparent reason.
`5..__class__` and `5. . __class__` compile correctly
`5 .__class__` compiles correctly

When the compilation fails, it does so at the ast parsing phase, which can be tested by copy-pasting the examples in the `ast.parse` function.
I see no reason (typically taken from the documentation) why the case which I flagged doesn't compile as/like the last one. The fact that it does not compile as a float seems reason enough to compile it as an attribute access on an int. If there is rationale not to compile it as such, the documentation should be completed and made clear about it (typically [here](https://docs.python.org/3/reference/lexical_analysis.html#floating-point-literals)).

**Your environment**

- CPython versions tested on: `Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32` (hope this is enough, but I don't think it's relevent here)
- Operating system and architecture: Windows x64 (same reserves)

**Comment by mdickinson** [comment]
This is a FAQ: https://docs.python.org/3/faq/programming.html#how-do-i-get-int-literal-attribute-instead-of-syntaxerror

I'll remove the bug label: Python _is_ working as designed here.

**Comment by mdickinson** [comment]
Here's a [link](https://mail.python.org/archives/list/python-ideas@python.org/thread/IMH4M6V2BXMPVQZ5QSYMTSAONZLA5L6U/#IMH4M6V2BXMPVQZ5QSYMTSAONZLA5L6U) to a related discussion on python-ideas; there are probably others. There may be a case for revisiting this with Python 3.9's new PEG parser.

**Comment by Gouvernathor** [comment]
The fact that `1.e1` (or something) is legal and not an attribute access is the reason I was missing. My bad !
