### ISSUE TITLE
PCbuild/readme.txt mentions build_pgo.bat which was removed in python 3.6

### ISSUE THREAD

**Issue by peendebak** [python/cpython#91795]
The file `PCbuild/readme.txt` still mentions the `build_pgo.bat` script, even though it was removed in python 3.6 (see https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Misc/NEWS.d/3.6.0a1.rst) 

### Linked PRs
* gh-91849
* gh-107776
* gh-107777

**Comment by fatihkabakk** [comment]
Also, [this link](http://msdn.microsoft.com/en-us/library/e7k32f4k(VS.140).aspx) under it is not found (404).

**Comment by arhadthedev** [comment]
@fatihkabakk Would you like to create a PR out of your `fix-issue-91795` branch?

**Comment by hauntsaninja** [comment]
Thanks all!
