### ISSUE TITLE
threading.Thread is rather awkward to use

### ISSUE THREAD

**Issue by BarneyStratford** [python/cpython#91876]
**Feature or enhancement**

I propose to add a new decorator, `@thread`, to threading. When called, a decorated function will start in its own thread and return the new thread to the caller.

**Pitch**

I find it awkward to write 
```
t = threading.Thread (target = target, args = <something>, kwargs= <something>)
t.start ()
...
t.join ()
```

every time I want to run something in a new thread. It's especially awkward if the _only_ calls to the target are from new threads. Instead, I'd prefer to write

```
@threading.thread 
def target (n):
    print ("Hello" * n)

t = target (3)
...
t.join ()
```

**Comment by DariuszPawlicki** [comment]
Hello. 
I'm interested in this issue.
I'm beginner in CPython so I don't know if newbie can do issues that aren't tagged as "easy", but in a case I could try,
any advices would be great :)

**Comment by BarneyStratford** [comment]
Hello Dariusz.

I opened this issue mainly so I'd have something to refer to in the pull request, which is at https://github.com/python/cpython/pull/91878 . Although it's not tagged as easy, it really is. My solution took only about 30 lines of new code. So I guess my advice is to look for something that seems interesting and give it a go. Just because it's not tagged doesn't necessarily mean it's not beginner-friendly. There are usually people around who can help you if you get stuck.

Barney.

**Comment by DariuszPawlicki** [comment]
Ok. understood thanks for the answer.

Sorry for offtopic, but GH don't have priv messages feature:

I have question, i've implemented this decorator similar to You and noticed strange "thread" behavior.

This is decorator:

`def thread(func):
    """

    """
    def wrapper(*args, **kwargs) -> Thread:
        t = Thread(target=func, args=(*args, ), kwargs={**kwargs})
        t.start()
        return t
    
    return wrapper`

This is my script that i've used for testing:

`import time
from Lib.threading import thread


@thread
def count_to(n):
    for i in range(1, n+1):
        print(i)
        time.sleep(1)



t1 = count_to(3)
t2 = count_to(5)
print("done")`

And here's a thing. If i run this script with decorator pasted into CPython "Lib.threading" output of the script looks like this:
1
1
"done"

and that's it, but i've noticed when i paste this decorator code into my main python dir "/usr/lib/python3.8/threading.py" everything works fine, script counts 11223345 and prints "done" somewhere. 
What's going on, can You tell me? :)

**Comment by BarneyStratford** [comment]
Arguably, you found a bug, or at least an edge case. Have a look in cpython/Python/pylifecycle.c line 2891, where you'll find a function called wait_for_thread_shutdown. This function is called after the main thread has finished executing and the interpreter is shutting down. Its sole purpose is to call threading._shutdown, which waits for all the threads to stop.

In your code, you haven't imported threading; instead you imported Lib.threading. As a result, wait_for_thread_shutdown can't find the threading module and thinks there are no threads to wait for. The interpreter shuts down prematurely.

If you import threading instead of Lib.threading you'll get the same module (assuming you're running the newly-built python.exe) and you'll get the expected behaviour.

**Comment by tiran** [comment]
Strong -1 from me

You really don't want to start new threads as a side-effect of an import statement. It can lead to all sorts of race conditions and even potentially a dead lock. It is recommended that application import all modules first, then run their threads. A ``@thread``decorator would promote bad design. 

Applications typically need ways to communication with a thread or wait for it (join). How would that work with your design?

**Comment by BarneyStratford** [comment]
I think there may be a misunderstanding. I'm not talking about starting threads with an import statement. I'm talking about starting a thread with a function call. The conversation with Dariusz is an aside.

What I'm proposing is to allow us to write
```
t = target (foo, bar, baz = 3)
```
instead of
```
t = threading.Thread (target = target, args = (foo, bar), kwargs = {"baz": 3})
t.start ()
```
by simply decorating the `target`.

**Comment by gst** [comment]
we could just add a `start: bool = False` arg to the Thread init maybe ?

**Comment by BarneyStratford** [comment]
@gst, can you show an example of what you mean?

**Comment by BarneyStratford** [comment]
@gst, I wonder if the confusion is because my proposed thread decorator is called `thread` and the thread class is called `Thread` (with capital T). Maybe I should rename the decorator to `threaded` in the PR #91878, so it looks like this:

```
from threading import threaded
import time

@threaded
def hello(who):
    time.sleep(10)
    print("Hello,", who)

hello("World")
```

**Comment by gst** [comment]
@BarneyStratford let's see what others think about the proposed feature.

I still think that it's better to limit the flag to the Thread class. and be done with it.

given that otherwise the function call return value **has** to be joined(). I think it's better to keep the function you want to execute in a sub-thread as is / "raw/pure" function. for unit testing already for instance.

eventually I would image a `with` context manager for Thread instances/objects that would be used like this  : 

```python
with threading.Thread(as_usual...) as instance:
    # do any // work along-side the instance Thread.
# thread is joined here
```

**Comment by BarneyStratford** [comment]
Threads don't have to be joined. I only put `t.join()` in my first post to show that you could do that if you need to. If you don't need to wait for it to complete then you can simply let it run. Once there are no references to the thread it'll just be garbage-collected like any other object.

What I'm struggling to communicate is that it's not the Thread.start() that's the problem but the way the thread is created in the first place. Hypothetically, how would you feel if you had to write
```
call_function(target = print, args = ("Hello",), kwargs = {"flush": True})
```
instead of the usual way to call a normal non-threaded function
```
print("Hello", flush = True)
```
To me the first of these looks pretty silly.

Re unit testing, I can see your point there. Maybe that aspect needs some more thought on my part.

**Comment by BarneyStratford** [comment]
Just done some more reading up. Turns out C++ does require you to dispose of your threads properly, by either joining them (same as python's join) or explicitly detaching them (same as letting them run to the end in Python). Java lets you just abandon threads like you can in Python, and they'll run to completion.

**Comment by gst** [comment]
> Threads don't have to be joined.

by default/most often they better have to.

**Comment by BarneyStratford** [comment]
I'm willing to believe that I'm wrong about joining (in which case I've been doing it wrong for years), but can you point to where in the docs it says that threads have to be joined?

In any case, this issue is not about the semantics of threads, it's about the syntax of how you create them in the first place. It's this that I see as ugly:
```
t = threading.Thread(target = target, args = <something>, kwargs= <something>)
```
not the starting/joining that happens afterwards.

**Comment by rhettinger** [comment]
I mostly like this idea and think it is interesting; however, it needs to be thought through and have buy-in before proposing a PR.   I recommend that you start a discussion on the python-ideas or the python-dev mail list.

**Comment by merwok** [comment]
I don’t personally see that using Thread is awkward, and I think the proposed decorator is too «cute» to fit in the standard library.
Something that looks like calling a function but actually creates and starts a thread is misleading.  This really is a two-line helper function (decorator or not) for personal toolboxes.

**Comment by merwok** [comment]
The discussion didn’t end up with general support for this.  Thanks for trying to improve Python regardless!
