### ISSUE TITLE
Add a `:gh:` role to the documentation to link to GitHub issues

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#91888]
The `` :issue:`...` `` role has been updated in GH-32342 to redirect to GitHub issues, but it still expects bpo ids.  A new `` :gh:`...` `` role is needed to link directly to new GitHub issues.

**Comment by kumaraditya303** [comment]
Fixed by #91889

**Comment by ezio-melotti** [comment]
> I think there's still open backport PRs for this, for 3.8 and 3.7

Yes:
* https://github.com/python/cpython/pull/91937
* https://github.com/python/cpython/pull/91936

The others have been merged:
* https://github.com/python/cpython/pull/91935
* https://github.com/python/cpython/pull/91934

**Comment by ezio-melotti** [comment]
All the backports have been merged, closing.
