### ISSUE TITLE
3.11.a7 Exception.add_note() and Exception.__notes__ not implemented; Exception.__note__ was instead

### ISSUE THREAD

**Issue by ptmcg** [python/cpython#91883]
**Documentation**

https://docs.python.org/3.11/library/exceptions.html?highlight=note#BaseException.add_note

The docs describe an instance method `add_note()`, but running Python 3.11.a7, there is no method for adding or setting notes on Exceptions. And instead of a `__notes__` attribute containing a list of strings, there is only the `__note__` attribute for a single string.

Not sure whether the documentation captured the intended implementation and the implementation was wrong, or if the docs documented a different implementation choice, which was rejected in favor of the current one.  See repl session below:

    >>> print(sys.version_info)
    sys.version_info(major=3, minor=11, micro=0, releaselevel='alpha', serial=7)
    >>> e = Exception()
    >>> e.add_note("This was intentional")
    Traceback (most recent call last):
      File "C:\Python3_11\Lib\code.py", line 90, in runcode
        exec(code, self.locals)
        ^^^^^^^^^^^^^^^^^^^^^^^
      File "<input>", line 1, in <module>
    AttributeError: 'Exception' object has no attribute 'add_note'
    >>> dir(e)
    ['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__note__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']
    >>> e.__note__ = "This was intentional"
    >>> raise e
    Traceback (most recent call last):
      File "C:\Python3_11\Lib\code.py", line 90, in runcode
        exec(code, self.locals)
        ^^^^^^^^^^^^^^^^^^^^^^^
      File "<input>", line 1, in <module>
    Exception
    This was intentional

**Comment by iritkatriel** [comment]
Thanks, this change was made after 3.11.a7 ad will be in the beta. The online documentation is updated continuously, so the documentation you are looking at is more recent than 3.11.a7.

**Comment by ptmcg** [comment]
So since the `__notes__` attribute does not exist unless `add_note` is called (according to https://docs.python.org/3.11/library/exceptions.html?highlight=add_note#BaseException.__notes__), is this the only reliable way to get the `__notes__` attribute?

    getattr(exception, '__notes__', [])

**Comment by iritkatriel** [comment]
That’s right, you can’t assume that the attribute exists.
