### ISSUE TITLE
`signal.signal` may throw when on `threading.main_thread`

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#91880]
Following on from https://github.com/python/cpython/pull/32105#issuecomment-1103098688

**Bug report**

It is possible for `signal.signal` to throw even when checked against `threading.main_thread`. For example, in this pattern:

```python
if threading.current_thread() is threading.main_thread() :
    signal.signal(signal.SIGINT, sigint_handler)
```

For example, in the case when the Python interpreter was started as an embedded interpreter with `Py_InitializeEx(0)` (0 meaning don't register signal handlers), then even though the `threading` check above will succeed `signal.signal` will throw because the "main thread" does not support signals.

It was suggested in https://github.com/python/cpython/pull/32105#issuecomment-1103350528 that it might be desirable to add a new API to the `signal` module which would return `True` only if the current thread supports signals.

**Comment by MojoVampire** [comment]
There's a mistake in this patch that I believe undoes at least part of the intent of the patch. When the exception is caught, the code sets:

    signal_handler = None

but `signal_handler` is not actually used anywhere. Almost certainly the intent was to do:

    sigint_handler = None

so as to prevent the attempt to check the currently set SIGINT handler later (and potentially restore the default handler). As is, it leaves `sigint_handler` as the `functools.partial` instance previously constructed, causing it to go down a code path that makes no sense when the main thread doesn't support signals at all.

**Comment by davidhewitt** [comment]
Thanks, I've opened a PR to correct my error.

**Comment by gvanrossum** [comment]
Ow, I should have caught that in review.
