### ISSUE TITLE
Broken link in Curses Programming with Python Guide

### ISSUE THREAD

**Issue by mile95** [python/cpython#91909]
**Documentation**

The `http://effbot.org/zone/console-index.html` link under `What is curses?` is broken. 

I'm referring to this page: 

https://docs.python.org/3/howto/curses.html

**Comment by Thaddeus1499** [comment]
This issue has been resolved with commit e9f66aedf44ccc3be27975cfb070a44ce6a6bd13 made in May 22, 2021 by removing the broken link to the console module.

**Comment by hauntsaninja** [comment]
Thanks both!
