### ISSUE TITLE
socket.shutdown() does not release a blocked recv() call - it's required to call socket.close()

### ISSUE THREAD

**Issue by bjoham** [python/cpython#91913]
**Bug report**

**Updated:** In Linux (Python 3.8.10, Ubuntu 20.04.4 LTS), it works as expected. 
Maybe the difference is that in Windows recv() can return with an error (WSAESHUTDOWN) for shutdown sockets whereas in Linux recv() returns with a byte count of zero.

**Original post:**
In my experience, a blocked call to a connected socket's recv() should be released by issuing a socket.shutdown(socket.SHUT_RDWR) - or socket.shutdown(socket.SHUT_RD)
That's according to function in Linux as well as TCP/IP standard (not sure here).

In Python, the shutdown() call seems to be ignored all together. See example, below.

**Your environment**

- CPython versions tested on: 3.9.12
- Operating system and architecture: Windows 10 Pro

**Example**
import threading
import socket
import time

HOST = "127.0.0.1"
PORT = 1234

def serverThread():
    print(f"Server starting for {HOST}:{PORT}")
    
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((HOST, PORT))
        s.listen()
        conn, addr = s.accept()
        with conn:
            print(f"Connected by {addr}")
            print("Server won't send anything")
            #conn.sendall(b"Hello")
            time.sleep(10)
            print("Server terminating...")
            conn.shutdown(socket.SHUT_RDWR) # Tell the client we're shutting down the connection - not absolutely necessary
            conn.close()
            
        s.close()

server = threading.Thread(target=serverThread, name="SERVER")

clientSocket = None
def clientThread():
    print(f"Connecting to server {HOST}:{PORT}")
    
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        global clientSocket
        clientSocket = s
        s.connect((HOST, PORT))
        print("Client is receiving...")
        try:
            data = s.recv(64)
        except OSError as e:
            print(f"Exception in client: {e}")
        else:
            print(f"Client has received: {data!r}")
            
        print("Client terminating...")
        
        if s.fileno() < 0:
            print("Someone has already closed the socket. Who is messing with my socket?!?!?")
        else:
            s.shutdown(socket.SHUT_RDWR) # Tell the server we're shutting down the connection - not absolutely necessary
            s.close()
        print("Client is done")
        
client = threading.Thread(target=clientThread, name="CLIENT")

print("Server and Client is set up")
server.start()
client.start()
time.sleep(2)

if clientSocket.fileno() < 0:
    print("Client socket is already closed, we're done")
    exit()
    
print("\nShutting down socket")
clientSocket.shutdown(socket.SHUT_RDWR)
print("\n   *** Nothing changed, right? ***")
time.sleep(2)

print("\n\nShutting down socket using close() coming up...")
time.sleep(2)
print("Now!")
clientSocket.close()
print("\n   >>> Now, we succeeded with releasing the blocked recv() call in client\n\n")

**Comment by bjoham** [comment]
It's not only telling the socket, It's also telling the other end that "time to rap things up".
In a multi-threaded case, it's also a good way (the only way?) to release any blocked threads and get them to terminate.

The consequences of not having a working shutdown() either forces a developer to use non-blocking sockets or to always check if the socket is already closed (through "emulated" shutdown()) before calling close() in a cleanup routine as part of terminating the thread. 


wellsilver ***@***.***> skrev: (25 april 2022 21:15:43 CEST)
>I think socket.shutdown() just tells sockets that its not listening anymore and that because nobody uses socket.shutdown() its been practicaly deprecated and is built into socket.close()
>
>though thats just an educated guess
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/python/cpython/issues/91913#issuecomment-1108943020
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by bjoham** [comment]
Moreover, with a working shutdown() implementation, the recv() call would just return and not raise an exception.

Hence, it would be possible to write simple *and robust* client-server apps in python making the language easy to learn, powerful, and fun. Isn't that the whole idea? 

"Björn Hammarberg" ***@***.***> skrev: (26 april 2022 07:27:25 CEST)
>It's not only telling the socket, It's also telling the other end that "time to rap things up".
>In a multi-threaded case, it's also a good way (the only way?) to release any blocked threads and get them to terminate.
>
>The consequences of not having a working shutdown() either forces a developer to use non-blocking sockets or to always check if the socket is already closed (through "emulated" shutdown()) before calling close() in a cleanup routine as part of terminating the thread. 
>
>
>wellsilver ***@***.***> skrev: (25 april 2022 21:15:43 CEST)
>>I think socket.shutdown() just tells sockets that its not listening anymore and that because nobody uses socket.shutdown() its been practicaly deprecated and is built into socket.close()
>>
>>though thats just an educated guess
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/python/cpython/issues/91913#issuecomment-1108943020
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>-- 
>Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.
-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by benrg** [comment]
`shutdown` is meant to inform the other end of the connection that one or both halves of it will no longer be used.

It isn't meant to exit from an ongoing blocking call on the same end of the connection. Neither [Microsoft](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown) nor [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/shutdown.html) say that it can be used for that.

Probably Windows just doesn't support what you're trying to do. It isn't a Python issue. Python is just calling the OS-provided functions.

**Comment by bjoham** [comment]
In Linux, it works and I have updated my post accordingly.

If it isn't meant to be used as a way to "unblock" a blocked call, how is the "unblocking" supposed to be done then? 

If "unblocking" is impossible, it essentially means that blocking calls are unusable unless the world is perfect (which it isn't) or one accepts applications that may hang and requires the user to issue a manual terminate of the app.

**Comment by bjoham** [comment]
I found this [https://groups.google.com/g/microsoft.public.win32.programmer.networks/c/qLFezDFTiiQ?pli=1](url)

From a hasty read, my conclusions are:
* Windows and POSIX (including Linux) does it differently
* Windows does NOT unblock a pending, e.g., recv() call when shutdown() is called
* This is not a Python issue and creating a workaround in python to fix Windows' bad implementation is not simple at least
* Blocking calls to Windows sockets is for any practical use just not recommended
