### ISSUE TITLE
Pathlib concatenation with abspath leads to root path?

### ISSUE THREAD

**Issue by p-hebert** [python/cpython#91926]
**Bug report**

Is this the expected behaviour?

```
>>> Path('/home/username/dir1') / '/dir2/dir3'
PosixPath('/dir2/dir3')
>>> Path('/home/username/dir1') / '/'
PosixPath('/')
```

Sounds to me like a dangerous behaviour because if someone wants to delete a dynamically constructed directory path and they are not aware of this behaviour, then that can result in wiping root level folders (granted, sufficient perms have to be given).
Here's a real world example I just happened to stumble upon:

```
filepath = Path('/home/username') / __file__.split('username')[1] # not ok, will result in __file__.split('username')[1]

filepath = Path('/home/username') / __file__.split('username/')[1] # ok, will result in appending __file__.split('username/')[1] to home user folder
```

**Your environment**

- CPython versions tested on: 3.8.11
- Operating system and architecture: MacOS, MacBook Pro (16-inch, 2019), 2.4 GHz 8-Core Intel Core i9

**Comment by ericvsmith** [comment]
Yes, this is documented. https://docs.python.org/3/library/pathlib.html#operators says slash is similar to `os.path.join()`. https://docs.python.org/3/library/os.path.html#os.path.join says "If a component is an absolute path, all previous components are thrown away and joining continues from the absolute path component."

**Comment by philippefutureboy** [comment]
Thanks @ericvsmith :)
Seems like I need to read the fine prints!
