### ISSUE TITLE
Clarify dict.setdefault()

### ISSUE THREAD

**Issue by kodcdangky** [python/cpython#91940]
Currently (Python 3.10.4), the documentation for `dict.setdefault()` reads:
"If _key_ is in the dictionary, return its value. If not, insert _key_ with a value of _default_ and return _default_. _default_ defaults to `None`."

Intuitively, this can be very easily misunderstood as `default` will not be evaluated if `key` was found in dictionary, especially since `default` is an optional argument, which is not the case. I suggest adding:
"_default_ is evaluated regardless of whether or not _key_ is in the dictionary. If this is undesired, the following template can be used instead:
```py
if key not in my_dict:
    my_dict[key] = default
```
" to the end of `setdefault()`'s doctumentation, or something similar. This can add some greatly appreciated clarity, especially for newer users of the language, or people unfamiliar with `dict.setdefault()` in general

**Comment by ericvsmith** [comment]
I'm not sure this is needed. In python, parameters are evaluated before functions are called. I don't think we want to add a warning to every applicable function that even if a parameter is potentially used, it's still evaluated before the function is called.

**Comment by kodcdangky** [comment]
I mistakenly clicked close issue.
About the issue, maybe I was too verbose in my suggestion, but I do believe the documentation implies the method has a timeline of operation, during which if the key was found, then it simply returns the key without going further. Maybe only a slight modification to make it more explicit is good enough, such as changing just the first sentence to "If _key_ is in the dictionary, return its value and ignore the evalutated _default_." or something to this effect.

**Comment by rhettinger** [comment]
> I figured most things are lazy similar 

Marking this a closed.  The OP's confusion has more to do with a general misunderstanding of the language than with *setdefault()* in particular.
