### ISSUE TITLE
Integer division of negative number rounds down rather than truncating

### ISSUE THREAD

**Issue by TBowen2k** [python/cpython#91956]
**Bug report**
Integer division of a negative number floors rather than giving just the integer part as it should.
(-a) DIV b ≡ -(a DIV b) --> correct
(-a) DIV b = FLOOR((-a) ÷ b)
e.g.
![image](https://user-images.githubusercontent.com/101470827/165314453-f7022357-6de9-4cdb-92aa-c4f832eeb92f.png)

**Your environment**
- CPython versions tested on:
- Operating system and architecture:
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by ericvsmith** [comment]
This is by design. See for example https://stackoverflow.com/questions/70730831/whats-the-mathematical-reason-behind-python-choosing-to-round-integer-division

**Comment by ericvsmith** [comment]
See also Note 1 under https://docs.python.org/3.8/library/stdtypes.html?highlight=integer%20division#numeric-types-int-float-complex
