### ISSUE TITLE
setenv/unsetenv errors on HP-UX during compilation

### ISSUE THREAD

**Issue by narender-n** [python/cpython#91965]
Trying to cross compile python3.10.4 on a Linux machine with gcc-9.3.0 for HP-UX IA64 and running into following errors. Did not find the setenv/unsetenv in stdlib.h for HP-UX.
```
*Python/pylifecycle.c: In function '_coerce_default_locale_settings':
Python/pylifecycle.c:319:9: error: implicit declaration of function 'setenv'; did you mean 'getenv'? [-Werror=implicit-function-declaration]
  319 |     if (setenv("LC_CTYPE", newloc, 1)) {
      |         ^~~~~~
      |         getenv
cc1: some warnings being treated as errors
./Modules/posixmodule.c: In function 'os_putenv_impl':
./Modules/posixmodule.c:10969:9: error: implicit declaration of function 'setenv'; did you mean 'getenv'? [-Werror=implicit-function-declaration]
10969 |     if (setenv(name_string, value_string, 1)) {
      |         ^~~~~~
      |         getenv
./Modules/posixmodule.c: In function 'os_unsetenv_impl':
./Modules/posixmodule.c:11014:15: error: implicit declaration of function 'unsetenv'; did you mean 'getenv'? [-Werror=implicit-function-declaration]
11014 |     int err = unsetenv(PyBytes_AS_STRING(name));
      |               ^~~~~~~~
      |               getenv*
```
Looks like this is implemented in 3.9 and does not have any config to skip this. Need help addressing this issue.

**Comment by vstinner** [comment]
HP-UX is not supported by Python: https://peps.python.org/pep-0011/

setenv() and unsetenv() functions are now required to build Python 3.9: https://docs.python.org/dev/whatsnew/3.9.html#build-changes -- See https://github.com/python/cpython/issues/83576

> Did not find the setenv/unsetenv in stdlib.h for HP-UX.

You might try to emulate/reimplement these functions for HP-UX (add a patch on top of Python).

**Comment by ronaldoussoren** [comment]
HP-UX appears to support these functions: https://docstore.mik.ua/manuals/hp-ux/en/B2355-60130/setenv.3C.html, there may be something wrong with the setup on the machine or HP-UX might require some additional define to enable this API (which probably can be enable using a suitable ``-D`` flag in the CFLAGS environment variable when running configure).

**Comment by vstinner** [comment]
If someone provides a PR, I can review it (but not test it) :-)

**Comment by ronaldoussoren** [comment]
> If someone provides a PR, I can review it (but not test it) :-)

Same here. It's been at least 10 years since I had access to HP-UX or other classic UNIX systems.

**Comment by narender-n** [comment]
Thank you all for looking into this. I don't think we have to address anything here.

We use cross compiled gcc to compile applications for several platforms. Some of them are deprecated years ago.

setenv and unsetenv are available in HP-UX11.31 and not in 11.23 which unfortunately is still a supported platform for us. I  was able to put  back the putenv implementation from 3.8 and it seems to work. 

We also use freeze.py to freeze the application for all these platforms.

I am attaching the patch file. 

[patch.txt](https://github.com/python/cpython/files/8673817/patch.txt)
.

**Comment by ronaldoussoren** [comment]
HP-UX 11.23 is End of Life according to [wikipedia](https://en.wikipedia.org/wiki/HP-UX).  Because of that and given that newer versions of the OS do support setenv() and unsetenv() I don't hink it is worthwhile to add the extra complexity to support this version of HP-UX back into CPython. 

Because of this I'm closing this issue.
