### ISSUE TITLE
Add FreeBSD build and test using Cirrus-CI

### ISSUE THREAD

**Issue by emaste** [python/cpython#91960]
**Feature or enhancement**

Add FreeBSD build and test using Cirrus-CI (for pull requests)
    
**Pitch**

Cirrus-CI is a hosted CI service that supports FreeBSD, Linux, macOS, and Winodws.  Add a .cirrus.yml to provide CI coverage on pull requests for FreeBSD 12.3 and 13.0.

Adding a .cirrus.yml to build + test on FreeBSD will add coverage for pull requests. (The Cirrus-CI application would need to be enabled on the cpython repo.)

Here is an example run from my fork: https://cirrus-ci.com/build/5512210465161216

**Previous discussion**

### Linked PRs
* gh-91961
* gh-108972
* gh-108993
* gh-108999
* gh-109010
* gh-109011
* gh-109127
* gh-109457
* gh-113938

**Comment by erlend-aasland** [comment]
We've currently got two [stable](https://www.python.org/dev/buildbot/) FreeBSD 14.0 buildbots in our "extended" CI:

- https://buildbot.python.org/all/#/builders/172
- https://buildbot.python.org/all/#/builders/483

The buildbots run on _every_ merge to `main`, and also on PR's where it is explicitly requested by a core dev or triager, so we do get FreeBSD coverage for everything that is merged. Of course, adding FreeBSD 13.0 and 12.3 would be a welcome addition to our buildbot fleet. See these links for more info:

- https://devguide.python.org/buildworker/
- https://github.com/python/buildmaster-config

I don't think we will be adding FreeBSD to our main CI, though, so I suggest closing this issue.

**Comment by emaste** [comment]
I did this based on @vstinner's comment that there's no pull request CI for FreeBSD and inquiry about whether there's a service that supports it. I'm sure FreeBSD 13.1/12.3 bots could be added instead, but is there a reason having comprehensive pre-merge CI for FreeBSD would be undesirable?

**Comment by emaste** [comment]
It's https://github.com/python/cpython/pull/91961

I opened this issue because the pull request template told me I needed one - apologies if I missed the appropriate metadata here or in the PR to cross-reference them.

I'd be happy to help out with getting 12.x/13.x buildbot workers attached instead if that's the desired approach, but Cirrus-CI has the nice property of being a hosted service that does not require ongoing maintenance on the workers, and can easily be updated to use any FreeBSD images that are available in GCP.

**Comment by vstinner** [comment]
Please have a look at PR #104574: a change proposes to use GNU make syntax which is not compatible with FreeBSD bsdmake.

**Comment by vstinner** [comment]
> May I ask you or @vstinner to check the current status?

One week ago, the two FreeBSD buildbot were removed: https://github.com/python/buildmaster-config/pull/386

I'm looking for a solution to keep running tests automatically on FreeBSD and get notifications if something breaks. Add a new buildbot worker, add a GitHub Action job, or both!

**Comment by vstinner** [comment]
> Oh, that's unfortunate. I don't have the resources to support a buildbot myself. But let me know if I can do anything to help make an automated job happen. 

I contact some FreeBSD developers who are interesed to set up new FreeBSD buildbot workers, especially Kurt Jaeger. Ping me in private if you want me to get in touch with them.

**Comment by vstinner** [comment]
Also, the Cirrus-CI approach is happening, see the PR of this issue: PR #91961.

**Comment by vstinner** [comment]
I wrote PR #109457 to disable the job: Python is out of free credit and so all jobs are reported as failure.
