### ISSUE TITLE
sort() method bug.

### ISSUE THREAD

**Issue by Noslenor** [python/cpython#91975]
**Bug report**

**A bug regarding sort() method.** 
**Issue:** When sort() method is used on a variable containing a list, it not only sorts the order of the variable used to contain the list, but it also sorts a variable (of a different name) that was initiated in order to preserve the original order of the list. For example, 

 # This code example demonstrates an issue with sort() method
 places = ['Borneo', 'Africa', 'Hawaii', 'Spain', 'Brazil', 'America']
 print(f"This prints the variable list 'places' in unsorted order: {places}")
 
 # This variable 'places1' is created in order to maintain the original sort order. 
 places1 = places
 print(f"This prints the variable 'places1' in the same order as the variable 'places': {places1}")
 
 # This sorts the variable 'place' and then prints it. 
print("Below is displayed the variables 'places' and 'places1', but both have been sorted even though only 'places' was sorted.")
 places.sort()
 print(places)

# However, for some reason the already defined variable 'places1' keeps the changed sort order of 'places.' This seems to be a problem. 
print(places1)

** Output **
This prints the variable list 'places' in unsorted order: ['Borneo', 'Africa', 'Hawaii', 'Spain', 'Brazil', 'America']
This prints the variable 'places1' in the same order as the variable 'places': ['Borneo', 'Africa', 'Hawaii', 'Spain', 'Brazil', 'America']
Below is displayed the variables 'places' and 'places1', but both have been sorted even though only 'places' was sorted.
['Africa', 'America', 'Borneo', 'Brazil', 'Hawaii', 'Spain']
['Africa', 'America', 'Borneo', 'Brazil', 'Hawaii', 'Spain']
** End Output **

Admittedly, this seems to be a minor issue, but I suppose could affect someone. 

** Environment **
I am running the following system: 
iMac - 4.2 GHz Guad-Core intell Cor i7
MacOS Monterey v. 12.3.1
python version 3.9.7
Using Sublime Text Editor

**Your environment**

**Comment by ericvsmith** [comment]
This is not a bug. `places` and `places1` are two names for the same list.
