### ISSUE TITLE
Asyncio RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by asterized** [python/cpython#91987]
**Bug report**

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

When using aiohttp with asyncio in a class, it throws a RuntimeError

MRE:
```py
import aiohttp
import asyncio

class Test:
    def __init__(self):
        self.session = asyncio.run(self.test())

    async def test(self):
        return aiohttp.ClientSession()

    async def get(self, url):
        async with self.session.get(url) as response:
            return await response.json()

t = Test()
async def test():
    print(await t.get("https://httpbin.org/get"))

asyncio.run(test())
```

**Your environment**

- CPython versions tested on: 3.10.2
- Operating system and architecture: MacOS using x86_64

**Comment by fatihkabakk** [comment]
I think it might not be a bug, it also happens on python3.9 Windows 10 build 19044

**Comment by SomeHybrid** [comment]
> I think it might not be a bug, it also happens on python3.9 Windows 10 build 19044
> 
> ```python
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\...\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\...\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "<stdin>", line 2, in test
>   File "<stdin>", line 7, in get
>   File "C:\...\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
>     self._resp = await self._coro
>   File "C:\...\Python39\lib\site-packages\aiohttp\client.py", line 429, in _request
>     handle = tm.start()
>   File "C:\...\Python39\lib\site-packages\aiohttp\helpers.py", line 586, in start
>     return self._loop.call_at(when, self.__call__)
>   File "C:\...\Python39\lib\asyncio\base_events.py", line 725, in call_at
>     self._check_closed()
>   File "C:\...\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> ```

I'm running it on MacOS though

**Comment by kumaraditya303** [comment]
This is not a python issue as you are creating `aiohttp.ClientSession()` in a different event loop and using it in a different event loop hence it is throwing `RuntimeError` exception.

You can ask user questions here https://discuss.python.org/c/users/7
