### ISSUE TITLE
--enable-pystats location, 'WebAssemby'

### ISSUE THREAD

**Issue by vainaixr** [python/cpython#91998]
https://docs.python.org/3.11/using/configure.html#cmdoption-enable-pystats

 I was reading through configure options and I think so the documentation has a mistake, for
--enable-pystats, it says,
Use Tools//summarize_stats.py to read the stats.
but on my computer, this file is in Tools/scripts/summarize_stats.py

also, 'WebAssemby' to 'WebAssembly'

**Comment by sweeneyde** [comment]
Would you like to submit a Pull Request fixing this?

**Comment by hauntsaninja** [comment]
Thanks! I think this can be closed, the "WebAssembly" PR is linked above and looks like summarize_stats filename was changed in #92011
