### ISSUE TITLE
test_faulthandler is too strict in threaded checks

### ISSUE THREAD

**Issue by jkloth** [python/cpython#92006]
In `test_faulthandler.check_dump_traceback_threads()` the regex is being overly strict in regard to the line number for the `run()` method.

It is possible for a context switch to happen between the `running.set()` and `stop.wait()` calls which leads to the checking regex to fail.  See [AMD64 Windows11 3.x/1225/test](https://buildbot.python.org/all/#/builders/733/builds/1225/steps/4/logs/stdio) for an example where this breaks.

### Linked PRs
* gh-92008

**Comment by hauntsaninja** [comment]
Is this still a problem on main? PR welcome if so!

**Comment by arhadthedev** [comment]
The referred logs did not survive till these days but I guess that the non-mutated code chunk does not change line numbers of methods inside. Also, this error does not manifest itself at all so closing.
