### ISSUE TITLE
sqlite3.Blob indexing is not conformant with existing norms

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#92019]
Yesterday, @JelleZijlstra enlightened me that sqlite3.Blob indexing operate with `bytes` objects of length 1. This is a deviation from how `bytes`, `bytearray`, and `memoryview` work:

```
>>> bytes(b"0")[0]
48
>>> bytearray(b"0")[0]
48
>>> memoryview(b"0")[0]
48
>>> b = bytearray(b"0")
>>> b[0] = 1
>>> b[0] = b"1"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bytes' object cannot be interpreted as an integer
>>> m = memoryview(b)
>>> m[0] = 1
>>> m[0] = b"1"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid type for format 'B'
>>> 
```

Suggesting to align sqlite3.Blob indexing behaviour so it expects `int`s and returns `int`s.

**Comment by JelleZijlstra** [comment]
Credit to @Akuli who brought this up in https://github.com/python/typeshed/pull/7684#issuecomment-1110308667

**Comment by serhiy-storchaka** [comment]
There is also a similar deviation in `mmap`.

**Comment by JelleZijlstra** [comment]
We probably can't fix that though, since mmap has already been in the stdlib for a long time.
