### ISSUE TITLE
Usage of first-person pronouns in documentation

### ISSUE THREAD

**Issue by AnnaElshayeb** [python/cpython#92033]
**Documentation**

On line 2525 of the documentation, first-person narration is used for one single line. The entire doc is written using second person narration throughout, excluding this singular typo. 

Current line: `Before I explain how auto-speccing works, here’s why it is needed.`
Proposed update line: `Before explaining how auto-speccing works, it is important to understand why it is needed.`

**Comment by rhettinger** [comment]
I don't see why we care about changing this. It reads well and allows a personal touch like a guided tour.

**Comment by serhiy-storchaka** [comment]
There is more of this. See #62480.

**Comment by slateny** [comment]
Borrowing some of the [discussion on Diataxis](https://discuss.python.org/t/adopting-the-diataxis-framework-for-python-documentation/15072/13), I think whether first-person pronouns belong in documentation depends on how the documentation is structured.

If it is the case how-to/guides and tutorials can be personal, and references impersonal (say like [Wikipedia articles](https://en.wikipedia.org/wiki/Wikipedia:Writing_better_articles#Use_of_pronouns)), then it seems acceptable that a page of documentation (pages under `/library`) that blends guides, tutorials, and references may have a blend of first- and third-person pronouns, as in the referenced [unittest.mock](https://docs.python.org/3/library/unittest.mock.html).

If it's the case that documentation shouldn't have first-person pronouns, then perhaps documentation should explicitly split these guides, tutorials, and references into their own pages, somewhat like [logging](https://docs.python.org/3/library/logging.html).

**Comment by JelleZijlstra** [comment]
I'm with Raymond; I don't think anything needs changing here.

**Comment by slateny** [comment]
If a section of the doc was written in first person I'd agree that it would read like a personal guide, but doesn't it read a bit oddly and seem out of place when there's only one instance of a first-person perspective?

**Comment by JelleZijlstra** [comment]
There's also a lot of "we" in this document.

**Comment by slateny** [comment]
I see I see, that makes a lot more sense, thanks.
