### ISSUE TITLE
how do support FGO with python

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#92043]
hi, my friend, i see the [README.rst](https://github.com/python/cpython#readme), and i know [Profile Guided Optimization](https://github.com/python/cpython#id5) with "--enable-optimizations", and i want to the python support FGO, i see "# Enable optimization flags" and "# Enable PGO flags." in configure.ac. I'm confused.

Which side should I imitate?

![image](https://user-images.githubusercontent.com/67537842/165920046-c74adb92-3464-4ac7-bc81-ace50b0407bd.png)

![image](https://user-images.githubusercontent.com/67537842/165920007-caabfde9-f1cb-4829-a698-10ed46ce372a.png)

**Comment by alittlesir** [comment]
如果这两个都要用到，那为什么要分开写呢？中间又插了一个LTO，这种写法真的很怪异

**Comment by alittlesir** [comment]
What's the difference between these two? ("# Enable optimization flags" and "# Enable PGO flags.")

**Comment by methane** [comment]
Don't care. Just use `--enable-optimizations --with-lto`.
