### ISSUE TITLE
The docs for Py_GetVersion assumes minor version < 9

### ISSUE THREAD

**Issue by jebob** [python/cpython#92047]
**Documentation**

From https://docs.python.org/3.11/c-api/init.html?highlight=py_getversion#c.Py_GetVersion:

> the first three characters are the major and minor version separated by a period.

Which is only true for single-digit minor version, this is untrue for Python 3.10+.

**Comment by vstinner** [comment]
Do you want to propose a PR to fix the doc?

**Comment by jebob** [comment]
PR proposed: https://github.com/python/cpython/pull/92048
