### ISSUE TITLE
specialized PRECALL opcodes don't check types

### ISSUE THREAD

**Issue by sweeneyde** [python/cpython#92063]
On the main branch, on both Windows and Linux, this crashes:

```python
class Thing:
    pass

thing = Thing()

for i in range(10):
    print(i)
    try:
        str.upper(thing)
    except TypeError:
        pass

print("ok")
```

Other methods like `str.split`, `bytes.split`, and `list.sort` fail similarly. I caught this by running

```
./python -m test test_descr -m test_proxy_call -R3:20
```

Looking through stack traces, it appears the failure is on the `res = cfunc(...)` call in `PRECALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS` instruction. It looks to be a 3.11-only bug.

**Comment by sweeneyde** [comment]
If we're trying to emulate [method_vectorcall_FASTCALL_KEYWORDS](https://github.com/python/cpython/blob/7861a9e3276cf9bf2bfa56d86f29ef06b2456f87/Objects/descrobject.c#L412-L429), then we're at least missing out on how `method_check_args` calls `descr_check`, which calls `PyObject_TypeCheck(obj, descr->d_type)`. So we need one of these:

```
DEOPT_IF(!PyObject_TypeCheck(obj, descr->d_type));
```
or
```
DEOPT_IF(!Py_IS_TYPE(obj, descr->d_type));
```

cc @Fidget-Spinner @kumaraditya303

**Comment by sweeneyde** [comment]
Marking as release blocker: it's easy to trigger but hard to reason about if you don't know about specialization, so it could create Heisenbugs, which would be unfortunate in the beta release.

**Comment by corona10** [comment]
macOS meets the same issue since as expected.

**Comment by sweeneyde** [comment]
It looks like `PRECALL_NO_KW_METHOD_DESCRIPTOR_NOARGS` is affected as well.

**Comment by sweeneyde** [comment]
PRECALL_NO_KW_METHOD_DESCRIPTOR_O as well
