### ISSUE TITLE
doctest is not working for specific case (Python 3.10.4 + PyCharm)

### ISSUE THREAD

**Issue by ChameleonRed** [python/cpython#92072]
**Bug report**
```
"""
>>> (2048).to_bytes(4, byteorder='little')
b'\x00\x08\x00\x00'
"""

if __name__ == '__main__':
    import doctest
    doctest.testmod()
```

**********************************************************************
Failed example:
    (2048).to_bytes(4, byteorder='little')
Expected:
    b'       '
Got:
    b'\x00\x08\x00\x00'
**********************************************************************
1 items had failures:
   1 of  37 in __main__
***Test Failed*** 1 failures.

Process finished with exit code 0
**Your environment**

- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows 10

**Comment by ChameleonRed** [comment]
Sometimes!
```
Failed example:
    (2048).to_bytes(4, byteorder='little')
Expected:
    b'  '
Got:
    b'\x00\x08\x00\x00'
```

**Comment by stevendaprano** [comment]
This is not a doctest bug. You need to escape the backslashes in your doc string, or use a raw string r""" ... """.

What you are doing is embedding actual ASCII nuls etc in the doc string, so the expected output is NUL BACKSPACE NUL NUL, but when doctest collects the output it uses the repr() of the string which is \x00 etc, so naturally they don't match.

**Comment by stevendaprano** [comment]
You can test for yourself by putting this after your existing doc string:

    print(chr(0) in __doc__)  # There should be no ASCII NUL in the docstring.
    print('b\\0x' in __doc__)  # Is there b-quote-backslash-zero in the docstring?

**Comment by ChameleonRed** [comment]
Let's try this - my bug - I forget that is such simple reason :)
Thank you :)
