### ISSUE TITLE
contextlib.closing is a class, but the docs mark it as a function

### ISSUE THREAD

**Issue by smheidrich** [python/cpython#92082]
**Documentation**

`contextlib.closing` [is a class](https://github.com/python/cpython/blob/e91dee87edcf6dee5dd78053004d76e5f05456d4/Lib/contextlib.py#L320) (and has been since Python 2.x, perhaps always but I'm not sure), but the docs [mark it as a function](https://github.com/python/cpython/blob/e91dee87edcf6dee5dd78053004d76e5f05456d4/Doc/library/contextlib.rst).

While searching for previous reports of this issue, I found #55102, which describes a similar mismatch between docs and reality for `staticmethod` and the resolution was that "this is a total non-issue", but in this case, right next to `closing` we have `aclosing` which [*is* marked as a class](https://raw.githubusercontent.com/python/cpython/e91dee87edcf6dee5dd78053004d76e5f05456d4/Doc/library/contextlib.rst), so this is just inconsistent.

Is this intentional and meant to signal to users that they shouldn't rely on `closing` being a class because that is considered an implementation detail? If so, why doesn't the same rationale hold for `aclosing`?

**Comment by JelleZijlstra** [comment]
Whether it's a class or a function is an implementation detail, and we don't need to explicitly say in the docs that `closing` is a class.

But I agree that it's inconsistent that we document `aclosing` as a class. I think we should just document `aclosing` as a function too.

**Comment by smheidrich** [comment]
Fixed in #92155
