### ISSUE TITLE
Minor doc enhancement for math.acos

### ISSUE THREAD

**Issue by BurdetteLamar** [python/cpython#92098]
**Documentation**

Propose adding to math.acos:
- Domain: [-1,.0 1.0].
- Range: [0.0, pi].
- Examples:
    math.acos(-1)
    3.141592653589793
    math.acos(1)
    0.00
  
Motivation:  In recent years I have been a major contributor to documentation over at ruby/ruby.  I'd like to start contributing here.  Module math seems like a good place to start b/c it's not subtle.

**Comment by rhettinger** [comment]
I don't think this addresses any known user need. It makes the docs more voluminous without making them more useful.

**Comment by rhettinger** [comment]
@BurdetteLamar To start to contribute, I recommend looking through the open doc issues and helping solve actual known places where users have been confused.  This will be much more productive than sweeping through the docs starting to rewrite everything you see.

Also, every project has its own documentation norms. I recommend getting familiar those norms before changing the style or approach that has mostly worked well for us.
