### ISSUE TITLE
help with pathlib python 3.10.4

### ISSUE THREAD

**Issue by korus93** [python/cpython#92139]
![Screenshot_2022-05-02_13_03_53](https://user-images.githubusercontent.com/57868704/166225037-7b1f9ee4-a45d-417b-ae25-036a22242627.png)

**Comment by AlexWaygood** [comment]
Hi! User-help questions should go to https://discuss.python.org/c/users/7, rather than the GitHub bug tracker — this is where we talk about bugs in CPython itself, rather than bugs in code that uses Python 🙂
