### ISSUE TITLE
Python segfaults when loading libxml2 module

### ISSUE THREAD

**Issue by lukaso** [python/cpython#92158]
**Crash report**

```
$ python3
>>> import libxml2
```

This segfaults on an M1 Mac when I have built both python and libxml2. The same code did not segfault on intel based Mac with same build system.

Python 3.10.4 is built with `--enable-shared`
libxml2 2.9.12 is build with `--libdir="$JHBUILD_LIBDIR" --with-python` (libdir is set for the build system).

libxml2 is also patched with the following:

```
--- a/configure.ac	2021-05-13 11:44:23.000000000 -0700
+++ b/configure.ac	2021-11-08 11:13:54.000000000 -0800
@@ -905,7 +905,17 @@
 	fi
     fi
     pythondir='$(PYTHON_SITE_PACKAGES)'
-    PYTHON_LIBS=`python$PYTHON_VERSION-config --ldflags`
+    py_ver_major=$(echo $PYTHON_VERSION | cut -d . -f 1)
+    py_ver_minor=$(echo $PYTHON_VERSION | cut -d . -f 2)
+    if test $py_ver_major -eq 3 -a $py_ver_minor -ge 8
+    then
+       PYTHON_LIBS=`python$PYTHON_VERSION-config --ldflags --embed`
+    elif test $py_ver_major -gt 3
+    then
+       PYTHON_LIBS=`python$PYTHON_VERSION-config --ldflags --embed`
+    else
+        PYTHON_LIBS=`python$PYTHON_VERSION-config --ldflags`
+    fi
 else
     PYTHON=
 fi

Diff finished.  Mon Nov  8 11:28:35 2021
```

**Error messages**

This is the stack trace:

```
_PyInterpreterState_GET (/Users/lukasoberhuber/gtk/source/Python-3.10.4/Include/internal/pycore_pystate.h:113)
PyModule_Create2 (/Users/lukasoberhuber/gtk/source/Python-3.10.4/Objects/moduleobject.c:176)
PyInit_libxml2mod (/Users/lukasoberhuber/gtk/source/libxml2-2.9.12/python/libxml.c:3913)
_PyImport_LoadDynamicModuleWithSpec (@_PyImport_LoadDynamicModuleWithSpec:203)
_imp_create_dynamic (@_imp_create_dynamic:105)
cfunction_vectorcall_FASTCALL (@cfunction_vectorcall_FASTCALL:70)
_PyEval_EvalFrameDefault (@_PyEval_EvalFrameDefault:6553)
_PyEval_Vector (@_PyEval_Vector:44)
call_function (@call_function:80)
_PyEval_EvalFrameDefault (@_PyEval_EvalFrameDefault:6347)
_PyEval_Vector (@_PyEval_Vector:44)
call_function (@call_function:80)
_PyEval_EvalFrameDefault (@_PyEval_EvalFrameDefault:6335)
_PyEval_Vector (@_PyEval_Vector:44)
call_function (@call_function:80)
_PyEval_EvalFrameDefault (@_PyEval_EvalFrameDefault:6379)
_PyEval_Vector (@_PyEval_Vector:44)
call_function (@call_function:80)
_PyEval_EvalFrameDefault (@_PyEval_EvalFrameDefault:6379)
```

Here's the crash inside the debugger:

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/5034/166261148-037106e0-7e67-4684-8d37-bbbf054434d6.png">

I also noticed this change https://github.com/python/cpython/pull/24583/files#diff-23071700ee893f365a4c117210b9129d4ac6afe5cc6e52bb5cd4cabbc6816e07R837 where the test that `tstate->interp` exists has been dropped.

**Your environment**

- CPython versions tested on: 3.10.4
- Operating system and architecture: MacOS Monterey 12.2.1, arm64 (M1)

**Comment by ronaldoussoren** [comment]
Is ``import libxml2mod`` after installing libxml2 enough to reproduce the problem or does this require more setup?

**Comment by ronaldoussoren** [comment]
Why did you patch the configure script? Linking C extensions to the python interpreter is generally not advisable, especially on macOS.  

This can cause problems when you have two python installations on your system. In particular:
* To installations of Python 3.10, "A" and "B"
* Build the extension with "A" with "python3-config --ldflags --embed"
* Load the extension with "B"

The CPython API calls in the extension will use symbols from the "A" install of Python, *not* the initialised "B" interpreter. The two don't share resources and that effectively results in the extension using an uninitialised interpreter.  

This scenario is compatible with the crash you're seeing where the thread state seen by Py_CreateModule2 is NULL even though the caller of the API has not given up the GIL. 

BTW. I cannot reproduce the crash on my machine:
- Python 3.10.4 installed from python.org
- Created a virtual environment ("python3.10 -m venv working")
- Installed libxml2 into the prefix of the virtual environment (after manually patching the configure script to use --embed)

**Comment by lukaso** [comment]
I'm not sure of why I'm calling `--embed` as this predates me.

> Is `import libxml2mod` after installing libxml2 enough to reproduce the problem or does this require more setup?

It was `import libxml2`, not `import libxml2mod` but yes, that's all it took.

**Comment by lukaso** [comment]
> Why did you patch the configure script? Linking C extensions to the python interpreter is generally not advisable, especially on macOS.
> 
> This can cause problems when you have two python installations on your system. In particular:
> 
> * To installations of Python 3.10, "A" and "B"
> * Build the extension with "A" with "python3-config --ldflags --embed"
> * Load the extension with "B"
> 
> The CPython API calls in the extension will use symbols from the "A" install of Python, _not_ the initialised "B" interpreter. The two don't share resources and that effectively results in the extension using an uninitialised interpreter.
> 
> This scenario is compatible with the crash you're seeing where the thread state seen by Py_CreateModule2 is NULL even though the caller of the API has not given up the GIL.

Interesting. My use case is embedding python into [Gimp for Mac](https://www.gimp.org/). I'm the Mac maintainer.

The `--embed` patch predates me, and all of it works with `3.9.12` without crashing, and with `3.9.7` on an intel mac. For now I've reverted to that version.

There is indeed a second 3.10 interpreter involved which is used for running the build (which does have its own virtual environment), which is not embedded into Gimp for packaging, so your hypothesis may well be correct.

I will have to dig harder because with 3.9.12 the `import libxml2` says module not found, which does point to something having gone wrong (since the `libxml2` module was built.

I won't have time for a bit to look into this further, but as soon as I find something, I'll reply here.

> 
> BTW. I cannot reproduce the crash on my machine:
> 
> * Python 3.10.4 installed from python.org
> * Created a virtual environment ("python3.10 -m venv working")
> * Installed libxml2 into the prefix of the virtual environment (after manually patching the configure script to use --embed)

**Comment by ronaldoussoren** [comment]
One way to check if what I wrote earlier is relevant for you is to check in the debugger which shared libraries are loaded. If there are two copies of Python you ran into what I described.

The ``--embed`` should not be necessary for your use case. I'm not an expert of python-config, but given its the output of ``python3-config --ldflags --embed`` I'd say that the option is primarily useful to get the linker flags for embedding Python itself and not for linking extensions.  For extensions your embedded copy of Python is the same as the standalone interpreter.

**Comment by lukaso** [comment]
> check in the debugger which shared libraries are loaded

Thanks! I'll do that.

> The --embed should not be necessary for your use case.

`libxml2` is being used in two ways. 1) as part of Gimp, in which case it does not need the embed flag, but 2) as part of `itstool` which apparently needs a `libxml2` build `--with-python` which probably does need the `--embed` flag.

**Comment by ronaldoussoren** [comment]
I'm >99% sure that the problem is caused by linking an extension to libpython and loading it in an interpreter linked to a different libpython. That doesn't work on macOS because the dynamic linker uses the full path embedded in binaries.

Issue can be reopened if there is additional information that shows there is a problem on our end.

**Comment by ntessore** [comment]
I am running into (what I think is) the same issue while trying to make conda recipes for [fontforge](https://github.com/fontforge/fontforge).

FontForge builds a single shared library `libfontforge` that _both_ embeds Python for scripting _and_ can be loaded as a native extension module. Due to the former, `libfontforge` is linked against `libpython` (as per `--embed`). When loading the latter in an `--enable-shared` Python on macOS, it segfaults because the interpreter is not initialised.

Is there a way out of this except for having two separate `libfontforge` instances, one for embedding, and one for the extension module?
