### ISSUE TITLE
[C-API] Add a function to access PyCodeObject.co_code in C

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#92154]
**Feature or enhancement**

Previously, you could access the `co_code` field in `PyCodeObject` directly to access the bytecode. This is no longer the case since https://github.com/python/cpython/commit/2bde6827ea4f136297b2d882480b981ff26262b6. Currently in 3.11a7+, C code cannot easily obtain the equivalent of `co_code` in 3.10. `co_code_adaptive` gets quickened bytecode which is not equivalent to the 3.10 behavior.

I would imagine many tools relying on the old behavior will break.

**Pitch**

I propose we expose some form of the currently internal `_PyCode_GetCode`.

**Previous discussion**

Related to #91397.
See also coverage.py issue https://github.com/nedbat/coveragepy/issues/1367

CC @vstinner @nedbat @brandtbucher @markshannon

**Comment by vstinner** [comment]
See also https://github.com/python/cpython/issues/91397 "[C API] Move the PyCodeObject structure to the internal C API (make the structure opaque)".

**Comment by vstinner** [comment]
Even if no function is added, please document at least the member removal in https://docs.python.org/dev/whatsnew/3.11.html (C API > Porting to Python 3.11) since the PyCodeObject structure **is** part of the public C API.

**Comment by markshannon** [comment]
Exposing `PyCode_GetCode` makes sense to me, as it equivalent to `code.co_code`.

@brandtbucher

**Comment by brandtbucher** [comment]
Sounds good to me as well.

**Comment by vstinner** [comment]
And I added the function to pythoncapi-compat: https://github.com/python/pythoncapi-compat/commit/85d1bd86f56c4ea96f619bd5766f6ebf2d2bbef2
