### ISSUE TITLE
"\U0001f229""\U0001f214""\U0001f22a""\U0001f242""\U0001f241" aren't recognize as numeric characters

### ISSUE THREAD

**Issue by cheny0y0** [python/cpython#92159]
**Bug report**

**Your environment**

- CPython versions tested on: Python 3.8.*
- Operating system and architecture: all if supported

The faces of these characters(perhaps some fonts do not support these glyphs): 🈩🈔🈪🉂🉁
These are characters with square or tortoise shell and numeric ideograph in it.

**Comment by ezio-melotti** [comment]
```py
>>> import unicodedata
>>> s = '🈩🈔🈪🉂🉁'
>>> [unicodedata.category(c) for c in s]
['So', 'So', 'So', 'So', 'So']
```
The Unicode category of these character is `So` (Symbol, other).  Only characters that have an [`Nd` (Number, Decimal Digit) category ](https://docs.python.org/3/library/stdtypes.html#typesnumeric) are recognized as numbers.
