### ISSUE TITLE
heappush creating diffrent heap than heapify

### ISSUE THREAD

**Issue by Thodoris-Evangelakos** [python/cpython#92190]
**Bug report**

While making a heap with elements found in a binary file I noticed that adding the elements in a list and calling heapq.heapify() on said list doesn't produce the same results as calling heapq.heappush() N times on an empty list,  code below:
```
import heapq
from helpMethods import readBytes, readInt, toIntArray
N = 10**6

heapA = []
heapB = []

with open("millionKeys.bin", 'rb') as file:
    for i in range (0,N):
        heapA.append(readInt(file, i)) #adding element to the list
        heapq.heappush(heapB, readInt(file, i)) #pushing element to the heap

heapq.heapify(heapA) #turning the list into a heap
print(heapA == heapB) #checking if they're the same

##some extra print statements for debugging
print(heapA[0:20])
print(heapB[0:20])
```

as far as the methods from "helpMethods" are concerned:

```
def readBytes(file, position): #reads 4 bytes
    file.seek(position)
    byte_array = bytearray(file.read(4))
    return byte_array

def toIntArray(bytes):
    result = [0]
    result[0] = int.from_bytes(bytes[0:4], 'big')
    return result[0]
    
def readInt(file, position):
    #pass a simple position to this method
    intFromFile = toIntArray(readBytes(file, position*4))
    return intFromFile
```

I don't feel like this is how it's supposed to work, but reading the comments on _siftdown I felt like I shouldn't use heapq.heappush() on an empty list, so I changed my code to add the first 5 integers to heapB, call heapify and then carry on with heappush. This didn't resolve the issue. Link to the .bin file is [here](https://anonfiles.com/B8t731ceyf/millionKeys_bin) (hosted on anonfiles)

**Your environment**

- CPython versions tested on: 3.9.2
- Operating system and architecture: Debian x64

**Comment by benjaminp** [comment]
Why is this a problem? For a given set of data, there are often many valid heaps.

**Comment by rhettinger** [comment]
This is long-standing and expected behavior.  The bulk *heapify()* function uses a different algorithm with is ``O(n)``, making it *much* cheaper than repeated calls to *heappush()*.

Thanks for the report, but this is not a bug.
