### ISSUE TITLE
Performance of attribute lookup for type objects

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#92216]
**Bug report**

The performance of attribute lookup for type objects is worse than for other objects. A benchmark
```
import pyperf
runner=pyperf.Runner()

setup="""
class Class:
    def all(self):
        pass

x=Class()
"""

runner.timeit('hasattr x.all', "hasattr(x, 'all')", setup=setup)
runner.timeit('hasattr x.__array_ufunc__', "hasattr(x, '__array_ufunc__')", setup=setup)
runner.timeit('hasattr Class.all', "hasattr(Class, 'all')", setup=setup)
runner.timeit('hasattr Class.__array_ufunc__', "hasattr(Class, '__array_ufunc__')", setup=setup) # worse performance
```
Results:
```
hasattr x.all: Mean +- std dev: 68.1 ns +- 1.1 ns
hasattr x.__array_ufunc__: Mean +- std dev: 40.4 ns +- 0.3 ns
hasattr Class.all: Mean +- std dev: 38.1 ns +- 0.6 ns
hasattr Class.__array_ufunc__: Mean +- std dev: 255 ns +- 2 ns
```

The reason seems to be that the [`type_getattro`](https://github.com/python/cpython/blob/364ed9409269fb321dc4eafdea677c09a4bc0d8d/Objects/typeobject.c#L3902) always executes `PyErr_Format`, wheras for the "normal" attribute lookup this is avoided (see [here](https://github.com/python/cpython/blob/364ed9409269fb321dc4eafdea677c09a4bc0d8d/Objects/object.c#L952) and [here](https://github.com/python/cpython/blob/364ed9409269fb321dc4eafdea677c09a4bc0d8d/Objects/object.c#L1348))

Notes:
* The benchmark is from the python side, but we are working with the C-API
* The performance is important for numpy, see https://github.com/numpy/numpy/pull/21423
* Another location where this is a bottleneck: https://github.com/python/cpython/blob/v3.12.0a2/Lib/dataclasses.py#L1301

**Your environment**

- CPython versions tested on: Python 3.11.0a7+
- Operating system and architecture: Linux Ubuntu

### Linked PRs
* gh-99977
* gh-99979

**Comment by seberg** [comment]
Related to this issue, I am wondering if we can consider `_PyObject_LookupAttr` either as stable (removing the `_`) or as "semi stable"?
Of course that is only faster currently for the default `tp_getattr`, but I suspect that is a huge amount of calls.

**Comment by eendebakpt** [comment]
Also see: https://github.com/python/cpython/issues/76752 (PRs where `_PyObject_LookupAttr` is introduced)

**Comment by serhiy-storchaka** [comment]
`_PyObject_LookupAttr` is an internal API.

I'll look if it is possible to speed up lookup of the absent attribute in a class object.

**Comment by Fidget-Spinner** [comment]
@eendebakpt thanks for the improvement. Can I close this issue now or do you plan to submit more PRs?

**Comment by eendebakpt** [comment]
The issue is solved, i will close
