### ISSUE TITLE
Porting argclinic socket.__init__ from Cinder.

### ISSUE THREAD

**Issue by zitterbewegung** [python/cpython#92210]
**Enhancement of socket.__init__ to use argument clinic**

In cinder this enhancement that is relatively easy involves adding argument clinic to    socket.__init__ . The primary goal will make this much easier to maintain.

**Comment by MojoVampire** [comment]
Coverage of argument clinic is not a goal. As for performance, the overhead of a slightly slower path to calling `socket`'s initializer is trivial relative to the cost of actually opening a socket; optimizing away even 10% of the cost would surprise me, and while that would be worth it if it were truly a super-hot code path, in practice, I doubt even high performance web servers would be spending an appreciable fraction of their time on just creating sockets.

There's nothing wrong with improving the module as a whole to use argument clinic (it's nice to maintain less argument parsing code, while getting speedups for free when argument clinic improves), but the savings available from switching from using `tp_new`/`tp_init` to using a `tp_vectorcall` is mostly just avoiding the creation and parsing of a couple `dict`s; worth it for built-ins that get exercised a lot and are only limited by the CPU, not so much for stuff that gets used less and is typically I/O limited.

**Comment by zitterbewegung** [comment]
Thanks @MojoVampire I have revised my issue from your comment.

**Comment by JelleZijlstra** [comment]
Thanks for your patch!
