### ISSUE TITLE
asyncio.create_task(): Remove obsolete section

### ISSUE THREAD

**Issue by srittau** [python/cpython#92223]
**Documentation**

https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task has a section about an alternative for Python 3.6 and prior. Now that 3.6 has reached end of life, this section is obsolete and hurts conciseness. I propose to remove it.

**Comment by srittau** [comment]
#92224 doesn't get linked automatically.

**Comment by AlexWaygood** [comment]
Now fixed — thanks @srittau!
