### ISSUE TITLE
`test_concurrent_futures` sometimes hangs indefinitely on Windows

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#92222]
**Bug report**

`test_concurrent_futures` appears to be hanging indefinitely on Windows in our CI. This has happened ~~twice~~ three times in two days, on three separate unrelated CI runs.

Two PRs:

- https://github.com/python/cpython/pull/92029#issuecomment-1115340805
- https://github.com/python/cpython/pull/29895: https://github.com/python/cpython/runs/6270908903?check_suite_focus=true

`test_concurrent_futures` has also been running for 4hr30 (and counting) on Windows (x86) on this recent push to `main`:

- https://github.com/python/cpython/commit/9b027d4cea57e98c76f5176cc3188dc81603356c: https://github.com/python/cpython/runs/6269422000?check_suite_focus=true

Neither PR had anything to do with `concurrent.futures` (and the push to `main` didn't have anything to do with `concurrent.futures` either). For the first PR, `test_concurrent_futures` was hanging on Windows (x64) but passed on Windows (x86). For the second PR, the test has passed on Windows (x64) but is hanging on Windows (x86).

cc. @pitrou, @brianquinlan, as listed experts for `concurrent.futures`.

**Comment by AlexWaygood** [comment]
I've run `python -m test test_concurrent_futures -v` five times in succession on my Windows machine, but I'm struggling to reproduce this behaviour locally.

**Comment by AlexWaygood** [comment]
The most recent significant change to `concurrent.futures` was #31408, merged by @JelleZijlstra. The most recent significant change to `test_concurrent_futures` was #91600, by @gpshead.

**Comment by gpshead** [comment]
fwiw my change to the test removed this logic that put a 0.1 second delay at the start of most every test (this is already one of the longest running tests in our suite), which was added over a decade ago without explanation and doesn't make logical sense:

```python
    def _prime_executor(self):
        # Make sure that the executor is ready to do work before running the
        # tests. This should reduce the probability of timeouts in the tests.
        futures = [self.executor.submit(time.sleep, 0.1)
                   for _ in range(self.worker_count)]
        for f in futures:
            f.result()
```

The only thing code like that can do is hope to work around a logical flaw in tests or hide an actual race condition bug. so if there _is_ a logic flaw or race condition somewhere... we'd be best off finding it as the real fix.

So far I've not observed timeout failures, but if anyone can reproduce them it'd be great to get a snapshot of what processes were stuck running and hanging on what so we can understand the root of the issue.

**Comment by pitrou** [comment]
> So far I've not observed timeout failures, but if anyone can reproduce them it'd be great to get a snapshot of what processes were stuck running and hanging on what so we can understand the root of the issue.

If nothing bad happens on the buildbots then great :-)

**Comment by AlexWaygood** [comment]
I opened this issue because I saw the same CI failure three times in two days. I haven't seen it since, though, and haven't been able to reproduce it locally, so I'll close this for now. If it happens again, I'll reopen.

**Comment by neonene** [comment]
I saw this issue on 3.11 branch Windows (x64):
https://github.com/python/cpython/runs/6939506633?check_suite_focus=true

**Comment by neonene** [comment]
I am not able to reproduce locally as well. Would it be possible to inject something that shows what test case is still running or got canceled?
