### ISSUE TITLE
Spurious LINE event when tracing `asyncio.tasks.sleep`

### ISSUE THREAD

**Issue by markshannon** [python/cpython#92236]
See https://github.com/nedbat/coveragepy/pull/1368#issuecomment-1116098613 for report.

Although this occurs in `asyncio.tasks.sleep` I suspect that this this is more generally related to entering coroutines and generators.

**Comment by markshannon** [comment]
Reproducer:
https://github.com/nedbat/coveragepy/pull/1368#issuecomment-1116451224

**Comment by nedbat** [comment]
Is there any chance of this being addressed in time for 3.11b1?

**Comment by MSJemprededor** [comment]
> See https://github.com/nedbat/coveragepy/pull/1368#issuecomment-1116098613 for report.
> 
> Although this occurs in `asyncio.tasks.sleep` I suspect that this this is more generally related to entering coroutines and generators.
> 

Boa noite

**Comment by markshannon** [comment]
Sorry, I was unable to reproduce this, so I couldn't make for a test for it nor fix it.

I think I know what the issue is now.
There is a spurious `LINE` event before the call, but pure Python tracing ignores `LINE` events that occur before the `CALL` event because `f_trace` is unset until set by the global trace function.
C tracing functions see this `LINE` event.

**Comment by nedbat** [comment]
Where does this leave us? Is this something that will change in CPython, or does coverage.py need to adapt?

**Comment by markshannon** [comment]
I'm fixing it. It just didn't make it into 3.11b1, obviously. It will be in 3.11b2

**Comment by markshannon** [comment]
https://github.com/python/cpython/pull/92722

**Comment by nedbat** [comment]
It's my only CPython expertise! Happy to help :)
