### ISSUE TITLE
`ctypes.cdll.LoadLibrary` on Cocoa library causes Python dock icon to appear unnecessarily

### ISSUE THREAD

**Issue by alexreg** [python/cpython#92235]
**Bug report**

An easy way to see this is to use the `enchant_applespell.so` provider from [*enchant*](https://github.com/AbiWord/enchant). The *pyenchant* library does exactly this.

Note: you can install *enchant* easily on macOS using Homebrew.

Then to reproduce the issue, run the following.

```python
import ctypes
e = ctypes.cdll.LoadLibrary("/opt/homebrew/Cellar/enchant/2.3.3/lib/enchant-2/enchant_applespell.so")
e.enchant_broker_init()
```

The Python icon then appears in the macOS Dock. This seems to be caused by the `enchant_broker_init` function, which initialises some Cocoa stuff.

Of course, it's quite unnecessary and a nuisance for a Python dock icon to appear. Indeed, no dock icon of any sort appears if this library is loaded by native code (and the `enchant_broker_init` function called).

**Your environment**

- CPython versions tested on: 3.9.12
- Operating system and architecture: macOS 12.3.1, arm64 (M1 chip)

**Comment by ronaldoussoren** [comment]
Which libraries is the dynamic library linked to? You can see this using ``otool -vL ..../enchant_applespell.so``.

AFAIK most installations of Python on macOS use a framework install, in which we arrange that the python interpreter is part of an application bundle (mostly to be able to use GUI libraries), that may cause an Python dock item to appear when an extension uses an Apple framework that assumes that it's part of an application.

**Comment by alexreg** [comment]
@ronaldoussoren Thanks for the explanation. I'm using the Homebrew installation of Python 3.9. (Is there any way to run python outside of an application bundle, in this case?)

Anyway, here's the output of `otool -vL ...`.

```
/opt/homebrew/Cellar/enchant/2.3.3/lib/enchant-2/enchant_applespell.so:
	/opt/homebrew/opt/glib/lib/libgmodule-2.0.0.dylib (compatibility version 7201.0.0, current version 7201.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/opt/homebrew/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 7201.0.0, current version 7201.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/opt/homebrew/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/opt/homebrew/Cellar/enchant/2.3.3/lib/libenchant-2.2.dylib (compatibility version 6.0.0, current version 6.3.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/opt/homebrew/opt/aspell/lib/libaspell.15.dylib (compatibility version 19.0.0, current version 19.1.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2113.40.126)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1858.112.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
```

**Comment by ronaldoussoren** [comment]
I've looked at the enchant source code and that conforms my theory of what's happining here. A simple way to reproduce using PyObjC:

```python
import AppKit
AppKit.NSSpellChecker.sharedSpellChecker()

import time
time.sleep(10)
```

This will also cause a bouncing icon in the dock.  There's nothing we can do about this without breaking other use cases (in particular, dropping the embedded Python.app would break command-line script that show a GUI).

With a framework build you can generally run the interpreter outside of an app by copying ``f"{sys.prefix}/Resources/Python.app/Contents/MacOS/Python"`` to a temporary location and run that, and for virtual environments replace the ``python3.X`` symlink by this executable. For the Python.org installer you'll also have strip the code signature, otherwise signature verification doesn't work and the interpreter crashes at startup.

**Comment by alexreg** [comment]
@ronaldoussoren Thanks for investigating, but it seems the issue is not quite that, unless something strange is going on here. On a macOS Homberew, `python3` points to `/opt/homebrew/Frameworks/Python.framework/Versions/3.9/bin/python3.9`.

Neither running that binary directly, nor your trick of copying that python executable to a temporary location, works. (The Python dock icon still displays.)

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren Thanks for investigating, but it seems the issue is not quite that, unless something strange is going on here. On a macOS Homberew, `python3` points to ```/bin/python3.9`.
> 
> Neither running that binary directly, nor your trick of copying that python executable to a temporary location, works. (The Python dock icon still displays.)

Given the path you mention homebrew does use a framework build, with an embedded Python.app. There should be a ``/opt/homebrew/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python`` as well, which is the "real" interpreter.

With a framework build ``f"{sys.prefix}/bin/python3"`` is a small stub executable that just launches the interpreter in the embedded app. That way the file structure in ``sys.prefix`` is the one expected on unix-y platforms.

**Comment by alexreg** [comment]
@ronaldoussoren Thank you for clarifying. That is indeed the case.
