### ISSUE TITLE
"What’s New In Python 3.X" does not include the release date for 3.0, 3.2, 3.8 and 3.10

### ISSUE THREAD

**Issue by MojoVampire** [python/cpython#92240]
**Documentation**

The What's New In Python 3.X docs for 3.1, 3.3-3.7 and 3.9 all include the initial release date in their first paragraph, which is handy to include for historical/reference purposes. The docs for 3.0, 3.2, 3.8 and 3.10 do not. Any chance the release date could be added to those four What's New docs (and included in future What's New docs), following the rough pattern seen in the other six:

> This article explains the new features in Python 3.X, compared to 3.X-1. Python 3.X was released on Monthname DD, YYYY.  See the changelog for a full list of changes.

with some adjustment needed for 3.0 (where the initial paragraph is an introduction to Python 3 as well, and much more verbose).

**Comment by Sumanth077** [comment]
Hello @MojoVampire Can I contribute to this?

**Comment by arhadthedev** [comment]
@Sumanth077 It's an open repository so there is no need to ask.

However, waiting time may be between a day and a month. That's because other contributors need a chance to participate and maybe give a feedback before the PR gets merged.

**Comment by Sumanth077** [comment]
Thank you @arhadthedev for your reply, can you kindly mention the links to that documentation here.

**Comment by georgically** [comment]
PR made for Release dates for "What's New in Python 3.X" for 3.0, 3.1, 3.2, 3.8 and 3.10 added. Note: @Sumanth077
