### ISSUE TITLE
Last iterators tutorial example is limited and limitation isn't mentioned

### ISSUE THREAD

**Issue by blmatthews** [python/cpython#92252]
**Documentation**

In section [9.8 Iterators of the tutorial](https://docs.python.org/3/tutorial/classes.html#iterators), the last example is of a class that is an iterator over itself "If the class defines \_\_next\_\_(), then \_\_iter\_\_() can just return self:" While that certainly works, it means that, unlike with things like strings and arrays, there can't be multiple independent iterators over an instance of the example `Reverse` class. That seems worth mentioning, if not as an anti-pattern, at least as something worth noting.

**Comment by rhettinger** [comment]
> there can't be multiple independent iterators

The example looks correct to me. Possibly, you may be conflating "iterator" with "iterable" which as distinguished in the glossary.You can in fact have multiple independent iterators.

```
>>> s = 'cat'
>>> it1 = reversed(s)
>>> it2 = reversed(s)
>>> next(it1)
't'
>>> next(it1)
'a'
>>> next(it2)
't'
>>> next(it1)
'c'
next(it2)
'a'


```

**Comment by blmatthews** [comment]
There can't be multiple independent iterators *over an instance of the example `Reverse` class*:

```
>>> rev = Reverse('cat')
>>> it1 = iter(rev)
>>> it2 = iter(rev)
>>> next(it1)
't'
>>> next(it1)
'a'
>>> next(it2)
'c'
>>> next(it1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 10, in __next__
StopIteration
```

(where `Reverse` is the class in the example in the tutorial). As you say, you can have multiple independent iterators over things like strings and arrays, so it seems like an example where that's not the case should at least mention it's not the case.

**Comment by rhettinger** [comment]
Sorry, I'm going to close this one.  AFAICT the report reflects a basic misunderstanding of the difference between an *iterable* and an *iterator*.   Many tools like *reversed()*, *enumerate()*, *zip()*, *filter()*, any of the itertools and generator instances all return an iterator.

Iterators always have an \__iter__ method that returns self.  This is a core feature that allows us to run a for-loop over a partially consumed iterator.
