### ISSUE TITLE
Trying to iterate over typing.Union results in hang

### ISSUE THREAD

**Issue by mrahtz** [python/cpython#92261]
If you accidentally iterate over a `Union`, you get a hang:

```python
from typing import Union
list(Union)
# ...hang
```

It looks like it's an infinite loop:

```python
from typing import Union
for i in Union:
    print(i)
# 0, 1, 2, ...
```

As far as I can tell, this happens because `typing.Union` is implemented using `typing._SpecialForm`, and `_SpecialForm` is implemented using `__getitem__` to support parameterisation like `Union[int]`. Unfortunately, because `_SpecialForm` doesn't implement `__iter__`, `__getitem__` is also used for iteration - meaning that when trying to iterate, we effectively do `Union[0]`, `Union[1]`, etc.

**Comment by JelleZijlstra** [comment]
We should deprecate `itertools.count` because it's now redundant.

More seriously, agree that we should disallow this.

**Comment by mrahtz** [comment]
Fixed in https://github.com/python/cpython/commit/4739997e141c4c84bd2241d4d887c3c658d92700.
