### ISSUE TITLE
MacOS build-installer.py script failing when building docs - cannot import name 'environmentfilter' from 'jinja2'

### ISSUE THREAD

**Issue by lmbelo** [python/cpython#92263]
**Bug report**

MacOS build-installer.py script failing when building docs.

**Error**

cannot import name 'environmentfilter' from 'jinja2'

**Details**
Sphinx-3.2.1 has a dependency with Jinja (Requires-Dist: Jinja2 (>=2.3)). In the latest Jinja version the environmentfilter module isn't able to be imported, beginning with the 3.1.0 update.

More info: https://github.com/pallets/jinja/issues/1630

**Your environment**

CPython versions tested on: 3.10.4
Operating system and architecture: MacOS M1

**Comment by lmbelo** [comment]
There is something already running around this issue:

https://github.com/python/cpython/issues/91294

**Comment by slateny** [comment]
Thanks for linking the issue - looks like it's been resolved over there so I'll close this too, but feel free to reopen if it's still an issue.
