### ISSUE TITLE
`sphinx-lint` now ignores default roles in docs' `make check`

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#92289]
We have a GitHub workflow for documentation that runs `make check`:
https://github.com/python/cpython/blob/7d7a378c1a351a2074e9e46838718a2dcbef2948/.github/workflows/doc.yml#L43-L44

`make check` runs 
https://github.com/python/cpython/blob/7d7a378c1a351a2074e9e46838718a2dcbef2948/Doc/Makefile#L215-L217

By default `sphinx-lint` only reports errors with a severity `>=1`:
https://github.com/sphinx-contrib/sphinx-lint/blob/b25d09c5a0cf15030c575d18078d815724a1e3e0/sphinxlint.py#L453-L459

The severity of the "default role" check (i.e. making sure that no single `` `...` `` are used), was recently changed to `severity=0` in https://github.com/sphinx-contrib/sphinx-lint/commit/999b43d52e98c117eeea9a5bad2728bb2808b092.

This means that the use of the default role is no longer caught as an error by `make check`.

See also #86404.

 (Thanks to @AlexWaygood for noticing the issue. cc @JulienPalard)

**Comment by erlend-aasland** [comment]
Did you land all the backports; can we close this?

**Comment by ezio-melotti** [comment]
Yes, I ported it to 3.11 in https://github.com/python/cpython/pull/92821 and previous versions were not affected since they used `Tools/rstlint.py`.
