### ISSUE TITLE
Better emphasise pending removals in What's New

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#92308]
As per discussion on [Discourse](https://discuss.python.org/t/proposal-pending-removal-category-in-whats-new/15470?u=erlendaasland).

Suggesting to add a **Pending Removal** category in What's New, to better communicate this information to users.

**Comment by ezio-melotti** [comment]
I merged the PR for the beta, however I'm reopening this since there were ongoing discussions and we want to go through more iterations before the final release.

**Comment by erlend-aasland** [comment]
Thanks, Ezio!

**Comment by vstinner** [comment]
For 3.12, see: https://github.com/python/cpython/pull/92562

**Comment by vstinner** [comment]
It seems like it's done, I close the issue ;-)

**Comment by erlend-aasland** [comment]
Thanks, everyone, for taking care of this! :)

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/93986 to add more.
