### ISSUE TITLE
Improve error message for list.remove

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#92305]
`list.remove` does not contains the ``repr`` of the object being removed from the list which is unhelpful. Proposed changes improves it from
Current:
```console 
>>> a = [1,2]
>>> a.remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: list.remove(x): x not in list
```
Proposed:
```console 
>>> a = [1,2]
>>> a.remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 3 is not in list
```

**Comment by ericvsmith** [comment]
It looks like the change is to include "list.remove", but remove the value being removed?

The current message similar to, for example:
```python
>>> {}.pop(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 1
```

Is there anywhere else where we include the method name in an error?

**Comment by kumaraditya303** [comment]
There was a copy and paste error in the issue comment, fixed now.

**Comment by ericvsmith** [comment]
Ah. That does look like an improvement. My only concern is listing the concrete type `list`, which wouldn't be true for a subclass. But I guess the message already has that problem:

```python
>>> class X(list): pass
...
>>> X().remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: list.remove(x): x not in list
```

**Comment by serhiy-storchaka** [comment]
This is a duplicate of #48760.

**Comment by serhiy-storchaka** [comment]
And #74039.

**Comment by serhiy-storchaka** [comment]
And #57558.
