### ISSUE TITLE
python lstrip does not work as intended when '-' is present.

### ISSUE THREAD

**Issue by hiraditya** [python/cpython#92315]
**Bug report**

```py
$ python3
Python 3.8.12 (default, Oct 13 2021, 06:42:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s1 = 'asdf-alpha_dec.o'
>>> s1 = s1.lstrip('asdf-')
>>> s1
'lpha_dec.o'
>>> 

```

**Your environment**

- CPython versions tested on:
$ python3 --version
Python 3.8.12

- Operating system and architecture:
MacOS 12.3.1 (21E258)
MacBook Pro (16-inch, 2019)
2.4 GHz 8-Core Intel Core i9
64 GB 2667 MHz DDR4

**Comment by hiraditya** [comment]
Even an online python compiler shows the same error: https://www.online-python.com/NG875E1HIy

**Comment by zware** [comment]
This is not a bug; [`lstrip`](https://docs.python.org/3/library/stdtypes.html#str.lstrip) behaves differently from [`removeprefix`](https://docs.python.org/3/library/stdtypes.html#str.removeprefix), which was added in 3.9.

**Comment by hiraditya** [comment]
Thanks for clarifying!
