### ISSUE TITLE
Corner case NaN comparison

### ISSUE THREAD

**Issue by facelessuser** [python/cpython#92313]
**Bug report**

Normally, NaN will evaluate as `False` when compared against each other, but there is a case where this breaks down. The NaN values have to be the same instance, and then they have to be wrapped in a sequence. In this very specific case, the two NaN values will actually be compared as equal.

```py
>>> a = float('nan')
>>> b = a
>>> a == b
False
>>> [a] == [b]
True
```

As to exactly why this occurs, I am uncertain. The same scenario does not evaluate `True` if the Nan value is of two separate instances:

```py
>>> a = float('nan')
>>> b = float('nan')
>>> a == b
False
>>> [a] == [b]
False
```

**Your environment**

- CPython versions tested on: Python 3.10.4
- Operating system and architecture: macOS Montery 12.3.1

I should note that I had this bug in CI running on other systems and Python versions as well, it seems to be a quirk that has existed through multiple Python versions for at least as far back as Python 3.6, but likey longer than that.

**Comment by ericvsmith** [comment]
This is because list comparisons use identity comparisons before equality comparisons. See https://stackoverflow.com/questions/20320022/why-in-numpy-nan-nan-is-false-while-nan-in-nan-is-true, for example.

**Comment by facelessuser** [comment]
> This is because list comparisons use identity comparisons before equality comparisons. See https://stackoverflow.com/questions/20320022/why-in-numpy-nan-nan-is-false-while-nan-in-nan-is-true, for example.

This feels like a different case `in` vs `==`. I could understand `in` returning `True`, but `==` is harder to swallow, though it is likely you are correct about the underlying comparison, even if this seems counterintuitive.

Is this just an accepted case in Python even though it doesn't make sense?

**Comment by ericvsmith** [comment]
> This feels like a different case `in` vs `==`.

I probably sent the wrong link, but the logic is: list comparisons use element-wise `is`, and if that is false, use `==`.

> Is this just an accepted case in Python even though it doesn't make sense?

Yes.

**Comment by rhettinger** [comment]
Yes, this was intended (and documented and tested).  This is the only way that containers can maintain their invariants.

**Comment by facelessuser** [comment]
@rhettinger, it may be tested, but where is it documented?

**Comment by stevendaprano** [comment]
[Built in equality for sequences](https://docs.python.org/3/reference/expressions.html#value-comparisons) says:

"Sequences compare lexicographically using comparison of corresponding elements. The built-in containers typically assume **identical objects are equal to themselves**. That lets them bypass equality tests for identical objects to improve performance and to maintain their internal invariants."

(Emphasis added.)

**Comment by stevendaprano** [comment]
Oh, and same applies for mappings (dict): "Equality comparison of the keys and values enforces reflexivity." (Same link as above.)

**Comment by facelessuser** [comment]
Oh, so NaN behavior is kind of inferred in the docs, not specifically spelled out. You kind of have to fully understand the comparison methodology of lists (and dicts) and then make the mental link about NaNs when you run into the issue 🙃.

Well, either way, I now understand that this quirky behavior is an accepted issue. I personally think it would make sense to spell it out under NaNs as It seems I'm not the only one to discover this odd behavior and not be able to make this connection. Regardless, I'm satisfied with the explanation.

**Comment by stevendaprano** [comment]
I would not object if you wanted to propose a documentation enhancement 

regarding the behaviour of NANs in collections.
