### ISSUE TITLE
FindPythonForBuild (PCBuild) fails with a path that contains a space

### ISSUE THREAD

**Issue by ariccio** [python/cpython#92348]
**Bug report**
I discovered this while playing around building with VS 2022 (I know it's not supported yet).

[`FindPythonForBuild`](https://github.com/python/cpython/blob/8122e8d5017be9f0683a49bc20d3c82e8b5398d6/PCbuild/pyproject.props#L231) tries to execute a batch file (`find_python.bat`) and builds the path as such:
```
$(MSBuildThisFileDirectory)\find_python.bat
```

If you clone the CPython repo into a user profile Documents directory (as is the default for the GitHub frontend for windows), and your user profile contains a space, this script fails.

Locally changing the line to [add encoded quotes like this](https://stackoverflow.com/a/2414096/625687) works for me:
```
<Exec Command="&quot;$(MSBuildThisFileDirectory)\find_python.bat&quot; -q"
```

You could probably repro this by cloning into any directory with a space in the path.

**Your environment**

- CPython versions tested on: latest main HEAD
- Operating system and architecture: Windows 10
- Visual Studio 2022
- User profile name: `Lucius Riccio` (yes, I still have a hand-me-down :))

CC @zooba since I think he still owns this code? It looks like the PSF has moved to GitHub for issue tracking, it will take a few minutes for me to reconfigure everything locally to fork this properly if you want me to submit a one-line patch.

**Comment by zooba** [comment]
(There's no point tagging me directly - it only creates even more noise and I'm less likely to notice it. Just let the OS-windows tag do its job.)

That change looks fine. You can do it through GitHub's web UI easily enough if you don't want to fork locally. The CI build should be sufficient testing.

**Comment by ariccio** [comment]
Ah! Very sorry. Didn't realize that's how you guys do that here! That makes sense, will do in the future!

Do I need to do that thing with a "news" note or can I just make the change in the web UI?

**Comment by zooba** [comment]
Nah, this doesn't require a NEWS entry. We'll set the tag that suppresses the check once the PR is there.
