### ISSUE TITLE
Speed up Condition.notify()

### ISSUE THREAD

**Issue by dgiger42** [python/cpython#92352]
**Feature or enhancement**

I think `threading.Condition.notify()` could be sped up by avoiding some unnecessary work.  `Condition.notify()` creates a `_deque` every time it is called, and it seems like this step can be eliminated.  This should speed up `notify()` without sacrificing readability.  The for loop at the end of the function would most likely need to be slightly tweaked to accommodate this change.

**Pitch**

This change should speed up `Condition.notify()`, which would also speed up operations on `queue.Queue`, since the `Queue` class uses `Condition` objects extensively.  The speedup for `Queue` could be significant, because `Queue` appears to spend a significant portion of it's time in `notify()` (or at least it did when I profiled a simple program that was using `Queue`).

If I'm right that this can be sped up significantly without sacrificing readability, should I make a PR for it?

**Comment by JelleZijlstra** [comment]
Performance improvements are welcome! If you can, would be great to also post a microbenchmark showing how much you improve performance.

This chance would probably make it only into Python 3.12, since 3.11 is going into feature freeze tomorrow.

**Comment by serhiy-storchaka** [comment]
The fix for #92530 includes changes equivalent to the proposed optimization.

Anyway, thank you @danielg1111 for your PR and for attracting attention to this code.
