### ISSUE TITLE
Make the slotted missing attribute AttributeError's message the same as the slotless one

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#92355]
**Feature or enhancement**

Make both AttributeErrors the same.
I'm not 100% sure whether this is a bug report or a feature request.

**Pitch**

For the next example classes, the behavior of `X().slot` is slightly different :
```py
class A:
    pass

class B:
    __slots__ = "slot"

class C:
    __slots__ = ()
```
`A().slot` and `C().slot` will raise `AttributeError: 'A' object has no attribute 'slot'`.
However, `B().slot` will raise `AttributeError: slot`.
The supplementary information (although limited) from the first message should be included in the second one as well. And I think it's a mistake to make a slotted missing attribute and an unslotted one behave differently, for arguable visibility reasons.

**Comment by hauntsaninja** [comment]
Thanks, I believe this is the case with Python 3.11
```
λ python3.11           
Python 3.11.1 (main, Jan  1 2023, 00:40:19) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class B:
...     __slots__ = "slot"
... 
>>> B().slot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'B' object has no attribute 'slot'
```
