### ISSUE TITLE
Missing possessive apostrophe

### ISSUE THREAD

**Issue by pfurbacher** [python/cpython#92368]
In the section, [Batteries Included](https://docs.python.org/3/tutorial/stdlib.html#batteries-included) the possessive apostrophe in the following is missing: 

> Despite the modules names, . . . .

Two modules are mentioned in the previous sentence; the snippet is referring to their names. Therefore, it should read: 

> Despite the modules' names, . . . .

**Comment by gophra** [comment]
I am will try to create pull request tomorrow

**Comment by ezio-melotti** [comment]
Fixed, thanks @pfurbacher for the report and @gophra for the PR (nice avatar btw :).
