### ISSUE TITLE
`csv.DictReader` and `DictWriter` not subscriptable at runtime

### ISSUE THREAD

**Issue by cdce8p** [python/cpython#92391]
**Feature or enhancement**

Add PEP 585 style `__class_getitem__` to `csv.DictReader` and `csv.DictWriter`.

**Pitch**

With PEP 585 most generic stdlib types are now subscriptable at runtime. Both [DictReader](https://github.com/python/typeshed/blob/46fc7768c4df6f713e81a0078e72b9805679c25f/stdlib/csv.pyi#L75) and [DictWriter](https://github.com/python/typeshed/blob/46fc7768c4df6f713e81a0078e72b9805679c25f/stdlib/csv.pyi#L107) are generic in typeshed but don't yet implement `__class_getitem__`.

```py
from csv import DictWriter
from typing import IO

def f(fp: IO[str]) -> DictWriter[str]:
    return DictWriter(fp, ["id", "name"])
```

**Previous discussion**
* #19423
* https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

**Comment by serhiy-storchaka** [comment]
Why are they generic in typeshed?

**Comment by AlexWaygood** [comment]
> Why are they generic in typeshed?

[`DictReader`](https://github.com/python/typeshed/blob/4e946b74bf18dc932caf41d0257957d85bbabe91/stdlib/csv.pyi#L79-L109) has been generic for a while. [`DictWriter`](https://github.com/python/typeshed/blob/4e946b74bf18dc932caf41d0257957d85bbabe91/stdlib/csv.pyi#L111-L132) was made generic in https://github.com/python/typeshed/pull/5366.

The classes are slightly complicated to type, so I am not sure the stubs are 100% correct at the moment (I have a [PR open at the moment](https://github.com/python/typeshed/pull/7788) to improve them). But I think it is correct that they are both generic. Copying what I wrote in https://github.com/python/typeshed/issues/7787#issuecomment-1119544366:

> `DictReader` seems pretty clearly like it should be generic -- the type that's returned from `DictReader.__next__` depends very clearly on the type that you stick into `DictReader.__init__`.
> 
> In fact, `DictReader` seems like it could possibly be typed more correctly if it took another parameter: see https://github.com/python/typeshed/pull/5994#issuecomment-911917345. (But that's irrelevant to the runtime; adding `__class_getitem__` will allow it to take any number of parameters at runtime.)
> 
> I was confused about the implicit conversion to string in `DictWriter`, which made me wonder if `DictWriter` should be generic. But `DictWriter` [does some runtime typechecking](https://github.com/python/cpython/blob/15dbe8570f215bfb4910cdd79b43dafb2ab6b38f/Lib/csv.py#L145-L151) in the `_dict_to_list` method before it does the implicit conversion to string. So I think it makes sense for `DictWriter` to be generic as well (as it is in the stub currently).

**Comment by serhiy-storchaka** [comment]
I am not sure that they were designed this way. Why not return just `dict[Any, Any]` in `DictReader.__next__`? The type of the result depends not only on the type of field names (which can have different types), but on types and values of other parameters and on the content of the file.

**Comment by AlexWaygood** [comment]
> The type of the result depends not only on the type of field names... but on types and values of other parameters and on the content of the file.

Can you give an example? If the stubs are incorrect, I would be interested in improving them.

**Comment by serhiy-storchaka** [comment]
The type of keys: the type of any item in `fieldnames` (`str | float` if `fieldnames` is None), or the type of `restkey`.
The type of values: `str | float`, `list[str|float]`, or the type of `restval`.
