### ISSUE TITLE
Clarification requested for library/syslog.rst

### ISSUE THREAD

**Issue by Gaasmann** [python/cpython#92412]
Hello,
While translating `library/syslog.rst` we've realized that the comment "Changed in 3.2" for `syslog.openlog()` seems ambiguous:
https://docs.python.org/3/library/syslog.html#syslog.openlog
> In previous versions, keyword arguments were not allowed, and *ident* was
      required.  The default for *ident* was dependent on the system libraries,
      and often was ``python`` instead of the name of the Python program file.

As *ident* was required before 3.2, it couldn't have a default value, so the sentence seems contradictory.
The documentation for 3.1 shows that *ident* is mandatory and the tests on the 3.1.5 distribution always define *ident* when calling `openlog()`.

Could someone help us understand the meaning of this sentence?

Thanks

**Comment by hauntsaninja** [comment]
I think this makes a little bit more sense in the context of the 3.1 docs (https://docs.python.org/3.1/library/syslog.html#syslog.openlog ):

> Logging options other than the defaults can be set by explicitly opening the log file with [openlog()](https://docs.python.org/3.1/library/syslog.html#syslog.openlog) prior to calling [syslog()](https://docs.python.org/3.1/library/syslog.html#syslog.syslog). The defaults are (usually) ident = 'syslog', logopt = 0, facility = LOG_USER.

So the defaults are what you get when you use syslog without openlog. But take it with a grain of salt, I don't really understand the code, in particular, I don't understand the claim in 3.1's docs that `ident` usually equalled `syslog`

Some more links:
https://github.com/python/cpython/commit/13daf12b47f628a77dbd174a43dc72ed32f00b5b
https://bugs.python.org/issue8451
https://mail.python.org/pipermail/python-dev/2010-March/098500.html

**Comment by Gaasmann** [comment]
Yes, that sounds right. Like you, I don't get the claim you mentioned.

From what I see,
- before the patch syslog.openlog fails and the C's openlog isn't called
- after the patch C's openlog is called with ident = NULL. 
 
In both cases, it seems the decision for what to use for ident is up to the syslog implementation (the man page on Debian says that POSIX.1-2008 does not specify the behavior when ident is NULL.)

So, most of the time, it seems that syslog uses C's `basename(argv[0])` but maybe some systems would behave differently and use `syslog` for *ident*?

In any case, even with the patch, it seems that the syslog implementation would decide the ident's value if `sys.argv[0] == ''`

If what I said above is right, I would remove the second line of the "Changed in 3.2" as it could still be true:
>  The default for ident was dependent on the system libraries, and often was python instead of the name of the Python program file.
