### ISSUE TITLE
Many references to unsupported Python versions in the stdlib docs

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#92417]
**Documentation**

There are currently many places in the stdlib docs where there are needless comments about how to maintain compatibility with Python versions that are now end-of-life. Many of these can now be removed, to improve brevity and clarity in the documentation.

I plan to submit a number of PRs to fix these.

PRs:
 
- #92418 
- #92419 
- #92420 
- #92421 
- #92422 
- #92423 
- #92424 
- #92425
- https://github.com/python/cpython/pull/92502
- #92538
- #92539
- #92543
- #92544
- [More to come]

Backports:
- https://github.com/python/cpython/pull/92459
- https://github.com/python/cpython/pull/92460
- https://github.com/python/cpython/pull/92461
- https://github.com/python/cpython/pull/92462
- https://github.com/python/cpython/pull/92463
- https://github.com/python/cpython/pull/92491
- https://github.com/python/cpython/pull/92467
- https://github.com/python/cpython/pull/92468
- https://github.com/python/cpython/pull/92492
- https://github.com/python/cpython/pull/92464
- https://github.com/python/cpython/pull/92465
- https://github.com/python/cpython/pull/92466
- https://github.com/python/cpython/pull/92472
- https://github.com/python/cpython/pull/92473
- https://github.com/python/cpython/pull/92474
- https://github.com/python/cpython/pull/92485
- https://github.com/python/cpython/pull/92486
- https://github.com/python/cpython/pull/92487
- https://github.com/python/cpython/pull/92606
- https://github.com/python/cpython/pull/92607

**Comment by CAM-Gerlach** [comment]
Might want to add #92502 to the list in the OP

**Comment by AlexWaygood** [comment]
> Might want to add #92502 to the list in the OP

Done.

**Comment by ambv** [comment]
I merged everything that was linked here. If all's done, this can be closed.

**Comment by AlexWaygood** [comment]
This is basically done at this point, and I ran out of energy to finish the remaining bits that are left to do.
