### ISSUE TITLE
Possible loss of data warnings when building 32bit executable since 3.11

### ISSUE THREAD

**Issue by neonene** [python/cpython#92434]
Windows (x86) buildbot shows two warnings on main branch:

- [x]  `channel_list_all()` in _xxsubinterpretersmodule.c, using `PyList_SET_ITEM()` function
```
D:\a\cpython\cpython\Modules\_xxsubinterpretersmodule.c(2341,9): warning C4244:
'function': conversion from 'int64_t' to 'Py_ssize_t', possible loss of data
```
<br>

- [x]  `serialize_impl()` in _sqlite/connection.c
```
D:\a\cpython\cpython\Modules\_sqlite\connection.c(2122,53): warning C4244:
'function': conversion from 'sqlite3_int64' to 'Py_ssize_t', possible loss of data
```
<br>

I'm not sure how to deal with them.

**Comment by erlend-aasland** [comment]
Fixed with the following PRs:

- #93091
- #93090 
- #93672

**Comment by neonene** [comment]
For the record, there is a slight possibility that `_sqlite/connection.c` is just silenced.
I won't open an issue without a reproducer.
