### ISSUE TITLE
Incorrect footnotes at https://docs.python.org/3/c-api/exceptions.html#standard-exceptions

### ISSUE THREAD

**Issue by anntzer** [python/cpython#92431]
**Documentation**

As of Python 3.10.4, the "Standard Exceptions" table has the following entries with footnotes:
- PyExc_ReferenceError : ReferenceError : (2)
- PyExc_WindowsError : (alias for PyExc_OSError) : (3)

but there is no footnote 3 and footnote 2 reads
"Only defined on Windows; protect code that uses this by testing that the preprocessor macro MS_WINDOWS is defined."

(As a related side point, the documentation for PyErr_SetFromWindowsErr (on the same page) refers to WindowsError and PyExc_WindowsError, but perhaps these should be updated to OSError and PyExc_OSError instead.)

**Comment by hugovk** [comment]
Footnotes in [3.10](https://docs.python.org/3.10/c-api/exceptions.html#standard-exceptions):

> 1. This is a base class for other standard exceptions.
> 2. Only defined on Windows; protect code that uses this by testing that the preprocessor macro `MS_WINDOWS` is defined.


Footnote 3 last seen in [3.6](https://docs.python.org/3.6/c-api/exceptions.html#standard-exceptions):

> 1. This is a base class for other standard exceptions.
> 2. This is the same as [weakref.ReferenceError](https://docs.python.org/3.6/library/weakref.html#weakref.ReferenceError).
> 3. Only defined on Windows; protect code that uses this by testing that the preprocessor macro `MS_WINDOWS` is defined.

And footnote 2 was deleted in https://github.com/python/cpython/pull/18452.

**Comment by hugovk** [comment]
Thanks for the report, please see PR https://github.com/python/cpython/pull/92432.
