### ISSUE TITLE
self-circular import when running as a script

### ISSUE THREAD

**Issue by CastixGitHub** [python/cpython#92435]
**Bug report**
I consider idiomatic to create modules within a package corresponding to installed dependencies, this is probably better explained by an example.

assume the following structure for an application that has two options for the ui:
```
.
└── pyabs
    ├── core.py
    ├── curses.py
    └── tk.py
```
assume you launch the application with `python pyabs/curses.py`

and the first line of `curses.py` is `import curses`

You would get a circuar import, as the module would try to import itself.

If you check `sys.path` the first entry is the `pyabs` directory where the module resides. because of how it was launched.

I am wondering if this case is special enough to be handled differently, and if can this be considered a bug

- CPython versions tested on: 3.9.11

Thanks

**Comment by JelleZijlstra** [comment]
This is documented and established behavior. You can work around it by using `python -m pyabs.curses`, and in 3.11 you'll be able to use the `-P` option to avoid adding the CWD to `sys.path`. We won't change this behavior in bugfix releases, so I don't think there's anything else to do.
