### ISSUE TITLE
print converts to string object automatically, but write to file doesn't and additional function needs to be called (on prettytable)

### ISSUE THREAD

**Issue by ghost** [python/cpython#92437]
pepe@pepe-MS-7C90:~$ python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import prettytable
>>> x = PrettyTable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PrettyTable' is not defined. Did you mean: 'prettytable'?
>>> x = prettytable.PrettyTable()
>>> print(x)
++
||
++
++
>>> f=open("yo.txt","wt")
>>> f.write(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: write() argument must be str, not PrettyTable
>>> f.write(x.get_string())
11
>>> 
![Screenshot from 2022-05-07 21-56-10](https://user-images.githubusercontent.com/27255946/167278531-5c4ea6d8-bc70-4b6e-9b45-d71ef1b52571.png)

**Comment by JelleZijlstra** [comment]
This is documented behavior: https://docs.python.org/3.11/library/io.html#io.TextIOBase.write. If you want to change this behavior, I'd recommend opening a discussion on discuss.python.org or the python-ideas mailing list first.

For what it's worth I'd oppose this change. Requiring that the argument is already a string helps avoid accidental bugs like writing the `str()` of a function object.

**Comment by pepe78** [comment]
If print does it, why not write?

**Comment by JelleZijlstra** [comment]
`print()` is usually meant for interactive or debugging use, where it's convenient to get automatic conversion. `.write()` is a lower-level API that has stricter type checks.

**Comment by pepe78** [comment]
print() and write() are both quite often used basic functions in python I use. I wonder if other people use only one of them dominantly.
