### ISSUE TITLE
Docs claim `from __future__ import annotations` will be on by default in 3.11

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#92436]
https://docs.python.org/3.11/library/__future__.html says the annotations `__future__` import is mandatory in 3.11, but it won't be. Right now, it's still undetermined whether this import will ever become the default; we may go with PEP-649's behavior or a combination of the two instead.

In the docs, I think we should just say "To be determined". Optionally, we could add some discussion and link to the SC's pronouncements on the issue.

**Comment by JelleZijlstra** [comment]
Relevant links:

- https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/ delayed the decision past 3.11
- https://mail.python.org/archives/list/python-dev@python.org/message/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/ delayed the decision past 3.10

**Comment by hauntsaninja** [comment]
Seems like this was added in #92568
