### ISSUE TITLE
External link for Github issue are not correctly rendered

### ISSUE THREAD

**Issue by corona10** [python/cpython#92448]
**Documentation**

<img width="951" alt="github_link" src="https://user-images.githubusercontent.com/5110323/167285112-c50ea3e9-4347-4d95-b787-ea4f7c406c26.png">

I found the unhandled places for Github issues and I am preparing to submit the patch for this.

**Comment by ned-deily** [comment]
I manually backported this to 3.7. It needs to be backported to 3.8 as well.

**Comment by corona10** [comment]
@ambv  cc @ned-deily @ezio-melotti 

For backport patch, the following patches should be landed.
- https://github.com/python/cpython/pull/91892
- https://github.com/python/cpython/pull/91895
- https://github.com/python/cpython/pull/91936

and then we can merge this patch: https://github.com/python/cpython/pull/92605 
(Draft, build check should be done after rebasing)

**Comment by ezio-melotti** [comment]
Landed!

**Comment by corona10** [comment]
All done, I close this issue one more time!
