### ISSUE TITLE
Argparse choices should be a sequence

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#92446]
**Documentation**

Instead of saying "any container" is supported, refer only to "sequences".

Technically, a *Container* is only required to support ``__contains__`` which is insufficent for argparse. Also, a sets do get accepted are a bad choice because the order shown in help and usage is non-deterministic. So, *Sequence* is the only reasonable choice because we need sizing and ordered iteration.

### Linked PRs
* gh-94627
* gh-100528
* gh-100529

**Comment by slateny** [comment]
Actually, the [linked pr changes](https://github.com/python/cpython/pull/92450/files) refer to `lzma` instead of `argparse`, was this intended?

**Comment by AA-Turner** [comment]
On a quick review I think that the change to `lzma.rst` should also be reverted, as the option is in the context of `.xz` or `.lzma` container formats.

**Comment by DanielNoord** [comment]
Both https://github.com/python/cpython/pull/94561 and https://github.com/python/cpython/pull/94627 fix this.
The latter seems better though as it is a little more thorough.

I don't think any more PRs are needed, let's focus on merging either of these.
