### ISSUE TITLE
Incorrect interaction between argparse nargs='*' and choices

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#92445]
In the code below, it is valid to supply no arguments.

```
from argparse import ArgumentParser

p = ArgumentParser()
p.add_argument('dessert', nargs='*', choices=('cake', 'pie'))
p.parse_args([])
```

However, the following error is generated:

```
usage: tmp5.py [-h] [{cake,pie} ...]
tmp5.py: error: argument dessert: invalid choice: [] (choose from 'cake', 'pie')
```

What is happening is that the empty list is being treated a value rather than a collection of values.

**Comment by AbhigyanBose** [comment]
@rhettinger 

Could you please elaborate the expected behavior here ?

I tested this on 3.8 and the main branch. In both `p.parse_args([])` gives us the same result as calling the script without any arguments.

Could you tell me the expected output should the code snippet you shared(also pasted below) be run without any arguments?

```
from argparse import ArgumentParser

p = ArgumentParser()
p.add_argument('dessert', nargs='*', choices=('cake', 'pie'))
p.parse_args([])
```

**Comment by Harry-Lees** [comment]
> Could you please elaborate the expected behavior here ?

I believe the expected behaviour for passing an empty list with `nargs="*"` should be the same behaviour as passing an empty list with `nargs="?"` since `*` is 0 or more arguments whereas `?` is 0 or 1 arguments.

```
>>> from argparse import ArgumentParser
>>> p = ArgumentParser()
>>> p.add_argument('dessert', nargs="?", choices=('cake', 'pie'))
>>> p.parse_args([])
Namespace(dessert=None)
```

**Comment by hpaulj** [comment]
This only happens for a `positional`.  `nargs='*'` (and '?') gets some special handling in `get_values`, when an emply list satisfies its `nargs`.  The `default` is assigned in place of the empty list.  

This is part of the logic that allows us to use these `positionals` in a `mutually_exclusive_group`.
