### ISSUE TITLE
`Release date: XXXX-XX-XX` in What's New of 3.5 and 3.9

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#92454]
3.5 and 3.9 are already released or even approached EOL so proper dates need to be here, like in 3.6, 3.7, and 3.8.

Edit: `Python next` header above the version also looks suspicious.

A specimen with the issue (https://docs.python.org/3.5/whatsnew/changelog.html):

> ![image](https://user-images.githubusercontent.com/4881073/167292136-f6291d21-461d-4c49-9964-5d54318f1de9.png)

A specimen without the issue (https://docs.python.org/3.7/whatsnew/changelog.html):

> ![image](https://user-images.githubusercontent.com/4881073/167292200-4b84ae3e-0d55-4206-b663-225b53f61942.png)

Related: gh-92240 (proposes new wording for release date).

**Comment by ned-deily** [comment]
Thank you for the issue. As you note, Python 3.5 has reached end-of-life but it appears the on-line documentation for 3.5 still needs to be run one last time to update the web site to the final release. Perhaps @JulienPalard can look into that.

As for 3.9, it has not yet reached end-of-life (the last bugfix release is in progress at the moment and there will be future security-fix releases) so what is shown currently for 3.9 is normal for any active release: the `Python Next` entry shows changes that have been merged into the branch repo but not yet in a release.

**Comment by arhadthedev** [comment]
Closing as not-a-bug.
