### ISSUE TITLE
Python3.11 error or AIOHTTP error?

### ISSUE THREAD

**Issue by machinexa2** [python/cpython#92511]
https://github.com/aio-libs/aiohttp/issues/6743
python3.11 --version
Python 3.11.0a7+
Python 3.11.0a7+ (heads/main:f2bc12f0d5, Apr 16 2022, 14:45:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by machineaaaac** [comment]
python3.10 sucessfully works which is installed by apt

**Comment by machineaaaac** [comment]
for 3.11 i use ./configure and make and make install

**Comment by JelleZijlstra** [comment]
This should be fixed in aiohttp, not here.
