### ISSUE TITLE
Minor bug in pprint module

### ISSUE THREAD

**Issue by ArturKhuziakhmetov** [python/cpython#92546]
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
> pprint.py
Traceback (most recent call last):
  File "C:\Python\Python310\Lib\pprint.py", line 670, in <module>
    _perfcheck()
  File "C:\Python\Python310\Lib\pprint.py", line 645, in _perfcheck
    p._safe_repr(object, {}, None, 0, True)
TypeError: PrettyPrinter._safe_repr() takes 5 positional arguments but 6 were given

**Comment by ericvsmith** [comment]
Please provide the code that triggered this problem.

**Comment by ericvsmith** [comment]
Ah, I misunderstood. Thanks.

**Comment by rhettinger** [comment]
Irit, 'git annotate' indicates that you made this change.

**Comment by ddurgoji** [comment]
I recently started working towards becoming python core developer. I came across this issue marked as easy. Can I take up and fix this issue?

**Comment by arhadthedev** [comment]
@ddurgoji It's an open project, no preliminary assignment is required. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

**Comment by ddurgoji** [comment]
@arhadthedev , Yes I am going through it thanks.

**Comment by denballakh** [comment]
I think this issue is no longer relevant because it is solved in #94613
