### ISSUE TITLE
Python 3.10.4 for linux install issue

### ISSUE THREAD

**Issue by GUBIY** [python/cpython#92551]
I I'm having a problem installing Python 3.10.4 on Linux. Here is my install commands:
tar -xvf Python-3.10.4.tgz
cd Python-3.10.4
./configure --prefix=/home/build/Dev/lib/python-3.10.4_x86_64
make && make install

If the path for the "--prefix" contains the "-" or "_", the python would be installed in the default path instead of my defined path. If "--prefix" is set to "/home/build/Dev/lib/python3.10.4", it would be correctly installed on the folder.

**Comment by itaisteinherz** [comment]
I couldn't reproduce the issue you described on a fresh Ubuntu 22.04 container, using a path which contains `-` (`/opt/sub/python-3.10_x1_23`).

**Comment by GUBIY** [comment]
@itaisteinherz 
My environment is CentOS 8. I am not sure it is a compatibility issue between CensOS 8 and Python 3.10.4

**Comment by ned-deily** [comment]
What shell are you using to run these commands? That might make a difference. You could try enclosing the path in quotes and see if that helps, like:

`./configure --prefix='/home/build/Dev/lib/python-3.10.4_x86_64'`

**Comment by kumaraditya303** [comment]
As Ned said you can fix this with enclosing it in quotes if your shell does not supports it.
