### ISSUE TITLE
Add IPv4Address.ipv6_mapped attribute

### ISSUE THREAD

**Issue by wbolster** [python/cpython#92573]
**Feature or enhancement**

Add `IPv4Address.ipv6_mapped` attribute for symmetry with existing `IPv6Address.ipv4_mapped`

**Pitch**

The `IPv6Address.ipv4_mapped` attribute ([docs](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv6Address.ipv4_mapped)) makes it easy to decode IPv6 addresses with embedded IPv4 addresses as defined in [RFC4291](https://datatracker.ietf.org/doc/html/rfc4291#section-2.5.5).

It would be useful to also create its mirror version: `IPv4Address.ipv6_mapped`

If others also think this makes sense, please let me know and i can cook up a pull request.

**Comment by encukou** [comment]
This was added in https://github.com/python/cpython/issues/109466
Sorry that we missed this report!
