### ISSUE TITLE
PEP 632: Remove the distutils package (Python 3.12)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#92584]
The distutils module was deprecated in Python 3.10 and is scheduled for removal in Python 3.12.

Right now, Python still uses distutils for different purpose:

* Build C extensions which can not be built by Makefile yet. Python 3.11 can build way more C extensions with Makefile than Python 3.10.
* peg_generator uses distutils to build C extensions.
* test_cppext uses distutils to check that the Python C API can be used in C++.
* ``Tools/c-analyzer/`` uses distutils to get a C preprocessor.

Until Python can be built and used without distutils, I propose to first rename the ``distutils`` package to ``_distutils``: rename th ``Lib/distutils/`` directory to ``Lib/_distutils/``.

Right now, test_venv fails without distutils, because pip fails on importing the distutils module in ``pip/_internal/locations/_distutils.py``: https://github.com/pypa/pip/blob/cb24fb4052ca8ab8009866b0de61980c81a7e13c/src/pip/_internal/locations/_distutils.py#L9-L12

I created the PR #92585 which renames distutils to _distutils.

* PR: gh-99061

* PR: gh-99062

* PR: gh-104744

* PR: gh-108018

* PR: gh-108020

* PR: gh-108024

* PR: gh-108026

* PR: gh-108030

* PR: gh-108031

* PR: gh-108039

* PR: gh-108040

* PR: gh-108043

* PR: gh-108044

* PR: gh-108047

* PR: gh-108057

* PR: gh-108058

* PR: gh-108059

* PR: gh-108060

* PR: gh-108061

* PR: gh-108062

* PR: gh-108063

* PR: gh-108333

* PR: gh-110213

* PR: gh-110214

**Comment by vstinner** [comment]
> Right now, test_venv fails without distutils, because pip fails on importing the distutils module in pip/_internal/locations/_distutils.py

I reported this issue to pip: https://github.com/pypa/pip/issues/11103

**Comment by vstinner** [comment]
The distutils package was deprecated by the issue #85454.

**Comment by vstinner** [comment]
PEP 632 "Deprecate distutils module": https://peps.python.org/pep-0632/

**Comment by FFY00** [comment]
That seems like a good plan. Thanks.

**Comment by jaraco** [comment]
My fear with renaming it is that it lingers indefinitely, and diverging in subtle ways from pypa/distutils. Why not address the dependencies and fully remove the functionality?

Regardless, I agree renaming is preferable to not removing the module at all.

**Comment by vstinner** [comment]
> Why not address the dependencies and fully remove the functionality?

Someone has to modify Python to no longer depend on distutils. The issue description lists code using it. It doesn't seem trivial.

**Comment by FFY00** [comment]
Would it be reasonable to keep it around in the repo while we don't drop the dependency but not ship it as part of Python installations?

**Comment by vstinner** [comment]
> Would it be reasonable to keep it around in the repo while we don't drop the dependency but not ship it as part of Python installations?

With my PR, the ``Lib/_distutils/`` directory is not installed by ``make install``.

**Comment by jkloth** [comment]
Do note that we have buildbots that run from an installed Python.  The tests would need to also be modified to fail gracefully 
 (or skip) when `_distutils` is not available.

**Comment by vstinner** [comment]
> Do note that we have buildbots that run from an installed Python. The tests would need to also be modified to fail gracefully (or skip) when _distutils is not available.

I propose skipping tests relying on _distutils if _distutils is not available.

**Comment by vstinner** [comment]
I wrote two PRs to avoid the deprecated distutils module in two tests:

* #92639: test_cppext uses setuptools
* #92640: test_decimal uses shutil.which() -- IMO an uncontroversial change

**Comment by AbhigyanBose** [comment]
Hi @vstinner  

I think https://github.com/python/cpython/pull/92639/ is causing a test failure, details here https://github.com/python/cpython/issues/92820

**Comment by encukou** [comment]
Marking as 3.12.0a1 release blocker. We want to have public-facing distutils gone in the first alpha, to have as much time as possible to deal with the fallout.

**Comment by pradyunsg** [comment]
For the curious, the PR that @tiran is refering to is https://github.com/python/cpython/pull/94474

**Comment by hroncok** [comment]
> Marking as 3.12.0a1 release blocker. We want to have public-facing distutils gone in the first alpha, to have as much time as possible to deal with the fallout.

It seems that 3.12.0a1 was released with distutils. Was that intentional? cc. @Yhg1s

**Comment by Yhg1s** [comment]
I was going to ping the issue during the core dev sprint and then intentionally ignore it for the alpha 1 release (using it more as a practice run rather than trying to get everything right) -- but then I accidentally ignored it instead :grimacing:. This should just get done for alpha 2.

**Comment by zooba** [comment]
Not sure why this got put on me. If nobody else wants to do it, I can get to it eventually, but I definitely don't want to prevent anyone else from taking the honours.

**Comment by vstinner** [comment]
Since May, the situation evolved:

* Python setup.py has been removed: distutils is no longer needed to **build** Python
* pip has been fixed: it now works if there is no distutils package
* test_cppext now creates a virtual environment to build the C++ with **setuptools**
* test_decimal now uses shutil.which(), rather than distutils.spawn.find_executable()

Thanks to that, I was able to create PR #99061. This PR removes the distutils package. It always skips test_check_c_globals and test_peg_generator since they use distutils. I prefer to remove distutils now, and fix these tests later, rather than missing the next Python 3.12 alpha release.

**Comment by vstinner** [comment]
Python 3.12 alpha 2 was released without distutils.

test_check_c_globals and test_peg_generator are currently skipped because of this removal. These tests should be rewritten without distutils.

**Comment by vstinner** [comment]
You may create new issues for these two currently skipped tests. As you want.

**Comment by pablogsal** [comment]
> test_peg_generator has the same issue, the whole test is also simply skipped in the main branch.

What do you mean is skipped? I don't feel comfortable with just skipping this test without thinking how to fix it. I think this aspect should have taken into account when merging the original PR.

**Comment by encukou** [comment]
To me it looks like `peg_generator` and `check_c_globals` are in the same situation as the rest of the ecosystem will be with 3.12: they broke and the maintainers need to fix them.

IMO, PEP 632 underestimated the amount of work needed, and failed to mention that no one was really interested in actually *implementing it*. (AFAIK we have an implicit assumption that a PEP author will manage the work if the PEP is accepted, we might want to add that to the PEP process docs.)

Thanks for picking up the slack at the last moment, Victor.

**Comment by pablogsal** [comment]
> To me it looks like `peg_generator` and `check_c_globals` are in the same situation as the rest of the ecosystem will be with 3.12: they broke and the maintainers need to fix them.
> 
> 
> 
> IMO, PEP 632 underestimated the amount of work needed, and failed to mention that no one was really interested in actually *implementing it*. (AFAIK we have an implicit assumption that a PEP author will manage the work if the PEP is accepted, we might want to add that to the PEP process docs.)
> 
> 
> 
> Thanks for picking up the slack at the last moment, Victor.

I was under the impression that the plan was to have distutils outside the standard library but available until we figure out what to do with the tests that depend on it. The PEP suggests this as well:

> The final dependency on distutils is CPython itself, which uses it to build native extension modules in the standard library (except on Windows). Because this is a CPython build-time dependency, it is possible to continue to use distutils for this specific case without it being part of the standard library.

Using alternatives within the test suite of CPython differs from using alternatives outside because installing packages like pip and setuptools is not that straightforward.

If this was the plan all along and I was under the wrong impression I apologize for the confusion but I still think having tests deactivated in `main` is just dangerous and we should have though about this first.

**Comment by merwok** [comment]
Reverting the removal would be some churn, but there are other options:
- should be quick to make the testsuite install setuptools, import distutils from setuptools and adjust code if needed
- a bit longer to replace the distutils code in tests with setuptools code, but hopefully not too hard (Extension class should have the same interface, various compiler functions should exist too even if renamed, etc)

**Comment by ericsnowcurrently** [comment]
FWIW, test_check_c_globals basically covers Tools/c-analyzer/check-c-globals.py.  We shouldn't be losing any coverage of CPython with that test disabled.  Plus, there are a few things that need to be fixed with that test that I'd been putting off.  It having been disabled is an extra motivator. 😄

That said, I agree it is surprising that we merged something requiring *any* tests to be disabled and then fixed after the fact by someone other than the author of that PR.  At the very least there should have been some discussion beforehand with the maintainers of the to-be-disabled tests and a clear agreement on how to proceed, all before the PR was merged.  While what happened with distutils may seem relatively benign and innocuous, it's a risky precedent to set.

**Comment by zooba** [comment]
> AFAIK we have an implicit assumption that a PEP author will manage the work if the PEP is accepted, we might want to add that to the PEP process docs.

There was an explicit agreement that the author of this PEP (me) was just putting it in writing and wasn't obligated to do all the work. But feel free to make that an explicit requirement - it just means that I won't volunteer for PEPs that we all want but nobody is willing to do (and will simply withdraw from maintaining the module that we all want to remove) ;)

But yes, I agree that breaking/disabling the tests is not right. Moving `distutils` into `Tools` and pointing the tests at it there would have been fine - they'd have eventually broken with bitrot rather than immediately, but that was happening anyway.

**Comment by ericsnowcurrently** [comment]
Is distutils required to build the docs?  I see uses of it in Doc/includes/setup.py and Doc/includes/test.py.

Also, I'm taking care of gh-100237 (c-analyzer) via gh-102506.  However, separately I'm vendoring a subset of the [reverted] distutils code under Tools/c-analyzer, in gh-102505.  However, we also need distutils for Tools/peg_generator/pegen/build.py (and possibly for the docs).  So it may make sense to vendor distutils in one common place (or use some other mechanism, e.g. pip install in a venv, that the reliant tools can share).

**Comment by zooba** [comment]
Doc builds already rely on a venv with packages from PyPI, so making them use/assume setuptools should be okay.

If we were to vendor it, I'd prefer we just vendor https://github.com/pypa/distutils directly under `Tools`.

**Comment by zware** [comment]
> Is distutils required to build the docs? I see uses of it in Doc/includes/setup.py and Doc/includes/test.py.

As far as I can tell via `git` archaeology, those two files have never actually been used and can just be removed, along with the others that go with them.  Currently testing that theory by ripping them out and seeing if things fail :)

**Comment by zware** [comment]
> along with the others that go with them.

Turns out that the other files (`custom*.c`, `sublist.c`) are referenced by `Doc/extending/newtypes_tutorial.rst`, which itself needs a `distutils`-ectomy.  The `setup.py` and `test.py` files were apparently meant for building and testing those test modules, but that was never made automatic, and those modules are currently quite broken.

**Comment by vstinner** [comment]
@pablogsal:
> What do you mean is skipped? I don't feel comfortable with just skipping this test without thinking how to fix it. I think this aspect should have taken into account when merging the original PR.

My PR clearly says that it skips 2 tests. It was approved by @zware.

[As I wrote previously](https://github.com/python/cpython/pull/92639#issuecomment-1122850347), my plan was to run test_check_c_globals and test_peg_generator in a venv so distutils is provided by setuptools installed in the venv. In the meanwhile, I got catched by more urgent issues and I didn't find time to update these two tests.

Removing distutils is a significant change in Python 3.12 and it's better to do it as soon as possible to give users more time to prepare their project for this [change planned for a long time (PEP 632)](https://peps.python.org/pep-0632/) before Python 3.12 final release.

Just in Fedora, there are already at least [250 packages known to be affected by this change](https://github.com/python/cpython/pull/99061#issuecomment-1302364039)!

Fixing the whole ecosystem for this change is tricky, there are many glitches, like this [setuptools bug](https://github.com/pypa/setuptools/issues/3661#issuecomment-1450572498).

> @vstinner I am sure you understand that is not good to just do something without thinking how to fix the problems you are creating and then throwing the issue to someone else.

I got a burnout for 3 months. I warned you and Eric before leaving so someone else can handle the issue.

There are still 6 months until Python 3.12 final version to decide how to fix the issue: add again distutils or update the 2 tests.

**Comment by vstinner** [comment]
Is there a reason or a technical issue which prevents to run whole test_check_c_globals and test_peg_generator files in a separated process running in a venv? We already have many tests which fully run in a child process for various reasons (usually to be "isolated", run in a controlled environment, and fully reset side effects when tests complete). Just two examples: test_atexit and test_eintr.

**Comment by JelleZijlstra** [comment]
This is still marked as a release blocker, so I decided to take a look. I am not familiar with the distutils situation, but I can see the following concrete issues:

- `Lib/test/test_peg_generator/__init__.py` is still disabled, and various code in `Tools/peg_generator/pegen/build.py` uses distutils. Perhaps it could be switched to `Tools/c-analyzer/distutils`, which is a bundled copy of distutils used by `Tools/c-analyzer`, but there is no PR for that yet.
- Some of the documentation still refers to distutils (e.g., `Doc/library/zipapp.rst`).
- At some point, perhaps the removal of distutils is too disruptive for the ecosystem and we should consider delaying it. I don't know if we're at that point. Victor above mentioned that 250 Fedora packages are affected.

We can probably afford to release the next beta without further changes here, but definitely the docs should be updated before 3.12 final.

**Comment by lysnikolaou** [comment]
> * `Lib/test/test_peg_generator/__init__.py` is still disabled, and various code in `Tools/peg_generator/pegen/build.py` uses distutils. Perhaps it could be switched to `Tools/c-analyzer/distutils`, which is a bundled copy of distutils used by `Tools/c-analyzer`, but there is no PR for that yet.

I can work on this. The question is how much of distutils are we okay with vendoring? The version in `Tools/c-analyzer/distutils` does not cover the needs of `peg_generator`, so we would have to add back in some of the parts that `peg_generator` relies on. Is it okay to add all of distutils there (without the tests etc.) or should I do the work of only adding the absolute necessary parts of it that `peg_generator` needs?

**Comment by AlexWaygood** [comment]
> The question is how much of distutils are we okay with vendoring? The version in `Tools/c-analyzer/distutils` does not cover the needs of `peg_generator`, so we would have to add back in some of the parts that `peg_generator` relies on. Is it okay to add all of distutils there (without the tests etc.) or should I do the work of only adding the absolute necessary parts of it that `peg_generator` needs?

I'd argue our first priority should be unskipping the test, so if that means vendoring all of distutils, so be it. We can always work on stripping the vendored version of distutils down after the test is unskipped, to make the vendored copy more minimal.

**Comment by pradyunsg** [comment]
FWIW, we have a bundled setuptools wheel for the test suite now (since https://github.com/python/cpython/pull/103316/) and it's likely reasonable to reuse that for a test if that's the intent.

**Comment by lysnikolaou** [comment]
@pradyunsg that's what we should be doing ideally, but cause we're so close to the beta-freeze and I'm not familiar enough with `setuptools`, I didn't have the time to do the port. Will probably take the time to properly do everything afterwards.

**Comment by lysnikolaou** [comment]
#104798 is now merged, and, with that, #100238 has been closed. Should we remove the release-blocker label?

**Comment by vstinner** [comment]
The main piece of the initial issue, removing Lib/distutils/ directory, has been completed. I propose to now close this issue. If someone cares about the few left overs, like references to distutils in the documentation, I suggest opening new more specific issues. Since many people got involved in this issue and may have a different opinion than me, I leave the issue open, but again, I suggest closing it ;-)

---

In the main branch, test_peg_generator is running again and Lib/test/test_check_c_globals.py got removed, replaced by a GHA job (commit 1ff81c0cb67215694f084e51c4d35ae53b9f5cf9).

Updating test_peg_generator to use the private setuptools wheel is not directly related to the distutils removal and can be addressed later.

@JelleZijlstra:
> At some point, perhaps the removal of distutils is too disruptive for the ecosystem and we should consider delaying it.

[Python 3.12 beta1 got released](https://blog.python.org/2023/05/python-3120-beta-1-released.html), IMO we should consider that the ship has sailed and we should now focus our efforts on helping the Python ecosystem to be prepared for this incompatible change, rather than discussing again the idea of adding it back to Python 3.12. setuptools provides distutils and IMO it's better than it's maintainer there, in https://github.com/pypa/distutils/ to be exact.

@JelleZijlstra:
> Some of the documentation still refers to distutils (e.g., Doc/library/zipapp.rst).

Hum, honestly, zipapp documentation deserves its own issue. Updating it is non trivial, unless you just want to remove the text about distutils (which is IMO acceptable for now).

@zware:
> Turns out that the other files (custom*.c, sublist.c) are referenced by Doc/extending/newtypes_tutorial.rst, which itself needs a distutils-ectomy.

IMO it's ok for now to have outdated documentation.

Maybe a new issue about outdated documentation using distutils should be created, since a similar replacement can be used? Maybe replacing distutils.core with setuptools is just enough?

**Comment by vstinner** [comment]
Is PR #95254 still useful for tests?

**Comment by vstinner** [comment]
I close the issue. Thanks everybody who helped to make this change possible!
