### ISSUE TITLE
typing._type_check no longer recognizes several kinds of non-types

### ISSUE THREAD

**Issue by davidfstr** [python/cpython#92601]
**Bug report**

The internal function `typing._type_check()` is used extensively to check whether a particular value represents a type. Its docstring begins with:

```
def _type_check(arg, msg, is_argument=True, module=None, *, allow_special_forms=False):
    """Check that the argument is a type, and return it (internal helper).
```

In Python 3.11b1 this function no longer errors on various kinds of non-types:

```python
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=11, micro=0, releaselevel='beta', serial=1)
>>> import typing
>>> typing._type_check(5, "Expected a type.")
# no error!
>>> typing.ClassVar[5]
typing.ClassVar[5]  # no error!
```

By contrast on Python 3.10:

```python
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)
>>> import typing
>>> typing._type_check(5, "Expected a type.")
TypeError: Expected a type. Got 5.
>>> typing.ClassVar[5]
TypeError: typing.ClassVar accepts only single type. Got 5.
```

**Your environment**

Regression introduced somewhere between Python 3.10 and Python 3.11b1.

**Comment by davidfstr** [comment]
CC @JelleZijlstra

**Comment by Fidget-Spinner** [comment]
I think commit https://github.com/python/cpython/commit/870b22b9c442d035190d2b8fb82256cd9a03da48 changed this behavior. It's intentional. Please see the explanation at https://github.com/python/cpython/pull/31151#pullrequestreview-905329086.

**Comment by davidfstr** [comment]
CC @GBeauregard as the originator of [bpo-46644](https://github.com/python/cpython/pull/31151)  
CC @AlexWaygood as a +1er to @JelleZijlstra 's [comment](https://github.com/python/cpython/pull/31151#pullrequestreview-905329086) on that PR to accept it

**Comment by JelleZijlstra** [comment]
This was an intentional change to reduce the number of bugs where typing.py would reject current or future exotic but valid type annotations.

Also, `_type_check` is an internal implementation detail, subject to change at any time. It's also not very good at recognizing valid type annotations: things like `ClassVar[len]` were always accepted. You should implement your own, more precise, check for valid types in your library.

**Comment by davidfstr** [comment]
> You should implement your own, more precise, check for valid types in your library.

Will do. Thanks for taking a look!
