### ISSUE TITLE
Typo in "Data Model" article

### ISSUE THREAD

**Issue by numoworld** [python/cpython#92624]
https://docs.python.org/3/reference/datamodel.html

![image](https://user-images.githubusercontent.com/32400447/167640161-459c169f-41f4-4425-b9a8-2e5f51d94b84.png)

Instead of "There's two type of integers" should be "There's two type of Integrals"

**Comment by numoworld** [comment]
> Or is it saying:
> 
> `numbers.Integral` represent elements from the mathematical set of integers.
> 
> There are two types of integers:
> 
>     * "Normal" integers
> 
>     * Booleans, which are like 0 and 1
> 
> 
> The rules for integer representation are intended etc.

Yes, but then shouldn't it somehow be highlighted that this is math term?

Maybe something like:
_There are two types of **mathematical** integers:_

**Comment by rhettinger** [comment]
I think the current wording is fine (and is definitely not a typo).  The section heading makes it clear that we're talking about the class ``numbers.Integral`` and the sentence following makes it clear the relationship to concept of "mathematical set of integers".  Of these, there are two kinds, "normal integers" and "booleans".  This is also correct.

The survives all but the most pedantic reading of the text (not something users normally do).
