### ISSUE TITLE
Change .js and .mjs MIME type to text/javascript per RFC 9239

### ISSUE THREAD

**Issue by mathiasbynens** [python/cpython#92626]
This is a follow-up to this earlier discussion: https://github.com/python/cpython/pull/3908#discussion_r222443254, now that [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239) resolves this disagreement across standards.

**Comment by mathiasbynens** [comment]
@iritkatriel Indeed! My bad.

**Comment by iritkatriel** [comment]
Not a problem! Thanks for following up.
