### ISSUE TITLE
Function starunpack_helper miss a break statement

### ISSUE THREAD

**Issue by zikcheng** [python/cpython#92632]
In function `starunpack_helper`, code snippet below seems to figure out whether there is a starred argument. I think it's better to insert a break statement below `seen_star = 1;` to stop the iteration as early as possible.

```
int seen_star = 0;
for (Py_ssize_t i = 0; i < n; i++) {
    expr_ty elt = asdl_seq_GET(elts, i);
    if (elt->kind == Starred_kind) {
        seen_star = 1;
    }
}
```

**Comment by corona10** [comment]
@zikcheng Do you want to submit the patch?
