### ISSUE TITLE
Dictionary shorthand

### ISSUE THREAD

**Issue by PositiveUser** [python/cpython#92668]
**Feature or enhancement**

 I want a shorthand for dictionaries

---

Code for a configuration:
```py
{
    'flavours': {
        'chocolate': {
            'type': 'dark'
        }
    }
}
```

This will be long. Below is my idea. You can use this idea or make your own shorthand syntax:

```py
{
    'flavours'['chocolate']['type']: 'dark'
}
# Is same as
{
    'flavours': {
        'chocolate': {
            'type': 'dark'
        }
    }
}
```

Another example:
```py
{
    'flavours': {
        'chocolate'['type']: 'dark',
        'apple'['type']: 'red',
    }
}
# Is same as
{
    'flavours': {
        'chocolate': {
            'type': 'dark'
        },
        'apple'{
            'type': 'red'
        }
    }
}
```

**Comment by AlexWaygood** [comment]
Hi, thanks for the feature request! Significant changes to builtins like this should first be discussed in [the "ideas" section](https://discuss.python.org/c/ideas/6) of discuss.python.org, or the [python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/), so I'm going to close this for now.
