### ISSUE TITLE
distutils does not support os.PathLike

### ISSUE THREAD

**Issue by taralx** [python/cpython#92687]
I prefer to use pathlib.Path objects, but helpers like `distutils.Command.make_file` only accept strings: https://github.com/python/cpython/blob/b69297ea23c0ab9866ae8bd26a347a9b5df567a6/Lib/distutils/cmd.py#L387-L391

Filing this issue before I go in and make a PR to change these to `os.PathLike` checks. Any issues with that approach?

**Comment by JelleZijlstra** [comment]
distutils is deprecated and will be removed in Python 3.12, so we won't accept any enhancements.

The setuptools project provides a version of distutils that will remain available, and they may accept this feature request.
