### ISSUE TITLE
Double Hex Hash Addition

### ISSUE THREAD

**Issue by aydaultani** [python/cpython#92711]
**Feature or enhancement**

A version of the `token_hex` secrets modules, twice.

**Pitch**

This would be better for protection overall since the the hash too, will be hashed if the user choses too.

**Comment by sweeneyde** [comment]
A token generated by `token_hex` is already as random as it can be. If you need to introduce more entropy, pass in more bits:

```
>>> import secrets
>>> secrets.token_hex(100)
'341162ad2ffab82c9396660554f77c347b0ff7463b076ffeb2f3f24af8fc608fa2a59138c64fd1bc630867a4eec5afd8420461a4dbd33e4d5302f0e9aa0a668c54dc98a86f0c44a0a04f29cc22273655054995995f098887e75b33ed83cd94636c9ca287'
```
