### ISSUE TITLE
The link in "Related Articles" section of "HOWTO Fetch Internet Resources Using The urllib Package" page does not work.

### ISSUE THREAD

**Issue by OmerFI** [python/cpython#92719]
**Documentation**

In the [HOWTO Fetch Internet Resources Using The urllib Package](https://docs.python.org/3/howto/urllib2.html) topic there is a section of "Related Articles" saying:
> Related Articles
>
>You may also find useful the following article on fetching web resources with Python:
>
>    - [Basic Authentication](http://www.voidspace.org.uk/python/articles/authentication.shtml)
>
>            A tutorial on Basic Authentication, with examples in Python.

The link goes to http://www.voidspace.org.uk/python/articles/authentication.shtml but does not work.

**Comment by hugovk** [comment]
Thanks for the report, that whole website is now down.

I couldn't find a replacement at a new website, we can instead replace it with a recent Internet Archive link:

https://web.archive.org/web/20201215133350/https://www.voidspace.org.uk/python/articles/authentication.shtml

@OmerFI Would you like to create a pull request? You can edit the page directly at https://github.com/python/cpython/blob/main/Doc/howto/urllib2.rst

Ping also @voidspace.

**Comment by OmerFI** [comment]
@hugovk Thanks for the quick reply.

The article uses python 2. So maybe it is better to remove this link?

Or, I can create a pull request and replace the broken link with the Internet Archive link.
