### ISSUE TITLE
Add example of named group to re.Match.__getitem__ doc

### ISSUE THREAD

**Issue by bmispelon** [python/cpython#92727]
**Documentation**

The documentation for [`re.Match.__getitem__`](https://docs.python.org/3/library/re.html#re.Match.__getitem__) only shows example of using positional capture groups (like `matchobj[1]`) but not named groups (like `matchobj['foo']`).

It mentions that "[...] is identical to m.group(g)" so you can infer that named groups work, but I think having an explicit example would encourage the adoption of the feature.

**Comment by slateny** [comment]
Resolved per #92730.
