### ISSUE TITLE
`buildrelease.bat` fails with `cannot find python3813.chm` on Windows 10

### ISSUE THREAD

**Issue by adam-grant-hendry** [python/cpython#92738]
**Bug report**

On Windows 10, for Python 3.8.13, building a release installer fails because it cannot find `python3813.chm` file. This help file is unavailable on the [Python Downloads Page](https://www.python.org/downloads/windows/) (_Perhaps because this is a security fix? Last release with Windows help file was 3.8.10._)

I'm not sure how to fix this from the included `README` files to make the `.msi` installer.

**Environment**

- CPython: 3.8.13
- OS and Architecture: Windows 10, x86_64 (amd64), build 19042.1586 (version 20H2)
- Editor: Visual Studio 2019 Community, Python development workload, Python native development tools
- Terminal: Command Prompt

**MRE**

1. Download and unzip [source](https://www.python.org/downloads/release/python-3813/) to `%USERPROFILE%\Code\python\Python-3.8.13` (**NOTE:** I'm not `git clone`ing from GitHub `python/cpython`)

2. In Command Prompt, navigate to folder and install external dependencies:

```cmd
> cd %USERPROFILE%\Code\python\Python-3.8.13
> .\PCbuild\get_externals.bat
```

**NOTE:** `nuget` installs `python3.10.4` even if I use `--python 3.8`

3. Build the debug and PGO binaries

```cmd
> .\PCbuild\build.bat -p x64 -c Debug
> .\PCbuild\build.bat -p x64 --pgo
```

4. Download the installer external dependencies:

```cmd
> .\Tools\msi\get_externals.bat
```

5. Turn on `.NET Framekwork 3.5 Features` in `Turn Windows features on or off`.

6. Test build (build the installer layout and docs):

```cmd
> .\Tools\msi\build.bat -x64 --doc > build_log.txt
```

**Log File:** 
[build_log.txt](https://github.com/python/cpython/files/8681045/build_log.txt)

7. Build the release installer

```cmd
> .\Tools\msi\buildrelease.bat -x64 > buildrelease_log.txt
```

**Log File:**
[buildrelease_log.txt](https://github.com/python/cpython/files/8681137/buildrelease_log.txt)

In both 6 and 7, the following traceback error is sent to stdout:

**Traceback Error:**
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\cmd\build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\application.py", line 34, in <module>
    from sphinx.highlighting import lexer_classes, lexers
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\highlighting.py", line 27, in <module>
    from sphinx.ext import doctest
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\ext\doctest.py", line 28, in <module>
    from sphinx.builders import Builder
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\builders\__init__.py", line 24, in <module>
    from sphinx.io import read_doc
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\io.py", line 33, in <module>
    from sphinx.util.rst import append_epilog, docinfo_re, prepend_prolog
  File "C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\sphinx\util\rst.py", line 22, in <module>
    from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (C:\Users\hendra11\Code\python\Python-3.8.13\externals\pythonx86\tools\lib\site-packages\jinja2\__init__.py)
```

**NOTE:** `jinja2` version is `3.1.2`:

```cmd
> cd %USERPROFILE%\Code\python\Python-3.8.13\externals\pythonx86\tools
> .\python.exe -c 'import jinja2;print(jinja2.__version__)'
3.1.2
```

**Comment by zooba** [comment]
I think we need to pin Sphinx to an earlier version in 3.8. I'm not entirely sure which version that is, but it's probably correct in the POSIX makefile for docs.

**Comment by adam-grant-hendry** [comment]
Downgrading `jinja2` (Uninstalling version `3.1.2` and installing `jinja2<3.1`) solves part of the issue:

```cmd
> cd .\externals\pythonx86\tools
> .\pip.exe uninstall jinja2
> .\pip.exe install jinja2<3.1
```

Also [sphinx-doc/sphinx Issue #5415](https://github.com/sphinx-doc/sphinx/pull/5415) replaced `HTMLHelpBuilder.open_file()` with standard python `open()`, which broke `Doc\tools\extensions\escape4chm.py`, lines 44 and 46. `pathlib.Path` or `os` should be imported and lines lines 44 and 46 changed. For example, from

```python
with app.builder.open_file(outdir, outname + '.hhk', 'r') as f:
    ...
with app.builder.open_file(outdir, outname + '.hhk', 'w') as f:
    ...
```

to

```python
import os
...
with open(os.path.join(outdir, ''.join([outname, '.hhk'])), 'r') as f:
    ...
with open(os.path.join(outdir, ''.join([outname, '.hhk'])), 'w') as f:
    ...
```

I'm waiting for `buildrelease.bat` to finish to see if I run into any other issues...

**Comment by adam-grant-hendry** [comment]
The first problem is fixed (it builds `python3813.chm`), but now I'm running into a `pip` error that breaks the build:

> `EXEC : error : pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`  
> `[C:\Users\hendra11\Code\python\Python-3.8.13\Tools\nuget\make_pkg.proj]`  
> 
> `ipython 7.32.0 requires backcall, which is not installed.`  
> `ipython 7.32.0 requires colorama; sys_platform == "win32", which is not installed.`  
> `ipython 7.32.0 requires decorator, which is not installed.`  
> `ipython 7.32.0 requires jedi>=0.16, which is not installed.`  
> `ipython 7.32.0 requires matplotlib-inline, which is not installed.`  
> `ipython 7.32.0 requires pickleshare, which is not installed.`  
> `ipython 7.32.0 requires prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, which is not installed.`  
> `ipython 7.32.0 requires pygments, which is not installed.`  
> `ipython 7.32.0 requires traitlets>=4.2, which is not installed.`

![error_img](https://user-images.githubusercontent.com/59346180/168166071-a62570b0-4efe-4477-b2de-8f6643a60145.PNG)

**Comment by zooba** [comment]
This one looks like it's because we've picked up your existing Python install, but are then trying to add more packages to it. We should probably switch to always creating a new install for our build process to avoid messing with a system install. Such a fix won't make it back to 3.8 though.

You probably want to create and activate a virtual environment with any other Python install, then run the build. That should put all the packages into the venv.

**Comment by adam-grant-hendry** [comment]
Using a virtual environment does not solve the problem. I get the exact same errors, so the issue still persists.

**Comment by zooba** [comment]
That warning is expected and okay, and the git errors are expected if you're not in a git repository - it just means that `sys._git` won't be filled out.

While an active venv should be picked up automatically, you can set the `PYTHON` environment variable to point at your other install. Or alternatively, if you don't need those conflicting packages, uninstall them so that the correct Sphinx version can be installed.

**Comment by adam-grant-hendry** [comment]
@zooba The error was on my end. I just found out I had previously set a system environment variable named `PYTHON`, which was pointing to other installed versions of python. After overwriting this in my local terminal

```powershell
> $env:PYTHON = ''
```

The installer compiles. I still have to downgrade `jinja2` and fix `Doc\tools\extensions\escape4chm.py`, but that was easy to do.

![image](https://user-images.githubusercontent.com/59346180/168320338-95e42e58-1655-49f6-b9fd-46f922a89c1a.png)

**Comment by zooba** [comment]
Judging from other discussions, we're unlikely to backport changes to install downgraded versions of build dependencies, so I guess this can be closed? Just shout if you think there's something we should fix in that release (or in the future - I'm pretty sure we've pinned all the docs build dependencies now, just not in the old releases).
