### ISSUE TITLE
Docs don't explicitly describe an implicit `return None` in user-defined function

### ISSUE THREAD

**Issue by mbottini** [python/cpython#92753]
**Documentation**

Empirically, it is the case that when execution reaches the end of a user-defined function body without encountering a `return` statement, the function returns `None`. 

    def foo():
        pass
        # implicit `return None`

And the docs hint at this in places! From [here](https://docs.python.org/3/reference/expressions.html#calls), in 6.3.4, emphasis added:

> A call always returns some value, **possibly `None`**, unless it raises an exception. How this value is computed depends on the type of the callable object.

Later, in User-Defined Functions:

> When the code block executes a [return](https://docs.python.org/3/reference/simple_stmts.html#return) statement, this specifies the return value of the function call.

Additionally, [here](https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy) in 3.2:

> [`None`] is used to signify the absence of a value in many situations, e.g., it is returned from functions that don’t explicitly return anything.

But the reference doesn't actually come out and explicitly say what happens in the absence of a `return` statement.

**Possible Fix**:

Ideally, I'd add one more sentence to the User-Defined functions section after the above quote:

> If the code block reaches the end of the function body without executing a `return` statement, the return value is `None`.

**Comment by sweeneyde** [comment]
For what it's worth, [this tutorial page](https://docs.python.org/3/tutorial/controlflow.html#defining-functions) already has the following sentences:

> In fact, even functions without a [return](https://docs.python.org/3/reference/simple_stmts.html#return) statement do return a value, albeit a rather boring one. This value is called None (it’s a built-in name).

> The [return](https://docs.python.org/3/reference/simple_stmts.html#return) statement returns with a value from a function. return without an expression argument returns None. Falling off the end of a function also returns None.

**Comment by mbottini** [comment]
That's fair, although I'd argue that the tutorial should be an informal exploration of behavior that is explicitly stated in the reference. It's totally fine for the tutorial to be explicit too, but it's strange to me that the formal language reference (which is what implementors should be targeting) is less rigorous than the tutorial.

**Comment by rhettinger** [comment]
> I'd argue that the tutorial should be an informal exploration of behavior that is rigorously specified in the reference.

See [Section 6.3.4 Calls](https://docs.python.org/3/reference/expressions.html#calls): "A call always returns some value, possibly None, unless it raises an exception. How this value is computed depends on the type of the callable object."

**Comment by saaketp** [comment]
> > I'd argue that the tutorial should be an informal exploration of behavior that is rigorously specified in the reference.
> 
> See [Section 6.3.4 Calls](https://docs.python.org/3/reference/expressions.html#calls): "A call always returns some value, possibly None, unless it raises an exception. How this value is computed depends on the type of the callable object."

That was pointed to by the OP too, but it says "possibly" and it doesn't say when exactly it could be None, so it doesn't really solve the issue I think.

There should be an explicit statement that if the end of the function is reached, and there is no `return` then the function returns None.  The description of None in the `datamodel` page does a better job of this https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy but I expect to see this mentioned in more relevant places like the `calls` section or maybe even the section about the `return` statement.

**Comment by hawkinsw** [comment]
Hello! I found this issue after exploring the Reference for several hours looking for exactly where the "implicit return `None`" behavior was formally specified. I think that the Reference is one of (if not *the*) language specification out there and I enjoy showing it off in the programming languages course that I teach! I see that @rhettinger closed this as "complete" but don't see any associated changes. 

Would anyone object to a PR for the Reference making explicit what "everyone" knows?

Thanks again for the great work on the Reference (and Python overall!)
