### ISSUE TITLE
Interpreter exits when argparse is called with invalid args

### ISSUE THREAD

**Issue by why-does-ie-still-exist** [python/cpython#92764]
**Crash report**

I was trying to see how argparse is used. After calling the parser with invalid arguments, the interpreter just exits without warning. `p.parse_args('--foo'.split())`

**Error messages**

Enter any relevant error message caused by the crash, including a core dump if there is one.
In Miniconda 3.9.12:
```
>>> from argparse import ArgumentParser
>>> p = ArgumentParser()
>>> p.add_argument('--foo')
_StoreAction(option_strings=['--foo'], dest='foo', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> p.parse_args('--foo'.split())
usage: [-h] [--foo FOO]
: error: argument --foo: expected one argument
(rl_pupper) PS C:\Users\Michael Owens\Documents\PHYS71R\puppersim_blame_the_hardware>
```
In CPython 3.10:
```
PS C:\Users\Michael Owens> python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from argparse import ArgumentParser
>>> p = ArgumentParser()
>>> p.add_argument('foo')
_StoreAction(option_strings=[], dest='foo', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> p.parse_args('--foo'.split())
usage: [-h] foo
: error: the following arguments are required: foo
PS C:\Users\Michael Owens>
```

**Your environment**

- CPython versions tested on:
Broken in Miniconda Python 3.9.12, Broken in CPython 3.10,4
Works on CPython 3.9.2,
- Operating system and architecture:
Microsoft Windows 10 Pro
10.0.19042 Build 19042

**Comment by hauntsaninja** [comment]
This is expected behaviour. `ArgumentParser` calls `sys.exit`. You're welcome to use your own `ArgumentParser` subclass that overloads the `error` method, or to catch SystemExit. The reason argparse does this is presumably so that CLI users get an error message instead of a traceback.
