### ISSUE TITLE
Create to_dict function

### ISSUE THREAD

**Issue by pvgmenegasso** [python/cpython#92773]
Create to_dict function

With Python built-in methods and attributes for classes it is possible to automatically translate a custom class
to a Dict object, which can be subsequently used when serializing data.

**Pitch**

I Have implemented this feature in a non related project which relies on python in order to be
able to serialize my custom and nested classes in jsonl format.

I plan to add it to json module... Nonetheless I am open to suggestions/comments

Here is an example of this feature in action:

![image](https://user-images.githubusercontent.com/15230675/168274142-e737c08a-097f-4442-aa3d-0f324143163b.png)
Here we convert an object to jsonl format and write it in disk.
![image](https://user-images.githubusercontent.com/15230675/168274935-65231bb0-1acb-4146-8697-b76adc94334b.png)
![image](https://user-images.githubusercontent.com/15230675/168274969-7901a3d0-f4b7-41ab-a498-9d38ef21601d.png)

This is an example of how the feature could be used

**Comment by ajoino** [comment]
This suggestion is basically implemented in Pydantic [https://pydantic-docs.helpmanual.io/usage/exporting_models/](https://pydantic-docs.helpmanual.io/usage/exporting_models/)

I once tried to do something similar to what you're doing and once I found Pydantic I rewrote large chunks of the project to use it. You should take a look and see how it could work in your project.

**Comment by serhiy-storchaka** [comment]
It fails in the category: "Not every one-line function should be added in the stdlib."

**Comment by serhiy-storchaka** [comment]
Well, it was not completely clear from your pictures what you want. I thought one of it contains an implementation of the `to_dict()` function, and all of them can be written in a single line.

How do you want to implement `to_dict()`? How it should work with, for example, int, or str, or file, or ElementTree? What is the difference from `vars()` and `dataclasses.asdict()`?

**Comment by pvgmenegasso** [comment]
> Well, it was not completely clear from your pictures what you want. I thought one of it contains an implementation of the `to_dict()` function, and all of them can be written in a single line.
> 
> How do you want to implement `to_dict()`? How it should work with, for example, int, or str, or file, or ElementTree? What is the difference from `vars()` and `dataclasses.asdict()`?

The idea was to include the implementation alongside the json module so we didn't have to extend every custom class with a specific function.
This code surely needs some refactoring, as I am using it in another project, but please tell me what you think:

``` Python

def to_dict(object: Any) -> dict:
    result : Dict= {}
    try:
        for index, item in enumerate(object):
            result[index]=to_dict(item)
    except:
        for x in dir(object):    
            if not x.startswith('__') and not x.startswith('_') and not callable(object.__getattribute__(x)):
                if type(object.__getattribute__(x)) is date:
                    var : date= object.__getattribute__(x)
                    result[x]=var.isoformat()
                else:
                    try:
                        json.JSONEncoder().encode(object.__getattribute__(x))
                        result[x]=object.__getattribute__(x)
                    except:
                        result[x]=to_dict(object.__getattribute__(x))
    return 
```

**Comment by AA-Turner** [comment]
This doesn't seem like something that should be in the standard library -- regardless, you should open a discussion on Discourse or `python-ideas` for more discussion of this feature. I'm closing the issue now, but if the outcome of that discussion is positive we can re-open.

A
