### ISSUE TITLE
No documentation for ast.Module class and others.

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#92788]
**Documentation**

The [documentation on the ast module](https://docs.python.org/3.10/library/ast.html) does not mention the `Module, Interactive, Expression, or FunctionType ` class.  They should be added.
I haven't checked but I think these are the only module members that are not documented.  You might want to check for any other public members (helper functions or node classes) that are not documented.

### Linked PRs
* gh-101055
* gh-106138
* gh-106139

**Comment by isidentical** [comment]
Would you like to submit a PR for them?

**Comment by sobolevn** [comment]
@mrolle45 @isidentical reviews are welcome :)

**Comment by hauntsaninja** [comment]
Thanks everyone!
