### ISSUE TITLE
sqlite3: `Connection.create_collation()` documentation inaccuracies

### ISSUE THREAD

**Issue by AdrianIssott** [python/cpython#92780]
**Documentation**

Currently the documentation of `sqlite3.create_collation()` (https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_collation) says:

> Note that the callable will get its parameters as Python bytestrings, which will normally be encoded in UTF-8.

However, as you can see from the discussion on https://github.com/python/cpython/issues/92742 that's incorrect in python 3 and the callable gets its parameters as Python strs which matches the [SQLite docs](https://sqlite.org/datatype3.html#collation) which says:

> Collating functions only matter when comparing string values

**Comment by erlend-aasland** [comment]
Would you mind reviewing the proposed change, @AdrianIssott?

**Comment by erlend-aasland** [comment]
Resolved by:

- main: gh-92790
- 3.11: gh-92922
- 3.10: gh-92923
