### ISSUE TITLE
sysconfig.get_config_var('INSTSONAME') get wrong library path

### ISSUE THREAD

**Issue by awfeequdng** [python/cpython#92794]
**Bug report**
- I get a wrong python library through sysconfig.get_config_var('INSTSONAME'), the result is 'Python.framework/Versions/3.9/Python'
- details as follow:
```
>>> import sysconfig
>>> sysconfig.get_config_var('LIBDIR')
'/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib'
>>> sysconfig.get_config_var('INSTSONAME')
'Python.framework/Versions/3.9/Python'
```
but I can not find the library: `/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/Python.framework/Versions/3.9/Python`

- the true python lib path is as follow: 
```
$ ll /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -> ../Python

$ ll /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python


```
**Your environment**

- CPython versions tested on: Python 3.9.4
- Operating system and architecture:   Darwin Kernel Version 19.6.0:  RELEASE_X86_64 x86_64
<img width="339" alt="image" src="https://user-images.githubusercontent.com/8253416/168406458-388e722c-5773-42ee-bf8f-4afdc2ec36f3.png">

**Comment by ronaldoussoren** [comment]
What are you trying to do?   That is, why are you using ``get_config_var`` to get these values and what are you trying to accomplish with the result. This may help advising you for a better way to accomplish this.

The values of a number  of keys you can get using ``get_config_var`` are undocumented and depend on detail of the build proces and therefore not useful outside of the build proces.

**Comment by awfeequdng** [comment]
> 

when i build pytorch，it use `get_config_var` to get python library which linked to torch_python , but this function `get_config_var` get a wrong python library path, so i build pytorch failed.

The setup.py in pytorch use `get_config_var` as follow:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/8253416/168421788-d12d52c5-476e-4cc1-a3dd-af0ac38d8ed3.png">

**Comment by ronaldoussoren** [comment]
This usage of INSTSONAME feels wrong to me. Please use ``python3-config`` to get the compiler flags to be used when linking (and compiling). 

Also: If you're trying to create a extension module do no link to libpython, that will bind the output to a specific installation prefix for python instead of being relocatable.

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by ronaldoussoren** [comment]
Not really.   ``python3-config`` is the documented interface for getting compiler flags.

As mentioned earlier, not all variables are useful outside of the build proces and INSTSONAME is one of them with a framework build of macOS.  If there is anything to be done it is designing and implementing an interface for queuing for well-defined and useful information. That's out of scope for this issue and would IMHO first require discussion elsewhere.
