### ISSUE TITLE
numpy.poly1d variable option not working

### ISSUE THREAD

**Issue by bjlBYUI** [python/cpython#92809]
When using the variable option in numpy.poly1d, the variable is not changing from 'x' if the poly1d object is manipulated after creation.

In the example below, the polynomial printed should show 'T' as the variable, but 'x' is showing.

**Example**

#start
import numpy as np
a = 5
f = np.poly1d([1,1],variable='T')
f = f/a
print(f)

**Your environment**

Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin

Operating system and architecture: MacOS 12.3.1

If the f = f/a is left out, the print shows the correct 'T' variable.

**Comment by samuelcolvin** [comment]
Hi @bjlBYUI your question/bug will get a better response if you format your code using [markdown code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

I also think your issue relates to numpy, not to cpython. You might have more luck asking on stackoverflow unless you're absolutely sure this is an issue with cypython?

**Comment by AlexWaygood** [comment]
Samuel is correct. Please ask your question on StackOverflow, https://discuss.python.org/c/users/7, or a numpy discussion forum :)
