### ISSUE TITLE
ArgumentParser.add_subparsers() argument spec discrepancies

### ISSUE THREAD

**Issue by MatthiasHeinz** [python/cpython#92812]
**Documentation**

The function-signature currently reads `ArgumentParser.add_subparsers([title][, description][, prog][, parser_class][, action][, option_string][, dest][, required][, help][, metavar])`, but when trying to use the parameter _option_string_, the error-message suggests, that this parameter does not exist. On the other hand, the code does suggest a parameter called _option_strings_ (with an additional 's' at the end).

Please update the docs accordingly.

[Link to the docs](https://docs.python.org/3/library/argparse.html#sub-commands)
[Link to the code](https://github.com/python/cpython/blob/main/Lib/argparse.py#L1835)

Might be related to #92811

**Comment by erlend-aasland** [comment]
Fixed by #92814 -- thanks for the report!
