### ISSUE TITLE
Python Launcher for Windows (py.exe) seems to ignore virtual environment in recent beta 3.11.0b1

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#92817]
When typing `py`, I get the **standard** python version as set by `%PY_PYTHON%`, i.c. 3.10, _even_ when a virtual environment (`venv`) is active.
When typing `python`, I get the python version from the `venv`, i.c. 3.11.

I _expected_ the Python Launcher for Windows (`py.exe`) to prefer the CLI command argument `py -<n.n>` (if any) over `venv` over `%PY_PYTHON%`.
That was the way I recall `py` worked in 3.10. 3.11.0a7 had an [issue](https://github.com/python/cpython/issues/91395) in ignoring `%PY_PYTHON%`, which is now remedied in 3.11.0.b1 (thanks @zooba !). The `venv` part still seems to have an issue in 3.11.0b1.

**Environment**
```
(venv) >set py
PY_PYTHON=3.10

(venv) >py -0p
 -V:3.11          C:\Program Files\Python311\python.exe
 -V:3.10 *        C:\Program Files\Python310\python.exe
 -V:3.9           C:\Program Files\Python39\python.exe
```
**Issue**
```
(venv) >py -V -V
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

(venv) >python -V -V
Python 3.11.0b1 (main, May  7 2022, 22:58:47) [MSC v.1931 64 bit (AMD64)]

(venv) >where python
C:\Users\[...]\venv\Scripts\python.exe
C:\Program Files\Python311\python.exe

(venv) >where py
C:\Windows\py.exe

(venv) >py -h
Python Launcher for Windows Version 3.11.0b1

usage:
py [launcher-args] [python-args] [script [script-args]]
[...]
```

**Comment by Dutcho** [comment]
(unsuccessfully looked for a way to add tags like Windows and 3.11 and 'nosy' people, like we did on [the previous tracker](https://bugs.python.org/), so hope this gets added in the process)

**Comment by zooba** [comment]
Could well be a regression. I'll have to look at the code, but it's probably picking up the environment variable as a preference rather than a default/fallback.

**Comment by zooba** [comment]
So how this is working is like this:
* an active venv gets detected just like any other install (registry, app store, etc.). it gets highest priority (you should see it in "py -0p" with the venv active)
* `PY_PYTHON` variable gets read if you don't specify a `-x` or `-x.y` tag and treated as if you specified it
* the implied tag skips the venv and finds a matching version

I guess we just need an additional flag to distinguish between explicit command line arguments and implicit configuration files and environment variables (and hopefully people just know that environment variables are always implicit, even if it looks explicit in their case).
