### ISSUE TITLE
Python 3.7.13 - Segmentation fault on import

### ISSUE THREAD

**Issue by diasjoaocarlos** [python/cpython#92825]
Python Environment:

Python 3.7.13 (default, Mar 28 2022, 07:24:34) 
[Clang 12.0.0 ]

on Anaconda: 
    conda version : 4.12.0
    conda-build version : 3.20.5
    python version : 3.7.13.final.0
    virtual packages : __osx=10.15.7=0
                                  __unix=0=0
                                  __archspec=1=x86_64

On:
$ lldb python
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) run
Process 11715 launched: '/Users/Joao/anaconda3/bin/python' (x86_64)
Python 3.7.13 (default, Mar 28 2022, 07:24:34) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import myextension
Process 11715 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000103077d9b libpython3.7m.dylib`PyModule_Create2 + 11
libpython3.7m.dylib`PyModule_Create2:
->  0x103077d9b <+11>: movq   0x10(%rax), %rax
    0x103077d9f <+15>: cmpq   $0x0, 0x28(%rax)
    0x103077da4 <+20>: je     0x103077dac               ; <+28>
    0x103077da6 <+22>: popq   %rbp
Target 0: (python) stopped.
(lldb) 
(lldb) reg read rax
     rax = 0x0000000000000000
(lldb) disass
libpython3.7m.dylib`PyModule_Create2:
    0x103077d90 <+0>:  pushq  %rbp
    0x103077d91 <+1>:  movq   %rsp, %rbp
    0x103077d94 <+4>:  movq   0x2576fd(%rip), %rax      ; _PyRuntime + 1528
->  0x103077d9b <+11>: movq   0x10(%rax), %rax

The module 'myextension.so' was made using:
gcc -DNDEBUG -g -O3 -Wall -fPIC -I/Users/Joao/anaconda3/include/python3.7m/ -c myextension.c
gcc -shared myextension.o -L/Users/Joao/anaconda3/lib/ -lpython3.7m -o myextension.so

And code is 'myextension.c', using the Python C API (using Python.h):

PyMODINIT_FUNC
PyInit_myextension(void)
{
#if PY_MAJOR_VERSION >= 3
    PyObject *module = PyModule_Create(&moduledef);
#else
    PyObject *module = Py_InitModule("myextension", myextension_methods);
#endif
...

Using bash and running python:

$ python
Python 3.7.13 (default, Mar 28 2022, 07:24:34) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import myextension
zsh: segmentation fault  python

**Comment by da-woods** [comment]
There's a lot of code that you don't show in 'myextension.c' that could be causing the crash, which is most likely a bug in 'myextension' rather than a Cython bug

**Comment by diasjoaocarlos** [comment]
@da-woods:

I have compiled several similar extensions (Python C API, in Ubuntu 18.04 LTS - Python 3.7.9 , in Windows 10 - Anaconda - Python 3.7.9) and they have behaved well.

However, when I try to compile and use these extensions in Macbook Air : Anaconda : Python 3.7.13 or with the default Python or macOS Catalina (3.9), they gave the error Segmentation Fault.

Do you see that I call PyModule_Create, this should call PyModule_Create2, but the register %RAX is zero which should be an error. It causes Segmentation Fault.

The extension myextension is almost an empty extension... All pythons on my Macbook can't run these extensions if compiled for the respective version...

**Comment by zware** [comment]
To have any hope of tracking down an issue in cpython related to this, we need to have the full source code of an extension module that produces the segfault.  Without it, there is nothing we can do but say that many thousands of other extension modules work fine on all of the mentioned platforms, so the problem is probably in the extension itself instead of cpython.

**Comment by diasjoaocarlos** [comment]
Code - myextension.c :

#include "Python.h"

struct module_state {
    PyObject *error;
};

#if PY_MAJOR_VERSION >= 3
#define GETSTATE(m) ((struct module_state*)PyModule_GetState(m))
#else
#define GETSTATE(m) (&_state)
static struct module_state _state;
#endif

static PyObject *
error_out(PyObject *m) {
    struct module_state *st = GETSTATE(m);
    PyErr_SetString(st->error, "something bad happened");
    return NULL;
}

static PyMethodDef myextension_methods[] = {
    {"error_out", (PyCFunction)error_out, METH_NOARGS, NULL},
    {NULL, NULL}
};

#if PY_MAJOR_VERSION >= 3

static int myextension_traverse(PyObject *m, visitproc visit, void *arg) {
    Py_VISIT(GETSTATE(m)->error);
    return 0;
}

static int myextension_clear(PyObject *m) {
    Py_CLEAR(GETSTATE(m)->error);
    return 0;
}


static struct PyModuleDef moduledef = {
        PyModuleDef_HEAD_INIT,
        "myextension",
        NULL,
        sizeof(struct module_state),
        myextension_methods,
        NULL,
        myextension_traverse,
        myextension_clear,
        NULL
};

#define INITERROR return NULL

PyMODINIT_FUNC
PyInit_myextension(void)

#else
#define INITERROR return

void
initmyextension(void)
#endif
{
#if PY_MAJOR_VERSION >= 3
    PyObject *module = PyModule_Create(&moduledef);
#else
    PyObject *module = Py_InitModule("myextension", myextension_methods);
#endif

    if (module == NULL)
        INITERROR;
    struct module_state *st = GETSTATE(module);

    st->error = PyErr_NewException("myextension.Error", NULL, NULL);
    if (st->error == NULL) {
        Py_DECREF(module);
        INITERROR;
    }

#if PY_MAJOR_VERSION >= 3
    return module;
#endif
}

**Comment by zware** [comment]
I can't reproduce the segfault using the code and commands you provided, but I'm also on Linux and not using Anaconda.

I will note that it seems incorrect to link `python3.7m` into the extension; as far as I can tell that should be unnecessary, and a local test works just as well without it (and also with a *much* smaller `.so`).  If removing `-lpython3.7m` from your link command doesn't help, I would recommend seeking help from the Anaconda project.

**Comment by diasjoaocarlos** [comment]
Without -lpython3.7m it doesn't link: there is not any PyModule_Create2,... which to link to.

Question in Anaconda Community https://community.anaconda.cloud/t/python-3-7-13-anaconda-macos/22342

**Comment by ronaldoussoren** [comment]
Don't link C extensions to libpython, at least not on macOS. This can lead to problems when the C extension refers to a different python shared library than used by the running interpreter. This results in libpython being loaded a second time, the second one (used by the extension) not initialised.

**Comment by diasjoaocarlos** [comment]
I did:
```
gcc -DNDEBUG -g -O3 -Wall -fPIC -I/Users/Joao/anaconda3/include/python3.7m/ -c myextension.c
```
with no errors and:
```
gcc -shared myextension.o -L/Users/Joao/anaconda3/lib/ -o myextension.so
Undefined symbols for architecture x86_64:
  "_PyErr_NewException", referenced from:
      _PyInit_myextension in myextension.o
  "_PyErr_SetString", referenced from:
      _error_out in myextension.o
  "_PyModule_Create2", referenced from:
      _PyInit_myextension in myextension.o
  "_PyModule_GetState", referenced from:
      _PyInit_myextension in myextension.o
      _myextension_traverse in myextension.o
      _myextension_clear in myextension.o
      _error_out in myextension.o
ld: symbol(s) not found for architecture x86_64
```

This happens for version 3.7.13 in macOS, now with updated OS. Even without the -L switch.

Note: I have in the lib directory the following files: 
/Users/Joao/anaconda3/lib/libpython3.7m.a
/Users/Joao/anaconda3/lib/libpython3.7m.dylib
/Users/Joao/anaconda3/lib/libpython3.7m.nolto.a

but it seems the linker uses the .dylib ...

**Comment by ronaldoussoren** [comment]
Sorry about the very short response yesterday, I could have provided some more information that helped you do the right thing.  Adding ``-undefined dynamic_lookup`` to the linker step ensures you won't get errors when linking, missing symbols will be looked up at runtime.

It might still be useful to have a second target that does link to libpython, just to get build errors when using symbols that don't exist (for example due to a typo).

Setuptools does the right thing automatically. I had expected that ``python3-config`` to print the correct flags as well, but I just noticed it doesn't include these flags. I haven't checked yet if that is intentional.

Getting the flags to used can be done using some python code though:

```
>>> sysconfig.get_config_var('LDSHARED')
'clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -Wl,-headerpad,0x1000'
```

The ``-headerpad`` option isn't really necessary, but can help in some manipulating the binary later (for example when using a tool like py2app to create standalone applications).

**Comment by diasjoaocarlos** [comment]
Thank you @ronaldoussoren 

This is the solution. Now I can make my extension in OS X.
