### ISSUE TITLE
bisect.insort crashes the interpreter if key is a string

### ISSUE THREAD

**Issue by PaulWGraham** [python/cpython#92839]
**Crash report**

The following code will crash the interactive interpreter. 

```
import bisect

x = []
y = {'a': 2 , "b" : 1 }
bisect.insort(x, y, key='b')
```

**Error messages**

None. Just dumped back to the command line from the interactive interpreter.  

**Your environment**

- CPython versions tested on:
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

- Operating system and architecture:
Edition	Windows 10 Pro
Version	21H2
Installed on	‎7/‎28/‎2021
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by stevendaprano** [comment]
Verified that there is a segmentation fault on Linux too, using Python 3.10.0.

**Comment by oda-gitso** [comment]
There appears to be a typo in the implementation: [_bisectmodule.c](https://github.com/python/cpython/blob/main/Modules/_bisectmodule.c) (line number 131).  I think that instead of `if (x == NULL)`, `if (key_x == NULL)` was intended. This fixes it for me.

**Comment by rhettinger** [comment]
Confirmed.
