### ISSUE TITLE
logging: Surprising call to basicConfig()

### ISSUE THREAD

**Issue by Gaasmann** [python/cpython#92859]
**Documentation**

Hello,

I just got surprised by a behavior of the `logging` module where a call to `logging.debug()` (or any level) [will call basicConfig()](https://github.com/python/cpython/blob/00f22e8cc234aa52ec1f28094a170d7b87d0d08f/Lib/logging/__init__.py#L2157) if no handler is set on the root logger but a call to `Logger.debug()` [won't](https://github.com/python/cpython/blob/00f22e8cc234aa52ec1f28094a170d7b87d0d08f/Lib/logging/__init__.py#L1467).

This issue was already discussed on #79711 and therefore, I would not discuss the behavior itself. Rather, I am wondering if the documentation displays this behavior enough. I agree that it is documented, but I think this is still misleading because:

- the behavior is documented in a paragraph in the middle of the [Advanced Logging Tutorial](https://docs.python.org/3.10/howto/logging.html#advanced-logging-tutorial)
- A paragraph named "[What happens if no configuration is provided](https://docs.python.org/3.10/howto/logging.html#what-happens-if-no-configuration-is-provided)" explains how logging.lastResort is used but makes no mention of `basicConfig()` being called by `logging.debug()`
- the call to basicConfig() isn't described on the documentation of [logging.debug()](https://docs.python.org/3.10/library/logging.html#logging.debug) itself.

If people agree that this is an issue, I would propose that I make a PR to add a paragraph to [logging.debug()](https://docs.python.org/3.10/library/logging.html#logging.debug) to describe the behavior.

Let me know what you think!

Thanks

**Comment by vsajip** [comment]
> would propose that I make a PR to add a paragraph to [logging.debug()](https://docs.python.org/3.10/library/logging.html#logging.debug) to describe the behavior

Yes, that's fine, and perhaps you should also add a paragraph in the "Basic Tutorial"'s "A simple example" section, adding not much detail (as it's an introductory section) but perhaps just a mention of :func:`basicConfig()` ?

**Comment by Gaasmann** [comment]
Sure thing, I'll make a PR. Thanks!
