### ISSUE TITLE
syntax parsing for `except*` appears a little too lenient (PEP 654)

### ISSUE THREAD

**Issue by asottile** [python/cpython#92862]
**Bug report**

these are all allowed by the current grammar, but I would argue that they should not be, especially given the documentation refers to it as the `except*` keyword:

```python
try:
    ...
except * Exception:  # space before the `*`
    ...
except*Exception:  # no space at all
    ...
except *Exception:  # no space after
    ...
except      *      Exception:  # just for funsies
    ...
```

my proposal is that `except*` is only valid without whitespace before the star and with whitespace after the star

**Your environment**

- CPython versions tested on: 3.11.0b1
- Operating system and architecture: linux x86_64

**Comment by sweeneyde** [comment]
For context, the motivation was discussed here: https://mail.python.org/archives/list/python-dev@python.org/thread/4B256YKUPW5P2M44GG5H6FBL3PSV6ODP/#7KHAN76UA5JRND2M2EMVLKML665KQDTC

**Comment by iritkatriel** [comment]
Isn't this a problem for linters? Syntactically all forms are correct, we don't enforce formatting in the parser.

**Comment by asottile** [comment]
normally I would say yes this is a linter's responsibility -- but the pep and all the documentation refers to this as a **new `except*` keyword** -- and that the `*` can be orphaned from the `except` feels like a bug.  of the cases above I would *definitely* like to see 1, 3, and 4 enforced as illegal by the parser (the `except*` keyword should remain intact).  case 2 feels more in linter territory (similar to `1or True` -- though that now raises a `SyntaxWarning` if I recall correctly)

**Comment by iritkatriel** [comment]
CC @pablogsal @gvanrossum 

I think this would require ‘except*’ to be a token. Not sure if there’s another way.

**Comment by pablogsal** [comment]
> CC @pablogsal @gvanrossum 
> 
> I think this would require ‘except*’ to be a token. Not sure if there’s another way.

The parser doesn't "see" whitespace so the only way to enforce this is in the lexer. We would need `except*` to be a token as @iritkatriel mentioned but we would also need a bunch of error messages because just getting "syntax error" because the * is one space away from the `except` is going to be quite confusing.

I would prefer not to go this route, personally.

**Comment by gvanrossum** [comment]
Let’s not enforce this in the parser.
