### ISSUE TITLE
Minor fix in cmathmodule.c

### ISSUE THREAD

**Issue by Djacon** [python/cpython#92879]
Hello everyone, just a quick question: why does the cmathmodule.c on line 644 takes [this](https://github.com/python/cpython/blob/main/Modules/cmathmodule.c#L664) approach? 
Specifically this line: `(am-1)*(am+1)+an*an`.

Why we can't replace this line by: `am*am - 1 + an*an`?

I was comparing both of these approaches and the second one gave me more accuracy, what with real numbers and what with complex numbers.

Thanks

**Comment by serhiy-storchaka** [comment]
Because it would be less accurate.

Consider the case `an=0`, `am=1+2**-27`. The current formula returns an exact result `2**-26 + 2**-54`, your formula returns just `2**-26`.

**Comment by Djacon** [comment]
Hmm, indeed. Now i see, thanks
