### ISSUE TITLE
Remove typing.io and typing.re

### ISSUE THREAD

**Issue by srittau** [python/cpython#92871]
As discussed in #82472 and mentioned in the [documentation](https://docs.python.org/3/library/typing.html#typing.IO), the `typing.io` and `typing.re` submodules are scheduled for removal in Python 3.12. They've been deprecated since Python 3.8.

I'm preparing a PR.

(Side note: There doesn't seem to be a matching issue template for this kind of issue.)

* PR: gh-98958

* PR: gh-98985

* PR: gh-98986

* PR: gh-92873

**Comment by srittau** [comment]
Cc @gvanrossum and @JelleZijlstra as resident typing experts.

**Comment by srittau** [comment]
PR: #92873 (didn't get linked automatically?)

**Comment by arhadthedev** [comment]
@srittau Bedevere the bot has this feature disabled for a while. python/bedevere#430 will enable it back after merging (i believe it's on feedback gathering stage).

**Comment by srittau** [comment]
Interestingly, import from `typing.re` or `typing.io` never worked at type check time. Since typeshed doesn't include those namespaces, when `--ignore-missing-imports` is used, any imports from those namespaces were silently assumed to by `Any`.
