### ISSUE TITLE
some tests fail with -O (assertions off)

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#92886]
On main (3.12 branch):

% ./python.exe -Om test -j2
[...]
10 tests failed:
    test_clinic test_coroutines test_dis test_imaplib
    test_multiprocessing_forkserver test_multiprocessing_spawn
    test_py_compile test_sys_settrace test_wsgiref test_zipimport

This seems wrong because
(1) it indicates that some assertions should be exceptions instead. 
(2) it implies that we don't have a buildbot testing with -O

- [x] test_clinic
- [x] test_coroutines
- [x] test_dis
- [x] test_imaplib
- [x] test_multiprocessing_forkserver
- [x] test_multiprocessing_spawn
- [x] test_py_compile
- [x] test_sys_settrace
- [x] test_wsgiref
- [x] test_zipimport

**Comment by arunsl** [comment]
Could reproduce issue with 4 test cases in windows with Python 3.9:

> python -Om test -j2 test_clinic test_coroutines test_dis test_imaplib test_multiprocessing_forkserver test_multiprocess
ing_spawn test_py_compile test_sys_settrace test_wsgiref test_zipimport
0:00:00 Run tests in parallel using 2 child processes
0:00:01 [ 1/10] test_clinic skipped
test_clinic skipped -- clinic directory could not be found
0:00:01 [ 2/10/1] test_coroutines failed
test test_coroutines failed -- Traceback (most recent call last):
  File "...\test\test_coroutines.py", line 1265, in test_with_5
    run_async(func())
AssertionError: AssertionError not raised
0:00:31 load avg: 0.00 running: test_dis (30.0 sec), test_imaplib (30.0 sec)
0:00:36 load avg: 0.00 [ 3/10/1] test_dis passed -- running: test_imaplib (34.8 sec)
0:00:36 load avg: 0.00 [ 4/10/1] test_imaplib passed (34.4 sec)
0:01:06 load avg: 0.22 running: test_multiprocessing_forkserver (30.0 sec), test_multiprocessing_spawn (30.0 sec)
0:01:36 load avg: 0.16 running: test_multiprocessing_forkserver (1 min), test_multiprocessing_spawn (1 min)
0:01:58 load avg: 0.11 [ 5/10/1] test_multiprocessing_forkserver skipped -- running: test_multiprocessing_spawn (1 min 22 sec)
test_multiprocessing_forkserver skipped -- forkserver is not available on Windows
0:01:58 load avg: 0.11 [ 6/10/1] test_multiprocessing_spawn passed (1 min 21 sec)
0:01:59 load avg: 0.11 [ 7/10/1] test_sys_settrace passed
0:01:59 load avg: 0.11 [ 8/10/2] test_py_compile failed
test test_py_compile failed -- multiple errors occurred; run in verbose mode for details
0:01:59 load avg: 0.11 [ 9/10/3] test_wsgiref failed
test test_wsgiref failed -- multiple errors occurred; run in verbose mode for details
0:01:59 load avg: 0.11 [10/10/4] test_zipimport failed
test test_zipimport failed -- multiple errors occurred; run in verbose mode for details

== Tests result: FAILURE ==

4 tests OK.

4 tests failed:
    test_coroutines test_py_compile test_wsgiref test_zipimport

2 tests skipped:
    test_clinic test_multiprocessing_forkserver

Total duration: 1 min 59 sec
Tests result: FAILURE



> python -m test -j2 test_coroutines test_py_compile test_wsgiref test_zipimport
0:00:00 Run tests in parallel using 2 child processes
0:00:01 [1/4] test_py_compile passed
0:00:01 [2/4] test_coroutines passed
0:00:02 [3/4] test_wsgiref passed
0:00:02 [4/4] test_zipimport passed

== Tests result: SUCCESS ==

All 4 tests OK.

**Comment by jackh-ncl** [comment]
Was able to reproduce this. I have a draft PR here: https://github.com/python/cpython/pull/93174 😃

**Comment by brettcannon** [comment]
I have created a checklist of the failing tests and checked off the ones that look to have merged PRs that fixed them.

**Comment by iritkatriel** [comment]
Thank you @jackh-ncl !
