### ISSUE TITLE
dataclasses.is_dataclass doesn't always work correctly with Generic types

### ISSUE THREAD

**Issue by Lyle-Alloy** [python/cpython#92893]
This was introduced by [BPO45663](https://bugs.python.org/issue45663).

```python
>>> import typing
... import dataclasses
... 
... T = typing.TypeVar("T")
... 
... @dataclasses.dataclass
... class A(typing.Generic[T]):
...     x: T
...     
>>> dataclasses.is_dataclass(A)
True
>>> dataclasses.is_dataclass(A[float])
False
>>> dataclasses.is_dataclass(A(0))
True
>>> dataclasses.is_dataclass(A[float](0))
True
```

That second `dataclasses.is_dataclass` call should be `True`

Bug reproduced on cpython 3.9.12 `x86_64-linux-gnu`

**Comment by JelleZijlstra** [comment]
I can see how this is confusing, but changing the behavior here may be risky. Right now you can assume that if `is_dataclass(o)` returns true, you can access `o.__dataclass_fields__`. But `A[float]` doesn't have a `__dataclass_fields__` attribute. I don't know what you're using `is_dataclass()` for, but it seems reasonable that a lot of people would use it before checking `__dataclass_fields__` for introspection.

So I don't think we should change this in any of the bugfix branches. We could change it on main, but it may be safer to keep the current behavior and document it.

**Comment by AlexWaygood** [comment]
> Right now you can assume that if `is_dataclass(o)` returns true, you can access `o.__dataclass_fields__`.

I don't think `__dataclass_fields__` is a public attribute (@ericvsmith, correct me if I'm wrong!), so users probably shouldn't be accessing it directly anyway. But you can say the same thing with respect to `dataclasses.fields()`: currently, any class for which `dataclasses.is_dataclass()` returns `True` can be safely passed to `dataclasses.fields()`. Changing that might be unfortunate.

**Comment by ericvsmith** [comment]
Yes, you should use `dataclasses.fields()` to access the fields, and not inspect `o.__dataclass_fields__`.

Instead of checking first, you can also just try `dataclasses.fields()` and catch the `TypeError` if it's not a dataclass.

**Comment by Penchekrak** [comment]
Perhaps, something should be done with `typing._GenericAlias` initialization so it would set `__dataclass_fields__` for its instance. The fact that `A[float]` does not have such information despite logically being a dataclass with specified types, defaults, etc, really sounds like a bug to me.

**Comment by JelleZijlstra** [comment]
Thinking about this again, I'd prefer to leave the behavior unchanged here. A GenericAlias is not a class, it is a special construct used in typing that proxies some behavior to the class. Trying to make it behave exactly like a class is going to be a never-ending project, and is itself bound to cause problems because at the end of the day, a GenericAlias is not in fact a class.

`is_dataclass()` is documented as "Returns True if obj is a dataclass or an instance of a dataclass." A GenericAlias of a dataclass is not a dataclass and is definitely not an instance of a dataclass. So I think the current behavior is correct.

**Comment by hauntsaninja** [comment]
I agree with Jelle and strongly agree with Alex's point about `is_dataclass` needing to being usable as a guard for `fields`
