### ISSUE TITLE
macOS Monterey 16" M1 Pro  _gdbm and _tkinter not found

### ISSUE THREAD

**Issue by Sr-316** [python/cpython#92895]
**Documentation**

(A clear and concise description of the issue.)

I followed the documentation to configure and build repo but got this issue:

configure: creating Modules/Setup.local
configure: creating Makefile
asset-overflow@MontereyJack:~/myRepos/cpython
main ✔ $ make -s -j2
Note: Deepfreeze may have added some global objects,
      so run 'make regen-global-objects' if necessary.
 CC='gcc' LDSHARED='gcc -bundle -undefined dynamic_lookup    ' OPT='-g -Og -Wall' 	./python.exe -E ./setup.py -q build
ld: warning: directory not found for option '-L/usr/lib/termcap'

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_gdbm                 _tkinter
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

renaming build/scripts-3.12/pydoc3 to build/scripts-3.12/pydoc3.12
renaming build/scripts-3.12/idle3 to build/scripts-3.12/idle3.12
renaming build/scripts-3.12/2to3 to build/scripts-3.12/2to3-3.12

I had already read through and installed openssl gdbm etc.. exactly per documentation and also added the necessary flags per macOS instructions for ./configure --with-pydebug --with-openssl=$(brew --prefix openssl) 

forgive me if there's anything here that might be a little off (in the last sentence/statement) since I didn't copy/paste it, but I even went back over twice after "make clean" and retry configure and make -s -j2

**Comment by erlend-aasland** [comment]
You can tell `configure` where to find the dependencies either by modifying `PKG_CONFIG_PATH`, or by using the following environment variables:

```console
$ ./configure --help | grep -i "\(tcl\|gdbm\).*flags"
  TCLTK_CFLAGS
  TCLTK_LIBS  linker flags for TCLTK, overriding pkg-config
  GDBM_CFLAGS C compiler flags for gdbm
  GDBM_LIBS   additional linker flags for gdbm
```

For example, In my build script, I modify `PKG_CONFIG_PATH` by adding `$(brew --prefix tcl-tk)/lib/pkgconfig`.

**Comment by zware** [comment]
See also gh-80086.

**Comment by erlend-aasland** [comment]
> See also [gh-80086](https://github.com/python/cpython/issues/80086).

Yes, I suggest closing this[^1] in favour of gh-80086.

[^1]: "close as not planned"

**Comment by feoh** [comment]
@ambv This PR works great on MacOS latest under WezTerm, Terminal.app and Kitty
