### ISSUE TITLE
changes to PyObject casting macros causing build failures with python-greenlet

### ISSUE THREAD

**Issue by tacaswell** [python/cpython#92898]
**Bug report**

There have been changes to how the macros for casting PyObject pointers per https://github.com/python/cpython/pull/91959#issuecomment-1114651243  by @vstinner any new compiler warnings are a regression.  

There were two types of errors in greenlet, one related to const correctness which has been fixed via https://github.com/python/cpython/pull/92138) and one related to casting wrapper classes (that has not been fixed).

Per @serge-sans-paille in https://github.com/python/cpython/pull/92138#issuecomment-1116983125

> That's an interesting situation: greenlets are written in C++, and the object that raises issues is of type greenlet::refs::OwnedErrPiece that has a conversion operator to PyObject* (namely: https://github.com/python-greenlet/greenlet/blob/be41e1a24925326b72a02ef5cb6d1ed9643eb062/src/greenlet/greenlet_refs.hpp#L924 ) Using C-style cast or static_cast directly uses that operator so that's fine. But a reinterpret_cast won't work.

and suggests a patch to CPython.

https://github.com/python-greenlet/greenlet/pull/302 is a fix on the greenlet side.

The key line of the error is

```
src/greenlet/greenlet_refs.hpp: In member function ‘void greenlet::refs::PyErrPieces::normalize()’:
/home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:30:25: error: invalid cast from type ‘greenlet::refs::OwnedErrPiece’ to type ‘const PyObject*’ {aka ‘const _object*’}
   30 |        const_cast<type>(reinterpret_cast<const type>(expr))
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is also affecting https://github.com/python/pyperformance/issues/198

A bunch of links: https://github.com/python/cpython/issues/92800#issuecomment-1126809930

**Your environment**

- CPython versions tested on: main branch
- Operating system and architecture: linux and x86_64

**Comment by vstinner** [comment]
> @corona10 corona10 assigned vstinner 4 hours ago 

Well, you can assign the issue to me, but I'm not sure that I have the C++ skills to fix this specific issue.

**Comment by corona10** [comment]
> Well, you can assign the issue to me, but I'm not sure that I have the C++ skills to fix this specific issue.

Okay, I will also take a look at this issue too.

**Comment by vstinner** [comment]
I wrote a simple C++ program to test casts of many types to ``PyObject*``: [py_cast.cpp.txt](https://github.com/python/cpython/files/8727501/py_cast.cpp.txt)

@serge-sans-paille's [approach using templates](https://github.com/python/cpython/pull/92138#issuecomment-1116983125) works in all cases:

```c++
template<typename type, typename expr_type>
type _Py_reinterpret_cast_impl(expr_type* expr)  { return reinterpret_cast<type>(expr);}

template<typename type, typename expr_type>
type _Py_reinterpret_cast_impl(expr_type const * expr)  { return reinterpret_cast<type>(const_cast<expr_type*>(expr));}

template<typename type, typename expr_type>
type _Py_reinterpret_cast_impl(expr_type & expr)  { return static_cast<type>(expr);}

template<typename type, typename expr_type>
type _Py_reinterpret_cast_impl(expr_type const & expr)  { return static_cast<type>(const_cast<expr_type &>(expr));}

#define _Py_CAST(type, expr) _Py_reinterpret_cast_impl<type>(expr)
```

**Comment by vstinner** [comment]
PEP 670 converted more macros to static inline functions. While doing this work, I tried to fix C++ compiler warnings on "old-style cast" by adding _Py_CAST() and _Py_STATIC_CAST(). I tried to minimize the quantity of C++ code in the Python C API header files: in short, it's mostly **2 lines** which use ``static_cast<>``, ``reinterpret_cast<>`` and ``const_cast<>``.

The problem is that my implementation doesn't cover all cases: it doesn't cover greenlet case which implements a class which has a cast operator to ``PyObject*`` on a class which does not inherit from ``PyObject``. The class only contains contains a private **pointer** to an object.
