### ISSUE TITLE
multiprocessing is not worked, when use type module.

### ISSUE THREAD

**Issue by AlitaIcon** [python/cpython#92920]
```python

import os
from multiprocessing import Pool


def run(cls, s):
    print(os.getpid())
    print(cls.__dict__)
    print(cls, s)


class A:
    a = 2

    def __str__(self):
        return self.__class__.__name__


b = type("B", (A,), {})
e = b()


class C(A): pass


if __name__ == '__main__':
    p = Pool()
    print(b.__dict__)
    p.apply_async(func=run, args=(A, "111",))
    p.apply_async(func=run, args=(b, "222",))
    p.apply_async(func=run, args=(C, "333",))
    p.apply_async(func=run, args=(e, "444",))
    p.close()
    p.join()
    while 1:
        pass

```
**Bug report**

Multiprocessing.Pool cannot worked, when I pass in the object created by type. You can try the above code

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

**Your environment**

- CPython versions tested on:
- Operating system and architecture:
os: windows 10
python: 3.6.8

**Comment by AlitaIcon** [comment]
```python
import os
import threading


def run(cls, s):
    print(os.getpid())
    print(cls.__dict__)
    print(cls, s)


class A:
    a = 2

    def __str__(self):
        return self.__class__.__name__


b = type("B", (A,), {})
e = b()


class C(A): pass


if __name__ == '__main__':

    threading.Thread(target=run, args=(A, "111",)).start()
    threading.Thread(target=run, args=(b, "222",)).start()
    threading.Thread(target=run, args=(C, "333",)).start()
    threading.Thread(target=run, args=(e, "444",)).start()
    while 1:
        pass
```
But threading is worked

**Comment by AlitaIcon** [comment]
It should be that the object created by type has no reference attribute, so the object cannot be found in multiple processes.(i guess)

**Comment by AlitaIcon** [comment]
Multiprocessing.Pool cannot worked, when I pass in the object created by type. You can try the above code
But the obj created by class, it`s worked, such as C.run is worked.  b.run is not worked.

**Comment by ronaldoussoren** [comment]
This may be platform dependent, but at least on some platforms (Windows, macOS) the data that is passed to a subprocess using multiprocessing is seriallzed using pickle.  Unpicking "b" won't work because it is a class whose ``__name__`` is "B" and because of that unpicking tries to access ``__main__.B`` which does not exist in your script.

This is described in <https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods>.

**Comment by serhiy-storchaka** [comment]
Make type B accessible by name:
```python
B = type("B", (A,), {})
```

Closed as "won't fix".

**Comment by AlitaIcon** [comment]
> Make type B accessible by name:
> 
> ```python
> B = type("B", (A,), {})
> ```
> 
> Closed as "won't fix".

It`s not pythonic, though  you may be right.
