### ISSUE TITLE
Documentation of `argparse.add_argument`s `append` should mention `dest`

### ISSUE THREAD

**Issue by jugmac00** [python/cpython#92928]
The current documentation of `append` shows this example:

```
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', action='append')
>>> parser.parse_args('--foo 1 --foo 2'.split())
Namespace(foo=['1', '2'])
```

Working then with `foo`, which indeed is a collection of `foos` felt wrong, but I did not know what to do about it.

A colleague pointed out that there is the `dest` keyword, so you can rewrite this as...

```
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', action='append', dest='foos')
>>> parser.parse_args('--foo 1 --foo 2'.split())
Namespace(foos=['1', '2'])
```

I think it would be a good idea to keep the current version of the example, but to reference the `dest` keyword to get a proper naming for the collection of values.

If this sounds about right, I'd like to create a pull request.

**Comment by erlend-aasland** [comment]
The very first `argparse` example uses the `dest` keyword. There is more than a handful of other examples that use the `dest` keyword.

**Comment by erlend-aasland** [comment]
FTR, this is the very first example shown in the `argparse` docs:

```py
import argparse

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('integers', metavar='N', type=int, nargs='+',
                    help='an integer for the accumulator')
parser.add_argument('--sum', dest='accumulate', action='store_const',
                    const=sum, default=max,
                    help='sum the integers (default: find the max)')

args = parser.parse_args()
print(args.accumulate(args.integers))
```

**Comment by erlend-aasland** [comment]
Would you like to propose a change in a PR?

**Comment by rhettinger** [comment]
> In my print preview, the API reference is 32 pages.

I would like for this situation to not be made worse by adding more volume.   The reference needs to be smaller and has already gone egregiously far with too many mostly repetitive examples.

If you want to submit a PR, look at modifying the argparse howto guide.  It is intended to be a tutorial.  IN contrast, the main reference needs to be more compartmentalized.

**Comment by jugmac00** [comment]
The reference from `append` to `dest` would make so much sense.

![Screenshot from 2022-05-19 21-43-24](https://user-images.githubusercontent.com/9895620/169394703-de590a19-6cfc-40c3-a5d6-6147085afc79.png)

 What if I could shorten it to one additional line? :-)

The tutorial neither refers to `dest` nor to `append`, so it would need a whole new section.

I still would prefer the change in the API reference.

I do not think 32 or even more pages are worse - it is an API reference, you go the the thing you want to look up, it is just nothing I would want to read from top to bottom.

**Comment by facundobatista** [comment]
+1 to a **small** comment about `dest` in the `append` section

**Comment by slateny** [comment]
If someone uses `append`, wouldn't they first go to the `add_argument` section and notice the `dest` arg? I would concur with the change if `dest` was used solely for `append`, but it looks like it can be used with various other arguments, so to me it doesn't seem too appropriate to add this note just for `append`.

A quick search on the argparse howto page shows no sections on using `dest`, so I would agree that inserting the short sentence there seems a bit better.

**Comment by jugmac00** [comment]
Hey @slateny,

I cannot speak for others, I can only speak for myself.

When I wanted to use `append`, I directly went to the API documentation for `append`, and I did not look up `add_argument`.

I can only repeat that while `dest` might be used in other combinations, `append` and `dest` are natural fits, as at least I collect single items with `append` and then want to work with a more appropriate name in plural form.

Unlike the mentioned suggestions, I do not think that the tutorial is the best place for this information.

If the Python documentation picks up the Diátaxis framework, this information might fit in a how-to, though.

Until then, as a long-term Python user, I would not visit the tutorial page, work through dozens of pages to maybe learn something new, but I usually go straight to the API documentation. Unlike other opinions expressed here, I do not think an API documentation needs to be "smaller", imho it needs to be comprehensive, and imho the difference between a complete and a really good API documentation are those little gems of information like the mentioned fit between `append` and `dest`.

**Comment by serhiy-storchaka** [comment]
I concur with @rhettinger and @hpaulj. The root of this issue is that the volume is so large, that users do not read the whole documentation. Increasing it even more will make it less accessible. The `dest` parameter is already documented on its own place. We should only add more information if it is an exception from the general rule, or not so obvious.
