### ISSUE TITLE
Virus found in parser.py

### ISSUE THREAD

**Issue by KwisatzJim** [python/cpython#92944]
I updated yt-dlp with 'brew upgrade' and my antivirus software found Win.Virus.Tirusor-9950253-0 in parser.py which is in one of the subdirectories used.  Anyone else seeing this?  Is this a false positive?

![image](https://user-images.githubusercontent.com/131250/169235301-b9949b3d-95f3-4dff-b57b-7009cdbd0f1d.png)

yt-dlp: stable 2022.5.18 (bottled), HEAD
Fork of youtube-dl with additional features and fixes
https://github.com/yt-dlp/yt-dlp
/opt/homebrew/Cellar/yt-dlp/2022.5.18 (2,211 files, 24.4MB) *
  Poured from bottle on 2022-05-18 at 17:55:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yt-dlp.rb

**Comment by erlend-aasland** [comment]
I'd report this at the Homebrew issue tracker.

**Comment by KwisatzJim** [comment]
I reported to homebrew and they said "Homebrew doesn't actually write the software it packages. You should report this to the developers of whatever is triggering the antivirus."

So I reported to yt-dlp and they said "That's an false positive related to pip, and it should be reported to that. Closing as external issue."

Is pip part of python? Not sure who this should go to. Or if it's really just a false positive if it even needs to be reported?

**Comment by erlend-aasland** [comment]
The pip issue tracker is found here: https://github.com/pypa/pip/issues
