### ISSUE TITLE
Fraction module in IDLE gives some incorrect results

### ISSUE THREAD

**Issue by KevinGlentworth** [python/cpython#92940]
**Bug report**

4 values supplied to Fraction return incorrect results.
print(Fraction(2.01))
2/1
print(Fraction(2.03))
101/50
print(Fraction(2.05))
51/25
print(Fraction(2.07))
103/50

**Your environment**

- CPython versions tested on: IDLE 3.10.4, IDLE 3.9.7
- Windows 11, 8Gb RAM, Intel Core i5-8250U

![python_fraction_bug](https://user-images.githubusercontent.com/105771861/169201295-a63621b4-4304-44db-8486-587d0526fa9a.png)

**Comment by ronaldoussoren** [comment]
How did you install the "fraction" module? The standard library module that supports fractions is named "fractions" and not "fraction" (not the additional 's' in the name of the standard library module).

The stdlib version also behaves differently:

```
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fractions import Fraction
>>> print(Fraction(2.03))
4571153621781053/2251799813685248
>>>
>>> from faction import Fraction
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faction'
```

**Comment by ronaldoussoren** [comment]
There is a fraction module on PyPI: https://pypi.org/project/Fraction/

I expect that you are having a problem with that module. Please either file and issue with that project, or use the stdlib fractions module.

**Comment by Crystalline-Entity** [comment]
Your from statement above, has a spelling error. You refer to faction, not fraction.

I will log this on the Fraction module page.
