### ISSUE TITLE
Comments in struct pool_header is not accurate

### ISSUE THREAD

**Issue by zikcheng** [python/cpython#92953]
```
struct pool_header {
    union { block *_padding;
            uint count; } ref;          /* number of allocated blocks    */
    block *freeblock;                   /* pool's free list head         */
    struct pool_header *nextpool;       /* next pool of this size class  */
    struct pool_header *prevpool;       /* previous pool       ""        */
    uint arenaindex;                    /* index into arenas of base adr */
    uint szidx;                         /* block size class index        */
    uint nextoffset;                    /* bytes to virgin block         */
    uint maxnextoffset;                 /* largest valid nextoffset      */
};
```

Pools in the linked list `arena.freepools` are not guaranteed in the same size class. So comment in the line below may be not accurate.
```
struct pool_header *nextpool;       /* next pool of this size class  */
```

### Linked PRs
* gh-124996
* gh-125545

**Comment by erlend-aasland** [comment]
This comment has been in the code for decades; it was introduced by Neil Schemenauer in 2001. It's documenting a strictly internal API, and it has not caused confusion within the core dev team since 2001. I don't think we need to amend this now.

**Comment by ericsnowcurrently** [comment]
CC @nascheme

**Comment by nascheme** [comment]
I think the comment is correct but only some of the time.  It depends which linked-list the pool is on.  If it's on the `usedpools` list then they are all the same size class.  I'll try to clarify it.
