### ISSUE TITLE
None is not a valid value for ast.ImportFrom.level

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#92986]
For example:
```
import ast
tree = ast.parse("from x import y")
tree.body[0].level = None
ast.unparse(tree)  # raises
```

This is very similar to https://bugs.python.org/issue46289 and https://github.com/python/cpython/pull/30467 cc @isidentical

Note the compiler does seem to allow it, but it's always an int in practice and documented as such

Discovered in typeshed.

**Comment by isidentical** [comment]
Thanks for the fix @hauntsaninja.
