### ISSUE TITLE
Bogus syntax error on "nonlocal"

### ISSUE THREAD

**Issue by snoopyjc** [python/cpython#92983]
**Bug report**

nonlocal statement on a loop var gives a syntax error.  For example:

    for name in ['red', 'blue', 'green']:
        def myfun(*args):
            nonlocal name

Per the `for` loop documentation, "Each item in turn is assigned to the target list using the standard rules for assignments (see [Assignment statements](https://docs.python.org/3/reference/simple_stmts.html#assignment)), and then the suite is executed"

**Your environment**

- CPython versions tested on: 3.10.1
- Operating system and architecture: Windows 10

**Comment by JelleZijlstra** [comment]
In your example, you should use `global` instead. `nonlocal` should be used when the outer assignment is itself in a nested scope such as a function.

**Comment by stevendaprano** [comment]
For future reference @snoopyjc this has nothing to do with loop variables. If you try the same with a non-loop variable, you get the same syntax error:

```
name = ;joe'
def f():
    nonlocal name
    print(name)
```
gives the same `SyntaxError: no binding for nonlocal 'i' found`.

In this case the relevant docs are for [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#the-nonlocal-statement), and [the FAQs](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result). Note the last line of that FAQ entry.
