### ISSUE TITLE
The compatibility problems start with expat 2.4.4, not just 2.4.5

### ISSUE THREAD

**Issue by mcepl** [python/cpython#93018]
This
https://github.com/python/cpython/blob/f20a6a54fb041507a334ad71706974960d1b473f/Lib/test/test_minidom.py#L1152
and this
https://github.com/python/cpython/blob/f20a6a54fb041507a334ad71706974960d1b473f/Lib/test/test_minidom.py#L1620
is wrong. Change of raised errors happened already in 2.4.4 not only in 2.4.5.

**Comment by corona10** [comment]
@hartwork Would you like to take look at this issue?

**Comment by hartwork** [comment]
> @hartwork Would you like to take look at this issue?

@corona10 had a quick look now, commented at https://github.com/python/cpython/pull/93022#pullrequestreview-992007983 . Thanks for bringing this to my attention. :+1:

**Comment by corona10** [comment]
closing the issue: https://github.com/python/cpython/pull/93022#issuecomment-1145415371

Thank you @hartwork
