### ISSUE TITLE
LTO fails to build on 10.5.x–10.6.x due to -Wl,-export_dynamic flag not understood by gcc

### ISSUE THREAD

**Issue by barracuda156** [python/cpython#93045]
**Bug report**

Pythons presently do not build with `+lto` on older macOS. The problem is that `configure` applies flags that compiler does not understand. Patching out those fixes the build: https://github.com/macports/macports-ports/pull/14816/files#diff-77fb5d41c051fffdedeba53d495bf1a00818b75e81ecd2c28c59dfb87018f8a8
In particular, `LTOFLAGS="-flto -Wl,-export_dynamic"` should be changed to `LTOFLAGS="-flto"` for macOS < 10.10.

I submitted the fix to Macports, but the port maintainer advised me to try fixing it in the upstream first.
I have confirmed that with my patch `python39` and `python310` build with `+lto` on 10.5.8, 10A190 and 10.6.8 for `ppc`, on 10.5.8 for `ppc64` and on 10.6.8 for `x86_64` (using `gcc11` across the board, since `gcc-4.2` does not understand `-flto`).

**Your environment**

- CPython versions tested on: `python39`, `python310`
- Operating system and architecture: macOS 10.5.8 (`ppc`+`ppc64`), macOS 10.6 PPC (`ppc`), macOS 10.6.8 (`ppc`, `x86_64`)

**Comment by ned-deily** [comment]
The simple solution is to don't use the `--with-lto` configuration option when building on these old long-unsupported systems. I see no reason to add more complexity to Python's `configure` for such a use case with a very tiny and ultimately shrinking audience. The beauty of open source is that you are free to make and maintain such changes yourself if you wish and if MacPorts wishes to.

**Comment by barracuda156** [comment]
@ned-deily If I make a test for that flag for it to be applied conditionally, can I open a PR then?
