### ISSUE TITLE
Wrap unused arguments in Objects/obmalloc.c with `Py_UNUSED`.

### ISSUE THREAD

**Issue by zikcheng** [python/cpython#93040]
As the title says, parameter `ctx` is not used in body of function pymalloc_alloc and pymalloc_free.

**Comment by erlend-aasland** [comment]
You'll find there's a lot of unused arguments in the CPython code base. We _could_ wrap these two in `Py_UNUSED`, but there would be a lot left, so I don't see a particular reason to just change these two.

Suggesting to close this.

**Comment by erlend-aasland** [comment]
cc. @vstinner

**Comment by erlend-aasland** [comment]
FTR:

https://github.com/python/cpython/blob/e5d8dbdd304935dbd0631ee9605efb501332f792/Objects/obmalloc.c#L1947-L1948

https://github.com/python/cpython/blob/e5d8dbdd304935dbd0631ee9605efb501332f792/Objects/obmalloc.c#L2217-L2218

**Comment by erlend-aasland** [comment]
The following functions in obmalloc.c have one or more unused arguments:

- `_PyMem_RawMalloc`
- `_PyMem_RawCalloc`
- `_PyMem_RawRealloc`
- `_PyMem_RawFree`
- `_PyObject_ArenaVirtualAlloc`
- `_PyObject_ArenaVirtualFree`
- `_PyObject_ArenaMmap`
- `_PyObject_ArenaMunmap`
- `_PyObject_ArenaMalloc`
- `_PyObject_ArenaFree`
- `address_in_range`
- `pymalloc_alloc`
- `pymalloc_free`

Victor says he's +1 on wrapping unused arguments with `Py_UNUSED`.

**Comment by zikcheng** [comment]
Why wrapping instead of removing, is it a convention?

**Comment by vstinner** [comment]
> Why wrapping instead of removing, is it a convention?

The *ctx* parameter is part of PEP 445 API.

**Comment by kumaraditya303** [comment]
Fixed by #93175
