### ISSUE TITLE
Unintentional changes in sqlite3.connect()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#93044]
There are some unintentional consequences of converting `sqlite3.connect()` to Argument Clinic in #40956.

1. The `database` argument always converted to bytes.
2. Keyword arguments are passed as positional arguments to `factory()`.
3. If an argument is not passed to `sqlite3.connect()`, its default value is passed to `factory()`.

It all works with the default `factory=Connection`, but `factory` can be an arbitrary callable, not completely compatible with `Connection()`. There may be a user code which uses a factory which only works with string `database` and does not support the `uri` argument. It worked fine in older versions when it is called with correct arguments, bet will become failing in 3.11.

This is a hypothetical scenario, but we should at least add a note about potential incompatibility. And I think that it is better to get rid of `PyUnicode_FSConverter` here.

**Comment by erlend-aasland** [comment]
FTR, sqlite3 was converted to Argument Clinic in gh-85128 (_bpo-40956_).

**Comment by erlend-aasland** [comment]
Sounds good to me.

**Comment by erlend-aasland** [comment]
Resolved with:

- main: gh-93046
- 3.11: gh-93048
