### ISSUE TITLE
Emoji causes IDLE to freeze or insert ghost chars

### ISSUE THREAD

**Issue by Moosems** [python/cpython#93052]
## When the user types an emoji into the IDLE terminal it causes it to freeze and the user can no longer to type. Another issue related to this is that when the user types an emoji while editing a file it repeats everything before it with ghost chars that don't have highlighting. This is related to [this](https://github.com/python/cpython/issues/85384) issue

# How to reproduce:
Python V3.9.10
Installation: python.org
Platform: Intel chip
Tcl/Tk version: 8.6
On a Mac go into IDLE and paste 💻. This causes it to freeze and the user can no longer type anything

Video of error:
https://user-images.githubusercontent.com/95927277/169656903-a1919930-931f-4f3a-ae24-82b838951359.mp4

**Comment by ned-deily** [comment]
Based on a glance at the video, you were using an out-of-date version of Python 3.9 (3.9.10) from the legacy macOS Intel-only installer variant which uses an out-of-date version of Tk 8.6 (8.6.8). Please retry your test using the current 3.9.13 universal2 macOS installer (not the Intel-only) version; it uses Tk 8.6.12. Also, be aware that Python 3.9 has now reached the security-fix-only phase of its life cycle so no further macOS installers for 3.9 will be produced; consider upgrading to Python 3.10.x, the current fully-supported version.

https://www.python.org/downloads/macos/
