### ISSUE TITLE
enum.EnumMeta renaming

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#93064]
#22392 renamed the `enum.EnumMeta` metaclass to `enum.EnumType`. This originally went into 3.10 and was reverted (#27010), but remained on 3.11.

The renaming caused some problems for me with introspection code that looks at the name of classes to find their stubs (quora/pyanalyze#537).

I don't see anything wrong with the old name (`EnumMeta`). Could we return to the `EnumMeta` name to avoid gratuitously making upgrades harder?

cc @ethanfurman for enum

**Comment by ethanfurman** [comment]
My apologies for the extra work.  I renamed it (and kept the old name as an alias) because I personally found it confusing when working with enums to have, for example, `SelectionEnum` be of type `EnumMeta` and not `EnumType`.

The change is not gratuitous.
