### ISSUE TITLE
Help me understand why a name in a class def sometimes goes to globals and sometimes to an enclosing function.

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#93067]
I've also posted this on Python Users Forum.  This might be a bug in the interpreter, but it's probably too late to go back and change behavior, so the current behavior should be blessed.  It might also be that the documentation could use some clarification.

Here is a sample program. It has a global variable named x and a function with a local variable named x. Inside this function are several classes which use x in a variety of ways, including setting it locally and/or defining new functions which capture it.

```
x = 'global x'
def f():
	x = 'f x'
	class C1:
		print('C1 = ', x)	# f x
	class D1:
		def g():
			print('D1.g = ', x)
		g()					# f x
	class C2:
		print('C2 = ', x)	# f x
	class D2:
		print('D2 = ', x)	# f x
		def g():
			print('D2.g = ', x)
		g()			# f x
	class C3:
		print('C3 = ', x)	# global x
		x = 'C3 x'
		print('C3 = ', x)	# C3 x
	class D3:
		print('D3 = ', x)	# global x
		def g():
			print('D3.g = ', x)
		g()					# f x
		x = 'D3 x'
		print('D3 = ', x)	# D3 x
		def g2():
			print('D3.g2 = ', x)
		g()					# f x
		g2()				# f x
	x = 'new f x'
	D1.g()					# new f x
	D2.g()					# new f x
	D3.g()					# new f x
	D3.g2()					# new f x
f()
```
_Why do C3 and D3 print out ‘global x’ whereas the others print out ‘f x’?_

I assume that Python is designed to work this way, but I can't figure out what the design is.  Perhaps the documentation on name resolution rules could be improved to make this clearer, or maybe it's just wrong.

I’ve looked at disassembly for this example. What I have noticed about various cases is:

-    The classes are built inside f() with a LOAD_CLOSURE bytecode for x, except C3, which has no closure.
-    The classes get the value of x with a LOAD_CLASSDEREF bytecode, except C3 and D3, which use LOAD_NAME.
-    All the nested functions are created using a LOAD_CLOSURE for x, and they reference x with a LOAD_DEREF.

[Here is the disassembly output](https://github.com/python/cpython/files/8749022/dis.txt)

**Comment by stevendaprano** [comment]
Here is a link to [the discussion](https://discuss.python.org/t/help-me-understand-why-a-name-in-a-class-def-sometimes-goes-to-globals-and-sometimes-to-an-enclosing-function/15905). It would have probably been better to wait for feedback there before posting a bug report here. (The bug tracker is not really intended as a help desk.)

I don't believe that this is a bug, although the docs may stand to be improved.

**Comment by mrolle45** [comment]
> It would have probably been better to wait for feedback there before posting a bug report here. (The bug tracker is not really intended as a help desk.)

I agree, now.  I wasn't sure how quickly I would get a response from Python Users, and I was just getting weary about the problem.  In the future, I'll trust Python Users to give me prompt help.
