### ISSUE TITLE
Fix contextvars HAMT implementation to handle iteration over deep trees

### ISSUE THREAD

**Issue by 1st1** [python/cpython#93065]
See https://github.com/MagicStack/immutables/issues/84 for more details.

**Comment by 1st1** [comment]
https://github.com/python/cpython/pull/93066

**Comment by molaxx** [comment]
Hey @1st1 as I found the bug and fixed it, can I open the PR  in cpython? i'll be honored to have a PR accepted in CPython!

**Comment by ambv** [comment]
Fixed all the way between 3.7 and 3.12. Thanks, @molaxx and @1st1!
