### ISSUE TITLE
Equality is not transitive on collections

### ISSUE THREAD

**Issue by fischbacher** [python/cpython#93069]
**Bug report**

Here are objects A, B, C that satisfy A==B, A==C, but fail to satisfy B==C:

 >>> B = collections.OrderedDict(["aA", "bB"])
 >>> C = collections.OrderedDict(["aA", "bB"][::-1])
 >>> A = dict(B)
 >>> A == B
 True
 >>> A == C
 True
 >>> B == C
 False

**Comment by AlexWaygood** [comment]
I think that this behaviour is expected and documented:

> Equality tests between `OrderedDict` objects are order-sensitive and are implemented as `list(od1.items())==list(od2.items())`. Equality tests between `OrderedDict` objects and other `Mapping` objects are order-insensitive like regular dictionaries.

https://docs.python.org/3/library/collections.html#collections.OrderedDict

**Comment by stevendaprano** [comment]
Transitivity of equality is certainly desirable, but I don't think it is promised anywhere, and I don't think it is possible. We have four conflicting requirements:

* dict equality should ignore order;
* OrderedDict equality should compare order;
* comparisons between dict and OrderedDict should be permitted;
* equality should be transitive.

There is a conflict in those four requirements, and the least worst one to give up is transitivity.

**Comment by rhettinger** [comment]
This was proposed by Antoine Pitrou and approved by Guido.  It is documented and tested.  That puts it firmly in the its-a-feature-not-a-bug category.

**Comment by fischbacher** [comment]
On: "That puts it firmly in the its-a-feature-not-a-bug category."

Unfortunately, doing things like that tend to also put Python in the category of "unsuitable for both teaching and serious use".

Please escalate this to Guido.

The problem is that such a design decision does heavy damage to language properties that are essential for reasoning about code. Thanks to this, the corresponding expected "equality makes sense" property does not even hold for anything else. Suppose I have three objects A,B,C that would all statically type as tuple[int, Mapping[str, str]].

When reasoning about code, it would not be valid to deduce that "A=B and A=C implies B=C".

Is it considered a guaranteed property that two mappings A, B are expected to satisfy A == B if and only if
(A is B or set(A.items()) == set(B.items()))?

If yes, then something that implements an incompatible notion of equality clearly cannot be a mapping.
(We see a similar situation with numpy.ndarray, which cannot be a Sequence, since a ndarray may
have a shape of (), i.e. "zero indices".)
