### ISSUE TITLE
List comprehension failure results in the merging of two items.

### ISSUE THREAD

**Issue by crispybacon** [python/cpython#93109]
**Bug report**

List comprehension failure results in the merging of two items.  I have verified this is not an issue on AMD with python 3.10 running Fedora 36.

**Your environment**

Apple M1, Python 3.10

```python
data_files = ['recipes.json', 'movies.json', 'chicago-taxi-data.csv', 'web.log', 'firewall.log', 
              'webapp.csv", webapp-tagged.csv', 'trips.csv', 'webapp-password-spraying-attemps.csv'
              'webapp-new-data.csv'
             ]
[x for x in data_files if x.endswith('csv')]
```
[Output]:
```python
['chicago-taxi-data.csv',
 'webapp.csv", webapp-tagged.csv',
 'trips.csv',
 'webapp-password-spraying-attemps.csvwebapp-new-data.csv']
```

**Comment by JelleZijlstra** [comment]
This has nothing to do with the list comprehension. You're missing a comma at the end of your second line, and adjacent string literals get implicitly concatenated.
