### ISSUE TITLE
enum.global_enum: `cls_name` undefined in `global_str`

### ISSUE THREAD

**Issue by The-Compiler** [python/cpython#93100]
**Bug report**

In acf7403f9baea3ae1119fc6b4a3298522188bf96 (#30582), @ethanfurman implemented a `global_enum` decorator, replacing the `__str__` of an enum with `enum.global_str`:

https://github.com/python/cpython/blob/760ec8940aabd6a7fc471bd913ea1ac501cc604b/Lib/enum.py#L1638-L1645

(This was later reverted in 42a64c03ec5c443f2a5c2ee4284622f5d1f5326c and reintroduced in 83d544b9292870eb44f6fca37df0aa351c4ef83a, but I believe the code to be the same).

If the `._name_` attribute is `None`, this uses `cls_name`, but that's not defined anywhere in that function!

Here is a (somewhat contrived) example:

```python
import enum

@enum.global_enum
class EnumTest(enum.Enum):
    VAL = 1

EnumTest.VAL._name_ = None

print(str(VAL))
```

this fails with:

```pytb
Traceback (most recent call last):
  File "/home/florian/tmp/x.py", line 9, in <module>
    print(str(VAL))
          ^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1646, in global_str
    return "%s(%r)" % (cls_name, self._value_)
                       ^^^^^^^^
NameError: name 'cls_name' is not defined
```

(Found by running `flake8` over `Lib/` out of curiosity, see https://github.com/python/cpython/issues/93010#issuecomment-1133402591)

**Your environment**

- CPython versions tested on: Python 3.11.0b1
- Operating system and architecture: Archlinux x86_64

**Comment by ethanfurman** [comment]
Fixed.
