### ISSUE TITLE
Missing brackets in docs: logging.handlers.SysLogHandler(address='localhost', SYSLOG_UDP_PORT,...

### ISSUE THREAD

**Issue by magnus-lycka** [python/cpython#93108]
**Documentation**

In https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SysLogHandler for Python 3.10.4,
the parentheses are missing for the address parameter, which is a tuple:

`class logging.handlers.SysLogHandler(address='localhost', SYSLOG_UDP_PORT, facility=LOG_USER, socktype=socket.SOCK_DGRAM)`

This looks like a syntax error...

The Python 3.9 docks are fine. I haven't checked whether this is a local oops of covers other tuple params as well.

**Comment by AA-Turner** [comment]
The Python 3.11 docs are built with Sphinx 4.5, and have the brackets again. @JulienPalard what would be the precedent here for fixing this? I don't imagine we can update the Python 3.10 Sphinx version? 

Sphinx only supports the latest version, so we're very unlikely to get a 3.2.2 release with a backported fix.

A

**Comment by JulienPalard** [comment]
We'll have to run a test build before pushing this to docs.python.org, but I'm OK to bump Sphinx to 3.3.1 for Python 3.10. The thing we can't easily bump is the `needs_sphinx` (the minimum required version) but we don't need to touch it here.

**Comment by JulienPalard** [comment]
I'm trying Sphinx==3.4.3, as Sphinx==3.5 is not compatible with Python 3.10 (https://github.com/sphinx-doc/sphinx/issues/9512)...

This issue is solved in 3.4.3 \o/

**Comment by JulienPalard** [comment]
Related PR: https://github.com/python/cpython/pull/93159

**Comment by ambv** [comment]
Fixed in 3.10. As neither 3.9 nor 3.11 were affected, we can close this! Thanks! ✨ 🍰 ✨
