### ISSUE TITLE
`test_sqlite3.test_dbapi`: `test_deserialize_too_much_data_64bit` uses undefined `size` (and requires 24 Exabytes of RAM)

### ISSUE THREAD

**Issue by The-Compiler** [python/cpython#93117]
**Bug report**

In a7551247e7cb7010fb4735281f1afa4abeb8a9cc (GH-26728, v3.11.0a7), @erlend-aasland added a `test_deserialize_too_much_data_64bit`, which would instantly raise a `NameError` for `size` if run:

https://github.com/python/cpython/blob/b2694ab46997746eae7e913738623b39f6334473/Lib/test/test_sqlite3/test_dbapi.py#L629-L634

...however, it's never actually run, because it's skipped on machines with less than 24 Exabytes (!) of RAM:

```
test_deserialize_too_much_data_64bit (test.test_sqlite3.test_dbapi.SerializeTests.test_deserialize_too_much_data_64bit) ... skipped 'not enough memory: 25769803776.0G minimum needed'
```

(Found by running `flake8` over `Lib/` out of curiosity, see https://github.com/python/cpython/issues/93010#issuecomment-1133402591)

**Comment by erlend-aasland** [comment]
Thanks for the report! Do you want to propose a PR, @The-Compiler?

**Comment by The-Compiler** [comment]
I'm afraid I have no idea how a proper fix would look like. Is the test really supposed to need exabytes of RAM? If so, it should probably just be removed altogether?

**Comment by erlend-aasland** [comment]
The test is not needed; see Serhiy's comment: https://github.com/python/cpython/pull/93154#issuecomment-1136897907
