### ISSUE TITLE
`ResourceDenied` raised in `TransientResource` but not imported in `test_urllib2net`

### ISSUE THREAD

**Issue by The-Compiler** [python/cpython#93112]
**Bug report**

`TransientResource` was moved out of `test.support` in 311110abcd8ab648dbf1803e36a8ba5d93fa019b (GH-20812) by @vstinner, thus making `ResourceDenied` undefined here:

https://github.com/python/cpython/blob/a458be3263b4cb92f3fde726461e8ef44b2a4a9d/Lib/test/test_urllib2net.py#L60

I don't see how to best reproduce this, but I will open a PR with a fix.

(Found by running `flake8` over `Lib/` out of curiosity, see https://github.com/python/cpython/issues/93010#issuecomment-1133402591)

**Your environment**

- CPython versions tested on: (not tested, but affects) Python 3.11.0b1, 3.10.4
- Operating system and architecture: Archlinux x86_64

**Comment by vstinner** [comment]
Ah right, do you want to propose a fix?
