### ISSUE TITLE
The readme claims macos creates `python.exe` =)

### ISSUE THREAD

**Issue by Pomax** [python/cpython#93137]
The readme currently reads:

> You can pass many options to the configure script; run ./configure --help to find out more. On macOS case-insensitive file systems and on Cygwin, the executable is called python.exe; elsewhere it's just python.

However, this implies that macos will built a `python.exe`, which is almost certainly not the case ;)

**Comment by JelleZijlstra** [comment]
I'm not sure why it's done this way (or even if it's CPython-specific, I don't compile too many other things from source on my Mac). Maybe someone else can come along with more backgroun.

**Comment by ned-deily** [comment]
> They key words there are "case-insensitive file systems".

Yes, the factory-installed macOS file systems have always been case-insensitive. However, it has long been possible to create and re-install macOS on a case-sensitive file system or, for that matter, create a separate case-sensitive volume and build Python there, in which case, ./configure will create the python executable as `python`, not `python.exe`. However it is not possible to change an existing file system volume from `case-insensitive` to `case-sensitive` so attempting to change your macOS system to be `case-sensitive` is not for the faint of heart and not recommended by Apple. (The good news is that this is something you normally only have to go through once per Mac but it can be quite an undertaking. FWIW, I've used `case-insensitive` file systems on my development Macs for years.)
