### ISSUE TITLE
Combination of @classmethod @property and @abc.abstractmethod

### ISSUE THREAD

**Issue by jbaudisch** [python/cpython#93167]
**Bug report**

```
import abc

class A(abc.ABC):
    @classmethod
    @property
    @abc.abstractmethod
    def type(cls):
        raise NotImplementedError
    
class B(A, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def other(self):
        raise NotImplementedError
    
class C(B):
    @classmethod
    @property
    def type(cls):
        return 'C'

    def other(self):
        print('other')

c = C()
c.other()
```
This script is failing with an NotImplementedError:
```
Traceback (most recent call last):
  File "C:\Users\Justin Baudisch\Desktop\test.py", line 10, in <module>
    class B(A, metaclass=abc.ABCMeta):
  File "C:\Program Files\Python310\lib\abc.py", line 107, in __new__
    _abc_init(cls)
  File "C:\Users\Justin Baudisch\Desktop\test.py", line 8, in type
    raise NotImplementedError
NotImplementedError
```

So the script executes the "type"-property. But why? This is not the expected behaviour (?).
If I remove the `@property` decorator and leave it as a method, it works fine. Same when I remove the `@classmethod` decorator.

**Your environment**

- CPython versions tested on: Python 3.10
- Operating system and architecture: Windows 11

**Comment by alkasm** [comment]
Note: if the order of property & classmethod are flipped, the script behaves as expected.

**Comment by jbaudisch** [comment]
> Note: if the order of property & classmethod are flipped, the script behaves as expected. See also: #89519

Yes, this error is obsolete in Python 3.11, because "class methods can no longer wrap other descriptors such as property".
https://docs.python.org/3.11/library/functions.html?highlight=classmethod#classmethod
