### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by xtonik** [python/cpython#93172]
https://github.com/python/cpython/blob/37c9a351b15c3fc4fcdca5dcb9ce19e51d7d2dd7/Modules/binascii.c#L1027

Branching is not necessary, suggested code:

```
rv = PyBytes_FromStringAndSize((char *)odata, out);
PyMem_Free(odata);
return rv;
```

**Comment by sweeneyde** [comment]
Would you like to open a pull request?

**Comment by sweeneyde** [comment]
Thanks!
