### ISSUE TITLE
Remove check for stdarg.h (HAVE_STDARG_PROTOTYPES) in configure.ac

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#93207]
CPython checks for `stdarg.h` as `HAVE_STDARG_PROTOTYPES` [^1] at some places [^2] but not at other places [^3]. Either this check should be repeated at every call site or should be removed all together, most compilers supports this nowadays (should be verified with buildbots). 

[^1]: https://github.com/python/cpython/blob/16a7e4a0b75080275bf12cfb71d54b01d85099b2/configure.ac#L5026

[^2]:https://github.com/python/cpython/blob/16a7e4a0b75080275bf12cfb71d54b01d85099b2/Modules/_asynciomodule.c#L2646

[^3]: https://github.com/python/cpython/blob/16a7e4a0b75080275bf12cfb71d54b01d85099b2/Objects/call.c#L557

cc @vstinner @tiran @erlend-aasland

**Comment by vstinner** [comment]
Do you want to propose a PR for that?

**Comment by kumaraditya303** [comment]
Created PR https://github.com/python/cpython/pull/93215

**Comment by erlend-aasland** [comment]
> [...] most compilers supports this nowadays 

As pointed out in https://github.com/cython/cython/pull/4820, this may change in the future:

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2975.pdf

**Comment by h-vetinari** [comment]
> As pointed out in [cython/cython#4820](https://github.com/cython/cython/pull/4820), this may change in the future:
> 
> https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2975.pdf

Bit late, but JFYI, this paper got accepted into C23.

**Comment by h-vetinari** [comment]
> As pointed out in [cython/cython#4820](https://github.com/cython/cython/pull/4820), this may change in the future:
> 
> https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2975.pdf

Bit late, but JFYI, this paper got accepted into C23.
