### ISSUE TITLE
Text copy-edit in the tutorial? Passing a dict named 'table'

### ISSUE THREAD

**Issue by JoshuaPollinger** [python/cpython#93240]
**Documentation**

https://docs.python.org/3.12/tutorial/inputoutput.html#the-string-format-method

Hi everyone!  I'm reading through the tutorial and at section "7.1.2. The String format() Method", the sixth paragraph refers to passing a dictionary (named "table") as an argument.  Here's the text as it reads:

> This could also be done by passing the table as keyword arguments with the '**' notation.

But I think it would be more clear if the text was written as follows:

> This could also be done by passing the dict as keyword arguments with the '**' notation.

or

> This could also be done by passing the dict (in this example 'table') as keyword arguments with the '**' notation.

Hope this feedback is helpful!  thanks!!

**Comment by AA-Turner** [comment]
A pull request would be welcomed.

A

**Comment by AA-Turner** [comment]
(I'd probably go for ```This could also be done by passing the ``table`` dictionary as keyword arguments with the ``**`` notation.```).

**Comment by paulreece** [comment]
Hi I made the adjustment and created a PR here https://github.com/python/cpython/pull/93276
