### ISSUE TITLE
Fix asyncio locks test case

### ISSUE THREAD

**Issue by cykerway** [python/cpython#93247]
There are some clear minor mistakes in asyncio locks test case: Duplicate statements and wrong assert function.

The duplicate statements (L846 and L850) might be intentional but the assert function (L856) is obviously wrong.

https://github.com/python/cpython/blob/518595652759462b13904df767f69b8cc2c61143/Lib/test/test_asyncio/test_locks.py#L845-L856

**Comment by kumaraditya303** [comment]
Fixed by #93248
