### ISSUE TITLE
Uninformative error message when working with semaphores

### ISSUE THREAD

**Issue by 86Ilya** [python/cpython#93253]
**Bug report**
Uninformative error message `OSError: [Errno 28] No space left on device` when working with semaphores
in "python3.8/multiprocessing/synchronize.py", line 57"
steps to reproduce:
```bash
docker run --shm-size="1m" -it python:3.8 python -c 'from multiprocessing import Array; myarr = [Array("b", 100) for _ in range(1000)]'
```
current behavior:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 141, in Array
    return Array(typecode_or_type, size_or_initializer, lock=lock,
  File "/usr/local/lib/python3.8/multiprocessing/sharedctypes.py", line 93, in Array
    lock = ctx.RLock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 73, in RLock
    return RLock(ctx=self.get_context())
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 187, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
```

**Your environment**

- CPython versions tested on: `3.8 3.9 3.10`
- Operating system and architecture: `Linux r2d2 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- docker: `docker-ce  5:20.10.13~3-0~ubuntu-focal`

How to fix:
Add a clearer message: `There is not enough space in the file system to create a semaphore`

**Comment by AA-Turner** [comment]
I'm marking this as a feature request for a better error message rather than a bug, as nothing is technically broken currently.

A

**Comment by JelleZijlstra** [comment]
The existing error seems pretty clear to me, and changing the exception class (as proposed in the linked PR) is a minor backward compatibility break. I'm inclined to close this feature request.

**Comment by kumaraditya303** [comment]
I am -1 as the existing error is self explanatory and it is backwards incompatible. Marking pending unless anyone else objects.

**Comment by erlend-aasland** [comment]
Closing due to the lack of response and support.
