### ISSUE TITLE
Wrong Result Documented in Date Arithmetic datetime

### ISSUE THREAD

**Issue by pweibert** [python/cpython#93267]
**Documentation**

The datetime module documentation states the following regarding the date arithmetic: 
date2 = date1 + timedelta   :  date2 is timedelta.days days removed from date1. (1)

it should actually be stating: 
date2 = date1 + timedelta   :  date1 is timedelta.days days removed from date2. (1)

**Comment by ericvsmith** [comment]
I think "removed" is being used as "away from", in which case it makes sense. I think replacing "removed" with a better phrase is a better idea.

**Comment by ericvsmith** [comment]
Merged in to main, 3.11, and 3.10. Thanks @BenjaminHelyer! Congrats on your contribution!
