### ISSUE TITLE
addition of line_iterator and positions_iterator to _collections_abc.py

### ISSUE THREAD

**Issue by ravi140222** [python/cpython#93282]
it is found in codeobject.c but not mentioned in _collections_abc.py

**Comment by AA-Turner** [comment]
Hi @ravi140222,

Your feature request is unclear -- what do you actually want to change? My guess would be registering `line_iterator` and `positions_iterator` with the `Iterator` ABC? It seems that `line_iterator` at least already works:

```pycon
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:34:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections.abc
>>> def f():
...     return True
...
>>> f.__code__.co_lines()
<line_iterator object at 0x0000019AF27D8EE0>
>>> isinstance(f.__code__.co_lines(), collections.abc.Iterator)
True
```

A

**Comment by AlexWaygood** [comment]
I'm closing this on the basis that OP hasn't provided any real-world use case that would benefit from this change.

@ravi140222, if you'd like to change something in the standard library, you need to provide evidence of something that isn't working (or isn't working as well as it should) currently. Simply pointing out an inconsistency isn't a strong enough argument for changing something in the standard library. The inconsistency has to be causing an actual problem somewhere.

If you have a piece of code that isn't working, @ravi140222, but would work if these were added to `_collections_abc.py`, then I'll happily reopen the issue :)

**Comment by AA-Turner** [comment]
As noted in the comments in the module, it is a private list for usage internally - there are no guarantees on support.

The 'right' way to check for an iterator is the isinstance test I illustrated above. Just enumerating all types in `collections.abc` will miss library defined types, types in the stdlib that conform but aren't explicitly registered, etc.

A

**Comment by AlexWaygood** [comment]
As I've said before, @ravi140222, if you find something that's curious or inconsistent about Python, please ask a question at https://discuss.python.org/c/users/7 before opening an issue here. It may well be the case that you have a slight misconception about what a module is for, or that you have a slight misunderstanding about how to approach a problem, rather than there being a bug in CPython.

**Comment by rhettinger** [comment]
I concur with Alex.

**Comment by vainaixr** [comment]
will confirm from users section before creating an issue here from now onwards.
