### ISSUE TITLE
New `bisect.contains` function proposal

### ISSUE THREAD

**Issue by carlbordum** [python/cpython#93294]
**Feature or enhancement**

`contains` function in `bisect` module that tells in `O(log n)` if an element is in a sorted list.

**Pitch**

It's a useful function and can easily be implemented wrong without care.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but I'm going to decline this. 

* Bisecting is primarily used for searching ranges, not for specific values.
* Searching for specific values is the number one misuse of the module
* Hash tables (sets and dicts) are a superior solution for searching for specific values.
* Bisect was primarily designed for locating insertion points to allow a sorted list to be maintained.
* Like the closely related sorted() function, bisect only uses the \__lt__ operation. Nowhere do we want to use \__eq__.

**Comment by carlbordum** [comment]
Fair. Perhaps there is a real need if this is the number one misuse of the module.

**Comment by rhettinger** [comment]
Misuse was the wrong word.  Premisconception is closer to the mark.  Prior to even looking at the module of its docs, people tend to think of "bisecting search" in the sense of the game pick a number between one and a hundred and tell me higher or lower.  Bisect wasn't designed for that and even if it was, it would be the best practice.  Bisect was designed for searching ranges to locate insertion points.
