### ISSUE TITLE
Make asyncio task groups prevent child tasks from being GCed

### ISSUE THREAD

**Issue by 1st1** [python/cpython#93297]
We discovered that sometimes child tasks in a task group can be picked up by a GC which leads to extremely hard to debug problems. This is fixable by switching to use a `set()` instead of `weakset` to internally track child tasks. I'll make a PR shortly.

See also https://github.com/edgedb/edgedb/pull/3914.

**Comment by AlexWaygood** [comment]
Closing, as I believe this was fixed in #93299, and backported in #93305. (Please reopen if there's more to do here).
