### ISSUE TITLE
sendfile for sockets neglects pseudo files on Linux

### ISSUE THREAD

**Issue by illia-v** [python/cpython#93300]
**Bug report**

`socket.socket.sendfile` and `asyncio.base_events.BaseEventLoop.sock_sendfile` rely on `st_size` to determine an amount of bytes to be sent if `count` is not provided.

But `st_size` is equal to zero for pseudo files like `/proc/cpuinfo` on Linux. Therefore, the methods send no data for such files.

**Related code**

https://github.com/python/cpython/blob/a637c09a608cd779c9a7c3e60b886d9f520c58a6/Lib/socket.py#L355-L360
https://github.com/python/cpython/blob/13c10bfb777483c7b02877aab029345a056b809c/Lib/asyncio/unix_events.py#L361-L367

**Example**

Assuming `nc -lkU some.sock` and `./python -m asyncio` run in the same directory:

```python
>>> import asyncio
>>> import socket
>>> sock = socket.socket(socket.AF_UNIX)
>>> loop = asyncio.get_running_loop()
>>> await loop.sock_connect(sock, "./some.sock")
>>> with open("/proc/cpuinfo", "rb") as cpuinfo_file:
...     os.fstat(cpuinfo_file.fileno()).st_size
...     await loop.sock_sendfile(sock, cpuinfo_file)
...     sock.sendfile(cpuinfo_file)
...     len(cpuinfo_file.read())
... 
0
0
0
18294
```

**Comment by kumaraditya303** [comment]
Do you have any fix for this or idea of how this could be fixed? Also are there any use-case of sending pseudo files through sendfile ?

**Comment by kumaraditya303** [comment]
I don't think this is a bug and there is nothing actionable here so closing. However, this can be reopened if required.
