### ISSUE TITLE
The binary files produced by compiling python twice are different

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#93317]
hi, man, i find a problem, that the binary files produced by compiling python twice are different. I was confused for a long time. The different pyc files are the following.

![image](https://user-images.githubusercontent.com/67537842/170821089-9e0f712e-f351-4141-8463-47d67a644b63.png)

i find different places are DA and FA with Beyond Compare.

![image](https://user-images.githubusercontent.com/67537842/170821158-e830b6ca-7a69-4001-b84a-fa5b104eb5ba.png)
configparser.cpython-39.pyc

![image](https://user-images.githubusercontent.com/67537842/170821178-96e4b56b-5924-435f-b975-7de1682a86ee.png)
argparse.cpython-39.pyc

then, i see this is **string instern**  after i study the source code of cpython, These strings are ”{“ ”{{“ ”}“ ”}“
````python
static int
maybe_init_static_strings(void)
{
    if (!_str_open_br &&
        !(_str_open_br = PyUnicode_InternFromString("{"))) {
        return -1;
    }
    if (!_str_dbl_open_br &&
        !(_str_dbl_open_br = PyUnicode_InternFromString("{{"))) {
        return -1;
    }
    if (!_str_close_br &&
        !(_str_close_br = PyUnicode_InternFromString("}"))) {
        return -1;
    }
    if (!_str_dbl_close_br &&
        !(_str_dbl_close_br = PyUnicode_InternFromString("}}"))) {
        return -1;
    }
    if (!_str_inf &&
        !(_str_inf = PyUnicode_FromString("inf"))) {
        return -1;
    }
    if (!_str_replace_inf &&
        !(_str_replace_inf = PyUnicode_FromFormat("1e%d", 1 + DBL_MAX_10_EXP))) {
        return -1;
    }
    return 0;
}
````

python >3.8 compile with multithreading, so there may be different by compiling python twice.  and if i add code here, it is OK! This is just my temporary plan, but i don't think this is a good idea, and i hope you could fix it

![image](https://user-images.githubusercontent.com/67537842/170821660-bc9ea8a3-4a52-4894-8648-2ef3caab7353.png)

**Comment by JelleZijlstra** [comment]
#73894 is the general issue about this.

**Comment by ericvsmith** [comment]
Closing on favor of #73894.
