### ISSUE TITLE
Expose PIDFD_NONBLOCK as os.PIDFD_NONBLOCK

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#93312]
**Feature or enhancement**

Expose `PIDFD_NONBLOCK` as `os.PIDFD_NONBLOCK` to be used with `os.waitid`.

**Pitch**

`pidfd_open` returns a nonblocking file descriptor if `PIDFD_NONBLOCK` is supplied as flag.  If the process
              referred to by the file descriptor has not yet terminated,
              then an attempt to wait on the file descriptor using
              [waitid(2)](https://man7.org/linux/man-pages/man2/waitid.2.html) will immediately return the error EAGAIN rather
              than blocking.

### Linked PRs
* gh-127593
* gh-127630
* gh-127631

**Comment by kumaraditya303** [comment]
Fixed by #93313

**Comment by n6koma7a** [comment]
according to documentation it should be available, yet it is not there:

> python3.13                                                                                                                                                                                                                                             Wed 04 Dec 2024 01:57:39 AM +03
Python 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import os
>> os.PIDFD_NONBLOCK
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    os.PIDFD_NONBLOCK
AttributeError: module 'os' has no attribute 'PIDFD_NONBLOCK'. Did you mean: 'EFD_NONBLOCK'?
>>

**Comment by vstinner** [comment]
> AttributeError: module 'os' has no attribute 'PIDFD_NONBLOCK'

Correct, something is wrong. I wrote https://github.com/python/cpython/pull/127593 to fix the constant.
