### ISSUE TITLE
Typo in Spanish version of documentation 

### ISSUE THREAD

**Issue by rcruz63** [python/cpython#93331]
**Documentation**

In the Spanish version of [modules](https://docs.python.org/es/3/tutorial/modules.html#more-on-modules) says: 

> "Hay una variante de la declaración import que importa **nos** nombres de un módulo directamente al espacio de nombres del módulo que hace la importación. Por ejemplo:"

It should be good to change the **"nos"** word for the **"los"** word:

> "Hay una variante de la declaración import que importa **los** nombres de un módulo directamente al espacio de nombres del módulo que hace la importación. Por ejemplo:" 

Hope this feedback is helpful! thanks!!

**Comment by AlexWaygood** [comment]
Hi, thanks for the report! Issues to do with the Spanish translations of the docs should be reported at the issue tracker here: https://github.com/python/python-docs-es/issues.
