### ISSUE TITLE
isnumeric() return True for "三" and float("三") throws error

### ISSUE THREAD

**Issue by nicoszerman** [python/cpython#93335]
Windows 11
Python 3.10.4

error:
```
s = "三"
if s.isnumeric():
    print(float(s))
```
Throws ValueError: could not convert string to float

**Comment by mdickinson** [comment]
See also #90852.

**Comment by nicszerman** [comment]
I'm sorry! Just saw that.

**Comment by JelleZijlstra** [comment]
I was confused because I thought the character in question was the Greek letter xi (Ξ), but in fact it's the Chinese numeral for 3 (三).
