### ISSUE TITLE
build_ext --inplace argument doesn't work when directory has __init__.py

### ISSUE THREAD

**Issue by williamhCode** [python/cpython#93347]
**Bug Description**
When I use the --inplace argument to build a .pyx file, such as `python setup.py build_ext --inplace` the .so file gets copied to the current directory only if `__init__.py` doesn't exist.

File Structure:
```
engine
├── __init__.py
├── render.pyx
```

Terminal Output:
```
engine ✗ python setup.py build_ext --inplace
...
copying build/lib.macosx-11.1-arm64-3.10/engine/render.cpython-310-darwin.so -> engine
error: could not create 'engine/render.cpython-310-darwin.so': No such file or directory
```

It seems like having `__init__.py` makes build_ext point to the directory 'root_directory/engine', even though it doesn't exist.

WIth  `__init__.py` removed, the last line of the terminal output becomes
```
copying build/lib.macosx-11.1-arm64-3.10/render.cpython-310-darwin.so -> 
```
which solves the issue.

**System Info**

Python Version: 3.10.0
Cython Version: 0.29.30
macbook pro (13-inch, M1, 2020)
macOS Monterey 12.2

**Comment by ronaldoussoren** [comment]
Are you using setuptools? 

If not, please start using setuptools instead of distutils because the latter is deprecated and will be removed.

If you are using setuptools: please file an issue with the setuptools project (https://setuptools.pypa.io/en/latest/)

**Comment by williamhCode** [comment]
Yes I am using setuptools. Ill file an issue there.

**Comment by williamhCode** [comment]
I just realized that this should be in Cython, not cpython. Sorry about that.

**Comment by LocutusOfBorg** [comment]
For reference to anybody reading this bug, this is the setuptool issue
https://github.com/pypa/setuptools/issues/3343
