### ISSUE TITLE
Undefined References when using recommended linking option: Embedding Python in C++ 

### ISSUE THREAD

**Issue by v-volatus** [python/cpython#93358]
**Documentation**

URL: <https://docs.python.org/3/extending/embedding.html>
System: Ubuntu 22.04 using Python 3.10

# Problem:

Using the recommended linking option `/opt/bin/python3.10-config --ldflags` leads to undefined references when compiling.

command used in terminal:
<code>
g++ $(python3.10-config --cflags ) -o 'test.o' 'test.cpp' $(python3.10-config --ldflags)
</code>

Output of `python3.10-config --ldflags`:
<code>
-L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu  -lcrypt -ldl  -lm -lm 
</code>

# Solution:
Adding the option `--embed` solves the issue. By this, `-lpython3.10` is also given to the compiler.

command used in terminal:
<code>
g++ $(python3.10-config --cflags ) -o 'test.o' 'test.cpp' $(python3.10-config --embed --ldflags)
</code>

output of `python3.10-config --embed --ldflags`:
<code> 
-L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm 
</code>

test.cpp:
<pre><code>
#include < Python.h >

int main()
{
	Py_Initialize();
	PyRun_SimpleString("print('Hello World from Embedded Python!!!')");
	Py_Finalize();
	
	return 0;
}
</code>
</pre>

**Comment by TianmingQu** [comment]
Hi, when I tried this approach, and I am using python3.8-config, there are still errors as following:

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status

Could you give me some hint on this?

**Comment by erlend-aasland** [comment]
> Adding the option `--embed` solves the issue. By this, `-lpython3.10` is also given to the compiler.

Yes, [the docs are out of date](https://docs.python.org/3.12/extending/embedding.html?highlight=python%20config#compiling-and-linking-under-unix-like-systems). This was changed in Python 3.8 -- see the 3.8 What's New:

https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

Adding `--embed` when producing the linker flags should help. I'll create a PR for updating the docs.

**Comment by erlend-aasland** [comment]
> Could you give me some hint on this?

Your program lacks a `main` function. This is not a Python issue; you'll find answers on StackOverflow.

**Comment by erlend-aasland** [comment]
The docs were updated by the following PRs:

- gh-98649
- gh-98857
- gh-98858
