### ISSUE TITLE
Running the Python test suite leaks .pem files in /tmp

### ISSUE THREAD

**Issue by vstinner** [python/cpython#93353]
Running the Python test suite has two issues:

* A test leaks 3 .pem files in /tmp
* The test suite is not marked as failed when it leaks temporary files (in /tmp)

Moreover, test_tools enters an unlimited loop and fills the $TMPDIR directory if the $TMPDIR is a sub-directory of the Python source code directory. Example:

* /home/vstinner/python/main/ : Python source code
* /home/vstinner/python/main/TMP/ : Temporary directory ($TMPDIR)

Running test_freeze_simple_script() of test_tools copies TMP/ into TMP/TMP/ and then into TMP/TMP/TMP/, etc. Quickly, it fills TMP/ with a "loop" of files :-)

### Linked PRs
* gh-93776

**Comment by vstinner** [comment]
The problem comes from pip bootstrap when running the test_with_pip() test of test_venv.

It seems like pip creates a .pem file in the temporary directory (like /tmp), but only when pip is imported from a ZIP file, which is the case when I run get-pip.py: https://bootstrap.pypa.io/get-pip.py

**Comment by vstinner** [comment]
In get-pip.py, ``from pip._internal.commands.install import InstallCommand`` is enough to create the ``.pem`` file.

**Comment by vstinner** [comment]
Shell script to reproduce the issue:

```sh
set -e -x

DIR=$PWD/TMP/
rm -rf $DIR
mkdir $DIR

rm -rf env
TMPDIR=$DIR TEMPDIR=$DIR ./python -m venv env --without-pip
TMPDIR=$DIR TEMPDIR=$DIR env/bin/python -m ensurepip -v

echo
echo
echo "=== TMPDIR ==="
find $DIR
```

Output:

```
(...)
=== TMPDIR ===
++ find /home/vstinner/python/main/TMP/
/home/vstinner/python/main/TMP/
/home/vstinner/python/main/TMP/tmpmb5ndxc7cacert.pem
```

**Comment by vstinner** [comment]
The PEM file is created indirectly by importlib.resources on ``import pip._vendor.requests``.

It's created by this code:

```py
>>> import sys; sys.path.insert(0, 'pip.zip')
>>> import pip._vendor.certifi
>>> pip._vendor.certifi.where()
pip.zip/pip/_vendor/certifi/core.py:50: DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
'/home/vstinner/python/main/TMP/tmp9osgb6wrcacert.pem'
```

Debugger:

```
Lib/importlib/resources/_common.py, line 84, in _tempfile (suffix='cacert.pem', fd=4, raw_path='/home/vstinner/python/main/TMP/tmpv7fwzaoocacert.pem')
```

If Python exits normally, the garbage collector deletes the temporary PEM file. When running ensurepip / get-pip.py, it's not deleted. I don't know why.

importlib.resources only creates a temporary file if pip is imported from a ZIP file.

**Comment by vstinner** [comment]
Workaround to manually delete the temporaryfile:

```py
pip._vendor.certifi.core._CACERT_CTX = None
```

**Comment by vstinner** [comment]
OpenSSL requires a filename to a PEM file. certifi uses importlib.resources to create a temporary named file if pip._vendor.certifi is imported from a ZIP file. That's convenient.

The problem is more that the ``pip._vendor.certifi.core._CACERT_CTX`` context manager which keeps the temporary file alive until it's destroyed. Maybe sometimes ``_CACERT_CTX`` is part of a complex reference cycle, it's never destroyed, and so the temporary file is not deleted.

**Comment by serhiy-storchaka** [comment]
Nice. How did you find this?

**Comment by vstinner** [comment]
I used a shell script similar to https://github.com/python/cpython/issues/93353#issuecomment-1141261167 and I ran manually a bisection on the test list (./python -m test --list-tests) using a script taking a random.sample() of half of tests. I repeated the operation until I found a single test file, then I looked at the code.

The leaked files was reported by more and more owners of buildbot workers.

Once the PEM issue is solved, my plan is to enhance test.regrtest to do something similar than the shell script: define TMPFILE env var. Maybe in the main process spawning test processes.

**Comment by vstinner** [comment]
Ok, this problem is quite complicated:

* pip imports requests
* requests imports certifi
* requests calls certifi.where()
* certifi.where() uses importlib.resources to create a temporary file using a context manager.
* logging is imported by pip
* logging calls os.register_at_fork() which keeps the whole logging namespace alive
* somehow, the logging module keeps the whole pip package (!) and all of its sub-modules (!) alive until Python clears os.register_at_fork(): that happens VERY LATE, like the last function call before the last GC collection.
* Python clears os.register_at_fork() callbacks: the context manager ``finally:`` block is called as expected....
* Oops, ``os.remove`` is ``None`` at this point, the call fails.

Fixing importlib.resources is simple: keep a reference to os.remove() in importlib.resources implementation to make sure that we can remove the file very late during Python finalization.

This problem is tricky because:

* importlib.resources only creates a named temporary file if pip is imported from a ZIP file. When pip is installed on disk as a file, the bug is gone.
* the code is valid.
* certifi relies on the garbage collector to gently calls the context manager finalizer which removes the temporary file.
* **Python doesn't log any error** when a bug occurs very late during Python finalization.

I'm working on a fix for importlib.resources.

**Comment by serhiy-storchaka** [comment]
Add parameter `_remove=os.remove` in `def _tempfile()` and use it instead of `os.remove`. The leak will gone.

I suppose that the finally code is executed after the module `os` has been cleared, so `os.remove` raises an exception. You do not get a report because the standard streams have already been cleared too. Perhaps the logging module creates reference loops and keeps reference to this module dict.

It is the answer of the puzzle. In general, you should not rely on the code executed at the interpreter shutdown stage (except registered with `atexit`). It may be much worse in PyPy.

**Comment by vstinner** [comment]
I created the PR https://github.com/python/cpython/pull/93377 to fix importlib.resources.

**Comment by vstinner** [comment]
> related: https://github.com/pypa/pip/issues/10753

Oh, it's known in pip. I didn't want to report the issue to pip until I found the root issue. Well, pip, requests and certifi are fine. The root issue is a Python bug (in importlib.resources).

**Comment by vstinner** [comment]
> Add parameter _remove=os.remove in def _tempfile() and use it instead of os.remove. The leak will gone.

Right, see my PR #93377

> I suppose that the finally code is executed after the module os has been cleared, so os.remove raises an exception.

When the _tempfile() context manager finalizer is called, os.remove is None.

> You do not get a report because the standard streams have already been cleared too.

Right.

> Perhaps the logging module creates reference loops and keeps reference to this module dict.

pip init_logging() function calls ``logging.setLoggerClass(VerboseLogger)``. Since logging calls os.register_at_fork(), the module namespace is kept alive until the last GC collection. Beause of ``logging.setLoggerClass(VerboseLogger)``, it seems like a large part of pip is also kept alive indirectly!

A common reference  leak is... defining a function at the module level: the function refers to the module namespace, the module namespace refers to the function. Enjoy :-) The GC can break such cycle, it's designed for that.

But yeah, a combo of issues keeps lot of objects alive way longer "than expected".

> In general, you should not rely on the code executed at the interpreter shutdown stage (except registered with atexit). It may be much worse in PyPy.

Well, that's a design choice of certifi. If you are concerned, report the issue to them ;-)

importlib.resources is not really faulty here, the API is designed to be used like:

```
with as_file() as filename: ...
```

But certifi calls ``__enter__()`` method and never calls the ``__exit__()`` method explicitly, but rely on Python GC to call the ``finally:`` block of ``_tempfile()`` context manager.

**Comment by tiran** [comment]
PR GH-93776 broke testing on WASI:

```
_PYTHON_HOSTRUNNER='wasmtime run --env PYTHONPATH=/build_oot/host/build/lib.wasi-wasm32-3.12:/Lib --mapdir /::../.. --' _PYTHON_PROJECT_BASE=/buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/build_oot/host _PYTHON_HOST_PLATFORM=wasi-wasm32 PYTHONPATH=/buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/build_oot/host/build/lib.wasi-wasm32-3.12:../../Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_d_wasi_wasm32-wasi ../build/python  ../../Tools/scripts/run_tests.py -j 1 -u all -W --slowest --fail-env-changed --timeout=900 -j2 --junit-xml test-results.xml 
== CPython 3.12.0a0 (heads/main-dirty:a338e106b6, Jun 14 2022, 13:20:18) [GCC 9.4.0]
== Linux-5.17.13-300.fc36.x86_64-x86_64-with-glibc2.31 little-endian
== cwd: /buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/build_oot/host/build/test_python_111802æ
== CPU count: 8
== encodings: locale=UTF-8, FS=utf-8
Using random seed 6754872
0:00:00 load avg: 5.20 Run tests in parallel using 2 child processes (timeout: 15 min, worker timeout: 20 min)
Warning -- regrtest worker thread failed: Traceback (most recent call last):
Warning --   File "/buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/Lib/test/libregrtest/runtest_mp.py", line 325, in run
Warning --     mp_result = self._runtest(test_name)
Warning --                 ^^^^^^^^^^^^^^^^^^^^^^^^
Warning --   File "/buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/Lib/test/libregrtest/runtest_mp.py", line 280, in _runtest
Warning --     os.mkdir(tmp_dir)
Warning --     ^^^^^^^^^^^^^^^^^
Warning -- FileExistsError: [Errno 17] File exists: '/buildmaster-config/master/workers/local-worker/3.x.local-worker.wasi/build/build_oot/host/build/test_python_111802æ_tmpdir'
Kill <TestWorkerProcess #1 running test=test_typing pid=111806 time=2 ms> process group
```

**Comment by vstinner** [comment]
> WASI runtimes do not pass environment variables to WASM programs. python.wasm process does not see the TMPDIR variable.

Ah, so this feature is not supported on WASI. Can you please test https://github.com/python/cpython/pull/93810 on WASI?

**Comment by vstinner** [comment]
Follow-up: issue #93919 "On Windows, test_distutils leaks a temporary file: Microsoft".
