### ISSUE TITLE
Ensure the position information in AST nodes created by the parser is always consistent

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#93351]
If we create an AST node with invalid position information, the error is reported in the compiler when it validates the line numbers and end line numbers, which is too far away and debugging this can be quite challenging. To improve the debugging experience, ensure that the parser cannot create an AST node with invalid position information.

**Comment by hauntsaninja** [comment]
This broke a project of mine https://github.com/hauntsaninja/pyp that does some AST tricks. Worth adding a news entry (possibly to Python 3.11 What's New as well)?

**Comment by pablogsal** [comment]
I will add a news entry for this
