### ISSUE TITLE
`str.format()` output for `enum.Enum` with `str` mixin changed in 3.11.0b1

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [python/cpython#93363]
**Bug report**

The following script changes output between 3.10.4 (and earlier) to 3.11.0b1.

```python
import enum
class E(str, enum.Enum):
    A = "A"
print("hello {0}".format(E.A))

```
```
$ python3.10 test.py
hello A
$ python3.11 test.py
hello E.A
```

Per https://docs.python.org/3/library/enum.html, I believe 3.11's behavior is wrong:
> [Formatted string literals](https://docs.python.org/3/reference/lexical_analysis.html#f-strings), [str.format()](https://docs.python.org/3/library/stdtypes.html#str.format), and [format()](https://docs.python.org/3/library/functions.html#format) will use the mixed-in type’s `__format__()` unless `__str__()` or `__format__()` is overridden in the subclass

**Your environment**

- CPython versions tested on: 3.10.4 and 3.11.0b1
- Operating system and architecture: the docker images `python:3.10-alpine` and `python:3.11-rc-alpine`, on an x86_64 host

**Comment by carlbordum** [comment]
This stems from https://bugs.python.org/issue40066

**Comment by ethanfurman** [comment]
There are two groups of derived enums at this point [^1]:  those created in the stdlib enum.py module, which have backwards compatibility concerns [^2], and those created in user code by directly mixing in other data types:

- the stdlib enums no longer change the `str()` of the mixed type -- this does two things for us [^3]:
  - makes the output of `str()` and `format()` consistent
  - allows stdlib enums to be drop-in replacements for existing constants while maintaining their printed output

- user-created enums, whether mixed with other data types or not, will override the `str()` and `format()` (and `repr()`) to the standard enum settings [^4]


[^1]: "this point" being Python 3.11
[^2]: `IntEnum`, `IntFflag`, and `StrFlag`, which should cover most, if not all, drop-in replacement concerns
[^3]: Note: the `repr()` is still the enum repr
[^4]: in both cases (stdlib or user-mixed), the `str()` and `format()` output the same text as the other

**Comment by AllSeeingEyeTolledEweSew** [comment]
I don't understand the resolution of this based on your message. Do you mean this change is intended to stay? If so, will the documentation at https://docs.python.org/3/library/enum.html be updated? Is there a separate issue tracker for that?
