### ISSUE TITLE
Time delta- provide total milliseconds and microseconds

### ISSUE THREAD

**Issue by nitinmuteja** [python/cpython#93373]
**Feature or enhancement**

(Need total milliseconds and total microseconds as a part of the time delta.)

**Pitch**

(For processing videos and transcripts, we need to get the exact millisecond or microsecond of a time delta within the video when the user has spoken. Currently there is a method to calculate total seconds in timedelta. Need similar feature for milliseconds and microseconds as well.)

**Previous discussion**

**Comment by AA-Turner** [comment]
The feature already exists:

```pycon
>>> datetime.timedelta(milliseconds=7, microseconds=6).microseconds 
7006
>>> divmod(7006, 1000)
(7, 6)
>>> milli, micro = divmod(7006, 1000) 
>>> milli  
7
>>> micro
6
```

A
