### ISSUE TITLE
Remove redundant check in PyLong_FromString() from Objects/longobject.c

### ISSUE THREAD

**Issue by ghost** [python/cpython#93374]
The `if (log_base_BASE[base] == 0.0)` check in line 2405 of `Objects/longobject.c` is redundant:  
 -  `static double log_base_BASE[37] = {0.0e0,};` (line 2401) appears just above it;
 -  at the point at which  `if (log_base_BASE[base] == 0.0)` appears, `base` is guaranteed to be an integer in the closed interval `[2, 36]`.

**Comment by tiran** [comment]
It's not redundant. The variable ``log_base_BASE`` is a local static variable. Local static variables are persistent and shared across function calls.

**Comment by oda-gitso** [comment]
@tiran Yikes! Seem to have forgotten about the `static`. Thanks!
