### ISSUE TITLE
Inconsistency of dataclass asdict

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [python/cpython#93388]
[`dataclass` documentation](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.asdict) does not explain this behaviour:

```python
from dataclasses import dataclass, asdict

@dataclass
class A:
    a = 1

a = A()
asdict(a)
# returns {}

@dataclass
class B:
    b: int = 1

b = B()
asdict(b)
# returns {'b': 1}
``` 

I think that type annotations should not change python behaviour.
Anyhow I would like to know if it's a bug or a documentation caveat so I can provide a PR.

**Comment by ericvsmith** [comment]
Type annotations absolutely change dataclasses behavior. That's the whole point of them! Your class `A` has no fields. Note the difference between `A(0)` (an error) and `B(0)` (works as expected).

There's no bug here.

**Comment by Hugo-Trentesaux** [comment]
> Your class A has no fields.

Yes it has:

```python3
>>> a = A()
>>> a.a
1
```

However that's right attributes without type annotations are also ignored from constructor...

**Comment by ericvsmith** [comment]
> > Your class A has no fields.
> 
> Yes it has:

No, it has no fields in the sense that dataclasses uses the term.

```python
>>> from dataclasses import *
>>> @dataclass
... class A:
...   a = 0
...
>>> len(fields(A))
0

>>> @dataclass
... class B:
...   b: int = 0
...
>>> len(fields(B))
1

```

**Comment by Hugo-Trentesaux** [comment]
> The [dataclass()](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.dataclass) decorator examines the class to find fields. A field is defined as a class variable that has a [type annotation](https://docs.python.org/3.11/glossary.html#term-variable-annotation). With two exceptions described below, nothing in [dataclass()](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.dataclass) examines the type specified in the variable annotation.

Ok. So the concept of `dataclass`/`fields` slightly differs from the python `class`/`attributes`. I'm closing this issue but I think this difference deserves a warning in the doc.
