### ISSUE TITLE
OSError: [WinError -1073741795] Windows Error 0xc000001d

### ISSUE THREAD

**Issue by aryan-debug** [python/cpython#93393]
0

I am working on an app and making it by using Windows API, ctypes and python. I already have a main window, but now I want a dialog box. I have tried functions like CreateDialog and CreateDialogIndirectParamA to make a dialog box, but that did not work. Now, I am trying to make a second window just like I made the main window. The second window is created, but is destroyed immediately and that error is throw. This is the error message: DispatchMessageA(lpmsg) OSError: [WinError -1073741795] Windows Error 0xc000001d. I have no clue what is causing the error or what it means. Please help me. I need it to work for a school project. Thank you!

You will need three files to make the app

main.py: https://gist.github.com/aryan-debug/fd579f01f42f92bea2369a3ec14e80ff

user32.py: https://gist.github.com/aryan-debug/cd3d1c34a18f9a8e46f9fb5481761384

button.py: https://gist.github.com/aryan-debug/8f145cb1b14a206af99ac72e430b53a6

**Comment by AA-Turner** [comment]
We don't answer questions for homework -- you might have more luck on StackOverflow or by asking your professor/teacher.

Your code doesn't raise an error for me (Windows 10; Python 3.10), and you haven't provided a traceback or a *minimal* reproducer, so I'm closing this now. If you still have the problem and your professor confirms it is a bug with Python, please re-open with a minimal reproducer.

A
