### ISSUE TITLE
Tool/demo/redemo: params of `event` for `recompile()` and `reevaluate()` are not accessed.

### ISSUE THREAD

**Issue by lucas-six** [python/cpython#93409]
**Bug report**

Tool/demo/redemo: params of `event` for `recompile()` and `reevaluate()` are not accessed.

**Your environment**

- CPython versions tested on: 3.9.13
- Operating system and architecture: macOS/x86_64, Ubuntu/x86_64.

**Comment by oda-gitso** [comment]
I wouldn't really call this a bug but it is in fact not used  in `redemo.py`. The only two places `event` appears in that file are lines 101 and 114:

https://github.com/python/cpython/blob/132e563703ed634312e54c04a9b1636f8b0e2923/Tools/demo/redemo.py#L101

https://github.com/python/cpython/blob/132e563703ed634312e54c04a9b1636f8b0e2923/Tools/demo/redemo.py#L114

**Comment by oda-gitso** [comment]
This is not a bug. Try removing `event=None` from the two function definitions and playing around with it. You should be getting an error. You will see this done a lot with `tkinter` programs.

**Comment by leven-cn** [comment]
Yes, you're right. Thanks.
