### ISSUE TITLE
Broken list comprehension/for loop

### ISSUE THREAD

**Issue by ghost** [python/cpython#93428]
code with the issue:

```
n = [1,2,3]
for i in n:
    print(i)
    n.remove(i)
print(n, f"Outside Of Loop '{n[0]}' not removed")
```

Expected Behavior:
console would output 1->2->3 then print [] or error out

Actual Behavior:
console outputs 1->3 then prints [2]

- Python versions tested on:
- 3.10.4
- 3.9.2
- (Also Tested On https://www.w3schools.com/python/trypython.asp?filename=demo_default)
- Operating system and architecture:
  Debain 11 - amd64
  Arch - amd64

**Comment by ericvsmith** [comment]
This is not a bug. You're mutating a list while you're iterating it. See for example https://stackoverflow.com/questions/1637807/modifying-list-while-iterating

The "solution" depends on what you're trying to do. Maybe you want to iterate over a copy of the list that you're trying to mutate?

**Comment by Zven214** [comment]
well I still have this issue, I have found this simplified code shows it better:

```
n = [1,2,3]
for i in n:
    print(i)
    print(n[0])
```
n[0] never changes yet specifically when there are 2 instructions within the for loop the output changes.

I can see why you might think about mutability however in this iteration I am not longer changing anything yet the values vary.
