### ISSUE TITLE
Iterating over ChainMap.values() and ChainMap.items() updates underlying defaultdicts

### ISSUE THREAD

**Issue by Alexamk** [python/cpython#93432]
**Bug report**

Hello,
I encountered some confusing behavior when combining ChainMap with defaultdicts. Might be related to #23534
Specifically, iterating over the values or items of the ChainMap updates one of the underlying dictionaries, and returns the wrong result. 
Just iterating over they keys or the dictionary directly produces the right results still and doesn't update the underlying dictionaries. 

```
from collections import ChainMap, defaultdict

d1 = defaultdict(int, {'a': 1, 'b': 2})
d2 = defaultdict(int, {'c': 3, 'd': 4})
d3 = ChainMap(d1, d2)

print('Prior to iter')
print(d1)
print(d2)
print('After iter')
a = list(d3.values()) # Same result when calling d3.items
print(a) # Should return: [1, 2, 3, 4]. Returns: [0, 0, 1, 2]
print(d1) # Now: {'a': 1, 'b': 2, 'c': 0, 'd': 0}
print(d2) # Unchanged
```

**Your environment**

Tested on Python version 3.10.4. 
Linux 5.13.0-41-generic #46~20.04.1-Ubuntu SMP 
x86_64 x86_64 x86_64 GNU/Linux

**Comment by corona10** [comment]
cc @serhiy-storchaka

**Comment by corona10** [comment]
The following patch will solve this issue, but I am waiting for @rhettinger and @serhiy-storchaka 
````diff

--- a/Lib/collections/__init__.py
+++ b/Lib/collections/__init__.py
@@ -997,10 +997,8 @@ def __missing__(self, key):

     def __getitem__(self, key):
         for mapping in self.maps:
-            try:
+            if key in mapping:
                 return mapping[key]             # can't use 'key in mapping' with defaultdict
-            except KeyError:
-                pass
         return self.__missing__(key)            # support subclasses that define __missing__

     def get(self, key, default=None):
````

**Comment by serhiy-storchaka** [comment]
Yes, it looks like an intentional behavior. There is even a comment in the code about this:
https://github.com/python/cpython/blob/8150b8cf7fe09d601246f5bdc6456a0e31f31bca/Lib/collections/__init__.py#L1001

**Comment by rhettinger** [comment]
FWIW, you can turn-off defaultdict's updating behavior prior to iteration:

```
d1.default_factory = None
d2.default_factory = None
a = list(d3.values()) # This no longer mutates d1 and d2
```
