### ISSUE TITLE
PyTuple_SET_ITEM fails to compile in C++ source

### ISSUE THREAD

**Issue by nascheme** [python/cpython#93442]
- CPython versions tested on: 3.11b3
- Operating system and architecture: Debian Linux, GCC 10.2.1-6

The kiwisolver extension doesn't compile with beta 3.  The error is:
```
/usr/local/python3.11.0b3/include/python3.11/pyport.h:47:24: error: invalid ‘static_cast’ from type ‘int’ to type ‘_object*’
   47 |                 return static_cast<type>(const_cast<expr_type &>(expr));
      |                        ^~~~~
```

This seems to be an issue with the new inline functions for things that used to be macros.  E.g. PyTuple_SET_ITEM.  The C++ code triggering the issue is:
```
--- a/py/src/symbolics.h
+++ b/py/src/symbolics.h
@@ -123,7 +123,7 @@ PyObject* BinaryMul::operator()( Expression* first, double second )
                return 0;
        Py_ssize_t end = PyTuple_GET_SIZE( first->terms );
        for( Py_ssize_t i = 0; i < end; ++i )  // memset 0 for safe error return
-               PyTuple_SET_ITEM( terms.get(), i, 0 );
+               PyTuple_SetItem( terms.get(), i, 0 );
        for( Py_ssize_t i = 0; i < end; ++i )
        {
                PyObject* item = PyTuple_GET_ITEM( first->terms, i );
```

Replacing the macro with the function version seems to allow the extension to compile.

This seems related to https://github.com/python/cpython/issues/92898

**Comment by vstinner** [comment]
What is the result type of terms.get()? Can you write a short C++ code reproducing the issue?

I guess that the cast which fails is ``_PyObject_CAST(0)``: 3rd argument of PyTuple_SET_ITEM(). The function expects a ``PyObject*`` and you pass ``0`` as a pointer.

**Comment by vstinner** [comment]
> Maybe in modern C++ versions that's not the case?

In C++, nullptr should be used to pass a "null pointer" (0), no?

Well, Python should accept 0 as ``PyObject*``.

**Comment by vstinner** [comment]
The issue can be reproduced by running test_cppext with this change:

```
diff --git a/Lib/test/_testcppext.cpp b/Lib/test/_testcppext.cpp
index eade7ccdaa..70f434e678 100644
--- a/Lib/test/_testcppext.cpp
+++ b/Lib/test/_testcppext.cpp
@@ -74,6 +74,10 @@ test_api_casts(PyObject *Py_UNUSED(module), PyObject *Py_UNUSED(args))
     Py_INCREF(strong_ref);
     Py_DECREF(strong_ref);
 
+    // gh-93442: Pass 0 as NULL for PyObject*
+    Py_XINCREF(0);
+    Py_XDECREF(0);
+
     Py_DECREF(obj);
     Py_RETURN_NONE;
 }
```

**Comment by nascheme** [comment]
My guess is that the `_Py_CAST_impl` needs to have an overload to handle `nullptr_t` as the argument.  Perhaps then `_Py_NULL` should not be needed.  We would like that API users can still use 0 and NULL as args to these macros.

**Comment by nascheme** [comment]
I can confirm this change makes `kiwi` compile without having to make source code changes. :tada:

**Comment by corona10** [comment]
@serge-sans-paille would you like to submit the PR for this issue? cc @nascheme @vstinner
