### ISSUE TITLE
`dataclasses` should use `ast` instead of generating code as strings

### ISSUE THREAD

**Issue by KOLANICH** [python/cpython#93452]
**Feature or enhancement**

It uses dynamic code generation and executing of it, but the code itself is generated as a string.

**Pitch**
May bring the following benefits:
* performance and overhead: no need to parse the code onto AST
* readability and modularity - ast is manipulated as objects
* security - `ast` classes ctors can be made verifying that the strings used as names don't contain any chars unallowed in the and are not the same as keywords, this way reducing the possibilities to inject malicious code when the names are supplied from untrusted source.

**Comment by ericvsmith** [comment]
I've implemented this is in the past, and I can assure you that one benefit it will _not_ bring is readability!

But the rest of the points are worth looking at.

**Comment by KOLANICH** [comment]
>and I can assure you that one benefit it will not bring is readability!

One can parse the blocks from source code if one wants to see them as source within source. I did something like that whan I was fixing and improving CoCoPy parser generator. The benefit in readability is that the subgraphs of AST can be and manipulated as objects, this way functions generating code can be decomposed into functions with self-documented names.

**Comment by iritkatriel** [comment]
> I've implemented this is in the past, and I can assure you that one benefit it will _not_ bring is readability!


Another problem is maintenance - changes to the ast will require updating dataclass code.  The ast maintainers need to be on board with that.

**Comment by ericvsmith** [comment]
I'm going to close this. I don't plan on moving to ast manipulation at this time.
