### ISSUE TITLE
Unable to do debugging in Python 3.10 version

### ISSUE THREAD

**Issue by jmishra01** [python/cpython#93456]
Below issue I got while doing debugging using Python 3.10 version.
Same issue raised in PyCharm, Spyder, in terminal (python3.10 -m pdb main.py)

(Pdb) 
Traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/jmishra/Projects/application/main.py", line 3, in <module>
    from server.get_query_testing import get_query, jsonify
  File "/home/jmishra/Projects/application/server/get_query_testing.py", line 11, in <module>
    from library.security.encryption import Encryption
  File "/home/jmishra/Projects/application/library/security/encryption.py", line 4, in <module>
    from cryptography.fernet import Fernet
  File "/home/jmishra/Projects/application/venv/lib/python3.10/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives.hmac import HMAC
  File "/home/jmishra/Projects/application/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 12, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/home/jmishra/Projects/application/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/jmishra/Projects/application/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/jmishra/Projects/application/venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 17, in <module>
    _OpenSSLErrorWithText = typing.NamedTuple(
  File "/usr/lib/python3.10/typing.py", line 2323, in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
  File "/usr/lib/python3.10/typing.py", line 2250, in _make_nmtuple
    nm_tpl = collections.namedtuple(name, fields,
  File "/usr/lib/python3.10/collections/__init__.py", line 393, in namedtuple
    field_defaults = dict(reversed(list(zip(reversed(field_names),
TypeError: 'dict' object is not callable
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3.10/collections/__init__.py(393)namedtuple()
-> field_defaults = dict(reversed(list(zip(reversed(field_names),

> pip list
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
arrow                         1.2.2
astroid                       2.11.4
atomicwrites                  1.4.0
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.10.1
backcall                      0.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.3.0
bleach                        5.0.0
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.12
click                         8.1.3
cloudpickle                   2.0.0
colorama                      0.4.4
commonmark                    0.9.1
cookiecutter                  1.7.3
coverage                      6.3.2
cryptography                  37.0.1
debugpy                       1.6.0
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.4
docutils                      0.17.1
entrypoints                   0.4
falcon                        3.1.0
fastjsonschema                2.15.3
flake8                        4.0.1
gevent                        21.12.0
greenlet                      1.1.2
gunicorn                      20.1.0
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
inflection                    0.5.1
iniconfig                     1.1.1
intervaltree                  3.1.0
ipdb                          0.13.9
ipykernel                     6.13.0
ipython                       7.33.0
ipython-genutils              0.2.0
isort                         5.10.1
jedi                          0.18.1
jeepney                       0.8.0
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.4.0
jupyter-client                7.3.0
jupyter-core                  4.10.0
jupyterlab-pygments           0.2.2
keyring                       23.5.0
lazy-object-proxy             1.7.1
MarkupSafe                    2.1.1
matplotlib-inline             0.1.3
mccabe                        0.6.1
memory-profiler               0.60.0
memray                        1.0.3
mistune                       0.8.4
mypy-extensions               0.4.3
mysql-connector-python        8.0.29
nbclient                      0.6.0
nbconvert                     6.5.0
nbformat                      5.3.0
nest-asyncio                  1.5.5
numpy                         1.22.3
numpydoc                      1.3.1
packaging                     21.3
pandas                        1.4.2
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.1.1
platformdirs                  2.5.2
pluggy                        1.0.0
poyo                          0.5.0
prompt-toolkit                3.0.29
protobuf                      3.20.1
psutil                        5.9.0
ptyprocess                    0.7.0
py                            1.11.0
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.12.0
PyJWT                         2.3.0
pylint                        2.13.7
pyls-spyder                   0.4.0
pyparsing                     3.0.8
PyQt5                         5.15.6
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.10.1
PyQtWebEngine                 5.15.5
PyQtWebEngine-Qt5             5.15.2
pyrsistent                    0.18.1
pytest                        7.1.2
pytest-cov                    3.0.0
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.4.1
python-slugify                6.1.2
pytz                          2022.1
pyxdg                         0.27
pyzmq                         22.3.0
QDarkStyle                    3.0.3
qstylizer                     0.2.1
QtAwesome                     1.1.1
qtconsole                     5.3.0
QtPy                          2.0.1
requests                      2.27.1
rich                          10.16.2
rope                          1.0.0
Rtree                         1.0.0
SecretStorage                 3.3.2
setuptools                    62.1.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.0
spyder-kernels                2.3.0
sqlparse                      0.4.2
text-unidecode                1.3
textdistance                  4.2.2
three-merge                   0.1.1
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
tornado                       6.1
traitlets                     5.1.1
ujson                         5.2.0
urllib3                       1.26.9
vertica-python                1.0.5
watchdog                      2.1.7
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.1
wrapt                         1.14.1
wurlitzer                     3.0.2
yapf                          0.32.0
zipp                          3.8.0
zope.event                    4.5.0
zope.interface                5.4.0

**Comment by hauntsaninja** [comment]
Please include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example).
