### ISSUE TITLE
[Asyncio] Support for async → sync → async call chains

### ISSUE THREAD

**Issue by omerXfaruq** [python/cpython#93462]
**Feature or enhancement**
Support for running async functions in sync functions
**Pitch**
Currently running async functions inside sync functions is only available with
`asyncio.run(func(x)) `or `loop.run_until_complete()`; however when there is a running loop, these calls cannot be used.
The only way is running the function in background, and using callback functions(which is very limiting)

```
event_loop = asyncio.get_event_loop()
task = event_loop.create_task(func(*args))
task.add_done_callback(callback_func)
```
See example [PR](https://github.com/gradio-app/gradio/pull/1460/files#r888773711)

I think there should be function to handle all cases of running async funcs in sync funcs
- when there is no event_loop
- when there is already running event_loop
Suggested syntax: `synchronize_async(func(*args))`

**Comment by FarukOzderim** [comment]
Oh, I found something in [fsspec](https://github.com/fsspec/filesystem_spec/blob/06c400335cb7d382cd57d94f93a4b30157dad9b2/fsspec/asyn.py#L98-L110), thanks to @isidentical!

Would be great to have something similar in asyncio as well!

**Comment by arhadthedev** [comment]
Could you change the title to something like `Support for async → sync → async call chains` please? Reading the title alone gives the wrong impression that you suggest implicit loop creation.

**Comment by FarukOzderim** [comment]
I found a similar [solution](https://github.com/django/asgiref/blob/6b1222a48f77fbe743a4ac476fb21e24a70a26c8/asgiref/sync.py#L154-L158) in django/asgiref, though it also does not support the specificed use case I mentioned, but could be decent example in terms of implementation.

**Comment by FarukOzderim** [comment]
Was able to create a solution to this in this [PR](https://github.com/gradio-app/gradio/pull/1547/files#diff-0dd827ecd796f1d09e48052f6f80c1c9cf519eb940595994c65744ca40b0ae6aR316-R329)

**Comment by gvanrossum** [comment]
> **Previous discussion**
> #93462

Is that a typo? It just links back to this same issue.

Separately, I note that the solution in fsspec (linked from the previous comment) just runs the whole thing in a separate thread, using a separate event loop. That's pretty heavy machinery, not something I'd like to enable with a quick call or decorator -- it'd just encourage a bad architecture.

**Comment by kumaraditya303** [comment]
I have needed something like this myself when wrapping an async library with a sync interface, the solution I came up with is very complicated for an average user  so would be nice to have support for this given that https://github.com/erdewit/nest_asyncio library which allows something like this is downloaded 17 million per month so in high demand.

**Comment by kumaraditya303** [comment]
This would require an event loop which supports reentrancy which does has it downsides so even if this were to be supported it should be behind a user configurable flag and will definitely be not the default behavior.

**Comment by gvanrossum** [comment]
Millions of downloads may be the result of being the dependency of one other very popular package; nest_asyncio only has modest numbers of starts/forks/issues.

Nevertheless, it seems to just patch a bunch of asyncio functions to allow re-entrancy, which looks much lighter weight than running in a thread (pool).

What would it take to just incorporate those patches in the stdlib asyncio? I guess we'd have to reimplement them in C for the C accelerator to keep working (nest_asyncio disables that), but that's a matter of work. *If* those patches don't introduce other bugs. My [post from 7 years ago](https://github.com/python/cpython/issues/66435#issuecomment-1093662817) makes it sound rather dubious though.

But I'd be happy to see someone try this experiment and report back how it went. (Try hard to come up with scenarios that break it, that's the interesting part of the experiment.)

**Comment by FarukOzderim** [comment]
WoW what an ancient issue :D

**Comment by kumaraditya303** [comment]
Please continue the discussion on #66435
