### ISSUE TITLE
Enum: auto() is not activated if combined with other values on assignment line

### ISSUE THREAD

**Issue by huwcbjones** [python/cpython#93464]
**Bug report**

Creating a Enum that uses automatic values and tuple assignment doesn't work!
```py
from enum import Enum, auto
from typing import Any

class Day(Enum):
    def __new__(cls, value, abbr=None):
        obj = Enum.__new__(cls, value)
        obj.abbr = abbr
        return obj

    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: list[Any]) -> Any:
        return name

    MONDAY = auto(), "Mon"
    # etc

print(Day.MONDAY, Day.MONDAY.value, Day.MONDAY.abbr)
```
Run that snippet and you get
<pre>
Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    class Day(Enum):
  File "lib/python3.9/enum.py", line 288, in __new__
    enum_member = __new__(enum_class, *args)
  File "mwe.py", line 8, in __new__
    obj = Enum.__new__(cls, value)
  File "lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: &lt;enum.auto object at 0x10b673fa0&gt; is not a valid Day
</pre>
**Your environment**

- CPython versions tested on: 3.9.2/3.9.7/3.10.2
- Operating system and architecture: Debian 11 (amd64)/macOS 11.4 (amd64)

* PR: gh-99148

* PR: gh-99149

* PR: gh-99997

* PR: gh-100004

**Comment by huwcbjones** [comment]
You _can_ bodge around this by replacing the tuple definition + __new__ with a map+property but that feels digusting

```py
from enum import Enum, auto
from typing import Any

class Day(Enum):

    def _generate_next_value_(name: str, start: int, count: int, last_values: list[Any]) -> Any:
        return name

    MONDAY = auto()
    # etc

    @property
    def abbr(self):
        return {
            self.MONDAY: "Mon",
        }[self]

print(Day.MONDAY, Day.MONDAY.value, Day.MONDAY.abbr)
```
prints
<pre>Day.MONDAY MONDAY Mon</pre>
as expected

**Comment by ethanfurman** [comment]
"auto" is short for automatic, the idea being that you don't need to type anything beyound `auto()` on the member assignment line.

If you are adding more on the assignment line, such as `, "Mon"`, then `auto()` is not the right tool.

**Comment by ethanfurman** [comment]
Fair point.  You may also want to check out my [`aenum library`](https://pypi.org/project/aenum/).  Using it would look like:

``` python
class Day(Enum):
    def __new__(cls, value, abbr=None):
        obj = Enum.__new__(cls, value)
        obj.abbr = abbr
        return obj

    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: list[Any]) -> Any:
        return name

    MONDAY = auto(abbr="Mon")
```

**Comment by huwcbjones** [comment]
> You may also want to check out my [aenum library](https://pypi.org/project/aenum/)

Ta, shall have a look :)

**Comment by d0sboots** [comment]
Just ran into the same issue. There's nothing whatsoever in the docs that would lead you to believe that `auto()` isn't a simple function that calls `_generate_next_value_`. And the docs say "If the exact value is unimportant you can use auto," which was precisely my use case: I don't care about the *value*, but I want to also specify **additional** data which has specifics that I **do** care about.

**Comment by ethanfurman** [comment]
I am convinced that `auto()` should always call `_generate_next_value_` -- reclassifying as a bug.
