### ISSUE TITLE
The floating-point information provided by `sys.float_info` is mostly incorrect.

### ISSUE THREAD

**Issue by wiseaidev** [python/cpython#93488]
**Bug report**

Running `sys.float_info` shows that the smallest number a float can store is `min_10_exp=-307`. However, by trial and error, it turns out that the true minimum value is `10.0 ** -323`

```python
>>> import sys
>>> sys.float_info
sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

>>> 10.0 ** -323
1e-323
>>> 10.0 ** -324
0.0
```

Therefore, `min_10_exp=-307` should be corrected to `min_10_exp=-323`.

The same apply for `min`, it should be:

```python
>>> f"{pow(10.0, -323):.16}"
'9.881312916824931e-324'
```

The max value is correct:

```python
>>> 10.0 ** 308
1e+308
>>> 10.0 ** 309
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: (34, 'Numerical result out of range')
```

It turns out that a lot of information provided by this attribute(`float_info`) is not correct, the correct ones are:

```python
>>> 2.0 ** 1023
8.98846567431158e+307

# this implies that max=8.98846567431158e+307 and max_exp=1023
# max_10_exp=308 is correct

>>> f"{pow(2.0, -1074):.16}"
'4.940656458412465e-324'

# this implies that min=4.940656458412465e-324 and min_exp=1074
```

Following the 64bits version of IEEE 754 standard, the sign is coded on 1 bit, the exponent on 11 bit, and 52-bit for the mantissa, 11 + 1 + 52 = 64 bits; the precision being 52 bits, thus 15 significant digits. This means that `dig=15` is correct and `mant_dig=52` instead of `mant_dig=53`.

```sh
|-63-|62-----------52|51------------------------0|      
|sign|---exponent----|---------mantissa----------|      
|1bit|----11bits-----|----------52bits-----------|       
```

**Your environment**

- CPython versions tested on: Python 3.9.10
- Operating system and architecture: Ubuntu 20.04.4 LTS 64 bits.

**Comment by mdickinson** [comment]
Thanks for the report. Assuming that you're on a system that uses IEEE 754 binary64 floating-point (which is in practice a very safe assumption), the `min` and `min_10_exp` values are correct here. As both the docstrings and the [online documentation](https://docs.python.org/3/library/sys.html#sys.float_info) indicate, they refer to the smallest representable positive _normal_ floating-point value, and the smallest representable _normal_ power of 10, respectively.

> It turns out that a lot of information provided by this attribute(`float_info`) is not correct

Please could you elaborate. What other values do you consider incorrect?

**Comment by Harmouch101** [comment]
Updated the issue.

**Comment by oda-gitso** [comment]
> Following the 64bits version of IEEE 754 standard, the sign is coded on 1 bit, the exponent on 11 bit, and 52-bit for the mantissa, 11 + 1 + 52 = 64 bits; the precision being 52 bits, thus 15 significant digits. This means that dig=15 is correct and mant_dig=52 instead of mant_dig=53.

The significand is 53 bits, 52 of which are actually stored in the significand field. There is a leading bit that is *implicit*. (See, for example, Section 3.4 of [IEEE-754](https://irem.univ-reunion.fr/IMG/pdf/ieee-754-2008.pdf).)

**Comment by mdickinson** [comment]
@oda-gitso Ah thanks; I missed that bit of the original report. Indeed `mant_dig=53` is correct.

**Comment by Harmouch101** [comment]
> The significand is 53 bits, 52 of which are actually stored in the significand field. There is a leading bit that is implicit. (See, for example, Section 3.4 of IEEE-754.)

I wasn't aware that it takes into consideration the sign bit. But in any case, the other values that I have mentioned are completely wrong. You can reproduce the error by running the examples that I provided above.

**Comment by Harmouch101** [comment]
`Joined 29 days ago`, @mdickinson, I see what you did there.

**Comment by mdickinson** [comment]
> the other values that I have mentioned are completely wrong

They're correct. Again, as documented, those constants refer to _normal_ values. The result of `10.0 ** -323` is subnormal, not normal: it's not represented with full precision.

**Comment by mdickinson** [comment]
> `Joined 29 days ago`, @mdickinson, I see what you did there.

Sorry, I have no idea what you're talking about.

**Comment by eryksun** [comment]
Anything smaller than `sys.float_info.min` is a [subnormal](https://en.wikipedia.org/wiki/Subnormal_number) (i.e. denormalized) number, including 0.0. Subnormal doubles have a fixed binary exponent of -1022. Here's the smallest subnormal that's greater than 0:

```
>>> f = float.fromhex('0x0.0000000000001p-1022')
>>> format(f, '.16e')
'4.9406564584124654e-324'
```
That's `(2 ** -52) * (2 ** -1022) == 2 ** -1074`.

Here's the smallest *normal* float value from hex format:

```
>>> f = float.fromhex('0x1.0000000000000p-1022')
>>> f == sys.float_info.min
True
>>> format(f, '.16e')
'2.2250738585072014e-308'
```

**Comment by Harmouch101** [comment]
Now I get it. I didn't know about the subnormal numbers. Thanks for the explanation, @eryksun.
