### ISSUE TITLE
ast keep number system

### ISSUE THREAD

**Issue by Fire-Cube** [python/cpython#93499]
**Feature or enhancement**

If you use a number system such as oct, bin, or hex in Python, you should keep it.
For example:
0o, 0b, 0x
This is currently simply converted to a decimal number.

**Pitch**

You should implement this so that the code stays the same as possible. This is especially important when using ast.unparse.

**Comment by sweeneyde** [comment]
We already have functions to print out the hex or binary or decimal representations of an integer, it's just that the default string representation (the result of `repr()`) is the decimal digits, which is what most people will expect:

```python
>>> hex(0x22)
'0x22'
>>> bin(0b1101)
'0b1101'
>>> repr(1970)
'1970'
>>> 1970 # calls repr()
1970
```

**Comment by sweeneyde** [comment]
An effort is made, where reasonable, to make `eval(repr(x)) == x`, but it unreasonable to expect that `repr(eval(s)) == s`:

```python
# expressions are evaluated
>>> repr(2+2) == "2+2"
False

# canonical representation is used (no underscores)
>>> repr(1_000_000) == "1_000_000"
False

# canonical representation is used (no exponent)
>>> repr(1e0) == "1e0" 
False

# canonical representation is used (decimal)
>>> repr(0xff) == "0xff"
False

# canonical representation is used (single quotes)
>>> repr("abc") == '"abc"'
False
```

If you need some integer-like type that gets printed out as hex, you could always do something like this:

```python
>>> class hexint(int):
...     def __str__(self):
...         return hex(self)
...     def __repr__(self):
...         return f"{type(self).__qualname__}({hex(self)})"
... 
...     
>>> hexint(0xff)
hexint(0xff)
>>> print(hexint(0xff))
0xff
```

But I don't think this belongs in the standard library or as a built-in.

**Comment by Fire-Cube** [comment]
I'm not sure if you understood me correctly. The system should be retained when using the ast module. So that the same thing comes out again with ast.unparse.

**Comment by sweeneyde** [comment]
Apologies if I misunderstood. Can you describe your use-case more? Perhaps you'd find more use in concrete syntax trees like those offered by [LibCST](https://pypi.org/project/libcst/)?

**Comment by hauntsaninja** [comment]
Yes, this use case is better served by [concrete syntax trees](https://eli.thegreenplace.net/2009/02/16/abstract-vs-concrete-syntax-trees/). Python's AST is lossy (A is for abstract) and that's not going to change.

This behaviour is also clearly documented, see the red warning box under `ast.unparse` https://docs.python.org/3/library/ast.html#ast.unparse
