### ISSUE TITLE
Typing Bug: Generic Argument in Callable signature

### ISSUE THREAD

**Issue by miili** [python/cpython#93494]
**Bug report**

The Generic type is not propagated correctly to the `Callable`. Subsequently the typing fails hard on the typed callback signature.

## Example Code

```python
from typing import Generic, TypeVar, Any, Callable

class BaseModel:
    ...

class Model(BaseModel):
    ...

_T = TypeVar("_T")
# _T = TypeVar("_T", covariant=True)  # Missing `_co` suffice here

class Dispatcher(Generic[_T]):
    def add_callback(self, func: Callable[[_T], Any]) -> None:
        ...

    def add_mod(self, mod: _T) -> None:
        ...

module_dispatcher: Dispatcher[BaseModel] = Dispatcher()

def call_me(model: Model) -> None:
    ...

module_dispatcher.add_callback(call_me)  # Throws incompatibility
module_dispatcher.add_mod(Model())  # This is OK
```

## mypy / pylance output

mypy complains about the `Callable` only. The `add_mod` method does the Generic type inference.

```
/tmp/testing.py:35: error: Argument 1 to "add_callback" of "Dispatcher" has incompatible type "Callable[[MyModel], None]"; expected "Callable[[MyBaseModel], Any]"
```

**Your environment**

- CPython versions tested on: 3.9.2
- Operating system and architecture: `Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`

**Comment by Fidget-Spinner** [comment]
I think you should open a bug with pylance/mypy. This isn't a CPython issue.

Also, correct me if I'm wrong please @JelleZijlstra , but isn't the behavior you describe correct behaviour? `Callable` is contravariant after all.

**Comment by JelleZijlstra** [comment]
Indeed, this is correct behavior because of variance, and even if it wasn't, it would be a type checker bug, not a CPython bug.

**Comment by miili** [comment]
Thanks for the prompt response. I was blind but now I see.

Following up on the concept: https://stackoverflow.com/a/68186433/2387835
