### ISSUE TITLE
Conditional backward edges should help "warm up" code

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#93554]
#93229 introduced a regression in how aggressively we quicken some `for` loops. Minimal example:

```py
def f(x: bool) -> None:
    for i in range(1_000_000):
        if x:
            pass
```

`f(True)` will quicken this code, but `f(False)` will not, even though both contain the same number of back edges. The issue is that we only quicken on *unconditional* backwards jumps, not on conditional ones.

We've known about this limitation for some time, in particular with regard to `while` loops. Since we check the loop condition at the bottom of `while` loops, one call is not enough to quicken `w`:

```py
def w() -> None:
    i = 0
    while i < 1_000_000:
        i += 1
```

@markshannon has expressed a preference for having all branches be forward (i.e. replacing backward `POP_JUMP_IF_FALSE(x)` instructions with `POP_JUMP_FORWARD_IF_TRUE(1); JUMP_BACKWARD(x)` in the assembler). @iritkatriel believes that this shouldn't be too difficult, based on recent assembler rewrites.

CC @sweeneyde 

### Linked PRs
* gh-119485

**Comment by sweeneyde** [comment]
Darn. Switching over to forward-only conditional jumps makes sense to me then.

**Comment by sweeneyde** [comment]
If it's easier to just revert https://github.com/python/cpython/pull/93229 for now, that is okay as well.

**Comment by iritkatriel** [comment]
@brandtbucher the assembler adds a basicblock with a branch [here ](https://github.com/python/cpython/blob/bb0b7689465c3aac3b1d7f68c8990009462c1ae5/Python/compile.c#L7469).

**Comment by brandtbucher** [comment]
This would need to happen later though, right? Like, at the last possible moment, after we've ordered the blocks and we're actually emitting concrete jump instructions?

The bummer is that I don't see a way to make this play nicely with the peepholer's jump elimination, unless we add a separate jump-to-jump elimination pass there. We may just need to accept that some optimization opportunities will slip through the cracks.

**Comment by sweeneyde** [comment]
> The bummer is that I don't see a way to make this play nicely with the peepholer's jump elimination, unless we add a separate jump-to-jump elimination pass there.

Couldn't we do jump-to-jump-elimination first, then afterward convert conditional backward jumps to (conditional forward jump + `JUMP_BACKWARD`)? I don't know how common chains of three jumps in a row are, but at least then those would be converted to only two jumps in a row (conditional_forward+backward).

**Comment by brandtbucher** [comment]
Most jump elimination will still work fine, but I'm anticipating weird edge-cases with this new transformation.

I'm picturing something like `POP_JUMP_IF_FALSE(<backward>); JUMP(<forward>)`. Peepholing can't do anything with that, but the assembler will turn it into `POP_JUMP_FORWARD_IF_FALSE(1); JUMP_BACKWARD(<backward>); JUMP_FORWARD(<forward>)`. So we miss an opportunity to eliminate a jump (and potentially a whole block).

**Comment by brandtbucher** [comment]
It's related to the issue with `FOR_ITER` jumping to `JUMP` now. By the time we find out if it's a legal transformation, it's too late.

**Comment by sweeneyde** [comment]
Would that be solved by having separate cases like this?

```
case [COND_JUMP(backward to A), JUMP(forward to B)]:
    replace with [INVERTED_COND_JUMP(forward to B), JUMP_BACKWARD(to A)]
case [COND_JUMP(backward to A), SOMETHING_ELSE]:
    replace with [INVERTED_COND_JUMP(forward to SOMETHING_ELSE), JUMP_BACKWARD(to A), SOMETHING_ELSE]
```

In the first case, Jump-To-Jump elimination will have already folded `JUMP(forward to B)` as much as possible, so there should be nothing left to fold.

**Comment by iritkatriel** [comment]
Can we move jump elimination later, just before we emit the code or is there a reason it needs to be earlier?

**Comment by iritkatriel** [comment]
We still need to add some tests for quicken of code in loops, as described here: https://github.com/python/cpython/pull/96318#issuecomment-1232241861
