### ISSUE TITLE
Replace bytebong.com reference

### ISSUE THREAD

**Issue by sblondon** [python/cpython#93573]
**Documentation**

In the [quick start section](https://docs.python.org/3.11/library/configparser.html#quick-start) of configparser module, there is an example with bytebong.com:
```
>>> 'bytebong.com' in config
False
```

Currently, such domain does not bind with website. Archive.org shows only robots.txt in the past. According to `whois`, the current expiration date is 2022-07-18.
```
$ whois bytebong.com
[...]
   Updated Date: 2021-09-30T12:55:07Z
   Creation Date: 2021-07-18T12:49:27Z
   Registry Expiry Date: 2022-07-18T12:49:27Z
[...]
```

The example was added (at least) 12 years ago so I don't think it's an emergency. However, I think it's safer for the future to change the domain to python.org so there is no risk of bad surprises (like cybersquatting). 

### Linked PRs
* gh-101953
* gh-101954

**Comment by architsinghal-mriirs** [comment]
Hi @sblondon Please assign. this issue to me

**Comment by arhadthedev** [comment]
@architsinghal-mriirs It's an open project, no preliminary assignment is required. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

**Comment by sblondon** [comment]
There is already a PR to fix it : https://github.com/python/cpython/pull/93574

**Comment by hauntsaninja** [comment]
Looks like this has been changed!
