### ISSUE TITLE
Python 3.10.5 installer fails to run on windows 11

### ISSUE THREAD

**Issue by chewett** [python/cpython#93577]
Apologies if this isn't the right place, I am happy to report this somewhere else if needed.

**Crash report**

When running the Python 3.10.5 installer it silently crashes before showing anything.

I have downloaded it from here: https://www.python.org/downloads/release/python-3105/

and am running: https://www.python.org/ftp/python/3.10.5/python-3.10.5-amd64.exe

The Python 3.10.4 installer works fine.
On another computer of similar spec the python 3.10.5 installer works

**Error messages**

Windows Application error:

Faulting application name: python-3.10.5-amd64.exe, version: 3.10.5150.0, time stamp: 0x5a10ad86
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0301092d
Faulting process ID: 0x2538
Faulting application start time: 0x01d87a57dc7d9d48
Faulting application path: C:\Users\username\Downloads\python-3.10.5-amd64.exe
Faulting module path: unknown
Report ID: 104d5a0f-3ee6-47f0-8f89-37d0c7b30b7e
Faulting package full name: 
Faulting package-relative application ID: 

**Your environment**

32 GB of RAM
Intel i7-10510U 
Windows 11 Pro Version 21H2 Build 22000.613

Python 3.9.1 is installed
Python 3.10.4 is installed

**Comment by vstinner** [comment]
cc @zooba

**Comment by zooba** [comment]
Do you have a log file from your `%TEMP%` directory? That will help us see how far it got.

**Comment by zooba** [comment]
Also, check your Downloads folder for any DLL files. It's a known attack vector for sites to try and drop malicious DLLs into Downloads folders that get loaded by installers, and while ours ought to protect against that, it's possible that a new method has been found.

**Comment by chewett** [comment]
> Do you have a log file from your %TEMP% directory? That will help us see how far it got.

There are a few logs for python 3.10.4 (which I installed today to test it) but none for Python 3.10.5

Is there a way to run the installer in a debug mode or something to get more information?

> Also, check your Downloads folder for any DLL files. It's a known attack vector for sites to try and drop malicious DLLs into Downloads folders that get loaded by installers, and while ours ought to protect against that, it's possible that a new method has been found.

It still crashes with an empty downloads folder.

I have also moved it to a folder under "desktop" and it still crashes.

**Comment by zooba** [comment]
> Is there a way to run the installer in a debug mode or something to get more information?

Only under an actual debugger (Visual Studio or Debugging Tools for Windows). Or if you enable telemetry on your machine and let it submit error reports to Microsoft, I'll be able to look those up in a couple of days.

**Comment by chewett** [comment]
Thanks, I will see if I can dig into the issue and if I can't find any more information I will close this ticket.
