### ISSUE TITLE
make altinstall for PGO is not parallel-safe

### ISSUE THREAD

**Issue by tiran** [python/cpython#93584]
**Bug report**

``setup.py`` has a helper method [``add_multiarch_paths``](https://github.com/python/cpython/blob/70690c7233aaad4431660a64daef81b5220e2ac1/setup.py#L688-L696). The method creates a temporary file ``build/lib.{platform}/multiarch`` and unlinks it at the end of the function call. This is not parallel-safe.

PGO builds of Python use ``$(MAKE)``, so called *recursive make*. [Recursive makes are considered harmful](https://accu.org/journals/overload/14/71/miller_2004/) because the main make process has no understanding what the child make process is doing. With heavy parallel makes this can cause race conditions.

The combination of unsafe ``add_multiarch_paths()``, recursive make and loooots of CPU cores can lead to build issues like https://github.com/python/cpython/issues/84461#issuecomment-1148672087.

**Possible workarounds**

1) Rewrite our Makefile to not use ``$(MAKE)``
2) Move ``CC -print-multiarch`` and ``dpkg-architecture ... -qDEB_HOST_MULTIARCH`` calls to ``configure.ac``
3) Fix ``_bootsubprocess.check_output()`` and ``add_multiarch_paths()`` to use a more safe tmp file

Option (3) is the simplest approach. Even ``tmpfile = os.path.join(self.build_temp, f'multiarch-{os.getpid()}')`` would be good enough to avoid file conflicts in parallel builds.

**Comment by tiran** [comment]
My PR solved the race condition in ``add_multiarch_paths()`` but revealed another race condition later.

@pablogsal 's problem is caused by the fact that PGO builds use recursive make. The ``sharedmods`` target and the ``profile-opt`` target run ``./python setup.py build`` at the same time. ``setup.py`` is not designed to be parallel-safe.

**Comment by tiran** [comment]
Did you create a build with ``configure --enable-optimizations``? The issue only occurs with PGO builds.

**Comment by ethanhs** [comment]
Yeah, I was running a script in a loop using the steps from Pablo's reproducer here: https://github.com/python/cpython/issues/84461#issuecomment-1148640586

After 2 hours it still hadn't failed

**Comment by pablogsal** [comment]
> Yeah, I was running a script in a loop using the steps from Pablo's reproducer here: [#84461 (comment)](https://github.com/python/cpython/issues/84461#issuecomment-1148640586)
> 
> After 2 hours it still hadn't failed

That's odd. I gave been able to reproduce in many systems, including Linux with arch Linux and RHEL7

**Comment by tiran** [comment]
In comment https://github.com/python/cpython/pull/93589#issuecomment-1149077998 @nascheme suggested to rename some of the targets to make the intention more clear. I like the idea, but I don't want to mix improvements with a release blocker fix.

**Comment by tiran** [comment]
@pablogsal As far as I know this bug has been fixed by GH-93589.
