### ISSUE TITLE
Not being able to install Python 2.7 on MacOS Monterey 12.4

### ISSUE THREAD

**Issue by SergDevy** [python/cpython#93595]
Hey, I am trying to install Python 2.7 on my MacBook Air which runs macOS Monterey 12.4. I am trying to install it so that I can use Cocos2d-x. The issue that occurs is it is trying to install something, but there is nothing to install.

I don't know if this is a problem with my MacBook or if this is a Python problem. Any help is appreciated!

**Comment by corona10** [comment]
Sorry, Python 2.7 is EOL, we don't have plans to fix CPython 2.7 anymore.
