### ISSUE TITLE
Dataclasses slots causes super() to raise TypeError

### ISSUE THREAD

**Issue by Bluenix2** [python/cpython#93593]
## Summary

Attempting to use `super()` with a dataclass which has `slots=True` specified raises a `TypeError: super(type, obj): obj must be an instance or subtype of type`.

## Reproducible example

```pycon
>>> from dataclasses import dataclass
>>> 
>>> 
>>> @dataclass(slots=True)
... class Base:
...     def __eq__(self, other: object) -> bool:
...         raise RuntimeError
...
>>>
>>> @dataclass(slots=True)
... class Subclass(Base):
...     def __eq__(self, other: object) -> bool:
...         return super().__eq__(other) and False
...
>>> Subclass() == Subclass()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __eq__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

### Environemnt

This is run on CPython 3.10 with a file containing the current code found under `Lib/dataclasses.py` as of opening this issue.

---

@ericvsmith

**Comment by JelleZijlstra** [comment]
Related: #90562

**Comment by Bluenix2** [comment]
Yes this appears to be a duplicate
