### ISSUE TITLE
`__future__.annotations` has inaccurate `mandatoryRelease` value

### ISSUE THREAD

**Issue by KotlinIsland** [python/cpython#93626]
`future.__annotations__` has been postponed, yet it is active in the 3.11 betas.

- PR: #93628

\>A clear and concise description of the issue.

https://docs.python.org/3.11/whatsnew/3.11.html

This page doesn't mention [pep 563](https://peps.python.org/pep-0563/) at all.

**Comment by JelleZijlstra** [comment]
PEP 563 has been deferred. There will be no behavior changes around the future import in 3.11. See https://docs.python.org/3.10/library/__future__.html#id1

**Comment by KotlinIsland** [comment]
https://github.com/python/cpython/blob/68f6a5da199826fef1098f869d8d2260aaccff8e/Lib/__future__.py#L145-L147

Does this need to be updated then?

**Comment by KotlinIsland** [comment]
Maybe the What's new could mention that it has been delayed again.

**Comment by graingert** [comment]
could it be set to `None` instead?

https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/__future__.py#L35-L36

the wording could be changed to say:

 MandatoryRelease may also be None, meaning that a planned feature has
no predicted release or has been dropped.

**Comment by KotlinIsland** [comment]
I've made that change.

**Comment by KotlinIsland** [comment]
@JelleZijlstra Could this be reopened?

**Comment by graingert** [comment]
Imho this is a release blocker

**Comment by zware** [comment]
I see no need for this to block beta 4, but it should be resolved before final release.

/cc @pablogsal
