### ISSUE TITLE
Tkinter font removes button rounding

### ISSUE THREAD

**Issue by Moosems** [python/cpython#93620]
**Bug report**

I have been messing around with tkinter in the newest version 3.10.4 and have noticed that when you use a special font on a button that it loses the rounding. How do I use a special font while keeping it round?

Code:

```python
from tkinter import *
window = Tk()
Button(window, text="Example", font=("Courier New bold", 15)).pack()
window.mainloop()
```

Image:

<img width="211" alt="Screen Shot 2022-05-24 at 4 09 45 PM" src="https://user-images.githubusercontent.com/95927277/172730377-e4505a96-6bae-499a-b83f-8f07de07e46e.png">

**Your environment**

- CPython versions tested on: Python 3.10.4
- Operating system and architecture: MacOSX

**Comment by Moosems** [comment]
Is there any way to keep the rounding without using ttk?

**Comment by serhiy-storchaka** [comment]
Tkinter is a relatively thin wrapper around the Tk library. Use the Tk bug tracker to file a report.

I guess that Tk uses native macOS buttons if it can. But when you specify the font, it falls back to different implementation, because native macOS buttons do not support non-standard font.
