### ISSUE TITLE
all the python test.regrtest crashed

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#93625]
when i use  `./python -m test.regrtest --pgo -j0 || true`, it run ok.

but when i run `./python -m test.regrtest --pgo -j0 || true` with bep-env that control timestamps to keep timestamps consistent. it run crashed. all the test crashed. 

![image](https://user-images.githubusercontent.com/67537842/172751287-24be2600-d826-4258-9fbd-1f1dd26d3b9b.png)

bep-env is our self-developed tool to control timestamps to be consistent.

**Comment by AA-Turner** [comment]
Hi,

I'm closing this as it only crashes with your custom internal tool -- please ensure the bug isn't in that, and if not share a minimal reproduceable example of the bug. Additionally, pasting images is very unhelpful as maintainers can't then directly use the text when debugging.

A
