### ISSUE TITLE
cpython\Modules\socketmodule.c(7473,5): error C2065: 'HVSOCKET_CONTAINE R_PASSTHRU': undeclared identifier

### ISSUE THREAD

**Issue by jschwar313** [python/cpython#93656]
**Bug report**

I forked the main branch on cpython and cloned it to my local Windows environment.  I then ran build.bat -e -d in my windows cmd as an administrator and I received the above error.

**Your environment**

I have 64-bit python 3.10.4 on Windows 10 64-bit version 21H2 (OS build 19044.1741)
I have visual studio 2019 Community Edition installed Version 16.11.15

Here is the output from running the build script as mentioned below.

H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild>build.bat -e -d
Using py -3.10 (found 3.10 with py.exe)
Fetching external libraries...
bzip2-1.0.8 already exists, skipping.
sqlite-3.38.4.0 already exists, skipping.
xz-5.2.5 already exists, skipping.
zlib-1.2.12 already exists, skipping.
Fetching external binaries...
libffi-3.4.2 already exists, skipping.
openssl-bin-1.1.1n already exists, skipping.
tcltk-8.6.12.1 already exists, skipping.
Finished.
Using "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" (found in the Visual Studio installation)
Using py -3.10 (found 3.10 with py.exe)

H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" "H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\pcbuild.proj" /t:Build /m /nologo /v:m /clp:summary /p:Configuration=Debug /p:Platform=x64 /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=true /p:UseTestMarker= /p:GIT="C:\Program Files\Git\cmd\git.exe"
  _freeze_module.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\win32\_freeze_module_d.exe
  Killing any running python_d.exe instances...
  Generated sources are up to date
  Getting build info from "C:\Program Files\Git\cmd\git.exe"
  Building heads/main:30610d2837 main
  deepfreeze.c
  pythoncore.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\python312_d.dll
  _ctypes_test.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_ctypes_test_d.pyd
  _testbuffer.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testbuffer_d.pyd
  _testcapi.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testcapi_d.pyd
  _testinternalcapi.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testinternalcapi_
  d.pyd
  _testembed.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testembed_d.exe
  _testimportmultiple.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testimportmulti
  ple_d.pyd
  _testmultiphase.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testmultiphase_d.py
  d
  _testconsole.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_testconsole_d.pyd
  python3dll.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\python3_d.dll
  _overlapped.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_overlapped_d.pyd
  pyexpat.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\pyexpat_d.pyd
  pywlauncher.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\pyw_d.exe
  venvwlauncher.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\venvwlauncher_d.exe
  _msi.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_msi_d.pyd
  pylauncher.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\py_d.exe
  venvlauncher.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\venvlauncher_d.exe
  _elementtree.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_elementtree_d.pyd
  pyshellext.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\pyshellext_d.dll
  _zoneinfo.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_zoneinfo_d.pyd
  _queue.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_queue_d.pyd
  _multiprocessing.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_multiprocessing_d.
  pyd
  _decimal.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_decimal_d.pyd
  _asyncio.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_asyncio_d.pyd
  _ctypes.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_ctypes_d.pyd
  sqlite3.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\sqlite3_d.dll
  select.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\select_d.pyd
  socketmodule.c
  unicodedata.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\unicodedata_d.pyd
  _bz2.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_bz2_d.pyd
  winsound.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\winsound_d.pyd
  _uuid.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_uuid_d.pyd
  _tkinter.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_tkinter_d.pyd
  liblzma.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\liblzma_d.lib
  _sqlite3.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_sqlite3_d.pyd
  _hashlib.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_hashlib_d.pyd
  _lzma.vcxproj -> H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\amd64\_lzma_d.pyd
H:\Users\LindaJim\Documents\SourceCode\Software\cpython\Modules\socketmodule.c(7473,5): error C2065: 'HVSOCKET_CONTAINE
R_PASSTHRU': undeclared identifier [H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\_socket.vcxproj]

Build FAILED.

H:\Users\LindaJim\Documents\SourceCode\Software\cpython\Modules\socketmodule.c(7473,5): error C2065: 'HVSOCKET_CONTAINE
R_PASSTHRU': undeclared identifier [H:\Users\LindaJim\Documents\SourceCode\Software\cpython\PCbuild\_socket.vcxproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:12.76

**Comment by jschwar313** [comment]
The main branch I forked in GitHub is https://github.com/python/cpython

**Comment by erlend-aasland** [comment]
If the HV socket feature was added in Windows 10, we should add a guard for Windows 10 for this feature, and also update the docs to mention this.

**Comment by jborean93** [comment]
Is there an expectation of a minimum Windows version for building CPython? If there isn't we can probably add a guard to get it compiling on older hosts but if there is, do we want to go out of our way to get it working. I'm happy either way, I just don't know what the general practice for all this is.

We can certainly add docs to state the Hyper-V sockets will only work on Windows 10/Server 2016. The only thing I will add is it looks like Python 3.12 will be coming out in 2023-10 which is pretty much the EOL of Server 2012, 2012 R2, and Win 8. Does Python follow this same support cycle for what Windows versions it runs on?

**Comment by erlend-aasland** [comment]
I'll let @zooba take over from here :) I don't use Windows, and I don't know which Windows version Python 3.12 will or should support.

**Comment by zooba** [comment]
We can certainly rule out older Windows SDKs. Those are forwards/backwards compatible, so anyone can use the latest one regardless of what version of Windows they are building on or targeting.

`PCbuild/project.props` contains a minimum WinSDK version, which will be upgraded if a newer one is detected. If we know which version is required, that field can just be updated.

**Comment by erlend-aasland** [comment]
`PCbuild/pcbuild.proj`, I presume? :)

**Comment by zooba** [comment]
No, it's in the props file that gets imported by each project.

**Comment by erlend-aasland** [comment]
Got it, thanks!

**Comment by jschwar313** [comment]
What do you mean by “closing as not planned”?  Could you please explain that more clearly?

**Comment by erlend-aasland** [comment]
> What do you mean by “closing as not planned”? Could you please explain that more clearly?

If you follow the link in my last post, you'll see that the PR it leads to removes the HVSOCKET_CONTAINER_PASSTHRU constant from socketmodule.c.

No problematic constant => no compilation warning => no issue => we close the issue as "not planned"
