### ISSUE TITLE
pathlib has no docstring

### ISSUE THREAD

**Issue by RhysU** [python/cpython#93654]
**Documentation**

Oddly, `pathlib` has no docstring: https://github.com/python/cpython/blob/main/Lib/pathlib.py

```
>>> import pathlib
>>> type(pathlib.__doc__)
<class 'NoneType'>
```

**Comment by RhysU** [comment]
`This module offers classes representing filesystem paths with semantics appropriate for different operating systems.` or some shortened version thereof is probably sensible, lifting from https://docs.python.org/3/library/pathlib.html#module-pathlib

**Comment by AA-Turner** [comment]
The first 0.1 release on PyPI didn't have a docstring either! (https://pypi.org/project/pathlib/0.1/#files)

cc: @pitrou @barneygale 

A
