### ISSUE TITLE
Specialising LOAD_ATTR for mutable class attributes

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#93657]
Currently the following code doesn't specialise:
```
from enum import Enum
class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

def f():
 for _ in range(10):
  Color.RED

f()
```

This use pattern is very common in enums and also the recommended way to check constants in pattern matching. Specialising for ~this~ all mutable class attributes should speed up those use cases.

**Comment by rhettinger** [comment]
I don't see any reason to preference one namespace over another.  I expect that  instance namespaces will be dominant in practice, followed by some mix of class namespaces, module namespaces, SimpleNamespaces, and descriptors.  In practice, non-enum attribute lookups dominate the Python world.

**Comment by Fidget-Spinner** [comment]
i misphrased. When specializing for enums it would specialize for all mutable class attributes, not just enums. I just pointed out the enum pattern to justify spending the time and code. I don't plan to really specialise for the enum type (I'm not sure how to even do that to begin with).

**Comment by Fidget-Spinner** [comment]
I'm going to wait until https://github.com/python/cpython/issues/93429 is merged. That will expand the `LOAD_ATTR` cache slightly.

**Comment by Fidget-Spinner** [comment]
Thanks to #94614 and #93910 we don't need this anymore.
