### ISSUE TITLE
data_files is deprecated

### ISSUE THREAD

**Issue by cdfarrow** [python/cpython#93668]
According to [setuptools documentation](https://setuptools.pypa.io/en/latest/references/keywords.html) `data_files` has been deprecated. This should be made clear in [this](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#data-files) section.

**Comment by hauntsaninja** [comment]
This isn't the correct repo to discuss this, please consider opening an issue at https://github.com/pypa/packaging.python.org
