### ISSUE TITLE
Descriptions of package_dir parameter seem to be wrong or unclear

### ISSUE THREAD

**Issue by cdfarrow** [python/cpython#93666]
I've been having a hard time understanding how package_dir works, and I think that some of the descriptions could do with fixing or clarifying. I see other people with similar confusions to me. (e.g. [here](https://github.com/pypa/setuptools/discussions/3194), [here](https://github.com/pypa/setuptools/issues/3184), and [here](https://stackoverflow.com/questions/17155804/confused-about-the-package-dir-and-packages-settings-in-setup-py).)

[2.1. Listing whole packages](https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages)

> If you use a different convention to lay out your source directory, that’s no problem: you just have to supply the package_dir option to tell the Distutils about your convention. For example, say you keep all Python source under lib, so that modules in the “root package” (i.e., not in any package at all) are in lib, modules in the foo package are in lib/foo, and so forth. Then you would put `package_dir = {'': 'lib'}` in your setup script.

The example syntax here is the same as for the "src layout", but the description seems to be saying that the Python source is directly under lib (as well as lib/foo) rather than in a sub-folder of lib. From my understanding this is wrong, and it shouldn't be talking about any code directly in the 'root package' because otherwise, these instructions would be putting (e.g.) lib\mypkg.py into site-packages directly instead of into site-packages\mypackagename.

The next part talks about putting code directly in lib, which is what it sounded like the first part was saying.
Then it says:

> A `package: dir` entry in the `package_dir` dictionary implicitly applies to all packages below package, so the foo.bar case is automatically handled here. In this example, having `packages = ['foo', 'foo.bar']` tells the Distutils to look for `lib/__init__.py` and `lib/bar/__init__.py`. (Keep in mind that although package_dir applies recursively, you must explicitly list all packages in packages: the Distutils will not recursively scan your source tree looking for any directory with an `__init__.py` file.)
This sounds contradictory: it says, "the foo.bar case is automatically handled", but then foo.bar is included in the example `packages=` entry, and then it says, "you must explicitly list all packages in packages". So, is it automatic or not?; or are they talking about different things? In that case it could be made clearer.

[Tutorial: Configuring metadata](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
Describing package_dir it says:
> `package_dir` is a mapping of package names and directories. An empty package name represents the “root package” — the directory in the project that contains all Python source files for the package — so in this case the src directory is designated the root package.

Again, the reference to 'root package' seems to refer to a folder full of .py files. It should be stated more clearly that there should be sub-folders (under src) otherwise the user is going to get the .py files in site-packages instead of a sub-folder. I haven't come across any documentation that clearly describes how all of this translates to the actual installation (or structure inside the wheel). So I suggest the following edits (changes marked italics}:

`package_dir` is a mapping of _installed_ package names to _source_ directories _that will become those packages_. An empty package name represents the root _of the installed package_ — _i.e. the site-packages directory itself._ So, in this case the src directory is designated _as_ the root package, _so that the example_package folder in this project will be installed into site-packages\example_package_.

**Comment by kumaraditya303** [comment]
This is not a CPython so closing, You should report this to setuptools repo.
