### ISSUE TITLE
Regex VERBOSE mode doesn't do all substitutions

### ISSUE THREAD

**Issue by Peterl777** [python/cpython#93664]
Regex substitution when used with VERBOSE mode doesn't work correctly. It appears to be limited to 64 substitutions when in VERBOSE mode?

Steps to reproduce:
Without VERBOSE mode substitution works correctly:
(Substituting all `x` with `@` in a string of 67 `x`)

```
>>> import re

>>> re.sub("x", "@", "x" * 67)
'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'

```
With VERBOSE mode substitution doesn't do all the substitutions:
```
>>> re.sub("x", "@", "x" * 67, re.VERBOSE)
'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@xxx'

```
Tested on Windows 10, CPython v3.10.5 and 3.9.7

**Comment by pochmann** [comment]
You used the flag as the `count` value:
```
re.sub(pattern, repl, string, count=0, flags=0)
```

**Comment by Peterl777** [comment]
Oh I got caught by this before! Thank you for reminding me.

**Comment by hauntsaninja** [comment]
Thanks for spotting that pochmann! Keyword arguments are great.
