### ISSUE TITLE
monetary argument to locale.format_string() not working as expected

### ISSUE THREAD

**Issue by annaraven** [python/cpython#93669]
The new 3.7+ keyword argument _monetary_ to locale.format_string() does not appear to do anything. Example below:

>>> locale.setlocale(locale.LC_NUMERIC, 'it')
'it'
>>> locale.setlocale(locale.LC_MONETARY, 'it')
'it'
>>> locale.format_string('%d', 100000)
'100000'
>>> locale.format_string('%d', 100000, grouping=True)
'100.000' #groups as expected with Italian thousands separator
>>> locale.format_string('%d', 100000, monetary=True)
'100000' #not the expected result! Expected '100.000,00' 
>>> locale.format_string('%d', 100000, grouping=True, monetary=True)
'100.000' #no difference from just "grouping=True"
>>> locale.format_string('%f', 100000, grouping=True, monetary=True)
'100.000,000000' #definitely not the expected result. I expected 2 decimal places. 
>>> locale.currency(100000, grouping=True)
'100.000,00 €' # THIS is the expected result, just a sanity check to make sure LC_MONETARY is appropriately set.

Example from: Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Similar results on a Mac running macOS Monterey version 12.3.1 and Python 3.10.5

**Comment by eryksun** [comment]
`monetary=True` switches to using "mon_decimal_point", "mon_thousands_sep", and "mon_grouping" from `locale.localeconv()`. Offhand, I don't know of a locale for which the monetary syntax differs from the regular "decimal_point", "thousands_sep", and "grouping". The "currency_symbol" is not included in the formatted output, unlike the default for `locale.currency()`. If you want grouping, you still have to pass `grouping=True`. For example:

```
>>> locale.setlocale(locale.LC_ALL, 'en_DK.utf8')
'en_DK.utf8'
>>> locale.format_string('%.2f', 100000, grouping=False, monetary=True)
'100000,00'
>>> locale.format_string('%.2f', 100000, grouping=True, monetary=True)
'100.000,00'
```

**Comment by annaraven** [comment]
Yeah - I finally figured out that monetary=True is for *overriding*  grouping to use LC_MONETARY syntax instead of LC_NUMERIC. That was unclear to me from the docs - I thought monetary was its own separate argument, not one that worked in conjunction with grouping=True. 

I can see an example where someone might set LC_NUMERIC to, say US english, and LC_MONETARY to some european language. In that case, if you set grouping=True, you'll get one result, if you additionally set monetary=True, you'll get another result.  

>>> locale.setlocale(locale.LC_MONETARY, 'it_it')
'it_it'
>>> locale.setlocale(locale.LC_NUMERIC, 'en_US')
'en_US'
>>> locale.format_string('%0.2f', n, grouping=True)
'1,800,000.00'
>>> locale.format_string('%0.2f', n, grouping=True, monetary=True)
'1.800.000,00'
>>>

I think I should just close this bug, but it might be useful to clarify in the docs that monetary=True is in *addition* to grouping, not instead of.

**Comment by eryksun** [comment]
> monetary=True is in _addition_ to grouping, not instead of.

However, it's separate from grouping if you're only interested in the monetary decimal point, which is why enabling `monetary` doesn't implicitly enable `grouping`.

**Comment by annaraven** [comment]
Thank you! That's the final piece I was missing. Thanks for your help.
