### ISSUE TITLE
SymbolTable.get_identifiers() docstring return value incorrect

### ISSUE THREAD

**Issue by pamelafox** [python/cpython#93660]
**Documentation**

SymbolTable.get_identifiers() currently says:
"Return a list of names of symbols in this table."

However, the returned value is actually dict_keys, a dictionary view object, which doesn't support everything that a list does (notably, it's not subscriptable).

I have a PR with a proposed change incoming.

**Comment by pamelafox** [comment]
Alternatively, that method could return a list by wrapping the return value in list(), but that could potentially be backward incompatible so I assume its preferable to just update the documentation.

**Comment by hauntsaninja** [comment]
Thanks for spotting this! As an aside, looks like the type in typeshed is also incorrect, in case you feel like making another PR: https://github.com/python/typeshed/blob/ad48606a0d901d907f2428917d7a5f97959b4733/stdlib/symtable.pyi#L21 :-)

**Comment by pamelafox** [comment]
Sure, typeshed PR is here:
https://github.com/python/typeshed/pull/8054
CPython PR is here:
https://github.com/python/cpython/pull/93661

**Comment by AlexWaygood** [comment]
Fixed in:

- #93661
- https://github.com/python/cpython/pull/93722
- https://github.com/python/cpython/pull/93723

Thanks, @pamelafox!
