### ISSUE TITLE
Direct unit tests for compiler optimisations

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#93678]
We currently do not have a way to directly test compiler optimisations, and the tests we have are not always reliable ([more background](https://github.com/faster-cpython/ideas/issues/405)).

We need to be able to feed a sequence of bytecode instructions into the optimiser from python, and get its output back into python. Then we can write tests.

**Comment by tiran** [comment]
The PR seems to have increase stack consumption slightly. Some tests are now failing on WASI because the WASM runtime is running out of stack space, https://buildbot.python.org/all/#/builders/1046/builds/278

In the past I have solved similar issues by replacing a hard-coded limit (e.g. 1000) with the current recursion limit. WASI has a lower default recursion limit.

**Comment by iritkatriel** [comment]
> The PR seems to have increase stack consumption slightly. Some tests are now failing on WASI because the WASM runtime is running out of stack space, https://buildbot.python.org/all/#/builders/1046/builds/278
> 
> In the past I have solved similar issues by replacing a hard-coded limit (e.g. 1000) with the current recursion limit. WASI has a lower default recursion limit.

Thank for the ping. I would guess it's because we now have things like `compiler_new_block` calling `cfg_builder_new_block`. It basically glue to avoid changing all the calls. I'll inline/replace them in a future PR.

**Comment by tiran** [comment]
Let me try if ``inline`` helps.

**Comment by tiran** [comment]
Sprinkling ``inline`` over ``compile.c`` does not help.

**Comment by tiran** [comment]
I have added a temporary band-aid in GH-95296. Feel free to remove the skips if you have a solution for the additional stack use.

**Comment by iritkatriel** [comment]
> I have added a temporary band-aid in [GH-95296](https://github.com/python/cpython/pull/95296). Feel free to remove the skips if you have a solution for the additional stack use.

Is there a way I can reproduce it?

**Comment by iritkatriel** [comment]
I created https://github.com/python/cpython/issues/95335 to track the WASM problem.
