### ISSUE TITLE
Python3.10.5 Pattern Matching Excessive Memory Consumption

### ISSUE THREAD

**Issue by tom-p-reichel** [python/cpython#93671]
**Crash report**

While writing some code to match a particularly complicated AST, I accidentally wrote a function whose definition causes the Python 3.10.5 interpreter to rapidly consume memory. On my system, it consumed approximately 24 GBs of memory before being killed.

The function is as follows:

```python
def defines(self):
        match self.ast:
                case [S('CoqAst'), [[S('v'), [_, _, [S('expr'), [S('VernacDefinition'), [S('NoDischarge'), S('Definition')], [[[S('v'), [S('Name'), [S('Id'), S(name)]]], _], []], [S('DefineBody'), [], [], [_, _], []]]]]], _]]
                | [S('CoqAst'), [[S('v'), [[S('control'), []], [S('attrs'), []], [S('expr'), [S('VernacStartTheoremProof'), S('Theorem'), [[[[[S('v'), [S('Id'), name]], _], []], _]]]]]], _]]:
                        return name

```

To replicate, paste the above function into a python file and run it.

**Error messages**

OOM killing produced no output, save for `Killed`. 

**Your environment**

- CPython versions tested on: 3.10.5
- Operating system and architecture: Tested on both Windows 10 and ArchLinux.

**Comment by Fidget-Spinner** [comment]
Wow. I can reproduce this on 3.11 and 3.12(main) too.

**Comment by kumaraditya303** [comment]
This seems like a parser issue.

Linux perf output:

```console
Samples: 36K of event 'cpu-clock:pppH', Event count (approx.): 9100000000
Overhead  Command  Shared Object       Symbol
   7.30%  python   python              [.] _PyPegen_expect_token
   6.68%  python   [kernel.kallsyms]   [k] clear_page_erms
   6.28%  python   [kernel.kallsyms]   [k] __do_page_fault
   4.64%  python   python              [.] closed_pattern_rule
   4.09%  python   python              [.] _PyArena_Malloc
   3.36%  python   python              [.] signed_real_number_rule
   3.09%  python   libc-2.31.so        [.] _int_malloc
   3.05%  python   python              [.] or_pattern_rule
   2.84%  python   python              [.] unicodekeys_lookup_unicode
```

**Comment by dignissimus** [comment]
It might be the related to the depth of the statement, the following also produces a crash
```python
match p:
    case [[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]:
        pass
```

**Comment by pablogsal** [comment]
Thanks, @tom-p-reichel and @dignissimus for the report and thanks a lot @kumaraditya303 for the initial investigation. Great work!
