### ISSUE TITLE
logging.LogRecord.getMessage() is cashed, but cash is not used

### ISSUE THREAD

**Issue by jburget** [python/cpython#93713]
I tried [this example](https://docs.python.org/3/howto/logging-cookbook.html#use-of-alternative-formatting-styles) from the logging docs with some modifications. 
I found, that whenever `LogRecord` is processed by `Formatter`, (so for every `Handler`, that handles the `LogRecord`),
message is recreated again. You can replicate the problem with running this code:

```python
from logging import getLogger, LoggerAdapter, DEBUG, Formatter, StreamHandler
import traceback


class Message:
    def __init__(self, message):
        self.message = message

    def __str__(self):
        print(f"formatting {self.message=}")
        # traceback.print_stack()
        return self.message


class Adapter(LoggerAdapter):

    def __init__(self, logger, extra=None):
        super().__init__(logger, extra or {})

    def log(self, level, msg, *args, **kwargs):
        super().log(level, Message(msg), *args, **kwargs)


root = Adapter(getLogger())
root.logger.setLevel(DEBUG)
stream1 = StreamHandler()
stream1.setLevel(DEBUG)
stream1.setFormatter(Formatter("%(asctime)s - %(levelname)s - %(funcName)s - %(message)s"))

stream2 = StreamHandler()
stream2.setLevel(DEBUG)
stream2.setFormatter(Formatter("%(asctime)s - %(levelname)s - %(funcName)s - %(message)s"))
root.logger.addHandler(stream1)
root.logger.addHandler(stream2)

root.info("info")
print()
root.critical("critical")
```
`__str__` is called every time `LogRecord` is processed by `Formatter`. 
Which is may quiet expensive. There is big effort to avoid formatting message, 
when it is not logged, I mean something like this is considerate to be a bad practise 
`logger.debug(f"debug {data}")`

The only case we would need to recreate `LogRecord.message` is when data in `LogRecord.args` are changed, for
example by custom `Filter`. But why anybody would want to do that? 
Cashing happens [here](https://github.com/python/cpython/blob/5849af7a80166e9e82040e082f22772bd7cf3061/Lib/logging/__init__.py#L703)

I am not sure why `LogRecord.message` is removed [here](https://github.com/python/cpython/blob/5849af7a80166e9e82040e082f22772bd7cf3061/Lib/logging/handlers.py#L644)

My final thoughts are, that `LogRecord.getMessage()` should cash the formatted message to `LogRecord.message`, not some method of `Formatter` like on the link above. Should return cash if present.

I will try to implement this. Will be my first contribution, looking forward to it.

**Comment by vsajip** [comment]
This is not a bug, and changing it may break existing code (e.g. if `__str__()` were to return different values, which could happen in some unusual cases, or if `Formatter` subclasses behave differently). The repeated recalculation of `message` has not led to any particular performance problems, and I don't want to change anything here - so I would suggest _not_ doing a PR for this. But thanks for your interest, and feel free to suggest any other things you think might be useful!
