### ISSUE TITLE
configparser case sensitivity

### ISSUE THREAD

**Issue by ghost** [python/cpython#93727]
**Feature or enhancement**

I propose to make configparser case sensitive by default 

**Pitch**

Config files are mainly used by systemd and systemd is case sensitive

**Previous discussion**

https://stackoverflow.com/questions/1611799/preserve-case-in-configparser
https://stackoverflow.com/questions/19359556/configparser-reads-capital-keys-and-make-them-lower-case
https://bytes.com/topic/python/answers/708398-why-does-configparser-change-names-lowercase
https://github.com/behave/behave/issues/320

**Comment by hauntsaninja** [comment]
Case insensitivity is clearly documented behaviour and this would be a breaking change. The stackoverflow links show that it's easy to add one line of code to get case sensitivity; this use of `optionxform` is also clearly documented .
