### ISSUE TITLE
Update C domain docs to Sphinx 3 syntax

### ISSUE THREAD

**Issue by AA-Turner** [python/cpython#93738]
Sphinx would like to remove support for the pre-v3 C domain syntax. We have confirmed that the Linux kernel is no longer using it, so Python is the only project we are blocked on.

I have [a branch](https://github.com/AA-Turner/cpython/tree/sphinx-3) where I've done the work, but it is a large number of files affected (~50) and the majority of the C-API documentation. The changes are almost all mechanical search-and-replace, but there are a few where I've had to use judgement.

Questions:

1. Is this change welcome?
2. How should I proceed with PRs? One per data type, per file, etc?
3. I would want to backport these changes to 3.10/3.11 (to allow future docs backports without conflicts), does anybody have objections?
4. Does anybody have other concerns?

cc: @vstinner @serhiy-storchaka @encukou @erlend-aasland @JelleZijlstra @hugovk (Selection of C-API/documentation people, if I've missed anyone please mention them).

A

### Tasks
- gh-97771
- gh-97784
- gh-97783
- gh-97782
- gh-97780
- gh-97773
- gh-97769
- gh-97770
- gh-97777
- gh-97776
- gh-97775
- gh-97778
- gh-97772
- gh-97774
- gh-97768
- gh-97962

**Comment by serhiy-storchaka** [comment]
What directives and roles can be used and what are gone?

> 1. Is this change welcome?

We do not have a choice, isn't?

> 2. How should I proceed with PRs? One per data type, per file, etc?

Could manual and automatic changes be separated, so intermediate results are still working? Say, first some preparing manual changes, then automatic changes, then final manual changes?

> 3. I would want to backport these changes to 3.10/3.11 (to allow future docs backports without conflicts), does anybody have objections?

Do not have objections if systems with 3.10 support Sphinx 3.

**Comment by AA-Turner** [comment]
> What directives and roles can be used and what are gone?

## Gone in 3.0-3.2:

Relaxed parsing. In Sphinx 2, a definition like ``:c:type:`const char*` `` was OK, but in Sphinx 3 this fails -- it should be a `:c:expr:`. ``:c:type:`PyObject*` `` is currently rendered in the docs with a link only to the "PyObject" part of the role text -- it should change to either having the `*` outside of the role (``:c:type:`PyObject`\*``) or being an expression (``:c:expr:`PyObject*` ``). Places where there are references to groups of functions using the type role are invalid (and currently don't work), these should be replaced with literal syntax (e.g. ``:c:func:`PyErr_Set\*` ``).

## New in 3.0-3.2, taken from [Sphinx's C domain docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-c-domain):

Directives:

- `.. c:macro:: name(arg list)` (Function style macro variant)
- `.. c:struct:: name`
- `.. c:union:: name`
- `.. c:enum:: name`
- `.. c:enumerator:: name`

Cross-referencing roles:

- `:c:var:` (alias of both `:c:member:` and `:c:data:`)
- `:c:struct:`
- `:c:union:`
- `:c:enum:`
- `:c:enumerator:`

Documentation support for anonymous entities (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#anonymous-entities)

Support for re-printing declarations in a list, e.g. for overviews of interfaces (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#aliasing-declarations)

Support for inline expresssions (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#inline-expressions-and-types):
- `:c:expr:` 
- `:c:texpr:` ("text-expression")

Support for documentation-namespaces (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#namespacing)

A

**Comment by hugovk** [comment]
> cc: @vstinner @serhiy-storchaka @encukou @erlend-aasland @JelleZijlstra @hugovk (Selection of C-API/documentation people, if I've missed anyone please mention them).

cc also @JulienPalard

**Comment by vstinner** [comment]
If I recall correctly, in 2020, I asked Sphinx to add an option to opt-in for the legacy C syntax. When it was discussed, the problem was that Sphinx supporting the new syntax was not widely available in Linux distributions. I guess that the situation changed and now it's perfectly fine to switch to the new syntax.

Doc/conf.py gives some context and links to bpo-40204:

```
# bpo-40204: Allow Sphinx 2 syntax in the C domain
c_allow_pre_v3 = True

# bpo-40204: Disable warnings on Sphinx 2 syntax of the C domain since the
# documentation is built with -W (warnings treated as errors).
c_warn_on_allowed_pre_v3 = False
```

> I would want to backport these changes to 3.10/3.11 (to allow future docs backports without conflicts)

I agree to backport for the reason that you give: make future backports simpler.

**Comment by encukou** [comment]
I've looked at the proposed branch. The commits there would make good individual PRs, IMO.
IMO we've now made it clear that documentation discussions live in the Discuss category. Perhaps mention there, and if no one objects, go ahead with PRs.


Some specific points:

Please keep/turn as many of these as possible as/into links. Many times this would just mean checking that the links are generated (and are correct).

AFAIK, Sphinx will parse `:c:expr:` expressions and linkify any types it finds, so <code>:c:expr:`const PyObject*`</code> will link to `PyObject`. If that's right, IMO the :c:type:`PyObject*` should be changed to `expr`, which is much easier to type than the ecaped star.
Or is there some disadvantage to `:c:expr:`?

References to a family of functions (glob patterns) like <code>:c:func:`PyArg_Parse\*` functions</code> link to the [section](https://docs.python.org/3/c-api/arg.html?highlight=pyarg_parse#api-functions) (especially for `PyArg_Parse` where not all of them actually use the prefix); other cases could use wording like <code>``PyArg_Parse*`` functions (such as :c:func:`PyArg_VaParse`)</code>

**Comment by AA-Turner** [comment]
Created at https://discuss.python.org/t/16500

A

**Comment by AA-Turner** [comment]
Thanks for the nudge Petr, 15 PRs later I've now covered all bases (I hope!) for the removal of the pre-v3 support. Some PRs are very trivial and can likely be merged instantly, some may need a few minutes to read through, but all are mechanical transformations.

A

**Comment by ezio-melotti** [comment]
I reviewed all the PRs and didn't notice any error, but I have a few general comments:
* instead of converting e.g. `` :c:type:`PyObject*` `` to `` :c:expr:`PyObject*` ``, could it be converted to `` :c:type:`PyObject* <PyObject>`  ``?
* similarly, in #97774, can't `:c:expr:` (or something more specific) be used instead of ` ``...`` `?  If not, could something like e.g. `` :c:func:`PyArg_Parse\* <PyArg_Parse>` ``  or `` :c:func:`!PyArg_Parse\*` `` be used instead of ` ``PyArg_Parse*`` `?

**Comment by encukou** [comment]
I suggested using ``` :c:expr:`PyObject*`  ``` in the previous comment. It is much easier to type than ``` c:type:`PyObject* <PyObject>` ``` (which is important since it comes up a lot). Is there some downside to `:c:expr:` that I don't see?

**Comment by serhiy-storchaka** [comment]
Does ``` :c:expr:`PyObject*` ``` create a link to PyObject? If yes, then there is no any downside.

**Comment by vstinner** [comment]
In general, Sphinx is able to understand that ``type*`` is a pointer to ``type``. See https://docs.python.org/dev/c-api/object.html : Sphinx adds links to PyObject on ``PyObject*``. I didn't check how ``:c:expr:`PyObject*` `` is rendered.

**Comment by AA-Turner** [comment]
> Sphinx adds links to PyObject on PyObject*. I didn't check how :c:expr:`PyObject*` is rendered.

I'll check the rendered docs for my PR, but just to note that this should be the same for `c:expr`, hence switching to it per Petr's suggestion vs `c:type` where we would have to escape the * or use the <> syntax.

A

**Comment by AA-Turner** [comment]
Done!

A

**Comment by vstinner** [comment]
I'm happy that CPython can now use the new Sphinx syntax for the ``c`` domain. It was annoying to have to support Sphinx 2 syntax. The Sphinx 3 syntax looks better and it's better rendered!
