### ISSUE TITLE
Mint: '_ctypes' are missing so no script runs

### ISSUE THREAD

**Issue by christian179717** [python/cpython#93748]
I hope this is the right respository to ask.

Everytime I want to run a python script or if I want to start some programs I get everytime a error:

```
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```
My OS is Mint

I've already done some research but if I try to install the mentioned package it always says it's already installed:
```
sudo apt-get install libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.3-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Do you have some help for me?

**Comment by ericvsmith** [comment]
You'd be better off asking this question on Stackoverflow or the python-list mailing list than on the bug tracker.

It depends on how you installed Python, and if the _ctypes module got built or not.

**Comment by christian179717** [comment]
But it is here possible too? So this question will be answered here and new ones I'll ask there?


I've installed python some months ago but thins problem is since few weeks. So it appears while it was installed and wasn't since the begin.

**Comment by corona10** [comment]
@christian179717 
Frankly speaking, this issue tracker is more about CPython implementation detail rather than troubleshooting.
But did you try to recompile CPython after you install the `libffi-dev` package?

**Comment by ericvsmith** [comment]
> But it is here possible too? So this question will be answered here and new ones I'll ask there?

No, this isn't the appropriate place to ask questions about installing or compiling Python. To make up an example: if you can demonstrate that there's a problem where _ctypes won't compile on your platform, then that would be a bug you could report here.

I'm going to close this issue, since it's not about a bug.

**Comment by christian179717** [comment]
I've compiled again, no PyQt5 is missing but I think I can do this in this way the hole time and it will work soon.

The problem was, that I didn't compiled again.
