### ISSUE TITLE
Add C API for importing an attribute from a module

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#93741]
It is common (more than 30 cases) in the C code to access a function or a variable from other module. For example:
```c
    functools = PyImport_ImportModule("functools");
    if (!functools)
        goto error;
    st->partial = PyObject_GetAttrString(functools, "partial");
    Py_CLEAR(functools);
```
 I propose to add a private helper function which combines `PyImport_ImportModule()` and `PyObject_GetAttrString()`.
```c
    st->partial = _PyImport_GetModuleAttrString("functools", "partial");
```
It will save 4-6 lines of code and a variable on every use.

**Comment by kumaraditya303** [comment]
Since this will a private API, how about using statically allocated string identifiers to avoid memory allocations?

**Comment by serhiy-storchaka** [comment]
The PR adds also function `_PyImport_GetModuleAttr()` which takes `PyObject*` arguments. You can use it with statically allocated string identifiers.
