### ISSUE TITLE
unicodedata.normalize: dotless i + acute accent should give i with acute

### ISSUE THREAD

**Issue by nschloe** [python/cpython#93767]
```python
from unicodedata import normalize

normalize("NFC", "\N{LATIN SMALL LETTER DOTLESS I}\N{COMBINING ACUTE ACCENT}").encode("ascii", "namereplace")
```
```python
b'\\N{LATIN SMALL LETTER DOTLESS I}\\N{COMBINING ACUTE ACCENT}'
```
when it should give
```python
b'\\N{LATIN SMALL LETTER I WITH ACUTE}'
```
When providing a regular dotted `i`, it already works correctly:
```python
normalize("NFC", "i\N{COMBINING ACUTE ACCENT}").encode("ascii", "namereplace")
```
```python
b'\\N{LATIN SMALL LETTER I WITH ACUTE}'
```

**Comment by mdickinson** [comment]
Related: https://stackoverflow.com/a/50087195

The comment from Jonas Schäfer on that answer looks particularly useful:

> [From TR15](https://www.unicode.org/reports/tr15/#Norm_Forms): toNFD(x)=toNFD(toNFC(x)), so if toNFC(x) composed ı+dot-above to i, toNFD(toNFC(x)) would be different from toNFD(x) (if i would not be decomposed to ı+dot-above; I don’t think that such a decomposition would be desirable).

So I think this isn't a bug. Or if it is a bug, it's a design bug in the Unicode standard rather than a Python bug.
