### ISSUE TITLE
none_dealloc fatal after 9c8e490b

### ISSUE THREAD

**Issue by oraluben** [python/cpython#93762]
**Bug report**

It seems to me that calling any function in C extension will trigger this error:

```
$./venv/bin/pip3 install .
...
$./venv/bin/python3 -c 'import _cds; _cds._set_mode(0)'
Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension
Python runtime state: finalizing (tstate=0x0000000000b2cef8)

Current thread 0x00007fecc3b63740 (most recent call first):
  <no Python frame>
Aborted
```

I met this while adapting my package to 3.11.
After some bisecting and deleting, I found the related commit is 9c8e490b, I also create a reproducer at https://github.com/oraluben/test-fini-crash, which contains a Dockerfile that build python from source and reproduce the bug.

cc @vstinner 

**Your environment**

- CPython versions tested on: 9c8e490b is buggy, previous one (1626bf4a) is good.
- Operating system and architecture: Tested on aarch64 Mac and x64 Linux

**Comment by vstinner** [comment]
The ``_cds`` extension is not part of Python.. Please report the issue to _cds bug tracker.

**Comment by vstinner** [comment]
In your reproducer:

```

static PyObject *
_cds__set_mode_impl(PyObject *module, int mode)
/*[clinic end generated code: output=ba43df118acf9262 input=d1ad8244814a77a7]*/
{
    return Py_None;
}
```

That's wrong. It must increment the reference count of Py_None. For example, use ``return Py_NewRef(Py_None);``.

**Comment by oraluben** [comment]
> That's wrong. It must increment the reference count of Py_None. For example, use `return Py_NewRef(Py_None);`.

Of course... Thanks!

**Comment by vstinner** [comment]
I'm happy that my none_dealloc() change helped you to spot a bug. I'm just surprised that the error message didn't list your C extension as "Extensions modules: _cds (total: 1)".

**Comment by oraluben** [comment]
> I'm happy that my none_dealloc() change helped you to spot a bug.

Thanks for that indeed, otherwise I cannot imagine how much time I'll spend in the future on this : )
