### ISSUE TITLE
My bug report got closed right after I opened it (#93775)

### ISSUE THREAD

**Issue by williamdavid900** [python/cpython#93777]
## I just submitted a bug report, but it got closed prematurely (#93775).

Sorry for this, but I don't know how to reopen a prematurely closed bug report (issue #93775). It documents a coding bug in **Lib/json/\_\_init\_\_.py)**.

When I edited the title, after submitting the issue, the bug report was marked as closed.  I don't know what I missed, but somehow I got the bug report closed prematurely.

Any help is appreciated,
Bill

**Comment by wtrenker** [comment]
Thanks for pointing me in the right direction.
