### ISSUE TITLE
Tkinter canvas visual bug on angled text

### ISSUE THREAD

**Issue by Unprex** [python/cpython#93778]
Hello,
I came across a visual bug on the tkinter canvas when changing the length of angled text.

Minimal example:

```python
import tkinter as tk

root = tk.Tk()
c = tk.Canvas(root, width=200, height=200)
text = "Hello World!00000000"
text_item = c.create_text(100, 100, text=text, angle=90)
c.pack()


def erase_text():
    global text
    text = text[1:]
    c.itemconfigure(text_item, text=text)
    if text:
        root.after(10, erase_text)


root.after(10, erase_text)
root.mainloop()
```
Result:

![image](https://user-images.githubusercontent.com/29612995/173401011-d40ae661-a419-4820-b879-876db0ce8b9c.png)

`c.delete(tk.ALL)` doesn't clear the canvas, but resizing the window or adding spaces at the end of the text *solves* the issue.
It only appends with certain characters and certain angles (numbers seem to work best and angle=0 doesn't reproduce the bug).

OS: Windows 10 Pro
Python: 3.10.4 / tkinter 8.6.12

**Comment by mrabarnett** [comment]
It shows the same problem even if you delete the item and then create a new one.

Given that the canvas is refreshed when it's resized, a workaround is to resize the canvas to its current size:

```python

def erase_text():
    global text
    text = text[1:]
    c.itemconfigure(text_item, text=text)
    c["width"], c["height"] = c["width"], c["height"]
    if text:
        root.after(10, erase_text)

```

**Comment by serhiy-storchaka** [comment]
Tkinter is a wrapper around the Tcl/Tk library. I do not see anything specific to the wrapper in this example. Most likely it is a bug in Tcl/Tk.

I cannot reproduce the bug on Linux. Try to call `c.update()` or `root.update()` after itemconfigure.

**Comment by mrabarnett** [comment]
@serhiy-storchaka: Tried that, didn't work. (Windows 10)

**Comment by serhiy-storchaka** [comment]
In any case this is not a Python issue. File a report on the Tk bug tracker.
