### ISSUE TITLE
Right parenthesis missing in Lib/json/__init__.py (all recent releases)

### ISSUE THREAD

**Issue by williamdavid900** [python/cpython#93775]
# Python 3.10.5 and previous releases

Line 293 in /Lib/json/\_\_init\_\_.py is missing a right parenthesis before the ending comma (see the details below). This happens in previous releases of Python as well.

$python3
Python 3.10.5 (main, Jun 11 2022, 16:53:24) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.load(open('/mnt/c/example/example.json'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  **File "/usr/lib/python3.10/json/\_\_init\_\_.py", line 293, in load
    return loads(fp.read(),**
  File "/usr/lib/python3.10/json/\_\_init\_\_.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 33 column 17 (char 574)
>>>

The specific problem in line 293 in Lib/json/\_\_init.\_\_py has been narrowed down here:
  File "/usr/lib/python3.10/json/\_\_init\_\_.py", line 293, in load
    **return loads(fp.read(),**

Line 293 is missing a right parenthesis before the ending comma (see the line immediately above this one). The problem also shows up in previous releases of Python.

Hope this helps,
Bill

**Comment by JelleZijlstra** [comment]
You have a syntax error in your JSON. The Python code in the `json` package does not have syntax errors; the parentheses are closed on a later line.

**Comment by erlend-aasland** [comment]
> Line 293 is missing a right parenthesis before the ending comma (see the line immediately above this one). The problem also shows up in previous releases of Python.

@wtrenker, you'll find the closing parenthesis on line 296. There is no bug.

**Comment by zware** [comment]
See https://github.com/python/cpython/blob/f37715396786fd4055f5891aa16774ede26392ff/Lib/json/__init__.py#L293-L296

The linked commit is the v3.10.5 tag.
