### ISSUE TITLE
bug in print function with lists and tuples with arabic characters

### ISSUE THREAD

**Issue by kubapok** [python/cpython#93811]
**Bug report**

```
a = 'a'
b = 'فوزیہ گیلانی'
c = '2'
d = '3'
x = (a,b,c,d)
print(x)
```
outputs for me in wrong order:
`('a', 'فوزیہ گیلانی', '2', '3')`

I think it has something to do with that the Arabic letters are written from right to left, but I have no idea how the given output can be seen as correct.

- CPython versions tested on: Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
- Operating system and architecture: Linux Mint 20 Ulyana , 5.4.0-113-generic

**Comment by stevendaprano** [comment]
Attached is a screenshot of how your bug report was emailed to me by Github, rendered in mutt (mail client). The items appear in the correct order to me.

(Also notice that Github seems to replace single quotes ' with backticks `. I am astonished that a website written for programmers should be so blase about mangling code snippets. But I digress.)

![Screenshot_2022-06-15_01-05-13](https://user-images.githubusercontent.com/19155079/173612387-39b42b96-46c0-47d6-9c3c-d95afc7cee93.png)

**Comment by iritkatriel** [comment]
I can reproduce on a Mac:

```
>>> a = 'a'
>>> b = 'فوزیہ گیلانی'
>>> c = '2'
>>> d = '3'
>>> x = (a,b,c,d)
>>> print(x)
('a', 'فوزیہ گیلانی', '2', '3')
```

**Comment by mdickinson** [comment]
@kubapok I strongly suspect that this has nothing to do with Python at all, and that it's your terminal that's doing this (helpfully applying the [Unicode algorithm ](https://unicode.org/reports/tr9/) for writing mixed RTL and LTR text).

**Comment by iritkatriel** [comment]
If I change it so that C is English, it becomes:

```
>>> a = 'a'
>>> b = 'فوزیہ گیلانی'
>>> c = 'c'
>>> d = '3'
>>> x = (a,b,c,d)
>>> print(x)
('a', 'فوزیہ گیلانی', 'c', '3')

```

**Comment by stevendaprano** [comment]
Using Python 3.10.0 on Fedora Linux I get the following. First, a screen shot showing that the output is in the correct order:

![Screenshot_2022-06-15_01-18-15](https://user-images.githubusercontent.com/19155079/173615241-4748cd7b-7d2a-4f43-83ce-08e197cdf02b.png)

The output looks correct. But when I copy it as text from my terminal, and paste into Github using Firefox, I get this:

```
>>> a = 'a'
>>> b = 'فوزیہ گیلانی'
>>> c = '2'
>>> d = '3'
>>> x = (a,b,c,d)
>>> print(x)
('a', 'فوزیہ گیلانی', '2', '3')
```

My intuition here is that it is a bug in the terminal. I am using xfce4-terminal.

**Comment by zware** [comment]
Agreed with @mdickinson, this doesn't look like anything of Python's doing.  See also `repr(x).encode('ascii', 'namereplace')`, which has everything in the expected order (I assume, as I don't know the names of Arabic characters :)):

```
>>> repr(x).encode('ascii', 'namereplace')
b"('a', '\\N{ARABIC LETTER FEH}\\N{ARABIC LETTER WAW}\\N{ARABIC LETTER ZAIN}\\N{ARABIC LETTER FARSI YEH}\\N{ARABIC LETTER HEH GOAL} \\N{ARABIC LETTER GAF}\\N{ARABIC LETTER FARSI YEH}\\N{ARABIC LETTER LAM}\\N{ARABIC LETTER ALEF}\\N{ARABIC LETTER NOON}\\N{ARABIC LETTER FARSI YEH}', '2', '3')"
```

This looks to me like a display edge case (which may or may not actually be a bug) that we can't do anything about.

**Comment by kubapok** [comment]
Thanks for your replies. I agree this may be not a problem with python. I've just tried the same with nodejs and got the same incorrect order result. I think it's not the problem with the terminal either because the problem occurs in jupyter notebook as well.

Sorry for posting this bug in the python bug issues.

However, I'd like to find an explanation for this behavior in some Mac and Linux systems. Do you have any idea where I should seek an answer?

**Comment by kubapok** [comment]
> Attached is a screenshot of how your bug report was emailed to me by Github, rendered in mutt (mail client). The items appear in the correct order to me.
> 
> (Also notice that Github seems to replace single quotes ' with backticks `. I am astonished that a website written for programmers should be so blase about mangling code snippets. But I digress.)
> 
> ![Screenshot_2022-06-15_01-05-13](https://user-images.githubusercontent.com/19155079/173612387-39b42b96-46c0-47d6-9c3c-d95afc7cee93.png)

For me its:
![image](https://user-images.githubusercontent.com/10453985/173618516-5f642e6d-01cf-41a1-aa5d-2bb3155f36d1.png)

**Comment by mdickinson** [comment]
> Do you have any idea where I should seek an answer?

Searches for "Terminal" and "bidirectional text" might pull up useful resources. For example: https://unix.stackexchange.com/questions/100811/are-there-terminal-emulators-that-support-bi-directional-text

In short, it's a feature, not a bug (at least inasmuch as it's intentional behaviour rather than accidental).
