### ISSUE TITLE
`_ast.Attribute` objects in a module are assigned the same `attr` values

### ISSUE THREAD

**Issue by gurukamath** [python/cpython#93828]
**Bug report**

Steps to reproduce

1. I have a simple `test.py` module which I parse using the `ast.parse` function. The test.py file looks like below.

```
from temp import A, B

A.y = 10

B.y = 5
```

2. The string form of the above code which I can directly pass into the`parse` function is

```
from temp import A, B\n\nA.y = 10\n\nB.y = 5\n\n\n
```

3. Call the `parse` function4. 
```
from ast import parse

node = parse('from temp import A, B\n\nA.y = 10\n\nB.y = 5\n\n\n', type_comments=True)
```

**Current behavior**

The two _ast.Attribute objects created for A.y and B.y have are assigned the same attr i.e. y which leads to an incorrect conclusion that they may be duplicates

**Expected behavior**

Should they have attr as A.y and B.y respectively? Or some other unique value?

**Your environment**

- CPython versions tested on: 3.8.9
- Operating system and architecture: macOS Monterey Version 12.3 (Apple M1)

**Comment by ericvsmith** [comment]
Could you clarify what "The two _ast.Attribute objects created for A.y and B.y have are assigned the same attr i.e. y which leads to an incorrect conclusion that they may be duplicates" means?
```python
from ast import parse, dump

node = parse('from temp import A, B\n\nA.y = 10\n\nB.y = 5\n\n\n')
print(dump(node))
```
produces this (after being reformatted):
```python
Module(body=[ImportFrom(module='temp',
                        names=[alias(name='A', asname=None),
                               alias(name='B', asname=None)],
                        level=0),
             Assign(targets=[Attribute(value=Name(id='A',
                                                  ctx=Load()),
                                       attr='y',
                                       ctx=Store())],
                    value=Constant(value=10, kind=None),
                    type_comment=None),
             Assign(targets=[Attribute(value=Name(id='B',
                                                  ctx=Load()),
                                       attr='y',
                                       ctx=Store())],
                    value=Constant(value=5, kind=None),
                    type_comment=None)],
       type_ignores=[])

```
which seems correct.
How would you suggest this be changed?

**Comment by JelleZijlstra** [comment]
My best guess at what the OP meant is that the same string object is returned for both `Attribute` nodes:

```
>>> node.body[1].targets[0].attr is node.body[2].targets[0].attr
True
```

But that's not a bug; we don't provide any guarantees about whether string objects are identical.

**Comment by gurukamath** [comment]
> My best guess at what the OP meant is that the same string object is returned for both `Attribute` nodes:

Yes. This is what I meant. However, I missed the fact that the `Name` object also has the id which captures the unique object to which the object belongs.

It's probably one of the downstream libraries that must be leaving this information out.

I apologise for the misunderstanding and am closing the issue. Thank you for the help.
