### ISSUE TITLE
Add the ability to turn on/off stats, dump them and clear them, when built with `--enable-pystats`

### ISSUE THREAD

**Issue by markshannon** [python/cpython#93841]
This would only apply with `--enable-pystats` and thus `#define Py_STATS`. For normal builds nothing would change.

Add `sys._stats_on()`, `sys._stats_off()`, `sys._stats_clear()` and `sys._stats_dump()` functions.
This would allow us to record and dump stats for parts of a program.

This would be useful for experimentation and having stats match timings for pyperf, as we could turn on stats when starting the timer, and turn them off when stopping the timer.

**Comment by markshannon** [comment]
https://github.com/python/cpython/pull/93843

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
