### ISSUE TITLE
`Audit events table` doc section is generated with broken links

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#93857]
*Parent issue: gh-93851*

https://docs.python.org/3/library/audit_events.html has two links to non-existent sections of `sqlite3.html`:

- `sqlite3.enable_load_extension | connection, enabled | [1]`
- `sqlite3.load_extension | connection, path | [1]`

I couldn't find where these lines come from. A source file https://github.com/python/cpython/blob/ff095e13dfdea64de5c1ad21021ae9b5ca2631f8/Doc/library/audit_events.rst is much shorter, and I don't know what to grep.

**Comment by erlend-aasland** [comment]
> https://docs.python.org/3/library/audit_events.html has two links to non-existent sections of `sqlite3.html`:
> 
> * `sqlite3.enable_load_extension | connection, enabled | [1]`
> * `sqlite3.load_extension | connection, path | [1]`

They are not non-existent, they just live under the `sqlite3.Connection` namespace. The _audit names_, however, are `sqlite3.enable_load_extension` and `sqlite3.load_extension`.

> I couldn't find where these lines come from. A source file https://github.com/python/cpython/blob/ff095e13dfdea64de5c1ad21021ae9b5ca2631f8/Doc/library/audit_events.rst is much shorter, and I don't know what to grep.

That file is partly autogenerated, as noted on line 17.

> This table is generated from the CPython documentation [...]

I suspect we need to alter the `audit-event` Sphinx extension to fix these things:

https://github.com/python/cpython/blob/ff095e13dfdea64de5c1ad21021ae9b5ca2631f8/Doc/tools/extensions/pyspecific.py#L189-L278

**Comment by erlend-aasland** [comment]
> [...] I don't know what to grep.

```console
$ grep -r "audit-event::" Doc/
```

**Comment by erlend-aasland** [comment]
> I suspect we need to alter the audit-event Sphinx extension to fix these things [...]

Or maybe we're using the `audit-event` directive wrongly in Doc/library/sqlite3.rst.

**Comment by erlend-aasland** [comment]
Yay, it was the latter. So we don't need to dig around in the Python Sphinx extensions (phew!) :)

**Comment by erlend-aasland** [comment]
FTR, the third argument to the `audit-event` directive is the target:

https://github.com/python/cpython/blob/ff095e13dfdea64de5c1ad21021ae9b5ca2631f8/Doc/tools/extensions/pyspecific.py#L236-L243

**Comment by erlend-aasland** [comment]
Fixed in:

- main: #93859 
- 3.11: #93861
- 3.10: #93862
