### ISSUE TITLE
strtobool docs innacurate

### ISSUE THREAD

**Issue by MareoRaft** [python/cpython#93863]
**Documentation**

The documentation on [strtobool](https://docs.python.org/3.10/distutils/apiref.html?highlight=strtobool#distutils.util.strtobool) says that any value outside of "y", "yes", "t", "true", "on", "1", "n", "no", "f", "false", "off", or "0" will produce a `ValueError`.

This is not true.  The value "True" does not produce a `ValueError`.

The documentation needs to say that the value is run through `.lower()` before comparison, or say that the comparison is **not** case-sensitive.

Thank you!

**Comment by merwok** [comment]
Thanks for the report, but sadly distutils is now removed from the stdlib so I will close this.

You could report it to https://github.com/pypa/distutils/issues if you wanted.
