### ISSUE TITLE
__text_signature__ in custom code

### ISSUE THREAD

**Issue by qwenger** [python/cpython#93865]
How official is `__text_signature__`?

- It is not described in the docs, only succinctly mentioned twice in the changelogs.
- The expected format of the docstring for a useful `__text_signature__` to be generated is not documented.
- In particular, the docstring format described in [PEP7](https://peps.python.org/pep-0007/#documentation-strings) for `PyDoc_STR(VAR)` does *not* seem compatible with `__text_signature__`.

So: are custom C extensions expected to provide docstrings compatible with `__text_signature__`, and if so, what is the correct format?

**Comment by encukou** [comment]
IMO, it's an internal implementation detail -- a way to get the information from a C structure to `inspect`.
It doesn't need to stay that way, but it would need to be clarified and documented. And possibly improved in the process.

There is a related question at https://discuss.python.org/t/43914 -- and discuss.python.org is a better place for questions than this bug tracker.
Please continue any discussion there, so it's seen by the proper people :)
