### ISSUE TITLE
timeit.default_timer() restarted.

### ISSUE THREAD

**Issue by SolsticeProjekt** [python/cpython#93877]
I've closed the lid of my notebook.
When I came back, it woke up from sleep.

Now, without changing anything at all, `default_timer()` returns `1077770.1358825`, which is `1970-01-13 12:22:50.135883`.

datetime.now() reports the current time.
time.time() also reports the current time.

Microsoft Windows [Version 10.0.19044.1706]
ASUS Zephyrus G15 2021, Ryzen 5900HS, 16gigs of RAM.
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

```
from timeit import default_timer
import datetime as dt

while True != False:
	print(default_timer(), dt.datetime.fromtimestamp(default_timer()))

```

**Comment by mdickinson** [comment]
@SolsticeProjekt I may have misunderstood what you're reporting. What was `default_timer()` reporting before the sleep, and what was it reporting afterwards?
