### ISSUE TITLE
Starred assignment limited number of targets before or after the starred argument.

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#93881]
**Bug report**
Generally, python can handle any number (up to 2 ** 32 - 1, actually) of targets in a list or tuple.

With a starred assignment, the numbers of expressions both before and after the * are limited, to 255 and 2**24 - 1, _resp._.  This is a consequence of the implementation of UNPACK_EX in `ceval.c`.

I assert that this should be fixed, because someday somebody will try to generate some Python code with many assignment targets and a trailing * target, and then their code will not compile!
**Example**
With 256 targets before the *, you get the following:
```
>>> exec(f'{"x," * 256}*y = range(258)')
SyntaxError: too many expressions in star-unpacking assignment
```
The outcome should be:
```
>>> exec(f'{"x," * 256}*y = range(258)')
>>> x
255
>>> y
[256, 257]
```
**Proposed fix**
I would propose a new bytecode, ~~UNPACK_EX_TOP~~ UNPACK_STAR_POS (or whatever), where the oparg is the count ~~_after_~~ _before_ the *~~, and TOS is the count _before_ the *~~.  This will **always** be followed by UNPACK_SEQUENCE where oparg is the total number of targets, including the *.  The compiler would emit:

~~`LOAD_CONST before-count`
`EXTENDED_ARG ... if necessary for an after-count >= 256`
`UNPACK_EX_TOP after-count`~~
```
UNPACK_STAR_POS (before-count)
UNPACK_SEQUENCE (before-count + 1 + after-count)
(with EXTENDED_ARG's as needed)
```
The interpreter will get the before-count from UNPACK_STAR_POS and then process the UNPACK_SEQUENCE as though it were an UNPACK_EX with the same before-count and after-count.

I also suggest that the normal cases, with up to 255 targets before the *, be handled as they are now, just to not break bytecode analysis programs that don't yet know about the new bytecode.  The generated code is the same length as what I propose above, and doesn't involve adding a constant:
```
EXTENDED_ARG after_count.
UNPACK_EX before-count
```
Please see my subsequent comment for tips on how to implement this.

**Comment by stevendaprano** [comment]
> someday somebody will try to generate some Python code with many assignment targets and a trailing * target, and then their code will not compile!

Isn't that a good thing?

Do we need to support 256+ assignment targets? What's the use-case for writing something like this? `exec(f'{"x," * 256}*y = range(258)')`

Is your concern only the inconsistency between the starred case and unstarred case, or is there a concrete need for this? If nobody has hit this limit in real life, that suggests that adding a new opcode to support a feature that nobody uses is just bloat and dead code. 

"Almost unlimited" limits have [real costs](https://peps.python.org/pep-0611/).

**Comment by mrolle45** [comment]
> If nobody has hit this limit in real life, that suggests that adding a new opcode to support a feature that nobody uses is just bloat and dead code.

My concern is both about consistency and about extending the capability of the compiler in what might already, or in the future, generated code which at present fails to compile.
I discount the possibility that the added code to the compiler and interpreter is dead code, because it would not be vary much added code.

Detailed arguments for my point:
1. Of course nobody uses this feature in real life because they can't compile.  If someone has run into the SyntaxError with generated code, then they will have had to implement a workaround.  They might not have bothered to complain about having to do this.  Therefore, it's possible in the real world that the originally generated code would now compile.
2. You could make the same argument about non-starred assignments.  Maybe nobody has ever had 256+ assignment targets in generated code, so the extra work in producing EXTENDED_ARG bytecodes would also be bloat and dead code.
3. Thus, if you support 256+ targets in one case, then you should also support it in the other case.
4. I think that implementation should be pretty quick and easy.  Adding a case to `ceval.c` would just be a few lines.  I don't know about the compiler, but where it emits the UNPACK_EX, it can emit the new bytecode sequence where it now raises a SyntaxError.  Again, just a few lines.

**Comment by iritkatriel** [comment]
There are all kinds of arbitrary limits, like the limit on static nesting level (try to nest 50 try-except blocks in each other).

The limits simplify the implementation, they don't need to be consistent with each other. They just need to not get in the way of what people need to do (so no, we don't need to support 256 in case A just because it is supported in case B).

The number of opcodes is small. The bar for adding a new opcode is high.

I don't think this issue is describing an actual problem.
