### ISSUE TITLE
IsolatedAsyncioTestCase and asyncio.run no-longer call asyncio.set_event_loop

### ISSUE THREAD

**Issue by graingert** [python/cpython#93896]
in https://github.com/python/cpython/pull/31799/files#diff-1f2ae0f6c6010caf9d5f1c80cd6033a796ffe2b60554f5df84f554f4a08e622b the calls to `asyncio.set_event_loop()` were removed which breaks aiohttp https://github.com/aio-libs/aiohttp/issues/6757 and `asyncio.SafeChildWatcher`

this looks like an intentional breaking change - and if it is should be documented

**Comment by graingert** [comment]
I know there were some efforts to deprecate `get/set_event_loop_policy` and child watchers https://github.com/python/cpython/issues/82772 so I think those Deprecations should be applied before asyncio.run/IsolatedAsyncioTestCase stops calling asyncio.set_event_loop()

**Comment by graingert** [comment]
alternatively is there still time to deprecate the child watchers system and the policy system in favor of 
`asyncio.Runner(loop_factory=asyncio.ProactorEventLoop/asyncio.SelectorEventLoop/uvloop.uvloop.new_event_loop)` before the 3.11 release?

**Comment by encukou** [comment]
Marking as potential release blocker.

**Comment by graingert** [comment]
> Marking as potential release blocker.

As this is a release blocker can you add @pablogsal as a reviewer for me?

> Please, add me as a reviewer to any PR that needs to be merged to address these issues.

https://mail.python.org/archives/list/python-dev@python.org/thread/ORCYBRP432J36LXP32IDX6KLRE7Z646V/

**Comment by encukou** [comment]
I can. Sadly, asyncio experts seem quiet. Myself, I am out of my depth here.

**Comment by kumaraditya303** [comment]
The PR adds a new argument to set the current event loop policy. I propose to not add a new argument and always set the loop and when in future policy setup will be deprecated, it can be reconsidered. Also I don't think we can add or remove a new argument after beta release of 3.11  but I'll defer to @pablogsal.

**Comment by pablogsal** [comment]
> The PR adds a new argument to set the current event loop policy.

New APIs cannot be added or modified after beta freeze. Also, existing behaviour cannot be changed *unless* the behaviour is fundamentally wrong.

**Comment by graingert** [comment]
I'm assuming that the calls to set_event_loop were removed as an intentional feature of asyncio.Runner, and ideally I'd like to keep this feature for my usage of it. However the removal from asyncio.run and IsolatedAsyncioTestCase is a breaking change

**Comment by graingert** [comment]
> Do you have a use-case where you don't want `set_event_loop()` to be called? 

Yes, I want to be able to run multiple event loops of different flavors without interacting with global state such as the policy system. Calling set_event_loop for example can join threads in the child watcher

> The Runner class is meant to abstract away working with a loop, but if we force the user to call set_event_loop() themselves then we're back at the beginning of working directly with the loop.

I'm not suggesting we force the user to do this, I'm suggesting that asyncio.run call `set_event_loop` for backwards compatibility purposes and asyncio.Runner is the new recommended interface, eventually phasing the policy system out entirely

**Comment by gvanrossum** [comment]
I am also out of my depth here. What would be the smallest change that fixes the release blocker in 3.11, without violating the feature freeze? We should have a separate discussion about the future of the policy system.

**Comment by kumaraditya303** [comment]
I'll create a minimal PR to unblock the release of 3.11 soon complying with feature freeze as I commented above. @gvanrossum If you are okay with it, you may assign this to me.

**Comment by gvanrossum** [comment]
Go ahead with that PR, Kumar.

**Comment by graingert** [comment]
> We should have a separate discussion about the future of the policy system.

see https://github.com/python/cpython/issues/94597

**Comment by kumaraditya303** [comment]
This is fixed in 3.12 (main) and 3.11 by  https://github.com/python/cpython/pull/94593 https://github.com/python/cpython/pull/94608 respectively. 

Thanks everyone!

**Comment by gvanrossum** [comment]
@ixenion Please be civil. This is not the place to get help, but you can find help for Python issues on discuss.python.org.
