### ISSUE TITLE
On Windows, test_distutils and test_peg_generator leak a temporary file: Microsoft

### ISSUE THREAD

**Issue by vstinner** [python/cpython#93919]
Running test_distutils on Windows leaks a temporary file: Microsoft.

```
0:08:46 load avg: 7.14 [231/436/3] test_distutils failed (env changed) (49.1 sec) -- running: test_socket (59.3 sec), test_urllib2_localnet (33.2 sec)
(...)
Warning -- test_distutils leaked temporary files (1): Microsoft
```

The test should be run with -jN, like: ``python -m test -j1 test_distutils -v --fail-env-changed``.

**Comment by vstinner** [comment]
Same issue with test_peg_generator:

```
0:15:37 load avg: 5.75 [424/436/5] test_peg_generator failed (env changed) (5 min 51 sec) -- running: test_largefile (38.2 sec), test_mmap (1 min 42 sec)
(...)
Warning -- test_peg_generator leaked temporary files (1): Microsoft
```

**Comment by vstinner** [comment]
> I get different results:

bisect_cmd picks any test which reproduces the issue. So at least 4 tests leak a temporary file :-)

**Comment by vstinner** [comment]
I marked my issue #98168 as a duplicate of this issue.

**Comment by vstinner** [comment]
Sadly, I don't have the bandwidth to work on this issue, I just close it.

**Comment by zware** [comment]
I've had a chance to look into this, and it looks like what is actually left is an empty directory tree: `Microsoft\VSApplicationInsights\vstelAIF-312cbd79-9dbb-4c48-a7da-3cc1a931cb70\` (that last part may not be the same every time).

I've searched around and found no way to disable this, but it may or may not be related to the worker being deployed on Azure.  @zooba or @eryksun, if you have any suggestions for making this go away I'm open to them, but I wonder if it wouldn't be better to just ignore a directory called `Microsoft` in the leaked temporary files check.

**Comment by zware** [comment]
Hmm.  It turns out that an update to VS (and an attempt to trim down the installed components) seems like it may have resolved this; the [latest build](https://buildbot.python.org/all/#/builders/914/builds/2399) (which was a rebuild of the previous failure) passed.
