### ISSUE TITLE
Build shared extensions without distutils

### ISSUE THREAD

**Issue by tiran** [python/cpython#93939]
**Feature or enhancement**

distutils is deprecated and is scheduled to be removed from Python 3.12. PyPA setuptools replaces distutils and provides shims for distutils package.

GH-90005 tracks effort to use ``configure.ac``, ``Makefile``, and ``makesetup`` to build almost all shared extensions without distutils. Only a handful of modules have not been ported yet

- [x] _curses
- [x] _curses_panel
- [X] _ctypes, see gh-32229
- [x] _dbm
- [x] readline

### Linked PRs
* gh-148182

**Comment by erlend-aasland** [comment]
The last modules are now ported! 🚀 🎉

**Comment by tiran** [comment]
Thank you for your hard work, @erlend-aasland 

The endeavor continues in gh-93939

**Comment by erlend-aasland** [comment]
> The link points back to this PR.

1. this is an issue, not a PR ;)
2. I believe the intention was to close #90005, and mark this issue as a follow up

**Comment by erlend-aasland** [comment]
AFAICS, there is no more work to be done here.
