### ISSUE TITLE
[C API] Move PyFrame_* API to <Python.h>

### ISSUE THREAD

**Issue by vstinner** [python/cpython#93937]
Currently, getter functions of a Python frame object (PyFrameObject) are only accessible if the ``frameobject.h`` header is included explicitly. It's not documented in the frame doc: https://docs.python.org/dev/c-api/frame.html

In Python 3.11, the PyFrameObject structure was moved to the internal C API. Third party C extensions now must only use getter functions, as explained in What's New in Python 3.11: https://docs.python.org/dev/whatsnew/3.11.html#id6

Problem: functions like PyFrame_GetBack() requires to include ``frameobject.h``. I propose to move these getter functions to ``Python.h`` (to ``pyframe.h`` in practice) to make these functions less special.

### Linked PRs
* gh-99695
* gh-99697

**Comment by vstinner** [comment]
Done:

* main: commit 27b989403356ccdd47545a93aeab8434e9c69f21
* 3.11: commit 96254a9acd0d9dbb49b7d54fd529223b2253245b

**Comment by kumaraditya303** [comment]
This is fixed, closing.

**Comment by encukou** [comment]
I'll reuse this issue to add missing docs.
