### ISSUE TITLE
Officially deprecate and remove abcs in importlib.abc moved to importlib.resources.

### ISSUE THREAD

**Issue by jaraco** [python/cpython#93963]
In #90276, I grouped the functionality related to `importlib.resources` into its own package (creating clearer separation of responsibility from `importlib.*`). That included moving some abstract base classes from `importlib.abc` to `importlib.resources.abc`. We need to officially deprecate the presence in `importlib.abc` and then remove them in a future release.

- [x] deprecation: https://github.com/python/cpython/pull/93965
- [x] documentation: #94546 
- [x] cleanup: #95217, #96598
- [ ] ~removal: https://github.com/python/cpython/pull/94528~
- [x] removal: https://github.com/python/cpython/pull/119720

_Originally posted by @jaraco in https://github.com/python/cpython/issues/93610#issuecomment-1157848163_

### Linked PRs
* gh-119720

**Comment by jaraco** [comment]
@encukou Here's the deprecation that officially announces the intention added in #90276. I know you were working on the doc updates. Let me know if I can help with that, especially with regard to this direction.

**Comment by jaraco** [comment]
Today I observed that one of the tests is still accessing `ResourceReader` from `importlib.abc`.

**Comment by tirkarthi** [comment]
It's `ResourceReader` being passed to `make_abc_subclasses` that tries to retrieve `abc.ResourceReader` triggering a `DeprecationWarning`. Below is an approach where default refers to `abc` module and `ResourceReaderDefaultsTests` overrides it with `resources`.

```diff
diff --git a/Lib/test/test_importlib/test_abc.py b/Lib/test/test_importlib/test_abc.py
index d59b663a43..66c8bf09cf 100644
--- a/Lib/test/test_importlib/test_abc.py
+++ b/Lib/test/test_importlib/test_abc.py
@@ -13,6 +13,7 @@
 init = test_util.import_importlib('importlib')
 abc = test_util.import_importlib('importlib.abc')
 machinery = test_util.import_importlib('importlib.machinery')
+resources = test_util.import_importlib('importlib.resources')
 util = test_util.import_importlib('importlib.util')
 
 
@@ -125,7 +126,7 @@ class SourceLoader(InheritanceTests):
 
 ##### Default return values ####################################################
 
-def make_abc_subclasses(base_class, name=None, inst=False, **kwargs):
+def make_abc_subclasses(base_class, name=None, inst=False, abc=abc, **kwargs):
     if name is None:
         name = base_class.__name__
     base = {kind: getattr(splitabc, name)
@@ -324,7 +325,7 @@ def contents(self, *args, **kwargs):
 
 class ResourceReaderDefaultsTests(ABCTestHarness):
 
-    SPLIT = make_abc_subclasses(ResourceReader)
+    SPLIT = make_abc_subclasses(ResourceReader, abc=resources)
 
     def test_open_resource(self):
         with self.assertRaises(FileNotFoundError):
```

**Comment by jaraco** [comment]
Oh, I'd missed test_abc. I think I'd like to just remove that test... or if it needs to exist, it should exist in `importlib_resources` also.

**Comment by jaraco** [comment]
I see now in ccf94a6289c722f56000ffed5dd416371127c759, Irit suppressed the DeprecationWarnings.

**Comment by serhiy-storchaka** [comment]
I am confused.

The documentation for `importlib.resources.abc.Traversable` says: "Deprecated since version 3.12, will be removed in version 3.14: Use `importlib.resources.abc.Traversable` instead."

The documentation for `importlib.resources.abc.TraversableResources` says: "Deprecated since version 3.12, will be removed in version 3.14: Use `importlib.resources.abc.TraversableResources` instead."

Why does it recommend to use the same deprecated class?

**Comment by serhiy-storchaka** [comment]
Opened new issue #107352 for this.

**Comment by hugovk** [comment]
Removal PR: https://github.com/python/cpython/pull/119720
