### ISSUE TITLE
refcounting bug in add_subclass in typeobject.c

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#93990]
Currently is does not decref key and ref when the created dict is null.
See https://github.com/python/cpython/pull/93989

**Comment by Fidget-Spinner** [comment]
Seems like this bug also exists in 3.11 and 3.10. Could you work on the 3.10 backport please? I think it needs to be done manually.

**Comment by kumaraditya303** [comment]
Okay, I'll create the backports.
