### ISSUE TITLE
Unreachable code warning in specialize.c

### ISSUE THREAD

**Issue by tiran** [python/cpython#94021]
**Bug report**

Some versions of clang complain about unreachable code in specialize.c

https://github.com/python/cpython/blob/774ef28814d0d9d57ec813cb31b0a7af6c476127/Python/specialize.c#L1911-L1920

```
Python/specialize.c:1915:13: warning: code will never be executed [-Wunreachable-code]
```

The problem is trivial to fix.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/94022
