### ISSUE TITLE
 fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by sw-dev-code** [python/cpython#94027]
I'm using the Ubuntu 20.04.4 OS with installed Python 3.7.3. When I try to use markupsafe module the following error occurs.

I try to install the python3-dev but that didn't help. I can find a Python.h file at location: /usr/local/include/python3.7/Python.h

tools.utils.ToolException: ./venv/lib/python3.7/site-packages/markupsafe/_speedups.c:1:10: fatal error: Python.h: No such file or directory
1 | #include <Python.h>

**Comment by sw-dev-code** [comment]
I've also installed the libraries for 3.7 with `sudo apt install libpython3.7-dev` but still no luck.

**Comment by zware** [comment]
This appears to be a bug in the packaging of Python rather than in Python itself, so you'll need to take this up with the vendor of your package.

**Comment by mprinc** [comment]
Please check these threads:

+ https://github.com/explosion/spaCy/issues/2160
+ https://stackoverflow.com/a/21530768/257561
