### ISSUE TITLE
Unhelpful `SyntaxError` with unclosed call before colon

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#94034]
Ran into this today. If you forget to close parentheses as part of a call in the header of a `for`, `with`, or `class` statement (maybe others too?), the `SyntaxError` seems to indicate that you forgot a colon:

```py
>>> for foo in bar(baz:
  File "<stdin>", line 1
    for foo in bar(baz:
                  ^
SyntaxError: expected ':'
```

It's not *wrong*, but could probably be improved. I personally find the pre-3.10 behavior more helpful:

```py
>>> bar(baz:
  File "<stdin>", line 1
    for foo in bar(baz:
                      ^
SyntaxError: invalid syntax
```

Even better, though, would be a "smarter" error message like the existing ones we have for unclosed parentheses:

```py
>>> bar(baz:
  File "<stdin>", line 1
    for foo in bar(baz:
                  ^
SyntaxError: '(' was never closed
```

@pablogsal

**Comment by pablogsal** [comment]
I think this will be fixed by https://github.com/python/cpython/pull/92894#issuecomment-1158160624. @brandtbucher can you check (I'm away from the keyboard right now)? Otherwise I will do it later today :)

**Comment by brandtbucher** [comment]
Looks like it might be. At any rate, I'll close this as a duplicate of #92858.
