### ISSUE TITLE
race condition in asyncio.BaseEventLoop.run_forever

### ISSUE THREAD

**Issue by graingert** [python/cpython#94031]
in the code here:

https://github.com/python/cpython/blob/cfb986a1a239f1a00af745a53235b8473b1bd54a/Lib/asyncio/base_events.py#L594-L596

two threads can win self._check_running() at the same time and if there's a thread switch in any of https://github.com/python/cpython/blob/cfb986a1a239f1a00af745a53235b8473b1bd54a/Lib/asyncio/base_events.py#L1912-L1925 both threads will call self._thread_id = ...

I think the fix is to copy the atomic compare and swap implementation from mixins._LoopBoundMixin:

```python
        self._check_running()
        thread_id = threading.get_ident()

        with _global_lock:
            if self._thread_id is None:
                self._thread_id = thread_id

        if thread_id != self._thread_id:
            raise RuntimeError("This event loop is running in a different thread')
        self._set_coroutine_origin_tracking(self._debug)
```

**Comment by kumaraditya303** [comment]
I don't think `run_forever` can be considered thread safe, most of the `asyncio` functions are not thread safe except `loop.call_soon_threadsafe` [^1]. Do you have any use case for this ?

[^1]: https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

**Comment by graingert** [comment]
> I don't think `run_forever` can be considered thread safe, most of the `asyncio` functions are not thread safe except `loop.call_soon_threadsafe` [1](#user-content-fn-1-b62f3a84d513e2d0e9b8c25cb2c3920e). Do you have any use case for this ?
> ## Footnotes
> 
>     1. [docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading](https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading) [leftwards_arrow_with_hook](#user-content-fnref-1-b62f3a84d513e2d0e9b8c25cb2c3920e)

run_forever has to be thread-safe because it the interface is designed to allow different threads to run it

**Comment by arhadthedev** [comment]
@kumaraditya303 would you mind to re-review and possibly merge this PR if no objection is present?

**Comment by kumaraditya303** [comment]
I still don't understand why this change is necessary and the OP's comment https://github.com/python/cpython/issues/94031#issuecomment-1200274846 is too vague for me so my question still stand https://github.com/python/cpython/issues/94031#issuecomment-1177330118.

**Comment by gvanrossum** [comment]
Also this:
> run_forever has to be thread-safe because the interface is designed to allow different threads to run it
makes no sense -- the interface is designed to allow different threads to run it **with different event loops**.

I am closing this and will reject the PR.
