### ISSUE TITLE
Readme.rst Release Schedule

### ISSUE THREAD

**Issue by MilanJuhas** [python/cpython#94038]
**Documentation**

(A clear and concise description of the issue.)

Under Release Schedule in Readme.rst is link for PEP 664 which is release schedule for Python 3.11. Actual Release Schedule for Python 3.12 is PEP 693. https://peps.python.org/pep-0693/

**Comment by hugovk** [comment]
Good find, would you like to create a PR to fix it?

**Comment by MilanJuhas** [comment]
Yeah, I would like that, thanks
