### ISSUE TITLE
Asyncio raise ConnectionResetError without the message set.

### ISSUE THREAD

**Issue by sileht** [python/cpython#94061]
**Bug report**

Asyncio may raise ConnectionResetError without instanciante it.

```
ConnectionResetError: null
  File "redis/asyncio/connection.py", line 700, in connect
    await self._connect()
  File "redis/asyncio/connection.py", line 735, in _connect
    reader, writer = await asyncio.open_connection(
  File "asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
```

Libraries (like redis-py) expected all OSError to be instantiated with `.args` set.

**Your environment**

python 3.10.4
Ubuntu 20.04

### Linked PRs
* gh-94062

**Comment by sileht** [comment]
Related to https://github.com/redis/redis-py/issues/2237

**Comment by kumaraditya303** [comment]
Can you provide a minimal reproducer for this? The issue you linked is closed now.

**Comment by sileht** [comment]
The redispy library has implemented a workaround, that why the downstream issue is closed.

Not sure this need a reproducer, this is not a logic issue, but an exception that missed to be instantiated.

To raise this exception, you need to break a tcp connection at a certain timing.

**Comment by kumaraditya303** [comment]
PR welcome!

**Comment by sileht** [comment]
The PR is waiting since 2 month for review here: https://github.com/python/cpython/pull/94062 and the CI failure is unrelated to the change.

**Comment by sileht** [comment]
I found this in the documentation: https://docs.python.org/3/library/exceptions.html#BaseException that could have misled the redis implementation.

```
args:
The tuple of arguments given to the exception constructor. Some built-in exceptions (like [OSError]
(https://docs.python.org/3/library/exceptions.html#OSError)) expect a certain number of arguments
and assign a special meaning to the elements of this tuple, while others are usually called only with
a single string giving an error message.
```

But I took a step back since I opened this and fixed the redis issue. And I agree nothing in Python enforces to set `args`. They were plenty of other places when OSError or alike didn't set `args`. Libs should handle that case correctly.

**Comment by gvanrossum** [comment]
Yeah, and the [docs](https://docs.python.org/3/library/exceptions.html#OSError) for OSError specifically call out the "no args" case in the signature.

I'm going to close these as wont-fix.
