### ISSUE TITLE
Duplicate of #70509

### ISSUE THREAD

**Issue by MaddenJohn** [python/cpython#94073]
This issue is happening again

_Originally posted by @MaddenJohn in https://github.com/python/cpython/issues/70509#issuecomment-1162003585_

**Comment by MaddenJohn** [comment]
##
##  It appears that strptime is ignoring the AM/PM field
##
from datetime import datetime
d1 = datetime.strptime("1:00 PM", "%H:%M %p")
d2 = datetime.strptime("1:00 AM", "%H:%M %p")
d1.hour, d2.hour
(1, 1) # d1 should be 13
d1 == d2
True # and these should not be equal

**Comment by zware** [comment]
As noted in #70509, this is a documented peculiarity.  Use `%I` instead of `%H`.
