### ISSUE TITLE
Unicode documentation references non-existent C function

### ISSUE THREAD

**Issue by pamelafox** [python/cpython#94087]
**Documentation**

The [C Unicode reference for PyUnicode_AsWideCharString](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsWideCharString) says "Returns a buffer allocated by PyMem_Alloc()". However, a function named PyMem_Alloc does not currently exist. The function used instead is PyMem_NEW which is a macro for PyMem_New.

I'll send a PR with a fix.

**Comment by kamilturek** [comment]
Probably can be closed via #94088.

**Comment by pamelafox** [comment]
Yep, closing, thanks!
