### ISSUE TITLE
importlib.metadata.packages_distributions does not see all packages installed on sys.path

### ISSUE THREAD

**Issue by pfmoore** [python/cpython#94113]
**Bug report**

If I install `rich` in a temporary directory and then add that directory to `sys.path`, `importlib.metadata.packages_distributions` cannot see rich (even though it can see dependencies of rich like `pygments`).

Reproducer:

```python
import sys
import subprocess
import shutil
from pathlib import Path

tst = Path("test")
tst.mkdir()

subprocess.run([sys.executable, "-m", "pip", "install", "-t", str(tst), "rich"])

reproducer = Path("reproducer.py")
reproducer.write_text(f"""\
import sys
import importlib.metadata
sys.path.append({repr(str(tst))})
import rich # to confirm rich is importable
dists = importlib.metadata.packages_distributions()
print(dists)
print("Rich version is accessible:", importlib.metadata.version("rich"))
if not "rich" in dists:
    print("Rich is not visible to importlib.metadata.package_distributions")
# Oddly, dependencies of rich (in the same sys.path entry) *are* visible
if "pygments" in dists:
    print("Pygments *is* visible to importlib.metadata.package_distributions")
"""
)
subprocess.run([sys.executable, str(reproducer)])

# tidy up
reproducer.unlink()
shutil.rmtree(tst)
```

**Your environment**

- CPython versions tested on: 3.10
- Operating system and architecture: Windows 11, 64-bit.
- Tested in a clean virtual environment created using `py -m venv .venv`

**Comment by jaraco** [comment]
This issue is easy to visualize using pip-run:

```
$ pip-run -q rich -- -c "import importlib.metadata as md, pprint; pprint.pprint(md.packages_distributions())"
{'argcomplete': ['argcomplete'],
 'autocommand': ['autocommand'],
 'click': ['click'],
 'commonmark': ['commonmark'],
 'importlib_metadata': ['importlib-metadata'],
 'packaging': ['packaging'],
 'path': ['path'],
 'pip': ['pip'],
 'pip-run': ['pip-run'],
 'pip_run': ['pip-run'],
 'pipx': ['pipx'],
 'pygments': ['Pygments'],
 'pyparsing': ['pyparsing'],
 'wheel': ['wheel']}
```

Next is to figure out why rich isn't present.

**Comment by jaraco** [comment]
One aspect of the problem appears to be that `rich` doesn't supply metadata about its top-level packages:

```
$ pip-run -q rich -- -c "import importlib.metadata as md, pprint; print(md.distribution('rich').read_text('top_level.txt'))"
None
```

**Comment by jaraco** [comment]
It looks like this issue may have been fixed already in `importlib_metadata`:

```
$ pip-run -q rich importlib_metadata -- -c "import importlib_metadata as md, pprint; print(md._top_level_inferred(md.distribution('rich')))"
{'rich'}
```

**Comment by jaraco** [comment]
The behavior was added in [importlib_metadata 4.7](https://importlib-metadata.readthedocs.io/en/latest/history.html#v4-7-0) and the problem no longer exists in Python 3.11:

```
$ py -3.11 -m pip-run -q rich -- -c "import importlib.metadata as md, pprint; pprint.pprint(md.packages_distributions())
"
{'_distutils_hack': ['setuptools'],
 'autocommand': ['autocommand'],
 'commonmark': ['commonmark'],
 'importlib_metadata': ['importlib-metadata'],
 'packaging': ['packaging'],
 'path': ['path'],
 'pip': ['pip'],
 'pip-run': ['pip-run'],
 'pip_run': ['pip-run'],
 'pkg_resources': ['setuptools'],
 'pygments': ['Pygments'],
 'pyparsing': ['pyparsing'],
 'rich': ['rich'],
 'setuptools': ['setuptools']}
```

**Comment by jaraco** [comment]
So what it boils down to is the version of importlib.metadata included in Python 3.10 did not have the feature required to infer the relationship between distribution and package. The fix is to use importlib_metadata>=4.7 on Python 3.10 and earlier.

**Comment by jaraco** [comment]
Although reported as a bug, in light of the finding, I believe it's a feature request that's already implemented, but unsuitable for backporting. Let me know if you feel differently.

**Comment by jaraco** [comment]
> I'm curious as to why `importlib.metadata` is relying on the (not standardised) `top-level.txt` file. While I'm happy the issue has been fixed, would it be better handled by actually standardising the way that the information required here is exposed?

Yes, it probably would be better to have a better standard for this need. When this function was drafted, it wasn't at all obvious if it would be useful. As it turns out, there are at least some users interested in it and finding these defects, so that may indicate that a more robust metadata spec may be needed.

I don't know the history behind `top-level.txt` - why it was created or what use-case it was intended to serve (perhaps this case was that use-case). 

Maybe the RECORD from dist-info and inferred top-level is sufficient (I'm unsure, especially about namespace packages). I note that RECORD doesn't exist for develop-installed packages.

Probably the next step here is for someone to analyze the situation and put together a design (PEP?).
