### ISSUE TITLE
remove reference to obsolete mirrors in python tutorial

### ISSUE THREAD

**Issue by partev** [python/cpython#94114]
**Documentation**

in python tutorial https://docs.python.org/3/tutorial/whatnow.html there is a reference to obsolete mirrors:
"This web site is mirrored in various places around the world, such as Europe, Japan, and Australia; a mirror may be faster than the main site, depending on your geographical location."

There are no more visible mirrors for python.org and this sentence probably needs to be removed.

**Comment by zware** [comment]
I agree.  Would you like to submit a PR to make this change?

**Comment by zware** [comment]
Ah, thanks.  GitHub failed to link things up, our bot was asleep on the job, and I'm not listening to the full new-PR stream.  Will take a look.

**Comment by zware** [comment]
Thanks for the report and PR!
