### ISSUE TITLE
Error in `python': double free or corruption (out): 0x00007fb048000d00

### ISSUE THREAD

**Issue by Aarif1430** [python/cpython#94134]
**Crash report**
One of my server jobs was processing a data file and the program got crashed in middle.

**Error messages**
*Error in `python': double free or corruption (out): 0x00007fb10048000d00*

**Your environment**
- CPython versions tested on: rhel-py39-64bit-gcc1 (Python3.9.5)
- Operating system and architecture: redhat enterprise version 6

**Comment by sweeneyde** [comment]
Do you have a stackdump or some kind of reproducer? Without anything to go off of, there's not much we can do.

**Comment by sweeneyde** [comment]
Can you describe anything about the sort of program? Are you using any extension modules? Threads? Multiprocessing? Asyncio? Numpy? Pandas? Is it reliably reproducable, or was it a one-time thing? If it's repeatable, can you try to pare it down to a short program? Without the ability to reproduce it, I don't see anything that can be done. Does it still happen if you update to python 3.10?

Do you have evidence that that other issue is related? Double frees are an unspecific and common bug in C programs.
