### ISSUE TITLE
how to solve this:

### ISSUE THREAD

**Issue by NSH531** [python/cpython#94167]
Traceback (most recent call last):
  File "u:\oracle\RTR.py", line 10, in <module>
    class sre_constants():
  File "u:\oracle\RTR.py", line 77, in sre_constants
    MAXREPEAT = _NamedIntConstant(32,name=str(32))
TypeError: 'name' is an invalid keyword argument for int()

    class _NamedIntConstant(int):
        def __init__(cls, value):
            self = super(_NamedIntConstant, cls).__init__(cls, value)
            self.name = name
            return self

        def __repr__(self):
            return self.name

whats can Ito change?????

**Comment by stevendaprano** [comment]
This is a bug tracker for reporting bugs in Python, not a help desk to ask for help.

You can ask for help in many places: the Python Discuss site, the mailing list, on Reddit, and more.

**Comment by stevendaprano** [comment]
Try [Discuss](https://discuss.python.org/c/users/7) or the [Python Forum](https://python-forum.io/forum-8.html) or [Reddit](https://www.reddit.com/r/learnpython/) or the [mailing list](http://mail.python.org/mailman/listinfo/python-list).
