### ISSUE TITLE
Fedora Rawhide Clang buildbot fails to build: "error: cannot apply asm label to function after its first use" in <stdio.h>

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94178]
Building Python on PPC64LE Fedora Rawhide Clang Installed 3.x fails with the following error:
https://buildbot.python.org/all/#/builders/312/builds/2208

```
In file included from Parser/string_parser.c:3:
In file included from ./Include/Python.h:24:
In file included from /usr/include/stdio.h:899:
/usr/include/bits/stdio-ldbl.h:26:20: error: cannot apply asm label to function after its first use
__LDBL_REDIR_DECL (vfprintf)
~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/sys/cdefs.h:569:26: note: expanded from macro '__LDBL_REDIR_DECL'
  extern __typeof (name) name __asm (__ASMNAME ("__" #name "ieee128"));
                         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems to be a Fedora Rawhide regression, not a Python regression.

cc @stratakis @hroncok

**Comment by hroncok** [comment]
cc @tstellar

**Comment by hroncok** [comment]
and cc @sharkcz

**Comment by vstinner** [comment]
The 4 other Fedora Rawhide GCC 3.x seems fine.

The 3 other Fedora Rawhide Clang 3.x seems fine as well.

For now, it seems like only 2 buildbot workers are affected:

* PPC64LE Fedora Rawhide Clang 3.x: https://buildbot.python.org/all/#/builders/33/builds/2287 -- started to fail at "June 23, 2020 1:41 PM" (5 hours ago)
* PPC64LE Fedora Rawhide Clang Installed 3.x: https://buildbot.python.org/all/#/builders/312/builds/2208 -- started to fail at "June 23, 2020 1:42 PM" (5 hours ago)

**Comment by sharkcz** [comment]
I believe this is a known issue between latest glibc and clang after we default to the ieee128 long double type.

**Comment by vstinner** [comment]
cc @serge-sans-paille

**Comment by vstinner** [comment]
Sorry, the Python bug tracker is the wrong place to discuss glibc regression. Please discuss the issue in this Fedora glibc issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2100546

**Comment by vstinner** [comment]
Previous successful build: https://buildbot.python.org/all/#/builders/33/builds/2286

test.pythoninfo:

```
CC.version: clang version 14.0.0 (Fedora 14.0.0-1.fc37)
platform.libc_ver: glibc 2.35.9000
platform.platform: Linux-5.18.0-0.rc6.47.fc37.ppc64le-ppc64le-with-glibc2.35.9000
```

**Comment by kumaraditya303** [comment]
Closing as the buildbot is green now.

**Comment by vstinner** [comment]
Right, glibc got fix for clang in Fedora Rawhide ;-) https://bugzilla.redhat.com/show_bug.cgi?id=2100546

Thanks for closing my old issue @kumaraditya303!
