### ISSUE TITLE
Remove deprecated keyfile, certfile and check_hostname parameters, in favor of context

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94172]
In Python 3.6, the **keyfile**, **certfile** and **check_hostname** parameters were deprecated in ftplib, http.client, imaplib, poplib, and smtplib modules. IMO it's now time to remove them in favor of the **context** parameters. Most Python projects now require Python 3.6 and newer (if not Python 3.7 or Python 3.8). And it's easy to support older Python versions with some if/else code.

I wrote **PR #94173** to remove these parameters.

* PR: gh-94173

* PR: gh-100431

* PR: gh-105392

* PR: gh-105402

* PR: gh-143515

**Comment by vstinner** [comment]
See the old issue #72209 which introduced the deprecation for the rationale of removing these parameters.

**Comment by vstinner** [comment]
I made two changes to prepare the main one:

* commit f0b234e6ed83e810bd9844e744f5e22aa538a356
* commit 37118fa2e3af133b0cf4935b008c7be7f5d07f68

**Comment by romaricnzoyem** [comment]
[spam]

**Comment by vstinner** [comment]
This issue is part of the larger issue https://github.com/python/cpython/issues/94199 "ssl and hashlib: Remove functions deprecated in Python 3.10".

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/ef0e72b31d22f780d3a165d7d0471806061fe380
