### ISSUE TITLE
PidfdChildWatcher runs callbacks on the main thread eventloop and not the currently running loop

### ISSUE THREAD

**Issue by graingert** [python/cpython#94182]
as of https://github.com/python/cpython/issues/93896 and https://github.com/python/cpython/pull/94593 asyncio.Runner(loop_factory=asyncio.new_event_loop) no longer calls `asyncio.set_event_loop()` and so the PidfdChildWatcher is never activated

this is unfortunate because it could run `asyncio.get_running_loop().add_reader` instead

**Comment by kumaraditya303** [comment]
Wasn't this fixed by https://github.com/python/cpython/pull/94593?

**Comment by graingert** [comment]
> Wasn't this fixed by #94593?

No

**Comment by graingert** [comment]
The purpose of os.open_pidfd is to allow a single event loop running in any thread to monitor processes without needing to interact with another event loop or thread. The pidfdchildwatcher is currently unnecessarily using another loop in another thread

**Comment by gvanrossum** [comment]
Thanks for the fix!

I don't think we should backport this (not even to 3.11.1).

**Comment by serhiy-storchaka** [comment]
This test fails if run separately. See #109862.
