### ISSUE TITLE
gettext: Remove support for using non-integer value for selecting a plural form

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94194]
The feature was deprecated in Python 3.7. It's now time to remove it.

commit f6595983e08fe20cf06a2535d74d912c6dbb044f NEWS entry:

> Using non-integer value for selecting a plural form in :mod:`gettext` is
> now deprecated.  It never correctly worked.
> (Contributed by Serhiy Storchaka in :issue:`28692`.)

Feature deprecated in Python 3.7 by issue #72878.

**Comment by serhiy-storchaka** [comment]
#88434 should be resolved first.

**Comment by vstinner** [comment]
I give up on changing gettext: https://github.com/python/cpython/pull/94195#issuecomment-1303567018
