### ISSUE TITLE
ssl and hashlib: Remove functions deprecated in Python 3.10

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94199]
The commit 2875c603b2a7691b55c2046aca54831c91efda8e deprecated many ssl and hashlib functions in Python 3.10:

* ssl.OP_NO_SSLv2
* ssl.OP_NO_SSLv3
* ssl.OP_NO_TLSv1
* ssl.OP_NO_TLSv1_1
* ssl.OP_NO_TLSv1_2
* ssl.OP_NO_TLSv1_3
* ssl.PROTOCOL_SSLv2
* ssl.PROTOCOL_SSLv3
* ssl.PROTOCOL_SSLv23 (alias for PROTOCOL_TLS)
* ssl.PROTOCOL_TLS
* ssl.PROTOCOL_TLSv1
* ssl.PROTOCOL_TLSv1_1
* ssl.PROTOCOL_TLSv1_2
* ssl.TLSVersion.SSLv3
* ssl.TLSVersion.TLSv1
* ssl.TLSVersion.TLSv1_1
* ssl.wrap_socket()
* ssl.RAND_pseudo_bytes()
* ssl.RAND_egd() (already removed since it's not supported by OpenSSL 1.1.1)
* ssl.SSLContext() without a protocol argument
* ssl.match_hostname()
* hashlib.pbkdf2_hmac() (pure Python implementation, fast OpenSSL function will stay)

They emit a DeprecationWarning in Python 3.10 and 3.11. According to PEP 387, they can now be removed in Python 3.12.

I'm not sure that we should actively remove all of these deprecated features, it should be decided on a case by case basis. Backward compatibility is even more complex when it's about security and old security protocols like SSL and old TLS versions.

* PR: gh-99023

**Comment by vstinner** [comment]
* ssl.RAND_pseudo_bytes: #94202
* ssl.match_hostname: #94224
* ssl.wrap_socket: #94203
* hashlib.pbkdf2_hmac: #94200

**Comment by vstinner** [comment]
[What's New in Python 3.10 lists many deprecated ssl functions](https://docs.python.org/dev/whatsnew/3.10.html#deprecated) and announces: "**will be removed in 3.11**" (Python 3.11).

But in the meanwhile, PEP 387 was updated to require a feature to be deprecated for 2 Python releases (Python 3.10 and 3.11), not only a single Python release. Some functions were deprecated way before Python 3.10 (emit a DeprecationWarning).

**Comment by vstinner** [comment]
> I have created ticket https://github.com/python/cpython/issues/94598 to track removal of SSL 3.0, TLS 1.0, and TLS 1.1 related features.

Thank you for that!

**Comment by illia-v** [comment]
Please note that `ssl.wrap_socket` is still documented on https://docs.python.org/3.12/library/ssl.html#ssl.wrap_socket despite it was removed.

**Comment by vstinner** [comment]
> Please note that ssl.wrap_socket is still documented on https://docs.python.org/3.12/library/ssl.html#ssl.wrap_socket despite it was removed.

Oops, right. I propose PR #99023 to update the doc.

**Comment by vstinner** [comment]
I merged the last PR to remove keyfile, certfile and check_hostname parameters: https://github.com/python/cpython/commit/ef0e72b31d22f780d3a165d7d0471806061fe380

I close the issue. I removed enough ssl deprecated functions for a single version and @tiran created https://github.com/python/cpython/issues/94598 to track removal of SSL 3.0, TLS 1.0, and TLS 1.1 related features.

**Comment by Amer7G7** [comment]
> The commit [2875c60](https://github.com/python/cpython/commit/2875c603b2a7691b55c2046aca54831c91efda8e) deprecated many ssl and hashlib functions in Python 3.10:
> 
> * ssl.OP_NO_SSLv2
> * ssl.OP_NO_SSLv3
> * ssl.OP_NO_TLSv1
> * ssl.OP_NO_TLSv1_1
> * ssl.OP_NO_TLSv1_2
> * ssl.OP_NO_TLSv1_3
> * ssl.PROTOCOL_SSLv2
> * ssl.PROTOCOL_SSLv3
> * ssl.PROTOCOL_SSLv23 (alias for PROTOCOL_TLS)
> * ssl.PROTOCOL_TLS
> * ssl.PROTOCOL_TLSv1
> * ssl.PROTOCOL_TLSv1_1
> * ssl.PROTOCOL_TLSv1_2
> * ssl.TLSVersion.SSLv3
> * ssl.TLSVersion.TLSv1
> * ssl.TLSVersion.TLSv1_1
> * ssl.wrap_socket()
> * ssl.RAND_pseudo_bytes()
> * ssl.RAND_egd() (already removed since it's not supported by OpenSSL 1.1.1)
> * ssl.SSLContext() without a protocol argument
> * ssl.match_hostname()
> * hashlib.pbkdf2_hmac() (pure Python implementation, fast OpenSSL function will stay)
> 
> They emit a DeprecationWarning in Python 3.10 and 3.11. According to PEP 387, they can now be removed in Python 3.12.
> 
> I'm not sure that we should actively remove all of these deprecated features, it should be decided on a case by case basis. Backward compatibility is even more complex when it's about security and old security protocols like SSL and old TLS versions.
> 
> * PR: [gh-94199: Remove ssl.wrap_socket() documentation #99023](https://github.com/python/cpython/pull/99023)
