### ISSUE TITLE
Expose `libpath` in `venv.EnvBuilder.ensure_directories` return value

### ISSUE THREAD

**Issue by pradyunsg** [python/cpython#94214]
**Feature or enhancement**

`venv.EnvBuilder.ensure_directories` should set `libpath` as an attribute in the return value.

**Pitch**

Currently, the value is not exposed in any way via the venv API. This means that API users of venv (ahem... pip) need to recompute this information, coupling strongly to the implementation details of this module.

I noticed this as part of working on pip's build isolation logic, which I'm trying to port to venv.

**Previous discussion**

This hasn't been discussed extensively yet, but I've posted about this on https://discuss.python.org/t/16796/

**Comment by vsajip** [comment]
> Tangent: @vsajip should we create a expert-venv label?

Sure, though I don't know if stuff comes up often enough to merit it.
