### ISSUE TITLE
fnmatch module parameters names are not correct

### ISSUE THREAD

**Issue by salahbsmdz** [python/cpython#94220]
**Documentation**

fnmatch module parameters names are not correct

```python
>>> import fnmatch
>>> fnmatch.fnmatch(filename='file.txt', pattern='*.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fnmatch() got an unexpected keyword argument 'filename'
```

### Linked PRs
* gh-114152
* gh-114155
* gh-114156

**Comment by krylowicz** [comment]
According to [docs](https://docs.python.org/3/library/fnmatch.html), fnmatch doesn't accept keyword arguments

**Comment by n-i-n** [comment]
In the docs the parameters are `filename` and `pattern` while in the code `name` and `pat` is being used.
