### ISSUE TITLE
_struct.Struct should be immutable, missing Py_TPFLAGS_IMMUTABLETYPE flag

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#94254]
In Python 3.8:
```console
Python 3.8.12 (default, Oct  4 2021, 15:56:52) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _struct
>>> _struct.Struct.x = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't set attributes of built-in/extension type 'Struct'
>>> 
```

On main:
```console
Python 3.12.0a0 (heads/gh-94207-fix-struct-module-leak:9d41baebd0, Jun 25 2022, 07:23:49) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _struct
>>> _struct.Struct.x=1
>>> _struct.Struct.x
1
```

This happens because `_struct.Struct` is missing `Py_TPFLAGS_IMMUTABLETYPE` in type flags.

cc: @erlend-aasland @encukou

**Comment by mdickinson** [comment]
> _struct.Struct should be immutable

Just wondering: why? Are there benefits to that immutability?

**Comment by mdickinson** [comment]
Ah, I see there's related discussion at #88074.

**Comment by kumaraditya303** [comment]
Yes, it was the previous issue [^1] where most of this was fixed but some were left which should be fixed. 
cc @gvanrossum 

[^1]: https://github.com/python/cpython/issues/88074

**Comment by gvanrossum** [comment]
Yeah, please fix.

**Comment by erlend-aasland** [comment]
Thanks for noticing this, and thanks for the PR!

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/94269
