### ISSUE TITLE
fnv hash optimisation proposal with clang

### ISSUE THREAD

**Issue by devnexen** [python/cpython#94264]
**Feature or enhancement**

Guarantees to save unnecessary extra calls for each chunk copied, regardless of the compiler flags.

**Comment by tiran** [comment]
This should not be needed. Modern compilers replace functions like memcpy with inline assembly automatically when the code is compiled with optimization flags like -O2.

**Comment by devnexen** [comment]
In general yes, but depends which flags you pass tough ... e.g. fno-builtin, still no memcpy call generated.
