### ISSUE TITLE
sorted() returns the wrong result for a specific input using the key parameter

### ISSUE THREAD

**Issue by jweyrich** [python/cpython#94271]
**Bug report**

The `sorted()` function is returning the wrong result for a specific input when using the key parameter. Here's my test case:

```python
def test(input: list, expected: list):
    indices = sorted(range(len(input)), key=input.__getitem__)
    print(f'{indices == expected}, indices={indices}, expected={expected}')

test([1,2,3,4,5,6], [0,1,2,3,4,5]) # Output: True, indices=[0, 1, 2, 3, 4, 5], expected=[0, 1, 2, 3, 4, 5]
test([1,2,3,4,6,5], [0,1,2,3,5,4]) # Output: True, indices=[0, 1, 2, 3, 5, 4], expected=[0, 1, 2, 3, 5, 4]
test([1,2,3,6,5,4], [0,1,2,5,4,3]) # Output: True, indices=[0, 1, 2, 5, 4, 3], expected=[0, 1, 2, 5, 4, 3]
test([3,2,1,5,6,4], [2,1,0,4,5,3]) # Output: False, indices=[2, 1, 0, 5, 3, 4], expected=[2, 1, 0, 4, 5, 3]
```

The 4th (last) test prints `False` because it is not sorting the input correctly. Looks like a bug, or I'm missing something here.

**Your environment**

- CPython versions tested on: 3.8.2 and 3.8.5
- Operating system and architecture: macOS 10.15.7 and WSL 2 Ubuntu 20.04 LTS

**Comment by sweeneyde** [comment]
The result looks correct to me:

```python
>>> sorted(range(6), key=[3,2,1,5,6,4].__getitem__)
[2, 1, 0, 5, 3, 4]
```

* The smallest is the number 1, from index 2
* Next is the number 2, from index 1
* Next is the number 3, from index 0
* Next is the number 4, from index 5
* Next is the number 5, from index 3
* Last is the number 6, from index 4

**Comment by jweyrich** [comment]
> The result looks correct to me:
> 
> ```python
> >>> sorted(range(6), key=[3,2,1,5,6,4].__getitem__)
> [2, 1, 0, 5, 3, 4]
> ```
> 
> * The smallest is the number 1, from index 2
> * Next is the number 2, from index 1
> * Next is the number 3, from index 0
> * Next is the number 4, from index 5
> * Next is the number 5, from index 3
> * Last is the number 6, from index 4

Which Python version did you run? Your Python is returning the correct result.

**Comment by sweeneyde** [comment]
I got the same result for python 3.6, 3.7, 3.8, 3.9, 3.10, and 3.11.

Are you sure your "expected" value `[2,1,0,4,5,3]` isn't the problem?
