### ISSUE TITLE
Documentation: Error in datetime.datetime.strptime()

### ISSUE THREAD

**Issue by jonschz** [python/cpython#94300]
**Documentation**

The documentation for [datetime.datetime.strptime](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) is incorrect:

https://github.com/python/cpython/blob/bb8b931385ba9df4e01f7dd3ce4575d49f60efdf/Doc/library/datetime.rst#L1048-L1050

This is incorrect if `format` contains microseconds or timezone information. Counterexample:
```python
>>> timestr = '20200304050607.554321'
>>> print(datetime.strptime(timestr, '%Y%m%d%H%M%S.%f'))
2020-03-04 05:06:07.554321
>>> print(datetime(*(time.strptime(timestr, '%Y%m%d%H%M%S.%f')[0:6])))
2020-03-04 05:06:07
```
I suggest removing the cited part entirely, since since I see no easy way of correcting these lines, especially concerning timezones.

### Linked PRs
* gh-95318
* gh-103785

**Comment by hauntsaninja** [comment]
Thank you!
