### ISSUE TITLE
% operator output wrong numbers

### ISSUE THREAD

**Issue by Yusuf-ASM** [python/cpython#94303]
Remainder operator in python outputs wrong answer with negative numbers.
Example -latest available version 3.10.5 /  os windows 10 - :
```print(24%5)
print(-24%-5)
print(-24%5)
print(24%-5)
```
The output 
```
4
-4
1
-1
```
The correct output should be 
```
4
-4
-4
4
``` 

![Screenshot 2022-06-26 144913](https://user-images.githubusercontent.com/78304945/175814997-7cb1fc18-c291-41fa-a843-5a121b7e2c5f.jpg)

**Comment by hauntsaninja** [comment]
See http://python-history.blogspot.com/2010/08/why-pythons-integer-division-floors.html and  https://stackoverflow.com/questions/3883004/the-modulo-operation-on-negative-numbers-in-python

This is also documented behaviour:
https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations

> The floor division and modulo operators are connected by the following identity: x == (x//y)*y + (x%y).
