### ISSUE TITLE
Tests: check for DAC override capability instead of using geteuid()

### ISSUE THREAD

**Issue by tiran** [python/cpython#94315]
**Feature or enhancement**

Several tests use ``os.geteuid() == 0`` to check whether the current effective user can override discretionary access control and bypass permission checks for files. While user root typically has CAP_DAC_OVERRIDE, it may not actually have the capability. Non-root accounts can have CAP_DAC_OVERRIDE, too. On wasm32-emscripten it is not possible to query the actual effective uid.

I propose to add a check for DAC override instead of relying on effective uid check.

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
