### ISSUE TITLE
logging module use super() instead of class methods directly

### ISSUE THREAD

**Issue by aminalaee** [python/cpython#94327]
**Enhancement**

In the `logging` and `logging.handlers` modules there are a few cases (which are really old actually) that use class methods directly but can also make use of `super()` like this one in `FileHandler`:

https://github.com/python/cpython/blob/c0453a40faaadb43d2e69767af6c9680f8689063/Lib/logging/__init__.py#L1276-L1280

Which can be `super().emit(record)`

**Pitch**
I have prepared a PR which updates all, but I wanted to confirm first before creating it.
This will be only an internal change to update all these occurrences to  and I don't know if this kind of improvement will be accepted in the cpython project, maybe @vsajip knows more about this.

Technically I don't think there will be a difference, but it will make the code more update and readable.

**Previous discussion**

**Comment by rhettinger** [comment]
The current code is perfectly acceptable and gives predictable results.  ``super()`` is useful of cooperative multiple inheritance which is not needed or wanted here.  I haven't timed it lately, but historically is was slower than the direct reference.

There is no "readability" requirement to have to use *super*.  It is sometimes helpful to avoid hard wiring the class name, but that isn't need here.

**Comment by aminalaee** [comment]
@vsajip I haven't really checked them thoroughly.

@rhettinger the comment was not about predictable results, as it is already perfectly fine.
But you're right about the performance difference, it is a bit slower to call `super`:

```python
import timeit


class Base:
    def __init__(self, a):
        self.a = a


class Super(Base):
    def __init__(self, a):
        super().__init__(a)


class Direct(Base):
    def __init__(self, a):
        Base.__init__(self, a)



print(timeit.timeit('Super(1)', "from __main__ import Super", number=100000))
# 0.03609574999427423
print(timeit.timeit('Direct(1)', "from __main__ import Direct", number=100000))
# 0.024121000024024397
```
