### ISSUE TITLE
3.11.0b3: document conflicting subparsers

### ISSUE THREAD

**Issue by supakeen** [python/cpython#94331]
**Bug report**

In https://github.com/python/cpython/commit/ad5e8520f3e the behaviour of `add_parser` was changed to raise an exception when a parser with the same name is added. This leads to failures in test cases (such as: https://github.com/Azure/azure-cli/issues/23015).

It seems to me that this change should/could be documented in the "What's New" section for Python 3.11.

**Your environment**

pyenv + Python 3.11b3.

**Output**

```
user@desktopa ~ € python3.10 -V
Python 3.10.5
user@desktopa ~ € python3.10 test.py
user@desktopa ~ € python3.11 -V
Python 3.11.0b3+
user@desktopa ~ € python3.11 test.py 
Traceback (most recent call last):
  File "/home/supakeen/test.py", line 5, in <module>
    p.add_parser("foo")
    ^^^^^^^^^^^^^^^^^^^
  File "/home/supakeen/.pyenv/versions/3.11-dev/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
argparse.ArgumentError: argument {foo}: conflicting subparser: foo
user@desktopa ~ € cat test.py
import argparse

p = argparse.ArgumentParser().add_subparsers()
p.add_parser("foo")
p.add_parser("foo")
```

**Comment by saito828koki** [comment]
That change is documented here, and you can see it in the [changelog](https://docs.python.org/3.11/whatsnew/changelog.html) of What's new in Python. 
https://github.com/python/cpython/blob/3440d197a55800ecceea3e115e44b4262411359c/Misc/NEWS.d/3.11.0b1.rst#L1660-L1662

**Comment by supakeen** [comment]
@saito828koki Thank you, I must've missed that.
