### ISSUE TITLE
Error message for dunder methods

### ISSUE THREAD

**Issue by vainaixr** [python/cpython#94362]
current scenario -
1) 
```
class A:
  def __init(self, x):
    self.x = x

a = A(1)
```
->
```
TypeError: A() takes no arguments
```
expected scenario - 
1) it gives an error message, `Did you mean __init__?`

https://discuss.python.org/t/error-message-for-dunder-methods/16880

**Comment by AlexWaygood** [comment]
I'm closing this for now, because I don't think this is a common enough error to be worth adding complexity for. But if you manage to find more support for your idea on Discourse, feel free to open another issue (and please try to take on board my feedback above).

**Comment by vainaixr** [comment]
have changed the op, will wait for some time, I was a bit confused should I create an issue or not, as this is the second time @stevendaprano told me that could create an issue, the last time was in this post, https://discuss.python.org/t/suggestion-for-invalid-decimal-literal/15170, which is also a similar error message topic. So, I thought to create an issue this time, let us hope there is a positive reaction on this one soon, so, this issue could be reopened.

**Comment by AlexWaygood** [comment]
I'm sorry if different people have been telling you different things.

In general, as our issue template for feature requests states, we'd usually prefer contributors who aren't core developers to discuss their ideas a little bit on Discourse or the python-ideas mailing list prior to opening an issue here.
