### ISSUE TITLE
map function syntax needs to be changed in the docs,refer https://docs.python.org/3/library/functions.html#map

### ISSUE THREAD

**Issue by jo777750** [python/cpython#94378]
refer map function syntax in (https://docs.python.org/3/library/functions.html#map) so the 1st argument needs to be a function BUT map can also a Class in its 1st argument  like the valid code:map(str,range(10)) ,hence the map function can contain either  a class or function AND not only a function as stated in :- https://docs.python.org/3/library/functions.html#map  , therefore map function syntax has a documentation bug
Suggestion: How about changing map function syntax in the docs from  map(function, iterable, ...) TO map(callable, iterable, ...) ?

**Comment by rhettinger** [comment]
Thanks for the suggestion but I think it is more accessible in the current form.  It has not caused any confusion over its long life.
