### ISSUE TITLE
zipimport: Remove deprecated find_loader() and find_module() methods, use find_spec() instead

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94379]
In Python 3.10, the find_loader() and find_module() methods of zipimport were deprecated by commit d2e94bb0848e04a90efa51be401f0ce8a9e252f2 and commit 57c6cb5100d19a0e0218c77d887c3c239c9ce435.

It's now time to remove them. The find_spec() method should be used instead.

See issue #86301 and [PEP 451](https://peps.python.org/pep-0451/) for the rationale.

I wrote **PR #94380** to remove these methods.

**Comment by vstinner** [comment]
> @vstinner Shouldn't this ticket be closed given that the PR you referenced was merged?

First my PR #94380 also tried to remove load_module() but I got issues, so https://github.com/python/cpython/commit/92bcb26d000c5890127a87ade2bd813cf1218704 only removes find_loader() and find_module() methods.

This issue title is only "zipimport: Remove deprecated find_loader() and find_module() methods", so yep, I'm fine with closing it.

**Comment by warsaw** [comment]
Thanks @vstinner.  When @brettcannon and I talked about it, we noticed that `load_module()` only raised `ImportWarning` in 3.10, so in 3.12 it will raise `DeprecationWarning` and will be removed in 3.14.

**Comment by vstinner** [comment]
Ah? I only looked at zipimport.py code:

```py
    # Load and return the module named by 'fullname'.
    def load_module(self, fullname):
        """load_module(fullname) -> module.

        Load the module specified by 'fullname'. 'fullname' must be the
        fully qualified (dotted) module name. It returns the imported
        module, or raises ZipImportError if it could not be imported.

        Deprecated since Python 3.10. Use exec_module() instead.
        """
        msg = ("zipimport.zipimporter.load_module() is deprecated and slated for "
               "removal in Python 3.12; use exec_module() instead")
        _warnings.warn(msg, DeprecationWarning)
        (...)
```
