### ISSUE TITLE
`argparse` handles empty string differently on Linux and Windows 🙀

### ISSUE THREAD

**Issue by AlexPykavy** [python/cpython#94417]
**Bug report**

Consider the code
```
import argparse
import sys

print(f"argv = {sys.argv}")

parser = argparse.ArgumentParser(description='Print value.')
parser.add_argument('--value', type=str, dest="value")

args = parser.parse_args()
print(f"Passed --value = '{args.value}'")
```

Running as:
```
python temp.py --value ''
```

Result on Windows:
```
argv = ['temp.py', '--value']
usage: temp.py [-h] [--value VALUE]
temp.py: error: argument --value: expected one argument
```

Result on Linux (I used Ubuntu from WSL):
```
argv = ['temp.py', '--value', '']
Passed --value = ''
```

As a simple solution, we can just remove empty values from the `argv` to have the same initial list of arguments on both OSes. If we need to preserve the existing logic of taking empty string on Linux, we may implement a smarter algorithm. Feel free to hint me which way we will go if any. I'll be honored to contribute to Python 😊.

**Comment by AlexPykavy** [comment]
Code:
```
import argparse
import sys

print(f"argv = {sys.argv}")

parser = argparse.ArgumentParser(description='Print value.')
parser.add_argument('--valueA', type=str, dest="valueA")
parser.add_argument('--valueB', type=str, dest="valueB")

args = parser.parse_args()
print(f"Passed --valueA = '{args.valueA}'")
print(f"Passed --valueB = '{args.valueB}'")
```

Running as
```
python3 temp.py --valueA '' --valueB 'B'
```

On Windows results to:
```
argv = ['temp.py', '--valueA', '--valueB', 'B']
usage: temp.py [-h] [--valueA VALUEA] [--valueB VALUEB]
temp.py: error: argument --valueA: expected one argument
```

On Linux results to:
```
argv = ['temp.py', '--valueA', '', '--valueB', 'B']
Passed --valueA = ''
Passed --valueB = 'B'
```

**Comment by gst** [comment]
I've not used a windows shell (cmd.exe I'm speaking) for long.

what if you replace `''` by `""` ?

**Comment by gst** [comment]
https://github.com/Azure/azure-cli/pull/23061/files#diff-259b8d326c62bf2cf92b80a1c2aab68f5d767248fa0026547491b9a3c6d29a2eR281

is not this the issue ?

```python
In [1]: args = ['foo', '', 'bar', '']

In [2]: list(filter(None, args))
Out[2]: ['foo', 'bar']
```

**Comment by AlexPykavy** [comment]
> I've not used a windows shell (cmd.exe I'm speaking) for long.
> 
> what if you replace `''` by `""` ?

the same

**Comment by AlexPykavy** [comment]
Thanks @ChrisDenton, I didn't know this. So, it means that empty strings CLI arguments works both on Windows (except PowerShell) and Linux.

**Comment by AlexPykavy** [comment]
> https://github.com/Azure/azure-cli/pull/23061/files#diff-259b8d326c62bf2cf92b80a1c2aab68f5d767248fa0026547491b9a3c6d29a2eR281
> 
> is not this the issue ?
> 
> ```python
> In [1]: args = ['foo', '', 'bar', '']
> 
> In [2]: list(filter(None, args))
> Out[2]: ['foo', 'bar']
> ```

Yes, I originally found this behavior in Azure CLI and then I found the roots of the logic here.

**Comment by hauntsaninja** [comment]
Seems like this is more an issue with shell behaviour than anything with Python

**Comment by AlexPykavy** [comment]
@ChrisDenton @hauntsaninja , I agree that it looks more as a shell issue. Maybe it makes sense to document this behavior somewhere like:
- empty strings are valid argument values
- escape empty strings when passing them from PowerShell

What do you think?
