### ISSUE TITLE
Get bad circle and arc when call create_oval and create_arc with large width in tkinter Canvas

### ISSUE THREAD

**Issue by jason990420** [python/cpython#94420]
**Bug report**

I got a bad circle and a bad arc when the border width increased, not sure why the yellow ring and the yellow arc looks wrong appearance.

```python
from tkinter import *

root = Tk()

frame1 = Frame(root)
frame1.pack(side='top')
for i in range(-1, 2):
    canvas = Canvas(frame1, width=300, height=300, bg='green')
    canvas.pack(side='left')
    canvas.create_oval(50, 50, 250+i, 250+i, width=81, outline='yellow')
    canvas.create_rectangle(50, 50, 250+i, 250+i)
    canvas.create_oval(50, 50, 250+i, 250+i, width=1)

frame2 = Frame(root)
frame2.pack(side='top')
for i in range(3):
    canvas = Canvas(frame2, width=300, height=300, bg='green')
    canvas.pack(side='left')
    canvas.create_arc(50, 50, 250, 250, start=0, extent=(i+1)*90, style='arc', width=81, outline='yellow',)

root.mainloop()
```

Following figure show that
- Flat area shown at about 0 degree for all circles.
- Round cap for 1st arc drawn to 90 degree, sometime it also happened when drawn to 180 or 270 degree but not sure when it will happened exactly.

![image](https://user-images.githubusercontent.com/55352169/176465669-5ea45be0-d761-4e89-85db-b19bc8081c30.png)

**Your environment**
Platform: WIN10
Python: 3.10.1
tkinter: 8.6.12

**Comment by ronaldoussoren** [comment]
Additional data point: The output looks correct on macOS (Python 3.10.5, Tk 8.6.12, using installer on python.org).

**Comment by serhiy-storchaka** [comment]
Tkinter is relatively thin wrapper around the Tk library. Use the Tk bug tracker to file a report.

The output looks correct on Linux.
