### ISSUE TITLE
ntpath and pathlib disagree on whether driveless paths are absolute

### ISSUE THREAD

**Issue by barneygale** [python/cpython#94467]
Best shown with an example:

```python
>>> import ntpath, pathlib
>>> ntpath.isabs('/')
True
>>> pathlib.PureWindowsPath('/').is_absolute()
False
```

pathlib requires that a drive and a root (such as `c:/` or a UNC path) is present, whereas ntpath only requires a root.

**Comment by eryksun** [comment]
When opened, a rooted path without a drive such as "\\spam" is relative to the drive (or share) of the current working directory. In a symlink target, it's relative to the drive of the opened path of the symlink, which depends on how the path leading up to the symlink was parsed by the kernel (this can be very complicated). `ntpath.isabs()` is wrong for rooted paths. This has been a known problem for years, more than a decade, but there's never been a pressing need or desire to fix it. Doing so will probably break code in the standard library and third-party packages, so I think a fix would have to go through a deprecation cycle. Maybe add a new `os.path.isabspath()` function and deprecate `os.path.isabs()`.

Also, any UNC path (i.e. any path that starts with two or more slashes) is absolute, regardless of whether it contains a valid 'drive' according to `ntpath.splitdrive()`. For example, a UNC path should always replace the current result in `ntpath.join()`. This provides consistency with `os.chdir()` / WinAPI `SetCurrentDirectoryW()`, for which a path that begins with two or more slashes is never resolved relative to the drive of the current working directory. Both pathlib and ntpath need work here.
