### ISSUE TITLE
Enable pointer authentication on arm64 builds

### ISSUE THREAD

**Issue by jgowdy** [python/cpython#94471]
ARM64v8.3 supports [Pointer Authentication](https://www.qualcomm.com/media/documents/files/whitepaper-pointer-authentication-on-armv8-3.pdf) with the PACIASP and AUTIASP instructions which are interpreted as NOP instructions on pre-8.3 architectures.  These instructions sign the stack pointer and validate the stack pointer prior to return to mitigate [return oriented programming](https://en.wikipedia.org/wiki/Return-oriented_programming).

GCC supports these [options](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html) on arm64 / aarch64.  The legacy option was `-msign-return-address=[all | non-leaf | none]` and the modern option is `-mbranch-protection=none|standard|pac-ret[+leaf+b-key]|bti`

I would like to suggest that the arm64 build be modified to include `-mbranch-protection=pac-ret` with the `-march` being set to ARMv8.2 or earlier or not configured, so that GCC will generate [PACIASP](https://developer.arm.com/documentation/100076/0100/A64-Instruction-Set-Reference/A64-General-Instructions/PACIA--PACIZA--PACIA1716--PACIASP--PACIAZ?lang=en) and [AUTIASP](https://developer.arm.com/documentation/100076/0100/A64-Instruction-Set-Reference/A64-General-Instructions/AUTIA--AUTIZA--AUTIA1716--AUTIASP--AUTIAZ?lang=en) instructions.  It is critical that `-march=armv8.3` or higher not be passed or the non-backwards compatible RETAA instruction will be generated.

The benefit of enabling pointer authentication for the stack pointer on ARM64 would be to mitigate [return oriented programming](https://en.wikipedia.org/wiki/Return-oriented_programming) attacks against the CPython runtime.

Presently we (GoDaddy) are pursuing custom compiles of the CPython runtime for the new Graviton3 CPUs that support pointer authentication in AWS.

**Comment by erlend-aasland** [comment]
Marking this as pending close; see PR for details: https://github.com/python/cpython/pull/94472#issuecomment-1294848365

**Comment by erlend-aasland** [comment]
Thanks for the request, and for your interest in improving CPython, @jgowdy. Well pass on this for now; see comments on the PR.
