### ISSUE TITLE
frame.f_lineno can be None

### ISSUE THREAD

**Issue by fabioz** [python/cpython#94485]
**Bug report**

As far as I know `frame.f_lineno` should never be `None`, yet, in the case below it is:

```
import sys
def tracefunc(frame, event, arg):
    if frame.f_lineno is None:
        raise AssertionError('frame.f_lineno is None!', frame)
    return tracefunc
sys.settrace(tracefunc)

# Apparently anything we import would give a frame.f_lineno = None during tracing.
import threading
```

**Your environment**

- CPython versions tested on: `3.11.0b3 (main, Jun  1 2022, 13:29:14) [MSC v.1932 64 bit (AMD64)]`
- Operating system and architecture: `Windows`

**Comment by markshannon** [comment]
We might be able to set the line number to 0, https://peps.python.org/pep-0626/#the-f-lineno-attribute, without producing a line event.

**Comment by markshannon** [comment]
> As far as I know `frame.f_lineno` should never be `None`

It is possible in unusual circumstances, such as when the cycle GC invokes Python or a keyboard interrupt, but it shouldn't happen in normal code execution.

**Comment by fabioz** [comment]
> > As far as I know `frame.f_lineno` should never be `None`
> 
> It is possible in unusual circumstances, such as when the cycle GC invokes Python or a keyboard interrupt, but it shouldn't happen in normal code execution.

This seems a bit surprising for me... I went on looking for docs but there's surprisingly few information about this (my use case is that I was typing things with cython and it's breaking due to being `None` in Python 3.11 -- I had never seen a report for that previously where `frame.f_lineno` could be anything but an integer).

Given that the first valid line number is `1`, if it's possible to set it to `0` to indicate an invalid number while keeping the same type would make things better IMHO.

**Comment by pablogsal** [comment]
Moving this back to release blocker.
