### ISSUE TITLE
match case boolean mishap (or I am stupid)

### ISSUE THREAD

**Issue by ghost** [python/cpython#94502]
```
a = [1,2,3]
match a:
    case [1, *a]: print('ok')
print(a) # [2, 3]
# case 0: [1, 2, 3]
# case 2: [1, 2, 3]

lst = ['a','b','c']
match lst:
    case ['a', *a]: print('ok')
print(lst) # ['a', 'b', 'c']
```

**Comment by JelleZijlstra** [comment]
What is the problem here? All your comments behave as I'd expect.

**Comment by marwal88** [comment]
As I said.. I might be just plain dumb: but should a [1,2,3]
turn into [2,3] in a match-case?

**Comment by marwal88** [comment]
OK.. I see. I might not have re-used a as 'a' variable again..
Sorry 'bout this. Next time I'll do better ;)

**Comment by JelleZijlstra** [comment]
Right, the name gets bound to the variable in the `*a` place.
