### ISSUE TITLE
sys.settrace and sys.setprofile are not re-entrant

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#94510]
The code that sets trace and profile functions is not re-entrant. We are leaking objects if removing a profile/trace functions triggers a re-entrant call.

We should raise in this case.

**Comment by ambv** [comment]
This is now fixed in 3.10 - 3.12. Thanks, Pablo! ✨ 🍰 ✨

**Comment by vstinner** [comment]
This change introduce a randomly failure in test_import: issue #98257.

I propose to make the function reentrant, rather than detecting and rejecting reentrant call: PR #98258.
