### ISSUE TITLE
IDLE: <<comment-region>> didn't obey with PEP8

### ISSUE THREAD

**Issue by znsoooo** [python/cpython#94522]
**Feature or enhancement**

IDLE default use `Alt+3` to make region commented, and use `Alt+4` to uncomment.

But event \<\<comment-region\>\> only add  "##" at every start of line, but PEP8 said comment should start with ONE "#" and at least with one SPACE.

Further, if a comment with spaces before "#", like "&nbsp;&nbsp;&nbsp;&nbsp;##code", \<\<uncomment-region\>\> can't uncomment this region.

**Pitch**

In most IDEs/editors, comments can be added or removed with ONE single shortcut. I have completed an implementation at behind link.

Do we need to combine these two shortcut keys (Alt+3 and Alt+4) into one shortcut key? The logic is that detect region whether if commented, do comment region if at least one line is uncomment, and remove (one level of) comment if region is comment.

Implementation: https://github.com/znsoooo/IDLE-Advance/blob/master/idlealib/AutoComment.py

**Comment by rhettinger** [comment]
The PEP 8 recommendation is just for plain text comments.  Commenting out blocks of code is commonly done with two octothorpes.   Changing IDLE's implementation would be a regression.

**Comment by terryjreedy** [comment]
Thanks for confirming my impression of common practice.  But this should have been closed as 'not planned', on the dropdown menu, rather than the equivalent of 'fixed'.  The new interface is worse in this respect, making 'fixed' the hidden default.

**Comment by znsoooo** [comment]
Dear @rhettinger , maybe I didn't understand, what is your mean "**just for plain text**"? Does not the PEP 8 is a sugesstion for a "**Python Script**"?
And I saw in PEP 8 that `comments should start with a # and a single space`:
https://github.com/python/peps/blob/main/pep-0008.txt#L721-L724
https://github.com/python/peps/blob/main/pep-0008.txt#L736

**Comment by terryjreedy** [comment]
reply.txt
```
# Plain text comments are comments with natural language sentences.
# PEP 8 also says comment text should begin with a capital letter and end with '.'.
# Such comments are not Python code and removal of the '#' would create syntax errors.

# Commented out code blocks are lines of code deleted from compilation
# but not from the file.  Usually the intent is to undelete in the future.
# Such code blocks may contain normal comments.  Even more reason for the double hash.

##if a and b:  # Normal comment about this code.
##   c = frobulate(a, b)   # Slow.
```

**Comment by znsoooo** [comment]
@terryjreedy Sorry, I misunderstood PEP 8. Thank you!

**Comment by znsoooo** [comment]
@rhettinger @terryjreedy Hi, I remembered another situation.

When I \<comment-region> and then \<indent-region> and then try to \<uncomment-region>, I can't uncomment it (because of leading whitespace).

This sometimes happens when I refact code-with-comment moving to a new indentation level, e.g. preceded by an `if 1:`.

So I thought if we can \<uncomment-region> and ignore the leading whitespace?

Like:
```python
class Boy:
    def __init__(self, name):
        self.name = name
    ##    self.name = name.lower()
```
After \<uncomment-region>:
```python
class Boy:
    def __init__(self, name):
        self.name = name
        self.name = name.lower()
```

Do you think this would be better? Can you reopen this issue? Or I need to create a new issue? Or you reject this issue again?

**Comment by terryjreedy** [comment]
The rule 'reverse operations in reverse order' applies here.  Reverse indent before reversing comment out with uncomment.  I like having two separate inverse pairs.

**Comment by znsoooo** [comment]
Thanks for these references. This is a disappointing ending. I will fork and build it myself if I need.
