### ISSUE TITLE
Possibility for buffer overreads: `strncpy` drops a null terminator if a target buffer has no trailing space for it

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#94536]
Ubuntu runners give a bunch of warnings:

> ‘__builtin_strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]

Ivaigult in [his answer to `gcc-8 -Wstringop-truncation what is the good practice?`](https://stackoverflow.com/a/66140407) points out that they're from GCC static analyzer when `strncpy` target is not terminated manually. A reason is given in https://en.cppreference.com/w/c/string/byte/strncpy:

> If `count` is reached before the entire array `src` was copied, the resulting character array is not null-terminated.

As a result, every call to `strncpy` with large enough dynamic source strings causes buffer overread later.

A list of `strncpy` callers that need to be further analyzed:

```bat
C:\Users\oleg\Documents\dev\notmine\cpython>git grep "strncpy("
Modules/_ctypes/darwin/dlfcn_simple.c:        strncpy(errstr, "dlcompat: ", ERR_STR_LEN);
Modules/getpath.c:                    strncpy(modPath, path, MAXPATHLEN);
Modules/socketmodule.c:        strncpy(ifr.ifr_name, interfaceName, sizeof(ifr.ifr_name));
Modules/socketmodule.c:                strncpy(ifr.ifr_name, PyBytes_AS_STRING(interfaceName), sizeof(ifr.ifr_name));
Modules/socketmodule.c:                strncpy(ifr.ifr_name, PyBytes_AS_STRING(interfaceName), sizeof(ifr.ifr_name));
Modules/socketmodule.c:                strncpy(ifr.ifr_name, PyBytes_AS_STRING(interfaceName), sizeof(ifr.ifr_name));
Modules/socketmodule.c:                strncpy(info.ctl_name, PyBytes_AS_STRING(ctl_name),
Modules/socketmodule.c:        strncpy((char *)sa->salg_type, type, sizeof(sa->salg_type));
Modules/socketmodule.c:        strncpy((char *)sa->salg_name, name, sizeof(sa->salg_name));
Modules/timemodule.c:    strncpy(zone, p->tm_zone ? p->tm_zone : "   ", n);
Objects/stringlib/find.h:    strncpy(format + len, function_name, FORMAT_BUFFER_SIZE - len - 1);
PC/_msi.c:        strncpy(pccab->szCab, PyBytes_AsString(result), sizeof(pccab->szCab));
Parser/pegen.c:        strncpy(tag, start, len);
Python/getargs.c:            strncpy(msgbuf, "is not retrievable", bufsize);
Python/pystrtod.c:            strncpy(p, float_strings[OFS_INF], 3);
Python/pystrtod.c:            strncpy(p, float_strings[OFS_NAN], 3);
Python/pystrtod.c:        strncpy(p, digits, decpt-0);
Python/pystrtod.c:        strncpy(p, digits+decpt, digits_len-decpt);
Python/pystrtod.c:        strncpy(p, digits, digits_len);
```

**Comment by nascheme** [comment]
Doing a search of the CPython code base for `strncpy` and then labelling it as a "bug" is not very helpful.  It is possible there are bugs but in most or all cases these calls of `strncpy` are safe.  I think if you want to open a bug, you should check the usage of `strncpy` and then explain why you think it is unsafe.

**Comment by arhadthedev** [comment]
> It is possible there are bugs but in most or all cases these calls of strncpy are safe.

I was worried that involvement of dynamic strings into `strncpy` will break after some future refactoring affecting length of these strings.

However, the found fragments cover fundamentals and, after the second thought, have no reason to be ever changed. Hence, I'm closing the issue.

**Comment by matthiasgoergens** [comment]
https://github.com/matthiasgoergens/cpython/pull/2/commits/c1fdddcf0f7b31a5954163bfd299115b1fa7799b has a fix for one of these warnings that's still left in `main`.
