### ISSUE TITLE
dataclass field `init_using` parameter for custom initialisation

### ISSUE THREAD

**Issue by DexterHill0** [python/cpython#94548]
The idea is similar to attrs' `converter` functionality, although expanded. Often you need to convert one value to another, before assigning it to the field, but also without necessarily wanting to override any `__init__` or `__post_init__` methods.

A simple example of the syntax is:
```py
@dataclass
class Character:
    lit: str = field(init_using=chr)
```
As shown, the new argument is `init_using`. It would take *either* a method name (this would indicate the method is defined on the class), or a callable, which could be say, a built-in method (like shown above).

In the example above, the field `lit`, still has the type `str`, however, in the `__init__` method, rather than the type being `str`, the type is taken from the function signature of the `init_using` field, which in this example would be `int` (as the signature of `chr` is `chr(number: int)`. The class would look something like this after all was generated:
```py
class Character:
    lit: str

    def __init__(self, lit: int) -> None:
        self.lit = chr(lit)
``` 
 
The `init_using` parameter also allows you to init more than one field at a time. Below is an example:
```py
@dataclass
class DocumentFile:
    filename: str = field(init_using='_init_name_and_ctype')
    content_type: str = field(init_using='_init_name_and_ctype')

    def _init_name_and_ctype(self, filename: str | Path = '/tmp/example.txt') -> None:
        self.filename = str(filename)
        self.content_type = mimetypes.guess_type(filename)
```
Passed to `init_using` is the method name of the method on the class. Any fields that pass a string to `init_using` are **excluded** from the `__init__` function. Instead, the parameter names in the given method are used as the parameter names in the `__init__` function.
Dataclass would then generate the given method for `DocumentFile` like so:
```py
class DocumentFile:
    filename: str
    content_type: str

    def __init__(self, filename: str | Path = '/tmp/example.txt'):
            self._init_name_and_ctype(filename)
    
    def _init_name_and_ctype(self, filename: str | Path = '/tmp/example.txt') -> None:
            self.filename = str(filename)
            self.content_type = mimetypes.guess_type(filename)
```

> the parameter names in the given method are used as the parameter names in the `__init__` function.

To make that clearer, if you were to change the `_init_name_and_ctype` signature to be:
```py
def _init_name_and_ctype(self, file: Path) -> None:
        self.filename = str(file)
        self.content_type = mimetypes.guess_type(file)
```
The respective `__init__` function would reflect that change and would generate like:
```py
def __init__(self, file: Path):
        self._init_name_and_ctype(file)
````
The names of the fields do not have any affect on the init function when `init_using` is provided a string.

The argument `default_factory` would be mutually exclusive with `init_using`,. It hasn't yet been decided whether `default` is also mutually exclusive, or whether it adds the default value to the `__init__` function like it already does.

**Previous discussion**
https://mail.python.org/archives/list/python-ideas@python.org/thread/4SM5EVP6MMGGHQMZSJXBML74PWWDHEWV/

**Comment by ajoino** [comment]
I have no strong feeling about this proposal, but I think this goes beyond the intention of dataclasses, i.e., a fast way to create (fairly) simple data containers. (I know it's used as a way to remove boilerplate too, even for more complex classes.)

When I've faced the problem of needing to create a class instance from other useful paramaters (using `@dataclass` or `pydantic.BaseModel`), I tend to create a new constructor instead. So what you're proposing
```python
@dataclass
class Foo:
    x: int
    y: str = field(init_using=chr)
    z: str = field(init_using='_initializer')
    w: str = field(init_using='_initializer')

    def _initializer(path: Path):
        self.z = str(path)
        self.w = path.suffix

foo = Foo(5, 68, 'file.txt')
```
I would write as
```python
@dataclass
class Foo:
    x: int
    y: str
    z: str
    w: str

    @classmethod
    def from_int_and_file(cls, x: int, y: int, path: Path) -> Self:
        y = chr(y)
        z = str(path)
        w = path.suffix
        return cls(x, y, z, w)

foo = Foo.from_int_and_file(5, 68, 'file.txt')
```

I think additional constructors is the better approach, but I can see the appeal of your suggestion.

**Comment by DexterHill0** [comment]
That's fair enough. The original reason I suggested the feature was while I was writing a something for regex. I had a `Literal` class which had a `lit` field that stored the character. There was already a secondary constructor that took a string and created the literal, so in that context it made more sense to then have `__init__` take an `int`, but obviously I couldn't convert it. (Also can partially blame that I just didn't think about an additional constructor).

> a fast way to create (fairly) simple data containers
The original idea I proposed was purely just for attrs' converter functionality but in dataclasses. Through the other discussion that syntax was proposed (which I liked as it built upon my original suggestion, but kept the ability for single field conversions), however, if the feature was purely the ability to map a single value to a single field, through a given function, do you think that would be better for dataclasses?

**Comment by florianlaws** [comment]
One nice usecase for this would be an initializer that could convert sets to frozenset, such that you can have a field that is a frozenset, but pass in a set in the constructor.

**Comment by ericvsmith** [comment]
Since PEP 712 was rejected, I'm going to close this. If there's any further discussion about creating a new PEP, it should be discussed on discuss.python.org.
