### ISSUE TITLE
Imporve docs for Raising Exceptions

### ISSUE THREAD

**Issue by CharlieZhao95** [python/cpython#94596]
**Documentation**

In [raising-exceptions](https://docs.python.org/3.10/tutorial/errors.html#raising-exceptions), the document describes the following:

> The sole argument to raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from Exception). 

Note, however, that unexpected results may occur if **the same exception instance** is raised repeatedly. For example:
```python
One = Exception()

def bad_func():
    try:
        raise One
    except Exception:
        print(os.linesep.join(traceback.format_tb(sys.exc_info()[-1])))
        print("-" * 70)

bad_func()
bad_func()
bad_func()
```
Execute above code:
```
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

----------------------------------------------------------------------
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

----------------------------------------------------------------------
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One
```
We got unexpected traceback. What we might want is:
```
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

----------------------------------------------------------------------
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One

----------------------------------------------------------------------
  File "f:\CPython\github\cpython\debug\demo.py", line 42, in bad_func
    raise One
```

The reason is that the exception object carries traceback information. When we throw the same exception object , the previous traceback object is added to the thread state (by function `PyException_GetTraceback` and `_PyErr_Restore`) and link to the current traceback object. 

Perhaps somewhere in the document we could remind users not to throw the same exception object to avoid unexpected results.

**Comment by ajoino** [comment]
What is the use case for creating an instance of an exception and then raising that instance, instead of just creating the instance in the `raise` statement?

**Comment by CharlieZhao95** [comment]
> What is the use case for creating an instance of an exception and then raising that instance, instead of just creating the instance in the `raise` statement?

I'm just trying to tell users not to use raise like this. Not everyone understands the internal implementation of CPython(This is a question put to me by my colleague). 

It doesn't happen in other languages either, such as Java. This python-specific behavior can be confusing.

We could provide best practices of `raise` to users:
```python
# best practices of `raise`
raise
raise MyException()  # <instance>
raise MyException    # <type> 
```
