### ISSUE TITLE
Compiling blake2 on x86

### ISSUE THREAD

**Issue by gvanem** [python/cpython#94594]
Compiling either `Modules/_blake2/impl/blake2b.c` or `Modules/_blake2/impl/blake2s.c` for 32-bit using either MSVC-2022
or clang-cl ver 13.0.1 have issues with prototyping ` _mm_set_epi64x()`.

First the error from clang-cl:
```
Modules/_blake2/impl/blake2b.c(31,23): error: conflicting types for '_mm_set_epi64x'
static inline __m128i _mm_set_epi64x( const uint64_t u1, const uint64_t u0 )
                      ^
F:\gv\VC_2022\VC\Tools\Llvm\lib\clang\13.0.1\include\emmintrin.h(3609,1): note: previous definition is here
_mm_set_epi64x(long long __q1, long long __q0)
^
```

Then compiling with `cl`:
```
Modules/_blake2/impl/blake2b.c(32): error C2169: '_mm_set_epi64x': intrinsic function, cannot be defined
```

Since `_mm_set_epi64x` is already prototyped in `<emmintrin.h>` as:
```c
extern __m128i _mm_set_epi64x (__int64 _I1, __int64 _I0);
```

The same issue exist when compiling `Modules/_blake2/impl/blake2s.c`.

The fix for me was simply to disable those *redefinitions* with:
```diff
--- a/Modules/_blake2/impl/blake2b.c 2021-05-19 09:59:27
+++ b/Modules/_blake2/impl/blake2b.c 2022-07-06 08:07:47
@@ -27,7 +27,7 @@
 #if defined(HAVE_SSE2)
 #include <emmintrin.h>
 // MSVC only defines  _mm_set_epi64x for x86_64...
-#if defined(_MSC_VER) && !defined(_M_X64)
+#if defined(_MSC_VER) && !defined(_M_X64) && 0
 static inline __m128i _mm_set_epi64x( const uint64_t u1, const uint64_t u0 )
 {
   return _mm_set_epi32( u1 >> 32, u1, u0 >> 32, u0 );

--- a/Modules/_blake2/impl/blake2s.c 2021-05-19 09:59:27
+++ b/Modules/_blake2/impl/blake2s.c 2022-07-06 08:07:42
@@ -27,7 +27,7 @@
 #if defined(HAVE_SSE2)
 #include <emmintrin.h>
 // MSVC only defines  _mm_set_epi64x for x86_64...
-#if defined(_MSC_VER) && !defined(_M_X64)
+#if defined(_MSC_VER) && !defined(_M_X64) && 0
 static inline __m128i _mm_set_epi64x( const uint64_t u1, const uint64_t u0 )
 {
   return _mm_set_epi32( u1 >> 32, u1, u0 >> 32, u0 );
```
So the comment in those files `// MSVC only defines  _mm_set_epi64x for x86_64...` is no longer true it seems.

**Comment by zooba** [comment]
Yes, the definition does seem to be there. However, it seems we never use these files when building CPython? So this doesn't affect us, and it's only an issue if you're trying to copy those files from our repo into something else?

**Comment by gvanem** [comment]
> However, it seems we never use these files when building CPython? 

Really?

**Comment by zooba** [comment]
I added deliberate syntax errors and forced a rebuild and nothing failed. But maybe there's some logic in the blake2 library that uses alternate implementations if a compile-time module is missing? Normally you need to have something in the project files though, and I don't think we do.

**Comment by gvanem** [comment]
> Normally you need to have something in the project files though, and I don't think we do.

I now see that  `Modules/_blake2/impl/blake2[bs].c`  are **not** referenced in any `*.vcxproj` file. 
But then it's rather confusing IMHO that they are present. I note `Modules/_blake2/impl/blake2[bs]-ref.c` are used instead. Correct?

Besides, the comments in these says:
*  `Modules/_blake2/impl/blake2[bs].c`:       optimized C implementations
*  `Modules/_blake2/impl/blake2[bs]-ref.c`: reference C implementations

Why shouldn't Python use the optimized versions for speed?

**Comment by tiran** [comment]
Because they are actually faster unless AVC, XOP, SSSE 3 or better are available:

https://github.com/python/cpython/blob/75a6441718dcbc65d993c9544e67e25bef120e82/Modules/_blake2/blake2b_impl.c#L27-L33

**Comment by gvanem** [comment]
Okay, I see. But MSVC doesn't define `__SSSE3__` or `__SSE4_1__` for any `-arch:xx` AFAICS. Only `__AVX__`.
