### ISSUE TITLE
Cannot use newline="\x00" with open() or TextIOWrapper

### ISSUE THREAD

**Issue by hydrargyrum** [python/cpython#94615]
# Bug report

I want to read lines of text, but separated with null bytes, which decode as null codepoint with UTF8. This is widespread practice in command-line tools, for example `find -print0`, `locate -0`, `xargs -0`, `sort -z`.

Python's `open` documentation states (emphasis mine):

> When reading input from the stream, if newline is None, universal newlines mode is enabled. Lines in the input can end in '\n', '\r', or '\r\n', and these are translated into '\n' before being returned to the caller. If it is '', universal newlines mode is enabled, but line endings are returned to the caller untranslated. **If it has any of the other legal values, input lines are only terminated by the given string, and the line ending is returned to the caller untranslated.**

So this is legal: `open(some_file, newline="\x00")`, but I immediately get the exception `ValueError: embedded null character`.

# Your environment

- CPython versions tested on: 3.9, 3.10

**Comment by zware** [comment]
This looks like perhaps the docs could use some clarification; it mentions "any of the *other legal values*" presumably meaning `\r`, `\n`, or `\r\n` but without coming right out and saying that.  From my reading, that means your `open(some_file, newline="\x00")` is *not* actually legal.  For example, `open('some_file', 'r', newline='e')` raises `ValueError` as well, though with a different error message.

**Comment by hydrargyrum** [comment]
Ok, now I see the misunderstanding! Indeed allowing other separators would be a useful addition for those cases of filter command-line tools. I don't know if there would be other use cases, or if there's an alternate way to do so. In the meantime, I will use some specific code to read a file, splitting at nulls.

**Comment by zware** [comment]
As a bug report, I'm going to go ahead and close this.  If someone is interested in making `\x00` a valid value for `newline`, please open a separate feature request (preferably with a PR ;) ).
