### ISSUE TITLE
SSLContext.set_default_verify_paths holds GIL for > 1s

### ISSUE THREAD

**Issue by efroemling** [python/cpython#94637]
Hi; I'm the author of a [game engine](https://github.com/efroemling/ballistica) which makes heavy use of Python. The engine sends various network requests in background threads for various purposes. Recently I switched these to use https instead of http, and soon after noticed my Android builds in particular started hitching badly.

I tracked this down to my main logic thread occasionally spending upwards of 1 second waiting for a GIL lock, and further tracked that down to SSLContext.set_default_verify_paths(). That gets called by the urllib requests I'm firing off in my bg thread and winds up starving all other threads as it holds on to the GIL for the entirety of the SSL_CTX_set_default_verify_paths() call, which for some reason is taking quite a while on some Android devices.

I can separately look into why the underlying call is taking so long in the Android case, but regardless I'm able to completely eliminate the hitches by releasing the GIL for that call (enclosing the SSL_CTX_set_default_verify_paths() call with PySSL_BEGIN_ALLOW_THREADS/PySSL_END_ALLOW_THREADS).

Is that safe and reasonable to do for that call? I'd be happy to make a PR if so.

This was all tested on Python 3.10.5.

Thanks
-Eric

https://github.com/python/cpython/blob/760b8cf0c887fbc5191611a7e7d4b8c0c4f15edc/Modules/_ssl.c#L4301-L4310

**Comment by efroemling** [comment]
> You can also optimize the code and use a single SSLContext object for all network code. It is safe to share a single instance across threads if you don't modify the object (load more certs, change verification parameters, options, etc.).

Good to know; thanks! Even with the GIL-related hitches fixed, that would probably be worth it for me to do to shave that time off of individual network round trips. I'm assuming this would be done by explicitly passing in the SSLContext for each particular use? Or is there any higher level way to get things to share a single context by default?

And on a related note, is there any clean way to point all contexts at a root cert file by default? Since Android doesn't seem to have certs in a consistent place I'm bundling ones from the Python certifi package and using the SSL_CERT_FILE env var to point SSL at them, which gets them picked up by all contexts, but I didn't know if there's a more 'correct' way to do that sort of thing.

**Comment by tiran** [comment]
All stdlib network modules accept a ``context`` or ``ssl_context`` argument, e.g. ``urllib.request.urlopen(context=...)``. You have to pass a context explicitly.

I recommend that users always create a context with [``ssl.create_default_context()``](https://docs.python.org/3/library/ssl.html#ssl.create_default_context). It will either load certificates from default location (and use ``SSL_CERT_FILE``) or you can pass arguments to load a cafile or capath instead. You can load additional trust anchors with ``ctx.load_verify_locations()``.

**Comment by efroemling** [comment]
Ok; sounds good. I'll just pass in an explicit shared context created from `ssl.create_default_context()` in places I want to speed up then. And it sounds like SSL_CERT_FILE is the right way to go to get said default contexts doing the right thing in my case. 👍

One obscure note in case its helpful: on my Android OpenSSL build, SSL_CERT_FILE wasn't actually getting read by default. OpenSSL does a `ossl_safe_getenv()` call which was disallowing its use for some reason. But ssl.get_default_verify_paths() incorrectly listed it as a verify path. I don't know if it would be possible or worth the energy to have get_default_verify_paths() tap into that same logic to keep things consistent, but I just thought I'd mention it. (I wound up just forcing my Android SSL build to always accept env vars to work around the issue).
