### ISSUE TITLE
Restructure the sqlite3 docs table-of-contents

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#94635]
The current docs are laid out more or less like this:

- short introduction
- relatively short tutorial
- reference
- how-to's/guides and some in-depth explanations

Suggesting to make the following improvements:

- add top-level headings for:
    - introduction
    - tutorial
    - reference
    - guides
    - concepts
- reorder sections according to the new ToC
- add anchors for each top-level heading

Implemented by (all backported to 3.11 and 3.10):
- #95269 
- #94636 
- #95751
- #96089
- #94677 (closed, as it was implemented by other PRs)
- #96136

**Comment by erlend-aasland** [comment]
cc. @CAM-Gerlach #diataxis

**Comment by erlend-aasland** [comment]
>   * introduction
>   * tutorial
>   * reference
>   * guides
>   * concepts

Maybe it is better to swap Concepts and Guides:

- introduction
- tutorial
- reference
- concepts
- guides

**Comment by rhettinger** [comment]
FWIW, I teach sqlite3 directly from the current docs.  They are VERY useful as-is.

I would like to know what problem is being solved here.  From what I can tell, no user has ever had issues with the current arrangement.

**Comment by erlend-aasland** [comment]
> FWIW, I teach sqlite3 directly from the current docs. They are VERY useful as-is.

Thanks!

> I would like to know what problem is being solved here.

The top-level structure is flat. I'm suggesting to organise the sections under headings:

<details>
<summary>Current layout</summary>

### Table of Contents

sqlite3 — DB-API 2.0 interface for SQLite databases
- Module functions and constants
- Connection Objects
- Cursor Objects
- Row Objects
- Blob Objects
- Exceptions
- SQLite and Python types
    - Introduction
    - Using adapters to store custom Python types in SQLite databases
        - Letting your object adapt itself
        - Registering an adapter callable
    - Converting SQLite values to custom Python types
    - Default adapters and converters
    - Adapter and Converter Recipes
- Controlling Transactions
- Using sqlite3 efficiently
    - Using shortcut methods
    - Accessing columns by name instead of by index
    - Using the connection as a context manager


</details>

<details>
<summary>After this PR</summary>

### Table of Contents

sqlite3 — DB-API 2.0 interface for SQLite databases
- Introduction
- Tutorial
- Reference
    - Module functions and constants
    - Connection Objects
    - Cursor Objects
    - Row Objects
    - Blob Objects
    - Exceptions
- Guides
    - Using adapters to store custom Python types in SQLite databases
        - Letting your object adapt itself
        - Registering an adapter callable
    - Converting SQLite values to custom Python types
    - Adapter and Converter Recipes
        - Default adapters and converters
    - Using shortcut methods
    - Accessing columns by name instead of by index
    - Using the connection as a context manager
- Concepts
    - SQLite and Python types
    - Controlling Transactions

</details>

**Comment by erlend-aasland** [comment]
> From what I can tell, no user has ever had issues with the current arrangement.

As I view it, this is a weak argument for keeping things as they are. There can be room for improvement, both in docs and code, even though no-one has taken the steps to create a ticket on the bug tracker.

**Comment by erlend-aasland** [comment]
I suggest to remove the _Introduction_ heading (it serves little purpose), and then close this issue.

**Comment by CAM-Gerlach** [comment]
There are still a couple things that need doing:

* The "How-to" sections should be renamed to avoid "Using", etc. and be more clear they are how tos per Diataxis as you did in the closed #94635 
* Thinking more about it, the "Default Adapters and Converters" section is actually pretty clearly a Reference, and should be moved accordingly

Would you like me to open PRs for these, or do them yourself?

**Comment by erlend-aasland** [comment]
> There are still a couple things that need doing:
> 
> * The "How-to" sections should be renamed to avoid "Using", etc. and be more clear they are how tos per Diataxis as you did in the closed [Restructure the sqlite3 docs table-of-contents #94635](https://github.com/python/cpython/issues/94635)
> * Thinking more about it, the "Default Adapters and Converters" section is actually pretty clearly a Reference, and should be moved accordingly
> 
> Would you like me to open PRs for these, or do them yourself?

Sure, go ahead :)

**Comment by erlend-aasland** [comment]
FTR, Daniele's Camera docs repeat "How-to" for subsections:
<img width="360" alt="Screenshot 2022-08-19 at 12 05 02" src="https://user-images.githubusercontent.com/13780613/185596484-2b3f498e-e58c-4e77-8813-0b87de4101dc.png">

**Comment by CAM-Gerlach** [comment]
Will do shortly :+1: 

I've indeed come around to your reasoning on this :smile:

**Comment by CAM-Gerlach** [comment]
Thanks, opened as #96136

**Comment by erlend-aasland** [comment]
AFAICS, we can close this. Thanks CAM and Ezio!

**Comment by CAM-Gerlach** [comment]
Thanks to you for doing most of the work!
