### ISSUE TITLE
`pyconfig.h` redefines system-supplied `_XOPEN_SOURCE` on Ubuntu

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#94642]
While analyzing [some unrelated cpython CI run](https://github.com/python/cpython/runs/7221193870?check_suite_focus=true), I met the folowing warning (highlighting is mine):

> 2022-07-06T19:04:46.9332000Z gcc -pthread -fPIC -Wsign-compare -g -Og -Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -I../cpython-ro-srcdir/Include/internal -D_DEFAULT_SOURCE ***-D_XOPEN_SOURCE=600*** -I/usr/include/readline -I../cpython-ro-srcdir/Include -IObjects -IPython -I. -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/home/runner/work/cpython/cpython-ro-srcdir/Include -I/home/runner/work/cpython/cpython-builddir -c /home/runner/work/cpython/cpython-ro-srcdir/Modules/readline.c -o build/temp.linux-x86_64-3.12-pydebug/home/runner/work/cpython/cpython-ro-srcdir/Modules/readline.o
2022-07-06T19:04:46.9425858Z In file included from ../cpython-ro-srcdir/Include/Python.h:12,
2022-07-06T19:04:46.9426664Z                  from /home/runner/work/cpython/cpython-ro-srcdir/Modules/readline.c:8:
2022-07-06T19:04:46.9427267Z ./pyconfig.h:1762: warning: "_XOPEN_SOURCE" redefined
2022-07-06T19:04:46.9427830Z  1762 | #define _XOPEN_SOURCE 700
2022-07-06T19:04:46.9428471Z       | 

According to it:

1. Makefile passes `-D_XOPEN_SOURCE=600` twice
2. The passed definition is forcedly overwritten by `#define _XOPEN_SOURCE 700` (maybe it should be wrapped in `#ifndef` instead?)

**Comment by arhadthedev** [comment]
The fragment is availabe in raw logs only for some reasons:

![image](https://user-images.githubusercontent.com/4881073/177698532-a10381f3-eefb-45db-8601-612d14bf3fc5.png)

**Comment by tiran** [comment]
It's a harmless warning. Some pkg-config files specify conflicting CFLAGS. We also want to use level 700 here. ``pyconfig.h`` is auto-generated and it is surprisingly complicated to add custom and conditional code.

**Comment by arhadthedev** [comment]
> We also want to use level 700 here

Can we do something like this then?

```cpp
#if _XOPEN_SOURCE < 700
#    if defined(_XOPEN_SOURCE)
#        undef _XOPEN_SOURCE
#    endif
#    define _XOPEN_SOURCE 700
#endif
```

> `pyconfig.h` is auto-generated and it is surprisingly complicated to add custom and conditional code.

Fortunately compiler doesn't complain so the deduplication efforts can be skipped altogether.

**Comment by tiran** [comment]
No, the file is auto-generated. The templating language is limited and we cannot use undef there.

**Comment by tiran** [comment]
gh-94642 gets rid of the define from pkg-config files for more cases. You should not see the warnings any more.

There might be hacks to work around the problem, but it would make our configure and build system even more complicated. I'm not ready to add more complications if a simple sed does the job, too.
