### ISSUE TITLE
Python 3.11 beta3 fails to build (_ctypes extension) on N32-abi based MIPS 

### ISSUE THREAD

**Issue by akhuettel** [python/cpython#94656]
**Bug report**

Python 3.11 beta3 fails to build (more specifically, its _ctypes extension) on Gentoo in all variants where
the N32 ABI is the main system ABI on MIPS. 

```
building '_ctypes' extension
mips64-unknown-linux-gnu-gcc -fPIC -Wsign-compare -DNDEBUG -O2 -march=mips64 -mabi=n32 -mplt -pipe -fwrapv -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I./Include -I. -I/usr/include/ncursesw -I/var/tmp/portage/dev-lang/python-3.11.0_beta3/work/Python-3.11.0b3/Include -I/var/tmp/portage/dev-lang/python-3.11.0_beta3/work/Python-3.11.0b3 -c /var/tmp/portage/dev-lang/python-3.11.0_beta3/work/Python-3.11.0b3/Modules/_ctypes/_ctypes.c -o build/temp.linux-mips64-3.11/var/tmp/portage/dev-lang/python-3.11.0_beta3/work/Python-3.11.0b3/Modules/_ctypes/_ctypes.o
/var/tmp/portage/dev-lang/python-3.11.0_beta3/work/Python-3.11.0b3/Modules/_ctypes/_ctypes.c:118:10: fatal error: ffi.h: No such file or directory
  118 | #include <ffi.h>
      |          ^~~~~~~
compilation terminated.
```
3.10 and earlier build fine.

**Explanation on MIPS ABI**
MIPS has 3 ABI, 
* o32 (a pure 32bit ABI, e.g. with CHOST=mips-unknown-linux-gnu on BE)
* n64 (a pure 64bit ABI, e.g. with CHOST=mips64-unknown-linux-gnu on BE)
* n32 (a "mixed ABI" similar to x32, which also requires 64bit hardware, **also with CHOST=mips64-unknown-linux-gnu** on BE)

Each of these can be used alone, in a single-ABI install; historically there are also multilib installs where n32 provides the main system ABI but n64 is supported for applications).

On Gentoo, the library directory is "lib" for o32, "lib32" for n32, and "lib64" for n64.

**Debugging done**
I tested on a multilib install, where n32 is the main system ABI and the build fails.
pkgconfig provides useful and correct output:
```
dilfridge-mips64-multilib ~ # pkg-config libffi --cflags-only-I
-I/usr/lib32/libffi/include 
dilfridge-mips64-multilib ~ # pkg-config libffi --cflags-only-I 2>/dev/null | sed -e 's/^-I//;s/ *$//'
/usr/lib32/libffi/include
dilfridge-mips64-multilib ~ # ls -l /usr/lib32/libffi/include
total 24
-rw-r--r-- 1 root root 14253 Apr 18 14:51 ffi.h
-rw-r--r-- 1 root root  6578 Apr 18 14:51 ffitarget.h
```
[build.log](https://github.com/python/cpython/files/9063185/build.log)
[config.log](https://github.com/python/cpython/files/9063186/config.log)

Maybe python is somehow setting a wrong libdir to search, or a wrong configuration directory for pkgconfig? 

MIPS installs with o32 or n64 ABI build python-3.11_beta3 fine.

**Comment by akhuettel** [comment]
See also the original bug report https://bugs.gentoo.org/850151

**Comment by tiran** [comment]
3.11 still uses this weird mix of pkg-config and custom distutils code to detect libffi.

Could you please add ``import pdb; pdb.set_trace`` to ``detect_ctypes`` in ``setup.py`` and show us the value of 
- ``sysconfig.get_config_var("LIBFFI_INCLUDEDIR")``
- ``self.lib_dirs``
- ``self.compiler.find_library_file(self.lib_dirs, lib_name`` for ``ffi`` and ``ffi_pic``?

**Comment by akhuettel** [comment]
```
(Pdb) print(sysconfig.get_config_var("LIBFFI_INCLUDEDIR"))
/usr/lib32/libffi/include
(Pdb) print(self.lib_dirs)
['.', '/usr/local/lib', '/lib64', '/usr/lib64', '/lib', '/usr/lib']
(Pdb) print(self.compiler.find_library_file(self.lib_dirs, 'ffi')) 
None
(Pdb) print(self.compiler.find_library_file(self.lib_dirs, 'ffi_pic'))
None
```

**Comment by akhuettel** [comment]
```
dilfridge-mips64-multilib / # find / -name libffi.so
/usr/lib32/libffi.so
dilfridge-mips64-multilib / # find / -name libffi_pic.so
dilfridge-mips64-multilib / # 
```

Basically, libffi is installed for the "main / system" abi which all the system binaries use, but not for any other abi which are only added on request.

**Comment by floppym** [comment]
For Python 3.10, Gentoo applies this patch:

https://github.com/gentoo/cpython/commit/69fccd4a801cb0e2f303f765e1bee8d7589d803f

We sed in the appropriate value for `@@GENTOO_LIBDIR@@` when we build the package.

I think this patch just needs to be adapted for Python 3.11 downstream.

**Comment by akhuettel** [comment]
@floppym I think you're right. Will test.
(I'm not member of python team but taking care of weird arches in release engineering, so...)

**Comment by akhuettel** [comment]
My apologies for the noise. @floppym was correct and this was due to the missing patch on the Gentoo side. Fixed now.
There's nothing left to do here.
