### ISSUE TITLE
[subinterpreters] Static types incorrectly share some objects between interpreters

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#94673]
While static types (`PyTypeObject` values) don't themselves ever change (once `PyType_Ready()` has run), they do hold mutable data.  This means they cannot be safely shared between multiple interpreters without a common GIL (and without state leaking between).

Mutable data:

* the object header (e.g. refcount), as with all objects
* otherwise immutable objects:
    * ob_type (`__class__`)
    * tp_base (`__base__`) - set by `PyType_Ready()` if not set
    * tp_bases (`__bases__`) - always set by `PyType_Ready()`
    * tp_mro (`__mro__`) - always set by `PyType_Ready()`
    * tp_dict (`__dict__`) - set by `PyType_Ready()` if not set
* mutable containers:
    * tp_subclasses (`__subclasses__`)
    * tp_weaklist

(See https://docs.python.org/3/c-api/typeobj.html#tp-slots.)
(Note that `tp_cache` is no longer used.)
 
For the object header, if PEP 683 (immortal objects) is accepted then we can make static types immortal.

For the otherwise immutable objects, we can make sure each is immortal and then we're good.  Even `tp_dict` is fine since it gets hidden behind `types.MappingProxyType`.  We'd also need to either make sure each contained item is immortal.

For `tp_subclasses` we will need a per-interpreter copy, and do the proper lookup in the `__subclasses__` getter.  The cache could be stored on `PyInterpreterState` or even as a dict in `tp_subclasses`.

For `tp_weaklist` it's a similar story as for `tp_subclasses`.  Note that `tp_weaklist` isn't very important for static types since they are never deallocated.

(The above is also discussed in [PEP 684](https://peps.python.org/pep-0684/#global-objects).)

CC @kumaraditya303

### Linked PRs
* gh-102663
* gh-103912
* gh-103940
* gh-103961
* gh-104072
* gh-104074
* gh-105465
* gh-105471
* gh-117761
* gh-117980

**Comment by ericsnowcurrently** [comment]
See https://peps.python.org/pep-0684/#global-objects.

**Comment by kumaraditya303** [comment]
The current `_PyInterpreterState_GET` (which would be used here) static inline function is quite inefficient as there is a lot indirection and involves atomic reads to get the "current" thread and then get the interpreter state. To improve this we can use thread local [^1] variables on supported platform such as Linux, Windows and macOS. On Linux with glibc, the thread local implementation uses fs segment register and on X86-64 it is very efficient compared to the current implementation.

[^1]: https://en.cppreference.com/w/c/thread/thread_local

**Comment by encukou** [comment]
> This means they cannot be safely shared between multiple interpreters without a common GIL

Python currently has a common GIL.
Shouldn't this be part of a PEP, rather than an issue?

**Comment by ericsnowcurrently** [comment]
I have the changes ready for this:
* gh-94995 - adds (basically) empty per-interpreter state for the static builtin types.
* based on top of that one:
   * https://github.com/ericsnowcurrently/cpython/compare/init-static-builtin...shareable-static-types-tp_subclasses - add `tp_subclasses` to that state
   * https://github.com/ericsnowcurrently/cpython/compare/init-static-builtin...shareable-static-types-tp_weaklist - add `tp_weaklist` to that state

**Comment by ericsnowcurrently** [comment]
> This isn't required here but would be nice to investigate separately.

This has been discussed elsewhere.  Also see https://github.com/python/cpython/pull/29228.

FYI, for this PR (and in most cases) the performance penalty is insignificant.

**Comment by ericsnowcurrently** [comment]
I've split up that first PR:

* https://github.com/python/cpython/pull/95152
* https://github.com/python/cpython/pull/95153

Which, together, are followed by:

* https://github.com/ericsnowcurrently/cpython/compare/init-static-builtin-new...static-builtin-state

On top of that I'll add:
* https://github.com/ericsnowcurrently/cpython/compare/init-static-builtin...shareable-static-types-tp_subclasses - add tp_subclasses to that state
* https://github.com/ericsnowcurrently/cpython/compare/init-static-builtin...shareable-static-types-tp_weaklist - add tp_weaklist to that state

**Comment by encukou** [comment]
> This is covered by PEP 684. The issue exists for implementation discussion and to anchor PRs.

Please get the PEP accepted before merging anything you can't easily revert.

**Comment by ericsnowcurrently** [comment]
gh-95302 slows things down ~1% so I'll need to address that.  (See https://github.com/python/cpython/pull/95302#issuecomment-1199025042.)

**Comment by ericsnowcurrently** [comment]
FYI, https://github.com/python/cpython/issues/44470 is where we dealt with leaking memory during finalization.  It looks like we missed some cases there (relative to both tp_subclasses and tp_weaklist), which my PRs help to address.

**Comment by ericsnowcurrently** [comment]
Also FTR, a per-interpreter GIL isn't the only motivator here.  It's a good idea to keep a per-interpreter `tp_subclasses`, etc.  Otherwise `cls.__subclasses__` and `weakref.getweakrefs(cls)` will show the objects from *all* interpreters, which is a problem for users.

**Comment by ericsnowcurrently** [comment]
I'm marking this as done.  If we determine we need to revisit this (e.g. for `tp_dict`) then we can create a new issue.

**Comment by ericsnowcurrently** [comment]
FTR, it is hypothetically possible to modify `tp_dict` from Python code.  See gh-88004.

**Comment by gvanrossum** [comment]
We now get a warning when building without pydebug:
```
Objects/typeobject.c:120:1: warning: unused function 'static_builtin_index_is_set' [-Wunused-function]
static_builtin_index_is_set(PyTypeObject *self)
^
1 warning generated.
```
