### ISSUE TITLE
`binascii.a2b_base64` ignores padding inside a string

### ISSUE THREAD

**Issue by DemiMarie** [python/cpython#94703]
**Bug report**

The following code should raise `binascii.Error` but does not:

```python
import binascii
binascii.a2b_base64(b'=aa==')
```

It appears (from looking at the source code) that this is also the case in 3.11, even in strict mode.

**Your environment**

- CPython versions tested on: 3.10
- Operating system and architecture: Fedora 36, Linux 5.15.52, x86_64

**Comment by yourlefthandman** [comment]
When running the code from main, the behaviour is as you expect it to be :)

```
>>> binascii.a2b_base64(b'=aa==', strict_mode=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
binascii.Error: Leading padding not allowed
```

The following code handles it-
```
if (strict_mode && ascii_len > 0 && ascii_data[0] == '=') {
        state = get_binascii_state(module);
        if (state) {
            PyErr_SetString(state->Error, "Leading padding not allowed");
        }
        goto error_end;
    }
```

Looking at 3.11, i see the code is there too - [link](https://github.com/python/cpython/blob/7a341724e4dc8188f01ac338deaa414c4e6542c4/Modules/binascii.c#L407)

**Comment by DemiMarie** [comment]
Does it reject this input?

```
import binascii
binascii.a2b_base64(b'aaaa=aa==', strict_mode=True)
```
?

**Comment by yourlefthandman** [comment]
Yup :)
```
>>> import binascii
>>> binascii.a2b_base64(b'aaaa=aa==', strict_mode=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
binascii.Error: Discontinuous padding not allowed
```

**Comment by Mohitduklan** [comment]
Is it because python 3.10.5 uses REF 4648. https://docs.python.org/3/library/base64.html

**Comment by idan22moral** [comment]
Hi @DemiMarie,
This behavior is normal in 3.10, since the `strict_mode` flag was not introduced yet.
In 3.11.0 it behaves as expected:
```py
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import binascii
>>> binascii.a2b_base64(b'=aa==')
b'i'
>>> binascii.a2b_base64(b'=aa==', strict_mode=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
binascii.Error: Leading padding not allowed
>>> binascii.a2b_base64(b'aaaa=aa==')
b'i\xa6\x9ai'
>>> binascii.a2b_base64(b'aaaa=aa==', strict_mode=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
binascii.Error: Discontinuous padding not allowed
```

For further information, please read:
- https://docs.python.org/3/library/binascii.html?highlight=strict_mode#binascii.a2b_base64
- https://github.com/python/cpython/pull/24402
