### ISSUE TITLE
Replacing %-formatting with f-strings in base64 module

### ISSUE THREAD

**Issue by Nougat-Waffle** [python/cpython#94717]
A simple rewriting of some of the code to be more modern. Replacing %-formatting with f-strings. In addition change `struct.Struct('!%dI' % (len(b) // 4)).unpack(b)` to `struct.unpack(f'!{len(b) // 4}I', b)` as there is no need to use the `Struct` class.

**Comment by stevendaprano** [comment]
We don't make a habit of re-writing working code just for the sake of re-writing it. %-formatting works, and is usually faster than "more modern" formatting, so that would be code churn that makes the code worse rather than better.
