### ISSUE TITLE
[feature request] Add tagged template literals to Python

### ISSUE THREAD

**Issue by yamashita-optarc** [python/cpython#94720]
**Feature or enhancement**
Thanks for such a great language and ecosystems! And I love Python's `f-string`.
I zapped some website, Javascript has *Tagged template literals*, and it is a powerful feature.
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates
- https://wesbos.com/tagged-template-literals

**Pitch**

It has similar functionality to f-string, but allows the value to be passed through a specific function before embedding, or to be reformatted for the entire resulting string.
This functionality is also used in a javascript project called [lit](https://lit.dev/), which is achieved through tagged literals rather than jsx.

Have we ever talked about introducing tagged literals?
I would really like to use this in Python, and I would like to see this functionality used in Python.

**Previous discussion**
(I cannot found it)

**Comment by kumaraditya303** [comment]
Changes to the language are discussed on mailing lists or discourse, once there is enough interest you may open a issue. You can post this to https://discuss.python.org/c/ideas/6. Thanks!
