### ISSUE TITLE
DocTest sorts by lineno which may be int or None

### ISSUE THREAD

**Issue by Strilanc** [python/cpython#94722]
In `doctest.py` the following ordering is defined for the class `DocTest`:

```
    def __lt__(self, other):
        if not isinstance(other, DocTest):
            return NotImplemented
        return ((self.name, self.filename, self.lineno, id(self))
                <
                (other.name, other.filename, other.lineno, id(other)))
```

This is incorrect because the `lineno` field may be an integer and may be None, and comparisons between integers and None fail. Typically `lineno` is an integer, but `_find_lineno` explicitly can fall back to returning `None` so the field may be None:

```
    def _find_lineno(self, obj, source_lines):
        ...

        # We couldn't find the line number.
        return None
```

### Linked PRs
* gh-112385
* gh-112400
* gh-112401

**Comment by pochmann** [comment]
Can that happen despite equal names and equal filenames?

**Comment by Strilanc** [comment]
I'm reporting this because I actually was getting exceptions from this method. I would have included a repro but the way i was triggering it was complex enough that it really wasn't worth the time. It involved pybind, installing from sdist not wheel, machine architecture detection, patching in a `__test__` dictionary with fake entries to work around properties not being tested, and more! And I wasn't able to get the bug happening consistently outside of one specific dev environment, so even if I'd given the repro I suspected it wouldn't necessarily happen on other machines.
