### ISSUE TITLE
Accepted keys for double-starred dictionaries

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#94728]
**Documentation**

Following the discussion [here](https://discuss.python.org/t/supporting-or-not-invalid-identifiers-in-kwargs/17147/10), it should be clarified in the documentation what constraints are put on the keys of a dict being double-starred in a function call.
The implementation allows any and all str or subtypes of str : not any key of any type is accepted, but that at the same time the keys are not checked for being valid identifiers.
How much of theat should be documented as a feature, and how much as an implementation detail is still being discussed.

**Comment by Gouvernathor** [comment]
Double of #96397.

**Comment by jeff5** [comment]
Sorry I didn't spot this when opening #96393.
