### ISSUE TITLE
Python 3.11.0b4 str(enum) giving integer value and not name

### ISSUE THREAD

**Issue by jborean93** [python/cpython#94763]
**Bug report**

The `str()` method on Python 3.11.0b4 is outputting the raw integer value not the class name and label that older Python versions do.

```python
import enum

class MyEnum(enum.IntEnum):
    TEST = 1


assert str(MyEnum.TEST) == "MyEnum.TEST", f"Actual '{MyEnum.TEST}'"
```

On Python 3.10 (and older Python 3 versions) this assertion is true. On python 3.11.0b4 the str value is just `1`.

The `repr()` is the same as on older versions, just seems like `str()` is affected.

**Your environment**

- CPython versions tested on: 3.11.0b4
- Operating system and architecture:  Linux (should be N/A though)

**Comment by AlexWaygood** [comment]
I believe that this is a deliberate behaviour change from previous versions. The Steering Council specifically approved this change; see the penultimate paragraph here regarding aligning `str()` and `format()` for `IntEnum`: https://mail.python.org/archives/list/python-dev@python.org/message/RN3WCRZSTQR55DOHJTZ2KIO6CZPJPCU7/

**Comment by jborean93** [comment]
No worries, so just to confirm this is expected for pretty much any enum types and not just a string enum as mentioned in the linked issue?

**Comment by ethanfurman** [comment]
This is (now) the expected behavior for any mixed Enum/Flag defined in the enum module.  The expectation is that existing code being replaced with `IntEnum`, `StrEnum`, or `IntFlag` should have its `str()` continue to be the same as it was; if you mix your own (i.e. `MyIntEnum(int, Enum)`) then you get the original behavior of both `repr()` and `str()` being overridden.  In either case, `format()` will be the same as `str()`.

**Comment by pitrou** [comment]
@ethanfurman So what is the idiomatic way to get the member name rather than the value? In 3.10 I have:
```python
>>> fs.FileType.__mro__
(<enum 'FileType'>, <enum 'IntEnum'>, int, <enum 'Enum'>, object)
>>> str(fs.FileType.Directory)
'FileType.Directory'
>>> repr(fs.FileType.Directory)
'<FileType.Directory: 3>'
```

How do I get `'FileType.Directory'` with 3.11?

**Comment by johnthagen** [comment]
I know it was intentional, but just as a data point, the breaking changes to `format` for `MyEnum(str, Enum)` did cause some downstream breakage, such as:

- https://github.com/cjolowicz/nox-poetry/issues/941

**Comment by ethanfurman** [comment]
> How do I get `'FileType.Directory'` with 3.11?

@pitrou Either change the `__str__` for the `FileType` enum, or make a new base enum to inherit from:

``` python
class OldIntEnum(int, Enum):
    """
    use the `classname.membername` str()
    """
    pass
```

**Comment by bilderbuchi** [comment]
@ethanfurman I know this is probably water under the bridge now, but I wonder why breaking changes like this are not called out more distinctly in the What's New (e.g. by including the word "breaking")?!

We just had code using a plain `IntEnum` change behaviour on Python 3.11, and now have to work around that breaking change (probably by inheriting from (`int, Enum`) to support all current Python versions and our user's use case.
Hitting surprises like this is unpleasant, and I have to admit they somewhat undermine my trust in the versioning scheme.

Could breaking changes at least be marked/called out with "breaking" or somesuch? Then it's easier to grep the What's new when, against expectations, a minor version upgrades changes public behaviour. :-(
