### ISSUE TITLE
os.MFD_HUGE_16GB negative value caused by integer overflow

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#94774]
Reproducer:

```py
import os
print(os.MFD_HUGE_16GB)
```
Output:
```py
-2013265920
```

Compiling Python with `-fsanitize=undefined` emits runtime error:

```console
Modules/posixmodule.c:15461:9: runtime error: left shift of 34 by 26 places cannot be represented in type 'int'
-2013265920
```
Version tested: Python 3.12.0a0 (cfafd3adf8, Jul 12 2022, 11:27:54) [GCC 9.4.0] on linux

**Comment by encukou** [comment]
Hm, I just saw this as well!
I don't think we can fix this in Python, actually.

I opened a `kernel-headers` bug in Fedora, hopefully it'll get seen by a relevant person: https://bugzilla.redhat.com/show_bug.cgi?id=2106756

**Comment by kumaraditya303** [comment]
> I opened a kernel-headers bug in Fedora, hopefully it'll get seen by a relevant person:

Thanks for submitting a bug report.
I was also thinking that it was a kernel bug but couldn't believe that I found one 😅.

**Comment by kumaraditya303** [comment]
https://github.com/torvalds/linux/commit/710bb68c2e3a24512e2d2bae470960d7488e97b1
