### ISSUE TITLE
`.c` and internal non-vendored `.h` files have `#ifdef __cplusplus`

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#94795]
**Feature or enhancement**

Remove `/^\s*#ifdef __cplusplus.*?\s*#endif.*?$/gms` from all C and H files inside `Python/` and `Modules/` except vendored headers (`addrinfo.h`, `ffi*.h`, `expat/*.h`, and `mpdecimal.h`).

**Pitch**

Some C files and internal headers (that cannot be included by outside C++ code) have a guard typical for public headers:

```cpp
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

// ...

#ifdef __cplusplus
}
#endif /* __cplusplus */
```

Git blame doesn't give a definitive answer (a commit with explainer) on why it was introduced. The only two hints I found are: https://github.com/python/cpython/blob/cceac5dd06fdbaba3f45b8be159dfa79b74ff237/config.guess#L531-L536 and https://github.com/python/cpython/blob/cceac5dd06fdbaba3f45b8be159dfa79b74ff237/Python/dynamic_annotations.c#L34-L36

If the guard was introduced to treat compilers that loosely followed standards, then today's compilation with strict C11 allows to remove it.

### Linked PRs
* gh-94796

**Comment by encukou** [comment]
Why is this a problem?

**Comment by arhadthedev** [comment]
It brings confusion and doubts. For example, if a `.c` file has a C++-specific guard, it likely means some hacky compilation as C++. So to not to tease contributors with groundless questions, it's better to remove the offending parts (27 files total plus `getcompiler.c` with never used version of `COMPILER` macro).

**Comment by arhadthedev** [comment]
Closing because nobody evaluated the change as non-cosmetical.
