### ISSUE TITLE
What's new in 3.11 doesn’t mention enum improvements

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#94791]
**Documentation**

There's a number of improvements (e.g. `StrEnum`) in module `enum` in version 3.11.0b4 (see https://docs.python.org/3.11/library/enum.html#module-contents).
However, module `enum` isn’t mentioned in 3.11's _What's new_ documentation https://docs.python.org/3.11/whatsnew/3.11.html#improved-modules.
I suggest adding there to announce. Now I only stumbled upon these new `enum` features by https://github.com/python/mypy/issues/12841 of @AlexWaygood

**Comment by CAM-Gerlach** [comment]
It looks like this was solved by #95455 and [its there now](https://docs.python.org/3.12/whatsnew/3.11.html#enum), so closing this
