### ISSUE TITLE
configure: non pkg-config fallback ignores custom CFLAGS and LIBS

### ISSUE THREAD

**Issue by tiran** [python/cpython#94801]
**Bug report**

In ``configure.ac`` we have several fallbacks when pkg-config is missing or a package does not provide a ``.pc`` file. The fallbacks do not take custom cflags into account. For example the block for ``zlib`` does ``AC_CHECK_HEADERS([zlib.h])`` and ``AC_CHECK_LIB([z])`` without setting ``CFLAGS="$CFLAGS $ZLIB_CFLAGS"`` first.

**Comment by tiran** [comment]
@erlend-aasland is there anything left to do? I think we are done here.

**Comment by erlend-aasland** [comment]
AFAICS, yes. Let's close it. If another issue surfaces, we can always open a new ticket, or just reopen this.
