### ISSUE TITLE
shutil.make_archive now fails with pathlib.Path object in Python 3.11.0b4

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#94844]
**Bug report**

This code works on Python 3.10 and Python 3.11.0a5 but raises a `TypeError` in Python 3.11.0b4:

```python
from pathlib import Path
from shutil import make_archive
path = Path.cwd().resolve()
make_archive(path, 'zip', path.parent, path.name)
```

Here's the output I see in Python 3.11.0b4:

```pycon
>>> from pathlib import Path
>>> from shutil import make_archive
>>> path = Path.cwd().resolve()
>>> make_archive(path, 'zip', path.parent, path.name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trey/.pyenv/versions/3.11.0b4/lib/python3.11/shutil.py", line 1130, in make_archive
    filename = func(base_name, base_dir, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trey/.pyenv/versions/3.11.0b4/lib/python3.11/shutil.py", line 977, in _make_zipfile
    zip_filename = base_name + ".zip"
                   ~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

**Your environment**

- CPython versions tested on: Python 3.11.0b4
- Operating system and architecture: 64-bit Ubuntu Linux 20.04

**Comment by tiran** [comment]
It is most likely related to gh-74696 / GH-93160 .

**Comment by serhiy-storchaka** [comment]
It was not documented, and it only worked if `root_dir` is not None. It was not supported feature, it was a side effect of calling `abspath()` for `base_name`. Unsurprisingly, there were no tests for this.

So we now have several options:

* Do nothing. No supported feature was broken -- nothing to fix.
* Add that feature officially (with tests and documentation) in bugfix releases.
* Only fix what was broken (accept Path-like objects if root_dir is not None), but do not document it. Added tests should contain a comment that it is an implementation detail. In 3.12 we can also either remove this partial feature, or implement it completely and support officially.

**Comment by gvanrossum** [comment]
IIUC this was reverted and we're trying again for 3.12. See https://github.com/python/cpython/pull/94251 (PR) and https://github.com/python/cpython/issues/74696 (issue).

Shall we close this as fixed? (I don't actually see the commits that reverted this -- how to find those?)

**Comment by merwok** [comment]
Don’t see any revert in file history: https://github.com/python/cpython/commits/3.11/Lib/shutil.py

**Comment by gvanrossum** [comment]
Yeah, I think I misunderstood (or confused this with another, unrelated issue).

It looks like this was fixed by GH-94846.

**Comment by serhiy-storchaka** [comment]
#94846 only restored the old behavior which was an implementation artifact -- undocumented and not consistent. Path-like object as `base_name` is only accepted if `root_dir` is not None.

If we want to make it an official feature, we should document it, cover by tests, and make it working for `root_dir=None`. Otherwise we can broke it and revert #94846 for 3.12.

**Comment by gvanrossum** [comment]
Then let's do the latter -- make it work for more cases, document it (lightly), and test it (briefly). And it's worth a new issue.
