### ISSUE TITLE
Help latest MSVC 1932 (v143, VS2022) to optimize PyObject_Free()

### ISSUE THREAD

**Issue by neonene** [python/cpython#94841]
There is a report that python.org `3.11` Windows release has slowed down on micro benchmarks:

https://github.com/faster-cpython/ideas/issues/420

One reason is that `PyObject_Free()` is not well optimized by the latest MSVC (ver.1932 in v143 tool set), which is likely to be used for the next `3.10` official as well.

This issue has been reported to the MSVC team. However, their tools would not be fixed urgently.

### Linked PRs
* gh-104409
* gh-104439

**Comment by gvanrossum** [comment]
Thank you so much for this one-line fix giving 20% perf improvement (in some cases)!
