### ISSUE TITLE
Rewrite modules with C

### ISSUE THREAD

**Issue by hpytree** [python/cpython#94855]
Maybe rewriting some standard modules that written by python with c can make cpython faster.

**Comment by zware** [comment]
Several modules already have a C accelerator, including most of those where it would provide a significant benefit.  As a general suggestion this is already a well-known route for performance increases; if you have a specific suggestion for a module that would greatly benefit from a C version and can demonstrate that benefit, please open a targeted issue (preferably with a pull request ;) ).
