### ISSUE TITLE
Hope to increase the visible properties of members in the class: public, private, protected (for subclasses). 

### ISSUE THREAD

**Issue by goophps** [python/cpython#94865]
**Feature or enhancement**

1 Hope to increase the visible properties of members in the class: public, private, protected (for subclasses). 
2 Because if you want to change the visibility after the code that has been written is widely called, you have to change the names of all places to start with an underscore, which is very unreasonable.
3 In order to support object-oriented programming more friendly.

**Pitch**

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

**Previous discussion**

**Comment by JelleZijlstra** [comment]
I'm not entirely sure what you're proposing, but this sounds like it's out of scope for the tracker. If you have a proposal for adding something to the language, please bring it up at discuss.python.org.

**Comment by goophps** [comment]
> 我不完全确定您的建议是什么，但这听起来超出了跟踪器的范围。如果您有关于向该语言添加内容的建议，请在 Discussion.python.org 上提出。

Discussion.python.org
This domain name cannot be opened.

> I'm not entirely sure what you're proposing, but this sounds like it's out of scope for the tracker. If you have a proposal for adding something to the language, please bring it up at discuss.python.org.

Discussion.python.org
This domain name cannot be opened.

**Comment by ericvsmith** [comment]
It’s discuss.python.org, not discussion.python.org.
