### ISSUE TITLE
Wrong example in stdlib tutorial about `sys.args`

### ISSUE THREAD

**Issue by marco-buttu** [python/cpython#94878]
That is the text and code example of the [stdlib tutorial](https://docs.python.org/3/tutorial/stdlib.html#command-line-arguments):

> For instance the following output results from running `python demo.py one two three` at the command line:
> 
> ```
> >>> import sys
> >>> print(sys.argv)
> ['demo.py', 'one', 'two', 'three']
> ```

The previous example is actually wrong. It should be something like this:

> For instance, let's take the following `demo.py` file:
>
> ```
> # File demo.py
> import sys
> print(sys.argv)
> ```
> 
> Here is the output from running `python demo.py one two three` at the command line:
> 
> ```
> ['demo.py', 'one', 'two', 'three']
> ```

**Comment by hugovk** [comment]
Makes sense, would you like to create a PR?

**Comment by marco-buttu** [comment]
@hugovk yes, of course.
