### ISSUE TITLE
Replace unused iteration variable "i" with "_" in heapsort example

### ISSUE THREAD

**Issue by aless10** [python/cpython#94888]
**Documentation**

The example In the docs of the usage of the heapq module, we use an iteration variable `i` which is not used. Could we use `_` instead?
<img width="499" alt="Schermata 2022-07-15 alle 22 30 24" src="https://user-images.githubusercontent.com/19170381/179309200-929c82bc-2ea4-4c08-8b81-392508d0f26c.png">

**Comment by ericvsmith** [comment]
I don't think it would make the example clearer.

**Comment by stevendaprano** [comment]
We should not encourage people to use `_` as the loop variable, that is harmful in the interactive interpreter where it can shadow the builtin `_` special variable. I don't think changing this would make the example any clearer, its just a trivial cosmetic change.

**Comment by rhettinger** [comment]
Let's leave this as-is.  The ``for i in range(n)`` idiom is deeply ingrained and well-understood.
