### ISSUE TITLE
library/re.html: Definition of the behavior of character groups [] is incorrect.

### ISSUE THREAD

**Issue by fischbacher** [python/cpython#94898]
**Documentation**

A general point here is that regular expressions are extremely information-dense ways to define Chomsky type 3 grammars.
As such, it matters that the definition is precise.

Currently, https://docs.python.org/3/library/re.html says:

"If the first character of the set is '^', all the characters that are not in the set will be matched."

Now, "If the first character of the set is '^'", this implies that the character '^' is part in the set (welcome to the tautology club).
So, according to this specification, such a character group could never match a '^'.

This is of course in conflict with how everybody proficient with regexps understands how this works.

Commonly, the behavior below would be understood as "the universally expected correct behavior that is good to rely on":

 >>> re.match('[^a]', '^')
 <re.Match object; span=(0, 1), match='^'>

A correct statement would be:

If a character set definition starts with a '^', then it matches any character that is not matched by the character set definition obtained by stripping the leading '^' and subsequently escaping the then leading character, should it happen to be a '^' (so, [^^] matches any character except the 'caret' symbol).

**Comment by hauntsaninja** [comment]
I think the examples make behaviour here clear; there is an example with and without a caret.

https://devguide.python.org/documentation/style-guide/#economy-of-expression applies here. The Python docs are meant for humans, not lawyers ;-)

So I'm inclined to close this. But maybe there's some less verbose phrasing that satisfies you? Perhaps
```diff
- If the first character of the set is '^', all the characters that are not in the set will be matched.
+ If the first character of the set is '^', all the characters that are not in the set will be matched (ignoring the first '^').
```

**Comment by mrabarnett** [comment]
If you're going to be pedantic, doesn't a character set definition start with a '['? If you want a formal definition, then you're probably better off with something like a context-free grammar, as in Python's grammar rules.

**Comment by Otimeyin123** [comment]
Hello, does anyone know anything about human behavior recognition I have a project on nurse care activity recognition

**Comment by fischbacher** [comment]
Two comments:

1. The level of rigor exemplified by the Python documentation has a lot of influence on Python authors. If the reference documentation is loose and imprecise, many Python authors will use similar style in their own code. This is a problem.

2. Comparing the quality of Python's reference documentation with other documentation that has been around for quite a while, the general impression is that other specs generally manage to be much more precise without being less readable.

Let us specifically look at how it's worded in the section-7 "regex" manpage: https://man7.org/linux/man-pages/man7/regex.7.html

       A bracket expression is a list of characters enclosed in "[]".
       It normally matches any single character from the list (but see
       below).  If the list begins with '^', it matches any single
       character (but see below) not from the rest of the list.  If two
       characters in the list are separated by '-', this is shorthand
       for the full range of characters between those two (inclusive) in
       the collating sequence, for example, "[0-9]" in ASCII matches any
       decimal digit.  (...)
