### ISSUE TITLE
Adding a context manager to contextlib

### ISSUE THREAD

**Issue by Nougat-Waffle** [python/cpython#94933]
Adding a context manager to `contextlib`.

A common pattern in Python code is to catch an `exception` and then raise a custom `exception` from it.

For example:
```python
try:
    function()
except SomeError as e:
    raise CustomException('Error message') from e
```

Consider the following snippet as an example:
```python
def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError as e:
        raise CalculatorError('Can not divide by zero') from e
```

We can replace the example code with the more idiomatic:
```python
def divide(a, b):
    with NewContextManager(CalculatorError('Can not divide by zero'), ZeroDivisionError):
        return a / b
```

If this code happens to throw a `ZeroDivisionError` then in `NewContextManager`'s `__exit__` function the `CalculatorError` passed to the context manager would be raised `from ZeroDivisionError`.

The proposed method signature of `NewContextManager`'s `__init__` function is:
```python
def __init__(to_raise, *exceptions):
    pass
```
`to_raise`: The exception object to raise from.
`*exceptions`: All exceptions which should be caught and raised from, similar to `contextlib.suppress`

In general this can be implement in a way similar to `contextlib.suppress`.

Notes:

1. I am unsure what would be a good name for this context manager, I considered the names `ReRaise` or `RaiseFrom`, however I think a better name can be found.
2. Creating the exception and passing it to the context manager might be wasteful in case no exception is actually thrown, so any ideas for a better method API are appreciated.

In addition I'm not sure if this feature is welcome or not, Would appreciate any feedback regarding if this feature is desired at all or any improvement suggestions with regard to the implementation.

If this does happen to be a welcome feature I'd be glad to implement it.

**Comment by arhadthedev** [comment]
> I am unsure what would be a good name for this context manager

Something like `with ReplaceRaisedExceptionWith(...)`?

**Comment by rhettinger** [comment]
I thought about proposing this long ago but decided against it. This pattern is common, but I think the solution is worse than the code it replaces.   

The try/except is very clear about what is caught and what is raised.  Using ``raise`` allows easy customization of the message, allows a straightforward choice of adding ``from None``, and allows data to be extracted from the caught exception for forwarding in the new exception.

Also, the cost model is different.  With try/except form, there is almost zero cost for the code path where an exception isn't raised.  In the context manager form, we pay most of the cost up front for both code paths.  The up front costs include looking up both exceptions in globals, in formatting a message, and instantiating the context manager.
