### ISSUE TITLE
ast.parse allows parenthesised context managers with old feature_version

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#94949]
The following should raise SyntaxError:
```
ast.parse('with (CtxManager() as example): ...', feature_version=(3, 9))
```

**Comment by pablogsal** [comment]
Thanks for the issue @hauntsaninja 

Although we made it official in 3.10, it works on 3.9. Tools supporting 3.9 don't need to support this, but I don't see the advantage in marking it as invalid and being that strict, specially since 3.9 is now in security fixes only

**Comment by hauntsaninja** [comment]
Thanks, updated the PR to check 3.9 instead of 3.10
