### ISSUE TITLE
Del command is not working as expected

### ISSUE THREAD

**Issue by ganeshnayak619** [python/cpython#94944]
Del command is removing key value combination from all dictionaries even if the ask is to remove from only one dictionaries.

Below is the piece of code --

payload={"topic": "account", "value" : { "eventBody": {"status": "A", "api": {"error":"404"}}}}
a=payload["value"]
b=payload["value"]
del a["eventBody"]["api"]
print(a,b)

api key and value combination is gone from both dictionary instead of removing it from only a

**Comment by stevendaprano** [comment]
`a` and `b` are not two different dicts, they are different names for the same dict. Of you print `payload`, you will see that the dict inside it has also been modified, for the same reason.

This is not a bug in Python, it is fundamental to the way Python operates on objects.
