### ISSUE TITLE
round -245162.5 fail

### ISSUE THREAD

**Issue by 466867517** [python/cpython#94946]
When I use Decimal(-245162.5).quantize(Decimal('0')) to round -245162.5 . The result is -245162 but not -245163. My python version is 3.8

**Comment by rhettinger** [comment]
The result is due to default rounding mode is ROUND_HALF_EVEN.

To get the result you want, try ROUND_HALF_UP:


```
>>> getcontext().rounding = ROUND_HALF_UP
>>> Decimal(-245162.5).quantize(Decimal('0'))
Decimal('-245163')

```
