### ISSUE TITLE
Continue statement never reached in debugger

### ISSUE THREAD

**Issue by schlatterbeck** [python/cpython#94974]
In the attached code the debugger never stops at the continue statement when I set a breakpoint there in pdb. With a pytest the continue statement is reported as not covered by the tests. When I uncomment the assignment statement, stopping at the continue in the debugger works and the continue statement is then reported as covered by the tests. When running the program the print statement after the continue is never reached (as you can verify yourself), so the continue statement *is* reached.
```
#!/usr/bin/python3
  
def t():
    a = [[1, 2], [2, 3]]
    b = [1, 2]

    j  = 0
    p1 = j + 1

    for i in range(2):
        if  (   a [p1][0] !=  a [j][0]
            and (   a [p1][0] != -a [j][0]
                 or b [0] + b [1] != 0
                )
            ):
            #xyzzy = 42
            continue
        print ('here i am')

if __name__ == '__main__':
    t()
```

Python 3.9.2 on Debian Bullseye.

**Comment by Fidget-Spinner** [comment]
Python 3.9 no longer accepts bugfixes. Could you please test on 3.10? Also please provide more details:
- Which debugger are you using?
- What operating system are you using?

**Comment by schlatterbeck** [comment]
- Which debugger: As stated I'm using the built-in pdb like so:
```
python3 -m pdb t.py
break 17
c
```
- Operating System: Linux Debian codename bullseye (also stated in the first msg)

For the record with python3.9 I'm getting:
```
(Pdb) break 17
Breakpoint 1 at /home/ralf/.../t.py:17
(Pdb) c
The program finished and will be restarted
> /home/ralf/checkout/own/projects/pymininec/t.py(3)<module>()
-> def t():
```

I've installed Python3.10 and tried on both Linux Debian Bullseye and Windows. The bug is not reproduceable there (it correctly stops on the continue statement). So I guess we can close this issue.

**Comment by Fidget-Spinner** [comment]
> * Which debugger: As stated I'm using the built-in pdb like so:

Woops sorry. Thanks for testing on 3.10!
