### ISSUE TITLE
BSD version of ctypes.util.find_library

### ISSUE THREAD

**Issue by josuah** [python/cpython#94983]
**Bug report**

#44314 improves the support for find_library() under BSD systems.
Although, find_library() returns a filename instead of a full path, unlike the comment stated at the top of the implementation:

> find_library(name) returns the pathname of a library, or None.

```
% python
Python 3.9.13 (main, May 26 2022, 16:26:43)
[Clang 13.0.0 ] on openbsd7
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('python3.9')
'libpython3.9.so.0.0'
>>>
```

**Your environment**

- CPython versions tested on: % `Python 3.9.13`
- Operating system and architecture: `OpenBSD lap1.josuah.net 7.1 GENERIC.MP#3 amd64`

**Comment by aisk** [comment]
Hi, `find_library` on Linux has the same behavior, which also returns the filename instead of the full path as the [document](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries) shows:

```
>>> from ctypes.util import find_library
>>> find_library("m")
'libm.so.6'
>>> find_library("c")
'libc.so.6'
>>> find_library("bz2")
'libbz2.so.1.0'
```

So I think `pathname` just means filename, whether it's a full name or not.

**Comment by josuah** [comment]
Thank you for confirming this. I can reproduce, so the bug I encountered might be rooting from somewhere else.
I think this can be closed then. Sorry for overlooking this, and thank you for testing!
