### ISSUE TITLE
Make 3.10 sqlite3 tests run

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#94998]
On my Windows 10, after fresh repository update and debug build, 3.10 sqlite3 tests do not run.
(3.11 and 3.12 are fine.)  In 3.10, `test_sqlite/` only contains `test_dbapi.py`

`python -m test test_sqlite3` is OK after no tests run.  (I though we made this an error.)
`python -m test.test_sqlite3` fails because test_sqlite3/ is missing `__main__.py`, as well as `__init__.py`

In 3.11, `test_sqlite3.__main__.py` is
```
from test.test_sqlite3 import load_tests  # Needed for the "load tests" protocol.
import unittest

if __name__ == "__main__":
    unittest.main()
```
The comment seems not needed.  The other 3.10 test.test_x directories all run and have variations of this.  Some have `from . import load_tests`.  Some have `unittest.main('test.test_x')` instead of a load_tests import.  Most omit the redundant if-clause.

After adding `__main__.py`, tests still do not run because `__init__.py` is needed.  I may try to do a PR tomorrow.

**Comment by terryjreedy** [comment]
I copied 3.11 `test_sqlite3/__init__.py` into the 3.10 directory.
With `python -m test -v test_sqlite3`, the loader runs but fails on line 47
`def cx_limit(cx, category=sqlite.SQLITE_LIMIT_SQL_LENGTH, limit=128):`
with an attribute error for SQLITE_LIMIT_SQL_LENGTH.

With the function commented out, python crashes with `Windows fatal exception: access violation` in test_connection_bad_reinit at line 572 , `self.assertRaisesRegex(...)`  line 572.  Before that, multiple tests failed, far more than need the commented out function.

**Comment by erlend-aasland** [comment]
> On my Windows 10, after fresh repository update and debug build, 3.10 sqlite3 tests do not run. (3.11 and 3.12 are fine.) In 3.10, `test_sqlite/` only contains `test_dbapi.py`

There is no `Lib/test/test_sqlite/` directory in the 3.10 branch. However, due to a backport failure (2229d34a6ef9c03e476882f46bba4d7c83552d1e), there is a partial `Lib/test/test_sqlite3/` directory. This needs to be removed from the 3.10 branch; the sqlite3 tests are found in `Lib/sqlite3/test/` for the 3.10 branch and older.

> In 3.11, `test_sqlite3.__main__.py` is [...]
 
> The comment seems not needed.

It was added by Brett's request. I'd like to keep it there, as it explains the otherwise apparently unused import.

> Most omit the redundant if-clause.

Tests can be run directly (`./<test-path>` on \*nix) or via `./python -m test <test-name>`, so please leave it as it is; it is needed.

**Comment by erlend-aasland** [comment]
FTR, sqlite3 tests run as they should in 3.10:

```console
$ ./python.exe -m test test_sqlite -v | wc -l 
     369
```

**Comment by erlend-aasland** [comment]
Sorry, this may not be obvious, but the sqlite3 tests were moved in 3.11. For 3.10 and older, they all lived in `Lib/sqlite3/test`, and were invoked via `Lib/test/test_sqlite.py` (for example, `python -m test test_sqlite`). For 3.11, they live in `Lib/test/test_sqlite3/`, and they are now invoked using the correct module name (`python -m test test_sqlite3`).

**Comment by erlend-aasland** [comment]
Fixed with gh-95016

**Comment by terryjreedy** [comment]
I wondered whether deleting test_sqlite3/ might be a reasonable alternative.  But was not aware that it was a partial duplicate.

The purpose of conditionalizing unittest.main() in x.py is to not call it when x is imported.  But  __main__.py is normally only run with `__name__`  `'__main__'`, when the call is wanted.  `python -m test test_xyz'  only *imports* test_xyz and when it is a directory, only runs its `__init__`, not `__main__`.   This is why the current omission in most such 3.10 `__main__`s is not a problem.  (But I have no intention of changing anything.)

I think all the test directory movements should be mentioned in the corresponding What's New.

**Comment by erlend-aasland** [comment]
Yeah, I think you're right about the `__main__` conditional; it is redundant.
