### ISSUE TITLE
Argument Clinic does not increase NoneType refcount when returning NoneType from a function with no parameters

### ISSUE THREAD

**Issue by noamcohen97** [python/cpython#95007]
**Bug report**

```python
/*[clinic input]
function -> NoneType
[clinic start generated code]*/
```

will produce this function:
```c
static PyObject *
function(PyObject *module, PyObject *Py_UNUSED(ignored))
{
    return function_impl(module);
}
```

while `function_impl` returns `Py_None` (as it should, if using NoneType return converter), refcount is not increased.

here is a working example of NoneType return converter:
```python
/*[clinic input]
function -> NoneType

    a: int
    /
[clinic start generated code]*/
```
```c
static PyObject *
function(PyObject *module, PyObject *arg)
{
    PyObject *return_value = NULL;
    int a;
    PyObject *_return_value;

    a = _PyLong_AsInt(arg);
    if (a == -1 && PyErr_Occurred()) {
        goto exit;
    }
    _return_value = function_impl(module, a);
    if (_return_value != Py_None) {
        goto exit;
    }
    return_value = Py_None;
    Py_INCREF(Py_None);

exit:
    return return_value;
}
```

Generation also fails when generating a function with a single `object` parameter.

It seems like the problem is with `default_return_converter` in clinic.py, being set to `True`

**Comment by serhiy-storchaka** [comment]
Good catch. This converter is not used, so the bug was not exposed. And since it has dubious semantic (requires returning a weak reference to None on success), I think that it is better to remove it.

**Comment by noamcohen97** [comment]
How about we'll get rid of the callback return value, and use `PyErr_Occurred()` to chose whether to return `NULL` or `Py_None`?

**Comment by arhadthedev** [comment]
> How about we'll get rid of the callback return value, and use `PyErr_Occurred()` to chose whether to return `NULL` or `Py_None`?

When I did the same in gh-91284, I found that `PyErr_Occurred` takes GIL. Currently (until nogil is implemented, at least) it's cheaper to do this only on `NULL` returned from a callback.
