### ISSUE TITLE
test_asyncio's `GenericWatcherTests.test_create_subprocess_fails_with_inactive_watcher` is not run

### ISSUE THREAD

**Issue by graingert** [python/cpython#95010]
**Bug report**
GenericWatcherTests does not inherit from TestCase, and so doesn't get run

**Comment by Akuli** [comment]
There seems to be quite a few classes like this:

```
$ git grep 'class .*Tests:' Lib/test/ | wc -l
94
```

**Comment by graingert** [comment]
> There seems to be quite a few classes like this:
> 
> ```
> $ git grep 'class .*Tests:' Lib/test/ | wc -l
> 94
> ```

I think some of those are supposed to be Mixins, but perhaps they should be re-named `*Mixin:` instead of `*Tests:`

**Comment by kumaraditya303** [comment]
@graingert Is this fixed now? if not can you create a separate PR to just fix this ?

**Comment by graingert** [comment]
I was going to backport it to 3.10 but the change ended up too controversial
