### ISSUE TITLE
syslog issues

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#95041]
There are several issues with corner cases in `syslog.openlog()`.

* `syslog_get_argv()` swallows exceptions, but not in all cases.
* if `ident` is non UTF-8 encodable, `syslog.openlog()` fails after setting the global reference to `ident`. Now the C string saved internally in the previous call to `openlog()` points to the freed memory.
* `PySys_Audit()` can crash if `ident` is NULL.
* There may be a race condition with `syslog.syslog()`, because the global reference to `ident` is decrefed before setting the new value.

And, since `syslog.syslog()` releases the GIL, there may be a race condition `syslog.syslog()` with `syslog.openlog()` and `syslog.closelog()` which can decref the global reference to `ident`.

P.S. @noamcohen97 noticed yet one issue in `syslog.syslog()` (potential returning a value from a function while an exception is set https://github.com/python/cpython/pull/95012#discussion_r929558676) and fixed it.

**Comment by arhadthedev** [comment]
GitHyb docs on Actions [describes](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#example) this scenario using an example:

> [code snippet]
>
> Due to path filtering, a pull request that only changes a file in the root of the repository will not trigger this workflow and is blocked from merging.
>
> You can fix this by creating a generic workflow, with the same name, that will return true in any case similar to the workflow below:
>
> [code snippet]
>
> Now the checks will always pass whenever someone sends a pull request that doesn't change the files listed under paths in the first workflow.

I hope it's applicable here.

**Comment by serhiy-storchaka** [comment]
Sorry, I don't understand how this applies to this issue. Could you please explain?

**Comment by arhadthedev** [comment]
My apologises, I commented into a wrong tab (and hoped I was fast enough to revert stuff by deletion).

**Comment by erlend-aasland** [comment]
I'm keeping this open until you decide about the NEWS entry, Serhiy. I'll mark it pending close, though.

**Comment by erlend-aasland** [comment]
Fixed by:

- #95058 
- #95261 
- #95262 
- #95264 
- #95275 
- #95277

**Comment by erlend-aasland** [comment]
(Ooops, sorry; pressed the wrong button)

**Comment by hauntsaninja** [comment]
We kept this open based on https://github.com/python/cpython/pull/95264#issuecomment-1195168543

It looks like Serhiy added the tests in https://github.com/python/cpython/pull/97953 but chose not to add a changelog entry, so I think we can close this out.
