### ISSUE TITLE
test_embed failing on 3.12

### ISSUE THREAD

**Issue by MaxwellDupre** [python/cpython#95048]
test_embed produces:

FAIL: test_no_memleak (test.test_embed.MiscTests.test_no_memleak) (frozen_modules='off', stmt='pass')

Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/Lib/test/test_embed.py", line 1763, in test_no_memleak
    self.assertEqual(refs, 0, out)
AssertionError: -1 != 0 : [-1 refs, 0 blocks]

FAIL: test_no_memleak (test.test_embed.MiscTests.test_no_memleak) (frozen_modules='on', stmt='pass')

Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/Lib/test/test_embed.py", line 1763, in test_no_memleak
    self.assertEqual(refs, 0, out)
AssertionError: -1 != 0 : [-1 refs, 0 blocks]

FAIL: test_no_memleak (test.test_embed.MiscTests.test_no_memleak) (frozen_modules='off', stmt='import __hello__')

Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/Lib/test/test_embed.py", line 1763, in test_no_memleak
    self.assertEqual(refs, 0, out)
AssertionError: -1 != 0 : [-1 refs, 0 blocks]

FAIL: test_no_memleak (test.test_embed.MiscTests.test_no_memleak) (frozen_modules='on', stmt='import __hello__')

Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/Lib/test/test_embed.py", line 1763, in test_no_memleak
    self.assertEqual(refs, 0, out)
AssertionError: -1 != 0 : [-1 refs, 0 blocks]

FAILED (failures=4, skipped=3)

Also:
./python -I -X showrefcount -c pass
[-1 refs, 0 blocks]

Searched for leak with git bisect and produced:
ad56919c5ed54523f866e6605a2573ab7b7d5235 is the first bad commit
commit ad56919c5ed54523f866e6605a2573ab7b7d5235
Author: Victor Stinner <vstinner@python.org>
Date:   Sun Feb 27 00:28:24 2022 +0100

    bpo-46857: Fix refleak in OSError INIT_ALIAS() (GH-31594)
    
    _Py_GetRefTotal() no longer decrements _PySet_Dummy refcount.

 Lib/test/test_embed.py |  8 ++------
 Objects/exceptions.c   | 10 ++++------
 Objects/object.c       |  7 +------
 3 files changed, 7 insertions(+), 18 deletions(-)

CPython versions tested on: latest 3.12
Operating system and architecture: fedora 5.18.11-200.fc36.x86_64

**Comment by kumaraditya303** [comment]
This was fixed by 1834133e66d95a143c9df5f068b3109927aefd65, you may try any commit newer than that and reproduce.

**Comment by MaxwellDupre** [comment]
Yes tested now ok.
