### ISSUE TITLE
In terms of immutable classes, such as int__ new__ () does the definition of function stipulate that only 2 parameters can be accepted?

### ISSUE THREAD

**Issue by Schira4396** [python/cpython#95050]
As shown in the figure, when inheriting the int class, override__ new__ () method. When extra parameters are added, an error will be reported
![image](https://user-images.githubusercontent.com/57404930/179961700-4c7bbddf-199f-49f0-93ab-ee13e3063f37.png)

![image](https://user-images.githubusercontent.com/57404930/179961421-5ce1847d-9ea7-486f-b84d-33b668729355.png)
Why?
I know this is a call to int__ new__ (), except int__ new__ () it's stipulated like this, otherwise it can't convince me
If not, can you give an explanation? be deeply grateful

**Comment by ronaldoussoren** [comment]
From the documentation of ``int``:

```
class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
```

Because ``int`` is an immutable type this interface is implemented in the ``__new__`` method, which accepts one or two arguments (other than the class/self argument).

BTW. This is not a support forum, it is better to ask questions like this on discuss.python.org.

**Comment by Schira4396** [comment]
> From the documentation of `int`:
> 
> ```
> class int(object)
>  |  int([x]) -> integer
>  |  int(x, base=10) -> integer
> ```
> 
> Because `int` is an immutable type this interface is implemented in the `__new__` method, which accepts one or two arguments (other than the class/self argument).
> 
> BTW. This is not a support forum, it is better to ask questions like this on discuss.python.org.

thanks
