### ISSUE TITLE
Code objects with nan constants should be equal

### ISSUE THREAD

**Issue by saulshanabrook** [python/cpython#95057]
**Bug report**

Currently, two code objects which are identical but have `nan`s as constants are not considered equal. For example:

```python
>>> code = 'print(1e1000 * 0)'
>>> compile(code, '', 'exec').co_consts
(nan, None)
>>> compile(code, '', 'exec') == compile(code, '', 'exec')
False
```

My expectation is that they should be. The code object already overrides equality to make sure that code with constants like `-0.0` are not equal to `0.0`, even though they are equal as standalone objects. 

My hunch is that this could be changed by modifying `_PyCode_ConstantKey` which is used in equality in the code object and is what differentiates the negative and positive floats.

One idea would be to have the `_PyCode_ConstantKey` replace all `nan`s with a constant global identical nan. Then the code objects would compare `=` based on object identity.

**Your environment**

- CPython versions tested on: main, 3.10, 3.7
- Operating system and architecture: macOS 12.4

**Comment by saulshanabrook** [comment]
I am [working on a library that provides an isomorphic data structure representation of Python's code objects](https://github.com/metadsl/python-code-data), for easier downstream analysis and was trying to match Python's built in equality semantics.

I was unsure if it was intended that two code objects are not equal if they contain `nan`s, but my sense was that isn't intended since the other equality code for code objects do not conform to Python's equality, but instead try to give some sense of "is this code equivalent semantically?". i.e. even though `1 == True`, replacing all instances of `1` within your code with `True` will give different semantics. So I was trying to apply that same logic to `nan`s. 

On a practical level, since the compiler uses this equality to create the `co_consts` list, if you have a code object with multiple `nan` literals in it, they will all create duplicate values, instead of referencing the same `nan` in `co_consts`.  So if this was fixed in `_PyCode_ConstantKey`, it would also reduce this duplication, resulting in smaller code objects, which would potentially save memory and time.

```python
>>> compile(print(1e1000 * 0, 1e1000 * 0), '', 'exec').co_consts
(nan, nan, None)
```

**Comment by mdickinson** [comment]
> it would also reduce this duplication, resulting in smaller code objects, which would potentially save memory and time

I'd hope that code that's using tricks like `1e1000 * 0` to create nans is rare, in which case we wouldn't expect to see much benefit from this in real code. (The recommended way to get hold of a NaN in pure Python code is to use `math.nan` or `float("nan")`, both of which would avoid the problem of nans in `co_consts` altogether.)

**Comment by saulshanabrook** [comment]
@mdickinson I agree, I don't know of a real-world use case where this is a performance case to be made here. My main question is around semantics and the performance gain would be ancillary to that.

**Comment by saulshanabrook** [comment]
Yeah if the compiler avoided ever producing `nan` constants, then this issue would be a moot point.

That seemed like a more invasive change to me than just handling `nan` constants are compared, with the potential for performance degradations, but it would definitely resolve it.

**Comment by mdickinson** [comment]
> One idea would be to have the _PyCode_ConstantKey replace all nans with a constant global identical nan.

So a technical issue with this is that it's hard to guarantee that all nans are interchangeable in practice: we'd be relying on the operating system and CPU for that guarantee. It's conceivable that different NaN-producing expressions (e.g., `1e1000 * 0.0`, `-1e1000 * 0.0`, `1e1000 / 1e1000`) could produce NaNs with different signs or payloads. I don't _think_ that happens on any current popular architectures, and it seems likely that few people are relying on the signs or payloads of NaNs, but there are no guarantees here.

**Comment by saulshanabrook** [comment]
@mdickinson Oh this is my first time looking into `nan` representations, I didn't realize they can have signs or payloads!

Does it ever make sense to compare these parts of a nan to see if two nans are equivalent nans?

**Comment by rhettinger** [comment]
I recommend closing this as "not worth it". The use case is rare and the code is arguably correct as is.

NaNs are a weird case that undermines basic reflexivity rules assumed in many parts of the language. It would be a mistake to propagate knowledge of the NaN special case to anything beyond the realm of the math module — that would be the tail wagging the dog.
