### ISSUE TITLE
PyCode_Addr2Location bogus assert(?) or invalid branch?

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#95060]
In https://github.com/python/cpython/blob/main/Objects/codeobject.c#L971-L975, ``addrq < 0`` is a condition but the assert following the branch fails when ``addrq < 0``. This causes mypyc to segfault on 3.11 debug.

**Comment by Fidget-Spinner** [comment]
I think the branch is supposed to return `0` or `1`. (Not sure which).

**Comment by markshannon** [comment]
There are no tests for `PyCode_Addr2Location` and it is undocumented. :shrug: 

Returning 0 with an exception if `addrq < 0` seems the better API, but at this stage in 3.11, returning 1 for success seems safer.

**Comment by markshannon** [comment]
Returning 1 seems consistent with the original implementation for https://github.com/python/cpython/issues/88116, so let's go with that.
