### ISSUE TITLE
ast.parse() abuses assert for error checking

### ISSUE THREAD

**Issue by jwilk** [python/cpython#95066]
**Bug report**

`ast.parse()` uses the assert statement to validate the `feature_version` argument:

```console
$ python3 -c 'import ast; ast.parse("print", feature_version=(2, 7))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jwilk/.local/lib/python3.11/ast.py", line 45, in parse
    assert major == 3
AssertionError
```

This is bad because the check will go away if you enable optimizations:

```console
$ python3 -O -c 'import ast; ast.parse("print", feature_version=(2, 7))' && echo yay
yay
```

**Your environment**

Python 3.11.0b4

**Comment by ambv** [comment]
Fixed with https://github.com/python/cpython/pull/95072. Thanks for the report, @jwilk! ✨ 🍰 ✨
