### ISSUE TITLE
Dataclass __post_init__ with InitVars (function arguments are redundant and only confuse the user)

### ISSUE THREAD

**Issue by oscar-LT** [python/cpython#95070]
Recently encountered the issue where I had the two `InitVars` declared in a `@dataclass` but then passed them into the `__post_init__` function in the reverse order to their declaration. This caused them to be wrongfully assigned to the other value as `__post_init__`'s argument's are positionally dictated (which should be documented more clearly to the user first of all).

e.g.

```python
from dataclasses import dataclass, InitVar

@dataclass
class Fruit:
    price : int = None
    demand : InitVar[float] = 1.0
    supply : InitVar[float] = 2.0

    # def __post_init__ (self, supply, demand):        <--- Arguments passed in wrong order
    def __post_init__ (self, demand, supply):
        self.price = demand / supply
        # self.price = self.demand / self.supply.           <--- This would also work and we wouldn't encounter unexpected confusion
```

The expected default price above would be `1.0 / 2.0 = 0.5`, but if the arguments are passed in the wrong order, it would be `2.0 / 1.0 = 2.0`. However, we could also set the price using the `self.demand` and `self.supply`, which would circumvent this confusion altogether.

One could try and argue, but what about if you set supply/demand to `init = False` -  what then? They won't be accessible from `self.demand` or `self.supply` in `__post_init__`!! But actually, you can not at all use `init = False` on an InitVar! If you try, it just won't work. You'll get a runtime error complaining about passing an unknown variable to `__post_init__`. 

In code:

```python
from dataclasses import dataclass, InitVar, field

@dataclass
class Fruit:
    price : int = None
    demand : InitVar[float] = field(init=False, default=1.0)
    supply : InitVar[float] = field(init=False, default=2.0)

    def __post_init__ (self, demand, supply):     #  <--- Can not work as both demand and supply are undefined when this is called
        self.price = demand / supply
```

The only use-case I can see for requiring the InitVars to be passed as arguments is if you are using `kw_only=True` as the passed value will differ from the `self` value (I don't fully understand why), but this would imply some really odd behavior...

**Anyway, all this to say this functionality is a bit confusing and I feel like it could be simplified a bit. E.g. do we really need the InitVars passed as arguments to `__post_init__` or wouldn't it be sufficient to to just access them with `self` - especially as it looks like they cannot be `init=False` anyway (so should always be available through `self`)**

**Comment by ericvsmith** [comment]
The entire point of InitVars is to not have them be instance attributes. If you want them as instance attributes, don’t use InitVar. 

It was probably a mistake to make parameters to `__post_init__` be positional, but that ship has sailed. Somewhere there’s an issue discussing that.

**Comment by oscar-LT** [comment]
@ericvsmith I'm testing this on `3.9.5` so maybe this has been sorted out on later version, but taking your example code
```python
>>> @dataclass
... class Fruit:
...     price : int = None
...     demand : InitVar[float] = 1.0
...     supply : InitVar[float] = 2.0
...
>>> Fruit.demand
1.0
>>> Fruit.supply
2.0
```

The following still works:
```python
>>> apple = Fruit()
>>> apple.demand
1.0
>>> apple.supply
2.0
>>> apple.demand = 3.0
>>> apple.demand
3.0
```

so by default, just indicating `InitVar` doesn't remove either `supply` or `demand` as attributes of the `apple` object that is an instance of `Fruit`. It does remove them from the representation of `apple`, in that
```python
>>> print(apple)
Fruit(price=None)
```
but you can still access/modify their values

So that's why I bring up the point of "if you set them to `field(init=False, default=1.0)`" - where you're explicitly not initializing them through `__init__` so that they don't become instance attributes. I haven't looked at what @dataclass does under the hood or anything, but I'm just a a bit confused. 

Essentially, what I'm saying is that if I can access `InitVar` type values from within `__post_init__` through `self.demand` or `self.supply` and avoid the entire problem of potential collisions due to argument positions, then why shouldn't I? (so far, only if the InitVar is also using `field(...,kw_only=True)` would this approach fail)

**Comment by ericvsmith** [comment]
In case anyone stumbles across this, this code shows the difference between the InitVar values and the defaults:

```python
from dataclasses import dataclass, InitVar, field

@dataclass
class Fruit:
    price : int = None
    demand : InitVar[float] = 1.0
    supply : InitVar[float] = 2.0

    def __post_init__ (self, demand, supply):
        print(demand, supply)
        print(self.demand, self.supply)

Fruit(0, demand=1000.0, supply=2000.0)
```
prints:
```
1000.0 2000.0
1.0 2.0
```
