### ISSUE TITLE
ArgumentParser: parse_known_args() in between of add_argument() corrupts help message

### ISSUE THREAD

**Issue by mallniya** [python/cpython#95073]
**Bug report**
Using `parse_known_args()` in between of `add_argument()` makes those arguments added after invocation of `parse_known_args()` absent from help message. Though argument parsing with parse_args() afterwards works fine.
Example:
```
from argparse import ArgumentParser
if __name__ == '__main__':
    PARSER = ArgumentParser()
    PARSER.add_argument('-a', default=1)
    PARSER.add_argument('-b', default=2)
    PARSER.parse_known_args()
    PARSER.add_argument('-c', default=3)
    ARGS = PARSER.parse_args()
    print(ARGS)
```
If executed such script would yield `Namespace(a=1, b=2, c=3)` and if passed arguments are `-a 2 -b 3 -c 4` -- then Namespace also would yield correct `Namespace(a='2', b='3', c='4')`.
If `-h` passed to this code, then following is yielded:
```
usage: test.py [-h] [-a A] [-b B]

options:
  -h, --help  show this help message and exit
  -a A
  -b B
```
which obviously omits `-c` argument. If one moves `PARSER.parse_known_args()` one line above, then `-b` argument will be omitted.

**Your environment**
- CPython versions tested on: 3.10.5
- Operating system and architecture: Arch Linux x86_64 5.15.55-1-lts

**Comment by hpaulj** [comment]
This is expected behavior.  The first parse_args or parse_known_args catches the '-h', displays help, and exits.  It has no way of knowing that you intend to add arguments and do another parse.

**Comment by mallniya** [comment]
I eventually used separate parsers with `add_help=False` and it worked well, though I think an option for `parse_known_args` to not exit after it's execution would be a better solution.

**Comment by serhiy-storchaka** [comment]
Agree with @hpaulj. You can also just catch SystemExit.
