### ISSUE TITLE
[Enum] Deprecate member.member access with removal in 3.14

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#95077]
Accessing one enum member from another was originally forbidden, but added later to improve performance (but still warned against in the docs).  Those performance issues are no longer a problem, and it is now possible to have deprecation warnings in the code to aid in transitioning away from such usage.

**Comment by brandtbucher** [comment]
> Those performance issues are no longer a problem

As somebody who hasn't been following `enum` changes very closely: why is this?

**Comment by ethanfurman** [comment]
Performance timings on my system:

<details>
<summary>The code</summary>

``` python
import time
import enum

class Color(enum.Enum):
    RED = "Red"
    BLUE = "Blue"
    GREEN = "Green"
RED, BLUE, GREEN = Color

class FastColor:
    RED = Color.RED
    BLUE = Color.BLUE
    GREEN = Color.GREEN

def f():
    for _ in range(10000000):
        Color.RED
        Color.BLUE
        Color.GREEN

def g():
    for _ in range(10000000):
        FastColor.RED
        FastColor.BLUE
        FastColor.GREEN

def h():
    for _ in range(10000000):
        RED
        BLUE
        GREEN

import timeit
print(round(timeit.timeit('f()', number=1, globals=globals()), 2), end='  ')
print(round(timeit.timeit('g()', number=1, globals=globals()), 2), end='  ')
print(round(timeit.timeit('h()', number=1, globals=globals()), 2), end=' \n\n')
```
</details>

| version | enum | "fast" enum | global enum |
|---|---|---|---|
3.9 | 2.23 |  0.78 | 0.41 |
3.10 | 2.68 | 0.91 | 0.47 |
3.11 | 2.29 | 0.72 | 0.21 |
3.12 | 2.21 | 0.62 | 0.14 |

The 3.12 timings are with every enum member being accessed via the `enum.property` descriptor (i.e. no enum members being stored directly in the enum class `__dict__`).

Out of curiosity I ran the above code with `member.member` access, both with and without the deprecation warning:

| warning | no warning|
|---|---|
|20.41|4.16|

So updating code to be correct will keep performance to 3.11 levels (or better).

**Comment by JelleZijlstra** [comment]
How are the timings for accessing `Color.RED.value` affected?

**Comment by ethanfurman** [comment]
> > Those performance issues are no longer a problem
> 
> As somebody who hasn't been following `enum` changes very closely: why is this?

I can only imagine it's due to the work you and others have done.  I had already noticed this in the other issue when comparing 3.10/3.11/3.12, and I was able to get another slight boost by storing the member directly in the descriptor and avoiding a dict lookup.

**Comment by ethanfurman** [comment]
> How are the timings for accessing `Color.RED.value` affected?

Some improvement, but I don't think I can take any credit for that (and those timings are not affected by this issue).

| version | enum property | custom python descriptor | standard property |
|---|---|---|---|
3.9 | 5.96 | 4.9 | 2.11 |
3.10| 5.64 | 5.01 | 2.18 |
3.11 | 3.67 | 3.46 | 1.58 |
3.12 | 3.03 | 2.75 | 0.78 |

**Comment by ethanfurman** [comment]
I can make `.name` and `.value` normal properties (when no member by the same name exists), but when I tried that they stopped being reported by `inspect` and so also stopped showing up in `pydoc`.
