### ISSUE TITLE
Use SSL_CTX_get_max_proto_version instead of SSL_CTX_ctrl

### ISSUE THREAD

**Issue by davidben** [python/cpython#95095]
Filing this since the devguide says to attach a GH issue to each PR. I'll upload a PR shortly to goes with it.

CPython uses `SSL_CTX_ctrl(SSL_CTRL_GET_MAX_PROTO_VERSION)` to query the maximum version, but it's cleaner to use the wrapper macro, `SSL_CTX_get_max_proto_version`. This is the version that's documented by OpenSSL and is easier to read.
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_get_max_proto_version.html

The macros are also slightly safer since you're less likely to mess up the `larg`/`parg` calling convention. If OpenSSL ever does https://github.com/openssl/openssl/issues/1319, it will also be more type-safe. (Also I work on BoringSSL, which has done just that, so fixing this makes life easier for us. But I think this change is good independent of BoringSSL.)

**Comment by tiran** [comment]
SGTM

We used SSL_CTX_ctrl with SSL_CTRL_GET_MAX_PROTO_VERSION because OpenSSL < 1.1.0g did not have the getter macro. Since we no longer support 1.1.0 it is safe to use the macro in 3.10 and newer.

**Comment by tiran** [comment]
Thanks David! :+1:
