### ISSUE TITLE
Reading Huge zip files crashes in python3.8 but runs fine in 3.10

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [python/cpython#95104]
I tried loading a huge zip file (a face recognition dataset, roughly 86.6GB , the same failed in python3.8 but worked successfully in python3.10)

(My computer is 16GB though)

I noticed that there is a patch made regarding the same issue #87816 , but I noticed that it was flagged under python3.9, and later releases and not for python3.8.

Only python3.6 is dropped out of support , can you please make this patch available for python3,7+ releases instead of python3.9.
If not possible may I know why its not feasible or worth the effort?

Thanks a lot for these really cool projects @-`-,-

**Comment by JelleZijlstra** [comment]
Python 3.8 is in security fix-only mode. Since this is not a security issue, we won't be fixing it in 3.8. You should upgrade to Python 3.10.
