### ISSUE TITLE
tkinter text editor takes Turkish letters wrongly

### ISSUE THREAD

**Issue by mu-us61** [python/cpython#95127]
OS is windows 10
python version is 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
when writing letters, typed wrongly but when copy pasted it is ok
![image](https://user-images.githubusercontent.com/73366454/180395815-aebc5622-bcb4-4dff-8fa8-533d5e4dc889.png)

**Comment by serhiy-storchaka** [comment]
Tkinter is a relatively thin wrapper around the Tk library. File a report on the Tk bug tracker.
