### ISSUE TITLE
http module cannot be installed

### ISSUE THREAD

**Issue by zxrpn** [python/cpython#95131]
**Bug report**
I'm running into an issue where the http module fails to install.
It seems that from request import Request should be from requests import Request.
C:\Users\zxr>pip install http
Collecting http
  Downloading http-0.02.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zxr\AppData\Local\Temp\pip-install-3e0p22di\http_02f831dbe7ce475997f100d6f9575e71\setup.py", line 3, in <module>
          import http
        File "C:\Users\zxr\AppData\Local\Temp\pip-install-3e0p22di\http_02f831dbe7ce475997f100d6f9575e71\http\__init__.py", line 17, in <module>
          from request import Request
      ModuleNotFoundError: No module named 'request'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.2 is available.
You should consider upgrading via the 'C:\Users\zxr\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

- CPython versions tested on:3.10.5
- Operating system and architecture:Windows10 AMD64

**Comment by ericvsmith** [comment]
http is apparently a third party module that hasn't been updated in 10 years. https://pypi.org/project/http/

You almost certainly want to be using the requests library. But this isn't the appropriate place to ask for help, so I'm going to close this issue. Maybe try the Users category on discuss.python.org: https://discuss.python.org/c/users/7
