### ISSUE TITLE
`TestCase.assertLogs` example has broken indentation

### ISSUE THREAD

**Issue by alexei** [python/cpython#95133]
**Documentation**

The indentation in the example at [`TestCase.assertLogs`](https://docs.python.org/3.10/library/unittest.html#unittest.TestCase.assertLogs) is broken:
```python
with self.assertLogs('foo', level='INFO') as cm:
   logging.getLogger('foo').info('first message')
   logging.getLogger('foo.bar').error('second message')
self.assertEqual(cm.output, ['INFO:foo:first message',
                             'ERROR:foo.bar:second message'])
```
It should be:
```python
with self.assertLogs('foo', level='INFO') as cm:
    logging.getLogger('foo').info('first message')
    logging.getLogger('foo.bar').error('second message')
self.assertEqual(cm.output, ['INFO:foo:first message',
                             'ERROR:foo.bar:second message'])
```

**Comment by zware** [comment]
"Broken" is a bit strong here, but thanks for the patch :)

**Comment by alexei** [comment]
@zware I agree. I'd appreciate it if you could suggest an alternative. English is not my mother tongue and it could help me in the future.

**Comment by zware** [comment]
I think "non-standard" would be a decent replacement for "broken" here; the latter implies that something doesn't work at all, while the former just points out that it's not following best practices.

**Comment by alexei** [comment]
Fair enough. Thanks for the suggestion!
