### ISSUE TITLE
Doc/using/mac.rst is out of date

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#95155]
macOS no longer comes with Python 2.7 pre-installed.

The doc also talks about "universal binary", but it's the kind of universal from the time when Intel macs were "new":
> which runs natively on the Mac's new Intel and legacy PPC CPU's

**Comment by ambv** [comment]
Fixed in 3.10 - 3.12. Thanks, @hauntsaninja and @howiezhao! ✨ 🍰 ✨

**Comment by hauntsaninja** [comment]
Notes for self:
- we should still fix the "universal binary" bit
- the backports currently have the wrong version and all say
> A :file:`Python 3.12` folder in your :file:`Applications` folder
