### ISSUE TITLE
Sorting tuples containing `None` raises `TypeError` in 3.11

### ISSUE THREAD

**Issue by jacobtylerwalls** [python/cpython#95173]
# Bug report

**3.10**
```python
>>> sorted([(None, 2), (None, 1)])
[(None, 1), (None, 2)]
```
**3.11.0b4**
```python
>>> sorted([(None, 2), (None, 1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

Sorting lists works fine:

```python
>>> sorted([[None, 2], [None, 1]])
[[None, 1], [None, 2]]
```

From the release notes, I expect this is due to #29076, however the release notes merely say that the "order of the result may differ", not that comparisons might newly raise `TypeError`:

> Cases of sorting using tuples as keys may be significantly faster
in some cases. This is worth mentioning because, if the tuple
elements don't define a total ordering, the order of the result
may differ from earlier releases. It's generally true that the
result of sorting simply isn't well-defined in the absence of a
total ordering on list elements.

And the issue [discussion](https://github.com/python/cpython/issues/89693#issuecomment-1093934143) says this about `sorted()`:

> Since very little is defined about the result of sorted() in the absence of a total ordering (just that it's _some_ permutation of the original), that's not surprising.

So while I agree with the sentiment that it's not great to be sorting tuples containing elements without a total ordering, I wonder if the current release note might merit some editing.

***
Real-life example involved a pattern like:
```python
sorted(iterable, key=attrgetter("optional_member", "required_member"))
```

**Comment by JelleZijlstra** [comment]
Confirmed. Adding the release-blocker tag since this regression could affect reasonable real-world code.

cc @pablogsal as release manager and @rhettinger and @tim-one who where involved with #29076

**Comment by rhettinger** [comment]
I suggest reverting the PR.  It was a minor optimization that was tenuous because it was premised on sorting not having made explicit promises about was it would do with objects that didn't define a total ordering.

It retrospect, that was a mistake because that premise was extended to tuples where we do have explicit promises.  We've [documented](https://docs.python.org/3/library/functions.html#sorted) that sorting only calls ``__lt__`` and people do rely on that fact.  And [lexicographic sorting ordering](https://docs.python.org/3/tutorial/datastructures.html?highlight=lexicographic#comparing-sequences-and-other-types) for sequences guarantees that the order is determined by the first unequal pair (plus rules for unequal length and nesting).   That amounts to a guarantee that in a tuple comparison, elements will only test ``__lt__`` if ``__eq__`` has returned False. This PR violates those promises.

Additionally, this PR made ``sorted()`` and ``list.sort()`` inconsistent with the rest of the language:

```
# If min() and max() work, sorted() should too
>> min([(None, 2), (None, 1)])
(None, 1)
>>> max([(None, 2), (None, 1)])
(None, 2)

# Tuple ordering is well-defined
>>> (None, 2) < (None, 1)
False
>>> (None, 1) < (None, 2)
True

# Sorting lists with None still works correctly
# Sequence types, list and tuple, should be consistent
>>> sorted([[None, 2], [None, 1]])
[[None, 1], [None, 2]

# Sort should be consistent with heaps which still work
# Also, heapify() should always be replaceable by list.sort()
>>> from heapq import heapify, heappop
>>> data = [(None, 2), (None, 1)]
>>> heapify(data)
>>> heappop(data)
(None, 1)
>>> heappop(data)
(None, 2)
```

**Comment by pablogsal** [comment]
I am producing to revert https://github.com/python/cpython/pull/29076 to unblock the 3.11b5 release of next week

**Comment by sweeneyde** [comment]
I agree that it's safest to just revert for now, to unblock 3.11.

But I don't think the optimization is necessarily doomed: we could decide to only apply it to situations where it's actually known to be safe, something like this:

```diff
diff --git a/Objects/listobject.c b/Objects/listobject.c
index 83dfb7da01..38a99849b7 100644
--- a/Objects/listobject.c
+++ b/Objects/listobject.c
@@ -2455,16 +2455,10 @@ list_sort_impl(PyListObject *self, PyObject *keyfunc, int reverse)
             ms.key_compare = safe_object_compare;
         }

-        if (keys_are_in_tuples) {
-            /* Make sure we're not dealing with tuples of tuples
-             * (remember: here, key_type refers list [key[0] for key in keys]) */
-            if (key_type == &PyTuple_Type) {
-                ms.tuple_elem_compare = safe_object_compare;
-            }
-            else {
-                ms.tuple_elem_compare = ms.key_compare;
-            }
-
+        if (keys_are_in_tuples && ms.key_compare != unsafe_object_compare
+                               && ms.key_compare != safe_object_compare) {
+            /* For use when each key[0] has the same safe type */
+            ms.tuple_elem_compare = ms.key_compare;
             ms.key_compare = unsafe_tuple_compare;
             ms.first_tuple_items_resolved_it = 1; /* be optimistic */
         }
```

If the `ms.tuple_elem_compare=unsafe_object_compare` case is important, we could instead revert the change to `unsafe_tuple_compare` and retain it for that case, but then add an additional function `very_unsafe_tuple_compare` that uses the `a[0] < b[0]` optimization from https://github.com/python/cpython/pull/29076, but only when `key_compare` is specialized to a known type with a total order.
