### ISSUE TITLE
Upgrade bundled setuptools to 63.2.0

### ISSUE THREAD

**Issue by sbidoul** [python/cpython#95199]

**Comment by erlend-aasland** [comment]
Resolved by:

- main: gh-95200
- 3.11: gh-95202
- 3.10: gh-95203

**Comment by pfmoore** [comment]
Thanks. I assumed these would get auto-closed. I assume the "Fixes: xxx" note needs to be added manually.

**Comment by erlend-aasland** [comment]
> Thanks. I assumed these would get auto-closed. I assume the "Fixes: xxx" note needs to be added manually.

Yes, you need to add those trigger words manually.
