### ISSUE TITLE
Loop work differently in normal form and in list comprehension

### ISSUE THREAD

**Issue by jmishra01** [python/cpython#95193]
The below code works perfectly to create a new arr list
```python
arr = []
a = [1,2,3]
b = [4,5,6]
for i in a, b:
    for j in i:
        arr.append(j)
```
But when I used list comprehension to create an arr list, I got a syntax error.
```python
arr = [j for i in a, b for j in i]
``` 
Error message
```python
arr = [j for i in a, b for j in i]
                   ^
SyntaxError: invalid syntax
```
The above list comprehension syntax should allow.

Python version: 3.10.5

**Comment by graingert** [comment]
for:
```python
a = [1, 2, 3]
b = [4, 5, 6]
arr = [j for i in a, b for j in i]
```

in python3.11 I see:

```
    arr = [j for i in a, b for j in i]
                       ^
SyntaxError: invalid syntax
```

in `python3.9 -x oldparser` I see:

```
$ python3.9 -X oldparser error.py 
  File "/home/graingert/error.py", line 3
    arr = [j for i in a, b for j in i]
                       ^
SyntaxError: invalid syntax
```

the correct syntax is:

```python
a = [1, 2, 3]
b = [4, 5, 6]
arr = [j for i in (a, b) for j in i]
```

python can't parse `[j for i in a, b for j in i]` because there's an ambiguity between:
```python
arr = [j for i in (a, b) for j in i]
```

```python
arr = [(j for i in a), (b for j in i)]
```

in fact pypy3.9 7.3.9 assumes you meant: `[j for i in a], [b for j in i]`:

```
pypy3
Python 3.8.13 (7.3.9+dfsg-1, Apr 01 2022, 21:41:47)
[PyPy 7.3.9 with GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> [j for i in a, b for j in i]
  File "<stdin>", line 1
    [j for i in a, b for j in i]
                 ^
SyntaxError: invalid syntax (expected ']')
```

**Comment by stevendaprano** [comment]
This is not a bug in the interpreter, it is a syntax error, which means it is a bug in your code: the syntax is wrong.

You should take syntax errors as definitive: the interpreter is (almost) always right when it comes to syntax. The only time a syntax error *might* be an interpreter bug is if the documentation explicitly says something is allowed, but the interpreter does not allow it. (Even then, it is probably a documentation bug.)
