### ISSUE TITLE
Wasm build instructions are confusing to this wasm newbie

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#95205]
# Documentation

I know nothing about wasm or emscripten, but am curious. I know next-to-nothing (anymore) about Docker. So, naively working my way through Tools/wasm/README.md I see:

```...# other
docker run --rm -ti -v $(pwd):/python-wasm/cpython quay.io/tiran/cpythonbuild:emsdk3
```

followed immediately by

```shell
mkdir -p builddir/build
pushd builddir/build
../../configure -C
make -j$(nproc)
popd
```

The `docker run` command puts me in a docker shell, from which the configure command is pretty worthless. It seems I am supposed to be back at my computer's prompt, but what good is the `docker run` command at that point? Am I supposed to check out .../python/cpython inside the docker env? I'm clearly missing something and suspect other people new to wasm probably are as well.

**Comment by erlend-aasland** [comment]
- The docker command should be executed from your local CPython repo clone (pwd == CPython repo).
- `../../configure -C` should be `../../cpython/configure -C`

FYI, the `-v` option to `docker run` maps `$(pwd)` to `/python-wasm/cpython` inside the Docker container.

**Comment by smontanaro** [comment]
Thanks. the incorrect configure reference was the problem. `make` is now making.

**Comment by tiran** [comment]
The documentation assumes that you run all commands from a CPython checkout inside and outside the container. Depending on how you run the container, you may ``/python-wasm`` as working directory. You need to run the commands from ``/python-wasm/cpython`` -- or better use the shell scripts in ``/python-wasm``.

**Comment by smontanaro** [comment]
Latest changes worked for me until I got here:

```shell
emrun builddir/emscripten-browser/python.html
```

This failed from inside the running Docker image with this error:

```
Unable to find browser "firefox"! Check the correctness of the passed --browser=xxx parameter!
```

I don't know where browser firefox is specified. Must be a default.

The second option (running `wasm_webserver.py`) worked for me outside the running image. Assuming it's less picky about available web browsers, maybe it should be the first option.

**Comment by erlend-aasland** [comment]
How's the last changes working out for you, Skip?
