### ISSUE TITLE
Out of bounds co_* tuple access is allowed

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#95222]
When a `LOAD_*` instruction needs to load from a `co_*s` tuple, it can segfault and crash the program when the index is out of bounds.
Examples:
```py
eval(compile('a', '<string>', 'eval').replace(co_names=()))
eval((lambda:0).__code__.replace(co_consts=()))
```

**Comment by TeamSpen210** [comment]
This is intentional I believe for efficiency - there's many ways invalid bytecode can crash the eval loop, and fixing them would degrade performance. Easier to say "don't do that".

**Comment by thatbirdguythatuknownot** [comment]
> This is intentional I believe for efficiency - there's many ways invalid bytecode can crash the eval loop, and fixing them would degrade performance. Easier to say "don't do that".

@TeamSpen210 I think it should be validated in a place like `_PyCode_Validate`, not the eval loop.

**Comment by sweeneyde** [comment]
See this comment from the "crashers" tests: https://github.com/python/cpython/blob/2ef73be891eb95064e268341e38e81d008add480/Lib/test/crashers/bogus_code_obj.py#L2-L11

**Comment by kumaraditya303** [comment]
This isn't worth fixing as there are many ways to crash the interpreter with broken code objects. https://github.com/python/cpython/blob/2ef73be891eb95064e268341e38e81d008add480/Lib/test/crashers/bogus_code_obj.py#L2-L11
