### ISSUE TITLE
crypt module fails to import in FIPS mode

### ISSUE THREAD

**Issue by sshedi** [python/cpython#95231]
# Bug report

If kernel fips is enabled, we get permission error upon doing `import crypt`.
```
Python 3.9.1 (default, May 10 2022, 11:36:26)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

            import crypt
            Traceback (most recent call last):
            File "", line 1, in
            File "/usr/lib/python3.9/crypt.py", line 117, in
            _add_method('MD5', '1', 8, 34)
            File "/usr/lib/python3.9/crypt.py", line 94, in _add_method
            result = crypt('', salt)
            File "/usr/lib/python3.9/crypt.py", line 82, in crypt
            return _crypt.crypt(word, salt)
            PermissionError: [Errno 1] Operation not permitted
```

# Your environment
VMware Photon OS 4.0
x86_64 machine
Python-3.9.1
Kernel fips is enabled

**Comment by sshedi** [comment]
Tried to fix it here: https://github.com/python/cpython/pull/94742

**Comment by tiran** [comment]
I have updated ticket to use the correct module name ``crypt`` instead of ``crypto``.

**Comment by erlend-aasland** [comment]
Resolved by:

- main: gh-94742 
- 3.11: gh-95999
- 3.10: gh-95998

Thanks for the PR, Shreenidhi!

**Comment by ArcticSnowman** [comment]
@erlend-aasland  Given this is a security issue, surely this change should be added to 3.7 to 3.9?

**Comment by erlend-aasland** [comment]
> @erlend-aasland Given this is a security issue, surely this change should be added to 3.7 to 3.9?

I don't think so. IMO, it is not a security issue; it is just a matter of failing gracefully instead of raising a (possibly) confusing exception.

**Comment by mixmind** [comment]
Hi everyone, any chance of backport it to 3.9 too??

**Comment by erlend-aasland** [comment]
> Hi everyone, any chance of backport it to 3.9 too??

Unfortunately not; see https://github.com/python/cpython/issues/95231#issuecomment-1323637693
