### ISSUE TITLE
test_ssl test_get_server_certificate_timeout is flaky on macOS

### ISSUE THREAD

**Issue by tiran** [python/cpython#95241]
# Bug report

``test_get_server_certificate_timeout`` is flaky and sometimes fails on macOS. The issue was previously reported in #88109 and #88403.

```
======================================================================
FAIL: test_get_server_certificate_timeout (test.test_ssl.SimpleBackgroundTests.test_get_server_certificate_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/cpython/cpython/Lib/test/test_ssl.py", line 1981, in test_get_server_certificate_timeout
    with self.assertRaises(socket.timeout):
AssertionError: TimeoutError not raised
```

**Comment by erlend-aasland** [comment]
New failure: https://github.com/python/cpython/runs/7700092385?check_suite_focus=true

**Comment by mdickinson** [comment]
And another one here: https://github.com/python/cpython/runs/7773405614?check_suite_focus=true

**Comment by erlend-aasland** [comment]
There has been no reports for over a year. Suggesting to close as outdated.

**Comment by mdickinson** [comment]
> Suggesting to close as outdated.

SGTM.

**Comment by davidmerwin** [comment]
@ImgBotApp
