### ISSUE TITLE
Add glossary / term for callable

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#95276]
# Documentation

There is no glossary entry for what a callable is, though that term is frequently used in the docs and elsewhere. I often find myself wanting to add `:term:callable` references; I suggest we add an entry.

**Comment by erlend-aasland** [comment]
@AlexWaygood, are you up for writing a PR? I believe you can word this way better than me :)

**Comment by AlexWaygood** [comment]
I'll try to find the time, but it may have to wait a few days or so — bit of a manic week for me 😄

**Comment by MonadChains** [comment]
Hi @erlend-aasland and @AlexWaygood,
I tried to write a possible entry to the glossary because it was a great opportunity to understand a bit more the Python implementation in C. I hope that it can help you :smiley:

**Comment by JelleZijlstra** [comment]
Fixed on main, backports are on their way. Thanks for your contribution!
