### ISSUE TITLE
failing configure command

### ISSUE THREAD

**Issue by BizarreBits** [python/cpython#95283]
# Bug report
When trying to build Python from source code on Mac, the configure command fails.

[config.log](https://github.com/python/cpython/files/9180910/config.log)

# Your environment
Python Version: 3.10.5
Operating System:

MacOS Monterey 12.3
64 Bit x68, Intel core CPU

### Linked PRs
* gh-99506
* gh-99718
* gh-99719

**Comment by erlend-aasland** [comment]
From `config.log`:

```
clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12.3'
```

**Comment by ned-deily** [comment]
While you shouldn't have to by default, you can always override the deployment target as a workaround. Try appending it to your ./configure command:

`./configure ... MACOSX_DEPLOYMENT_TARGET=12`

**Comment by erlend-aasland** [comment]
Hm, do we need to make adjustments for this in `configure`?

Also, I see we're passing on `CONFIGURE_MACOSX_DEPLOYMENT_TARGET` and `EXPORT_MACOSX_DEPLOYMENT_TARGET` to the makefile in `Mac/` and `Mac/PythonLauncher`. Are they used? It seems to me they are not.

**Comment by ronaldoussoren** [comment]
@BizarreBits : What's the output of ``xcodebuild -showsdks`` on your system? And which version of Xcode or the command-line tools is installed?   

Also, does @ned-deily's suggestion of overriding the deployment target work for you?  If you do have an older version of Xcode installed it may be necessary to specify an older deployment target as well. That's something I've never experimented with myself.

Our build system assumes that the compiler can target the current system version. That might be a problem if an old version of Xcode is installed on a newer version of macOS.   I've check that using the current Xcode beta on macOS 12.3 is not a problem (as expected).

@erlend-aasland : I don't know if it is necessary to make adjustments to the configure script. If this is indeed an older Xcode version on a newer OS it might be possible to detect this and bail out, but I don't know if it is worthwhile to do this. It might be better to just document the assumption I mention earlier (but more clearly).

**Comment by ronaldoussoren** [comment]
To answer my own question, config.log contains:

```
configure:3928: gcc --version >&5
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

According to <https://gist.github.com/yamaya/2924292> this is the compiler shipped with Xcode 11 (and the corresponding command line tools), while the system runs macOS 12.3 (``uname -r = 21.4.0`` in config.log).  Xcode 11 is Apple's "system" compiler for macOS 10.15.

The compiler on the system is too old to understand the new macOS numbering scheme introduced in macOS 11, which likely explain this error.

@BizarreBits : Why do you use an old version of Xcode to build on this system?  In general it is better to use a newer compiler and explicitly target older macOS versions ("MACOSX_DEPLOYMENT_TARGET=10.15") when needed. CPython supports building on macOS 12.x while targeting older versions (the oldest deployment target that will work is macOS 10.9).

@ned-deily, @erlend-aasland: I propose closing this issue. Our support matrix is already fairly large when only supporting the latest compiler that Apple supports on the platform. Adding support for this variant will end up untested unless we (realistically,  Ned) set up a VM with this configuration and include that in pre-release testing.

**Comment by erlend-aasland** [comment]
> I propose closing this issue. Our support matrix is already fairly large when only supporting the latest compiler that Apple supports on the platform.

+1

>  I don't know if it is necessary to make adjustments to the configure script. If this is indeed an older Xcode version on a newer OS it might be possible to detect this and bail out, but I don't know if it is worthwhile to do this. It might be better to just document the assumption I mention earlier (but more clearly).

I agree that is not worth it to make adjustments to `configure`. We could consider improving the documentation, though, before closing.

**Comment by ronaldoussoren** [comment]
Documenting this is useful. We basically require the Xcode, or corresponding Command Line Tools,  released with the OS, or a later one that's supported on the OS (generally the next major version).

**Comment by erlend-aasland** [comment]
I'll see if I can find the time to produce a PR for `Mac/README.txt`. After a quick glance, it seems several sections in that file could make use of an update.

**Comment by ronaldoussoren** [comment]
I've added a PR with some documentation about this. @ned-deily are notes like this something you prefer to back-port to 3.11 and 3.10?

Btw. Longer term it is probably better to merge most of Mac/README.txt into <https://docs.python.org/3/using/index.html> for increased visibility. But that's something for another ~~day~~ issue.

**Comment by ronaldoussoren** [comment]
The supported Xcode versions are now documented in Mac/README.txt, I'm closing the issue.
