### ISSUE TITLE
Broken links on documentation download pages

### ISSUE THREAD

**Issue by hop** [python/cpython#95290]
I'm sorry, if there is a dedicated bug tracker for docs.python.org, I haven't been able to find it.

All links on https://docs.python.org/release/3.10.4/download.html (for all python versions) lead to a 404 page.

The links on that page are of the form:

https://docs.python.org/ftp/python/doc/3.10.4/python-3.10.4-docs-html.zip

which returns a 404 error.

The URL

https://docs.python.org/ftp/python/doc/3.10.4/

redirects to

https://www.python.org/ftp/python/doc/3.10.4/

(notice `www.` vs. `docs.`!) where all archives are present and downloadable.

I've verified this with `curl` on the command line. It is not a browswer issue.

**Comment by hop** [comment]
As I wrote in my initial description: the docs are **available for download**

**Comment by hugovk** [comment]
The bottom of the pages says "Last updated on Mar 23, 2022" so these are old docs. 

https://docs.python.org/release/3.10.5/download.html is the latest 3.10, "Last updated on Jun 06, 2022", and has the same problem, so looks like a valid bug.

**Comment by hop** [comment]
As I said in my initial description: the download pages **for all python versions** have the same problem.

**Comment by hugovk** [comment]
Problem at https://github.com/python/cpython/blob/main/Doc/tools/templates/download.html with `dlbase`?

**Comment by arhadthedev** [comment]
@ned-deily Probably, https://github.com/python/cpython/pull/93853#discussion_r898495381 should be reconsidered to not confuse doc readers.

**Comment by hop** [comment]
> As I said in my initial description: the download pages **for all python versions** have the same problem.

I'm sorry, I have to correct myself: all versions linked from https://www.python.org/doc/versions/ have the problem. 3.10.5 (latest as of now) does not have the problem but is not linked from there.

**Comment by ned-deily** [comment]
There is something wrong in a website redirect because those downloads are on the dl server for those releases. I don't have time to look into that at the moment. There should be a redirect from, for example, https://docs.python.org/ftp/python/doc/3.10.5/python-3.10.5-docs-pdf-letter.zip to https://www.python.org/ftp/python/doc/3.10.5/python-3.10.5-docs-pdf-letter.zip that is not happening. Perhaps someone else can look into that.

**Comment by hop** [comment]
As I said, the redirect is there for the directory, but not for the archive files themselves.

It's now been several hours and the problem persists, so even if this _has_ to do with the build process as @Mariatta suggested, it is a _problem_.

**Comment by encukou** [comment]
@ewdurbin, can *you* set up redirects from `https://docs.python.org/ftp` to `https://www.python.org/ftp`?
As discussed above it would fix the docs download links, without needing to rebuild docs. IMO it's also better in long-term than changing build scripts, even though it'll be one more thing to think about if docs move to e.g. Read The Docs.

**Comment by ewdurbin** [comment]
Yeah, that is doable right now in our cdn configuration. Though it should also be doable here: https://github.com/python/psf-salt/blob/main/salt/docs/config/nginx.docs-backend.conf

**Comment by ewdurbin** [comment]
Oh, I see. That redirect should just need updated to match on the prefix `/ftp`. If anyone would like to open a PR to psf-salt I will happily review, merge, and deploy it.

**Comment by ewdurbin** [comment]
Best guess is there is a bad interaction with the block directly above the ftp redirect given the following:

```
$ curl -s -I https://docs.python.org/ftp/python/doc/3.10.4/python-3.10.4-docs-html.zip
HTTP/2 404 
server: nginx
content-type: text/html

$ curl -s -I https://docs.python.org/ftp/python/doc/3.10.4/python-3.10.4-docs-html.zap
HTTP/2 301 
server: nginx
content-type: text/html
location: https://www.python.org/ftp/python/doc/3.10.4/python-3.10.4-docs-html.zap
```

**Comment by hugovk** [comment]
Testing an arbitrary version, all the download links now work: https://docs.python.org/release/3.9.3/download.html

Thanks!
