### ISSUE TITLE
randint and randrange produce results out of range for integers.

### ISSUE THREAD

**Issue by btilly** [python/cpython#95303]
# Bug report
import random
x = 31274592613493751415103060963
if x < random.randint(0, x):
    print("FAILURE")

This function should never produce results outside of the specified range, but for big integers it does.  randrange does likewise.

It reasonably produces a warning because it does not have enough bits to truly choose in this range, but it shouldn't also return a number outside the range.

# Your environment
Tested on OS X 12.4 on M1 chip with both Python 3.9.13 from brew and Python 3.9.9.

**Comment by rhettinger** [comment]
The code you supplied works fine for me on an M1.  Do you have anything reproducible, perhaps a seed value that triggers the bug? What warning did you get? Try printing `random.__file__` to confirm you're running the standard library Python and not something else. Is it possible that unittest.mock is being used to modify the methods or to feed an out of range value into random? 

Did your brew build come with the standard library test suite? If so, please run it to make sure the test suite passes.  We have tests that cover the case of large integers:  test_bigrand, test_bigrand_ranges, and test_rangelimits.  All of those tests pass for me.

**Comment by btilly** [comment]
The brew did not come with a standard library test suite. AND I can no longer reproduce.

Plus when I had the problem yesterday, I was also able to reproduce by multiplying a fraction against a large integer.

Therefore I'm going to say it is intermittent bugginess in my laptop, and not a problem with Python. :-(

**Comment by pochmann** [comment]
@btilly Still worrisome that "bugginess in my laptop" is capable of affecting Python in that way. Would've been good to show the warning and example results right away, while you were still able to reproduce.
