### ISSUE TITLE
Documentation about PyTypeObject being part of the Stable ABI

### ISSUE THREAD

**Issue by ov2k** [python/cpython#95300]
https://docs.python.org/3/c-api/typeobj.html#static-types says: 

> Also, since [PyTypeObject](https://docs.python.org/3/c-api/type.html#c.PyTypeObject) is not part of the [stable ABI](https://docs.python.org/3/c-api/stable.html#stable), any extension modules using static types must be compiled for a specific Python minor version.

https://docs.python.org/3/c-api/type.html#c.PyTypeObject says: 

> Part of the [Stable ABI](https://docs.python.org/3/c-api/stable.html#stable).

I'm not sure what needs to be fixed, but something does. Can extension modules using the Stable ABI use static types now?

**Comment by erlend-aasland** [comment]
The former quote should probably read _Limited API_, not _Stable ABI_. cc. @encukou

**Comment by kumaraditya303** [comment]
Technically `PyTypeObject` is part of the stable ABI as an opaque struct (whose fields are part of the ABI) because stable ABI uses Limited C API. Maybe it's better to just document it as "part of Limited C API as an opaque struct".

**Comment by encukou** [comment]
This is fixed in https://docs.python.org/3.11/c-api/type.html#c.PyTypeObject
But it would make sense to backport to earlier docs.

**Comment by encukou** [comment]
PR is at https://github.com/python/cpython/pull/95711

**Comment by ov2k** [comment]
I think https://docs.python.org/3/c-api/typeobj.html#static-types still needs to be fixed. https://docs.python.org/3/c-api/stable.html says: 

> Extensions that only use the Limited API can be compiled once and work with multiple versions of Python.

It's not that `PyTypeObject` isn't part of the Stable ABI, but that its members aren't part of the Limited API.

**Comment by erlend-aasland** [comment]
Suggesting to close this as fixed.

**Comment by encukou** [comment]
@o2vk, please feel free to comment if you disagree, have other suggestions, or if something is unclear.
(Not sure if you have permission to reopen – if you do, that's also an option.)

**Comment by ov2k** [comment]
That's exactly my point, but perhaps I wasn't being clear enough.  https://docs.python.org/3/c-api/typeobj.html#static-types makes no reference to `PyTypeObject` being opaque, which is the real reason why extension modules using static types must be compiled for a specific Python minor version.  It should say something like: 

> Also, since [PyTypeObject](https://docs.python.org/3/c-api/type.html#c.PyTypeObject) is only part of the [Limited API](https://docs.python.org/3/c-api/stable.html#stable) as an opaque struct...

**Comment by encukou** [comment]
It makes sense to me, but I've been thinking about API/ABI way too much :)
Could you send a PR to make this clearer? If not I'll get to it eventually.
