### ISSUE TITLE
git diff <commit> <commit>

### ISSUE THREAD

**Issue by Morteza43** [python/cpython#95326]
git diff <commit> <commit> -> View the changes between two arbitrary commits  shared via :  https://goo.gl/mDwpGh

**Comment by Morteza43** [comment]
> > > @Morteza43 0x126e0d907067cd623a32975ac45de268a8d860798f41cff339c1b49adba9e073`6135c688b854fdbf741e56630328349ad3d26b42`

**Comment by Morteza43** [comment]
> git diff <commit> <commit> -> View the changes between two arbitrary commits  shared via :  https://goo.gl/mDwpGh

@Morteza43

**Comment by AlexWaygood** [comment]
> @python/organization-owners please block @Morteza43 as a spammer. This issue + #95306

And also #95327

**Comment by AlexWaygood** [comment]
> @python/organization-owners please block @Morteza43 as a spammer. This issue + #95306

Also posting spammy comments on other people's PRs, such as #95328
