### ISSUE TITLE
Check tokens[0] after allocating memory

### ISSUE THREAD

**Issue by imzhuhl** [python/cpython#95355]
# Bug report

I have questions when reading the source code of file `pegen.c`.
There is a code snippet in function `_PyPegen_Parser_New`:
```c
p->tokens[0] = PyMem_Calloc(1, sizeof(Token));
if (!p->tokens) {
    PyMem_Free(p->tokens);
    PyMem_Free(p);
    return (Parser *) PyErr_NoMemory();
}
```
I think it makes more sense to check `p->tokens[0]` but not `p->tokens` in if condition.

I look at the PR #19669 where the code was introduced and no one discussed this. Is this an oversight, or am I wrong?

# Your environment

- CPython versions tested on: main branch

**Comment by arhadthedev** [comment]
@AlexWaygood It seems to be a `type-crash` since `PyMem_Calloc()` failure is skipped with a natural null pointer access somewhere below.

**Comment by AlexWaygood** [comment]
> @AlexWaygood It seems to be a `type-crash` since `PyMem_Calloc()` failure is ignored leading to a C null pointer access somewhere below.

Sounds plausible, but I'm not much of a C programmer, so I'll let somebody else do the relabelling :)

**Comment by kumaraditya303** [comment]
> Sounds plausible, but I'm not much of a C programmer, so I'll let somebody else do the relabelling :)

Ok done, it can indeed segfault if allocation fails, classic null dereference :)

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/95356, thanks for the report!
