### ISSUE TITLE
Similar to `test_grp` in `test_pwd`, add a test with null value in name

### ISSUE THREAD

**Issue by Yaminyam** [python/cpython#95376]
Both getpwnam(name) and getgrnam(name) should return ValueErr if null is entered in the name value
In test_grp, the part is being tested, but in test_pwd, the part is not being tested.
Is it ok to write a PR that adds that test?

**Comment by mdboom** [comment]
Yes, I think a PR to add that test would be quite welcome.  Thanks.

**Comment by ambv** [comment]
This is now fixed in 3.10 - 3.12. Thanks! ✨ 🍰 ✨
