### ISSUE TITLE
Expose some of ETH_P_* consts to ease raw socket creation

### ISSUE THREAD

**Issue by noamcohen97** [python/cpython#95389]
# Feature or enhancement

Expose some of `ETH_P_*` consts to ease raw socket creation

# Pitch

Creating a raw socket requires setting *protocol* to one of the `ETH_P_*` constants, which are not exposed by the socket module as for now.
I suggest we expose some of those values in the `socket` module.

**Comment by tiran** [comment]
It would help us understand your cause if you could provide real-world examples for each of the constants. How are they used?

**Comment by noamcohen97** [comment]
> running `root` Python

`root` is not required, the `CAP_NET_RAW` capability alone is sufficient.
`SOCK_RAW` is already supported in Python
