### ISSUE TITLE
Remove unused indent_level from Modules/_json.c

### ISSUE THREAD

**Issue by aivarsk** [python/cpython#95382]
There are commits from 2009-05-02 calculating indent_level but not
using it to indent. There are some other commits from 2011-02-22
commenting out the code with the message "it does not work". Nobody cared
enough about it for 10 years, time to remove commented code and leftovers.

### Linked PRs
* gh-118105
* gh-118636

**Comment by corona10** [comment]
Maybe we need to decide not to implement it forever or should be implemented.
I need to understand the historical log for this issue.

**Comment by aivarsk** [comment]
If that helps, when indent is requested (`json.dumps(obj, indent=4)`) it uses the pure Python implementation. C implementation is called when indent is not requested
https://github.com/python/cpython/blob/main/Lib/json/encoder.py#L247

**Comment by aivarsk** [comment]
@corona10 Any updates on this? The proposal is to remove some dead code from the json encoder C implementation that is either commented-out or only increments the indent (all decrements are commented-out) and eliminate an unused function parameter. Right now it uses the Python implementation when an indentation is requested.

I can also update the C encoder to do the indentation correctly if that is the way to proceed.

**Comment by corona10** [comment]
> I can also update the C encoder to do the indentation correctly if that is the way to proceed.

I think that this way the right way to do, would you like to update the C implementation with a benchmark?

Thanks

**Comment by eendebakpt** [comment]
@corona10 @aivarsk The relatively slow json encoding for `indent!=None` was a small bottleneck in our code, so I decided to implement it (instead of removing the old dead code). Feedback on the implementation is welcome
