### ISSUE TITLE
Fastpath for encoding unsorted dict to JSON

### ISSUE THREAD

**Issue by aivarsk** [python/cpython#95385]
JSON encoder can produce output sorted by key (`json.dumps(sort_keys=True)`) The default value for `sort_keys` is `False`. The code always creates a list of dictionary items, sorts them if needed, and then iterates through them.
However, if sorting is not requested we can use `PyDict_Next` to avoid allocating a list of tuples.

pyperformance on my machine before changes:

```
### json_dumps ###
Mean +- std dev: 10.6 ms +- 0.1 ms
```

pyperformance after changes:

```
### json_dumps ###
Mean +- std dev: 9.00 ms +- 0.08 ms
```

**Comment by aivarsk** [comment]
Patched pyperformance to use `json.dumps(sort_keys=True)`

before changes
```
### json_dumps ###
Mean +- std dev: 14.0 ms +- 0.2 ms
```

after changes
```
### json_dumps ###
Mean +- std dev: 13.6 ms +- 0.2 ms
```

Probably because the new code does not create an iterator from the list and PyList_GET_ITEM is a bit faster than PyIter_Next (extra incref/decref)?

**Comment by serhiy-storchaka** [comment]
It caused a regression for OrderedDict. See #100272.
