### ISSUE TITLE
Similar to test_pwd in test_grp, more tested for `TypeError`

### ISSUE THREAD

**Issue by Yaminyam** [python/cpython#95395]
As grp and pwd modules behave similarly, I think that what is being tested in pwd should also be tested in grp.

add a test in which a number is entered as an argument to getgrnam() or a non-integer number is entered as an argument to getgrgid().

**Comment by Yaminyam** [comment]
Should I merge this issue into #95376?

**Comment by mdboom** [comment]
I think it's ok if this remains a separate issue.
