### ISSUE TITLE
remove references to deprecated CGI library

### ISSUE THREAD

**Issue by partev** [python/cpython#95413]
Remove references to CGI library because it has deprecated since version 3.11, will be removed in version 3.13

https://docs.python.org/3.12/library/cgi.html

**Comment by iritkatriel** [comment]
We keep the docs until the feature is removed.

**Comment by iritkatriel** [comment]
Ah I see in the PR that you are proposing to remove them from the tutorial intro only (in the future try to be more specific in the issue).

I don’t have an opinion on when that should happen.

**Comment by erlend-aasland** [comment]
I think the proposed change makes sense, as it only removes parts of sentences that propote certain stdlib modules. IMO, we don't want to promote use of a deprecated stdlib module.

**Comment by erlend-aasland** [comment]
Fixed with:

- #95414 
- #96422
