### ISSUE TITLE
Make "availability" directive consistent and parsable 

### ISSUE THREAD

**Issue by tiran** [python/cpython#95415]
# Documentation

The ``.. availability::`` directives in our documentation do not use a consistent syntax. The arguments are all over the place. For example versions are indicate as `Linux >= 4.2`, `Linux 4.2 and newer`, or `Linux 4.2 or later`. Some directives have additional content that point to man pages. Others reference minimum versions although we no longer support the version (e.g. `FreeBSD 9 or later` although FreeBSD 9 is not supported any more).

I would like to make the availability directive arguments consistent and parsable:

- Use consistent spelling for version restrictions `platform >= version`.
- Introduce `not ` prefix to indicate that a feature is not available on that platform.
- Check for known platform strings and emit a warning when a platform is not in an allow list.
- Enable `has_content` for the directive and move all additional remarks to the contents body of the directive.

```
.. availability:: Windows, Linux >= 3.17, not WASI

   See :manpage:`python(1)` for more information

```

A consistent and parsable syntax will allow us to automatically generate a table of non-supported features on Emscripten and WASI later.

**Comment by erlend-aasland** [comment]
Linked PRs:

- gh-95416
- gh-95438

Marking as resolved, since the PRs were merged.
