### ISSUE TITLE
IDLE: Browse non-.py python files

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#95411]
Make .pyw and .pyi and maybe no-extension files work with `File => Module Browser`.

**Comment by terryjreedy** [comment]
Transfered from #89610.  https://github.com/python/cpython/issues/89610#issuecomment-1093932972 noted that '.py' is hardcoded within browser.ModuleBrowserTreeItem in OnDoubleClick, IsExpandable, and listchildren methods.

**Comment by terryjreedy** [comment]
I am narrowing this to enabling .pyw, which is easy and nearly done.  I made .pyi and no-extension files separate tasks on #95410.

**Comment by erlend-aasland** [comment]
Resolved with:

- #95397
- #95457 
- #95458
