### ISSUE TITLE
What way to choose to fix `Warning: ULONG_PTR differs in levels of indirection from void *` in AC-generated code?

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#95417]
Currently, Argument Clinic generates initialization of `ULONG_PTR` arguments using `PyLong_AsVoidPtr()`. The reason is `sizeof(ULONG_PTR) == sizeof(void*)` akin to C99 `uintptr_t`.

However, a compiler warns that implicit conversion of a pointer to a pointer-sized integer is not the best practice. This is relevant for `_overlapped.CreateIoCompletionPort()`: https://github.com/python/cpython/blob/3e7cad3bca64ab213c66e2bd41c9d1cf1d057526/Modules/clinic/overlapped.c.h#L15-L18 https://github.com/python/cpython/blob/3e7cad3bca64ab213c66e2bd41c9d1cf1d057526/Modules/clinic/overlapped.c.h#L40

I see three ways to fix it in [`ULONG_PTR` Argument Clinic converter](https://github.com/python/cpython/blob/3e7cad3bca64ab213c66e2bd41c9d1cf1d057526/Modules/overlapped.c#L52-L53) and need an opinion on how to address the warning best:

- generate in-place cast: `CompletionKey = (ULONG_PTR)PyLong_AsVoidPtr(args[2]);` or
- add a private Windows-only `#define _PyLong_AsUlongPtr(arg) (ULONG_PTR)PyLong_AsVoidPtr(arg)` macro so the generated line becomes `CompletionKey = PyLong_AsUlongPtr(args[2]);` or
- add a public Windows-only `PyLong_AsUlongPtr` entity and document it so Python integrators and module authors also can work with this volatile WinAPI type

### Linked PRs
- gh-95538
- gh-95518

**Comment by eryksun** [comment]
The C API could support cross-platform `PyLong_AsUintptr_t()` and `PyLong_FromUintptr_t()`. The type definitions for `ULONG_PTR` and `uintptr_t` are compatible in Windows. For 64-bit, they're both `unsigned __int64`. For 32-bit, `uintptr_t` is `unsigned int`, and `ULONG_PTR` is `unsigned long`.

**Comment by arhadthedev** [comment]
To fix the warning, two steps are necessary:

- gh-95446 (deciding first whether `PyLong_*Uintptr_t` should be a macro/inline function or exported from python3.dll/.so)
- gh-95518

**Comment by arhadthedev** [comment]
According to https://devguide.python.org/developer-workflow/c-api/#guidelines-for-adding-to-the-limited-api, addition of stable ABI requires long discussion. I'm not ready for this for the sake of a single use case so closing this issue.
