### ISSUE TITLE
venv --upgrade does not seem to upgrade Python inside the virtual environment

### ISSUE THREAD

**Issue by sandrinr** [python/cpython#95424]
# Bug report

Consider the following minimal `venv` create and upgrade procedure:

```shell
$ pyenv shell 3.10.4
$ python --version
Python 3.10.4
$ python -m venv venv
$ venv/bin/python --version
Python 3.10.4
$ pyenv shell 3.10.5
$ python --version
Python 3.10.5
$ python -m venv --upgrade venv
$ venv/bin/python --version
Python 3.10.4
```

I am creating a new virtual environment using Python 3.10.4, then I upgrade it using Python 3.10.5. My expectation would be that Python inside the virtual environment would report version 3.10.5 but it still reports version 3.10.4.

# Your environment

CPython version: 3.10.4 and 3.10.5 (provided through `pyenv`)
OS: macOS 12.4 (x86_64)

**Comment by ronaldoussoren** [comment]
The help for venv says:

```
--upgrade             Upgrade the environment directory to use this version of Python, assuming Python has been upgraded in-place.
```

The ``pyenv`` tool creates separate installs for the various versions, and hence does not fit the documented assumption for ``--upgrade``. 

That said, supporting this use-case seem to be a useful enhancement.

**Comment by ericvsmith** [comment]
You should report this on the pyenv tracker. Even though this isn't strictly a packaging issue, I suggest raising it on discuss.python.org in the Packaging category: https://discuss.python.org/c/packaging/14. They can probably point you in the right direction.

In the meantime, I'm going to close this.
