### ISSUE TITLE
iscoroutinefunction doesn't work for partial bound methods

### ISSUE THREAD

**Issue by pdewacht** [python/cpython#95444]
# Bug report

`iscoroutinefunction` doesn't work for partial bound methods. Consider this example. The second assert fails.

```
import asyncio
import functools

class A:
    async def a(self, x, y):
        pass

assert asyncio.iscoroutinefunction(A().a)
assert asyncio.iscoroutinefunction(functools.partial(A().a, 1))
```
I found two related issues:
- #79071 fixed this for functions, but not for bound methods
- #82545 proposes to add support for partialmethod, but wouldn't fix this case

# Your environment

- CPython versions tested on: Python 3.10.5
- Operating system and architecture: Debian unstable, amd64

**Comment by PurityLake** [comment]
This seems to be fixed in #67707

Can confirm assertion passes on main branch. Python version`3.12.0a0`.

**Comment by corona10** [comment]
> This seems to be fixed in https://github.com/python/cpython/issues/67707

Yeah I double check that this issue was already fixed.

**Comment by graingert** [comment]
That's weird

**Comment by graingert** [comment]
Ah that's because the paritalmethod isn't going via unwrap_partial, it passes `inspect._signature_is_functionlike` directly

```python
>>> import functools
>>> class A:
...     async def a(self, x, y):
...         pass
... 
>>> A().a
<bound method A.a of <__main__.A object at 0x7f8219707a30>>
>>> import inspect
>>> inspect._signature_is_functionlike(A().a)
True
>>> A().a.__code__.co_flags
195
>>> 
```
