### ISSUE TITLE
python-3.11.0b5-amd64.exe doesn't uninstall itself well

### ISSUE THREAD

**Issue by stonebig** [python/cpython#95445]
# Bug report

install on windows 10 python-3.11.0b5 via  python-3.11.0b5-amd64.exe and the following command

d:\toto\python-3.11.0b5-amd64.exe TargetDir=d:\toto\winpython-3.11.0b5-amd64\python-3.11.0b5.amd64   InstallAllUsers=0 Include_launcher=0 InstallLauncherAllUsers=0 Include_test=0  AssociateFiles=0 Shortcuts=0

uninstall it (per reclicking on the installer)

the (empty) directory d:\toto\winpython-3.11.0b5-amd64\python-3.11.0b5.amd64\Doc  remains

# Your environment

- CPython versions tested on: python-3.11.0b5
- Operating system and architecture: windows 10

**Comment by stonebig** [comment]
it was also true for b3 and b4

**Comment by zooba** [comment]
Thanks for the report, and the fix!
