### ISSUE TITLE
Some "truthy/falsy" crept in

### ISSUE THREAD

**Issue by pochmann** [python/cpython#95454]
Python consistently says true/false, not truthy/falsy. But a few "truthy/falsy" crept into the `logging` docs:

https://github.com/python/cpython/search?q=truthy
https://github.com/python/cpython/search?q=falsy

([Previous issue](https://github.com/python/cpython/issues/89509) about a previous instance)

**Comment by PurityLake** [comment]
This can probably be closed now unless I missed some.

**Comment by pochmann** [comment]
@PurityLake The above search for falsy still finds two in `Lib/test/test_except_star.py` (not sure if intentional ... in the previous issue, Raymond Hettinger also left some in test code and only fixed the docs (which is why above I only spoke of the docs), but it looks like you tried to fix truly all).

**Comment by PurityLake** [comment]
@pochmann maybe I was a little over zealous, hasn't seemed to affect the functionality at least, I'll make another PR to squash that last one. Seemed Raymond was the one to commit the changes so he must not have minded.

**Comment by rhettinger** [comment]
IMO the PR was too aggressive. I approved it only because it wasn't worth the time to debate each individual case.   Let's be done with this one now.

**Comment by PurityLake** [comment]
Apologies, I'll be more diligent in future
