### ISSUE TITLE
avoid the global_lock in `asyncio.mixins._LoopBoundMixin`

### ISSUE THREAD

**Issue by graingert** [python/cpython#95474]
@asvetlov 

> The alternative is using the fast C atomic `compare_and_swap` function
> which is executed under the hold GIL.
> We need the pure-Python fallback anyway.

I was checking some minor detail in socketpair and noticed this: https://github.com/python/cpython/blob/bceb197947bbaebb11e01195bdce4f240fdf9332/Lib/socketserver.py#L700

and it looks like it benchmarks a 100ns faster than a global lock:

```python
#!/usr/bin/env python3
import pyperf
from asyncio import events

"""Event loop mixins."""

import threading

_global_lock = threading.Lock()

# Used as a sentinel for loop parameter
_marker = object()


class _LoopBoundMixin:
    _loop = None

    def __init__(self, *, loop=_marker):
        if loop is not _marker:
            raise TypeError(
                f'As of 3.10, the *loop* parameter was removed from '
                f'{type(self).__name__}() since it is no longer necessary'
            )

    def _get_loop(self):
        loop = events._get_running_loop()

        if self._loop is None:
            with _global_lock:
                if self._loop is None:
                    self._loop = loop
        if loop is not self._loop:
            raise RuntimeError(f'{self!r} is bound to a different event loop')
        return loop


class _LoopBoundMixinSetDefault:
    _loop = None

    def __init__(self, *, loop=_marker):
        if loop is not _marker:
            raise TypeError(
                f'As of 3.10, the *loop* parameter was removed from '
                f'{type(self).__name__}() since it is no longer necessary'
            )

    def _get_loop(self):
        loop = events._get_running_loop()
        if self._loop is None:
            self.__dict__.setdefault("_loop", loop)

        if self._loop is not loop:
            raise RuntimeError(f'{self!r} is bound to a different event loop')

        return loop

runner = pyperf.Runner()
runner.timeit(name="get loop with lock",
              stmt="lbm = _LoopBoundMixin(); lbm._get_loop(); lbm._get_loop()",
              setup="import asyncio; from __main__ import _LoopBoundMixin; asyncio._set_running_loop(asyncio.new_event_loop())")

runner.timeit(name="get loop with setdefault",
              stmt="lbm = _LoopBoundMixin(); lbm._get_loop(); lbm._get_loop()",
              setup="import asyncio; from __main__ import _LoopBoundMixinSetDefault as _LoopBoundMixin; asyncio._set_running_loop(asyncio.new_event_loop())")

runner.timeit(name="get loop already set with lock",
              stmt="lbm._get_loop()",
              setup="import asyncio; from __main__ import _LoopBoundMixin; asyncio._set_running_loop(asyncio.new_event_loop()); lbm = _LoopBoundMixin(); lbm._get_loop()")

runner.timeit(name="get loop already set with setdefault",
              stmt="lbm._get_loop()",
              setup="import asyncio; from __main__ import _LoopBoundMixinSetDefault as _LoopBoundMixin; asyncio._set_running_loop(asyncio.new_event_loop()); lbm = _LoopBoundMixin(); lbm._get_loop()")
```

_Originally posted by @graingert in https://github.com/python/cpython/issues/86558#issuecomment-1198672464_

**Comment by kumaraditya303** [comment]
I wonder how it works on other Python implementations which reuse asyncio, this is making assumption that `setdefault` does not calls back into Python and is thread safe and that no thread can switch in `vars` call.

**Comment by graingert** [comment]
Jython used to implement setdefault not-atomically, but then fixed it as a bug:

https://bugs.jython.org/issue735205

**Comment by graingert** [comment]
>  this is making assumption that setdefault does not calls back into Python

I think the only way to make it call back into python is hacking items on the lock vars(). But this is ok because the `asyncio.get_running_loop()` is still the same.

```
class EqHashHack:
    def __init__(self, k, cb):
        self._k = k

    def __hash__(self):
        return hash(self._k)

    def __eq__(self, *args, **kwargs):
        cb()
        return False
        
lock = asyncio.Lock()
vars(lock)[EqHashHack(k="_loop", cb=lambda: lock.aquire())] = None
```

**Comment by graingert** [comment]
@kumaraditya303 actually worse news - I think it's now possible to re-enter this lock with asyncio.Runner:

https://github.com/python/cpython/blob/89f52293281b6efc4ef666ef25e677683821f4b9/Lib/asyncio/runners.py#L147-L154

calling `main_task.cancel` can call `main_task._fut_waiter.cancel()` which could be a custom Future implementing a `def cancel(self):` method. This is now running user code in a re-entrant context that it cannot possibly hope to support.

**Comment by graingert** [comment]
@kumaraditya303 https://github.com/python/cpython/issues/95592

**Comment by kumaraditya303** [comment]
This only optimizes the uncommon case that the loop isn't already cached on the object as such I don't think this is worth and I am rejecting it.
