### ISSUE TITLE
IDLE - Tweak Edit menu

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#95471]
Move `Select All` above  `Cut` as it is used with `Cut` and `Copy` but not with `Paste`.  Add a separator between `Replace` and  `Go to Line` to show IDLE issue triagers the separation between menu items that belong to the 'Edit-find' and 'Edit-show' topics.

**Comment by erlend-aasland** [comment]
Resolved by:

- gh-95481
- gh-95487
- gh-95488
