### ISSUE TITLE
IDLE - document github project issue topics

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#95491]
The primary field for the [IDLE issues](https://github.com/orgs/python/projects/31/views/1?filterQuery=-status%3ADone+topic%3A&visibleFields=%5B%22Title%22%2C10094998%2C%22Linked+pull+requests%22%2C10681642%5D) project in the github cpython repository is 'Topic'. I will add a listing of topics and explanation of each to idlelib/README.txt, which is accessible from IDLE on the `Help => About IDLE` dialog.

This will replace my private 'idle-issues.txt', which has been absolutely essential for me working with IDLE.  I once uploaded a snapshot to #74607.  I considered adding a periodically updated snapshot to idlelib but never decided that the benefit would justify the extra work.  The IDLE issues project should be a net plus for me *and* be available to anyone else working with IDLE issues.

Many of the topics comprise issues related to groups of menu items indicated by separators on each drop-down menu.  #95471 added a separator needed for this purpose.

**Comment by erlend-aasland** [comment]
Each GitHub Project has an associated README file that can be edited through the project's settings. I suggest to use this feature to document the _Topic_ meta field, and also update it with more instructions for how to triage IDLE issues. After this is done, we can close this issue as resolved.

Suggested list of tasks:

- [ ] Add triaging information, including GH Projects meta fields info and other useful tips/pointers, to the IDLE GH Project README file
- [ ] Add a note about the GH Project to `Lib/idlelib/README.txt`

**Comment by terryjreedy** [comment]
Do you have anything to add now to the project settings?  Otherwise, I'd like to close this after the PR is merged.

**Comment by erlend-aasland** [comment]
Not at the moment. The project settings look good to me. If we need to update them futher, we can just do it; there is no need for an issue.

**Comment by erlend-aasland** [comment]
Fixed with:

- gh-95750
- gh-95790
- gh-95791
