### ISSUE TITLE
Expose all functionality of list_sort_impl in C API

### ISSUE THREAD

**Issue by boomanaiden154** [python/cpython#95506]
# Feature or enhancement

Add in a new function, `PyList_SortAdvanced` (or probably something with a better name) that takes in all of the same parameters as the underlying `list_sort_impl` function and is implemented in a very similar way to `PyList_Sort`.

# Pitch

Currently, there is no way (at least that I can find) to access the same functionality as the Python list's `sort()` function in the C API. It would be useful to have the ability to define a custom key function while interfacing with Python Objects through the C API, or set the reverse flag. But currently, `PyList_Sort` only takes in a list of objects to sort and doesn't allow setting the parameters that are available in `list_sort_impl`. This makes doing something like sorting a list of more complex datatypes (where a key function would typically be used) or sorting lists with multiple different data types significantly less elegant.

I'm proposing a new function with a different name rather than changing the signature of the existing function to improve backwards compatibility.

# Previous discussion

Discussed on the Python ideas forum [here](https://discuss.python.org/t/a-more-controllable-version-of-pylist-sort/17815) and it was suggested that I open an issue here.

**Comment by ronaldoussoren** [comment]
Note that there's already a way to do this through the generic API: Use call related APIs like ``PyObject_VectorcallMethod`` to call the "sort" method of the list object. This will also work on older Python versions.

**Comment by rhettinger** [comment]
Since there is a valid, documented way to do it and since no one has stepped forward to champion this, I'm marking this as closed.

Thank you for the suggestion, but it doesn't seem to be necessary.
