### ISSUE TITLE
Wrong sign placement in PyUnicode_FromFormat

### ISSUE THREAD

**Issue by philg314** [python/cpython#95504]
# Bug report

When specifying width or precision with a negative number the sign ignores that and sticks to the number.
Width specifies the minimum output width, so if the zero flag is set the sign should be the first character of the width padding, if the zero flag is not set the last character of the padding.
Precision specifies the number of digits, so the sign should be placed before precision count digits.

```c
PyUnicode_FromFormat(  "%05d", -123); //   "0-123" should be   "-0123"
PyUnicode_FromFormat(  "%.5d", -123); //   "0-123" should be  "-00123"
PyUnicode_FromFormat( "%7.5d", -123); // "  0-123" should be " -00123"
PyUnicode_FromFormat("%07.5d", -123); // "000-123" should be "-000123"
```

# Your environment

- CPython versions tested on: main branch

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/95848
