### ISSUE TITLE
Many versions of 3.1.2 string Chinese document translation errors

### ISSUE THREAD

**Issue by BeHappy0o0o0o0** [python/cpython#95553]
# Documentation

## English document content
This feature is particularly useful when you want to break long strings:

```
>>>
>>> text = ('Put several strings within parentheses '
...         'to have them joined together.')
>>> text
'Put several strings within parentheses to have them joined together.'
```

## Simplified Chinese translation

拆分长字符串时，这个功能特别实用：

```
>>>
>>> text = ('Put several strings within parentheses '
...         'to have them joined together.')
>>> text
'Put several strings within parentheses to have them joined together.'
```

## Change suggestions
The content of the Chinese document is incorrectly expressed, so it should be changed to long strings separated by splicing. This function is particularly practical.

Instead of that split str in the original translation.

The correct Chinese expression is as follows:

`对于拼接分隔开的长字符串，这个功能特别实用：`

The traditional Chinese expression is not very clear, so it can be changed as follows:

`對於拼接分隔開的長字符串，這個功能特別實用：`

end。

**Comment by AlexWaygood** [comment]
Thanks! Issues relating to the simplified Chinese translations of the docs should be filed over at https://github.com/python/python-docs-zh-cn/issues, not the CPython repo (and I see you've already filed an issue over there as well)

**Comment by BeHappy0o0o0o0** [comment]
Yes, the problem has been solved, thank you!
