### ISSUE TITLE
Failed Sub processes do not seem to have capture stderr and stdout 

### ISSUE THREAD

**Issue by mriddell95** [python/cpython#95561]
# Bug report

While trying to run the following command: `subprocess.run(<my-command>, check=True, capture_output=True)` I would assume based on the code and documentation https://github.com/python/cpython/blob/3.10/Lib/subprocess.py#L524 https://docs.python.org/3/library/subprocess.html#subprocess.run that a subprocess which fails and returns a CalledProcessError would also include the stdout and stderr. 

However it seems no matter what process it seems no matter which process I try I cannot get the output to be captured as long as check mode is enabled. An example command could be something as simple as `["git", "aaaaaaa"]` which when `check=True` does not have the stdout however when `check=False` the stdout is captured correctly.

# Your environment

- Python version 3.10
- Buster amd64

**Comment by eryksun** [comment]
Here's an example with a `CalledProcessError` exception:

```python
>>> try:
...     subprocess.run(['git', 'aaaaaaa'], capture_output=True, check=True)
... except subprocess.CalledProcessError as e:
...     print('stdout:', repr(e.stdout))
...     print('stderr:', repr(e.stderr))
... 
stdout: b''
stderr: b"git: 'aaaaaaa' is not a git command. See 'git --help'.\n"
```

**Comment by mriddell95** [comment]
Apologies I thought I had previously tried this but apparently I must have just thought I did. Thanks for clearing my confusion
