### ISSUE TITLE
make asyncio.Timeout and asyncio.TaskGroup fail early when used incorrectly

### ISSUE THREAD

**Issue by graingert** [python/cpython#95569]
asyncio.timeout and asyncio.TaskGroup objects are sensitive to a number of re-use anti-patterns, especially re-use across different event-loops and threads

I think they should both be sub-classes of `asyncio.mixins._LoopBoundMixin` and make sure that they are in the created state in `__aenter__` eg:

```python
async def __aenter__(self):
    loop = self._get_loop()
    assert self._state == _State.CREATED
    self._task = tasks.current_task(loop)
```

**Comment by graingert** [comment]
eg consider someone trying to use timeout like this:

```python
import asyncio

import logging
logger = logging.getLogger(__name__)

async def nested_reuse():
    timeout = asyncio.timeout(1)
    async with timeout:
        async with timeout:
            await asyncio.sleep(4)

async def concurrent_reuse():
    timeout = asyncio.timeout(1)

    async def use():
        async with timeout:
            await asyncio.sleep(4)

    await asyncio.gather(use(), use())

async def serial_reuse():
    timeout = asyncio.timeout(1);

    try:
        async with timeout:
            await asyncio.sleep(4)
    except TimeoutError:
        print("timed out")

    try:
        async with timeout:
            await asyncio.sleep(4)
    except TimeoutError:
        print("timed out")


def run_test(fn):
    print("##################################################################")
    try:
        asyncio.run(fn())
    except (asyncio.CancelledError, Exception):
        logger.exception(f"{fn=} failed")

    print("##################################################################")

run_test(nested_reuse)
run_test(concurrent_reuse)
run_test(serial_reuse)
```

**Comment by gvanrossum** [comment]
Have you already observed users doing this? I’m open to making this more robust but it would need to not slow things down.

**Comment by kumaraditya303** [comment]
FWIW later down the road I would like to get rid of the `asyncio.mixins._LoopBoundMixin`  alongside the policies so we should avoid this in new code.

**Comment by kumaraditya303** [comment]
Unless something is documented as thread safe, nothing is thread safe in `asyncio`. There are too many ways to break `asyncio` if you want to.

**Comment by kumaraditya303** [comment]
I don't want to use `_LoopBoundMixin` in more code, rather I would like to get rid of it but that's for another issue. Given how long this has been dormant and I have not yet seen any user doing these mistakes (no bug reports or SO), I am inclined to close it.

**Comment by gvanrossum** [comment]
> I don't want to use `_LoopBoundMixin` in more code, rather I would like to get rid of it but that's for another issue.

Indeed, I would like to get rid of it too.
