### ISSUE TITLE
subprocess.check_output fails when calling bash script with preceding newline

### ISSUE THREAD

**Issue by Juksefantomet** [python/cpython#95575]
# Bug report

python file test.py:
```
import subprocess
import re

rc = subprocess.check_output("/home/user/test.sh")
print(rc)
```

bash file test.sh:
```
<newline here>
#!bin/bash
echo "Hello World"
```

When executing the subprocess.check_output fails to reckognize the bash script as executable due to the newline.

```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/test.py", line 5, in <module>
    rc = subprocess.check_output('/home/user/test.sh')
  File "/usr/lib64/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

# Your environment

Amazon Linux 2 - VM clean install
python 2.7.18
python 3.7.10

Is this expected behavior? or should there be any expected removing of preceding newlines?

Normal bash script execution works as intended even with newline in place.

**Comment by JelleZijlstra** [comment]
This isn't a Python bug. Python just passes control to the operating system, and the OS requires the shebang line to be strictly the first line. That's why you get an OSError.

**Comment by Juksefantomet** [comment]
Odd that normal execution as mentioned does not demand it and works as expected, but fair enough.

**Comment by Juksefantomet** [comment]
i'm not trying to be difficult here :D

but on the failing OS, this is not correct:

```
[ec2-user@ip-10-0-0-57 ~]$ mkdir temp
[ec2-user@ip-10-0-0-57 ~]$ cd temp
[ec2-user@ip-10-0-0-57 temp]$ echo ' 
> #!/bin/bash
> echo "lol"
> ' > test.sh
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ chmod +x+w+r test.sh 
[ec2-user@ip-10-0-0-57 temp]$ bash test.sh
lol
[ec2-user@ip-10-0-0-57 temp]$ sh test.sh
lol
[ec2-user@ip-10-0-0-57 temp]$ ./test.sh 
lol
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ echo 'import subprocess
> import re
> 
> rc = subprocess.check_output("/home/ec2-user/temp/test.sh")
> print(rc)
> ' > test.py
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ chmod +x+w+r test.py
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    rc = subprocess.check_output("/home/ec2-user/temp/test.sh")
  File "/usr/lib64/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ echo '#!/bin/bash
> echo "lol"
> ' > test.sh
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ bash test.sh
lol
[ec2-user@ip-10-0-0-57 temp]$ sh test.sh
lol
[ec2-user@ip-10-0-0-57 temp]$ ./test.sh
lol
[ec2-user@ip-10-0-0-57 temp]$ 
[ec2-user@ip-10-0-0-57 temp]$ python test.py
lol

```
I see your logic, but it does work in all three cases, but not when executed through pythons subprocess.

**Comment by eryksun** [comment]
> I see your logic, but it does work in all three cases, but not when executed through pythons subprocess.

When executing a text file fails with `ENOEXEC`, bash tries to execute the contents as a shell script. The shebang isn't used or even required. Refer to the source of [`shell_execve()`](https://github.com/gitGNU/gnu_bash/blob/bc007799f0e1362100375bb95d952d28de4c62fb/execute_cmd.c#L5445). A Python script can handle `ENOEXEC` however it wants, or use `shell=True` to let the shell handle it.

**Comment by erlend-aasland** [comment]
You can easily verify the behaviour of the `execve()` syscall using a small C snippet:

<details>
<summary>main.c</summary>

```c
#include <stdio.h>
#include <unistd.h>
#include <sys/errno.h>

int main() {
    const char *path = "./test.sh";
    char *const argv[] = { NULL, };
    char *const envp[] = { NULL, };
    int rc = execve(path, argv, envp);
    printf("execve('%s', ...) => %d, errno=%d\n", path, rc, errno);
    return 0;
}
```
</details>

Compile and run it in the directory where you saved your script:
```console
$ cat test.sh

#!bin/bash
echo "Hello World"
$ gcc main.c 
$ ./a.out    
execve('./test.sh', ...) => -1, errno=8
$
```

See also the relevant parts in the Linux kernel source code where `ENOEXE` is returned if the shebang is malformed:

- [fs/exec.c](https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/fs/exec.c)
- [fs/binfmt_script.c](https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/fs/binfmt_script.c)

**Comment by Juksefantomet** [comment]
Thank you both for the clarification :smile:
