### ISSUE TITLE
Entire `threading` docs contained within a `note::` in 3.10

### ISSUE THREAD

**Issue by gjoseph92** [python/cpython#95585]
# Documentation

On the 3.10 docs, the entire contents of the page shows up within the gray box for "In the Python 2.x series, this module contained `camelCase` names" note.

[3.9 docs](https://docs.python.org/3.9/library/threading.html):
<img width="444" alt="Screen Shot 2022-08-02 at 11 01 47 PM" src="https://user-images.githubusercontent.com/3309802/182527867-699effcb-2b6c-49e8-b3b8-03c5c977a98e.png">

[3.10 docs](https://docs.python.org/3.10/library/threading.html):
<img width="444" alt="Screen Shot 2022-08-02 at 11 01 37 PM" src="https://user-images.githubusercontent.com/3309802/182527820-ee6bdae1-17c0-458e-88ea-e13897099add.png">

https://github.com/python/cpython/pull/25174 looks like the most recent thing to touch that area, but also seems like an unlikely culprit. Sphinx version bump maybe https://github.com/python/cpython/pull/32124?

**Comment by AlexWaygood** [comment]
Also happening with the `typing` docs. This is #91483 happening again.

**Comment by gjoseph92** [comment]
Ah sorry for the duplicate, want me to close this one?

**Comment by AlexWaygood** [comment]
> Ah sorry for the duplicate, want me to close this one?

Not your fault, since that one's been open for a while, and this has only just started happening again! I think I will close this one in favour of that one, though; there's not much reason to have them both open :)
