### ISSUE TITLE
Backport Fixes for #71992 to Python3.6

### ISSUE THREAD

**Issue by aaronemassey** [python/cpython#95583]
See https://github.com/python/cpython/issues/71992 for details on the exact problem.

This was never backported to Python3.6 and I'd like to be. I thought I could assign the issue to myself but it looks like I can't.

I'll happily try backporting it at somepoint soon.

**Comment by JelleZijlstra** [comment]
Thanks for the offer, but Python 3.6 has reached its end of life; we no longer accept patches for it.
