### ISSUE TITLE
Update bugs to point to Github instead of bugs.python.org issue tracker

### ISSUE THREAD

**Issue by gnbl** [python/cpython#95608]
# Documentation

"Found a bug?" in the footer of the documentation points to 
https://docs.python.org/3/bugs.html which points to 
https://bugs.python.org/ which states
> This issue tracker has been migrated to [GitHub](https://github.com/python/cpython/issues), and is currently read-only.

and points here (https://github.com/python/cpython/issues).

If it has been migrated it should be possible to link to the Github Issues directly?

**Comment by hauntsaninja** [comment]
This was fixed on master and 3.11 in #91425, but looks like the backports to 3.9 and 3.10 failed

**Comment by hauntsaninja** [comment]
Okay, I opened:
3.9 backport https://github.com/python/cpython/pull/95614
3.10 backport https://github.com/python/cpython/pull/95615

**Comment by gnbl** [comment]
I can confirm that https://docs.python.org/bugs.html ->  https://docs.python.org/3/bugs.html (3.10.6) point to GitHub Issues now.

**Comment by gnbl** [comment]
3.9 / 3.9.13 doesn't.

**Comment by ezio-melotti** [comment]
This has been fixed on all branches so it can be closed, even though 3.9 docs haven't been rebuilt yet.
* https://github.com/python/cpython/pull/91425
* https://github.com/python/cpython/pull/95615
* https://github.com/python/cpython/pull/95614
Previous issue:
* https://github.com/python/cpython/issues/91423

Thanks for the report and the PRs!
