### ISSUE TITLE
make test fails; executable works; runtime error in background

### ISSUE THREAD

**Issue by slmatrix** [python/cpython#95635]
# Bug report

The runtime error will occur on simply launching the interpreter.
**Modules/posixmodule.c:15451:9: runtime error: left shift of 34 by 26 places cannot be represented in type 'int'**
```
Modules/posixmodule.c:15451:9: runtime error: left shift of 34 by 26 places cannot be represented in type 'int'
Python 3.12.0a0 (heads/main:dc2757accd, Aug  3 2022, 19:28:30) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

# Your environment

- CPython versions tested on: 3.12.0a0
- Operating system and architecture: Debian 11 -- amd64

debug output is attached. [out.txt](https://github.com/python/cpython/files/9255899/out.txt)

**Comment by iritkatriel** [comment]
What exactly are you running?

**Comment by iritkatriel** [comment]
I mean, what produced the "debug output"?

**Comment by iritkatriel** [comment]
What do you mean by “ when I execute the interpreter”? How did you obtain the interpreter and how did you execute it?

The interpreter is working for many people, so there is something in your process which is different. We can’t do anything with this bug report if you don’t tell us exactly what you are doing.

**Comment by iritkatriel** [comment]
Please get a fresh check out, start from scratch, and send the precise commands you used to get the source code, configure and compile it. Include also all the output you got on the screen.

**Comment by iritkatriel** [comment]
What is test.py?

**Comment by iritkatriel** [comment]
Yes please.

**Comment by iritkatriel** [comment]
I'm closing this as there has been no followup for over two weeks. If you are still having this problem and are able to provide full information about it as discussed above, we can reopen.

**Comment by grammy-jiang** [comment]
I got the same error.

I am trying to compile Python 3.11.0 on my Fedora 36 workstation with the following command:

`./configure --enable-shared --enable-profiling --enable-pystats --enable-optimizations --enable-loadable-sqlite-extensions --with-pydebug --with-trace-refs --with-assertions --with-lto=full --with-undefined-behavior-sanitizer --with-valgrind`

and got the following error:

> make[1]: Leaving directory '/home/grammy-jiang/Downloads/Python-3.11.0'
LD_LIBRARY_PATH=/home/grammy-jiang/Downloads/Python-3.11.0 ./python -E  ./Tools/scripts/run_tests.py
Modules/posixmodule.c:15543:9: runtime error: left shift of 34 by 26 places cannot be represented in type 'int'
/home/grammy-jiang/Downloads/Python-3.11.0/python -u -W default -bb -E -E -m test -r -w -j 0 -u all,-largefile,-audio,-gui
make: *** [Makefile:1814: test] Profiling timer expired

Any idea?

**Comment by iritkatriel** [comment]
That looks like a different error. Please create a new issue for it.
