### ISSUE TITLE
New asyncio ssl implementation is lacking license and origin information

### ISSUE THREAD

**Issue by tiran** [python/cpython#95649]
# Bug report

In GH-31275 / GH-88177 a new asyncio ssl implementation was added. The code was copied from uvloop project. The commit message 13c10bfb777483c7b02877aab029345a056b809c lacks information about origin, original authors, and original license of the code. The copied files and code also lacks provenance and license information.

Lack of license information is problematic from a legal standpoint. MIT license requires us to keep the license with code or non-trival portions of code.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Each file with non-trivial code from uvloop should gain a file header with information about origin of the files, authors of the code, and the original license of the uvloop project. Further more ``Docs/license.rst`` should be extended. Please get in contact with our lawyer VanL if you have further questions.

### Linked PRs
* gh-107536
* gh-114045
* gh-114046

**Comment by graingert** [comment]
I think Lib/asyncio/taskgroup.py should include the Apache license. The "with permission from edgedb" header is confusing for people trying to reuse the code
