### ISSUE TITLE
Enable sqlite extensions in the Windows build

### ISSUE THREAD

**Issue by pfmoore** [python/cpython#95656]
# Feature or enhancement

Enable SQLite extension loading in the Windows build (in the sqlite DLL shipped with Python, and in the stdlib sqlite3 module).

# Pitch

At the moment, sqlite extensions are disabled at compile time - see the note in [the docs](https://docs.python.org/3.11/library/sqlite3.html#sqlite3.Connection.enable_load_extension). On Windows, though:

1. We supply our own sqlite DLL, so we control the build options, and
2. Users rarely build their own copy of Python.

So the reasons for not enabling extension loading don't really apply there, and conversely, people who want to use extensions cannot do so without limiting themselves to custom Python builds.

# Previous discussion

See https://discuss.python.org/t/should-we-audit-enabling-loading-of-sqlite3-extensions-shared-libraries/8124/9

**Comment by erlend-aasland** [comment]
+1

I'll create a patch.

As I said on Discourse, I'd like to make it possible to enable extension loading via `sqlite3_db_config()`, but that is out of scope for this issue.

**Comment by erlend-aasland** [comment]
Repeating https://github.com/python/cpython/pull/95662#issuecomment-1205689607:

> Aha... no backport to 3.10 is needed. I changed the `#ifdef` guard in 3.11, while Christian and I were updating `configure.ac`. So... this means I broke this for Windows builds in 3.11.
>
> FTR, broken in gh-29434.

**Comment by pfmoore** [comment]
lol, I'd forgotten that by installing 3.11b5, it was now my default, so when I checked and it wasn't working I assumed that was normal, rather than a 3.11 regression.

Thanks for fixing it, and sorry for misreporting it!
