### ISSUE TITLE
Missing documentation for iterables in set methods

### ISSUE THREAD

**Issue by matthewhughes934** [python/cpython#95679]
# Documentation

Set methods such as `set.isdisjoint`, `set.issubset` can take either a set or any iterable as an arugment, however the latter case is not clearly documented (as far as I can tell from browsing https://docs.python.org/3/library/stdtypes.html#set) despite this case being used within Python's standard library. Should this use case also be documented (or perhaps it already is and I missed it?).

I have a very quick+rough example of documenting this (with links to existing usage etc.) under https://github.com/matthewhughes934/cpython/commit/084e54eae770226efa3b9b2eee92ab513d93fba2

**Comment by pochmann** [comment]
What about the paragraph right under the methods, *"Note, the non-operator versions..."*? (Granted, `isdisjint` isn't mentioned there, as it doesn't have an operator based counterpart.)

**Comment by matthewhughes934** [comment]
> What about the paragraph right under the methods, _"Note, the non-operator versions..."_? 

:facepalm: yeah, there it is. Once more demonstrating that my brain doesn't actually work at the end of the day :upside_down_face:
