### ISSUE TITLE
pipe test failures on some  Linux configurations  

### ISSUE THREAD

**Issue by colesbury** [python/cpython#95672]
# Bug report

On Linux systems, when configured with a default pipe capacity of 4096, the following test fail:
- test_fcntl.test_fcntl_f_pipesize
- test_subprocess.test_pipesizes

From a recent `fcntl(2)` Linux [man page](https://man7.org/linux/man-pages/man2/fcntl.2.html#:~:text=Attempts%20to%20set%20the%20pipe%20capacity%20below%20the%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20page%20size%20are%20silently%20rounded%20up%20to%20the%20page%20size.):

```
F_SETPIPE_SZ:
...
Attempts to set the pipe capacity below the page size are silently rounded up to the page size.
```

There's a check that attempts to skip the tests if the pipe capacity is [512 bytes](https://github.com/python/cpython/blob/6a5104f4fa83ed08fe31f712757dddabfede394c/Lib/test/test_fcntl.py#L202), but that's less than the smallest page size on x86.

Since this feature appears to be Linux specific, the check should:

1) Use `os.sysconf('SC_PAGESIZE')` as a minimum
2) Fix the typos ("SkitTest") in [test_fcntl_f_pipesize](https://github.com/python/cpython/blob/6a5104f4fa83ed08fe31f712757dddabfede394c/Lib/test/test_fcntl.py#L203) and [test_pipesizes](https://github.com/python/cpython/blob/f6dd14c65336cda4e2ebccbc6408dfe3b0a68a34/Lib/test/test_subprocess.py#L715)

### Linked PRs
* gh-102119
* gh-102121
* gh-102122
* gh-102163
* gh-102365
* gh-102455

**Comment by corona10** [comment]
Same as https://github.com/python/cpython/issues/95675#issuecomment-1435519257
I will introduce this issue into the internal OSS sprint as the good first bug.
I will delegate the issue to my mentees.

**Comment by hyeongyun0916** [comment]
I'm looking this issue 👀

**Comment by corona10** [comment]
@hyeongyun0916 Thanks for the hardwork!
