### ISSUE TITLE
test_tar test_add_dir_getmember fails if uid/gid is larger than 16777215

### ISSUE THREAD

**Issue by colesbury** [python/cpython#95675]
# Bug report

The [`test_add_dir_getmember`](https://github.com/python/cpython/blob/12d92c733cfc00ee630b30e4e0250da400c83395/Lib/test/test_tarfile.py#L223) added in https://github.com/python/cpython/pull/30283 fails if the current user's uid or gid is larger than 16777215 because of limitations of UStar format.

Note that the other test cases don't have this problem.

This test should either avoid depending on the current user's uid/gid (such as by using an explicit uid/gid) or be skipped if the current uid/gid is 8**8 or larger. 

For example,

```python
def filter(tarinfo):
 tarinfo.uid = 100
 tarinfo.gid = 100
 return tarinfo

...
tar.add(name, filter=filter)
```

Will use 100 as the uid and gid instead of the current user's uid/gid.

### Linked PRs
* gh-102207
* gh-102230
* gh-102231

**Comment by corona10** [comment]
@colesbury 
I will try to introduce this issue into the internal OSS sprint as the good first bug.
I will delegate the issue to my mentees.

**Comment by uyw4687** [comment]
I'll take it :)

**Comment by corona10** [comment]
Thank you @uyw4687!
