### ISSUE TITLE
Remove yellow box from string documentation

### ISSUE THREAD

**Issue by Mariatta** [python/cpython#95685]
# Documentation

All the text in the `string` documentation is inside a yellow box, and is hard to read.
The other docs don't have the same problem.

We should remove the yellow box.

See url: https://docs.python.org/3/library/string.html

Sample screenshot: 
![Screen Shot 2022-08-04 at 3 17 44 PM](https://user-images.githubusercontent.com/5844587/182962218-3dfb90cd-b849-44ca-87cd-3773c268921b.png)

**Comment by AlexWaygood** [comment]
The same is happening in the `typing` docs: https://docs.python.org/3/library/typing.html

And the pickle docs: https://docs.python.org/3/library/pickle html

See:

- #91483 

(opened a while back, but started happening again yesterday or the day before)
