### ISSUE TITLE
ctypes: AttributeError: function 'DestroyIcon ' not found with WINFUNCTYPE prototype

### ISSUE THREAD

**Issue by hugochrist1** [python/cpython#95698]
# Bug report

The function DestroyIcon is not found when I use the WINFUNCTYPE prototype but it is found without.

This code raises an AttributeError
```
from ctypes import *
from ctypes import wintypes

DestroyIcon = WINFUNCTYPE(
	wintypes.BOOL,
	wintypes.HICON,
	)(('DestroyIcon ',windll.user32))
```
```
Traceback (most recent call last):
  File "Z:\Documents\tests\destroyicon_bug.py", line 4, in <module>
    DestroyIcon = WINFUNCTYPE(
AttributeError: function 'DestroyIcon ' not found
```

This code works.
```
from ctypes import *
from ctypes import wintypes

GetSystemMetrics = WINFUNCTYPE(wintypes.INT,wintypes.INT)(('GetSystemMetrics',windll.user32))

DestroyIcon = windll.user32.DestroyIcon
DestroyIcon.restype = wintypes.BOOL
DestroyIcon.argtypes = (wintypes.HICON,)
```

# Your environment

- CPython versions tested on: 3.10.4
- Operating system: Windows

**Comment by arhadthedev** [comment]
You accidentlally misput a space:

```cpp
	)(('DestroyIcon ',windll.user32))
                       ^^^
```

instead of

```cpp
	)(('DestroyIcon', windll.user32))
                       ^^^
```

**Comment by hugochrist1** [comment]
I  just noticed, sorry

**Comment by eryksun** [comment]
FYI, `DestroyIcon()` sets the thread's last error value, so you should pass `use_last_error=True` to [`WINFUNCTYPE()`](https://docs.python.org/3/library/ctypes.html#ctypes.WINFUNCTYPE). If the call fails, get the last error reliably with `ctypes.get_last_error()`, or get an `OSError` exception to raise with `ctypes.WinError(ctypes.get_last_error())`. Using FFI to call `GetLastError()` is kind of unreliable in a high-level scripting environment. It's completely unreliable when calling functions interactively in the REPL.

**Comment by hugochrist1** [comment]
Interresting, currently I use an `errcheck` function to raise an `OSError` with `ctypes.WinError`, so I should set `use_last_error=True` for it to correctly report the error ?

**Comment by eryksun** [comment]
`ctypes.WinError()` defaults to calling `GetLastError()` via FFI. It's better to configure the function with `use_last_error=True`, which captures the last error value in C. Then pass the captured error code explicitly via `ctypes.WinError(ctypes.get_last_error())`.

**Comment by hugochrist1** [comment]
Ok, thank you, I did not understand what `use_last_error` when I read the doc
