### ISSUE TITLE
"Embedding Python in Another Application" documentation examples use deprecated functions

### ISSUE THREAD

**Issue by vstinner** [python/cpython#95709]
Examples of the C API documentation should be updated to use the new PyConfig API, rather than deprecated functions like Py_SetProgramName():

* https://docs.python.org/dev/c-api/intro.html#embedding-python
* https://docs.python.org/dev/extending/extending.html
* https://docs.python.org/dev/extending/embedding.html

In the intro, this paragraph is outdated:

> The embedding application can steer the search by calling Py_SetProgramName(file) before calling [Py_Initialize()](https://docs.python.org/dev/c-api/init.html#c.Py_Initialize). Note that [PYTHONHOME](https://docs.python.org/dev/using/cmdline.html#envvar-PYTHONHOME) still overrides this and [PYTHONPATH](https://docs.python.org/dev/using/cmdline.html#envvar-PYTHONPATH) is still inserted in front of the standard path. An application that requires total control has to provide its own implementation of [Py_GetPath()](https://docs.python.org/dev/c-api/init.html#c.Py_GetPath), [Py_GetPrefix()](https://docs.python.org/dev/c-api/init.html#c.Py_GetPrefix), [Py_GetExecPrefix()](https://docs.python.org/dev/c-api/init.html#c.Py_GetExecPrefix), and [Py_GetProgramFullPath()](https://docs.python.org/dev/c-api/init.html#c.Py_GetProgramFullPath) (all defined in Modules/getpath.c).

**Comment by erlend-aasland** [comment]
See also:

- gh-88052
- gh-70702
- gh-68840
- gh-63352
- gh-42771

Perhaps we should mark those as superseded by this and actually update the docs :)

**Comment by erlend-aasland** [comment]
There are also slightly related issues:

- gh-83463
- gh-64423

**Comment by DarshitSolanki04** [comment]
If it is possible, I would like to help. Since I am learning, it would be a great learning opportunity for me. Probably I might need a little guidance.

**Comment by DarshitSolanki04** [comment]
If it is possible, I would like to help. And I might need a little guidance to know what to update exactly.

**Comment by ncoghlan** [comment]
When updating the embedding docs, the changes should be clear that the simple `Py_Initialize` and `Py_InitializeEx` configuration APIs are not deprecated: what's deprecated are the pre-init configuration API functions that rely on global variables to pass settings to the initialization functions. If embedders want non-default interpreter behaviour, they should switch over to the config struct based `Py_InitializeFromConfig` API.

**Comment by vstinner** [comment]
Sadly, I failed to find the bandwidth to update the doc. I created this issue as a TODO item, but my TODO list is full of more important stuff as usual, so I prefer to close it. If someone is volunteer, please go ahead, the old API is now deprecated!
