### ISSUE TITLE
The "with permission from edgedb" header is confusing for people trying to reuse the code

### ISSUE THREAD

**Issue by graingert** [python/cpython#95724]
I think Lib/asyncio/taskgroups.py should include the Apache license. The "with permission from edgedb" header is confusing for people trying to reuse the code

_Originally posted by @graingert in https://github.com/python/cpython/issues/95649#issuecomment-1206845457_

**Comment by graingert** [comment]
https://github.com/python/cpython/blob/main/Lib/asyncio/taskgroups.py#L1

**Comment by graingert** [comment]
I also think there's a few changes that were backported from CPython to edgedb and then back again which need the PSF copyright header, maybe?

**Comment by gvanrossum** [comment]
I specifically asked @1st1 what to do with the license/copyright notice from EdgeDb and he approved the current text. IIUC the EdgeDb CLA allows him to do that.

**Comment by gvanrossum** [comment]
@graingert Please see https://github.com/python/cpython/pull/95847 for Yury's suggested changes.
