### ISSUE TITLE
rename asyncio tests so they have readable names by adding a suffix to them

### ISSUE THREAD

**Issue by graingert** [python/cpython#95772]
> can we give the changed tests meaningful names and docstrings?

_Originally posted by @Tinche in https://github.com/python/cpython/pull/95761#pullrequestreview-1064468343_

**Comment by graingert** [comment]
There's a bunch of tests with names like test_context_1 test_context_2 or test_taskgroup_27b it's very difficult to work out how to fix them when they break

**Comment by graingert** [comment]
> Eventually we could do a separate cleanup PR that adds docstrings (actually for tests I prefer comments, since the unittest package does something funny with docstrings) and maybe add something to the name (e.g. test_taskgroup_08_cancellation_in_body) but I am loath to clean up just the changed tests -- it will look weird (PEP 8 has a rule about respecting the local style over almost everything else: "Consistency within one module or function is the most important").

**Comment by erlend-aasland** [comment]
Expanding the quote in https://github.com/python/cpython/issues/95772#issuecomment-1207777589, which quotes Guido's https://github.com/python/cpython/pull/95761#issuecomment-1207557189, since the first, and essential, part of Guido's post is missing:

> I know I let you do that in the past, but when we started comparing the code to the original in EdgeDb I realized that it would be better to keep the names and style consistent with the original.

This was a reaction to the following proposal:

> In the spirit of the old boy scouts rule, 'Always leave the campground cleaner than you found it', can we give the changed tests meaningful names and docstrings?


Suggesting to close this and instead follow the advice of adding _comments_.

**Comment by graingert** [comment]
@erlend-aasland apologies I wasn't aiming to misquote Guido here, just to track "the separate cleanup PR"

**Comment by erlend-aasland** [comment]
> @erlend-aasland apologies I wasn't aiming to misquote Guido here, just to track "the separate cleanup PR"

If you want to do the add-comments-cleanup, you should close this issue and create a new one which aims to do that specific cleanup; the title, the OP, and subsequent posts in _this_ issue are all about renaming test method names.

**Comment by Tinche** [comment]
I think someone mentioned leaving the original names as they are and just adding a suffix explaining the test. How bout that?

**Comment by graingert** [comment]
I think there may be some misunderstanding around what a rename is. To me adding a suffix eg test_taskgroup_08 into test_taskgroup_08_cancellation_in_body is a rename

**Comment by erlend-aasland** [comment]
Yes, and renaming was discouraged. Adding explanatory docstrings was encouraged, unless I misread the discussion.

**Comment by graingert** [comment]
The original suggestions made on the other PR was to remove the old name and make a brand new name

An issue was later discovered with this "renaming completely approach" that the tests no longer line up between the edgedb TaskGroup and the asyncio TaskGroup and actually lead to making determining the purpose of the test harder rather than easier (which was the opposite goal of renaming)

This ticket is tracking the project to rename the test items in a way that's compatible with this triple purpose to understand the intent when the test is seen in the test output (add a suffix)

**Comment by kumaraditya303** [comment]
This will cause more churn than benefit IMO, just creating a PR with suffixes isn't enough somebody needs to review the entire test to check if your suffix is even correct.  This isn't the best use of our time so I'll close this.
