### ISSUE TITLE
Functions in Itertools

### ISSUE THREAD

**Issue by NeginGit** [python/cpython#95770]
# Feature or enhancement

Introducing a function argument to itertools functions like "product" to stop the iterations on demand.

# Pitch

I encountered several situations when some functions in itertools module, such as products or combinations, took either so long or so much memory to finish. I think introducing an argument function to stop the inner iterations on demand would be so helpful.

# Previous discussion

**Comment by TeamSpen210** [comment]
All the functions in the itertools module are lazy, computing values one at a time as they're requested. If you want to stop them early, simply arrange for whatever is iterating to stop, or use `itertools.takewhile()` to cut off the iterator when the predicate fails.

**Comment by stevendaprano** [comment]
Hello and welcome @NeginGit 

When you created this issue, did you see the note that said "New features to Python should first be discussed elsewhere before creating issues on GitHub"? If not, what can we do to make that note more obvious?

If you have discussed this elsewhere, can you link to the discussion please?

**Comment by rhettinger** [comment]
You can limit the number of iterations with *islice()*.  That is a general approach that works well with all iterators and doesn't require modifying all of them with a limit.

     islice(product('abcd', repeat=100), 30)

**Comment by NeginGit** [comment]
Thank you all for your responses!

@stevendaprano, no unfortunately, this issue wasn't discussed elsewhere and I wasn't aware of the process. Sorry for the inconvenience.

@rhettinger, the issue is not only the number of the loops. Let's say the user needs to perform some operations on the products in each iteration and if the desired result is obtained, they need it to stop. Could you please let me know if there is a work around for that.

E.g., I need to run the following for n = 10. And I don't need it to create all the products and then slice them.

def generate_three_letter_strings(n):    
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    combinations = list(islice(product(alphabet, repeat=3), n))    
    result = [''.join(combination[:3])
        for combination in combinations]
    return result

**Comment by stevendaprano** [comment]
The bug tracker is not the place for asking for help. There are many 
forums you should go to to ask for help, such as Reddit's r/learnpython, 
or Python Discuss. You should try those first.

https://discuss.python.org/

But since you are here, the code you show does not create all the 
products and then slice it. That would be 

`list(product(alphabet, repeat=3))[:3]`

Both product and slice are iterators which yield one value at a time, so 
product stops as soon as islice has taken n values.
