### ISSUE TITLE
Assignment OR expressions fail on using lambda expressions

### ISSUE THREAD

**Issue by tomlin7** [python/cpython#95788]
# Bug report
The case is where if a variable is None or False, we need to set it to another value; in this specific case, a lambda expression. 

The if statement: 
```py
if b:
    a = b
else:
    a = c
```
can be shortened to:
```py
a = b or c
```
and is common in many codebases I have came across, its a lot cleaner too.

But when the secondary value here is a lambda expression, it fails to parse.
```py
event = event or lambda e: None
```
Now if the lambda is inside a parenthesized expression, it works well
```py
event = event or (lambda e: None)
```
I think the first result is not supposed to happen, the statement should be valid.

## Example & Output
```py
>>> foo = 0 or (lambda e: None)
>>> foo = 0 or lambda e: None
  File "<stdin>", line 1
    foo = 0 or lambda e: None
               ^^^^^^
SyntaxError: invalid syntax
>>>
```

# Your environment

- Python 3.10.3
- Windows 10 Home 21H2 (Build 19044.1826)
- [MSC v.1929 64 bit (AMD64)] on win32

---

- Python 3.9.5
- Ubuntu 22.04 LTS
- [GCC 9.3.0] on linux

**Comment by saito828koki** [comment]
@billyeatcookies 
Hello Billy,

Thank you for your bug report.

I think parentheses are necessary for this case.
```
b = None
c = 5
a = b or c # a = 5
```
Like the above example, multiple `or` expression can be used like this.
```
b = None
c = 5
d = 10
a = b or c or d # a = 5
a = b or d or c # a = 10
```
Then, think of an example of `lambda` expression that contains `or`.
```
b = None
a = b or lambda x: 0 or 5
```
This code can be interpreted in two ways.
```
a = b or (lambda x: 0) or 5 # a = <function <lambda> at 0x~~~> (which takes one argument named x and always returns 0)
```
```
a = b or (lambda x: 0) or 5 # a = <function <lambda> at 0x~~~> (which takes one argument named x and always returns 0 or 5)
```

Therefore, I think it is natural that `event = event or lambda e: None` cannot be parsed.

**Comment by billyeatcookies** [comment]
@saito828koki 
Hello, thank you for the reply!

I do agree to your opinion. It's true that this will create an ambiguous case in a multiple OR expression. I guess parenthesized expressions are more suited and less confusing here then.

Thank you for the explanation
