### ISSUE TITLE
RFC links are broken

### ISSUE THREAD

**Issue by JulianMaurin** [python/cpython#95789]
# Documentation

Hello  :wave: 
RFC hyperlinks present on https://docs.python.org are broken.

It's impacting the documentation version from `3.5.X` to `3.10.X` and any link to RFC.

Example:
- https://docs.python.org/3.10/library/urllib.parse.html
- https://docs.python.org/3.5/library/urllib.parse.html
- https://docs.python.org/3.10/library/email.utils.html?highlight=rfc#email.utils.decode_rfc2231

Links are targeting `https://tools.ietf.org/html/rfcXXXX.html` (redirecting to `https://www.rfc-editor.org/rfc/rfcXXXX.html.html`).

The correct address seems to be `https://www.rfc-editor.org/rfc/rfcXXXX.html` but I notice the usage of `https://datatracker.ietf.org/doc/html/rfcXXXX.html` on the python `3.12.X` documentation.

Not sure there is not already something about this issue, if it's the case sorry but I was not able to find it.

**Comment by hugovk** [comment]
The RFC links are built using the Sphinx RFC role, like ``` :rfc:`1808` ```

Sphinx itself expands these out to the full links.

I see Sphinx updated the RFC base URL in https://github.com/sphinx-doc/sphinx/pull/9858:

```diff
-    'rfc_base_url': 'https://tools.ietf.org/html/',`
+    'rfc_base_url': 'https://datatracker.ietf.org/doc/html/',
```

As mentioned in that PR:

> The tools.ietf.org subdomain is being wound down and services are moving to
datatracker.ietf.org. Links to RFC documents using the old subdomain are being
redirected to datatracker; this updates the configured rfc_base_url to
point to the current subdomain.
> 
> Discussion: [mailarchive.ietf.org/arch/msg/ietf/0n-6EXEmkTp3Uv_vj-5Vnm3o0bo](https://mailarchive.ietf.org/arch/msg/ietf/0n-6EXEmkTp3Uv_vj-5Vnm3o0bo/)

That change was released in Sphinx 4.4.0 (released [Jan 2022](https://pypi.org/project/Sphinx/4.4.0/)).

---

main/3.12 and 3.11 are already on sphinx==4.5.0:

* https://github.com/python/cpython/blob/main/Doc/requirements.txt
* https://github.com/python/cpython/blob/3.11/Doc/requirements.txt

But 3.10 is on sphinx==3.4.3:

* https://github.com/python/cpython/blob/3.10/Doc/requirements.txt

And 3.9 and 3.8 are on sphinx==2.4.4:

* https://github.com/python/cpython/blob/3.9/Doc/requirements.txt
* https://github.com/python/cpython/blob/3.8/Doc/requirements.txt

And 3.7 is on 2.3.1:

* https://github.com/python/cpython/blob/3.7/Doc/Makefile

**Comment by merwok** [comment]
Welcoming pull requests that add the RFC base URL setting to our sphinx config!

**Comment by JulianMaurin** [comment]
> Welcoming pull requests that add the RFC base URL setting to our sphinx config!

One my way :rocket:

**Comment by hugovk** [comment]
Ping also @rjsparks (author of the above-mentioned https://mailarchive.ietf.org/arch/msg/ietf/0n-6EXEmkTp3Uv_vj-5Vnm3o0bo/):

It looks like there's a problem with the RFC redirects. For example:

`https://tools.ietf.org/html/rfc123.html`

redirects to

`https://www.rfc-editor.org/rfc/rfc123.html.html`

Note the double `.html.html`

If I remove a surplus `.html` then it works:

`https://www.rfc-editor.org/rfc/rfc123.html`

@rjsparks - please could you check the redirects? Thank you!

**Comment by JulianMaurin** [comment]
> Ping also @rjsparks (author of the above-mentioned [mailarchive.ietf.org/arch/msg/ietf/0n-6EXEmkTp3Uv_vj-5Vnm3o0bo](https://mailarchive.ietf.org/arch/msg/ietf/0n-6EXEmkTp3Uv_vj-5Vnm3o0bo/)):
> 
> It looks like there's a problem with the RFC redirects. For example:
> 
> `https://tools.ietf.org/html/rfc123.html`
> 
> redirects to
> 
> `https://www.rfc-editor.org/rfc/rfc123.html.html`
> 
> Note the double `.html.html`
> 
> If I remove a surplus `.html` then it works:
> 
> `https://www.rfc-editor.org/rfc/rfc123.html`
> 
> @rjsparks - please could you check the redirects? Thank you!

It seems that the problem has already been solved. I assume that something has been done about the redirection? 
If it's the case, I'm interested about what was the fix, thanks

**Comment by rjsparks** [comment]
The redirect rule needed tuning.

**Comment by merwok** [comment]
Thanks for fixing it and letting us know!

Keeping this ticket open for PRs, we might as well generate canonical links and avoid redirections.
Links in people’s browsers may change from visited to unvisited, but I don’t think it’s a concern here.

**Comment by ambv** [comment]
I don't think this should be addressed in security fixes-only branches as they don't include regular documentation updates. As such, I think this is fixed. Thanks, all! ✨ 🍰 ✨
