### ISSUE TITLE
Future type annotations do not allow type aliases with built-in types

### ISSUE THREAD

**Issue by plinss** [python/cpython#95805]
# Bug report

When using `from __future__ import annotations` in Python 3.7 or 3.8, I'm unable to use built-in types in type aliases.

e.g.
```
from __future__ import annotations

def foo(x: dict[str, str]) -> None:
	pass

Bar = dict[str, str]

def bar(x: Bar) -> None:
	pass
```

works fine in Python 3.9+ (with or without the `from __future__` import), but fails with `TypeError: 'type' object is not subscriptable` on line 6 (`Bar = dict[str, str]`) in 3.7 or 3.8.

# Your environment

- Python 3.7
- Python 3.8
- MacOS
- Windows

**Comment by ericvsmith** [comment]
Sorry, but 3.7 and 3.8 no longer get bug fixes.
