### ISSUE TITLE
Add simple dark mode to http.server directory list and error pages

### ISSUE THREAD

**Issue by marvinruder** [python/cpython#95812]
# Feature or enhancement

A simple dark mode in http.server’s directory list and error pages, using white font on black background.

# Pitch

To make the directory lists and error pages of the simple HTTP server from `http.server` more readable in dark environments, a simple dark mode support using a few lines of CSS could enhance user experience. I propose the following CSS code, which uses white font on black background when requested by the browser:

```
<style type="text/css">
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: #fff;
  }
}
</style>
```

# Previous discussion

see https://discuss.python.org/t/add-simple-dark-mode-to-http-server-directory-list/18081

**Comment by serhiy-storchaka** [comment]
The listing does not contain any hardcoded colors and should not. If your browser is not able to show a simple page with default style, it is a problem either with your configuration or with the browser. It is not Python issue.
