### ISSUE TITLE
load aifc file that created by the MacOS say command error unsupported compression type

### ISSUE THREAD

**Issue by louishot** [python/cpython#95829]
# Bug report
Hi guys,

I'm trying to merge files that created by the MacOS say command but getting an error.
is the same problem with https://github.com/python/cpython/issues/74263 ?

```
File "/Users/louis/.conda/envs/test/lib/python3.9/aifc.py", line 501, in _read_comm_chunk
    raise Error('unsupported compression type')
aifc.Error: unsupported compression type
```

`$ say -v Tom -r 100 -o ./files/ability_en "ability"`

My app
```
import aifc
f = aifc.open("files/ability_en.aiff", 'rb')
print(f.getnframes())
print(f.getparams())
```

Debug output
print(self._compname)
`b'Linear PCM, 16 bit big-endian signed integer'`

# Your environment
python3.9

- CPython versions tested on: python3.9
- Operating system and architecture: MacOS 12.3.1 (21E258) M1

**Comment by louishot** [comment]
All right I adding --file-format in the say command 
`say -v Tom -r 100 -o ./files/ability_en --file-format=AIFF "ability"`
Looks like mac use PCM formant by default but given a AIFF extension name

**Comment by mdboom** [comment]
Thanks for the report.  Given that you seem to have found a solution, I'll close this bug.  Feel free to reopen it if I misunderstood.

**Comment by erlend-aasland** [comment]
Also note that the `aifc` module is deprecated as of Python 3.11, slated for removal in Python 3.13. See PEP-594 for more details.
