### ISSUE TITLE
Inaccurate emulation of _PyType_Lookup() in the Descriptor HOWTO

### ISSUE THREAD

**Issue by iyume** [python/cpython#95822]
# Documentation

Doc link: https://docs.python.org/3.10/howto/descriptor.html#invocation-from-an-instance

Source: https://github.com/python/cpython/blame/eb81c1aea16914347919745e843c982ed831a9fb/Doc/howto/descriptor.rst#L585-L601

The code example is bad at https://github.com/python/cpython/blame/eb81c1aea16914347919745e843c982ed831a9fb/Doc/howto/descriptor.rst#L589

`getattr(objtype, name)` will go through `descriptor.__get__`.

Code Snippet:

```python
class A:
    def __get__(self, obj, objtype):
        return obj, objtype

class B:
    a = A()

print(B().a)
# (<__main__.B object at 0x7ff56d0915e0>, <class '__main__.B'>)
print(B.a)  # same as getattr
# (None, <class '__main__.B'>)
```

## Solution

Using `__dict__` (or vars) instead of `getattr`:

```python
print(vars(B)['a'])
# <__main__.A object at 0x7ff56cfef2b0>
```

**Comment by rhettinger** [comment]
Thanks for the bug report.  I'm thinking about how to approach making the code correct without impacting the understandability of an already complex function. Ideally, I want something equivalent to but more concise than this:


      # Emulate the name search in typeobject.c/_PyType_Lookup()
      cls_var = null
      for base in objtype.__mro__:
          if name in vars(base):
              cls_var = vars(base)[name]
              break

Here's another variant that would work but would entail an import and prerequisite knowledge:

     cls_var = ChainMap(*(vars(base) for base in objtype.__mro__)).get(name, null)

Also, I want to add tests to cover your example and to cover why the fix proposed in the PR is incorrect.

Will look at this again over the next few days.  I would like the name search to be accurate, simple, understandable, and not distracting from the overall flow of the function.

**Comment by rhettinger** [comment]
Thanks for the report. This is fixed now.
