### ISSUE TITLE
Ambiguity in behavior of ArgumentParser prefix_chars when same flag is specified with different prefixes

### ISSUE THREAD

**Issue by joshnatis** [python/cpython#95836]
## Environment
```
$ python --version
Python 3.8.10
$ uname -a
Linux 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Description
It seems that flags specified with different prefixes but the same 'name' (for lack of a better word) are treated as one flag.

## Example
```python
# example.py
import argparse

parser = argparse.ArgumentParser(prefix_chars='-+')
parser.add_argument('-e', metavar='<example>', action='append')
parser.add_argument('+e', metavar='<example>', action='append')
args = parser.parse_args()

print(args)
```
```sh
$ python example.py -e hello1 +e hello2
Namespace(e=['hello1', 'hello2'])
```

I was kind of hoping that somebody had thought of a smart way of treating them as two distinct flags : ). Regardless, I don't see anything about this on https://docs.python.org/3/library/argparse.html#prefix-chars, so I'm filing this as a bug in the documentation. It seems like a nitty detail but the page advertises itself as being thorough:
> This page contains the API reference information. For a more gentle introduction to Python command-line parsing, have a look at the [argparse tutorial](https://docs.python.org/3/howto/argparse.html#id1).

### Linked PRs
* gh-125376
* gh-125642
* gh-125643

**Comment by najmiehsa** [comment]
I work on this issue.

**Comment by serhiy-storchaka** [comment]
Prefix character has nothing to do with this. These options do the same because they are defined the same way.

I encountered such problem several times. You want to collect values in the _same_ list, but with some tags depending on the option. Usually this is `'--include'`/`'--exclude'`, but you write it as `'+e'`/`'-e'`.

One way is to use a custom action. I used this in [`Lib/test/libregrtest/cmdline.py`](https://github.com/python/cpython/blob/165ed68c26759b817388add52a7aa2d26755d451/Lib/test/libregrtest/cmdline.py#L188):

```py
class FilterAction(argparse.Action):
    def __call__(self, parser, namespace, value, option_string=None):
        items = getattr(namespace, self.dest)
        items.append((value, self.const))
...
    group.add_argument('-m', '--match', metavar='PAT',
                       dest='match_tests', action=FilterAction, const=True,
                       help='match test cases and methods with glob pattern PAT')
    group.add_argument('-i', '--ignore', metavar='PAT',
                       dest='match_tests', action=FilterAction, const=False,
                       help='ignore test cases and methods with glob pattern PAT')
```

But now I see that it would be easier to do with a custom type converter. Modifying your example:

```py
import argparse
parser = argparse.ArgumentParser(prefix_chars='-+')
parser.add_argument('-e', metavar='<example>', action='append', type=lambda x: ('-', x))
parser.add_argument('+e', metavar='<example>', action='append', type=lambda x: ('+', x))
print(parser.parse_args('-e hello1 +e hello2'.split()))
```
The output is:
```
Namespace(e=[('-', 'hello1'), ('+', 'hello2')])
```

**Comment by serhiy-storchaka** [comment]
This could be added to the tutorial as an example of using custom type converter or two options with the same `dest`.

**Comment by savannahostrowski** [comment]
Agreed - I'm in the process of reworking the docs/tutorial to remove duplicative examples etc. I'll self-assign and make sure that this is incorporated.
