### ISSUE TITLE
The str.format feature — "Accessing arguments’ items" failed, when using negative indices.

### ISSUE THREAD

**Issue by weipeng1999** [python/cpython#95846]
# Bug report

It is a TypeError caused by following the example "Accessing arguments’ items" in document "https://docs.python.org/3/library/string.html#formatspec" but changing the indices to the negative. Here is my code and result:
```python
>>> coord = (3, 5)
>>> 'X: {0[0]};  Y: {0[1]}'.format(coord) # OK
'X: 3;  Y: 5'
>>> 'X: {0[0]};  Y: {0[-1]}'.format(coord) # failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple indices must be integers or slices, not str
```

# Your environment

- CPython versions tested on: Python 3.10.6
- Operating system and architecture: 
- - OS: Arch Linux x86_64
- - Host: HP ProBook 455 G8 Notebook PC 
- - Kernel: 5.19.0-zen1-1-zen

**Comment by JelleZijlstra** [comment]
In the reference section you cited, there is nothing suggesting negative indices are supported. An `element_index` is either a `digit+` or an `index_string`; the former is interpreted as a numeric index, the latter as a string. Your example behaves as documented.

Changing this behavior would be a backward compatibility break, so we're unlikely to do it, especially since a better alternative is available: just use f-strings.

**Comment by weipeng1999** [comment]
#

> In the reference section you cited, there is nothing suggesting negative indices are supported. An `element_index` is either a `digit+` or an `index_string`; the former is interpreted as a numeric index, the latter as a string. Your example behaves as documented.
> 
> Changing this behavior would be a backward compatibility break, so we're unlikely to do it, especially since a better alternative is available: just use f-strings.

Well, but it also do not tell people that this only support digit+! I think at least we need update the document to explicitly tell people this limit...

**Comment by ericvsmith** [comment]
The documentation at https://docs.python.org/3/library/string.html#format-string-syntax does say it only supports `digit+1`:
```
replacement_field ::=  "{" [field_name] ["!" conversion] [":" format_spec] "}"
field_name        ::=  arg_name ("." attribute_name | "[" element_index "]")*
arg_name          ::=  [identifier | digit+]
attribute_name    ::=  identifier
element_index     ::=  digit+ | index_string
index_string      ::=  <any source character except "]"> +
conversion        ::=  "r" | "s" | "a"
format_spec       ::=  <described in the next section>
```

It says that `element_index` is either `digit+`, or an `index_string`. I suppose that the docs only hint at `digit+` being used as a numeric index. I'd accept a PR that makes that clearer.

**Comment by makukha** [comment]
Can we reopen this feature? It continues to mislead users:
https://stackoverflow.com/questions/78997513/why-is-there-typeerror-string-indices-must-be-integers-when-using-negative-in

I could propose a documentation PR as a quick fix.
