### ISSUE TITLE
 Cannot use concurrent.futures.ThreadPoolExecutor() within a loop

### ISSUE THREAD

**Issue by Geek4ray** [python/cpython#95875]
Cannot use concurrent.futures.ThreadPoolExecutor() within a loop

Cannot use concurrent.futures.ThreadPoolExecutor() within a for loop, it dosent work after first iteration.

![image](https://user-images.githubusercontent.com/42889493/184069603-aa3704ef-1c7b-461e-b156-71fda5790dcb.png)

**Comment by graingert** [comment]
@Geek4ray what do you mean when you say doesn't work? There's a green tick in your notebook cell.

Can you make a copy/pastable report that I can run myself with the output?

It looks like `args` is a generator here, and so can only be iterated once. You could use a list comprehension `args = [(a, 1, 2) for a in c]` instead, or move the generator into the body of your loop

**Comment by kumaraditya303** [comment]
You can ask these questions on https://discuss.python.org/c/users/7, this bug tracker is for bugs in CPython.
