### ISSUE TITLE
posixmodule.c: osdefs.h inclusion should not depend on compiler

### ISSUE THREAD

**Issue by TheShermanTanker** [python/cpython#95896]
osdefs.h should not be defined by the compiler used, this small patch moves an inclusion out of an _MSC_VER check into an MS_WINDOWS one to better honour the assumption that compiler and OS macros are independent

### Linked PRs
* gh-95897
* gh-99788
* gh-99789

**Comment by kumaraditya303** [comment]
Thanks for the PR.
