### ISSUE TITLE
compiler's eliminate_empty_basic_blocks does not remove empty block if it is the last in the compilation unit

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#95922]
Because of the ``next->b_next`` in the loop condition, this does not remove an empty basic block at the end. I put an assert and saw that this can happen. 

```
     for (basicblock *b = entryblock; b != NULL; b = b->b_next) {
         basicblock *next = b->b_next;
        if (next) {
            while (next->b_iused == 0 && next->b_next) {
                next = next->b_next;
            }
            b->b_next = next;
         }
     }
```

**Comment by markshannon** [comment]
If the last block is empty, then it must be unreachable. So is this a problem?

**Comment by iritkatriel** [comment]
There probably isn't an actual problem in generated code, but it means we can't assume that there are no empty blocks in the b_next list, which we might be tempted to do, so it can create the kind of chaos that leads to bugs.

I found this through the new unit tests I'm writing, because the actual basicblocks didn't match the ones expected.

**Comment by iritkatriel** [comment]
Empty blocks are not really a problem anywhere - they cause no code to be emitted, so we could not remove any of them.
