### ISSUE TITLE
Exception ignored in: <function WeakSet.__init__.<locals>._remove

### ISSUE THREAD

**Issue by ssergiienko** [python/cpython#95959]
# Bug report

Interpreter ignores KeyboardInterrupt sometimes. Code is single threaded, but heavy concurrent with asyncio.

Currently I observed few a bit different tracebacks:

```
^CException ignored in: <function WeakSet.__init__.<locals>._remove at 0x7f1b88f96560>
Traceback (most recent call last):
  File "/usr/lib/python3.10/_weakrefset.py", line 39, in _remove
    def _remove(item, selfref=ref(self)):
KeyboardInterrupt:
```
and

```
^CException ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f9a363b2290>
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 106, in remove
    def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
KeyboardInterrupt:
```

and

```
^CException ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f3e4829c3a0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 370, in remove
    def remove(k, selfref=ref(self)):
KeyboardInterrupt:
```

I've seen https://github.com/python/cpython/issues/86190 but decided not to reopen it because
- current issue is for a latest python
- a bit different traceback (at least one of them)
- not related to Ansible in any way

# Your environment

- CPython versions tested on: Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
- Operating system and architecture: Archlinux

**Comment by iritkatriel** [comment]
This is not a bug. See https://docs.python.org/3/library/weakref.html#weakref.ref

**Comment by ssergiienko** [comment]
Thanks for your feedback!

Looks like you are referring specifically to the:
> Exceptions raised by the callback will be noted on the standard error output, but cannot be propagated; they are handled in exactly the same way as exceptions raised from an object’s __del__() method. 

I understand that there are probably good technical reasons why that was not possible to do in other way, but I still don't understand what me (as an end-user) should do with that problem, because it's not my code use `weakref/__del__` directly, it's something in the stdlib (asyncio most likely), so I can't do anything with that (or I'm missing something?).

Maybe it's more like a documentation issue, which misses the part "... and what to do with that?".

Could you please share maybe some best practice / recommendations on how to deal with that? Because "just accept that it's like that" doesn't look like a solution). If there is anything that I have to add to my code to make it work properly (ability to stop program with exactly one Ctrl+C instead of hitting it 10 times till exception finally propagated to the right place), I will be really grateful for such recommendations and I believe they will be useful not only for me, thanks in advance!

**Comment by iritkatriel** [comment]
See https://docs.python.org/3/library/sys.html#sys.unraisablehook
