### ISSUE TITLE
Add a test for `csv.register_dialect` with both `Dialect` and `kwargs`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#95950]
# Feature or enhancement

Python docs state:

```
csv.register_dialect(name[, dialect[, **fmtparams]])

    Associate dialect with name. name must be a string. The dialect can be specified either by passing a sub-class of [Dialect](https://docs.python.org/3/library/csv.html#csv.Dialect), or by fmtparams keyword arguments, or both, with keyword arguments overriding parameters of the dialect. For full details about dialects and formatting parameters, see section [Dialects and Formatting Parameters](https://docs.python.org/3/library/csv.html#csv-fmt-params).
```

Notice this part:

> or both, with keyword arguments overriding parameters of the dialect

But, this is not ever tested in `test_csv`. 
Link: https://github.com/python/cpython/blob/f235178beccf5eb5b47e770240f32d9ba24b26fd/Lib/test/test_csv.py#L432-L449

# Pitch

Let's add a test that ensures that `register_dialect` do work as documented.

**Comment by JelleZijlstra** [comment]
PRs were merged, thank you!
