### ISSUE TITLE
Ref target labels for except/except*/finally not located precisely

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/cpython#95975]
As originally noticed by @ezio-melotti on #95937 , the ref target labels for the `except`, `except*` and `finally` keywords are located at the top of the [`try` statement section in the Compound Statements][(https://docs.python.org/3.11/reference/compound_stmts.html#the-try-statement) reference; however, they are actually discussed at specific points sometimes several pages down in the lengthy section. Therefore, the targets should be moved to more precise locations immediately prior to the introduction of the relevant keyword.

~It would also be nice to make the section either to navigate with sub sections rather than one big long section, but that is considered outside the immediate scope of this proximate issue.~ It turns out this is required to get `:keyword:` to work, and the section is already organized by clause, so it makes sense just to add them.

**Comment by CAM-Gerlach** [comment]
The plot thickens—for no obvious reason, it seems `:keyword:` simply won't work with ref target labels that don't precede a section header (or at least some named object), which is presumably why they were put there in the first place. However, given it would make navigating what has become a quite long section easier, and requires no textual changes given the section is already strongly organized by clause type, I can just add the appropriate subsection headers to fix this, given it improves both internal and external navigation.

**Comment by najmiehsa** [comment]
@CAM-Gerlach hi, can I work on this issue? please.

**Comment by CAM-Gerlach** [comment]
@najmiehsa Sorry, I already submitted #95976

**Comment by hauntsaninja** [comment]
Thanks all!
