### ISSUE TITLE
The example using match keyword isn't complete

### ISSUE THREAD

**Issue by Aljumaily** [python/cpython#95986]
# Documentation

The [Other Key Features](https://docs.python.org/3/whatsnew/3.10.html#other-key-features) in [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#what-s-new-in-python-3-10) contains the following code snippet:
```
from enum import Enum
class Color(Enum):
    RED = 0
    GREEN = 1
    BLUE = 2

match color:
    case Color.RED:
        print("I see red!")
    case Color.GREEN:
        print("Grass is green")
    case Color.BLUE:
        print("I'm feeling the blues :(")
```

However, the variable `color` is unknown, hence, `NameError: name 'color' is not defined` is shown. The solution is the declare a `color` variable and assign it any of the `Color` enum values, like so:

```
from enum import Enum
class Color(Enum):
    RED = 0
    GREEN = 1
    BLUE = 2

color = Color.BLUE

match color:
    case Color.RED:
        print("I see red!")
    case Color.GREEN:
        print("Grass is green")
    case Color.BLUE:
        print("I'm feeling the blues :(")
```

**Comment by hauntsaninja** [comment]
Looks like a PR was merged for this
