### ISSUE TITLE
Recommendations for resolving dependency issues

### ISSUE THREAD

**Issue by showkeyjar** [python/cpython#95990]
# Feature or enhancement

(A clear and concise description of your proposal.)
When packaging, extract the methods in the dependent package and place them in a separate directory.

# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

For example, I develop a package called 'smalltool', it depend `pandas groupby` function, 

so when packaging 'smalltool', it'll copy `pandas groupby` function to 'smalltool_deps' dir, 

and then when other people install 'smalltool', the install progress will copy 'smalltool_deps' either,

then, no more packet conflicts!

# Previous discussion

**Comment by hugovk** [comment]
Thanks for the suggestion! I don't think this belongs to CPython itself, you're probably better off posting in the Packaging category on Discourse:

https://discuss.python.org/c/packaging/14
