### ISSUE TITLE
Mistake in python documentation related to escape sequences

### ISSUE THREAD

**Issue by anupkaushal97** [python/cpython#95994]
![Escape_Sequences](https://user-images.githubusercontent.com/103025861/184623417-c0b6d196-694d-4646-8cda-8d2a32ef7e27.png)
There is mistake related to escape sequences in Python documentation 
page link: https://docs.python.org/3/reference/lexical_analysis.html#strings

it shows "\newline" with meaning "Backslash and newline ignored" while using this has no effect in code 

`print('Hello \newline World!')`

outputs: Hello 
ewline World!

**Comment by ronaldoussoren** [comment]
The documentation could be clearer here, but what's meant is a literal newline, that is:

s = "foo \
bar"

Here the backslash and the newline after it are ignored.

**Comment by ezio-melotti** [comment]
Fixed, thanks for the report!

- [x] #96066 
- [x] #96321 
- [x] #96360
