### ISSUE TITLE
Itertools tee doc wording mistake

### ISSUE THREAD

**Issue by MrSuspicious0** [python/cpython#96039]
On the section for `tee` on the itertools documentation it says "A RuntimeError may be raised when using simultaneously iterators returned by the same tee" i do believe this should say "A RuntimeError may be raised when simultaneously using iterators returned by the same tee"

**Comment by rhettinger** [comment]
Would you like to make a PR for this?

**Comment by MrSuspicious0** [comment]
PR made, thanks Raymond.

**Comment by MrSuspicious0** [comment]
PR made, thanks Raymond
