### ISSUE TITLE
Tweak asyncio.Runner loop_factory docs to emphasize that the default case *does* call `set_event_loop()`

### ISSUE THREAD

**Issue by graingert** [python/cpython#96036]
> Whatever gives users the best guidance. I searched for code that uses `Runner(loop_factory=...)` and there is one case apart from `test_runners.py`: in `test_asyncio/test_subprocess.py` it is used as `loop_factory=asyncio.new_event_loop` specifically to prevent the watcher to be set (since the test sets its own watcher).

I would emphasize that the default case *does* call `set_event_loop()` and implies attaching the watcher (if there is one!) to the loop; it's fine to suggest that `loop_factory` should be used only if this is undesired.

_Originally posted by @gvanrossum in https://github.com/python/cpython/pull/95979#discussion_r946971337_

**Comment by kumaraditya303** [comment]
@graingert Are you planning to work on a PR for this?

**Comment by kumaraditya303** [comment]
Are you still interested in working on rewording this to your liking? If not I am inclined to close this, for me the existing docs added by myself is sufficient.
