### ISSUE TITLE
Some opcodes leave frame->prev_instr in an incorrect state

### ISSUE THREAD

**Issue by tom-pytel** [python/cpython#96049]
# Bug report

Opcodes which have caches (specifically adaptive calls) leave `frame->prev_instr` pointing to the last byte of the cache instead of the actual last instruction.

# Your environment

v3.11.0rc1
Linux tom-VirtualBox 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brandtbucher** [comment]
This is intentional. See this comment in the code: https://github.com/python/cpython/blob/d8c07f8cb4eebbe4ed0f76ba98024313f76a181c/Include/internal/pycore_frame.h#L58-L62

For my own understanding, how has this negatively affected you?

CC @markshannon

**Comment by tom-pytel** [comment]
> For my own understanding, how has this negatively affected you?
> 
> CC @markshannon

Ok, I missed that quote, just figured since all other instructions left the pointer at the last instruction these should as well since otherwise the location of the original instruction is unrecoverable (due to random data in cache area).

This is problematic for us because we have an error reporting fork of the cpython interpreter as a product and after an exception we want to get the instruction which caused it. This particular patch leaves the last instruction pointer always valid but if it is not an issue and not desirable for the base cpython implementation then I will close the PR and just keep the change on our branch.

**Comment by brandtbucher** [comment]
> Ok, I missed that quote, just figured since all other opcodes left the pointer at the last instruction these should as well since otherwise the location of the original instruction is unrecoverable (due to random data in cache area).

It is recoverable, just with a bit of effort. A call to `PyCode_GetCode` (or accessing the `co_code` member in the Python layer) will give you a copy of the bytecode with the caches cleared. It's safe to scan backwards over this to find the last "real" instruction.
