### ISSUE TITLE
extra space in the str.split doc

### ISSUE THREAD

**Issue by YousufSMahmoud** [python/cpython#96056]
# Documentation
https://docs.python.org/3/library/stdtypes.html#str.split

in the doc its written ```
str.split(sep=None, maxsplit=- 1)``` an extra space after ```-```
which is legal but not the best practices, 
I would like if you could fix it to 
str.split(sep=None, maxsplit= -1)
``` 
so instead of ```- 1``` it became ```-1```

**Comment by ericvsmith** [comment]
I'd just drop the space entirely, and make it `maxsplit=-1`. Same for `rsplit()`. This would match the style elsewhere in the file.

**Comment by zware** [comment]
This looks like a rendering error; [line 2031 of the source](https://github.com/python/cpython/blame/main/Doc/library/stdtypes.rst#L2031) is `.. method:: str.split(sep=None, maxsplit=-1)`.

**Comment by ericvsmith** [comment]
Good catch, @zware !

I see the HTML as `<span class="o">=</span><span class="default_value">- 1</span>`, so it does seem like a rendering issue.

**Comment by ezio-melotti** [comment]
This is already fixed in Sphinx:
* https://github.com/sphinx-doc/sphinx/issues/10550
* https://github.com/sphinx-doc/sphinx/issues/10551

Once we upgrade to Sphinx 5.1 it will be fixed here too.
