### ISSUE TITLE
faulthandler prints "Segmentation fault" on non SIGSEGV signal deaths

### ISSUE THREAD

**Issue by gpshead** [python/cpython#96055]
# Bug report

The faulthandler module has a hard coded fixed small list of signals that it knows the name of. For anything not in this list it uses the final entry in its table as the value to print in the error message. This is misleading.

Ex: trigger a SIGTRAP in a Python process with faulthandler enabled.

The process exits properly indicating the correct death signal to the OS (Linux on aarch64 in this case), but the message emitted by Python is confusingly:

```
Fatal Python error: Segmentation fault

Current thread 0x0000005504ffa450 (most recent call first):
...
```

The cause is the `faulthandler_handlers` array of structs in https://github.com/python/cpython/blob/main/Modules/faulthandler.c#L130

We should expand that to include more deadly signals.  SIGTRAP led someone to notice it here.  When we don't have the signal listed in the table it'd be nicer to emit an error message saying that rather than mislabelling it.

* PR: gh-99162

* PR: gh-99179

* PR: gh-99178

**Comment by corona10** [comment]
@gpshead Can we close the issue or do we need more action?

**Comment by gpshead** [comment]
Good enough. Thanks!
