### ISSUE TITLE
count() affects data in demo().The scope of the variable has been changed.

### ISSUE THREAD

**Issue by LeroyK111** [python/cpython#96060]
# Bug report

```
"""
Python version: 3.10.6 64bit
The problem: count() affects data in demo().The scope of the variable has been changed.
"""


def count(dt: list):
    # dt.pop(0)
    # dt.remove(0)
    # dt.clear()
    del dt[0]


def demo():
    data = [0, 1, 2, 3, 4, 5, 6, 7, 9, 0, 0]
    while True:
        count(data)
        print(data)
        # count1: [1, 2, 3, 4, 5, 6, 7, 9]
        # count2: [2, 3, 4, 5, 6, 7, 9]
        # ....


if __name__ == '__main__':
    demo()
```

# Your environment

- CPython versions tested on: Python 3.10.6 64bit
- Operating system and architecture: Windows11 22H2 22622.575 . AMD Ryzen 7 5800H with Radeon Graphics.

**Comment by ericvsmith** [comment]
What does "variable domain problem" mean? Also, I don't see any recursion in your code.

Please show what behavior you're getting, and what behavior you're expecting. Otherwise we cannot help you.

**Comment by LeroyK111** [comment]
Sorry, the description is not accurate enough, I have corrected the problem again.

**Comment by serhiy-storchaka** [comment]
It is not a bug, it works as it is supposed to do. It is not the scope of the variable.

**Comment by eryksun** [comment]
The expression `count(data)` references the `data` object as `dt` in the scope of the call. It's the exact same object, not a copy.
