### ISSUE TITLE
Lib/inspect.py: Avoid wild replacement in formatannotation

### ISSUE THREAD

**Issue by iyume** [python/cpython#96073]
# Bug report

Source: https://github.com/python/cpython/blob/91afe66707237558d808aeca4683d0822aa0511e/Lib/inspect.py#L1449-L1458

An error replacement happens in:

```python
repr(annotation).replace('typing.', '')
```

Suppose that I define a class or Protocol under `foo/typing.py`:

```python
class A:
    pass
```

Then `Union[int, A]` will turn to `Union[int, foo.A]`, but expected result is `Union[int, foo.typing.A]`

Any module with suffix like `xxtyping` will be replaced, such as `nptyping`.

# Solution

Replace the line to:

```python
        def repl(match):
            text = match.group()
            if text.startswith('typing.'):
                    return text[len('typing.'):]
            return text
        return re.sub(r'[\w\.]+', repl, repr(annotation))
```

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
