### ISSUE TITLE
Lib/typing.py Missing field _name for _AnnotatedAlias

### ISSUE THREAD

**Issue by iyume** [python/cpython#96079]
# Bug report

Relate to: https://github.com/python/cpython/blob/main/Lib/typing.py#L2102

_AnnotatedAlias should give `name="Annotated"` to _GenericAlias

The cpython main branch add the `__getattr__` to define a different behaviour from _GenericAlias

I wonder if this is a bug.

To perform a runtime check, I can only use `sys.version_info >= (3, 9) and isinstance(obj, _AnnotatedAlias)`

**Comment by HACKED-need-HELP** [comment]
Hackers are back in my account as the past 20 minutes. Did any one see a change

**Comment by AlexWaygood** [comment]
@python/organization-owners, can you block @HACKED-need-HELP as a spammer, please? They seem to be posting bizarre messages like this

**Comment by AlexWaygood** [comment]
(Reopened the issue by accident!)
