### ISSUE TITLE
The os.sched_yield() implementation in posixmodule.c doesn't release the GIL

### ISSUE THREAD

**Issue by FilipDepta** [python/cpython#96078]
I've reviewed the `main` branch and the GIL isn't released: https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L7060

The forum thread: https://discuss.python.org/t/does-the-os-sched-yield-release-the-gil/18301

Expected: The GIL is released before sched_yield() and acquired after that.

**Comment by eryksun** [comment]
Interestingly, `os.sched_yield()` was added [11 years ago](https://github.com/python/cpython/issues/56864), and no one has ever mentioned this oversight. I guess the users, if any[^1], are satisfied that it can only yield execution to ready threads that aren't waiting to acquire the GIL. The behavior was never documented, so I'm tagging this as a bug in 3.10+. 

[^1]: The man page for `sched_yield()` in Linux says the behavior is "unspecified" if the process isn't using a deterministic realtime scheduler such as `SCHED_FIFO` (first in, first out) or `SCHED_RR` (round robin). I'm guessing it's not common for Python applications to use realtime scheduling.

**Comment by FilipDepta** [comment]
> [...] using a deterministic realtime scheduler such as `SCHED_FIFO` (first in, first out) or `SCHED_RR` (round robin). I'm guessing it's not common for Python applications to use realtime scheduling. [↩](#user-content-fnref-1-9000aa05ea4bcc8c0148dce25448788c)

That is exactly what I do - using `SHED_FIFO` with two threads, I sometimes call `os.sched_yield()` to ensure that the second thread was executed as freshly as possible.

Maybe it's a good idea to add an annotation in docs for older cpythons that os.sched_yield() doesn't release the GIL?
