### ISSUE TITLE
Note for "Boolean Operations — and, or, not" wrongly suggests priority as syntax error reason

### ISSUE THREAD

**Issue by Gnudini** [python/cpython#96103]
In section [Boolean Operations — and, or, not](https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not) there's Note 3 saying: 

> <html>
> <body>
> 
> 
> <code class="docutils literal notranslate"><span class="pre">not</span></code> has a lower priority than non-Boolean operators, so …, and <code class="docutils literal notranslate"><span class="pre">a</span> <span class="pre">==</span> <span class="pre">not</span> <span class="pre">b</span></code> is a syntax error.
> 
> 
> </body>
> </html>

This mistakenly suggests that the reason for `True == not False` constituting a syntax error had to do with operator priority. If that were the case, the expression `2 ** - 1` would yield a syntax error as well, which of course it doesn't. Priority never causes an operator to be drawn in in place of an operand.

The true reason for `True == not False` being a syntax error is that there exists no syntax rule that would produce a [comparison][1] therefrom, since

>comparison    ::=  or_expr (comp_operator or_expr)*

\- i. e. after the comp_operator `==` an [or_expr][2] must follow, which includes an xor_expr, an and_expr, a [shift_expr][3], an a_expr, an [m_expr][4], a [u_expr][5], a [power][6]…, but no [not_test][7].

By comparison, the priority-wise similar construct `2 ** - 1` in accordance with the power rule

>power ::=  (await_expr | primary) ["**" u_expr]

has u_expr following the power operator `**`, thus allowing `- x` on the right hand side.

This wrong impression could be avoided by removing the subclause "_, and `a == not b` is a syntax error_" from the note.

  [1]: https://docs.python.org/3/reference/expressions.html#grammar-token-comparison
  [2]: https://docs.python.org/3/reference/expressions.html#grammar-token-or-expr
  [3]: https://docs.python.org/3/reference/expressions.html#grammar-token-shift-expr
  [4]: https://docs.python.org/3/reference/expressions.html#grammar-token-m-expr
  [5]: https://docs.python.org/3/reference/expressions.html#grammar-token-u-expr
  [6]: https://docs.python.org/3/reference/expressions.html#grammar-token-power
  [7]: https://docs.python.org/3/reference/expressions.html#grammar-token-not-test

**Comment by pochmann** [comment]
Looks alright to me, and your `2 ** - 1` example is [documented](https://docs.python.org/3/reference/expressions.html#id21) in the "Operator precedence" section:

> The power operator `**` binds less tightly than an arithmetic or bitwise unary operator on its right, that is, `2**-1` is `0.5`.

And I'd say the grammar doesn't provide "the true" reason but "a technical" reason. After all, the grammar is written to reflect what's wanted, not the other way around.

**Comment by Gnudini** [comment]
> The current wording looks alright to me, and your 2 ** - 1 example is [documented](https://docs.python.org/3/reference/expressions.html#id21) in the "Operator precedence" section:
>
>> The power operator ** binds less tightly than an arithmetic or bitwise unary operator on its right, that is, 2**-1 is 0.5.

The _2 ** - 1 example_ in that footnote is equally wrong in explaining the parsing with operator binding tightness. It is the grammar which in the first place decides that the `-` is a unary and not a binary operator, and it does this before operator priority can even be taken into consideration.

> And I'd say the grammar doesn't provide "the true" reason but "a technical" reason. After all, the grammar is written to reflect what's wanted, not the other way around.

You'd really say that in the beginning someone made up his mind about what he wanted - e. g. "I want `a == not b` to be a syntax error" - and afterwards wrote the grammar for it? I find that hard to believe. And I'd say _"a technical" reason_ is _"the_ **only** _true" reason_.

**Comment by hauntsaninja** [comment]
> And I'd say "a technical" reason is "the only true" reason.

I get what you're going for here, but taken literally this would mean e.g. that it's impossible for there to be a bug in the grammar. Like pochmann says, the grammar is meant to encode human intention for how Python should parse. The docs are meant for humans — there's a reason we don't just point users straight to the grammar — so I think describing that intention here is useful. `a == (not b)` works fine, so to me this is accurately described as an issue of priority.

**Comment by SuibianP** [comment]
> Priority never causes an operator to be drawn in place of an operand.

Not restricted to Python, is this the general case for parsing?

> the grammar is meant to encode human intention for how Python should parse

`True == not False` could be unambiguously parsed (programmatically as well as cognitively) as `True == (not False)`. There seems to be no drawback to encode this intention into the grammar as well if this is the case. 🤔
