### ISSUE TITLE
The term "typechecks" is confusingly used as an adjective

### ISSUE THREAD

**Issue by ketozhang** [python/cpython#96130]
# Documentation

Arguably to new eyes, you can mistaken "typecheck" to be a verb meaning "to do type checking". I understand this term came from the C function TypeCheck that returns a boolean.

**Comment by ketozhang** [comment]
It's particular confusing in NewType https://docs.python.org/3.10/library/typing.html#newtype

The static type checker will treat the new type as if it were a subclass of the original type. This is useful in helping catch logical errors:

```py
def get_user_name(user_id: UserId) -> str:
    ...

# typechecks
user_a = get_user_name(UserId(42351))

# does not typecheck; an int is not a UserId
user_b = get_user_name(-1)
```

The last two line may mean, the type checker skips checking this line.

**Comment by ericvsmith** [comment]
Do you have a proposal to improve this? I think it’s okay as-is, but if you can make it better that would be good.

**Comment by ketozhang** [comment]
I believe "Passes type checking" and "Fails type checking" is very clear.

**Comment by ericvsmith** [comment]
> I believe "Passes type checking" and "Fails type checking" is very clear.

Agreed!

**Comment by JelleZijlstra** [comment]
Thanks @ketozhang for the report and @hauntsaninja for the fix!
