### ISSUE TITLE
`match_args`, `slots` and possibly `kw_only` missing from `__dataclass_params__`

### ISSUE THREAD

**Issue by da-woods** [python/cpython#96142]
# Bug report

Dataclasses have an undocumented `__dataclass_params__` class-attribute which appears to document the flags sent to the `dataclass` decorator:
https://github.com/python/cpython/blob/6ec57e7c5af6816178d34233a4da12eb0c21c9d9/Lib/dataclasses.py#L903-L904

A few new flags have been added since the initial implementation of dataclasses. These don't seem to have been added to the `__dataclass_params__` field. In the case of `kw_only` I think that makes sense - it's effectively controlled at a per-field level and the parameter to the `dataclass` decorator is just a convenience. However, the others seem like a genuine omission.

# Your environment

I've just looked at the code for the current main branch.

**Comment by ericvsmith** [comment]
Thanks, @sobolevn !
