### ISSUE TITLE
Clarification of method definition

### ISSUE THREAD

**Issue by mkaizad** [python/cpython#96154]
I've come across two definitions of the term "method" in the docs:

1. In the [glossary](https://docs.python.org/3/glossary.html#term-method):
 
   > **method**
A function which is defined inside a class body. 

2. In the last paragraph of [4.7 Defining Functions](https://docs.python.org/3/tutorial/controlflow.html#defining-functions:~:text=A%20method%20is%20a%20function%20that%20%E2%80%98belongs%E2%80%99%20to%20an%20object%20and%20is%20named%20obj.methodname%2C%20where%20obj%20is%20some%20object%20(this%20may%20be%20an%20expression)%2C%20and%20methodname%20is%20the%20name%20of%20a%20method%20that%20is%20defined%20by%20the%20object%E2%80%99s%20type.):

   > A method is a function that ‘belongs’ to an object and is named obj.methodname, where obj is some object (this may be an expression), and methodname is the name of a method that is defined by the object’s type.

**Could someone please clarify if these two definitions are equivalent?** 

**Definition 2)** seems to say that a method is a function that is bound to a *particular instance* of the class in which that function is defined. On the other hand, **definition 1)** seems to apply the term to functions defined in the *class body* (with no requirement that they be bound to an instance of that class).

Example: 

```python
class Foo(object):
    def hello(self):
        print('Hello')

f1 = Foo()

print(type(f1.hello))     # <class 'method'>
print(type(Foo.hello))    # <class 'function'>
```

**Definition 2)** is more consistent with what I see in the console, i.e. `f1.hello` is of type `method` because it belongs to the instance `f1` and `Foo.hello` is of type `function` because it is not bound to any particular instance.

But **definition 1)** makes it seem like both,  `f1.hello` and `Foo.hello`, should be of type `method` since `hello` is defined in `Foo`'s body.

**Comment by ericvsmith** [comment]
Python used to have the distinction between bound (tied to an object) and unbound (just associated with a class) methods. But that went away in Python 3, and the latter are now just normal functions. Still, I and others still use the terms bound and unbound methods.

**Comment by mkaizad** [comment]
I see, so while unbound method *objects* are no longer a thing, we can still use the term "unbound method" to refer to methods that are just associated with a class, hence definition 1. 

Thank you for your prompt response @ericvsmith.
