### ISSUE TITLE
libpython3.9 not handling undefined symbols properly (Linux)

### ISSUE THREAD

**Issue by N1coc4colA** [python/cpython#96153]
# Bug report
While running Python script from C++ code, if the file imports `ssl`, CPython fails to load the SSL library.
Here is the error raised:
ImportError: /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyExc_OSError

But I checked in my Python libraries, and it defines the PyExc_* symbols, as in the Python 3.9 binary. However, if I run the same script from Python 3.9 binary, and not from Python 3.9 libraries, it all works more than properly. And both the Python binary and the Python library loads this same file. What is more strange is that if I do load SSL library from QLibrary (Qt, C++) or dlopen, the import (loading at runtime a shared library) does not fail. I do not know why Python won't import it, but it is really... strange, and I can just tell that this is a bug from what I've seen.

# Your environment
I used Python 3.9, and Python 3.9 libraries, linking the library with CMake. Nothing else special I think.

- CPython versions tested on: I guess that x86_64 (amd) has been tested (however not sure).
- Operating system and architecture: Linux (Debian based), architecture amd64.

**Comment by kumaraditya303** [comment]
Python 3.9 is security fixes only, does this happen on 3.10+?  Do you have a reproducer for this?

**Comment by hauntsaninja** [comment]
Closing, since OP never responded
