### ISSUE TITLE
Confusing tutorial terms (documentation)

### ISSUE THREAD

**Issue by dev-pep** [python/cpython#96152]
# Tutorial, section 4.8.3 Special parameters

References to:

- Positional-or-Keyword Arguments
- Positional-Only Arguments
- Keyword-Only Arguments

Should be changed to:

- Positional-or-Keyword Parameters
- Positional-Only Parameters
- Keyword-Only Parameters

**Comment by rhettinger** [comment]
This should be left as-is.   The phrases "Positional-or-Keyword Arguments", "Positional-Only Arguments", and "Keyword-Only Arguments" are commonplace.   Also, most people tend use the terms "parameters" and "arguments" interchangeably even though technically "arguments" are values passed in an "formal parameters" are the names they bind to.

**Comment by fluesvamp** [comment]
> References to:
>-  Positional-or-Keyword Arguments
>-  Positional-Only Arguments
> -  Keyword-Only Arguments


@dev-pep 

```
$ cd cpython/Doc/tutorial
$ ed -s controlflow.rst <<<'701,702p'
Special parameters
------------------
$ ed -s controlflow.rst <<<'726,728p'
-------------------------------
Positional-or-Keyword Arguments
-------------------------------
$ ed -s controlflow.rst <<<'733,735p'
--------------------------
Positional-Only Parameters
--------------------------
$ ed -s controlflow.rst <<<'747,749p'
----------------------
Keyword-Only Arguments
----------------------
$ 
```

I think you imply these changes.

```sh
$ pwd
/tmp/cpython/Doc/tutorial
$ sed -i "s/Positional-or-Keyword Arguments/Positional-or-Keyword Parameters/g" controlflow.rst
$ sed -i "s/Keyword-Only Arguments/Keyword-Only Parameters/g" controlflow.rst
$
```

- 4.8. More on Defining Functions
  - 4.8.1. Default Argument Values
  -  4.8.2. Keyword Arguments
  - 4.8.3. Special parameters
    - 4.8.3.1. Positional-or-Keyword Parameters
    - 4.8.3.2. Positional-Only Parameters
    - 4.8.3.3. Keyword-Only Parameters

**Comment by fluesvamp** [comment]
My presumption is that the OP does not have the intention to implement further textual changes to the *.rst file.

It'd be trivial to implement the changes which would result in the *.rst content corresponding to the Tools/clinic/clinic.py excerpt.

**Comment by dev-pep** [comment]
That's correct. However, just to point out there could be some exception error messages using that wording, like. From the tutorial examples:

```
TypeError: pos_only_arg() got some positional-only arguments passed as keyword arguments: 'arg'
```

**Comment by fluesvamp** [comment]
> technically "arguments" are values passed in an "formal parameters" are the names they bind to

possible divergence from technical writing already here

4.7. Defining Functions

```
$ ed -s /tmp/cpython/Doc/tutorial/controlflow.rst <<<'465,470p'
The actual parameters (arguments) to a function call are introduced in the local
symbol table of the called function when it is called; thus, arguments are
passed using *call by value* (where the *value* is always an object *reference*,
not the value of the object). [#]_ When a function calls another function,
or calls itself recursively, a new
local symbol table is created for that call.
$ 
```
>some exception error messages using that wording

location where the message arises might be Lib/test/test_positional_only_arg.py

```
$ ed -s /tmp/cpython/Doc/tutorial/controlflow.rst <<<'788,794p'
   >>> pos_only_arg(1)
   1

   >>> pos_only_arg(arg=1)
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
   TypeError: pos_only_arg() got some positional-only arguments passed as keyword arguments: 'arg'
$ 
```
<hr>

might be indicated to solicit an opinion on this ticket from a second committer to Tools/clinic/clinic.py

**Comment by fluesvamp** [comment]
@ericvsmith

Thanks for chipping in.

<hr>

IMHO writing which is not technical propagates errors/misconceptions.

_cf_: `#95969` (closed as not planned)

```
# sed -i "s/UNMARSHALLABLE/UNMARSHALABLE/g" cpython/Python/marshal.c
# sed -i "s/unmarshallable/unmarshalable/g" cpython/Python/marshal.c
# sed -i "s/unmarshallable/unmarshalable/g" cpython/Python/clinic/marshal.c.h
# sed -i "s/unmarshallable/unmarshalable/g" cpython/Lib/test/test_marshal.py
# sed -i "s/unmarshallable/unmarshalable/g" cpython/Doc/library/marshal.rst
```
