### ISSUE TITLE
sqlite3 docs: extract row factory examples into row factory howto

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#96168]
There are several row factory examples scattered around the sqlite3 docs. Most of them in various places in the reference. Suggesting to extract them and create a row factory _How-to Guide_, in order to clean up the reference and reduce duplication of information.

* gh-96457
* gh-96494
* gh-96495

* gh-99507
* gh-99778
* gh-99779

**Comment by erlend-aasland** [comment]
cc. @CAM-Gerlach @ezio-melotti

**Comment by CAM-Gerlach** [comment]
Seems reasonable to me—short-ish examples are reasonable for a reference, but advice like

> If returning a tuple doesn’t suffice and you want name-based access to columns, you should consider setting [row_factory](https://docs.python.org/3.12/library/sqlite3.html#sqlite3.Connection.row_factory) to the highly optimized [sqlite3.Row](https://docs.python.org/3.12/library/sqlite3.html#sqlite3.Row) type. [Row](https://docs.python.org/3.12/library/sqlite3.html#sqlite3.Row) provides both index-based and case-insensitive name-based access to columns with almost no memory overhead. It will probably be better than your own custom dictionary-based approach or even a db_row based solution.

is much more appropriate in a how-to, or perhaps actually an explanation (but there isn't really enough meat for that, and a how-to is certainly closer than a reference here)

**Comment by erlend-aasland** [comment]
As a first step, I suggest to improve the dict-factory example by:

- modermising the code; we can use a dict comprehension
- using a doctest, so the expected output is visible
- SELECTing a row with multiple columns, so the effect of the dict factory becomes clearer
