### ISSUE TITLE
Move GIL code into its own file

### ISSUE THREAD

**Issue by markshannon** [python/cpython#96177]
Currently the GIL code lives in ceval.c
ceval.c is a large file (8k lines) and doesn't need to contain the GIL code.
It used to, as it was quite tightly coupled with the interpreter, but that is no longer the case.

Apart from general code health, moving the GIL code to its own file will ease generating the interpreter and other performance work.

**Comment by kumaraditya303** [comment]
https://github.com/python/cpython/pull/96204 moved the code to new file, @markshannon anything left to do here ?

**Comment by jakirkham** [comment]
Should this be closed?

**Comment by markshannon** [comment]
Yes
