### ISSUE TITLE
Minor error in bisect documentation

### ISSUE THREAD

**Issue by encukou** [python/cpython#96179]
Reposting from the [docs list](https://mail.python.org/archives/list/docs@python.org/thread/U7NTPCD67KPCSCPN3RTV2BNIR3J5UPMU/):

> Hi,
> 
> The bisect library documentation includes an example with movies that is
> stated to "find the first movie released *on or after 1960*". The example
> given uses bisect.bisect, which is an alias for bisect.bisect_right, and so
> will find the first move released *after* 1960. This can be verified by
> adding in a movie from 1960.
> 
> The example can be corrected by either:
> 
> 1. Changing the comment to "Find the first movie released after 1960"
> 2. Importing bisect_left and using that instead.
> 
> Thanks for your efforts in maintaining the Python docs!
> 
> Best wishes,
> James Skelton

@rhettinger, you added the example in https://github.com/python/cpython/pull/92602 – which would you prefer?

**Comment by rhettinger** [comment]
Thanks for noticing.  Just change the comment to *after*.  These essential point in these examples is how to use a key-function with `bisect()` and `insort()`, so it would be distracting to also address the left/right variants in the same example.
