### ISSUE TITLE
Wrong argument name in date.fromisocalendar docs

### ISSUE THREAD

**Issue by encukou** [python/cpython#96180]
Reposting from the [docs list](https://mail.python.org/archives/list/docs@python.org/thread/473SA46SKYU54GZNH42IXYQMHP26QBT3/):

> Bonsoir,
> Dans classmethod [date.fromisocalendar(year, week, day)](https://mail.python.org/archives/list/docs@python.org/thread/473SA46SKYU54GZNH42IXYQMHP26QBT3/)
> week devrait être remplacé par month !
> Cordialement
> Philippe Geissbühler

While I don't understand French, I completely agree.

**Comment by zware** [comment]
It's correct as is:

```
>>> datetime.fromisocalendar(2022, 34, 1)
datetime.datetime(2022, 8, 22, 0, 0)
```

ISO calendar is just weird.

**Comment by zware** [comment]
One could argue that `day` should be `weekday` instead to match the `isocalendar` method `fromisocalendar` is meant to mirror, but I'm afraid that ship has sailed and isn't coming back without a cumbersome deprecation period.
