### ISSUE TITLE
test_invalid_utf8 test failing on some buildbots

### ISSUE THREAD

**Issue by mdboom** [python/cpython#96189]
The test added in #94856 is failing on a number of buildbots:

- https://buildbot.python.org/all/#/builders/188
- https://buildbot.python.org/all/#/builders/285
- https://buildbot.python.org/all/#/builders/33
- https://buildbot.python.org/all/#/builders/455
- https://buildbot.python.org/all/#/builders/40
- https://buildbot.python.org/all/#/builders/339

**Comment by hauntsaninja** [comment]
Thanks for fixing, looks like this has been completed
