### ISSUE TITLE
`del sys.breakpointhook` is not tested in test_builtin

### ISSUE THREAD

**Issue by youknowone** [python/cpython#96197]
# Bug report

`test_builtin::TestBreakpoint` contains various scenario of breakpointhook setup, but missing deleted hook test. 
Adding a new test will prevent a future regression.

# Your environment

Not applicable.

**Comment by warsaw** [comment]
The semantics of `del sys.breakpointhook` isn't well defined, either in PEP 553 or in the stdlib docs.  However the intent is for it to act similarly to `sys.displayhook` and `sys.excepthook`, except that those aren't entirely consistent either:

```python
Python 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> del sys.displayhook
>>> repr(object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lost sys.displayhook
>>> del sys.excepthook
>>> 1/0
sys.excepthook is missing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

`del sys.displayhook` produces a `RuntimeError` but `del sys.excepthook` does not (you get the original exception).  This all makes sense, and in the case of `del sys.breakpointhook` I suppose it should act more like `del sys.displayhook`, which it does.

All that to say, I wonder if these behaviors should be documented in `sys` module documentation?

**Comment by corona10** [comment]
> All that to say, I wonder if these behaviors should be documented in sys module documentation?

Agree

**Comment by youknowone** [comment]
Thank you, that sounds great to me.
