### ISSUE TITLE
configure.ac update

### ISSUE THREAD

**Issue by ghost** [python/cpython#96191]
The configure messages refer to bugs.python.org.

Tests / Check if generated files are up to date (pull_request)

A PR with a solitary edit to configure.ac will fail the above test.

`sed -i "s#https://bugs.python.org/#https://github.com/python/cpython/issues#g" cpython/configure.ac`

I would leave it to someone else to open a PR.

> - install podman or docker
> - run ./configure to generate the Makefile
> - run make regen-configure
> - done

A Member can decide whether to mention podman and docker in the 1st block comment of configure.ac .

```
$ ed -s cpython/configure.ac <<<'1,13p'
dnl ***************************************************
dnl * Please run autoreconf -if to test your changes! *
dnl ***************************************************
dnl
dnl Python's configure script requires autoconf 2.69 and autoconf-archive.
dnl

# Set VERSION so we only need to edit in one place (i.e., here)
m4_define(PYTHON_VERSION, 3.12)

AC_PREREQ([2.69])

AC_INIT([python],[PYTHON_VERSION],[https://bugs.python.org/])
$ 
```

**Comment by fluesvamp** [comment]
@ptsneves 

ping

**Comment by fluesvamp** [comment]
```
dnl ***************************************************
dnl * Please run autoreconf -if to test your changes! *
dnl ***************************************************
dnl
dnl An easy way to generate files for upstream, after modifying this
dnl file, is to install podman or docker, run ./configure' and then
dnl make regen-configure.
dnl
dnl Python's configure script requires autoconf 2.69 and autoconf-archive.
dnl
```

**Comment by fluesvamp** [comment]
I suggest merging the linked to PR as is.

If the file is revisited for update in the future some comment modifications might be made.

_this is a good example of comment style_

As the minimum autoconf version is included in the code there is no need to restate this in a comment.

The package autoconf-archive may be included with installed development package series but may not always be installed.

```diff
  dnl
- dnl Python's configure script requires autoconf 2.69 and autoconf-archive.
  dnl

  # Set VERSION so we only need to edit in one place (i.e., here)
  m4_define(PYTHON_VERSION, 3.12)

+ dnl Some Linux distros may require installing autoconf-archive.
  AC_PREREQ([2.69])
```
