### ISSUE TITLE
Segmentation fault, on calling embedded python method, for the second time from C

### ISSUE THREAD

**Issue by pavanfromflashbox** [python/cpython#96214]
OS: Ubuntu 20.04
Compiler: g++ (v9.4.0)

**Problem**: 
The following code contains a function `resamplePython`, which calls a function `multiply(a,b)` from python file `run.py`.
When the `resamplePython` function is called twice, first time it gets executed, but the second time, 
I'm getting `segmentation fault` error.

On debugging each line, I have found that, for the first time `PyImport_Import` method returns some address as `eg: 0x0987187628`,
but the second time it returns `0`.

```cpp
#define PY_SSIZE_T_CLEAN
#define PY_MODULE_NAME "run"
#define PY_FUNCTION_NAME "multiply"

#include <Python.h>
#include <stdio.h>
#include <stdlib.h>


char* resamplePython(char* dataStr)
{
	void *handle = dlopen("libpython3.8.so", RTLD_LAZY | RTLD_GLOBAL);
	if (!handle) {
		fprintf(stderr, "%s\n", dlerror());
		exit(EXIT_FAILURE);
	}


	PyObject *pName, *pModule, *pFunc;
	PyObject *pArgs, *pValue;

	Py_Initialize();
	PyRun_SimpleString("import sys");
	PyRun_SimpleString("sys.path.append('.')");

	pName = PyUnicode_DecodeFSDefault(PY_MODULE_NAME);
	
	pModule = PyImport_Import(pName);
	Py_DECREF(pName);

	if (pModule == NULL)
	{
		PyErr_Print();
		fprintf(stderr, "Failed to load \"%s\"\n", PY_MODULE_NAME);
		return NULL;
	}

	pFunc = PyObject_GetAttrString(pModule, PY_FUNCTION_NAME);

	if (!pFunc || !PyCallable_Check(pFunc))
	{
		PyErr_Print();
		fprintf(stderr, "Failed to load function \"%s\"\n", PY_FUNCTION_NAME);
		return NULL;
	}
	pArgs = PyTuple_New(1);

	pValue = PyUnicode_FromString(dataStr);
	PyTuple_SetItem(pArgs, 0, pValue);

	pValue = PyObject_CallObject(pFunc, pArgs);

	Py_DECREF(pArgs);

	if (pValue == NULL)
	{
		Py_DECREF(pFunc);
		Py_DECREF(pModule);
		PyErr_Print();
		fprintf(stderr, "Failed to get return from function \"%s\"\n", PY_FUNCTION_NAME);
		return NULL;
	}

	char *resultString = const_cast<char *>(PyUnicode_AsUTF8(pValue));

	Py_XDECREF(pFunc);
	Py_XDECREF(pModule);

	Py_FinalizeEx();

	return resultString;
}

int main(){
   // Execute for the first time
    resamplePython("Test resample");

    // Execute for second time.
    resamplePython("Test resample 1");
}
```

**Comment by ericvsmith** [comment]
Is `Py_FinalizeEx()` getting called the first time through?

Also, I suggest trying with 3.9 and/or 3.10.

**Comment by pavanfromflashbox** [comment]
Yeah, It's getting called for the first time, and the return value of `Py_FinalizeEx()` is 0, which I have noticed when it is run for the first time.

**Comment by ericvsmith** [comment]
And what about using 3.9 or 3.10?

But this really sounds like a usage issue, and the bug tracker isn't the best place to get help.

**Comment by pavanfromflashbox** [comment]
I have noticed the issue, on executing the c code with gdb. Following is the error I see.
```
0x00007ffff68fb7f8 in PyArray_Item_INCREF () from /home/pavan/.local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
```

**Comment by kumaraditya303** [comment]
Numpy does not supports multiple interpreter initializations and is not a CPython bug.  If you can provide a reproducer without third party dependencies that would be great else I'll close this as not a CPython bug.

**Comment by pavanfromflashbox** [comment]
Then, I think this ticket can be closed. Thanks.
