### ISSUE TITLE
Dict of variables less verbose with walrus operator

### ISSUE THREAD

**Issue by iuiu34** [python/cpython#96219]
Hi,
more often than not, we define a dict of variables, with the respective names as keys.

For example
```py
a = 1
dict(a=a, b=2)
```

Would be nice, to do this in a more simplified less verbose way.
As an idea, using the walrus operator

```py
a = 1
dict(a:=, b=2)
```

# Pitch
For me the implicit << explicit argument doesn’t apply; doing `a=a` seems just verbose.

# Previous discussion
https://discuss.python.org/t/dict-of-variables-less-verbose/12229

**Comment by kumaraditya303** [comment]
The discourse discussion has no comments and it wasn't discussed. Once there is some discussion and agreement then create a issue. Closing as there is nothing actionable.
