### ISSUE TITLE
Windows Path.symlink_to target_is_directory argument doesn't matter

### ISSUE THREAD

**Issue by t-mart** [python/cpython#96223]
# Bug report

The documentation for [pathlib's `Path.symlink_to`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.symlink_to) states:

> Under Windows, *target_is_directory* must be true (default `False`) if the link’s target is a directory.

It is not clear what will happen if this argument is set incorrectly. And, in fact, in my testing, this argument seems to have no effect on the outcome -- **it works when False if the target is a directory**.

Here is a reproduction script:

```python
from pathlib import Path
import sys

assert sys.platform == "win32"

this_dir = Path(__file__).parent

target = this_dir / "target"
symlink = this_dir / "symlink"

target.mkdir()
assert target.is_dir()

# this should not succeed because target is a directory
symlink.symlink_to(target, target_is_directory=False)

assert symlink.resolve() == target

# clean up
symlink.unlink()
target.rmdir()
```

Perhaps, this is a case of some versions of Windows not requiring the flag. "Newer" versions of Windows have made symlink creation more accessible in other ways (see note [here](https://docs.python.org/3/library/os.html#os.symlink), Microsoft reference [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.2)). Maybe even newer versions have gone further.

I'm doubtful that the argument was ineffective for all builds of Windows, but I'm wrong, the argument should be removed. If instead this is just a recent-build development, the documentation should mention that the argument is not necessary for some even-newer builds.

# Your environment

- OS Name: `Microsoft Windows 10 Pro`
- Version: `10.0.19044 Build 19044`
- Developer Mode is on
- Python version: `3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]`

**Comment by t-mart** [comment]
Digging deeper (and with some feedback from `bookworm`, a user on the Libera #python IRC channel), the documentation of [`os.symlink`](https://docs.python.org/3/library/os.html#os.symlink) provides some insight: This argument only matters on Windows **when the target does not already exist** because "on Windows, a symlink represents either a file or a directory, and does not morph to the target dynamically".

Instead of a bug, I think this is more of an underdocumented description for [`Path.symlink_to`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.symlink_to).

I will begin looking into how I can contribute documentation updates. Perhaps others will see a clarification as warranted.

**Comment by grawity** [comment]
The flag has a different purpose than you assume – it's not checked when *creating* a link, it's used to set an "is directory" flag within the link's metadata that is later checked when *following* the link. (It would be roughly equivalent to having both `stat.S_IFDIR|S_IFLNK` bits set, which is impossible in POSIX but is possible in Windows.)

You can always manually read the link's target as a string regardless of the 'directory' bit, but Windows will refuse to automatically follow it when the target type doesn't match:

```
PS> cmd /c mklink /d testlink.txt testoriginal.txt
PS> cat testlink.txt
cat : Access to the path 'testd.txt' is denied.
```

Use `fsutil file layout the_symlink` to inspect the created file object (and `fsutil reparsepoint query the_symlink` for completeness, but the bit is in the general metadata).

**Comment by t-mart** [comment]
Interesting, @grawity. This is indeed more nuanced that I thought.
