### ISSUE TITLE
Allow the `f_func` field of the `_PyInterpreterFrame` struct to be any object (and rename it)

### ISSUE THREAD

**Issue by markshannon** [python/cpython#96237]
In order to better support shim frames, trampolines, Cython frames and other such bits and pieces, we need to relax the requirement that the `f_func` field is a function.
The only reason for it to be a function is that it needs to hold a strong reference to builtins and globals, as the frame only has a borrowed reference to those. Any object with those references will do.
In fact, for code that has no builtins or globals (many shims and trampolines) there is no need for those references and `f_func` could even be `None`.

**Comment by iritkatriel** [comment]
Does it really need to allow any object? Could you instead define a small number of object types that it can be?

**Comment by markshannon** [comment]
I don't see any advantage to restricting the possible types. Allowing any object is no worse for any code reading from `f_funcobj` and more flexible for anything storing to it.

Given the values of `f_globals` and `f_builtins` can no longer be trusted, I think I'll make them `void *` just to make it clear that if you didn't set them, then you can't trust them.

**Comment by carljm** [comment]
Currently whatever is in `f_func` also needs to have a `func_closure`. https://github.com/python/cpython/pull/101310 demonstrates one way to remove this requirement.

**Comment by carljm** [comment]
Should this issue be closed, given the attached PR was merged? Or is there more planned here?
