### ISSUE TITLE
http.server: should use configurable logging instead of hard-coded print to stderr

### ISSUE THREAD

**Issue by johann-petrak** [python/cpython#96246]
Please make it possible to pass a logger or at least use logging instead of hard coded printing to sys.stderr e.g. at
https://github.com/python/cpython/blob/fba3b67af47723c201fe3425cb615932970a8f28/Lib/http/server.py#L582
or at other locations where error handling occurs.

**Comment by ethanfurman** [comment]
The one location where `stderr` is written to is in the function `log_message` -- if you want to log somewhere else simply subclass the request handler and provide your own `log_message` method.

**Comment by ericvsmith** [comment]
Agreed with @ethanfurman. There's even a comment in the code and https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.log_message saying that subclassing is the correct way to modify the logging.
