### ISSUE TITLE
Support custom PKG_CONFIG_PATH in the wasm build

### ISSUE THREAD

**Issue by rchiodo** [python/cpython#96253]
# Feature or enhancement

tools/wasm/wasm_build.py does not have an easy way to build submodules. 

# Pitch

PKG_CONFIG_PATH could be used to support say things like https://github.com/hoodmane/libffi-emscripten.

I propose adding this to the wasm_build.py to support custom package configs.

# Previous discussion

https://discuss.python.org/t/get-ctypes-working-in-emscripten-build/18466/2

**Comment by tiran** [comment]
Actually there is no need to change any code in CPython. It turns out that Emscripten has an undocumented env var `EM_PKG_CONFIG_PATH`. I have opened https://github.com/emscripten-core/emscripten/pull/17736 to add the env var to Emscripten docs.

**Comment by tiran** [comment]
@rchiodo Can you confirm that `EM_PKG_CONFIG_PATH` solves your problem?

**Comment by rchiodo** [comment]
Yes that did work for me. Thanks.
