### ISSUE TITLE
Improve `faq/design.rst` rst markup

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#96265]
I noticed that the [`faq/design.rst`](https://github.com/python/cpython/blob/main/Doc/faq/design.rst) page has several parts that either have no markup (e.g. try/except, :=, etc.) or a generic ` ``...`` ` when a more specific one could be used (e.g. `` :c:type:`double` ``).

We should review the page and apply proper markup where applicable.  Some other FAQs might need the same treatment.

* PR: gh-98991

* PR: gh-98994

**Comment by slateny** [comment]
Created a PR for just `design.rst` - as for other FAQs, I think the [general faq](https://docs.python.org/dev/faq/general.html) could get some grave accents too (maybe under 'version numbering', `A.B.C` etc. could be literal), but changes to `design.rst` are looking somewhat long already so I'll put them in a separate PR.

Some of the missing formatting can also be found in other docs (i.e., ` ``if`` ` -> `` :keyword:`if` ``), should those be globally applied or should it change file-by-file?

**Comment by hauntsaninja** [comment]
Thanks, closing. We can open another issue for any other FAQs
