### ISSUE TITLE
AIX build failing because of python.exp not being created before building shared modules. 

### ISSUE THREAD

**Issue by ayappanec** [python/cpython#96269]
https://buildbot.python.org/all/#/builders/438/builds/3408

AIX build is failing with the main branch. The error thrown is "Modules/python.exp" file not found while building the shared modules. In AIX, the export file is required for the creation of shared modules.  
So the "sharedmods" target needs "EXPORTSYMS" target to be built before so that the export file is created before building the shared modules.

**Comment by tiran** [comment]
Problem is fixed in main branch.

**Comment by ayappanec** [comment]
The fix didn't work actually. It introduced a circular dependency and the creation of libpython3.12.a didn't happen, so it ended up creating a empty python.exp file. 

https://buildbot.python.org/all/#/builders/438/builds/3413/steps/3/logs/stdio

gmake: Circular Modules/python.exp <- libpython3.12.a dependency dropped.
./Modules/makexp_aix Modules/python.exp "." 

I already have working fix for the original issue. Planning to create a PR. 
@tiran Can you revert the changes ?

**Comment by tiran** [comment]
Does https://github.com/python/cpython/pull/96316 work for you?

**Comment by ayappanec** [comment]
The above works. 
But I have created a fix like this.

diff --git a/Modules/makesetup b/Modules/makesetup
index 08303814c8..85bdf03187 100755
--- a/Modules/makesetup
+++ b/Modules/makesetup
@@ -99,6 +99,12 @@ CYGWIN*) if test $libdir = .
         ExtraLibs="-L$ExtraLibDir -lpython\$(LDVERSION)";;
 esac
 
+# AIX needs export file to build shared modules
+# So needs EXPORTSYMS target before building shared modules
+case `uname -s` in
+AIX*)    ExpFileTarget="\$(EXPORTSYMS)";;
+esac
+
 # Main loop
 for i in ${*-Setup}
 do
@@ -282,7 +288,7 @@ sed -e 's/[         ]*#.*//' -e '/^[        ]*$/d' |
                                BUILT_SHARED="$BUILT_SHARED $mod"
                                ;;
                        esac
-                       rule="$file: $objs"
+                       rule="$file: $objs $ExpFileTarget"
                        rule="$rule; \$(BLDSHARED) $objs $libs $ExtraLibs -o $file"
                        echo "$rule" >>$rulesf
                done

Let me know your opinion about my fix.

**Comment by ayappanec** [comment]
The above works.
But I have created a fix like this 
```diff
diff --git a/Modules/makesetup b/Modules/makesetup
index 08303814c8..85bdf03187 100755
--- a/Modules/makesetup
+++ b/Modules/makesetup
@@ -99,6 +99,12 @@ CYGWIN*) if test $libdir = .
         ExtraLibs="-L$ExtraLibDir -lpython\$(LDVERSION)";;
 esac
 
+# AIX needs export file to build shared modules
+# So needs EXPORTSYMS target before building shared modules
+case `uname -s` in
+AIX*)    ExpFileTarget="\$(EXPORTSYMS)";;
+esac
+
 # Main loop
 for i in ${*-Setup}
 do
@@ -282,7 +288,7 @@ sed -e 's/[         ]*#.*//' -e '/^[        ]*$/d' |
                                BUILT_SHARED="$BUILT_SHARED $mod"
                                ;;
                        esac
-                       rule="$file: $objs"
+                       rule="$file: $objs $ExpFileTarget"
                        rule="$rule; \$(BLDSHARED) $objs $libs $ExtraLibs -o $file"
                        echo "$rule" >>$rulesf
                done
```
Let me know your opinion about my fix.

**Comment by ayappanec** [comment]
@tiran Can #96316 be merged? . This will fix one of the two build issues in AIX.

**Comment by ayappanec** [comment]
@tiran

**Comment by ayappanec** [comment]
Can this be merged please ?
