### ISSUE TITLE
open() function documentation shows newline as lowerCamelCase: newLine.  Should be shown as: newline

### ISSUE THREAD

**Issue by incy-tron** [python/cpython#96278]
# Documentation

open() function documentation shows newline as lowerCamelCase: newLine.  Should be shown as lowercase: newline

**Comment by zware** [comment]
Can you provide a link to this?  I don't see it at https://docs.python.org/3/library/functions.html#open

**Comment by incy-tron** [comment]
my bad, closing the issue.  It's the weird font use on that page, that makes it look like lowercase CamelCase.
