### ISSUE TITLE
Documentation typo for `pathlib.Path.walk` in Python 3.12

### ISSUE THREAD

**Issue by SimpleArt** [python/cpython#96279]
# Documentation

In the documentation for [`pathlib.Path.Walk`](https://docs.python.org/3.12/library/pathlib.html#pathlib.Path.walk), there is a typo in the provided example's keyword argument that should be `top_down=False`:

```python
# Delete everything reachable from the directory "top".
# CAUTION:  This is dangerous! For example, if top == Path('/'),
# it could delete all of your files.
for root, dirs, files in top.walk(topdown=False):
    for name in files:
        (root / name).unlink()
    for name in dirs:
        (root / name).rmdir()
```

**Comment by zware** [comment]
Good catch!  Would you like to submit a PR to fix this?
