### ISSUE TITLE
The docstring for `os.mkdir` should mention the effect of umask

### ISSUE THREAD

**Issue by hagai-helman** [python/cpython#96288]
# Documentation

In `os.mkdir`, when the argument `mode` is used, the current umask value is first masked out of it. This behavior is mentioned in the library's documentation, but not in the docstring.

This behavior may be unexpected for some (for example, this is not the behavior of GNU's `mkdir` command - when a mode is explicitly given to it, it overrides the umask). When one is unaware of this behavior, it can lead to bugs that are difficult to notice or trace. For these two reasons, I suggest it will be mentioned in the docstring.

My edit suggestion is given in #96271.

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
