### ISSUE TITLE
Global strings do not regen on Windows

### ISSUE THREAD

**Issue by zooba** [python/cpython#96291]
Example build at https://github.com/python/cpython/runs/8027063542?check_suite_focus=true

Running `PCbuild/build.bat --regen` should regenerate global strings as well. There's probably a command that needs to be added to PCbuild/regen.targets.

**Comment by ericsnowcurrently** [comment]
@kumaraditya303, would you like to take a look at this.  It would be an opportunity to get a little more familiar with the tooling for Windows builds.

(Don't feel like you have to.  I'll take a look if you don't.)

**Comment by kumaraditya303** [comment]
Alright, https://github.com/python/cpython/pull/96394 should fix this.

**Comment by ericsnowcurrently** [comment]
Thanks for the fix, @kumaraditya303 (and @zooba for pointing out the problem)!
