### ISSUE TITLE
Windows paths in FileHandler logging config cause OSError

### ISSUE THREAD

**Issue by r-bird** [python/cpython#96306]
Configuring a log file file path in the `.conf` file passed to `logging.config.fileConfig` with Windows paths causes an `OSError`.

`logging.conf` contains:
```
[handler_fileHandler]
class=logging.handlers.RotatingFileHandler
args=("logs\test.log",)
```

Stack trace:
```
C:\Program Files\Python39\lib\logging\config.py:79: in fileConfig
    handlers = _install_handlers(cp, formatters)
C:\Program Files\Python39\lib\logging\config.py:145: in _install_handlers
    h = klass(*args, **kwargs)
C:\Program Files\Python39\lib\logging\handlers.py:153: in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
C:\Program Files\Python39\lib\logging\handlers.py:58: in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
C:\Program Files\Python39\lib\logging\__init__.py:1146: in __init__
    StreamHandler.__init__(self, self._open())
C:\Program Files\Python39\lib\logging\__init__.py:1175: in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
E   OSError: [Errno 22] Invalid argument: 'C:\\ws\\logs\test.log'
```

As you can see, the argument is evaluated to `'C:\\ws\\logs\test.log'`, containing the tab character '\t'.
This makes the path invalid.

----

The reason for this is this line in the logging module evaluating `args`:
https://github.com/python/cpython/blob/d348afa15d5a997e7a8e51c0f789f41cb15cc651/Lib/logging/config.py#L142
and could possibly cause errors when evaluating `kwargs` two lines below:
https://github.com/python/cpython/blob/d348afa15d5a997e7a8e51c0f789f41cb15cc651/Lib/logging/config.py#L144

I don't know the reason, why the arguments are evaluated, but in this case this causes an error, that is hard to track down or understand.

This might not be an issue, if the config file is written by hand, but when the path is generated by a script, e.g. with
```py
str(pathlib.Path(file_path).resolve())
```
this is a likely pitfall.

**Comment by vsajip** [comment]
It's always worked like this (using `eval()`), and that is documented [here](https://docs.python.org/3/library/logging.config.html#configuration-file-format). The answer is to use `/` as a separator, or to use `args=(r"logs\test.log",)` to ensure backslashes are properly handled. It the path is written programmatically, the computation needs to take into account that its result is passed through `eval()`.

Did you actually use `pathlib`? I don't get the results you suggest:
```
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> p = pathlib.Path('logs/test.log').resolve()
>>> p
WindowsPath('C:/Temp/logs/test.log')
>>> str(p)
'C:\\Temp\\logs\\test.log'
>>> p = pathlib.Path('logs\test.log').resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Vinay\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1204, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Vinay\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name or volume label syntax is incorrect: 'logs\test.log'
>>>
```

**Comment by r-bird** [comment]
I have to disagree. This issue is not solved.

The problem occurs in the `logging` module, not in `pathlib` - as described above.

**Comment by vsajip** [comment]
Did you just add a comment and then delete it? I received an email notification of a comment, but I don't see a corresponding comment ...

**Comment by r-bird** [comment]
Yes, I had mentioned that I disagree with that it is a good idea to allow such pitfalls by evaluating the arguments. But this is would lead to a mayor discussion about the logging file config in general.

**Comment by vsajip** [comment]
Whether you agree or not with the design decisions made at the time, it will continue to work as it does because existing code has to keep working, so the need for backward compatibility precludes changes in this area. Given that the use of `eval()` is clearly documented, whoever sets the configuration file has to understand what the input has to be in order to be correctly computed via `eval()`. If it's a human user, then they have to edit the config file appropriately. If it's a program, then whoever writes that program has to arrange computing the content of that part of the file correctly, in order for the result of `eval()` to be as expected. I just illustrated in my snippet that usage of `pathlib` leads to a string like `'C:\\Temp\\logs\\test.log'`, which should be correctly processed by `eval()`.

**Comment by vsajip** [comment]
Wherever possible, people should generally move over to using `dictConfig()`, which doesn't use `eval()`.
