### ISSUE TITLE
JSON bug / maybe enhancement - string with : fails decoding

### ISSUE THREAD

**Issue by mrkprdo** [python/cpython#96317]
# Bug report

json module unable to parse string with `:` but is not a expected json data.
```python3
import json

my_data = ["{\"obj_data\":\"ok\"}", "no smiley", "just smiley :)"]
for data in my_data:
    # 1st element prints {'obj_data':'ok'}
    # 2nd element prints "no smiley"
    # 3rd element raises json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    print(json.loads(data)) 

```

I know this can be handled by sanitizing data prior decoding it, however, in general, when data is a normal type str without `:`, it just returns it as type str. Shouldn't we expect same for str with `:`?

If this is an invalid report, please close :)

# Your environment

- CPython versions tested on: 3.6+
- Operating system and architecture: any

Edit: added sample, fix typo :)

**Comment by pochmann** [comment]
Actual outcome: `NameError: name 'mydata' is not defined`. And after fixing that, your second string causes an error for me as well (as it should).

**Comment by mrkprdo** [comment]
> Actual outcome: `NameError: name 'mydata' is not defined`. And after fixing that, your second string causes an error for me as well (as it should).

fixed the typo there.

But would it be more clear that as expected that string (that errored) should be instead treated as string? Serialize should be able to treat / detect it correctly?

**Comment by pochmann** [comment]
Neither your second nor your third string are valid JSON, so both should error (as they do for me, and partly due to the typo, I'm not convinced you actually ran the code you showed above and didn't get an error for the second).

**Comment by mrkprdo** [comment]
> Neither your second nor your third string are valid JSON, so both should error (as they do for me, and partly due to the typo, I'm not convinced you actually ran the code you showed above and didn't get an error for the second).

Ok after inspecting my data in my api pipeline, the string is passed to a template object, but at some point the serialization broke when added some `:` in it. Therefore, its an invalid bug for json. Thanks for the input. 

PS. yeah i did not run it thinking it was a similar representation of the code im working. There really was a "sanitization" happened prior decoding it. 😁
