### ISSUE TITLE
WASI socket support

### ISSUE THREAD

**Issue by tiran** [python/cpython#96320]
# Feature or enhancement

WASI has limited support for BSD-like sockets in snapshot preview 1. tl;dr it is not possible to open new connections. The WASI runtime must pass a socket file descriptor into the process. Preview 1 supports both connected client-side socket and `accept()` on bound listening sockets. `poll()` is available as well, although limited to `poll_oneoff`. bind, connect, sendto / recvfrom, DNS lookup and NETDB (gethostbyname, getaddrinfo, getservbyname) etc are not available.

Let's document the missing functions and address the remaining issues to get socketserver and simple clients working.

# Previous discussion

GH-95179 addressed several missing functions that prevented us to compile the socket module on WASI.

**Comment by tiran** [comment]
## Related WASI / wasmtime issues

* https://github.com/bytecodealliance/wasmtime/issues/4754, addressed by https://github.com/bytecodealliance/wasmtime/pull/4776
* https://github.com/WebAssembly/wasi-libc/issues/318, fixed in https://github.com/bytecodealliance/wasmtime/pull/4777
* https://github.com/bytecodealliance/wasmtime/issues/3936

**Comment by brettcannon** [comment]
FYI this should be coming in WASI preview2.

**Comment by brettcannon** [comment]
WASI SDK 21 and https://github.com/dicej/cpython/commit/118e9d8eeabb6345d57295f6cec1616694eacbc2 are apparently enough to get socket support.

**Comment by brettcannon** [comment]
Closing as this is only possible once WASI-libc lands support.
