### ISSUE TITLE
Deprecate `gen.throw(typ, val, tb)`

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#96348]
CC: @iritkatriel 

Issue GH-89874 gets rid of exception triples where it makes sense. I don't know if it was considered, but another place where such triples are supported is the `gen.throw()`. It allows passing either an exception, or a (type, value, traceback) triple where the value and traceback are optional. I think it makes sense to keep allowing passing an exception type, but I don't see the use case for passing separate type and value. We could deprecate this easily by adding a warning to `gen_throw()` when more than one argument is present.

Thoughts?

**Comment by rhettinger** [comment]
This would be a nice simplification.  AFAICT, the three argument form if rarely used, so deprecating that variant won't be disruptive. Also, when the signature becomes `METH_O`, calls to `gen.throw` will get faster.

**Comment by iritkatriel** [comment]
Yes, this would be good. The triplet is not just wasteful, it's also ambiguous when ``val.__traceback__ != tb``.

**Comment by gvanrossum** [comment]
I wonder if this could be marked as an "easy" issue for someone with moderate C skills to tackle? All you have to do (for now) is issue a deprecation warning if the arg count is larger than 1. (And update some docs.)

**Comment by iritkatriel** [comment]
Marked as easy, but also as release-blocker for 3.12 so we won't forget.

**Comment by ofey404** [comment]
> I wonder if this could be marked as an "easy" issue for someone with moderate C skills to tackle? All you have to do (for now) is issue a deprecation warning if the arg count is larger than 1. (And update some docs.)

Does it locate in `Objects/iterobject.c`? I'm trying to become a core developer and willing to help.

https://github.com/python/cpython/blob/af368a7db46594ca6bd7ed5d4d68bb39900dae0e/Objects/iterobject.c#L413-L416

And the (type, value, traceback) triple documentation:

```plain text
help(a.throw)
Help on built-in function throw:

throw(...) method of builtins.generator instance
    throw(typ[,val[,tb]]) -> raise exception in generator,
    return next yielded value or raise StopIteration.
```

**Comment by gvanrossum** [comment]
No, I'm looking at `gen_throw` in genobject.c. Looks like you found another instance of the same problem!

**Comment by ofey404** [comment]
I got it, here is the `genobject.c:gen_throw` doc:

https://github.com/python/cpython/blob/af368a7db46594ca6bd7ed5d4d68bb39900dae0e/Objects/genobject.c#L1145-L1150

Besides, there is another occurrence in `genobject.c`, the `async_gen_athrow`:

https://github.com/python/cpython/blob/af368a7db46594ca6bd7ed5d4d68bb39900dae0e/Objects/genobject.c#L1539-L1540

And how to throw deprecation warning from cpython c code? I searched the web but didn't find much useful material.

**Comment by arhadthedev** [comment]
The keywords here are [`PyExc_DeprecationWarning`](https://github.com/python/cpython/search?q=PyExc_DeprecationWarning) and `PyErr_WarnEx` (I've briefly seen these names before but didn't use them in practice). Here are relevant examples, though I don't know how to determine the last parameter of the function (`7` in two examples, `2` in the third):

https://github.com/python/cpython/blob/692e9078a10b268530f8da7d3095cfb05c48435b/Modules/spwdmodule.c#L256-L267
https://github.com/python/cpython/blob/804f2529d8e545a8d59eaf260ee032d014e681ba/Modules/nismodule.c#L524-L534
https://github.com/python/cpython/blob/b2afe482f21b826d53886a69ea2c99d0d940c59a/Modules/_asynciomodule.c#L1110-L1126

**Comment by ofey404** [comment]
> The keywords here are [`PyExc_DeprecationWarning`](https://github.com/python/cpython/search?q=PyExc_DeprecationWarning) and `PyErr_WarnEx` (I've briefly seen these names before but didn't use them in practice).

Besides, I wonder are there any unit test catches depreciated warning? I randomly delete one in cpython source code, but all test suite still passed.

**Comment by CharlieZhao95** [comment]
> Besides, I wonder are there any unit test catching depreciated warning? I randomly delete one warning in cpython source code, but all test suite still passed.

You might refer to a historical commit(https://github.com/python/cpython/commit/beea26b57e8c80f1eff0f967a0f9d083a7dc3d66) from vstinner, which uses   `assertWarns` to check if the `DeprecationWarning` is thrown.
```python
with self.assertWarns(DeprecationWarning):
    do_something()
```
Also, you can check the git log of the deprecated module to see if the unit test was also committed :)

**Comment by gvanrossum** [comment]
> I don't know how to determine the last parameter of the function (`7` in two examples, `2` in the third)

This is the number of (Python) stack levels to skip when computing the file name and line number to appear in the message. I'd start setting it to 1 and see what warning message actually gets printed. Increase it until the filename is reasonable.

**Comment by kumaraditya303** [comment]
While we are at it, the same should be done for async generators too.

**Comment by ofey404** [comment]
I opened a pull request: #96428 

One problem: raise `DeprecationWarning` will break many lib tests, since they use the (type, val, tb) exception representation.

Eg:

https://github.com/python/cpython/blob/22ed5233b76fe33f9767c6a5665608e7f398e7d7/Lib/contextlib.py#L154-L155

**Comment by gvanrossum** [comment]
Would it be reasonable to fix the failing tests in the same PR? Or are there too many? They should all just switch to throwing the middle value of the triple (the exception instance).

**Comment by iritkatriel** [comment]
You'll get pretty far with the tests if you fix this one:

```
--- a/Lib/contextlib.py
+++ b/Lib/contextlib.py
@@ -152,7 +152,7 @@ def __exit__(self, typ, value, traceback):
                 # tell if we get the same exception back
                 value = typ()
             try:
-                self.gen.throw(typ, value, traceback)
+                self.gen.throw(value)
             except StopIteration as exc:
                 # Suppress StopIteration *unless* it's the same exception that
                 # was passed to throw().  This prevents a StopIteration

```

**Comment by ofey404** [comment]
The problem size is not so large. I'll try to submit a version fixing them.

With regex `throw\(.*,.*,.*\)`, there are 51 results in 12 files.

- 3 file is under `Lib`
- 1 is in `Lib/lib2to3/fixes`
- The rest are tests.
- [51 results in 12 files.txt](https://github.com/python/cpython/files/9457682/51.results.in.12.files.txt)

**Comment by iritkatriel** [comment]
Not all of them need to be ‘fixed’ though. 

Some of the tests are testing the deprecated API and need to stay (with the deprecation warning suppressed). 

lib2to3 maps the deprecated form to the single arg form. It should not change.

Also, I would run the tests and see what fails rather than rely on a regex  search.

**Comment by iritkatriel** [comment]
Note also that just emitting a deprecation warning doesn’t cause tests to fail (we don’t run the tests with warnings-as-errors in CI).

This is why I suggested the change in https://github.com/python/cpython/issues/96348#issuecomment-1232217457, because that actually causes most (if not all) of the test failures.

**Comment by ofey404** [comment]
> This is why I suggested the change in [#96348 (comment)](https://github.com/python/cpython/issues/96348#issuecomment-1232217457), because that actually causes most (if not all) of the test failures.

You're right.

**Comment by ofey404** [comment]
Should we close this since the PR is merged?

**Comment by gvanrossum** [comment]
Search other C files in the same directory for DeprecationWarning.

-- 
--Guido (mobile)

**Comment by AdamWill** [comment]
Wasn't this deprecation rather aggressive?

For generators at least, the single-argument form was only added in Python 3.9, at least according to the docs. It's not mentioned in the [3.8 docs](https://docs.python.org/3.8/reference/expressions.html#generator.throw), it only appears in the [3.9 docs](https://docs.python.org/3.9/reference/expressions.html#generator.throw).

3.8 is still in support for another whole year. So if I'm trying to fix something - like [twisted](https://github.com/twisted/twisted/blob/trunk/src/twisted/python/failure.py#L519) - to not print deprecation warnings constantly on Python 3.12, I either have to break it for a still-supported version of Python, or use some kind of rather ugly conditional to figure out what to pass it, right?

**Comment by AdamWill** [comment]
...or is this similar to https://github.com/python/cpython/issues/105269 and the single-argument form was actually added earlier, but not documented?
