### ISSUE TITLE
Improve coverage of `typing.get_overloads`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96357]
Right now `get_overloads` function is not fully covered:
<img width="612" alt="Снимок экрана 2022-08-28 в 11 49 55" src="https://user-images.githubusercontent.com/4660275/187066029-d4f3bf30-9a34-43c2-b1c2-635f7334f30f.png">

I will send a PR with a fix.

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
