### ISSUE TITLE
unittest.TestCase.assertRaises msg argument is not used

### ISSUE THREAD

**Issue by ptmcg** [python/cpython#96362]
# Bug report

[Docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) indicate that unitTest.TestCase.assertRaises supports an optional msg argument when used as a context manager, as an optional additional filter on matching exceptions.

The following code shows that the msg argument is not used. The test should fail because the exception string does not match the given compiled regex.

(It would also be nice if the initializer would accept a str and convert it to a compiled regex. There is no mention in the docs of what type is expected for msg.)

``` python
import unittest
import re

class AssertRaisesTest(unittest.TestCase):
    def test_x(self):
        d = {}
        # should not pass this test, since the exception 
        # string does not match the msg re
        with self.assertRaises(KeyError, msg=re.compile(r'xyz')) as ar:
            d['a']

if __name__ == '__main__':
    unittest.main()
```

# Your environment

- CPython versions tested on: 3.6 through 3.11
- Operating system and architecture: Windows 11

**Comment by ptmcg** [comment]
I misinterpreted the purpose of msg, this is not an error.

**Comment by Julien00859** [comment]
I understand the problem the same as you do, what is actually the purpose of `msg`?

**Comment by AlexWaygood** [comment]
@Julien00859, here's what the test failure would look like if you don't specify the `msg` parameter:

```pytb
>>> from unittest import TestCase
>>> c = TestCase()
>>> with c.assertRaisesRegex(TypeError, "foo"):
...     raise TypeError("bar")
...
TypeError: bar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 276, in __exit__
    self._raiseFailure('"{}" does not match "{}"'.format(
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 200, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: "foo" does not match "bar"
```

But if you specify the `msg` parameter, you get a custom message with your test failure (note the difference in the last line of the traceback):

```pytb
>>> with c.assertRaisesRegex(TypeError, "foo", msg="I WANTED FOO"):
...     raise TypeError("bar")
...
TypeError: bar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 276, in __exit__
    self._raiseFailure('"{}" does not match "{}"'.format(
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 200, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: "foo" does not match "bar" : I WANTED FOO
```

If you have further questions, please ask them at https://discuss.python.org/c/users/7 rather than posting on closed GitHub issues :)
