### ISSUE TITLE
difflib.SequenceMatcher.find_longest_match() returns wrong result

### ISSUE THREAD

**Issue by jwes44** [python/cpython#96363]
On windows 11 and python 3.9.7 and this code I get poor results. The problem seems to be that the first call to difflib.SequenceMatcher.find_longest_match() returns Match(a=14, b=549, size=1) which is clearly not the longest match.

import difflib
from difflib import SequenceMatcher
a = r"iu his chest. ' Roar upon roar of applause beat upon his eardrums. . He sought for and found the motionless body of the tiger and moved toward it on feet that seemed strangely mmib beneath him, but already his keen brain Was working. In his struggles with the tiger, he had approached within a half dozen paces of the scarlet gate. While he had fought, the scarlet-clad guards and. the priests had ducked behind the brass grating that closed the exit, but now they were filing back. Beyond them, Bourtai had said, a horse would be waiting. But Wan Tengri's resolution was already formed."
b = r"in his chest. Roar upon roar of applause beat upon his eardrums. He sought for and found the motionless body of the tiger and moved toward it on feet that seemed strangely numb beneath him, but already his keen brain was working. In his struggles with the tiger, he had approached within a half dozen paces of the scarlet gate. While he had fought, the scarlet-clad guards and the priests had ducked behind the brass grating that closed the exit, but now they were filing back. Beyond them, Bourtai had said, a horse would be waiting. But Wan Tengri's resolution was already formed."
s = SequenceMatcher(None, a,b)
for tag, i1, i2, j1, j2 in s.get_opcodes():
    print('{:7}   a[{}:{}] --> b[{}:{}] {!r:>8} --> {!r}'.format(
        tag, i1, i2, j1, j2, a[i1:i2], b[j1:j2]))

**Comment by sweeneyde** [comment]
I think this is a consequence of using `autojunk=True` (the default) in `SequenceMatcher`.

If you do `print(''.join(sorted(s.bpopular)))` in your example, you get something like `" .abcdefghilmnoprstuw"`, which is certainly a lot to consider to be "junk".

Using `SequenceMatcher(None, a, b, autojunk=False)` in your program gives a more expected result:

```
equal   a[0:1] --> b[0:1]      'i' --> 'i'
replace a[1:2] --> b[1:2]      'u' --> 'n'
equal   a[2:13] --> b[2:13] ' his chest.' --> ' his chest.'
delete  a[13:15] --> b[13:13]     " '" --> ''
equal   a[15:65] --> b[13:63] ' Roar upon roar of applause beat upon his eardrums' --> ' Roar upon roar of applause beat upon his eardrums'
delete  a[65:67] --> b[63:63]     '. ' --> ''
equal   a[67:176] --> b[63:172] '. He sought for and found the motionless body of the tiger and moved toward it on feet that seemed strangely ' --> '. He sought for and found the motionless body of the tiger and moved toward it on feet that seemed strangely '
insert  a[176:176] --> b[172:174]       '' --> 'nu'
equal   a[176:177] --> b[174:175]      'm' --> 'm'
delete  a[177:179] --> b[175:175]     'mi' --> ''
equal   a[179:221] --> b[175:217] 'b beneath him, but already his keen brain ' --> 'b beneath him, but already his keen brain '
replace a[221:222] --> b[217:218]      'W' --> 'w'
equal   a[222:380] --> b[218:376] 'as working. In his struggles with the tiger, he had approached within a half dozen paces of the scarlet gate. While he had fought, the scarlet-clad guards and' --> 'as working. In his struggles with the tiger, he had approached within a half dozen paces of the scarlet gate. While he had fought, the scarlet-clad guards and'
delete  a[380:381] --> b[376:376]      '.' --> ''
equal   a[381:587] --> b[376:582] " the priests had ducked behind the brass grating that closed the exit, but now they were filing back. Beyond them, Bourtai had said, a horse would be waiting. But Wan Tengri's resolution was already formed." --> " the priests had ducked behind the brass grating that closed the exit, but now they were filing back. Beyond them, Bourtai had said, a horse would be waiting. But Wan Tengri's resolution was already formed."
```

and

```
>>> s.find_longest_match()
Match(a=381, b=376, size=206)
```

I believe the autojunk feature is used to speed up the computations, and it works well when analyzing source code files, but it seems it has unintuitive results on some kinds of text.

**Comment by jwes44** [comment]
Thank you. That seems to fix my problem completely.

**Comment by jwes44** [comment]
Perhaps a note in the docks suggesting that if they get bad results trying it with autojunk=False.

**Comment by sweeneyde** [comment]
At https://docs.python.org/3/library/difflib.html , it looks like we already have:

> **Automatic junk heuristic**: [SequenceMatcher](https://docs.python.org/3/library/difflib.html?highlight=difflib#difflib.SequenceMatcher) supports a heuristic that automatically treats certain sequence items as junk. The heuristic counts how many times each individual item appears in the sequence. If an item’s duplicates (after the first one) account for more than 1% of the sequence and the sequence is at least 200 items long, this item is marked as “popular” and is treated as junk for the purpose of sequence matching. This heuristic can be turned off by setting the autojunk argument to False when creating the [SequenceMatcher](https://docs.python.org/3/library/difflib.html?highlight=difflib#difflib.SequenceMatcher).

**Comment by sweeneyde** [comment]
For posterity, I'll note that there are several essentially duplicate issues, such as https://github.com/python/cpython/issues/47235
