### ISSUE TITLE
Installing crash in Ubuntu 22.04

### ISSUE THREAD

**Issue by UmanSheikh** [python/cpython#96373]
# pip3 install functools

```diff
-Collecting functools
-Using cached functools-0.5.tar.gz (4.9 kB)
-Preparing metadata (setup.py) ... done
-Building wheels for collected packages: functools
-Building wheel for functools (setup.py) ... error
-error: subprocess-exited-with-error
 
-× python setup.py bdist_wheel did not run successfully.
-│ exit code: 1
-╰─> [87 lines of output]

```

# setup.py bdist_wheel did not run successfully

```bash
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> functools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```
# Details
While Installing functools I am facing the above error. Can you please fix it? I am using Ubuntu 22.04 OS. As far as I know, error is in either setup.py file or __init__.py file.

**Comment by hauntsaninja** [comment]
functools has been part of the standard library since Python 2.5

**Comment by Umansheikh224** [comment]
Okay. I got it. Actually I read on an old blog which says to install it. That's why I use command. By the way I didn't knew that it has become standard library.
