### ISSUE TITLE
`TypeVarTuple.__typing_prepare_subst__` does not work as intented

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96385]
Right now there's an uncovered branch in `TypeVarTuple.__typing_prepare_subst__`:

<img width="775" alt="Снимок экрана 2022-08-29 в 15 16 14" src="https://user-images.githubusercontent.com/4660275/187199050-d95b0e39-d260-4fcd-aef6-ebd376019648.png">

And it looks like there's a bug in it, [these two lines](https://github.com/python/cpython/blob/b2714f05c5cc8765178f296f0f8043410e3a5584/Lib/typing.py#L1077-L1078):

```python
        for param in enumerate(params[typevartuple_index + 1:]):
            if isinstance(param, TypeVarTuple):
```

This `if`'s body will never be executed, because `enumerate` always returns `tuple[int, T]`, it is never `TypeVarTuple`.

So, I think that we need to remove `enumerate()` call here and add a test like:

```python
>>> from typing import Generic, TypeVarTuple
>>> V = TypeVarTuple('V')
>>> T = TypeVarTuple('T')
>>> class My(Generic[*T]): pass
... 
>>> My[*T, *V][*V]
TypeError: More than one TypeVarTuple parameter in __main__.My[*T, *V]
```

I will send a PR 😉

**Comment by hauntsaninja** [comment]
Thanks for spotting this, looks like this has been completed
