### ISSUE TITLE
configure.ac: using $CC to check compiler names may result in erroneous judgements

### ISSUE THREAD

**Issue by kanavin** [python/cpython#96398]
configure.ac contains multiple checks of this kind:
```
case $CC in
```

When paths contain "clang"/"gcc"/"icc", they might be part of $CC
for example because of the "--sysroot" parameter. That could cause
judgement error about clang/gcc/icc compilers. e.g.
    
when "icc" is containded in working path, below errors are reported when compiling python3:

x86_64-wrs-linux-gcc: error: strict: No such file or directory
x86_64-wrs-linux-gcc: error: unrecognized command line option '-fp-model'

### Linked PRs
* gh-117815
* gh-117819
* gh-117825
* gh-117836
* gh-117857

**Comment by tiran** [comment]
We are aware that the checks are problematic have already plans to replace `$CC` checks with `$ac_cv_cc_name`. It's a new variable that I introduced a short while ago.

**Comment by tiran** [comment]
CC @erlend-aasland @mdboom

**Comment by erlend-aasland** [comment]
cc. @corona10

**Comment by erlend-aasland** [comment]
A quick summary:

#110034 points out that we've got various attempts to detect the compiler version in configure. There's the `$CC` variable, there's `$cc_is_clang`, `$ac_cv_cc_name`, and `$GCC`. All four of them are used.

#110577 points out that the compiler selection check on macOS is at least partly obsolete. Perhaps that issue deserves to be re-opened and investigated on its own.

`$ac_cv_cc_name` was introduced by Christian in 3124d9a5aafb64431aa9facd0ae0e12201be77fa (PR: #93492, issue: #93491).

**Comment by erlend-aasland** [comment]
#117815 adapts most relevant checks to use `$ac_cv_cc_name`. Reviews welcome!

**Comment by erlend-aasland** [comment]
This should now be resolved. Please shout out if you still encounter problems.
