### ISSUE TITLE
Docs give incorrect grouping for conditional expressions

### ISSUE THREAD

**Issue by kaya3** [python/cpython#96417]
# Documentation

Quoting from [6.17 Operator Precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence):

> Operators in the same box group left to right (except for exponentiation, which groups from right to left).

Another exception should be included for conditional expressions, which also group from right to left: `a if b else c if d else e` is equivalent to `a if b else (c if d else e)`, not `(a if b else c) if d else e`.

**Comment by rhettinger** [comment]
Agreed.

Do care to make a PR?
