### ISSUE TITLE
asyncio.gather overhead is quite large (~40 times vs await one by one)

### ISSUE THREAD

**Issue by orenwang** [python/cpython#96450]
This costs ~0.29s:
```python
import asyncio
from time import time

async def my_func():
    return 1

async def one_by_one():
    start_t = time()
    for _ in range(1000):  # Repeat 1,000 times.
        for _ in range(3000):
            await my_func()
    print(f"Cost {time() - start_t}s")

asyncio.run(one_by_one())
```

This costs ~11.71s:
```python
import asyncio
from time import time

async def my_func():
    return 1

async def gather_them():
    start_t = time()
    for _ in range(1000):  # Repeat 1,000 times.
        coros = []
        for _ in range(3000):
            coros.append(my_func())
        await asyncio.gather(*coros)
    print(f"Cost {time() - start_t}s")

asyncio.run(gather_them())
```

OK, I understand `my_func` has no I/O related code, so what I get from `asyncio.gather` is pure overhead. e.g. context switches. But is it normal that the overhead is that large?

Assuming I have to manage and call async "handlers", but whatever happens inside any "handler" depends on the user side. So is it recommended to just run one by one if I have a lot of "handlers", even though that would cause one slow "handler" to block everything?

**Comment by ht-thomas** [comment]
I've not run tests on the two methods yet, but by first look of things, I don't think the overhead in the second method is coming from the gather coroutine.

First of all, you're creating the coros list 1000 times, and calling it's append method 3000 times, this alone is just plain bulky before we even reach to the gather.

**Comment by orenwang** [comment]
@ht-thomas Thanks for the reply. I've thought about all the list operations but I thought that should not be a big overhead. Now that you brought it up, I tested the code below. indeed, there is some overhead (larger than I thought) but is far less than `asyncio.gather`.

This costs ~2.32s:
```python
import asyncio
from time import time

async def my_func():
    return 1

async def gather_them():
    start_t = time()

    for _ in range(1000):
        coros = []
        for _ in range(3000):
            coros.append(my_func())
        # await asyncio.gather(*coros)
        _ = [*coros]
    print(f"Cost {time() - start_t}s")

asyncio.run(gather_them())
```

**Comment by ht-thomas** [comment]
True, in such trivial cases you might say that gather is adding lots of overhead, but in real world scenarios, it becomes insignificant on a way. The first method is generally running in a way a synchronous operation would run, with no concurrency, so it would just run fast and end. Try using cProfile to get the stats on the execution of both methods, I don't think I've explained anything but the results from using a profiler will help you understand how things are working.

**Comment by orenwang** [comment]
Sure I will profile this using cProfile soon (after I learn how to use it...)

Actually I came here from trying to build a library, where I call a lot of async handlers one by one (by mistake) and is very satisfied with the performance. However, after I fix that mistake and call multi async handlers in `asyncio.gather`, my library suddenly became too slow to use in real world 😂

**Comment by kumaraditya303** [comment]
I wonder if `asyncio.gather` can now be implemented using `asyncio.TaskGroup` so if we optimize taskgroups,  gather will speed up automatically.

**Comment by gvanrossum** [comment]
> I wonder if `asyncio.gather` can now be implemented using `asyncio.TaskGroup` so if we optimize taskgroups, gather will speed up automatically.

I doubt that, the semantics are subtly different (IIRC there are cases where `gather()` doesn't wait for all tasks by design).

Re: the original question in this issue, is `TaskGroup` any faster? @orenwang

**Comment by gvanrossum** [comment]
@orenwang Can you also see if there's something quadratic going on? E.g. try calling `gather` with different numbers of tasks, say 500, 1000, 1500, 2000, 2500, 3000, and see if the time increases linearly or not.

For an explanation, I would look not just to gather (which does do a lot of work, like creating a Task and setting a callback on it) but also to the event loop -- your "bare" example doesn't even invoke the event loop at all. (You could try what happens if you put `await asyncio.sleep(0)` in my_func().)

**Comment by orenwang** [comment]
Many thanks for pointing the directions! What I found out so far:

> ... is TaskGroup any faster?

It's ~12% faster. Helps a little but not much. I tested it with the code below, using Python 3.11.0b4:
```python
import asyncio
from time import time

async def my_func():
    return 1

async def run_with_tg():
    start_t = time()
    for _ in range(1000):
        async with asyncio.TaskGroup() as tg:
            for _ in range(3000):
                tg.create_task(my_func())
    print(f"Cost {time() - start_t}s")

asyncio.run(run_with_tg())
```


> ... if there's something quadratic going on? 

Nope. What I see is a **linear** process, with 500, 1000, 1500, 2000, 2500, 3000 numbers of tasks.

**Comment by orenwang** [comment]
So I suppose for the purposes of my library, I could just document something like "if there isn't any event loop involved, just use a sync handler instead of an async one", allowing me to handle sync ones differently maybe.
