### ISSUE TITLE
CACHE and SWAP documentation is vague with the meaning of the oparg

### ISSUE THREAD

**Issue by MatthieuDartiailh** [python/cpython#96461]
# Documentation

The current documentation says that CACHE and SWAP acts on the *i*th element of the stack but it is nowhere mentioned if the stack is indexed from 0 or 1. Looking at the actual implementation in ceval.c makes the answer obvious but it is tedious and the documentation could be improved I believe.

* PR: gh-96462

**Comment by hauntsaninja** [comment]
Should this PR have been backported to 3.11?

**Comment by MatthieuDartiailh** [comment]
It could be but 3.12 already changed quite a bit to the bytecode and the back port would not be straightforward.

**Comment by hauntsaninja** [comment]
Okay, thanks, I'll close this then :-)
