### ISSUE TITLE
[wasm32-emscripten] Emscripten node build is not portable to windows

### ISSUE THREAD

**Issue by rchiodo** [python/cpython#96509]
# Bug report

Emscripten-node builds should be portable to other platforms. Copying an emscripten-build to a windows machine throws an error on startup:

```
Exception ignored error evaluating path:
Traceback (most recent call last):
  File "<frozen getpath>", line 268, in <module>
OSError: failed to make path absolute
Fatal Python error: error evaluating path
```

The root cause I believe is here:

https://github.com/python/cpython/blob/656167db81a53934da55d90ed431449d8a4fc14b/Python/fileutils.c#L1993

Emscripten builds don't define MS_WINDOWS (and they shouldn't) but the emscripten-node build has to be able to handle running on windows too. 

# Your environment

- CPython versions tested on: Emscripten-node-debug build
- Operating system and architecture: Windows 10 x64

**Comment by rchiodo** [comment]
I'd like to try fixing this if I can. 

I was thinking there would be another #Ifdef for WASM and it would run both the posix checks and the windows checks for an absolute path.

I'm guessing there's more locations related to paths that don't port though.

**Comment by encukou** [comment]
Emscripten is now unsupported. I'll close this.
Like other Emscripten issues, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back.
