### ISSUE TITLE
main branch code cleanups for int_max_str_digits non-backportable TODOs

### ISSUE THREAD

**Issue by gpshead** [python/cpython#96512]
I had some post-merge TODOs ready in https://github.com/python/cpython/pull/96499 for improvements specific to the main (3.12) branch. This is a rollup issue for those, they're all small:

- [x] Cleanup: Move `int_max_str_digits` into PyConfig in 3.12.
- [ ] ~~Use `int32_t` or `Py_ssize_t` instead of `int` for the max digits value internally.~~
- [ ] ~~Minor feature: add [PEP-578](https://peps.python.org/pep-0578/) `PySys_Audit` hook calls at the new ValueError raise spots.~~
- [x] Once this ships in 3.11.0: Update the version notes about it in the 3.12 docs to say 3.11 and remove the 3.12 whatsnew text about it. The original PR was created not knowing exactly when we'd be able to merge.

**Comment by isuruf** [comment]
Could the limit be a configuration option, so that people who build from source can configure the limit?

**Comment by gpshead** [comment]
> Could the limit be a configuration option, so that people who build from source can configure the limit?

Lets have that be its own issue if someone comes up with a compelling use case for it.

My thinking in not including a configure flag to start with is that anyone who builds from source likely also carries patches to their sources so there isn't a good reason to offer a configure option. We don't want to encourage interpreters built and shipped in different environments to have different limits as that can create compatibility headaches for application and library authors potentially expanding their test matrix.
