### ISSUE TITLE
Math.Sin() Function Computational Error

### ISSUE THREAD

**Issue by lbalossa** [python/cpython#96520]
# Bug report

Math.sin() function call returns  0.8939966636005579 instead of 1.0 when the argument passed to the function is 90. The returned value is incorrect. 

# Your environment

- CPython versions tested on:  Tested on Python version 2.7 and 3.10.6 (64-bit)
- Operating system and architecture:  Lunux Red Hat 7 and Microsoft Windows 10

**Comment by sweeneyde** [comment]
This is the expected behavior: see https://docs.python.org/3/library/math.html#math.sin:

> math.sin(x)
>     Return the sine of x radians.

If you need to use degrees, then you need to convert to radians first:
```
>>> from math import sin, radians
>>> sin(radians(90))
1.0
```

**Comment by lbalossa** [comment]
I overlooked the conversion to radians.

Thank you,

L.B.
