### ISSUE TITLE
Change docstring of `format()` built-in

### ISSUE THREAD

**Issue by mikez** [python/cpython#96526]
# Feature or enhancement

The [`format.__doc__`](https://github.com/python/cpython/blob/bbcf42449e13c0b62f145cd49d12674ef3d5bf64/Python/bltinmodule.c#L680) currently states

```
Return value.__format__(format_spec)

format_spec defaults to the empty string.
See the Format Specification Mini-Language section of help('FORMATTING') for
details.
```

I propose to change this to

```
Return type(value).__format__(value, format_spec)

Many built-in types implement format_spec according to the
Format Specification Mini-language. See help('FORMATTING').

If type(value) does not supply a method named __format__
and format_spec is empty, then str(value) is returned.
See also help('SPECIALMETHODS').
```

While I'm at it, I propose to also clarify the docstrings of `object.__format__` and `int.__format__`. (See [comment here](https://github.com/python/cpython/issues/96526#issuecomment-1236221742) for current behavior.)

# Pitch

I saw this documentation today and it confused me as I tried to understand how to format `bytes`. The help prompted me to look at `help('FORMATTING')` which seemed misleading. Only after looking at the C-code of `format()` did I understand what was going on.

The main clarifications I added here was:

1. no, not all types support this
2. the behavior of `object.__format__` and pointer to [`__format__` documentation](https://docs.python.org/3/reference/datamodel.html#object.__format__).
3. `type(value).__format__(...)` is returned, not `value.__format__(...)`

Moreover, I propose to remove "format_spec defaults to the empty string", since this is shown already in "help()" through the function signature.

# Previous discussion

- https://github.com/python/cpython/pull/166
- https://github.com/python/cpython/issues/73712

_Note: Updated on 2022-09-03 to include @Teamspen210's remark._
_Note: Updated on 2022-09-05 to include @ericvsmith's remark._
_Note: Updated on 2022-09-06 to include @Teamspen210's remark._
_Note: Updated on 2022-09-07 to include new findings upon reading the C code._

**Comment by TeamSpen210** [comment]
The mini-language actually doesn't only apply to strings. Most of those options are actually specific to numeric types. The fallback you mentioned is quite correct though.

**Comment by mikez** [comment]
@TeamSpen210 Thank you. I updated the proposal wording to include numeric types. Also, for further verification, I tested `x.__format__` for all built-ins. Only `str`, `complex`, `float`, `bool`, and `int` seemed to work at this time.

As an aside, and likely this has been discussed before—since `bytes` values are a list of integers, maybe letting `bytes.__format__` use the mini-language too could make sense. Thus, `format(b'\xcb\x80\x00\x00', 'b')` may return akin to `''.join(format(i, 'b') for i in b'\xcb\x80\x00\x00')`

**Comment by ericvsmith** [comment]
> Only `str`, `complex`, `float`, `bool`, and `int` seemed to accept a non-empty format_spec at this time.

There's also at least `datetime.datetime`, `.date`, and `.time`; and `decimal.Decimal`.

The actual behavior is that (after a few optimizations) it really just calls `value.__format__(format_spec)`. I'm not sure it's a good idea to always point to the mini-language. The `datetime` types don't use it, for example. Maybe some hand waving like "For many builtin types see help('FORMATTING')", or something like that. It's also true that if a type doesn't define `__format__` and thus relies on `object.__format__`, it's an error to specify a non-empty string.

**Comment by mikez** [comment]
@ericvsmith Thank you for the pointer. I had only checked built-in types (via `import builtins`). I now also searched the built-in modules. Besides `datetime` and `decimal`, there is also `enum` and `ipaddress`.

I'll ponder a bit on how to reformulate this to make it explicit yet simple and readable.

While I'm at it, I checked the various `help(x.__format__)`. Some are helpful, some I found less so.

These are confusing to me:

```py
>>> import inspect; doc = inspect.getdoc
>>> doc(object.__format__)
'Default object formatter'
>>> doc(int.__format__)
'Default object formatter'
>>> doc(bool.__format__)
'Default object formatter.'
>>> doc(bytes.__format__)  # as an example of a type without a defined __format__
'Default object formatter.'
>>> doc(decimal.Decimal.__format__)
'Default object formatter.'
```

These I find more helpful, and some may benefit from a pointer to the mini-language:

```py
>>> doc(str.__format__)
'Return a formatted version of the string as described by format_spec.'
>>> doc(float.__format__)
'Formats the float according to format_spec.'
>>> doc(complex.__format__)
'Convert to a string according to format_spec.'
>>> doc(datetime.date.__format__)
'Formats self with strftime.'
>>> doc(enum.Enum.__format__)
'Returns format using actual value type unless __str__ has been overridden.'
```
```
>>> print(doc(ipaddress.IPv4Address.__format__))
Returns an IP address as a formatted string.

Supported presentation types are:
's': returns the IP address as a string (default)
'b': converts to binary and returns a zero-padded string
'X' or 'x': converts to upper- or lower-case hex and returns a zero-padded string
'n': the same as 'b' for IPv4 and 'x' for IPv6

For binary and hex presentation types, the alternate form specifier
'#' and the grouping option '_' are supported.
```

**Comment by mikez** [comment]
@ericvsmith @TeamSpen210 Your comments helped me think more clearly. I updated the wording and pitch with what I think captures the essence. What do you think?

**Comment by TeamSpen210** [comment]
I'd suggest tweaking the second sentence a bit, to indicate that the spec has to be empty if no `__format__` method is defined.

**Comment by ericvsmith** [comment]
What’s the PR number?

**Comment by mikez** [comment]
@TeamSpen210 Updated. Thank you.

@ericvsmith No PR yet. My intention with posting here was to understand if this kind of a change would be welcomed. I've never done a Python PR before, but happy to try. :) Is the process described [here](https://devguide.python.org/getting-started/pull-request-lifecycle/) the current one?

**Comment by ericvsmith** [comment]
@mikez Yes, I think that's correct.

**Comment by mikez** [comment]
@ericvsmith see PR above.

I made two additional changes
- `type(value).__format__(value, format_spec)` (if I read the C code correctly)
- clarified the docstrings of `object.__format__` and (for me) misleading `int.__format__`

`decimal.Decimal` might need to change too, since it misleadingly shows the docstring of `object.__format__`. However, I don't quite understand yet how their docstrings work—it seems to involve `decimal.rst` somehow? I could need some help here.

**Comment by mikez** [comment]
@ericvsmith @TeamSpen210 To clarify, when I did the pull request, it seems it got auto-assigned to @markshannon as a reviewer. Should I instead have assigned it to one of you? Or, is this reviewer-assignment correct, and I have to expect to wait at least a month or some more for it to get reviewed? (Asking, since I'm new here.)

**Comment by ericvsmith** [comment]
I’m not sure why it was assigned to Mark. This is on my list of things to look at the week of October 3, when I’m at a sprint and plan to knock out a bunch of PRs.

**Comment by mikez** [comment]
@ericvsmith Thank you for the clarification. (Also odd, I couldn't find any way on Github to reassign it or add you to it, at least not with my current user permissions.)

**Comment by ericvsmith** [comment]
I see it as unassigned. I'll assign it to myself.

**Comment by mikez** [comment]
@ericvsmith 👍 To clarify, when I said "assigned" I meant the PR: https://github.com/python/cpython/pull/96648

**Comment by ericvsmith** [comment]
I see Mark as a reviewer, not assignee. I've assigned the PR to myself.

**Comment by mikez** [comment]
@ericvsmith I previously thought of reviewer and assignee as synonymous, but according to [this article](https://stackoverflow.com/q/41087206) it seems they're not. I guess for Python "assignee" is relevant here, and reviewer acts more like a CC in email.
