### ISSUE TITLE
argparse: 'name' variable unused when handling ArgumentTypeError

### ISSUE THREAD

**Issue by JonathonReinhart** [python/cpython#96548]
The `name` variable in this block is unused:
https://github.com/python/cpython/blob/ac4ddab405a36bd0e2b86bcd147b3a647b734492/Lib/argparse.py#L2525-L2528

**Comment by saito828koki** [comment]
@JonathonReinhart 

Hello,

Thank you for your report!
Have you already started to fix it?
I am a new grad student and finding an easy issue, so if you have not started yet, I want to fix it.

Thank you,

**Comment by JonathonReinhart** [comment]
Hi @saito828koki -- Yes, it is trivial to just remove the unused variable. I have a commit and will be submitting a PR soon. You won't learn anything by fixing this issue, so I would suggest you find another more challenging bug :-)

**Comment by saito828koki** [comment]
@JonathonReinhart 
Thanks for your reply!

> You won't learn anything by fixing this issue
That's exactly right. I will find another better issue!
