### ISSUE TITLE
Typo in: Standard Library >  Other Built-in Types > Modules

### ISSUE THREAD

**Issue by joe-gregory** [python/cpython#96540]
# Documentation
In the second sentence of the "Modules" subsection under "Other Built-in Types", it reads: 
_Module attributes can be assigned **to**._

Most likely what was meant was: 
_Module attributes can be assigned **too**._

**Comment by ericvsmith** [comment]
No, the sentence is trying to say something along the lines of “you can assign values to module attributes”. So nodule attributes can be assigned to. Maybe not the world’s best sentence, but it’s not incorrect in its meaning.

**Comment by joe-gregory** [comment]
Ok, I didn't understand it in its original form.
