### ISSUE TITLE
Checkbutton will not work properly when font is set to a color "near" white

### ISSUE THREAD

**Issue by gitagogaming** [python/cpython#96550]
I stumbled on this bug for at least an hour today before I noticed it was an actual bug

When the text is colored near/close to white it will not activate properly

Python Version: 3.9.9
Operating System: Windows 10 64bit

Here is a code snippet so you can try for yourself.
```
from tkinter import * 


root = Tk()
root.geometry("300x200")
  
w = Label(root, text ='Broken Checkbox', font = "50") 
w.pack()

        
enable_DVR = IntVar()
broken_checkbox = IntVar()

chk_EnableDVR = Checkbutton(root, text="MEH",
    variable=enable_DVR,
    foreground="red",
    background="#585858",
    offvalue=0,
    onvalue=1
    
)

broken_checkbox = Checkbutton(root, text="MEH2",
    variable=broken_checkbox,
    foreground="#F5F5F5",
    background="#585858",
    offvalue=0,
    onvalue=1
    
)

broken_checkbox.pack()
chk_EnableDVR.pack()

  
mainloop() 
```

**Comment by sweeneyde** [comment]
This is what I see with your code:

<img src='https://user-images.githubusercontent.com/36520290/188356807-bc8e04fb-d843-48e7-a42d-aa1c07c21ead.png' width='300'><img src='https://user-images.githubusercontent.com/36520290/188356843-332ddfcd-8bd9-4df3-9ef6-ca276acaa264.png' width='300'>

When I add `selectcolor="#000000",` to your `Checkbutton(...)`, I get this:

<img src='https://user-images.githubusercontent.com/36520290/188357702-5470cb8a-2247-415f-beab-2fe35ea75804.png' width='300'><img src='https://user-images.githubusercontent.com/36520290/188357403-eb4eac30-20cd-47b3-a8b4-238157fb9892.png' width='300'>

Does that address your issue?

**Comment by gitagogaming** [comment]
> This is what I see with your code:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/36520290/188356807-bc8e04fb-d843-48e7-a42d-aa1c07c21ead.png"><img alt="" width="300" src="https://user-images.githubusercontent.com/36520290/188356843-332ddfcd-8bd9-4df3-9ef6-ca276acaa264.png">
> 
> When I add `selectcolor="#000000",` to your `Checkbutton(...)`, I get this:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/36520290/188357702-5470cb8a-2247-415f-beab-2fe35ea75804.png"><img alt="" width="300" src="https://user-images.githubusercontent.com/36520290/188357403-eb4eac30-20cd-47b3-a8b4-238157fb9892.png">
> 
> Does that address your issue?

No unfortunately this does not fix or address the issue as I have gone ahead and did that for both buttons and set it to #FFFFFF instead of black, cause i want i want mine to be white   
This same issue is happening on numerous other widgets in tkinter where if its set to white or near white it will not function properly.

**Comment by gitagogaming** [comment]
> If the forward and the background colours are the same then you can't see whether it works or not. You need them to be different colours.

Ok so now I am actually seeing where I went wrong here... 
I overlooked the obvious due to getting distracted by a visual "glitch" so to speak..
In my example when you click the action, it briefly shows the checkbox even though its supposedly white. and then it disappears so thats what had me thinking it was a bug of some sort 

I appreciate your patience and what not with me :)
