### ISSUE TITLE
pip install crcmod for 3.10 on Win10 terminal change font

### ISSUE THREAD

**Issue by kyrreaa** [python/cpython#96578]
Every time I install crcmod on a fresh python 3.10 install on Windows 10 using a terminal window it changes the terminal windows font when running the final setup.
![image](https://user-images.githubusercontent.com/3826624/188432367-5361ecc3-9fea-4ac7-a67b-86eee0699525.png)
![image](https://user-images.githubusercontent.com/3826624/188432408-df90c2e9-96ea-4937-a00d-da9448bf8a38.png)
Uninstalling the package and repeating with fresh window shows same behavior every time.

**Comment by mdickinson** [comment]
Hi @kyrreaa. This tracker is for bugs in core Python. This _could_ conceivably be a problem in core Python, but it seems unlikely and we don't really have sufficient evidence of that at the moment: it could also be an issue in `pip`, in `setuptools`, in `crcmod` itself, or arising from some other source. You _might_ be able to get more help on the `pip` tracker, but be prepared to give more details about the exact package versions you used and your operating system.

I'm going to close here; I don't think there's anything to be done at core Python level.

**Comment by eryksun** [comment]
The classic console window may switch to a different font when the output code page is changed (e.g. `chcp.com 936`). The "setup.py" of crcmod builds an extension module. Maybe the build system modifies the console code page.

**Comment by kyrreaa** [comment]
Thanks for the insight. That may well be the case. Maybe it is even testable.
