### ISSUE TITLE
Potential bug in eq.h

### ISSUE THREAD

**Issue by sternopanko** [python/cpython#96573]
https://github.com/python/cpython/blob/097f74a5a37e2a8a26d529cede456ede7011b66f/Objects/stringlib/eq.h#L20

Hi! It seems like there might be a bug here. Why does cmp(a,b) -> a.len == 0 return 1?
I might not have understood the code but it seems off

Thank you!

**Comment by ronaldoussoren** [comment]
The if statement above this test checks that the sizes of the two strings are equal.  If the sizes are equal and 0 the strings are equal.

**Comment by sternopanko** [comment]
Yeah looks fine, my bad.
Thanks!

**Comment by sternopanko** [comment]
Would it not be faster to cache the result of PyUnicode_GET_LENGTH on the stack, though?
