### ISSUE TITLE
Inconsistent `ast.parse` result for `python<3.11` and PEP654

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96587]
PEP654 introduced exception groups and `except*` in python3.11
Link: https://peps.python.org/pep-0654/

Right now it is possible to parse `except*` with older `ast.parse(..., feature_version=(3, 10))`.
Example:

```python
>>> import ast
>>> code = '''
... try:
...   ...
... except* Exception:
...   ...
... '''
>>> 
>>> ast.parse(code)
<ast.Module object at 0x10c685410>
>>> ast.parse(code, feature_version=(3, 8))
<ast.Module object at 0x10c685280>
>>> 
```

Which is not correct.

But, unlike https://github.com/python/cpython/issues/96427 it is very simple to fix. And I belive it should be fixed.

I've already applied a patch and will send it shortly after :)

**Comment by pablogsal** [comment]
Thanks for the PR!

**Comment by iritkatriel** [comment]
This is resolved now, right?
