### ISSUE TITLE
i'm trying to create a login screen in python but the images i put on it don't show up when i try to run the code

### ISSUE THREAD

**Issue by Kpssouza** [python/cpython#96590]
first i apologize if i wrote something wrong, i'm brazilian and i'm not good at english so i'm using google translator.
About my problem, recently the programming course I'm studying passed a job where I need to make an inventory control system, and one of the requirements was to have a good interface. So I started making a login screen following youtube videos, the problem is that when I tried to run my code, the login screen appeared, but the images I put in it just disappeared:
![image](https://user-images.githubusercontent.com/112887965/188489691-e4e820a0-141b-45ab-9e3e-e3b439c91cbc.png)
how my screen is looking.

![image](https://user-images.githubusercontent.com/112887965/188489774-533a02af-dff9-4162-aac6-d8291d4f839d.png)
how i wanted it to stay.

resources I'm using to make this system:
- Visual Studio Code.
- Qty designer
- language: python

**Comment by mdickinson** [comment]
Hi @Kpssouza. This isn't really a problem that we can help with here - this tracker is a place where you can help us with issues in core Python itself, not a place for us to help you with your Python code. You might consider asking for help at [discuss.python.org](https://discuss.python.org/) or a similar forum.

I'll close here.
