### ISSUE TITLE
os.path.exists(True) returns True

### ISSUE THREAD

**Issue by maginth** [python/cpython#96614]
# Bug report

os.path.exists(True) returns True, it should be False
This was used to detect if an arbitrary function argument is a path.

# Your environment

Python 3.8.13

- CPython versions tested on:
- Operating system and architecture: Linux Mint 20.3 Cinnamon, Intel© Xeon© CPU E5-2630 v3 @ 2.40GHz × 8

**Comment by maginth** [comment]
I see, it is hard not to fall for it when first encountered. Maybe it should reject type bool or at least print a warning.

**Comment by matthiasgoergens** [comment]
Is os.path.exists even a good way to detect if something is a path?

**Comment by mdickinson** [comment]
> Maybe it should reject type bool or at least print a warning.

An instance of `bool` _is_ an instance of `int`, so it would be a bit odd to either reject or warn about a `bool` argument. In your code, you probably want to test for `isinstance(str, os.PathLike)` (or something similar, depending on your needs and on how the tested value is going to be used) before calling `os.path.exists`.

I'll close here.

**Comment by maginth** [comment]
I don't have problem with my code, I fixed it immediately. I use the mtime of args corresponding to files for unvalidating the cache of a custom cache decorator.
os.PathLike seems to be for type hinting only, I just check if not isinstance(arg, int) as stdin/stdout have a mtime.

**Comment by maginth** [comment]
Thanks for the responses
