### ISSUE TITLE
Tracemalloc should skip incomplete frames when creating traceback.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#96612]
In the process of implementing https://github.com/python/cpython/issues/96421, I discovered that tracemalloc doesn't filter out incomplete frames. This might be an issue when allocating in the `RETURN_GENERATOR` instruction.

This might only be a hypothetical problem, but it should be fixed anyway.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/96613
