### ISSUE TITLE
python -m test test_unitttest -R3:3 fails

### ISSUE THREAD

**Issue by sweeneyde** [python/cpython#96624]
For the last couple months, it seems buildbots have been failing `-m test test_unittest -R3:3`, then re-trying the 3 failed test cases and passing on the re-try. Look at https://buildbot.python.org/all/#/builders/123 for example. The tests consistently pass the first warmup run, then fail on the second warmup run.

Example stdout from running `-m test test_unittest -R3:3 -v`:

```
======================================================================
FAIL: test_loadTestsFromName__module_not_loaded (test.test_unittest.test_loader.Test_TestLoader.test_loadTestsFromName__module_not_loaded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_unittest\test_loader.py", line 594, in test_loadTestsFromName__module_not_loaded
    self.assertEqual(list(suite), [])
AssertionError: Lists differ: [<unittest.loader._FailedTest testMethod=dummy>] != []

First list contains 1 additional elements.
First extra element 0:
<unittest.loader._FailedTest testMethod=dummy>

- [<unittest.loader._FailedTest testMethod=dummy>]
+ []

======================================================================
FAIL: test_loadTestsFromNames__module_not_loaded (test.test_unittest.test_loader.Test_TestLoader.test_loadTestsFromNames__module_not_loaded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_unittest\test_loader.py", line 1019, in test_loadTestsFromNames__module_not_loaded
    self.assertEqual(list(suite), [unittest.TestSuite()])
AssertionError: Lists differ: [<uni[15 chars]tSuite tests=[<unittest.loader._FailedTest testMethod=dummy>]>] != [<uni[15 chars]tSuite tests=[]>]

First differing element 0:
<unit[13 chars]stSuite tests=[<unittest.loader._FailedTest testMethod=dummy>]>
<unit[13 chars]stSuite tests=[]>

- [<unittest.suite.TestSuite tests=[<unittest.loader._FailedTest testMethod=dummy>]>]
+ [<unittest.suite.TestSuite tests=[]>]

======================================================================
FAIL: test_loadTestsFromNames__unknown_attr_name (test.test_unittest.test_loader.Test_TestLoader.test_loadTestsFromNames__unknown_attr_name)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_unittest\test_loader.py", line 715, in test_loadTestsFromNames__unknown_attr_name
    error, test = self.check_deferred_error(loader, list(suite)[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_unittest\test_loader.py", line 620, in check_deferred_error
    self.assertEqual(1, len(loader.errors))
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 1001 tests in 8.861s

FAILED (failures=3, skipped=55)
test_unittest failed (3 failures)

== Tests result: FAILURE ==

1 test failed:
    test_unittest

Total duration: 18.3 sec
Tests result: FAILURE
```

I bisected to here:

> commit c735d545343c3ab002c62596b2fb2cfa4488b0af
> Author: Victor Stinner <vstinner@python.org>
> Date:   Tue Jun 21 10:27:59 2022 +0200
> 
>     gh-93839: Move Lib/unttest/test/ to Lib/test/test_unittest/ (#94043)
> 
>     * Move Lib/unittest/test/ to Lib/test/test_unittest/
>     * Remove Lib/test/test_unittest.py
>     * Replace unittest.test with test.test_unittest
>     * Remove unittest.load_tests()
>     * Rewrite unittest __init__.py and __main__.py
>     * Update build system, CODEOWNERS, and wasm_assets.py

cc @vstinner

**Comment by sweeneyde** [comment]
For convenience, here are those tests:

https://github.com/python/cpython/blob/56d9cf7fc87d2cd7b8231c44f1d710ee77fbb998/Lib/test/test_unittest/test_loader.py#L580-L600

https://github.com/python/cpython/blob/56d9cf7fc87d2cd7b8231c44f1d710ee77fbb998/Lib/test/test_unittest/test_loader.py#L1005-L1025

https://github.com/python/cpython/blob/56d9cf7fc87d2cd7b8231c44f1d710ee77fbb998/Lib/test/test_unittest/test_loader.py#L704-L720

**Comment by sweeneyde** [comment]
It appears to be something a bad interaction between those three test methods and `test.test_unittest.testmock.testpatch.PatchTest.test_dotted_but_module_not_loaded`:

https://github.com/python/cpython/blob/56d9cf7fc87d2cd7b8231c44f1d710ee77fbb998/Lib/test/test_unittest/testmock/testpatch.py#L1916-L1932

**Comment by sweeneyde** [comment]
Here's the bare essentials of what is failing:

```python
import sys
from unittest.mock import patch

if 1: # change to 1 to see "tu.dummy" fail.

    # Inline test_dotted_but_module_not_loaded

    import test.test_unittest.testmock.support
    with patch.dict('sys.modules'):
        del sys.modules['test.test_unittest.testmock.support']
        del sys.modules['test.test_unittest.testmock']
        del sys.modules['test.test_unittest']
        del sys.modules['unittest']

        # now make sure we can patch based on a dotted path:
        @patch('test.test_unittest.testmock.support.X')
        def test(mock):
            print(mock)
        test()

if 1:
    # The part that fails in test_loadTestsFromName__module_not_loaded
    module_name = 'test.test_unittest.dummy'
    sys.modules.pop(module_name, None)
    tu = __import__(module_name).test_unittest
    tu.dummy
```

So essentially, I believe `test_dotted_but_module_not_loaded` needs to do a better job cleaning up after itself.

**Comment by sweeneyde** [comment]
@ezio-melotti or @gpshead or @cjw296, any suggestions on how to make `test_dotted_but_module_not_loaded` play more nicely? I don't know all that much about unittest.mock.

**Comment by vstinner** [comment]
> So essentially, I believe test_dotted_but_module_not_loaded needs to do a better job cleaning up after itself.

Maybe save/restore sys.modules?

**Comment by sweeneyde** [comment]
I believe this is fixed now.

**Comment by vstinner** [comment]
Oh nice, thanks for the fix!
