### ISSUE TITLE
Explicitly documenting `logging.Logger.exception("msg", exc_info=exc)`

### ISSUE THREAD

**Issue by jamesbraza** [python/cpython#96620]
# Documentation

When working with `logging.Logger.exception`, I have often wanted to pass a custom message.  Previously, I was doing this over two adjacent calls:

```python
log: logging.Logger
log.error("Custom message.")
log.exception(exc)
```

From reading the library's source code, I realized it's possible to handle this in one call:

```python
log: logging.Logger
log.exception("Custom message.", exc_info=exc)
```

The keyword argument `exc_info` is explained within [`logging.debug`](https://docs.python.org/3/library/logging.html#logging.debug).  However, this still feels like a relatively hidden feature with respect to `logging.exception` users, as they have to in-depth read another section of the docs.

I think it could be worthwhile to mention the existence of `exc_info` for custom messages in the [`logging.exception`](https://docs.python.org/3/library/logging.html#logging.exception) section of the docs.  Something like the following:

> To include a custom message in addition to Exception info, pass the custom message via the positional argument `msg` and pass the Exception info via the keyword argument `exc_info`, as interpreted for [`debug`](https://docs.python.org/3/library/logging.html#logging.debug).

---

Thoughts: I see this docs request being rejected as it's just documenting one permutation of a use case that's already documented in some capacity.  However, I see this "one-off" addition being relevant because I think it's a common pattern for `logging.exception` callers.

**Comment by vsajip** [comment]
The [documentation](https://docs.python.org/3/library/logging.html#logging.Logger.exception) says:
```
exception(msg, *args, **kwargs)

    Logs a message with level `ERROR` on this logger. 
    The arguments are interpreted as for `debug()`.
    Exception info is added to the logging message.
    This method should only be called from an exception handler.
```
Which clearly shows *msg* as the first positional argument. Perhaps you didn't read, or didn't fully understand, the above snippet? You don't need to pass `exc_Info` here as it is meant to be called from an exception handler, so the exception info is available there.
