### ISSUE TITLE
_dnsname_match() causes wrong missmatch for hostnames with multiple '.'

### ISSUE THREAD

**Issue by diegojbravo** [python/cpython#96637]
Hi, this is my first time reporting an issue sorry if there is any mistake.
I was developing some code that aims to connect to a hostname of the likes:

`<a>.<b>.<c>-<d>.com`

when I got the error: 

`Certificate did not match expected hostname`

I investigated a bit in the code since the dns in my certificate is:

`*.<c>-<d>.com`

and found out that it was trying to match `.<b>.<c>-<d>.com` with `.<c>-<d>.com`.
The issue I found is that partitioning the hostname with `hostname_leftmost, sep, hostname_remainder = hostname.partition('.')` yields in this case:

`hostname_leftmost = '<a>'
sep = '.'
hostname_remainder = '<b>.<c>-<d>.com'`

and then the remainder of dns (`.<c>-<d>.com`) is compared with the remainder of the hostname (`<b>.<c>-<d>.com`) and gives a missmatch. However it shouldn't be a missmatch since `<a>.<b>.<c>-<d>.com` matches the regular expression `*.<c>-<d>.com` .

I think the comparison should be made with some regex matcher and not as it is done now.

**Comment by diegojbravo** [comment]
I am sorry I came to the wrong repository.

**Comment by diegojbravo** [comment]
After further investigation and according to RFC 6125 rules in section 6.4.3 (https://www.rfc-editor.org/rfc/rfc6125.html#section-6.4.3) 

If the wildcard character is the only character of the left-most label in the presented identifier, the client SHOULD NOT compare against anything but the left-most label of the reference identifier (e.g., *.example.com would match foo.example.com but not bar.foo.example.com or example.com).

So my interpretation might be wrong.

I assume then this is expected behavior and I should ask my certificate provider for an updated certificate with `*.<b>.<c>-<d>.com` in the subjectAltName. Is this right?

**Comment by gpshead** [comment]
> So my interpretation might be wrong.
> 
> I assume then this is expected behavior and I should ask my certificate provider for an updated certificate with `*.<b>.<c>-<d>.com` in the subjectAltName. Is this right?

I believe that is correct.
