### ISSUE TITLE
Kindly Ship Requests as Builtin Module

### ISSUE THREAD

**Issue by Ayub-Khan** [python/cpython#96638]
# Feature or enhancement
Requests is one of the most used libraries of Python. I think it should be builtin.

**Comment by AlexWaygood** [comment]
Hi, thanks for the feature request!

This is quite a significant change you're requesting. In order for it to be accepted, it needs discussion at https://discuss.python.org/c/ideas/6, buy-in from the `requests` team, and a PEP to be written and accepted. I'm closing this for now, until those steps have been taken :)

**Comment by stevendaprano** [comment]
Please note that the **first** step absolutely must be to get agreement from the requests developers. If they are not interested in transferring ownership of the library over to the PSF, and fitting in with the Python's standard library's release schedule and policies, then there is no possibility of us just *taking* the library without their agreement.
