### ISSUE TITLE
Inconsistent `__module__` names in `_functools` objects

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96646]
Simplest demo:

```python
>>> import _functools
>>> _functools.__name__
'_functools'
>>> _functools.cmp_to_key.__module__
'_functools'
>>> _functools.partial.__module__
'functools'
```

I think that all objects in `_functools` must have `_functions` as `__module__`.
I think that this error comes from the fact that most objects are re-exported in `functools.py`

Considerations:
- Some objects in `functools` will change its `__module__` to `_functools`, but I don't think that this is a big problem for two reasons. First, no-one probably rely on it. Secondly, `functools` module already have such objects, like `cmp_to_key` or `reduce`. Example:

   ```python
   >>> import functools
   >>> functools.cmp_to_key.__module__
   '_functools'
   >>> functools.reduce.__module__
   '_functools'
   ```
- I cannot really think of a real-life use-case where this is going to explode. We might keep things as-is just to reduce the chore. I think I will leave this up to @rhettinger (as code owner) to decide. If this problem is worth fixing, I will send a PR :)

**Comment by rhettinger** [comment]
This seems find to me.  Perhaps check with @ncoghlan . He has better knowledge of the semantics of `__module__` and `__qualname__`.

**Comment by ncoghlan** [comment]
At an implementation level, the different module names come from the types being explicitly declared with a "functools.xyz" qualname, while the functions use the default C extension function export machinery and hence use the actual module name.

At least for functools.partial, this matters for pickle compatibility with versions that aren't using the C accelerated version (as per PEP 399), so we definitely don't want to change those prefixes.
