### ISSUE TITLE
BINARY_SUBSCR_GETITEM has duplicate CALL_STAT_INC(inlined_py_calls)

### ISSUE THREAD

**Issue by itamaro** [python/cpython#96653]
as titled and discussed in GH-92257

**Comment by itamaro** [comment]
permalink - https://github.com/python/cpython/blob/3eaf70d8369a7d78f3e21949e438c8ff8a30f433/Python/ceval.c#L1662-L1674

@Fidget-Spinner I'm happy to submit a PR - not sure which one should be removed (or whether it matters)

**Comment by Fidget-Spinner** [comment]
It doesn't really matter, but I'd prefer we keep the one nearer to the bottom.
