### ISSUE TITLE
typing._Tupletype.__getitem__ errors poorly on non tuple iterables

### ISSUE THREAD

**Issue by blakewintermute** [python/cpython#96685]
# Bug report

The implementation of typing._Tupletype.__getitem__ assumes passed value is either tuple or type. Other iterables of types are handled by placing them in the first element of a tuple, then generating an error that an Iterable of types is not a valid type. This error is not clear and leads to confusion.

# Your environment

- CPython versions tested on: 3.8.10
- Operating system and architecture: Windows x86_64

# Comments
I will make a pull request to fix this issue.

**Comment by sobolevn** [comment]
Can you please provide an example: what exactly do you do? What happens? What do you expect?
Why do you think that there's a problem?

Right now it is unclear what the issue is.
