### ISSUE TITLE
venv\Scripts\activate.bat fails silently on Python 3.11.0rc1 on Windows 11 Pro

### ISSUE THREAD

**Issue by davidthewatson** [python/cpython#96693]
# Bug report

I'm trying to create and activate a virtual environment on Windows 11 Pro with Python 3.11.0rc1. 

I issue the following command:

    py -m venv .venv

The command takes several seconds (seems slow relative to all other python's I've run on this hardware including WSL2/ubuntu/python 3.8.10).

Then, I try to activate the virtual environment with:

    .\.venv\bin\activate.bat

I expected this to activate the environment as designed but the script runs silently, produces no ouptut, and post script execution, the environment hasn't been modified at all as evidenced by the fact that the prompt has not changed and pip cannot be found:

    PS C:\Users\david\Github\cms\src> .\.venv\Scripts\activate.bat
    PS C:\Users\david\Github\cms\src> pip
    pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
    was included, verify that the path is correct and try again.
    At line:1 char:1
    + pip
    + ~~~
        + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException

    PS C:\Users\david\Github\cms\src> $env:PATH
    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\GitHub CLI\;C:\Program Files\Git\cmd;C:\Users\david\AppData\Local\Microsoft\WindowsApps

# Your environment

- CPython versions tested on:

    Python 3.11.0rc1

- Operating system and architecture:

    PS C:\Users\david\Github\cms\src> systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List

    
    OS Name             : Microsoft Windows 11 Pro
    OS Version          : 10.0.22000 N/A Build 22000
    OS Manufacturer     : Microsoft Corporation
    OS Configuration    : Standalone Workstation
    OS Build Type       : Multiprocessor Free
    System Boot Time    : 9/8/2022, 3:01:58 PM
    System Manufacturer : ASUSTeK COMPUTER INC.
    System Model        : ZenBook UX534FTC_UX534FT
    System Type         : x64-based PC
    System Directory    : C:\Windows\system32
    System Locale       : en-us;English (United States)
    Hotfix(s)           : 4 Hotfix(s) Installed.,[01]: KB5016594,[02]: KB5010690,[03]: KB5016691,[04]: KB5016706

**Comment by eryksun** [comment]
You ran the wrong activation script. Use `.venv\bin\activate`. This runs "Activate.ps1" in PowerShell and "activate.bat" in CMD.

> The command takes several seconds (seems slow relative to all other python's I've run on this hardware including WSL2/ubuntu/python 3.8.10).

Installing setuptools and pip in an environment takes more time in Windows, for whatever reason.
