### ISSUE TITLE
asyncio exception handler called with incorrect context

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#96704]
Reproducer:
```py
import asyncio
import contextvars

name = contextvars.ContextVar('name', default='foo')


def exc_handler(*args):
    assert name.get() == 'bar'


async def task():
    name.set('bar')
    1/0


async def main():
    loop = asyncio.get_running_loop()
    loop.set_exception_handler(exc_handler)
    asyncio.create_task(task())

asyncio.run(main())
```

On main:
```console
Unhandled error in exception handler
context: {'message': 'Task exception was never retrieved', 'exception': ZeroDivisionError('division by zero'), 'future': <Task finished name='Task-2' coro=<task() done, defined at /workspaces/cpython/main.py:11> exception=ZeroDivisionError('division by zero')>}
Traceback (most recent call last):
  File "/workspaces/cpython/Lib/asyncio/base_events.py", line 1797, in call_exception_handler
    self._exception_handler(self, context)
  File "/workspaces/cpython/main.py", line 8, in exc_handler
    assert name.get() == 'bar'
AssertionError
```

The exception handler is called with incorrect context hence the `AssertionError`. It should called with the same context as the task. 
My use case is retrieving the current request id from the context var if there are any unhandled error but because of this bug, I always get the default value.

**Comment by gvanrossum** [comment]
Maybe you can retrieve the task from the dict arg to the handler and use its ‘_context’ attribute? Or maybe we need to add a ‘get_context()’ method to Task? That’s a complex API change b/c custom task implementations though. Otherwise the implementation seems far from easy, given how many places call this?

**Comment by kumaraditya303** [comment]
I only care about correct context in the task finalizer so that exception handler is called with correct context. I don't want to rely on any private attribute and it can change.

**Comment by gvanrossum** [comment]
Your wish is my command. :-) (Sorry if you had a PR already, if you did we can compare notes, if you didn't you can review mine. :-)
