### ISSUE TITLE
Deprecate `PyTracebackObject` struct

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#96709]
See https://discuss.python.org/t/leaky-abstractions-and-cpython-performance/18392 for discussion.

---

The entire struct would be deprecated under this issue. For deprecating `PyTracebackObject` the following changes will be performed under this issue in `3.12`:

- [ ] Mark the entire struct with `Py_DEPRECATED(3.12)` 
- [ ] Add C  API function to access `tb_lineno` in C.
- [ ] Document the changes in What's New  with fallback code snippets for older versions.

Changes in 3.14:

- [ ] The struct would be removed from the public C headers and moved to the internal C API.
- [ ] The optimizations would be implemented.

**Comment by gvanrossum** [comment]
Hold your horses. I’m not convinced yet that we should do this.

**Comment by kumaraditya303** [comment]
@gvanrossum What alternative do we have? Or do you mean this should be done at all as if it is not worth it ?

**Comment by gvanrossum** [comment]
We can just choose to live with the status quo, can't we?

**Comment by kumaraditya303** [comment]
> We can just choose to live with the status quo, can't we?

That's what I asked, this has proven to be more controversial than I had hoped, the SC advised to deprecate this first hence I created this issue, I'll just close it now as it seems there isn't enough support for this now :(
