### ISSUE TITLE
sqlite3 docs: Connection methods and attribute order

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#96702]
Reading through the docs in their current form, I wonder if it was a mistake to put the connection attributes before the connection methods; for your everyday sqlite3 programming, I suspect you'll be using the connection methods way more often than you'll be using the connection attributes. I think we should consider putting the methods before the attributes.

_Originally posted by @erlend-aasland in https://github.com/python/cpython/issues/96090#issuecomment-1236417471_

**UPDATE**
Resolved with:

- gh-96703
- gh-96788
- gh-96789

**Comment by erlend-aasland** [comment]
cc. @CAM-Gerlach

**Comment by CAM-Gerlach** [comment]
Yeah, agreed—I was thinking the same when I was a PR to the Cursor class to match Connection, as I got second thoughts and didn't go through with it.

**Comment by erlend-aasland** [comment]
Resolved with:

- gh-96703
- gh-96788
- gh-96789
