### ISSUE TITLE
AttributeError: module {__name__!r} has no attribute {name!r}. Did you mean: 'StringIO'?: Python 3.11.0rc1 (main, Aug  8 2022, 11:30:54) [MSC v.1932 64 bit (AMD64)] on win32

### ISSUE THREAD

**Issue by gumerov-amir** [python/cpython#96700]
import io

stream = io.StringIo()

raises the next error: AttributeError: module {__name__!r} has no attribute {name!r}. Did you mean: 'StringIO'?

**Comment by JelleZijlstra** [comment]
That error message is correct; the class is in fact called `StringIO` and not `StringIo`. It's documented at https://docs.python.org/3.11/library/io.html#io.StringIO.

**Comment by gumerov-amir** [comment]
I meant error text

**Comment by gumerov-amir** [comment]
I meant error text

**Comment by JelleZijlstra** [comment]
Thanks, good catch! Submitted #96701 to fix it.

**Comment by JelleZijlstra** [comment]
This affects only 3.11; main and 3.10 don't have this code.

**Comment by AlexWaygood** [comment]
Fixed in #96701 🎉

**Comment by ASIMBASIR** [comment]
AttributeError("module {!r} has no attribute
