### ISSUE TITLE
appx test failure on windows: `test_denial_of_service_prevented_str_to_int`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96710]
Looks like this test is flaky.
Example: https://dev.azure.com/Python/cpython/_build/results?buildId=111460&view=logs&j=c8a71634-e5ec-54a0-3958-760f4148b765&t=599737bc-ad72-560d-1530-0f89b05729e4

```
======================================================================
FAIL: test_denial_of_service_prevented_str_to_int (test.test_int.IntStrDigitLimitsTests.test_denial_of_service_prevented_str_to_int)
Regression test: ensure we fail before performing O(N**2) work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\b\layout-appx-amd64\Lib\test\test_int.py", line 715, in test_denial_of_service_prevented_str_to_int
    self.assertLess(seconds_to_fail_extra_huge, seconds_to_convert/8)
AssertionError: 0.015625 not less than 0.013671875
```

Related https://github.com/python/cpython/issues/96684
CC @zooba

**Comment by zooba** [comment]
Probably just needs the expected value raised. I expect this test should take multiple seconds if it fails, so having a threshold of ~10ms seems very low.

@gpshead, do you agree?

**Comment by zooba** [comment]
Also, I doubt #96684 is at all related. This test has nothing to do with the WMI tests or that module.

**Comment by gpshead** [comment]
Yes I'll just raise the expected value to < 1/2 instead of < 1/8 and see if this ever comes up again.  it's a regression test, there was nothing _exact_ about the chosen values.  false test passes due to system load or CI timing hiccups are fine.
