### ISSUE TITLE
Dictionary-literal-definition missing `:` SyntaxError error message pointer, is not at the best position.

### ISSUE THREAD

**Issue by mahdihaghverdi** [python/cpython#96718]
# Enhancement
Consider this dictionary literal definition:
```python
my_dict = {"key1": "value1", "key2", "value2"}
```
We get the error mesage:
```
  File "...", line 1
    my_dict = {'Key1': "Value1", "Key2", 'Value'}
                                      ^
SyntaxError: ':' expected after dictionary key
```

The `^` points to ending double quote of `"Key2"`, BUT I think it would be better for `^` to point at the next character which is not the expected `:` Like:

```
  File "...", line 1
    my_dict = {'Key1': "Value1", "Key2", 'Value'}
                                       ^
SyntaxError: ':' expected after dictionary key
```
Or with:
```
my_dict = {'Key1': "Value1", 2; "Value"}
```

to show message:
```
  File "/home/mahdi/PycharmProjects/JsonicDB/experiments/expr.py", line 11
    my_dict = {'Key1': "Value1", 2; "Value"}
                                  ^
SyntaxError: ':' expected after dictionary key

```
# Pitch

The more clear error messages, the better user experience.

# Python Version Information
build: ('main', 'Jun 29 2022 12:14:53')
version: 3.10.4
compiler: GCC 11.2.0

**Comment by pablogsal** [comment]
Thanks for raising the issue!

I will close it but feel free to tell us if we missed anything. We may reopen if we find an easy way to do it in the future
