### ISSUE TITLE
shutil.copyfileobj line 195 OSError Invalid Argument

### ISSUE THREAD

**Issue by jschwar313** [python/cpython#96721]
I have a python process and I received this error under my old python version and now under 3.10.7.  It's weird because I can just restart the process with the same parameters and it works fine the second time, so I know it's not a coding error.  I'm using windows version 10.  Python is 64-bit.  Here's the stack trace:

Traceback (most recent call last):
  File "C:\Users\jschw\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "C:\Users\jschw\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "src\python\aws_copy_backups_main.py", line 394, in <module>
  File "src\python\aws_copy_backups_main.py", line 353, in main
  File "C:\Users\jschw\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
OSError: [Errno 22] Invalid argument

C:\Windows\system32>pip list
Package                   Version
------------------------- ---------
altgraph                  0.17.2
boto3                     1.24.68
botocore                  1.27.68
certifi                   2022.6.15
cffi                      1.15.1
charset-normalizer        2.1.1
cryptography              38.0.1
cx-Freeze                 6.11.1
cx-Logging                3.0
Cython                    0.29.32
future                    0.18.2
idna                      3.3
importlib-metadata        4.12.0
jmespath                  1.0.1
lief                      0.12.1
packaging                 21.3
pefile                    2022.5.30
pip                       22.2.2
psutil                    5.9.2
pycparser                 2.21
pyinstaller               5.3
pyinstaller-hooks-contrib 2022.10
pyOpenSSL                 22.0.0
pyparsing                 3.0.9
python-dateutil           2.8.2
pywin32-ctypes            0.2.0
requests                  2.28.1
s3transfer                0.6.0
setuptools                60.10.0
six                       1.16.0
urllib3                   1.26.12
wheel                     0.37.1
zipp                      3.8.1

C:\Windows\system32>python --version
Python 3.10.7

**Comment by jschwar313** [comment]
Line 353 in main is the copyfileobject line below:

    for entry in sorted_file_list:
        if file_number > files:
            break
        backup_filename = entry[0]
        logging_root.info('backup filename is ' + backup_filename)
        # Copy backup file to temp directory
        temporary_filename = temporary_directory + os.path.basename(backup_filename)
        if backup_directory != temporary_directory:
            source = open(backup_filename, 'rb')
            target = open(temporary_filename, 'wb')
            try:
                copyfileobj(source, target)
            finally:
                source.close()
                target.close()
                logging_root.info('file ' + backup_filename + ' is closed')

These lines are logged.  I have debug level logging turned on.

2022-09-08 13:28:33,538 - aws_copy_backups - [INFO] - backup filename is F:\\My Backups\\H Drive Backup\\\H_VOL-b010.spf
2022-09-08 15:36:30,677 - aws_copy_backups - [INFO] - file F:\\My Backups\\H Drive Backup\\\H_VOL-b010.spf is closed

I know it shouldn't have three \ before the file name, but it works other times with the same thing showing up.  Not sure what's going on.

**Comment by eryksun** [comment]
To help diagnose the problem, try using the following implementation of `copyfileobj()`. It includes the C runtime's `_doserrno` value in the raised exception.

```python
def copyfileobj(fsrc, fdst, length=0):
    if not length:
        length = shutil.COPY_BUFSIZE
    fsrc_read = fsrc.read
    fdst_write = fdst.write

    import ctypes
    __doserrno = ctypes.CDLL('ucrtbase').__doserrno
    __doserrno.restype = ctypes.POINTER(ctypes.c_ulong)
    _doserrno = __doserrno()     
    _doserrno[0] = 0

    while True:
        try:
            buf = fsrc_read(length)
            if not buf:
                break
            fdst_write(buf)
        except OSError as e:
            winerror = _doserrno[0]
            raise OSError(e.errno, e.strerror, e.filename, winerror) from None
```

> I know it shouldn't have three \ before the file name, but it works other times with the same thing showing up. Not sure what's going on.

Windows normally ignores repeated slashes in file paths, except not in a UNC prefix (e.g. "\\\\server\\share") and not in "\\\\?\\" extended paths.

**Comment by jschwar313** [comment]
Ok, thanks.  I'll try running it several times.  It might take a while to fail.  It doesn't fail every time.  Thanks again and for the quick response.

**Comment by eryksun** [comment]
I updated the function to also support debug builds of the interpreter that link with "ucrtbased.dll" instead of "ucrtbase.dll", in case you happen to be running "python_d.exe" or embedding "python310_d.dll".

**Comment by jschwar313** [comment]
Ok, thanks.  I've stopped the process, updated the code, and started it again.

**Comment by jschwar313** [comment]
I received this message when I ran the python program.  Is this what you expect?  The errorlevel I print out after the program runs.  The script ran for more than two hours and it copied all three files it was supposed to copy.  I'm not sure what is going on.  I think I can reproduce this now.

The filename, directory name, or volume label syntax is incorrect.
"errorlevel is " 123

**Comment by eryksun** [comment]
The original reported error is due to `fsrc_read(length)`, which failed with `errno` set to `EINVAL` (22). 

Reading from a file calls C `read()`, which calls WinAPI `ReadFile()`. If the latter fails, the C runtime maps the WinAPI error to a C `errno` code. For example, `ERROR_INVALID_PARAMETER` maps to `EINVAL` (22), and `ERROR_INVALID_HANDLE` maps to `EBADF` (9). However, except for common errors, most WinAPI errors are mapped to `EINVAL`. This is useless for diagnostics, unless an error is obviously due to an invalid parameter. Fortunately, the original WinAPI error code is sill available in the C `_doserrno` value. The modified version of `copyfileobj()` captures this value.

>The filename, directory name, or volume label syntax is incorrect.
"errorlevel is " 123

WinAPI `ReadFile()` should never fail with `ERROR_INVALID_NAME` (123).

**Comment by jschwar313** [comment]
ok.  Thanks.  I had a remove step after the copy, so I didn't have to delete them manually.  I took that code out.  The copy must have worked that time.  I'll keep trying to reproduce it.  I tried once with a cx_freeze version and it worked just fine.  Sometimes it does that.  I'm trying it now with running the python code, not a cx_freeze executable.

**Comment by jschwar313** [comment]
Well, I've run my process a couple of dozen or more times various ways trying to reproduce this issue and I think I'll stop.  I will continue to run my normal process twice a week with your modified code in it, so if it happens that way, I'll update this issue with the results.  Sorry, but it's just taking too much of my time.

**Comment by eryksun** [comment]
I wish I could help more. I've marked this issue as pending. If it gets closed by the time you see the error again, just create a new issue that references this one.

**Comment by jschwar313** [comment]
I ran it again and I received a different error.  Should I open a different issue for this?  I'm running this as an admin.

Line 350 is this line:

        temporary_filename = temporary_directory + os.path.basename(backup_filename)

--------------------------------------------------------------------------------------------------------------

2022-09-15 00:00:05,525 - aws_copy_backups - [INFO] - backup filename is F:\\My Backups\\H Drive Backup\\\H_VOL-b012.spf.tmp
Traceback (most recent call last):
  File "C:\Users\jschw\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "C:\Users\jschw\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "src\python\aws_copy_backups_main.py", line 394, in <module>
  File "src\python\aws_copy_backups_main.py", line 350, in main
PermissionError: [Errno 13] Permission denied: 'F:\\\\My Backups\\\\H Drive Backup\\\\\\H_VOL-b012.spf.tmp'

**Comment by jschwar313** [comment]
Could these be Windows issues and not python issues?

**Comment by iritkatriel** [comment]
As @eryksun said, please reopen this or create a new issue if you see the problem again.

**Comment by jschwar313** [comment]
I have a question.  If I have a virtual environment, would I have to modify the shutil.copyfileobj function somewhere in that environment or would modifying it only in my python location be ok?  I can't find shutil.py anywhere in my virtual environment directory.  I just want to be sure I'm using this code, since it's not part of the normal python distribution.  Thanks.

**Comment by eryksun** [comment]
@jschwar313, "shutil.py" is located in "<installation directory>\\Lib". Copy it to the directory of the script that you're running, and modify the copy.
