### ISSUE TITLE
Signature.bind doesn't raise`TypeError` when it got multiple values for `POSITIONAL_ONLY` arguments.

### ISSUE THREAD

**Issue by komoto48g** [python/cpython#96743]
# Bug report

Signature.bind doesn't raise`TypeError`, though it got multiple values for `POSITIONAL_ONLY` arguments.
```python
>>> import inspect
>>> def f(x, /, y, z=3, *args, key=None, value:int=0, **kwargs):
...     pass
... 
>>> inspect.signature(f).bind(0, 1, x=2)
<BoundArguments (x=0, y=1, kwargs={'x': 2})>
```
Expected outcome: TypeError

# Your environment

- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows 10

This issue has been mentioned on Discuss Python:
https://discuss.python.org/t/check-if-function-is-callable-with-given-args-and-kwargs/18820/5

**Comment by sobolevn** [comment]
Why do you expect this to fail?
It works the same way as regular function calls.
Since `x /` is positional only, `x=` is considered a kwarg:

```python
>>> def f(x, /, **kwargs):
...    print(x, kwargs)
... 
>>> f(0, x=1)
0 {'x': 1}
```

Does not really look like a bug to me.

**Comment by komoto48g** [comment]
Oh, I didn't know that positional-only and keywords can be duplicated... 
I thought this was a bug because `inspect.getcallargs` fails.
```python
>>> def f(x, /, **kwargs):
...    print(x, kwargs)
...    
>>> inspect.getcallargs(f,0,x=0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python310\lib\inspect.py", line 1527, in getcallargs
    raise TypeError("%s() got multiple values for argument %r" %
TypeError: f() got multiple values for argument 'x'
```
Thank you for your time. I will close this soon.
