### ISSUE TITLE
Subtypes of extension type appear to inherit Py_TPFLAGS_DISALLOW_INSTANTIATION flag

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#96746]
When `Py_TPFLAGS_BASETYPE` and `Py_TPFLAGS_DISALLOW_INSTANTIATION` flags are set on extension type `tp_flags` field, attempt to create type subclass instance fails:
```python
>>> import _foo
>>> class Bar(_foo.Foo): pass
... 
>>> Bar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot create 'Bar' instances
```

According to documentation, it shouldn't happen:
https://docs.python.org/3/c-api/typeobj.html#Py_TPFLAGS_DISALLOW_INSTANTIATION

Extension code example:
[_foo.c.txt](https://github.com/python/cpython/files/9541527/_foo.c.txt)

Tested on 3.10.3 and 3.12.0a0.

* PR: gh-99002

* PR: gh-99212

* PR: gh-99213

**Comment by vstinner** [comment]
cc @erlend-aasland @encukou

**Comment by erlend-aasland** [comment]
Changing this behaviour _might_ break existing code. Perhaps it would be better to update the docs to match the actual behaviour. Alternatively, we could issue a warning for this in 3.12 and change the behaviour in 3.14.

I'm not sure what's the most correct (or less painful) solution.

**Comment by chgnrdv** [comment]
@erlend-aasland Can we update the docs for 3.10/3.11/3.12 to match behaviour, but for 3.12 mention that inheritance is deprecated and will be removed in 3.14, and make 3.12 issue a deprecation warning on attempt to instantiate subclass of non-instantiable?

**Comment by encukou** [comment]
IMO the Python example above *should* fail. But the flag isn't responsible directly: this fails because the flag prevented inheriting `tp_new`, and so there is no C-level constructor to call. There's no way Python code can safely work around that.

If a subclass provides a `tp_new` (from C), then it should be possible to instantiate it – the subclass knows how to create its instances in that case. (I haven't checked if there's a bug there as well, though.)

**Comment by erlend-aasland** [comment]
> IMO the Python example above _should_ fail. But the flag isn't responsible directly: this fails because the flag prevented inheriting `tp_new`, and so there is no C-level constructor to call. There's no way Python code can safely work around that.

Ok, so we should probably just leave the current behaviour as it is, if I am reading you right. In any case, the docs should be updated to reflect the implementation.

**Comment by chgnrdv** [comment]
I agree that there is misconception on my part, and subclass don't actually inherit said flag but have its `tp_new` set to value of the same field of its base class, which is `NULL` if base class is not instantiable.

My opinion is that if flag is not inheritable, it shouldn't affect ability of subclasses to be instantiable. The current situation is that ability to instantiate class depends on presence of flag in base class.

Also I think that non-instantiable base classes with instantiable subclasses can be useful in some situations, e. g. as abstract classes defined in extensions.

Now I see that probably there is no bug here, but there still can be a little feature :)

**Comment by erlend-aasland** [comment]
> Now I see that probably there is no bug here, but there still may be a little feature :)

If you think such a feature is worth it, raise a discussion first on Discourse. If you gain support for you idea, create a new `type-enhancement` issue for you idea here on the tracker.

Suggesting closing this.

**Comment by encukou** [comment]
@chgnrdv, does https://github.com/python/cpython/pull/99002/files look helpful?

**Comment by encukou** [comment]
The docs were updated. Thanks again for bringing this up!
