### ISSUE TITLE
Numpy deprecation warning in test_buffer.py

### ISSUE THREAD

**Issue by pitrou** [python/cpython#96742]
# Bug report

When running `test_buffer.py` on the main branch with Numpy installed, the following warnings are displayed:
```
0:00:00 load avg: 0.29 Run tests sequentially
0:00:00 load avg: 0.29 [1/1] test_buffer
/home/antoine/cpython/default/Lib/test/test_buffer.py:2298: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  self.assertEqual(b, na.tostring(order='C'))
/home/antoine/cpython/default/Lib/test/test_buffer.py:2321: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  self.assertEqual(b, na.tostring(order='F'))
/home/antoine/cpython/default/Lib/test/test_buffer.py:2345: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  self.assertEqual(b, na.tostring(order='A'))

== Tests result: SUCCESS ==

```

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

Numpy version 1.23.3, installed from source on a debug build of the CPython main branch.

**Comment by pitrou** [comment]
cc @corona10

**Comment by corona10** [comment]
Oops, I pushed the change to https://github.com/python/cpython/pull/96738/commits/e8c1fed38ff93546d554c43a49e82bbd6fa910f4 already.
If you want to handle it separately please let me know.
