### ISSUE TITLE
urllib: Use `_` for unused variables when parsing a tuple

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#96758]
# Feature or enhancement

`hostinfo` variable is not accessed in `_userinfo` method. To indicate it, single underscore `_` should be used instead.

https://github.com/python/cpython/blob/53a54b781d1f05f2d0b40ce88b3da92d5d23e9d2/Lib/urllib/parse.py#L184-L194

# Pitch

For better readability, single underscores are used for unused variables when parsing a tuple as follows. Like this, `_` should be used in `_userinfo` method too.

https://github.com/python/cpython/blob/53a54b781d1f05f2d0b40ce88b3da92d5d23e9d2/Lib/urllib/parse.py#L196-L208

**Comment by AlexWaygood** [comment]
As per my comments on the linked PR:

> Thanks for your interest in improving CPython!
> 
> Unfortunately, cosmetic changes are usually not accepted for the CPython repo. We have a large number of open bug reports, and prefer to spend our time fixing those.
