### ISSUE TITLE
Dead code in `CALL_FUNCTION_EX` opcode handler

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96751]
I am talking about these lines:
https://github.com/python/cpython/blob/a36235d5c7863a85fa323b2048d3d254116a958e/Python/ceval.c#L4722-L4734

They are not ever called, because after https://github.com/python/cpython/pull/18141 all `**` dict unpacking is handled in `DICT_MERGE` opcode.

This was found while working on https://github.com/python/cpython/issues/94808 but I think that it deserves a separate issue.

PR is on its way.

**Comment by mdboom** [comment]
Thanks for taking such an interest in coverage.  This is very welcome (but I'll leave it to @markshannon to review the specific change in #96752).
