### ISSUE TITLE
Signal handlers don't skip incomplete frames

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#96754]
Currently signal handlers don't skip incomplete frames and this leads to crash when creating frame object. Incomplete frames should be skipped in `_PyErr_CheckSignalsTstate`.

**Comment by mdboom** [comment]
To make sure we aren't playing "whac-a-mole", is there a way to find all of these cases and/or improve the internal API?

**Comment by kumaraditya303** [comment]
It depends upon if the function calls back into python with a frame reference. I don't think these can be found all at once, it requires following the entire call chain and if the callback can be overridden.

**Comment by mdboom** [comment]
Ok, thanks for the clarification, @kumaraditya303.

**Comment by pablogsal** [comment]
3.11.1 unless you think it absolutely needs to go on 3.11.0
