### ISSUE TITLE
typing tests: Not all subclass cases are covered

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96769]
There are a lot of test cases in `test_typing.py` where we test that different typing things cannot be used as base classes. However, there are multiple missing cases. Examples:
- `Final` / `Final[int]` is not tested to be invalid base class: https://github.com/python/cpython/blob/53a54b781d1f05f2d0b40ce88b3da92d5d23e9d2/Lib/test/test_typing.py#L3748-L3756
- `Ts` is tested, but `*Ts` is not: https://github.com/python/cpython/blob/53a54b781d1f05f2d0b40ce88b3da92d5d23e9d2/Lib/test/test_typing.py#L1039
- Different special forms only tested with / or without `[]`
- And other issues

I think this should be all covered. I went through all subtyping tests and added more cases.
I will send a PR :)

**Comment by sobolevn** [comment]
And I found https://github.com/python/cpython/issues/96771 due to the fact that `class C(Annotated[int, ...]): ...` was not covered.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/96772
