### ISSUE TITLE
Rewrite `asyncio.wait_for` using `asyncio.timeout`

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#96764]
Over the years a lot of issues have accumulated for `asyncio.wait_for` and the code has become complicated. The `asyncio.timeout` can be used to simplify this a lot and will also fix bugs which are already fixed or don't exist in `asyncio.timeout`. This rewrite won't be backported. `asyncio.wait_for` should be nothing more than a wrapper around `asyncio.timeout`.

`asyncio.wait_for`  issues: https://github.com/python/cpython/issues?q=is%3Aissue+is%3Aopen+wait_for+label%3Aexpert-asyncio

### Linked PRs
* gh-98518

**Comment by gvanrossum** [comment]
Note that whatever we do should preserve all the existing behavior in `wait_for()`. Breaking existing code using it would be worse than keeping a bunch of issues that people can avoid by switching to using `timeout()` directly.

**Comment by kumaraditya303** [comment]
@graingert IIRC you had a branch for this, interested in this?

**Comment by graingert** [comment]
Yeah I'm interested, but one thing to note is that wait_for has changed dramatically between versions so matching the behavior is hard

**Comment by kumaraditya303** [comment]
> Yeah I'm interested, but one thing to note is that wait_for has changed dramatically between versions so matching the behavior is hard

It can be evaluated by checking how many tests it breaks by just changing it to use `asyncio.timeout` and take it from there.

**Comment by graingert** [comment]
https://github.com/python/cpython/pull/31847#discussion_r925531271 here's the work so far

**Comment by eIGato** [comment]
When can we expect it to be released?
And under what patch number?

**Comment by gvanrossum** [comment]
3.12

**Comment by cretz** [comment]
Just want to note on this issue that this change is an unfortunate compatibility break in our Temporal deterministic event loop implementation. We can deterministically implement `call_later` because it's relative time, but now `wait_for` uses fixed time of `call_at` which our time-travelling event loop can't support. I am looking into options...
