### ISSUE TITLE
pow() is slow

### ISSUE THREAD

**Issue by isaacl** [python/cpython#96768]
Based on timeit, `pow()` is much slower than `**`.  This could be a performance trap as the two are supposed to be [equivalent](https://docs.python.org/3/library/functions.html#pow).

```
>>> timeit.timeit("3**3")
0.009507275011856109
>>> timeit.timeit("pow(3, 3)")
0.2119580740109086
```

`**` might be avoided for cosmetic reasons –  feels wrong to have significant performance differences.

**Comment by stevendaprano** [comment]
More likely that's a difference between constant folding and actually performing the exponentiation at runtime.

```
>>> import dis
>>> dis.dis('3**3')
  1           0 LOAD_CONST               0 (27)
              2 RETURN_VALUE
```

I think you are measuring the difference between evaluating a constant 27 versus calling a function `pow(3, 3)`, but I could be wrong.

**Comment by stevendaprano** [comment]
On my computer, there is a small difference between the two, which is probably due to the overhead of calling a function:

```
[steve ~]$ python3.10 -m timeit "3**3"  # Constant folding.
50000000 loops, best of 5: 7.83 nsec per loop
[steve ~]$ python3.10 -m timeit -s "a=3" "a**3"
1000000 loops, best of 5: 241 nsec per loop
[steve ~]$ python3.10 -m timeit "pow(3, 3)"
1000000 loops, best of 5: 262 nsec per loop
```

**Comment by eryksun** [comment]
The compiler can't assume that `pow` is the builtin `pow()` function, but it can and does fold the constant expression `3**3` as the constant 27.

**Comment by isaacl** [comment]
thanks everyone.

**Comment by isaacl** [comment]
Follow up: why is math.pow faster than pow() then?
```
python3.10 -m timeit -s "a=3; import math" "math.pow(a, 3)"
2000000 loops, best of 5: 102 nsec per loop
python3.10 -m timeit -s "a=3" "pow(a, 3)"
1000000 loops, best of 5: 251 nsec per loop
python3.10 -m timeit -s "a=3; from __main__ import __builtins__" "__builtins__.pow(a, 3)"
1000000 loops, best of 5: 251 nsec per loop
```

**Comment by eryksun** [comment]
`math.pow()` calls C `pow()` and thus operates on C `double` values. A C `double` is typically a 64-bit IEEE 754 float. This has 53 bits of precision, which is 15 decimal digits (rounded down from `log10(2**53)`). Maybe that's enough precision for one's needs, and maybe it's not. For example:

```pycon
>>> pow(123456789, 3)
1881676371789154860897069
>>> math.pow(123456789, 3)
1.8816763717891548e+24
>>> print(f'{math.pow(123456789, 3):.0f}')
1881676371789154785165312
```
