### ISSUE TITLE
Order of configparser.ConfigParser.read() arguments

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [python/cpython#96765]
# Bug report

When multiple INI configuration files with identical section(s)  and key(s) are fed to [`configparser.ConfigParser.read`](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read), the result is undefined / not documented. Actually the last file containing a given section/key takes precedence over previous files, as I would have expected from a straightforward implementation. However:
* This behaviour should be documented.
* ~~Perhaps this behaviour should be changed, and the first file take precedence over subsequent files. In practice that would break compatibility, but since the result is currently undocumented, that may be OK.~~

## Example

Here are two INI files:

**`1.ini`**
```ini
[section]
a = 1
b = "11"
```
**`2.ini`**
```ini
[section]
a = 2
b = "22"
```

And here is the order of the filenames changes the result:
```python
>>> import sys
>>> import configparser
>>> config = configparser.ConfigParser()
>>> 
>>> config.read(["1.ini", "2.ini"])
['1.ini', '2.ini']
>>> config.write(sys.stdout)
[section]
a = 2
b = "22"

>>> 
>>> config.read(["2.ini", "1.ini"])
['2.ini', '1.ini']
>>> config.write(sys.stdout)
[section]
a = 1
b = "11"

>>> 
```
# Your environment

- CPython versions tested on: 3.6.9
- Operating system and architecture: Ubuntu 18.04

### Linked PRs
* gh-107683
* gh-121664
* gh-121687
* gh-121688

**Comment by sappelhoff** [comment]
I believe this is documented here: https://docs.python.org/3/library/configparser.html

> It is possible to read several configurations into a single [ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser), where the most recently added configuration has the highest priority. Any conflicting keys are taken from the more recent configuration while the previously existing keys are retained.

**Comment by DimitriPapadopoulos** [comment]
Indeed. Sorry about that.

Still, I still think piece of information needs to be moved or copied from [Quick Start](https://docs.python.org/3/library/configparser.html#quick-start) to the [configparser.ConfigParser.read](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read) documentation.
