### ISSUE TITLE
typing tests: `get_args()` is missing a lot of possible types of arguments

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#96784]
Right now `get_args()` has a lot of test arguments: https://github.com/python/cpython/blob/1756ffd66a38755cd45de51316d66266ae30e132/Lib/test/test_typing.py#L4938-L4975

But, it still misses a lot more:
- `collections.abc.Callable` with `ParamSpec` (it is special cased in `get_args`)
- Different type variables and `P.args` / `P.kwargs`
- Raw `Concatenate` type
- `Unpack`
- `Any`
- `Optional`
- `TypeAlias`
- `TypeGuard`
- `LiteralString`
- `Self`
- `Protocol` subtypes
- Generic `TypedDict` / `NamedTuple`

I am already working on a PR for this. Will send it later today.

**Comment by sobolevn** [comment]
Notice that there are also `.__args__` tests for different types. They are highly related (and do the same thing for some of them), but it is a different API.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/96791
