### ISSUE TITLE
Unify pprint and reprlib

### ISSUE THREAD

**Issue by ivanovmg** [python/cpython#96805]
It seems reasonable to unify ``pprint`` and ``reprlib`` functionality.

Both modules serve formatting of the output, hence their functionality can probably be unified.

_Originally posted by @gvanrossum in https://github.com/python/cpython/issues/92734#issuecomment-1241388362_

**Comment by gvanrossum** [comment]
It's too early to have an issue open about this. Please discuss on Discourse until you have a design ready.
