### ISSUE TITLE
TypeError when closing BufferedRandom with custom stream

### ISSUE THREAD

**Issue by omots** [python/cpython#96817]
# Bug report

Wrapping a custom `io.RawIOBase` implementation with a `BufferedRandom` raises `TypeError: 'NoneType' object cannot be interpreted as an integer` when it is closed.

[Here is a gist](https://gist.github.com/omots/997d71c6501609c642c31eaa623d8373) of a full self-contained example. Briefly, this is what it looks like in the REPL:

```python
Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> import repro
>>> s = repro.MyStream()
>>> f = io.BufferedRandom(s)
>>> f.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object cannot be interpreted as an integer
```

# Your environment

- CPython versions tested on: 3.10.4 and 3.10.6
- Operating system and architecture: Linux amd64

**Comment by vadmium** [comment]
Your _seek_ method isn't returning the new offset
