### ISSUE TITLE
Subquadratic algorithms for base conversion

### ISSUE THREAD

**Issue by oscarbenjamin** [python/cpython#96812]
Problems have been reported with CPython's algorithms for converting int to str and vice versa:
https://github.com/python/cpython/issues/95778
https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889

Better algorithms can be used e.g.:
https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889/14?u=oscarbenjamin

This issue is to track the implementation of subquadratic complexity algorithms for base conversion in CPython.

**Comment by gpshead** [comment]
I think https://github.com/python/cpython/issues/90716 already tracks the same thing. Lets use that one.
