### ISSUE TITLE
Multiprocessing resource tracker incorrectly checks pipe write length

### ISSUE THREAD

**Issue by grgsrs** [python/cpython#96819]
https://github.com/python/cpython/blob/4781535a5796838fc4ce88e6e669e8907e426685/Lib/multiprocessing/resource_tracker.py#L164

I think this line should be:

```python
if len(msg) > 512:
```

**Comment by saito828koki** [comment]
@grgsrs 
Thanks for your report!

Your suggestion seems to be correct. To guarantee that a write operation is atomic, the length of `msg` has to be less than or equal to `PIPE_BUF`(the kernel pipe buffer size). 
According to [this page](https://man7.org/linux/man-pages/man7/pipe.7.html), the minimum acceptable value of `PIPE_BUF` is set to 512 bytes in POSIX system , so checking if `len(msg)` is not greater than 512 is enough. 

I will create a PR for this issue.

**Comment by grgsrs** [comment]
Thanks for responding so quickly and glad to help (if only in a very small
way).
