### ISSUE TITLE
sqlite3 docs: clarify transaction control for SELECT

### ISSUE THREAD

**Issue by KennyChenBasis** [python/cpython#96810]
# Documentation

In https://docs.python.org/3/library/sqlite3.html#transaction-control, it says that transactions are implicitly opened before `INSERT`, `UPDATE`, `DELETE`, or `REPLACE` statements, but it leaves open what happens for `SELECT` statements. Especially in the light of https://github.com/python/cpython/issues/54133, it should be more clear that `SELECT` statements don't start a transaction, either by saying "only" `INSERT`, etc. statements implicitly open transactions, or adding another sentence.

CC: @erlend-aasland @CAM-Gerlach

**Comment by CAM-Gerlach** [comment]
At least in my (beginner-level) reading of the docs, it seems implicit to me that a transaction is opened before these, and only these statements, i.e. in formal logic "If and only if a statement is a `INSERT`, `UPDATE`, `DELETE` or `REPLACE` statement, an SQL transaction is implicitly opened before that statement." But if there is concern that users might be uncertain if one is opened before `SELECT`, or we want to call attention to that fact (being the other member of the CRUD quartet), the the wording could be revised to add a parenthetical calling this out:

> and [executemany()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executemany) executes `INSERT`, `UPDATE`, `DELETE`, or `REPLACE` (but not `SELECT`) statements.

@erlend-aasland ?

**Comment by erlend-aasland** [comment]
Sure, I see no reason not to be explicit. It'll also help reduce the number of issues like this.

**Comment by erlend-aasland** [comment]
Resolved with:

- gh-96832
- gh-96854
- gh-96855
