### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Pekka-Kalevi** [python/cpython#96820]
# Documentation

(What’s New In Python 3.11

Deprecated

Quote 'The lib2to3 package and 2to3 tool are now deprecated and may not be able to parse Python 3.10 or newer. See the PEP 617 (New PEG parser for CPython). (Contributed by Victor Stinner in bpo-40360.)'

It should clarify that on Python 3.10 on Ubuntu have in  /usr/bin/2to3-3.10 conversion tool.

**Comment by hauntsaninja** [comment]
`2to3-3.10` still uses lib2to3 and so may not be able to parse 3.10.
