### ISSUE TITLE
deadcode elimination is not consistent under cpython 3.11.0rc2

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#96833]
strings/code objects which start with `dead_` in this example should never be part of the function constants.
`test1` produces no problems, but the behaviour changes if you add `c=5` at the end of the function.

script:
```python
def test1():
    a = "var"

    if False:
        b = "dead_var"

        def dead_foo():
            print("hi")


print("in test1:")
print(*test1.__code__.co_consts, sep="\n")
print()


def test2():
    a = "var"

    if False:
        b = "dead_var"

        def dead_foo():
            print("hi")

    c = 5


print("in test2:")
print(*test2.__code__.co_consts, sep="\n")
```

output (Python 3.11.0rc2+):
```python
in test1:
None
var

in test2:
None
var
False
dead_var
<code object dead_foo at 0x7fab9a67c730, file "/home/frank/projects/executing/example.py", line 22>
5
```

`dead_foo` and `dead_var` are part of the constants of test2, but I see no reason why they should.
Can only the last constants be eliminated?

3.10 did not performed any deadcode elimination at all.

output (Python 3.10.0):
```python
in test1:
None
var
False
dead_var
<code object dead_foo at 0x7f6e0651d370, file "/home/frank/projects/executing/example.py", line 7>
test1.<locals>.dead_foo

in test2:
None
var
False
dead_var
<code object dead_foo at 0x7f6e0651d580, file "/home/frank/projects/executing/example.py", line 22>
test2.<locals>.dead_foo
5
```

**Comment by iritkatriel** [comment]
Your output is not showing that dead code did not get eliminated, it only shows what const trimming did.

Currently the unused suffix of the consts list is removed. Removing consts from the middle of the list requires another pass over the code to fix consts references. This could be implemented, maybe one day it will be.

To see whether dead code was removed or not you need to look at the code. Use the dis module.

**Comment by 15r10nk** [comment]
Thank you for your answer.
It is no problem for me now because I have a workaround. The question is also if saving some bytes is wroth the additional runtime to check it for every function, because deadcode is not so common.
