### ISSUE TITLE
collections.Counter's arithmatic operators cause subclassing issues

### ISSUE THREAD

**Issue by GiovanH** [python/cpython#96839]
# Bug report

Because the `Counter` class uses its own name in the arithmetic operations, running arithmetic on instances of a `Counter` subclass will unexpectedly produce `Counter` objects, instead of the subclass. 

An example:

```python
import collections

class ConciseCounter(collections.Counter):
    def __repr__(self):
        return '<' + ', '.join(f"{f'{c}x '}{k}" for k, c in self.items()) + '>'


c1 = ConciseCounter([1, 2, 2, 3])
c2 = ConciseCounter([1, 3])

print(c1, type(c1))
print(c2, type(c2))
print(c1 - c2, type(c1-c2))

# Expected: 
# <1x 1, 2x 2, 1x 3> <class '__main__.ConciseCounter'>
# <1x 1, 1x 3> <class '__main__.ConciseCounter'>
# <2x 2> <class '__main__.ConciseCounter'>
# 
# Actual:
# <1x 1, 2x 2, 1x 3> <class '__main__.ConciseCounter'>
# <1x 1, 1x 3> <class '__main__.ConciseCounter'>
# Counter({2: 2}) <class 'collections.Counter'>
```

# Cause

Using `__add__` as an example:

https://github.com/python/cpython/blob/7528e2c06c8baf809b56f406bcc50e8436c9647c/Lib/collections/__init__.py#L794-L811

Because the name `Counter` is used explicitly, this function always returns instances of `collection.Counter`, even from instances of classes inheriting the method from `Counter`.
The instance of `Counter` in `isInstance` should not be changed, only the instantiation of new instances.

Note how `copy` in the same class uses `self.__class__` to avoid this problem:

https://github.com/python/cpython/blob/7528e2c06c8baf809b56f406bcc50e8436c9647c/Lib/collections/__init__.py#L701-L703

**Comment by gvanrossum** [comment]
@rhettinger What do you think of this? It may actually break code that currently relies on this behavior. Is subclassing `Counter` a reasonable thing to do?

OP: you can of course work around this by redefining `__add__`, `__sub__` etc. in your subclass.

**Comment by GiovanH** [comment]
> Is subclassing `Counter` a reasonable thing to do?
I know for my use case I needed a version of counter in which subtracting a counter with elements not in the original counter raised an error instead of being silently ignored, which would have been trivial to do with normal subclassing but ended up causing the above problem.

**Comment by pochmann** [comment]
Isn't that normal/expected? Other types do the same:
```
class L(list): pass
class S(str): pass
class I(int): pass

for x in L(), S(), I():
    print(type(x), type(x + x))
```
Output:
```
<class '__main__.L'> <class 'list'>
<class '__main__.S'> <class 'str'>
<class '__main__.I'> <class 'int'>
```

**Comment by GiovanH** [comment]
Hm. I do see some cases where classes act like that, but sometimes they don't. My immediate question then is "Is there a defined expectation for this?"

I would though point again to `copy()` behaving as I expected. Is `copy()` expected to be safe to inherit, while operators are not? Or is this a per-class thing?

**Comment by rhettinger** [comment]
This isn't a bug. It was a conscious design choice to follow the norm for other classes like set, dict, list, int, str, etc.

For the most part this worked out well.  Counter has been around for 12 years without a complaint until now. Also, we can't change the default behavior without breaking existing code.

What we could do is add a factory function class variable that can be overridden by a subclasser if they want to change the default.

```
class Counter:

    factory = None                           # <-- New code

    def __missing__(self, key):
        return 0
    
    def __add__(self, other):
        if not isinstance(other, Counter):
            return NotImplemented
        result = Counter()                 
        for elem, count in self.items():
            newcount = count + other[elem]
            if newcount > 0:
                result[elem] = newcount
        for elem, count in other.items():
            if elem not in self and count > 0:
                result[elem] = count
        return self.factory(result)          # <-- Changed code

Counter.factory = Counter                    # <-- New code  
``` 

 > My immediate question then is "Is there a defined expectation for this?"

No.  There are just language norms like capitalizing class names, using `self` to refer to the current instance, and having mutating methods return `None`.  All of these "rules" have exceptions that were made when a strong need arose.

Regarding the return type of arithmetic operators in a subclass, the norm has advantages and disadvantages. If you're interested, I discussed this in [The Art of Subclassing](https://www.youtube.com/watch?v=miGolgp9xq8).

On the plus side, we get predictable behavior that is easy to reason about and doesn't have to make assumptions about subclass semantics.  On the minus side, it is a minor PITA for subclassers to override every arithmetic operator if they want those operators to return an instance of the subclass.  Essentially, a subclasser would need to wrap every operator method with a cast to the desired type:

```
class Sub(Counter):
    def __add__(self, other):
        return Sub(super().__add__(other))
```

**Comment by GiovanH** [comment]
Okay, if this was an intentional design choice, that’s different. I think it’s perfectly reasonable to have an expectation that if you make a subclass you also have to redefine the operator functions. 

I still don’t like that this is a “gotcha” though. If I hadn’t also overwritten my repr I never would have noticed this. Even if this isn’t a formal design point, if this is consistent behavior throughout the standard library, shouldn’t this be documented somehow? Or is it documented already, and I missed it?

**Comment by gvanrossum** [comment]
It’s not consistent. It’s up to each module’s design, and it’s decided based on the cost of doing it this way and the perceived need. Also realize that doing what you want constrains the class constructor signature for subclasses.

**Comment by pochmann** [comment]
A quick decorator hack, maybe an idea for fun tools or just you ([Try it online!](https://tio.run/##bVBBboMwELz7FatcbFqCBLlUVVtVyjOqyqJmSd2AbdlGbYTydmoTUgjqigOenZndHXPyn1rtHowdBtkabT0I3TQovNTKEVJhDRZ9ZxV33Yc/GWQtBknlkkcCoSKhQqFt6bVlornisWptQZUtglQwqTJnGunZghTr0oRnOKAvvR990lGa3PDisG9bGnZX2oNbmcS6rApBPq05MW9t3HpKOrrOpNmGLJ5/ZxJCXlehUB5/OacJEU3pHOy1EtLhXnfKYxg1h5pN2CJAzi0ayzlz2NSLs6bB9InCPdAUaPalpWL1pq9pL84/QM/98bwZgz6mIGLQ0SKTHlvHkiTKXmjYV@Qh3dVOb3kKxfjt3sPaxf@M2CPGSuWZCM/xWpGHRCesuGLFjOWwhbmRb2NvGH4B "Python 3.8 (pre-release) – Try It Online")):
```

**Comment by GiovanH** [comment]
> A quick decorator hack, maybe an idea for functools or just you. You just specify which methods to modify:

Oh, this is beautiful. 

My only thought with this (and the `return Sub(super().__add__(other))` form, as the same kind of "casting") is that this wouldn't work for cases where a new instance can't be trivially created with the form `cls(instance)`, although a sensible example where that would be the case isn't coming to mind. 

But even in cases like that you could probably do some hacking with `copy`, something like 

```python
    def __sub__(self, other):
        to_cast = ConciseCounter((super().__sub__(other)))
        return self.__class__.copy(to_cast)
```
or the equivalent decorator version.
