### ISSUE TITLE
Minor parsing issue with new -X int_max_str_digits option if PYTHONINTMAXSTRDIGITS

### ISSUE THREAD

**Issue by vstinner** [python/cpython#96848]
``python -X int_max_str_digits`` command is invalid:

```
$ python -X int_max_str_digits
Fatal Python error: config_init_int_max_str_digits: -X int_max_str_digits: invalid limit; must be >= 640 or 0 for unlimited.
Python runtime state: preinitialized
```

But if PYTHONINTMAXSTRDIGITS environment variable is defined, the invalid option is no longer rejected:

```
$ PYTHONINTMAXSTRDIGITS=5000 python -X int_max_str_digits
Python 3.12.0a0 (heads/main:e37ac5fbb6, Sep 15 2022, 15:03:41) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

It's just because the `valid` variable in config_init_int_max_str_digits() is not initialized again in the -X option code path, after the env var is parsed.

I noticed this minor issue while backporting the change to Python 3.6 in Fedora for Red Hat.

cc @tiran @gpshead

**Comment by gpshead** [comment]
Nice find.  "Oops!"  We're obviously missing an integration test for this situation.  At least this scenario should be uncommon.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/41351662bcd21672d8ccfa62fe44d72027e6bcf8
