### ISSUE TITLE
Show value in error of list.remove

### ISSUE THREAD

**Issue by tdegeus** [python/cpython#96844]
Consider
```python
foo = ["a", "b"]
for i in ["c"]:
    foo.remove(i)
```

This throws with a useless error message:
```
Traceback (most recent call last):
  File "/Users/tdegeus/Downloads/t.py", line 3, in <module>
    foo.remove(i)
ValueError: list.remove(x): x not in list
```

Instead it would be very helpful to show the value of `x`. Now one needs extra manual debugging, or extra lines of code. 

### Linked PRs
* gh-106455
* gh-116956

**Comment by pochmann** [comment]
What if `x` is large, so large that it pushes the previous information off-screen or even out of the screen buffer?

What if the conversion of `x` to string takes a long time or causes another error? (Think of the current [large int issue](https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889)).

**Comment by ericvsmith** [comment]
Wouldn't we already have this problem with KeyError on dict lookups:
```python
>>> {}[1234]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 1234
```
?
I guess you could argue that the value should be removed from KeyError.

**Comment by corona10** [comment]
````

Python 3.13.0a0 (heads/main:217f47d6e5, Jul  6 2023, 07:20:36) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> foo = ["a", "b"]
>>> for i in ["c"]:
...     foo.remove(i)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: 'c' is not in list
````

Now the error message is updated, here is the rationale why I agree with the updating error message even if for the possibility of large input.

https://github.com/python/cpython/pull/106455#issuecomment-1622021822

cc @tdegeus @pochmann @ericvsmith
