### ISSUE TITLE
Error message when converting an Integer that's too big to a String might be misinterpreted

### ISSUE THREAD

**Issue by emilia-ghdt** [python/cpython#96857]
The error message when converting from int to str for ints with more than 4300 digits (default setting):
`ValueError: Exceeds the limit (4300) for integer string conversion`
makes it seem like the limit is 4300 instead of 4300 **_digits_**.
`ValueError: Exceeds the limit (4300 digits) for integer string conversion`
would be more clear

The other way around is a little bit more clear, because it mentions the number of digits of the input:
`ValueError: Exceeds the limit (4300) for integer string conversion: value has ... digits`
but
`ValueError: Exceeds the limit (4300 digits) for integer string conversion: value has ... digits`
would be more clear in this case too.

**Comment by iritkatriel** [comment]
This was fixed in 935ef593211a627526b2b869ce1fc2a5e67e6cdd.
