### ISSUE TITLE
docs: clarify using lru_cache on class method keeps a reference to the instance

### ISSUE THREAD

**Issue by codicocodes** [python/cpython#96851]
# Documentation

When using the [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) decorator on class methods the cached function keeps a reference to each instance (self) preventing the class instance from being garbage collected. This is expected behavior, as `self` is a parameter to the cached function. However, many use it on class methods expecting the cache to be on a per instance basis.

[This](https://www.youtube.com/watch?v=sVjtp6tGo0g) video explains the issue in detail, and googling `lru_cache memory leak` gives a lot of examples of people who have faced this issue.

I suggest that we clarify this behavior in the documentation to prevent others from falling into this trap.

Perhaps modifying the following paragraph something like this:

> The cache keeps references to the arguments and return values until they age out of the cache or until the cache is cleared.  >>*This includes references to self, which will prevent class instances from getting garbage collecting.*<<

Would be happy to make a PR if you think this is a good idea.

Looking forward to feedback!

**Comment by rhettinger** [comment]
I've closed the PR because I want to work this differently.

**Comment by codicocodes** [comment]
Thank you for your quick response!

I do think linking to the FAQ would help because it clearly states that:

> The two principal tools for caching methods are [functools.cached_property()](https://docs.python.org/3/library/functools.html#functools.cached_property) and [functools.lru_cache()](https://docs.python.org/3/library/functools.html#functools.lru_cache). The former stores results at the instance level and the latter at the class level.

I think the issue could be that the documentation doesn't mentioned if it's cached on the class level or on the instance level when used on a method, even though it's implied that it's on the class level in the previously mentioned sentence. This could lead to someone using `lru_cache(maxsize=None)` mistakenly believing the cache is on the instance level and that it will be cleared when the instance is garbage collected.

Thank you for clarifying and helping!
