### ISSUE TITLE
os.path.samefile should mention MacOS

### ISSUE THREAD

**Issue by merriam** [python/cpython#96856]
# Documentation

The documentation has chosen to by silent on MacOS issues.  MacOS, by default, is a case-preserving and case-insensitive file system.   That is, files "fileName" and "FILEname" cannot both exist, but referencing the file by either is correct.  This causes lots of fun bugs in cross platform software.

There should be a line that samefile on MacOS (default) is case insensitive.

**Comment by vovoxxx7** [comment]
from __future__ import annotations

**Comment by ronaldoussoren** [comment]
I don't think this needs to be mentioned in the documentation. There are numerous reasons why two paths may refer to the same file, and case sensitiveness is one of those reasons.
