### ISSUE TITLE
venv.create() fails when sys._base_executable is empty

### ISSUE THREAD

**Issue by meeuw** [python/cpython#96861]
# Bug report

`venv.create()` fails when `sys._base_executable` is empty.

This happens when Python cannot determine the base_executable when it's started without a full path and `PATH` is empty:

```
$ env -i python
Python 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys ; print(sys._base_executable)

>>> 
```

```
$ env -i python -mvenv /tmp/dmtest
Unable to symlink '' to '/tmp/dmtest/bin/meeuw'
Error: [Errno 2] No such file or directory: ''
```

# Your environment

- CPython versions tested on: 3.10.6
- Operating system and architecture: linux / x86_64

Would it be possible to raise an exception when `sys._base_executable` is empty with a sane error message?

Related to: https://github.com/python-poetry/install.python-poetry.org/issues/43

**Comment by vsajip** [comment]
This isn't a bug in `venv`. If you do `env -i python`, then `sys.executable` is set to the empty string, so _lots_ of things would break.

**Comment by meeuw** [comment]
I'm not so sure about that, the documentation describes that `sys.executable` can be empty:

> If Python is unable to retrieve the real path to its executable, [sys.executable](https://docs.python.org/3/library/sys.html#sys.executable) will be an empty string or None.

I think it makes sense for venv to error out with a proper error message. For example start python using a full path or set a `PATH` where python can be found.
