### ISSUE TITLE
incorrect translation for `milliseconds` in zh-cn documents

### ISSUE THREAD

**Issue by chuckliu1979** [python/cpython#96862]
# Documentation
from https://docs.python.org/zh-cn/3/library/datetime.html datetime.isoformat(sep='T', timespec='auto'):

'milliseconds': 包含完整时间，但将秒值的小数部分截断至微秒。 格式为 HH:MM:SS.sss

(A clear and concise description of the issue.)
It's wrong translated 'milliseconds', in chinese, it's "毫秒“, not "微秒"

**Comment by AlexWaygood** [comment]
Issues to do with translations need to be filed over at https://github.com/python/python-docs-zh-cn (and I see you've already filed an issue over there :)
