### ISSUE TITLE
assertAlmostEqual: ValueError on negative delta

### ISSUE THREAD

**Issue by wehlgrundspitze** [python/cpython#96882]
While adding the keyword rel_delta to the test functions assertAlmostEqual and assertNotAlmostEqual (issue #96881 ), I thought about restrictions on delta and rel_delta. Obviously, they should be both positive to perform a meaningful test. So far, there is no exception thrown if they are negative. Shouldn't there be ValueError implemented ?

**Comment by ericvsmith** [comment]
Do negative values really cause a problem? Wouldn't the test always fail and the user would figure it out?

**Comment by mdickinson** [comment]
I don't think I'd describe this as a bug - that is, it's not obviously wrong behaviour that we should be considering changing for 3.11 and earlier; only potentially for 3.12 and later.

What value would the additional check bring? Arguably it could catch user bugs where the user happens to have supplied a negative `delta`, but I'm having trouble seeing that as a common enough user error that it's worth adding extra checks to guard against it, and the failure mode for that error (test always fails, as @ericvsmith pointed out) seems reasonable.

**Comment by mdickinson** [comment]
Consistency with `math.isclose` would be one possible reason for changing this:
```
>>> math.isclose(2.3, 2.4, abs_tol=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: tolerances must be non-negative
```

**Comment by rhettinger** [comment]
Since this would already surface as a failing test, I don't see any reason for a change.  There isn't a problem to be solved.

**Comment by mdickinson** [comment]
I think we have consensus here. Closing.
