### ISSUE TITLE
`re.sub` returns duplicated replacement strings in some cases.

### ISSUE THREAD

**Issue by danny0838** [python/cpython#96907]
# Bug report
```python
re.sub(r'.*', r'x', 'a')   # expect: 'x', actual: 'xx'
re.sub(r'^.*$', r'x', 'a')   # expect: 'x', actual: 'x'
re.sub(r'^.*', r'x', 'a')   # expect: 'x', actual: 'x'
re.sub(r'.*$', r'x', 'a')   # expect: 'x', actual: 'xx'
```

# Environment
- CPython 3.10.6 / Linux
- CPython 3.8.13 / Windows

**Comment by sweeneyde** [comment]
Is this a duplicate of https://github.com/python/cpython/issues/85727 ?

**Comment by mrabarnett** [comment]
Yes, it's a duplicate.

**Comment by animalize** [comment]
This is not a bug. `regex` module has the same behavior.
```python
>>> import regex as re
>>> re.sub(r'.*', r'x', 'a')   # expect: 'x', actual: 'xx'
'xx'
>>> re.sub(r'^.*$', r'x', 'a')   # expect: 'x', actual: 'x'
'x'
>>> re.sub(r'^.*', r'x', 'a')   # expect: 'x', actual: 'x'
'x'
>>> re.sub(r'.*$', r'x', 'a')   # expect: 'x', actual: 'xx'
'xx'
```

**Comment by animalize** [comment]
This is a bit suspicious. `$` has been matched in the first time.
```python
re.sub(r'.*$', r'x', 'a')   # expect: 'x', actual: 'xx'
```

**Comment by pochmann** [comment]
Well `$` is zero-length, so doesn't *consume* anything. And `.*$` simply matches `'a'` both at index 0 and at index 1.

**Comment by danny0838** [comment]
Oh, I get it.

For the case of `re.sub(r'.*', r'x', 'a') `, there's a chance for ".*"  to match "" at position 1 after matching "x" at position 0 and replacing it with "a".

If we don't want the ending "" be matched, we'd have to write a regex like `(?!$).*`.

**Comment by animalize** [comment]
> Well $ is zero-length, so doesn't consume anything. And .*$ simply matches 'a' both at index 0 and then at index 1.

The zero-length `$` should have been matched in the first time. It seems the zero-length end has been matched twice.

> If we don't want the ending "" be matched, we'd have to write a regex like (?!$).*.

`.+` is simpler.

**Comment by pochmann** [comment]
> the zero-length end has been matched twice

Yes. Why wouldn't it?
