### ISSUE TITLE
Not to generate local variable when only "+=" operator's found

### ISSUE THREAD

**Issue by anzhi0708** [python/cpython#96916]
# Feature or enhancement

When "=" operation found in function definition code, Python adds the variable name to this function's local variable list - this is easy for me to understand; but "+=" was treated the same way - different from what people (beginners like me) would expect.

# Pitch

When people do 
```python
global_var = 0

def access():
        print(global_var)
        global_var += 1

access()
```

You can tell what they really wanted to achieve - to change that variable because "=" can be used as variable declaration and "+=" can't. In my opinion this is somehow not beginner friendly?

I know you can use `global` keyword to access it, but the fact that any read-only operations e.g. `print(global_var)` does not need to use `global` is kind of confusing?

# Previous discussion

Not really sure... New to python

**Comment by AlexWaygood** [comment]
This is a long-standing feature of Python, so changing it would require a substantial amount of discussion. I'd recommend starting a discussion at https://discuss.python.org/; I think it's too soon to open a GitHub issue for this :)
