### ISSUE TITLE
FR: Add Link to Typing RTD in `typing` Module

### ISSUE THREAD

**Issue by adam-grant-hendry** [python/cpython#96917]
# Feature or enhancement

Discussions on adding a link to the [typing readthedocs](https://typing.readthedocs.io/en/latest/#) (RTD) on the `typing` module documentation page have been had:

- [python/typing: Make Link to ReadTheDocs Typing Docs More Explicit](https://github.com/python/typing/discussions/1255#discussioncomment-3675497)
- [python/typing: Why is typeshed information not integrated into the official python docs?](https://github.com/python/typing/discussions/1227)
- [python/cpython: Proposal: Convert the typing-module PEPs into a series of HOWTOs](https://github.com/python/cpython/issues/91533)
- [python/typing: Document Structure and Wishlist](https://github.com/python/typing/issues/845)

The request is to add a link to the top of the [`typing` module docs](https://docs.python.org/3.11/library/typing.html#module-typing) linking readers to the page. This would serve the following needs:

1. The RTD is not particularly discoverable via search engines (the most notable link is in the README of the [typeshed repo](https://github.com/python/typeshed/))
2. A desire has been expressed for incorporating PEPs into a series of HOWTOs and [some consensus has been achieved](https://github.com/python/typing/discussions/1255#discussioncomment-3675497) that the RTD would be the best place for this

# Pitch

Please add a link to the [typing readthedocs](https://typing.readthedocs.io/en/latest/#) on the python [`typing` module docs](https://docs.python.org/3.11/library/typing.html#module-typing) page.

- It [has been suggested](https://github.com/python/typing/discussions/1255#discussioncomment-3665825) that a "See Also" box would work nicely

The OP is open to any implementation resulting in an easily findable and noticeable hyperlink for users.

# Previous discussion

Repeated from above:

- [python/typing: Make Link to ReadTheDocs Typing Docs More Explicit](https://github.com/python/typing/discussions/1255#discussioncomment-3675497)
- [python/typing: Why is typeshed information not integrated into the official python docs?](https://github.com/python/typing/discussions/1227)
- [python/cpython: Proposal: Convert the typing-module PEPs into a series of HOWTOs](https://github.com/python/cpython/issues/91533)
- [python/typing: Document Structure and Wishlist](https://github.com/python/typing/issues/845)

**Comment by AlexWaygood** [comment]
The link has been added, and the change has been backported to 3.11 and 3.10.
