### ISSUE TITLE
Optimizing constant list subscripting

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#96939]
Optimizing subscripting lists with constants.

**Comment by thatbirdguythatuknownot** [comment]
I don't really see any other label that fits this issue.

**Comment by sweeneyde** [comment]
Related prior discussion here: https://github.com/python/cpython/issues/83404

**Comment by sweeneyde** [comment]
Are there any real examples of people writing `["a", "b", "c"][1]` or the like where this optimization would help things?

**Comment by thatbirdguythatuknownot** [comment]
> Are there any real examples of people writing `["a", "b", "c"][1]` or the like where this optimization would help things?

I don't know, actually. Someone in the Python Discord suggested to open an issue with this one, since the implementation is just simple.

**Comment by corona10** [comment]
@thatbirdguythatuknownot 
For the optimization approach, we need to know if the use case often happens.
For the same reason, we don't implement aggressive optimization if the use case is rare.

**Comment by iritkatriel** [comment]
> > Are there any real examples of people writing `["a", "b", "c"][1]` or the like where this optimization would help things?
> 
> I don't know, actually. Someone in the Python Discord suggested to open an issue with this one, since the implementation is just simple.


Apart from the doubts already expressed about the usefulness of this optimisation, a PR like this needs to include a unit test that asserts that the optimisation did what it was supposed to do. Otherwise we can break the optimisation without even knowing with future code changes.

**Comment by kumaraditya303** [comment]
As said above there are no real world use for this. Thanks for PR but its not worth it.
