### ISSUE TITLE
Port PyPy's new unicode name db format to optimize binary CPython size

### ISSUE THREAD

**Issue by isidentical** [python/cpython#96954]
# Feature or enhancement

PyPy has a new algorithm that might help us reduce the unicode name db size of our binaries (which would be helpful on our way forward to better WASM compatibility [through reduced download sizes]). For more details, you can see the new implementation in [PyPy side](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/rpython/rlib/unicodedata/dawg.py#L1-12) by @cfbolz. 

CC: @ambv @cfbolz

We'll probably start with missing tests, and then build out a prototype to see how feasible it is and will share numbers on how much it would help before going forward with the implementation.

### Linked PRs
* gh-97906
* gh-111764
* gh-112118
* gh-112120

**Comment by hroncok** [comment]
I've noticed `make regen-unicodedata` fails in out-of-tree build:

```
python3.13 Tools/unicode/makeunicodedata.py
python3.13: can't open file '.../build/debug/Tools/unicode/makeunicodedata.py': [Errno 2] No such file or directory
make: *** [Makefile:1498: regen-unicodedata] Error 2
```

I think I know how to fix this and will submit a PR once I test my assumption.

**Comment by hroncok** [comment]
https://github.com/python/cpython/pull/112118

**Comment by hroncok** [comment]
I've also noticed it is now impossible to call `make regen-all` when offline.

Is it necessary to include `regen-unicodedata` in `regen-all`?

**Comment by vstinner** [comment]
> I've also noticed it is now impossible to call make regen-all when offline.

regen-configure pulls a docker container image, it's not the only "regen" command using Internet. But `regen-configure` is excluded from `make regen-all`.

Maybe we can exclude `regen-unicodedata` from `regen-all` since it's rare to have to update these data, whereas it's common to run `regen-all` to update more frequently changed files.

**Comment by vstinner** [comment]
The initial feature request is now implemented and known issues have been fixed. I close the issue.

Thanks @cfbolz for this cool optimization!
