### ISSUE TITLE
Update to libffi 3.4.3

### ISSUE THREAD

**Issue by zooba** [python/cpython#96965]
The issue described in #26204 should be resolved by this update.

It should be backported to all branches currently using 3.4.2.

**Comment by dpy013** [comment]
cc
                    @ambv 
                    and
                    @MaxwellDupre 
                    Is it possible to submit a
                    [pull request](https://github.com/python/cpython/pulls)
                    to update libffi?

**Comment by zooba** [comment]
No, I need to do it, because we have to build it on our release infrastructure. Just haven't gotten to it because I've been sick.

**Comment by zooba** [comment]
Compilation error:

```
libtool: compile:  /cygdrive/c/Users/mick/programming/git/cpython-source-deps/msvcc.sh -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -DFFI_BUILDING_DLL -I. -I../include -Iinclude -I../src -c ../src/x86/sysv_intel.S  -DDLL_EXPORT -DPIC -o src/x86/.libs/sysv_intel.obj
sysv_intel.S
 Assembling: src/x86/.libs/sysv_intel.asm
src/x86/.libs/sysv_intel.asm(1807) : error A2008:syntax error : *
src/x86/.libs/sysv_intel.asm(1808) : error A2008:syntax error : *
make[3]: *** [Makefile:1279: src/x86/sysv_intel.lo] Error 1
```

**Comment by zooba** [comment]
Seems to be these lines:

https://github.com/python/cpython-source-deps/blob/ba2ec1402a4039f86f39962c90dc10f23630e71b/src/x86/sysv_intel.S#L758-L759

The preprocessor is handling the double `*/ */` differently, I assume, and ending the comment at the first one rather than treating them as nested (which I believe is incorrect anyway?)

I can patch it out of our copy of the sources and build anyway, just checking what else might break before committing it.

@atgreen FYI
