### ISSUE TITLE
PyCodeObject co_lnotab not found on 3.10.7

### ISSUE THREAD

**Issue by leandrogmuller** [python/cpython#96963]
# Bug report
I'm trying to compile C++ with below code and C++ not found the propertie co_lnotab.
Did 3.10 remove the co_lnotab propertie?
In doc is there: https://docs.python.org/3.10/library/inspect.html

`static int checkBycodePosition(PyCodeObject* co, int fline)
{   
	Py_ssize_t size = PyBytes_Size(co->co_lnotab) / 2; //error
	unsigned char* p = (unsigned char*)PyBytes_AsString(co->co_lnotab); //error

}`

# Your environment
Python 3.10.7

**Comment by sweeneyde** [comment]
Yes, it appears this was removed in 3.10. See PEP 626, particularly https://peps.python.org/pep-0626/#the-co-lnotab-attribute

> Tools that parse the co_lnotab table should move to using the new co_lines() method as soon as is practical.

See also the c function [PyCode_AddrToLine(PyCodeObject *co, int byte_offset)](https://docs.python.org/3.10/c-api/code.html?highlight=codeobject#c.PyCode_Addr2Line).

**Comment by leandrogmuller** [comment]
Hello.
The co_lines ia not present in PyCodeObject, and I need convert line to addr bytes.

**Comment by sweeneyde** [comment]
The documentation is for a python-level attribute, not a c-level structure member. So you can still do `PyObject_GetAttrString(co, "co_lnotab")` for right now, though PEP 626 mentions that the `co_lnotab` python attribute will be deprecated as well. But it doesn't emit any warnings yet.

Using `PyObject_CallMethod(co, "co_lines", NULL)` will return a Python iterator, which you can iterate through using the [iterator protocol](https://docs.python.org/3/c-api/iter.html).

Example:
```python
>>> def f(x):
...     x += 1
...     return x
...
>>> code = f.__code__
>>> code.co_lnotab # deprecated
b'\x00\x01\x08\x01'
>>> code.co_lines()
<line_iterator object at 0x0000025A2BF9BF00>
>>> list(code.co_lines())
[(0, 8, 2), (8, 12, 3)]
```

**Comment by leandrogmuller** [comment]
Hello sweeneyde, thanks for your help.

I need to get address from line to jump on debug (trampoline).
But I don't understand how can I do with co_lines.
frame->f_lasti = get_addr_to_jump(frame->f_code, 10)

`static int get_addr_to_jump(PyCodeObject* co, int line_to_jump)
{   
 	PyObject * co_lnotab = PyObject_GetAttrString((PyObject *) co, "co_lnotab");
	Py_ssize_t size = PyBytes_Size(co_lnotab) / 2;
	unsigned char* p = (unsigned char*)PyBytes_AsString(co_lnotab);
	int line_current = co->co_firstlineno;
	int addr = 0;
	while (--size >= 0)
	{
		addr += *p++;
		line_current += (signed char)*p;
		if (line_current == line_to_jump)
			break;
		p++;
	}
	return addr;
}
`

**Comment by leandrogmuller** [comment]
Thanks.

I got.

First I changed the function to check if I can to jump.

`static int has_addr_to_jump(PyCodeObject* co, int line_to_jump)
{
	int has = 0;
	PyObject* co_lnotab = PyObject_GetAttrString((PyObject*)co, "co_lnotab");
	Py_ssize_t size = PyBytes_Size(co_lnotab) / 2;
	unsigned char* p = (unsigned char*)PyBytes_AsString(co_lnotab);
	int line_current = co->co_firstlineno;
	int addr = 0;
	while (--size >= 0)
	{
		addr += *p++;

		line_current += (signed char)*p;

		if (line_current == line_to_jump) {
			has = 1;
			break;
		}
		 
		p++;
	} 
	return has;
}
`

After I only check if I can jump, so I set to trace = true and CPython enable f_lineno to change address on f_lasti on internal function frame_setlineno of the frameobject.c.
So...
`if (has_addr_to_jump(frame->f_code, PyLong_AsLong(line))==1) {
				frame->f_trace = Py_True;
				PyObject_SetAttrString((PyObject*)frame, "f_lineno", line);
				frame->f_trace = Py_False;
			}`
