### ISSUE TITLE
A wrong example in Python Tutorial at "5.7. More on Conditions" 

### ISSUE THREAD

**Issue by alduico** [python/cpython#96980]
# Documentation
The sentence "For example, if A and C are true but B is false, A and B **and** C does not evaluate the expression C." must be corrected into "For example, if A and C **or** true but B is false, A and B and C does not evaluate the expression C.

Proof:
a = True
b = True
c = False
a and b and c    ---> False   (c is evaluated)
a and b or c      ---> True    (c is'nt evaluated)

(A clear and concise description of the issue.)

**Comment by saito828koki** [comment]
Thanks for your report.

I think the original document is correct.
“If A and C are true” means “If both A and C are true”.

**Comment by pochmann** [comment]
A [link](https://docs.python.org/3/tutorial/datastructures.html#more-on-conditions) to it would be good, especially since you didn't replicate the styling shown there.

Your bold **or** is at a different place in the sentence  than your bold **and**, making this unclear.

Anyway, the documentation is correct.

**Comment by zware** [comment]
The documentation is correct as is.  @alduico, you swapped the truthiness of `b` and `c` in your example; the docs call for `B` to be false and `C` to be true.

Here's an attempt to show what the docs are saying with some code that's hopefully relatively easy to follow, though it uses some concepts from beyond this point of the tutorial:

```python
class c:
    def __init__(self, name):
        self.name = name
        print(self, 'created')

    def __bool__(self):
        result = self.name != 'B'
        print(self, '.__bool__ called, returning ', result, sep='')
        return result

    def __repr__(self):
        return f'{type(self).__name__}({self.name!r})'

and_result = c('A') and c('B') and c('C')
print(f'{and_result=}')

print()

or_result = c('A') and c('B') or c('C')
print(f'{or_result=}')
```

The output of the above is:

```
c('A') created
c('A').__bool__ called, returning True
c('B') created
c('B').__bool__ called, returning False
and_result=c('B')

c('A') created
c('A').__bool__ called, returning True
c('B') created
c('B').__bool__ called, returning False
c('C') created
or_result=c('C')
```

Hopefully this shows that in the `A and B and C` case, when `B` is false `C` is not evaluated at all, while in the `A and B or C` case `C` is evaluated and given as the result, but not checked for truthiness.

If you have any questions about this, please open a topic at https://discuss.python.org/c/help/7 and our community will be glad to help you understand.

**Comment by alduico** [comment]
> and

**Comment by alduico** [comment]
You persuaded me at all. Probably I did'nt read carefully  the sentence.
Thank you for your attention.
Ciao
