### ISSUE TITLE
Provide NameError/AttributeError suggestions in traceback.py

### ISSUE THREAD

**Issue by ambv** [python/cpython#97008]
Python 3.10 added NameError and AttributeError suggestions in raised exceptions, in the form of:

```pycon
>>> dim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dim' is not defined. Did you mean: 'dir'?
```

This is implemented in `Python/suggestions.c` and unavailable in the pure Python implementation of traceback formatting in `Lib/traceback.py`. This makes the output of both different, which is problematic for tooling using `traceback.py`, as well as for alternative implementations of Python like PyPy and GraalPy.

Let's implement the equivalent of `suggestions.c` in `Lib/traceback.py` to bring both in line.

**Comment by ambv** [comment]
cc @cfbolz

**Comment by sweeneyde** [comment]
I'm not sure if exact equivalence with suggestions.c is required, but if not, IIRC there was at one point a call to use difflib's [get_close_matches()](https://docs.python.org/3/library/difflib.html?highlight=difflib#difflib.get_close_matches), which might simplify things.

**Comment by cfbolz** [comment]
@sweeneyde the plan is to start from [PyPy's implementation](https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.9/lib-python/3/traceback.py#L190), @ambv and I started working on that today (it's a port of Pablo's original commit, at the time I didn't your later changes hadn't landed).

**Comment by gpshead** [comment]
cc @Yhg1s

**Comment by ambv** [comment]
Fixed!

**Comment by cfbolz** [comment]
wonderful, thank you @ambv, @pablogsal and @sweeneyde :blush:
