### ISSUE TITLE
Redundant and possibly misleading SyntaxWarnings

### ISSUE THREAD

**Issue by aroberge** [python/cpython#97029]
# Feature or enhancement

This report actually suggest *removing* a feature.

When trying to add information about warnings in friendly-traceback, I found out that cPython emits `SyntaxWarning`s for code that triggers exceptions. In some cases, the warnings include hints of dubious value. Ignoring the hint, the message tacked on to the `SyntaxWarning` is identical to that provided by the exception that is raised.

Here are two examples.

```python
Python 3.10.2 ... on win32
>>> import warnings
>>> warnings.simplefilter("always")
>>> 1[2]
<stdin>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not subscriptable
>>> [1, 2, 3]()
<stdin>:1: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list' object is not callable
```
I am wondering about the value of emitting such warnings, and if this does result in reduced efficiency.

I realize that, if one uses `compile(statement, filename, "single")`, a `SyntaxWarning` will be shown without triggering an exception, but even then I fail to see the usefulness of emitting such warnings, and wonder about the additional code complexity required to provide this information, which is likely not visible by the vast majority of users who do not enable warnings.

**Comment by sweeneyde** [comment]
These were introduced at https://github.com/python/cpython/pull/11757. (cc @serhiy-storchaka)

**Comment by aroberge** [comment]
Note that this should have been labeled as "Feature" instead of "Bug". This was due to a mistake of my part.

**Comment by serhiy-storchaka** [comment]
It is neither redundant nor misleading. It helps to fix the following bugs:
```python
a = [
    (1, 2, 3),
    (4, 5, 6)
    (7, 8, 9)
]
```
```python
a = [
    [1, 2, 3],
    [4, 5, 6]
    [7, 8, 9]
]
```
