### ISSUE TITLE
Bug in string capitalize() method

### ISSUE THREAD

**Issue by dppalukuri** [python/cpython#97504]
# Bug report

When trying to capitalize a string using capitalize() method, the first character is capitalized as expected. However, the rest of the string is converted to lower case.

# Expected Behavior :
a= "cats and Dogs are Friends"
a.capitalize()
"Cats and Dogs are Friends"

# Actual Behavior :
a= "cats and Dogs are Friends"
a.capitalize()
"Cats and **d**ogs are **f**riends"

# Your environment
Python 3.9.11

- Operating system and architecture:
Tested on Windows 10 Enterprise and Ubuntu 20/22

**Comment by hugovk** [comment]
This is the documented behaviour:

> Return a copy of the string with its first character capitalized **and the rest lowercased**.

https://docs.python.org/3/library/stdtypes.html#str.capitalize says:

**Comment by stevendaprano** [comment]
You should also check out the `string` module, especially `string.capwords()` which may do what you want.
