### ISSUE TITLE
Unwanted handling of the printing string with min() function inside print().

### ISSUE THREAD

**Issue by jjmuriel** [python/cpython#97508]
# Bug report
Unwanted handling of the printing string with min() function.

Example:
```
# Demonstrating min()
t = 'The Knights Who Say "Ni!"'   # or: print('[' + min(t) + ']')
print(f'[{min(t)}]')
```
Prints:
`A`
`[ ]`

Expected output:
`[A]`

# Your environment

- CPython versions tested on: Python 3.10.6
- Operating system and architecture: Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 (macOS Big Sur 11.6.8 - MacBook Pro Retina mid 2014)

**Comment by ronaldoussoren** [comment]
This is expected behaviour, the code point for space has a lower value than the code point for other characters in the string.

E..g.
```python
>>> " " < "A"
True
```

Which is why you get:
```python
>>> min("A ")
' '
```

**Comment by jjmuriel** [comment]
> This is expected behaviour, the code point for space has a lower value than the code point for other characters in the string.
> 
> E..g.
> 
> ```python
> >>> " " < "A"
> True
> ```
> 
> Which is why you get:
> 
> ```python
> >>> min("A ")
> ' '
> ```

Thank you very much for the clarification.
