### ISSUE TITLE
the results of eval(...) for basic arithmetic operations are inccorrect

### ISSUE THREAD

**Issue by v381654729** [python/cpython#97505]
# Bug report

print(eval("85 / ( 92.6 - 78 - 14.6 )"))  =>  -1.5950248680270506e+16  (but should throw a ZeroDivisionError)
print(eval("29 / ( 28.4 - 17 - 11.4 )"))  =>  -1.6325548649218048e+16  (but should throw a ZeroDivisionError)
print(eval("17 / ( 10.8 - 8.5 - 2.3 )"))   =>    1.914029841632461e+16  (but should throw a ZeroDivisionError)

This error occurs on both Windows and Ubuntu. Hope that this type of bugs in basic arithmetic operations can be resolved in future versions of Python 3.

**Comment by ericvsmith** [comment]
`eval` is not required for this:
```python
>>> 85 / ( 92.6 - 78 - 14.6 )
-1.5950248680270506e+16
```
You're seeing binary floating point approximations for decimal numbers. See https://docs.python.org/3/tutorial/floatingpoint.html to understand what's happening.

The root of the issue is:
```python
>>> 92.6 - 78 - 14.6
-5.329070518200751e-15
```
