### ISSUE TITLE
Synchronize links in other copies of HISTORY OF THE SOFTWARE

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#97519]
HTTP links in the "HISTORY OF THE SOFTWARE" section of `Doc/license.rst` were converted to HTTPS. But there are other copies of this section in `LICENSE` and `Mac/BuildScript/resources/License.rtf`, and there is yet one related link in `Misc/HISTORY`. HTTP links were kept here. I though that we can upgrade these links because they are not part of third-party licenses and not part of the PSF license. But @gvanrossum said that "HISTORY OF THE SOFTWARE" is also important.

There are two ways to fix the discrepancy:

1. Upgrade other occurrences of these HTTP links to HTTPS.
2. Revert all or the part of upgrades of HTTP links to HTTPS in `Doc/license.rst`:
    * e73778c1ac0e58d3520b37308b970073e818fa00
    * 6dff0205b724669cc0469dd65a3f7edc5a69e1e7
    * dfe726b1ace03f206f45253b93ed7610473ae20f
    * f62ff97f31a775cc7956adeae32c14e7c85bdc15
    * f79547a429d5c90af83a0da821e082cba20d4712

**Comment by gvanrossum** [comment]
Honestly I think fixing http links is like fixing whitespace. Let's just do it.

**Comment by serhiy-storchaka** [comment]
Thanks, Guido.
