### ISSUE TITLE
Multi-variable assignment with nested assignment unexpected behaviour

### ISSUE THREAD

**Issue by YayL** [python/cpython#97542]
Same line variable assignments are, as far as I know, unpacked tuple assignments. However, multi-variable
assignment, where one assignment contains another assignment, does not work the same way as shown below.

Example:
```py
obj = False

for i in range(5):
    v, o = obj = not obj, "dont mind me"
    print(f'{v : <2} | {o}')
```
What I want it to behave like:
```py
obj = False

for i in range(5):
    (v, o) = (obj := not obj, "dont mind me")
    print(f'{v : <2} | {o}')
```

If I write the same assignment as my expected outcome without the parenthesis I get a syntax error not allowing the Walrus operator. Now, if I get rid of the multi-variable assignment and just assign **v** a value this is no longer an issue and it works as I would expect going through each nested assignment from the bottom up.
```py
obj = False

for i in range(5):
    v = obj = not obj
    print(v)
```

To conclude, either; give a syntax error on the first example or allow the Walrus in that case. 

**x86_64 Linux 5.15.70-1-lts
Endeavour OS**

Tested on versions:
**3.10.7
2.7.18**

**Comment by stevendaprano** [comment]
> give a syntax error on the first example or allow the Walrus in that case.

There is no need for a syntax error in the first example, the syntax is fine, and it behaves as expected: `v, o = obj = not obj, "dont mind me"` assigns obj to the tuple `(not obj, "dont mind me"), and unpacks that same tuple into v and o.

The walrus operator is allowed in the first example, you just have to use parentheses correctly:

```
v, o = (obj := not obj), "dont mind me"
```

Or you could use the syntax you already showed that will accomplish what you want:

```
(v, o) = (obj := not obj, "don't mind me")
```

You already know how to accomplish this. There's no need to break backwards compatibility by changing the behaviour of assignment.

**Comment by JelleZijlstra** [comment]
As @stevendaprano explained there is no bug here. Perhaps a case could be made for allowing an unparenthesized walrus operator in more places, but that's better discussed first in discuss.python.org.

**Comment by YayL** [comment]
> > give a syntax error on the first example or allow the Walrus in that case.
> 
> There is no need for a syntax error in the first example, the syntax is fine, and it behaves as expected: `v, o = obj = not obj, "dont mind me"` assigns obj to the tuple `(not obj, "dont mind me"), and unpacks that same tuple into v and o.
> 
> The walrus operator is allowed in the first example, you just have to use parentheses correctly:
> 
> ```
> v, o = (obj := not obj), "dont mind me"
> ```
> 
> Or you could use the syntax you already showed that will accomplish what you want:
> 
> ```
> (v, o) = (obj := not obj, "don't mind me")
> ```
> 
> You already know how to accomplish this. There's no need to break backwards compatibility by changing the behaviour of assignment.

Yes, that would be correct. The sort of approved solution can not be used as the walrus operator is not usable if you are using a list.

Example:
```py
obj = {'bool': False}

for i in range(5):
    (v, s) = (obj['bool'] := not obj['bool'], "don't mind me")
    print(f'{v : >2}| s}'
```

This is incorrect as you are given syntax and you can not use '=' only as that is not permitted. This was the initial cause of this report. Now, there might be a good solution for this and I understand that breaking backward compatibility is not something you really want.
