### ISSUE TITLE
Typo in Chinese documentation of inspect module

### ISSUE THREAD

**Issue by kanglmf** [python/cpython#97551]
# Chinese Documentation Typo

https://docs.python.org/zh-cn/3/library/inspect.html?highlight=inspect#inspect.CO_VARKEYWORDS

The doc:
`代码对象拥有一个可变关键字形惨死（类似 **kwrags）。`

should be:
`代码对象拥有一个可变关键字形参（类似 **kwrags）。`

**Comment by saito828koki** [comment]
@kanglmf 

Thanks for your report.
Issues about translations need to be posted to this repository( [https://github.com/python/python-docs-zh-cn](https://github.com/python/python-docs-zh-cn) ).

**Comment by kanglmf** [comment]
OK, Thanks.
