### ISSUE TITLE
create a personal python interpreter use python 3.8

### ISSUE THREAD

**Issue by twilight2017** [python/cpython#97560]
# Feature or enhancement
Creating a private python interpreter using opcode permutation strategy
(A clear and concise description of your proposal.)
I want to create a private python interpreter by exchanging opcodes , aims to increase the difficulty of cracking the pyc file, we make a private python environment(private python)。
I made a little attempt first and I tested is 3.9.6:
swap the opcode of the two operations of BINARY_ADD and BINARY_SUBTRACT's opcode
My modification policy has the following three places:
1.Include/opcode.h：swap bytecode definitions:
![image](https://user-images.githubusercontent.com/38035081/192253544-e868c04f-079f-4e84-ad4a-4191951c510d.png)
2. Lib/opcoe.py: exchange the opcode:
![image](https://user-images.githubusercontent.com/38035081/192254769-e94bc98e-7ed2-49f8-a4e7-9b78e9cafd4f.png)
3.Python: opcode_targets .h: swap the order of the two opcodes in the swap
![image](https://user-images.githubusercontent.com/38035081/192255146-b7b32b86-8cc2-4429-a38c-d1967206c625.png)
<img width="683" alt="lQLPJxa42KP0z2jNAWTNBVawjsj6xfVo-2YDL-schECkAA_1366_356" src="https://user-images.githubusercontent.com/38035081/192255546-9c6006e3-a0f4-49b1-a2ae-859207b62093.png">
I would appreciate it if someone can provide me with some help
#problem
Unfortunately, after such a modification has been made, the python compilation precess failed。The error message is shown in the following figure:

# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

# Previous discussion

**Comment by ronaldoussoren** [comment]
This is a tracker for bugs and enhancements for CPython, not a general support forum for hacking on the project.

Please ask for help on discuss.python.org, or some other forum.
