### ISSUE TITLE
sqlite3.connect parameter `cached_statements` default value is incorrect

### ISSUE THREAD

**Issue by jiajunjie** [python/cpython#97567]
# Documentation

https://github.com/python/cpython/blob/8bdaf9bf8e39b2ea374ee01a36b3c1bdaed01b23/Doc/library/sqlite3.rst#L260

**Comment by pochmann** [comment]
Where is it defined as 100?

**Comment by jiajunjie** [comment]
> Where is it defined as 100? (The PR changes that doc to say 100.)

https://github.com/python/cpython/blob/8bdaf9bf8e39b2ea374ee01a36b3c1bdaed01b23/Modules/_sqlite/connection.c#L76

**Comment by erlend-aasland** [comment]
Thanks. FYI, the default limit was changed from 100 to 128 early in the 3.11 alpha phase (IIRC). The doc inconsistency pointed out stems from the backport of gh-94629.
