### ISSUE TITLE
Add SupportsBool to typing

### ISSUE THREAD

**Issue by pamelafox** [python/cpython#97569]
# Feature or enhancement

Similar to SupportsInt and SupportsFloat, I would like a SupportsBool to indicate any type that has `__bool__`.

# Pitch

I need this for typing in a current project and I imagine others could use as well.
I have a PR ready.

**Comment by pamelafox** [comment]
We're trying to type `Logger.propagate` for picologging, a third-party library which implements a subset of the logging module. We initially typed `propagate` as a bool and then realized it's sometimes set as an int (0/1), and comparisons internally just make sure its truthy or falsy. That's why we thought this typing would be appropriate.

That's a fair point that `bool()` can be called on anything. The classes that have `__bool__` explicitly supported would be more appropriately used for propagate however (basically int or bool). How would you suggest typing such things?

**Comment by JelleZijlstra** [comment]
If I were you I would use `bool` as the type and fix the code that passes 0 or 1. Alternatively you could use `object`.

In Python virtually anything can be converted to bool, but this can lead to bugs (infamously, `if self.some_method:` instead of `if self.some_method():`). If you use typing to make your code safer, I recommend using only `bool` for bools.

**Comment by AlexWaygood** [comment]
> that does mean that someone switching code from logging to picologging would need to set 0 to False, if their code was currently doing that.

Anybody using type-checking will already get errors if they set `propagate` to a non-`bool` attribute (using stdlib `logging`), since we use `bool` for the attribute in typeshed:

https://github.com/python/typeshed/blob/9abe56a19a42fd1e225a2b8d8b9ab8d830d5f1ab/stdlib/logging/__init__.pyi#L105

**Comment by AlexWaygood** [comment]
> I could also send a PR to make it more consistently a True/False bool in CPython itself.

It would be up to the `logging` maintainer to decide whether that change would be worth it. Personally, I agree that it would make the code cleaner, easier to follow, and more in line with modern Python idioms. But it could also be seen as a "cosmetic" change that doesn't have much of an impact that's visible to end users.

**Comment by sobolevn** [comment]
I also think that adding `SupportsBool` is not really worth it:
- `bool` is kinda special, everything can be converted to `__bool__` (at least I cannot remember any noticable exceptions)
- But, you can also convert objects with `__len__` to `bool` like:

  ```python
  >>> class Some:
  ...    def __len__(self):
  ...        return 0
  ... 
  >>> bool(Some())
  False
  ```
- It is easy to write, it takes just two lines of code

**Comment by pamelafox** [comment]
Ah okay, so the CPython unit tests don't go through the typeshed checks. Thank you for sharing your type wisdom, all.
I'll close this issue/associated PR.
