### ISSUE TITLE
Python Patterns - Implementing Graphs

### ISSUE THREAD

**Issue by DaveBeCoding** [python/cpython#97573]
# Documentation

I found a small issue with the follow snippet of code found on the page titled "Python Patterns - Implementing Graphs" : 

`
def find_path(graph, start, end, path=[]):
        path = path + [start]
        if start == end:
            return path
        if not graph.has_key(start):
            return None
        for node in graph[start]:
            if node not in path:
                newpath = find_path(graph, node, end, path)
                if newpath: return newpath
        return None
`

The above snippet should be changed to :

`
def find_path(graph, start, end, path=[]):
        path = path + [start]
        if start == end:
            return path
        if start not in graph: # .has_key(start) was removed in python 3 
            return None
        for node in graph[start]:
            if node not in path:
                newpath = find_path(graph, node, end, path)
                if newpath: return newpath
        return None
`

The method `.has_key()` is no longer supported by Python 3,  [Documention](https://docs.python.org/3.0/whatsnew/3.0.html#builtins).

I am a little unsure as where this is located within the repository so that I can submit a Pull Request(s) for the handful corrections needed on this page/documention for Python.org.

**Comment by vstinner** [comment]
> I found a small issue with the follow snippet of code found on the page titled "Python Patterns - Implementing Graphs"

Would you mind to provide a link to the doc?

**Comment by vstinner** [comment]
> Looks like https://www.python.org/doc/essays/graphs/

This documentation is part of https://github.com/python/pythondotorg/ project

See for example https://github.com/python/pythondotorg/issues/1452 which mentions that admins can edit them. I close the issue. Please report an issue to: https://github.com/python/pythondotorg/issues

**Comment by DaveBeCoding** [comment]
> > Looks like https://www.python.org/doc/essays/graphs/
> 
> This documentation is part of https://github.com/python/pythondotorg/ project
> 
> See for example [python/pythondotorg#1452](https://github.com/python/pythondotorg/issues/1452) which mentions that admins can edit them. I close the issue. Please report an issue to: https://github.com/python/pythondotorg/issues

Thanks for that update, and I've resubmitted the issue at https://github.com/python/pythondotorg/issues
