### ISSUE TITLE
Incorrect suggestions for os.walk() recursion modification method

### ISSUE THREAD

**Issue by AKAAkira** [python/cpython#97580]
The passage in question:

>When *topdown* is `True`, the caller can modify the *dirnames* list in-place (perhaps using [`del`](https://docs.python.org/3/reference/simple_stmts.html#del) or slice assignment), and [`walk()`](https://docs.python.org/3/library/os.html#os.walk) will only recurse into the subdirectories whose names remain in *dirnames* [...]

Neither `del` nor slice assignment on *dirnames* actually work to modify the recursion process. It seems the *dirnames* variable that's assigned the returned data from `os.walk()` is just an alias for the actual data `os.walk()` consults for its recursion, so only methods that modify the actual contents pointed to by *dirname* (i.e. `dirnames.clear()`, `dirnames.remove()`, `dirnames.sort()`) will do anything meaningful, and should be what's suggested by the docs.

(The example provided further down from the passage does correctly use `dirnames.remove()` to modify the recursion process, though.)

**Comment by pochmann** [comment]
You're probably doing the `del` or slice assignment wrong. Can't tell without seeing your code.

**Comment by AKAAkira** [comment]
An example code, then:

```
>>> import os
>>> for dpath, dnames, fnames in os.walk('./'):
...   print(dpath)
...
./
./dir1
./dir1\dir2
>>> for dpath, dnames, fnames in os.walk('./'):
...   print(dpath)
...   if 'dir2' in dnames:
...     del dnames
...
./
./dir1
./dir1\dir2
>>> for dpath, dnames, fnames in os.walk('./'):
...   print(dpath)
...   if 'dir2' in dnames:
...     dnames.remove('dir2')
...
./
./dir1
>>> for dpath, dnames, fnames in os.walk('./'):
...   print(dpath)
...   if 'dir2' in dnames:
...     dnames.clear()
...
./
./dir1
>>> for dpath, dnames, fnames in os.walk('./'):
...   print(dpath)
...   if 'dir2' in dnames:
...     dnames = dnames[1:]
...   print(dnames)
...
./
['dir1']
./dir1
[]
./dir1\dir2
[]
```

**Comment by pochmann** [comment]
The doc says "modify the dirnames list in-place". You're not doing that. That would for example be `del dirnames[0]` or `dirnames[:1] = []`.

**Comment by AKAAkira** [comment]
Ugh, my mistake then. I wasn't aware of that meaning for "in-place".

**Comment by pochmann** [comment]
I'd say at least as important there is the word "list". Your `del` and assignment don't modify the list, only your variable.
