### ISSUE TITLE
Documentation for list methods (append(), extend(), insert(), etc) found only in the tutorial

### ISSUE THREAD

**Issue by jaysridhar** [python/cpython#97593]
# Documentation

The documentation for the list methods (`append()`, `extend()`, `insert()`, etc) are found only in the tutorial. Nowhere in the reference are these found. Can we also add them into the reference? Seems strange that some methods would be documented only in the tutorial.

I can help with this issue.

**Comment by stevendaprano** [comment]
https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types

**Comment by jaysridhar** [comment]
Even then, they are all over the place. For example `index()` and `count()` are found under https://docs.python.org/3/library/stdtypes.html#common-sequence-operations. `sort()` is found under `list`: https://docs.python.org/3/library/stdtypes.html#list.sort. Do you think it would be useful to have them all in one place, in addition to wherever they are now?

**Comment by pochmann** [comment]
Note what the doc says in the [list section](https://docs.python.org/3/library/stdtypes.html#list), right above the doc for `sort` that you linked to:

> Lists implement all of the common and mutable sequence operations. Lists also provide the following additional method

"common" and "mutable" are links to those docs for the other methods. You just need to click them.
