### ISSUE TITLE
Walrus operator in f-string result in unexpected value and leading space

### ISSUE THREAD

**Issue by JPEWdev** [python/cpython#97599]
# Bug report

Using the walrus operator in a f-string results in an expected result and erroneous leading whitespace character. For example in IDLE:

```python3
a = 1
b = 2
print(repr(f"{a := b}"))
' 1'
```
The expected result from this expression is `2`, e.g. the value of `b`. Also no leading whitespace was requested in the f-string.

**Note**: Using `repr()` is not required, but makes the leading space more apparent

# Your environment

- CPython versions tested on: Python 3.8 & Python 3.10.6
- Operating system and architecture: x86_64

**Comment by saito828koki** [comment]
@JPEWdev 

Thanks for your report. I could reproduce the same bug.
For now, you can obtain the expected behavior by adding parentheses.

```
a = 1
b = 2
print(f"{(a := b)}") # "2" is printed
```

**Comment by pochmann** [comment]
I'd say if it were a bug, it wouldn't be explicitly [documented](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals):

> assignment expressions `:=` must be surrounded by explicit parentheses

**Comment by rhettinger** [comment]
I can also reproduce the effect:

```
>>> a = 1
>>> b = 2
>>> f"{a := b}"
' 1'
```

Possibly, there is an unexpected interaction between the `=` in the walrus operator and the whitespace preserving aspect of using `=` to emit an expression:

```
>>> f"{ 4 =}"
' 4 =4'
=
```

**Comment by ericvsmith** [comment]
"a := b" is interpreted as:

"a " is the expression to be evaluated.
"=" is the alignment, which means force the padding to be placed after the sign (if any) but before the digits.
" " is the sign character, which means a leading space should be used on positive numbers, and a minus sign on negative numbers
"b" is binary.

The value of the variable "b" is unused.

You can see this better with:
```python
>>> a = 10
>>> f"{a := b}"
' 1010'
```

So, this isn't a bug, it's working as designed. As noted, use parens if you want to use a walrus operator.
