### ISSUE TITLE
lib/site-packages/pathlib.py @ 3.10.7 @ Windows 10

### ISSUE THREAD

**Issue by ghost** [python/cpython#97615]
# Bug report

Line number 12 in the file `lib/site-packages/pathlib.py`, generated in my virtual environment, contains `from collections import Sequence`

But I think it should really be `from collections.abc import Sequence`

# Your environment
Fresh install of Python 3.10.7 on Windows 10.

**Comment by JelleZijlstra** [comment]
You have probably installed the third-party https://pypi.org/project/pathlib/ package. Don't; pathlib has been in the standard library for years.

**Comment by peter-jansson** [comment]
Thank you and my bad, I thought it was a fresh venv without any third-party packages which is obviously was not.
