### ISSUE TITLE
Skip tests when there's no space left on device?

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#97642]
Right now buildbots sometimes fail with something like:

```
======================================================================
ERROR: test_zipfile (test.test_multiprocessing_main_handling.SpawnCmdLineTest.test_zipfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.pablogsal-arch-x86_64/build/Lib/test/test_multiprocessing_main_handling.py", line 223, in test_zipfile
    with os_helper.temp_dir() as script_dir:
  File "/buildbot/buildarea/3.x.pablogsal-arch-x86_64/build/Lib/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/buildbot/buildarea/3.x.pablogsal-arch-x86_64/build/Lib/test/support/os_helper.py", line 467, in temp_dir
    path = tempfile.mkdtemp()
           ^^^^^^^^^^^^^^^^^^
  File "/buildbot/buildarea/3.x.pablogsal-arch-x86_64/build/Lib/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 28] No space left on device: '/tmp/tmpcuj5padp'
```

Log: https://buildbot.python.org/all/#/builders/484/builds/2129/steps/5/logs/stdio

The problem is that it creates some problems:
- It reports back to contributors: https://github.com/python/cpython/pull/95129#issuecomment-1261934943 Some people might get confused by it, clearly
- It fails the CI, so it is now red:
  <img width="905" alt="Снимок экрана 2022-09-29 в 11 29 36" src="https://user-images.githubusercontent.com/4660275/192981375-5ebd076b-68a6-4a3c-89cd-06cafd369ec9.png">

We might catch `OSError` with error code 28 on linux and just skip tests.
How does this sound to others?

If this looks like a good idea, I will send a PR.

**Comment by iritkatriel** [comment]
Shouldn’t test fail when they can’t run?

**Comment by iritkatriel** [comment]
Out of disk space/memory is not the same thing as some socket type not being available on your system.

**Comment by ericvsmith** [comment]
I agree failing tests should fail. There's too much of a chance of accidentally passing something that really was a failure.

**Comment by sobolevn** [comment]
Ok then! 👍
