### ISSUE TITLE
`mimetypes.py` uses deprecated "application/javascript"

### ISSUE THREAD

**Issue by ppena-LiveData** [python/cpython#97646]
The [_types_map_default values for JavaScript](https://github.com/python/cpython/blob/4652093e1b816b78e9a585d671a807ce66427417/Lib/mimetypes.py#L430) use the deprecated "application/javascript" value. [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239.html#name-common-javascript-media-typ) as well as http://www.iana.org/assignments/media-types (which is [referenced in mimetypes.py](https://github.com/python/cpython/blob/main/Lib/mimetypes.py#L423)) both say that type/subtype name is obsolete and should be replaced with "text/javascript".

**Comment by ambv** [comment]
Thanks for this! We're not backporting to 3.11 or 3.10 to avoid confusion. This change will land in Python 3.12.
