### ISSUE TITLE
Remove sys.getdxp() and Tools/scripts/analyze_dxp.py: superceded by Py_STATS infra

### ISSUE THREAD

**Issue by vstinner** [python/cpython#97670]
In Python 3.10/3.11, the old DYNAMIC_EXECUTION_PROFILE and DXPAIRS macros were replaced with Py_STATS macro. The sys.getdxp() function is no longer used with Tools/scripts/analyze_dxp.py. Now if Python is built with ``./configure --enable-pystats``, statistics on opcodes are written into the ``/tmp/py_stats/`` directory and these files can be analyzed with ``Tools/scripts/summarize_stats.py``.

I propose to remove sys.getdxp() and Tools/scripts/analyze_dxp.py.

**Comment by mdboom** [comment]
Cc: @markshannon

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/116fa62c6ee18e2b2ccf3697802034c0d13a16e8
