### ISSUE TITLE
datetime works a bit differently depending upon '+=' or '=+' is used

### ISSUE THREAD

**Issue by ghost** [python/cpython#97673]
**Environment**
- Python Version: 3.11.0b1 64-bit
- Operating system: Microsoft Windows 10 Home Single Language
- Build Number: 19043
- architecture: x64

The output of `python -V`
`Python 3.11.0b1`

**Bug Report**
`from datetime import date, timedelta as td`
`today = date.today()`
`today =+ td(days=1)`
`type(today)`
`<class 'datetime.timedelta'>`

As you can see above the type is 'datetime.timedelta' but as you can see below the type is 'datetime.date'

`from datetime import date, timedelta as td`
`today = date.today()`
`today += td(days=1)`
`type(today)`
`<class 'datetime.date'>`

How is this possible?

**Comment by TeamSpen210** [comment]
Though they look similar, flipping the `+` and `=` symbols around produces a totally different meaning. `a += b` is usually shorthand for `a = a + b`, except `a` is directly modified. `a =+ b` on the other hand is a regular assignment of `(+b)` - `+` can be used with a single value like you’d do `-x` to invert a number. `+` does nothing to the number though.

Your first snippet just assigns the timedelta to `today`, overwriting the existing contents. The second adds the delta to the current date, which is probably what you want.
