### ISSUE TITLE
Convert Readme.rst to Readme.md

### ISSUE THREAD

**Issue by Baahcy** [python/cpython#97705]
- Convert README.rst to README.md

**Comment by ericvsmith** [comment]
Why? I'm not necessarily opposed, but there needs to be a benefit that's a positive trade-off.

**Comment by funkyfuture** [comment]
please don't open issues just for fun, people have more important things to work on.

**Comment by stevendaprano** [comment]
What's the purpose of converting Restructured Text to Markdown? And if we did this, which of the many different flavours of markdown would we choose?

You've had 15 hours to provide a reason for this change and haven't done so, so I'm going to close the task. If you think you have a good reason for the change, please respond on this ticket, and we can reopen the task.
