### ISSUE TITLE
`rand` variable unused in `test_resource_tracker`

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#97706]
The `rand` variable is unused in `TestResourceTracker.test_resource_tracker`. In addition, `tempfile` is only used for  `rand`, so there's no need to import it.

https://github.com/python/cpython/blob/273a819ed2c927ed205ff334ea997cb62b1d20af/Lib/test/_test_multiprocessing.py#L5298

**Comment by JelleZijlstra** [comment]
Thanks for your contribution!
