### ISSUE TITLE
`asyncio.Task.print_stack` doesn't use `sys.stderr` by default

### ISSUE THREAD

**Issue by megabug** [python/cpython#97725]
`asyncio.Task.print_stack` is described by documentation as having a default output file of `sys.stderr`. However, the default `None` is passed all the way to `print` statements, leading to an actual default of `sys.stdout`.

### Linked PRs
* gh-101652
* gh-101653
* gh-101654

**Comment by arhadthedev** [comment]
Fixed by gh-101652.
