### ISSUE TITLE
Use of uninitialized pointer in Argument Clinic generated code

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#97728]
The code generated for the Py_UNICODE converter (and derived converter LPCWSTR) looks like:
```c
const Py_UNICODE *name;
...
if (!_PyArg_ParseXXX(..., name, ...)) {
    goto exit;
}
...
exit:
    PyMem_Free((void *)name);
```
If parsing fails, `PyMem_Free()` is called for uninitialized variable.

It is the only converter with non-trivial cleanup which does not have a mandatory initializer.

**Comment by serhiy-storchaka** [comment]
Seems that for now it only affects the Windows code.

I have found this bug when tried to use Argument Clinic for OS agnostic code which converts arguments to `wchar_t *` (in `getpath.c`).

**Comment by eryksun** [comment]
These needs to be fixed if `_winapi.CreateJunction()` is used as a fallback for `os.symlink()` when creating a compatibility link such as "bin -> Scripts". More here: https://github.com/python/cpython/issues/97586#issuecomment-1262604996.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/97729
