### ISSUE TITLE
.gitignore seems a bit too aggressive or make distclean isn't aggressive enough

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#97731]
# Bug report

I recently moved from Linux back to a Mac. After a bunch of `rsync` commands I started to make sure stuff worked. When I got to my cpython repo, I couldn't get `test_tools` to pass because it continued to try and find a nonexistent Conda version of Python 3.9. (That always existed on my Linux box, so the problem was masked there.) Af first, I thought it was the Conda setup on the Mac, but eventually realized that the `.../Doc/venv/binpython3` symlink was to the old Linux path. I eventually dumped `.../Doc/venv` altogether, after which everything worked as expected.

# Your environment

My old environment was Ubuntu 22.04 LTS with a miniconda installation whose base Python executable was 3.9. My new environment is a Mac M1 running Monterey with a miniconda installation also using 3.9 as its base Python interpreter. The difference in paths though (`/home/skip/miniconda3/...` vs `/Users/skip/miniconda3/...`) exposed the problem.

- CPython versions tested on:

Up-to-date CPython repo on main branch.

- Operating system and architecture:

MacOS Monterey (M1 architecture)

# Proposed solution:

While it's nice that the `.gitignore` file hides a bunch of extraneous detail, in this case I think it might have been nice if `Doc/venv` was revealed as not under Git's control. Alternately, it seems like `make distclean` should remove that directory.

Oddly enough, looking at the `docclean` target in the top-level `Makefile`, I see that it doesn't use the `clean` target in `Doc/Makefile` to do its dirty work. Nor is it used by any of the cleaner targets in that file.

```
docclean:
	-rm -rf Doc/build
	-rm -rf Doc/tools/sphinx Doc/tools/pygments Doc/tools/docutils
```

The two targets don't even clean up the same cruft. Here are the cleaner targets from `Doc/Makefile`

```
clean: clean-venv
	-rm -rf build/*

clean-venv:
	rm -rf $(VENVDIR)
```

`Doc/tools/{sphinx,pygments,docutils}` doesn' exist after executing `make -C Doc html`. I suspect the `docclean` target could simply be replaced by `make -C Doc clean`, and made a dependency of the `distclean` target.

* PR: gh-98982

* PR: gh-99024

* PR: gh-99025

**Comment by tiran** [comment]
The changeset broke out-of-tree builds. The Docs directory is in `$(srcdir)`, not in the current `$(builddir)`.

```
make -C Doc clean
make[1]: *** Doc: No such file or directory.  Stop.
make: *** [Makefile:2593: docclean] Error 2
```

**Comment by brettcannon** [comment]
On Discord there were two suggested solutions to this:

```shell
test -d Doc && $(MAKE) -C Doc clean
```

or:
```shell
make -C $(srcdir)/Doc clean
```

which is a simpler version of:
```shell
docdir=$(srcdir)/Doc
docclean:
    test -d $(docdir) && $(MAKE) -C $docdir clean
```

**Comment by brettcannon** [comment]
Another solution is you can apparently put [a `-` in front of a command which tells `Make` to ignore errors](https://www.gnu.org/software/make/manual/make.html#Errors) and continue on. This also seems to be supported by [bmake](https://linux.die.net/man/1/bmake) (see the `.IGNORE` section of the docs).

**Comment by brettcannon** [comment]
I'm using https://github.com/python/cpython/pull/98982 to try out the `$(srcdir)` solution, and if that doesn't work then I will try the `-` solution.
