### ISSUE TITLE
Non-obvious error output of f-string 

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#97734]
# Enhancement for error output of f-string 

Let's assume a f-string expression like that;
```python
f"test (|) {|} (|) test (|)"
```

This statement produces a error like that;
```python
>>> f"test (|) {|} (|) test (|)"
  File "<stdin>", line 1
    (|)
     ^
SyntaxError: f-string: invalid syntax
>>> 
```

Who reading this comment may be confused by thinking that the wrong part is in ``` test (|)```.  But the wrong part of the code is ```{|}```.

# Suggestion
If the error output is corrected in this way, the confusion will be eliminated.

```python
>>> f"test (|) {|} (|) test (|)"
  File "<stdin>", line 1
    {|}
     ^
SyntaxError: f-string: invalid syntax
>>>
```

**Comment by shivance** [comment]
Is this task free ?, I would love to take a crack at it.

**Comment by arhadthedev** [comment]
@shivance Sure. It's an open project, no assignment is required. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

**Comment by shivance** [comment]
Hey ! I'm a graduating student looking to contribute to python. Are there any project open ? Where should I get started then.

**Comment by iritkatriel** [comment]
This is out of date, on main I get this:

```
>>> f"test (|) {|} (|) test (|)"
  File "<stdin>", line 1
    f"test (|) {|} (|) test (|)"
                ^
SyntaxError: f-string: expecting a valid expression after '{'
```
