### ISSUE TITLE
Improved usability of WASM web REPL for testing/development.

### ISSUE THREAD

**Issue by katharosada** [python/cpython#97747]
# Feature or enhancement

There's a demo python WASM REPL included in cpython for development and testing purposes.

It has the following issues:
* It's currently impossible to 'stop' the python process - an infinite loop means you have to close the browser tab.
* The 'Start REPL' button can be pressed multiple times while the program is running, this does not work as expected. It queues another REPL to start as soon as the current REPL exits.
* Working in the REPL for testing is painful - especially since it's a limited REPL implementation, e.g. no up-arrow to repeat previous commands.

Example here: https://repl.ethanhs.me/

# Pitch

I propose adding the following to the REPL:
* A stop button that kills the webworker process (effectively terminating the python process)
* Disabling the start button while there is an active python process running.
* Adding a text area for python code so that code can be edited and executed multiple times. 

# Previous discussion

### Linked PRs
* gh-97665
* gh-119828

**Comment by brettcannon** [comment]
@katharosada Did you want me to leave this open to target this for WASI, or should I close this?

**Comment by hugovk** [comment]
> @katharosada Did you want me to leave this open to target this for WASI, or should I close this?

No reply in four months, let's close. We can always re-open.
