### ISSUE TITLE
Skipping of ndbm tests in test_shelve module

### ISSUE THREAD

**Issue by zuhu2195** [python/cpython#97753]
Hi, I am working on a python build in which I want to skip some test cases which are run when I call test_shelve. specifically, I want to skip test_read, test_write and test_update only for ndbm module. But as I see the whole class mapping_tests are imported in test_shleve and all of its tests are run one by one. How can I selectively skip these tests for ndbm module in test_shelve.

The following is a small part of output of regression test test_shelve

test_len (test.test_shelve.TestProto5File_ndbmShelve) ... ok
test_pop (test.test_shelve.TestProto5File_ndbmShelve) ... ok
test_popitem (test.test_shelve.TestProto5File_ndbmShelve) ... ok
test_read (test.test_shelve.TestProto5File_ndbmShelve) ...
ERROR
test_setdefault (test.test_shelve.TestProto5File_ndbmShelve) ... ok
test_update (test.test_shelve.TestProto5File_ndbmShelve) ...
ERROR
test_values (test.test_shelve.TestProto5File_ndbmShelve) ... ok
test_write (test.test_shelve.TestProto5File_ndbmShelve) ...
ERROR
test_bool (test.test_shelve.TestProto5MemShelve) ... ok

as I mentioned I want to skip only the three tests and that too that are called for ndbm case. please assist me through this. I know why the test cases are throwing errors and I don't want to fix it; I just want to skip them selectively. Please assist me in this.

Thank you.

**Comment by hauntsaninja** [comment]
You could delete the method off of the type created in test_shelve.py. discuss.python.org is probably a better place to ask this kind of question
