### ISSUE TITLE
.github/problem-matchers/sphinx.json:20: DeprecationWarning: invalid escape sequence

### ISSUE THREAD

**Issue by vstinner** [python/cpython#97767]
There is a DeprecationWarning in ``.github/problem-matchers/sphinx.json``:

```
./.github/problem-matchers/sphinx.json:20: DeprecationWarning: invalid escape sequence '\/'
  "regexp": "(\/.*\\.rst):\\s+(\\w*):\\s+(.*)$",
./.github/problem-matchers/sphinx.json
```

cc @ammaraskar @kumaraditya303

**Comment by kumaraditya303** [comment]
Does this happens on CI? Can you provide a link?

**Comment by vstinner** [comment]
More warnings:

```
./Tools/c-analyzer/c_parser/_state_machine.py:99: DeprecationWarning: invalid escape sequence '\s'
  '''
./Tools/wasm/wasm_build.py:140: DeprecationWarning: invalid escape sequence '\d'
  version_re = re.compile("^PACKAGE_VERSION='(\d\.\d+)'")
```

**Comment by vstinner** [comment]
> Does this happens on CI? Can you provide a link?

I noticed these warnings when running the old scripts Tools/scripts/pysource.py.

**Comment by vstinner** [comment]
Wait, it's a JSON file, why does this script tries to load it as a Python script? Oops, ignore the warning on sphinx.json ...
