### ISSUE TITLE
typing.Annotated should document the __metadata__ field

### ISSUE THREAD

**Issue by martindemello** [python/cpython#97797]
Both `help(typing.Annotated)` and `help(typing._AnnotatedAlias)` should document the `__metadata__` field; based on the comments in #89543 the field was meant to be public but was inadvertently omitted from the PEP and documentation.

### Linked PRs
* gh-103405
* gh-103413
* gh-105365
* gh-105448
* gh-105449

**Comment by AlexWaygood** [comment]
Now documented in the docstring and in `typing.rst`
