### ISSUE TITLE
dataclass should use inspect.get_annotations instead of examining cls.__dict__

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#97799]
`dataclass` needs to examine the annotations of class objects it decorates.  Due to `__annotations__` being badly designed, it currently pulls the `__annotations__` out of the class dict (`cls.__dict__.get('__annotations__')`).  While this works today, this wouldn't work properly for classes defiend in modules using `from __future__ import co_annotations` if PEP 649 is accepted.  It's also not recommended best practices for working with annotations.  (Which, admittedly, [I wrote.)](https://docs.python.org/3/howto/annotations.html)

Best practices call for using `inspect.get_annotations` to get the annotations on any object.  This does exactly what `dataclass` wants; it doesn't inherit base class annotations if no child class defines annotations, and it always returns a dict.  (Empty, if appropriate.)

`dataclass` has in the past resisted using `inspect.get_annotations` because it didn't want to incur the runtime cost of importing `inspect`.  However, as of this time in CPython trunk, `inspect` is always imported during startup, and `dataclass` is already importing it anyway.  It's time `dataclass` changed to best practices here.

**Comment by larryhastings** [comment]
@ericvsmith Tagging you so you see this.  Working on a PR.

**Comment by AlexWaygood** [comment]
Closing, as I think this is fixed. (Feel free to reopen if there's more still to do!)

**Comment by peku33** [comment]
Will this fix https://github.com/python/cpython/issues/83623 ?

**Comment by carljm** [comment]
> Will this fix https://github.com/python/cpython/issues/83623 ?

No. `inspect.get_annotations()` does not eval string annotations by default, and #97800 does not pass `eval_str=True`. And IMO it shouldn't, because that is likely to trigger cycles or failures to eval in currently-working code. (If you want to discuss that any further, please direct it to #83623, not here.)

**Comment by ericvsmith** [comment]
I agree with @carljm. In addition, I don't think there should be changes made to how dataclasses uses annotations until PEP 649 is implemented.
