### ISSUE TITLE
Unnecessary if-else block in `mutliprocessing.spawn`

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#97818]
The same code is executed regardless of whether `sys.platform` is `win32` or not.

https://github.com/python/cpython/blob/06016845dcca1d444a6db6d70ce9fe6274d551d3/Lib/multiprocessing/spawn.py#L36-L41

**Comment by eryksun** [comment]
No, it's not the same code. On Windows, a pathlike argument is returned as `str` by `fsdecode()`, which decodes using the filesystem encoding if needed. On POSIX, a pathlike argument is returned as `bytes` by `fsencode()`, which encodes using the filesystem encoding if needed.

**Comment by saito828koki** [comment]
@eryksun 
Thanks for your reply! I misunderstood this block. The PR should be closed. Thank you!
