### ISSUE TITLE
Unused variables in `mutliprocessing.managers.Server`

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#97816]
The following 3 variables `obj`, `exposed` and `gettypeid` are declared but not used. We can delete this line.
https://github.com/python/cpython/blob/72b5a55bc80676d57e492520d39aaf3fb6f186df/Lib/multiprocessing/managers.py#L436

**Comment by gpshead** [comment]
odd, perhaps an old line for extra debugging? anyways obviously unnecessary. thanks!
