### ISSUE TITLE
Typing annotations are not documented in the language reference

### ISSUE THREAD

**Issue by pitrou** [python/cpython#97829]
# Documentation

The only place where the syntax for typing annotations seems to be documented is the [grammar specification](https://docs.python.org/3.12/reference/grammar.html), which is obviously not very user-friendly. And in even there, the "TYPE_COMMENT" token does not seem explained.

(yes, there are the PEPs, which is not much better either)

**Comment by Fidget-Spinner** [comment]
I thought `TYPE_COMMENT` is supposed to be an internal implementation detail? I don't think we should document it.

CC @pablogsal .

**Comment by pitrou** [comment]
Perhaps? That said, this feature request is not really about TYPE_COMMENT but the fact that type annotations are not documented _at all_ in an approachable yet comprehensive manner.

**Comment by hauntsaninja** [comment]
Note that the `TYPE_COMMENT` token isn't used for PEP 526 / PEP 3107 type annotations. It's used for the `ast.parse(..., type_comments=True)` feature which allows `ast.parse` to recognise `# type: ...` comments and `# type: ignore`

**Comment by hauntsaninja** [comment]
For documenting annotations more generally, I'm curious what you have in mind.

> The only place where the syntax for typing annotations seems to be documented is the grammar specification

Note that there is some documentation of annotations in the language reference, as part of the documentation of "Function definitions" and of "Annotated assignment statements".

**Comment by pitrou** [comment]
@hauntsaninja Hmm, I had missed that, thank you. That said, it's still merely an annotated (!) copy of the syntax specification...

**Comment by JelleZijlstra** [comment]
This is now documented, e.g. there is a paragraph about annotations in https://docs.python.org/3/reference/compound_stmts.html#function-definitions, a section on AnnAssign was linked above, I added various new documentation for PEP 649.
