### ISSUE TITLE
documentation for `http.server` refers to wrong `test()` function

### ISSUE THREAD

**Issue by yedpodtrzitko** [python/cpython#97822]
# Documentation

the following paragraph in docs for `http.server` mentions function `test`: 

https://github.com/python/cpython/blob/e3b6ff19aaa318a813130ba9ad2ab0a332f27feb/Doc/library/http.server.rst#L395-L396

which is a reference to function `test` in the same file:

https://github.com/python/cpython/blob/9a95fa9267590c6cc66f215cd9808905fda1ee25/Lib/http/server.py#L1239

[but in the rendered docs](https://docs.python.org/3/library/http.server.html#http.server.SimpleHTTPRequestHandler.do_GET) ```:func:`test` ``` is resolved as a link to https://docs.python.org/3/library/test.html#module-test instead of the aforementioned function in the same file.

**Comment by orsenthil** [comment]
Could open a pull request to fix this?

**Comment by yedpodtrzitko** [comment]
sure, I just dont know what's the recommended way how to refer to a specific function in the code - do I use link with the latest commit or is it preferred some other way?

**Comment by davidism** [comment]
List the full path to the name, it will be a link with the text `http.server.test`:

```rst
For example, see the implementation of the :func:`http.server.test` function.
```

Alternatively, add a `~` at the front, and it will remain in the current format, showing only the `test` name.

```rst
For example, see the implementation of the :func:`~http.server.test` function in the :mod:`http.server` module. 
```

**Comment by hauntsaninja** [comment]
Looks like this is fixed and all backports are merged. Thank you!
