### ISSUE TITLE
strftime error output

### ISSUE THREAD

**Issue by ricoeo** [python/cpython#97843]
I am dealing with a time series data, with timestamp as index. While dealing with the index, I find this error.
![image](https://user-images.githubusercontent.com/36293694/193919686-04915f95-884b-4ba9-90a7-f5ead8c6b264.png)
This is my datetransfer function:
from datetime import datetime
def datetransfer(time):
    return datetime.fromtimestamp(time).strftime("%A, %B %d, %Y %H:%M:%S")
There is a missing in 2:00:00 but it is so obvious the adjacent time data only differ in 1 hour. 

Another similar problem happens in 
![image](https://user-images.githubusercontent.com/36293694/193931594-3b8c3c82-3e02-4399-b553-a46718b5341f.png)

**Comment by ericvsmith** [comment]
Is this a daylight savings time issue?

**Comment by zware** [comment]
This looks suspiciously like a DST transition.  `datetime.fromtimestamp` is [documented](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) to convert to the local time and return a naive `datetime` object.

**Comment by ricoeo** [comment]
> This looks suspiciously like a DST transition. `datetime.fromtimestamp` is [documented](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) to convert to the local time and return a naive `datetime` object.

Yeah I want to convert it to local time because I need to find a complete natural week data(from Monday to Sunday).

**Comment by ricoeo** [comment]
> Is this a daylight savings time issue?

OHHH. thanks I think this is a reasonable explanation.

**Comment by zware** [comment]
Did 02:00 on March 29, 2020 exist in your timezone?

**Comment by ricoeo** [comment]
> Did 02:00 on March 29, 2020 exist in your timezone?

Thanks for your help. I think this is just as @ericvsmith  said. I found out when I try to group by the same date and there are some duplicates.
