### ISSUE TITLE
Add missing text/rtf to mimetypes

### ISSUE THREAD

**Issue by amaddio** [python/cpython#97901]
# Feature or enhancement

As of Python 3.10, the types map does not contain an entry for the valid mime type of `text/rtf`. It only contains a `application/rtf` entry for non standard types. The missing `text/rtf` mapping should be added as this is a valid mime type. For example this file type is guessed by the `file` command (e.g. version 5.04; see [libmagic1](https://www.darwinsys.com/file/)). My temporary workaround is to add the mapping manually: 
```python
mimetypes.add_type("text/rtf", ".rtf", strict=False)
```
I would dare to add it to the list of standard types, but to be consistend with the other `rtf` mapping I'd add it to the non standard (`strict=False`) list.

# Pitch

The feature is implemented in a pull request pointing to this issue. I simply adds one one line with the mapping. Other python lovers could take advantage of this functional mapping of a valid mime type to an extension.

### Linked PRs
* gh-97902

**Comment by amaddio** [comment]
Note regarding IANA Requirement: the type is registered: http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by nanjekyejoannah** [comment]
Makes sense to me.
