### ISSUE TITLE
Docs for some C struct members repeat the struct name

### ISSUE THREAD

**Issue by encukou** [python/cpython#97908]
The members of [PyType_Spec](https://docs.python.org/3/c-api/type.html?highlight=pytype_spec#c.PyType_Spec.PyType_Spec.name) are documented as e.g. `PyType_Spec.PyType_Spec.name`:
![image](https://user-images.githubusercontent.com/302922/194091887-2c3311c6-0c37-4b4d-b313-182ec577b388.png)
This makes it cumbersome to link to them.
Fixing this will probably break URLs.

### Linked PRs
* gh-100054
* gh-105057

**Comment by CAM-Gerlach** [comment]
To note, in that issue the fragments visible to external links will change, unless we add ref target labels with the old name (which will generate anchors for them).

**Comment by encukou** [comment]
`:ref:` targets will not work, since Sphinx rewrites them (converts dots to dashes &c.)
I cant's see a better way to add old fragments than `raw:: html`. I guess this *is* HTML-specific, or at least hypertext-specific.

**Comment by hauntsaninja** [comment]
Looks like this was completed, thanks!
