### ISSUE TITLE
Mention "assignment expressions" and/or walrus in genindex-all

### ISSUE THREAD

**Issue by Mariatta** [python/cpython#97913]
# Documentation

Initially reported in docs mailing list by Denilson Sá Maia

https://mail.python.org/archives/list/docs@python.org/thread/NZTUNIYEZVY2WOF3GH6TAZ32OLMKR3QO/

## Indexing the walrus operator

_If you look at the main index: https://docs.python.org/3.10/genindex-all.html_

_You can find most operators, but you can't find the walrus operator._
_Try Ctrl+F and search for "walrus", ":=", "named expression",_
_"assignment expression", "assignment"→"expression". You can't find_
_them anywhere in the index._

_Sure, you can find them at the main search page:_
_https://docs.python.org/3.10/search.html?q=walrus_

_Again, a minor issue, but still worth fixing._

_And since I know the walrus operator is new, I wonder if any of the_
_newer sections of the documentation could also suffer from the same_
_issue._

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/97921.

I added:

* := (colon equals)
* assignment expression
* walrus operator
