### ISSUE TITLE
Refresh importlib.resources

### ISSUE THREAD

**Issue by jaraco** [python/cpython#97930]
This bug tracks the sync with importlib_resources 5.x ([history](https://importlib-resources.readthedocs.io/en/latest/history.html)) into Python 3.12. For now, 5.9, but probably some other releases soon.

- [x] 5.9 (#97929)
- [x] 5.10 (#100598)
- [x] 5.12 (#102010)

### Linked PRs
* gh-100598
* gh-102010
* gh-102030

**Comment by hauntsaninja** [comment]
Looks like both 5.9 and 5.10 have been synchronised
