### ISSUE TITLE
PyFunction_GetAnnotations is probably causing ref leaks

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#97943]
In issue #30409 `PyFunction_GetAnnotations` was fixed so it wouldn't return a tuple.  That's good.

But this change changed the return value.  `PyFunction_GetAnnotations` now returns a *new* reference to the annotations dict.  But according to the documentation, it should return a *borrowed* reference.

    https://docs.python.org/3/c-api/function.html#c.PyFunction_GetAnnotations

If users only read the documentation, and assume that it's correct, they'll leak a reference to the annotation dict.

We could fix this by changing the documentation.  However, all the other `PyFunction_Get*` functions *also* return borrowed references.  So I think the correct fix is to remove the incref.

**Comment by larryhastings** [comment]
IDK how to tag people, so I'll just do it in a comment:

@pablogsal  @methane

**Comment by larryhastings** [comment]
Also, I consider this enough of a bug fix that it should be backported to versions still getting bug fixes.

**Comment by ericvsmith** [comment]
I agree that changing back to a borrowed reference to the current version and backporting that behavior it is correct. Many more people would read the documentation and assume it's correct than would read the source code and know that it's a new reference that they need to manage.

**Comment by larryhastings** [comment]
I didn't do a full forensic analysis, but I think what happened here is:

- func_get_annotations (the getter/setter) returns a fresh reference.
- func_get_annotations was changed to call this code that says "oh! if it's a tuple, turn it into a dict."  this function returns a new reference.
- PyFunction_GetAnnotations wasn't changed, it was returning the dict.
- the bug fix was, "oh! just have it call the same function to turn it from a tuple into a dict."  but this function returns a new reference, and PyFunction_GetAnnotations shouldn't return a new reference.

**Comment by hauntsaninja** [comment]
Thanks for spotting, looks like it's been fixed and backported
