### ISSUE TITLE
Migrate `zoneinfo` to argument clinic

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#97955]
# Feature or enhancement

Migrate `_zoneinfo.c` to argument clinic.

It is proposed by @vstinner and @pganssle 
Link: https://github.com/python/cpython/pull/19909#discussion_r425272501

# Pitch

This will improve several things:
1. `help()` on `ZoneInfo` methods. Here's how it looks now:

```
>>> help(zoneinfo.ZoneInfo.clear_cache)
Help on built-in function clear_cache:

clear_cache(...) method of builtins.type instance
    Clear the ZoneInfo cache.
```

2. Add `__text_signature__` property to methods, it is very useful: for example, `python/typeshed` uses it to be sure that stubs and implementation match
3. Move all argument parsing to clinic, which is more convenient

# Previous discussion

1. https://github.com/python/cpython/issues/84683
2. https://github.com/python/cpython/pull/19909
3. https://github.com/python/cpython/pull/19909#discussion_r425272501

I will send a PR for this today :)

**Comment by ambv** [comment]
Thanks, Nikita! ✨ 🍰 ✨
