### ISSUE TITLE
uname_result _asdict and _fields are missing platform

### ISSUE THREAD

**Issue by jaraco** [python/cpython#97966]
Not sure if this should be a new issue, but [`platform.uname` docs for 3.12][1] still say:

> ... Returns a [namedtuple()](https://docs.python.org/3.12/library/collections.html#collections.namedtuple) containing **six attributes**: [system](https://docs.python.org/3.12/library/platform.html#platform.system), [node](https://docs.python.org/3.12/library/platform.html#platform.node), [release](https://docs.python.org/3.12/library/platform.html#platform.release), [version](https://docs.python.org/3.12/library/platform.html#platform.version), [machine](https://docs.python.org/3.12/library/platform.html#platform.machine), and [**processor**](https://docs.python.org/3.12/library/platform.html#platform.processor).

(my emphasis)

I've got python 3.10.6 installed, which returns 5 attributes, not including `processor`, as expected from the discussion above:

```
uname_result(
    system='Linux', 
    node='MyName', 
    release='5.15.0-48-generic', 
    version='#54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022', 
    machine='x86_64'
)
```

[1]: https://docs.python.org/3.12/library/platform.html#platform.uname

_Originally posted by @dennisvang in https://github.com/python/cpython/issues/84750#issuecomment-1270085689_
      

### Linked PRs
* gh-99793
* gh-99794

**Comment by dennisvang** [comment]
> It's only in the `repr` that the `platform` isn't presented.
> 
> All six attributes are present.
> 
> I can tweak the docs to make this clearer, but is there an issue you encountered as a result?

@jaraco Thanks for converting my comment to an issue,

You're right, `len(platform.uname())` is indeed `6`.

To be more precise, my issue acually arises from the use of [`_fields`][2] and [`_asdict()`][1] on the return value ([uname_result][3]):

```python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
>>> import platform
>>> len(platform.uname()._fields)
5
>>> len(platform.uname()._asdict())
5
```

[1]: https://docs.python.org/3.10/library/collections.html#collections.somenamedtuple._asdict
[2]: https://docs.python.org/3.10/library/collections.html#collections.somenamedtuple._fields
[3]: https://github.com/python/cpython/blob/11945f2cf6ae4aeb8202f481e8881ec0fbfabe89/Lib/platform.py#L767

**Comment by kwsp** [comment]
The documentation said the return type is a `namedtuple`, but in reality the returned type `uname_result` is a hacked `namedtuple` that prevents unnecessary computation of the `platform` property. It tries to emulate a `namedtuple`, but doesn't support all documented methods on a `namedtuple`.

I think the way to fix this is to either edit the documentation of `platform.uname()` to specify these caveats, or completely emulate [all documented methods of a `namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) on the `uname_result`. The second option seems hard to maintain, and is prone to bugs in the future, so I vote editing the documentation of `platform.uname()`

**Comment by jaraco** [comment]
I agree. Specifying the caveats is probably better.

Another option might be to deprecate the (named)tuple behaviors altogether, which I proposed in https://github.com/python/cpython/issues/84758, but which was rejected.

If we follow the guidance from @malemburg in that issue, it would suggest to fully emulate the `namedtuple` for unrelenting backward compatibility. Probably the implementation should support `_fields` and `_asdict` for compatibility with old versions.

**Comment by kwsp** [comment]
Re emulating `namedtuple`'s behavior: we go through all this trouble just to avoid computing `platform` when we call `uname`? I looked at git blame and traced this back to https://bugs.python.org/issue35967, but I still don't understand the significance of a late bound computation of `platform`. Since we can cache that property so all subsequent calls to `uname` are free, how bad would it be if we just compute `platform` on the first call to `uname`?

**Comment by jaraco** [comment]
The problem is a race condition / circular dependency on Linux/Mac:

- A project (e.g. [cmdix](/jaraco/cmdix) wishes to implement the `uname` command in Python.
- When that package is installed for testing, it exposes `uname` on the path.
- When running tests, another library, `pkg_resources` calls `platform.uname()` to check installed packages and evaluate environment markers (though it doesn't use the processor attribute).
- `platform.uname()` will create a subprocess to the `uname -p` command to get the processor eagerly.
- Because `uname` is now implemented by the project, it is invoked for the subprocess, and its own entry point will import `pkg_resources` and thus invoke `platform.uname()`, recursing to the prior step.

Furthermore, this infinite loop is implemented in a subprocess loop, so it's not caught by the max recursion depth, so will consume resources on the user's machine until it runs out of some resource (memory, file descriptors, ...).

All of this happens before `cmdix` code is ever reached (even the script handler is written by setuptools), so there's nothing `cmdix` can do to bypass the undesirable behavior.

You can reproduce this behavior by checking out cmdix and attempting to run the tests on Python 3.8 or earlier. Just run `tox -e py38` on Linux or Mac in a checkout of the project. It will appear to hang while it creates a giant tree of recursive subprocess calls.

Other ways I've considered to address the issue include:

- Don't use subprocess to resolve the processor, but instead invoke APIs directly. Unfortunately, the APIs that `uname -p` uses are subtle and vary across platforms and distributions. Maintaining compatibility without shelling out to `uname -p` would be difficult if not intractable.
- pkg_resources could write its own port of `uname` that doesn't shell out to any processes. This approach would fix the proximate cause but not the root cause, and the root cause could potentially get triggered by another code path, suggesting that no library should use `platform.uname` if they can't guarantee that `uname -p` is safe to call.
