### ISSUE TITLE
Code C API docs should be strong reference not new reference

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#97980]
These new functions were added in 3.11.

In 3.10 and earlier, accessing the attributes via Python these functions would return a strong reference that was shared, not a brand new reference. So we should relax the terminology and just say strong reference in the docs (to also allow further optimisations in the future).

Continuing from https://github.com/python/cpython/issues/94936.

**Comment by ronaldoussoren** [comment]
Isn't "New Reference" used throughout the documentation for functions returning a ``PyObject*`` that the caller should DECREF? For example see [the documentation for ``PyObject_GetAttr``](https://docs.python.org/3/c-api/object.html#c.PyObject_GetAttr).

**Comment by Fidget-Spinner** [comment]
I'm making the terminology consistent with `PyCode_GetCode`.
