### ISSUE TITLE
List slicing does not obey modular arithmetic

### ISSUE THREAD

**Issue by mauler2025** [python/cpython#97988]
Adding 10 to the index or subtracting  10 from index should produce the same result.
However, I found that this modular arithmetic is not obeyed for `lst[9:-1:-1]`.

```python
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(lst[-1:-11:-1])  # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
print(lst[9:-11:-1])   # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
print(lst[9:-1:-1])     # []
```

**Comment by ronaldoussoren** [comment]
Why do you think this is a bug? There is no modular arithmetic involved in indexing.

``list[9:-1:-1]`` steps backwards from the 9th to the "-1"-th (e.g. last) elements of the list. That's an empty range because indexes ``9`` and ``-1`` refer to the same element of ``lst``. 

``list[9:-11:-1]`` and ``list[-1:-11:-1]`` return the entire list reversed because they steps backwards from the last to the first element (inclusive).

**Comment by pstricks-fans** [comment]
> `list[9:-1:-1]` steps backwards from the 9th to the "-1"-th (e.g. last) elements of the list. That's an empty range because indexes `9`and `-1` refer to the same element of `lst`.


If I use the same logic,

 `list[9:-11:-1]` steps backwards from the 9th to the "-11"-th (e.g. last) elements of the list. That should also be an empty range because indexes `9`and `-11` refer to the same element of `lst`. However, it returns the entire elements reversed.

**Comment by ronaldoussoren** [comment]
> `list[9:-11:-1]` steps backwards from the 9th to the "-11"-th (e.g. last) elements of the list. That should also be an empty range because indexes `9`and `-11` refer to the same element of `lst`. However, it returns the entire elements reversed.

``9`` and ``-11`` to not refer to the same element of list, ``9`` refers to the last element while ``-11`` refers to an item before the start of the list.  List indexes do *not* wrap around.

**Comment by eryksun** [comment]
When a slice is applied to a sequence, a negative start or stop index is normalized by adding the length of the sequence to the value. For the range of valid indices -- i.e. `[-length, length - 1]` -- the result happens to be equivalent to modulo in the length (i.e. negative index values are wrapped around to equivalent non-negative values). Obviously that's not the case for values that are outside the latter range. Instead, a slice gets bound according to the step direction and sequence length. If the step is positive, the lower bound is 0 and the upper bound is the length. If the step is negative, the lower bound is -1, and the upper bound is the length minus 1.

**Comment by sweeneyde** [comment]
I agree, this is not a bug. Each sequence item has exactly two indices: in `"Python"`:

* `P` has index 0 and -6
* `y` has index 1 and -5
* `t` has index 2 and -4
* `h` has index 3 and -3
* `o` has index 4 and -2
* `n` has index 5 and -1

Any indices other than that are out of range, but as mentioned in [the tutorial](https://docs.python.org/3.11/tutorial/introduction.html#strings),

> [...] out of range slice indexes are handled gracefully when used for slicing:
>
> ```
> >>> word = 'Python'
> ```
>
> ```
> >>> word[4:42]
> 'on'
> >>> word[42:]
> ''
> ```
