### ISSUE TITLE
Unify `PyUncode_Count` and `unicode_count`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#97982]
# Feature or enhancement

Right now `PyUnicode_Count` from https://github.com/python/cpython/blob/cbdeda8ce7a3543cb3376d70e4cd46fcf24f42a7/Objects/unicodeobject.c#L8968-L9040 and `unicode_count` from https://github.com/python/cpython/blob/cbdeda8ce7a3543cb3376d70e4cd46fcf24f42a7/Objects/unicodeobject.c#L10854-L10916 share a lot of code.

They can be unified, because the do the same thing.

# Pitch

[Citing](https://github.com/python/cpython/pull/96929#issuecomment-1270262538) @encukou:

> Apparently unicode_count missed [an optimization in 2011](https://github.com/python/cpython/commit/c3cec7868bf1019c0987f1e9aadb56d73fa93d61), otherwise they're equivalent (except arg parsing & converting the return value). Merging them could add the optimization to unicode_count.
If you want to work on that, note that there's also anylib_count that duplicates the main switch.

# Previous discussion

Link: https://github.com/python/cpython/pull/96929

PR in the works.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/ccab67ba7901a3012ad66f0ffafac4ea925a1ff0
