### ISSUE TITLE
Unused arguments in `urllib.request`

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#98016]
While checking if #96873 is a bug, I have noticed that there are some unused arguments in methods.
We can delete these args.

`data` is not used in `OpenerDirector._open`

https://github.com/python/cpython/blob/13d44891426e0faf165f974f2e46907ab5b645a9/Lib/urllib/request.py#L528-L541

`type` is not used in `ProxyHandler.proxy_open`
https://github.com/python/cpython/blob/13d44891426e0faf165f974f2e46907ab5b645a9/Lib/urllib/request.py#L805-L831

**Comment by sobolevn** [comment]
> We can delete these args.

This is a breaking change. Some code out there is probably using the old form.

**Comment by JelleZijlstra** [comment]
Agree with @sobolevn, this is probably not worth changing.

**Comment by saito828koki** [comment]
Thanks for your comments!
I totally agree with @sobolevn . This issue should be closed now.
