### ISSUE TITLE
Change default child watcher to `PidfdChildWatcher` on supported Linux versions

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#98023]
`PidfdChildWatcher` based on [pidfd_open](https://www.man7.org/linux/man-pages//man2/pidfd_open.2.html) is the best child watcher implementation for Linux as it avoids race conditions and is most reliable of all of them. It requires  Linux 5.3+ so this will be detected at runtime if it can be used and if so use this instead of `ThreadedChildWatcher`. `asyncio` will favor using `PidfdChildWatcher` over `ThreadedChildWatcher` in 3.12+ on systems which supports it.

**Comment by gvanrossum** [comment]
Thanks!

There's a little bit of possible cleanup -- the check whether `os.pidfd_open()` exists and works (`can_use_pidfd()`) is duplicated in Lib/test/test_asyncio/test_subprocess.py (as `_has_pidfd_support`). While `can_use_pidfd()` is not a documented or public API I think it's better to call it from the test code so there's only one copy to update if the check ever changes.
