### ISSUE TITLE
Improve the Descriptor HowTo Guide

### ISSUE THREAD

**Issue by geryogam** [python/cpython#98038]
# Documentation

PR https://github.com/python/cpython/pull/24901 provides the following changes to the [*Descriptor HowTo Guide*](https://docs.python.org/3/howto/descriptor.html):

- fix a typo;
- fix a Sphinx tag preventing syntax highlighting;
- fix a bug in `ClassMethod`;
- reuse an existing `cls` name in `Object`;
- allow keyword arguments in `Type.__new__` and `Object.__new__`;
- allow attribute lookup from a class in `Member.__get__`;
- use two more `super()` in `Object` and `Type` for consistency.

**Comment by rhettinger** [comment]
I added the Skip Issue tag to the PR.  So we can close this issue and leave the PR discussion in one place.
