### ISSUE TITLE
socket: add missing TCP socket options from Linux

### ISSUE THREAD

**Issue by matttbe** [python/cpython#98030]
# Feature or enhancement

`socket` modules already know most TCP socket options (`TCP_NODELAY`, `TCP_MAXSEG`, `TCP_CORK`, etc.) but not the recent ones.

Here is the complete list from the last Linux kernel version:
https://elixir.bootlin.com/linux/v6.0/source/include/uapi/linux/tcp.h#L91

# Pitch

I noticed `TCP_FASTOPEN_CONNECT` was missing. I wanted to use it to write some quick tests for the kernel (MPTCP development). I was going to add only this one but while at it, best to add all the missing ones.

### Linked PRs
* gh-98031

**Comment by gpshead** [comment]
thanks!
