### ISSUE TITLE
Remove more deprecated importlib APIs from Python 3.12

### ISSUE THREAD

**Issue by warsaw** [python/cpython#98040]
Issue #97850 is the meta issue tracking removals of long deprecated functions from importlib.  This ticket tracks just the removals of the following previously deprecated APIs:

- [x] `find_loader()`
- [x] `find_module()`
- [x] `imp` module
- [x] `importlib.abc.Finder`
- [x] `pkgutil.ImpImporter`
- [x] `pkgutil.ImpLoader`

+ @brettcannon @ericsnowcurrently 

### Linked PRs
* gh-98573
* gh-102561
* gh-98059
* gh-104131
* gh-105743
* gh-105754

**Comment by warsaw** [comment]
Questions:

* What about `imp.NullImporter`?  [The docs say](https://docs.python.org/3.11/library/imp.html?highlight=nullimporter#imp.NullImporter) it's been deprecated since 3.4 and it only implements `find_module()` so I am going to remove the entire class.

**Comment by warsaw** [comment]
`pkgutil.ImpImporter` cannot be removed since [pip 22.2.2 still uses it](https://github.com/pypa/pip/issues/11501)

**Comment by hugovk** [comment]
Little reminder: we're a month away from the beta freeze to remove these, or to bump removal to 3.13.

**Comment by warsaw** [comment]
My plan is to complete this work at the 2023 PyCon sprints.

**Comment by warsaw** [comment]
Since the `imp` module was finally removed, I'm going to close this issue.  Please refer back to the #97850 as the meta issue for cleaning up the import system cruft.

**Comment by encukou** [comment]
“Perhaps you need the imp's services for just a little longer?” a voice asks as a piece of parchment is pressed in your hand. The incantation, done in ornate reddish lettering, is invitingly simple: `pip install zombie-imp`.
You should probably burn it.

**Comment by vstinner** [comment]
Can you please mention it in What's New In Python 3.12?

**Comment by encukou** [comment]
No, it's not supported and there are no guarantees about it.
If we agree, as the CPython devs, that `imp` is still used/useful, then let's put it back in stdlib.
