### ISSUE TITLE
Redundant call to call_soon_threasafe when using PidfdChildWatcher 

### ISSUE THREAD

**Issue by graingert** [python/cpython#98057]
It would be better to move the responsibility to the child watchers for calling callbacks on the event loop thread. Currently the callback needs to defensively call `call_soon_threadsafe` which is redundant on the Pidfdchildwatcher

Eg https://github.com/python/cpython/blob/282edd7b2a74c4dfe1bfe3c5b1d30f9c21d554d6/Lib/asyncio/unix_events.py#L225-L227

_Originally posted by @graingert in https://github.com/python/cpython/issues/94597#issuecomment-1272068837_

**Comment by graingert** [comment]
This will probably need to wait for deprecation of the child watcher system

**Comment by gvanrossum** [comment]
Yeah, I notied this too when @1st1 and I were reviewing the watcher code this morning. Not sure we need to keep an issue open to remind us of this though.

**Comment by kumaraditya303** [comment]
I doubt anything can be done for this until the entire child watcher system is removed and is harmless.

**Comment by kumaraditya303** [comment]
Will take care of it in 3.14 when removing child watchers, no need for an issue for it, I am already working on it.
