### ISSUE TITLE
dataclasses documentation does not mention weakref_slot

### ISSUE THREAD

**Issue by ericvsmith** [python/cpython#98077]
When `weakref_slot` was added to `@dataclass` it was not documented.

**Comment by achhina** [comment]
I see that the `weakref_slot` parameter and a description was added in the [dataclass](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) docs by yourself. Would you have liked to see something more?

**Comment by ericvsmith** [comment]
@achhina : Thanks for the reminder. I'm going to close this, as the task is complete.
