### ISSUE TITLE
Improved documentation for exec() closure parameter

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#98117]
I like the `closure` argument to exec() and eval() added to 3.11.
But, ... I have some complaints about it as it stands at present.

> The closure argument specifies a closure–a tuple of cellvars. It’s only valid when the object is a code object containing free variables. The length of the tuple must exactly match the number of free variables referenced by the code object.

**Which** free variables??  In the exec() code, or in the frame where exec() is called from?

Where do I get or make cellvars?

In what order do the cellvars go?

Without answering these questions, the new feature will be useless to a programmer.

The answers, as well as I can figure out, are:

- The whole business only applies if exec() is executing a code object compiled from a _target_ which is function or lambda.
- EDIT: The purpose of the feature is to allow the executed code to assign or delete a free variable (which must be declared nonlocal), or get the value of a free variable.
- This code object is in _target_.__code__.
- The names of the free variables are in _target_.code.co_freevars.
- The appropriate closure argument is in _target_.__closure__.  This has the cellvars corresponding to the free variables named in _target_.code.co_freevars, and in the same order.
- You can also use a different closure from a different target, provided it was compiled in the same scope, and contains the same variable names (even if they appear in a different order)
- The order in which free variable names appear is fixed in the enclosing scope, so different targets will have their free variable names in the same order.
- If the code binds, rebinds, or deletes one of the free variables (which must be declared as nonlocal in the code), that change will show up in that variable in the calling scope.
- There is no way in Python to create a cellvar other than the above.  In the future, if some means is provided to create a cellvar for a free variable, then that cellvar will be tied to that variable in the scope in which it was created.

# Suggested enhancement:

1. I propose a new builtin function called **closure()**.  This will return a dict of cellvars for _all_ free variables in the current scope.  The same dict can be used by exec() with different code objects compiled in the scope.  
2. closure() may be called as closure(names, [name, ]...), which will return a dict for just those variables (which must be free variables in the current scope).
3. exec() will _also_ accept a closure argument which is a dict of variable names to cellvar objects.  This _may_ include names which are _not_ free variables in the code object being executed, but it must include _all_ names which _are_ free variables.  Any stores or deletes performed in the executed code will show up in the cellvar values.  If they reflect the actual free variables in the scope, the changes will show up in the variables in the calling scope.

4. **Why not provide a closure to eval() also?**  eval() can already evaluate an expression with free variables.  However, eval() of an assignment expression doesn't work as expected.  The assignment is made in the locals dict given to eval().  Passing a closure would allow the assignment to be made to a free variable.

5. Provide methods on cellvar objects to bind, rebind, or delete the cell_contents _in-place_.  This will be visible in the free variable which the cellvar corresponds to.  This would be more convenient than performing the corresponding exec().

**Comment by eryksun** [comment]
> The purpose of the feature is to allow the executed code to assign or delete a free variable.

It could be used just to reference the value, without modifying it. Here's a silly example:

```pycon
>>> f = (lambda x: lambda: print(x))('spam')
>>> f()
spam
>>> exec(f.__code__, closure=(types.CellType('eggs'),))
eggs
```
 
> The appropriate closure argument is in _target_.**closure**.  This has the cellvars corresponding to the free variables named in _target_.code.co_freevars, and in the same order.

To me, the phrase "tuple of cellvars" in the docs and docstring seems like lazy language. The `__closure__` attribute of a function is defined as "a tuple of cells that contain bindings for the function's free variables". A cell object is anonymous data, and as such it is not a variable. However, a cell variable or free variable is backed by a cell object instead of the frame's stack, and, in the normal case, each cell can be traced back to a cell variable (i.e. cellvar) in the call stack. 

> There is no way in Python to create a cellvar other than the above.

What do you mean by "create a cellvar"? Since 3.8, a cell object can be created via [`types.CellType`](https://docs.python.org/3/library/types.html#types.CellType).

> I propose a new builtin function called **closure()**.  This will return a dict of cellvars for _all_ free variables in the current scope.  The same dict can be used by exec() with different code objects compiled in the scope.

You mean that `closure()` will return a name-cell mapping that contains all of the cell variables and free variables in the current scope, not just the free variables, right? What are some uses cases for executing a code object as if it had been defined in the current lexical scope?

> Provide methods on cellvar objects to bind, rebind, or delete the cell_contents _in-place_.  This will be visible in the free variable which the cellvar corresponds to.

The `cell_contents` attribute is already mutable. For example:

```python
def f():
    x = 'spam'
    cell = (lambda: x).__closure__[0]
    cell.cell_contents = 'eggs'
    print(x)
    del cell.cell_contents
    try:
        x
    except NameError:
        print('x is not defined')
```
```pycon
>>> f()
eggs
x is not defined
```

**Comment by larryhastings** [comment]
Your complaints seem to be about the documentation, or requests for additional functionality you'd like to see.  But you haven't described any bugs yet.  So describing the argument as "broken", and applying the "type-bug" label, both seem inappropriate.

**Comment by mrolle45** [comment]
> > The purpose of the feature is to allow the executed code to assign or delete a free variable.
> 
> It could be used just to reference the value, without modifying it.
> 
> > The appropriate closure argument is in _target_.**closure**.  This has the cellvars corresponding to the free variables named in _target_.code.co_freevars, and in the same order.
> 
> To me, the phrase "tuple of cellvars" in the docs and docstring seems like lazy language. The `__closure__` attribute of a function is defined as "a tuple of cells that contain bindings for the function's free variables". A cell object is anonymous data, and as such it is not a variable. However, a cell variable or free variable is backed by a cell object instead of the frame's stack, and, in the normal case, each cell can be traced back to a cell variable (i.e. cellvar) in the call stack.
> 
> > There is no way in Python to create a cellvar other than the above.
> 
> What do you mean by "create a cellvar"? Since 3.8, a cell object can be created via [`types.CellType`](https://docs.python.org/3/library/types.html#types.CellType).
> 
> > I propose a new builtin function called **closure()**.  This will return a dict of cellvars for _all_ free variables in the current scope.  The same dict can be used by exec() with different code objects compiled in the scope.
> 
> You mean that `closure()` will return a name-cell mapping that contains all of the cell variables and free variables in the current scope, not just the free variables, right? What are some uses cases for executing a code object as if it had been defined in the current lexical scope?
> 
> > Provide methods on cellvar objects to bind, rebind, or delete the cell_contents _in-place_.  This will be visible in the free variable which the cellvar corresponds to.
> 
> The `cell_contents` attribute is already mutable. For example:
> 
> ```python
> def f():
>     x = 'spam'
>     cell = (lambda: x).__closure__[0]
>     cell.cell_contents = 'eggs'
>     print(x)
>     del cell.cell_contents
>     try:
>         x
>     except NameError:
>         print('x is not defined')
> ```
> 
> ```
> >>> f()
> eggs
> x is not defined
> ```

**Comment by ncoghlan** [comment]
Functional suggestions were posted in #100068

Additional docs suggestions were posted in #98176

I've retitled this issue to be specifically about improving the docs for exec's closure parameter.
