### ISSUE TITLE
collections.defaultdict violates the object.__getitem__ contract.

### ISSUE THREAD

**Issue by fischbacher** [python/cpython#98128]
# Documentation

Right here:

https://docs.python.org/3.10/reference/datamodel.html#object.__getitem__

the contract for `object.__getitem__` states two things that will be subsequently relevant: 

(1) `__getitem__` implements the `self[key]` lexical-index-lookup operator.

(2)  So, for any object that has a `__getitem__` method, this must raise a `KeyError` instance on a missing-key-lookup.

The `collections.abc` documentation specifies:

  - A `collections.abc.Mapping` subclass must provide `__getitem__` 
   (cf. https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes)
  - Standard library Mappings include `dict` and `defaultdict`
    (cf. https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping 
    plus https://docs.python.org/3/glossary.html#term-mapping)

So, it logically follows that both `dict` and `defaultdict` must have a `__getitem__` method, which must be in alignment with the `object.__getitem__` contract (everything else would violate the Liskov Substitution Principle).

However, the `dict` contract is written to allow behavior in violation of the `object.__getitem__` contract.

While instances of `dict` that are not subclass instances do not violate the `object.__getitem__` contract directly,
the `dict` contract allows subclass instances to behaviorally violate that contract - and `collections.defaultdict` instances indeed do that -  in fact, the very design idea of `collections.defaultdict` is to violate the `object.__getitem__` contract.

The problem seems to be that the wording of `object.__getitem__` should refer to `object.__missing__`.

**Comment by ericvsmith** [comment]
I don't think the documentation would be improved by mentioning this. Has this caused some actual confusion?

I guess you could throw in the word "generally", or some other weasel word, but again I don't think that's an improvement.

**Comment by TeamSpen210** [comment]
Another way to look at it is that `defaultdict` doesn't actually violate the contract - if the key is missing, it's silently created before `__getitem__` returns, so it's no longer actually missing by that point. If the caller's relying on the lack of an exception, everything will work as expected for a mapping from then on.

**Comment by pochmann** [comment]
> must raise a `KeyError`

That's not true. What it **actually** says:

> "KeyError should be raised"

So then you read [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) again and see:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

And I'd say `defaultdict` does have a very valid reason.

**Comment by rhettinger** [comment]
I disagree about discussing `__missing__` in a general description of `__getitem__`.  The `__missing__` method is a dictionary specific concept, so it is appropriate that it is covered in more detail [here](https://docs.python.org/3/library/stdtypes.html#dict).

Note that the class `object` doesn't have a `__getitem__` method.  Perhaps confusingly, the data model docs refer to `object.__getitem__` but it really is just a way to talk about the dunder method in general rather than as an actual method for an instance of `object()`.  IIRC there is an existing PR that will change the entry to `someinstance.__getitem__` or somesuch.

With respect to subclasses and ABCs, ISTM that you're reading too much into "the contract".  The Liskov substitution principle is a principle, not a law.  Subclasses can and do change their parent's rules.  Usually the constructor is different and often at least one of the principal behaviors is different.  These differences are on purpose and are necessary for the subclass to do something useful.

Think of LSP as a gray scale.  The more a subclass behaves likes its parent, the more substitutable it is.  However, to do something useful (as defaultdict does), it can choose a different behavior — just like a Counter is a kind of dictionary that returns zero instead of raising KeyError for a missing key. 

I'm going to close this because there isn't a bug here.  Instead the issue seems to be that you have a stronger notion of LSP and contracts than the language actually has (practicality beats purity) and that you have a difference of opinion about where `__missing__` is documented.

**Comment by fischbacher** [comment]
*Sigh*

Violations of the Liskov Substitution Principle are in the "I found a sharp metal part in my food" category of design bugs.

The problem is that this can easily cause very sinister action-at-a-distance bugs that are extremely hard to track down: Someone changes something in one place, and all of a sudden, code starts to misbehave in a very different place.

I can recommend this article that nicely explains it: https://okmij.org/ftp/Computation/Subtyping/

So, really, if a class contract specifies "this is how instances of this class must behave",then this must apply to all instances, and subclasses are not allowed to break that contract - it is always valid to regard a subclass instance as a base class instance.

Really, violating this principle is opening a Pandora's box of problems. Believe me - you do not want that.

Concerning the interpretation of "should" - does the Python reference documentation actually state anywhere that it follows RFC 2119 conventions?

**Comment by pochmann** [comment]
> does the Python reference documentation actually state anywhere that it follows RFC 2119 conventions?

I don't know. But like I said it's commonly used, for example apparently [in six PEPs](https://www.google.com/search?q=site%3Apeps.python.org+rfc+2119). Even my hobby, solving Rubik's Cubes, uses RFC 2119 in the competition regulations. And "must" and "should" have different meanings in English already, and the RFC in my understanding reflects those meanings. They're not equivalent, and claiming a "must" when it's only a "should" is misleading.

Or does the Python reference documentation actually state anywhere that "should" means "must"?

**Comment by fischbacher** [comment]
> > must raise a `KeyError`
> 
> That's not true. What it _actually_ says:
> 
> > `KeyError` should be raised
> 
> Now have a look at the commonly used [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt):
> 
> > SHOULD   This word, or the adjective "RECOMMENDED", mean that there
> > may exist valid reasons in particular circumstances to ignore a
> > particular item, but the full implications must be understood and
> > carefully weighed before choosing a different course.
> 
> And I'd say `defaultdict` does have a very valid reason.

Here's why I disagree with "defaultdict does have a very valid reason".

First, let's note that neither is frozenset a subclass of set, nor vice-versa:

 >>> issubclass(frozenset, set)
 False
 >>> issubclass(set, frozenset)
 False

This makes perfect sence, since the set-contract includes "must have an .add() method that will mutate the object", and the frozenset-contract includes "must be hashable, and - in alignment with expectations about that - hence immutable".

So, *if* we want to have something with the semantics of defaultdict, one option would have been to make this a collections.abc.MutableMapping that does not inherit from dict - paralleling the design of frozenset/set.

Now, let's consider an example: suppose some callable's documentation states that "this returns a list of mappings".
It should be valid for the caller to then conclude that all elements of that list do satisfy the contract of a mapping - and use that property when writing their code.

Suppose for a moment that "this returns a list of mappings" would merely imply "this returns a list of elements, each of which would identify a mapping if we asked them, but only those that feel like it may actually behave the way it is expected of a mapping".

A fundamental principle of any engineering is that solutions are built from components, and synthesis works because these components come with clearly documented properties that the engineer can rely on. This is a ubiquitous principle that holds as much for rebar specifications as it does for analog electronics components, for concrete, and just about everything that engineering works with. So, the claim that one could take a more relaxed approach for software engineering basically translates as "this framework" (here, Python) is fundamentally unsuitable for engineering".

I'm not sure this is a position that Python wants to be in.

**Comment by ericvsmith** [comment]
Again: has this caused any actual problem in a real situation?

And if you think python’s approach here makes it unsuitable for your use cases, I’d suggest not using it.

**Comment by fischbacher** [comment]
Yes, this is causing problems.

"My use cases" are: I'm one of the people running the Python readability program at Google.
If I report a bug here, the underlying situation is that the issue has surfaced in an internal code review.

I hope you understand if I cannot be too specific about our internal code.

**Comment by fischbacher** [comment]
But, addendum to the above "should defaultdict not subclass dict and be an independent MutableMapping" approach - this would of course discuss a hypothetical design approach where the `mapping` contract would allow missing-key-lookup to not raise KeyError.

**Comment by pochmann** [comment]
You're still arguing as if it said "must" instead of "should". It does allow missing-key-lookup to not raise KeyError.

The *entire point* of defaultdict is to provide a default for missing values, and defaultdict is useful. That makes it a very valid reason to do that.
