### ISSUE TITLE
Allow shutil copytree to not modify existing files

### ISSUE THREAD

**Issue by eroeum** [python/cpython#98125]
# Feature or enhancement

Add an argument to `shutil.copytree` to not modify files that are already existing.  In its current implementation, any files in the destination that are already existing will be overwritten with the contents from the source destination, which is not always desirable.  The new argument will specify the argument to not write over existing files.

# Pitch

A `no-clobber` argument should be added to `shutil.copytree`.  From `cp` man documentation:

```
-n, --no-clobber
    do not overwrite an existing file (overrides a previous -i option)
```

For a single file, `shutil` can accomplish this by simply doing:

```python
if os.path.isfile(dst):
    shutil.copyfile(...)
```

When copying a whole tree, the `copytree` function basically needs to be rewritten to add this functionality.

The need for this functionality, for example, can be when we want to copy a bunch of files from a source to an already copied tree with some modifications and we only want to copy the new files over without modifying the other files.

**Comment by kwsp** [comment]
Can you please add a test for this? I imaging you'd also need to document this flag in the docs.

**Comment by encukou** [comment]
GitHub issues aren't a good place to suggest new features. We aren't likely to accept a feature like this: it seems that it doesn't serve a common use case, and keeping it supported and tested isn't free.

If you want to propose a feature, please discuss on [Discourse](https://discuss.python.org/c/6) first (as mentioned in the issue template you filled in here).

---

> When copying a whole tree, the copytree function basically needs to be rewritten to add this functionality.

I don't think that's correct. You can use a `ignore` callable. Or you can use a `copy_function` that wraps `copy2`, which would let you do things like compare modification times or even merge contents.

That's best discussed on Discourse though. I will close the issue now; please follow up there if there's more to say.
