### ISSUE TITLE
Compiling Cpython 3.8.X with shared libffi fails

### ISSUE THREAD

**Issue by cubanpit** [python/cpython#98145]
# Bug report

Compiling CPython on Windows with shared libffi fails because of redefinition of some symbols (see https://github.com/conan-io/conan-center-index/pull/13279).
This [recent commit](https://github.com/python/cpython/commit/38f331d4656394ae0f425568e26790ace778e076#diff-6f6b7f83e2fb49775efdfa41b4aa4f8fadcf71f43c4f3bcf9f37743acafd3fdf) seems to address the problem in the next release, but it is not going to be backported. 
Is it worth to open a PR to backport a fix?

I tried to compile CPython 3.8.12 and the linked PR to the Conan project shows plenty of information.

The error message with my setup is:
```
malloc_closure.obj : error LNK2005: ffi_closure_alloc already defined in libffi.lib(libffi.dll) [C:\Users\anonpath\source_subfolder\PCbui
ld\_ctypes.vcxproj]
malloc_closure.obj : error LNK2005: ffi_closure_free already defined in libffi.lib(libffi.dll) [C:\Users\anonpath\source_subfolder\PCbuil
d\_ctypes.vcxproj]
C:\Users\anonapath\source_subfolder\PCbuild\amd64\_ctypes.pyd : fatal error LNK1169: one or more multiply defined symbols found [C:\Users\
anonpath\source_subfolder\PCbuild\_ctypes.vcxproj]
```

**Comment by gpshead** [comment]
The change you'd want to backport came from https://github.com/python/cpython/pull/29791.  I agree with Christian on the cited issue on not wanting to backport that to 3.10 (which will only receive non-security fixes for a few more weeks).
