### ISSUE TITLE
Migrate Tools/xxbench script into pyperformance project

### ISSUE THREAD

**Issue by corona10** [python/cpython#98152]
We have several benchmark scripts under `Tools` directory.
I would like to port those scripts under `pyperformance` project by using `pyperf` tool and remove them from the CPython repository.
The reason needs this port is that moving those scripts into `pyperformance` project and monitoring the measurement with other benchmarks results would be beneficial. 

- [ ] [stringbench](https://github.com/python/cpython/tree/f4c03484da59049eb62a9bf7777b963e2267d187/Tools/stringbench) -> bm_stringbench
- [ ] [iobench](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Tools/iobench/iobench.py) -> bm_iobench
- [ ] [importbench](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Tools/importbench/importbench.py) -> bm_importbench
- [ ] [ccbench](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Tools/ccbench/ccbench.py) -> bm_ccbench

There might be objections to this proposal, please let me know if the script should be managed by CPython repository directly.

cc @ericsnowcurrently @vstinner @gvanrossum @mdboom

**Comment by arhadthedev** [comment]
A duplicate of gh-97680.

**Comment by corona10** [comment]
Oh thanks I didn't notice that.
