### ISSUE TITLE
Segmentation fault calling `PyUnicode_Concat` from `ctypes.pythonapi`

### ISSUE THREAD

**Issue by gnufede** [python/cpython#98153]
# Crash report

A segmentation fault occurs while calling `PyUnicode_Concat` from `ctypes.pythonapi`
```
from ctypes import pythonapi
pythonapi.PyUnicode_Concat("a", "b")
```

# Error messages
segmentation fault  python3.10

# Your environment
- CPython versions tested on: CPython 3.8, CPython 3.9, CPython 3.10 
- Operating system and architecture: Ubuntu Linux x86_64, Darwin arm64

**Comment by JelleZijlstra** [comment]
It's very easy to segfault things using ctypes. I believe you are expected to wrap objects in `ctypes.py_object`:

```
In [4]: pythonapi.PyUnicode_Concat(py_object("a"), py_object("b"))
Out[4]: 487402800
```

**Comment by eryksun** [comment]
`ctypes.pythonapi` isn't prototyped, so arguments are passed using the default conversion from Python types to C types, and the default result type is a C `int`. Python `str` is passed as C `wchar_t *`. 

It works fine if you actually define the [prototype](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Concat):

```pycon
>>> pythonapi.PyUnicode_Concat.argtypes = (ctypes.py_object, ctypes.py_object)
>>> pythonapi.PyUnicode_Concat.restype = ctypes.py_object
>>> pythonapi.PyUnicode_Concat("a", "b")
'ab'
```
