### ISSUE TITLE
tkinter documentation uses man page instead of main page

### ISSUE THREAD

**Issue by JosephKemper** [python/cpython#98198]
# Documentation

(A clear and concise description of the issue.)

On the page https://docs.python.org/3/library/tkinter.html is 15 separate instances of the use of the phrase "man page" instead of "main page"

**Comment by JelleZijlstra** [comment]
That's intentional. `man` pages are documentation accessed using the Unix `man` command. For example:

```
% man tk | head
tk(n)                         Tk Built-In Commands                         tk(n)



________________________________________________________________________________

NAME
       tk - Manipulate Tk internal state

SYNOPSIS
```

**Comment by zware** [comment]
The documentation is referring to the [manual pages](https://en.wikipedia.org/wiki/Man_page) for [Tcl/Tk](http://tcl.tk/man/tcl8.6.11/).  "Main page" would be incorrect.

**Comment by JosephKemper** [comment]
Sorry, I misunderstood what they were trying to say.
