### ISSUE TITLE
3.10.7 - MinGW on Windows makefile error

### ISSUE THREAD

**Issue by manhnt9** [python/cpython#98211]
# Bug report
After configuring Python source code (3.10.7) and running make, the error appears:
`mingw32-make: *** No rule to make target 'Modules/Setup.config', needed by 'Makefile'.  Stop.`

# Your environment

- Operating system and architecture: Windows 10 x64
- Compiler: GCC 10.3.0

**Comment by manhnt9** [comment]
I also tested with 3.10.8, same error.

**Comment by dg0yt** [comment]
Note #89701.

**Comment by manhnt9** [comment]
Thanks @dg0yt. I can be the maintainer for this matter but currently very new to building Python from source.
Could you or someone help me understand about `'Modules/Setup.config'` ?

**Comment by Fidget-Spinner** [comment]
@manhnt9 the maintainer for MinGW support needs to be a Python core developer. We also need the steering council to approve it, Please see PEP 11 https://peps.python.org/pep-0011/

**Comment by ericvsmith** [comment]
Per #89701, I'm closing this as a duplicate.

Our general stance on non-supported platforms is that we will accept patches if they're not too invasive. So while I'm closing this, if someone wants to submit a patch it might be accepted.

**Comment by manhnt9** [comment]
Solved, posting here for reference: https://github.com/msys2-contrib/cpython-mingw/issues/103

**Comment by dg0yt** [comment]
> Solved, posting here for reference: [msys2-contrib#103](https://github.com/msys2-contrib/cpython-mingw/issues/103)

I don't think it is solved. AFAIU https://github.com/msys2-contrib/cpython-mingw is to maintain the patches which are needed to build python for msys2/mingw:
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python

**Comment by manhnt9** [comment]
It's quite different. MinGW build script fetches original python source (this repo archive) and apply patches.
The way they generate patches is to look at `cpython-mingw` repo, compare and generate.

Solved means:
- This repo won't support MinGW build soon
- I just use `cpython-mingw` directly

There won't be 100+ patches needed in the build script.
