### ISSUE TITLE
Add a daemon parameter to threading.Timer

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#98230]
# Feature or enhancement

Adding Thread's `daemon` parameter to Timer's constructor

# Pitch

Timer is already a subclass of Thread, and inherits the `daemon` property's behavior.
Here is an example of what works and what doesn't.
```py
t = Thread(..., daemon=True)

t = Thread(...)
t.daemon = True

t = Timer(...)
t.daemon = True

t = Timer(..., daemon=True) # that one doesn't work
```

# Previous discussion

https://discuss.python.org/t/add-daemon-kwarg-to-threading-timer/19932

**Comment by gpshead** [comment]
We may not want to do this as it could encourage more daemon threads... daemon threads in general are often considered to be a mistake at this point.

**Comment by Gouvernathor** [comment]
I'm not sure that's a decision to make on the designer side. Either there's a technical difficulty and we're talking about deprecating it, or we keep it the user's business and add at best a warning in the doc.
I mean, the feature is there already, it's just more annoying to enable because the constructor doesn't cooperate.

**Comment by erlend-aasland** [comment]
The proposal did not get any support, neither on Discourse nor here on the bug tracker. Closing it as not planned.

Thanks for you interest in improving CPython!
