### ISSUE TITLE
Bug: `pprint` module print dict object in wrong key sequence

### ISSUE THREAD

**Issue by znsoooo** [python/cpython#98232]
# Bug report

```python
>>> from pprint import pprint
>>> pprint({3: 1, 2: 2, 1: 3})
{1: 3, 2: 2, 3: 1}
>>> print({3: 1, 2: 2, 1: 3})
{3: 1, 2: 2, 1: 3}
```

In very old Python versions, dictionary keys were not in order. However, PY36 already has a built-in ordered dictionary. Maybe this feature have not be updated to the `pprint` module, resulting in different results between `pprint` and `print`.

This is not important in PY34, because the dictionary in PY34 is unordered. However, in Python > 3.6, print out by `pprint` and copy text to the code, maybe cause an error.

# Your environment

- CPython versions tested on: Python 3.12.0a0
- Operating system and architecture: [MSC v.1916 64 bit (AMD64)] on win32

**Comment by pochmann** [comment]
The documentation says *"dictionaries will be formatted with their keys sorted"*, which it does, so what's wrong?

**Comment by znsoooo** [comment]
@pochmann Thank you very much.
