### ISSUE TITLE
`inspect.getmro()` fails with `AttributeError` for `typing.Annotated`

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#98233]
# Bug report
A typehint `Annotated[T, x]` *should* be interpreted as its type `T` if not specially handled (see [typing documentation](https://docs.python.org/3.11/library/typing.html#typing.Annotated)).
However, `inspect.getmro()` fails on `Annotated[T, x]`, while it succeeds on `T`:
```
import inspect
import typing

print(inspect.getmro(int))
# works and outputs (<class 'int'>, <class 'object'>)

AnnotatedInt = typing.Annotated[int, 'annotation']
print(inspect.getmro(AnnotatedInt))
# fails with AttributeError: __mro__
```
I think this is incorrect, and that any remediation more likely should be (generically) in `typing.Annotated` than (as special case) in `inspect.getmro()`.

# Your environment
This fails on all Python version that support `Annotated`: 3.9-3.11. Tested with 3.9.13, 3.10.4, 3.11.0rc2 on Windows 11.

## Linked PRs
- #98234

**Comment by sobolevn** [comment]
On the second thought: `inspect.getmro(AnnotatedInt)` is used directly. Maybe the intention is to get the real `Annotated` mro?

It looks the same as `__name__` and `__qualname__` getters:

```python
>>> AnnotatedInt.__name__
'Annotated'
>>> AnnotatedInt.__qualname__
'Annotated'
```

What about `__class__`?

```
>>> AnnotatedInt.__class__
<class 'typing._AnnotatedAlias'>
```

Why `__mro__` should be different?

So, it should be `1.` :)

**Comment by AlexWaygood** [comment]
> So, it should be `1.` :)

`inspect.getmro()` generally fails when called on _instances_ of classes rather than the class objects themselves, however:

```pycon
>>> import inspect
>>> inspect.getmro(int)
(<class 'int'>, <class 'object'>)
>>> inspect.getmro(1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/B79F943B-69E2-4D28-9297-30042C2480F8/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 455, in getmro
    return cls.__mro__
AttributeError: 'int' object has no attribute '__mro__'
```

And `Annotated[int]` is an _instance_ of the class `typing._AnnotatedAlias`, rather than the class object itself. So, if we're saying `inspect.getmro(Annotated[int])` should be treated differently to `inspect.getmro(int)`, then perhaps it is "correct" (or at least consistent) that `inspect.getmro` should fail here?

**Comment by sobolevn** [comment]
`Annotated[int]` is kinda both: 
- It is kinda `int`
- It an instance of `_AnnotatedAlias`

I've made a demo to show what I mean in https://github.com/python/cpython/issues/98233#issuecomment-1277198811
Link: https://github.com/python/cpython/pull/98234

But, I can say honestly, that I don't quite understand all the details here.

**Comment by Dutcho** [comment]
Thanks for the quick follow-up.
Indeed my use case was *not* for typing, but rather for value validation, i.e. a dual-use parameter annotation indicating type (`int`) *and* value predicate (written as `'annotation'` in my minimal example, and as `ValueRange(...)` in PEP 593). In understand the typing/runtime clash and will work around with `get_args`:
```
import inspect
import typing

AnnotatedInt = typing.Annotated[int, 'annotation']
for typ in int, AnnotatedInt:
    print(typ, inspect.getmro(typing.get_args(typ)[0] if typing.get_origin(typ) is typing.Annotated else typ))
    # works and outputs (<class 'int'>, <class 'object'>) for both cases
```
