### ISSUE TITLE
Updating documentation for path lib.Path.rename

### ISSUE THREAD

**Issue by mateka** [python/cpython#98240]
Would it be possible to update documentation of [Path.rename method](https://docs.python.org/3.8/library/pathlib.html?highlight=pathlib#pathlib.Path.rename) to mention, that it is equivalent of [os.rename](https://docs.python.org/3.8/library/os.html#os.rename)? Sometimes it is important, that Posix ensures that renames are atomic on the same filesystem.

### Linked PRs
* gh-101414
* gh-101415

**Comment by hauntsaninja** [comment]
Should this be backported?

**Comment by mateka** [comment]
I have not checked the code in other versions. If it is true, it would be nice to have.
