### ISSUE TITLE
venv does not respect `PYTHONDONTWRITEBYTECODE` setting

### ISSUE THREAD

**Issue by zooba** [python/cpython#98251]
When [we invoke pip](https://github.com/python/cpython/blob/main/Lib/venv/__init__.py#L347), we use `-I` to avoid interference from other variables. However, this also means that we ignore legitimate user preferences that ought to be retained. We probably want `PYTHONDONTWRITEBYTECODE`, `PYTHONUTF8`, `PYTHONIOENCODING`, `PYTHONMALLOC`, `PYTHONCOERCECLOCALE`, `PYTHONPYCACHEPREFIX` at least, and maybe more (I just went through the help output of 3.10).

Interestingly, we don't use isolated mode later on when we upgrade the packages, so maybe we don't need it at all? Or perhaps we should be in some middle ground where we override `PYTHONPATH` and `PYTHONHOME` to point at the venv/be empty but leave everything else in place?

Ping @vsajip 

(Discovered in a system where attempting to write .pyc files would break.)

**Comment by vsajip** [comment]
> so maybe we don't need it [`python -I`] at all?

Perhaps not - IIUC the `python -Im ensurepip` was added by @ncoghlan originally, and I don't know what the logic was for the decision to use `-I`. From my perspective, a venv should only change the active `sys.path` (so overriding `PYTHONHOME` and `PYTHONPATH` seems necessary) but I can't see any reason not to respect the other `PYTHON*` environment variables.
