### ISSUE TITLE
`Enum.__str__` change could be improved in What's New

### ISSUE THREAD

**Issue by mdboom** [python/cpython#98250]
https://github.com/python/cpython/pull/30582 (in 3.11) introduced a [change](https://github.com/python/cpython/pull/30582/files#diff-007214cd4321f2b3600c085a1b9abe8c6f05662421ff232fb42ee77dafc85920L49) to `Enum.__str__` so that it shows the enum name and the member name, whereas prior it only included the member name.

This could be a breaking change in some cases. As an example in real world code, the Azure CLI uses enums for the acceptable values of command-line flags, and then uses `str` on the enum to generate the string that is passed to the subprocess as arguments.

For example, this [enum](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/custom.py#L643) is used to define a "compute model":

```
class ComputeModelType(str, Enum):

    provisioned = "Provisioned"
    serverless = "Serverless"
```

And then it's used [here to construct arguments for a subprocess](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py#L857):

```
self.cmd('sql db update -g {} --server {} --name {} --compute-model {}'
                 .format(resource_group, server, database_name, compute_model_serverless),
```

The changelog entry for this change just says:

```
IntEnum / IntFlag / StrEnum fixes: these now inherit from ReprEnum so the str() output now matches format() output, which is the data types’ (so both str(AnIntEnum.ONE) and format(AnIntEnum.ONE) is equal to '1').
```

This is unlikely to be easily findable for users running into this change, since `StrEnum` doesn't exist in Python 3.10, and it's a little obscure.  I would suggest:

> The default str() of an Enum has changed to include both Enum name and the member name (`Enum.MEMBER`), whereas before it was just the member name.  To continue to use the old behavior, inherit from `IntEnum` or `StrEnum`.

Does this make sense? Are there other cases I'm missing? Happy to file a PR, but thought I would get some discussion first.

**Comment by ethanfurman** [comment]
I'm more than happy to have help crafting a better What's New entry.  Keep in mind that the change you are talking about is `format`, not `str` -- `str()` output hasn't changed, `format()` has changed to match `str()`.

**Comment by CAM-Gerlach** [comment]
Hey, I didn't see this before I first submitted #98295, but I'd noticed something similar, and I've revised that PR to further resolve this issue.
