### ISSUE TITLE
Removing pathlib.Path.link_to() in python 3.12 is a breaking change which is a violation of semver. 

### ISSUE THREAD

**Issue by brunoais** [python/cpython#98264]
# Bug report

Using python 3 where this is valid (e.g. Python 3.8):
```
from pathlib import Path
Path('destination').link_to('source')
```
It doesn't work in python 3.12 anymore.
I agree it should be deprecated at this point but the removal should be in python 4, not in python 3.
In my case, it will break some production code of my employer which started using `link_to` as soon as it became available in a python stable version (python 3.9).

Because this is breaking change on a minor version, without any security requirements, I consider that a bug.

# Your environment
Python 3.8
Linux x64

**Comment by JelleZijlstra** [comment]
Python does not follow semver; our general policy is that features can be removed after they have been deprecated in two feature releases (e.g.,  3.10 and 3.11). See PEP 387 for the policy.

In this case, it appears that  `link_to` was deprecated in 3.10, which makes it eligible to be removed in 3.12 (https://docs.python.org/3.10/library/pathlib.html#pathlib.Path.link_to).

**Comment by brunoais** [comment]
What's the official recommendation on how to make code that code work in python 3.8 and 3.12 at the same time, then.

**Comment by JelleZijlstra** [comment]
Something like:

```
if sys.version_info >= (3, 10):
    my_path.hardlink_to(target)
else:
    target.link_to(my_path)
```
