### ISSUE TITLE
TypeError for undefined `abstractmethod` does not highlight the undefined method name  

### ISSUE THREAD

**Issue by kaushikcfd** [python/cpython#98284]
# Feature or enhancement

Currently, on instantiating a type with an undefined abstract property named "name" we get the following error message:
```
TypeError: Can't instantiate abstract class IndexNode with abstract method name
```

The name could be confused as a part of the sentence itself. It must be highlighted, most likely by surrounding the method names with single-quotes

# Pitch

Could be implemented via a nondisruptive patch that would edit just the error message in `Objects/typeobject.c` 

# Previous discussion

A reference implementation was discussed at https://github.com/python/cpython/pull/97971.

* PR: gh-97971

**Comment by Blueee46** [comment]
Hıı

**Comment by JelleZijlstra** [comment]
Thanks for your contribution!
