### ISSUE TITLE
Document new 3.11 enum APIs (ReprEnum, global_* and/or show_flag_values)

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/cpython#98298]
As discovered in #98295 , there are several undocumented new APIs in the `enum` module:

* `ReprEnum` and is documented in [What's New](https://docs.python.org/3.11/whatsnew/3.11.html#enum) (and exported in `__all__`), but not anywhere in the [enum library module documentation](https://docs.python.org/3.11/library/enum.html#enum.StrEnum), which seems like an oversight.
* Likewise, `global_enum` is documented in What's New (and exported in `__all__`) and was previously documented in the library docs, but that documentation was reverted in #30637 , and not restored, so I'm unsure on the current status.
* `global_str`, `global_enum_repr` and `global_flag_repr` were added (to replace the `__str__()` and `__repr__()` of the appropriate classes) and are not marked as private (`_`) and are exported by `__all__`, but aren't documented either. Should they be?
* `show_flag_values` was added and is not in `__all__`, but its use is referred to in an error message (cited in the docs) and it is not marked private (`_`). Should this be documented as well?

@ethanfurman your guidance here would be much appreciated, thanks. I'm happy to review/copyedit a PR, or if you prefer, I can draft something and you review it. Ideally, we should get this in before the 3.11 release in a week or so...

Related: #95913 

### Linked PRs
* gh-103163
* gh-103227

**Comment by ethanfurman** [comment]
Working on something now.  I presume I commit to main and backport to 3.11?

**Comment by CAM-Gerlach** [comment]
> I presume I commit to main and backport to 3.11?

Yup :+1:

**Comment by CAM-Gerlach** [comment]
Hey @ethanfurman , are we all done here?

**Comment by ethanfurman** [comment]
@CAM-Gerlach I tihnk so.

**Comment by Bktero** [comment]
Hi!

In[the documentation](https://docs.python.org/3/library/enum.html), we can read (3.11.1) :

> @enum.global_enum
> A decorator to change the [str()](https://docs.python.org/3/library/stdtypes.html#str) and [repr()](https://docs.python.org/3/library/functions.html#repr) of an enum to show its members as belonging to the module instead of its class

It is not said that members of the enum are also added to the global namespace. Example:

```python
from enum import global_enum, Enum

@global_enum
class Foo(Enum):
    BAR = 1

print(BAR) # the documentation doesn't tell that this is possible
```

Is this behavior a bug? Or is there something missing in the documentation?

**Comment by ethanfurman** [comment]
The behavior is intended, the docs need updating.

**Comment by Bktero** [comment]
I have been testing the almost all the new `enum` features yesterday, and I have other points for improving the documentation.

Should I create a new issue or is there an existing issue I can contribute to?

**Comment by ethanfurman** [comment]
Yes, you can link PRs to this issue.  Thanks!

**Comment by ethanfurman** [comment]
@Bktero Closing this issue.  When you have more doc updates, please open a new issue.  :smile:
