### ISSUE TITLE
Logging: SysLogHandler.createSocket added in 3.11 but not documented

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/cpython#98307]
Part of #95913 

A `createSocket()` method was added to the  [SysLogHandler](https://docs.python.org/3.11/library/logging.handlers.html#logging.handlers.SysLogHandler) class for issue #88457 by PR #26490 to match the [one in SocketHandler](https://docs.python.org/3.11/library/logging.handlers.html#logging.handlers.SocketHandler.createSocket), but unlike the latter, the former was not documented (and also not mentioned in What's New).

@vsajip , shouldn't this be documented? If so, do you think you could help draft something describing its semantics and usage (I can help do the final writeup, but its not entirely clear to me what the precise intended behavior is, since it doesn't seem too similar internally to the other documented function, and there is no docstring). Thanks!

**Comment by CAM-Gerlach** [comment]
Also, I noticed [logging.getLevelNamesMapping](https://docs.python.org/3.11/library/logging.html#logging.getLevelNamesMapping) was added as well, but not mentioned in What's New. Seems like at least a brief note/reference would be worth adding, too (which I could easily do on my own as part of or separate from this, as its already documented).

**Comment by vsajip** [comment]
> Also, I noticed [logging.getLevelNamesMapping](https://docs.python.org/3.11/library/logging.html#logging.getLevelNamesMapping) was added as welll, but not mentioned in What's New ... which I could easily do on my own as part of or separate from this

I'd say please do it separately, as it's unrelated to the socket creation part of the issue.

**Comment by CAM-Gerlach** [comment]
Thanks for the quick response!

Sure; the main reason I didn't just do it separately to begin with was the PRs would conflict (at least as far as the What's New is concerned), but I just added the two What's New entries to the same PR, leaving your PR to document `createSocket` as a separate one (which makes a lot more sense anyway).

See #98320 for that.
