### ISSUE TITLE
IDLE 3.10.8 fails to open in Windows 10

### ISSUE THREAD

**Issue by anoban** [python/cpython#98310]
I've upgraded to the most recent version of Python 3.10.8 yesterday and the IDLE didn't seem to work. I've tried reinstalling and repairing my installation. (I'm using the standard cpython implementation downloaded from https://www.python.org). (I did check the checkbox to install IDLE during the customized installation).
I've even tried to run the idle.bat file manually (located at C:\Program Files\Python310\Lib\idlelib\) but no use. IDLE failed to open when I clicked the start menu icon and the batch file. Then I reverted back to 3.10.7 version without manually deleting the install directory. (So, the libraries installed with python 3.10.8 were still there on my machine). 
With python 3.10.7 IDLE works just fine. May be some of you could look into this. Thank you.
PS. I'm totally fine using python 3.10.7 but there seems to be an issue in IDLE with 3.10.8 on Windows 10, so I just thought of letting you guys know.

In case you need system specs:
Dell Inspiron-3501
11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
16.0 GB (15.7 GB usable)
64-bit operating system, x64-based processor
Windows 10 Home Single Language
21H2 Build 19044.2130

**Comment by terryjreedy** [comment]
Duplicate.  See https://github.com/python/cpython/issues/98324#issuecomment-1279990057 for explanation and fix - either edit a file or install test package.
