### ISSUE TITLE
Missing email notifications from Python Insider blog

### ISSUE THREAD

**Issue by pewscorner** [python/cpython#98328]
# Bug report

Maybe half a year or more ago I stopped getting emails for new Python releases in the Python Insider blog (blog.python.org). Nothing in my spam folder. Resubscribing with the same email address throws up an error stating that I'm already subscribed. Unsubscribing doesn't seem to be possible (maybe possible from within the emails I'm not getting). A couple of months ago I tried subscribing with a different email address, but still no emails. 

Any ideas?

# Your environment

Gmail.

**Comment by sobolevn** [comment]
Hi, @pewscorner! Please, report this issue to https://github.com/python/pythondotorg

This is for bugs with CPython itself :)
