### ISSUE TITLE
refactor _import_module function from importlib

### ISSUE THREAD

**Issue by Pablito2020** [python/cpython#98339]
# Feature or enhancement
Refactor the [_import_module function](https://github.com/python/cpython/blob/main/Lib/importlib/__init__.py#L107). The changes would be:

    - To apply the "return early pattern", which makes reading the code more pleasant and easy to read.
    - Use functional programming instead a for loop since it is easier to read.

I've already implemented the change in my fork, and you can see the commit here: https://github.com/Pablito2020/cpython/commit/f946937422593dbc47241dd75650e11d238fb755

If the "performance downgrade" of using the _next_ builtin function instead of a loop is too much, I could change the index calculation to:

``` python3

index = get_index(name)

def get_index(name):
    for index, character in enumerate(name):
        if character != ".":
            return index
```
Which I think it is easier than the current implementation.

# Pitch
It is easier to read the function, since there is less code and now the "prerequisites" of the function are at the top, not at two lines of indentation.

**Comment by rhettinger** [comment]
Thanks for the suggestion but to my eyes the PR mades the code harder to read and doesn't match the style elsewhere in the module.
