### ISSUE TITLE
[idea] Ease understanding of positional-only and keyword-only makers in function prototyes 

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#98340]
# Documentation

In https://docs.python.org/dev/library/functions.html I added many `/` and `*` markers in function prototypes. There were already a few of them here, and I bet there is some in other places in the doc too.

For newcomers it may look like a typo, and it may be hard for them to discover what it means.

I think it would be nice to tell them what it is, maybe by making all markers a link to the [glossary](https://docs.python.org/dev/glossary.html#term-parameter) or by displaying a message on mouse hover like « The parameters on the left of a / are positional-only. ».

**Comment by rhettinger** [comment]
I thought we had decided long ago to not use these markers unless there was a specific need.   It has the effect of makes the docs *much* less usable without the benefit of having a trainer.   AFAICT, no other language docs have this sort of notion, so Python is the outlier.

**Comment by JulienPalard** [comment]
> I thought we had decided long ago

Is it documented? I've never heard of it and I see good usages of those markers already in the doc.

For the rest, I agree.

My initial goal was to avoid hard-to-read things like `bytearray([source[, encoding[, errors]]])` in the `functions.html` page, and after reviews the PR derived to this overzealous state, and should have needed a discussion beforehand.

**Comment by slateny** [comment]
If we do decide not to keep the position/keyword markers, could we still somehow keep documentation of the default arguments? I think those are useful and even a beginner can make reasonable assumptions or ignore what it is since it's more intuitive than the markers.

**Comment by rhettinger** [comment]
Check with Carol.  She was party to the decision to not sweep through the docs applying the new notation.  I don't know where that decision was written down.  It is likely in the same place as the decision to not put type annotations in the docs:  ``enumerate(iterable: Iterable[_T], n: int=0) -> Iterator[tuple[int, _T]]``.

**Comment by slateny** [comment]
@willingc Would you happen to know whether the discussion on this was documented somewhere?
