### ISSUE TITLE
Doc on weakref.proxy should mention ReferenceError

### ISSUE THREAD

**Issue by fancidev** [python/cpython#98348]
The [documentation on weakref.proxy](https://docs.python.org/3/library/weakref.html#weakref.proxy) does not say what happens if an attribute of the proxy object is accessed when the referent is gone. I had to do a bit of googling to find out it raises [ReferenceError](https://docs.python.org/3/library/exceptions.html#ReferenceError).

Would be helpful to mention that in the doc of weakref.proxy.

**Comment by sobolevn** [comment]
@fancidev are you willing to send a PR? :)

**Comment by fancidev** [comment]
Here you go!

**Comment by hauntsaninja** [comment]
Thanks, looks like this was completed
