### ISSUE TITLE
Python3.11: invalid help query raises an ImportError

### ISSUE THREAD

**Issue by qexat** [python/cpython#98374]
# Bug report

Running this on Python 3.11 REPL:

```py
>>> help("invalid query")
```

Raises the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "/usr/lib/python3.11/pydoc.py", line 2001, in __call__
    self.help(request)
  File "/usr/lib/python3.11/pydoc.py", line 2057, in help
    elif request: doc(request, 'Help on %s:', output=self._output)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pydoc.py", line 1784, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pydoc.py", line 1758, in render_doc
    object, name = resolve(thing, forceload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pydoc.py", line 1744, in resolve
    raise ImportError('''\
ImportError: No Python documentation found for 'invalid query'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.
```

Python 3.10.8 (and most probably any 3.10.*) simply prints this:

```
No Python documentation found for 'invalid query'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.
```

# Your environment

- CPython versions tested on: 3.11.0, 3.10.8
- Operating system and architecture: EndeavourOS, kernel: 6.0.1-arch2-1 (64-bit)

Apparently, this is due to commit [8868d48712aee2b490efaf60bed8dfe9fb14d6b7](https://github.com/python/cpython/commit/8868d48712aee2b490efaf60bed8dfe9fb14d6b7) (thanks to @asottile for finding it).

Is it expected behavior though?

**Comment by iritkatriel** [comment]
Possibly due to https://github.com/python/cpython/pull/27868.

**Comment by qexat** [comment]
> Possibly due to https://github.com/python/cpython/pull/27868.

Indeed, the commit I mention was present in this PR.

**Comment by terryjreedy** [comment]
Something unfixed this fix.  See #102541.
