### ISSUE TITLE
Backcompatibility broken for format_exception_only

### ISSUE THREAD

**Issue by zois-tasoulas** [python/cpython#98377]
# Bug report

I think the change below breaks backwards compatibility,
https://github.com/python/cpython/commit/91e93794d5dd1aa91fbe142099c2955e0c4c1660#diff-96634ca56022c201d0ff677e922810a97e4ad8a55de53258cf0cbc22bd7c9be1R133

Specifically, usage of `traceback.format_exception_only()` that conforms to Python 3.10 signature, cannot be used on Python 3.8. Even if the argument `value` is provided.

A reproducible example would be:
```
import sys
import traceback

# Works on Python 3.8
try:
    raise Exception("test exception, pass")
except Exception as exc:
    exception_type, exception_value, _ = sys.exc_info()
    print(traceback.format_exception_only(exception_type, exception_value))

# Raises exception on Pyhton 3.8
try:
    raise Exception("test exception, fail")
except Exception as exc:
    _, exception_value, _ = sys.exc_info()
    print(traceback.format_exception_only(exc, exception_value))
```

# Your environment
- CPython versions tested on:
Python 3.8.10

- Operating system and architecture:
Ubuntu 20.04.5 LTS, x86_64

**Comment by zois-tasoulas** [comment]
May I ask, from an engineering perspective, what is the think process for the design and decision of the above change between Python 3.8 and 3.10?

**Comment by iritkatriel** [comment]
You should not expect a change that was made in 3.10 to be available in 3.8.

The documentation of this function for 3.8 is here: https://docs.python.org/3.8/library/traceback.html#traceback.format_exception

**Comment by iritkatriel** [comment]
Backward compatibility means that code written for older versions can still run on the newer version.  If we make an older version compatible with a more recent change, that's called a backport. It is only done for bugifxes.

**Comment by zois-tasoulas** [comment]
Thank you! I clarified the terminology.
