### ISSUE TITLE
Tuple can be changed by `+=`

### ISSUE THREAD

**Issue by chen-qingyu** [python/cpython#98382]
# Bug report

I know that an element inside a tuple that is of a mutable type can be changed by calling the method of that element (`t[2].append(4) # assume t is (1, 2, [3]), then got (1, 2, [3, 4])`) , but not by assignment (`t[2] += [4]` will cause exception). But by chance I discovered that tuple elements can be changed by `+=`, this is the code:

```
>>> t = (1, 2, [3])
>>> t[2].append(4)
>>> t
(1, 2, [3, 4])
>>> t[2] += [5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object does not support item assignment
>>> t
(1, 2, [3, 4, 5])
>>> # t is changed by +=
```

I don't know whether the `+=` operator has any features I don't know, but intuitively, if the `+=` operator can change the element, it should not report an error, otherwise the element cannot be changed.

I've glanced through the issue tracker with a quick search and I didn't find a duplicate of this issue, but incase I'm mistaken, my apologies; this issue can be closed.

# Your environment

- CPython versions tested on: Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
- Operating system and architecture: Windows 10, x64

**Comment by chen-qingyu** [comment]
I've tried that in the latest version (3.10.8), and it's the same problem.

**Comment by eryksun** [comment]
This behavior occasionally gets reported and discussed on forums. By design, in-place operations are implemented to store the result back to the target name, subscript, or attribute, regardless of whether the object is mutated in place or whether the operation returns a new object. For example, consider a readonly property that always returns a particular object that happens to be mutable:

```python
class C:
    @property
    def p(self, value=[3]):
        return value
```
```pycon
>>> c = C()
>>> c.p.append(4)
>>> c.p
[3, 4]
>>> c.p += [5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: property 'p' of 'C' object has no setter
>>> c.p
[3, 4, 5]
```

**Comment by ronaldoussoren** [comment]
This is part of the Python data model, see [this FAQ entry](https://docs.python.org/3/faq/programming.html#faq-augmented-assignment-tuple-error) and [the data model](https://docs.python.org/3/reference/datamodel.html#object.__iadd__).

**Comment by stevendaprano** [comment]
This is a [FAQ](https://docs.python.org/3/faq/programming.html#why-does-a-tuple-i-item-raise-an-exception-when-the-addition-works).

**Comment by chen-qingyu** [comment]
Got It. Thanks.

**Comment by chen-qingyu** [comment]
```
>>> t = (1, 2, [3])
>>> t
(1, 2, [3])
>>> tmp = t[2] + [4]; t[2] = tmp # `+=` I thought so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object does not support item assignment

>>> tmp = t[2].extend([4]); t[2] = tmp # `+=` In fact
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object does not support item assignment
>>> t
(1, 2, [3, 4])
```

The key point is that, in the intuitive perspective of `+=`, it is first generating a temporary value and then performing an assignment, and the change occurs after the assignment; but the change in this case occurs before the assignment.

**Comment by eryksun** [comment]
Keep in mind that this applies in general, not just to tuple objects. If assigning to the subscript or attribute fails for any reason (probably `TypeError` or `AttributeError`), the in-place mutation itself may have succeeded. Another example:

```python
class C:
   x = [3]
```
```pycon
>>> vars(C)['x'] += [4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'mappingproxy' object does not support item assignment
>>> C.x
[3, 4]
```

**Comment by chen-qingyu** [comment]
Got It. Thanks.
