### ISSUE TITLE
test_filter_to_company() in test_launcher fails due to py.ini

### ISSUE THREAD

**Issue by eryksun** [python/cpython#98414]
The test in `test_filter_to_company()` executes a dry run of the launcher with the argument "-V:PythonTestSuite/". The filter is incomplete, but the test expects the launcher to select "PythonTestSuite/3.100", with the command "X.Y.exe". In practice, however, a default version set in "py.ini" overrides an incomplete filter by company. I assume this is a bug in the launcher, that it's supposed to select the best match among the installations for the given company instead of using the default version. That's how it behaves if no default is set in "py.ini" or the "PY_PYTHON" environment variable.

**Comment by zooba** [comment]
Yes correct, it shouldn't use the default value in this case.

**Comment by hauntsaninja** [comment]
Thanks, looks like this was completed
