### ISSUE TITLE
Please add `getbufferproc` and `releasebufferproc` to the limited API headers

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#98410]
# Feature or enhancement

Starting with Python 3.11 the Py_Buffer API has [been made available in the limited API](https://github.com/python/cpython/issues/89622), including the `bf_getbuffer` and `bf_releasebuffer` type slots.

However the definitions for the function pointer types stored in those slots, `getbufferproc` and `releasebufferproc` are still [only defined when including "cpython" headers](https://github.com/python/cpython/blob/c051d55ddb29c4ff7b1fcc65971535f78369ffc0/Include/cpython/object.h#L54-L55).

This means on the limited API starting with Python 3.11 it is now possible to do `PyType_GetSlot(Py_TYPE(obj), Py_bf_getbuffer)`, however the `void *` returned does not have a function pointer type available which it can be cast to (unless the user adds this typedef themselves in their own code).

# Pitch

This is a relatively straightforward change to make use of these type slots more convenient on the limited API.

I wrote an initial implementation at https://github.com/python/cpython/pull/31158. A couple of tiny tweaks beyond moving the typedefs was necessary so that forward definitions continued to function. Please see that PR for the detail.

**Comment by encukou** [comment]
Thank you!

**Comment by vstinner** [comment]
I dislike the fact that most callback types used by PyTypeObject are **not** prefixed by ``Py_`` prefix, nor use the same coding style (casing) than other names used by the Python API :-(

binaryfunc, ternaryfunc, ssizeobjargproc, etc.
