### ISSUE TITLE
Remove Dead Code in PyObject_Print

### ISSUE THREAD

**Issue by MonadChains** [python/cpython#98421]
# Bug report

While working on covering `PyObject_Print`, I noticed that I couldn't hit some lines with any test. Specifically, the part that checks the type of the representation of the object returned by `PyObject_Str` or `PyObject_Repr`:
https://github.com/python/cpython/blob/f4ead4874b558efa6379e3a130b0c491fec3acb1/Objects/object.c#L280-L308

As pointed out by @encukou, both aforementioned functions already check and **ensure** that the return type is a Python string:
https://github.com/python/cpython/blob/f4ead4874b558efa6379e3a130b0c491fec3acb1/Objects/object.c#L492-L498
https://github.com/python/cpython/blob/f4ead4874b558efa6379e3a130b0c491fec3acb1/Objects/object.c#L433-L439

So it is possible to simplify the function by excluding the useless checks of types diffent from Python string.

**Comment by mdboom** [comment]
Linking to coverate metabug #94808

**Comment by auvipy** [comment]
https://github.com/python/cpython/pull/98422 was merged, can we close this?
