### ISSUE TITLE
Unexcepted UnboundLocalError: local variable

### ISSUE THREAD

**Issue by MrMarvel** [python/cpython#98427]
# Bug report
![image](https://user-images.githubusercontent.com/24212110/196591474-c098c778-b958-465b-b530-2177f11a0709.png)

After declaring and predefined variable I am working with it in loop.
After I use this variable and it cause and error like it wasn't defined by default.

# Your environment

- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows 10H2

**Comment by stevendaprano** [comment]
Please don't post screenshots of code and error messages. Please copy and paste them as text, formatted as code, in the bug report.

**Comment by stevendaprano** [comment]
I cannot replicate this error. This works for me:

```
sql_where = str()
f"SELECT * FROM ... WHERE {sql_where};"
```

**Comment by stevendaprano** [comment]
I wonder whether this is a Unicode issue? Is it possible that you have accidentally used a Cyrillic е instead of Latin e in the variable name?

**Comment by JelleZijlstra** [comment]
Perhaps they're just running a different version of the code than what appears in their editor. In any case, this isn't going to be a bug in Python.

**Comment by MrMarvel** [comment]
It is fixed by several tries of running.
