### ISSUE TITLE
Docs: Default argument `-1` rendered with a space after the minus

### ISSUE THREAD

**Issue by encukou** [python/cpython#98444]
In docs for 3.10 & above, negative default arguments, like in [`io.RawIOBase.read`](https://docs.python.org/3.12/library/io.html#io.RawIOBase.read), are rendered with a space after the minus:

> ![image](https://user-images.githubusercontent.com/302922/196706402-c2ae0834-9aaa-4c0a-bd70-8707c3962bac.png)

cc @AA-Turner

**Comment by AA-Turner** [comment]
Fixed in Sphinx 5.1 -- there's a patch in the Python-Docs-Theme repo to add support for Sphinx 5 but I don't know who has merge rights there (I have been meaning to ask you!) and whilst I'm happy with the JS review would be useful.

A

**Comment by zware** [comment]
See also #96056.

**Comment by AA-Turner** [comment]
Closing with the same rationale as #96056.

A
