### ISSUE TITLE
Unittest: self-referencing explicit exception cause results in infinite loop

### ISSUE THREAD

**Issue by AlexTate** [python/cpython#98458]
# Bug report

If an exception is raised with a self-referencing \_\_cause__ or \_\_context__ then TestResult._clean_tracebacks() in result.py enters an infinite loop.

Minimal example 1:
```python
try:
    raise Exception()
except Exception as e:
    raise e from e
```

Minimal example 2:
```python
try:
    e = Exception()
    raise e from e
except Exception as e:
    raise e
```

# Identified Cause
Self-references are not checked while unwinding the chained exception [on line 216 of result.py](https://github.com/python/cpython/blob/3.9/Lib/unittest/result.py#L216)

# Your environment

- CPython versions tested on: 3.9, 3.10
- Operating system and architecture: macOS

### Linked PRs
* gh-98459
* gh-99995
* gh-99996

**Comment by gpshead** [comment]
Thanks! A bit of an unusual issue but no doubt a pain to debug when something winds up with this happening.
The backport PRs should automerge after CI runs.
