### ISSUE TITLE
Expose internal optimization engine as a part of `ast` module

### ISSUE THREAD

**Issue by KOLANICH** [python/cpython#98463]
# Feature or enhancement

Provide an API to apply internal optimization engine to ASTs.

# Pitch

Constant folding and copy propagation is an necessary step of safe AST analysis without execution of Turing-complete code. 

For example, if we wanna extract metadata from `setup.py` without executing it (and the security risks necesserily associated with it)

```python
import ast

m = ast.parse("""
descr = "descr"
dic1 = {"name": "aa", "version": "1.2.3.4"}
dic2 = {"install_requires": ["b"]}
setup(name=dic1["name"], version=dic1["version"], short_description=descr, **dic2)
""")

m = ast.optimize(m, [ast.Optimizations.propagate])  # propagate is an object of class `ast.OptimizationPass`
metadata = findSetupAndParseItsArgs(m)
```

Currently we have to rely on external packages (I also wonder if I can use the internal engine anyhow through ctypes), which is a burden because external code has to be written, maintained and installed through package manager, and internal code is already written and maintained. Also performance of the internal optimizer is expected to be better than the one of pure python one.

**Comment by iritkatriel** [comment]
We've recently added an arg to ast.parse and compile() to ask for an optimized AST: https://github.com/python/cpython/issues/108113
