### ISSUE TITLE
datetime format in dict

### ISSUE THREAD

**Issue by alfclement** [python/cpython#98506]
The following code
```python
import datetime
p = "2022-05-25T03:08:00.000Z"
x = datetime.datetime.strptime(p,"%Y-%m-%dT%H:%M:%S.%fZ")
print(x)

d={}
d['timestamp']=x
print(d)
```
produces this output:
```python
2022-05-25 03:08:00
{'timestamp': datetime.datetime(2022, 5, 25, 3, 8)}
```

The value for seconds is missing in the output of the dict.
I would expect that this value is printed too, even its zero, in the output of the dict to allow consistent parsing of the datetime string.

python --version
Python 3.9.10

**Comment by saito828koki** [comment]
I do not agree with your idea. The output should be concise.

In addition, that is not related to `dict`. `datetime.datetime.__repr__` method is called when printing it. For example, `list` that contains `datetime.datetime` objects is printed like this.
```
import datetime

p = "2022-05-25T03:08:00.000Z"
x = datetime.datetime.strptime(p, "%Y-%m-%dT%H:%M:%S.%fZ")
print([x]) # [datetime.datetime(2022, 5, 25, 3, 8)]
```

**Comment by ericvsmith** [comment]
This is just the way `repr` of a `datetime.datetime` works. You don't need to involve dicts or `strptime`:

```python
>>> datetime.datetime(2022, 5, 25, 3, 8, 0)
datetime.datetime(2022, 5, 25, 3, 8)
>>> datetime.datetime(2022, 5, 25, 3, 8, 1)
datetime.datetime(2022, 5, 25, 3, 8, 1)
```

Changing this would be too disruptive.

There is no inconsistency with parsing, since `eval` of the `repr` returns the original value:
```python
>>> d = datetime.datetime(2022, 5, 25, 3, 8, 0)
>>> d
datetime.datetime(2022, 5, 25, 3, 8)
>>> eval(repr(d))
datetime.datetime(2022, 5, 25, 3, 8)
```
This is because the default value for `second` is zero.

**Comment by AlexWaygood** [comment]
I agree with the other participants in this issue. This isn't a bug, and changing it would cause disruption for little gain.
