### ISSUE TITLE
Rephrase: "`Callable` now supports `[]`. See `PEP585` and  `types-genericalias`"

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98507]
I think it would be better to say: "`Callable` now supports `__class_getitem__`. See `PEP585` and  `types-genericalias`"

Because it is not quite clear what `[]` is: 
- empty list?
- slices?
- `__getitem__` operator?
- `__class_getitem__` method?

I will send a PR.

**Comment by Fidget-Spinner** [comment]
`__class_getitem__` has its own problems too - unless you're aware of typing internals, no one knows what it is. Users also won't understand the implications.

It might be better to say ``Now supports subscripting ([])``.

**Comment by sobolevn** [comment]
Done :)

**Comment by AlexWaygood** [comment]
Thanks @sobolevn!
