### ISSUE TITLE
Not all abstract types have their method validated in `test_collections`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98513]
Most types with `@abstractmethod` definitions have their methods validated in `test_collections.py`, for example:
1. https://github.com/python/cpython/blame/49f61068f49747164988ffc5a442d2a63874fc17/Lib/test/test_collections.py#L1896-L1897
2. https://github.com/python/cpython/blame/49f61068f49747164988ffc5a442d2a63874fc17/Lib/test/test_collections.py#L928

But, not these three:
1. `Awaitable`
2. `Coroutine`
3. `ByteString`

I will add missing test cases for it.
Related https://github.com/python/cpython/issues/98512

* PR: gh-99226

* PR: gh-99227

**Comment by hauntsaninja** [comment]
Thank you!
