### ISSUE TITLE
`collections.abc.ValuesView` is not sufficently tested

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98512]
There are places where it is either not complete:

https://github.com/python/cpython/blob/49f61068f49747164988ffc5a442d2a63874fc17/Lib/test/test_dictviews.py#L338-L340

Not base classes are covered here. But, I guess it should be.

Or there are places where it is not tested at all:

https://github.com/python/cpython/blob/49f61068f49747164988ffc5a442d2a63874fc17/Lib/test/test_collections.py#L1866-L1869

I will go through places like this and cover `ValuesView`.
Noticed while working on https://github.com/python/cpython/pull/98511

* PR: gh-99035

* PR: gh-99036

**Comment by hauntsaninja** [comment]
Thanks, looks like this is completed
