### ISSUE TITLE
Add regression tests for ancient str methods

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#98536]
I just noticed that Python's test suite doesn't seem to include any tests for the `split`, `rsplit`, and `splitlines` methods on strings.  There are plenty of uses of these methods, of course--they're fundamental.  But there are no regression tests ensuring they behave in a consistent manner from release to release.

This isn't a huge cause for concern, both because they don't change much, and because so much code is reliant on these functions, we'd notice very quickly if they changed.  Still, I think it's worthwhile to build up a test suite that exercises all their quirks.

For example, I only recently discovered that when using the `split` method on strings to split on whitespace, if `maxsplit` prevents `split` from splitting the entire string, it won't actually strip trailing whitespace:

```Python
>>> "   a b c   ".split(None, 1)
['a', 'b c   ']
```

Verifying this sort of thing is exactly what unit test suites are for!

There's _slightly_ more testing for `split` on bytes objects, but not much.  So I'd say both need doing.  Might also be worth checking all the core builtin types and ensuring that they have unit tests for all their methods.

**Comment by JelleZijlstra** [comment]
We do have these tests, they are in `Lib/test/string_tests.py`. They're a little hard to find because they go through some `getattr()` indirection.

**Comment by JelleZijlstra** [comment]
As for the general issue, #94808 should ensure all methods implemented in C are eventually covered by tests. @sobolevn and @mdboom have been contributing lots of improvements to get coverage better.

**Comment by sobolevn** [comment]
Also related: https://github.com/python/cpython/issues/98229

**Comment by serhiy-storchaka** [comment]
Tests for methods common for `str`, `UserString`, `bytes` and `bytearray` are defined in `string_tests`.

**Comment by abdnafees** [comment]
Can I take this issue? I would need some guidance as to where to look for the files that I need to work on.

**Comment by rblcoder** [comment]
This issue can be closed right as the tests are present?
