### ISSUE TITLE
Workflow: invalid sh syntax

### ISSUE THREAD

**Issue by sterliakov** [python/cpython#98548]
# Bug report

This bug report is low-priority. I'm reporting the problem with github workflow. The part that checks whether ABI is up-to-date uses nonexistent `-neq` operator, which should be spelled `-ne`. As a result, this check is never fired.

Workflow file: https://github.com/python/cpython/actions/runs/3303180763/workflow#L85

Failure example: https://github.com/python/cpython/actions/runs/3303180763/jobs/5450809583#step:6:38

# Your environment

Not related.

Introduced in [this commit](https://github.com/python/cpython/commit/ee2ddc2d445dd6b549710d3fbf729805e0d97cd3).

I'm going to submit a PR solving this issue soon. 

UPD: what branch should I submit against? It is present on 3.x branches (3.7-3.11), but not on main.

**Comment by arhadthedev** [comment]
> what branch should I submit against

`main`. A triager or a core developer will add some [`need packport` labels](https://github.com/python/cpython/labels?q=backport) so a bot will submit a copy to the corresponding `3.x` after this PR is merged.

**Comment by sterliakov** [comment]
@arhadthedev This action job is not present on `main` branch, how do I submit against it?.. 

https://github.com/python/cpython/blob/main/.github/workflows/build.yml

It is on all 3.x branches, but not on `main`.

**Comment by sterliakov** [comment]
Ough, sorry, my bad. It is present on 3.10 and 3.11 only, other branches are not affected. It is a bit weird: 3.10 and 3.11 have this mistake; 3.7-3.9 have this check without error message and `main` does not contain this job at all.

**Comment by sobolevn** [comment]
Thanks for fixing this.
