### ISSUE TITLE
Potential for confusion in common sequence operations table

### ISSUE THREAD

**Issue by uhasker** [python/cpython#98578]
The table showcasing common sequence operations in the "Sequence Types" section of the standard library reference (https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range) mentions the `+` and `*` operators. However these operators

* are not implemented by all built-in sequences (e.g. `range`)
* are not implemented by the `collections.abc.Sequence` class
* are often not implemented by user-defined sequence classes

I am aware that this particular section is primarily about lists, tuples and ranges and not all sequence types and that note (7) mentions

> Some sequence types (such as [range](https://docs.python.org/3/library/stdtypes.html#range)) only support item sequences that follow specific patterns, and hence don’t support sequence concatenation or repetition.

However the layout of the section heavily implies that the table is about operators which are supported by all sequences via this wording:

> The operations in the following table are supported by most sequence types, both mutable and immutable. The [collections.abc.Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) ABC is provided to make it easier to correctly implement these operations on custom sequence types.

Additionally the wording of note (7) kind of implies that not supporting concatenation or repetition is just a quirk of `range`, while in reality it's simply not an inherent property of sequences.

Mentioning it, because I ran into this while tutoring a developer, who misunderstood precisely that (and came away with the impression that all sequences support `+` and `*` except for `range` and other quirky things). If other people here agree that this is an issue, I can create a PR with a proposed fix.

**Comment by pochmann** [comment]
Emphasis mine:

> However the layout of the section heavily implies that the table is about operators which are supported by **all** sequences via this wording:
> 
> > The operations in the following table are supported by **most** sequence types, both mutable and immutable.

Why do you say "all" when it said "most"?

**Comment by uhasker** [comment]
Huh, my bad, this

> However the layout of the section heavily implies that the table is about operators which are supported by all sequences via this wording:

should be

> However the layout of the section heavily implies that the table is about operators which are supported by sequences (by virtue of them being sequences) via this wording:

Thanks for pointing this out @pochmann.

To rephrase - you kind of get away from this section with the impression that `+` and `*` are inherent operators of sequences (like the fact that you can do `in` because sequences implement `__contains__` or the fact that you can do integer-based access because sequences implement `__getitem__`) except for `range` and some other "quirky" sequences. Hope that makes more sense now.

As a side note: My point in this issue isn't that the documentation is wrong (everything in this section is technically correct), but merely that there is potential for confusion.

**Comment by pochmann** [comment]
Hmm, you're still leaving out the word "most". As soon as you stop ignoring that word, it seems clear to me that not all sequences support all those operations...

**Comment by pochmann** [comment]
Hmm, you're still leaving out the word "most". That makes it clear that not all sequences support all those operations. Plus the table references that note 7 that you mentioned, which says "Some sequence types (such as `range`)" don't support `+` or `*`. That does *not* imply that it's just a quirk of `range`. Quite the opposite, it says that `range` is only an example.

**Comment by uhasker** [comment]
Here is the reading flow of someone browsing this section:

> The operations in the following table are supported by most sequence types, both mutable and immutable. The [collections.abc.Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) ABC is provided to make it easier to correctly implement these operations on custom sequence types.

From this paragraph the average dev gathers that there is a sequence type in python, this type is provided by the `Sequence` ABC and that the following table will contain operations supported by most sequence types **by virtue of them being sequence types**. This is compounded by the fact that the other operators mentioned in the table do indeed exist on any `Sequence` (like the `in` operator). 

But now the table contains `+` and `*` and a reference to note (7). The developer goes to note (7) and sees

> Some sequence types (such as [range](https://docs.python.org/3/library/stdtypes.html#range)) only support item sequences that follow specific patterns, and hence don’t support sequence concatenation or repetition.

The picture in the developers head is now (quite reasonably): **The sequence type as given by the `Sequence` ABC supports the operators `+` and `*` except for some sequence types like `range`.**

But the `Sequence` ABC does not in general support `+` and `*`, since `Sequence` does not implement `__add__` and `__mul__`. Therefore this part should probably be restructured in such a way that it is clear that `+` and `*` just happen to be implemented for `list` and `tuple`, but are not inherently given for the `Sequence` type (and therefore e.g. if I create a class of type `Sequence` I don't get `__add__` and `__mul__` for free).

**Comment by rhettinger** [comment]
Perhaps some note can be added, but I think you're making an overly tight reading of the docs.  

The term "sequence" is generic while "Sequence" with a capital "S" is one in the abstract base classes.   The ABC Sequence is a subset of capabilities, a least common denominator and it only applies to classes that have inherited from or are registered to the ABC.  In contrast, the section on "sequences" in stdtypes refers to the builtin concrete sequence types, all of which have more capabilities than the ABCs (as concrete classes usually do).   The built in sequences do in fact support addition and multiplication.

The loose general term "sequence" and the abstract base class "Sequence" have been around for a long time and have documentation ecosystems that have grown around them.  They cannot be easily changed without disrupting a lot of documentation and people's associated mental models.  It is a fact of life that the terms look similar but have differing meanings.

I think the best that can or should be done is to mention the distinction in the glossary entry for Sequence.  Otherwise, this should be closed as "not a bug".

**Comment by uhasker** [comment]
I realize that this is kind of an "opinionated" issue & I can absolutely see your point. I am not sure I can agree with this as an argument:

> With minimal experimentation, It is immediately evident that concrete sequence classes implement additional and multiplication. And just running dir(Sequence) immediately shows that those methods aren't provided. So, this is more in the category of not liking the docs than an actual coding problem.

I think that docs should be as self-contained and unambiguous as reasonable with no need for things that we think might be self-evident or the need to run `dir`.

But I definitely agree with this important point:

> The loose general term "sequence" and the abstract base class "Sequence" have been around for a long time and have documentation ecosystems that have grown around them. They cannot be easily changed without disrupting a lot of documentation and people's associated mental models. It is a fact of life that the terms look similar but have differing meanings.

I think that the main problem arises from the fact that the documentation mentions the abstract base classes and then immediately proceeds to talk about operators on built-in classes without skipping a beat. Let's take the section on "Mutable sequence types" (https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types) as a example (the one from https://github.com/python/cpython/issues/98578#issuecomment-1291042795). Before the table the section looks like this:

> The operations in the following table are defined on mutable sequence types. The [collections.abc.MutableSequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSequence) ABC is provided to make it easier too correctly implement these operations on custom sequence types.
In the table s is an instance of a mutable sequence type [...]

The table then proceeds to showcase `*=` which does not apply to all mutable sequence types. Now we can of course say that since it's a chapter on built-in types, it might be reasonable to assume that only built-in types are meant here. But the first time I read **this** section I thought that it would be a brief introduction on mutable sequence types in general (which I think is reasonable) followed by some concrete examples of built-in mutable sequence types.

I think that at least a change from "In the table s is an instance of a mutable sequence type" to "In the table s is an instance of a **built-in** mutable sequence type" in the "Mutable Sequences" section.

Similarly I think it might be a good idea to change "In the table, s and t are sequences of the same type, n, i, j and k are integers and x is an arbitrary object that meets any type and value restrictions imposed by s." to "In the table, s and t are **built-in** sequences of the same type, n, i, j and k are integers and x is an arbitrary object that meets any type and value restrictions imposed by s." in the "Sequences" section.

I believe this is a minimal change, which doesn't disrupt anyone's mental model and immediately dismantles all possible confusion.

My apologies for being so annoying, but I care even about such (relatively) minor things, precisely because the Python docs are already so high-quality and so even (relatively) minor things stand out.

Do you agree that such a change might be in order?

**Comment by rhettinger** [comment]
> Do you agree that such a change might be in order?

-0 on changing this. I don't think anyone would ever be helped by the edit and it is perhaps more easily misread than the current wording.

I recommend closing this, but I'll leave that to you.

**Comment by uhasker** [comment]
I mean it's a docs edit proposal, so if no one thinks it's helpful, then it's not helpful.

Closed.
