### ISSUE TITLE
Example in dataclass documentation is incorrectly typed

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#98576]
The example of InitVar in dataclass documentation does not pass static type checking. This caused some confusion here: https://github.com/python/mypy/issues/13934

* PR: #98577

* PR: gh-98909

* PR: gh-98910

**Comment by AlexWaygood** [comment]
Fixed on `main`, and backported to the 3.11 and 3.10 branches.

Thanks @hauntsaninja for the PR, and thanks @Kentzo for originally pointing out the problem over at mypy!
