### ISSUE TITLE
lru_cache never hit when passing args with unpredictable repr

### ISSUE THREAD

**Issue by Naelpuissant** [python/cpython#98589]
# My issue

Hello ! 
I got an issue with the lru_cache, I was trying to add cache to a function that had objects as arguments and the cache was always missed. 
I figured out that the object I passed as arguments has an unpredictable repr (print the address of the object or something).
So if the object was the same (same hash) but had a different repr, the cache didn't hit.
Is this a normal behavior ? 
Shouldn't we use the hash (that is computed [here](https://github.com/python/cpython/blob/main/Lib/functools.py#L445) ) instead of the repr as key for the cache ?

Here is an example of code : 
```
from random import randint
from functools import cache

class Foo:
    def __init__(self, hello):
        self.hello = hello

    def __repr__(self):
        return f"<repr {str(randint(0, 1000))}>"

    def __hash__(self):
        return hash(self.hello)

@cache
def make_smth(x: int, y: int, foo: Foo) -> str:
    print(foo)
    return f"x + y = {x+y}"

make_smth(1,1, Foo("hello"))
print(make_smth.cache_info())
make_smth(1,1, Foo("hello"))
print(make_smth.cache_info())
make_smth(1,1, Foo("hello"))
print(make_smth.cache_info())
```

# Tested on 

CPython versions :
Python 3.10.7
Python 3.9.7

System : 
Manjaro Linux (Kernel: 5.11.22-2-MANJARO)

**Comment by sweeneyde** [comment]
> if the object was the same (same hash)

I think you may have a misconception. Python uses objects' `__eq__` methods to ultimately decide whether two objects are equal. The result of a `__hash__` method is just a hint to quickly decide when objects are definitely-not-equal, particularly in hash tables like dictionaries and sets. But unequal objects can have equal hashes.

**Comment by Naelpuissant** [comment]
So it's about collisions that the hash isn't considered as safe in this case ?

> Since your `Foo` class has no custom `__eq__` method, no two `Foo` instances will ever compare as equal.
Yeah you right, mb !

> `__repr__` is a red herring, it does not get involved in equality comparisons.
So you suggest to fix the `__repr__` method in those cases ? (btw my initial issue was with SQLAlchemy object that was printing an address in `__repr__`)
