### ISSUE TITLE
inspect.iscoroutinefunction should return True for functools.partial wrapping an async bound method

### ISSUE THREAD

**Issue by fancidev** [python/cpython#98590]
Currently inspect.iscoroutinefunction(fn) returns False if fn is a functools.partial object that wraps a bound async method. I believe it is more logical and useful for it to return True instead.

A StackOverflow question describes the exact same requirement: https://stackoverflow.com/questions/67020609/partial-of-a-class-coroutine-isnt-a-coroutine-why

Do you think this makes sense?

**Comment by gvanrossum** [comment]
HOw would you even do that? AFAIK, `partial` is opaque -- you can't know what it wraps.

**Comment by fancidev** [comment]
The _partial_ object (returned by the _partial_ function) has a _func_ attribute that exposes the wrapped callable object: https://docs.python.org/3/library/functools.html#functools.partial.func

The current _iscoroutinefunction_ [implementation](https://github.com/python/cpython/blob/main/Lib/inspect.py#L376) calls *functools._unwrap_partial* to unwrap a partial object *after* unwrapping bound method. But it doesn’t unwrap a partial object *before* unwrapping a bound method. That’s the missing functionality in some usage scenarios.

**Comment by fancidev** [comment]
A quick explanation of why I find checking for “coroutine function like” is useful for *iscoroutinefunction*:

Because of duck typing, the Pythonic way is not to check for the type of an argument but just use it. Wrongly typed argument will lead to an exception somewhere later. So why do people use *iscoroutinefunction*? Without doing a systematic search over GitHub on its usage, I guess the function is used to detect error early and to make the error easier to diagnose for the user.

However, *iscoroutinefunction* may give “false negative” due to duck typing, “false negative” if the user really wants to know if the callable returns a coroutine when called. For this reason, asyncio has its own version of *iscoroutinefunction*, which I used to find extremely confusing when I was less experienced with asyncio.

**Comment by fancidev** [comment]
I propose the following to address this issue:

Add a function *unbind_callable* to the *inspect* module:

*unbind_callable(f)* returns *unbind_callable(g)* if *f* is a callable object that is *known* to wrap a callable object *g* by binding some of its arguments, or returns *f* otherwise.

Leave *iscoroutinefunction* and a few other *is…* functions unchanged for backward compatibility.

A user can call *iscoroutinefunction(unbind_callable(f))* if that’s what they want.

The heavy lifting is to implement *unbind_callable*. I expect it to cover all binding constructs in the Python language and standard library. I can think of the following (as far as my limited knowledge of Python goes):

- functools.partial
- functools.partialmethod
- bound method
- bound class method
- bound static method

Anything else?

**Comment by gvanrossum** [comment]
Since this is now purely an inspect issue, I'm removing the expert-asyncio label. Also, because I'm already backed up, I'll leave it up to someone else to decide whether this is a useful design. And finally, asyncio uses its own iscoroutinefunction() only it two places, where a positive result causes an early TypeError. So a false negative doesn't prevent any useful functionality, at worst it causes a poorer error message.

**Comment by fancidev** [comment]
Thanks for reviewing.

After looking into the details, I find `functools.partialmethod` not straightforward to “unbind” as it returns an opaque function object wrapping a coroutine function in some cases.

I’m also unable to verify the full scope of unbindable constructs in the language and standard library.

For my particular usage case, which is sensitive to false negative, I will refrain from using `inspect.iscoroutinefunction(fn)` and simply just call `fn`. This is also what the `trio` library does.

Therefore I’m closing this issue as “won’t fix”.
