### ISSUE TITLE
Clean up `typing.rst` docs about `Generic` base classes

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98623]
There are multiple issues right now:
1. `Mapping` has `Mapping(Sized, Collection[KT], Generic[VT_co])` which is not correct. [Typeshed's definition](https://github.com/python/typeshed/blob/6aae57783ade5cf3f5af44ed7730cb5f5d25a261/stdlib/typing.pyi#L576): `class Mapping(Collection[_KT], Generic[_KT, _VT_co]):`. Here we have extra `Sized` and wrong `Generic` base class with only one type argument
2. There's also `AbstractSet(Sized, Collection[T_co])`, which has extra `Sized`. `Collection` is always `Sized`

**Comment by kamilturek** [comment]
Looks like the issue can be closed.
