### ISSUE TITLE
The documentation about asyncio.TaskGroup might portray it as a replacement for asyncio.gather

### ISSUE THREAD

**Issue by why-not-try-calmer** [python/cpython#98641]
# Documentation
I think the documentation be slightly adjusted to rule out the (possible) implication that asyncio.TaskGroup is a drop-in replacement / better alternative to asyncio.gather(). Both have their idiomatic uses cases, and asyncio.gather() works well for tasks that do not schedule tasks themselves, especially when the caller needs to consume their result as soon as possible (i.e.

    re1, re2 = asyncio.gather(corou1(), corou2())
)

I have a branch implementing the proposed changed [ready to be PR-ed](https://github.com/python/cpython/compare/3.11...why-not-try-calmer:cpython:3.11?expand=1)

### Linked PRs
* gh-103644

**Comment by kumaraditya303** [comment]
I am not sure that we to explicitly say this, it depends on the user how they want to use it. For most part `asyncio.TaskGroup` is much better than `gather`.

**Comment by gvanrossum** [comment]
I just closed the PR, closing this as won't fix.
