### ISSUE TITLE
`array.typecodes` is incorrectly documented as a class attribute

### ISSUE THREAD

**Issue by jsbueno-blockfi** [python/cpython#98657]
# Documentation
https://docs.python.org/3/library/array.html#array.typecodes 

Is a module attribute, but the documents put it intermingled with the methods and attributes of the `array.array` class instead.
It looks like this definition was intended to be before the `class array` paragraph that starts the documentation for the class (https://docs.python.org/3/library/array.html#array.array)

### Linked PRs
* gh-101484
* gh-101483

**Comment by nanjekyejoannah** [comment]
This has been handled in https://github.com/python/cpython/pull/98729 . Please reopen if anything else comes up.
