### ISSUE TITLE
array.array should support `__class_getitem__`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#98658]
The `array.array` class has been marked as generic in typeshed since 2017 (python/typeshed#1649). We just got a report on mypy (python/mypy#13942) pointing out that the class is not subscriptable at runtime. Just like other generic standard library classes, we should make `array.array` subscriptable at runtime (PEP-585).

I'll make a PR.

**Comment by serhiy-storchaka** [comment]
Isn't it a bug in typeshed? This class does not look generic.

**Comment by serhiy-storchaka** [comment]
It makes sense.
