### ISSUE TITLE
Links missing on Python 3.11.0 release page

### ISSUE THREAD

**Issue by adang1345** [python/cpython#98660]
The Python 3.11.0 release page at https://www.python.org/downloads/release/python-3110/ is missing the links for
- Windows installer (32-bit)
- Windows installer (ARM64)

These files can be found at https://www.python.org/ftp/python/3.11.0/python-3.11.0.exe and https://www.python.org/ftp/python/3.11.0/python-3.11.0-arm64.exe.

**Comment by infinitepower18** [comment]
Also these two pages still list 3.10.8 as the latest version:
https://www.python.org/downloads/
https://www.python.org/downloads/windows/

**Comment by pablogsal** [comment]
> Also these two pages still list 3.10.8 as the latest version:

Not for me:

![Screenshot 2022-10-25 at 16 42 32](https://user-images.githubusercontent.com/11718525/197819738-3b07c8dd-7a83-4b35-90a0-b231f21044f8.png)

**Comment by pablogsal** [comment]
> The Python 3.11.0 release page at [python.org/downloads/release/python-3110](https://www.python.org/downloads/release/python-3110/) is missing the links for
> 
> * Windows installer (32-bit)
> * Windows installer (ARM64)
> 
> These files can be found at [python.org/ftp/python/3.11.0/python-3.11.0.exe](https://www.python.org/ftp/python/3.11.0/python-3.11.0.exe) and [python.org/ftp/python/3.11.0/python-3.11.0-arm64.exe](https://www.python.org/ftp/python/3.11.0/python-3.11.0-arm64.exe).

I will take a look later today

**Comment by pablogsal** [comment]
I added those to the release script:

https://github.com/python/release-tools/pull/29

**Comment by pablogsal** [comment]
> * Windows installer (32-bit)
> * Windows installer (ARM64)

Fixed:

![lel](https://user-images.githubusercontent.com/11718525/197826334-0567548c-d5b0-4597-b3b4-0171cdc526ca.png)

**Comment by pablogsal** [comment]
I opened an issue on the release tools repo

**Comment by infinitepower18** [comment]
Not yet added on this page

<img width="526" alt="Screenshot 2022-10-25 at 7 04 02 pm" src="https://user-images.githubusercontent.com/44692189/197848517-3903a2da-3afd-4744-b494-8a499a402371.png">

**Comment by infinitepower18** [comment]
ARM64 and 32 bit installers are not there.

**Comment by pablogsal** [comment]
Ah, you are referring to the installers. I don't think that page is automatically updated. CC@zooba

**Comment by pablogsal** [comment]
CC @zooba

**Comment by pablogsal** [comment]
@infinitepower18 You may need to open a bug in https://github.com/python/pythondotorg/ because there are many entries there that are missing files.

**Comment by infinitepower18** [comment]
python/pythondotorg#2168

**Comment by zooba** [comment]
Is it possibly capping at 4 entries? Can we choose to only show the installers here and not the embeddable packages?
