### ISSUE TITLE
PyMemoryView_FromMemory is part of stable ABI but the flag constants (PyBUF_READ, etc.) are not

### ISSUE THREAD

**Issue by asottile** [python/cpython#98680]
# Feature or enhancement

I'd rather not write:

```c
#ifndef PyBUF_READ
#define PyBUF_READ 0x100
#endif
```

and instead be able to rely on these even in stable abi mode

relevant error message:

```
whatever.c:1:30: error: ‘PyBUF_READ’ undeclared (first use in this function)
```

### Linked PRs
* gh-100018
* gh-100020

**Comment by encukou** [comment]
> ```
> whatever.c:1:30: error: ‘PyBUF_READ’ undeclared (first use in this function)
> ```

How did you get this error? The flags should be available with `#define Py_LIMITED_API 0x030b0000` (3.11).

It's true that they weren't added to the manifest, though. Thanks for catching that!

**Comment by asottile** [comment]
anything older than 3.11 has:

```c
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x03030000
PyAPI_FUNC(PyObject *) PyMemoryView_FromMemory(char *mem, Py_ssize_t size,
                                               int flags);
#endif
```

**Comment by encukou** [comment]
Ah! Of course. 3.11 added the whole buffer API and I somehow assumed `PyMemoryView_FromMemory` was part of that.

If we add the constants retroactively, code that compiles fine on newer Python versions might fail to compile on older ones, even with the same `Py_LIMITED_API` setting. I'd rather avoid that.
The `#ifndef/#define` you posted is a good workaround. (Pedantically, it is relying on non-limited API until 3.11, but earlier releases won't change any more so it's fine.)

**Comment by asottile** [comment]
yeah I totally understand -- my bad for not checking 3.11 otherwise this would have been more accurately just a documentation issue /o\

**Comment by encukou** [comment]
Don't feel bad at all -- an issue that's not fully triaged is better than no issue :)
Thanks for reaching out!
