### ISSUE TITLE
-X frozen_modules=on|off should be configurable with environment variable

### ISSUE THREAD

**Issue by virtuald** [python/cpython#98697]
# Feature or enhancement

`-X frozen_modules=on|off` should be configurable with environment variable

# Pitch

The [crossenv](https://github.com/benfogle/crossenv) project provides the ability to generate virtualenvs that are customized to allow very simple cross-compilation, by mixing pieces of a host-native python and the right configuration variables from a cross-compiled python. [Python 3.11 broke it in a few ways](https://github.com/benfogle/crossenv/issues/103), but in particular the way that it injects its hooks is by overriding the contents of `site.py`, which is now included in a frozen module by default. To allow the patching to continue working, we have to add the -X option to the python command line each time it starts. This is doable, but it would be much simpler if we could just set an environment variable to disable the frozen modules.

Many other -X options are configurable through an environment variable, it seems like this one should too. Maybe `PYUSEFROZENMODULES=0|1`?

Note: yes, crossenv does a lot of dirty tricks to do its work, but I've tried several cross-compilation approaches and it's the easiest I've used by far.

# Previous discussion

No prior discussion, seems like a small enough feature that is an easy yes/no?

**Comment by kumaraditya303** [comment]
It's too late to add this to 3.11 as this is new feature and 3.11 is final now. 

cc @gvanrossum @ericsnowcurrently

**Comment by gvanrossum** [comment]
If you submit a PR that references this issue we could add this to 3.12; alas, for 3.11 it's too late, as Kumar says. I don't have the bandwidth to do anything myself.
