### ISSUE TITLE
Constant folding of unpacking in sets

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#98701]
# Feature or enhancement

Optimize out an empty/one-element constant unpack into a set, which currently output these bytecodes:
```py
>>> from dis import dis
>>> dis("{*()}")
              0 RESUME                   0

  1           2 BUILD_SET                0
              4 LOAD_CONST               0 (())
              6 SET_UPDATE               1
              8 RETURN_VALUE
>>> dis("{*(1,)}")
              0 RESUME                   0

  1           2 BUILD_SET                0
              4 LOAD_CONST               0 ((1,))
              6 SET_UPDATE               1
              8 RETURN_VALUE
```

# Pitch

Add a check for constants in the set case in `Python/ast_opt.c` and apply optimizations if the constant is a sequence and the size is 0 or 1.

# Previous discussion

N/A

**Comment by pochmann** [comment]
I can see `{*()}` being used as a perhaps faster or safer `set()`, but why would anyone write `{*(1,)}` instead of `{1}`?

**Comment by thatbirdguythatuknownot** [comment]
> I can see `{*()}` being used as a perhaps faster or safer `set()`, but why would anyone write `{*(1,)}` instead of `{1}`?

I just decided to also add it since it's only 3 more lines of code in the implementation. Might remove it if I'm instructed to do so.

**Comment by MojoVampire** [comment]
I like the idea of [the one-eyed money operator](https://github.com/python/cpython/issues/67865#issuecomment-1093677900) being optimized. 👍 I experimented with manual bytecode manipulation to do this awhile ago and it made it the fastest way to build a `set` by a significant margin (the shift a `LOAD_GLOBAL` cache and vectorcall for built-in constructors probably limits the benefit, but it's hard to beat a single dedicated `BUILD_SET 0` bytecode to make the empty `set` (just like it works for `[]` and `{}`).

**Comment by TeamSpen210** [comment]
Is there any reason to limit the optimisation to only 0/1-long sets? Obviously it would be better to use the regular set syntax for those, but Python already does things like swapping to tuples/frozensets when it knows the container can't be directly accessed.

**Comment by thatbirdguythatuknownot** [comment]
> Is there any reason to limit the optimisation to only 0/1-long sets? Obviously it would be better to use the regular set syntax for those, but Python already does things like swapping to tuples/frozensets when it knows the container can't be directly accessed.

Might as well do that.

**Comment by rhettinger** [comment]
I'm opposed to this.  Writing `{*()}` is unpythonic and should not be encouraged or incentivized.  Writing `set()` is the one-obvious-way-to-do-it and is pretty fast now that builtin lookups have gotten fast.

**Comment by thatbirdguythatuknownot** [comment]
> I'm opposed to this. Writing `{*()}` is unpythonic and should not be encouraged or incentivized. Writing `set()` is the one-obvious-way-to-do-it and is pretty fast now that builtin lookups have gotten fast.

It does seem to be faster.
```py
> py -m timeit "set()"
5000000 loops, best of 5: 48.5 nsec per loop
> py -m timeit "{*()}"
5000000 loops, best of 5: 64.9 nsec per loop
```

**Comment by rhettinger** [comment]
> But shouldn't a lone BUILD_SET 0 perform faster?

No.  It doesn't matter and isn't worth anyone's time to try to optimize.
