### ISSUE TITLE
Consistent test failures in test test_asyncio.test_streams.test_drain_raises on Windows

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#98703]
Run ``python_d.exe -m test test_asyncio -m test_drain_raises -F`` on Windows. The test eventually fails after some repetitions.

The problem is that `_call_connection_lost` can be called multiple times, even after the socket by the proactortransport is closed. So it's calling `close()` on something that is already set to `None`.

I have a PR to fix it.

**Comment by pablogsal** [comment]
Thanks a lot @Fidget-Spinner 🙏

**Comment by gvanrossum** [comment]
Does it needs to be a release blocker? Or just be backported?

**Comment by Fidget-Spinner** [comment]
> Does it needs to be a release blocker? Or just be backported?

It causes the [release status page](https://buildbot.python.org/all/#/release_status) to flicker in and out of being releasable and non-releasable. That's a release blocker IMO.

**Comment by Fidget-Spinner** [comment]
Waiting for Kumar's tests to land before I close this issue. It's no longer a release blocker though.
