### ISSUE TITLE
Sqlite 3 html documentation shows functions with `\*` instead of `*`.

### ISSUE THREAD

**Issue by nadavwe** [python/cpython#98716]
# Documentation
e.g. see:
https://docs.python.org/3.10/library/sqlite3.html#sqlite3.Connection.backup

other modules look fine.

I tried to look into the code to understand why sqlite outputs different html but the C code looks similar to other modules.

**Comment by erlend-aasland** [comment]
> hi @erlend-aasland, if you can give me some hint where to look i'd gladly try to solve it myself...

Sure, look in Doc/library/sqlite3.rst. It's just a wrongly applied escape backslash.

**Comment by erlend-aasland** [comment]
Here's a list of what needs fixup:

- blobopen
- create_function
- backup
- serialize
- deserialize

**Comment by erlend-aasland** [comment]
Actually, you can just revert #96081 (yes, there are entirely my fault)

`git revert 91afe66707237558d808aeca4683d0822aa0511e`

**Comment by nadavwe** [comment]
if it's a revert then there's no point in me doing it.
I assumed the docs were somehow generated from the C source code...

**Comment by erlend-aasland** [comment]
Np, thanks for the report though! I can't believe I didn't check the rendered output before merging gh-96081. Lessons learned.

**Comment by nadavwe** [comment]
Glad to have helped! :)
