### ISSUE TITLE
C arg-parsing docs suggest NULL bf_releasebuffer implies immutability

### ISSUE THREAD

**Issue by encukou** [python/cpython#98712]
[The docs]() say:

> Some formats require a read-only [bytes-like object](https://docs.python.org/3/glossary.html#term-bytes-like-object), and set a pointer instead of a buffer structure. They work by checking that the object’s [PyBufferProcs.bf_releasebuffer](https://docs.python.org/3/c-api/typeobj.html#c.PyBufferProcs.bf_releasebuffer) field is NULL, which disallows mutable objects such as [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray).

This can easily be understood that `bf_releasebuffer` is directly linked to (im)mutability.
In reality this check is there to ensure whether the buffer can be safely "borrowed". For simple buffer exporters (like most of the stdlib ones), this correlates with immutability -- but not always, e.g.:

```
>>> import unicodedata
>>> unicodedata.lookup(b'SNAKE')  # `lookup` happens to use the s# format internally
'🐍'
>>> view = memoryview(b'SNAKE')
>>> view.readonly
True
>>> unicodedata.lookup(view)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: lookup() argument must be read-only bytes-like object, not memoryview
```

The docs should explain the semantics precisely, without overwhelming the user that just wants to take `str`/`bytes`.

### Linked PRs
* gh-100461
* gh-100462

**Comment by hauntsaninja** [comment]
Thanks, looks like the backports are all merged
