### ISSUE TITLE
`typing` tests: `test_overload_on_compiled_functions()` may not work on alternative Python implementations

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#98713]
# Bug report

A few weeks ago, the `typing_extensions` backport library received a bug report that `test_overload_on_compiled_functions()`, a recently added test, failed when run on PyPy: https://github.com/python/typing_extensions/issues/83. This is due to the fact that `builtins.sum()` and `builtins.print()` are not compiled functions on PyPy.

The same test exists in the CPython test suite (the test was ported over to `typing_extensions` in https://github.com/python/typing_extensions/pull/73 after being added to the CPython test suite in #96479): https://github.com/python/cpython/blob/de6981680bcf6496e5996a853b2eaa700ed59b2c/Lib/test/test_typing.py#L4638-L4650.

I think the test should probably be marked with the `@test.support.cpython_only` decorator in the CPython test suite.

(Cc. @sobolevn, who added the test.)

**Comment by sobolevn** [comment]
Yes, I will send a PR for that!

**Comment by AlexWaygood** [comment]
Thanks for the fix @sobolevn!
