### ISSUE TITLE
Remove old-style classes from `test_cmath`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98727]
Right now old-style classes are long gone. But, `test_cmath` still tests for them and has an outdated comment about them being not fully supported:

https://github.com/python/cpython/blob/365852a03a0c934ccd9b6c2b8e24c71181c41f03/Lib/test/test_cmath.py#L258-L265

I will send a PR with removal of old style classes, correct exception handling, and comment rewording.

**Comment by mdickinson** [comment]
Closed in #98728. Thank you for the fix!
