### ISSUE TITLE
Not able to install Pyarrow 

### ISSUE THREAD

**Issue by rahilkasimi** [python/cpython#98735]
I'm not able to install pyarrow. log trace is below. any suggestions

`Defaulting to user installation because normal site-packages is not writeable
Processing h:\download\python\pyarrow-9.0.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.16.6 in c:\users\rahil\appdata\roaming\python\python311\site-packages (from pyarrow==9.0.0) (1.23.4)
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [215 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\benchmark.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\cffi.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\compute.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\conftest.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\csv.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\cuda.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\dataset.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\feather.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\filesystem.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\flight.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\fs.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\hdfs.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\ipc.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\json.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\jvm.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\orc.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\pandas_compat.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\plasma.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\serialization.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\substrait.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\types.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\util.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_compute_docstrings.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_generated_version.py -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\__init__.py -> build\lib.win-amd64-cpython-311\pyarrow
      creating build\lib.win-amd64-cpython-311\pyarrow\parquet
      copying pyarrow\parquet\encryption.py -> build\lib.win-amd64-cpython-311\pyarrow\parquet
      copying pyarrow\parquet\__init__.py -> build\lib.win-amd64-cpython-311\pyarrow\parquet
      creating build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\arrow_16597.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\arrow_7980.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\conftest.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\deserialize_buffer.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\pandas_examples.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\pandas_threaded_import.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\read_record_batch.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\strategies.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_adhoc_memory_leak.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_array.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_builder.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_cffi.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_compute.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_convert_builtin.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_csv.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_cuda.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_cuda_numba_interop.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_cython.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_dataset.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_deprecations.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_exec_plan.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_extension_type.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_feather.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_filesystem.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_flight.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_fs.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_gandiva.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_gdb.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_hdfs.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_io.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_ipc.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_json.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_jvm.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_memory.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_misc.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_orc.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_pandas.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_plasma.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_plasma_tf_op.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_scalars.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_schema.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_serialization.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_serialization_deprecated.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_sparse_tensor.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_strategies.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_substrait.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_table.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_tensor.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_types.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_udf.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\test_util.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\util.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\__init__.py -> build\lib.win-amd64-cpython-311\pyarrow\tests
      creating build\lib.win-amd64-cpython-311\pyarrow\vendored
      copying pyarrow\vendored\docscrape.py -> build\lib.win-amd64-cpython-311\pyarrow\vendored
      copying pyarrow\vendored\version.py -> build\lib.win-amd64-cpython-311\pyarrow\vendored
      copying pyarrow\vendored\__init__.py -> build\lib.win-amd64-cpython-311\pyarrow\vendored
      creating build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\common.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\conftest.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\encryption.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_basic.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_compliant_nested_type.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_dataset.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_data_types.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_datetime.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_encryption.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_metadata.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_pandas.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_parquet_file.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\test_parquet_writer.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      copying pyarrow\tests\parquet\__init__.py -> build\lib.win-amd64-cpython-311\pyarrow\tests\parquet
      running egg_info
      writing pyarrow.egg-info\PKG-INFO
      writing dependency_links to pyarrow.egg-info\dependency_links.txt
      writing entry points to pyarrow.egg-info\entry_points.txt
      writing requirements to pyarrow.egg-info\requires.txt
      writing top-level names to pyarrow.egg-info\top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'pyarrow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '..\LICENSE.txt'
      warning: no files found matching '..\NOTICE.txt'
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*~' found anywhere in distribution
      warning: no previously-included files matching '#*' found anywhere in distribution
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '.DS_Store' found anywhere in distribution
      no previously-included directories found matching '.asv'
      writing manifest file 'pyarrow.egg-info\SOURCES.txt'
      copying pyarrow\__init__.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_compute.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_compute.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_csv.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_csv.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_cuda.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_cuda.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_dataset.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_dataset.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_dataset_orc.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_dataset_parquet.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_exec_plan.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_feather.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_flight.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_fs.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_fs.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_gcsfs.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_hdfs.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_hdfsio.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_json.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_orc.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_orc.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_parquet.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_parquet.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_parquet_encryption.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_parquet_encryption.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_plasma.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_s3fs.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\_substrait.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\array.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\benchmark.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\builder.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\compat.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\config.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\error.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\gandiva.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\io.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\ipc.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\lib.pxd -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\lib.pyx -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\memory.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\pandas-shim.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\public-api.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\scalar.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\serialization.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\table.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\tensor.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      copying pyarrow\types.pxi -> build\lib.win-amd64-cpython-311\pyarrow
      creating build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\common.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_cuda.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_dataset.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_dataset_parquet.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_feather.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_flight.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_fs.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_python.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libarrow_substrait.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libgandiva.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\libplasma.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      copying pyarrow\includes\__init__.pxd -> build\lib.win-amd64-cpython-311\pyarrow\includes
      creating build\lib.win-amd64-cpython-311\pyarrow\tensorflow
      copying pyarrow\tensorflow\plasma_op.cc -> build\lib.win-amd64-cpython-311\pyarrow\tensorflow
      copying pyarrow\tests\bound_function_visit_strings.pyx -> build\lib.win-amd64-cpython-311\pyarrow\tests
      copying pyarrow\tests\pyarrow_cython_example.pyx -> build\lib.win-amd64-cpython-311\pyarrow\tests
      creating build\lib.win-amd64-cpython-311\pyarrow\tests\data
      creating build\lib.win-amd64-cpython-311\pyarrow\tests\data\feather
      copying pyarrow\tests\data\feather\v0.17.0.version.2-compression.lz4.feather -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\feather
      creating build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\README.md -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.emptyFile.jsn.gz -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.emptyFile.orc -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.test1.jsn.gz -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.test1.orc -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.testDate1900.jsn.gz -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\TestOrcFile.testDate1900.orc -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\decimal.jsn.gz -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      copying pyarrow\tests\data\orc\decimal.orc -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\orc
      creating build\lib.win-amd64-cpython-311\pyarrow\tests\data\parquet
      copying pyarrow\tests\data\parquet\v0.7.1.all-named-index.parquet -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\parquet
      copying pyarrow\tests\data\parquet\v0.7.1.column-metadata-handling.parquet -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\parquet
      copying pyarrow\tests\data\parquet\v0.7.1.parquet -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\parquet
      copying pyarrow\tests\data\parquet\v0.7.1.some-named-index.parquet -> build\lib.win-amd64-cpython-311\pyarrow\tests\data\parquet
      running build_ext
      creating C:\Users\rahil\AppData\Local\Temp\pip-req-build-imuv4nac\build\temp.win-amd64-cpython-311
      -- Running cmake for pyarrow
      cmake "-DPYTHON_EXECUTABLE=C:\Program Files\Python311\python.exe" "-DPython3_EXECUTABLE=C:\Program Files\Python311\python.exe" "" -G "Visual Studio 15 2017 Win64" -DPYARROW_BUILD_CUDA=off -DPYARROW_BUILD_SUBSTRAIT=off -DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_BUILD_PARQUET=off -DPYARROW_BUILD_PARQUET_ENCRYPTION=off -DPYARROW_BUILD_PLASMA=off -DPYARROW_BUILD_GCS=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_USE_TENSORFLOW=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_BOOST=off -DPYARROW_GENERATE_COVERAGE=off -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_PARQUET_USE_SHARED=on -DCMAKE_BUILD_TYPE=release C:\Users\rahil\AppData\Local\Temp\pip-req-build-imuv4nac
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects`

**Comment by hugovk** [comment]
This repo is for the Python programming language itself, not third-party packages.

Please follow this PR at the pyarrow repo:

* https://github.com/apache/arrow/pull/14499
