### ISSUE TITLE
Make 3.12 installable by py launcher

### ISSUE THREAD

**Issue by zooba** [python/cpython#98745]
The py.exe launcher now supports [install on demand](https://docs.python.org/3.11/using/windows.html#install-on-demand) for versions we have in the Store.

There's now a 3.12 alpha available (unlisted), so we should add an entry to the table in the launcher for it. The ID is `9NCVDN91XZQP`

This can be backported, as the launcher isn't part of the Python runtime and this won't have any impact on existing functionality (assuming the change is correct ;) )

**Comment by hauntsaninja** [comment]
Thanks, looks like this is completed and backports are merged
