### ISSUE TITLE
Std library  doc - built-in functions - slice: faulty example

### ISSUE THREAD

**Issue by steady-state** [python/cpython#98759]
Description of "class slice" contains two examples for extended indexing, the second is "a[start:stop, i]". However this mixture of slice (:) and tuple (,) is not found elsewhere in the docs and gives an error message if tested with a standard list.   
Proposal: omit this second example.

**Comment by rhettinger** [comment]
I think[ this](https://docs.python.org/3/library/functions.html?highlight=class%20slice#slice) is fine as-is. 

The docs are pretty clear that slices have no  explicit functionality but are used by NumPy and other third-party packages.  The examples are legitimate and without them, it is hard to know that `a[start:stop, i]` is valid syntax.

Thanks for the suggestion but I think the docs are correct, clear, and serve a purpose.
