### ISSUE TITLE
Resolving circular import error

### ISSUE THREAD

**Issue by apodgorny** [python/cpython#98777]
# Pitch + Feature Description

When module A imports B, and B imports A, I get error: 
"ImportError: cannot import name from partially initialized module (most likely due to a circular import)."

However, if I merge contents of both modules into one, no error happens.
Is there a reason why python does not treat circularly imported files as one big one?

I understand, that ambiguity arises: "Which to run first?", but that can be easily achieved by slightly adjusting syntax of imports. Something like:

from foo import A priority 2
from foo import B priority 1

In case of multiple and complex circular imports, the solution would not change.
An algorithm similar to graph path calculation can be applied to sort the priorities, if none specified in code.

# Previous discussion
https://stackoverflow.com/questions/74225877/circular-import-with-python/74226042#74226042

**Comment by ericvsmith** [comment]
There's also the issue of creating separate namespaces for each module, which you'd have to address with your proposal.

I don't think it's worth complicating the import machinery to handle this relatively rare case. Is there a reason you can't modify the modules (perhaps by adding another module) to avoid the import loop?

**Comment by apodgorny** [comment]
Relatively rare, but when it rains – it pours. Here is a real example. I am writing a language interpreter in python. I have a number of Type classes, I have a TypeManager which does casting. Casting needs Types, and Types must do internal casting. Adding more modules just expand the import loop. The only solution is to put it all into one long file, which is just dirty.

**Comment by ericvsmith** [comment]
> Also, please specify what you mean by "issue of creating separate namespaces for each module".

As I read it, your proposal would mean that foo.A and foo.B would no longer be separate modules / namespaces in sys.modules, which is a big change. You've merged two modules into one, so presumably there'd only be one namespace (for foo?) instead of two (for foo.A and foo.B).

In any event, I'd suggest continuing the discussion on discuss.python.org, since that's where most feature discussions get flushed out these days. More people are likely to see it there.

**Comment by iritkatriel** [comment]
Closing as this won't go anywhere without a PEP. We can reopen or create a new issue once it is agreed what to do.
