### ISSUE TITLE
Search can't search C code in cpython even though files are indexed

### ISSUE THREAD

**Issue by DefaultRyan** [python/cpython#98791]
I keep having issues searching code in the https://github.com/python/cpython repository. For instance, searching for `win32_xtat_impl` using this query (https://github.com/search?q=win32_xstat_impl+repo%3Apython%2Fcpython&type=Code) is not returning any results in the C language.

However, that symbol does exist in the repo at Modules/posixmodule.c, https://github.com/python/cpython/blob/3e07f827b359617664ad0880f218f17ae4483299/Modules/posixmodule.c#L1828

And doing a C language search on the repo shows that posixmodule.c was indexed recently:
https://github.com/search?q=repo%3Apython%2Fcpython+path%3AModules+language%3AC&type=Code

Is something in GitHub search broken, or is there a repository setting that could somehow defeat code search?

**Comment by asottile** [comment]
if it hasn't changed since last time I asked support about this: github search has a limitation where it won't search past the 1000th line of a file

**Comment by ammaraskar** [comment]
Closing as this is a Github limitation.

Did you ask support somewhere publicly @asottile where we can +1? :)

**Comment by DefaultRyan** [comment]
I posted this in the Community forums. https://github.com/orgs/community/discussions/37569
