### ISSUE TITLE
pandas method xs crash in 3.11.0 at tupleobject.c:927: bad argument to internal function

### ISSUE THREAD

**Issue by WoolenWang** [python/cpython#98794]
`

  File "E:\git\py_help\py_help\lib\finance\factor_analysis\performance.py", line 372, in compute_mean_returns_spread
    mean_return_difference = mean_returns.xs(upper_quant,
  File "D:\running\python3.11\Lib\site-packages\pandas\core\generic.py", line 4035, in xs
    result = self.iloc[indexer]
             │         └ (slice(0, 3, None), slice(None, None, None))
             └                             period_1  period_5  period_10
factor_quantile date                                     
1           ...
  File "D:\running\python3.11\Lib\site-packages\pandas\core\indexing.py", line 1064, in __getitem__
    key = tuple(com.apply_if_callable(x, self.obj) for x in key)
    │           │                        │                  └ (slice(0, 3, None), slice(None, None, None))
    │           │                        └ <pandas.core.indexing._iLocIndexer object at 0x00000176629E7D90>
    │           └ <module 'pandas.core.common' from 'D:\\running\\python3.11\\Lib\\site-packages\\pandas\\core\\common.py'>
    └ (slice(0, 3, None), slice(None, None, None))
SystemError: D:\_w\1\s\Objects\tupleobject.c:927: bad argument to internal function

`
# Crash report

Tell us what happened, ideally including a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example).

# Error messages

Enter any relevant error message caused by the crash, including a core dump if there is one.

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: windows server 2016   1607

**Comment by JelleZijlstra** [comment]
That sounds like a bug in pandas. Could you report it to them?

**Comment by kumaraditya303** [comment]
You should report it to pandas bug tracker.
