### ISSUE TITLE
Python console   bug

### ISSUE THREAD

**Issue by tiannyj** [python/cpython#98800]
When running anything with a freshly installed version of Python 3.11.0a7 on 64-bit Windows, the following message is printed:

-------------------------------------------------------------------------------
pydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807

**Comment by kumaraditya303** [comment]
This is a pydev bug . You should report it to their bug tracker, also you should try the latest stable release https://www.python.org/downloads/release/python-3110/.
