### ISSUE TITLE
logging to postgresql

### ISSUE THREAD

**Issue by CSVKRAO** [python/cpython#98802]
Logging to different DBs when creating Full Stack Application.

Sometimes we need to log the module wise status to Db's instead of file system. 

i searched in the Web on logging to PostgreSQL. I could not find the relevant option.

Please consider this.

thanks
Gururaj

**Comment by kumaraditya303** [comment]
This bug tracker is for bugs in CPython. You can ask this on https://discuss.python.org/c/users/7
