### ISSUE TITLE
Add more shortcuts (Related to math) to improve developer experience

### ISSUE THREAD

**Issue by Advik-B** [python/cpython#98813]
# Feature or enhancement

Add new operators:
```python
*=
/=
//=
%=
```

# Pitch

What if we add more operators to python to make developer much easier
Examples:

```python
age = 16
age *= 2
# Same as:
age = age * 2
```
---
```python
age = 16
age /= 2
# Same as:
age = age / 2
```
---
```python
age = 16
age //= 2
# Same as:
age = age // 2
```
---
```python
age = 16
age %= 2
# Same as:
age = age % 2
# In this case, the value of age should be 0 cause it is divisible by 2
```
---

I think this would be a great ease-of-life feature.
Also, the examples speak for themselves 😉 

# Previous discussion

**Comment by AlexWaygood** [comment]
These all already exist in the way you'd like

**Comment by Advik-B** [comment]
> These all already exist in the way you'd like
Omg, I did not realise, sorry for wasting your time 😅
