### ISSUE TITLE
module 'tomllib' has no attribute 'load'

### ISSUE THREAD

**Issue by aerosadegh** [python/cpython#98848]
# Bug report

When I run this code, get below error:
```python
import tomllib

toml_file_path = "sample.toml"

with open(toml_file_path, "rb") as toml_file:
    content = tomllib.load(toml_file)

print(content)
```

```bash
...
content = tomllib.load(toml_file)
              ^^^^^^^^^^^^
AttributeError: partially initialized module 'tomllib' has no attribute 'load' (most likely due to a circular import)
```
# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: Window x64 & WSL:Ubuntu 22.04

**Comment by wookie184** [comment]
I'd guess the issue is that your file is named `tomllib.py`, meaning it's importing itself instead of the tomllib module.

**Comment by aerosadegh** [comment]
I'm sorry about this issue. 🥺
That's true!
