### ISSUE TITLE
math (power) calcuation error

### ISSUE THREAD

**Issue by cozyClassic** [python/cpython#98843]
# Bug report

I think power operator (**) does not calculated from the front.
this is the only one not starting from front.
it is calculated from the back.

1. 2 ** 3 ** 2 = 512  = (2 ** (3**2))
2. 2 ** 3 * 2 = 16  = ((2**3) *2)
3. 2 ** (3 *2) = 64

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment
- CPython versions tested on: 3.11.0rc2
- Operating system and architecture: mac, M1 (arm64)

**Comment by ronaldoussoren** [comment]
This is documented here: https://docs.python.org/3/reference/expressions.html#the-power-operator

**Comment by rhettinger** [comment]
Also documented [here](https://docs.python.org/3/reference/expressions.html#operator-precedence ):

> Operators in the same box group left to right (except for exponentiation and conditional expressions, which group from right to left).
