### ISSUE TITLE
Asyncio: Cannot step into code of tasks.Task class

### ISSUE THREAD

**Issue by 40dpt-thegoodcop** [python/cpython#98849]
# Bug report

The Python debugger always skips code of the `asyncio.tasks.Task` class. See [details on stackoverflow](https://stackoverflow.com/questions/74241149/python-asyncio-can-t-debug-into-task-class).

# Your environment

- CPython versions tested on: 3.8., 3.9, 3.11
- Operating system and architecture: macOS Ventura ARM64, Windows 10 x86-64

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/77081

**Comment by kumaraditya303** [comment]
This is a `pdb` limitation as it does not supports coroutines.
