### ISSUE TITLE
Add `list.len()` method

### ISSUE THREAD

**Issue by maronuu** [python/cpython#98859]
# Feature or enhancement

Add `list.len()` method which works exactly the same as `list.__len__()`.

## Point 1
Other popular languages support `list.len()`.
```
# Java
array.length
# Kotlin
arr.size
```

## Point 2
The number of nests '()' is decreased.

When you get length of the list, you should 
```
len(ls)
```
or 
```
ls.__len__()
```

`__len__()` method is not ordinary one to be called from a "every-day" code, so most of cases are `len(ls)`.
However, `len(ls)` add a nest of `()`, which may lead to poor readability.
Example:
```
# Get the number of elements that satisfies a condition in a list
len(list(filter(some_func, ls)))
```
If it can be written like below,
```
list(filter(some_func, ls)).len()
```
the number of nests is decreased.

## Point 3
Supporting `list.len()` is the most easiest and small step of the enhancement explained below.

Some python built-in functions (especially related to higher-order functions) like `map`, `filter`, `sum`, `max/min`, and `len` can be used in a chain. However, when you apply these functions, a lot of nests are inevitable. For example,
```
# Suppose that ls is a list of which you want to summarize some information
len(
  list(
    filter(some_condition,
      map(some_transformation, ls)
    )
  )
)
```

If these kinds of higher-order functions and reduction methods like `sum`, `max`, `min`, `len` are supported as `list`'s methods, the code can be like this:
```
ans = ls.map(some_transformation).filter(some_condition).len()
```
This is quite simple and clean because the nests of `()` are removed.

Thus, as the first step, `list.len()` may be a good choice.

# Pitch

Example use cases:
```
class Product:
    def __init__(self, name: str, price: int) -> None:
        self.name = name
        self.price = price

ls = [
    Product("apple", 100),
    Product("grape", 240),
    Product("rice", 1234)
]
# number of products whose price >= 200
ans = list(map(lambda p.price >= 200, ls)).len()
```

# Previous discussion

**Comment by hauntsaninja** [comment]
This runs afoul of the "there should be only one way to do it" design guideline.

To your point 3, this privileges methods in a way that is not modular or extensible. `list` is not going to develop the entire `itertools` interface as methods. It would also privilege the stdlib unnecessarily, e.g. the third party `more-itertools` library would not be able to put its chained methods on list.

Luckily, if you want this kind of thing, Python is flexible enough to give you good approximations of it. See for instance https://github.com/dwt/fluent

This just makes the language less consistent, e.g. what about other collections? We shouldn't do "small and easy steps" if they're not worth doing on their own. And if you want to make a large change, you should try and get support on discuss.python.org and attempt to go through the PEP process. There's a high bar for changing this stuff, see for example PEP 616, which was a much smaller change (adding a couple highly desirable methods to `str`).

**Comment by rhettinger** [comment]
Please take this discussion to python-ideas.

**Comment by stevendaprano** [comment]
https://docs.python.org/3/faq/design.html#why-does-python-use-methods-for-some-functionality-e-g-list-index-but-functions-for-other-e-g-len-list
