### ISSUE TITLE
isinstance(True, int) or isinstance(False, int) results True always

### ISSUE THREAD

**Issue by kbogineni** [python/cpython#98868]
When I try to check instance type of bool object, it is always returning True, please check on this

I am using Python 3.10.8

**Comment by hugovk** [comment]
This is by design. The docs say this about Booleans (`bool`):

> These represent the truth values False and True. The two objects representing the values `False` and `True` are the only Boolean objects. The Boolean type is a subtype of the integer type, and Boolean values behave like the values 0 and 1, respectively, in almost all contexts, the exception being that when converted to a string, the strings `"False"` or `"True"` are returned, respectively. 

https://docs.python.org/3/reference/datamodel.html#index-10
