### ISSUE TITLE
Command.__call__() missing 1 required positional argument: 'context', threading library error

### ISSUE THREAD

**Issue by zSynctic** [python/cpython#98861]
Command.__call__() missing 1 required positional argument: 'context'

**Comment by hauntsaninja** [comment]
Hello, welcome to here!

This report doesn't contain enough information to understand what your problem is. Do you have a reproducible example? Or a full stack trace?

**Comment by zSynctic** [comment]
Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\account\Anaconda\envs\Discord\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\account\Anaconda\envs\Discord\lib\threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
TypeError: Command.__call__() missing 1 required positional argument: 'context'
![Screenshot 2022-10-30 094324](https://user-images.githubusercontent.com/71632495/198864375-cd6e30d9-559b-4c32-8707-498b7745038e.png)

**Comment by hauntsaninja** [comment]
You need to pass args to threading.Timer. This isn't the right forum to ask for generic help, try https://discuss.python.org/
