### ISSUE TITLE
(Pathlib): Paths With “~” Symbol Are Bugged

### ISSUE THREAD

**Issue by ChrisDev8** [python/cpython#98887]
**Path's with "~" character do not work as expected. This demo below shows how to recreate this error. I will update you when I upgrade to python 3.11.0.**

**Python Version**: 3.10.6

# Example Code

```python
from pathlib import Path

path1 = Path('~/.config/salt')
print(f'Relative Path: {str(path1)}')

path2 = Path('~/.config/salt').resolve()
print(f'Absolute Path: {str(path2)}')

print('Expected result: /Users/chris-dev/.config/salt')
```

# Returns

```
Relative Path: ~/.config/salt
Absolute Path: /Users/chris-dev/Workspace/Python/~/.config/salt
Expected result: /Users/me/.config/salt
```

**Comment by JelleZijlstra** [comment]
I think you're looking for `expanduser`: https://docs.python.org/3.10/library/pathlib.html#pathlib.Path.expanduser

**Comment by ChrisDev8** [comment]
Thanks, I did not see that! It would be nice if you add this to pathlib without having to call `pathlib.expanduser`.

**Comment by eryksun** [comment]
The "~" character is valid in filenames, so it can't have special significance in methods that handle paths in general.
