### ISSUE TITLE
`pathlib` assumes that `functools` might not have `lru_cache`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98884]
There's this line in `pathlib` right now:

https://github.com/python/cpython/blob/018b2483c422031ba5a6084238ab66ba44ea9fcf/Lib/pathlib.py#L218-L219

It was added 9 years ago as part of https://github.com/python/cpython/commit/31119e4f10d2905d0ed2c21a012dd9f45ec2fa61

But, `functools` at this moment always has this function. It is widely used in other modules.

**Comment by AlexWaygood** [comment]
Fixed in #98885. Thanks @sobolevn!
