### ISSUE TITLE
Typo in c-api/buffer docs

### ISSUE THREAD

**Issue by Riahiamirreza** [python/cpython#98891]
# Documentation

https://github.com/python/cpython/blob/main/Doc/c-api/buffer.rst

```
   .. c:member:: const char *format

      A *NUL* terminated string in :mod:`struct` module style syntax describing
      the contents of a single item. If this is ``NULL``, ``"B"`` (unsigned bytes)
      is assumed.
```
`NUL` should be replaced by `NULL`.

* PR: gh-98892

**Comment by kumaraditya303** [comment]
This is incorrect as here `NUL` refers to `0` terminated `char *` not `NULL` as pointer.
