### ISSUE TITLE
Memory leak if `math.dist` raises exception

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#98897]
Reproducer:
```py
import math
try:
    math.dist([1, 2], [3, 4, 5])
except ValueError:
    pass

```

Memory leak:
```console
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python -X showrefcount main.py 
[7 refs, 2 blocks]
```

Python Version: main at 9bdec0aa45

* PR: gh-98898

* PR: gh-98941

* PR: gh-98942

**Comment by vstinner** [comment]
I'm glad that ``./python -X showrefcount`` can now be used to detect memory leaks at exit :-) https://mail.python.org/archives/list/python-dev@python.org/thread/E4C6TDNVDPDNNP73HTGHN5W42LGAE22F/

**Comment by vstinner** [comment]
Do you want to propose a fix?
