### ISSUE TITLE
List Indexing and If Condition Always True

### ISSUE THREAD

**Issue by TawadrosGamal** [python/cpython#98907]
# Bug report

we have a list, no matter what is filled with and its length

in an, **IF condition** in the **indexing brackets,** **No Matter** what we put on the right or the left of the two **Equal Signs** the IF condition is always True
Even if it were string == int/double or double == string or number == number  or string == string

For an **Example** :
```
stop_words=['going']
print(stop_words[0])
if stop_words[-20=="going"]:
    print("*************************************************************************************************************************")
```
**Output** :
```
going
*************************************************************************************************************************
```

# My environment

- CPython versions tested 3.10.8:
- Windows 11 64:

**Comment by JelleZijlstra** [comment]
You put the `==` in the wrong place. `stop_words[-20=="going"]` evaluates `-20=="going"` first, which is False, so it does `stop_words[False]`. `False` is equal to 0, so you are checking `stop_words[0]`.

You probably want `if stop_words[-20] == "going":` instead.
