### ISSUE TITLE
`re` module: `search() vs. match()` section should mention `fullmatch()`

### ISSUE THREAD

**Issue by pekkaklarck** [python/cpython#98906]
The docs at https://docs.python.org/3/library/re.html#search-vs-match start with

> Python offers two different primitive operations based on regular expressions: [re.match()](https://docs.python.org/3/library/re.html#re.match) checks for a match only at the beginning of the string, while [re.search()](https://docs.python.org/3/library/re.html#re.search) checks for a match anywhere in the string (this is what Perl does by default).

but there has been [re.fullmatch()](https://docs.python.org/3/library/re.html#re.fullmatch) since Python 3.4. I believe the third method should be mentioned and should get its own examples as well.

* PR: gh-98916

* PR: gh-99912

* PR: gh-99913

**Comment by ericvsmith** [comment]
That seems like a good idea. Just this week I was looking at search vs. match, and completely forgot about fullmatch.

**Comment by ramvikrams** [comment]
Can I add the  ``` re.fullmatch() ```  and it's examples

**Comment by pekkaklarck** [comment]
Great that there's interest enhancing this! One thing to decide is should the section header be changed or not. Mentioning only search and match when there's also fullmatch would be odd, but the change would break possible internal and external links to this section. Internal links can be fixed as part of this change, though, and external ones can be preserved by adding an explicit link target with the old name. What approach has been used in this kind of situations earlier?

**Comment by akulakov** [comment]
I think it's fine to keep the section name, especially as fullmatch is a variant of `match()`.

**Comment by rhettinger** [comment]
+1

I would also like `fullmatch` become better known.

That said, a cross-reference between the two entries doesn't make sense.  The entries are already adjacent to one another.  And we don't want to get into the business of stylistic nudging by having one feature "advertise" another.

Instead, it would be better to beef up the examples to show off `fullmatch`.  Also the text for `match` and `fullmatch` should be expanded to draw a distinction between the them.  We already have verbiage about being different from a zero-length match. There should be further wording to highlight how `match` and `fullmatch` differ from one another.

**Comment by ericvsmith** [comment]
Thanks, @ramvikrams !

**Comment by ramvikrams** [comment]
> Thanks, @ramvikrams !

Thanks sir
