### ISSUE TITLE
smtplib: _get_socket_() function may be wrong

### ISSUE THREAD

**Issue by heeler-deer** [python/cpython#98902]
https://github.com/python/cpython/blob/57dd11038f22379770d9f16e527f787fdea978fd/Lib/smtplib.py#L308

when i look smtplib source code, i find this may get wrong:

```python
 def _get_socket(self, host, port, timeout):
        # This makes it simpler for SMTP_SSL to use the SMTP connect code
        # and just alter the socket connection bit.
        if timeout is not None and not timeout:
            raise ValueError('Non-blocking socket (timeout=0) is not supported')
```

it seems that raise valueerror will never be executed due to contradict of "timeout is not None" and "not timeout",
or it's just I understand wrong?

**Comment by akulakov** [comment]
If timeout=0, `not timeout` will be True, and `timeout is not None` will be also True. I'm not sure why it doesn't just compare to `0` value.

Closing as the logic works correctly when timeout=0.
