### ISSUE TITLE
Use yield from expression to explain chain.from_iterable

### ISSUE THREAD

**Issue by blv-brunoneyra** [python/cpython#98917]
# Documentation

`chain.from_iterable` explanation uses nested for loops to explain what it does. I believe using `yield from` would be slightly more pythonic:

### before

```python
      def from_iterable(iterables):
          # chain.from_iterable(['ABC', 'DEF']) --> A B C D E F
          for it in iterables:
              for element in it:
                  yield element
```

### after

```python
      def from_iterable(iterables):
          # chain.from_iterable(['ABC', 'DEF']) --> A B C D E F
          for it in iterables:
              yield from it
```

* PR: gh-98918

* PR: gh-98919

**Comment by ericvsmith** [comment]
While many people would use `yield from`, I’m not sure the proposed change is an improvement. More people are likely to understand the current code than the proposed new code.

**Comment by stevendaprano** [comment]
I agree with @ericvsmith

Swapping to `yield from` would probably be better code for experts but less informative to those who need the explanation.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but we will decline.
