### ISSUE TITLE
Lambda in list comprehension

### ISSUE THREAD

**Issue by ZeeshanQazi** [python/cpython#98927]
# Bug report

```
>>> [(lambda j: j+i) for i in range(1,12)][0](3)
14

vs.

>>> def g(x):
...     return lambda j: x + j;
...

>>> [g(i) for i in range(1,12)][0](3)
4

```
Is that supposed to be different?

# Your environment

Python 2.7.7 and Python 3.6.9

**Comment by saaketp** [comment]
https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

**Comment by ZeeshanQazi** [comment]
> https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

Thanks.
