### ISSUE TITLE
Improve syntax error for invalid imports

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#98931]
Is quite common to type `import x from y` instead of `from y import x`. We can easily offer a better error message in this case.

* PR: gh-98932

* PR: gh-105985

* PR: gh-105991

**Comment by martin-martin** [comment]
Hi @pablogsal thanks for all your work on error messages. Is a similar situation, but where someone attempts to import more than one name from a module something we'd like to support?

Currently this situation doesn't benefit from your updates:

```python
>>> import s, d from this
  File "<stdin>", line 1
    import s, d from this
                ^^^^
SyntaxError: invalid syntax
```

Just came across it, so I thought I'd leave a note. Thanks again!

**Comment by pablogsal** [comment]
> Hi @pablogsal thanks for all your work on error messages. Is a similar situation, but where someone attempts to import more than one name from a module something we'd like to support?

Thanks a lot for the kind words and the suggestion! I will give some though to see how hard is to support this. :)
