### ISSUE TITLE
Python configure step checks for unused readelf

### ISSUE THREAD

**Issue by serge-sans-paille** [python/cpython#98948]
# Bug report

During configure step, the presence of `readelf` on the host architecture is checked for, with an hard stop in case of cross compilation. The result of that check is never used. It got introduced in 5884449539510313c826d69835829c7957c7154a for a check that no longer exists, so it can be removed.

# Your environment

Linux 64 bit, Fedora 36, using main branch of cpython

* PR: gh-98949

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/8c4de57de9842a5330e8b8f18b02bd6865ce59bb
