### ISSUE TITLE
Mac/Extras.install.py，Can not filter osx .DS_Store file

### ISSUE THREAD

**Issue by zhangbo2012** [python/cpython#98940]
# Mac/Extras.install.py，Can not filter osx .DS_store file

Mac/Extras.install.py，Can not filter osx DS_store file

As

```python
if name == '.DS_store': return 0
```

But in OSX, Real File Name is .DS_Store, like this

```shell
(venv) zhangbo@zhangbodeMacBook-Pro a2 % ll -a
total 16
drwxr-xr-x  4 zhangbo  staff   128 Oct 22 17:34 .
drwxr-xr-x  8 zhangbo  staff   256 Oct 22 17:18 ..
-rw-r--r--@ 1 zhangbo  staff  6148 Oct 22 17:17 .DS_Store
drwxr-xr-x  3 zhangbo  staff    96 Oct 22 17:23 123
```

So we need update ``.DS_store``  to ``.DS_Store``

# Your environment

macOS 11.1 

* PR: gh-98943

* PR: gh-99528

**Comment by ronaldoussoren** [comment]
I've merged the PR into main.
