### ISSUE TITLE
Pass through -X options in test.bisect_cmd

### ISSUE THREAD

**Issue by tekknolagi** [python/cpython#98950]
# Feature or enhancement

`bisect_cmd` should read `sys._xoptions` and append to `sys.executable` like it already does with `subprocess._args_from_interpreter_flags` and `subprocess._optim_args_from_interpreter_flags`.

# Pitch

Other runtimes like Cinder use -X options to configure runtime behavior. We would like to pass through `-X jit`, for example, but `test.bisect_cmd` ignores it right now.

* PR: gh-98951

**Comment by kumaraditya303** [comment]
cc @vstinner

**Comment by encukou** [comment]
I guess another option would be for `bisect_cmd` itself to take `-X` options, and pass them to the subprocess.

**Comment by vstinner** [comment]
The `subprocess._args_from_interpreter_flags()` function now copies the `gil` flag.

bisect_cmd.py `python_cmd()` calls `subprocess._args_from_interpreter_flags()`, so we are good, no?

> Other runtimes like Cinder use -X options to configure runtime behavior. We would like to pass through -X jit, for example, but test.bisect_cmd ignores it right now.

Cinder should modify `subprocess._args_from_interpreter_flags()` to pass the `-X jit` option.

I propose to close the issue as fixed, are you ok with that?

**Comment by vstinner** [comment]
> Do you think it's a bad idea for bisect_cmd itself to take -X options, and pass them only to the subprocess?

The bisect_cmd usage is that you take a Python command line running the test suite and just replace `-m test` with `-m test.bisect_cmd`, and the bisection starts.

For example, `./python -X jit -m test test_mytest` becomes `./python -X jit -m test.bisect_cmd test_mytest` and it should just works.

Since `-X jit` is specific to Cinder, I would prefer to not take care of this flag in CPython `subprocess._args_from_interpreter_flags()`.

**Comment by vstinner** [comment]
@tekknolagi: Are you ok with that?

**Comment by tekknolagi** [comment]
Hi, sorry for the lack of response. I'm no longer working on Cinder these days and this is not a correctness issue so my stake in this is pretty much zero. Do whatever you think is reasonable for CPython!

**Comment by tekknolagi** [comment]
I'm happy to just close this issue and the PR unless you want to make a change.

**Comment by vstinner** [comment]
I closed the PR this issue. I suggest Cinder to pass `-X jit` either in `subprocess._args_from_interpreter_flags()` or in `subprocess._optim_args_from_interpreter_flags()`.
