### ISSUE TITLE
Translate code examples in documentation

### ISSUE THREAD

**Issue by humitos** [python/cpython#98964]
# Documentation

Hi! I wonder what are people's opinions about translating the code examples that appear all over the documentation? For example, https://github.com/python/cpython/blob/b3cafb60afeb2300002af9982d43703435b8302d/Doc/tutorial/interpreter.rst?plain=1#L111-L115 in Spanish, would be:

```rst
   >>> el_mundo_es_plano = True
   >>> if el_mundo_es_plano:
   ...     print("¡Ten cuidado de no caerte!")
   ...
   ¡Ten cuidado de no caerte!
```

In the way that the documentation is structured, this is not currently possible to do because these texts are not extracted by Sphinx.

In case there are enough positive replies to this issue and people _really want_ to translate them. How can we ensure that the translated version _works exactly as the original one_ in an automated way?

**Comment by AA-Turner** [comment]
Closing in favour of a Discourse topic. (We'd also need to support this in Sphinx.)
