### ISSUE TITLE
Iterating an IntFlag ignores 0 in cpython 3.11

### ISSUE THREAD

**Issue by bdraco** [python/cpython#98976]
# Bug report

Minimal reproducer that fails on 3.11 but works on older versions.

```python
from enum import IntFlag


class MessageFlag(IntFlag):
    ZERO = 0


MESSAGE_FLAG_MAP = {field.value: field for field in MessageFlag}

assert 0 in MESSAGE_FLAG_MAP, "0 is missing from the map"
```

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: MacOS Ventura

**Comment by ethanfurman** [comment]
In 3.11 flag aliases are not included in iterations, and `0`-valued flags are considered aliases.

**Comment by bdraco** [comment]
closing this as by design. Will adjust the downstream code.

thanks
