### ISSUE TITLE
why last output varies in this block of python code?

### ISSUE THREAD

**Issue by munavvar-codes** [python/cpython#98970]
I can understand the first output of the first example, that is 2 as the i += 1 makes value to 2 than print calls, I also understand the second example's first output that is 1 because print calls i then increment begins. But, what about the end, as we have already defined
"while i < 6:" then why first example return the last output as 6 (why its not stopped to 5).

`i = 1
while i < 6:
    i += 1
    print(i)  # Print output after i increment, see the result
>> The output is -
2
3
4
5
6

i = 1
while i < 6:
    print(i)  # Print output before i increment, see the result
    i += 1
>> The output is -
1
2
3
4
5`

**Comment by zware** [comment]
Hi @munavvar-codes, and welcome to Python.

This is not a help forum, but is rather an issue tracker for keeping track of bugs in Python itself.  Please ask your question instead on [discuss.python.org](https://discuss.python.org/c/help/7) where there are plenty of helpful people who can lead you to understanding.
