### ISSUE TITLE
tkinter: variable gets corrupted when defined twice with both name and value

### ISSUE THREAD

**Issue by vandersluispe** [python/cpython#99008]
The second time the same variable is defined, with both name and value arguments, it becomes unusable:
```
import tkinter as tk
master_window = tk.Tk()

string_variable = tk.StringVar(name="textvariable", value="value")
print(string_variable.get())

string_variable = tk.StringVar(name="textvariable", value="value")
print(string_variable.get())
```
results in
```
value
Traceback (most recent call last):
  File "C:\temp\PythonScripts\tkintervarbug.py", line 8, in <module>
    print(string_variable.get())
  File "C:\Toepassingen\Python310\lib\tkinter\__init__.py", line 544, in get
    value = self._tk.globalgetvar(self._name)
_tkinter.TclError: can't read "textvariable": no such variable
```
Tested on:
```
Microsoft Windows [Version 10.0.19042.2130]
```
with
```
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)] on win32
```

**Comment by serhiy-storchaka** [comment]
Constructor of `StringVar` sets the corresponding Tcl variable. Destructor of `StringVar` removes the Tcl variable.

In you case you first create a `StringVar` instance and save it in `string_variable`. Then you create yet one `StringVar` instance and save it in the same Python variable. When you do this, the old `StringVar` instance has no longer references and it will be destroyed. The destructor removes the Tcl variable.

Save the new `StringVar` instance in a different Python variable, or destroy it before creating a new instance with the same name, or better do not reuse the same name for variables.
