### ISSUE TITLE
CI: "Tests / Check if generated files are up to date" failed

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#99016]
CI: "Tests / Check if generated files are up to date" failed because some source generating scripts are not compatible with Python 3.8.

There is no reason to not make them compatible with Python 3.8.

* PR: gh-99017

* PR: gh-99693

**Comment by JelleZijlstra** [comment]
I fixed this in #98988: we were incorrectly skipping 3.11. However, we should probably also make the script compatible with 3.8.
