### ISSUE TITLE
Minor doc issue: dataclasses.KW_ONLY not documented as inspected by dataclass()

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#99026]
# [dataclasses](https://docs.python.org/3.11/library/dataclasses.html) documentation

According to [dataclasses](https://docs.python.org/3.11/library/dataclasses.html) documentation, the only places "where [dataclass()](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.dataclass) inspects a type annotation" are:
* [Class variables](https://docs.python.org/3.11/library/dataclasses.html#class-variables) "One of two places"
* and [Init-only variables](https://docs.python.org/3.11/library/dataclasses.html#init-only-variables) "The other place"

However, [dataclasses.KW_ONLY](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.KW_ONLY) logically must be (and [actually is](https://github.com/python/cpython/blob/3.11/Lib/dataclasses.py#L945)) the third place.

It's only a minor inconsistency, but it can be easily remedied (in a future-proof way, if ever a fourth, etc. place would be added) by changing:
* [Class variables](https://docs.python.org/3.11/library/dataclasses.html#class-variables) to "One of *few* places" 
* and [Init-only variables](https://docs.python.org/3.11/library/dataclasses.html#init-only-variables) to "*An*other place"

(*italics* only to show the difference, not intended in the change)

### Linked PRs
* gh-100798
* gh-100799
* gh-100800

**Comment by exitflynn** [comment]
can i work on this one? :cowboy_hat_face:

**Comment by ericvsmith** [comment]
Sure. Create a PR and I'll look at it.
