### ISSUE TITLE
Outdated info about encoding in "datetime"

### ISSUE THREAD

**Issue by wjandrea** [python/cpython#99032]
In the `datetime` docs, there's a [Technical Detail](https://docs.python.org/3/library/datetime.html#technical-detail) note that seems to say that `strftime()` will return an encoded string (i.e. `bytes`), but actually it returns a Unicode string as of Python 3.0 (i.e. `str`).

> 1. Because the format depends on the current locale, care should be taken when making assumptions about the output value. Field orderings will vary (for example, “month/day/year” versus “day/month/year”), and the output may contain Unicode characters encoded using the locale’s default encoding (for example, if the current locale is `ja_JP`, the default encoding could be any one of `eucJP`, `SJIS`, or `utf-8`; use `locale.getlocale()` to determine the current locale’s encoding).

---

(I jumped the gun by submitting a PR for this (#93365) before an issue.)

* PR: gh-93365

* PR: gh-103788

**Comment by JelleZijlstra** [comment]
All PRs merged, thank you!
