### ISSUE TITLE
Windows build fails with TypeError

### ISSUE THREAD

**Issue by ucodery** [python/cpython#99041]
# Bug report

When building python 3.11 on windows, if the version of python already present for bootstrapping is too old, the build fails. This appears to be because `find_python.bat` only enforces that the python version is `>=3.8` while deepfreeze.py uses 3.9 only features (and in fact, not hit upon here, when using a virtualenv the version of python is not in any way checked).

I am not sure if core devs would prefer that `find_python.bat` enforce python `>=3.9` or that any 3.9 features be taken out of build tools for this release cycle.

Sample failure after running `msbuild` with `%HOST_PYTHON%` set specifically to `C:\build\deps\python3.EXE` which is version 3.8:
```
       FindPythonForBuild:

         "C:\build\deps\python3.EXE"

         Using PythonForBuild="C:\ActiveState\APy\python3.EXE"

       _RebuildDeepFrozen:

         . . .

         Traceback (most recent call last):

           File "C:\builds\sources\3e560ba6-c6c6-580d-8dcb-ffa1437fe7ba\Python-3.11.0\Tools\scripts\deepfreeze.py", line 460, in <module>

             def generate(args: list[str], output: TextIO) -> None:

         TypeError: 'type' object is not subscriptable


```

**Comment by AlexWaygood** [comment]
@zooba, thoughts on backporting #94281?

**Comment by zooba** [comment]
Done (once CI finishes)
