### ISSUE TITLE
quopri: Unnecessary conditional import

### ISSUE THREAD

**Issue by srittau** [python/cpython#99053]
# Possible Refactoring

The `quopri` module conditionally imports `binascii` and uses custom code if `binascii` can't be found. For example, the `encode()` function currently has 60 lines (including empty lines and the docstring), of which only 47 lines are dedicated to the workaround:

https://github.com/python/cpython/blob/e9ac890c0273aee413aa528cc202c3efa29f1d7a/Lib/quopri.py#L44-L104

This is essentially dead code, since I don't think there are any (sane) scenarios nowadays, where `binascii` is not available. I recommend to remove the conditional import and dead code. I'm willing to write a PR.

# Your environment

- CPython versions tested on: Seen on cpython HEAD as of 2022-11-03

**Comment by corona10** [comment]
> This is essentially dead code, since I don't think there are any (sane) scenarios nowadays, where binascii is not available

No, some of the alternative implementations use the CPython library directly, and some of them don't have the implementation for binsacii, I would like to maintain the code as-is.
