### ISSUE TITLE
Clearing memory on specific variables to keep performance

### ISSUE THREAD

**Issue by AhmedAbdelazizSeif** [python/cpython#99055]
# Feature or enhancement

Ever wondered if you can use a function than the garbage collector to remove unwanted variables on your script? This is exactly what this class does. You can always control variables in memory either clear the variables you want, or keep only these variables for further use

# Usage

Variable Delete Class usage can be used using the following steps as for 
## - Clear Variables 
```
if __name__ == '__main__':
    a = 1
    b = 2
    c = 3
    vd.clear(vd, [a, b, c])
```
if you ever try to ```print(globals())```
This outputs 
``` {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x000001F4A9736CD0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '~/main.py', '__cached__': None, 'vd': <class '__main__.vd'>}```
so clearly if you ever try to print **for example** _variable "a"_ a traceback is returned as ```NameError: name 'a' is not defined``` and memory is cleared 

## - Exclude Variable Clearing
Instead, you may need to clear all variables on a script but exclude specific variables 
Here, you can use the function ```exclude()``` as follows 
```
    a = 1
    b = 2
    c = 3
    vd.exclude(vd,[a, c])
```
if you ever try printing the globals this time it outputs 
```{'a': 1, 'c': 3}```
it only keeps variables on a data called

## Notes on Usage
on both functions `clear ` and `exclude`, you can either use variable as [a,b,c] or as ['a','b','c'], or if you are clearing a single variable you can just use `clear(vd, a)` but this could be just achieved by `del a`, but the exclude this comes handy as you can follow the same instructions by `exclude(vd,a)` or `exclude(vd,'a')`

# Previous discussion

<a href="https://discuss.python.org/t/clearing-memory-on-specific-variables-to-keep-performance/20694">Discussed as an idea on python forum</a>

**Comment by AlexWaygood** [comment]
I'm closing this issue for now, since the referenced post on discuss.python.org was only created today. If there's significant interest in this feature from other people on [the discourse thread](https://discuss.python.org/t/clearing-memory-on-specific-variables-to-keep-performance/20694), feel free to open a new issue; for now, this is a little premature :)
