### ISSUE TITLE
`test_weakref` contains two identical test cases

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#99051]
There are two identical test cases right now:

https://github.com/python/cpython/blob/e9ac890c0273aee413aa528cc202c3efa29f1d7a/Lib/test/test_weakref.py#L601-L612

and:

https://github.com/python/cpython/blob/e9ac890c0273aee413aa528cc202c3efa29f1d7a/Lib/test/test_weakref.py#L655-L664

The only difference is that the second one used to test old style classes, which does not exist anymore.

I think, it should be removed: not to cause confusion for the readers.

* PR: gh-99052

* PR: gh-99170

* PR: gh-99171

**Comment by hauntsaninja** [comment]
Thanks for fixing!
