### ISSUE TITLE
cannot install and import kivy module, get ModuleNotFound error

### ISSUE THREAD

**Issue by 3n3code** [python/cpython#99050]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by sobolevn** [comment]
This does not look like a valid bug report at the moment, sorry.

Please, fill all the required details.

**Comment by ronaldoussoren** [comment]
I'm closing this issue as there's not enough information here.
