### ISSUE TITLE
Broken example for `functools.singledispatchmethod`

### ISSUE THREAD

**Issue by rocapp** [python/cpython#99074]
# Documentation

- **Python version:** 3.8.10
- **Platform:** Ubuntu (Windows Subsystem Linux 2)

I encounter the following error when trying the [`@classmethod` example for `functools.singledispatchmethod`](https://docs.python.org/3.8/library/functools.html#:~:text=class%20Negator%3A%0A%20%20%20%20%40singledispatchmethod%0A%20%20%20%20%40classmethod).

The error:

```<python>
TypeError: Invalid first argument to `register()`: <classmethod object at 0x7f080365b5b0>. Use either `@register(some_class)` or plain `@register` on an annotated function.
```

**Comment by AlexWaygood** [comment]
This is fixed on 3.9+: see #83860. 3.8 now only accepts security-related patches, so we won't be fixing this (or changing the documentation) for Python 3.8, I'm afraid.
