### ISSUE TITLE
PTHREAD_SCOPE_SYSTEM configure check fails with Clang 16 (-Wimplicit-int)

### ISSUE THREAD

**Issue by thesamesam** [python/cpython#99086]
# Bug report

The PTHREAD_SCOPE_SYSTEM configure check lacks `int` before the `main()` definition and causes Clang to emit a `-Wimplicit-int` warning. This warning becomes an error by default with Clang 16+.

# Your environment

- CPython versions tested on: master
- Operating system and architecture: Gentoo Linux amd64
- Clang 16 (or Clang 15 with `-Werror=implicit-int -Werror=implicit-function-declaration`)

* PR: gh-99085

* PR: gh-99118

* PR: gh-99119

* PR: gh-99406

* PR: gh-99919

* PR: gh-99920

**Comment by thesamesam** [comment]
It's relevant all the way down, including Python 2.7, yes.

**Comment by kloczek** [comment]
So my understanding is that this will be added (just checked 3.8 branch and I don't see anything).

**Comment by thesamesam** [comment]
I don't have any authority in CPython. I'd say this is worth backporting to all supported (even security-only) branches personally given they either won't be buildable with modern compilers or will misbehave.
