### ISSUE TITLE
Calling py works but not py with arguments

### ISSUE THREAD

**Issue by solomoncyj** [python/cpython#99097]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on: `Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32`
- Operating system and architecture: win 10 22H2 x64

when i run only `py`
```
py
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
when i run `py "./setup.py" instal`
```
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases
```

**Comment by eryksun** [comment]
It seems that "setup.py" is trying to run "python" or "python3". However, it's finding the the Windows app that launches the store. Disable the "python.exe" and "python3.exe" app execution aliases in the apps & features settings. Then modify the Python 3.11 installation to select the option to add Python to environment variables. This adds a "python" command to the search path, but not "python3".
