### ISSUE TITLE
Implement PEP 684: A Per-Interpreter GIL

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#99113]
While PEP 684 is not accepted yet (and *could* get rejected, of course), it would be helpful to have an issue against which I can start creating draft PRs for the implementation.

This issue isn't for all the prerequisite work for a per-interpreter GIL, rather just the implementation of what's actually specified in the PEP.  The rest is happening separately.

(Also see my checklist: https://github.com/ericsnowcurrently/multi-core-python/wiki/0-The-Plan)

* PR: gh-99114

* PR: gh-104203

* PR: gh-104204

* PR: gh-104205

* PR: gh-104206

* PR: gh-104208

* PR: gh-104209

* PR: gh-104210

* PR: gh-107520

* PR: gh-107523

* PR: gh-123079

**Comment by ericsnowcurrently** [comment]
Docs updates:

* add docs for `Py_NewInterpreterFromConfig()` and `PyInterpreterConfig`
* https://github.com/python/cpython/pull/99114#discussion_r1186116258
* ...

**Comment by erlend-aasland** [comment]
@ericsnowcurrently, do you still want to keep this open? IIRC, most of the follow-up work is tracked in separate issues.

**Comment by ericsnowcurrently** [comment]
Yeah, I think you're right.
