### ISSUE TITLE
Improve NameError error suggestion for instances

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#99139]
If we are in a method and a NameError is raised for the name X, first check if `X` is an attribute of the instance as `self.X` is likely more common than whatever closest match we find in the scope.

* PR: gh-99140

**Comment by hauntsaninja** [comment]
This is great! I learnt C++ before Python so I used to forget self all the time when I first started programming in Python. Thank you!

**Comment by sobolevn** [comment]
Looks awesome! Lots of begginers going to love that!

What about a case like:

```python
class Some:
   x = 1
   @classmethod 
   def method(cls):
       x + 2  # Should be cls.x
```

Do we care to support it? 🤔

**Comment by pablogsal** [comment]
> Looks awesome! Lots of begginers going to love that!
> 
> 
> 
> What about a case like:
> 
> 
> 
> ```python
> 
> class Some:
> 
>    x = 1
> 
>    @classmethod 
> 
>    def method(cls):
> 
>        x + 2  # Should be cls.x
> 
> ```
> 
> 
> 
> Do we care to support it? 🤔 

Thanks for the proposal!

I will consider it but is unlikely that will happen as we are not interested in supporting all possible variations of this, specially since the name of the variable here (cls) is less standardised than "self" and is less common.

Also, this will force us to distinguish the type of function to avoid inspecting random variables called "cls".
