### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by ypradat** [python/cpython#99159]
# Bug report

Launching today (06 Nov 2022) a snakemake pipeline on a linux machine through a conda environment (see below)

```
name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba
  - pandas
  - snakemake
```
returns

## Traceback

```
  File "/home/[...]/miniconda3/envs/snakemake/lib/python3.11/site-packages/snakemake/scheduler.py", line 109, in __init__
    from ratelimiter import RateLimiter
  File "/home/[...]t/miniconda3/envs/snakemake/lib/python3.11/site-packages/ratelimiter.py", line 36, in <module>
    class RateLimiter(object):
  File "/home/[...]/miniconda3/envs/snakemake/lib/python3.11/site-packages/ratelimiter.py", line 127, in RateLimiter
    __aexit__ = asyncio.coroutine(__exit__)
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

# Your environment

CPython versions tested on:

- miniconda3: [Miniconda3-py38_4.12.0-Linux-x86_64.sh](https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh)
- conda env (raises error)
```
+ mamba                             1.0.0  py311h3072747_2      conda-forge/linux-64
+ pandas                            1.5.1  py311h8b32b4d_1      conda-forge/linux-64
+ python                           3.11.0  ha86cf86_0_cpython   conda-forge/linux-64 
+ snakemake                        7.18.1  hdfd78af_0           bioconda/noarch
```
- Operating system and architecture: Debian GNU/Linux 11 (bullseye)

Executing the same snakemake pipeline within a python 3.8 conda environment (see below) runs without error.
- conda env  (no error)
```
+ mamba                             1.0.0  py311h3072747_2      conda-forge/linux-64
+ pandas                            1.5.1  py311h8b32b4d_1      conda-forge/linux-64
+ python                           3.8.13  ha86cf86_0_cpython   conda-forge/linux-64
+ snakemake                        7.18.1  hdfd78af_0           bioconda/noarch
```

**Comment by JelleZijlstra** [comment]
`asyncio.coroutine` was removed in 3.11, so packages need to stop using it. Your error comes from `ratelimiter`, which has an open issue about this but the package looks unmaintained: https://github.com/RazerM/ratelimiter/issues/10. Snakemake is exploring replacing the dependency instead: https://github.com/snakemake/snakemake/issues/1952.
