### ISSUE TITLE
3.10 asyncio still uses deprecated loop argument

### ISSUE THREAD

**Issue by ilayanyatto72733** [python/cpython#99167]
- CPython versions tested on: 3.10.8-amd64
- Operating system and architecture: Win10x64

# Bug report

Minimal example will be so big that will create more questions.
Running code is fork of yt-dlp, located at https://github.com/redraskal/yt-dlp/tree/fix/tiktok-user

```
c:\temp>yt-dlp https://www.tiktok.com/@meme
[tiktok:user] meme: Downloading user embed
[tiktok:user] 7162754035781586219: Downloading video feed
[tiktok:user] Downloading signature function
Executing <Task finished name='Task-1' coro=<TikTokUserIE._video_entries_api() done, defined at C:\temp\yt_dlp\extractor\tiktok.py:616> exception=DeprecationWarning('remove loop argument') created at C:\temp\python3\lib\asyncio\tasks.py:636> took 0.688 seconds
ERROR: remove loop argument
Exception ignored in atexit callback: <function Launcher.launch.<locals>._close_process at 0x0000020D297654F0>
Traceback (most recent call last):
  File "C:\temp\python3\lib\site-packages\pyppeteer\launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "C:\temp\python3\lib\asyncio\base_events.py", line 624, in run_until_complete
    self._check_closed()
  File "C:\temp\python3\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Launcher.killChrome at 0x0000020D2982E210>
Traceback (most recent call last):
  File "C:\temp\python3\lib\warnings.py", line 506, in _warn_unawaited_coroutine
    warn(msg, category=RuntimeWarning, stacklevel=2, source=coro)
RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
Exception ignored in: <function Popen.__del__ at 0x0000020D26A98C00>
Traceback (most recent call last):
  File "C:\temp\python3\lib\subprocess.py", line 1072, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 14680 is still running
```

which is refers to
https://github.com/python/cpython/blob/3.10/Lib/asyncio/tasks.py#L636
called via
https://github.com/redraskal/yt-dlp/blob/fix/tiktok-user/yt_dlp/extractor/tiktok.py#L618
using function `_download_webpage()` from
https://github.com/redraskal/yt-dlp/blob/fix/tiktok-user/yt_dlp/extractor/common.py#L1056

if `python/lib/asincio/tasks.py` function `ensure_future()` fixed next error is

```
yt-dlp https://www.tiktok.com/@meme
[tiktok:user] meme: Downloading user embed
[tiktok:user] 7162754035781586219: Downloading video feed
[tiktok:user] Downloading signature function
Executing <Task finished name='Task-1' coro=<TikTokUserIE._video_entries_api() done, defined at C:\temp\yt_dlp\extractor\tiktok.py:616> exception=DeprecationWarning('remove loop argument') created at C:\temp\python3\lib\asyncio\base_events.py:628> took 1.156 seconds
ERROR: remove loop argument
Exception ignored in atexit callback: <function Launcher.launch.<locals>._close_process at 0x000001A378FA55A0>
Traceback (most recent call last):
# skipped
```

Error points at function `run_until_complete()` in
https://github.com/python/cpython/blob/3.10/Lib/asyncio/base_events.py#L628

**Comment by kumaraditya303** [comment]
> if python/lib/asincio/tasks.py function ensure_future() fixed next error is

What "fix" are you applying? 

From what I can tell this is not an `asyncio` bug but a bug in library as it not waiting for the process to exit before closing the loop.

**Comment by Bo98** [comment]
> ```
> yt-dlp https://www.tiktok.com/@meme
> [tiktok:user] meme: Downloading user embed
> [tiktok:user] 7162754035781586219: Downloading video feed
> [tiktok:user] Downloading signature function
> Executing <Task finished name='Task-1' coro=<TikTokUserIE._video_entries_api() done, defined at C:\temp\yt_dlp\extractor\tiktok.py:616> exception=DeprecationWarning('remove loop argument') created at C:\temp\python3\lib\asyncio\base_events.py:628> took 1.156 seconds
> ERROR: remove loop argument
> Exception ignored in atexit callback: <function Launcher.launch.<locals>._close_process at 0x000001A378FA55A0>
> Traceback (most recent call last):
> # skipped
> ```
> 
> Error points at function `run_until_complete()` in https://github.com/python/cpython/blob/3.10/Lib/asyncio/base_events.py#L628

That's from https://github.com/aaugustin/websockets/blob/2cbb8134acfa8b56aba5c40f0479f12434104a62/src/websockets/legacy/client.py#L488

which in turn is from https://github.com/pyppeteer/pyppeteer/blob/0fd15a7c4b2d3aeaaf6da65da9033c150de0d3cb/pyppeteer/connection.py#L44

and initially set here: https://github.com/pyppeteer/pyppeteer/blob/7245ee0bccd97d43e45b801319dd6cbae860292a/pyppeteer/launcher.py#L77
