### ISSUE TITLE
Typo in python.gram?

### ISSUE THREAD

**Issue by valq7711** [python/cpython#99176]
https://github.com/python/cpython/blob/bd221c01ddcd2cad102133611fab3569a99680b0/Grammar/python.gram#L690-L695

[`L692:`](https://github.com/python/cpython/blob/bd221c01ddcd2cad102133611fab3569a99680b0/Grammar/python.gram#L692) Shouldn't it be `comparison` instead of `inversion`? like
```
|  'not' a=comparison
```

I just follow the same logic for the previous rules:
https://github.com/python/cpython/blob/bd221c01ddcd2cad102133611fab3569a99680b0/Grammar/python.gram#L677-L695

**Comment by hauntsaninja** [comment]
Not a grammar expert, but `not not not False` is valid Python

**Comment by valq7711** [comment]
Oh, well then it is ok
