### ISSUE TITLE
Resurrection, ante-mortem debugging, time-travel debugging, interactive debugging, find and fix the bug then continue execution

### ISSUE THREAD

**Issue by James4Ever0** [python/cpython#99187]
# Feature or enhancement

Stop at the buggy code for a prompt for user intervention. Users can put new code right at the spot where the problem occurs, remove any lines which will cause trouble, then continue execution without restarting the process.

# Pitch

Suppose there's some code running for 4 hours and suddenly popping up for a bug, losing all the context. Traceback is there, and all you can do is some guess work trying to fix the bug and rerun the code for another 4 hours then hope for no bugs.

With resurrection debugging, code will stop when bug happens, and you can fix the bug, persist your patch to the disk with all context avaliable.

# Previous discussion

[Discussed in python forum](https://discuss.python.org/t/exec-with-return-keyword/19916/27)

For anyone wants more links: [My note on this topic](https://github.com/James4Ever0/notes/blob/2c15e8508805188c618106ab9c2f9a63f5b4f4a1/Python%20Bytecode%2C%20Time%20Travel%20Debugging%2C%20Resurrection%2C%20Ante-Mortem%20Debugging%2C%20Interactive%20Debugging%2C%20Resume%20after%20Exception%2C%20P.md)

# Important notice

This might be some historical issues related to exception handling inherited from C++. Common lisp diverges from C's "termination semantics" to "resumption semantics", and that's the feature I requested.

**Comment by JosephSBoyle** [comment]
The scenario described in your pitch is something that I've experienced a few times..

I wonder if it's possible to somehow open a `breakpoint` where the offending exception is raised, from there I imagine the user could do the rest?

**Comment by JosephSBoyle** [comment]
After some thinking, it occurred to me we could use a flag mechanism similar to the existing "-i" flag that enters interactive mode once the program finishes.

**Comment by carljm** [comment]
This feels a bit too vague and non-actionable to me for it to be useful as an issue. At least two quite different (if possibly related by usage scenario) features are described here: 1) the ability to pause and enter a debugger when an exception is raised, 2) the ability to skip/remove lines of code when in the debugger, and maybe 3) some kind of persistence of state/code to disk, which isn't described in enough detail for me to understand what is being proposed.

Feature (1) is already possible today, I've used programs that implement it; you catch exceptions and call `pdb.pm()` if one is raised. It doesn't require changes to the language or to the standard library.

Feature (2) I highly suspect is also already possible today via a `set_trace` function, though I haven't tried implementing it.

Both of these seem like experimental features that can and should be first implemented in an external debugger project/library, and if they prove to be both feasible and popular, could be considered for integration into Python/pdb. I think the most practical route to achieve your aims would be to try to implement something usable by others, to more clearly demonstrate both the practicality and the value. If you run into specific limitations that make it impossible to implement what you want as a library, those could make for good focused, actionable issues.
