### ISSUE TITLE
datetime.date.fromisoformat('20191204') does not work using python 3.8.0

### ISSUE THREAD

**Issue by AnttiGH** [python/cpython#99207]
When using Using python 3.8.0
Example presented here https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat does not seem to work:

>>> date.fromisoformat('20191204')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid isoformat string: '20191204'

**Comment by hugovk** [comment]
Yes, note the [docs](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) say:

> _Changed in version 3.11:_ Previously, this method only supported the format YYYY-MM-DD.

So it doesn't work with Python 3.7-3.10:

```console
$ python3.7 -c "from datetime import date; print(date.fromisoformat('20191204'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Invalid isoformat string: '20191204'
$ python3.8 -c "from datetime import date; print(date.fromisoformat('20191204'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Invalid isoformat string: '20191204'
$ python3.9 -c "from datetime import date; print(date.fromisoformat('20191204'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Invalid isoformat string: '20191204'
$ python3.10 -c "from datetime import date; print(date.fromisoformat('20191204'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Invalid isoformat string: '20191204'
```

But it does on 3.11 and 3.12a1:

```console
$ python3.11 -c "from datetime import date; print(date.fromisoformat('20191204'))"
2019-12-04
$ python3.12 -c "from datetime import date; print(date.fromisoformat('20191204'))"
2019-12-04
```

**Comment by ronaldoussoren** [comment]
That's correct. The 3.8 documentation mentions that its implementation only supports "YYYY-mm-dd", the 3.11 documentation alludes to that in the "changed in 3.11" comment at the end of the documentation for isodateformat. Support for the other formats was added in 3.11
