### ISSUE TITLE
sysconfig.get_config_vars() fails on Windows when dynamic loading is disabled

### ISSUE THREAD

**Issue by philthompson10** [python/cpython#99201]
# Bug report

A change was made in Python v3.8 where, on Windows, EXT_SUFFIX was initialised from the first element of the list returned by _imp.extension_suffixes(). In previous versions this was hardcoded to '.pyd'. When HAVE_DYNAMIC_LOADING is not defined the list of suffixes will always be empty resulting in a IndexError exception being raised.

# Your environment

Windows. Python v3.8 to v3.11.

* PR: gh-99274

**Comment by FFY00** [comment]
Fixed by #99274
