### ISSUE TITLE
Adding iterables to Counter class object

### ISSUE THREAD

**Issue by ShivKJ** [python/cpython#99245]
# Feature or enhancement

Enabling adding iterables to Counter, for example,

```python
from collections import Counter
cnt = Counter('abc')

print(cnt + ['a', 'b', 'b', 'd']) # should print: Counter({'a': 2, 'b': 3, 'c': 1, 'd': 1})
``` 
As of now, adding list (or any iterable) will raise the following error,

```
TypeError: unsupported operand type(s) for +: 'Counter' and 'list'
```

# Pitch

`Counter` is very useful class which can be used to keep/change frequency/occurrence of an item. Default occurrence of an item is `0`.

To increase occurrence of item, we can use `cnt['a'] = cnt['a'] + 1`. We could also use `cnt.update(['a'])` or `cnt.update('a')` but there methods change state of `cnt` as well.

There are some overloaded methods such as `+`, which can be used as `cnt + Counter(['a'])` to create a new copy and add the other `counter` object to it. This is not very intuitive. We should be able to add any iterable (list, set, tuple etc).

Let me know what do you think of enabling adding any iterable to `Counter` class object.

**Comment by sobolevn** [comment]
> We could also use cnt.update(['a']) or cnt.update('a') but there methods change state of cnt as well.

Isn't your usecase already covered by `copy` + `update`?

```python
>>> from collections import Counter
>>> c = Counter('abc')
>>> c.update('ab')

>>> c1 = c.copy()
>>> c1.update('de')

>>> c
Counter({'a': 2, 'b': 2, 'c': 1})
>>> c1
Counter({'a': 2, 'b': 2, 'c': 1, 'd': 1, 'e': 1})
```

In my opinion using `+` to concat collections of different types is not intuative: you cannot predict the resulting type without looking at the docs :(
This will also make `__add__` and `__radd__` difference significant: `'abc' + c` is a type error, while `c + 'abc'` is `Counter`

Several more questions:
1. I think that calling `Counter` can be the last step. In any way, users can create any collections and then call `Counter` on them. Can this be considered as a proper solution?
2. What is the motivation to create new counters from existing ones? Why one is not enough?
3. How often is this use-case? 
4. What are the alternatives? Like `.copy()` + `.update()` I've shown

**Comment by ShivKJ** [comment]
> This will also make __add__ and __radd__ difference significant: 'abc' + c is a type error, while c + 'abc' is Counter

Understood. Adding iterable to a `Counter` class object is not possible as it will create inconsistencies.


> I think that calling Counter can be the last step. In any way, users can create any collections and then call Counter on them. Can this be considered as a proper solution?

My motivation was to have a one-liner. 

> What is the motivation to create new counters from existing ones? Why is one not enough?

I was proposing for not creating a new Counter but enhancing it.

> How often is this use-case?

I frequently encounter this.

> What are the alternatives? Like .copy() + .update() I've shown
One way to use the overloading operation `+`

```python
c + Counter('de')
```
