### ISSUE TITLE
IntFlag ~ operator returns 0 instead of inverse for combined fields

### ISSUE THREAD

**Issue by rt121212121** [python/cpython#99260]
# Bug report

As of Python 3.11 combined fields for an `IntFlag`, `~` returns `0` instead of the inverse.

Reproduction on 3.11 (see field `MASK` for what I mean by combined field):
```
>py -3.11
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from enum import IntFlag
>>> class MyFlags(IntFlag):
...     A = 1 << 0
...     B = 1 << 1
...     MASK = A | B
...
>>>
>>> MyFlags.A
<MyFlags.A: 1>
>>> MyFlags.B
<MyFlags.B: 2>
>>> MyFlags.MASK
<MyFlags.MASK: 3>
>>> ~MyFlags.MASK # <------------------ CHANGED BEHAVIOUR
<MyFlags: 0>
>>> ~MyFlags.A
<MyFlags.B: 2>
```

Existing behaviour for 3.10 (see field `MASK` for what I mean by combined field):

```
>py -3.10
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from enum import IntFlag
>>> class MyFlags(IntFlag):
...     A = 1 << 0
...     B = 1 << 1
...     MASK = A | B
...
>>> MyFlags.A
<MyFlags.A: 1>
>>> MyFlags.B
<MyFlags.B: 2>
>>> MyFlags.MASK
<MyFlags.MASK: 3>
>>> ~MyFlags.MASK # <---------------- EXISTING BEHAVIOUR
<MyFlags.-4: -4>
>>> ~MyFlags.A
<MyFlags.B: -2>
```

# Your environment

Windows Python 3.11 installer (python-3.11.0-amd64.exe) from python.org.
Windows 11 Home

**Comment by ethanfurman** [comment]
This is an intentional change: `MASK` is a combination of all flags, and the inverse of all the flags is none of the flags, or zero.

**Comment by rt121212121** [comment]
From my perspective that is a subjective choice that breaks existing code, but at this point it is baked in as a breaking change and there's nothing I can do about it.
