### ISSUE TITLE
configure script lies about where it's looking for ssl.h

### ISSUE THREAD

**Issue by wimglenn** [python/cpython#99278]
I was trying to use the `--with-openssl` option and saw:

    checking for openssl/ssl.h in /path/to/openssl-1.1.1g/include... no

But that's exactly where it was, file existing at `/path/to/openssl-1.1.1g/include/openssl/ssl.h`

I had to look in the configure file and see that it was actually tacking on include itself, so you _don't_ need to specify that.

* PR: gh-99279

**Comment by BeyondEvil** [comment]
THANK YOU!

This got me a step closer to getting python3 working in an isolated environment.

Unfortunately, I'm still suffering from certificate verify failed: self-signed certificate in certificate chain

**Comment by serhiy-storchaka** [comment]
Fixed in #89886.
