### ISSUE TITLE
Add link to the first article about Python

### ISSUE THREAD

**Issue by maskalev** [python/cpython#99276]
# Documentation

Add link to the first article about Python (https://ir.cwi.nl/pub/18204) to part about Python articles (https://docs.python.org/3/faq/general.html#are-there-any-published-articles-about-python-that-i-can-reference)

### Linked PRs
* gh-101396
* gh-101461
* gh-101462

**Comment by eshaanmandal** [comment]
Is this issue still open? I would like to work on it
