### ISSUE TITLE
NameError in class definition using list comprehension with if statement

### ISSUE THREAD

**Issue by matesken** [python/cpython#99295]
This code works

```
class A:
    data = ' '
    remains = [c for c in data]
```

This code gives us `NameError: name 'data' is not defined`

```
class A:
    data = ' '
    remains = [c for c in data if c in data]
```

Is there any valid reason why this happens (running Python 3.9)?

**Comment by AlexWaygood** [comment]
This is covered in the ["Naming and Binding" section](https://docs.python.org/3/reference/executionmodel.html#naming-and-binding) of the docs on Python's "Execution model":

> Class definition blocks and arguments to [exec()](https://docs.python.org/3/library/functions.html#exec) and [eval()](https://docs.python.org/3/library/functions.html#eval) are special in the context of name resolution. A class definition is an executable statement that may use and define names. These references follow the normal rules for name resolution with an exception that unbound local variables are looked up in the global namespace. The namespace of the class definition becomes the attribute dictionary of the class. The scope of names defined in a class block is limited to the class block; it does not extend to the code blocks of methods – this includes comprehensions and generator expressions since they are implemented using a function scope. This means that the following will fail:

> ```python
> class A:
>     a = 42
>     b = list(a + i for i in range(10))
> ```

In general, if you're not sure whether something is a bug or not, please post your question at https://discuss.python.org/c/users/7 instead of here. This is a tracker for bugs in CPython, not a user help forum, but there are lots of people over at discuss.python.org who'll be happy to help :)

**Comment by matesken** [comment]
I understand the explanation in the documentation. But if the rules are as defined, the first code example should also trigger an error. I still consider this different behaviour inconsistent and consequently incorrect.

But thank you for pointing me to discuss.python.org. I think I'll discuss this problem over there.

**Comment by wjandrea** [comment]
@matesken The first code example is working as expected because the first iterable of a comprehension is treated specially. This is covered in the docs at [Displays for lists, sets and dictionaries](https://docs.python.org/3/reference/expressions.html#displays-for-lists-sets-and-dictionaries)

> The iterable expression in the leftmost `for` clause is evaluated directly in the enclosing scope and then passed as an argument to the implicitly nested scope. Subsequent `for` clauses and any filter condition in the leftmost `for` clause cannot be evaluated in the enclosing scope as they may depend on the values obtained from the leftmost iterable.
