### ISSUE TITLE
legacy-install-failure

### ISSUE THREAD

**Issue by ayush4garg** [python/cpython#99303]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by ayush3103garg** [comment]
While installing pandas-datareader or lxml an error is occurring legacy-install-failure whereas attempts to install it in python 3.10 are successful but not in 3.11

**Comment by hauntsaninja** [comment]
This isn't a bug in CPython. Probably the projects you're trying to install don't have 3.11 wheels yet, consider reporting to those projects instead.
