### ISSUE TITLE
A 'Bug'?

### ISSUE THREAD

**Issue by xyuhjh2007** [python/cpython#99316]
I'm a Python novice.And I found a "bug".
ivt = input
input("1.")
if ivt != '1.otopenot':
    raise TypeError('invalid syntax ')
I think these code is true.But runed is false.Why?

**Comment by xyuhjh2007** [comment]
Of courst.I was indentation。

**Comment by sobolevn** [comment]
Please, ask questions about the langauge / learning process on the specialized resources.
There's https://www.reddit.com/r/learnpython/ PythonDiscord, StackOverflow, etc.

This is the place for bugs in CPython language.
