### ISSUE TITLE
`collections.abc.MutableMapping` should implement `__or__`, `__ror__` and `__ior__` (PEP 584)

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#99327]
# Feature or enhancement

[PEP 584 – Add Union Operators To dict](https://peps.python.org/pep-0584/) introduced Merge (|) and update (|=) operators that have been added to the built-in [dict](https://docs.python.org/3/library/stdtypes.html#dict) class in Python 3.9. They complement the existing dict.update and {**d1, **d2} methods of merging dictionaries.

`collections.abc.MutableMapping` should support these operations, and [implement them as mixin methods](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes).

# Pitch

Currently, MutableMapping lacks the following attributes:

```python
from colelctions.abc import *
set(dir(dict)) - set(dir(MutableMapping))
# {'__or__', 'copy', '__ror__', '__ior__', 'fromkeys'}
```

`copy` and `fromkeys` are not implemented for good reason, as they would impose constraints on the `__init__` function.
However, there seems to be no good reason why `__or__` and its variants are missing, as they can naturally be implemented using the `MutableMapping.update` method, which is available.

<details><summary>Sample implementation</summary>

```python
class MutableMapping(Mapping):
    ...

    def __or__(self, other, /):
        self.update(other)
        return self

    def __ior__(self, other, /):
        self.update(other)
        return self

    def __ror__(self, other, /):
        other.update(self)
        return other

    def __ror_alternative__(self, other, /):
        if isinstance(other, self.__class__)
            other.update(self)
            return other
        return NotImplemented
```

</details>

**Comment by pochmann** [comment]
`__or__` and `__ror__` should create a new object, not modify one of the two operands.

**Comment by rhettinger** [comment]
Once published, the ABCs cannot be changed.  See https://github.com/python/cpython/blob/6dedf42527fddbed8ef61ef8d3f025bf3a373359/Lib/_collections_abc.py#L9
