### ISSUE TITLE
`test_complex` contains tests for old-style classes

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#99320]
https://github.com/python/cpython/blob/d8f239d86eb70c31aa4c4ac46a1d0a27bdb14b20/Lib/test/test_complex.py#L309-L316

Right now there are "old-style classes". It should be removed.
PR is on its way.

* PR: gh-99321

* PR: gh-99322

* PR: gh-99323

**Comment by AlexWaygood** [comment]
Thanks @sobolevn!
