### ISSUE TITLE
Clarify the documentation of pathlib.Path.is_relative_to()

### ISSUE THREAD

**Issue by thomas-mckay** [python/cpython#99334]
Hi,

Currently (python 3.10.6 & 3.11.0):
```python
from pathlib import Path

p = Path('/var/log/../../opt')
p.is_relative_to('/var/log')
>>> True

p = p.resolve()
p.is_relative_to('/var/log')
>>> False
```
Once you know `is_relative_to` uses `relative_to`, this makes more sense but it's not obvious from the documentation and the examples given. Also it can easily lead to code that looks secure but isn't. Case in point, I was tasked with reviewing this code today (simplified for illustration purposes):

```python
path = Path(ROOT_PATH, user_input_rel_path)
if path.is_relative_to(ROOT_PATH):
    path.unlink()
else:
    raise PermissionError('Nope!')
```

I was unsure if I should open a bug or not because one could easily argue it isn't a bug. I do believe however that a warning in the documentation could save a few devs from making a mistake.

### Linked PRs
* gh-114031
* gh-114460
* gh-114461

**Comment by barneygale** [comment]
Pathlib never elides `../` segments unless you call `resolve()`

I'm not a big fan of `is_relative_to()`. And I agree that users may expect a slightly more rigorous check that automatically handles `../`. Once #99031 lands, the method be equivalent to `b == a or b in a.parents`, which IMO is too trivial to justify its existence. We could look at deprecating it?

**Comment by brettcannon** [comment]
It's probably too late to bother deprecating the function when the implementation is going to become trivial, but the docs could be clarified to effectively state the one-liner to clarify what the function represents.

**Comment by thomas-mckay** [comment]
I would say, if we're going as far as thinking about deprecation, I'd rather keep the function and have it do more:
```python
def is_relative_to(self, other, strict=False):
    a, b = self, other
    if strict:
        a = Path(os.path.normpath(a))
        b = Path(os.path.normpath(b))
    return b == a or b in a.parents

Path('/var/../../opt').is_relative_to(Path('/var'))
>>> True  # we keep the current behavior as default

Path('/var/../../opt').is_relative_to(Path('/var'), strict=True)
>>> False
```

**Comment by barneygale** [comment]
Tis done! Thanks @thomas-mckay for reporting, hopefully the new text makes sense to you.
