### ISSUE TITLE
TypeVarTuple and ParamSpec don't work together

### ISSUE THREAD

**Issue by LeeeeT** [python/cpython#99344]
# Bug report

The following code gives me an error:

```python
from typing import Generic, TypeVarTuple, ParamSpec


Ts = TypeVarTuple("Ts")

P = ParamSpec("P")


class Foo(Generic[*Ts, P]):
    pass


Foo[int, str, [bytes]]
```

```
TypeError: Too many arguments for <class 'Foo'>; actual 3, expected 2
```

I don't see any reasons why it doesn't work with `ParamSpec`. I believe it should assign `int, str` to `Ts` and `[bytes]` to `P`.

# Environment

- CPython versions tested on: 3.11
- Operating system and architecture: Linux x86_64

* PR: gh-99412

* PR: gh-99866

**Comment by JelleZijlstra** [comment]
cc @mrahtz @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Yes, such case is just not supported in the code, and it needs a nontrivial rewriting. I have found also several other similar bugs. I am working on the solution, PRs are almost ready.

**Comment by mrahtz** [comment]
Thank you for taking care of this, Serhiy!
