### ISSUE TITLE
Python Multiplication Error

### ISSUE THREAD

**Issue by Bits-pro** [python/cpython#99356]
print(1.4*1400)
the result will be:
1959.9999999999998

**Comment by MojoVampire** [comment]
This is how IEEE 754 binary floating point math works. It isn't decimal accurate (it's using base-2, not base-10, it can't be decimal precise in all cases). See: https://stackoverflow.com/questions/588004/is-floating-point-math-broken

You can use the `decimal.Decimal` class when you need decimal accurate results.

**Comment by stevendaprano** [comment]
@Bits-pro this is a [FAQ](https://docs.python.org/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate).

@MojoVampire it is misleading to suggest that decimal is always the best solution "when you need decimal accurate results". Rounding errors in decimal tend to be *worse* than rounding errors in binary. One advantage of Decimal is that it can more easily represent *exact* decimals like 1.4, but when the numbers are the result of a computation, Decimals suffer from the same rounding issues as binary floats. 

This example is probably familiar to anyone who has used a calculator:

```
>>> (1/Decimal(3))*3
Decimal('0.9999999999999999999999999999')
```

Decimals often suffer from *worse* rounding than binary floats:

```
>>> [i for i in range(1, 100) if 1/i*i != 1]
[49, 98]

>>> [i for i in range(1, 100) if 1/Decimal(i)*i != 1]
[3, 9, 22, 28, 29, 30, 33, 38, 43, 45, 46, 47, 48, 55, 58, 61, 62, 63, 65, 66, 68, 74, 75, 81, 83, 84, 87, 88, 89, 90, 93, 99]
```
