### ISSUE TITLE
pathlib.Path.absolute not marked as "new in version 3.11"

### ISSUE THREAD

**Issue by tudortimi** [python/cpython#99387]
New methods are generally marked as "new in version X". For example, `pathlib.Path.is_relative_to` is marked as "new in version 3.9" : https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to

![image](https://user-images.githubusercontent.com/8170909/201400213-273b41b0-926d-4e17-88e3-c4e43dcf2b8c.png)

`pathlib.Path.absolute` was added in version 3.11, but is not marked as such: https://docs.python.org/3/library/pathlib.html#pathlib.Path.absolute

![image](https://user-images.githubusercontent.com/8170909/201400186-11ea68b2-4dbd-443f-939b-43c7dd1eee66.png)

* PR: gh-99416

**Comment by sobolevn** [comment]
@tudortimi this is a good first issue to contribute? Would you like to do it? If you don't have time, no worries - I can help you.

**Comment by tudortimi** [comment]
@sobolevn I'll give it a try.

**Comment by AA-Turner** [comment]
`pathlib.Path.absolute` has been in the standard library since `pathlib` was addded in 3.4, though only documented in GH-26153 -- I am not sure what the precedent is here?

https://github.com/python/cpython/blame/v3.4.0/Lib/pathlib.py#L1002-L1018

A

**Comment by Reddragonemperor58** [comment]
I am going to try!

**Comment by Reddragonemperor58** [comment]
I have gone through helping with documentation, is that enough or is there anything else I need to go through before I start making changes

**Comment by brandtbucher** [comment]
I'm not sure that documenting when a function was first documented makes much sense. Saying "New in version ..." is really saying when the feature first became available (and is typically used only if that feature was added *after* the module or class it is a part of was first made available). Even the directive itself is called `versionadded`.

I recommend we just close this issue.

**Comment by tudortimi** [comment]
@brandtbucher But was the function widely used if it wasn't documented? I for one always used `resolve()` to get the absolute path, because the table mentioned that it was the equivalent of `os.path.abspath()`:

![image](https://user-images.githubusercontent.com/8170909/201489635-a20b2ae5-6705-480d-a498-54fd5b476117.png)

**Comment by hauntsaninja** [comment]
Agree with Brandt that closing this issue seems appropriate. Although maybe we could think about backporting https://github.com/python/cpython/pull/26153 (this would e.g. update the table above in 3.10's docs)?

**Comment by novialriptide** [comment]
The pull request https://github.com/python/cpython/pull/99416 should be linked to this issue to notify issue hunters that this issue is being worked on.

**Comment by brettcannon** [comment]
Without tests I didn't want to backport the doc changes as I don't know what state the code was i. But I also agree that documenting it as new in 3.11 seems weird, too, since the name has previously existed. I say we just leave the docs alone.
