### ISSUE TITLE
Add fixture for ValueError.message to 2to3 tool

### ISSUE THREAD

**Issue by CarstenGrohmann** [python/cpython#99394]
# Bug report

Please extend the `2to3` tool to display a warning when `ValueError.message` is used ,or replace the `message` attribute
e.g. with `str(<exception>)`, since `ValueError.message` no longer exists in Python 3.

## Reproducer
 ```
 $ cat example.py2
 #!/usr/bin/env python2.7
 try:
     raise ValueError('Foo')
 except ValueError as e:
     print "Caught: %s" % e.message
 
 $ 2to3 example.py2 
 RefactoringTool: Skipping optional fixer: buffer
 RefactoringTool: Skipping optional fixer: idioms
 RefactoringTool: Skipping optional fixer: set_literal
 RefactoringTool: Skipping optional fixer: ws_comma
 RefactoringTool: Refactored example.py2
 --- example.py2	(original)
 +++ example.py2	(refactored)
 @@ -2,4 +2,4 @@
  try:
      raise ValueError('Foo')
  except ValueError as e:
 -    print "Caught: %s" % e.message
 +    print("Caught: %s" % e.message)
 RefactoringTool: Files that need to be modified:
 RefactoringTool: example.py2
 ```

## Example of an expected result

```
--- example.py2	(original)
+++ example.py2	(refactored)
@@ -2,4 +2,4 @@
 try:
     raise ValueError('Foo')
 except ValueError as e:
-    print "Caught: %s" % e.message
+    print("Caught: %s" % str(e))
```

## My environment
* up-to-date ArchLinux on x86_64
* Python 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]

**Comment by JelleZijlstra** [comment]
2to3 is no longer maintained and will be removed from CPython in the future. Perhaps third-party tools like https://python-future.org/futurize.html would be open to adding such a converter.

**Comment by CarstenGrohmann** [comment]
Issue reported to : https://github.com/PyCQA/modernize/issues/261 and https://github.com/PythonCharmers/python-future/issues/609
