### ISSUE TITLE
dataclasses library is NOT backward compatible

### ISSUE THREAD

**Issue by yonikremer** [python/cpython#99401]
One of the changes in the [dataclasses library](https://docs.python.org/3/library/dataclasses.html) in Python 3.11 (Python 3.10 works fine) is causing backward compatibility issues with the [datasets library by hugging face](https://huggingface.co/docs/datasets/index).

When you import the datasets library using python 3.11 you get the following error:
```
Traceback (most recent call last):
  File "/kaggle/working/import_datasets.py", line 1, in <module>
    import datasets
  File "/opt/conda/envs/myenv/lib/python3.11/site-packages/datasets/__init__.py", line 45, in <module>
    from .builder import ArrowBasedBuilder, BeamBasedBuilder, BuilderConfig, DatasetBuilder, GeneratorBasedBuilder
  File "/opt/conda/envs/myenv/lib/python3.11/site-packages/datasets/builder.py", line 91, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/conda/envs/myenv/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/conda/envs/myenv/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/myenv/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/myenv/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'datasets.utils.version.Version'> for field version is not allowed: use default_factory
```

To reproduce the error, run [my kaggle kernels notebook](https://www.kaggle.com/code/yonikremer/repreducing-issue/edit/run/110702160)

**Comment by JelleZijlstra** [comment]
This is called out in https://docs.python.org/3.11/whatsnew/3.11.html#dataclasses and it feels unlikely we'll go back on this change. cc @ericvsmith though.

**Comment by yonikremer** [comment]
@JelleZijlstra @ericvsmith So if I add a `__hash__` method to `datasets.utils.version.Version` it should work?

**Comment by ericvsmith** [comment]
@yonikremer : Yes, I think so (although I can't test it just now). Your other option is to use a `default_factory`. Sorry for the hassle.

**Comment by visko-sc** [comment]
Could another option be using @dataclass(unsafe_hash=True) ?

**Comment by kinnala** [comment]
Doesn't it affect all dataclasses that have numpy arrays as default values?

**Comment by hauntsaninja** [comment]
As Eric mentions, the fix you probably want is to use a `default_factory`.

Closing as per https://github.com/python/cpython/issues/99401#issuecomment-1312213496

**Comment by ASEM000** [comment]
Hello, 

For [jax](https://github.com/google/jax),  JAX arrays are immutable but not hashable. So this goes against the proxy method used.

Moreover, JAX Arrays can not be subclassed to add a `hash` to count as non-mutable by dataclasses.

This change will break the JAX array annotation for dataclasses.

https://github.com/google/jax/issues/14295

**Comment by jakevdp** [comment]
I would suggest that https://github.com/python/cpython/commit/e029c53e1a408b89a4e3edf30a9b38b094f9c880 has a logical flaw, and should be considered a bug.

It's true that hashability implies immutability; but it's not true that immutability implies hashability. The commit in question assumes the latter, and thus the logic is flawed: there are valid, immutable values that incorrectly lead to an error because they happen to not have a hash function.

Is there any possibility that the team would consider rolling back https://github.com/python/cpython/commit/e029c53e1a408b89a4e3edf30a9b38b094f9c880 due to this flaw in its logic?
