### ISSUE TITLE
Foul-mouthed spam

### ISSUE THREAD

**Issue by anshiq** [python/cpython#99428]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by sobolevn** [comment]
I've submitted a GitHub content report about this issue. T

**Comment by AlexWaygood** [comment]
@python/organization-owners if you could block this person as well, that would be great
