### ISSUE TITLE
A function for matching true-like strings

### ISSUE THREAD

**Issue by carlbordum** [python/cpython#99445]
# Feature or enhancement

A function that parses a string and returns `True` if the string is generally used to mean so in CLIs, otherwise `False`.

# Pitch

Example implementation:

```python
def true_string(s: str) -> bool:
    return s.lower() in {"1", "on", "t", "true", "y", "yes"}
```

This function is often implemented in various slightly different ways, which is why I'd like to see it in stdlib. Perhaps it could live in `argparse` as a utility function?

**Comment by carlbordum** [comment]
Currently, there are at least two implementation here. In `Lib/pdb.py`: `reply in ('y', 'yes')`, and in `Lib/wsgiref/util.py`: `environ.get("HTTPS") in ('yes','on','1')`.

**Comment by ericvsmith** [comment]
You should raise this on Discourse for discussion: https://discuss.python.org/c/ideas/6

**Comment by JelleZijlstra** [comment]
`distutils.util.strtobool` is apparently fairly popular for this purpose, but `distutils` is gone starting in 3.12.

**Comment by JelleZijlstra** [comment]
> Ideally, we shouldn't hardwire English language specific word choices because it would make them inaccessible to `gettext`.

This is an important point. Any function of this sort will have to hardcode some specific English words, and I don't think it's appropriate for the stdlib to privilege the English language in this way in a string processing function.

**Comment by ericvsmith** [comment]
I agree with @rhettinger's points. I don't think there's much chance of this being implemented in the stdlib, but if you want to discuss it further, discuss.python.org is the right place to have that discussion (link above). I'm going to close this, pending discussions there.
