### ISSUE TITLE
`descr_set_trampoline_call` return type should be `int` not `PyObject*`

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#99443]
`getset_set` return type is `int`, `descr_set_trampoline_call`'s return type needs to be the same. I think this was a copy-paste error that occurred when applying my patch where `descr_set_trampoline_call` returns `int`:
https://github.com/pyodide/pyodide/blob/main/cpython/patches/0001-Patch-in-call-trampolines-to-handle-fpcast-troubles.patch

### Linked PRs
* gh-99444
* gh-99552

**Comment by hoodmane** [comment]
See also #91318.

**Comment by hauntsaninja** [comment]
Thanks for fixing!
