### ISSUE TITLE
Incorrect collection of parameters when subclassing generic with ParamSpec

### ISSUE THREAD

**Issue by LeeeeT** [python/cpython#99450]
# Bug report

It seems like something was broken in version 3.11 leading to incorrect collection of type parameters when subclassing generic with ParamSpec.

```python
from typing import Generic, ParamSpec

P = ParamSpec("P")

class A(Generic[P]):
    pass

class B(A[P]):
    pass

print(A.__parameters__)  # (~P,)
print(B.__parameters__)  # ([~P],)
```

Parameters of `B` should definitely be `(~P,)` too. This bug makes the following code fail at runtime:

```python
class C(A[P], Generic[P]):
    pass
```
```
TypeError: Some type variables ([~P]) are not listed in Generic[~P]
```

# Environment

- CPython versions tested on: 3.11
- Operating system and architecture: Linux x86_64

**Comment by sobolevn** [comment]
Looks like it is fixed on `main`:

```python
Python 3.12.0a1+ (heads/main-dirty:57be545959, Nov 13 2022, 11:20:28) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Generic, ParamSpec
>>> 
>>> P = ParamSpec("P")
>>> 
>>> class A(Generic[P]):
...     pass
... 
>>> class B(A[P]):
...     pass
... 
>>> print(A.__parameters__)
(~P,)
>>> print(B.__parameters__)
(~P,)
```

**Comment by LeeeeT** [comment]
Yes, it is not reproducing on https://github.com/python/cpython/tree/3.11 either. I'm going to close the issue. Sorry for the noise.

**Comment by sobolevn** [comment]
Thanks for noticing and reporting it! It is always worth checking.
