### ISSUE TITLE
Lambda is not keeping parameters

### ISSUE THREAD

**Issue by valof** [python/cpython#99457]
# Bug report
The following piece of code demonstrates how setattr() doesn't keep parameter's of Lambda functions. The behavior is inconsistent between the case when parameters of lambda got initialized by literals by non-literals. The sample below also demonstrates this discrepancy - the first two calls are using literals and the result is as expected; the second two calls are using initialization by taking parameters at run run-time and result is not as expected (and not as in the first case, when literals are used):

list_tuples=[
    ('test1', 'result1'),
    ('test2','result2')
]

class Test:
    def _my_calc(self, x):
        return self.s+'_'+x
    def __init__(self, s, is_bug):
        self.s = s

        if is_bug:
            for p in list_tuples:
                setattr(self, 'on_'+p[0], lambda: self._my_calc(p[1]))
        else:
            setattr(self, 'on_test1', lambda: self._my_calc('result1'))
            setattr(self, 'on_test2', lambda: self._my_calc('result2'))

print ('This is working as expected:---------------------------')
print (Test('OK on test1:', False).on_test1())
print (Test('OK on test2:', False).on_test2())
print ('But this is not:--------------------------------------')
print (Test('OK on test2:', True).on_test2())
print (Test('WTF is wrong with test1?:', True).on_test1())

# Your environment
Python 3.10.6
Windows 64-bit

**Comment by valof** [comment]
I am sorry for the formatting. The python file demonstrating the issue is attached.
[bug.zip](https://github.com/python/cpython/files/9999448/bug.zip)

**Comment by valof** [comment]
Oh, in 3.11 it is fixed. I am closing this.

**Comment by ronaldoussoren** [comment]
This is not a bug, see <https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result>

**Comment by JelleZijlstra** [comment]
I don't think 3.11 changed anything here. Sounds like you hit https://docs.python-guide.org/writing/gotchas/#late-binding-closures

**Comment by valof** [comment]
My mistake, sorry.
