### ISSUE TITLE
Optimized code paths in ceval / bytecodes need call trampolines for Emscripten

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#99460]
Since #91318 the faster CPython folks have added a few more code paths where a METH_NOARGS or METH_O function may be called. These also need call trampolines for the same reason. For instance, the bitarray package when built for Emscripten will hit these code paths with oddly shaped functions causes `indirect call signature mismatch` errors.

### Linked PRs
- gh-99514

**Comment by gvanrossum** [comment]
I'll leave it up to you to close this.

**Comment by hoodmane** [comment]
Thanks @gvanrossum!
