### ISSUE TITLE
We need to add the set_exc_info() function to the standard library

### ISSUE THREAD

**Issue by pomponchik** [python/cpython#99478]
# Feature or enhancement

We need to move the `set_exc_info()` function from the `_testcapi` module to the standard library.

# Pitch

I am a developer of a logging library named [polog](https://github.com/pomponchik/polog). In this library, it is possible to hang a decorator on any function that will record what is happening in it. It looks like:

```python
from polog import log

@log
def function():
    ...

function()
```

In the case when an exception is raised inside this function, this decorator records information about it. But the decorator itself does not affect the exception traceback, does not "clog" it. The traceback that you will see in the console looks the same as if there was no decorator. Because of this, logging becomes completely transparent to the user, and he no longer has any reason to avoid logging his code. I implemented this using the function `set_exc_info()` from the `_testcapi` module. There is something similar to the [code](https://github.com/pomponchik/polog/blob/1b798d120302873569d4d78832740f8efd81c004/polog/core/utils/cut_traceback.py#L6) of my library:

```python
tp, exc, tb = exc_info()
set_exc_info(tp, exc, tb.tb_next)
```

This code contains some problems. First: it worked on python 3.9 and 3.10, but it stopped working on python 3.11. Second: this code is not officially supported as part of the python standard library. This creates a risk that the library that depends on this feature will not work properly or will stop working altogether.

**Comment by sobolevn** [comment]
> I implemented this using the function set_exc_info() from the _testcapi 

`_testcapi` is very private :) You should not use anything from there. We have no guarantees for it, ever. This is a module with test utils and test cases.

> First: it worked on python 3.9 and 3.10, but it stopped working on python 3.11

Most likely it is related to the new exception features: https://docs.python.org/3/library/sys.html#sys.exception (but, again, we never promised that anything from `_testcapi` will work for you)

CC @iritkatriel

**Comment by ericvsmith** [comment]
I don’t think this is a bug report about a private API changing. Rather, it’s a request to expose and support the equivalent functionality in a future release.

**Comment by pomponchik** [comment]
Yes, I'm saying that it would be good to add this functionality in a future release. We don't need to fix it in the module `_testcapi`, we need to move it to the main officially supported part of the standard library.

**Comment by iritkatriel** [comment]
In 3.11 you can modify the traceback on the "exc_info" exception and it will stick:

```
>>> def raiseTypeError(): raise TypeError
... 
>>> try: raiseTypeError()
... except Exception as e: te = e
... 
>>> def raiseValueError(): raise ValueError
... 
>>> try: raiseValueError()
... except Exception as e:
...     e.__traceback__ = te.__traceback__
...     raise
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in raiseTypeError
ValueError 
```

See how raiseTypeError raised a ValueError?

You can also use ``sys.exception()`` instead of ``sys.exc_info()``.

**Comment by iritkatriel** [comment]
Marking as pending because I don't think I see a use case for exposing set_exc_info, given my previous comment.

**Comment by iritkatriel** [comment]
Closing. If you do still have an issue this can't solve, please reopen or create a new issue.
