### ISSUE TITLE
Round errors: function print(round(4.5)) outputs 4 instead of 5 etc

### ISSUE THREAD

**Issue by franko7878** [python/cpython#99471]
What was I doing:
rounding values using print(round(x.5))

Expected output:
Round to nearest whole number i.e. 3.5=4 4.5=5

Actual outputs:
(Even numbers).5 give an error and round down, (odd numbers).5 give the correct rounded up value.
3.5=4 Correct
4.5=4 ERROR 
5.5=6 Correct
6.5=6ERROR

# Your environment

Software used:
Python3.9 interpreter
PyCharm 2022.2.3 (Community Edition)
Build #PC-222.4345.23, built on October 10, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-131-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 2
Current Desktop: Undefined

**Comment by ronaldoussoren** [comment]
This is documented behaviour: <https://docs.python.org/3/library/functions.html#round>. The halfway point is rounded towards even.

**Comment by franko7878** [comment]
oh... rtfm, I should... thank you.
