### ISSUE TITLE
Call to _imp.source_hash with incorrect arguments in (unreachable?) part of SourceLoader.get_code (importlib._bootstrap_external)

### ISSUE THREAD

**Issue by DavidCEllis** [python/cpython#99508]
# Bug report

As far as I can tell this line:
https://github.com/python/cpython/blob/4e4b13e8f6211abbc0d53056da11357756daa314/Lib/importlib/_bootstrap_external.py#L1147-L1147

will raise a TypeError and should be a 2 argument form as seen earlier in the same method.

https://github.com/python/cpython/blob/4e4b13e8f6211abbc0d53056da11357756daa314/Lib/importlib/_bootstrap_external.py#L1117-L1120

However, as either `hash_based` is False, `source_hash` has already been generated or the code returns early I don't think this line can be reached. (Maybe if you have a flaky version of get_data that sometimes raises an ImportError/EOFError??).

Example:
```python3
>>> _imp.source_hash(_RAW_MAGIC_NUMBER, b'')
b's\x8d\x9c\xd5\xd5\xe8\x7fs'

>>> _imp.source_hash(b'')
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: source_hash() missing required argument 'source' (pos 2)
```

Edit: Sorry, as I opened the issue from within the source line via 'reference in new issue' I think I accidentally skipped the bug report format that would have given this a label.

### Linked PRs
* gh-99635

**Comment by FFY00** [comment]
It seems this was a bug of #4575, which went unnoticed until now. Looks like it is just missing `_RAW_MAGIC_NUMBER` as the first argument.
