### ISSUE TITLE
in print function ，if end is "\r"

### ISSUE THREAD

**Issue by overmind1980** [python/cpython#99524]
# Bug report

>>> print("123 456",end="\r")

456

# Your environment

mac 
- CPython versions tested on:3.9
- Operating system and architecture:intel

**Comment by stevendaprano** [comment]
The behaviour is correct.

The carriage return returns to the beginning of the line, not the next line, so it prints `123 456`, then returns to the start of the line, where the interactive prompt overprints the first three digits and you get `>>> 456`.

```
>>> print("123 456",end="\r")
>>> 456
```

If you then type at the prompt, the letters you type will overwrite the `456`.

This is not a bug, it is working as intended.

**Comment by overmind1980** [comment]
thank you！
