### ISSUE TITLE
NOT find “PyIOBase_Type” in libpython3.9.so.1 with python3.9.9

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#99525]
# Bug report

i can find `PyIOBase_Type` in `libpython3.7m.so.1` with  python3.7.9 
```
[root@localhost ~]# python --version
Python 3.7.9
[root@localhost ~]# strings /usr/lib64/libpython3.7m.so.1.0 |grep PyIOBase_Type
PyIOBase_Type

```
![image](https://user-images.githubusercontent.com/67537842/202068750-d8054509-2c9d-4b47-8f5b-27aa4d9383d6.png)

but i can't find `PyIOBase_Type` in `libpython3.9.so.1` with  python3.9.9 
```
[root@localhost lib64]# python --version
Python 3.9.9
[root@localhost lib64]# strings /usr/lib64/libpython3.9.so.1.0 |grep PyIOBase_Type
[root@localhost lib64]# 

```
![image](https://user-images.githubusercontent.com/67537842/202068915-9c4b81d2-41de-42b6-9aff-ee3625918310.png)

# Your environment

- CPython versions tested on: python3.7.9 and python3.9.9
- Operating system and architecture: arm64

**Comment by alittlesir** [comment]
I know that this has been defined here，but `strings /usr/lib64/libpython3.7m.so.1.0 |grep PyIOBase_Type` can print something, however, `strings /usr/lib64/libpython3.9.so.1.0 |grep PyIOBase_Type` print nothing.



> It is defined here: https://github.com/python/cpython/blob/3.9/Modules/_io/_iomodule.h#L8
> 
> Are you sure that this is not an issue with `zookeeper`?

i am sure, it is OK with python3.7.9, and it is some wrong with python3.9.9, same version of `zookeeper`

**Comment by ronaldoussoren** [comment]
AFAIK PyIOBase_Type is not part of the public API for CPython.  The error is likely due to zookeeper trying to use the symbol while the CPython build proces has been changed to hide symbols that shouldn't be public (e.g. use ``-fvisibility=hidden`` with GCC/Clang). 

Please ask the zookeeper maintainers about this.
