### ISSUE TITLE
ValueError: incompatible stacks when jumping to async function signatures for python 3.11.0

### ISSUE THREAD

**Issue by dkrystki** [python/cpython#99527]
Jumping to async function signatures raises `ValueError: incompatible stacks` error.
Works for non async functions and python versions < 3.11

Environment:
- CPython versions tested on: Python 3.11.0
- Operating system and architecture: Linux q 5.4.0-42-generic x64

Full reproducer:
```
import asyncio
import sys


async def fun():  # <---- jump location
    a = 1

    b = 2

    c = 3  # current location


def trace(frame, event, arg):
    if event == "line" and frame.f_lineno == 10:
        frame.f_lineno = 5

    return trace

sys.settrace(trace)

if __name__ == "__main__":
    asyncio.run(fun())
```

What's the use case of it?
[Reloadium](https://github.com/reloadware/reloadium) keeps debug code in the function signature. 
Above exception prevents reloadium to work on async functions.

**Comment by brandtbucher** [comment]
Thanks for finding this... I'll take a look at it later this week (I'm already fixing a related bug in the jump code).

CC @markshannon

**Comment by dkrystki** [comment]
@brandtbucher Any updates on this?

**Comment by brandtbucher** [comment]
No updates yet, sorry. This is still on my to-do list, just busy with higher-priority items at the moment.

The rules for where you can jump changed a bit between 3.10 and 3.11... I believe we used to only validate the "block" stack (used for control flow), but that was removed in 3.11, and now we validate the "value" stack (used for evaluation) instead.

So I'm not sure that this is even a bug at all: we haven't historically made any promises about where it's legal to jump to, and just tried our best to make the "obvious" spots work.

Have you tried jumping to the start of the `a = 1` line instead? That makes more sense to me than jumping to the `def` line (which contains a lot of one-time setup for when the coroutine is first created and run).

**Comment by dkrystki** [comment]
Unfortunately this won't work since the debug code has to be executed before the first line is executed.

You are correct, not really a bug although some tools might rely on this behavior.
 
I have some experience in C and can try fixing this. Do you think you would find some time to guide me if needed?
