### ISSUE TITLE
Add tkinter to the windows nuget packages

### ISSUE THREAD

**Issue by martinResearch** [python/cpython#99546]
# Feature or enhancement

Add tkinter to the windows nuget packages that can be found on https://www.nuget.org/packages/python

# Pitch

At the moment tkinter is not included to the nuget packages despite being part of the standard library. Unfortunately, there does not seem to be an easy way to add it back after installing the nuget package because it is not on pypi.org.
It seems that adding tkinter to the nuget packages could be a matter of adding a single line in 
https://github.com/python/cpython/blob/0faa0ba240e815614e5a2900e48007acac41b214/PC/layout/support/options.py
If the omission has been motivated by trying to keep the nugget file as small as possible maybe n alternative would be to provide an official tkinter package on pypi.org.

**Comment by zooba** [comment]
Same reasoning as for the embeddable distro. The discussion about publishing tkinter somewhere independently can continue on #99566
