### ISSUE TITLE
unittest.TestCase.assertCountEqual doesn't work well with mock.ANY or similar

### ISSUE THREAD

**Issue by dseomn** [python/cpython#99557]
# Bug report

This test passes despite `1` on the left not matching either `None` or `2` on the right:

```python
import unittest
from unittest import mock

class FooTest(unittest.TestCase):
    def test_foo(self):
        self.assertCountEqual((mock.ANY, 1), (None, 2))

if __name__ == '__main__':
    unittest.main()
```

At a glance I'm guessing it's because `mock.ANY` compares equal to `NULL` from https://github.com/python/cpython/blob/5fdd49dc653b4c14e3303c1eefd9d031602bbbf5/Lib/unittest/util.py#L126 but that's just a guess and I haven't looked at it very closely.

# Your environment

- CPython versions tested on: 3.10.7
- Operating system and architecture: Debian amd64

**Comment by sobolevn** [comment]
This indeed happens because of `mock.ANY` and the fact that it is equal to anything.

```python
>>> from unittest import mock
>>> mock.ANY == 1
True
>>> mock.ANY == None
True
```

Looks like it works as expected: if you have `mock.ANY` inside your collection, it will consume all elements as "equal".

**Comment by dseomn** [comment]
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual says "Test that sequence first contains the same elements as second, regardless of their order." It doesn't really mention anything about comparing elements of `first` to other elements of `first`. So even though `mock.ANY` can match `1`, the fact that `1` doesn't match anything in the second sequence seems like the assertion should fail. Also, if you swap the order of the two sequences in my example, the assertion fails, and the docs don't mention anything about the order of the two args being important.

**Comment by gpshead** [comment]
`assertCountEqual` and `mock` were not co-designed so wanting to use mock matchers in a context outside of mock's own Mock assertion methods is likely to lead to surprises.
