### ISSUE TITLE
Subclasses of `ExceptionGroup` can wrap `BaseException`s

### ISSUE THREAD

**Issue by Zac-HD** [python/cpython#99553]
```python
class MyEG(ExceptionGroup):
    """Holds BaseExceptions without itself being a BaseException."""

oops = MyEG("oops", [KeyboardInterrupt()])
assert isinstance(oops, Exception)
assert not isinstance(oops.exceptions[0], Exception)
```

I believe that this is a bug tracing to the period when PEP-654 did not intend `(Base)ExceptionGroup` to be usable as a parent class; and I think a sufficient fix would be to replace the type-equality check with an isinstance check in:

https://github.com/python/cpython/blob/bc390dd93574c3c6773958c6a7e68adc83d0bf3f/Objects/exceptions.c#L740-L744

cc @iritkatriel; raised via https://github.com/agronholm/exceptiongroup/pull/40#discussion_r1020961107

### Linked PRs
* gh-99572
* gh-99580
* gh-99615
* gh-103435

**Comment by Zac-HD** [comment]
I think at least documented, though I'd prefer it was changed.  

If people *intend* `MyEG` to contain `BaseException`s then the obvious way is to inherit from `BaseExceptionGroup` (and likely have a `BaseMyEg`; Trio has already shipped this pattern), so any cases where `MyEG` ends up containing e.g. a `KeyboardInterrupt` and then discarding that to an `except Exception:` would be unfortunate!  [I think the PEP argues against this well](https://peps.python.org/pep-0654/#make-it-impossible-to-wrap-baseexceptions-in-an-exception-group) 🙂 

The `==` comparison also makes static typing very confusing: if we have `BaseExceptionGroup` -> `ExceptionGroup` -> `MyEG` and the last can also contain `BaseException`s, then either `ExceptionGroup.exceptions` must be annotated as able to contain `BaseException`s when it cannot, the annotations for `MyEG` must say it cannot when in fact it can, or we violate the substitution principle.  This last is currently the case at runtime, but typecheckers are not keen on such things.

**Comment by Zac-HD** [comment]
Hah!  It looks like I just find this persistently startling: https://github.com/python/cpython/pull/28569#discussion_r721276505 (but I promise, no PEP this time 😉)

**Comment by gvanrossum** [comment]
Yeah, I definitely recall that we discussed this before. But looking at the [code](https://github.com/python/cpython/blob/main/Objects/exceptions.c#L740) it's possible that we were too conservative. In particular in the [fallback clause](https://github.com/python/cpython/blob/main/Objects/exceptions.c#L755) we could have chosen to check if `cls` is a subclass of `PyExc_ExceptionGroup` if `nested_base_exceptions` is set and raise the same error as on line 742.

The thing we definitely _can't_ do is adjusting the class if it is exactly `PyExc_BaseExceptionGroup` and `nested_base_exceptions` is false.

The question is, can we treat this as a bug and fix it (in 3.11.1 if it isn't out yet) or would such a fix be considered backwards compatible?

**Comment by iritkatriel** [comment]
I think we can call it a bug. It’s better to change it in 3.11.1 than in 3.12.

**Comment by gvanrossum** [comment]
Sounds good.
