### ISSUE TITLE
Win-11 3.11.0 - Can't enable admin privileges, even if I install as the atmin.  Can't install for all users as the result.

### ISSUE THREAD

**Issue by AD5GB** [python/cpython#99568]
Well, the subject line pretty much tells it all.  I'm not entirely sure it is a bug though since I see no other reports of  the issue.  I'm on UNIX or Linux most of the time anyway but I wanted to upgrade from a Python -19 version I had on my Windows laptop.  I could simply not find a way to enable the admin button on the first installer dialog page so there was no way moving forward to enable a global install. .  I grabbed the latest 3.12 pre-release and it worked like a charm.  I'm stumped, but then I'm not a Windows fanboy by any means.   

I'll wait for the next maintenance release of 3.11 and try again.  If you have any ides in the interim,, shoot me a message.

**Comment by rizwan342** [comment]
Sounds more like a user problem more than a Python problem.

**Comment by rizwan342** [comment]
Besides, there really isn't much of a solution as I know it to this problem; I'm not an admin on my device either. The only way I could manage to install Python was by selecting "only for user".

**Comment by velly7** [comment]
> Well, the subject line pretty much tells it all. I'm not entirely sure it is a bug though since I see no other reports of the issue. I'm on UNIX or Linux most of the time anyway but I wanted to upgrade from a Python -19 version I had on my Windows laptop. I could simply not find a way to enable the admin button on the first installer dialog page so there was no way moving forward to enable a global install. . I grabbed the latest 3.12 pre-release and it worked like a charm. I'm stumped, but then I'm not a Windows fanboy by any means.
> 
> I'll wait for the next maintenance release of 3.11 and try again. If you have any ides in the interim,, shoot me a message.

Go to Settings - Apps - Uninstall Python launcher. Install your version, should work

**Comment by zooba** [comment]
The "Install for All Users" option is under the Advanced install options. It's documented at [the end of this section](https://docs.python.org/3/using/windows.html#installation-steps).
