### ISSUE TITLE
No windows/mac installer for security release of pythons 3.7.10-15, 3.8.11-15 and 3.9.14-15

### ISSUE THREAD

**Issue by mangin** [python/cpython#99569]
Hey there,
it looks like that we don't create python installers for the freshest python3.7,3.8 and 3.9.
Is it a bug or a decision?

# Bug report
For example https://www.python.org/downloads/release/python-3914/ there are no installer for Windows/mac
But here https://www.python.org/downloads/release/python-3913/ we can find them.

**Comment by ronaldoussoren** [comment]
This is documented in [the developer guide](https://devguide.python.org/developer-workflow/development-cycle/). Security releases are source only.
