### ISSUE TITLE
Add tests for Unicode C API

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#99593]
Several years ago I started to write tests for Unicode C API. It required a lot of effort, because this category is big, so after doing 2/3 of the work I put it off for later. Certain circumstances prevented me from completing it. But now I found time to return to it.

In the meantime, other people have done some of this work (moving parts of the `_testcapi.c` to a separate files, adding coverage for more C API functions), and some of the legacy C API has been removed. Therefore, it took more than a week to arrange the code, fix conflicts, remove outdated tests and write remaining tests. But some errors may still remain, be careful.

### Linked PRs
* gh-99594
* gh-99651
* gh-99868
* gh-104728
* gh-106595

**Comment by vstinner** [comment]
Can the issue be closed?
