### ISSUE TITLE
Misleading error description when using f-string

### ISSUE THREAD

**Issue by JohnyL** [python/cpython#99597]
The following code:
```python
x = 5
print(f"{x = wrong}")
```
generates the following syntax error:

![image](https://user-images.githubusercontent.com/7391680/202860460-0ec5ae4f-14ca-438a-8dd7-21459792dfb9.png)

although VSCode shows correct error text:

![image](https://user-images.githubusercontent.com/7391680/202860506-40144216-7ae8-4cc8-99d0-1fec5c069c17.png)

# Your environment

- CPython versions tested on: 3.11, 3.12a2
- Operating system and architecture: Windows 10 x64

### Linked PRs
* gh-99636

**Comment by MonadChains** [comment]
The same error appears also for older versions (Python 3.10/3.9/3.8).
However, for Python 3.7 the error message is the following:
![Screenshot from 2022-11-19 23-34-51](https://user-images.githubusercontent.com/105170638/202874191-b4196d16-3e21-48b7-979b-04b8c1aafde9.png)

**Comment by thatbirdguythatuknownot** [comment]
It should highlight `wrong` though because `f"{expr=}"` is a valid f-string.

**Comment by ericvsmith** [comment]
Yes, it's no doubt a result of `f"{expr=}"` processing, which was added in 3.8.

**Comment by hugovk** [comment]
> It should highlight `wrong` though because `f"{expr=}"` is a valid f-string.

With current `main`/Python 3.13:

```pycon
❯ ./python.exe
Python 3.13.0a2+ (heads/main:0d8fec79ca, Jan 11 2024, 18:18:25) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 5
>>> print(f"{x = wrong}")
  File "<stdin>", line 1
    print(f"{x = wrong}")
                 ^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
```

Now also in colour!

![image](https://github.com/python/cpython/assets/1324225/02ea3971-01de-43a5-928c-5a77ea8fb04f)

I think we can close this now.
