### ISSUE TITLE
winsound 

### ISSUE THREAD

**Issue by briankardon** [python/cpython#99607]
# Documentation

I've found some kind of inconsistency relating to `winsound.PlaySound`.

In the [`winsound` documentation](https://docs.python.org/3/library/winsound.html#winsound.PlaySound), the `PlaySound` documentation states:

> The sound parameter may be a filename, a system sound alias, audio data as a [`bytes-like object`](https://docs.python.org/3/glossary.html#term-bytes-like-object), or `None`

The [bytes-like object](https://docs.python.org/3/glossary.html#term-bytes-like-object) documentation states that "bytes-like object":

> includes all [bytes](https://docs.python.org/3/library/stdtypes.html#bytes), [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray), and [array.array](https://docs.python.org/3/library/array.html#array.array) objects, as well as many common [memoryview](https://docs.python.org/3/library/stdtypes.html#memoryview) objects.

However, when I try to supply a `bytes` object to the `winsound.PlaySound`, I get an error. For example:

```
>>> import winsound
>>> winsound.PlaySound(b'abcdefg', winsound.SND_ASYNC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'sound' must be str or None, not 'bytes'

```

I'm not exactly sure which part of the documentation is in error, but something isn't matching up. It's possible I'm not understanding which flags to use, but I can't find a combination of flags that allows me to pass a `bytes` object in without an error. What format is the bytes-like object supposed to take? Can it be raw audio data? Or does it need to have some kind of header? Maybe it has to have a wave file format?

System info:
Windows 10
Python 3.8.10 
(The 3.8 documentation says the same things about this as the latest 3.11 documentation)

Thank you!

**Comment by briankardon** [comment]
Ok, I've done some more investigating, and it seems that the problems is that the bytes-like object needs to have a wave header in it, and needs the `winsound.SND_MEMORY` flag.

I think the documentation can be easily made clearer - I'll look into how to do that myself.

Example usage that works:
```
import wave
import io
import winsound
f = io.BytesIO()
wf = wave.open(f, mode='wb')
wf.setnchannels(1)
wf.setframerate(22050)
wf.setsampwidth(1)
wf.writeframes(b'here are some random bytes to interpret as audio')
wf.close()
f.seek(0)
data = f.read()
winsound.PlaySound(data, winsound.SND_MEMORY)

```

**Comment by hauntsaninja** [comment]
Yeah, I think the documentation means to address this with:

> The sound parameter may be [...]. Its interpretation depends on the value of flags, which can be a bitwise ORed combination of the constants described below

So if you want SND_ASYNC as in your original example, you can combine to pass `SND_MEMORY | SND_ASYNC` as flags.

**Comment by briankardon** [comment]
Ok, the process for getting set up to actually make a documentation pull request is a little much for me right now, but in case someone else wants to do it, here's how I'd change it to make it clearer:

winsound.**PlaySound**(_sound, flags_)

> Call the underlying `PlaySound()` function from the Platform API. The sound parameter may be a filename, a system sound alias, audio data as a [bytes-like object](https://docs.python.org/3.8/glossary.html#term-bytes-like-object), or `None`. Its interpretation depends on the value of flags, which can be a bitwise ORed combination of the constants described below. If the sound parameter is a bytes-like object, it must be formatted as a wave file, such as can be produced by the [wave library](https://docs.python.org/3/library/wave.html#wave.Wave_write.writeframes), and the [`SND_MEMORY`](https://docs.python.org/3.8/library/winsound.html#winsound.SND_MEMORY)  flag must be included. If the sound parameter is `None`, any currently playing waveform sound is stopped. If the system indicates an error, [`RuntimeError`](https://docs.python.org/3.8/library/exceptions.html#RuntimeError) is raised.

**Comment by briankardon** [comment]
> Yeah, I think the documentation means to address this with:
> 
> > The sound parameter may be [...]. Its interpretation depends on the value of flags, which can be a bitwise ORed combination of the constants described below
> 
> So if you want SND_ASYNC as in your original example, you can combine to pass `SND_MEMORY | SND_ASYNC` as flags.
> 
> Documentation improvements welcome!

I agree - it does need the `SND_MEMORY` flag, but it also seems to need to be in a wave format, with an appropriate wave header. Thanks for your reply!

**Comment by pochmann** [comment]
> need the `SND_MEMORY` flag, but it also seems to need to be in a wave format, with an appropriate wave header, which I don't see anywhere in the documentation.

Isn't that what the [`SND_MEMORY` doc](https://docs.python.org/3/library/winsound.html#winsound.SND_MEMORY) says?

"The sound parameter to PlaySound() is a memory image of a **WAV file**, as a bytes-like object."

**Comment by briankardon** [comment]
Yes, I suppose you're right - I don't know why that didn't really register when I read it before. Thanks!

**Comment by brockbrownwork** [comment]
This issue page was helpful in solving my problem, _thanks_!
