### ISSUE TITLE
ModuleNotFoundError: No module named "encodings" when lauching Python 3.12 alpha 2

### ISSUE THREAD

**Issue by HGStyle** [python/cpython#99600]
# Crash report

I was compiling Python 3.12.0 alpha 2, and I got the compiled `python` file.
I moved it, deleted the building folder and launched it. But I got an error : 

# Error message

``` Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = './python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/local/lib/python3.12'
  sys._base_executable = '/home/runner/Python-3120-alpha-2/python'
  sys.base_prefix = '/usr/local'
  sys.base_exec_prefix = '/usr/local'
  sys.platlibdir = 'lib'
  sys.executable = '/home/runner/Python-3120-alpha-2/python'
  sys.prefix = '/usr/local'
  sys.exec_prefix = '/usr/local'
  sys.path = [
    '/usr/local/lib/python312.zip',
    '/usr/local/lib/python3.12',
    '/usr/local/lib/python3.12/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

# My environment

- CPython versions tested on: CPython 3.12.0 alpha 2 - downloaded from GitHub as ZIP
- Operating system and architecture: Replit (Bash Repl, I think its Linux)

**Comment by zware** [comment]
What exactly does "I moved it, deleted the building folder and launched it" entail (what commands did you run, and why)?

This sounds to me like you moved just the executable without installing the standard library where it could be found.

Also note that the ZIP file provided by GitHub is not actually a supported release. The official source release can be found as a tarball at python.org/downloads
