### ISSUE TITLE
Bytecode for empty f-string != bytecode for empty normal string

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#99606]
# Bug report

The bytecode for an empty f-string does not match the bytecode for an empty normal string.
```py
import dis
dis.dis('""')
dis.dis('f""')
```
Output:
```
0           0 RESUME                   0

1           2 LOAD_CONST               0 ('')
            4 RETURN_VALUE
0           0 RESUME                   0

1           2 BUILD_STRING             0
            4 RETURN_VALUE
```

# Environment

- CPython versions tested on:
3.11, 3.12.0a2

### Linked PRs
* gh-99608
* gh-112407

**Comment by pochmann** [comment]
Why do you call that a bug? And why would you write `f""`?

**Comment by thatbirdguythatuknownot** [comment]
> Why do you call that a bug? And why would you write `f""`?

Aren't they the same thing so shouldn't they have the same bytecode? Also sometimes I can forget to remove or subconsciously add `f`.

**Comment by ericvsmith** [comment]
The intention was that an f-string without any substitutions would be equivalent to a normal string. These examples are  3.12+. It's true for non-empty strings, it should probably be the same for empty strings. Not that I think it's a big deal.

```python
>>> dis.dis("f'x'")
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 ('x')
              4 RETURN_VALUE
>>> dis.dis("'x'")
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 ('x')
              4 RETURN_VALUE
>>> dis.dis("f''")
  0           0 RESUME                   0

  1           2 BUILD_STRING             0
              4 RETURN_VALUE
>>> dis.dis("''")
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 ('')
              4 RETURN_VALUE
```
