### ISSUE TITLE
I think it is a python locals or globals bug!

### ISSUE THREAD

**Issue by gzg365** [python/cpython#99640]
# Bug report

**consider this:**

```python
aaa = 123
bbb = 456

def myfunc(n):
    if n > 0:
        bbb = n

    print("abc" + str(bbb))

myfunc(3)
myfunc(0)
```

**the output is:**

```
abc3
Traceback (most recent call last):
  File "D:\testPython310\test.py", line 53, in <module>
    myfunc(0)
  File "D:\testPython310\test.py", line 50, in myfunc
    print("abc" + str(bbb))
UnboundLocalError: local variable 'bbb' referenced before assignment
```

in this function call "myfunc(0)", I did not create/write a local var bbb, why can not read the global var bbb ?

# Your environment

Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
win10 professional

**Comment by ronaldoussoren** [comment]
This is not a bug, but normal Python behaviour.  See [the Python FAQ](https://docs.python.org/3/faq/programming.html#why-am-i-getting-an-unboundlocalerror-when-the-variable-has-a-value) for an explanation.
