### ISSUE TITLE
Possible typo in typing.TypeVarTuple docs

### ISSUE THREAD

**Issue by GabrielAnguita** [python/cpython#99662]
# Documentation
In the [section about the TypeVarTuple type](https://docs.python.org/3.11/library/typing.html#typing.TypeVarTuple), there is a bit of text that I find diffcult making sense of. My guess is that the author made a typo, but of course I could be wrong and maybe I am not getting the idea.

Where the text states:
> Type variable tuples must always be unpacked. This helps distinguish type variable **types** from normal type variables

I think it meant:
> Type variable tuples must always be unpacked. This helps distinguish type variable **tuples** from normal type variables

In case it is indeed a typo I'd be happy to open a PR fixing the issue.

### Linked PRs
* gh-99672
* gh-99674

**Comment by AlexWaygood** [comment]
Cc. @mrahtz

**Comment by mrahtz** [comment]
Ah, yes, it is indeed a typo - good catch! Please do go ahead and send a PR :)

**Comment by JelleZijlstra** [comment]
Thanks for reporting and fixing!
