### ISSUE TITLE
Python 3.10.8 missing from versions page

### ISSUE THREAD

**Issue by jakirkham** [python/cpython#99671]
Python 3.10.8 is missing from [the versions page]( https://www.python.org/doc/versions/ )

**Comment by ned-deily** [comment]
That page you reference is just for the documentation checkpoints and, while it should be updated to link to the 3.10.8 documentation (@pablogsal), the canonical page for releases is https://www.python.org/downloads/ where you will find a link to [the 3.10.8 release page](https://www.python.org/downloads/release/python-3108/).

**Comment by pablogsal** [comment]
I don't think I have ever modified that page so whatever is adding the entries there, the canonical info comes from somewhere else

**Comment by pablogsal** [comment]
Shoul

**Comment by mbargull** [comment]
@pablogsal, thanks! `3.8.15` and `3.9.15` are missing from the "Documentation by Version" page, too. (`3.7.15` from the same batch is listed, though.)
Just for future reference: Is there a repository where one can directly open an issue/pull request for this? I couldn't find the sources of that page at the pythondotorg repo et al.
