### ISSUE TITLE
case error in test_unary.py

### ISSUE THREAD

**Issue by Isaac-Lee** [python/cpython#99688]
Hello all,
I was looking throw the test code in cpython to use a test cases for my own python interpreter.
While looking at the code, I got curious.

First is this function.

> https://github.com/python/cpython/blob/7e3f09cad9b783d8968aa79ff6a8ee57beb8b83e/Lib/test/test_unary.py#L23-L27

I think this function is not testing invert operator.
Instead it is just copying test cases of negative operator.

Next is these functions.
> https://github.com/python/cpython/blob/7e3f09cad9b783d8968aa79ff6a8ee57beb8b83e/Lib/test/test_unary.py#L7-L13
> https://github.com/python/cpython/blob/7e3f09cad9b783d8968aa79ff6a8ee57beb8b83e/Lib/test/test_unary.py#L15-L21

I think these functions have duplicated test cases.
`self.assertTrue(-2 == 0 - 2)` tested twice in test_negative,
`self.assertEqual(+2, 2)` tested twice as well in test_positive.

I want to know if there is an intention that I don't know. 
Or if there is a problem, I think we need to fix the test code.

### Linked PRs
* gh-99712

**Comment by sweeneyde** [comment]
It looks like some of this is left over from Python 2, where the test cases would have said `self.assertEqual(+2L, 2L)`. Redundant tests can be safely removed now.

I agree that test_invert should be fixed to actually test the `~` operator.

Would you like to make a PR?

**Comment by Isaac-Lee** [comment]
> It looks like some of this is left over from Python 2, where the test cases would have said self.assertEqual(+2L, 2L). Redundant tests can be safely removed now.

Thank you for your answer. Now I understand.

And sure if I make a PR then it would be grateful.

**Comment by sweeneyde** [comment]
I'm sorry this took me so long to get to. Thanks for your contribution!
