### ISSUE TITLE
asyncio: cannot schedule new futures after shutdown

### ISSUE THREAD

**Issue by noskill** [python/cpython#99704]
I am getting this stacktrace from time to time. It appears during program shutdown.

```
  tcp_server.py", line 79, in __cb
    fut = self.loop.run_in_executor(None, lambda: self.onMessageReceived(data))
  File "python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
```
    
Here __cb is a coroutine i pass to asyncio.start_server

I am using Python 3.10.4

**Comment by gvanrossum** [comment]
How did you start the server? Your traceback is incomplete. Also, how do you shut down the program?

**Comment by noskill** [comment]
I create loop like that:
```
loop: AbstractEventLoop = asyncio.new_event_loop()
th = threading.Thread(target=loop.run_forever, daemon=True)
```

then i pass this event loop every time i need to create a server to _asyncio.start_server_

more complete stack trace:

```
2022-11-22 10:05:00,188: ERROR    Task exception was never retrieved
future: <Task finished name='Task-21' coro=<TCPServer.__cb() done, defined at /anaconda3/envs/malmo/lib/python3.10/site-packages/tagilmo/VereyaPython/tcp_server.py:55> exception=RuntimeError('cannot schedule new futures after shutdown')>
Traceback (most recent call last):
  File "/anaconda3/envs/malmo/lib/python3.10/site-packages/tagilmo/VereyaPython/tcp_server.py", line 85, in __cb
    raise e
  File "/anaconda3/envs/malmo/lib/python3.10/site-packages/tagilmo/VereyaPython/tcp_server.py", line 79, in __cb
    fut = self.io_service.run_in_executor(None, lambda: self.onMessageReceived(result))
  File "/anaconda3/envs/malmo/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/anaconda3/envs/malmo/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

**Comment by noskill** [comment]
I create server with this event loop, i pass the loop to my tcp_server class

in tcp_server.py:
```
asyncio.run_coroutine_threadsafe(self.startAccept(), self.loop).result()
```
in tcp_server.py:
```
async def startAccept(self) -> None:
    self.server = await asyncio.start_server(self.__cb, None, self.port)
```

**Comment by noskill** [comment]
the program exists after last statement in the script is executed, most often it's unittest.main() . I'll try to make reproducible example

**Comment by noskill** [comment]
[test_bug_server.py.txt](https://github.com/python/cpython/files/10075695/test_bug_server.py.txt)
[test_bug_client.py.txt](https://github.com/python/cpython/files/10075696/test_bug_client.py.txt)

I tried to separate related code into runable example, but now exception is different

```
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<TCPServer.__cb() done, defined at /home/leron/projects/minecr/experiments/vereya/test_bug_server.py:36> exception=RuntimeError('cannot schedule new futures after interpreter shutdown')>
Traceback (most recent call last):
  File "/home/leron/projects/minecr/experiments/vereya/test_bug_server.py", line 46, in __cb
    fut = self.io_service.run_in_executor(None, lambda: self.onMessageReceived('result'))
  File "/home/leron/miniconda3/envs/py31/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/leron/miniconda3/envs/py31/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by gvanrossum** [comment]
Why are you running a separate thread with another event loop? That is asking for trouble, and it doesn't help you (because of the GIL only one thread will run at a time).

**Comment by noskill** [comment]
Well, asyncio.run_until_complete or run_forever blocks main thread, and i can't block the main thread. 
My project is a port of https://github.com/microsoft/malmo. They use c++ with boost::asio  for networking, wrapped as python extension. Their extension runs its own threads and don't block the main thread. I replaced c++ code with python + asyncio, but i have to follow existing api.

Concerning this bug: my first reaction was to do some manual cleanup in __del__ method in the class that holds the event loop and the thread, but it don't getting called at all, is it expected?

**Comment by noskill** [comment]
I can add debug logs in shutdown code in BaseEventLoop to see what is going on.

**Comment by gvanrossum** [comment]
I cannot cause your demo to fail on my laptop (a mac). I would be more comfortable if you created the loop and the servers in the thread that's running the loop -- asyncio loops really like to belong to one thread only. I would also recommend using asyncio.run() to start the program.

I'm not sure what causes the traceback, but my suspicion is this: the callback `onMessage` is run in a threadpool via `loop.run_in_executor`, and while it is running the loop is closed. Then when the callback completes, there is code that tries to wake up the `asyncio.Future` returned by `run_in_executor`. Since it is running in a different thread, it uses a complicated mechanism (`asyncio.futures.wrap_future` and `_chain_future`). At this point I've lost the chain of events, but you can understand that if some random thread tries to do something with a closed loop things will not end well.

Does your code run with Python 3.11 yet? IIRC we've done a few things there to make this more robust (if the loop is closed we just skip doing that step).

**Comment by noskill** [comment]
@gvanrossum i added a lot of debug prints in concurrent/futures/thread.py and asyncio/base_events.py. 
I found that this code shuts down default thread pool executor, while event loop still runs. I'll check if the problem still reproducible in 3.11 https://github.com/python/cpython/blob/59241fe2a223a1202728169984a8793a88e4abb7/Lib/concurrent/futures/thread.py#L103

the condition holds because global _shutdown=True

**Comment by gvanrossum** [comment]
You probably need to close the servers first before closing the loop (and wait for the callbacks to finish).

**Comment by noskill** [comment]
Ok, i'll try to use atexit to cleanup, since "\_\_del\_\_" is not getting called at interpreter shutdown. 

Concerning your previous comment `created the loop and the servers in the thread that's running the loop`. 
I call asyncio.start_server via asyncio.run_coroutine_threadsafe with the loop i started in another thread. I thought run_coroutine_threadsafe will run the passed coroutine in the thread of the loop.

**Comment by noskill** [comment]
It seems _shutdown is getting set by another function registered with atexit and before my function. It's hard to avoid such problems without RAII, so i'll just wrap run_in_executor in try except

**Comment by gvanrossum** [comment]
Okay, good luck. You should really use close() methods though, using try/finally.

**Comment by noskill** [comment]
My program hangs forever on exit, if i press ctrl-c it 

```
Traceback (most recent call last):
  File "/home/leron/miniconda3/envs/py31/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
terminate called without an active exception
Aborted
```
@gvanrossum  could you please reopen the issue?  I believe it's related, because i create only one daemon thread in my program. That lock must be from one of the threads created by thread pool executor.

[core](https://drive.google.com/file/d/1dQi_DmEp4SbQ0NX1bEVcW_jx1oYumEXI/view?usp=sharing)

**Comment by gvanrossum** [comment]
I’m sorry, this tracker is not for help debugging issues in user code.
