### ISSUE TITLE
wave.py - support for ulaw and alaw formats

### ISSUE THREAD

**Issue by thiborose** [python/cpython#99724]
# Feature or enhancement
Add support for reading / writing wave files to the ULAW and ALAW format. wave.py currently does not support this.

Example: 

```python
>>> import wave
>>> wf = wave.open("alaw08m.wav")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\AppData\Local\miniforge3\lib\wave.py", line 509, in open
    return Wave_read(f)
  File "C:\Users\me\AppData\Local\miniforge3\lib\wave.py", line 163, in __init__
    self.initfp(f)
  File "C:\Users\me\AppData\Local\miniforge3\lib\wave.py", line 143, in initfp
    self._read_fmt_chunk(chunk)
  File "C:\Users\me\AppData\Local\miniforge3\lib\wave.py", line 268, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 6
```

# Pitch

Two new global variables should be defined: 
```python
WAVE_FORMAT_ALAW = 0x0006
WAVE_FORMAT_MULAW = 0x0007
```
 
Then, in `_read_fmt_chunk`, the properties `self._comptype` and `self._compname` should be filled appropriately depending on the wFormatTag (which could be either WAVE_FORMAT_PCM, WAVE_FORMAT_ALAW, WAVE_FORMAT_MULAW, WAVE_FORMAT_EXTENSIBLE).

The function `_write_header` should also take care of writing the header appropriately depending on `self._comptype`.

# Previous discussion

No previous discussion found.

### Linked PRs
* gh-99725

**Comment by encukou** [comment]
Sorry, but this type of feature is much better suited for a third-party project on PyPI.

If you disagree, please open a discussion [on Discourse](https://discuss.python.org/c/ideas/6), and some motivation/rationale for adding G.711 formats to Python's standard library. As mentioned in the template you filled out, a GitHub issue isn't a good place for feature requests.

Note that the `wav` module was already [considered for deprecation](https://peps.python.org/pep-0594/#wave) before.
