### ISSUE TITLE
Possible typo in the documentation of datetime

### ISSUE THREAD

**Issue by busywhitespace** [python/cpython#99728]
At the bottom of the page, in the section Technical Detail, the point 9 in the notes says:

> When used with the strptime() method, the leading zero is optional for formats %d, %m, %H, %I, %M, %S, **%J**, %U, %W, and %V.

But **%J** (the uppercase J) does not exist. Maybe **%j** (the lowercase J) was meant.

If it is the case, I'll be glad to create an PR.

### Linked PRs
* gh-99750
* gh-100158
* gh-100159

**Comment by tbwolfe** [comment]
PR has been submitted. Please let me know if any additional changes are required.
