### ISSUE TITLE
Add “maybe you meant” in argparse `choices` argument

### ISSUE THREAD

**Issue by NIKDISSV-Forever** [python/cpython#99749]
# argparse guesses
### Print the possible (nearest) value of the argument. If options are specified with the `choices` argument.
# Pitch
argparse are end user oriented.
Such a message will make the program interface more user-friendly.
```python
def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument('family', type=str.casefold, help='Font family', choices=get_all_family_names(FAMILY_FILES))
    args = arg_parser.parse_args(['S200Flora'])
```

---

### Now outputs this:
_error: argument family: invalid choice: 's200flora' (choose from 'a431', ..., 's200flor', ... 'wingdings 3')_
### I suggest making the output look like this:
_error: argument family: invalid choice: 's200flora', **maybe you meant 's200flor'**? (choose from 'a431', ..., 's200flor', ... 'wingdings 3')_

---

It doesn't have to look exactly like this. I'm not talking about the implementation, perhaps the assumptions should always be (if there are matches) in the presence of the _choices_ argument, perhaps only in some certain conditions.
These questions are decided by those who will implement it, as they see fit.

# Previous discussion

[Add “maybe you meant” in argparse `choices` argument _on discuss.python.org_](https://discuss.python.org/t/add-maybe-you-meant-in-argparse-choices-argument/21335)

### Linked PRs
* gh-99773
* gh-99831
* gh-124456
* gh-125671

**Comment by NIKDISSV-Forever** [comment]
I don't mind working on it, I have an idea of ​​how argparse works, it's just that I'm not a professional in git and have never done pull requests.

**Comment by savannahostrowski** [comment]
Now completed with #124456
