### ISSUE TITLE
Python bug in if and else

### ISSUE THREAD

**Issue by Untilsara** [python/cpython#99757]
Dear programmers, thank you for your intelligence and ingenuity in serving technology, I must say that I saw a bug in Python.  My laptop is the latest Asus model and my programming environment is IDLE.  To answer this question, I designed a code and registered it in Playton, but the answer was wrong.  My question is: ask the user to enter the three sides of a triangle and let Python tell what kind of triangle this triangle is?  First, I used int input to request numbering. 
Using if, elif and else formats, I first checked the condition of having two equal sides, and then in elif, I checked the condition of three sides being equal, and finally, for else, (invalid input).  I noticed that if the user enters the number 5 for all three sides, contrary to expectation, Python says that this triangle has two equal sides!  If he has to say that it has three equal sides!  Because all lines of coding must be checked in the form of if and else!  And in fact, Python checked the first if and did not pay attention to the fact that if we have three sides of size 5, it must be an equilateral triangle, and in fact, Python was satisfied with the first if and did not check the continuation of the code, which was wrong because in  The format of if and else should also pay attention to the condition that three sides are equal..
Thank you for your review.

**Comment by zware** [comment]
Please post usage questions to https://discuss.python.org/c/help/7 instead.

**Comment by terryjreedy** [comment]
Also see this [comment](https://github.com/python/cpython/issues/99759#issuecomment-1326830910l) on a similar question.

Edit: just noticed that you are same person.  Please do not post twice.
