### ISSUE TITLE
DOC: tp_watch was added to PyTypeObject but is not documented

### ISSUE THREAD

**Issue by mattip** [python/cpython#99767]
# Documentation

PR #97875 extended the `PyTypeObject` structure with a new `tp_watch` field. It should be documented in the [tp slots](https://docs.python.org/3.12/c-api/typeobj.html#tp-slots) section, the [PyTypeObject struct](https://docs.python.org/3.12/c-api/typeobj.html#pytypeobject-definition) definition, and the [PyTypeObject slots](https://docs.python.org/3.12/c-api/typeobj.html#pytypeobject-slots) sections of typeobject.rst

### Linked PRs
* gh-99928
* gh-100271

**Comment by mattip** [comment]
xref @carljm as the author of #97875

**Comment by carljm** [comment]
Thanks! I'll work on a PR with these doc updates.

**Comment by mattip** [comment]
Thanks. Documenting it makes it easier for things like cython to know what to do.
