### ISSUE TITLE
New compile warnings in `Py_SETREF`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#99780]
After https://github.com/python/cpython/pull/99737 we got a bunch of new warnings:
<img width="908" alt="Снимок экрана 2022-11-25 в 17 01 51" src="https://user-images.githubusercontent.com/4660275/204001483-afd0df89-4ef1-4130-9690-c5909e206249.png">

Link: https://github.com/python/cpython/pull/99737/files#diff-7c8590641fc0d835bdab9395a95dbacfb2abb056cec4217466c0f3ca6cca8270R337

cc @vstinner

**Comment by vstinner** [comment]
Oops. I created https://github.com/python/cpython/pull/99781 to fix these warnings.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/5556d3e02ca841b82b1eb42cc3974e0a3bbffaac
