### ISSUE TITLE
Possible typo in the documentation of importlib.resources.abc

### ISSUE THREAD

**Issue by busywhitespace** [python/cpython#99795]
The documentation for importlib.resources.abc.TraversableResources at the end of the _importlib.resources.abc_ documentation says:

> ... Therefore, any loader supplying importlib.abc.**TraversableReader** also supplies ResourceReader.

But importlib.abc.**TraversableReader** isn't exposed in the module. In my opinion, the author of the documentation meant **TraversableResources** considering the fact, that the preceding sentence talks about **TraversableResources** subclassing ResourceReader.

> Subclasses importlib.resources.abc.ResourceReader and provides concrete implementations of the importlib.resources.abc.ResourceReader’s abstract methods

I've created the PR in case the issue is correct.

### Linked PRs
* gh-99796
* gh-99799
* gh-99800

**Comment by jaraco** [comment]
My initial instinct was that `TraversableReader` was intended here, but after reading it over several times, I agree with your assessment.
