### ISSUE TITLE
Editable packages show up with weird names in iter_modules

### ISSUE THREAD

**Issue by antazoey** [python/cpython#99805]
# Bug report

File related: https://github.com/python/cpython/blob/main/Lib/pkgutil.py

When iterating over modules (calling `iter_modules()`), editable installs of packages sometimes show up with unexpected prefixes and suffixes, causing issues. I am wondering I am supposed to handle these names myself and try to parse out the real package name or if this is a bug. Here are examples:

```
__editable___ape_fantom_0_4_1_dev1_g048574f_finder",
__editable___ape_infura_0_4_1_dev1_g791b83a_d20220817_finder",
__editable___ape_ledger_0_4_0_finder",
__editable___ape_kong_0_1_dev7_g4acf792_d20221127_finder",
```

The packages are `ape_fantom`, `ape_infura`, `ape_ledger`, and `ape_kong`.

# Your environment

It seems to happen on all the Pythons I try.
But here is my main one:

pip 22.3.1 from /Users/jules/virtualenvs/yoko/lib/python3.9/site-packages/pip (python 3.9)

I am on macOS.

**Comment by unparalleled-js** [comment]
In my `pip freeze,` they look kind of funny too:

traitlets==5.3.0
-e git+ssh://git@github.com/unparalleled-js/trezor-firmware.git@d1a16a0f07e0a6c9858ff68fea03de85781d9d3a#egg=trezor&subdirectory=python
trie==2.0.1

**Comment by unparalleled-js** [comment]
Wow... Just found this bug: https://stackoverflow.com/questions/62885911/pip-freeze-creates-some-weird-path-instead-of-the-package-version

And now I am realizing that whatever `pip` bug this is likely breaks `iter_modules()` as well.. huh.

**Comment by iritkatriel** [comment]
Closing as third party since this is happening in pip.
