### ISSUE TITLE
BUILD: 3.12.0a2 configure script selects wrong libraries compared to 3.11 

### ISSUE THREAD

**Issue by debohman** [python/cpython#99814]
In 3.12.0a2 vs. 3.11.0, the configure script does not reliably select libraries from /usr/local over /usr when available. In fact, in some cases it appears to use headers from /usr/local/include for configuration tests, and then builds against the library in /usr/lib.

e.g.

```console
% CC=clang CXX=clang++ ./configure

.
.
.

% make

.
.
.

./python.exe -E -c 'import sys ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
[ERROR] readline failed to import: dlopen(/tera/tera/debo/Projects/Python/v3.12.0a2/build/lib.macosx-10.12-x86_64-3.12/readline.cpython-312-darwin.so, 2): Symbol not found: _rl_completion_suppress_append
  Referenced from: /tera/tera/debo/Projects/Python/v3.12.0a2/build/lib.macosx-10.12-x86_64-3.12/readline.cpython-312-darwin.so
  Expected in: flat namespace
 in /tera/tera/debo/Projects/Python/v3.12.0a2/build/lib.macosx-10.12-x86_64-3.12/readline.cpython-312-darwin.so
The necessary bits to build these optional modules were not found:
_gdbm                 _tkinter                                 
To find the necessary bits, look in configure.ac and config.log.

Following modules built successfully but were removed because they could not be imported:
readline                                                       

Checked 110 modules (30 built-in, 75 shared, 2 n/a on macosx-10.12-x86_64, 0 disabled, 2 missing, 1 failed on import)
```
In this case, the configure script used the header from /usr/local/include to check for the existence of ```rl_completion_suppress_append```, and then linked against the library in /usr/lib, which failed.

There are other cases where it selects an library in /usr/lib over a more recent one in /usr/local/lib. Note that the same system builds 3.11.0 and selects the correct libraries without any problems, so this is a new issue in the configure script.

# Your environment

Python 3.12.0a2 vs. 3.11.0. Same machine, same toolchain used for both.

macOS 10.12.6 using clang-15.

**Comment by debohman** [comment]
I am still wondering whether this change is intentional, or if it is a bug that should be fixed. It is possible to work around the problem by setting ```CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib``` for the configure command, but that is pretty ugly.

I don't think that it is reasonable that, out of the box, configure uses the readline header from ```/usr/local/include``` and then during the build, the makefile links the readline loadable against the readline library in ```/usr/lib```. That seems to be a bug.

**Comment by FFY00** [comment]
It looks very much like a bug, or an environment misconfiguration, to me.

Can you share the output of `env` (make sure to redact any private information that may be there!)?

**Comment by debohman** [comment]
What exactly about my environment are you interested in? I don't have any special settings that should affect libreadline over say libffi, which works fine.

**Comment by debohman** [comment]
I believe that the change that introduced this problem was e925241d95d8095adf67f492042f97254ff82ec1.

**Comment by debohman** [comment]
And I have retested this using 3.12.0a6. The issue still exists.

**Comment by erlend-aasland** [comment]
If you want to select a specific `readline` library, you can set `LIBREADLINE_CFLAGS` and `LIBREADLINE_LIBS` when calling `configure`. See `./configure --help | grep READLINE`.

Most third-party dependencies are now found using `pkg-config`. There's no hard-coding of preferring one particular include path over another. If you want `pkg-config` to detect custom installs, please see `PKG_CONFIG_PATH`.

**Comment by debohman** [comment]
I am using `pkg-config`:

```
% pkg-config --cflags readline 
-I/usr/local/include
% pkg-config --libs readline
-L/usr/local/lib -lreadline
% which pkg-config
/usr/local/bin/pkg-config
% 
```
If you read from my initial post:

>In this case, the configure script used the header from /usr/local/include to check for the existence of rl_completion_suppress_append, and then linked against the library in /usr/lib, which failed.

The readline library in `/usr/lib` is an older library.

The new configure script does not appear to be using `pkg-config` in a consistent manner.

It works, out of the box, in 3.11.

**Comment by debohman** [comment]
```
% pkg-config --modversion readline
8.2
% 
```

**Comment by erlend-aasland** [comment]
Can you please post the output of the following commands?

```console
$ grep -r readline config.cache
$ grep READLINE config.status
```

**Comment by debohman** [comment]
Interesting, I cannot reproduce the problem with `readline` now, but I did replace `readline` `8.1` with `readline` `8.2` within the last several weeks. I don't like that answer, but it is a fact.

However, the problem does persist with e.g. `libffi`:

```
% pkg-config --cflags libffi   
-I/usr/local/include
% pkg-config --libs libffi      
-L/usr/local/lib -lffi
% pkg-config --modversion libffi
3.4.4
% grep LIBFFI config.status
"MODULE__CTYPES_CFLAGS=-fno-strict-overflow -I/usr/include/ffi -DUSING_APPLE_OS_LIBFFI=1 -DUSING_MALLOC_CLOSURE_DOT_C=1\n"\
S["LIBFFI_LIBS"]="-lffi -ldl"
S["LIBFFI_CFLAGS"]="-I/usr/include/ffi -DUSING_APPLE_OS_LIBFFI=1 -DUSING_MALLOC_CLOSURE_DOT_C=1"
```
There is no `config.cache`.

And, it does link against the wrong library:

```
% otool -L /tmp/dst.python/usr/local/lib/python3.12/lib-dynload/_ctypes.cpython-312-darwin.so:
	/usr/lib/libffi.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

```
% git status
Not currently on any branch.
nothing to commit, working tree clean
% git describe
v3.12.0a7
```

The problem also occurs with `libbz2`. Does not occur with `openssl`, `libz`, etc.

**Comment by debohman** [comment]
I am aware that `libbz2` does not install a `.pc` file, but I rebuilt `v3.11.3` using the configure line at the very top of this report, and it selected everything out of `/usr/local` over `/usr/lib` without exception.

**Comment by erlend-aasland** [comment]
On Darwin, the system supplied libffi is checked before querying pkg-config. BTW, what does `./configure | grep SDKROOT` show?

**Comment by erlend-aasland** [comment]
If you want to override libbz2, you'll need to either override `PKG_CONFIG_PATH` or use the configure flags:

```console
$ ./configure --help | grep BZ
  BZIP2_CFLAGS
              C compiler flags for BZIP2, overriding pkg-config
  BZIP2_LIBS  linker flags for BZIP2, overriding pkg-config
```

**Comment by erlend-aasland** [comment]
It looks like this is a docs issue, rather than a bug in configure. Perhaps the 3.12 What's New could be clearer in communicating the build system changes.

**Comment by debohman** [comment]
```
checking macOS SDKROOT... 
```

**Comment by debohman** [comment]
I would argue that, even on macOS, you should be able to override a library in the SDK by installing a different version in `/usr/local/lib`. Presence in `/usr/local` should always take precedence over the system installation.

**Comment by erlend-aasland** [comment]
> checking macOS SDKROOT...

Sorry, I should've been more specific: `grep -A1 SDKROOT config.log` will do the trick.

**Comment by debohman** [comment]
> On Darwin, the system supplied libffi is checked before querying pkg-config.

But, that is new in `3.12`, right? In `3.11` it chooses the one in `/usr/local`.

**Comment by debohman** [comment]
> grep -A1 SDKROOT config.log

```
configure:4142: checking macOS SDKROOT
configure:4151: result: 
```

**Comment by ronaldoussoren** [comment]
The discussion on this issue petered out. Is there anything left to do?

FWIW I just did a full build of main with libedit, sqlite, ncurses, tcl/tk, bz2, xz and openssl configured through pkg-config. I don't have them installed in /usr/local though.  I only needed to do some extra tweaking for libedit and ncurses, for both the system install was preferred by configure.

**Comment by debohman** [comment]
I think this can be closed. I adjusted my configure environment for 3.12+.
