### ISSUE TITLE
asyncio: Document return values of AbstractEventLoop.remove_{reader,writer}

### ISSUE THREAD

**Issue by bdarnell** [python/cpython#99830]
# Documentation

According to https://github.com/python/typeshed/pull/7042, `AbstractEventLoop.remove_{reader,writer}` return a bool, but there is no indication of this in the [documentation for these methods](https://docs.python.org/3/library/asyncio-eventloop.html#watching-file-descriptors). These return values need to be documented so that subclass implementors can know how to implement them appropriately. 

### Linked PRs
* gh-100302
* gh-100303
* gh-100304

**Comment by kumaraditya303** [comment]
Would you like to create a PR for this?

**Comment by bdarnell** [comment]
Sure: #100302

**Comment by gvanrossum** [comment]
Thanks, Ben!
