### ISSUE TITLE
[Distutils] strtobool

### ISSUE THREAD

**Issue by martigan** [python/cpython#99867]
# Documentation

Specification of distutils.util function strtobool doesn't mention that the values are case insensitive.

![python_38_strtobool](https://user-images.githubusercontent.com/6177711/204490292-e3ea596e-5ca1-4003-baa6-642f1a3d90fd.png)

https://docs.python.org/3.8/distutils/apiref.html#distutils.util.strtobool

I didn't tested on other python version but implementation found [here](https://github.com/pypa/distutils/blob/main/distutils/util.py#L340) hadn't change for a while.

**Comment by hugovk** [comment]
Thank you for the report.

I'll note that distutils is deprecated and has been removed from the upcoming Python 3.12:

* https://peps.python.org/pep-0632/
* https://docs.python.org/3.12/whatsnew/3.12.html#removed
* https://github.com/python/cpython/pull/99061

The PEP's [migration advice](https://peps.python.org/pep-0632/#migration-advice) says there's no planned replacement for `strtobool` and you'll need to implement it yourself, but it's only a dozen lines of code so you could grab directly.

We could update the docs for 3.10 and 3.11 (and separately, possibly update the [docs at setuptools](https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#distutils.util.strtobool)), but given the deprecation/removal status it's probably not worth it.
