### ISSUE TITLE
Where's dataclasses.field(alias=) argument?

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#99860]
# Bug report

[PEP 681](https://peps.python.org/pep-0681/#field-specifier-parameters) says that dataclasses.field will have a keyword argument called "alias".  The PEP also says 

> Python-Version:    3.11

I don't see this in the [3.11 doc for dataclasses](https://docs.python.org/3.11/library/dataclasses.html), nor in the [source code](https://github.com/python/cpython/blob/main/Lib/dataclasses.py).

By the way, same for new "factory" argument.

I'm filing this as a bug report to be sure that the implementation of PEP 681 gets tracked and the work done.

When will we see these changes??

**Comment by JelleZijlstra** [comment]
PEP 681 doesn't specify that this argument is to be added to `dataclasses.field`. Instead, third-party libraries can use these new parameters when they provide an API similar to `dataclasses`.
