### ISSUE TITLE
`functools.reduce` is not necessary in example code of `Is it possible to write obfuscated one-liners in Python?`

### ISSUE THREAD

**Issue by 2chanhaeng** [python/cpython#99870]
# Documentation

`functools.reduce` is used in example code of [Programming FAQ - Is it possible to write obfuscated one-liners in Python?](https://docs.python.org/3/faq/programming.html#is-it-possible-to-write-obfuscated-one-liners-in-python).
But, `functools.reduce` is not encouraged in Python 3 and there are functions and methods to replace.
The example code of primes less than 1000 could be written like this without `functools.reduce`.
```python
# Primes < 1000
print(list(filter(None,map(lambda y:y*all(map(lambda x,
y=y:y%x,range(2,int(pow(y,0.5)+1)))),range(2,1000)))))
# reduce(lambda x,y:x*y!=0, ...) -> all(...)

# It could be more simplified like this.
print([y for y in range(2,1000) if all(y % x for x in range(2,int(pow(y,0.5)+1)))])
```

And the example code of Mandelbrot set could be written like this without `functools.reduce`.
```python
print((lambda Ru,Ro,Iu,Io,IM,Sx,Sy:'\n'.join(map(lambda y,Iu=Iu,
Io=Io,Ru=Ru,Ro=Ro,Sy=Sy,L=lambda yc,Iu=Iu,Io=Io,Ru=Ru,Ro=Ro,i=IM,
Sx=Sx,Sy=Sy:''.join(map(lambda x,xc=Ru,yc=yc,Ru=Ru,Ro=Ro,i=i,Sx=Sx,
F=lambda xc,yc,x,y,k,f=lambda xc,yc,x,y,k,f:(k<=0)or(x*x+y*y>=4.0)
or 1+f(xc,yc,x*x-y*y+xc,2.0*x*y+yc,k-1,f):f(xc,yc,x,y,k,f):chr(64+
F(Ru+x*(Ro-Ru)/Sx,yc,0,0,i)),range(Sx))):L(Iu+y*(Io-Iu)/Sy),range(Sy
))))(-2.1, 0.7, -1.2, 1.2, 30, 80, 24))
# reduce(lambda x,y:x+'\n'+y, ...) -> '\n'.join(...)
# reduce(lambda x,y:x+y, ...) -> ''.join(...)
```

Additionally, the example code first 10 Fibonacci numbers could be more simplified like this.
```python
[x := 1] + [y := 1] + [y := x + (x:=y) for _ in range(8)]
```

**Comment by zware** [comment]
As the question is `Is it possible to write obfuscated one-liners in Python?`, `reduce` seems like a perfect fit here since it is discouraged due to it not being clear at a glance what it does :)

Thanks for the suggestion, but I think we'll leave it as is.
