### ISSUE TITLE
decimal.Decimal when used with statistics.quantiles results in unexpected behaviour

### ISSUE THREAD

**Issue by maxwbuckley** [python/cpython#99881]
Python Version:  3.9.15

When using the quantiles function from the statistics package with Decimal values, the returned quantile values are subtly different from the input Decimal values. This should not be the case.

As [per the statistics package documentation](https://docs.python.org/3/library/statistics.html) the Decimal type should be supported, and superficially it appears to be. However unit testing shows the issue

```python
import statistics
from decimal import Decimal as D


class DecimalQuantileTest(untitest.TestCase):

  def test_decimal_statistics_quantiles(self):
    input_data = [D(1.0), D(1.2), D(3.0), D(3.6), D(2.1)]
    quantiles = statistics.quantiles(input_data, n=4, method="inclusive")
    self.assertListEqual(quantiles, [D(1.2), D(2.1), D(3.0)])
```

The above test fails with:

```diff
    self.assertListEqual(quantiles, [D(1.2), D(2.1), D(3.0)])
AssertionError: Lists differ: [Deci[28 chars]079015'), Decimal('2.1000000000000000888178419[41 chars]00')] != [Deci[28 chars]0790149937383830547332763671875'), Decimal('2.[63 chars]'3')]

First differing element 0:
Decimal('1.199999999999999955591079015')
Decimal('1.1999999999999999555910790149937383830547332763671875')

- [Decimal('1.199999999999999955591079015'),
+ [Decimal('1.1999999999999999555910790149937383830547332763671875'),
?                                       +++++++++++++++++++++++++

-  Decimal('2.100000000000000088817841970'),
+  Decimal('2.100000000000000088817841970012523233890533447265625'),
?                                        ++++++++++++++++++++++++

-  Decimal('3.00000000000000000000000000')]
+  Decimal('3')]
```

**Comment by rhettinger** [comment]
It looks like you've misunderstood how to build exact `Decimal` objects.  If the input is a float, it is rounded to a binary fraction *before* the `Decimal` class even sees it.  To build an exact `Decimal`, the input should be a string:

```
>>> input_data = [D('1.0'), D('1.2'), D('3.0'), D('3.6'), D('2.1')]
>>> quantiles(input_data, n=4, method="inclusive")
[Decimal('1.2'), Decimal('2.1'), Decimal('3.0')]
```

**Comment by maxwbuckley** [comment]
Thanks for the quick and detailed response.

I was aware of how to build exact decimals from strings and the precision issue. The application I was working with gets values out of a database stored as float64 which I then convert to Decimal and use throughout.

What surprised me was that the values at the end of a sequence of taking medians and quantiles were different from any of the input values.

I dug into the Python statistics source code last night some more and I think the thing that threw me was the interpolation on [line 854](https://github.com/python/cpython/blob/main/Lib/statistics.py#L854). This is why we end up with a different decimal which is clearly intended behaviour.

```
The cut points are linearly interpolated from the two nearest data points. For example, if a cut point falls one-third of the distance between two sample values, 100 and 112, the cut-point will evaluate to 104.
```

 -> There it is in the Python docs

Lesson to self: Read the docs better and even the source code of functions you are using, even in the core library :D
