### ISSUE TITLE
Directory traversal in uu module / uu.decode

### ISSUE THREAD

**Issue by hannob** [python/cpython#99889]
# Bug report

The function uu.decode is vulnerable to trivial directory traversal if no output filename is given. An uu-encoded file with a path starting with a repetition of ../../ or a / allows writing a file to an arbitrary location on the filesystem. 

I reported this to security@python.org and was asked to report it publicly as the function is rarely used and removal is planned anyway for Python 3.13.

# Your environment

CPython versions tested on: 3.10.8
Operating system and architecture: Linux

# example files

Case 1:
```
begin 644 ../../../../../../../../tmp/test1
$86)C"@``
`
end
```

Case 2:
```
begin 644 /tmp/test2
$86)C"@``
`
end
```

### Linked PRs
* gh-104096
* gh-104329
* gh-104330
* gh-104331
* gh-104332
* gh-104333

**Comment by alittlesir** [comment]
The permission on the uu.py file is changed from 755 to 644. Is this a misoperation? Why change this permission?

**Comment by arhadthedev** [comment]
@alittlesir Could you file a new issue, please? Here is a chance that core developers do not track solved ones.

**Comment by arhadthedev** [comment]
@alittlesir Could you file a new issue, please? Here is a chance that core developers do not track the solved ones.
