### ISSUE TITLE
classes odds and ends could mention dataclasses

### ISSUE THREAD

**Issue by gpshead** [python/cpython#99908]
# Documentation

https://docs.python.org/3/tutorial/classes.html#odds-and-ends

_"Sometimes it is useful to have a data type similar to the Pascal “record” or C “struct”, bundling together a few named data items. An empty class definition will do nicely:"_

This does not mention dataclasses but the use case it covers makes sense for that. Should the tutorial go there?

### Linked PRs
* gh-100433
* gh-100498
* gh-100499
* gh-100500
* gh-100501

**Comment by ramvikrams** [comment]
> 

i'll do that

**Comment by AlexWaygood** [comment]
Fixed on `main`, and backported to 3.11 and 3.10. Thanks @JosephSBoyle!
