### ISSUE TITLE
Different build systems generate different macros HAVE_BROKEN_NICE

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#99915]
# Bug report

Compile python3.9 on machine A, and Compile python3.9 on another machine B. 

`checking for broken nice()` is  different. 

```
checking for broken nice()... yes
checking for broken nice()... no
```
it is makes that  macros `HAVE_BROKEN_NICE` in the file `pyconfig.h.in` is different

```
/* Define if nice() returns success/failure instead of the new priority. */
/* #undef HAVE_BROKEN_NICE */

/* Define if nice() returns success/failure instead of the new priority. */
#define HAVE_BROKEN_NICE 1
```

it make macros `HAVE_BROKEN_NICE` 1 if  function `main` return 0
```c
#include <stdlib.h>
#include <unistd.h>
int main()
{
	int val1 = nice(1);
	if (val1 != -1 && val1 == nice(2))
		exit(0);
	exit(1);
}
```

Shouldn't the result be the same during compilation and build? all return 0 or all return 1

# Your environment

- CPython versions tested on:python3.9.9
- Operating system and architecture:openeruler22.03, x86

**Comment by iritkatriel** [comment]
CC @Yhg1s .

**Comment by Yhg1s** [comment]
Why do you think the answer should be the same? The configure test is checking whether the `nice()` function appears to behave correctly. The configure script does this the same way it tests many such features: by compiling a program and checking the output. It sounds like it's behaving correctly on machine A and not on machine B. Without digging into what's happening on machine B it's hard to say _why_ it's not behaving correctly, but there's not much more that Python can do here.

If you _know_ machine B's `nice()` is not actually broken you can override the configure test by passing `ac_cv_broken_nice=no` to configure.
