### ISSUE TITLE
Use of first person throughout documentation 

### ISSUE THREAD

**Issue by leobastin** [python/cpython#99916]
# Documentation
Use of first person in an official technical documentation is a very odd practise making less professional. It is usually not a place for opinions or feelings of the writer. Readers may regard such writing as being subjective, whereas science is all about objectivity. This ticket is to change all such instances of use of first person to third person. 

For example, see section 9.2 for the use of "I" (Excerpt below)
 https://docs.python.org/3/tutorial/classes.html
_9.2. Python Scopes and Namespaces_
_Before introducing classes, **I** first have to tell you..._

**Comment by rhettinger** [comment]
Our documentation style allows this.  Having a personal feel is not bad thing. It can make the docs more humanistic and approachable.
