### ISSUE TITLE
Python3 installer is broken on Windows

### ISSUE THREAD

**Issue by juj** [python/cpython#99923]
I was unable to find the appropriate GitHub repository for the Windows installer, so reporting this here to get visibility somewhere at least.

Steps To Reproduce:

1. Visit python.org to download Python 3.11 for Windows:

![image](https://user-images.githubusercontent.com/225351/205048051-af07ce86-312a-4acb-a31d-35985edf1ee9.png)

2. Launch the installer, choose e.g. the following options (shouldn't matter much, except note to add Python to PATH):

![image](https://user-images.githubusercontent.com/225351/205048208-6d86613f-631f-45f0-b256-3e7a03d6f322.png)

![image](https://user-images.githubusercontent.com/225351/205048289-83cf3f3d-97e5-45b1-b8bc-74488a3e9cf0.png)

![image](https://user-images.githubusercontent.com/225351/205048323-e45ce8bc-ebba-4bb0-aaea-6b4978d1e4d1.png)

3. After installation finishes, open a new command prompt, and type `python3`:

![image](https://user-images.githubusercontent.com/225351/205048526-4779154e-3f7a-4f5b-9378-4fb1e090bebb.png)

and press enter.

Observed: The Microsoft Store page pops up, asking the user to install Python 3.10:

![image](https://user-images.githubusercontent.com/225351/205049014-bb4adbce-9449-48b5-bb06-0e7c1285dcc3.png)

Expected: The just installed python 3.11 interpreter should launch.

**Comment by juj** [comment]
As a workaround, looks like one can copy `C:\python311\python.exe` over to `C:\python311\python3.exe`, but that should have been done by the installer?

**Comment by pochmann** [comment]
Why are you typing `python3` instead of `python`? You chose the option "Add python.exe to PATH", not "Add python3.exe to PATH", so why do you expect there to be a python3.exe?

**Comment by juj** [comment]
> Why are you typing python3 instead of python

I am trying to build the [Google v8 JS shell](https://v8.dev/docs/build), which uses `depot_tools`(https://www.chromium.org/developers/how-tos/install-depot-tools/) package, which invokes `python3` as part of its build script.

If that is the wrong thing to do and `python3` should not be executed on Windows (which is odd given [PEP 394](https://peps.python.org/pep-0394/) which suggests that on Unix-likes Python 3 may be present via invoking `python3`, not sure why it would be any different for Windows), I can raise this as a bug report against depot_tools, though it does not seem like this would be Google's fault.

> You chose the option "Add python.exe to PATH", not "Add python3.exe to PATH"

There is no option `"Add python3.exe to PATH"` in the installer. Maybe such an option should then be added, if that is the problem?

> why do you expect there to be a python3.exe?

Among other things because of that PEP 394, which states

"When invoked, python2 should run some version of the Python 2 interpreter, and python3 should run some version of the Python 3 interpreter."

**Comment by pochmann** [comment]
PEP 394's name is *"The “python” Command on Unix-Like Systems"*, and Windows is no Unix-like system. It even has a section [Exclusion of MS Windows](https://peps.python.org/pep-0394/#exclusion-of-ms-windows) which says *"This PEP deliberately excludes any proposals relating to Microsoft Windows"*.

If Python doesn't promise the existence of `python3`, then its non-existence isn't a bug in Python but in the other software that assumes its existence.

The [depot_tools setup tutorial](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) mentions python.exe but not python3.exe, so looks like depot_tools even already knows the correct name...

**Comment by juj** [comment]
I am not following a setup tutorial, but I am running the automated depot_tools build script, which programmatically invokes `python3` on Windows.

> If Python doesn't promise the existence of python3, then its non-existence isn't a bug in Python but in the other software that assumes its existence.

What is the point of devising the whole `python2`, `python3` scheme if one OS is deliberately excluded from it? Why deliberately break cross-platform compatibility? There are no downsides to having `python3.exe` also on Windows Python 3 installations.

**Comment by juj** [comment]
Raised a bug report against depot_tools in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1395090

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by juj** [comment]
I agree with ecmziegler on depot_tools bug tracker, who commented

```
Though I think they make it unnecessarily hard on Windows for cross-platform applications. Just because the spec does not require it does not mean it can't be done.
```
I still think Windows installations of Python 3 should provide python3.exe. The rationales above of why not do not seem particularly convincing.

**Comment by zooba** [comment]
Closing this as a dup of #99185
