### ISSUE TITLE
Inconsistent JSON serialization error messages

### ISSUE THREAD

**Issue by fnesveda** [python/cpython#99925]
# Bug report

When you try to serialize a `NaN`, `inf` or `-inf` with `json.dumps(..., allow_nan=False)`, the error messages are inconsistent, depending on whether you use the `indent` argument or not.

```python
>>> json.dumps(float('nan'), allow_nan=False)
ValueError: Out of range float values are not JSON compliant

>>> json.dumps(float('nan'), allow_nan=False, indent=4)
ValueError: Out of range float values are not JSON compliant: nan
```

That is because if you don't use `indent`, the encoding is done in C code [here](https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Modules/_json.c#L1321-L1327),
but if you use `indent`, the encoding is done in pure Python code [here](https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Lib/json/encoder.py#L239-L242), and the error messages are different between the two.

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: MacOS 12.6, Apple Silicon

### Linked PRs
* gh-99926

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, @fnesveda.
