### ISSUE TITLE
Bug with nested dictionaries

### ISSUE THREAD

**Issue by Alex-Bujorianu** [python/cpython#99932]
# Bug report
```python 
patients = list(range(8))
X = {'1_2020': [1, 2, 3], '6_2020': [1, 2, 3], '7_2021': [1, 2, 3]} 
def train_test_split(X: dict):
    print("Keys of X: ", X.keys())
    X_train = dict.fromkeys(patients[0:6], {})
    X_test = dict.fromkeys(patients[6:], {})
    for key, value in X.items():
        patient = key.split("_")[0]
        if patient in X_train:
            X_train[patient][key[3:]] = value
        elif patient in X_test:
            X_test[patient][key[3:]] = value
            print("Keys of patient: ", X_test[patient].keys())
    return (X_train, X_test)
```
# Your environment
- CPython versions tested on: 3.10
- Operating system and architecture: Linux 6.0-8-1 Manjaro x64

**Comment by JelleZijlstra** [comment]
Can you explain what you think the bug is?

Your code overrides the `dict` builtin with a specific dictionary you define. That's likely to cause problems.

**Comment by Alex-Bujorianu** [comment]
> Can you explain what you think the bug is?
> 
> Your code overrides the `dict` builtin with a specific dictionary you define. That's likely to cause problems.

So the X_test dictionary contains two keys, 95 and 96, whose values are also dictionaries. The inner dictionary of key 96 inherits the keys and values of key 95. Maybe it’s clearer from this output:

```
Patient nr is  95  date is 2021_7_5_16_39
Keys of patient:  dict_keys(['2021_7_7_14_39', '2021_7_7_14_44', '2021_7_7_15_6', '2021_7_8_10_34', '2021_7_8_10_9', '2021_7_5_16_39'])
Patient nr is  95  date is 2021_7_5_17_10
Keys of patient:  dict_keys(['2021_7_7_14_39', '2021_7_7_14_44', '2021_7_7_15_6', '2021_7_8_10_34', '2021_7_8_10_9', '2021_7_5_16_39', '2021_7_5_17_10'])
Patient nr is  96  date is 2021_6_4_13_15
Keys of patient:  dict_keys(['2021_7_7_14_39', '2021_7_7_14_44', '2021_7_7_15_6', '2021_7_8_10_34', '2021_7_8_10_9', '2021_7_5_16_39', '2021_7_5_17_10', '2021_6_4_13_15'])
```

**Comment by Alex-Bujorianu** [comment]
> That's simply because Python objects are passed by reference, so if you do `d = dict.fromkeys([95, 96], {})`, you'll get a dictionary equivalent to `_value = {}; d = {95: _value, 96: _value}`, where both keys map to the same dict. If you want to map each key to a different empty dict, use a dict comprehension: `{k: {} for k in [95, 96]}`.

Thank you, using a dictionary comprehension solved the problem. Is this intended behaviour?

**Comment by JelleZijlstra** [comment]
Yes, it's fundamental to how Python works.

**Comment by pochmann** [comment]
> using a dictionary comprehension solved the problem. Is this intended behaviour?

I guess you didn't read the function's [documentation](https://docs.python.org/3/library/stdtypes.html#dict.fromkeys)? It says:

> All of the values refer to just a single instance, so it generally doesn’t make sense for value to be a mutable object such as an empty list. To get distinct values, use a dict comprehension instead.
