### ISSUE TITLE
libpython3.9.so is crashing in apache server

### ISSUE THREAD

**Issue by rohan-97** [python/cpython#99945]
# Crash report

I am using Apache2 Server which uses libpython3.9.so file internally.
I am getting intermittent crashes whenever request hits the server,

Following logs are found in error.log of apache server
```
Nov 30 22:52:31 debian kernel: apache2[46150]: segfault at e4 ip 00007fa76f62abcd sp 00007fa75bffebe0 error 4 in libpython3.9.so.1.0[7fa76f43a000+286000]
Nov 30 22:52:31 Debian kernel: Code: 00 ff e0 66 2e 0f 1f 84 00 00 00 00 00 e8 3b 75 f9 ff 48 8b 7d 10 eb d5 0f 1f 44 00 00 55 48 89 fd 53 48 83 ec 08 48 8b 5f 10 <48> 83 3b 00 7e 0f 48 3b 1d fe 21 2c 00 74 06 80 7b 20 00 75 0e 48
```

I am using Debian 11.5 Bullseye with kernel 5.10.113 and 
libc.so.6 (libc6,x86-64, OS ABI: Linux 3.2.0) => /lib/x86_64-linux-gnu/libc.so.6

Let me know if you need any other details.

**Comment by ronaldoussoren** [comment]
The description does not contain enough information to reproduce the issue, let alone debug it. That said, this is likely a problem with the 3th-party code that integrates Python into apache2 (possibly mod_python or mod_wsgi).
