### ISSUE TITLE
Chain import SystemError on unexpected exceptions

### ISSUE THREAD

**Issue by seberg** [python/cpython#99947]
# Feature or enhancement

For functions, the `SystemError` chains an in-fly unexpected exceptions, for some import errors this is not the case.

# Pitch

Chaining seems easy, and helps debugging since it is tricky to get back the original exception otherwise, and knowing the exception is often sufficient.

### Linked PRs
* gh-99946

**Comment by brettcannon** [comment]
@seberg  What does "ENH" mean?

**Comment by seberg** [comment]
Hehe, old habits... just the short-form for "enhancement" that we use at NumPy, not that I am sure that "enhancement" is the best tag.
