### ISSUE TITLE
dis output is missing information for KW_NAMES

### ISSUE THREAD

**Issue by chilaxan** [python/cpython#99944]
# Bug report

dis output is missing the constant value for KW_NAMES

This is due to a hardcoded check that the op is LOAD_CONST before grabbing the value.
This check comes after a check that the opcode is in dis.hasconst, so reasonably it can be removed to allow KW_NAMES and future opcodes that feature constants to work moving  forward.

I have drafted a simple pull request #99943 to fix this bug

### Linked PRs
* gh-99943
* gh-103856

**Comment by Lorisredstone** [comment]
It seems that i have the same problem, is this pr still active?

**Comment by arhadthedev** [comment]
@Lorisredstone The PR needs tests and there is nobody with free time to dig into the matter and add them.

**Comment by iritkatriel** [comment]
Thank you @chilaxan and @jkchandalia.
