### ISSUE TITLE
error handling in the compiler is inconsistent

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#99955]
In compile.c some function return 0 for failure and 1 for success, and some return -1 for failure and 0 for success. 

Should be -1 / 0 consistently.

### Linked PRs
* gh-99956
* gh-100010
* gh-100215
* gh-101412

**Comment by ramvikrams** [comment]
can I still work on this or is it done

**Comment by iritkatriel** [comment]
I’m working on it, the remaining part is not as simple as it sounds. Assigning to myself.

**Comment by ramvikrams** [comment]
ok
