### ISSUE TITLE
New warnings: `'function': conversion from 'int64_t' to 'int', possible loss of data`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#99984]
# Bug report

GitHub is showing new warnings in `Modules/_xxsubinterpretersmodule.c`:
<img width="911" alt="Снимок экрана 2022-12-04 в 12 07 02" src="https://user-images.githubusercontent.com/4660275/205482677-87e8c7f3-0ffd-4a4e-ba27-4329e946421c.png">

> 'function': conversion from 'int64_t' to 'int', possible loss of data [D:\a\cpython\cpython\PCbuild\pythoncore.vcxproj]

Looks like https://github.com/python/cpython/pull/99940 is the cause. 
Link: https://github.com/python/cpython/blame/bf26bdf6ac04878fc720e78422991aaedb9808a1/Modules/_xxsubinterpretersmodule.c#L2530
CC @ericsnowcurrently 

### Linked PRs
* gh-100036

**Comment by ramvikrams** [comment]
so should we not convert from `int64_t` to `int`, can it fix the problem

**Comment by ericsnowcurrently** [comment]
This should be fixed.  Thanks for letting us know.
