### ISSUE TITLE
Python 3.9.14: grammar/clarity improvements for str.encode, str.decode error-checking documentation

### ISSUE THREAD

**Issue by jayaddison** [python/cpython#99991]
# Documentation
The are a couple of paragraphs about error-checking behaviour for `str.encode` and `str.decode` that appears in a few versions of Python and could potentially be improved in future versions.

As found in the [Python 3.9.14 documentation for `std.encode`](https://docs.python.org/3.9/library/stdtypes.html#str.encode):

> By default, the _errors_ argument is not checked for best performances, but only used at the first encoding error. Enable the [Python Development Mode](https://docs.python.org/3.9/library/devmode.html#devmode), or use a debug build to check _errors_.

The paragraph before that is fairly dense - there could be an opportunity to improve both of them.

### Linked PRs
* gh-100198
* gh-100382
* gh-100383

**Comment by bizzyvinci** [comment]
do you have recommendations on how to improve them

**Comment by jayaddison** [comment]
It's not easy, but I'll try - here's an attempt for `str.encode`:

> `str.encode(encoding="utf-8", errors="strict")`
>
> Return a [_bytes_](https://docs.python.org/3.9/library/stdtypes.html#bytes) object containing the string in the requested _encoding_.
>
> The default `strict` error handling raises a [UnicodeError](https://docs.python.org/3.9/library/exceptions.html#UnicodeError) exception when an encoding error occurs. Other possible values include `ignore`, `replace`, `xmlcharrefreplace`, `backslashreplace` and any other name registered via [codecs.register_error()](https://docs.python.org/3.9/library/codecs.html#codecs.register_error), see section [Error Handlers](https://docs.python.org/3.9/library/codecs.html#error-handlers).
>
> For a list of possible encodings, see section [Standard Encodings](https://docs.python.org/3.9/library/codecs.html#standard-encodings).
> 
> For performance reasons, the value of the _errors_ argument is not checked for validity unless [Python Development Mode](https://docs.python.org/3.9/library/devmode.html#devmode) is enabled.

**Process used**
Thinking like refactoring, the important items to maintain (like creating unit tests) seemed to be:

* That the documentation describes what the method does (encodes a string, handles errors)
* That relevant entities are hyperlinked/emphasized
* That the documentation is relatively concise (the time required to read and understand the description is similar or reduced)

So looking at the text, there seemed to be a few steps to refactor it:

* Break the dense paragraph into individual statements (usually individual sentences)
* Apply consistent emphasis to entities (types, arguments, ...) that appear in the statements
* Remove redundant/self-explanatory statements
* It's a 2-argument method -- and each argument requires explanation -- so consolidate the statements into one paragraph per argument:
  * Move sentences describing `encoding` into the first paragraph
  * Move sentences describing `errors` into the second paragraph
  * Exception: some of the commentary appears to be about non-functional behaviour (performance) -- OK, that could move into a third paragraph
* Re-read and refactor to remove unnecessary words and statements
* Nitpick: error handling is important to understand, so let's move the list of codecs -- useful though it is -- to after the _errors_ argument, in the hope that people will read about error-handling first

Note:
* https://docs.python.org/3.9/library/codecs.html#codecs.EncodedFile also has documentation for a similarly-behaved `errors` argument

**Comment by bizzyvinci** [comment]
Thanks. I'll work on that.

**Comment by jayaddison** [comment]
> For performance reasons, the value of the errors argument is not checked for validity unless [Python Development Mode](https://docs.python.org/3.9/library/devmode.html#devmode) is enabled.

Ah: I forgot to mention debug builds in this suggestion.  Similar to development-mode, debug builds also validate the _errors_ argument.

A simple check to test whether error-handler-name-validation is enabled is to attempt encoding using an invalid error-handler-name.  For example, `"".encode('utf-8', errors='gh-99991')`.

**Comment by CAM-Gerlach** [comment]
By the way, thanks for your comprehensive and insightful feedback, @jayaddison ! We'd love to have more of it elsewhere, and you're welcome to contribute the changes yourself if you like—you seem to have quite a knack for documentation writing, which makes a big positive impact on the community. Thanks again!

**Comment by jayaddison** [comment]
Thanks for the kind words @CAM-Gerlach!  There are more than a few similarities between good code and good documentation, I think :smile:  I'll do my best to help out where and when I can.

**Comment by hauntsaninja** [comment]
Thanks, looks like everything is merged!
