### ISSUE TITLE
The Numeric Types description table missing a note

### ISSUE THREAD

**Issue by chen-qingyu** [python/cpython#99992]
# Documentation

The Notes column in the Operation description table missed `(2)` from the line `x // y` in https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex .

The line: `x // y | floored quotient of x and y | (1)` should be `x // y | floored quotient of x and y | (1) (2)`

> Notes: 2. Not for complex numbers. Instead convert to floats using abs() if appropriate.

Because the complex also does not support `//` operation.

**Comment by chen-qingyu** [comment]
Emmmmm, sorry, I didn't get a good look

**Comment by pochmann** [comment]
I find the note odd. The paragraph above the table already said *"All numeric types **(except complex)** support the following operations"*, so the note's *"Not for complex numbers"* isn't even needed. Looks like the point of the note is just its suggestion to *"Instead convert to floats using abs() if appropriate"*. I googled a bit for definitions of the modulo operator for complex numbers and I didn't see this one with abs(). So I wonder where/whether that's appropriate...
